Fix fee calculation in native blockifier validation
starkware-libs/blockifier pull request #1007
Opened 2023-10-19 10:16 UTC by giladchase

- Make ActualCostBuilder consider nonce increments when calculating the fee for the validate action.
- This is already taken into account in execution via `handle_nonce`, which is not appropriate in a validation context. However, since modified_contracts is a set, this change doesn't affect it.
- Hoist `into_actual_cost_builder` up to the public methods section.

Python: https://reviewable.io/reviews/starkware-industries/starkware/31652

2023-10-22 09:57 UTC, elintul requested changes
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1007)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 465 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1007#-NhLoGsl8HlsFD6NtsQM:-NhLoGsl8HlsFD6NtsQN:b-pcasr5) ([raw file](https://github.com/starkware-libs/blockifier/blob/750ba5b5120e726a92ce0157b96093fd44bf370a/crates/blockifier/src/transaction/transactions.rs#L465)):*
> ```XML
> }
> 
> pub trait NonceBehavior {
> ```

Why is this trait needed?



_Code quote:_
```XML
pub trait NonceBehavior 
```


<!-- Sent from Reviewable.io -->

2023-10-22 10:08 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1007)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @giladchase, @noaov1, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1007#-NhLqskh9Z7zYKQgTzdA:-NhLqskh9Z7zYKQgTzdB:b4wd1lc) (no related file):*
Where is [this](https://github.com/starkware-industries/starkware/blob/43cfdd7b825058b29a3b8d7e87acf8235d14bf26/src/starkware/starknet/services/gateway/gateway.py#L684-L686) handled in your flow?

___


<!-- Sent from Reviewable.io -->

2023-10-22 10:42 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1007)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @elintul, @noaov1, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1007#-NhLqskh9Z7zYKQgTzdA:-NhLv-Im2SOPyh8OCagx:btikix9) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Where is [this](https://github.com/starkware-industries/starkware/blob/43cfdd7b825058b29a3b8d7e87acf8235d14bf26/src/starkware/starknet/services/gateway/gateway.py#L684-L686) handled in your flow?
</blockquote></details>

In the python PR, [here](https://github.com/starkware-industries/starkware/pull/31652/files#diff-d524f2dab95deaf418ec2dc1727fdab056c1bc5f36cbbcd209ee99780196eba8R699)

___
___
*[`crates/blockifier/src/transaction/transactions.rs` line 465 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1007#-NhLoGsl8HlsFD6NtsQM:-NhLw8Fe8dpgwVV5bPHN:b-qhy69m) ([raw file](https://github.com/starkware-libs/blockifier/blob/750ba5b5120e726a92ce0157b96093fd44bf370a/crates/blockifier/src/transaction/transactions.rs#L465)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is this trait needed?
</blockquote></details>

Added the trait to formalize a shared behavior among transaction types, making the code self-documenting. It avoids the need for extensive docstrings to explain why all these structs happen to have the same method in their impl block.

However, its single use case may make it seem overkill. Should I remove it?


<!-- Sent from Reviewable.io -->

2023-10-22 10:54 UTC, elintul requested changes
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1007)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 465 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1007#-NhLoGsl8HlsFD6NtsQM:-NhM0FA3Braj7uu1wDBZ:b-12s8x4) ([raw file](https://github.com/starkware-libs/blockifier/blob/750ba5b5120e726a92ce0157b96093fd44bf370a/crates/blockifier/src/transaction/transactions.rs#L465)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Added the trait to formalize a shared behavior among transaction types, making the code self-documenting. It avoids the need for extensive docstrings to explain why all these structs happen to have the same method in their impl block.

However, its single use case may make it seem overkill. Should I remove it?
</blockquote></details>

Got it, thanks. Add a TODO (or a nonblocking Monday item) to consider removing if we end up not supporting V0?


<!-- Sent from Reviewable.io -->

2023-10-22 11:32 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1007)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 465 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1007#-NhLoGsl8HlsFD6NtsQM:-NhM8yjm7sx0m391Yl94:b6vpmtd) ([raw file](https://github.com/starkware-libs/blockifier/blob/750ba5b5120e726a92ce0157b96093fd44bf370a/crates/blockifier/src/transaction/transactions.rs#L465)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Got it, thanks. Add a TODO (or a nonblocking Monday item) to consider removing if we end up not supporting V0?
</blockquote></details>

[Done ](https://starkware.monday.com/boards/2735879357/pulses/5370212161)


<!-- Sent from Reviewable.io -->

2023-10-22 11:44 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1007)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 465 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1007#-NhLoGsl8HlsFD6NtsQM:-NhMB2u92MeMD2t5c371:b-xja9m0) ([raw file](https://github.com/starkware-libs/blockifier/blob/750ba5b5120e726a92ce0157b96093fd44bf370a/crates/blockifier/src/transaction/transactions.rs#L465)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

[Done ](https://starkware.monday.com/boards/2735879357/pulses/5370212161)
</blockquote></details>

I think we should neglect V0 and make it simple (always charge).
We usually מחמירים with fees (e.g., same price for deploy account, with or without c-tor invocation)

BTW, what about L1 handler fee calculation?
That's the only place you may need this


<!-- Sent from Reviewable.io -->

2023-10-22 16:18 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1007)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 465 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1007#-NhLoGsl8HlsFD6NtsQM:-NhN9WZE2qu0ZAmy_VMw:bfolw05) ([raw file](https://github.com/starkware-libs/blockifier/blob/750ba5b5120e726a92ce0157b96093fd44bf370a/crates/blockifier/src/transaction/transactions.rs#L465)):*
Done, now simply incrementing the nonce --- since the state in native_blockifier is reset between calls to validate, this will work, and better mimic the execution flow, which indeed increments the nonce.

>BTW, what about L1 handler fee calculation?

Different flow, currently can't get to this flow since it isn't called from the gateway.
However, there is a pending refactor to its flow to use `ActualCost`, which will make things clearer.


<!-- Sent from Reviewable.io -->

2023-10-22 17:16 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1007)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 465 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1007#-NhLoGsl8HlsFD6NtsQM:-NhNNTMS9SVxh1mqy7J-:b-q9jo2q) ([raw file](https://github.com/starkware-libs/blockifier/blob/750ba5b5120e726a92ce0157b96093fd44bf370a/crates/blockifier/src/transaction/transactions.rs#L465)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Done, now simply incrementing the nonce --- since the state in native_blockifier is reset between calls to validate, this will work, and better mimic the execution flow, which indeed increments the nonce.

>BTW, what about L1 handler fee calculation?

Different flow, currently can't get to this flow since it isn't called from the gateway.
However, there is a pending refactor to its flow to use `ActualCost`, which will make things clearer.
</blockquote></details>

This won't work (you're using a function the compares the tx nonce with the latest), the exact reason why we don't check the nonce in the gateway - the sync with the latest state is not tight.


<!-- Sent from Reviewable.io -->

2023-10-23 09:57 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1007)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @elintul, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 465 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1007#-NhLoGsl8HlsFD6NtsQM:-NhQx-zC1QaThrAIco17:bioglte) ([raw file](https://github.com/starkware-libs/blockifier/blob/750ba5b5120e726a92ce0157b96093fd44bf370a/crates/blockifier/src/transaction/transactions.rs#L465)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

This won't work (you're using a function the compares the tx nonce with the latest), the exact reason why we don't check the nonce in the gateway - the sync with the latest state is not tight.
</blockquote></details>

Right :facepalm: 
Now it's ok right? 
This assumes that the correct nonce check (only checks <=) stays in the gateway though.


<!-- Sent from Reviewable.io -->

2023-10-23 11:13 UTC, elintul approved these changes
> Reviewed 2 of 5 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1007)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2023-10-23 12:11 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1007#-:-NhRRaVv8UJ9aKPfm9zI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-10-23 13:16 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1007#-:-NhRfXX_5fcpXgftLhGZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-10-24 09:51 UTC, merged