Amos/add pre execution validations
starkware-libs/blockifier pull request #1013
Opened 2023-10-22 13:45 UTC by amosStarkware

2023-10-24 12:14 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1013)* status: 0 of 11 files reviewed, 4 unresolved discussions

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWYvG0BHGCBoOXiI02:-NhWYvG0BHGCBoOXiI03:b-64hrmy) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/fee/fee_utils.rs#L91)):*
> ```XML
> /// Error may indicate insufficient balance, or some other error.
> pub fn verify_can_pay_max_fee(
>     state: &mut dyn State,
> ```

Otherwise I get an error when trying to call this function from `check_fee_balance`. I don't know the implications



_Code quote:_
```XML
state: &mut dyn State,
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWZSEx9yKQpYZ3jk82:-NhWZSEyD5Ei2vsu8kxv:b-6b2fzc) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L175)):*
> ```XML
>                             max_l1_gas_price: Fee(max_l1_gas_price),
>                             current_gas_price: Fee(block_context.gas_prices.strk_l1_gas_price),
>                         },
> ```

Very ugly - is this what you meant when you said the `from` function won't be well defined?



_Code quote:_
```XML
                    Err(TransactionPreValidationError::TransactionFeeError(
                        TransactionFeeError::MaxL1GasPriceTooLow {
                            max_l1_gas_price: Fee(max_l1_gas_price),
                            current_gas_price: Fee(block_context.gas_prices.strk_l1_gas_price),
                        },
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 245 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWZpNUBVTJN48BBAkZ:-NhWZpNUBVTJN48BBAk_:bu1yipm) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L245)):*
> ```XML
>     fn check_fee_balance(
>         &self,
>         state: &mut dyn State,
> ```

I did this because otherwise I get an error when this function is called (indirectly) by `PyValidator::Validate()`. not sure if this is valid



_Code quote:_
```XML
state: &mut dyn State,
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 549 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWa4330rBL_D5-_Wld:-NhWa4330rBL_D5-_Wle:brf6yg8) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/transactions_test.rs#L549)):*
> ```XML
>     assert_matches!(
>         execution_error,
>         TransactionExecutionError::TransactionPreValidationError(TransactionPreValidationError::TransactionFeeError(TransactionFeeError::MaxFeeTooLow { min_fee, max_fee }))
> ```

again, very ugly - is there a better way to do this?



_Code quote:_
```XML
TransactionExecutionError::TransactionPreValidationError(TransactionPreValidationError::TransactionFeeError(TransactionFeeError::MaxFeeTooLow { min_fee, max_fee }))
```


<!-- Sent from Reviewable.io -->

2023-10-24 12:51 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 10 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1013)* status: all files reviewed, 19 unresolved discussions (waiting on @amosStarkware and @giladchase)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWYvG0BHGCBoOXiI02:-NhWbsU13w5-jUpfO0iw:bf7t69p) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/fee/fee_utils.rs#L91)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Otherwise I get an error when trying to call this function from `check_fee_balance`. I don't know the implications
</blockquote></details>

maybe add @giladchase to review?
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 188 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWbzoI5tQVd7--V-2x:-NhWbzoI5tQVd7--V-2y:b-lzl8ai) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/fee/gas_usage.rs#L188)):*
> ```XML
>         Err(err) => Err(err.into()),
>         Ok(other) => Ok(other),
>     }
> ```

try doing this instead of the match; should coerce the error to the correct type



_Suggestion:_
```XML
    Ok(calculate_tx_fee(&resources, block_context, &tx.fee_type())?)
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 156 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWeLqZ5cfX42GQ1Q90:-NhWeLqZ5cfX42GQ1Q91:bmc0wbw) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L156)):*
> ```XML
>         Self::check_nonce(account_tx_context, state, strict)?;
>         if charge_fee {
>             Self::check_max_l1_gas_price(account_tx_context, block_context)?;
> ```

I don't think this check should only be for the charge fee case.
I think that tx simulation should fail if the resource bounds are insufficient; no?
Or do we really want to allow simulation with zero resource bounds...?
question for @elintul or @Yoni-Starkware 



_Code quote:_
```XML
Self::check_max_l1_gas_price(account_tx_context, block_context)?;
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWZSEx9yKQpYZ3jk82:-NhWejv41TiC7VFJ-IK0:b-i38rcl) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L175)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Very ugly - is this what you meant when you said the `from` function won't be well defined?
</blockquote></details>

I think you don't need to explicitly wrap `TransactionFeeError` in a `TransactionPreValidationError` here.
Just return `Err(TransactionFeeError::...)`.
Since the return type in this function is `TransactionPreValidationResult`, it should coerce to the prevalidation type...
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 223 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWdCsY6l_vlIVzJZjV:-NhWdCsY6l_vlIVzJZjW:b-l6sjth) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L223)):*
> ```XML
>             Err(err) => Err(err.into()),
>             Ok(res) => Ok(res),
>         }
> ```

reduce



_Suggestion:_
```XML
        Ok(state.increment_nonce(account_tx_context.sender_address())?)
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 245 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWZpNUBVTJN48BBAkZ:-NhWdQ9Y-55NaO2q-pek:brf6ifv) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L245)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I did this because otherwise I get an error when this function is called (indirectly) by `PyValidator::Validate()`. not sure if this is valid
</blockquote></details>

@giladchase ?
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 260 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWdVj97xBvjMHl7JCY:-NhWdVj97xBvjMHl7JCZ:b-zacqne) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L260)):*
> ```XML
>             return Err(TransactionPreValidationError::TransactionFeeError(
>                 TransactionFeeError::MaxFeeTooLow { min_fee: minimal_fee, max_fee },
>             ));
> ```

this doesn't work? I think `#[from]` should handle this



_Suggestion:_
```XML
            return Err(TransactionFeeError::MaxFeeTooLow { min_fee: minimal_fee, max_fee });
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 266 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWdelJ4MFKbf_U97lN:-NhWdelJ4MFKbf_U97lO:b-l6sjth) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L266)):*
> ```XML
>             Err(err) => Err(err.into()),
>             Ok(res) => Ok(res),
>         }
> ```

reduce



_Suggestion:_
```XML
        Ok(verify_can_pay_max_fee(state, &account_tx_context, block_context, max_fee)?)
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 299 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWdrRUAoXL9qHILDYS:-NhWdrRUAoXL9qHILDYT:bdzxsdu) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L299)):*
> ```XML
>             return Err(TransactionExecutionError::TransactionFeeError(
>                 TransactionFeeError::FeeTransferError { max_fee, actual_fee },
>             ));
> ```

this should work...?



_Suggestion:_
```XML
            return Err(TransactionFeeError::FeeTransferError { max_fee, actual_fee });
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 613 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWe0CO9Ctr56mYPjKG:-NhWe0CO9Ctr56mYPjKH:b-nchjk7) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L613)):*
> ```XML
>         ) {
>             return Err(err.into());
>         }
> ```

should work.
this function also outputs a pre-validation error, never a fee error directly, so conversion will work as intended



_Suggestion:_
```XML
        self.perform_pre_validation_checks(
            &account_tx_context,
            state,
            block_context,
            charge_fee,
            true,
        )?;
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWggDu-3je59677P-j:-NhWggDu-3je59677P-k:b-n91cnx) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/objects.rs#L74)):*
> ```XML
>     }
> 
>     pub fn max_l1_gas_price(&self) -> Option<Fee> {
> ```

please add a docstring for this (explaining what some and none values mean)
___
*[`crates/blockifier/src/transaction/objects.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWgprWACkq5Jt_tiuy:-NhWgprWACkq5Jt_tiuz:b-x7c7yv) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/objects.rs#L113)):*
> ```X [...]

2023-10-24 13:40 UTC, amosStarkware reviewed
+reviewer:@dorimedini-starkware +reviewer:@giladchase 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-:-NhWuUFc4IHVh3oxbMZ2:bxr3mj9)* status: all files reviewed, 19 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)



<!-- Sent from Reviewable.io -->

2023-10-24 14:58 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1013)* status: all files reviewed, 19 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWYvG0BHGCBoOXiI02:-NhWuXzQ85J3YkHN1pgN:b-ccl0wz) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/fee/fee_utils.rs#L91)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe add @giladchase to review?
</blockquote></details>

Added him now
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 188 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWbzoI5tQVd7--V-2x:-NhWvckb6IHfd7Tw3m_9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/fee/gas_usage.rs#L188)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

try doing this instead of the match; should coerce the error to the correct type
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 156 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWeLqZ5cfX42GQ1Q90:-NhWvia13-Ag3y1j8sPP:boxqmsw) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L156)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't think this check should only be for the charge fee case.
I think that tx simulation should fail if the resource bounds are insufficient; no?
Or do we really want to allow simulation with zero resource bounds...?
question for @elintul or @Yoni-Starkware
</blockquote></details>

`execute_raw` only called `check_fee_balance` if `charge_fee` is True:
https://github.com/starkware-libs/blockifier/blob/9db89309ae0d0a3136c6b7bd29ec4ee72c969774/crates/blockifier/src/transaction/account_transaction.rs#L566
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWZSEx9yKQpYZ3jk82:-NhWyVQt24syiDkRi-Bx:b9q44e6) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L175)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think you don't need to explicitly wrap `TransactionFeeError` in a `TransactionPreValidationError` here.
Just return `Err(TransactionFeeError::...)`.
Since the return type in this function is `TransactionPreValidationResult`, it should coerce to the prevalidation type...
</blockquote></details>

I tried that, but it doesn't work. @giladchase is there a better solution?
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 223 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWdCsY6l_vlIVzJZjV:-NhWyvu96EeTRExFdQSP:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L223)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

reduce
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 260 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWdVj97xBvjMHl7JCY:-NhWzAo4B5swey-f8e-v:b-xmbm2x) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L260)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this doesn't work? I think `#[from]` should handle this
</blockquote></details>

doesn't work. @giladchase is there a better way than this?
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 266 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWdelJ4MFKbf_U97lN:-NhX0ghq3q6M2k9c2RH-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L266)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

reduce
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 299 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWdrRUAoXL9qHILDYS:-NhX0mCh8CMTXoMOT4Fw:b-7ropln) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L299)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this should work...?
</blockquote></details>

ditto
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 613 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWe0CO9Ctr56mYPjKG:-NhX1KCJCMdnMzPWn_Si:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L613)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

should work.
this function also outputs a pre-validation error, never a fee error directly, so conversion will work as intended
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWggDu-3je59677P-j:-NhX1lRYEk-_eRjr7u1f:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/objects.rs#L74)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a docstring for this (explaining what some and none values mean)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWgprWACkq5Jt_tiuy:-NhX3x4oEXwcxm4U22ki:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/objects.rs#L113)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

currently, not equivalent to what was previously returned
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 202 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWgw20Da37R4t4f8Bw:-NhX3z5K-fdX96pR8Q1l:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/objects.rs#L202)):*
> ```XML
>             Err(err) => Err(err.into()),
>             Ok(other) => Ok(other),
>         }
> ```

Done.
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWh4M79s96O0RQl8XI:-NhX4Z9D1kyNaEKyhlix:b-bnbk4i) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/transaction_execution.rs#L122)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

should work
</blockquote></details>

doesn't work, hopefully we'll find a solution
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 549 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWa4330rBL_D5-_Wld:-NhX4tHH7maE1JRXLIC2:bujy5tg) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d [...]

2023-10-24 15:38 UTC, amosStarkware reviewed
python side:
https://reviewable.io/reviews/starkware-industries/starkware/32300

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-:-NhXKaiV13DVE9EVMtuS:bvikiz9)* status: 7 of 12 files reviewed, 19 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @giladchase, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2023-10-24 17:05 UTC, dorimedini-starkware requested changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1013)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @elintul, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 156 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWeLqZ5cfX42GQ1Q90:-NhXXKg-0zTOl-r9Pp5X:bhkl5hm) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L156)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

`execute_raw` only called `check_fee_balance` if `charge_fee` is True:
https://github.com/starkware-libs/blockifier/blob/9db89309ae0d0a3136c6b7bd29ec4ee72c969774/crates/blockifier/src/transaction/account_transaction.rs#L566
</blockquote></details>

yes, but the gas price check is new.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWZSEx9yKQpYZ3jk82:-NhXXO7k6J6hqSTzAH--:b6ontfg) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L175)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I tried that, but it doesn't work. @giladchase is there a better solution?
</blockquote></details>

maybe you can add a question mark `Err(...)?` to coerce...?
try it, unblocking anyway...
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 260 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWdVj97xBvjMHl7JCY:-NhXdAUT5DKzUlHwbK_E:b-1rkzjy) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L260)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

doesn't work. @giladchase is there a better way than this?
</blockquote></details>

unblocking unless `?` works
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 299 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWdrRUAoXL9qHILDYS:-NhXdDV62GzkGWb7TGcy:b-7ropln) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L299)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWh4M79s96O0RQl8XI:-NhXdFleDdYOu7Rdj_hF:b-7ropln) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/transaction_execution.rs#L122)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

doesn't work, hopefully we'll find a solution
</blockquote></details>

ditto
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 549 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWa4330rBL_D5-_Wld:-NhXXkciE_tWuTzCeBya:bt0ww9x) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/transactions_test.rs#L549)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

doesn't work
</blockquote></details>

maybe the question mark method then...? unblocking for now


<!-- Sent from Reviewable.io -->

2023-10-25 08:06 UTC, amosStarkware reviewed
+reviewer:@elintul 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-:-Nh_r_U4BJ-n9BrVAISZ:bktvhsi)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul, @giladchase, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2023-10-25 08:28 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1013)* status: 10 of 12 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 175 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWZSEx9yKQpYZ3jk82:-Nh_s1Cs-LhelLfJeXGj:b-a9q7lg) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L175)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe you can add a question mark `Err(...)?` to coerce...?
try it, unblocking anyway...
</blockquote></details>

worked!
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 260 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWdVj97xBvjMHl7JCY:-Nh_sseF6IGLxHJhTD5A:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L260)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

unblocking unless `?` works
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 299 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWdrRUAoXL9qHILDYS:-Nh_tBdU2oNJ9gbCrlOS:b-7ropln) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L299)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 122 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWh4M79s96O0RQl8XI:-Nh_taJ64KYQ9G9T3ZSa:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/transaction_execution.rs#L122)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 549 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWa4330rBL_D5-_Wld:-Nh_tgoo6JZIrxoCq69m:b-rfno9b) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/transactions_test.rs#L549)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe the question mark method then...? unblocking for now
</blockquote></details>

Here we want to write it explicitly, no?


<!-- Sent from Reviewable.io -->

2023-10-25 08:38 UTC, dorimedini-starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-:-Nh_ymqWBloSpXvglzSq:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 549 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWa4330rBL_D5-_Wld:-Nh_yeye4bSQDBoSCEmU:b-sh5wyg) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/transactions_test.rs#L549)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Here we want to write it explicitly, no?
</blockquote></details>

ah right


<!-- Sent from Reviewable.io -->

2023-10-25 09:51 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1013)* status: all files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 182 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhaEZb-5Gq-FthTBGyk:-NhaEj2q5PlUyN__d8wR:b-jmykjh) ([raw file](https://github.com/starkware-libs/blockifier/blob/76f8d8a5b71c90b6b0836a95cda3d00e7321ba7b/crates/blockifier/src/transaction/account_transaction.rs#L182)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Separate the nonce change (adding the flag) to another PR.
</blockquote></details>

(Flag addition + function separation)


<!-- Sent from Reviewable.io -->

2023-10-25 09:53 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1013)* status: all files reviewed, 10 unresolved discussions (waiting on @amosStarkware, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 185 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhaEv-oBfUSrq1Ae7jG:-NhaEv-oBfUSrq1Ae7jH:b-vijcl4) ([raw file](https://github.com/starkware-libs/blockifier/blob/76f8d8a5b71c90b6b0836a95cda3d00e7321ba7b/crates/blockifier/src/transaction/account_transaction.rs#L185)):*
> ```XML
>     fn check_nonce(
>         account_tx_context: &AccountTransactionContext,
>         state: &mut dyn State,
> ```

Swap order.



_Code quote:_
```XML
        account_tx_context: &AccountTransactionContext,
        state: &mut dyn State,
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 210 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhaErY0D21dumTR-OJP:-NhaErY0D21dumTR-OJQ:b-vijcl4) ([raw file](https://github.com/starkware-libs/blockifier/blob/76f8d8a5b71c90b6b0836a95cda3d00e7321ba7b/crates/blockifier/src/transaction/account_transaction.rs#L210)):*
> ```XML
>     pub fn increment_nonce(
>         account_tx_context: &AccountTransactionContext,
>         state: &mut dyn State,
> ```

Swap order.



_Code quote:_
```XML
        account_tx_context: &AccountTransactionContext,
        state: &mut dyn State,
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 10 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhaF69p1nhQfz44aBf3:-NhaF69p1nhQfz44aBf4:b-5itw9e) ([raw file](https://github.com/starkware-libs/blockifier/blob/76f8d8a5b71c90b6b0836a95cda3d00e7321ba7b/crates/blockifier/src/transaction/errors.rs#L10)):*
> ```XML
> use crate::execution::errors::EntryPointExecutionError;
> use crate::state::errors::StateError;
> ```

I appreciate the ordering, but just to have context: what caused you to do that?


<!-- Sent from Reviewable.io -->

2023-10-25 10:56 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1013)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 182 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhaEZb-5Gq-FthTBGyk:-NhaSVO6CXCUqEuqYius:b971owk) ([raw file](https://github.com/starkware-libs/blockifier/blob/76f8d8a5b71c90b6b0836a95cda3d00e7321ba7b/crates/blockifier/src/transaction/account_transaction.rs#L182)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

(Flag addition + function separation)
</blockquote></details>

I'll split the PR
___
*[`crates/blockifier/src/transaction/errors.rs` line 10 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhaF69p1nhQfz44aBf3:-NhaT6vn7S66LN-qMK3T:b-bihvay) ([raw file](https://github.com/starkware-libs/blockifier/blob/76f8d8a5b71c90b6b0836a95cda3d00e7321ba7b/crates/blockifier/src/transaction/errors.rs#L10)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I appreciate the ordering, but just to have context: what caused you to do that?
</blockquote></details>

I'm not sure what you mean by ordering?
do you mean the new Error types and their heirarchy?


<!-- Sent from Reviewable.io -->

2023-10-25 11:30 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1013)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @elintul, @giladchase, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2023-10-29 13:15 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1013)* status: all files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @elintul, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 245 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhWZpNUBVTJN48BBAkZ:-NhvZVJW7YIrTePiTOhD:bezocdo) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2ba28ced982362d35db56b707328a6d0a87c010/crates/blockifier/src/transaction/account_transaction.rs#L245)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@giladchase ?
</blockquote></details>

Can you tell me how you reproduced this? compilation-wise there is no problem, so i'm assuming you're referring to unpublished test?
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 181 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-NhvXIQWDuxHIg1SRqZO:-NhvXIQWDuxHIg1SRqZP:bu793u3) ([raw file](https://github.com/starkware-libs/blockifier/blob/4d448461e166edf29e78300ad2e163687f321424/crates/blockifier/src/transaction/account_transaction.rs#L181)):*
> ```XML
>             }
>             None => Ok(()),
>         }
> ```

Consider, for reduced nesting level.



_Suggestion:_
```XML
        if let Some(Fee(max_l1_gas_price)) = account_tx_context.max_l1_gas_price() {
            let current_gas_price = block_context.gas_prices.strk_l1_gas_price;
            if current_gas_price > max_l1_gas_price {
                return Err(TransactionFeeError::MaxL1GasPriceTooLow {
                    max_l1_gas_price: Fee(max_l1_gas_price),
                    current_gas_price: Fee(current_gas_price),
                })?;
            }
        }
        Ok(())
```


<!-- Sent from Reviewable.io -->

2023-10-30 09:10 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1013)* status: all files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @elintul, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/objects.rs` line 114 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1013#-Nhv_LH_48GtiN4BKdAz:-Nhv_LHaBQ-Y02qJRK0y:b3e40no) ([raw file](https://github.com/starkware-libs/blockifier/blob/4d448461e166edf29e78300ad2e163687f321424/crates/blockifier/src/transaction/objects.rs#L114)):*
> ```XML
> impl CurrentAccountTransactionContext {
>     fn get_l1_gas_bounds(&self) -> ResourceBounds {
>         self.resource_bounds.0.get(&Resource::L1Gas).copied().unwrap_or_default()
> ```

Non-blocking, we can add `derive_more::Deref` to this type in SN API in order to not have to `.0` all the time (it's a prime example for when this is applicable).



_Code quote:_
```XML
self.resource_bounds.0
```


<!-- Sent from Reviewable.io -->

2023-11-06 09:39 UTC, closed without merging