Move pre-validation checks into method.
starkware-libs/blockifier pull request #1041
Opened 2023-10-26 12:47 UTC by amosStarkware

2023-10-26 13:47 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NhgDxSu1i8h_0Y-Nf-H:-NhgDxSu1i8h_0Y-Nf-I:bt5hh27) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/fee/fee_utils.rs#L78)):*
> ```XML
> /// Returns the current fee balance and a boolean indicating whether the balance covers the fee.
> fn get_balance_and_if_covers_fee(
>     state: &mut dyn State,
> ```

would still like @giladchase or @elintul 's opinion on this change



_Code quote:_
```XML
&mut dyn State
```


<!-- Sent from Reviewable.io -->

2023-10-29 06:45 UTC, elintul requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-Nhu8Ijg1NALv3B64mu8:-Nhu8Ijh4Jbrbwq0h7oC:bewth11) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L161)):*
> ```XML
> 
>     fn check_nonce(
>         state: &mut dyn State,
> ```

Why? You're only reading.



_Code quote:_
```XML
state: &mut dyn State,
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-Nhu88oQBrfHkgS92ZK0:-Nhu88oR5-IDgs_mj3yO:b893mwi) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L171)):*
> ```XML
>         let current_nonce = state.get_nonce_at(address)?;
>         let tx_nonce = account_tx_context.nonce();
>         let invalid_nonce = current_nonce != tx_nonce;
> ```

Do we really need all these variables (except `current_nonce`)?



_Code quote:_
```XML
        let address = account_tx_context.sender_address();
        let current_nonce = state.get_nonce_at(address)?;
        let tx_nonce = account_tx_context.nonce();
        let invalid_nonce = current_nonce != tx_nonce;
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NhuAObU5ommuMzMneMy:-NhuAObU5ommuMzMneMz:b-sr8wlb) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L183)):*
> ```XML
>     }
> 
>     pub fn increment_nonce(
> ```

[We're incrementing the nonce](https://github.com/starkware-libs/blockifier/blob/90a548d39431244184a0eccd677775d5fd323310/crates/native_blockifier/src/transaction_executor.rs#L117) in the validation flow as well, so you shouldn't separate the methods yet.



_Code quote:_
```XML
increment_nonce
```


<!-- Sent from Reviewable.io -->

2023-10-29 09:40 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-Nhu8Ijg1NALv3B64mu8:-Nhul2Pt87bCB1ZyEGnc:b6788s8) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L161)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why? You're only reading.
</blockquote></details>

I did this because otherwise I get an error when `perform_pre_validation_checks()`
is called by `PyValidator::Validate()` , which passes a `state` of type `pub state: CachedState<PyStateReader>,` .
it was basically trial and error, so good chance I was wrong - what type should state be?
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-Nhu88oQBrfHkgS92ZK0:-NhumGIH0seborXFJBQn:b5h630c) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L171)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we really need all these variables (except `current_nonce`)?
</blockquote></details>

`address` and `tx_nonce` are used twice, and `invalid_nonce` is a "preparation" for the non strict nonce check, so IMO yes
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NhuAObU5ommuMzMneMy:-Nhun7evEfvbVCau5F1J:bilaofw) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L183)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

[We're incrementing the nonce](https://github.com/starkware-libs/blockifier/blob/90a548d39431244184a0eccd677775d5fd323310/crates/native_blockifier/src/transaction_executor.rs#L117) in the validation flow as well, so you shouldn't separate the methods yet.
</blockquote></details>

I'm not sure I understand this comment?
the pre-validation checks don't increment the nonce, so I separated the nonce increment from the nonce check


<!-- Sent from Reviewable.io -->

2023-10-29 12:15 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-Nhu8Ijg1NALv3B64mu8:-NhvLXVC3MBiPaMAe691:bea289k) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L161)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I did this because otherwise I get an error when `perform_pre_validation_checks()`
is called by `PyValidator::Validate()` , which passes a `state` of type `pub state: CachedState<PyStateReader>,` .
it was basically trial and error, so good chance I was wrong - what type should state be?
</blockquote></details>

I might be misunderstanding something, i just tried replacing all `State`s here with `StateReader` and it compiled.

Also, where is the usage in PyValidator you mentioned? it's not in this PR so i'm assuming it's in a separate one?


<!-- Sent from Reviewable.io -->

2023-10-29 12:21 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NhgDxSu1i8h_0Y-Nf-H:-NhvMByx9zaVM3lIbC3H:b-j8iwhv) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/fee/fee_utils.rs#L78)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

would still like @giladchase or @elintul 's opinion on this change
</blockquote></details>

AFAICS `StateReader` works here, i'm not seeing an error :thinking: 
This is my diff:
```bash
diff --git a/crates/blockifier/src/fee/fee_utils.rs b/crates/blockifier/src/fee/fee_utils.rs
index 8d3b992..5d62b6d 100644
--- a/crates/blockifier/src/fee/fee_utils.rs
+++ b/crates/blockifier/src/fee/fee_utils.rs
@@ -5,7 +5,7 @@ use starknet_api::transaction::Fee;
 
 use crate::abi::constants;
 use crate::block_context::BlockContext;
-use crate::state::state_api::State;
+use crate::state::state_api::StateReader;
 use crate::transaction::errors::TransactionExecutionError;
 use crate::transaction::objects::{
     AccountTransactionContext, FeeType, HasRelatedFeeType, ResourcesMapping,
@@ -75,7 +75,7 @@ pub fn calculate_tx_fee(
 
 /// Returns the current fee balance and a boolean indicating whether the balance covers the fee.
 fn get_balance_and_if_covers_fee(
-    state: &mut dyn State,
+    state: &mut dyn StateReader,
     account_tx_context: &AccountTransactionContext,
     block_context: &BlockContext,
     fee: Fee,
@@ -96,7 +96,7 @@ fn get_balance_and_if_covers_fee(
 /// Verifies that, given the current state, the account can pay the given max fee.
 /// Error may indicate insufficient balance, or some other error.
 pub fn verify_can_pay_max_fee(
-    state: &mut dyn State,
+    state: &mut dyn StateReader,
     account_tx_context: &AccountTransactionContext,
     block_context: &BlockContext,
     max_fee: Fee,
@@ -112,7 +112,7 @@ pub fn verify_can_pay_max_fee(
 
 /// Returns `true` if and only if the balance covers the fee.
 pub fn can_pay_fee(
-    state: &mut dyn State,
+    state: &mut dyn StateReader,
     account_tx_context: &AccountTransactionContext,
     block_context: &BlockContext,
     fee: Fee,
diff --git a/crates/blockifier/src/transaction/account_transaction.rs b/crates/blockifier/src/transaction/account_transaction.rs
index 305c504..d8c7390 100644
--- a/crates/blockifier/src/transaction/account_transaction.rs
+++ b/crates/blockifier/src/transaction/account_transaction.rs
@@ -143,7 +143,7 @@ impl AccountTransaction {
 
     pub fn perform_pre_validation_checks(
         &self,
-        state: &mut dyn State,
+        state: &mut dyn StateReader,
         account_tx_context: &AccountTransactionContext,
         block_context: &BlockContext,
         charge_fee: bool,
@@ -158,7 +158,7 @@ impl AccountTransaction {
     }
 
     fn check_nonce(
-        state: &mut dyn State,
+        state: &mut dyn StateReader,
         account_tx_context: &AccountTransactionContext,
     ) -> TransactionExecutionResult<()> {
         if account_tx_context.version() == TransactionVersion::ZERO {
@@ -210,7 +210,7 @@ impl AccountTransaction {
     /// Checks that the account's balance covers max fee.
     fn check_fee_balance(
         &self,
-        state: &mut dyn State,
+        state: &mut dyn StateReader,
         block_context: &BlockContext,
     ) -> TransactionExecutionResult<()> {
         let account_tx_context = self.get_account_tx_context();
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NhuAObU5ommuMzMneMy:-NhvNHboB2CZgCx3FFQM:bb7oms7) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L183)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Also, IIUC all transactions have their nonces incremented in your flow, while previously v0 did not have this behavior (see `handle_nonce` logic which short-circuits on v0).
Is that intentional?
</blockquote></details>

Oh wait never mind ignore my comment i didn't notice the check inside `increment_nonce`.


<!-- Sent from Reviewable.io -->

2023-10-29 12:43 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NhvOvy0AozAfEiR06qb:-NhvOvy0AozAfEiR06qc:bvk5cwv) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L163)):*
> ```XML
>         state: &mut dyn State,
>         account_tx_context: &AccountTransactionContext,
>     ) -> TransactionExecutionResult<()> {
> ```

Refactor this function to be a standalone function, as it doesn't refer to the struct. The same applies to `increment_nonce`.

Alternatively, consider encapsulating these functions into methods of a dedicated struct like `TransactionExecutionPreprocessor`.
Initialize this struct at the beginning of the `execute` method, passing in relevant context like `state` and `account_tx_context`.
This would keep this `impl` of `ExecutableTransaction` focused solely on transaction execution.



_Code quote:_
```XML
    fn check_nonce(
        state: &mut dyn State,
        account_tx_context: &AccountTransactionContext,
    ) -> TransactionExecutionResult<()> {
```


<!-- Sent from Reviewable.io -->

2023-10-29 13:36 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NhgDxSu1i8h_0Y-Nf-H:-NhvdUAyCU9yaAmh8cyW:btup9nr) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/fee/fee_utils.rs#L78)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

AFAICS `StateReader` works here, i'm not seeing an error :thinking: 
This is my diff:
```bash
diff --git a/crates/blockifier/src/fee/fee_utils.rs b/crates/blockifier/src/fee/fee_utils.rs
index 8d3b992..5d62b6d 100644
--- a/crates/blockifier/src/fee/fee_utils.rs
+++ b/crates/blockifier/src/fee/fee_utils.rs
@@ -5,7 +5,7 @@ use starknet_api::transaction::Fee;
 
 use crate::abi::constants;
 use crate::block_context::BlockContext;
-use crate::state::state_api::State;
+use crate::state::state_api::StateReader;
 use crate::transaction::errors::TransactionExecutionError;
 use crate::transaction::objects::{
     AccountTransactionContext, FeeType, HasRelatedFeeType, ResourcesMapping,
@@ -75,7 +75,7 @@ pub fn calculate_tx_fee(
 
 /// Returns the current fee balance and a boolean indicating whether the balance covers the fee.
 fn get_balance_and_if_covers_fee(
-    state: &mut dyn State,
+    state: &mut dyn StateReader,
     account_tx_context: &AccountTransactionContext,
     block_context: &BlockContext,
     fee: Fee,
@@ -96,7 +96,7 @@ fn get_balance_and_if_covers_fee(
 /// Verifies that, given the current state, the account can pay the given max fee.
 /// Error may indicate insufficient balance, or some other error.
 pub fn verify_can_pay_max_fee(
-    state: &mut dyn State,
+    state: &mut dyn StateReader,
     account_tx_context: &AccountTransactionContext,
     block_context: &BlockContext,
     max_fee: Fee,
@@ -112,7 +112,7 @@ pub fn verify_can_pay_max_fee(
 
 /// Returns `true` if and only if the balance covers the fee.
 pub fn can_pay_fee(
-    state: &mut dyn State,
+    state: &mut dyn StateReader,
     account_tx_context: &AccountTransactionContext,
     block_context: &BlockContext,
     fee: Fee,
diff --git a/crates/blockifier/src/transaction/account_transaction.rs b/crates/blockifier/src/transaction/account_transaction.rs
index 305c504..d8c7390 100644
--- a/crates/blockifier/src/transaction/account_transaction.rs
+++ b/crates/blockifier/src/transaction/account_transaction.rs
@@ -143,7 +143,7 @@ impl AccountTransaction {
 
     pub fn perform_pre_validation_checks(
         &self,
-        state: &mut dyn State,
+        state: &mut dyn StateReader,
         account_tx_context: &AccountTransactionContext,
         block_context: &BlockContext,
         charge_fee: bool,
@@ -158,7 +158,7 @@ impl AccountTransaction {
     }
 
     fn check_nonce(
-        state: &mut dyn State,
+        state: &mut dyn StateReader,
         account_tx_context: &AccountTransactionContext,
     ) -> TransactionExecutionResult<()> {
         if account_tx_context.version() == TransactionVersion::ZERO {
@@ -210,7 +210,7 @@ impl AccountTransaction {
     /// Checks that the account's balance covers max fee.
     fn check_fee_balance(
         &self,
-        state: &mut dyn State,
+        state: &mut dyn StateReader,
         block_context: &BlockContext,
     ) -> TransactionExecutionResult<()> {
         let account_tx_context = self.get_account_tx_context();
```
</blockquote></details>

@amosStarkware you sure this doesn't work? maybe in later PRs it's relevant?
If so, I would revert the change here and apply in the PR it's needed, we can discuss there


<!-- Sent from Reviewable.io -->

2023-10-29 15:13 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-Nhu8Ijg1NALv3B64mu8:-Nhvxhnk6jSVFTrPFa6j:b-lm500y) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L161)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I might be misunderstanding something, i just tried replacing all `State`s here with `StateReader` and it compiled.

Also, where is the usage in PyValidator you mentioned? it's not in this PR so i'm assuming it's in a separate one?
</blockquote></details>

you can see the usage here:
https://reviewable.io/reviews/starkware-libs/blockifier/1013
I removed the changes to `state`'s type, I'll add them when they're relevant :-)
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NhvOvy0AozAfEiR06qb:-NhvyNJSD_gYYGB82Dut:b-yr7ejh) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L163)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Refactor this function to be a standalone function, as it doesn't refer to the struct. The same applies to `increment_nonce`.

Alternatively, consider encapsulating these functions into methods of a dedicated struct like `TransactionExecutionPreprocessor`.
Initialize this struct at the beginning of the `execute` method, passing in relevant context like `state` and `account_tx_context`.
This would keep this `impl` of `ExecutableTransaction` focused solely on transaction execution.
</blockquote></details>

Are you sure?
This method doesn't operate on the struct but it is relevant to it (like a python static function) - that's why it doesn't have a `self` parameter. @dorimedini-starkware WYT?
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NhgDxSu1i8h_0Y-Nf-H:-NhvypXX-gWmuhbIgv1i:b-q03udk) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/fee/fee_utils.rs#L78)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@amosStarkware you sure this doesn't work? maybe in later PRs it's relevant?
If so, I would revert the change here and apply in the PR it's needed, we can discuss there
</blockquote></details>

it's relevant when the PyValidator calls perform_pre_validation_checks
I reverted the changes like you suggested :thumbsup: 


<!-- Sent from Reviewable.io -->

2023-10-29 15:22 UTC, dorimedini-starkware submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-Nhu8Ijg1NALv3B64mu8:-Nhw0lAj68E5z5y2MZEn:b-n4e9hk) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L161)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

you can see the usage here:
https://reviewable.io/reviews/starkware-libs/blockifier/1013
I removed the changes to `state`'s type, I'll add them when they're relevant :-)
</blockquote></details>

It should be done with StateReader... the dependency is mutable, if you use `State`, compiler won't protect you if you accidentally mutate the state in this function
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NhvOvy0AozAfEiR06qb:-Nhw0Dih5Ky0C--QCSO2:b68927p) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L163)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Are you sure?
This method doesn't operate on the struct but it is relevant to it (like a python static function) - that's why it doesn't have a `self` parameter. @dorimedini-starkware WYT?
</blockquote></details>

@giladchase I think AccountTransaction is becoming a monster anyway - separating into traits is the way to go IMO, I am in favor of keeping it static and extracting a `PreValidatableTransaction` trait later (like `ExecutableTransaction` and `ValidatableTransaction` (I hope I didn't make up that last one))


<!-- Sent from Reviewable.io -->

2023-10-29 15:36 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-Nhu8Ijg1NALv3B64mu8:-Nhw3xVg2SXLDYXPTKbD:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L161)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

It should be done with StateReader... the dependency is mutable, if you use `State`, compiler won't protect you if you accidentally mutate the state in this function
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-29 15:50 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-:-Nhw7L3X190Azor1XZDk:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)



<!-- Sent from Reviewable.io -->

2023-10-30 11:29 UTC, giladchase submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NhvOvy0AozAfEiR06qb:-Ni-En78BUaBNfFeiLab:bidzxls) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L163)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@giladchase I think AccountTransaction is becoming a monster anyway - separating into traits is the way to go IMO, I am in favor of keeping it static and extracting a `PreValidatableTransaction` trait later (like `ExecutableTransaction` and `ValidatableTransaction` (I hope I didn't make up that last one))
</blockquote></details>

From what i could find, the requirement for a func to be assoc to a struct is stricter than "relevant", it should be _inherently tied_ to the struct (which usually means that it has to mention it in some way, even implicitly, but mostly it's constructors/factories).
I also agree that `AccountTransaction` is becomeing a bit of a god object (especially account_transaction_test), but for me it wasn't the main motivation for not making it an assoc.

The way i think about it is: if i read this function `check_nonce` and only it, will it be totally obvious that it is tied to the AccountTransaction struct? IMO It could technically have been even a method on account_tx_context (i don't propose we do this but just for example).

Haven't found an official reference, but here the best [non-official](https://users.rust-lang.org/t/best-practice-with-associated-methods/70949) one i could find, but it has a core member in the thread.

[@giladchase](https://github.com/giladchase) I think AccountTransaction is becoming a monster anyway - separating into traits is the way to go IMO, I am in favor of keeping it static and extracting a `PreValidatableTransaction` trait later (like `ExecutableTransaction` and `ValidatableTransaction` (I hope I didn't make up that last one))


<!-- Sent from Reviewable.io -->

2023-10-30 15:46 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NhvOvy0AozAfEiR06qb:-Ni0FdDf5shFX_-yHiqa:bf1rmob) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L163)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

From what i could find, the requirement for a func to be assoc to a struct is stricter than "relevant", it should be _inherently tied_ to the struct (which usually means that it has to mention it in some way, even implicitly, but mostly it's constructors/factories).
I also agree that `AccountTransaction` is becomeing a bit of a god object (especially account_transaction_test), but for me it wasn't the main motivation for not making it an assoc.

The way i think about it is: if i read this function `check_nonce` and only it, will it be totally obvious that it is tied to the AccountTransaction struct? IMO It could technically have been even a method on account_tx_context (i don't propose we do this but just for example).

Haven't found an official reference, but here the best [non-official](https://users.rust-lang.org/t/best-practice-with-associated-methods/70949) one i could find, but it has a core member in the thread.

[@giladchase](https://github.com/giladchase) I think AccountTransaction is becoming a monster anyway - separating into traits is the way to go IMO, I am in favor of keeping it static and extracting a `PreValidatableTransaction` trait later (like `ExecutableTransaction` and `ValidatableTransaction` (I hope I didn't make up that last one))
</blockquote></details>

Good point.
Don't think it's so important, but it's strange that check_nonce will be a separate function, while other assocs stay.
better to have a separate PR to move a chunk of stuff


<!-- Sent from Reviewable.io -->

2023-10-31 07:41 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NhvOvy0AozAfEiR06qb:-Ni3fEgA8h3nQWiWOTj3:b-tbaldh) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L163)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Good point.
Don't think it's so important, but it's strange that check_nonce will be a separate function, while other assocs stay.
better to have a separate PR to move a chunk of stuff
</blockquote></details>

True, consistency takes precedence.
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 


<!-- Sent from Reviewable.io -->

2023-10-31 08:59 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2023-10-31 13:18 UTC, dorimedini-starkware submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2023-11-05 05:49 UTC, elintul requested changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-Nhu88oQBrfHkgS92ZK0:-NiT0Rw4E5lCzfxVdViK:b-mph7m7) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L171)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

`address` and `tx_nonce` are used twice, and `invalid_nonce` is a "preparation" for the non strict nonce check, so IMO yes
</blockquote></details>

So please add them in the non-strict PR.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NhuAObU5ommuMzMneMy:-NiT-zdf3QfB92jwJZ82:b-o476hc) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L183)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Oh wait never mind ignore my comment i didn't notice the check inside `increment_nonce`.
</blockquote></details>

I'm saying, no need to split `handle_nonce` to two functions: in both (GW and sequencer) flows we check the nonce and increment it (in the GW it is currently done and the state is dropped right after that).


<!-- Sent from Reviewable.io -->

2023-11-05 06:05 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-Nhu88oQBrfHkgS92ZK0:-NiT4FiIBYmEOgUbeY89:bl3fxtb) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L171)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

So please add them in the non-strict PR.
</blockquote></details>

Nevermind, I reviewed that PR as well; but in general - it's good to either add code changes in the relevant PR, or alternatively: add a small comment to the reviewer on how you foresee this area to look like. 


<!-- Sent from Reviewable.io -->

2023-11-05 10:43 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NhuAObU5ommuMzMneMy:-NiU0rirBM_G-QuqfKtb:ba8m24k) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L183)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'm saying, no need to split `handle_nonce` to two functions: in both (GW and sequencer) flows we check the nonce and increment it (in the GW it is currently done and the state is dropped right after that).
</blockquote></details>

Done (though this is less good IMO)


<!-- Sent from Reviewable.io -->

2023-11-05 11:56 UTC, elintul submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NhuAObU5ommuMzMneMy:-NiUKUbo8eu4uv0LjsqX:b1p7k15) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0cf094855d0ac6ed72556c68859a0930d2aa25d/crates/blockifier/src/transaction/account_transaction.rs#L183)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Done (though this is less good IMO)
</blockquote></details>

I understand and you're right. The assumption the state in the GW is being dropped after each transaction is well-documented. Besides, we're going to develop this component (mempool) anew soon.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 144 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NiUKl4QCAfzNU50XpGO:-NiUKl4QCAfzNU50XpGP:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd9fd1ad96ef2f9d0073e4b03ef275ee8ba7fbb1/crates/blockifier/src/transaction/account_transaction.rs#L144)):*
> ```XML
>     }
> 
>     // The nonce is incremented during these checks.
> ```





_Suggestion:_
```XML
// Performs static checks before executing validation entry point.
// Note that nonce is incremented during these checks.
```


<!-- Sent from Reviewable.io -->

2023-11-05 15:47 UTC, dorimedini-starkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2023-11-07 10:49 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 156 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NidOIPK-6A5x_ZCjIvl:-NidOIPK-6A5x_ZCjIvm:b25dxrq) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd9fd1ad96ef2f9d0073e4b03ef275ee8ba7fbb1/crates/blockifier/src/transaction/account_transaction.rs#L156)):*
> ```XML
>         if charge_fee {
>             self.check_fee_balance(state, block_context)?;
>         }
> ```

Out of curiosity- Why change the order?



_Code quote:_
```XML
        Self::handle_nonce(state, account_tx_context)?;

        if charge_fee {
            self.check_fee_balance(state, block_context)?;
        }
```


<!-- Sent from Reviewable.io -->

2023-11-07 15:40 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 156 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NidOIPK-6A5x_ZCjIvl:-NieQ_hP1B3E0c8jnk3N:bf5skj3) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd9fd1ad96ef2f9d0073e4b03ef275ee8ba7fbb1/crates/blockifier/src/transaction/account_transaction.rs#L156)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Out of curiosity- Why change the order?
</blockquote></details>

Not my work but I like that the no-condition check is checked before the conditional-check; makes sense to start with the "bigger filter"


<!-- Sent from Reviewable.io -->

2023-11-08 09:44 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 144 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NiUKl4QCAfzNU50XpGO:-NiiDhIZ6KgNyZxSirIG:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd9fd1ad96ef2f9d0073e4b03ef275ee8ba7fbb1/crates/blockifier/src/transaction/account_transaction.rs#L144)):*
> ```XML
>     }
> 
>     // The nonce is incremented during these checks.
> ```

Done
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 156 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NidOIPK-6A5x_ZCjIvl:-NiiE2KK4Fhz2CYhvOAw:b37ypwn) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd9fd1ad96ef2f9d0073e4b03ef275ee8ba7fbb1/crates/blockifier/src/transaction/account_transaction.rs#L156)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Not my work but I like that the no-condition check is checked before the conditional-check; makes sense to start with the "bigger filter"
</blockquote></details>

It's also a more basic check so IMO it makes sense to put it first


<!-- Sent from Reviewable.io -->

2023-11-08 09:57 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)



<!-- Sent from Reviewable.io -->

2023-11-08 10:07 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 174 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NiiOWDA0nQIrx5WT64b:-NiiOWDA0nQIrx5WT64c:b2ni78k) ([raw file](https://github.com/starkware-libs/blockifier/blob/6666da90c8cd3f766976090bc7728cd9bb4c03fa/crates/blockifier/src/transaction/account_transaction.rs#L174)):*
> ```XML
>             });
>         }
>         Ok(state.increment_nonce(account_tx_context.sender_address())?)
> ```

lol



_Suggestion:_
```XML
address
```


<!-- Sent from Reviewable.io -->

2023-11-08 10:19 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 174 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-NiiOWDA0nQIrx5WT64b:-NiiRRdkE4uAvl6kwGnW:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6666da90c8cd3f766976090bc7728cd9bb4c03fa/crates/blockifier/src/transaction/account_transaction.rs#L174)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

lol
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-08 10:20 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1041#-:-NiiRk4b2nSUDZUkfpMh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase and @noaov1)



<!-- Sent from Reviewable.io -->

2023-11-08 10:23 UTC, merged