Post-execution checks for v3
starkware-libs/blockifier pull request #1045
Opened 2023-10-28 20:03 UTC by dorimedini-starkware

2023-10-29 11:14 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @elintul, @noaov1, and @zuphitf)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Nhv87pR5qGWxkN1b9bl:-Nhv87pR5qGWxkN1b9bm:bk1tz) (no related file):*
[python side](https://reviewable.io/reviews/starkware-industries/starkware/32347)

___


<!-- Sent from Reviewable.io -->

2023-10-31 07:22 UTC, noaov1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @elintul, and @zuphitf)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 144 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni3Y0AQ3DJ2eQBlheiT:-Ni3Y0AQ3DJ2eQBlheiU:b-4ftx62) ([raw file](https://github.com/starkware-libs/blockifier/blob/7645d9698bb23f4cd79a3fc6f618ea37fc07735f/crates/blockifier/src/fee/fee_utils.rs#L144)):*
> ```XML
> }
> 
> /// Returns the fee to charge, if the L1 gas used is equal to the max L1 gas allowed.
> ```

This behaviour is not reflecting in the implementation. 



_Code quote:_
```XML
if the L1 gas used is equal to the max L1 gas allowed.
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 148 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni3Y84QEBNCEsOfsYmW:-Ni3Y84QEBNCEsOfsYmX:b6ns0b6) ([raw file](https://github.com/starkware-libs/blockifier/blob/7645d9698bb23f4cd79a3fc6f618ea37fc07735f/crates/blockifier/src/fee/fee_utils.rs#L148)):*
> ```XML
>     account_tx_context: &CurrentAccountTransactionContext,
>     block_context: &BlockContext,
> ) -> Fee {
> ```

Why not passing directly the `l1_gas_max_amount`?



_Code quote:_
```XML
pub fn fee_for_l1_gas_limit(
    account_tx_context: &CurrentAccountTransactionContext,
    block_context: &BlockContext,
) -> Fee {
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 285 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni3_vWqAaMkuZUyv8CM:-Ni3_vWqAaMkuZUyv8CN:b-1lcn6y) ([raw file](https://github.com/starkware-libs/blockifier/blob/7645d9698bb23f4cd79a3fc6f618ea37fc07735f/crates/blockifier/src/transaction/account_transaction.rs#L285)):*
> ```XML
>         // price(s). The sender is ensured to have sufficient balance to cover these costs due to
>         // pre-validation checks: deprecated transactions check `balance >= max_fee`, and current
>         // transactions check `balance >= max_l1_gas * gas_price`.
> ```

We currently verify `balance >= max_l1_gas * max_gas_price`. Are we planning to change it according to your comment? 



_Code quote:_
```XML
 // transactions check `balance >= max_l1_gas * gas_price`.
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 305 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni3WSHYCwJwzbfBbiMd:-Ni3WSHYCwJwzbfBbiMe:b-uj35q6) ([raw file](https://github.com/starkware-libs/blockifier/blob/7645d9698bb23f4cd79a3fc6f618ea37fc07735f/crates/blockifier/src/transaction/account_transaction.rs#L305)):*
> ```XML
>                     .max_amount as u128;
>                 let l1_gas_usage =
>                     calculate_tx_l1_gas_usage(post_execute_resources, block_context)?;
> ```

Can you try to avoid repeating this calculation? Maybe calculate the actual fee in this method?



_Code quote:_
```XML
calculate_tx_l1_gas_usage(post_execute_resources, block_context)?;
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 324 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni3alpc3qoF5Oy2513t:-Ni3alpc3qoF5Oy2513u:bfiw5u2) ([raw file](https://github.com/starkware-libs/blockifier/blob/7645d9698bb23f4cd79a3fc6f618ea37fc07735f/crates/blockifier/src/transaction/account_transaction.rs#L324)):*
> ```XML
>         // post-validation is equal to balance pre-validation). As such, it is safe to charge
>         // post-execution fee if (a) resources used (and the fee derived from them) are within
>         // bounds and (b) the execution state is reverted.
> ```

I'm not sure I understand :) How it relates to the code below?



_Code quote:_
```XML
        // The resource bounds are verified to be covered by the account's balance in pre-validation
        // checks, and account validation can only effect the account contract's state (so balance
        // post-validation is equal to balance pre-validation). As such, it is safe to charge
        // post-execution fee if (a) resources used (and the fee derived from them) are within
        // bounds and (b) the execution state is reverted.
```


<!-- Sent from Reviewable.io -->

2023-10-31 07:37 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @elintul, and @zuphitf)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Nhv87pR5qGWxkN1b9bl:-Ni3e4AA3_tWkKeyjcko:bx8lah8) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[python side](https://reviewable.io/reviews/starkware-industries/starkware/32347)
</blockquote></details>

What about [this](https://github.com/starkware-libs/blockifier/blob/4a77d6b926015d4b0e1c85c5e9a332d862e7d114/crates/blockifier/src/transaction/account_transaction.rs#L231) check? Is it used for the non-revertible flow? 

___


<!-- Sent from Reviewable.io -->

2023-10-31 08:58 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @elintul, @noaov1, and @zuphitf)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Nhv87pR5qGWxkN1b9bl:-Ni3tKSFEhFc6WTIaRYU:b-oyc1mr) (no related file):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What about [this](https://github.com/starkware-libs/blockifier/blob/4a77d6b926015d4b0e1c85c5e9a332d862e7d114/crates/blockifier/src/transaction/account_transaction.rs#L231) check? Is it used for the non-revertible flow?
</blockquote></details>

No; it needs fixing as [part of the effort](https://reviewable.io/reviews/starkware-libs/blockifier/1044) to remove the `max_fee()` getter.
Once 1044 is in I'll search for remaining usages of `max_fee()` and remove + fix them

___
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 144 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni3Y0AQ3DJ2eQBlheiT:-Ni3tloh983Wjr6z60af:bvyb82y) ([raw file](https://github.com/starkware-libs/blockifier/blob/7645d9698bb23f4cd79a3fc6f618ea37fc07735f/crates/blockifier/src/fee/fee_utils.rs#L144)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

This behaviour is not reflecting in the implementation.
</blockquote></details>

better?
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 148 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni3Y84QEBNCEsOfsYmW:-Ni3vCvN4Y71NPE6rO2e:b59m4dk) ([raw file](https://github.com/starkware-libs/blockifier/blob/7645d9698bb23f4cd79a3fc6f618ea37fc07735f/crates/blockifier/src/fee/fee_utils.rs#L148)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why not passing directly the `l1_gas_max_amount`?
</blockquote></details>

good point, done
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 285 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni3_vWqAaMkuZUyv8CM:-Ni3vTRm5qrv9R2zOTIR:bo4xloe) ([raw file](https://github.com/starkware-libs/blockifier/blob/7645d9698bb23f4cd79a3fc6f618ea37fc07735f/crates/blockifier/src/transaction/account_transaction.rs#L285)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We currently verify `balance >= max_l1_gas * max_gas_price`. Are we planning to change it according to your comment?
</blockquote></details>

Debatable, but I'm in favor or keeping the `balance >= max * max` check; this is what the sender signed for, the sender should be able to pay.
Edited the comment to be more ambiguous in case we want to change things in pre-validation
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 305 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni3WSHYCwJwzbfBbiMd:-Ni3w3liCvjjB2j_taiM:b-1z69ou) ([raw file](https://github.com/starkware-libs/blockifier/blob/7645d9698bb23f4cd79a3fc6f618ea37fc07735f/crates/blockifier/src/transaction/account_transaction.rs#L305)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you try to avoid repeating this calculation? Maybe calculate the actual fee in this method?
</blockquote></details>

WDYM? I should get the post-execution gas usage and fee as input, not just fee?
This is a bit difficult to untangle in this scope
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 324 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni3alpc3qoF5Oy2513t:-Ni3wgGV23ktuSy58wn7:b-m97o70) ([raw file](https://github.com/starkware-libs/blockifier/blob/7645d9698bb23f4cd79a3fc6f618ea37fc07735f/crates/blockifier/src/transaction/account_transaction.rs#L324)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I'm not sure I understand :) How it relates to the code below?
</blockquote></details>

It explains why it is safe; i.e. why - on revert - the reverted state is such that the sender has enough balance to pay the original post-execution fee.
Need both inequalities here:
1. Pre-execution balance covers fee/gas bounds
2. fee/gas bounds cover post-execution fee


<!-- Sent from Reviewable.io -->

2023-10-31 16:28 UTC, giladchase requested changes
Tests for the new error messages? Or are they up the stack?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-:-Ni5YD997-5gXEsM8Wmc:b-wuk4yb)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @elintul, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 324 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni3alpc3qoF5Oy2513t:-Ni5WD1k0cbfRmBHMBBX:b-2hjggc) ([raw file](https://github.com/starkware-libs/blockifier/blob/7645d9698bb23f4cd79a3fc6f618ea37fc07735f/crates/blockifier/src/transaction/account_transaction.rs#L324)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

It explains why it is safe; i.e. why - on revert - the reverted state is such that the sender has enough balance to pay the original post-execution fee.
Need both inequalities here:
1. Pre-execution balance covers fee/gas bounds
2. fee/gas bounds cover post-execution fee
</blockquote></details>

I'm also not quite following  :thinking:  does this mean that up until "(b)" it is recapping what happened in the previous block?
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 269 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni5UnHH5-e9QVW6xInS:-Ni5UnHH5-e9QVW6xInT:b-dghc1r) ([raw file](https://github.com/starkware-libs/blockifier/blob/eeeb2a76992ae8c2924396b1cdf2f74979b0e900/crates/blockifier/src/transaction/account_transaction.rs#L269)):*
> ```XML
>     /// After successful execution and fee computation, checks that the sender can pay the fee.
>     /// Returns the actual fee to pay and an optional revert error (if revert is needed).
>     fn post_execution_final_fee_and_error<S: StateReader>(
> ```

I think this function is doing too much at this point, should it be split into 2? Each part being one of the two checks you mention.

We can make them into 2 methods on `ActualCost` (instead of unpacking it a few lines before in the callsite), i think they'd fit better there than as a static method on `AccountTransaction`.

It should also help testability.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 285 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni5Iz4Q0BmjcOKqbH4M:-Ni5Iz4R3_1LSOwLgWQV:b3jskjm) ([raw file](https://github.com/starkware-libs/blockifier/blob/eeeb2a76992ae8c2924396b1cdf2f74979b0e900/crates/blockifier/src/transaction/account_transaction.rs#L285)):*
> ```XML
>         // price(s). The sender is ensured to have sufficient balance to cover these costs due to
>         // pre-validation checks: deprecated transactions check balance covers max_fee, and current
>         // transactions check balance covers the max gas amount.
> ```

Could we split this up into inline comments to clarify the logic here? It took me a few reads to fully grasp it.

Consider declaring a variable like `let insufficient_max_fee: Option<Fee> = match ...` and afterwards match again and add the revert error (with a comment before each block).

It adds some duplication but could make the code easier to understand quickly.



_Code quote:_
```XML
        // First, compare actual resources used against the upper bound(s) defined by the sender.
        // If the initial check fails, revert and charge based on the upper bound(s) and current
        // price(s). The sender is ensured to have sufficient balance to cover these costs due to
        // pre-validation checks: deprecated transactions check balance covers max_fee, and current
        // transactions check balance covers the max gas amount.
```


<!-- Sent from Reviewable.io -->

2023-10-31 16:29 UTC, dorimedini-starkware reviewed
[here](https://reviewable.io/reviews/starkware-libs/blockifier/1049)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-:-Ni5ZQkmBQfODjNArkyJ:b-dcgad)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @elintul, @noaov1, and @zuphitf)



<!-- Sent from Reviewable.io -->

2023-10-31 16:32 UTC, giladchase reviewed
I should have known better :white_heart:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-:-Ni5Ze554P3BRHgZVGrc:b6oxk60)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @elintul, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 324 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni3alpc3qoF5Oy2513t:-Ni5ZmHj7NZkQJHrmPF-:b-7s5q5p) ([raw file](https://github.com/starkware-libs/blockifier/blob/7645d9698bb23f4cd79a3fc6f618ea37fc07735f/crates/blockifier/src/transaction/account_transaction.rs#L324)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I'm also not quite following  :thinking:  does this mean that up until "(b)" it is recapping what happened in the previous block?
</blockquote></details>

Also, can any of these assumptions be translated into assert!ons? 


<!-- Sent from Reviewable.io -->

2023-11-01 09:13 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @elintul, @giladchase, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 324 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni3alpc3qoF5Oy2513t:-Ni97d8R8xFWrn600DOU:bmxre32) ([raw file](https://github.com/starkware-libs/blockifier/blob/7645d9698bb23f4cd79a3fc6f618ea37fc07735f/crates/blockifier/src/transaction/account_transaction.rs#L324)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Also, can any of these assumptions be translated into assert!ons?
</blockquote></details>

I'll rephrase...
No, we shouldn't assert at this point; the assumptions were asserted in pre-validation phase of *this* transaction. No point in repeating.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 269 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni5UnHH5-e9QVW6xInS:-Ni97BOE9ObNTaJ-LKre:b5jlj0l) ([raw file](https://github.com/starkware-libs/blockifier/blob/eeeb2a76992ae8c2924396b1cdf2f74979b0e900/crates/blockifier/src/transaction/account_transaction.rs#L269)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think this function is doing too much at this point, should it be split into 2? Each part being one of the two checks you mention.

We can make them into 2 methods on `ActualCost` (instead of unpacking it a few lines before in the callsite), i think they'd fit better there than as a static method on `AccountTransaction`.

It should also help testability.
</blockquote></details>

I'd prefer merging this as-is, and having you refactor; I'm less familiar with the ActualCost Way of Life™.
Or would you like to explain f2f what refactor you have in mind?
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 285 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni5Iz4Q0BmjcOKqbH4M:-Ni978489pyJQUhYuv_g:bpqu37y) ([raw file](https://github.com/starkware-libs/blockifier/blob/eeeb2a76992ae8c2924396b1cdf2f74979b0e900/crates/blockifier/src/transaction/account_transaction.rs#L285)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Could we split this up into inline comments to clarify the logic here? It took me a few reads to fully grasp it.

Consider declaring a variable like `let insufficient_max_fee: Option<Fee> = match ...` and afterwards match again and add the revert error (with a comment before each block).

It adds some duplication but could make the code easier to understand quickly.
</blockquote></details>

Done (split the comment, good enough?)


<!-- Sent from Reviewable.io -->

2023-11-01 11:04 UTC, giladchase submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @elintul, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 324 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni3alpc3qoF5Oy2513t:-Ni9Rp-Q3-s53fCuCN_w:bxxv560) ([raw file](https://github.com/starkware-libs/blockifier/blob/7645d9698bb23f4cd79a3fc6f618ea37fc07735f/crates/blockifier/src/transaction/account_transaction.rs#L324)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I'll rephrase...
No, we shouldn't assert at this point; the assumptions were asserted in pre-validation phase of *this* transaction. No point in repeating.
</blockquote></details>

Thanks for clarifying, however i still don't follow why these assumptions have to be laid out at this particular function.

In other words, if those assumptions are violated, will the behaviour of this function change?
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 269 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni5UnHH5-e9QVW6xInS:-Ni9K92X1wGdkLrZh_sP:bvdopsg) ([raw file](https://github.com/starkware-libs/blockifier/blob/eeeb2a76992ae8c2924396b1cdf2f74979b0e900/crates/blockifier/src/transaction/account_transaction.rs#L269)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I'd prefer merging this as-is, and having you refactor; I'm less familiar with the ActualCost Way of Life™.
Or would you like to explain f2f what refactor you have in mind?
</blockquote></details>

It's a struct containing `actual_cost` and `actual_resources`, which is currently only unpacked for those values and does nothing else (but arguably could be a good home for these methods than as static function on an AccountTransaction)

But regardless of ActualCost, i still think this is doing too much in one function and should be split.
Currently this function is in charge of:
1. deciding if a revert should be made, using two separate criteria, and calculated the required fee based on each case --- this is done twice for each of current/deprecated.
2. for each of the 4 state in (1) decide on:
    2.1 how much fee to charge
    2.2 what error message to generate.

Also, looking at the callsite, it looks liked the error message is the sole indicator that a revert was issued?
Perhaps we should encapsulate the error message and amended fee in a dedicated object? 


<!-- Sent from Reviewable.io -->

2023-11-01 11:07 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @elintul, @giladchase, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 324 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni3alpc3qoF5Oy2513t:-Ni9Z0r33kfa7bdYppgb:bvfxm4q) ([raw file](https://github.com/starkware-libs/blockifier/blob/7645d9698bb23f4cd79a3fc6f618ea37fc07735f/crates/blockifier/src/transaction/account_transaction.rs#L324)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Thanks for clarifying, however i still don't follow why these assumptions have to be laid out at this particular function.

In other words, if those assumptions are violated, will the behaviour of this function change?
</blockquote></details>

If the assumptions are violated, the fee this function returns may not be safe to charge.
The point is: after this function is called, *the returned fee can be charged* (conditioned on revert, possibly).


<!-- Sent from Reviewable.io -->

2023-11-01 15:54 UTC, giladchase reviewed
Python Pr?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-:-NiAa0U--8cNpfWsvhJZ:bta0o3i)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @elintul, @noaov1, and @zuphitf)



<!-- Sent from Reviewable.io -->

2023-11-02 08:23 UTC, dorimedini-starkware reviewed
[here](https://reviewable.io/reviews/starkware-industries/starkware/32347)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-:-NiE1Y0v97RhmTZmClvX:b-2zlnkq)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @elintul, @giladchase, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 269 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni5UnHH5-e9QVW6xInS:-NiE1fI1-Hs1733B6SpP:b-9otcf6) ([raw file](https://github.com/starkware-libs/blockifier/blob/eeeb2a76992ae8c2924396b1cdf2f74979b0e900/crates/blockifier/src/transaction/account_transaction.rs#L269)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

It's a struct containing `actual_cost` and `actual_resources`, which is currently only unpacked for those values and does nothing else (but arguably could be a good home for these methods than as static function on an AccountTransaction)

But regardless of ActualCost, i still think this is doing too much in one function and should be split.
Currently this function is in charge of:
1. deciding if a revert should be made, using two separate criteria, and calculated the required fee based on each case --- this is done twice for each of current/deprecated.
2. for each of the 4 state in (1) decide on:
    2.1 how much fee to charge
    2.2 what error message to generate.

Also, looking at the callsite, it looks liked the error message is the sole indicator that a revert was issued?
Perhaps we should encapsulate the error message and amended fee in a dedicated object?
</blockquote></details>

1. I am very much against splitting the function - you absolutely cannot perform the second check unless you first performed the first one. You need the first one to get one of the required inequalities that makes the second check correct.
2. I'll put it in the cost builder and use Error objects, see if you like?


<!-- Sent from Reviewable.io -->

2023-11-02 14:15 UTC, elintul reviewed
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045)* status: 1 of 4 files reviewed, 16 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @giladchase, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 83 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-NiFMNeD236nQhklpx_q:-NiFMNeE18HDvz65973Q:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1438648883b617f484d54ace96ddaa22feaa399c/crates/blockifier/src/fee/actual_cost.rs#L83)):*
> ```XML
> 
>     // Utility to check the actual cost can be paid by the account. If not, returns an error.
>     pub fn post_execution_cost_check<S: StateReader>(
> ```





_Suggestion:_
```XML
perform_post_execution_cost_check
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 86 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-NiFMRes9Lrl_T5I3geM:-NiFMRes9Lrl_T5I3geN:bvpjo6t) ([raw file](https://github.com/starkware-libs/blockifier/blob/1438648883b617f484d54ace96ddaa22feaa399c/crates/blockifier/src/fee/actual_cost.rs#L86)):*
> ```XML
>         block_context: &BlockContext,
>         account_tx_context: &AccountTransactionContext,
>         execution_state: &mut TransactionalState<'_, S>,
> ```

Move first, `mut` arguments are less likely to change location/be deleted from the signature.



_Code quote:_
```XML
execution_state: &mut TransactionalState<'_, S>,
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 96 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-NiFMne1DzjjamL5MMGB:-NiFMne1DzjjamL5MMGC:b-79zhf8) ([raw file](https://github.com/starkware-libs/blockifier/blob/1438648883b617f484d54ace96ddaa22feaa399c/crates/blockifier/src/fee/actual_cost.rs#L96)):*
> ```XML
>         // price(s). The sender is ensured to have sufficient balance to cover these costs due to
>         // pre-validation checks: deprecated transactions check balance covers max_fee, and current
>         // transactions check balance covers the max gas amount.
> ```

Out of scope, might become outdated.



_Suggestion:_
```XML
        // pre-validation checks.
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 98 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-NiFMtYLAfqukmYulvO4:-NiFMtYLAfqukmYulvO5:boird40) ([raw file](https://github.com/starkware-libs/blockifier/blob/1438648883b617f484d54ace96ddaa22feaa399c/crates/blockifier/src/fee/actual_cost.rs#L98)):*
> ```XML
>         // transactions check balance covers the max gas amount.
>         match account_tx_context {
>             AccountTransactionContext::Deprecated(deprecated_context) => {
> ```

I think they can both be named `context`.



_Suggestion:_
```XML
context
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 114 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-NiFN0eADCBrWQy_bDIC:-NiFN0eADCBrWQy_bDID:b-3kp9ua) ([raw file](https://github.com/starkware-libs/blockifier/blob/1438648883b617f484d54ace96ddaa22feaa399c/crates/blockifier/src/fee/actual_cost.rs#L114)):*
> ```XML
>                     .l1_resource_bounds()
>                     .expect("L1 gas bounds must be set.")
>                     .max_amount as u128;
> ```

Consider a getter, if repeated more than twice?



_Code quote:_
```XML
                let max_l1_gas = current_context
                    .l1_resource_bounds()
                    .expect("L1 gas bounds must be set.")
                    .max_amount as u128;
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 115 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-NiFNCb6DvDkggqfRbGK:-NiFNCb6DvDkggqfRbGL:b-91ny3x) ([raw file](https://github.com/starkware-libs/blockifier/blob/1438648883b617f484d54ace96ddaa22feaa399c/crates/blockifier/src/fee/actual_cost.rs#L115)):*
> ```XML
>                     .expect("L1 gas bounds must be set.")
>                     .max_amount as u128;
>                 let l1_gas_usage =
> ```

For symmetry and to comply with other locations in the code.



_Suggestion:_
```XML
actual_used_l1_gas
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 125 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-NiFNOcq-Dt024FlqdF-:-NiFNOcq-Dt024FlqdF0:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1438648883b617f484d54ace96ddaa22feaa399c/crates/blockifier/src/fee/actual_cost.rs#L125)):*
> ```XML
>                         ),
>                         reason: format!(
>                             "Insufficient max L1 gas: max amount: {:?}, actual: {:?}.",
> ```





_Suggestion:_
```XML
actual used
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 66 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-NiFNTudBg4WDl5JMxaw:-NiFNTue1DXDnlYjticL:b8nleu1) ([raw file](https://github.com/starkware-libs/blockifier/blob/1438648883b617f484d54ace96ddaa22feaa399c/crates/blockifier/src/fee/fee_utils.rs#L66)):*
> ```XML
> }
> 
> pub fn fee_by_l1_gas_usage(
> ```

Is this the naming convention for such converters? WDYT of adding `get_`?



_Code quote:_
```XML
fee_by_l1_gas_usage
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 82 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-NiFNcHh0LepVpMISXZp:-NiFNcHh0LepVpMISXZq:b-g4klb4) ([raw file](https://github.com/starkware-libs/blockifier/blob/1438648883b617f484d54ace96ddaa22feaa399c/crates/blockifier/src/fee/fee_utils.rs#L82)):*
> ```XML
>     Ok(fee_by_l1_gas_usage(
>         block_context,
>         calculate_tx_l1_gas_usage(resources, block_context)?,
> ```

Define a variable, so it's easier to read.



_Code quote:_
```XML
calculate_tx_l1_gas_usage(resources, block_context)?
```


<!-- Sent from Reviewable.io -->

2023-11-02 14:22 UTC, elintul requested changes
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045)* status: 2 of 4 files reviewed, 19 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @giladchase, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 110 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-NiFOVGT71-ue8iMNfbv:-NiFOVGT71-ue8iMNfbw:b-a522v4) ([raw file](https://github.com/starkware-libs/blockifier/blob/1438648883b617f484d54ace96ddaa22feaa399c/crates/blockifier/src/fee/actual_cost.rs#L110)):*
> ```XML
>                 }
>             }
>             AccountTransactionContext::Current(current_context) => {
> ```

Move to be first.



_Code quote:_
```XML
AccountTransactionContext::Current(current_context)
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 381 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-NiFPIRcBfDxWWEmIQDE:-NiFPIRcBfDxWWEmIQDF:b-bim8vd) ([raw file](https://github.com/starkware-libs/blockifier/blob/1438648883b617f484d54ace96ddaa22feaa399c/crates/blockifier/src/transaction/account_transaction.rs#L381)):*
> ```XML
>             remaining_gas,
>         );
> ```

Very very very long function. Let's split it please.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 403 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-NiFPOBxEF_uEouj_u-V:-NiFPOBy20-5llWOxDdx:bo420p7) ([raw file](https://github.com/starkware-libs/blockifier/blob/1438648883b617f484d54ace96ddaa22feaa399c/crates/blockifier/src/transaction/account_transaction.rs#L403)):*
> ```XML
>                         &mut execution_state,
>                         &actual_cost,
>                     ),
> ```

Variable, please.
Maybe even a struct to couple both results together.
I find it hard to read this `match`.



_Code quote:_
```XML
                    ActualCostBuilder::post_execution_cost_check(
                        block_context,
                        &account_tx_context,
                        &mut execution_state,
                        &actual_cost,
                    ),
```


<!-- Sent from Reviewable.io -->

2023-11-02 14:34 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045)* status: 2 of 4 files reviewed, 8 unresolved discussions (waiting on @amosStarkware, @elintul, @giladchase, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 114 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-NiFN0eADCBrWQy_bDIC:-NiFQCUh6xB7IxfGRx3C:b-qkpsgh) ([raw file](https://github.com/starkware-libs/blockifier/blob/1438648883b617f484d54ace96ddaa22feaa399c/crates/blockifier/src/fee/actual_cost.rs#L114)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider a getter, if repeated more than twice?
</blockquote></details>

`ResourceBounds` is defined in SN-API, getter should be added there; out of scope for now.
We should, however, stop `expect`ing and start raising a missing resource error (creation of which is in PR I believe)
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 66 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-NiFNTudBg4WDl5JMxaw:-NiFQamK4Evgkai2BrJq:bb7oryy) ([raw file](https://github.com/starkware-libs/blockifier/blob/1438648883b617f484d54ace96ddaa22feaa399c/crates/blockifier/src/fee/fee_utils.rs#L66)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this the naming convention for such converters? WDYT of adding `get_`?
</blockquote></details>

sure
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 381 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-NiFPIRcBfDxWWEmIQDE:-NiFQsp89CRDYX5EOTo1:body0k4) ([raw file](https://github.com/starkware-libs/blockifier/blob/1438648883b617f484d54ace96ddaa22feaa399c/crates/blockifier/src/transaction/account_transaction.rs#L381)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Very very very long function. Let's split it please.
</blockquote></details>

This is after a split.
More logic is coming in: during removal of `max_fee()`.
Once this PR is in, we can consider moving logic into the cost builder and splitting out subroutines; these types of refactor are out of scope of this PR IMO
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 403 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-NiFPOBxEF_uEouj_u-V:-NiFS1kSDxdZO9nsNPZK:b8fic75) ([raw file](https://github.com/starkware-libs/blockifier/blob/1438648883b617f484d54ace96ddaa22feaa399c/crates/blockifier/src/transaction/account_transaction.rs#L403)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Variable, please.
Maybe even a struct to couple both results together.
I find it hard to read this `match`.
</blockquote></details>

moved `charge_fee` back into the post execution check, now `match` is nicer


<!-- Sent from Reviewable.io -->

2023-11-02 14:57 UTC, giladchase submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045)* status: 1 of 4 files reviewed, 8 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @elintul, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 285 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni5Iz4Q0BmjcOKqbH4M:-NiAaAtt5QmkZXXZqBto:b-c4sc1f) ([raw file](https://github.com/starkware-libs/blockifier/blob/eeeb2a76992ae8c2924396b1cdf2f74979b0e900/crates/blockifier/src/transaction/account_transaction.rs#L285)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done (split the comment, good enough?)
</blockquote></details>

I don't see the split?


<!-- Sent from Reviewable.io -->

2023-11-02 15:00 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @elintul, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 285 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Ni5Iz4Q0BmjcOKqbH4M:-NiFXkWK4MiIBONtSIcW:byw6o0x) ([raw file](https://github.com/starkware-libs/blockifier/blob/eeeb2a76992ae8c2924396b1cdf2f74979b0e900/crates/blockifier/src/transaction/account_transaction.rs#L285)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I don't see the split?
</blockquote></details>

the `can_pay_fee` part was split; the doc above the `match` documents both arms, I don't want to copy-paste.
I'll add inline clarifications.


<!-- Sent from Reviewable.io -->

2023-11-02 15:11 UTC, elintul reviewed
> Reviewed 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 130 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-NiF_aum2WRn6bjz2Emb:-NiF_aum2WRn6bjz2Emc:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b8f619db3d85a135b3a7c8684546b10d0313f2d9/crates/blockifier/src/fee/actual_cost.rs#L130)):*
> ```XML
>                         final_fee: max_fee,
>                         reason: format!(
>                             "Insufficient max fee: max_fee: {max_fee:?}, actual_fee: \
> ```





_Suggestion:_
```XML
max fee: {max_fee:?}, actual fee
```


<!-- Sent from Reviewable.io -->

2023-11-02 15:31 UTC, noaov1 approved these changes
> Reviewed 1 of 3 files at r5, 2 of 3 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @elintul, and @zuphitf)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Nhv87pR5qGWxkN1b9bl:-NiFdLZ38R_l-OcgEu4D:b-17ad4b) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

No; it needs fixing as [part of the effort](https://reviewable.io/reviews/starkware-libs/blockifier/1044) to remove the `max_fee()` getter.
Once 1044 is in I'll search for remaining usages of `max_fee()` and remove + fix them
</blockquote></details>

Got it. Why do we check this twice then? 

___


<!-- Sent from Reviewable.io -->

2023-11-02 15:33 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @elintul, and @zuphitf)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Nhv87pR5qGWxkN1b9bl:-NiFeb9f1zuuBGKPLSCb:bwfde8a) (no related file):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Got it. Why do we check this twice then?
</blockquote></details>

Not resolved

___


<!-- Sent from Reviewable.io -->

2023-11-02 15:38 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @elintul, @noaov1, and @zuphitf)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-Nhv87pR5qGWxkN1b9bl:-NiFfZn07v6pj-gxCQIx:b-l5pg0r) (no related file):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Not resolved
</blockquote></details>

It is for the non-revertible flow, but it is not yet up-to-date with v3 anyway.
This PR is for *revertible* post-execution

___


<!-- Sent from Reviewable.io -->

2023-11-02 15:39 UTC, noaov1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @elintul, and @zuphitf)



<!-- Sent from Reviewable.io -->

2023-11-05 17:27 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1045)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @elintul, and @zuphitf)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1045#-NiVWabqAjB2RCuVvtjq:-NiVWabrB28A9IfrccCq:b-rf829w) (no related file):*
Closed in favor of [this](https://reviewable.io/reviews/starkware-libs/blockifier/1084)

___


<!-- Sent from Reviewable.io -->

2023-11-05 17:27 UTC, closed without merging