Test resource overdraft
starkware-libs/blockifier pull request #1049
Opened 2023-10-28 20:04 UTC by dorimedini-starkware

2023-11-01 10:01 UTC, giladchase submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1208 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Ni8xmyd4OBXpVN9FFh6:-Ni8xmyd4OBXpVN9FFh7:b-losqn7) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1206ff08dfb1e866c2a906e06acc426b1e440b9/crates/blockifier/src/transaction/account_transactions_test.rs#L1208)):*
> ```XML
> #[case(TransactionVersion::ONE)]
> #[case(TransactionVersion::THREE)]
> fn test_revert_on_resources_overdraft(
> ```

Should `test_revert_on_overdraft` be deleted? Or are they testing different things? If they do then one should be renamed



_Code quote:_
```XML
#[case(TransactionVersion::ONE)]
#[case(TransactionVersion::THREE)]
fn test_revert_on_resources_overdraft(
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1221 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Ni8dODaDZ9Twd9XHRth:-Ni8dODb0F_tOGko73yF:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1206ff08dfb1e866c2a906e06acc426b1e440b9/crates/blockifier/src/transaction/account_transactions_test.rs#L1221)):*
> ```XML
>         mut nonce_manager,
>         block_context,
>     } = create_test_init_data(Fee(MAX_FEE), block_context, state);
> ```





_Suggestion:_
```XML
max_fee
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1249 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Ni98ECc97ozucv9xGYq:-Ni98ECc97ozucv9xGYr:bmczazr) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1206ff08dfb1e866c2a906e06acc426b1e440b9/crates/blockifier/src/transaction/account_transactions_test.rs#L1249)):*
> ```XML
>     // Prepare resources bounds slightly lower than the actual fee / resources.
>     let max_fee = Fee(execution_info_0.actual_fee.0 - 1);
>     max_resource_bounds.0.insert(
> ```

Does this overrides the only key-value stored inside `max_resource_bounds`? (for the key L1Gas)
If it is, better to define a new instance using `l1_resource_bounds()`



_Code quote:_
```XML
max_resource_bounds.0.insert(
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1257 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Ni99rSuDnSaOAf89hBv:-Ni99rSuDnSaOAf89hBw:b-fgcdz8) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1206ff08dfb1e866c2a906e06acc426b1e440b9/crates/blockifier/src/transaction/account_transactions_test.rs#L1257)):*
> ```XML
>             )
>             .unwrap() as u64
>                 - 1,
> ```

Do we need both this to be decremented and the max_fee? I'm not sure i understand why both need to be changed :thinking: 

Also, i think putting -1 implies tightness, and IIUC this isn't tight: i tried removing both -1 (or even add ~100 to either one) it remains green.
It only gets red when max_amount is increased by somewhere between 1000 to 10000.



_Code quote:_
```XML
            max_amount: calculate_tx_l1_gas_usage(
                &execution_info_0.actual_resources,
                &block_context,
            )
            .unwrap() as u64
                - 1,
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1291 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Ni9JxQkBpNmIT2arTeE:-Ni9JxQkBpNmIT2arTeF:bmx9efq) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1206ff08dfb1e866c2a906e06acc426b1e440b9/crates/blockifier/src/transaction/account_transactions_test.rs#L1291)):*
> ```XML
>             "Insufficient max L1 gas"
>         }
>     ));
> ```

Can you remind me plz why errors must be passed as string in this way and not via error objects?



_Code quote:_
```XML
    assert!(execution_info_1.revert_error.unwrap().starts_with(
        if version < TransactionVersion::THREE {
            "Insufficient max fee"
        } else {
            "Insufficient max L1 gas"
        }
    ));
```


<!-- Sent from Reviewable.io -->

2023-11-01 10:13 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @giladchase, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1208 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Ni8xmyd4OBXpVN9FFh6:-Ni9LWQz8y7cBBpOPuXE:b-a8ed2i) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1206ff08dfb1e866c2a906e06acc426b1e440b9/crates/blockifier/src/transaction/account_transactions_test.rs#L1208)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Should `test_revert_on_overdraft` be deleted? Or are they testing different things? If they do then one should be renamed
</blockquote></details>

They test different things, I'll rename...
1. `test_revert_on_overdraft` checks that txs are reverted *if we transfer out all the balance from the account before paying the fee*.
2. This new test tests that txs are reverted if the actual amount / actual fee ends up greater than the max amount / max fee.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1221 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Ni8dODaDZ9Twd9XHRth:-Ni9Lmvs3k5qyfJQ3IRy:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1206ff08dfb1e866c2a906e06acc426b1e440b9/crates/blockifier/src/transaction/account_transactions_test.rs#L1221)):*
> ```XML
>         mut nonce_manager,
>         block_context,
>     } = create_test_init_data(Fee(MAX_FEE), block_context, state);
> ```

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1249 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Ni98ECc97ozucv9xGYq:-Ni9M7tN3Uefg6qyc4HZ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1206ff08dfb1e866c2a906e06acc426b1e440b9/crates/blockifier/src/transaction/account_transactions_test.rs#L1249)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Does this overrides the only key-value stored inside `max_resource_bounds`? (for the key L1Gas)
If it is, better to define a new instance using `l1_resource_bounds()`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1257 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Ni99rSuDnSaOAf89hBv:-Ni9MEdm6loS7771hSHm:b-v1386m) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1206ff08dfb1e866c2a906e06acc426b1e440b9/crates/blockifier/src/transaction/account_transactions_test.rs#L1257)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Do we need both this to be decremented and the max_fee? I'm not sure i understand why both need to be changed :thinking: 

Also, i think putting -1 implies tightness, and IIUC this isn't tight: i tried removing both -1 (or even add ~100 to either one) it remains green.
It only gets red when max_amount is increased by somewhere between 1000 to 10000.
</blockquote></details>

1. we need max_fee if version=1 and resource_bounds if version=3. we need to pass both to invoke_tx_args to get the behavior we want for each version.
2. I don't understand the question: we need the resource bounds to be below the actual bounds used, doesn't really matter by how much, BUT if we give upper bounds that are *too* small, *we will revert on RunResources out of steps*, and not even reach the post-execution area.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1291 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Ni9JxQkBpNmIT2arTeE:-Ni9MfX76XJdeZxOuCPD:b-hw1ipo) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1206ff08dfb1e866c2a906e06acc426b1e440b9/crates/blockifier/src/transaction/account_transactions_test.rs#L1291)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can you remind me plz why errors must be passed as string in this way and not via error objects?
</blockquote></details>

TransactionExecutionInfo defines `revert_error: Option<String>`.
This is the error for REVERTed txs.
We return (rusty) errors in execution when we REJECT a tx.


<!-- Sent from Reviewable.io -->

2023-11-01 18:30 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1257 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Ni99rSuDnSaOAf89hBv:-NiB-7Kl2aS74ZFUNJQY:btgwsd4) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1206ff08dfb1e866c2a906e06acc426b1e440b9/crates/blockifier/src/transaction/account_transactions_test.rs#L1257)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. we need max_fee if version=1 and resource_bounds if version=3. we need to pass both to invoke_tx_args to get the behavior we want for each version.
2. I don't understand the question: we need the resource bounds to be below the actual bounds used, doesn't really matter by how much, BUT if we give upper bounds that are *too* small, *we will revert on RunResources out of steps*, and not even reach the post-execution area.
</blockquote></details>

I see, in that case, let's put that decrement behind an if-else on the version?

I realize that run_invoke/invoke_tx_args! ignores the unused one, but since this is point is the crux of the test, i think it should be free of implementation details.
In other words, if we change invoke_tx_args's implementation, this should influence the core logic of the tests, only their setup.

Regarding the tightness, i think there's something i'm missing here...
Let's assume version is 1 WLOG.
AFAICS, i can change:
```
    // Prepare resources bounds slightly lower than the actual fee / resources.
    let max_fee = Fee(execution_info_0.actual_fee.0 - 1);
```
into 
```
    // Prepare resources bounds slightly lower than the actual fee / resources.
    let max_fee = Fee(execution_info_0.actual_fee.0);
```
and the test still passes.
The comment (IMO) implies that this -1 was why the subsequent assert worked out, which doesn't seem to be the case.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1291 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Ni9JxQkBpNmIT2arTeE:-NiAzcZE-Ep-hTcyziFT:b-5q4tsn) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1206ff08dfb1e866c2a906e06acc426b1e440b9/crates/blockifier/src/transaction/account_transactions_test.rs#L1291)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

TransactionExecutionInfo defines `revert_error: Option<String>`.
This is the error for REVERTed txs.
We return (rusty) errors in execution when we REJECT a tx.
</blockquote></details>

Yes yes, but can't we return rusty errors for both? just a different variant of a more general error?


<!-- Sent from Reviewable.io -->

2023-11-02 08:57 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @giladchase, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1257 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Ni99rSuDnSaOAf89hBv:-NiEDzvsCN8IpTLp6CR6:bny9xvh) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1206ff08dfb1e866c2a906e06acc426b1e440b9/crates/blockifier/src/transaction/account_transactions_test.rs#L1257)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I see, in that case, let's put that decrement behind an if-else on the version?

I realize that run_invoke/invoke_tx_args! ignores the unused one, but since this is point is the crux of the test, i think it should be free of implementation details.
In other words, if we change invoke_tx_args's implementation, this should influence the core logic of the tests, only their setup.

Regarding the tightness, i think there's something i'm missing here...
Let's assume version is 1 WLOG.
AFAICS, i can change:
```
    // Prepare resources bounds slightly lower than the actual fee / resources.
    let max_fee = Fee(execution_info_0.actual_fee.0 - 1);
```
into 
```
    // Prepare resources bounds slightly lower than the actual fee / resources.
    let max_fee = Fee(execution_info_0.actual_fee.0);
```
and the test still passes.
The comment (IMO) implies that this -1 was why the subsequent assert worked out, which doesn't seem to be the case.
</blockquote></details>

I disagree about the if-else - we'll need to pass *some* max_fee to InvokeTxArgs, even in the V3 case; the hidden bugs you may get when you only change the resource bounds in V3 and keep default max fee, are probably harder to find.
It also makes the code very annoying to read - better to separate V1 and V3 tests altogether.

About the tight bounds - not only can I not reproduce this, I added a test case for it.
If bounds are exactly tight, the execution does not revert; if I decrement one from each bound, execution reverts.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1291 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Ni9JxQkBpNmIT2arTeE:-NiEEkKM7v7b69CIeuZa:b-q22no2) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1206ff08dfb1e866c2a906e06acc426b1e440b9/crates/blockifier/src/transaction/account_transactions_test.rs#L1291)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Yes yes, but can't we return rusty errors for both? just a different variant of a more general error?
</blockquote></details>

I only have the `TransactionExecutionInfo` object to work with here..
Current design has string-based error message on revert.
I like the idea of rusty error and nice trace on revert, but this is not a small feature, and out of scope of this PR anyway


<!-- Sent from Reviewable.io -->

2023-11-05 12:32 UTC, elintul requested changes
> Reviewed 2 of 3 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @giladchase, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1189 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-NiUSdDn196SVbyxQrJP:-NiUSdDn196SVbyxQrJQ:bpw3v48) ([raw file](https://github.com/starkware-libs/blockifier/blob/3366c51eac12dde3efbf3e81c5753f5d7afb10b1/crates/blockifier/src/transaction/account_transactions_test.rs#L1189)):*
> ```XML
> }
> 
> /// Tests that when a transaction requires more resources than the sender allowed, the execution is
> ```

How do you create the exact conditions for every check?



_Suggestion:_
```XML
sender is allowed
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1198 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-NiUS0b44ig1atg4AtRH:-NiUS0b44ig1atg4AtRI:burpbvk) ([raw file](https://github.com/starkware-libs/blockifier/blob/3366c51eac12dde3efbf3e81c5753f5d7afb10b1/crates/blockifier/src/transaction/account_transactions_test.rs#L1198)):*
> ```XML
>     max_resource_bounds: ResourceBoundsMapping,
>     block_context: BlockContext,
>     #[from(create_state)] state: CachedState<DictStateReader>,
> ```

What does this line mean?



_Code quote:_
```XML
#[from(create_state)] state: CachedState<DictStateReader>,
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1215 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-NiUSDMe1MN4kSg9HvSv:-NiUSDMe1MN4kSg9HvSw:bm61n12) ([raw file](https://github.com/starkware-libs/blockifier/blob/3366c51eac12dde3efbf3e81c5753f5d7afb10b1/crates/blockifier/src/transaction/account_transactions_test.rs#L1215)):*
> ```XML
>     // Every call bumps the start address by `n_writes`, so each call writes to new storage slots.
>     let mut write_a_lot_start_address = 0_u16;
>     let mut write_a_lot_calldata = || {
> ```

Why a function and not a variable? Ownership issues?



_Code quote:_
```XML
||
```


<!-- Sent from Reviewable.io -->

2023-11-05 16:14 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @elintul, @giladchase, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1189 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-NiUSdDn196SVbyxQrJP:-NiVDvToA70_Ehpbqqhd:b-oe39gr) ([raw file](https://github.com/starkware-libs/blockifier/blob/3366c51eac12dde3efbf3e81c5753f5d7afb10b1/crates/blockifier/src/transaction/account_transactions_test.rs#L1189)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How do you create the exact conditions for every check?
</blockquote></details>

1. The text is correct, though maybe unclear: I want to say "how much the sender allows the blockifier to use", not "how much the sender is allowed to use". Rephrased, see if you like
2. Run the same specific heavy transaction 3 times: (a) measure the resources consumed; (b) assert that when the resources are exactly equal, tx does not revert; (c) assert that when the sender bounds are slightly below the actual used resources, we get the correct resource-overuse error.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1198 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-NiUS0b44ig1atg4AtRH:-NiVFH2d81p3K58cbvJW:b-izwigr) ([raw file](https://github.com/starkware-libs/blockifier/blob/3366c51eac12dde3efbf3e81c5753f5d7afb10b1/crates/blockifier/src/transaction/account_transactions_test.rs#L1198)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What does this line mean?
</blockquote></details>

The fixture is called `create_state`.
We can either do:
```
create_state: CachedState<DictStateReader>,
```
in which case we'd have a strange parameter name, or we can do:
```
#[from(create_state)] state: CachedState<DictStateReader>,
```
to use, and rename, the result of the fixture
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1215 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-NiUSDMe1MN4kSg9HvSv:-NiVFZwE4gDY4f3LBTvx:baxr2l4) ([raw file](https://github.com/starkware-libs/blockifier/blob/3366c51eac12dde3efbf3e81c5753f5d7afb10b1/crates/blockifier/src/transaction/account_transactions_test.rs#L1215)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why a function and not a variable? Ownership issues?
</blockquote></details>

because I want to do
```
write_a_lot_start_address += n_writes
```
on every call.
not sure this is necessary; I just wanted all writes to be in unused storage slots, so the same resources are used on each invocation.
You think it's unecessary?


<!-- Sent from Reviewable.io -->

2023-11-07 13:11 UTC, elintul reviewed
> Reviewed 3 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: 3 of 8 files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @giladchase, @noaov1, and @zuphitf)



<!-- Sent from Reviewable.io -->

2023-11-21 12:41 UTC, noaov1 reviewed
> Reviewed 1 of 8 files at r5, 5 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @elintul, and @zuphitf)

___
*[`crates/blockifier/feature_contracts/cairo0/test_contract.cairo` line 87 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Njlt8hr4woTTDx7qzI8:-Njlt8hr4woTTDx7qzI9:bsmsjzu) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c678d59e0a02b609e12797696d967a4c24eb36b/crates/blockifier/feature_contracts/cairo0/test_contract.cairo#L87)):*
> ```Cairo
> 
> @external
> func write_a_lot{syscall_ptr: felt*}(n_writes: felt, start_address: felt) {
> ```

Can you please explain this method?
Why do you set `address = start_address + n_writes`?
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1215 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-NiUSDMe1MN4kSg9HvSv:-NjltYKu2H2S4NHycU99:b-3fhx1c) ([raw file](https://github.com/starkware-libs/blockifier/blob/3366c51eac12dde3efbf3e81c5753f5d7afb10b1/crates/blockifier/src/transaction/account_transactions_test.rs#L1215)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

because I want to do
```
write_a_lot_start_address += n_writes
```
on every call.
not sure this is necessary; I just wanted all writes to be in unused storage slots, so the same resources are used on each invocation.
You think it's unecessary?
</blockquote></details>

I think that it's enough that you write different values.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1327 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-NjlqinP-vQRhA9P1URu:-NjlqinP-vQRhA9P1URv:b-9fh7uf) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c678d59e0a02b609e12797696d967a4c24eb36b/crates/blockifier/src/transaction/account_transactions_test.rs#L1327)):*
> ```XML
> /// execution is reverted; in the non-revertible case, checks for the correct error.
> #[rstest]
> #[case(TransactionVersion::ZERO, "DUMMY", false)]
> ```

Less confusing IMO



_Suggestion:_
```XML
#[case(TransactionVersion::ZERO, "", false)]
```


<!-- Sent from Reviewable.io -->

2023-11-21 13:18 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @elintul, @noaov1, and @zuphitf)

___
*[`crates/blockifier/feature_contracts/cairo0/test_contract.cairo` line 87 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Njlt8hr4woTTDx7qzI8:-NjlyB6UA85jNDxkzIyA:byrq2m7) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c678d59e0a02b609e12797696d967a4c24eb36b/crates/blockifier/feature_contracts/cairo0/test_contract.cairo#L87)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain this method?
Why do you set `address = start_address + n_writes`?
</blockquote></details>

see below
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1215 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-NiUSDMe1MN4kSg9HvSv:-Njm0Kb1DPVoVjPLalqv:b8h2dlw) ([raw file](https://github.com/starkware-libs/blockifier/blob/3366c51eac12dde3efbf3e81c5753f5d7afb10b1/crates/blockifier/src/transaction/account_transactions_test.rs#L1215)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think that it's enough that you write different values.
</blockquote></details>

Tried changing `write_a_lot` to
```
@external
func write_a_lot{syscall_ptr: felt*}(n_writes: felt, value: felt) {
    if (n_writes == 0) {
        return ();
    }
    storage_write(address=n_writes, value=value);
    return write_a_lot(n_writes - 1, value);
}
```
and calling with `value=1` first, then `value=2` (both with `n_writes=100`).
second call is more expensive than the first now:
```
thread 'transaction::account_transaction::test::test_revert_on_resource_overuse::case_1' panicked at crates/blockifier/src/transaction/account_transactions_test.rs:1394:6:
called `Result::unwrap()` on an `Err` value: FeeCheckError(MaxFeeExceeded { max_fee: Fee(13385300000000000), actual_fee: Fee(13507700000000000) })
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1327 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-NjlqinP-vQRhA9P1URu:-Njm-EmK6QpEBsi6Lj_F:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c678d59e0a02b609e12797696d967a4c24eb36b/crates/blockifier/src/transaction/account_transactions_test.rs#L1327)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Less confusing IMO
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-21 13:52 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @elintul, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1215 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-NiUSDMe1MN4kSg9HvSv:-Njm8CS_3RhSzXQWXqMk:b97mxfz) ([raw file](https://github.com/starkware-libs/blockifier/blob/3366c51eac12dde3efbf3e81c5753f5d7afb10b1/crates/blockifier/src/transaction/account_transactions_test.rs#L1215)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Tried changing `write_a_lot` to
```
@external
func write_a_lot{syscall_ptr: felt*}(n_writes: felt, value: felt) {
    if (n_writes == 0) {
        return ();
    }
    storage_write(address=n_writes, value=value);
    return write_a_lot(n_writes - 1, value);
}
```
and calling with `value=1` first, then `value=2` (both with `n_writes=100`).
second call is more expensive than the first now:
```
thread 'transaction::account_transaction::test::test_revert_on_resource_overuse::case_1' panicked at crates/blockifier/src/transaction/account_transactions_test.rs:1394:6:
called `Result::unwrap()` on an `Err` value: FeeCheckError(MaxFeeExceeded { max_fee: Fee(13385300000000000), actual_fee: Fee(13507700000000000) })
```
</blockquote></details>

Now you simply writes `n_writes` times to the same `address`, no?
I'm not sure thought why writing `2` is more expensive. 


<!-- Sent from Reviewable.io -->

2023-11-21 14:18 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @elintul, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1215 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-NiUSDMe1MN4kSg9HvSv:-NjmEZN83zeEiC1TDZ4q:b-z1wyal) ([raw file](https://github.com/starkware-libs/blockifier/blob/3366c51eac12dde3efbf3e81c5753f5d7afb10b1/crates/blockifier/src/transaction/account_transactions_test.rs#L1215)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Now you simply writes `n_writes` times to the same `address`, no?
I'm not sure thought why writing `2` is more expensive.
</blockquote></details>

no, I write to different addresses: 100, 99, 98, ...
```
    storage_write(address=n_writes, value=value);
    return write_a_lot(n_writes - 1, value);
```


<!-- Sent from Reviewable.io -->

2023-11-22 09:02 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @elintul, @noaov1, and @zuphitf)

___
*[`crates/blockifier/feature_contracts/cairo0/test_contract.cairo` line 87 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Njlt8hr4woTTDx7qzI8:-NjqFwI816-31MsFZMHu:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c678d59e0a02b609e12797696d967a4c24eb36b/crates/blockifier/feature_contracts/cairo0/test_contract.cairo#L87)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see below
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-22 11:05 UTC, noaov1 approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @elintul, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1215 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-NiUSDMe1MN4kSg9HvSv:-NjmFUXy1YAS4QOQO__5:b-yi1m4s) ([raw file](https://github.com/starkware-libs/blockifier/blob/3366c51eac12dde3efbf3e81c5753f5d7afb10b1/crates/blockifier/src/transaction/account_transactions_test.rs#L1215)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no, I write to different addresses: 100, 99, 98, ...
```
    storage_write(address=n_writes, value=value);
    return write_a_lot(n_writes - 1, value);
```
</blockquote></details>

Sorry, I missed that change. Discussed offline: There is a problem with the value `1`. It is already written in some storage cell in the contract.


<!-- Sent from Reviewable.io -->

2023-11-22 11:29 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @elintul, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1215 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-NiUSDMe1MN4kSg9HvSv:-NjqmkcL2Ol6dIxTDkTc:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/3366c51eac12dde3efbf3e81c5753f5d7afb10b1/crates/blockifier/src/transaction/account_transactions_test.rs#L1215)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Sorry, I missed that change. Discussed offline: There is a problem with the value `1`. It is already written in some storage cell in the contract.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-22 11:44 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @elintul, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1351 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Njqp1SjERrEP6u7iwNJ:-Njqp1SjERrEP6u7iwNK:b-8d3s5o) ([raw file](https://github.com/starkware-libs/blockifier/blob/4bf97a7a2f8238f38e4480aa1ca003094f9a4bce/crates/blockifier/src/transaction/account_transactions_test.rs#L1351)):*
> ```XML
> 
>     // Utility function to generate calldata for the `write_a_lot` function.
>     // Every call bumps the start address by `n_writes`, so each call writes to new storage slots.
> ```

Still true?



_Code quote:_
```XML
    // Every call bumps the start address by `n_writes`, so each call writes to new storage slots.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1360 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Njqphbz7yQSKuCD8po_:-Njqphc-3tfrGAUG8FDS:b-b4mddq) ([raw file](https://github.com/starkware-libs/blockifier/blob/4bf97a7a2f8238f38e4480aa1ca003094f9a4bce/crates/blockifier/src/transaction/account_transactions_test.rs#L1360)):*
> ```XML
>     };
> 
>     // Run a "heavy" transaction and measure the resources used.
> ```

Out of curiosity- why did you need it to be a "heavy" transaction?



_Code quote:_
```XML
    // Run a "heavy" transaction and measure the resources used.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1381 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-NjqpEBD5shHLb_cmfby:-NjqpEBE4ImgDqnt9sle:becxl5t) ([raw file](https://github.com/starkware-libs/blockifier/blob/4bf97a7a2f8238f38e4480aa1ca003094f9a4bce/crates/blockifier/src/transaction/account_transactions_test.rs#L1381)):*
> ```XML
>     .unwrap() as u64;
> 
>     // Run the same function, writing to a new address space (to keep cost high), with the actual
> ```

Please update.
Same below.



_Code quote:_
```XML
    // Run the same function, writing to a new address space (to keep cost high), with the actual
```


<!-- Sent from Reviewable.io -->

2023-11-22 12:22 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware, @elintul, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1351 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Njqp1SjERrEP6u7iwNJ:-NjqyWUl50lhNNe-a623:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4bf97a7a2f8238f38e4480aa1ca003094f9a4bce/crates/blockifier/src/transaction/account_transactions_test.rs#L1351)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Still true?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1360 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Njqphbz7yQSKuCD8po_:-NjqxVxr2XZhWNSKiapq:byrrjsr) ([raw file](https://github.com/starkware-libs/blockifier/blob/4bf97a7a2f8238f38e4480aa1ca003094f9a4bce/crates/blockifier/src/transaction/account_transactions_test.rs#L1360)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Out of curiosity- why did you need it to be a "heavy" transaction?
</blockquote></details>

I want to test the case where
1. Execution completes successfully
2. Post-execution fails due to `actual > bound`
If only (2) was required, then we could just set max_fee = 1 or (something low enough to pass pre-validation checks).
However, the resource bounds *also limit the execution steps*, so if we want (1), we need to invoke a function that is (a) "heavy" on the resource (L1 gas) cost and (b) "light" in cairo steps (so it's not stopped mid-execution).
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1381 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-NjqpEBD5shHLb_cmfby:-NjqyEYH4dSMATQgqBwA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4bf97a7a2f8238f38e4480aa1ca003094f9a4bce/crates/blockifier/src/transaction/account_transactions_test.rs#L1381)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please update.
Same below.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-22 13:42 UTC, noaov1 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, @elintul, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1360 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Njqphbz7yQSKuCD8po_:-NjrFIlYAu3H7x447rYE:bmkd16x) ([raw file](https://github.com/starkware-libs/blockifier/blob/4bf97a7a2f8238f38e4480aa1ca003094f9a4bce/crates/blockifier/src/transaction/account_transactions_test.rs#L1360)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I want to test the case where
1. Execution completes successfully
2. Post-execution fails due to `actual > bound`
If only (2) was required, then we could just set max_fee = 1 or (something low enough to pass pre-validation checks).
However, the resource bounds *also limit the execution steps*, so if we want (1), we need to invoke a function that is (a) "heavy" on the resource (L1 gas) cost and (b) "light" in cairo steps (so it's not stopped mid-execution).
</blockquote></details>

Isn't it enough to have only 5 storage writes? "Heavy" means a lot of storage updates?  
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1401 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Njr6YLo-dUayxYsOogI:-Njr6YLo-dUayxYsOogJ:b4iievy) ([raw file](https://github.com/starkware-libs/blockifier/blob/e4cdf3b4a15acbc8cfb604bc19d52de0eaaf3ef9/crates/blockifier/src/transaction/account_transactions_test.rs#L1401)):*
> ```XML
>     assert_eq!(execution_info_tight.actual_resources, execution_info_measure.actual_resources);
> 
>     // Re-run the same function, writing to a new address space (to keep cost high).
> ```

Update? :)



_Code quote:_
```XML
   // Re-run the same function, writing to a new address space (to keep cost high).
```


<!-- Sent from Reviewable.io -->

2023-11-22 14:07 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @elintul, @noaov1, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1360 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Njqphbz7yQSKuCD8po_:-NjrLo3b2C10xcOMfeEW:b-tjr4ye) ([raw file](https://github.com/starkware-libs/blockifier/blob/4bf97a7a2f8238f38e4480aa1ca003094f9a4bce/crates/blockifier/src/transaction/account_transactions_test.rs#L1360)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Isn't it enough to have only 5 storage writes? "Heavy" means a lot of storage updates?
</blockquote></details>

5 works as well, done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1401 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Njr6YLo-dUayxYsOogI:-NjrLvFQ8xNcu0Hmw-MV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e4cdf3b4a15acbc8cfb604bc19d52de0eaaf3ef9/crates/blockifier/src/transaction/account_transactions_test.rs#L1401)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Update? :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-22 14:10 UTC, noaov1 submitted a review, later dismissed
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @amosStarkware, @elintul, and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1360 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1049#-Njqphbz7yQSKuCD8po_:-NjrMEpOBPmCsYzs686C:bygjqee) ([raw file](https://github.com/starkware-libs/blockifier/blob/4bf97a7a2f8238f38e4480aa1ca003094f9a4bce/crates/blockifier/src/transaction/account_transactions_test.rs#L1360)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

5 works as well, done.
</blockquote></details>

Add to doc the meaning of heavy?


<!-- Sent from Reviewable.io -->

2023-11-22 14:21 UTC, noaov1 approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @elintul, and @zuphitf)



<!-- Sent from Reviewable.io -->

2023-11-22 14:48 UTC, elintul reviewed
> Reviewed 4 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @zuphitf)



<!-- Sent from Reviewable.io -->

2023-11-22 14:58 UTC, elintul approved these changes
> Reviewed 5 of 6 files at r8, 2 of 3 files at r9, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1049)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @zuphitf)



<!-- Sent from Reviewable.io -->

2023-11-22 14:58 UTC, merged