Add pre-validation fee checks.
starkware-libs/blockifier pull request #1060
Opened 2023-10-30 12:27 UTC by amosStarkware

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1060)

2023-10-30 18:06 UTC, dorimedini-starkware requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0ISR01npMhylOA4QG:-Ni0ISR01npMhylOA4QH:bsfoftx) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/account_transaction.rs#L167)):*
> ```XML
>     ) -> TransactionExecutionResult<()> {
>         match account_tx_context.max_l1_gas_price() {
>             Some(Fee(max_l1_gas_price)) => {
> ```

Use new context directly, no fetching "max L1 gas price" on deprecated objects (see comment below)



_Suggestion:_
```XML
        if let AccountTransactionContext::Current(current_ctx) = account_tx_context {
            let max_l1_gas_price = current_ctx.get_l1_gas_bounds().max_price_per_unit;
            ...
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 403 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0K87x3us3PSNTfvgH:-Ni0K87x3us3PSNTfvgI:b-kktxn6) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/account_transactions_test.rs#L403)):*
> ```XML
>         version: tx_version,
>         nonce: nonce_manager.next(account_address),
>         resource_bounds: ResourceBoundsMapping(BTreeMap::from([
> ```

why is this computation necessary? why not take max resource bounds?
if default max resource bounds aren't defined yet, maybe steal them from [here](https://reviewable.io/reviews/starkware-libs/blockifier/1048) (see changes to `utils` and `test_utils` modules)
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 407 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0JpFqEL3Cdbv507Na:-Ni0JpFqEL3Cdbv507Nb:b-btejge) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/account_transactions_test.rs#L407)):*
> ```XML
>                 max_amount: (max_fee.0 / DEFAULT_STRK_L1_GAS_PRICE) as u64,
>                 max_price_per_unit: DEFAULT_STRK_L1_GAS_PRICE }),
>         ])),
> ```

see [this](https://github.com/starkware-libs/blockifier/blob/main/crates/blockifier/src/fee/fee_utils.rs#L125)



_Suggestion:_
```XML
        resource_bounds: l1_resource_bounds(
            (max_fee.0 / DEFAULT_STRK_L1_GAS_PRICE) as u64,
            DEFAULT_STRK_L1_GAS_PRICE
        ),
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0K_0J7DvTbNr866Mw:-Ni0K_0J7DvTbNr866Mx:b7vmp79) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/objects.rs#L62)):*
> ```XML
>             Self::Current(context) => {
>                 let l1_resource_bounds = context.get_l1_gas_bounds();
>                 // TODO(nir, 01/11/2023): Change to max_amount * block_context.gas_price.
> ```

is this TODO relevant? if not, delete it



_Code quote:_
```XML
// TODO(nir, 01/11/2023): Change to max_amount * block_context.gas_price.
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0IJtH1dcESfD6nHPM:-Ni0IJtH1dcESfD6nHPN:b-yzggex) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/objects.rs#L75)):*
> ```XML
>             Self::Deprecated(_) => None,
>         }
>     }
> ```

please delete this... we are also trying to delete `max_fee()`. this shouldn't be a method of a context object wrapping both tx variants. see comment above



_Code quote:_
```XML
    pub fn max_l1_gas_price(&self) -> Option<Fee> {
        match self {
            Self::Current(context) => Some(Fee(context.get_l1_gas_bounds().max_price_per_unit)),
            Self::Deprecated(_) => None,
        }
    }
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0Kk01BjFpITHbRst3:-Ni0Kk01BjFpITHbRst4:bsv4tfs) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/objects.rs#L110)):*
> ```XML
>     fn get_l1_gas_bounds(&self) -> ResourceBounds {
>         self.resource_bounds.0.get(&Resource::L1Gas).copied().unwrap_or_default()
>     }
> ```

Since this is production code, and the default value may be unexpected, I would return `Option<ResourceBounds>`.
The caller should `expect()` when needed.



_Code quote:_
```XML
    fn get_l1_gas_bounds(&self) -> ResourceBounds {
        self.resource_bounds.0.get(&Resource::L1Gas).copied().unwrap_or_default()
    }
```


<!-- Sent from Reviewable.io -->

2023-10-30 18:09 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 9 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 660 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0l3xG18RSzrlgqIzb:-Ni0l3xG18RSzrlgqIzc:b4t6on2) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/transactions_test.rs#L660)):*
> ```XML
>                 max_amount: (MAX_FEE / insufficient_max_l1_gas_price) as u64,
>                 max_price_per_unit:  insufficient_max_l1_gas_price}),
>         ])), version:TransactionVersion::THREE, ..valid_invoke_tx_args.clone() });
> ```

please use `l1_resource_bounds`



_Code quote:_
```XML
        account_invoke_tx(invoke_tx_args! {resource_bounds: ResourceBoundsMapping(BTreeMap::from([
            (Resource::L1Gas, ResourceBounds {
                max_amount: (MAX_FEE / insufficient_max_l1_gas_price) as u64,
                max_price_per_unit:  insufficient_max_l1_gas_price}),
        ])), version:TransactionVersion::THREE, ..valid_invoke_tx_args.clone() });
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 660 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0lFB2ENtsSXZAO3cd:-Ni0lFB2ENtsSXZAO3ce:b-rtyc76) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/transactions_test.rs#L660)):*
> ```XML
>                 max_amount: (MAX_FEE / insufficient_max_l1_gas_price) as u64,
>                 max_price_per_unit:  insufficient_max_l1_gas_price}),
>         ])), version:TransactionVersion::THREE, ..valid_invoke_tx_args.clone() });
> ```

macro inputs aren't auto-formatted unfortunately.
please fix the formatting



_Suggestion:_
```XML
    let invalid_tx = account_invoke_tx(invoke_tx_args! {
        resource_bounds: ResourceBoundsMapping(BTreeMap::from([
            (Resource::L1Gas, ResourceBounds {
                max_amount: (MAX_FEE / insufficient_max_l1_gas_price) as u64,
                max_price_per_unit:  insufficient_max_l1_gas_price
            }),
        ])),
        version:TransactionVersion::THREE,
        ..valid_invoke_tx_args.clone()
    });
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 665 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0lV2F8f9tbJfzPgSS:-Ni0lV2G5S5pfyZKjrFo:byadoo5) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/transactions_test.rs#L665)):*
> ```XML
>         .perform_pre_validation_checks(
>             &mut transactional_state,
>             &invalid_tx_context,
> ```

is this possible? or does rust complain?
if possible, use and delete variable above (non-blocking)



_Suggestion:_
```XML
&invalid_tx.get_account_tx_context()
```


<!-- Sent from Reviewable.io -->

2023-10-31 13:46 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: 0 of 14 files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0ISR01npMhylOA4QG:-Ni43Y2c9-0z8DNpT11F:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/account_transaction.rs#L167)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Use new context directly, no fetching "max L1 gas price" on deprecated objects (see comment below)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 403 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0K87x3us3PSNTfvgH:-Ni4hbLL5I9HJP2dbsCr:b-zbp104) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/account_transactions_test.rs#L403)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this computation necessary? why not take max resource bounds?
if default max resource bounds aren't defined yet, maybe steal them from [here](https://reviewable.io/reviews/starkware-libs/blockifier/1048) (see changes to `utils` and `test_utils` modules)
</blockquote></details>

stole them :thumbsup: (though I changed the type of `MAX\_L1\_GAS\_AMOUNT` to `u64`, because that's what `ResourceBounds` expects).
it's not needed, the `max_fee` parameter confused me (because it's not actually used for V3 txs, right?)
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 407 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0JpFqEL3Cdbv507Na:-Ni4nOv2CSsN69CpdHo4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/account_transactions_test.rs#L407)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see [this](https://github.com/starkware-libs/blockifier/blob/main/crates/blockifier/src/fee/fee_utils.rs#L125)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0K_0J7DvTbNr866Mw:-Ni4cheO6DCwtENzxIH8:b30rmaa) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/objects.rs#L62)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this TODO relevant? if not, delete it
</blockquote></details>

I think it's still relevant (notice `block_context`)
___
*[`crates/blockifier/src/transaction/objects.rs` line 75 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0IJtH1dcESfD6nHPM:-Ni43nGrBpmyEqPm7H6x:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/objects.rs#L75)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please delete this... we are also trying to delete `max_fee()`. this shouldn't be a method of a context object wrapping both tx variants. see comment above
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0Kk01BjFpITHbRst3:-Ni43uO50UUh45l4VTEd:b6hzecr) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/objects.rs#L110)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Since this is production code, and the default value may be unexpected, I would return `Option<ResourceBounds>`.
The caller should `expect()` when needed.
</blockquote></details>

Changed it to return an error, as we discussed.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 660 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0l3xG18RSzrlgqIzb:-Ni4lAxX9o0PrZxmVhnK:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/transactions_test.rs#L660)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please use `l1_resource_bounds`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 660 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0lFB2ENtsSXZAO3cd:-Ni4nQH0DRUSzlJZUgR2:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/transactions_test.rs#L660)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

macro inputs aren't auto-formatted unfortunately.
please fix the formatting
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 665 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0lV2F8f9tbJfzPgSS:-Ni4o8Nt5OKsU17cL1MQ:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/transactions_test.rs#L665)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this possible? or does rust complain?
if possible, use and delete variable above (non-blocking)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-10-31 14:34 UTC, dorimedini-starkware requested changes
> Reviewed 6 of 14 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 403 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0K87x3us3PSNTfvgH:-Ni57j8ZCtiwbGjvAJud:b-nls5ji) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/account_transactions_test.rs#L403)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

stole them :thumbsup: (though I changed the type of `MAX\_L1\_GAS\_AMOUNT` to `u64`, because that's what `ResourceBounds` expects).
it's not needed, the `max_fee` parameter confused me (because it's not actually used for V3 txs, right?)
</blockquote></details>

not sure what you're asking;
1. u64 is a good type for this, yes; worst case u64->u128 conversion is always fine, and u128->u64 is not always fine, so define the base type as u64 please
2. max_fee is not used in v3 txs
3. Maybe define a `max_resource_bounds` fixture/function that returns this bound (with max defaults) without arguments. non-blocking though, maybe not so useful
___
*[`crates/blockifier/src/transaction/objects.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0K_0J7DvTbNr866Mw:-Ni58gMw5oFNQ3dT5FDO:bn41pmk) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/objects.rs#L62)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I think it's still relevant (notice `block_context`)
</blockquote></details>

nvm, we're trying to delete the `max_fee()` function soon anyway
___
*[`crates/blockifier/src/transaction/objects.rs` line 101 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni58t4m9MkzWEfKEWfU:-Ni58t4m9MkzWEfKEWfV:bka8xp7) ([raw file](https://github.com/starkware-libs/blockifier/blob/2703ba13fd35c5b89910d275b1352cfc7e53292f/crates/blockifier/src/transaction/objects.rs#L101)):*
> ```XML
> impl CurrentAccountTransactionContext {
>     /// Fetch the L1 resource bounds, if they exist.
>     pub fn l1_resource_bounds(&self) -> Option<ResourceBounds> {
> ```

this function is only needed because of the `unwrap_or_default` above?
`unwrap_or_default` should also work on `Result` type objects, not just `Option`; please delete this function and simply use `get_l1_gas_bounds` everywhere



_Code quote:_
```XML
pub fn l1_resource_bounds
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 660 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0lFB2ENtsSXZAO3cd:-Ni58Vzb5vCil8Mb5avI:b-u5ct8d) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/transactions_test.rs#L660)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see a formatting change; is it auto-formatted like this?


<!-- Sent from Reviewable.io -->

2023-11-01 07:46 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/objects.rs` line 101 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni58t4m9MkzWEfKEWfU:-Ni8ogAu0Ox2jUAAgW1Z:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/2703ba13fd35c5b89910d275b1352cfc7e53292f/crates/blockifier/src/transaction/objects.rs#L101)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this function is only needed because of the `unwrap_or_default` above?
`unwrap_or_default` should also work on `Result` type objects, not just `Option`; please delete this function and simply use `get_l1_gas_bounds` everywhere
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 660 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni0lFB2ENtsSXZAO3cd:-Ni8pk7E08hKiTPxcwRs:b-ce29d5) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3f8ce136a229f585c1c2ad5c417f0dfcd14fecb/crates/blockifier/src/transaction/transactions_test.rs#L660)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't see a formatting change; is it auto-formatted like this?
</blockquote></details>

It is (ran `fmt` and it switched to this)


<!-- Sent from Reviewable.io -->

2023-11-01 09:22 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 230 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni9BA7U-rvcKVxcGqF5:-Ni9BA7U-rvcKVxcGqF6:b-sjftjh) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7f484b5052559e8fa2fe7a35e9938f5a839a7fa/crates/blockifier/src/execution/entry_point.rs#L230)):*
> ```XML
>                 current_context
>                     .get_l1_gas_bounds()
>                     .expect("No L1 resource bounds found on current transaction context.")
> ```

maybe this should also return a FeeError if the bounds aren't found...?



_Code quote:_
```XML
                current_context
                    .get_l1_gas_bounds()
                    .expect("No L1 resource bounds found on current transaction context.")
```


<!-- Sent from Reviewable.io -->

2023-11-01 12:27 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 230 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni9BA7U-rvcKVxcGqF5:-Ni9qLasET7_Sz9i9EE0:b9ofsay) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7f484b5052559e8fa2fe7a35e9938f5a839a7fa/crates/blockifier/src/execution/entry_point.rs#L230)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe this should also return a FeeError if the bounds aren't found...?
</blockquote></details>

umm maybe, but this would require more changes (update the calling functions to return a result which includes said error, etc), so I don't think it should be done in this PR


<!-- Sent from Reviewable.io -->

2023-11-02 07:57 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 230 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni9BA7U-rvcKVxcGqF5:-NiE1EypE-R5sAawXHiu:b-fynwg4) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7f484b5052559e8fa2fe7a35e9938f5a839a7fa/crates/blockifier/src/execution/entry_point.rs#L230)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

umm maybe, but this would require more changes (update the calling functions to return a result which includes said error, etc), so I don't think it should be done in this PR
</blockquote></details>

Can you add a TODO then?


<!-- Sent from Reviewable.io -->

2023-11-02 10:54 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 230 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Ni9BA7U-rvcKVxcGqF5:-NiEe7WtDGoeintCHqgE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7f484b5052559e8fa2fe7a35e9938f5a839a7fa/crates/blockifier/src/execution/entry_point.rs#L230)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Can you add a TODO then?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-02 10:56 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: 9 of 15 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 405 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiEf2xX7PDpe8Xg-0aw:-NiEf2xX7PDpe8Xg-0ax:b-ly38v9) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transactions_test.rs#L405)):*
> ```XML
>             );
>         }
>         TransactionVersion::THREE => {
> ```

Is this behaviour ok? I didn't understand what this test does



_Code quote:_
```XML
 TransactionVersion::THREE => {
```


<!-- Sent from Reviewable.io -->

2023-11-02 14:11 UTC, dorimedini-starkware requested changes
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 13 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 157 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFIA0vDDKUVtzTDCg1:-NiFIA0vDDKUVtzTDCg2:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L157)):*
> ```XML
>             if !account_tx_context.enforce_fee() {
>                 return Ok(());
>             }
> ```





_Suggestion:_
```XML
        if charge_fee && account_tx_context.enforce_fee() {
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 172 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFIwkaEPxlma5xZjWd:-NiFIwkaEPxlma5xZjWe:bn3t53y) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L172)):*
> ```XML
>     }
> 
>     fn check_fee_bounds(
> ```

You have two independent checks here:
1. Check minimal resource bounds
2. For v3, check gas price
Please add a docstring explaining these checks... the function name can't explain it all.



_Code quote:_
```XML
fn check_fee_bounds(
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 180 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFJRFK6pA4Si0DwDL9:-NiFJRFK6pA4Si0DwDLA:b-bddu8p) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L180)):*
> ```XML
>         match account_tx_context {
>             AccountTransactionContext::Current(current_context) => {
>                 let l1_gas_bounds = current_context.get_l1_gas_bounds()?;
> ```

destructure instead of defining variables



_Suggestion:_
```XML
let ResourceBounds {
    max_amount: max_l1_gas_amount,
    max_price_per_unit: max_l1_gas_price
} = current_context.get_l1_gas_bounds()?;
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 197 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFIkLgEPwuMr8KXvr1:-NiFIkLgEPwuMr8KXvr2:b-i1ttam) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L197)):*
> ```XML
>             }
>             AccountTransactionContext::Deprecated(_) => {
>                 let max_fee = account_tx_context.max_fee();
> ```

trying to slowly delete `max_fee()` usages



_Suggestion:_
```XML
            AccountTransactionContext::Deprecated(deprecated_context) => {
                let max_fee = deprecated_context.max_fee;
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 198 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFIbyD94hVTL5Yb1e5:-NiFIbyE6RJ4jR59iNSy:b8tsltc) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L198)):*
> ```XML
>             AccountTransactionContext::Deprecated(_) => {
>                 let max_fee = account_tx_context.max_fee();
>                 let minimal_fee = minimal_l1_gas_amount * block_context.gas_prices.eth_l1_gas_price;
> ```

use `fee_by_l1_gas_usage`, it's in `fee_utils`



_Code quote:_
```XML
minimal_l1_gas_amount * block_context.gas_prices.eth_l1_gas_price;
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 372 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFL5ms4daVriAJmX3s:-NiFL5ms4daVriAJmX3t:b-tyvz7i) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transactions_test.rs#L372)):*
> ```XML
>     #[from(create_state)] state: CachedState<DictStateReader>,
>     #[case] tx_version: TransactionVersion,
> ) {
> ```

better to put parametrizations in the attribute



_Suggestion:_
```XML
#[case(TransactionVersion::ONE, true)]
#[case(TransactionVersion::THREE, false)]
fn test_max_fee_limit_validate(
    block_context: BlockContext,
    #[from(create_state)] state: CachedState<DictStateReader>,
    #[case] tx_version: TransactionVersion,
    #[case] is_deprecated: bool
) {
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 405 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiEf2xX7PDpe8Xg-0aw:-NiFL_T2AnDjw6z9rV48:byz4762) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transactions_test.rs#L405)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Is this behaviour ok? I didn't understand what this test does
</blockquote></details>

The test doesn't test what it says it does... my bad...
please rename to `test_minimal_resource_bounds` and rewrite the docstring... I'll work on a proper validation-step-limit test
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 410 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFLFCc7KgeBWTCrU9i:-NiFLFCc7KgeBWTCrU9j:b-6p3uii) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transactions_test.rs#L410)):*
> ```XML
>         other => panic!("Add arm for tx version {:?}.", other),
>     }
> }
> ```

see above `#[case]` addition



_Suggestion:_
```XML
    if is_deprecated {
        assert_matches!(
            error, TransactionExecutionError::MaxFeeTooLow { max_fee: Fee(10), .. }
        );
    } else {
        assert_matches!(error, TransactionExecutionError::MaxL1GasAmountTooLow { .. });
    }
}
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 554 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFMSRXAmcPKfydZjV3:-NiFMSRXAmcPKfydZjV4:bv6k2kj) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/transactions_test.rs#L554)):*
> ```XML
>         TransactionExecutionError::MaxFeeTooLow{ min_fee, max_fee }
>         if max_fee == invalid_max_fee && min_fee == minimal_fee
>     );
> ```

this entire block is tested in the test above; right?
if it's covered, please delete this part of the test



_Code quote:_
```XML
    let block_context = &BlockContext::create_for_account_testing();
    let valid_invoke_tx_args = default_invoke_tx_args();
    // The minimal gas estimate does not depend on tx version.
    let minimal_l1_gas =
        estimate_minimal_l1_gas(block_context, &account_invoke_tx(valid_invoke_tx_args.clone()))
            .unwrap();

    // Test V1 tx

    let minimal_fee = Fee(minimal_l1_gas * block_context.gas_prices.eth_l1_gas_price);
    // Max fee too low (lower than minimal estimated fee).
    let invalid_max_fee = Fee(minimal_fee.0 - 1);
    let invalid_v1_tx = account_invoke_tx(
        invoke_tx_args! { max_fee: invalid_max_fee, ..valid_invoke_tx_args.clone() },
    );
    let execution_error = invalid_v1_tx.execute(state, block_context, true, true).unwrap_err();

    // Test error.
    assert_matches!(
        execution_error,
        TransactionExecutionError::MaxFeeTooLow{ min_fee, max_fee }
        if max_fee == invalid_max_fee && min_fee == minimal_fee
    );
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 572 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFMavWAvE1ZxtDnv9p:-NiFMavWAvE1ZxtDnv9q:bvtxqvz) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/c [...]

2023-11-05 06:41 UTC, elintul approved these changes
> Reviewed 7 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 18 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 178 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiTBnjE7e6sFwFLsKSa:-NiTBnjE7e6sFwFLsKSb:b-te1ak2) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L178)):*
> ```XML
>     ) -> TransactionExecutionResult<()> {
>         let minimal_l1_gas_amount = estimate_minimal_l1_gas(block_context, self)?;
>         match account_tx_context {
> ```

Add a blank line above.



_Code quote:_
```XML
match account_tx_context {
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 179 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiTBXh70U_5QBalCdvL:-NiTBXh70U_5QBalCdvM:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L179)):*
> ```XML
>         let minimal_l1_gas_amount = estimate_minimal_l1_gas(block_context, self)?;
>         match account_tx_context {
>             AccountTransactionContext::Current(current_context) => {
> ```





_Suggestion:_
```XML
context
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 188 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiTBqpaEav_TLcQResH:-NiTBqpb0ZyH7sxkEPkd:b-te1ak2) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L188)):*
> ```XML
>                     });
>                 }
>                 let max_l1_gas_price = l1_gas_bounds.max_price_per_unit;
> ```

Add a blank line above.



_Code quote:_
```XML
let max_l1_gas_price = l1_gas_bounds.max_price_per_unit;
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 189 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiTC6YN8fGF668Eythh:-NiTC6YN8fGF668Eythi:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L189)):*
> ```XML
>                 }
>                 let max_l1_gas_price = l1_gas_bounds.max_price_per_unit;
>                 if max_l1_gas_price < block_context.gas_prices.strk_l1_gas_price {
> ```





_Suggestion:_
```XML
let actual_gas_price = block_context.gas_prices.get_by_fee_type(&context.fee_type()));
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 192 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiTCSRC-IaMPDMOeWMf:-NiTCSRC-IaMPDMOeWMg:bhugjro) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L192)):*
> ```XML
>                     return Err(TransactionExecutionError::MaxL1GasPriceTooLow {
>                         max_l1_gas_price: Fee(max_l1_gas_price),
>                         current_l1_gas_price: Fee(block_context.gas_prices.strk_l1_gas_price),
> ```

Perhaps we should consider keeping all these numbers as `Fee`... (not for now)
Please _do_ align the types in the errors: I think the arguments should all be of type `Fee`; the current asymmetry is a bit weird.



_Code quote:_
```XML
                        max_l1_gas_price: Fee(max_l1_gas_price),
                        current_l1_gas_price: Fee(block_context.gas_prices.strk_l1_gas_price),
```


<!-- Sent from Reviewable.io -->

2023-11-05 13:33 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: 11 of 15 files reviewed, 14 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 157 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFIA0vDDKUVtzTDCg1:-NiUB-Bc3ECEy_hSfb2l:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L157)):*
> ```XML
>             if !account_tx_context.enforce_fee() {
>                 return Ok(());
>             }
> ```

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 172 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFIwkaEPxlma5xZjWd:-NiUE7bQ08C_RpUq5WFf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L172)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

You have two independent checks here:
1. Check minimal resource bounds
2. For v3, check gas price
Please add a docstring explaining these checks... the function name can't explain it all.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 180 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFJRFK6pA4Si0DwDL9:-NiUE_YJ9wv16GpFUNRi:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L180)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

destructure instead of defining variables
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 197 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFIkLgEPwuMr8KXvr1:-NiUH_Ek12cpvB0T3j2n:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L197)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

trying to slowly delete `max_fee()` usages
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 198 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFIbyD94hVTL5Yb1e5:-NiUIhN17dMu5Vy5cuzB:b-9wnqj) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L198)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use `fee_by_l1_gas_usage`, it's in `fee_utils`
</blockquote></details>

I don't see this function in the repo (or any similar function in `fee_utils`)
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 372 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFL5ms4daVriAJmX3s:-NiULa7V4-7hVS2xgC2v:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transactions_test.rs#L372)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

better to put parametrizations in the attribute
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 410 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFLFCc7KgeBWTCrU9i:-NiULxDPCvPPyyahgYTa:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transactions_test.rs#L410)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above `#[case]` addition
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 554 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFMSRXAmcPKfydZjV3:-NiUNfW9-yVxE1sYy42a:b-h4csqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/transactions_test.rs#L554)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this entire block is tested in the test above; right?
if it's covered, please delete this part of the test
</blockquote></details>

Looks like it is, but don't you think it makes more sense to have all the checks in one test? and move it to `account_transaction_test` when all pre-validation-checks-tests move there?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 579 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFMkE76PqQTYnNREM-:-NiUQqlADKDsFgKeqj0z:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/transactions_test.rs#L579)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

fix indentation...
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 579 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFMqGD4VS3EeNTKZh8:-NiURu5xDmsSqDV1wDe8:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/transactions_test.rs#L579)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no need for this final `clone()`, `valid_invoke_tx_args` isn't used again after this
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-05 13:43 UTC, elintul reviewed
> Reviewed 1 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: 11 of 15 files reviewed, 14 unresolved discussions (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2023-11-05 16:22 UTC, dorimedini-starkware requested changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 8 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 192 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiTCSRC-IaMPDMOeWMf:-NiVGk7L7ivT2gae6b-z:b-h38221) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L192)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps we should consider keeping all these numbers as `Fee`... (not for now)
Please _do_ align the types in the errors: I think the arguments should all be of type `Fee`; the current asymmetry is a bit weird.
</blockquote></details>

Why should these arguments be of type `Fee`?
Gas price is an amount of tokens, but not a fee; right?
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 198 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFIbyD94hVTL5Yb1e5:-NiVH09u-oH0xrEjUH0O:b-htlo2u) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L198)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I don't see this function in the repo (or any similar function in `fee_utils`)
</blockquote></details>

gawd dammit... please put a TODO to change this computation, `fee_by_l1_gas_usage` probably exists in some PR in some stack somewhere
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 170 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiVGJF_C04N_eC0cf20:-NiVGJF_C04N_eC0cf21:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/029d8108a7322087ef2765de2d0f77a04e486053/crates/blockifier/src/transaction/account_transaction.rs#L170)):*
> ```XML
> 
>     /// Checks the tx's specified fee bounds -
>     /// For txs of version less than three: asserts max fee is greater / equal to
> ```





_Suggestion:_
```XML
deprecated transactions
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 172 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiVGNLy1cgg2pHqyVUn:-NiVGNLy1cgg2pHqyVUo:b-a7pu1s) ([raw file](https://github.com/starkware-libs/blockifier/blob/029d8108a7322087ef2765de2d0f77a04e486053/crates/blockifier/src/transaction/account_transaction.rs#L172)):*
> ```XML
>     /// For txs of version less than three: asserts max fee is greater / equal to
>     /// the estimated minimal fee.
>     /// For txs of version 3 and higher: asserts max amount of L1 gas >= estimated minimal
> ```

current? new? not so sure



_Suggestion:_
```XML
current transactions
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 554 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFMSRXAmcPKfydZjV3:-NiVHJuh9nNZ19m3p6am:b-olfiv1) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/transactions_test.rs#L554)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Looks like it is, but don't you think it makes more sense to have all the checks in one test? and move it to `account_transaction_test` when all pre-validation-checks-tests move there?
</blockquote></details>

Well, moving tests around is out of scope, but to get this current PR in, I would like at least to delete the scenario in one of the places


<!-- Sent from Reviewable.io -->

2023-11-06 09:41 UTC, elintul requested changes
> Reviewed 2 of 6 files at r5, 2 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 14 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 222 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiYzJ278E767vyrCnGR:-NiYzJ278E767vyrCnGS:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/029d8108a7322087ef2765de2d0f77a04e486053/crates/blockifier/src/execution/entry_point.rs#L222)):*
> ```XML
>         // transactions derive this value from the `max_fee`.
>         let tx_gas_upper_bound = match account_tx_context {
>             AccountTransactionContext::Deprecated(deprecated_context) => {
> ```





_Suggestion:_
```XML
context
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 227 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiYzKhU0lj9GgclSzgD:-NiYzKhU0lj9GgclSzgE:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/029d8108a7322087ef2765de2d0f77a04e486053/crates/blockifier/src/execution/entry_point.rs#L227)):*
> ```XML
>                     as usize
>             }
>             AccountTransactionContext::Current(current_context) => {
> ```





_Suggestion:_
```XML
context
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 192 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiTCSRC-IaMPDMOeWMf:-NiYza9cDIwhJBUgsC50:b-9b1lfw) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L192)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Why should these arguments be of type `Fee`?
Gas price is an amount of tokens, but not a fee; right?
</blockquote></details>

Sorry, I meant a wrapper type.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 204 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiYzj5W9s5aQcOzewqp:-NiYzj5W9s5aQcOzewqq:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/029d8108a7322087ef2765de2d0f77a04e486053/crates/blockifier/src/transaction/account_transaction.rs#L204)):*
> ```XML
>                 }
>             }
>             AccountTransactionContext::Deprecated(deprecated_context) => {
> ```





_Suggestion:_
```XML
context
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 57 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiYzyUID30Fn5maOKPO:-NiYzyUID30Fn5maOKPP:b-gtcepi) ([raw file](https://github.com/starkware-libs/blockifier/blob/029d8108a7322087ef2765de2d0f77a04e486053/crates/blockifier/src/transaction/errors.rs#L57)):*
> ```XML
>          {actual_l1_gas_price:?}."
>     )]
>     MaxL1GasPriceTooLow { max_l1_gas_price: Fee, actual_l1_gas_price: Fee },
> ```

Why are those `Fee`s?



_Code quote:_
```XML
max_l1_gas_price: Fee, actual_l1_gas_price: Fee
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 72 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiZ-5Yn-npXVhGEi6F0:-NiZ-5Yn-npXVhGEi6F1:b-qr949r) ([raw file](https://github.com/starkware-libs/blockifier/blob/029d8108a7322087ef2765de2d0f77a04e486053/crates/blockifier/src/transaction/errors.rs#L72)):*
> ```XML
>     ValidateTransactionError(#[source] EntryPointExecutionError),
>     #[error("Missing bounds for resource: {:?}.", resource)]
>     MissingResourceBounds { resource: Resource },
> ```

Please keep alphabetized.



_Code quote:_
```XML
MissingResourceBounds
```


<!-- Sent from Reviewable.io -->

2023-11-08 08:30 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 15 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 163 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Nii2GTX1PNJYkW91Ciy:-Nii2GTYDjOLGzkG2uQR:bpon8pd) ([raw file](https://github.com/starkware-libs/blockifier/blob/029d8108a7322087ef2765de2d0f77a04e486053/crates/blockifier/src/transaction/account_transaction.rs#L163)):*
> ```XML
>                 block_context,
>                 account_tx_context.max_fee(),
>             )?;
> ```

This is wrong for v3 - there is no `max_fee`.
For v3, we must check `balance >= max_amount * max_price`...
the `verify_can_pay_max_fee` probably needs a refactor and rename, I'll TAL



_Code quote:_
```XML
            verify_can_pay_max_fee(
                state,
                account_tx_context,
                block_context,
                account_tx_context.max_fee(),
            )?;
```


<!-- Sent from Reviewable.io -->

2023-11-08 08:30 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 15 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 163 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Nii2GTX1PNJYkW91Ciy:-Nii2GTYDjOLGzkG2uQR:bpon8pd) ([raw file](https://github.com/starkware-libs/blockifier/blob/029d8108a7322087ef2765de2d0f77a04e486053/crates/blockifier/src/transaction/account_transaction.rs#L163)):*
> ```XML
>                 block_context,
>                 account_tx_context.max_fee(),
>             )?;
> ```

This is wrong for v3 - there is no `max_fee`.
For v3, we must check `balance >= max_amount * max_price`...
the `verify_can_pay_max_fee` probably needs a refactor and rename, I'll TAL



_Code quote:_
```XML
            verify_can_pay_max_fee(
                state,
                account_tx_context,
                block_context,
                account_tx_context.max_fee(),
            )?;
```


<!-- Sent from Reviewable.io -->

2023-11-08 09:03 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 15 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 163 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Nii2GTX1PNJYkW91Ciy:-NiiA-lt3YZZW3Mr5oMH:b8e4tlb) ([raw file](https://github.com/starkware-libs/blockifier/blob/029d8108a7322087ef2765de2d0f77a04e486053/crates/blockifier/src/transaction/account_transaction.rs#L163)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

This is wrong for v3 - there is no `max_fee`.
For v3, we must check `balance >= max_amount * max_price`...
the `verify_can_pay_max_fee` probably needs a refactor and rename, I'll TAL
</blockquote></details>

[PTAL](https://reviewable.io/reviews/starkware-libs/blockifier/1101)


<!-- Sent from Reviewable.io -->

2023-11-08 12:00 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 10 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 198 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFIbyD94hVTL5Yb1e5:-NiiXl5J07OHvGf9d7GH:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L198)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

gawd dammit... please put a TODO to change this computation, `fee_by_l1_gas_usage` probably exists in some PR in some stack somewhere
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 163 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Nii2GTX1PNJYkW91Ciy:-NiiVQoV0kbSv7IW1yuC:bmzjs4z) ([raw file](https://github.com/starkware-libs/blockifier/blob/029d8108a7322087ef2765de2d0f77a04e486053/crates/blockifier/src/transaction/account_transaction.rs#L163)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[PTAL](https://reviewable.io/reviews/starkware-libs/blockifier/1101)
</blockquote></details>

As we talked F2F - the logic is correct also for V3 txs, we can refactor the function separately
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 170 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiVGJF_C04N_eC0cf20:-NiiWAyK4CbdUUksJXC8:bwwchna) ([raw file](https://github.com/starkware-libs/blockifier/blob/029d8108a7322087ef2765de2d0f77a04e486053/crates/blockifier/src/transaction/account_transaction.rs#L170)):*
> ```XML
> 
>     /// Checks the tx's specified fee bounds -
>     /// For txs of version less than three: asserts max fee is greater / equal to
> ```

WYT of new comment?
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 172 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiVGNLy1cgg2pHqyVUn:-NiiWDBtCCYr-0CsvA7H:b-7ropln) ([raw file](https://github.com/starkware-libs/blockifier/blob/029d8108a7322087ef2765de2d0f77a04e486053/crates/blockifier/src/transaction/account_transaction.rs#L172)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

current? new? not so sure
</blockquote></details>

ditto
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 405 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiEf2xX7PDpe8Xg-0aw:-NiiY9TF15Qwbj8KW8Fk:b-qda71) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transactions_test.rs#L405)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

The test doesn't test what it says it does... my bad...
please rename to `test_minimal_resource_bounds` and rewrite the docstring... I'll work on a proper validation-step-limit test
</blockquote></details>

I'll delete this test since I think it's better to have all pre-validation checks tests in `transaction_test.rs` until we move all of them together.
___
*[`crates/blockifier/src/transaction/errors.rs` line 57 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiYzyUID30Fn5maOKPO:-Niif4tc4sGvQAFSHoLy:bix8vfz) ([raw file](https://github.com/starkware-libs/blockifier/blob/029d8108a7322087ef2765de2d0f77a04e486053/crates/blockifier/src/transaction/errors.rs#L57)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why are those `Fee`s?
</blockquote></details>

Changed to `u128`, thanks
___
*[`crates/blockifier/src/transaction/errors.rs` line 72 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiZ-5Yn-npXVhGEi6F0:-Niim4ok5KcywLIUyDaD:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/029d8108a7322087ef2765de2d0f77a04e486053/crates/blockifier/src/transaction/errors.rs#L72)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please keep alphabetized.
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 554 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFMSRXAmcPKfydZjV3:-NiillZr4-TPFpslOFaY:b-48h1w2) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/transactions_test.rs#L554)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Well, moving tests around is out of scope, but to get this current PR in, I would like at least to delete the scenario in one of the places
</blockquote></details>

Deleted the test in `account_transaction_test.rs`
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 572 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFMavWAvE1ZxtDnv9p:-Niilr1aBjRxdbyScT3P:b-7ropln) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/transactions_test.rs#L572)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is also tested above, please delete
</blockquote></details>

ditto
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 586 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiFMdfxAwHNm1_n0_jj:-NiiltE82sQlXO2DvF7H:b-7ropln) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/transactions_test.rs#L586)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is the only scenario not covered above - please keep only it, and rename the test accordingly
</blockquote></details>

ditto


<!-- Sent from Reviewable.io -->

2023-11-08 12:04 UTC, elintul requested changes
> Reviewed 5 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: 13 of 16 files reviewed, 14 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 547 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiioJJlE9HjAOfi5yfT:-NiioJJm4tp_UNpCHc1f:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4bda7e305884e90ed8d17e55df6f8467e7c638dc/crates/blockifier/src/transaction/transactions_test.rs#L547)):*
> ```XML
>             .unwrap();
> 
>     // Test V1 tx
> ```





_Suggestion:_
```XML
// Test V1 transaction.
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 564 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiioN6a6DQhUdZFP5EJ:-NiioN6a6DQhUdZFP5EK:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4bda7e305884e90ed8d17e55df6f8467e7c638dc/crates/blockifier/src/transaction/transactions_test.rs#L564)):*
> ```XML
>     );
> 
>     // Test V3 tx
> ```





_Suggestion:_
```XML
// Test V3 transaction.
```


<!-- Sent from Reviewable.io -->

2023-11-08 13:13 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: 11 of 16 files reviewed, 13 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 564 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiioN6a6DQhUdZFP5EJ:-Nij0KzdAT11zg9Mhm0c:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4bda7e305884e90ed8d17e55df6f8467e7c638dc/crates/blockifier/src/transaction/transactions_test.rs#L564)):*
> ```XML
>     );
> 
>     // Test V3 tx
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-11-08 14:26 UTC, dorimedini-starkware approved these changes
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2023-11-09 12:05 UTC, dorimedini-starkware approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2023-11-09 13:56 UTC, elintul reviewed
> Reviewed 1 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2023-11-09 14:09 UTC, elintul requested changes
> Reviewed 2 of 5 files at r8, 1 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 166 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NioN6Kr8IrhvWTnU5Xf:-NioN6Kr8IrhvWTnU5Xg:bibm7nz) ([raw file](https://github.com/starkware-libs/blockifier/blob/e092284c18e3883dca8d09181b0e2e4060cfff09/crates/blockifier/src/transaction/account_transaction.rs#L166)):*
> ```XML
>     /// the estimated minimal fee.
>     /// Otherwise: asserts max amount of L1 gas >= estimated minimal
>     /// gas amount, and max price of L1 gas per unit >= current L1 gas price in STRK.
> ```

Unnecessary, IMO; it repeats code.



_Code quote:_
```XML
    /// Checks the tx's specified fee bounds -
    /// If the transaction is deprecated: asserts max fee is greater / equal to
    /// the estimated minimal fee.
    /// Otherwise: asserts max amount of L1 gas >= estimated minimal
    /// gas amount, and max price of L1 gas per unit >= current L1 gas price in STRK.
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 91 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NioPYslBxSQEIU5jpa2:-NioPYslBxSQEIU5jpa3:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e092284c18e3883dca8d09181b0e2e4060cfff09/crates/blockifier/src/transaction/objects.rs#L91)):*
> ```XML
>     pub fn enforce_fee(&self) -> bool {
>         match self {
>             AccountTransactionContext::Current(current_context) => {
> ```





_Suggestion:_
```XML
context
```


<!-- Sent from Reviewable.io -->

2023-11-09 16:16 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: 8 of 16 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiorPne08E3GK7A5vyF:-NiorPne08E3GK7A5vyG:ban208c) (no related file):*
python side
https://reviewable.io/reviews/starkware-industries/starkware/32529

___
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 166 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NioN6Kr8IrhvWTnU5Xf:-Nior7ql3AEP6_th56S-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e092284c18e3883dca8d09181b0e2e4060cfff09/crates/blockifier/src/transaction/account_transaction.rs#L166)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Unnecessary, IMO; it repeats code.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 91 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NioPYslBxSQEIU5jpa2:-NiorLr74Y4oqOdRcpqX:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e092284c18e3883dca8d09181b0e2e4060cfff09/crates/blockifier/src/transaction/objects.rs#L91)):*
> ```XML
>     pub fn enforce_fee(&self) -> bool {
>         match self {
>             AccountTransactionContext::Current(current_context) => {
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-11-10 09:12 UTC, dorimedini-starkware requested changes
> Reviewed 8 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 11 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 195 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NisTpZRBE6fUwD-6OPR:-NisTpZRBE6fUwD-6OPS:b-6wq570) ([raw file](https://github.com/starkware-libs/blockifier/blob/85031cb87340affe71d5ccedeca2faa99d2d77a0/crates/blockifier/src/transaction/account_transaction.rs#L195)):*
> ```XML
>                 let max_fee = deprecated_context.max_fee;
>                 // TODO(Amos, 01/12/2023): Use `fee_by_l1_gas_usage` when it's merged.
>                 let minimal_fee = minimal_l1_gas_amount * block_context.gas_prices.eth_l1_gas_price;
> ```

`get_fee_by_l1_gas_usage` is now available after rebase, I think



_Code quote:_
```XML
                // TODO(Amos, 01/12/2023): Use `fee_by_l1_gas_usage` when it's merged.
                let minimal_fee = minimal_l1_gas_amount * block_context.gas_prices.eth_l1_gas_price;
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 66 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NisUAIE8uX-y4ht-9tf:-NisUAIE8uX-y4ht-9tg:b-wbg2gn) ([raw file](https://github.com/starkware-libs/blockifier/blob/85031cb87340affe71d5ccedeca2faa99d2d77a0/crates/blockifier/src/transaction/objects.rs#L66)):*
> ```XML
>         match self {
>             Self::Current(context) => {
>                 let l1_resource_bounds = context.l1_resource_bounds().unwrap_or_default();
> ```

how painful would it be to make this change...?
I know `max_fee()` is temporary, but `unwrap_or_default` can be dangerous here: user can omit the L1 bounds, `max_fee()` will return zero, which can indicate `enforce_fee==false` (`enforce_fee()` doesn't use `max_fee()` but in principle it's confusing)



_Suggestion:_
```XML
    pub fn max_fee(&self) -> TransactionExecutionResult<Fee> {
        match self {
            Self::Current(context) => {
                let l1_resource_bounds = context.l1_resource_bounds()?;
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 244 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NisV0Km9oSlcIH3xC-Q:-NisV0Km9oSlcIH3xC-R:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/85031cb87340affe71d5ccedeca2faa99d2d77a0/crates/blockifier/src/execution/entry_point.rs#L244)):*
> ```XML
>                 current_context
>                     .l1_resource_bounds()
>                     .expect("No L1 resource bounds found on current transaction context.")
> ```





_Suggestion:_
```XML
                current_context.l1_resource_bounds()?
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 210 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NisV8wlEaqlY8fKIFWC:-NisV8wlEaqlY8fKIFWD:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/85031cb87340affe71d5ccedeca2faa99d2d77a0/crates/blockifier/src/fee/actual_cost.rs#L210)):*
> ```XML
>                 // Check L1 gas limit.
>                 let max_l1_gas =
>                     context.l1_resource_bounds().expect("L1 gas bounds must be set.").max_amount
> ```





_Suggestion:_
```XML
context.l1_resource_bounds()?.max_amount
```


<!-- Sent from Reviewable.io -->

2023-11-12 08:45 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 10 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 195 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NisTpZRBE6fUwD-6OPR:-Nj1cm4F6RFzdPu2MMbP:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/85031cb87340affe71d5ccedeca2faa99d2d77a0/crates/blockifier/src/transaction/account_transaction.rs#L195)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`get_fee_by_l1_gas_usage` is now available after rebase, I think
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 66 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NisUAIE8uX-y4ht-9tf:-Nj1eJZo82lmV_BrMJNz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/85031cb87340affe71d5ccedeca2faa99d2d77a0/crates/blockifier/src/transaction/objects.rs#L66)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

how painful would it be to make this change...?
I know `max_fee()` is temporary, but `unwrap_or_default` can be dangerous here: user can omit the L1 bounds, `max_fee()` will return zero, which can indicate `enforce_fee==false` (`enforce_fee()` doesn't use `max_fee()` but in principle it's confusing)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/entry_point.rs` line 244 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NisV0Km9oSlcIH3xC-Q:-Nj1gdwA5XS3gti-a2FK:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/85031cb87340affe71d5ccedeca2faa99d2d77a0/crates/blockifier/src/execution/entry_point.rs#L244)):*
> ```XML
>                 current_context
>                     .l1_resource_bounds()
>                     .expect("No L1 resource bounds found on current transaction context.")
> ```

Done.
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 210 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NisV8wlEaqlY8fKIFWC:-Nj1eMWm9blxSYFZAaBF:bzeunxl) ([raw file](https://github.com/starkware-libs/blockifier/blob/85031cb87340affe71d5ccedeca2faa99d2d77a0/crates/blockifier/src/fee/actual_cost.rs#L210)):*
> ```XML
>                 // Check L1 gas limit.
>                 let max_l1_gas =
>                     context.l1_resource_bounds().expect("L1 gas bounds must be set.").max_amount
> ```

I though you did this in a separate PR?
Done


<!-- Sent from Reviewable.io -->

2023-11-12 08:49 UTC, dorimedini-starkware approved these changes
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 7 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 195 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Nj1hzxj7ZtF-zNB7jQ3:-Nj1hzxj7ZtF-zNB7jQ4:b-j55jtt) ([raw file](https://github.com/starkware-libs/blockifier/blob/69dcff0c7ac6169e8cac53f0155fc5da81e5db2a/crates/blockifier/src/transaction/account_transaction.rs#L195)):*
> ```XML
>                 let max_fee = deprecated_context.max_fee;
>                 let min_fee =
>                     get_fee_by_l1_gas_usage(block_context, minimal_l1_gas_amount, &FeeType::Eth);
> ```

maybe `self.fee_type()` is better - you are coupling the ETH fee type with the deprecated account context, which is correct, but maybe shouldn't be hardcoded here.
non blocking



_Code quote:_
```XML
&FeeType::Eth
```


<!-- Sent from Reviewable.io -->

2023-11-12 08:50 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-:-Nj1iLi65CFgWVHw7SH5:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @amosStarkware and @elintul)



<!-- Sent from Reviewable.io -->

2023-11-12 09:09 UTC, dorimedini-starkware submitted a review, later dismissed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2023-11-12 11:23 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: 14 of 16 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 204 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-NiYzj5W9s5aQcOzewqp:-Nj2GQocBrQ5joGCV1uD:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/029d8108a7322087ef2765de2d0f77a04e486053/crates/blockifier/src/transaction/account_transaction.rs#L204)):*
> ```XML
>                 }
>             }
>             AccountTransactionContext::Deprecated(deprecated_context) => {
> ```

Done


<!-- Sent from Reviewable.io -->

2023-11-12 14:16 UTC, dorimedini-starkware submitted a review, later dismissed
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2023-11-12 14:50 UTC, dorimedini-starkware approved these changes
> Reviewed 6 of 6 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2023-11-12 15:28 UTC, elintul submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 6 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-:-Nj38_MBC1QSnT8Rs9YI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2023-11-12 15:29 UTC, dorimedini-starkware submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2023-11-13 09:28 UTC, elintul requested changes
> Reviewed 2 of 3 files at r15, 1 of 1 files at r16, 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 234 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Nj6xwOXCp8pAvq3rqNL:-Nj6xwOXCp8pAvq3rqNM:b-7ywit1) ([raw file](https://github.com/starkware-libs/blockifier/blob/e010e9446a5ef67d2d320790d37df19e749a10ee/crates/blockifier/src/execution/entry_point.rs#L234)):*
> ```XML
> 
>         // New transactions derive the step limit by the L1 gas resource bounds; deprecated
>         // transactions derive this value from the `max_fee`.
> ```

Please rename to "context" in all locations.


<!-- Sent from Reviewable.io -->

2023-11-13 10:08 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 234 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1060#-Nj6xwOXCp8pAvq3rqNL:-Nj78krSDGmEgH5ntY6Q:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/e010e9446a5ef67d2d320790d37df19e749a10ee/crates/blockifier/src/execution/entry_point.rs#L234)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please rename to "context" in all locations.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-13 12:20 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2023-11-13 12:42 UTC, elintul approved these changes
> Reviewed 2 of 8 files at r10, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1060)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2023-11-13 18:52 UTC, merged