Perform pre-validation checks in PyValidator.
starkware-libs/blockifier pull request #1061
Opened 2023-10-30 12:30 UTC by amosStarkware

2023-10-30 18:17 UTC, dorimedini-starkware requested changes
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 237 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-Ni0mM5c6hVkHBqi45dF:-Ni0mM5c6hVkHBqi45dG:b-e3lm6f) ([raw file](https://github.com/starkware-libs/blockifier/blob/4298e9fc005e84b1e292992519d5031810f4c8da/crates/blockifier/src/transaction/account_transaction.rs#L237)):*
> ```XML
>     fn check_fee_balance(
>         &self,
>         state: &mut dyn StateReader,
> ```

why is this needed...? non blocking



_Code quote:_
```XML
    fn check_fee_balance(
        &self,
        state: &mut dyn StateReader,
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-Ni0mZxU9UNpAN6pK5U3:-Ni0mZxU9UNpAN6pK5U4:bu4k1h1) ([raw file](https://github.com/starkware-libs/blockifier/blob/4298e9fc005e84b1e292992519d5031810f4c8da/crates/blockifier/src/transaction/errors.rs#L16)):*
> ```XML
>     CairoResourcesNotContainedInFeeCosts,
>     #[error("Actual fee ({actual_fee:?}) exceeded max fee ({max_fee:?}).")]
>     FeeTransferError { max_fee: Fee, actual_fee: Fee },
> ```

5 errors cut-pasted here, right? no diff?
___
*[`crates/blockifier/src/transaction/errors.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-Ni0mf8l5SHGcsGYkerX:-Ni0mf8l5SHGcsGYkerY:b-sj779x) ([raw file](https://github.com/starkware-libs/blockifier/blob/4298e9fc005e84b1e292992519d5031810f4c8da/crates/blockifier/src/transaction/errors.rs#L76)):*
> ```XML
> pub enum TransactionPreValidationError {
>     #[error(
>         "Invalid transaction nonce of contract at address {address:?}. Account nonce: \
> ```

InvalidNonce error cut-pasted without changes, correct?
___
*[`crates/native_blockifier/src/errors.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-Ni0mvITAVDqY5GZ4G8x:-Ni0mvITAVDqY5GZ4G8y:b-pe1nxb) ([raw file](https://github.com/starkware-libs/blockifier/blob/4298e9fc005e84b1e292992519d5031810f4c8da/crates/native_blockifier/src/errors.rs#L68)):*
> ```XML
>     (TransactionExecutionError, TransactionExecutionError, PyTransactionExecutionError),
>     (StorageError, papyrus_storage::StorageError, PyStorageError),
>     (TransactionPreValidationError, TransactionPreValidationError, PyTransactionPreValidationError)
> ```

breaking change; can you paste a link to a commit-bump PR?



_Code quote:_
```XML
(TransactionPreValidationError, TransactionPreValidationError, PyTransactionPreValidationError)
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-Ni0n6Pl2q_arSD3X2Gi:-Ni0n6Pl2q_arSD3X2Gj:b-jllz72) ([raw file](https://github.com/starkware-libs/blockifier/blob/4298e9fc005e84b1e292992519d5031810f4c8da/crates/native_blockifier/src/py_validator.rs#L95)):*
> ```XML
>         else {
>             panic!("L1 handlers should not be validated separately, only as part of execution")
>         };
> ```

please use `match` and explicitly give the two current variants of the `Transaction` enum (I know this is cut-pasted but let's make it better while we're here...)



_Code quote:_
```XML
        let Transaction::AccountTransaction(account_tx) = py_tx(&tx_type, tx, raw_contract_class)?
        else {
            panic!("L1 handlers should not be validated separately, only as part of execution")
        };
```


<!-- Sent from Reviewable.io -->

2023-10-31 14:38 UTC, dorimedini-starkware requested changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @elintul)

___
*[`crates/native_blockifier/src/py_validator.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-Ni0n6Pl2q_arSD3X2Gi:-Ni59jukC2ZJgVvaK1Rq:b-teltx1) ([raw file](https://github.com/starkware-libs/blockifier/blob/4298e9fc005e84b1e292992519d5031810f4c8da/crates/native_blockifier/src/py_validator.rs#L95)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

can you explain why using a match is better?
IMO `let else` works well here
</blockquote></details>

because `let else` doesn't guard you from the future. if someone adds another `NotAccountTransaction` variant to `Transaction`, the code will silently use the `else` case, whereas with `match` the compiler will complain that this variant is unhandled.
compilation error > hidden possible bugs


<!-- Sent from Reviewable.io -->

2023-11-01 07:57 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/py_validator.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-Ni0n6Pl2q_arSD3X2Gi:-Ni8si512DTHxU15v4ka:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/4298e9fc005e84b1e292992519d5031810f4c8da/crates/native_blockifier/src/py_validator.rs#L95)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

because `let else` doesn't guard you from the future. if someone adds another `NotAccountTransaction` variant to `Transaction`, the code will silently use the `else` case, whereas with `match` the compiler will complain that this variant is unhandled.
compilation error > hidden possible bugs
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-01 09:23 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-:-Ni9BRJ10WkgPmi8AcKG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2023-11-02 14:13 UTC, dorimedini-starkware approved these changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2023-11-05 06:31 UTC, elintul requested changes
> Reviewed 5 of 12 files at r1, 1 of 6 files at r2, 2 of 3 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: all files reviewed, 9 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 6 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NiT7xM2AaPsBCniWy3h:-NiT7xM2AaPsBCniWy3i:bqghww7) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9cb8f32dfcaf386c6a65bbf7395394db73e4e8b/crates/blockifier/src/transaction/account_transaction.rs#L6)):*
> ```XML
> use starknet_api::deprecated_contract_class::EntryPointType;
> use starknet_api::hash::StarkFelt;
> use starknet_api::transaction::{Calldata, Fee, TransactionVersion};
> ```

Remove `super::` usages, in all the code while at it.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 146 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NiT9E7zEQmG8KdIi6wO:-NiT9E7zEQmG8KdIi6wP:b-16rrrt) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L146)):*
> ```XML
>     pub fn perform_pre_validation_checks<S: StateReader>(
>         &self,
>         state: &mut TransactionalState<'_, S>,
> ```

Why this change specifically now?
Maybe `TransactionalState<'_, S>` wasn't really needed in the first place?



_Code quote:_
```XML
    pub fn perform_pre_validation_checks<S: StateReader>(
        &self,
        state: &mut TransactionalState<'_, S>,
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 620 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NiTA9ga6XSYiCbO_F2y:-NiTA9ga6XSYiCbO_F2z:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9cb8f32dfcaf386c6a65bbf7395394db73e4e8b/crates/blockifier/src/transaction/account_transaction.rs#L620)):*
> ```XML
> 
>         // Run validation and execution.
>         let ValidateExecuteCallInfo {
> ```





_Suggestion:_
```XML
        // Run validation and execution.
        let mut remaining_gas = Transaction::initial_gas();
        let ValidateExecuteCallInfo {
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 10 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NiT7dK12NJBSRBRt20t:-NiT7dK28N3EwpzjNXQ7:b4vbnbe) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9cb8f32dfcaf386c6a65bbf7395394db73e4e8b/crates/blockifier/src/transaction/errors.rs#L10)):*
> ```XML
> use crate::execution::errors::EntryPointExecutionError;
> use crate::state::errors::StateError;
> ```

Is this related to this PR? Is it just rearranging, or did the code change cause it?
Note that if not, it should have appeared in a separate (preliminary to this) PR.
___
*[`crates/blockifier/src/transaction/objects.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NiT8HxoC2LSEY1lw4rT:-NiT8HxoC2LSEY1lw4rU:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9cb8f32dfcaf386c6a65bbf7395394db73e4e8b/crates/blockifier/src/transaction/objects.rs#L22)):*
> ```XML
> pub type TransactionPreValidationResult<T> = Result<T, TransactionPreValidationError>;
> 
> pub type TransactionFeeResult<T> = Result<T, TransactionFeeError>;
> ```





_Suggestion:_
```XML
pub type TransactionExecutionResult<T> = Result<T, TransactionExecutionError>;
pub type TransactionFeeResult<T> = Result<T, TransactionFeeError>;
pub type TransactionPreValidationResult<T> = Result<T, TransactionPreValidationError>;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 555 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NiT9-GBAu_KHxs_xqhs:-NiT9-GBAu_KHxs_xqht:bu4mldb) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9cb8f32dfcaf386c6a65bbf7395394db73e4e8b/crates/blockifier/src/transaction/transactions_test.rs#L555)):*
> ```XML
>     // Test error.
>     assert_matches!(
>         execution_error,
> ```

Repeats a lot, consider a small utility, even a better mechanism the language has (ask Gilad/ChatGPT?).
___
*[`crates/native_blockifier/src/errors.rs` line 59 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NiT7TpW0aVbTAUEvawB:-NiT7TpW0aVbTAUEvawC:b-m4gde3) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9cb8f32dfcaf386c6a65bbf7395394db73e4e8b/crates/native_blockifier/src/errors.rs#L59)):*
> ```XML
> }
> 
> native_blockifier_errors!(
> ```

Please alphabetize while at it.



_Code quote:_
```XML
native_blockifier_errors!
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 97 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NiT68xLDzryX-CkyQIw:-NiT68xLDzryX-CkyQIx:b-wyamkm) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9cb8f32dfcaf386c6a65bbf7395394db73e4e8b/crates/native_blockifier/src/py_validator.rs#L97)):*
> ```XML
>                 panic!("L1 handlers should not be validated separately, only as part of execution")
>             }
>         };
> ```

Please instead add `py_account_tx` that will return `AccountTransaction` and `py_tx` will call it (will check "L1_HANDLER" first, then call `py_account_tx`).



_Code quote:_
```XML
        let tx_type: String = py_enum_name(tx, "tx_type")?;
        let account_tx = match py_tx(&tx_type, tx, raw_contract_class)? {
            Transaction::AccountTransaction(account_tx) => account_tx,
            Transaction::L1HandlerTransaction(_) => {
                panic!("L1 handlers should not be validated separately, only as part of execution")
            }
        };
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 105 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NiT6lIB1CgWW3phVq7g:-NiT6lIB1CgWW3phVq7h:b95qj0z) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9cb8f32dfcaf386c6a65bbf7395394db73e4e8b/crates/native_blockifier/src/py_validator.rs#L105)):*
> ```XML
>             &tx_executor.block_context,
>             true,
>             false,
> ```

Please give them names, I don't remember what these arguments represent.



_Code quote:_
```XML
            true,
            false,
```


<!-- Sent from Reviewable.io -->

2023-11-05 16:10 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: 6 of 14 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 146 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NiT9E7zEQmG8KdIi6wO:-NiVD34WEwGJWJmpFuhW:b-y5n37c) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef8131ff02a85d16a043184b0dc14f22566787b0/crates/blockifier/src/transaction/account_transaction.rs#L146)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why this change specifically now?
Maybe `TransactionalState<'_, S>` wasn't really needed in the first place?
</blockquote></details>

It was needed because `check_fee_balance` received a parameter of type `state: &mut TransactionalState<'_, S>`. I guess I could have done this last PR
___
*[`crates/blockifier/src/transaction/errors.rs` line 10 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NiT7dK12NJBSRBRt20t:-NiV4Zs32w_jqSc2FmBA:b-o8xr1x) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9cb8f32dfcaf386c6a65bbf7395394db73e4e8b/crates/blockifier/src/transaction/errors.rs#L10)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this related to this PR? Is it just rearranging, or did the code change cause it?
Note that if not, it should have appeared in a separate (preliminary to this) PR.
</blockquote></details>

It is related to the PR (and it's not just rearranging):
since `perform_pre_validation_checks()` is now also called from `PyValidator` it doesn't make sense for it to return errors of type `TransactionExecutionError`, so I added the type `TransactionPreValidationError`.
and since there are methods which are called during both pre-validation checks and during execution I added another Error type - `TransactionFeeError` - which is a variable of both `TransactionPreValidationError`, `TransactionExecutionError` (so it can be turned into either).
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 555 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NiT9-GBAu_KHxs_xqhs:-NiVAkTZBoKznQ2qGchx:b-rydrrk) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9cb8f32dfcaf386c6a65bbf7395394db73e4e8b/crates/blockifier/src/transaction/transactions_test.rs#L555)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Repeats a lot, consider a small utility, even a better mechanism the language has (ask Gilad/ChatGPT?).
</blockquote></details>

I think specifically in a test this is OK
___
*[`crates/native_blockifier/src/py_validator.rs` line 105 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NiT6lIB1CgWW3phVq7g:-NiVD1_24-JfVlw2biWx:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9cb8f32dfcaf386c6a65bbf7395394db73e4e8b/crates/native_blockifier/src/py_validator.rs#L105)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please give them names, I don't remember what these arguments represent.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-05 16:15 UTC, elintul requested changes
> Reviewed 2 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: 8 of 14 files reviewed, 8 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 107 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NiVG2t606yW9ekfiAnA:-NiVG2t606yW9ekfiAnB:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/native_blockifier/src/py_transaction.rs#L107)):*
> ```XML
>     py_tx: &PyAny,
>     raw_contract_class: Option<&str>,
> ) -> NativeBlockifierResult<Transaction> {
> ```





_Suggestion:_
```XML
AccountTransaction
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 123 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NiVG-_h5E8Q6m9_uVVm:-NiVG-_h5E8Q6m9_uVVn:b-9lcozs) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/native_blockifier/src/py_transaction.rs#L123)):*
> ```XML
>             Ok(Transaction::AccountTransaction(invoke_tx))
>         }
>         "L1_HANDLER" => Ok(Transaction::L1HandlerTransaction(py_l1_handler(py_tx)?)),
> ```

Remove, this is not an account transaction.



_Code quote:_
```XML
"L1_HANDLER" => Ok(Transaction::L1HandlerTransaction(py_l1_handler(py_tx)?)),
```


<!-- Sent from Reviewable.io -->

2023-11-05 16:46 UTC, dorimedini-starkware reviewed
> Reviewed 6 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: all files reviewed, 8 unresolved discussions (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2023-11-07 13:07 UTC, elintul requested changes
> Reviewed 6 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: all files reviewed, 8 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 146 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-Nidshsa0AEkxNEoRX4d:-Nidshsa0AEkxNEoRX4e:bkwy8kv) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/blockifier/src/transaction/account_transaction.rs#L146)):*
> ```XML
> 
>     // The nonce is incremented during these checks.
>     pub fn perform_pre_validation_checks<S: State + StateReader>(
> ```

Why do we need both? `State` implements `StateReader`.



_Code quote:_
```XML
State + StateReader
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 109 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NidtDwp6SO_SDqqxbdX:-NidtDwp6SO_SDqqxbdY:b-te1ak2) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/native_blockifier/src/py_validator.rs#L109)):*
> ```XML
>             strict_nonce_check,
>         )?;
>         let (optional_call_info, actual_fee) = tx_executor.validate(remaining_gas, &account_tx)?;
> ```

Add a blank line above.



_Code quote:_
```XML
let (optional_call_info, actual_fee) = tx_executor.validate(remaining_gas, &account_tx)?;
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NidtGTyDinmpFd0zt32:-NidtGTyDinmpFd0zt33:b-te1ak2) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/native_blockifier/src/py_validator.rs#L111)):*
> ```XML
>         let (optional_call_info, actual_fee) = tx_executor.validate(remaining_gas, &account_tx)?;
>         let py_optional_call_info = optional_call_info.map(PyCallInfo::from);
>         Ok((py_optional_call_info, actual_fee.0))
> ```

Add a blank line above.



_Code quote:_
```XML
Ok((py_optional_call_info, actual_fee.0))
```


<!-- Sent from Reviewable.io -->

2023-11-07 15:13 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: all files reviewed, 9 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NieKwfbA63n0aM-u8rI:-NieKwfc68kdL2rjWwxm:batinv2) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/native_blockifier/src/transaction_executor.rs#L111)):*
> ```XML
>         // calculating the fees for validation.
>         // Note: This assumes that the state is reset between calls to validate.
>         self.state.increment_nonce(account_tx_context.sender_address())?;
> ```

You might want to delete it, no?



_Code quote:_
```XML
        // For fee charging purposes, the nonce-increment cost is taken into consideration when
        // calculating the fees for validation.
        // Note: This assumes that the state is reset between calls to validate.
        self.state.increment_nonce(account_tx_context.sender_address())?;
```


<!-- Sent from Reviewable.io -->

2023-11-08 15:38 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: all files reviewed, 9 unresolved discussions (waiting on @amosStarkware and @elintul)

___
*[`crates/native_blockifier/src/py_validator.rs` line 85 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NijL58SA0DkisTt9AVe:-NijL58SA0DkisTt9AVf:baft7gx) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/native_blockifier/src/py_validator.rs#L85)):*
> ```XML
> 
>     #[pyo3(signature = (tx, remaining_gas, raw_contract_class))]
>     pub fn validate(
> ```

IIUC you should not edit this method. It is called in the `version < 3` flow.
We want to create a new method, [PTAL](https://reviewable.io/reviews/starkware-libs/blockifier/1103).


<!-- Sent from Reviewable.io -->

2023-11-09 10:27 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: 4 of 20 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 6 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NiT7xM2AaPsBCniWy3h:-NinXmxW1U7Bsm6vTRIl:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9cb8f32dfcaf386c6a65bbf7395394db73e4e8b/crates/blockifier/src/transaction/account_transaction.rs#L6)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Remove `super::` usages, in all the code while at it.
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 146 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-Nidshsa0AEkxNEoRX4d:-NijXGYm8l_QajjxeePy:b-fe1uvu) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/blockifier/src/transaction/account_transaction.rs#L146)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why do we need both? `State` implements `StateReader`.
</blockquote></details>

rust doesn't allow upcasting here:
`cannot cast \`dyn state\_api::State\` to \`dyn StateReader\`, trait upcasting coercion is experimental
see issue #65991 <[https://github.com/rust-lang/rust/issues/65991](https://github.com/rust-lang/rust/issues/65991)\> for more information
required when coercing \`&mut dyn state\_api::State\` into \`&mut dyn StateReader\``
___
*[`crates/native_blockifier/src/py_transaction.rs` line 107 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NiVG2t606yW9ekfiAnA:-NinJVeO3QzX8wFgeVYi:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/native_blockifier/src/py_transaction.rs#L107)):*
> ```XML
>     py_tx: &PyAny,
>     raw_contract_class: Option<&str>,
> ) -> NativeBlockifierResult<Transaction> {
> ```

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 123 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NiVG-_h5E8Q6m9_uVVm:-NinJWZW2E5Ns41oZo-K:b-kypor4) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/native_blockifier/src/py_transaction.rs#L123)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Remove, this is not an account transaction.
</blockquote></details>

I must have pasted `py_tx` and then forgot about it. sorry.
___
*[`crates/native_blockifier/src/py_validator.rs` line 97 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NiT68xLDzryX-CkyQIw:-NinJmj--Wl_QFTg6Cv2:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9cb8f32dfcaf386c6a65bbf7395394db73e4e8b/crates/native_blockifier/src/py_validator.rs#L97)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please instead add `py_account_tx` that will return `AccountTransaction` and `py_tx` will call it (will check "L1_HANDLER" first, then call `py_account_tx`).
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_validator.rs` line 85 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NijL58SA0DkisTt9AVe:-NinL7ht8AC1q-HGwMYC:b-xnmrbm) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/native_blockifier/src/py_validator.rs#L85)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

IIUC you should not edit this method. It is called in the `version < 3` flow.
We want to create a new method, [PTAL](https://reviewable.io/reviews/starkware-libs/blockifier/1103).
</blockquote></details>

thanks, made this blocking
___
*[`crates/native_blockifier/src/py_validator.rs` line 109 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NidtDwp6SO_SDqqxbdX:-NinMBto5z5n0L1llZ-t:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/native_blockifier/src/py_validator.rs#L109)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a blank line above.
</blockquote></details>

Done
___
*[`crates/native_blockifier/src/py_validator.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NidtGTyDinmpFd0zt32:-NinME-V8y9D8NdrC0c4:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/native_blockifier/src/py_validator.rs#L111)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a blank line above.
</blockquote></details>

Done
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NieKwfbA63n0aM-u8rI:-NinNF1sBwHFlMCCoAG7:bng5z3u) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/native_blockifier/src/transaction_executor.rs#L111)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

You might want to delete it, no?
</blockquote></details>

Good point! thanks


<!-- Sent from Reviewable.io -->

2023-11-09 10:43 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: 4 of 20 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NieKwfbA63n0aM-u8rI:-NindgTJ1_eurGckypT2:b-vroemb) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/native_blockifier/src/transaction_executor.rs#L111)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Good point! thanks
</blockquote></details>

I retracted it after adding the previous comment. As long as we don't change the `version <3` flow, this is necessary.
However, this raises a problem: if the nonce value is used in `__validate__`, it may lead to a transaction failure.


<!-- Sent from Reviewable.io -->

2023-11-09 10:43 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: 4 of 20 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NieKwfbA63n0aM-u8rI:-NinfYWd00LCdv5HtzvC:basyhic) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/native_blockifier/src/transaction_executor.rs#L111)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I retracted it after adding the previous comment. As long as we don't change the `version <3` flow, this is necessary.
However, this raises a problem: if the nonce value is used in `__validate__`, it may lead to a transaction failure.
</blockquote></details>

Not resolved.


<!-- Sent from Reviewable.io -->

2023-11-09 10:50 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: 4 of 20 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware, @elin, @elintul, and @noaov1)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NieKwfbA63n0aM-u8rI:-Ninh2vhBiKTp7pyXvUo:b-7zcfqc) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/native_blockifier/src/transaction_executor.rs#L111)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Not resolved.
</blockquote></details>

@elintul 


<!-- Sent from Reviewable.io -->

2023-11-09 11:01 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: 4 of 20 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NieKwfbA63n0aM-u8rI:-Ninhm0F-4ZJE8v7cxM4:b-6va795) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/native_blockifier/src/transaction_executor.rs#L111)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

@elintul
</blockquote></details>

However2- In python we increment the nonce after the `__validate__` (see [here](https://github.com/starkware-industries/starkware/blob/b53c705ff18238584ae304635a4b7e31f497939e/src/starkware/starknet/business_logic/transaction/state_objects.py#L70)), so I don't know if it matters. 


<!-- Sent from Reviewable.io -->

2023-11-09 11:15 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: 4 of 20 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NieKwfbA63n0aM-u8rI:-NinmY00C-V0GoZehlV5:b-w3nf1o) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/native_blockifier/src/transaction_executor.rs#L111)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

However2- In python we increment the nonce after the `__validate__` (see [here](https://github.com/starkware-industries/starkware/blob/b53c705ff18238584ae304635a4b7e31f497939e/src/starkware/starknet/business_logic/transaction/state_objects.py#L70)), so I don't know if it matters.
</blockquote></details>

And it indeed does not matter, since we read the nonce value from the transaction :)


<!-- Sent from Reviewable.io -->

2023-11-09 12:09 UTC, dorimedini-starkware reviewed
> Reviewed 12 of 16 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: all files reviewed, 8 unresolved discussions (waiting on @amosStarkware, @elintul, and @noaov1)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 11 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NinyPhV1x1224Jv4xV8:-NinyPhV1x1224Jv4xV9:b-ab67xo) ([raw file](https://github.com/starkware-libs/blockifier/blob/cd280d033fc676944111a2ba42f076dde04df95d/crates/blockifier/src/state/cached_state_test.rs#L11)):*
> ```XML
> 
> use crate::block_context::BlockContext;
> use crate::state::cached_state::*;
> ```

why is this `*` needed and we don't `use` explicit objects...? non-blocking



_Code quote:_
```XML
use crate::state::cached_state::*;
```


<!-- Sent from Reviewable.io -->

2023-11-12 10:34 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: all files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @noaov1)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 11 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NinyPhV1x1224Jv4xV8:-NiovZRw3LEIToNDtoiX:bquca6a) ([raw file](https://github.com/starkware-libs/blockifier/blob/cd280d033fc676944111a2ba42f076dde04df95d/crates/blockifier/src/state/cached_state_test.rs#L11)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this `*` needed and we don't `use` explicit objects...? non-blocking
</blockquote></details>

IDK, I just removed the use of `super`


<!-- Sent from Reviewable.io -->

2023-11-12 10:38 UTC, elintul requested changes
> Reviewed 3 of 16 files at r6, 8 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: 19 of 20 files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 146 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-Nidshsa0AEkxNEoRX4d:-NioE99ZCj81Rd7EcitZ:b-mrdokv) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/blockifier/src/transaction/account_transaction.rs#L146)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

rust doesn't allow upcasting here:
`cannot cast \`dyn state\_api::State\` to \`dyn StateReader\`, trait upcasting coercion is experimental
see issue #65991 <[https://github.com/rust-lang/rust/issues/65991](https://github.com/rust-lang/rust/issues/65991)\> for more information
required when coercing \`&mut dyn state\_api::State\` into \`&mut dyn StateReader\``
</blockquote></details>

Can you simply explain the issue? (Unblocking)


<!-- Sent from Reviewable.io -->

2023-11-12 10:38 UTC, elintul reviewed
> Reviewed 2 of 16 files at r6, 1 of 9 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @noaov1)



<!-- Sent from Reviewable.io -->

2023-11-12 10:39 UTC, elintul reviewed
> Reviewed 3 of 16 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @noaov1)



<!-- Sent from Reviewable.io -->

2023-11-12 10:56 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: 19 of 20 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @noaov1)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NieKwfbA63n0aM-u8rI:-Nj2A3qu6j8fvcdh_SJX:be6m84o) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/native_blockifier/src/transaction_executor.rs#L111)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

And it indeed does not matter, since we read the nonce value from the transaction :)
</blockquote></details>

@noaov1 should I add a TODO to remove this increment?


<!-- Sent from Reviewable.io -->

2023-11-12 10:56 UTC, amosStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: 19 of 20 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 146 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-Nidshsa0AEkxNEoRX4d:-Nj2AEVj41afnXTbscJK:bz4tm53) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/blockifier/src/transaction/account_transaction.rs#L146)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you simply explain the issue? (Unblocking)
</blockquote></details>

rust doesn't allow using `State` as `StateReader`


<!-- Sent from Reviewable.io -->

2023-11-12 13:31 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: 16 of 20 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 111 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NieKwfbA63n0aM-u8rI:-Nj2iWaYCnp8It83ZFJp:b9y1bfs) ([raw file](https://github.com/starkware-libs/blockifier/blob/172fb63a8f6c84b06348d263de8231752a641ec3/crates/native_blockifier/src/transaction_executor.rs#L111)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

@noaov1 should I add a TODO to remove this increment?
</blockquote></details>

Yes please


<!-- Sent from Reviewable.io -->

2023-11-12 14:21 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2023-11-13 04:37 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-:-Nj5y6UX-klVyTws3WUy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-11-13 07:24 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-11-13 09:28 UTC, elintul approved these changes
> Reviewed 7 of 7 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-11-13 12:13 UTC, dorimedini-starkware submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-11-14 08:28 UTC, dorimedini-starkware approved these changes
> Reviewed 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-11-14 12:11 UTC, elintul submitted a review, later dismissed
> Reviewed 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-11-15 08:47 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/native_blockifier/src/py_validator.rs` line 117 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NjDF0zVE4UakDtE5p1k:-NjDF0zVE4UakDtE5p1l:b3kqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/65ecbcf5c51d79fc1a168813d769786c00b900be/crates/native_blockifier/src/py_validator.rs#L117)):*
> ```XML
> 
>         let strict_nonce_check = false;
>         let charge_fee = true;
> ```

.



_Suggestion:_
```XML
        // A Flag indicating to perform the fee and balance related validations checks.
        let charge_fee = true;
```


<!-- Sent from Reviewable.io -->

2023-11-15 12:18 UTC, elintul submitted a review, later dismissed
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/native_blockifier/src/py_validator.rs` line 118 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1061#-NjHuRew3BGxqaaafOG0:-NjHuRexArtk3EMx2kUr:bnw2emp) ([raw file](https://github.com/starkware-libs/blockifier/blob/fb25c5d2cd0b70abc564395497fbffaa6a913e4a/crates/native_blockifier/src/py_validator.rs#L118)):*
> ```XML
>         let account_tx = py_account_tx(&tx_type, tx, raw_contract_class)?;
> 
>         // `DeployAccount` transactions should be fully executed (including pre-validation and
> ```

x2
Add in the end: `, since the constructor is ran before validation. `.



_Suggestion:_
```XML
Deploy account
```


<!-- Sent from Reviewable.io -->

2023-11-15 12:24 UTC, elintul approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1061)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)



<!-- Sent from Reviewable.io -->

2023-11-15 14:25 UTC, merged