Add calldata generator + one usage
starkware-libs/blockifier pull request #1066
Opened 2023-11-01 07:56 UTC by giladchase

Usage:
```rust
create_calldata(
    contract_address: <ContractAddress>,
    entry_point_name: "some_entry_point_name",
    entry_point_args: [
	starkfelt_arg_1,
	starkfelt_arg_2,
	...
    ]);
```

To be used instead of this pattern:
```rust
    calldata: calldata![
	*contract_address.0.key(),                      // Contract address.
	selector_from_name("some_entry_point_name").0,  // EP selector.
	stark_felt!(2_u8),                      	// Calldata length.
	stark_felt!(2_u8)                       	// Calldata: arg1.
	stark_felt!(3_u8)                       	// Calldata: arg2.
    ]
```

2023-11-01 08:00 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1066)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/test_utils.rs` line 679 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-Ni8sjCd1MLNYarZ5s7V:-Ni8sjCd1MLNYarZ5s7W:b-o3j0kf) ([raw file](https://github.com/starkware-libs/blockifier/blob/30499a91b30592a5fcbea474132f5e629ee8cdf5/crates/blockifier/src/test_utils.rs#L679)):*
> ```XML
> #[rustfmt::skip]
> #[macro_export]
> macro_rules! create_calldata {
> ```

Only reason this is a macro is to get kwargs.

The other alternative considered was using a struct like `CallDataGenerator {contract_address: ...,}.create()`, but it looks a bit clumsy.
The struct option also allows the kwargs to be passed out of order, while the macro doesn't allow this, but i consider that a feature here (the current order makes the most sense).


<!-- Sent from Reviewable.io -->

2023-11-01 08:07 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1066)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/test_utils.rs` line 693 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-Ni8udi7DL3vj5qlOhJp:-Ni8udi89TW_aFQBSrUz:b-k8ggn7) ([raw file](https://github.com/starkware-libs/blockifier/blob/8fc33677f32c9d8d9327c79516e81410ad2a8169/crates/blockifier/src/test_utils.rs#L693)):*
> ```XML
>         $contract_address:expr,entry_point_name:
>         $entry_point_name:expr,entry_point_args:
>         $entry_point_args:expr $(,)*
> ```

This should have looked like below, but rustfmt has a bug which forces this, and also a bug with [using rustfmt::skip with macros](https://github.com/rust-lang/rustfmt/issues/4449).



_Suggestion:_
```XML
        contract_address: $contract_address:expr,
        entry_point_name: $entry_point_name:expr,
        entry_point_args: $entry_point_args:expr $(,)*
```


<!-- Sent from Reviewable.io -->

2023-11-01 08:09 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1066)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/test_utils.rs` line 679 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-Ni8sjCd1MLNYarZ5s7V:-Ni8uVBB1Dsp1LQcPAbf:bntro2r) ([raw file](https://github.com/starkware-libs/blockifier/blob/30499a91b30592a5fcbea474132f5e629ee8cdf5/crates/blockifier/src/test_utils.rs#L679)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Only reason this is a macro is to get kwargs.

The other alternative considered was using a struct like `CallDataGenerator {contract_address: ...,}.create()`, but it looks a bit clumsy.
The struct option also allows the kwargs to be passed out of order, while the macro doesn't allow this, but i consider that a feature here (the current order makes the most sense).
</blockquote></details>

I prefer a rust function (not macro) with inputs `ContractAddress, &str, [StarkFelt]`; var-args are fun but passing an array is fine IMO.
Y macro?


<!-- Sent from Reviewable.io -->

2023-11-01 08:15 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1066)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/test_utils.rs` line 679 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-Ni8sjCd1MLNYarZ5s7V:-Ni8wEhE83XqhalT4mvI:bn00vmm) ([raw file](https://github.com/starkware-libs/blockifier/blob/30499a91b30592a5fcbea474132f5e629ee8cdf5/crates/blockifier/src/test_utils.rs#L679)):*
>Y macro?

What i wrote above :grimacing: 
If we use a function, we'll still have to write comments near every arg like:
```rust
/// create_calldata(
///     contract_address,
///     "some_entry_point_name" // EP name
///     [                                             // EP args
///         starkfelt_arg_1,
///         starkfelt_arg_2,
///         ...
///     ]
/// );
```
Since this will be used quite heavily in tests (hopefully :pleading_face: ) it should be as easy to use as possible and with as little boilerplate.


<!-- Sent from Reviewable.io -->

2023-11-01 09:02 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1066)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/test_utils.rs` line 679 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-Ni8sjCd1MLNYarZ5s7V:-Ni96XyQCp_FdeQj_fzr:bu0ydtj) ([raw file](https://github.com/starkware-libs/blockifier/blob/30499a91b30592a5fcbea474132f5e629ee8cdf5/crates/blockifier/src/test_utils.rs#L679)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

>Y macro?

What i wrote above :grimacing: 
If we use a function, we'll still have to write comments near every arg like:
```rust
/// create_calldata(
///     contract_address,
///     "some_entry_point_name" // EP name
///     [                                             // EP args
///         starkfelt_arg_1,
///         starkfelt_arg_2,
///         ...
///     ]
/// );
```
Since this will be used quite heavily in tests (hopefully :pleading_face: ) it should be as easy to use as possible and with as little boilerplate.
</blockquote></details>

Fine, you win :grimacing: 
Done.


<!-- Sent from Reviewable.io -->

2023-11-01 09:26 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1066)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/test_utils.rs` line 684 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-Ni9BsFdCIvQdtYSJVbN:-Ni9BsFdCIvQdtYSJVbO:b-fx1mjv) ([raw file](https://github.com/starkware-libs/blockifier/blob/ffb8473f5c4a9500b5d57fe1b67fe69c7976670a/crates/blockifier/src/test_utils.rs#L684)):*
> ```XML
> ) -> Calldata {
>     let n_args = u128::try_from(entry_point_args.len()).expect("Calldata too big");
>     let n_args = StarkFelt::try_from(n_args).unwrap();
> ```

`n_args` is a u128, StarkFelt has a fail-free `from` in this case



_Suggestion:_
```XML
StarkFelt::from(n_args);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 151 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-Ni9C6vm1kFup2Wu0rXW:-Ni9C6vm1kFup2Wu0rXX:b-h6fnpp) ([raw file](https://github.com/starkware-libs/blockifier/blob/ffb8473f5c4a9500b5d57fe1b67fe69c7976670a/crates/blockifier/src/transaction/account_transactions_test.rs#L151)):*
> ```XML
>                     stark_felt!(2_u8),        // constructor calldata length.
>                     stark_felt!(1_u8),        // constructor calldata: address.
>                     stark_felt!(1_u8)         // constructor calldata: value.
> ```

why did you de-capitalize the `c`s?



_Suggestion:_
```XML
                    salt.0,                   // Contract address salt.
                    stark_felt!(2_u8),        // Constructor calldata length.
                    stark_felt!(1_u8),        // Constructor calldata: address.
                    stark_felt!(1_u8)         // Constructor calldata: value.
```


<!-- Sent from Reviewable.io -->

2023-11-01 09:52 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1066)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/test_utils.rs` line 684 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-Ni9BsFdCIvQdtYSJVbN:-Ni9E9hT6_gbT-j9DlVA:b-nyvhxz) ([raw file](https://github.com/starkware-libs/blockifier/blob/ffb8473f5c4a9500b5d57fe1b67fe69c7976670a/crates/blockifier/src/test_utils.rs#L684)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`n_args` is a u128, StarkFelt has a fail-free `from` in this case
</blockquote></details>

`n_args` is usize :sob: 
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 151 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-Ni9C6vm1kFup2Wu0rXW:-Ni9HKq6AeeawqXelqCb:bwvyox4) ([raw file](https://github.com/starkware-libs/blockifier/blob/ffb8473f5c4a9500b5d57fe1b67fe69c7976670a/crates/blockifier/src/transaction/account_transactions_test.rs#L151)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why did you de-capitalize the `c`s?
</blockquote></details>

Reverted


<!-- Sent from Reviewable.io -->

2023-11-01 10:05 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1066)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/test_utils.rs` line 684 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-Ni9BsFdCIvQdtYSJVbN:-Ni9Kzvg0r2z3EYR0fBV:b-vguw9a) ([raw file](https://github.com/starkware-libs/blockifier/blob/ffb8473f5c4a9500b5d57fe1b67fe69c7976670a/crates/blockifier/src/test_utils.rs#L684)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

`n_args` is usize :sob:
</blockquote></details>

`n_args` is a result of `u128::try_from(...).expect(...)`.
how is it a usize?


<!-- Sent from Reviewable.io -->

2023-11-01 11:23 UTC, elintul submitted a review, later dismissed
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1066)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-Ni9c-uFDNqixMr2Fk0z:-Ni9c-uG8dmRJazOvsuB:b-y6fob3) (no related file):*
Wanna use your function everywhere?

___


<!-- Sent from Reviewable.io -->

2023-11-01 16:45 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1066)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 684 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-Ni9BsFdCIvQdtYSJVbN:-NiAlOf72VCELJ_u-fQk:b-3muclz) ([raw file](https://github.com/starkware-libs/blockifier/blob/ffb8473f5c4a9500b5d57fe1b67fe69c7976670a/crates/blockifier/src/test_utils.rs#L684)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`n_args` is a result of `u128::try_from(...).expect(...)`.
how is it a usize?
</blockquote></details>

Oh i missread, srry.


<!-- Sent from Reviewable.io -->

2023-11-01 17:41 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1066)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-Ni9c-uFDNqixMr2Fk0z:-NiAyQyH9AXM8u0mVjOz:bb6un1j) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Wanna use your function everywhere?
</blockquote></details>

Done

___


<!-- Sent from Reviewable.io -->

2023-11-02 09:08 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 5 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1066)* status: all files reviewed, 8 unresolved discussions (waiting on @giladchase)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 516 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-NiEFtjcAbFX3owHf6G8:-NiEFtjcAbFX3owHf6G9:b4og3ck) ([raw file](https://github.com/starkware-libs/blockifier/blob/66db7b8e62f0d4527b7aeddce53bca83b001d773/crates/blockifier/src/execution/entry_point_test.rs#L516)):*
> ```XML
>     let calldata = create_calldata(
>         contract_address!(TEST_CONTRACT_ADDRESS_2),
>         "test_call_contract",
> ```

`"test_call_contract"` string is written twice.
I would either delete `outer_entry_point_selector` if possible, or define `call_contract_function_name: &str` variable for it.
non-blocking



_Code quote:_
```XML
    let outer_entry_point_selector = selector_from_name("test_call_contract");
    let inner_entry_point_selector = selector_from_name("foo");
    let calldata = create_calldata(
        contract_address!(TEST_CONTRACT_ADDRESS_2),
        "test_call_contract",
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 224 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-NiEGAix7Z7ykZ9FR6L3:-NiEGAix7Z7ykZ9FR6L4:b-cabdg4) ([raw file](https://github.com/starkware-libs/blockifier/blob/66db7b8e62f0d4527b7aeddce53bca83b001d773/crates/blockifier/src/transaction/account_transactions_test.rs#L224)):*
> ```XML
>                 &[
>                 stark_felt!(2_u8)          // Calldata: num.
>                 ]
> ```

one line?



_Suggestion:_
```XML
                &[stark_felt!(2_u8)]       // Calldata: num.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 377 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-NiEGZGz1L_BibAbmEoj:-NiEGZGz1L_BibAbmEok:b-8mzuch) ([raw file](https://github.com/starkware-libs/blockifier/blob/66db7b8e62f0d4527b7aeddce53bca83b001d773/crates/blockifier/src/transaction/account_transactions_test.rs#L377)):*
> ```XML
>                 "return_result",
>                 &[
>                     stark_felt!(1_u8),                      // Calldata length.
> ```

no length :)
How does the test pass when you pass too many args...?
also, make it a one-liner
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 420 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-NiEH8K8048iuil6-Mi6:-NiEH8K8048iuil6-Mi7:bfonorc) ([raw file](https://github.com/starkware-libs/blockifier/blob/66db7b8e62f0d4527b7aeddce53bca83b001d773/crates/blockifier/src/transaction/account_transactions_test.rs#L420)):*
> ```XML
>         &[
>             *contract_address.0.key(), // Calldata: raw contract address.
>             selector_from_name("recursive_syscall").0, // Calldata: raw selector.
> ```

bummer on the dup here... put `"recursive_syscall"` in a variable?



_Code quote:_
```XML
        "recursive_syscall",
        &[
            *contract_address.0.key(), // Calldata: raw contract address.
            selector_from_name("recursive_syscall").0, // Calldata: raw selector.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 444 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-NiEHEOw1l7f89jFZ6WD:-NiEHEOw1l7f89jFZ6WE:b-bi96n9) ([raw file](https://github.com/starkware-libs/blockifier/blob/66db7b8e62f0d4527b7aeddce53bca83b001d773/crates/blockifier/src/transaction/account_transactions_test.rs#L444)):*
> ```XML
>         &[
>             *contract_address.0.key(), // Calldata: raw contract address.
>             selector_from_name("recursive_syscall").0, // Calldata: raw selector.
> ```

variable for `"recursive_syscall"`?



_Code quote:_
```XML
        "recursive_syscall",
        &[
            *contract_address.0.key(), // Calldata: raw contract address.
            selector_from_name("recursive_syscall").0, // Calldata: raw selector.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 650 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-NiEHKu-AsMWoydQU-FG:-NiEHKu-AsMWoydQU-FH:b-cabdg4) ([raw file](https://github.com/starkware-libs/blockifier/blob/66db7b8e62f0d4527b7aeddce53bca83b001d773/crates/blockifier/src/transaction/account_transactions_test.rs#L650)):*
> ```XML
>                 &[
>                     stark_felt!(depth)                   // Calldata: recursion depth.
>                 ]
> ```

one line?



_Code quote:_
```XML
                &[
                    stark_felt!(depth)                   // Calldata: recursion depth.
                ]
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 892 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-NiEHMzy-N2pyl14pWrm:-NiEHMzy-N2pyl14pWrn:b-cabdg4) ([raw file](https://github.com/starkware-libs/blockifier/blob/66db7b8e62f0d4527b7aeddce53bca83b001d773/crates/blockifier/src/transaction/account_transactions_test.rs#L892)):*
> ```XML
>         &[
>             stark_felt!(25_u8), // Calldata: arg.
>         ],
> ```

one line?



_Code quote:_
```XML
        &[
            stark_felt!(25_u8), // Calldata: arg.
        ],
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 275 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-NiEHVCiDPpJbREcnCCS:-NiEHVCiDPpJbREcnCCT:b-cabdg4) ([raw file](https://github.com/starkware-libs/blockifier/blob/66db7b8e62f0d4527b7aeddce53bca83b001d773/crates/blockifier/src/transaction/transactions_test.rs#L275)):*
> ```XML
>         &[
>             stark_felt!(2_u8), // Calldata: num.
>         ],
> ```

one line?



_Code quote:_
```XML
        &[
            stark_felt!(2_u8), // Calldata: num.
        ],
```


<!-- Sent from Reviewable.io -->

2023-11-02 10:49 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1066)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 377 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-NiEGZGz1L_BibAbmEoj:-NiEMvXlAlG0OO2W6rmO:b-brwwmu) ([raw file](https://github.com/starkware-libs/blockifier/blob/66db7b8e62f0d4527b7aeddce53bca83b001d773/crates/blockifier/src/transaction/account_transactions_test.rs#L377)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no length :)
How does the test pass when you pass too many args...?
also, make it a one-liner
</blockquote></details>

Done, it his MaxFeeTooLow before it gets to inspect the calldata: `check_fee_balance` is called before `run_or_revert`.
(I can change the calldata to whatever and it still passes)
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 420 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-NiEH8K8048iuil6-Mi6:-NiEcUEA8Mu3S7TtEOKP:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/66db7b8e62f0d4527b7aeddce53bca83b001d773/crates/blockifier/src/transaction/account_transactions_test.rs#L420)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

bummer on the dup here... put `"recursive_syscall"` in a variable?
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 444 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-NiEHEOw1l7f89jFZ6WD:-NiEcUsX6wEq0VTikxIy:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/66db7b8e62f0d4527b7aeddce53bca83b001d773/crates/blockifier/src/transaction/account_transactions_test.rs#L444)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

variable for `"recursive_syscall"`?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-02 13:49 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1066#-:-NiFHsVx6W-PvUvaddoC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-11-02 14:10 UTC, merged