Add pre-validation checks to `PyValidator`
starkware-libs/blockifier pull request #1128
Opened 2023-11-13 15:15 UTC by giladchase

2023-11-14 11:12 UTC, elintul requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1128)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/native_blockifier/src/py_validator.rs` line 157 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-NjCWEWI-SIkgOQmBlzv:-NjCWEWI-SIkgOQmBlzw:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/686f0788aa9471139648a1ede85b47ec2cce85f3/crates/native_blockifier/src/py_validator.rs#L157)):*
> ```XML
>     // All checks that should be done before running __validate__.
>     // Returns true if and only if the pre validation checks succeeded.
>     fn pre_validation_checks(
> ```





_Suggestion:_
```XML
    // All checks that should be done before excuting `__validate__`.
    // Returns true if and only if the pre validation checks succeeded.
    fn perform_pre_validation_checks(
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 166 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-NjCWK3c3oNZ0kz73uLm:-NjCWK3c3oNZ0kz73uLn:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/686f0788aa9471139648a1ede85b47ec2cce85f3/crates/native_blockifier/src/py_validator.rs#L166)):*
> ```XML
>     }
> 
>     fn should_do_validations(
> ```





_Suggestion:_
```XML
should_skip_validate_execution
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 176 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-NjCWN-Z70osKrikRDA0:-NjCWN-_1RRHUW3L2-DQ:bxaoz50) ([raw file](https://github.com/starkware-libs/blockifier/blob/686f0788aa9471139648a1ede85b47ec2cce85f3/crates/native_blockifier/src/py_validator.rs#L176)):*
> ```XML
>         else {
>             panic!("L1 handlers should not be validated separately, only as part of execution")
>         };
> ```

Please use `py_account_tx`.



_Code quote:_
```XML
        let tx_type: String = py_enum_name(tx, "tx_type")?;
        let Transaction::AccountTransaction(account_tx) = py_tx(&tx_type, tx, raw_contract_class)?
        else {
            panic!("L1 handlers should not be validated separately, only as part of execution")
        };
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 184 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-NjCWW3X-GxaR2x60V70:-NjCWW3X-GxaR2x60V71:bfq11o1) ([raw file](https://github.com/starkware-libs/blockifier/blob/686f0788aa9471139648a1ede85b47ec2cce85f3/crates/native_blockifier/src/py_validator.rs#L184)):*
> ```XML
>         // Check if deploy account was submitted but not processed yet. If so, then skip
>         // validations for subsequent transactions for a better user experience.
>         // (Otherwise they'll fail solely because the deploy account hasn't been processed yet.)
> ```

Move to docstring?



_Suggestion:_
```XML
        // Check if deploy account was submitted but not processed yet. If so, then skip
        // validations for subsequent transactions for a better user experience.
        // (they will otherwise fail solely because the deploy account hasn't been processed yet).
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 190 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-NjCWlDg569-pWB2KOJU:-NjCWlDg569-pWB2KOJV:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/686f0788aa9471139648a1ede85b47ec2cce85f3/crates/native_blockifier/src/py_validator.rs#L190)):*
> ```XML
>         let nonce_small_enough_to_qualify_for_validation_skip =
>             tx_nonce <= self.max_nonce_for_validation_skip;
>         let deploy_account_has_been_sent = deploy_account_tx_hash.is_some();
> ```





_Suggestion:_
```XML
        let deploy_account_not_processed = deploy_account_tx_hash.is_some() && nonce == Nonce(StarkFelt::ZERO);
        let is_post_deploy_nonce = Nonce(StarkFelt::ONE) <= tx_nonce;
        let nonce_small_enough_to_qualify_for_validation_skip =
            tx_nonce <= self.max_nonce_for_validation_skip;
```


<!-- Sent from Reviewable.io -->

2023-11-15 15:01 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1128)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/native_blockifier/src/py_validator.rs` line 166 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-NjCWK3c3oNZ0kz73uLm:-NjIT0Zz35QSNVMUzRY4:b-rl0p20) ([raw file](https://github.com/starkware-libs/blockifier/blob/686f0788aa9471139648a1ede85b47ec2cce85f3/crates/native_blockifier/src/py_validator.rs#L166)):*
> ```XML
>     }
> 
>     fn should_do_validations(
> ```

:facepalm:  tnx
___
*[`crates/native_blockifier/src/py_validator.rs` line 190 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-NjCWlDg569-pWB2KOJU:-NjIUNIY7jTufT8m-rpk:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/686f0788aa9471139648a1ede85b47ec2cce85f3/crates/native_blockifier/src/py_validator.rs#L190)):*
> ```XML
>         let nonce_small_enough_to_qualify_for_validation_skip =
>             tx_nonce <= self.max_nonce_for_validation_skip;
>         let deploy_account_has_been_sent = deploy_account_tx_hash.is_some();
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-11-15 15:19 UTC, elintul approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-11-15 21:02 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1128)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/py_validator.rs` line 197 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-NjJdsUq54H0EgFJyixl:-NjJdsUq54H0EgFJyixm:b-2db00w) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb9fb97f96a3be6478093d42498d93615898cd0b/crates/native_blockifier/src/py_validator.rs#L197)):*
> ```XML
> 
>             return Ok(false);
>         }
> ```

It isn't exactly pre-validations checks.



_Code quote:_
```XML
        // Deploy account transactions should be fully executed (not just validated),
        // since the constructor must run before any validations are performed. Since the execution
        // already includes all necessary validations, so they are skipped here.
        if let AccountTransaction::DeployAccount(_deploy_account_tx) = account_tx {
            let (_py_tx_execution_info, _py_casm_hash_calculation_resources) =
                self.execute(tx, raw_contract_class)?;
            // TODO(Ayelet, 09/11/2023): Check call succeeded.

            return Ok(false);
        }
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 198 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-NjJlsiN5VKy7MYv8KHv:-NjJlsiN5VKy7MYv8KHw:bb6f014) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb9fb97f96a3be6478093d42498d93615898cd0b/crates/native_blockifier/src/py_validator.rs#L198)):*
> ```XML
>             return Ok(false);
>         }
> ```

My thoughts (only my opinion, you can do as you wish):



_Code snippet:_
```XML
fn perform_validations {
    if deploy_account {
        execute();
        return Ok(());
    }
    perform_pre_validation_stage()
    if skip_due_to_unprocessed_deploy_account(){
        return Ok(());
    }
    validate();
    perform_post_validation_stage();
    Ok(())
```


<!-- Sent from Reviewable.io -->

2023-11-16 05:08 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1128)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/native_blockifier/src/py_validator.rs` line 197 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-NjJdsUq54H0EgFJyixl:-NjLWDCh6QiZ2SVga_vb:b-c6tzhd) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb9fb97f96a3be6478093d42498d93615898cd0b/crates/native_blockifier/src/py_validator.rs#L197)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It isn't exactly pre-validations checks.
</blockquote></details>

Ok, put back into perform_validations.
___
*[`crates/native_blockifier/src/py_validator.rs` line 198 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-NjJlsiN5VKy7MYv8KHv:-NjLSpQt4RTIZ7EbaO1w:bmmdt8g) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb9fb97f96a3be6478093d42498d93615898cd0b/crates/native_blockifier/src/py_validator.rs#L198)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

My thoughts (only my opinion, you can do as you wish):
</blockquote></details>

Sagur, i'm assuming you meant that `skip_due_to_unprocessed_deploy` be called before the `pre_validation_stage` (unless i'm missing something here), so i did what you said with those switched.

Also I moved the pre_validation_stage call into a wrapper inside py_validator, for symmetry with post_validation stage (which is a method) and to hide all the initialization variables.  


<!-- Sent from Reviewable.io -->

2023-11-16 07:47 UTC, noaov1 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1128)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/py_validator.rs` line 198 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-NjJlsiN5VKy7MYv8KHv:-NjM3vWc-bqk8A2eu2Gr:b-clryok) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb9fb97f96a3be6478093d42498d93615898cd0b/crates/native_blockifier/src/py_validator.rs#L198)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Sagur, i'm assuming you meant that `skip_due_to_unprocessed_deploy` be called before the `pre_validation_stage` (unless i'm missing something here), so i did what you said with those switched.

Also I moved the pre_validation_stage call into a wrapper inside py_validator, for symmetry with post_validation stage (which is a method) and to hide all the initialization variables.
</blockquote></details>

No. You want to to preform the pre-validations and just skip validate :)
These transactions should pass the pre-validation checks (should have enough balance and large enough `max_fee`) but will fail `__validate__` since the state does not know the account.


<!-- Sent from Reviewable.io -->

2023-11-16 07:50 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1128)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/py_validator.rs` line 133 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-NjM5R9O7mj9LayoznwG:-NjM5R9O7mj9LayoznwH:b3kqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/2ae349f10f47516d737616a377e7481690931eb9/crates/native_blockifier/src/py_validator.rs#L133)):*
> ```XML
>         // Deploy account transactions should be fully executed (not just validated),
>         // since the constructor must run before any validations are performed. Since the execution
>         // already includes all necessary validations, so they are skipped here.
> ```

.



_Suggestion:_
```XML
        // Deploy account transactions should be fully executed, since the constructor must run before 
        // `__validate_deploy__`. The execution already includes all necessary validations, so they are 
        // skipped here.
```


<!-- Sent from Reviewable.io -->

2023-11-16 07:50 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1128)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/native_blockifier/src/py_validator.rs` line 198 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-NjJlsiN5VKy7MYv8KHv:-NjM5zrb5jjWIevey1DV:b7dutcq) ([raw file](https://github.com/starkware-libs/blockifier/blob/eb9fb97f96a3be6478093d42498d93615898cd0b/crates/native_blockifier/src/py_validator.rs#L198)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

No. You want to to preform the pre-validations and just skip validate :)
These transactions should pass the pre-validation checks (should have enough balance and large enough `max_fee`) but will fail `__validate__` since the state does not know the account.
</blockquote></details>

Oh i see now, thanks for the correction!
Fixed.


<!-- Sent from Reviewable.io -->

2023-11-16 07:53 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1128)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/native_blockifier/src/py_validator.rs` line 133 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-NjM5R9O7mj9LayoznwG:-NjM6RPzCm-L_iumRNJW:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2ae349f10f47516d737616a377e7481690931eb9/crates/native_blockifier/src/py_validator.rs#L133)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-16 08:00 UTC, noaov1 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1128)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/py_validator.rs` line 202 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-NjM7sOJDk71FYqvUHgh:-NjM7sOJDk71FYqvUHgi:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/32e0beb131f69e39a7595f9629dff886eb258e8d/crates/native_blockifier/src/py_validator.rs#L202)):*
> ```XML
> 
>     // Check if deploy account was submitted but not processed yet. If so, then skip
>     // validations for subsequent transactions for a better user experience.
> ```





_Suggestion:_
```XML
   // `validate` method for subsequent transactions for a better user experience.
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 204 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-NjM7i5R5ILZ3Jn7iAV3:-NjM7i5R5ILZ3Jn7iAV4:b-gt656) ([raw file](https://github.com/starkware-libs/blockifier/blob/32e0beb131f69e39a7595f9629dff886eb258e8d/crates/native_blockifier/src/py_validator.rs#L204)):*
> ```XML
>     // validations for subsequent transactions for a better user experience.
>     // (they will otherwise fail solely because the deploy account hasn't been processed yet).
>     fn skip_validations_due_to_unprocessed_deploy_account(
> ```

Less confusing IMO :)



_Suggestion:_
```XML
    fn skip_validate_due_to_unprocessed_deploy_account(
```


<!-- Sent from Reviewable.io -->

2023-11-16 08:37 UTC, noaov1 approved these changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1128)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)



<!-- Sent from Reviewable.io -->

2023-11-16 09:15 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1128)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/native_blockifier/src/py_validator.rs` line 202 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-NjM7sOJDk71FYqvUHgh:-NjMPW5HBkigzlmuI_aq:b-6gbw1n) ([raw file](https://github.com/starkware-libs/blockifier/blob/32e0beb131f69e39a7595f9629dff886eb258e8d/crates/native_blockifier/src/py_validator.rs#L202)):*
> ```XML
> 
>     // Check if deploy account was submitted but not processed yet. If so, then skip
>     // validations for subsequent transactions for a better user experience.
> ```

Can I use `__validate__` instead of `validate`? I think Elin asked that it be that way in some other place here


<!-- Sent from Reviewable.io -->

2023-11-16 09:17 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1128)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/py_validator.rs` line 202 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-NjM7sOJDk71FYqvUHgh:-NjMPu071Nl9bFSG4vLn:b2nhswy) ([raw file](https://github.com/starkware-libs/blockifier/blob/32e0beb131f69e39a7595f9629dff886eb258e8d/crates/native_blockifier/src/py_validator.rs#L202)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can I use `__validate__` instead of `validate`? I think Elin asked that it be that way in some other place here
</blockquote></details>

Yes


<!-- Sent from Reviewable.io -->

2023-11-16 09:31 UTC, noaov1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1128#-:-NjMSkZE4DYwxVutLtez:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2023-11-16 09:48 UTC, merged