Better `TransactionType` handling in `native_blockifier`
starkware-libs/blockifier pull request #1136
Opened 2023-11-15 09:07 UTC by giladchase

(Wasn't sure if this should have been split further, since these are all related changes.)

- Remove py_enum_name, it was only used for `tx_type`.
- Push down tx_type extraction into py_tx, it's only used there and is already included inside the `tx` argument.
- Cast string tx_type into `TransactionType` as soon as possible.
- Unify tx parsing logic under `py_tx`
- Rename the arguments py_tx -> tx since `py_tx` shadows the function with the same name.
- Add `From` to `Transaction`, for less verbose initialization.
- Throw regular panic instead of `unimplemented!()` --- this was true in the past when we didn't implement all tx_types, but now that we do any value passed from Python that is not in the match is a bug.

2023-11-15 09:35 UTC, dorimedini-starkware requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1136)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1136#-NjHEuO33SprYMqvT67P:-NjHEuO33SprYMqvT67Q:b-hly2zx) (no related file):*
python side PR?

___
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1136#-NjHEQl47-hWsh6jaq16:-NjHEQl47-hWsh6jaq17:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5089b801385a84cd32146b592af55caef48d5b53/crates/blockifier/src/transaction/test_utils.rs#L206)):*
> ```XML
>             AccountTransaction::Invoke(invoke_tx)
>         }
>         _ => panic!("Not an account transaction."),
> ```





_Suggestion:_
```XML
"{tx_type:?} is not an account transaction."
```
___
*[`crates/blockifier/src/transaction/transaction_types.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1136#-NjHEeN38BELgwLcKfoM:-NjHEeN4CKNc-jZRRFP6:b-ykd7c1) ([raw file](https://github.com/starkware-libs/blockifier/blob/5089b801385a84cd32146b592af55caef48d5b53/crates/blockifier/src/transaction/transaction_types.rs#L6)):*
> ```XML
> use strum_macros::EnumIter;
> 
> use super::errors::ParseError;
> ```

use `crate`



_Code quote:_
```XML
super
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1136#-NjHF9fb4q6r7RXDQz9m:-NjHF9fb4q6r7RXDQz9n:b-gm6ver) ([raw file](https://github.com/starkware-libs/blockifier/blob/5089b801385a84cd32146b592af55caef48d5b53/crates/native_blockifier/src/py_transaction.rs#L152)):*
> ```XML
>     let tx_type: &str = tx.getattr("tx_type")?.getattr("name")?.extract()?;
>     let tx_type: TransactionType =
>         tx_type.parse().map_err(NativeBlockifierInputError::ParseError)?;
> ```

this calls `from_str`...?



_Code quote:_
```XML
tx_type.parse()
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1136#-NjHJkhH00vAkVtwjWgQ:-NjHJkhH00vAkVtwjWgR:b-ef0nrf) ([raw file](https://github.com/starkware-libs/blockifier/blob/5089b801385a84cd32146b592af55caef48d5b53/crates/native_blockifier/src/py_transaction.rs#L167)):*
> ```XML
>     };
> 
>     Ok(Transaction::from(account_tx))
> ```

will this work?



_Suggestion:_
```XML
    Ok(match tx_type {
        TransactionType::Declare => {
            let raw_contract_class: &str = raw_contract_class
                .expect("A contract class must be passed in a Declare transaction.");
            AccountTransaction::Declare(py_declare(tx, raw_contract_class)?).into()
        }
        TransactionType::DeployAccount => AccountTransaction::DeployAccount(py_deploy_account(tx)?).into(),
        TransactionType::InvokeFunction => AccountTransaction::Invoke(py_invoke_function(tx)?).into(),
        TransactionType::L1Handler => py_l1_handler(tx)?.into(),
    })
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1136#-NjHK9tv4_FrxlWZfvOw:-NjHK9tv4_FrxlWZfvOx:b-oecpxy) ([raw file](https://github.com/starkware-libs/blockifier/blob/5089b801385a84cd32146b592af55caef48d5b53/crates/native_blockifier/src/py_validator.rs#L115)):*
> ```XML
>     ) -> NativeBlockifierResult<()> {
>         let account_tx = py_tx(tx, raw_contract_class)?;
>         if let Transaction::AccountTransaction(_) = account_tx {
> ```

what?
no; this should only be for deploy account txs.
need to match specifically.



_Code quote:_
```XML
if let Transaction::AccountTransaction(_) = account_tx
```


<!-- Sent from Reviewable.io -->

2023-11-15 09:46 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1136)* status: 5 of 9 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @noaov1)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1136#-NjHEQl47-hWsh6jaq16:-NjHKrpV98jD5nqCmeYh:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5089b801385a84cd32146b592af55caef48d5b53/crates/blockifier/src/transaction/test_utils.rs#L206)):*
> ```XML
>             AccountTransaction::Invoke(invoke_tx)
>         }
>         _ => panic!("Not an account transaction."),
> ```

Done.
___
*[`crates/blockifier/src/transaction/transaction_types.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1136#-NjHEeN38BELgwLcKfoM:-NjHL8NWD5M8lWfwtVkz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5089b801385a84cd32146b592af55caef48d5b53/crates/blockifier/src/transaction/transaction_types.rs#L6)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

use `crate`
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1136#-NjHF9fb4q6r7RXDQz9m:-NjHL9QICo3ILvJh_n8L:b-d07wtk) ([raw file](https://github.com/starkware-libs/blockifier/blob/5089b801385a84cd32146b592af55caef48d5b53/crates/native_blockifier/src/py_transaction.rs#L152)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this calls `from_str`...?
</blockquote></details>

Yep:
```text
`FromStr`’s `from_str`method is often used implicitly, through `str`’s [`parse`] method. 
```
(Taken from https://doc.rust-lang.org/std/str/trait.FromStr.html)
___
*[`crates/native_blockifier/src/py_transaction.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1136#-NjHJkhH00vAkVtwjWgQ:-NjHMIND5Sbw3HCiFsBq:b-xdz69s) ([raw file](https://github.com/starkware-libs/blockifier/blob/5089b801385a84cd32146b592af55caef48d5b53/crates/native_blockifier/src/py_transaction.rs#L167)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

will this work?
</blockquote></details>

Yep, thought about it as well but wasn't sure if you'd like the 4 `into`s.
___
*[`crates/native_blockifier/src/py_validator.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1136#-NjHK9tv4_FrxlWZfvOw:-NjHMmdvEOd6Ddy5Co3S:b-fn0hnd) ([raw file](https://github.com/starkware-libs/blockifier/blob/5089b801385a84cd32146b592af55caef48d5b53/crates/native_blockifier/src/py_validator.rs#L115)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what?
no; this should only be for deploy account txs.
need to match specifically.
</blockquote></details>

Whoops sorry, by mistake.
Thanks for catching!


<!-- Sent from Reviewable.io -->

2023-11-15 09:48 UTC, dorimedini-starkware reviewed
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1136)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1136#-NjHJkhH00vAkVtwjWgQ:-NjHNEUQ2XfMxIhRIHiA:b5m771i) ([raw file](https://github.com/starkware-libs/blockifier/blob/5089b801385a84cd32146b592af55caef48d5b53/crates/native_blockifier/src/py_transaction.rs#L167)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Yep, thought about it as well but wasn't sure if you'd like the 4 `into`s.
</blockquote></details>

love 'em


<!-- Sent from Reviewable.io -->

2023-11-15 09:49 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1136)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @elintul, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1136#-NjHEuO33SprYMqvT67P:-NjHN_7G14D5RjgtwLXJ:bgzr4ac) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

python side PR?
</blockquote></details>

Thanks, forgot about it this time :scream: 

Python: https://reviewable.io/reviews/starkware-industries/starkware/32609

___


<!-- Sent from Reviewable.io -->

2023-11-15 09:51 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1136#-:-NjHOEQ55d32p3quuUmX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @elintul and @noaov1)



<!-- Sent from Reviewable.io -->

2023-11-16 12:33 UTC, elintul approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1136)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-11-16 13:30 UTC, dorimedini-starkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1136)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-11-16 13:56 UTC, merged