Add Storage mock and test for get_block_id
starkware-libs/blockifier pull request #1155
Opened 2023-11-20 11:01 UTC by giladchase

Specifically, when retrieving block_id from a Papyrus snapshot
it can be a large hash, which we had a bug on back when we assumed it
was a u64.

---

**Stack**:
- #1155 ⬅
- #1153

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2023-11-20 12:09 UTC, giladchase reviewed
Not sure why https://reviewable.io/reviews/starkware-libs/blockifier/1154 was closed, i think because i pushed --force by mistake and it pissed of `spr`.
All comments addressed though

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1155#-:-NjgccRVClwzv5WjGYlI:b-gg2oeg)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @elintul)



<!-- Sent from Reviewable.io -->

2023-11-20 12:24 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1155)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/py_block_executor_test.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1155#-NjgfpRg5jdFtVSmSfxo:-NjgfpRg5jdFtVSmSfxp:bts9lq4) ([raw file](https://github.com/starkware-libs/blockifier/blob/6efb37b3e01549de051bc3e6c43ba11dbc05c6b4/crates/native_blockifier/src/py_block_executor_test.rs#L57)):*
> ```XML
>             0x9, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf,
>             0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf,
>         ])
> ```

can't you reuse...?



_Suggestion:_
```XML
        StarkFelt::new(max_class_hash.into_iter().rev().collect())
```
___
*[`crates/native_blockifier/src/test_utils.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1155#-Njgg8_30oT3miZyR3yn:-Njgg8_30oT3miZyR3yo:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6efb37b3e01549de051bc3e6c43ba11dbc05c6b4/crates/native_blockifier/src/test_utils.rs#L10)):*
> ```XML
>     // .. Add more as needed.
> }
> impl Storage for MockStorage {
> ```





_Suggestion:_
```XML
}

impl Storage for MockStorage {
```


<!-- Sent from Reviewable.io -->

2023-11-20 12:35 UTC, elintul approved these changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1155)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-11-20 12:35 UTC, elintul submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1155#-:-NjgicJiDpxoK2bja8zt:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-11-20 13:11 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1155)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/py_block_executor_test.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1155#-NjgfpRg5jdFtVSmSfxo:-NjgqFq92WC2RWr-zGnI:bqziz5) ([raw file](https://github.com/starkware-libs/blockifier/blob/6efb37b3e01549de051bc3e6c43ba11dbc05c6b4/crates/native_blockifier/src/py_block_executor_test.rs#L57)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can't you reuse...?
</blockquote></details>

Done. I changed it a bit if that's Ok
___
*[`crates/native_blockifier/src/test_utils.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1155#-Njgg8_30oT3miZyR3yn:-NjgqawYEw5zRqqrPins:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6efb37b3e01549de051bc3e6c43ba11dbc05c6b4/crates/native_blockifier/src/test_utils.rs#L10)):*
> ```XML
>     // .. Add more as needed.
> }
> impl Storage for MockStorage {
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-11-20 13:11 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1155)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/native_blockifier/src/py_block_executor_test.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1155#-NjgfpRg5jdFtVSmSfxo:-NjgqpNrElHd0DwHk91h:b-2df3p) ([raw file](https://github.com/starkware-libs/blockifier/blob/6efb37b3e01549de051bc3e6c43ba11dbc05c6b4/crates/native_blockifier/src/py_block_executor_test.rs#L57)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Done. I changed it a bit if that's Ok
</blockquote></details>

(couldn't get the rev thing to work :sweat_smile: )


<!-- Sent from Reviewable.io -->

2023-11-20 13:15 UTC, elintul submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1155)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2023-11-20 13:28 UTC, elintul approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1155)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2023-11-20 16:00 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1155#-:-NjhSRXABfK9T1nJepri:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-11-21 09:43 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1155)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-11-22 06:59 UTC, merged