Define and use DeployTxArgs
starkware-libs/blockifier pull request #1194
Opened 2023-11-28 12:35 UTC by dorimedini-starkware

Same idea as `InvokeTxArgs` - will allow easier construction of `DeployAccount` transactions, and soon we will be able to vary over version

2023-11-28 15:57 UTC, giladchase reviewed
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1194)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @MohammadNassar1)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1194#-NkLce8A2NjOLIJAqBll:-NkLce8A2NjOLIJAqBlm:b-jbzg16) ([raw file](https://github.com/starkware-libs/blockifier/blob/d4b189a635342c75d31ae756d38144d517761d33/crates/blockifier/src/test_utils/deploy_account.rs#L26)):*
> ```XML
>     pub fee_data_availability_mode: DataAvailabilityMode,
>     pub paymaster_data: PaymasterData,
>     pub deployer_address: ContractAddress,
> ```

Are all of these fields used? i think paymaster isn't yet.

If they are unused now, i think it might be better to omit them now and add them when we need to, WDYT?



_Code quote:_
```XML
    pub version: TransactionVersion,
    pub max_fee: Fee,
    pub signature: TransactionSignature,
    pub nonce: Nonce,
    pub class_hash: ClassHash,
    pub contract_address_salt: ContractAddressSalt,
    pub constructor_calldata: Calldata,
    pub resource_bounds: ResourceBoundsMapping,
    pub tip: Tip,
    pub nonce_data_availability_mode: DataAvailabilityMode,
    pub fee_data_availability_mode: DataAvailabilityMode,
    pub paymaster_data: PaymasterData,
    pub deployer_address: ContractAddress,
```


<!-- Sent from Reviewable.io -->

2023-11-28 16:48 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1194)* status: 1 of 6 files reviewed, all discussions resolved (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1194#-NkLce8A2NjOLIJAqBll:-NkLp5yK15iBReI2RLTp:b6asri3) ([raw file](https://github.com/starkware-libs/blockifier/blob/d4b189a635342c75d31ae756d38144d517761d33/crates/blockifier/src/test_utils/deploy_account.rs#L26)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Are all of these fields used? i think paymaster isn't yet.

If they are unused now, i think it might be better to omit them now and add them when we need to, WDYT?
</blockquote></details>

They are used [next PR](https://reviewable.io/reviews/starkware-libs/blockifier/1195), where a V3 deployaccount is created with this struct


<!-- Sent from Reviewable.io -->

2023-11-29 06:39 UTC, MohammadNassar1 requested changes
> Reviewed 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1194)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 15 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1194#-NkOloUIATeogkbTwE9m:-NkOloUIATeogkbTwE9n:bn9ziw0) ([raw file](https://github.com/starkware-libs/blockifier/blob/c09a4991016fad6a2ee006c9388b52abab9a108a/crates/blockifier/src/test_utils/deploy_account.rs#L15)):*
> ```XML
> pub struct DeployTxArgs {
>     pub version: TransactionVersion,
>     pub max_fee: Fee,
> ```

Is there a way to verify that new arguments are not used for the deprecated version, and vice versa, for V3, that `max_fee=0`? 



_Code quote:_
```XML
pub max_fee: Fee,
```
___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1194#-NkOkOnTAIelbxE-rGbP:-NkOkOnTAIelbxE-rGbQ:b-7c34nl) ([raw file](https://github.com/starkware-libs/blockifier/blob/c09a4991016fad6a2ee006c9388b52abab9a108a/crates/blockifier/src/test_utils/deploy_account.rs#L26)):*
> ```XML
>     pub fee_data_availability_mode: DataAvailabilityMode,
>     pub paymaster_data: PaymasterData,
>     pub deployer_address: ContractAddress,
> ```

Please ensure consistency with the order of the arguments in other transactions (e.g. `Declare`, `Invoke`).



_Code quote:_
```XML
    pub version: TransactionVersion,
    pub max_fee: Fee,
    pub signature: TransactionSignature,
    pub nonce: Nonce,
    pub class_hash: ClassHash,
    pub contract_address_salt: ContractAddressSalt,
    pub constructor_calldata: Calldata,
    pub resource_bounds: ResourceBoundsMapping,
    pub tip: Tip,
    pub nonce_data_availability_mode: DataAvailabilityMode,
    pub fee_data_availability_mode: DataAvailabilityMode,
    pub paymaster_data: PaymasterData,
    pub deployer_address: ContractAddress,
```
___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 45 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1194#-NkOkyir7G5HRBXhKECY:-NkOkyir7G5HRBXhKECZ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c09a4991016fad6a2ee006c9388b52abab9a108a/crates/blockifier/src/test_utils/deploy_account.rs#L45)):*
> ```XML
>             max_fee: Fee::default(),
>             deployer_address: ContractAddress::default(),
>         }
> ```





_Suggestion:_
```XML
        DeployTxArgs {
            version: TransactionVersion::ONE,
            max_fee: Fee::default(),
            signature: TransactionSignature::default(),
            nonce: Nonce::default(),
            class_hash: ClassHash::default(),
            contract_address_salt: ContractAddressSalt::default(),
            constructor_calldata: Calldata::default(),
            resource_bounds: default_testing_resource_bounds(),
            tip: Tip::default(),
            nonce_data_availability_mode: DataAvailabilityMode::L1,
            fee_data_availability_mode: DataAvailabilityMode::L1,
            paymaster_data: PaymasterData::default(),
            deployer_address: ContractAddress::default(),
        }
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 339 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1194#-NkOn0bUBKfBUlsPXIJP:-NkOn0bUBKfBUlsPXIJQ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c09a4991016fad6a2ee006c9388b52abab9a108a/crates/blockifier/src/transaction/test_utils.rs#L339)):*
> ```XML
>                     signature,
>                     ..Default::default()
>                 },
> ```





_Suggestion:_
```XML
                DeployTxArgs {
                    class_hash: class_hash!(TEST_FAULTY_ACCOUNT_CONTRACT_CLASS_HASH),
                    constructor_calldata: calldata![stark_felt!(constants::FELT_FALSE)],
                    signature,
                    ..Default::default()
                },
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1163 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1194#-NkOn9l_BD-Q-1Crn-tJ:-NkOn9l_BD-Q-1Crn-tK:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c09a4991016fad6a2ee006c9388b52abab9a108a/crates/blockifier/src/transaction/transactions_test.rs#L1163)):*
> ```XML
>                 ]),
>                 ..Default::default()
>             },
> ```





_Suggestion:_
```XML
            DeployTxArgs {
                class_hash: class_hash!(TEST_FAULTY_ACCOUNT_CONTRACT_CLASS_HASH),
                constructor_calldata: calldata![stark_felt!(constants::FELT_TRUE)],
                // run faulty_validate() in the constructor.
                signature: TransactionSignature(vec![
                    stark_felt!(CALL_CONTRACT),
                    stark_felt!(TEST_FAULTY_ACCOUNT_CONTRACT_ADDRESS),
                ]),
                ..Default::default()
            },
```


<!-- Sent from Reviewable.io -->

2023-11-29 07:24 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1194)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @MohammadNassar1)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 15 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1194#-NkOloUIATeogkbTwE9m:-NkOx-Pe7Tn5975Yi9hO:b-1z1xsx) ([raw file](https://github.com/starkware-libs/blockifier/blob/c09a4991016fad6a2ee006c9388b52abab9a108a/crates/blockifier/src/test_utils/deploy_account.rs#L15)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Is there a way to verify that new arguments are not used for the deprecated version, and vice versa, for V3, that `max_fee=0`?
</blockquote></details>

Two ways:

a) Make the v3-sensitive fields Optional and initialized as None,  and use the builder pattern: but that's probably a big refactor at this point?
b) Make them private and only allow them to be set by dedicated functions: but then we have to implement getters for them, which might also be a big change.


<!-- Sent from Reviewable.io -->

2023-11-29 08:58 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1194)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 15 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1194#-NkOloUIATeogkbTwE9m:-NkPGGBNEYuO1mck1FUP:bv8xbr8) ([raw file](https://github.com/starkware-libs/blockifier/blob/c09a4991016fad6a2ee006c9388b52abab9a108a/crates/blockifier/src/test_utils/deploy_account.rs#L15)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Two ways:

a) Make the v3-sensitive fields Optional and initialized as None,  and use the builder pattern: but that's probably a big refactor at this point?
b) Make them private and only allow them to be set by dedicated functions: but then we have to implement getters for them, which might also be a big change.
</blockquote></details>

There is no way to use `max_fee` in a V3 transaction.
Once you `match` against `deploy_tx_args.version` and construct the respective object version only, the fact that you ignore irrelevant fields is "enforced" simply because the struct you're constructing doesn't support these fields.
___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1194#-NkOkOnTAIelbxE-rGbP:-NkPGtV1EoWv82TGRz-W:b-a2dlqs) ([raw file](https://github.com/starkware-libs/blockifier/blob/c09a4991016fad6a2ee006c9388b52abab9a108a/crates/blockifier/src/test_utils/deploy_account.rs#L26)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please ensure consistency with the order of the arguments in other transactions (e.g. `Declare`, `Invoke`).
</blockquote></details>

Done.
Also fixed the `DeclareTxArgs` order (point of truth is the `InvokeTxArgs` struct)
___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 45 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1194#-NkOkyir7G5HRBXhKECY:-NkPHCJQ056NlAfBYZaf:b7fms4m) ([raw file](https://github.com/starkware-libs/blockifier/blob/c09a4991016fad6a2ee006c9388b52abab9a108a/crates/blockifier/src/test_utils/deploy_account.rs#L45)):*
> ```XML
>             max_fee: Fee::default(),
>             deployer_address: ContractAddress::default(),
>         }
> ```

Done (ordered to match struct order).


<!-- Sent from Reviewable.io -->

2023-11-29 09:18 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1194)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @giladchase, and @MohammadNassar1)

___
*[`crates/blockifier/src/test_utils/deploy_account.rs` line 15 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1194#-NkOloUIATeogkbTwE9m:-NkPMYIeC930yi_Wxyts:b-4rooue) ([raw file](https://github.com/starkware-libs/blockifier/blob/c09a4991016fad6a2ee006c9388b52abab9a108a/crates/blockifier/src/test_utils/deploy_account.rs#L15)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

When we do the match?
Does this mean that we are not able to execute a transaction with both `max_fee>0` and `resource_bound>0`?
</blockquote></details>

[here](https://reviewable.io/reviews/starkware-libs/blockifier/1195) is the match.
This struct is just a *union* of all args needed to construct a DeployAccount tx of *any version*.
The struct also includes the `version` meta-argument, on which we `match` when `deploy_account_tx` function is called.


<!-- Sent from Reviewable.io -->

2023-11-29 09:21 UTC, MohammadNassar1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1194)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-11-29 09:32 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1194)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-11-29 09:32 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1194)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-11-29 09:32 UTC, merged