Added test test_count_actual_storage_changes in rust
starkware-libs/blockifier pull request #1253
Opened 2023-12-13 13:21 UTC by aner-starkware

Added test _test_count_actual_storage_changes_ in Rust to test the actual number of storage changes for a fee when:
1. Writing a new value to a contract cell
2. Rewriting the same value to the cell
3. Transfering 1 ETH to another account

2023-12-13 16:08 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1253)* status: all files reviewed, 22 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1341 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYrN4F1HpDle3nZCoU:-NlYrN4F1HpDle3nZCoV:b-oljjv5) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1341)):*
> ```XML
> use crate::execution::execution_utils::{felt_to_stark_felt, stark_felt_to_felt};
> use crate::state::cached_state::CachedState;
> use crate::transaction::constants::TRANSFER_ENTRY_POINT_NAME;
> ```

move to top of file.
the formatter should rearrange the imports when you save



_Code quote:_
```XML
use crate::execution::execution_utils::{felt_to_stark_felt, stark_felt_to_felt};
use crate::state::cached_state::CachedState;
use crate::transaction::constants::TRANSFER_ENTRY_POINT_NAME;
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1351 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYrWLN7Z0Uu61tN0sh:-NlYrWLN7Z0Uu61tN0si:b1mrxkc) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1351)):*
> ```XML
>     #[case] fee_type: FeeType,
> ) {
>     // FeeType according to version
> ```

end comments with punctuation.



_Suggestion:_
```XML
// FeeType according to version.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1352 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYr_Zj3LE8gPazKPPq:-NlYr_Zj3LE8gPazKPPr:b-aubikj) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1352)):*
> ```XML
> ) {
>     // FeeType according to version
>     let fee_type_addr = block_context.fee_token_address(&fee_type);
> ```

don't abbreviate, and this is a token address



_Suggestion:_
```XML
fee_token_address
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1359 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYrg7m0vOayTii4fkf:-NlYrg7m0vOayTii4fkg:bxcb1l2) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1359)):*
> ```XML
>         mut nonce_manager,
>         block_context,
>     } = create_test_init_data(max_fee, block_context);
> ```

please do not use `create_test_init_data`.
Take a look at usages of `FeatureContracts` enum, along with the `test_state` function.
Perhaps @MohammadNassar1 can help, he recently hit the same issue :)



_Code quote:_
```XML
    let TestInitData {
        mut state,
        account_address,
        contract_address,
        mut nonce_manager,
        block_context,
    } = create_test_init_data(max_fee, block_context);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1360 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYrrkQ9uMvu7UFgm6p:-NlYrrkQ9uMvu7UFgm6q:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1360)):*
> ```XML
>         block_context,
>     } = create_test_init_data(max_fee, block_context);
>     let initial_seq_fee = stark_felt_to_felt(
> ```





_Suggestion:_
```XML
initial_sequencer_balance
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1376 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYs2zA4j6lpvE7ZXhL:-NlYs2zA4j6lpvE7ZXhM:b-aqjgfs) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1376)):*
> ```XML
>             &[recipient, felt_to_stark_felt(&transfer_amount), stark_felt!(0_u8)],
>         )
>     };
> ```

1. end comments in punctuation.
2. these are not transactions - they are calldata instances.
3. No need for lambda functions; just create an instance of calldata and `clone()` when necessary.
```
    // Calldata.
    let write_1_calldata = create_calldata(contract_address, "test_count_actual_storage_changes", &[]);
    let recipient = stark_felt!(435_u16);
    let transfer_amount: Felt252 = 1.into();
    let transfer_calldata = create_calldata(
        fee_type_addr,
        TRANSFER_ENTRY_POINT_NAME,
        &[recipient, felt_to_stark_felt(&transfer_amount), stark_felt!(0_u8)],
    );
```



_Suggestion:_
```XML
    // Calldata.
    let write_1_calldata = create_calldata(contract_address, "test_count_actual_storage_changes", &[]);
    let recipient = stark_felt!(435_u16);
    let transfer_amount: Felt252 = 1.into();
    let transfer_calldata = create_calldata(
        fee_type_addr,
        TRANSFER_ENTRY_POINT_NAME,
        &[recipient, felt_to_stark_felt(&transfer_amount), stark_felt!(0_u8)],
    );
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1378 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYs_gK40nobsewisQp:-NlYs_gK40nobsewisQq:b-q4ixhp) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1378)):*
> ```XML
>     };
> 
>     // run transactions
> ```

Capitalization, punctuation.
Also, add a comment why a transactional state is used.



_Suggestion:_
```XML
// Run transactions.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1379 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYtZVN-RjK3EqgRheZ:-NlYtZVN-RjK3EqgRhe_:bvkctba) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1379)):*
> ```XML
> 
>     // run transactions
>     let mut state = CachedState::create_transactional(&mut state);
> ```

Add a comment about this transaction and what it does.



_Suggestion:_
```XML
// First transaction: storage cell changes from 0 to 1.
let mut state = CachedState::create_transactional(&mut state);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1380 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYtkLz0nKSvcJp87s7:-NlYtkLz0nKSvcJp87s8:bmkd13t) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1380)):*
> ```XML
>     // run transactions
>     let mut state = CachedState::create_transactional(&mut state);
>     let mut args = invoke_tx_args! {
> ```

1. why `mut`?
2. please rename



_Suggestion:_
```XML
let invoke_args 
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1389 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYvPXD6V8_CCZN_Jbr:-NlYvPXECyQVqcc3Qr1s:b-uc44eu) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1389)):*
> ```XML
>     };
>     let account_tx = account_invoke_tx(args.clone());
>     let execution_info = account_tx.execute_raw(&mut state, &block_context, true, true); //execute write to unwritten cell
> ```

delete (we rarely use trailing inline comments except in specific cases; prefer commenting on a separate line).



_Code quote:_
```XML
 //execute write to unwritten cell
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 139 [...]

2023-12-14 10:39 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1253)* status: 2 of 3 files reviewed, 22 unresolved discussions (waiting on @dorimedini-starkware and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1341 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYrN4F1HpDle3nZCoU:-NlbiC526PeFl5FDlUVz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1341)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move to top of file.
the formatter should rearrange the imports when you save
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1351 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYrWLN7Z0Uu61tN0sh:-NlbiDpCBmWHWrXf1OcA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1351)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

end comments with punctuation.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1352 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYr_Zj3LE8gPazKPPq:-NlbiENn3bM_DZOsrXeV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1352)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't abbreviate, and this is a token address
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1359 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYrg7m0vOayTii4fkf:-NlbjUv40VNHs0ybVAsp:bhrjqxl) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1359)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please do not use `create_test_init_data`.
Take a look at usages of `FeatureContracts` enum, along with the `test_state` function.
Perhaps @MohammadNassar1 can help, he recently hit the same issue :)
</blockquote></details>

I tried to follow the example in `create_flavors_test_state`.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1360 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYrrkQ9uMvu7UFgm6p:-NlbiSAL-IYpwSCb80u3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1360)):*
> ```XML
>         block_context,
>     } = create_test_init_data(max_fee, block_context);
>     let initial_seq_fee = stark_felt_to_felt(
> ```

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1376 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYs2zA4j6lpvE7ZXhL:-NlbiUjw4fLEFurQLJE4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1376)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. end comments in punctuation.
2. these are not transactions - they are calldata instances.
3. No need for lambda functions; just create an instance of calldata and `clone()` when necessary.
```
    // Calldata.
    let write_1_calldata = create_calldata(contract_address, "test_count_actual_storage_changes", &[]);
    let recipient = stark_felt!(435_u16);
    let transfer_amount: Felt252 = 1.into();
    let transfer_calldata = create_calldata(
        fee_type_addr,
        TRANSFER_ENTRY_POINT_NAME,
        &[recipient, felt_to_stark_felt(&transfer_amount), stark_felt!(0_u8)],
    );
```
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1378 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYs_gK40nobsewisQp:-NlbiVavARwdpvyDZgdD:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1378)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Capitalization, punctuation.
Also, add a comment why a transactional state is used.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1379 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYtZVN-RjK3EqgRheZ:-NlbiY-aCPB0WWkFgZTB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1379)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Add a comment about this transaction and what it does.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1380 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYtkLz0nKSvcJp87s7:-NlbiZunEsqRPOSdcd84:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1380)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. why `mut`?
2. please rename
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1389 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYvPXD6V8_CCZN_Jbr:-Nlbi_hF6mH65oJiuE1Z:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1389)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete (we rarely use trailing inline comments except in specific cases; prefer commenting on a separate line).
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1397 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYsoWkDKRIOLsg5jqF:-NlbiaHy7XNxPnkcF7th:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1397)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Add `use pretty_assertions::assert_eq;` at the top of the file; if other tests here use "non-pretty" version of `assert_eq`, it's time they are updated ;)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1403 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYt6bL52rFbIEeaGC9:-NlbibGYBPKq-HsZqWx4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1403)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the `patricia_key!` macro can operate directly on hex strings.
you could also try `patricia_key!(15_u8)`, see if that works
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1417 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYtTSK8vF5AapdKf-x:-Nlbibze80djF9QDm89_:b-896fix) ([raw file](https://github.com/starkware-libs/blockif [...]

2023-12-14 10:50 UTC, aner-starkware commented
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1419 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYuN8U1glf8NiU603e:-NlbwKpeCIw9iOkj4Y57:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1419)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Add a comment marking the second scenario
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-14 11:40 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1253)* status: all files reviewed, 5 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1423 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYvJky2nOJTOPSCSif:-Nlc6WPsDmfE6K7qAeFG:bkrg7vs) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1423)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nope :) maybe didn't commit?
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1075 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-Nlc4zEr2YNoSqnZDZf3:-Nlc4zEr2YNoSqnZDZf4:b5nt955) ([raw file](https://github.com/starkware-libs/blockifier/blob/157c7e2938033720105cd872e522ccad3afbfe27/crates/blockifier/src/transaction/account_transactions_test.rs#L1075)):*
> ```XML
>     );
> 
>     // Calldata types
> ```

end in punctuation



_Suggestion:_
```XML
// Calldata types.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1099 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-Nlc5B-hCJOw1IbbVgFL:-Nlc5B-hCJOw1IbbVgFM:b-nlkzcr) ([raw file](https://github.com/starkware-libs/blockifier/blob/157c7e2938033720105cd872e522ccad3afbfe27/crates/blockifier/src/transaction/account_transactions_test.rs#L1099)):*
> ```XML
>     };
>     let account_tx = account_invoke_tx(invoke_args.clone());
>     let execution_info = account_tx.execute_raw(&mut state, &block_context, true, true);
> ```

this is misleading the type of this variable is not `TransactionExecutionInfo`, it's `TransactionExecutionResult<TransactionExecutionInfo>`. Either
1. rename to `execution_result`, or
2. add an `unwrap()` on this same line

I prefer option (2), you unwrap next line anyway



_Code quote:_
```XML
execution_info = account_tx.execute_raw(&mut state, &block_context, true, true)
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1129 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-Nlc65T_-IpwKQ8lGn2-:-Nlc65TaCTFTxtMOZSKP:b5ogypi) ([raw file](https://github.com/starkware-libs/blockifier/blob/157c7e2938033720105cd872e522ccad3afbfe27/crates/blockifier/src/transaction/account_transactions_test.rs#L1129)):*
> ```XML
>     let mut state = CachedState::create_transactional(&mut state);
>     let account_tx = account_invoke_tx(
>         invoke_tx_args! {nonce:nonce_manager.next(account_address),..invoke_args.clone()},
> ```

This should be formatted as struct construction is formatted (you are missing whitespace).
To see how it should be auto-formatted, you can simply instantiate without the macro (you are using `..invoke_args` at the end anyway, macro doesn't save any boilerplate):
```
InvokeTxArgs { nonce: nonce_manager.next(account_address), ..invoke_args.clone() }
```
that way, the auto-formatter will handle it for you.



_Suggestion:_
```XML
invoke_tx_args! { nonce: nonce_manager.next(account_address), ..invoke_args.clone() }
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1152 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-Nlc6rj248d_T1m-E-S7:-Nlc6rj248d_T1m-E-S8:bduisjd) ([raw file](https://github.com/starkware-libs/blockifier/blob/157c7e2938033720105cd872e522ccad3afbfe27/crates/blockifier/src/transaction/account_transactions_test.rs#L1152)):*
> ```XML
>     let account_tx =
>         account_invoke_tx(invoke_tx_args! {nonce:nonce_manager.next(account_address), calldata:
>         transfer_calldata,..invoke_args.clone()});
> ```

auto-formatter issues.
I suggest you replace `invoke_tx_args!` with `InvokeTxArgs` and let the auto-formatter do it's thing (see above comment)



_Code quote:_
```XML
    let account_tx =
        account_invoke_tx(invoke_tx_args! {nonce:nonce_manager.next(account_address), calldata:
        transfer_calldata,..invoke_args.clone()});
```


<!-- Sent from Reviewable.io -->

2023-12-14 12:09 UTC, aner-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1253)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1423 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-NlYvJky2nOJTOPSCSif:-NlcDGfv4mCUeP4NzUhb:bl4hdp1) ([raw file](https://github.com/starkware-libs/blockifier/blob/603408b05f63dba58b5901b9c08ef1304d2fd00d/crates/blockifier/src/transaction/account_transactions_test.rs#L1423)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

nope :) maybe didn't commit?
</blockquote></details>

Oops :grimacing: 
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1075 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-Nlc4zEr2YNoSqnZDZf3:-NlcCaYU3qLUGmZrzNsM:b1h1hx5) ([raw file](https://github.com/starkware-libs/blockifier/blob/157c7e2938033720105cd872e522ccad3afbfe27/crates/blockifier/src/transaction/account_transactions_test.rs#L1075)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

end in punctuation
</blockquote></details>

OK, though this is technically not a sentence :grin: 
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1099 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-Nlc5B-hCJOw1IbbVgFL:-NlcCnKK3tCfxKUWM_xb:bmm5oh9) ([raw file](https://github.com/starkware-libs/blockifier/blob/157c7e2938033720105cd872e522ccad3afbfe27/crates/blockifier/src/transaction/account_transactions_test.rs#L1099)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is misleading the type of this variable is not `TransactionExecutionInfo`, it's `TransactionExecutionResult<TransactionExecutionInfo>`. Either
1. rename to `execution_result`, or
2. add an `unwrap()` on this same line

I prefer option (2), you unwrap next line anyway
</blockquote></details>

Done. Option (2)
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1129 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-Nlc65T_-IpwKQ8lGn2-:-NlcCqcv3TMpky8ensGb:b-9wb4xs) ([raw file](https://github.com/starkware-libs/blockifier/blob/157c7e2938033720105cd872e522ccad3afbfe27/crates/blockifier/src/transaction/account_transactions_test.rs#L1129)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

This should be formatted as struct construction is formatted (you are missing whitespace).
To see how it should be auto-formatted, you can simply instantiate without the macro (you are using `..invoke_args` at the end anyway, macro doesn't save any boilerplate):
```
InvokeTxArgs { nonce: nonce_manager.next(account_address), ..invoke_args.clone() }
```
that way, the auto-formatter will handle it for you.
</blockquote></details>

Done, although I guess I'm missing some understanding of when to call the macro and when not to use the macro.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1152 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-Nlc6rj248d_T1m-E-S7:-NlcDFHX6dT-rZQguw5U:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/157c7e2938033720105cd872e522ccad3afbfe27/crates/blockifier/src/transaction/account_transactions_test.rs#L1152)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

auto-formatter issues.
I suggest you replace `invoke_tx_args!` with `InvokeTxArgs` and let the auto-formatter do it's thing (see above comment)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-14 12:31 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-:-NlcIr_t6bi1AFEIPs48:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1129 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1253#-Nlc65T_-IpwKQ8lGn2-:-NlcISn8EV1Fh9zozb2I:bwdsmms) ([raw file](https://github.com/starkware-libs/blockifier/blob/157c7e2938033720105cd872e522ccad3afbfe27/crates/blockifier/src/transaction/account_transactions_test.rs#L1129)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done, although I guess I'm missing some understanding of when to call the macro and when not to use the macro.
</blockquote></details>

There is no general rule I think.
You can call:
```
invoke_tx_args! { nonce: Nonce(7) }
```
but to get the equivalent with `InvokeTxArgs` you need to add `..Default::default()`:
```
InvokeTxArgs { nonce: Nonce(7), ..Default::default() }
```
the macro can save you a line.
however, if you're doing `..` on an object anyway, there is no good reason other than uniformity in the test.


<!-- Sent from Reviewable.io -->

2023-12-14 12:38 UTC, merged