Calculates messages size field
starkware-libs/blockifier pull request #1290
Opened 2023-12-25 09:40 UTC by ayeletstarkware

2023-12-25 11:00 UTC, elintul requested changes
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NmVc1Uk3LyZf0qk3gvz:-NmVc1Uk3LyZf0qk3gw-:b-njrgsy) ([raw file](https://github.com/starkware-libs/blockifier/blob/b6518af087c3fbb1091db7d547f0af20b56f4035/crates/blockifier/src/transaction/transaction_execution.rs#L90)):*
> ```XML
>     }
> 
>     pub fn get_l1_handler_payload_size(&self) -> Option<usize> {
> ```

It's a bit weird to put this method on `Transaction`, when most of types don't have it.
I'd do an `if let` in the `native_blockifier` code.



_Code quote:_
```XML
get_l1_handler_payload_size
```


<!-- Sent from Reviewable.io -->

2023-12-25 12:30 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NmVc1Uk3LyZf0qk3gvz:-NmVx9vs0KE3bWh4cg-B:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b6518af087c3fbb1091db7d547f0af20b56f4035/crates/blockifier/src/transaction/transaction_execution.rs#L90)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It's a bit weird to put this method on `Transaction`, when most of types don't have it.
I'd do an `if let` in the `native_blockifier` code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-26 08:35 UTC, noaov1 requested changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nm_3SstBQOyzaqEkFei:-Nm_3SstBQOyzaqEkFej:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e48cefaf7347a94a2867b856ba85914023adc01f/crates/blockifier/src/fee/gas_usage.rs#L60)):*
> ```XML
> }
> 
> pub fn calculate_messages_size(
> ```





_Suggestion:_
```XML
pub fn calculate_message_segment_size(
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nm_F4bOCJqs1pODmPBZ:-Nm_F4bOCJqs1pODmPB_:b-dfioks) ([raw file](https://github.com/starkware-libs/blockifier/blob/e48cefaf7347a94a2867b856ba85914023adc01f/crates/blockifier/src/fee/gas_usage.rs#L61)):*
> ```XML
> 
> pub fn calculate_messages_size(
>     tx_info: &TransactionExecutionInfo,
> ```

Why not pass directly `[&tx_info.validate_call_info, &tx_info.execute_call_info]`? It's the only information that you need from the `TransactionExecutionInfo`.



_Code quote:_
```XML
    tx_info: &TransactionExecutionInfo,
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nm_4aUg271k3fR0KM6b:-Nm_4aUg271k3fR0KM6c:bb383om) ([raw file](https://github.com/starkware-libs/blockifier/blob/e48cefaf7347a94a2867b856ba85914023adc01f/crates/blockifier/src/fee/gas_usage.rs#L72)):*
> ```XML
>     for call_info in &call_infos {
>         l2_to_l1_payloads_length
>             .extend(call_info.get_sorted_l2_to_l1_payloads_length().into_iter().flatten());
> ```

What does it mean to use `faltten()` on a result object? 



_Code quote:_
```XML
            .extend(call_info.get_sorted_l2_to_l1_payloads_length().into_iter().flatten());
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nm_EQ2iBX35SfUjMZSU:-Nm_EQ2iBX35SfUjMZSV:b-sp69aj) ([raw file](https://github.com/starkware-libs/blockifier/blob/e48cefaf7347a94a2867b856ba85914023adc01f/crates/native_blockifier/src/transaction_executor.rs#L74)):*
> ```XML
>         let l1_handler_payload_size: Option<usize> =
>             if let Transaction::L1HandlerTransaction(l1_handler_tx) = &tx {
>                 Some(l1_handler_tx.tx.calldata.0.len() - 1)
> ```

Consider defining a method for `L1HandlerTransaction` to calculate the payload size.



_Code quote:_
```XML
                Some(l1_handler_tx.tx.calldata.0.len() - 1)
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nm_ExMZChn3sZ-ep8Aj:-Nm_ExM_Cz8-UStfPbBg:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e48cefaf7347a94a2867b856ba85914023adc01f/crates/native_blockifier/src/transaction_executor.rs#L87)):*
> ```XML
>             Ok(tx_execution_info) => {
>                 tx_executed_class_hashes.extend(tx_execution_info.get_executed_class_hashes());
>                 let messages_size =
> ```





_Suggestion:_
```XML
let message_segment_size =
```


<!-- Sent from Reviewable.io -->

2023-12-26 09:36 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nm_F4bOCJqs1pODmPBZ:-Nm_Pd5z0SU6Odelbx_6:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e48cefaf7347a94a2867b856ba85914023adc01f/crates/blockifier/src/fee/gas_usage.rs#L61)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why not pass directly `[&tx_info.validate_call_info, &tx_info.execute_call_info]`? It's the only information that you need from the `TransactionExecutionInfo`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nm_4aUg271k3fR0KM6b:-Nm_STYJ5oBzA4liCfz8:b-nb2smt) ([raw file](https://github.com/starkware-libs/blockifier/blob/e48cefaf7347a94a2867b856ba85914023adc01f/crates/blockifier/src/fee/gas_usage.rs#L72)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What does it mean to use `faltten()` on a result object?
</blockquote></details>

changed it to filter map 
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nm_EQ2iBX35SfUjMZSU:-Nm_SrUf-WR99vjldWoh:bvcu6hf) ([raw file](https://github.com/starkware-libs/blockifier/blob/e48cefaf7347a94a2867b856ba85914023adc01f/crates/native_blockifier/src/transaction_executor.rs#L74)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider defining a method for `L1HandlerTransaction` to calculate the payload size.
</blockquote></details>

hope that i understood correctly


<!-- Sent from Reviewable.io -->

2023-12-26 14:31 UTC, noaov1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nm_4aUg271k3fR0KM6b:-NmaXF2D3LmoTJ8mK2P8:b-ncb9nx) ([raw file](https://github.com/starkware-libs/blockifier/blob/e48cefaf7347a94a2867b856ba85914023adc01f/crates/blockifier/src/fee/gas_usage.rs#L72)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

changed it to filter map
</blockquote></details>

I meant the `flatten()` inside the `extend`. Notice that `get_sorted_l2_to_l1_payloads_length` returns a result object. 


<!-- Sent from Reviewable.io -->

2023-12-26 15:17 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nm_4aUg271k3fR0KM6b:-NmagBQL4q-kZ2UGFgMc:baliiuz) ([raw file](https://github.com/starkware-libs/blockifier/blob/e48cefaf7347a94a2867b856ba85914023adc01f/crates/blockifier/src/fee/gas_usage.rs#L72)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I meant the `flatten()` inside the `extend`. Notice that `get_sorted_l2_to_l1_payloads_length` returns a result object.
</blockquote></details>

because the result get_sorted_l2_to_l1_payloads_length of is of type Vec<usize>. if I don't flatten the result, we get Vec<Vec<usize>>. do you know another way to do so?


<!-- Sent from Reviewable.io -->

2023-12-26 15:18 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nm_4aUg271k3fR0KM6b:-Nmah3sc-9pB973YlvH6:b-jez369) ([raw file](https://github.com/starkware-libs/blockifier/blob/e48cefaf7347a94a2867b856ba85914023adc01f/crates/blockifier/src/fee/gas_usage.rs#L72)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

because the result get_sorted_l2_to_l1_payloads_length of is of type Vec<usize>. if I don't flatten the result, we get Vec<Vec<usize>>. do you know another way to do so?
</blockquote></details>

we get Vec<Vec<usize>>*


<!-- Sent from Reviewable.io -->

2023-12-28 10:46 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 75 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nmk0bVi5wSP3DlaKO0W:-Nmk0bVi5wSP3DlaKO0X:b28gl0v) ([raw file](https://github.com/starkware-libs/blockifier/blob/cbe718c1940ef6e1270867bd8862332bca2976fe/crates/blockifier/src/fee/gas_usage.rs#L75)):*
> ```XML
>             Ok(vec) => l2_to_l1_payloads_length.extend(vec),
>             Err(err) => return Err(err),
>         }
> ```

l2_to_l1_payloads_length.extend(call_info.get_sorted_l2_to_l1_payloads_length()?);



_Code quote:_
```XML
        match call_info.get_sorted_l2_to_l1_payloads_length() {
            Ok(vec) => l2_to_l1_payloads_length.extend(vec),
            Err(err) => return Err(err),
        }
```


<!-- Sent from Reviewable.io -->

2023-12-28 12:22 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @elintul, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 75 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nmk0bVi5wSP3DlaKO0W:-NmkN6Mm3P0n5WYiLUK_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cbe718c1940ef6e1270867bd8862332bca2976fe/crates/blockifier/src/fee/gas_usage.rs#L75)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

l2_to_l1_payloads_length.extend(call_info.get_sorted_l2_to_l1_payloads_length()?);
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-31 08:25 UTC, noaov1 requested changes
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @Yael-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nm_F4bOCJqs1pODmPBZ:-NmyuERK23sPLhr9OSqn:bx6u9ed) ([raw file](https://github.com/starkware-libs/blockifier/blob/e48cefaf7347a94a2867b856ba85914023adc01f/crates/blockifier/src/fee/gas_usage.rs#L61)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you please align your code with the original one? See [here](https://github.com/starkware-libs/blockifier/blob/bd7633214270cf1a50fc2d1ed2be8c6669c24664/crates/blockifier/src/transaction/transaction_utils.rs#L18).
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nm_4aUg271k3fR0KM6b:-NmywNZ370fB_1GGrgJL:b6g95vd) ([raw file](https://github.com/starkware-libs/blockifier/blob/e48cefaf7347a94a2867b856ba85914023adc01f/crates/blockifier/src/fee/gas_usage.rs#L72)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

we get Vec<Vec<usize>>*
</blockquote></details>

Not relevant anymore (given you recent change). I would try to understand the meaning of `faltten()` on a `Result` object :) 
___
*[`crates/blockifier/src/transaction/transactions.rs` line 470 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NmywePZDg3sbGt_1zck:-NmywePZDg3sbGt_1zcl:b-ytt4uk) ([raw file](https://github.com/starkware-libs/blockifier/blob/db76d80390dbfb02109229625a30d9974748b90b/crates/blockifier/src/transaction/transactions.rs#L470)):*
> ```XML
>     }
> 
>     pub fn get_payload_size(&self) -> Option<usize> {
> ```

Why return an `Option`?



_Suggestion:_
```XML
pub fn get_payload_size(&self) -> usize {
```


<!-- Sent from Reviewable.io -->

2023-12-31 09:30 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @elintul, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nm_F4bOCJqs1pODmPBZ:-Nmz6KnNAOa5hS2ggd-i:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e48cefaf7347a94a2867b856ba85914023adc01f/crates/blockifier/src/fee/gas_usage.rs#L61)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please align your code with the original one? See [here](https://github.com/starkware-libs/blockifier/blob/bd7633214270cf1a50fc2d1ed2be8c6669c24664/crates/blockifier/src/transaction/transaction_utils.rs#L18).
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nm_4aUg271k3fR0KM6b:-NmzCEVQDZPE1XNLVudI:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e48cefaf7347a94a2867b856ba85914023adc01f/crates/blockifier/src/fee/gas_usage.rs#L72)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Not relevant anymore (given you recent change). I would try to understand the meaning of `faltten()` on a `Result` object :)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 470 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NmywePZDg3sbGt_1zck:-Nmz52LrENE7eEfNRA1Q:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/db76d80390dbfb02109229625a30d9974748b90b/crates/blockifier/src/transaction/transactions.rs#L470)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why return an `Option`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-02 14:33 UTC, noaov1 reviewed
> Reviewed 1 of 3 files at r7, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 63 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nn9UgOG2lGliksYfYcI:-Nn9UgOH-3P9CLjnSb3d:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/1c9a0f21cc3d84ad5ef06541ca1d05c7dd66c0c5/crates/blockifier/src/fee/gas_usage.rs#L63)):*
> ```XML
>     call_infos: &[&CallInfo],
>     l1_handler_payload_size: Option<usize>,
> ) -> Result<usize, TransactionExecutionError> {
> ```





_Suggestion:_
```XML
) -> TransactionExecutionResult<usize> {
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 471 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nn9VKKy7LD_FT2Vj508:-Nn9VKKy7LD_FT2Vj509:bjtpzqk) ([raw file](https://github.com/starkware-libs/blockifier/blob/1c9a0f21cc3d84ad5ef06541ca1d05c7dd66c0c5/crates/blockifier/src/transaction/transactions.rs#L471)):*
> ```XML
> 
>     pub fn get_payload_size(&self) -> usize {
>         self.tx.calldata.0.len() - 1
> ```

Please use it [here](https://github.com/starkware-libs/blockifier/blob/94ee1a7058a7806ee59a39c578420ff6df5c2a9f/crates/blockifier/src/transaction/transaction_execution.rs#L107).



_Suggestion:_
```XML
    pub fn payload_size(&self) -> usize {
         // The calldata includes the "from" field, which is not a part of the payload.
        self.tx.calldata.0.len() - 1
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 101 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nn9__X59ftXXjH43WZQ:-Nn9__X59ftXXjH43WZR:b9g35mw) ([raw file](https://github.com/starkware-libs/blockifier/blob/1c9a0f21cc3d84ad5ef06541ca1d05c7dd66c0c5/crates/native_blockifier/src/transaction_executor.rs#L101)):*
> ```XML
>                         .iter()
>                         .filter_map(|&call_info| call_info.as_ref())
>                         .collect::<Vec<&CallInfo>>();
> ```

Consider extracting into a method to be used [here](https://github.com/starkware-libs/blockifier/blob/77c1244633e8f874b3c2dfe916b68338cb00a4db/crates/blockifier/src/fee/actual_cost.rs#L127) as well.



_Code quote:_
```XML
                let call_infos: Vec<&CallInfo> =
                    [&tx_execution_info.validate_call_info, &tx_execution_info.execute_call_info]
                        .iter()
                        .filter_map(|&call_info| call_info.as_ref())
                        .collect::<Vec<&CallInfo>>();
```


<!-- Sent from Reviewable.io -->

2024-01-03 08:21 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 101 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nn9__X59ftXXjH43WZQ:-NnDP69x1PSESdlHyJXU:b-fag90x) ([raw file](https://github.com/starkware-libs/blockifier/blob/1c9a0f21cc3d84ad5ef06541ca1d05c7dd66c0c5/crates/native_blockifier/src/transaction_executor.rs#L101)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider extracting into a method to be used [here](https://github.com/starkware-libs/blockifier/blob/77c1244633e8f874b3c2dfe916b68338cb00a4db/crates/blockifier/src/fee/actual_cost.rs#L127) as well.
</blockquote></details>

Will be added in a different PR


<!-- Sent from Reviewable.io -->

2024-01-03 10:58 UTC, noaov1 approved these changes
> Reviewed 3 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-01-03 11:04 UTC, noaov1 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 66 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NnDzSpoCpzINcRQaJRJ:-NnDzSpoCpzINcRQaJRK:bhykey8) ([raw file](https://github.com/starkware-libs/blockifier/blob/6df16f40b636e3fffcf38272d600b2d776678db2/crates/blockifier/src/fee/gas_usage.rs#L66)):*
> ```XML
>     for call_info in call_infos {
>         l2_to_l1_payloads_length.extend(call_info.get_sorted_l2_to_l1_payloads_length()?);
>     }
> ```

Code duplication: will be handled in a separate PR.



_Code quote:_
```XML
    for call_info in call_infos {
        l2_to_l1_payloads_length.extend(call_info.get_sorted_l2_to_l1_payloads_length()?);
    }
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 101 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NnDzcRw9V5xjfu_czCs:-NnDzcRw9V5xjfu_czCt:bhykey8) ([raw file](https://github.com/starkware-libs/blockifier/blob/6df16f40b636e3fffcf38272d600b2d776678db2/crates/native_blockifier/src/transaction_executor.rs#L101)):*
> ```XML
>                         .iter()
>                         .filter_map(|&call_info| call_info.as_ref())
>                         .collect::<Vec<&CallInfo>>();
> ```

Code duplication: will be handled in a separate PR.



_Code quote:_
```XML
                    [&tx_execution_info.validate_call_info, &tx_execution_info.execute_call_info]
                        .iter()
                        .filter_map(|&call_info| call_info.as_ref())
                        .collect::<Vec<&CallInfo>>();
```


<!-- Sent from Reviewable.io -->

2024-01-03 11:12 UTC, elintul requested changes
> Reviewed 1 of 2 files at r2, 1 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: all files reviewed, 3 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 58 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NnE0T6lAaaZ8dbqA2lL:-NnE0T6lAaaZ8dbqA2lM:bkn84lw) ([raw file](https://github.com/starkware-libs/blockifier/blob/6df16f40b636e3fffcf38272d600b2d776678db2/crates/blockifier/src/fee/gas_usage.rs#L58)):*
> ```XML
>     starknet_gas_usage + sharp_gas_usage
> }
> ```

Please separate messages L1 cost calculation from `calculate_tx_gas_usage`, in order to reuse the code.


<!-- Sent from Reviewable.io -->

2024-01-16 11:07 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 58 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NnE0T6lAaaZ8dbqA2lL:-NoGx0gABXbIIB9aMce1:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6df16f40b636e3fffcf38272d600b2d776678db2/crates/blockifier/src/fee/gas_usage.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please separate messages L1 cost calculation from `calculate_tx_gas_usage`, in order to reuse the code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-16 15:50 UTC, noaov1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-:-NoHxqln0xhIUchuBcuC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-01-18 11:01 UTC, elintul requested changes
> Reviewed 1 of 3 files at r12, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 21 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NoRCOJL8Y2G5h8SQK4Y:-NoRCOJMA1rk5dveMLYl:bdl8ep) ([raw file](https://github.com/starkware-libs/blockifier/blob/a52d658ec47cb6015416cf9602da512913539e24/crates/blockifier/src/fee/gas_usage.rs#L21)):*
> ```XML
> pub mod test;
> 
> pub fn calculate_l2_to_l1_payloads_length_and_message_segment_length<'a>(
> ```

Please add a small struct `MessageL1CostInfo` with those two fields and convert this function to its c-tor; can be done in another PR if too big of an addition.



_Code quote:_
```XML
calculate_l2_to_l1_payloads_length_and_message_segment_length
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 97 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NoRD7Fd-ZiFi5LWWwXA:-NoRD7Fd-ZiFi5LWWwXB:bcm4y9f) ([raw file](https://github.com/starkware-libs/blockifier/blob/a52d658ec47cb6015416cf9602da512913539e24/crates/native_blockifier/src/transaction_executor.rs#L97)):*
> ```XML
>                 tx_executed_class_hashes.extend(tx_execution_info.get_executed_class_hashes());
>                 tx_visited_storage_entries.extend(tx_execution_info.get_visited_storage_entries());
>                 let call_infos: Vec<&CallInfo> =
> ```

This function is getting too long.
Please define a c-tor for `PyBouncerInfo` receiving all it needs and move all related code (inc. your new code) there.


<!-- Sent from Reviewable.io -->

2024-01-21 12:06 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 21 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NoRCOJL8Y2G5h8SQK4Y:-NofuO3z5u1rBWO7sNCd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a52d658ec47cb6015416cf9602da512913539e24/crates/blockifier/src/fee/gas_usage.rs#L21)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please add a small struct `MessageL1CostInfo` with those two fields and convert this function to its c-tor; can be done in another PR if too big of an addition.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 97 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NoRD7Fd-ZiFi5LWWwXA:-NofuJUA0R_RSVSeFklA:b-snlpmv) ([raw file](https://github.com/starkware-libs/blockifier/blob/a52d658ec47cb6015416cf9602da512913539e24/crates/native_blockifier/src/transaction_executor.rs#L97)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This function is getting too long.
Please define a c-tor for `PyBouncerInfo` receiving all it needs and move all related code (inc. your new code) there.
</blockquote></details>

Will be done in a different PR


<!-- Sent from Reviewable.io -->

2024-01-23 11:03 UTC, elintul requested changes
> Reviewed 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/blockifier/src/execution/call_info.rs` line 32 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NopuDCC75bs9tzF24lk:-NopuDCD3Izp0LF8x_1U:bb76mu4) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b09382192c908a6019ce380b48dc3a125dc963/crates/blockifier/src/execution/call_info.rs#L32)):*
> ```XML
> }
> 
> #[cfg_attr(test, derive(Clone))]
> ```

Why?



_Code quote:_
```XML
#[cfg_attr(test, derive(Clone))]
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 35 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NopuiW045CMpvQ3OCq5:-NopuiW045CMpvQ3OCq6:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b09382192c908a6019ce380b48dc3a125dc963/crates/blockifier/src/execution/call_info.rs#L35)):*
> ```XML
> #[derive(Debug, Default, Eq, PartialEq)]
> pub struct MessageL1CostInfo {
>     pub l2_to_l1_payloads_length: Vec<usize>,
> ```





_Suggestion:_
```XML
l2_to_l1_payload_lengths
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 36 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NopuHW520pQkfbOO9_i:-NopuHW520pQkfbOO9_j:b-22k5zs) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b09382192c908a6019ce380b48dc3a125dc963/crates/blockifier/src/execution/call_info.rs#L36)):*
> ```XML
> pub struct MessageL1CostInfo {
>     pub l2_to_l1_payloads_length: Vec<usize>,
>     pub message_segment_length: usize,
> ```

We have a `new` c-tor; no need to leave the default one `pub`lic.



_Suggestion:_
```XML
    l2_to_l1_payloads_length: Vec<usize>,
    message_segment_length: usize,
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 40 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NopuYbo2wHFJQiOSrkS:-NopuYbo2wHFJQiOSrkT:bi8b7gz) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b09382192c908a6019ce380b48dc3a125dc963/crates/blockifier/src/execution/call_info.rs#L40)):*
> ```XML
> 
> impl MessageL1CostInfo {
>     pub fn new<'a>(
> ```

Rename to `create`/`calculate`, so it's clear to the reader work is done here.



_Code quote:_
```XML
new
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 47 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NopuOT93JQGVfCBf8Aa:-NopuOT93JQGVfCBf8Ab:b-lifqcl) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b09382192c908a6019ce380b48dc3a125dc963/crates/blockifier/src/execution/call_info.rs#L47)):*
> ```XML
>         for call_info in call_infos {
>             l2_to_l1_payloads_length.extend(call_info.get_sorted_l2_to_l1_payloads_length()?);
>         }
> ```

Is there a more idiomatic way to write this loop? Perhaps ChatGPT would suggest one.



_Code quote:_
```XML
        let mut l2_to_l1_payloads_length = Vec::new();
        for call_info in call_infos {
            l2_to_l1_payloads_length.extend(call_info.get_sorted_l2_to_l1_payloads_length()?);
        }
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 30 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nopz9g44i91YRYu26ZO:-Nopz9g44i91YRYu26ZP:b32wzj) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b09382192c908a6019ce380b48dc3a125dc963/crates/blockifier/src/fee/gas_usage.rs#L30)):*
> ```XML
>     l1_handler_payload_size: Option<usize>,
> ) -> TransactionExecutionResult<usize> {
>     let message_l1_cost_info = MessageL1CostInfo::new(call_infos, l1_handler_payload_size)?;
> ```

x2



_Suggestion:_
```XML
let MessageL1CostInfo { l2_to_l1_payloads_length, message_segment_length } = 
    MessageL1CostInfo::new(call_infos, l1_handler_payload_size)?;
```


<!-- Sent from Reviewable.io -->

2024-01-23 12:54 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @elintul, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/execution/call_info.rs` line 32 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NopuDCC75bs9tzF24lk:-NoqHP1REmrnz5QNQTDN:b8u0qz2) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b09382192c908a6019ce380b48dc3a125dc963/crates/blockifier/src/execution/call_info.rs#L32)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

not needed. deleted.
___
*[`crates/blockifier/src/execution/call_info.rs` line 36 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NopuHW520pQkfbOO9_i:-NoqD5TM7afzo11Vgt2g:b-i3q9fu) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b09382192c908a6019ce380b48dc3a125dc963/crates/blockifier/src/execution/call_info.rs#L36)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

We have a `new` c-tor; no need to leave the default one `pub`lic.
</blockquote></details>

But i'm calling these fields in gas_usage.rs
___
*[`crates/blockifier/src/execution/call_info.rs` line 47 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NopuOT93JQGVfCBf8Aa:-NoqMzFNE9kFm4JeAPBu:b-7wtky2) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b09382192c908a6019ce380b48dc3a125dc963/crates/blockifier/src/execution/call_info.rs#L47)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is there a more idiomatic way to write this loop? Perhaps ChatGPT would suggest one.
</blockquote></details>

Is flat_map better?
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 30 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Nopz9g44i91YRYu26ZO:-NoqJ9Nt2l6iJJs50d1O:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b09382192c908a6019ce380b48dc3a125dc963/crates/blockifier/src/fee/gas_usage.rs#L30)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

x2
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-23 13:04 UTC, elintul requested changes
> Reviewed 1 of 3 files at r12, 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: all files reviewed, 4 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/blockifier/src/execution/call_info.rs` line 36 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NopuHW520pQkfbOO9_i:-NoqPNij34sDV9sEZ6kp:bh89b7k) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b09382192c908a6019ce380b48dc3a125dc963/crates/blockifier/src/execution/call_info.rs#L36)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

But i'm calling these fields in gas_usage.rs
</blockquote></details>

Where? Please link to the code.
___
*[`crates/blockifier/src/execution/call_info.rs` line 47 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NopuOT93JQGVfCBf8Aa:-NoqPsoC9C5ZetvNFf8K:bmuwwbf) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b09382192c908a6019ce380b48dc3a125dc963/crates/blockifier/src/execution/call_info.rs#L47)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Is flat_map better?
</blockquote></details>

What exactly does it do?
___
*[`crates/blockifier/src/execution/call_info.rs` line 44 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NoqPSamAK2XE7Id2jPW:-NoqPSamAK2XE7Id2jPX:b-8u1v5s) ([raw file](https://github.com/starkware-libs/blockifier/blob/81aab7c242cee9f5b4963ff30be17ac98cc75221/crates/blockifier/src/execution/call_info.rs#L44)):*
> ```XML
>     ) -> TransactionExecutionResult<Self> {
>         let l2_to_l1_payload_lengths: Vec<usize> = call_infos
>             .flat_map(|call_info| call_info.l2_to_l1_payload_lengths().unwrap())
> ```

Will cause `panic`; instead, add the error variant to the appropriate error enum, and return a result - as before.



_Code quote:_
```XML
unwrap()
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 103 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NoqPoqx8QRzAPu9nacT:-NoqPoqx8QRzAPu9nacU:b-h4vn0a) ([raw file](https://github.com/starkware-libs/blockifier/blob/81aab7c242cee9f5b4963ff30be17ac98cc75221/crates/native_blockifier/src/transaction_executor.rs#L103)):*
> ```XML
>                 let MessageL1CostInfo { l2_to_l1_payload_lengths: _, message_segment_length } =
>                     MessageL1CostInfo::calculate(
>                         call_infos.into_iter(),
> ```

Can we move this up to the `call_infos` line?



_Code quote:_
```XML
.into_iter()
```


<!-- Sent from Reviewable.io -->

2024-01-23 14:46 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/call_info.rs` line 36 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NopuHW520pQkfbOO9_i:-NoqYMiH8Fyup7KTp64y:bsi6f2n) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b09382192c908a6019ce380b48dc3a125dc963/crates/blockifier/src/execution/call_info.rs#L36)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Where? Please link to the code.
</blockquote></details>

here: 
https://github.com/starkware-libs/blockifier/blob/9c065aaf4dfb696a818935605febf12777c782df/crates/blockifier/src/fee/gas_usage.rs#L48

it doesn't work without the public visibality.
___
*[`crates/blockifier/src/execution/call_info.rs` line 47 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NopuOT93JQGVfCBf8Aa:-NoqQoRCCdUL3m0Sc6LK:bnlmmot) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b09382192c908a6019ce380b48dc3a125dc963/crates/blockifier/src/execution/call_info.rs#L47)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What exactly does it do?
</blockquote></details>

from rust-lang:
flat_map creates an iterator that works like map, but flattens nested structure.
The `map`adapter is very useful, but only when the closure argument produces values. If it produces an iterator instead, there’s an extra layer of indirection. `flat_map()` will remove this extra layer on its own.

In this case, where 'l2_to_l1_payload_lengths' returns a 'TransactionExecutionResult<Vec<usize>>', using 'flat_map' ensures that the final result is a flattened 'Vec<usize>'
___
*[`crates/blockifier/src/execution/call_info.rs` line 44 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NoqPSamAK2XE7Id2jPW:-Noqf9PQ1vfPb9Urc4n-:bm0pehq) ([raw file](https://github.com/starkware-libs/blockifier/blob/81aab7c242cee9f5b4963ff30be17ac98cc75221/crates/blockifier/src/execution/call_info.rs#L44)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Will cause `panic`; instead, add the error variant to the appropriate error enum, and return a result - as before.
</blockquote></details>

I tried using 'flat_map' but wasn't successful, so I went back to the previous version.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 103 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NoqPoqx8QRzAPu9nacT:-NoqauJK30xwgDiMe5cr:b-ni29gb) ([raw file](https://github.com/starkware-libs/blockifier/blob/81aab7c242cee9f5b4963ff30be17ac98cc75221/crates/native_blockifier/src/transaction_executor.rs#L103)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we move this up to the `call_infos` line?
</blockquote></details>

I tried but couldn't make it work.


<!-- Sent from Reviewable.io -->

2024-01-23 15:49 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @elintul)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 103 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NoqPoqx8QRzAPu9nacT:-Nor-iUa3NbV-HZIFg1y:bt2vr0y) ([raw file](https://github.com/starkware-libs/blockifier/blob/81aab7c242cee9f5b4963ff30be17ac98cc75221/crates/native_blockifier/src/transaction_executor.rs#L103)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

I tried but couldn't make it work.
</blockquote></details>

Fixed!


<!-- Sent from Reviewable.io -->

2024-01-25 10:07 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r17, 1 of 1 files at r18, 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-:-Np-4h6NBs0-RlnVN_0S:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ayeletstarkware)

___
*[`crates/blockifier/src/execution/call_info.rs` line 36 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-NopuHW520pQkfbOO9_i:-Nozwldq1l6lS8ucfA2F:b-a9vsy3) ([raw file](https://github.com/starkware-libs/blockifier/blob/94b09382192c908a6019ce380b48dc3a125dc963/crates/blockifier/src/execution/call_info.rs#L36)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

here: 
https://github.com/starkware-libs/blockifier/blob/9c065aaf4dfb696a818935605febf12777c782df/crates/blockifier/src/fee/gas_usage.rs#L48

it doesn't work without the public visibality.
</blockquote></details>

Okay, didn't know that unpacking to the struct means the regular c-tor must be `pub`lic. 
___
*[`crates/blockifier/src/execution/call_info.rs` line 102 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Np-3LHk7V1fEqIw054Z:-Np-3LHk7V1fEqIw054_:bvp0s5y) ([raw file](https://github.com/starkware-libs/blockifier/blob/54f2f5b445404963e1f91252d96f751d36eba58d/crates/blockifier/src/execution/call_info.rs#L102)):*
> ```XML
>     /// Returns a list of Starknet L2ToL1Payload length collected during the execution, sorted
>     /// by the order in which they were sent.
>     pub fn get_sorted_l2_to_l1_payloads_length(&self) -> TransactionExecutionResult<Vec<usize>> {
> ```

Restore?



_Code quote:_
```XML
get_sorted_
```


<!-- Sent from Reviewable.io -->

2024-01-25 11:32 UTC, elintul approved these changes
> Reviewed 2 of 2 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)



<!-- Sent from Reviewable.io -->

2024-01-25 12:58 UTC, elintul requested changes
> Reviewed 2 of 2 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Np-gj0M61L5F6U_laYb:-Np-gj0M61L5F6U_laYc:b-e8f697) (no related file):*
Please link to the Python-side PR.

___


<!-- Sent from Reviewable.io -->

2024-01-25 13:34 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1290#-Np-gj0M61L5F6U_laYb:-Np-p6R3DGl1YxPG_JHT:bnqtqfb) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please link to the Python-side PR.
</blockquote></details>

https://reviewable.io/reviews/starkware-industries/starkware/33090

___


<!-- Sent from Reviewable.io -->

2024-01-25 13:36 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1290)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ayeletstarkware)



<!-- Sent from Reviewable.io -->

2024-01-25 13:44 UTC, merged