Clear global_contract_cache on revert block.
starkware-libs/blockifier pull request #1295
Opened 2023-12-27 16:05 UTC by ArniStarkware

Tested against: https://github.com/starkware-industries/starkware/tree/arni/blockifier_revert_bug/poc/declare_v2 with a local repo.

2023-12-28 11:45 UTC, noaov1 requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-NmjCTLoBc12ni7aAusW:-NmjCTLoBc12ni7aAusX:bvlwytd) ([raw file](https://github.com/starkware-libs/blockifier/blob/88190c341207a5d6256caf38120d501ec1042b76/crates/native_blockifier/src/py_block_executor.rs#L178)):*
> ```XML
>     #[pyo3(signature = (block_number))]
>     pub fn revert_block(&mut self, block_number: u64) -> NativeBlockifierResult<()> {
>         self.global_contract_cache.cache_clear();
> ```

@elintul pointed out that this can be painful. Note- this cache stores every contract that was declared or executed.
It is better to clean only the relevant declared contracts (note that you get this information from `revert_state_diff`).



_Code quote:_
```XML
        self.global_contract_cache.cache_clear();
```


<!-- Sent from Reviewable.io -->

2023-12-28 14:20 UTC, ArniStarkware commented
*[`crates/blockifier/src/state/cached_state.rs` line 705 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nmkmu7X8pgCH1XyLER4:-Nmkmu7Y7hygvWB6eITY:b-pjgfts) ([raw file](https://github.com/starkware-libs/blockifier/blob/88190c341207a5d6256caf38120d501ec1042b76/crates/blockifier/src/state/cached_state.rs#L705)):*
> ```XML
> impl GlobalContractCache {
>     pub fn cache_clear(&mut self) {
>         self.0.lock().unwrap().cache_clear();
> ```

An unwrap seems unhealthy...



_Code quote:_
```XML
self.0.lock().unwrap().cache_clear();
```


<!-- Sent from Reviewable.io -->

2023-12-31 08:41 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @elintul, and @noaov1)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nmz09iJ7sjrPdxMZ7LI:-Nmz09iJ7sjrPdxMZ7LJ:b-1r0reh) ([raw file](https://github.com/starkware-libs/blockifier/blob/88190c341207a5d6256caf38120d501ec1042b76/crates/native_blockifier/src/py_block_executor.rs#L53)):*
> ```XML
>             tx_executor,
>             storage: Box::new(storage),
>             global_contract_cache: GlobalContractCache::default(),
> ```

Add a TODO to make the cache size configurable



_Code quote:_
```XML
  global_contract_cache: GlobalContractCache::default(),
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-NmjCTLoBc12ni7aAusW:-Nmz0VRe9kBO151Ys1I6:b-b9vqrk) ([raw file](https://github.com/starkware-libs/blockifier/blob/88190c341207a5d6256caf38120d501ec1042b76/crates/native_blockifier/src/py_block_executor.rs#L178)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

@elintul pointed out that this can be painful. Note- this cache stores every contract that was declared or executed.
It is better to clean only the relevant declared contracts (note that you get this information from `revert_state_diff`).
</blockquote></details>

The cache size is (and should be) limited (currently hard-coded 100), and reverting a block is highly rare, so this solution is simple and not too bad


<!-- Sent from Reviewable.io -->

2023-12-31 08:44 UTC, elintul requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nmz1tgh3qb569USfEye:-Nmz1tgh3qb569USfEyf:b-hhg9i5) (no related file):*
Consider rebasing over `main-v0.13.0`.

___
___
*[`crates/blockifier/src/state/cached_state.rs` line 705 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nmkmu7X8pgCH1XyLER4:-Nmz1lXbAZbeornY8t48:b-li4wdv) ([raw file](https://github.com/starkware-libs/blockifier/blob/88190c341207a5d6256caf38120d501ec1042b76/crates/blockifier/src/state/cached_state.rs#L705)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

An unwrap seems unhealthy...
</blockquote></details>

Right, how is the object locked in the filling stage?


<!-- Sent from Reviewable.io -->

2023-12-31 09:45 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @elintul, and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nmz1tgh3qb569USfEye:-NmzFdco72384qEoPXkv:b-ap1mpq) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider rebasing over `main-v0.13.0`.
</blockquote></details>

@ArniStarkware indeed, we're going to create a new tag for 0.13.0 anyway

___


<!-- Sent from Reviewable.io -->

2023-12-31 11:42 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 705 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nmkmu7X8pgCH1XyLER4:-NmzfUEIDIeRt1eCZ5GY:b-pko3k5) ([raw file](https://github.com/starkware-libs/blockifier/blob/88190c341207a5d6256caf38120d501ec1042b76/crates/blockifier/src/state/cached_state.rs#L705)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Right, how is the object locked in the filling stage?
</blockquote></details>

Can't you use `fn global_class_hash_to_class`?


<!-- Sent from Reviewable.io -->

2023-12-31 13:23 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2023-12-31 13:26 UTC, ArniStarkware commented
It was tested against 0.13.0 as well. 





<!-- Sent from Reviewable.io -->

2023-12-31 15:35 UTC, elintul reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 707 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn-VwPL0DR5gGjAFDYR:-Nn-VwPMAOhJcd-oj_nT:bdwdvad) ([raw file](https://github.com/starkware-libs/blockifier/blob/59c1a19c7a89595517dd5ca0e5e11e68fd4b30c7/crates/blockifier/src/state/cached_state.rs#L707)):*
> ```XML
>     // store. The Guard will panic only if the Mutex panics during the lock operation, but
>     // this shouldn't happen in our flow.
>     // Note: `&mut` is used since the LRU cache updates internal counters on reads.
> ```

This is out of scope here; if you want to add this comment, please move it to `StateReader` trait instead.



_Code quote:_
```XML
// Note: `&mut` is used since the LRU cache updates internal counters on reads.
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 708 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn-V_mS7rfh05i8yCLO:-Nn-V_mS7rfh05i8yCLP:bcrmep1) ([raw file](https://github.com/starkware-libs/blockifier/blob/59c1a19c7a89595517dd5ca0e5e11e68fd4b30c7/crates/blockifier/src/state/cached_state.rs#L708)):*
> ```XML
>     // this shouldn't happen in our flow.
>     // Note: `&mut` is used since the LRU cache updates internal counters on reads.
>     fn lock_mutex_gaurd_cache(&mut self) -> MutexGuard<'_, ContractClassLRUCache> {
> ```

Too many impl. details in the function name.



_Suggestion:_
```XML
lock
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 708 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn-VeugC-5jp-63I9Js:-Nn-VeuhB74LCDlmmYyO:b2f2ura) ([raw file](https://github.com/starkware-libs/blockifier/blob/59c1a19c7a89595517dd5ca0e5e11e68fd4b30c7/crates/blockifier/src/state/cached_state.rs#L708)):*
> ```XML
>     // this shouldn't happen in our flow.
>     // Note: `&mut` is used since the LRU cache updates internal counters on reads.
>     fn lock_mutex_gaurd_cache(&mut self) -> MutexGuard<'_, ContractClassLRUCache> {
> ```

Does this type repeat more than once? If so, please alias.



_Code quote:_
```XML
MutexGuard<'_, ContractClassLRUCache>
```


<!-- Sent from Reviewable.io -->

2023-12-31 15:42 UTC, elintul requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295)* status: all files reviewed, 6 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 706 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn-W7wQDbPzI5p6aRnN:-Nn-W7wQDbPzI5p6aRnO:b-7v1glo) ([raw file](https://github.com/starkware-libs/blockifier/blob/59c1a19c7a89595517dd5ca0e5e11e68fd4b30c7/crates/blockifier/src/state/cached_state.rs#L706)):*
> ```XML
>     // Locks the Mutex and unwraps the MutexGuard, thus exposing the internal cache
>     // store. The Guard will panic only if the Mutex panics during the lock operation, but
>     // this shouldn't happen in our flow.
> ```

I can't say I understood this documentation. 
Rephrasing suggestion: "Locks the cache for atomic access. Although conceptually shared, writing to this cache is only possible for one writer at a time.". No reason to go into more details, IMO. I'll shared Gilad's original messages on Slack so you can read and maybe add more words.



_Code quote:_
```XML
    // Locks the Mutex and unwraps the MutexGuard, thus exposing the internal cache
    // store. The Guard will panic only if the Mutex panics during the lock operation, but
    // this shouldn't happen in our flow.
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 712 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn-XZ4M8hxqNDRlhMj3:-Nn-XZ4NBphKzS7TxgZh:b-y4wzfu) ([raw file](https://github.com/starkware-libs/blockifier/blob/59c1a19c7a89595517dd5ca0e5e11e68fd4b30c7/crates/blockifier/src/state/cached_state.rs#L712)):*
> ```XML
>     }
> 
>     pub fn cache_clear(&mut self) {
> ```

The "cache" part is clear from the context.



_Suggestion:_
```XML
clear
```


<!-- Sent from Reviewable.io -->

2024-01-01 09:55 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 706 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn-W7wQDbPzI5p6aRnN:-Nn3JJV64PQbYzEC54us:b-kc6s92) ([raw file](https://github.com/starkware-libs/blockifier/blob/59c1a19c7a89595517dd5ca0e5e11e68fd4b30c7/crates/blockifier/src/state/cached_state.rs#L706)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I can't say I understood this documentation. 
Rephrasing suggestion: "Locks the cache for atomic access. Although conceptually shared, writing to this cache is only possible for one writer at a time.". No reason to go into more details, IMO. I'll shared Gilad's original messages on Slack so you can read and maybe add more words.
</blockquote></details>

Done.
If you think there is no need for more details - this seems like a satisfactory explanation of the lock function.
___
*[`crates/blockifier/src/state/cached_state.rs` line 707 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn-VwPL0DR5gGjAFDYR:-Nn3RJuN15Y_PgPNEytl:blx6gbf) ([raw file](https://github.com/starkware-libs/blockifier/blob/59c1a19c7a89595517dd5ca0e5e11e68fd4b30c7/crates/blockifier/src/state/cached_state.rs#L707)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This is out of scope here; if you want to add this comment, please move it to `StateReader` trait instead.
</blockquote></details>

This comment was copied from: `global_class_hash_to_class` of `impl<S: StateReader> CachedState<S>`, where it exists now. 
___
*[`crates/blockifier/src/state/cached_state.rs` line 708 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn-V_mS7rfh05i8yCLO:-Nn3I01h1xOUccnYFF0m:b8sjqfv) ([raw file](https://github.com/starkware-libs/blockifier/blob/59c1a19c7a89595517dd5ca0e5e11e68fd4b30c7/crates/blockifier/src/state/cached_state.rs#L708)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Too many impl. details in the function name.
</blockquote></details>

Done.
Note I changed the implementation so that the `lock` function of `GlobalContractCache` will not collide with the `lock` function of `Arc<_>`.
___
*[`crates/blockifier/src/state/cached_state.rs` line 708 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn-VeugC-5jp-63I9Js:-Nn3IuWGAJeNJet7Bl46:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/59c1a19c7a89595517dd5ca0e5e11e68fd4b30c7/crates/blockifier/src/state/cached_state.rs#L708)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Does this type repeat more than once? If so, please alias.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 712 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn-XZ4M8hxqNDRlhMj3:-Nn3Izxl3u5MQPHuPK34:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/59c1a19c7a89595517dd5ca0e5e11e68fd4b30c7/crates/blockifier/src/state/cached_state.rs#L712)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

The "cache" part is clear from the context.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-02 07:25 UTC, elintul submitted a review, later dismissed
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 708 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn-V_mS7rfh05i8yCLO:-Nn82mYq-sKeaK3XLH1w:b-g559dv) ([raw file](https://github.com/starkware-libs/blockifier/blob/59c1a19c7a89595517dd5ca0e5e11e68fd4b30c7/crates/blockifier/src/state/cached_state.rs#L708)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
Note I changed the implementation so that the `lock` function of `GlobalContractCache` will not collide with the `lock` function of `Arc<_>`.
</blockquote></details>

Is it possible to override an existing method's name?
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn82wNC4B0oQkx2bS6P:-Nn82wND8xUsXdeBRUvV:b-9vwcz5) ([raw file](https://github.com/starkware-libs/blockifier/blob/37a6a4d0a659289f69dffe8044a67e6023cf24bc/crates/native_blockifier/src/py_block_executor.rs#L47)):*
> ```XML
>         log::debug!("Initialized Block Executor.");
>         // TODO(Arni, 7/1/2024): make global_contract_cache size configurable via a CachedState
>         // constructor argument.
> ```

No need to repeat, it's the same as the other comment, right?



_Code quote:_
```XML
        // TODO(Arni, 7/1/2024): make global_contract_cache size configurable via a CachedState
        // constructor argument.
```


<!-- Sent from Reviewable.io -->

2024-01-02 07:44 UTC, elintul approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 708 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn-V_mS7rfh05i8yCLO:-Nn877oz4cJy2uPmnIs7:b1ifmg8) ([raw file](https://github.com/starkware-libs/blockifier/blob/59c1a19c7a89595517dd5ca0e5e11e68fd4b30c7/crates/blockifier/src/state/cached_state.rs#L708)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

It is not an override. If the function name was `lock_mutex_gaurd_cache`, when `self` looks for `.lock`, it would get into the one member of the struct `GlobalContractCache`. Now that the struct implements a `lock` function, it takes precedence. 

See compiler diagnostic:
```
error[E0599]: no method named `expect` found for struct `std::sync::MutexGuard<'_, cached::SizedCache<starknet_api::core::ClassHash, execution::contract_class::ContractClass>>` in the current scope
   --> crates/blockifier/src/state/cached_state.rs:706:21
    |
706 |         self.lock().expect("Global contract cache is poisoned.")
    |                     ^^^^^^ method not found in `MutexGuard<'_, SizedCache<ClassHash, ContractClass>>`
```

</blockquote></details>

How was it previously possible to do `self.lock()` (instead of `self.0.lock()`?


<!-- Sent from Reviewable.io -->

2024-01-02 08:02 UTC, ArniStarkware commented
*[`crates/blockifier/src/state/cached_state.rs` line 708 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn-V_mS7rfh05i8yCLO:-Nn8BCt92w_qS_2Z7wZE:bt0s2m4) ([raw file](https://github.com/starkware-libs/blockifier/blob/59c1a19c7a89595517dd5ca0e5e11e68fd4b30c7/crates/blockifier/src/state/cached_state.rs#L708)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How was it previously possible to do `self.lock()` (instead of `self.0.lock()`?
</blockquote></details>

IIUC, it looked at the one member of the struct `GlobalContractCache`. It is a feature of Rust for structs with only one member.


<!-- Sent from Reviewable.io -->

2024-01-02 08:06 UTC, elintul submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 708 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn-V_mS7rfh05i8yCLO:-Nn8CHjo4PgeUo5IpxL_:b-k6h4m3) ([raw file](https://github.com/starkware-libs/blockifier/blob/59c1a19c7a89595517dd5ca0e5e11e68fd4b30c7/crates/blockifier/src/state/cached_state.rs#L708)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

IIUC, it looked at the one member of the struct `GlobalContractCache`. It is a feature of Rust for structs with only one member.
</blockquote></details>

Are you sure? Can you check in a small example to make sure?


<!-- Sent from Reviewable.io -->

2024-01-02 08:09 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-:-Nn8AQmP-dxVIzqEB02D:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-NmjCTLoBc12ni7aAusW:-Nn8BYsH9DtOiLFwTILl:b2hiurp) ([raw file](https://github.com/starkware-libs/blockifier/blob/88190c341207a5d6256caf38120d501ec1042b76/crates/native_blockifier/src/py_block_executor.rs#L178)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I am marking this thread as resolved.
</blockquote></details>

Non-blocking: add a short comment above this line (not trivial)


<!-- Sent from Reviewable.io -->

2024-01-02 08:46 UTC, ArniStarkware commented
*[`crates/blockifier/src/state/cached_state.rs` line 708 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn-V_mS7rfh05i8yCLO:-Nn8L1EH3NkIlfJjhpgH:b83xg3l) ([raw file](https://github.com/starkware-libs/blockifier/blob/59c1a19c7a89595517dd5ca0e5e11e68fd4b30c7/crates/blockifier/src/state/cached_state.rs#L708)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are you sure? Can you check in a small example to make sure?
</blockquote></details>

I was wrong. The issue was discussed in Slack and fixed here. Removed: ` derive_more::Deref, derive_more::DerefMut` from `GlobalContractCache`.


<!-- Sent from Reviewable.io -->

2024-01-02 08:53 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul, @noaov1, and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 178 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-NmjCTLoBc12ni7aAusW:-Nn8N70c4zh7NkNORjCE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/88190c341207a5d6256caf38120d501ec1042b76/crates/native_blockifier/src/py_block_executor.rs#L178)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Non-blocking: add a short comment above this line (not trivial)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-02 08:55 UTC, Yoni-Starkware approved these changes
> Reviewed 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-01-02 12:06 UTC, noaov1 submitted a review, later dismissed
> Reviewed 1 of 3 files at r4, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295)* status: all files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 694 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn92gF3BAOHeZbpEorV:-Nn92gF41zvhL3Gs0Rht:b-m65c53) ([raw file](https://github.com/starkware-libs/blockifier/blob/64c522308b48f8e478002fc63a5fd27164370148/crates/blockifier/src/state/cached_state.rs#L694)):*
> ```XML
>     // TODO(Arni, 7/1/2024): make this configurable via a CachedState constructor argument.
>     const CACHE_SIZE: usize = 100;
> }
> ```

Consider unifying the `impl`s.



_Code quote:_
```XML
impl GlobalContractCache {
    // TODO(Arni, 7/1/2024): make this configurable via a CachedState constructor argument.
    const CACHE_SIZE: usize = 100;
}
```


<!-- Sent from Reviewable.io -->

2024-01-02 12:14 UTC, elintul submitted a review, later dismissed
> Reviewed 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 184 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn94nC10arws-6kF2Zc:-Nn94nC10arws-6kF2Zd:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/64c522308b48f8e478002fc63a5fd27164370148/crates/native_blockifier/src/py_block_executor.rs#L184)):*
> ```XML
>     pub fn revert_block(&mut self, block_number: u64) -> NativeBlockifierResult<()> {
>         // Clearing the global contract cache as the revert_block function on the storage does not
>         // affect this cache. The declared contract may still be cached unless cleared.
> ```





_Suggestion:_
```XML
        // Clear global class cache, to peroperly revert classes declared in the reverted 
        // block.
```


<!-- Sent from Reviewable.io -->

2024-01-02 12:20 UTC, noaov1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-:-Nn96ZGAAHVXeapXEVKQ:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)



<!-- Sent from Reviewable.io -->

2024-01-02 12:24 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-:-Nn97X2JBUBIetToBN3H:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)



<!-- Sent from Reviewable.io -->

2024-01-02 12:41 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1295)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 694 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn92gF3BAOHeZbpEorV:-Nn95ZUr3EOH7rh5QeEA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/64c522308b48f8e478002fc63a5fd27164370148/crates/blockifier/src/state/cached_state.rs#L694)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider unifying the `impl`s.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 184 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1295#-Nn94nC10arws-6kF2Zc:-Nn95on75vLfssqp2av6:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/64c522308b48f8e478002fc63a5fd27164370148/crates/native_blockifier/src/py_block_executor.rs#L184)):*
> ```XML
>     pub fn revert_block(&mut self, block_number: u64) -> NativeBlockifierResult<()> {
>         // Clearing the global contract cache as the revert_block function on the storage does not
>         // affect this cache. The declared contract may still be cached unless cleared.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-01-02 12:41 UTC, merged