TransactionExecutionInfo: add serialize
starkware-libs/blockifier pull request #1315
Opened 2024-01-07 10:21 UTC by MohammadNassar1

2024-01-07 11:16 UTC, elintul requested changes
> Reviewed 10 of 14 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 7 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/call_info.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnYaO7g9Hk9wYcjyxWP:-NnYaO7g9Hk9wYcjyxWQ:b-90eygn) ([raw file](https://github.com/starkware-libs/blockifier/blob/82e76fc43591f84dfac88baf61a7ce2d3ccff6fc/crates/blockifier/src/execution/call_info.rs#L16)):*
> ```XML
> use crate::transaction::objects::TransactionExecutionResult;
> 
> #[derive(Clone, Debug, Default, Eq, PartialEq, Serialize)]
> ```

What is the default impl. of this trait?



_Code quote:_
```XML
Serialize
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnYblnD8DQHMgR0rewg:-NnYblnD8DQHMgR0rewh:b-xt6llo) ([raw file](https://github.com/starkware-libs/blockifier/blob/82e76fc43591f84dfac88baf61a7ce2d3ccff6fc/crates/blockifier/src/execution/call_info.rs#L59)):*
> ```XML
> 
> #[derive(Debug, Default, Eq, PartialEq)]
> pub struct VmExecutionResourcesWrapper(pub VmExecutionResources);
> ```

As `VmExecutionResources` is already an alias, consider renaming it to `VmExecutionResourcesInner` and then you won't have to change the type in `CallInfo`.
If in the future LC adds the trait to their struct, we'd have less changes.



_Code quote:_
```XML
VmExecutionResourcesWrapper
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnYciwkDDWYd3obQDiK:-NnYciwkDDWYd3obQDiL:b-yhentd) ([raw file](https://github.com/starkware-libs/blockifier/blob/82e76fc43591f84dfac88baf61a7ce2d3ccff6fc/crates/blockifier/src/execution/call_info.rs#L59)):*
> ```XML
> 
> #[derive(Debug, Default, Eq, PartialEq)]
> pub struct VmExecutionResourcesWrapper(pub VmExecutionResources);
> ```

Consider adding `new` and implementing `Deref` for less changes throughout the code. Perhaps Gilad will have a good suggestion.



_Code quote:_
```XML
pub struct VmExecutionResourcesWrapper
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnYbANN2Qr1Q5vQOP8c:-NnYbANN2Qr1Q5vQOP8d:bt5ogfz) ([raw file](https://github.com/starkware-libs/blockifier/blob/82e76fc43591f84dfac88baf61a7ce2d3ccff6fc/crates/blockifier/src/execution/call_info.rs#L62)):*
> ```XML
> 
> impl Serialize for VmExecutionResourcesWrapper {
>     fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
> ```

Can we ask LC to add this trait to their repo.?
Also, while currently implementing here, why can't we add `Serialize` to the wrapper? Is repeating the inner structure necessary?



_Code quote:_
```XML
fn serialize
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnYb_-ZC7nRRzjRq378:-NnYb_-ZC7nRRzjRq379:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/82e76fc43591f84dfac88baf61a7ce2d3ccff6fc/crates/blockifier/src/execution/call_info.rs#L75)):*
> ```XML
> 
>         // Finish serializing the struct
>         state.end()
> ```





_Suggestion:_
```XML
        // Create a serialize struct with the appropriate number of fields.
        let mut state = serializer.serialize_struct("ExecutionResourcesWrapper", 3)?;

        // Serialize each field individually.
        state.serialize_field("builtin_instance_counter", &self.0.builtin_instance_counter)?;
        state.serialize_field("n_memory_holes", &self.0.n_memory_holes)?;
        state.serialize_field("n_steps", &self.0.n_steps)?;

        // Finish serializing the struct.
        state.end()
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnYcAx84KnUQi3IV7rE:-NnYcAx84KnUQi3IV7rF:bqu4mia) ([raw file](https://github.com/starkware-libs/blockifier/blob/82e76fc43591f84dfac88baf61a7ce2d3ccff6fc/crates/blockifier/src/execution/call_info.rs#L93)):*
> ```XML
> 
> impl Serialize for CallInfo {
>     fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
> ```

Why implement manually?



_Code quote:_
```XML
fn serialize<
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnYc_m5AYl1ApHIYSDD:-NnYc_m5AYl1ApHIYSDE:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/82e76fc43591f84dfac88baf61a7ce2d3ccff6fc/crates/blockifier/src/execution/entry_point_execution.rs#L14)):*
> ```XML
> use starknet_api::stark_felt;
> 
> use super::call_info::VmExecutionResourcesWrapper;
> ```





_Suggestion:_
```XML
crate::...
```


<!-- Sent from Reviewable.io -->

2024-01-07 11:17 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 8 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnYcsrq4aN1Y5GmOrB8:-NnYcsrq4aN1Y5GmOrB9:b-84thc8) (no related file):*
Just to make sure: only the structs required to allow serialization of `TransactionExecutionInfo` now implement `Serialize`, right?

___


<!-- Sent from Reviewable.io -->

2024-01-07 12:56 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: 11 of 14 files reviewed, 6 unresolved discussions (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnYcsrq4aN1Y5GmOrB8:-NnYfixv0wTn3C01tIOa:bh49h2r) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Just to make sure: only the structs required to allow serialization of `TransactionExecutionInfo` now implement `Serialize`, right?
</blockquote></details>

Goal: to enable serialization for `TransactionExecutionInfo`.
I've derived serialize to all the inner structs, and implemented `Serialize` for the VmExecutionResources as it's an LC struct.

___
___
*[`crates/blockifier/src/execution/call_info.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnYaO7g9Hk9wYcjyxWP:-NnYhkY6CYHnQO-USedL:bnbd7n5) ([raw file](https://github.com/starkware-libs/blockifier/blob/82e76fc43591f84dfac88baf61a7ce2d3ccff6fc/crates/blockifier/src/execution/call_info.rs#L16)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What is the default impl. of this trait?
</blockquote></details>

something like:
`self.0.serialize(...)`
Which is the same like my below implementation for `VmExecutionResourcesWrapper`.
___
*[`crates/blockifier/src/execution/call_info.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnYblnD8DQHMgR0rewg:-NnYjuP7ED9a6sMrL58t:b2n34il) ([raw file](https://github.com/starkware-libs/blockifier/blob/82e76fc43591f84dfac88baf61a7ce2d3ccff6fc/crates/blockifier/src/execution/call_info.rs#L59)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

As `VmExecutionResources` is already an alias, consider renaming it to `VmExecutionResourcesInner` and then you won't have to change the type in `CallInfo`.
If in the future LC adds the trait to their struct, we'd have less changes.
</blockquote></details>

In all the files?
Many files are using this alias. [example](https://github.com/starkware-libs/blockifier/blob/82e76fc43591f84dfac88baf61a7ce2d3ccff6fc/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L7)
___
*[`crates/blockifier/src/execution/call_info.rs` line 59 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnYciwkDDWYd3obQDiK:-NnYzHLz-k9ogMWov8-R:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/82e76fc43591f84dfac88baf61a7ce2d3ccff6fc/crates/blockifier/src/execution/call_info.rs#L59)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider adding `new` and implementing `Deref` for less changes throughout the code. Perhaps Gilad will have a good suggestion.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/call_info.rs` line 62 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnYbANN2Qr1Q5vQOP8c:-NnYnYmt1ygMKe9JeOGl:b-inh5a1) ([raw file](https://github.com/starkware-libs/blockifier/blob/82e76fc43591f84dfac88baf61a7ce2d3ccff6fc/crates/blockifier/src/execution/call_info.rs#L62)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we ask LC to add this trait to their repo.?
Also, while currently implementing here, why can't we add `Serialize` to the wrapper? Is repeating the inner structure necessary?
</blockquote></details>

Adding `Serialize` to the Wrapper requires an implementation in the inner fields.
___
*[`crates/blockifier/src/execution/call_info.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnYcAx84KnUQi3IV7rE:-NnYuxj54JL5IPcwQ5iN:bon364y) ([raw file](https://github.com/starkware-libs/blockifier/blob/82e76fc43591f84dfac88baf61a7ce2d3ccff6fc/crates/blockifier/src/execution/call_info.rs#L93)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why implement manually?
</blockquote></details>

You are right; no need for it.


<!-- Sent from Reviewable.io -->

2024-01-07 15:28 UTC, elintul reviewed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-01-08 08:14 UTC, giladchase requested changes
> Reviewed 8 of 14 files at r1, 3 of 4 files at r2, 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/call_info.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnYaO7g9Hk9wYcjyxWP:-Nnc3wti-LlIEK5g-Nsa:b-eegoe9) ([raw file](https://github.com/starkware-libs/blockifier/blob/82e76fc43591f84dfac88baf61a7ce2d3ccff6fc/crates/blockifier/src/execution/call_info.rs#L16)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

something like:
`self.0.serialize(...)`
Which is the same like my below implementation for `VmExecutionResourcesWrapper`.
</blockquote></details>

It'll ignore the wrapper types and just print the primitives in json format, so in this case, an array of [u8;32] arrays.

Example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=569bdb8b3bc4d77d369b1e591ae83a7d
___
*[`crates/blockifier/src/execution/call_info.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Nnc4vg-0J4Rg_RqZPwS:-Nnc4vg-0J4Rg_RqZPwT:bmf15yf) ([raw file](https://github.com/starkware-libs/blockifier/blob/551706ad1a6bd01a71d8bb1f5a146f52871138b8/crates/blockifier/src/execution/call_info.rs#L68)):*
> ```XML
>         &self.0
>     }
> }
> ```

The derive generates the code you wrote



_Suggestion:_
```XML
#[derive(Debug, Default, Eq, PartialEq, derive_more::Deref)]
pub struct VmExecutionResourcesWrapper(pub VmExecutionResources);
```
___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 256 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Nnc5gOUEdaVRg786eRZ:-Nnc5gOUEdaVRg786eR_:b-zdpwvx) ([raw file](https://github.com/starkware-libs/blockifier/blob/551706ad1a6bd01a71d8bb1f5a146f52871138b8/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L256)):*
> ```XML
>             gas_consumed: 0,
>         },
>         vm_resources: VmExecutionResourcesWrapper(full_call_vm_resources.filter_unused_builtins()),
> ```

nit: Consider adding `derive_more::From` to this type and replacing it with `full_call_vm_resources.filter_unused_builtins().into()`, this hides the newtype which is generally a good thing, since it only exists due to technical constraints and doesn't have any significance on its own.
(DItto for other constructors in other files.)

But totally not critical, can stay as is.



_Code quote:_
```XML
VmExecutionResourcesWrapper(full_call_vm_resources.filter_unused_builtins())
```


<!-- Sent from Reviewable.io -->

2024-01-09 10:42 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: 8 of 14 files reviewed, 5 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/execution/call_info.rs` line 68 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Nnc4vg-0J4Rg_RqZPwS:-Nnhl5vkAYLDvdfqwpr2:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/551706ad1a6bd01a71d8bb1f5a146f52871138b8/crates/blockifier/src/execution/call_info.rs#L68)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

The derive generates the code you wrote
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/deprecated_entry_point_execution.rs` line 256 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Nnc5gOUEdaVRg786eRZ:-NnhmIxL1fqVwYzN0PxL:b-mslqb5) ([raw file](https://github.com/starkware-libs/blockifier/blob/551706ad1a6bd01a71d8bb1f5a146f52871138b8/crates/blockifier/src/execution/deprecated_entry_point_execution.rs#L256)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

nit: Consider adding `derive_more::From` to this type and replacing it with `full_call_vm_resources.filter_unused_builtins().into()`, this hides the newtype which is generally a good thing, since it only exists due to technical constraints and doesn't have any significance on its own.
(DItto for other constructors in other files.)

But totally not critical, can stay as is.
</blockquote></details>

Liked it.
Code was updated accordingly.


<!-- Sent from Reviewable.io -->

2024-01-10 07:38 UTC, giladchase approved these changes
> Reviewed 6 of 6 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-01-11 14:30 UTC, elintul requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: 15 of 17 files reviewed, 5 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/call_info.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnYaO7g9Hk9wYcjyxWP:-NnsaQdNDEt3xCss5uIJ:b-ucfknh) ([raw file](https://github.com/starkware-libs/blockifier/blob/82e76fc43591f84dfac88baf61a7ce2d3ccff6fc/crates/blockifier/src/execution/call_info.rs#L16)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

It'll ignore the wrapper types and just print the primitives in json format, so in this case, an array of [u8;32] arrays.

Example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=569bdb8b3bc4d77d369b1e591ae83a7d
</blockquote></details>

Thanks!
___
*[`crates/blockifier/src/execution/call_info.rs` line 58 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Nnsv-Ce2XtpbSCT6WfP:-Nnsv-Ce2XtpbSCT6WfQ:bjdkfmg) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0195fd77deba2cf64a2749a8f5af0c0093d647/crates/blockifier/src/execution/call_info.rs#L58)):*
> ```XML
> }
> 
> #[derive(Debug, Default, Eq, PartialEq, derive_more::Deref, derive_more::From)]
> ```

Do we still need `.0`-s throughout the code?



_Code quote:_
```XML
derive_more::Deref
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 73 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnsuDIs158ENQrKxC3g:-NnsuDIs158ENQrKxC3h:b6c1h22) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0195fd77deba2cf64a2749a8f5af0c0093d647/crates/blockifier/src/execution/call_info.rs#L73)):*
> ```XML
>     {
>         // Create a serialize struct with the appropriate number of fields.
>         let mut state = serializer.serialize_struct("ExecutionResourcesWrapper", 3)?;
> ```

What does this name represent?



_Code quote:_
```XML
"ExecutionResourcesWrapper"
```


<!-- Sent from Reviewable.io -->

2024-01-15 13:42 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: 11 of 17 files reviewed, 5 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/execution/call_info.rs` line 58 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Nnsv-Ce2XtpbSCT6WfP:-NoCDfik4ty7RLfLlrsf:b-anpfr3) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0195fd77deba2cf64a2749a8f5af0c0093d647/crates/blockifier/src/execution/call_info.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we still need `.0`-s throughout the code?
</blockquote></details>

I used `.0` in one case when using `PyVmExecutionResources::from`, which doesn't call `deref` automatically. The other option is to call it explicitly with `.deref()` instead of `.0`. I prefer the second option.
___
*[`crates/blockifier/src/execution/call_info.rs` line 73 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnsuDIs158ENQrKxC3g:-NoCFaqdE9XzrT9UR82D:b3xyjee) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0195fd77deba2cf64a2749a8f5af0c0093d647/crates/blockifier/src/execution/call_info.rs#L73)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What does this name represent?
</blockquote></details>

It's the name of the struct.
It's not used during the serialization. An example of an output:

"vm_resources":{"builtin_instance_counter":{"range_check_builtin":1},"n_memory_holes":0,"n_steps":62}


<!-- Sent from Reviewable.io -->

2024-01-18 08:28 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: 11 of 17 files reviewed, 4 unresolved discussions (waiting on @elin, @elintul, and @giladchase)

___
*[`crates/blockifier/src/execution/call_info.rs` line 58 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Nnsv-Ce2XtpbSCT6WfP:-NoNNTbk8KKwhCPMjGxt:b2i1qep) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0195fd77deba2cf64a2749a8f5af0c0093d647/crates/blockifier/src/execution/call_info.rs#L58)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Deref is only for method calls unfortunately, so it doesn't apply for field accessors unless they are via getters :(

A common solution for this is to add an `inner()` method which returns self.0 (we haven't done this alot thus far but it's idiomatic).

This allows you to make the inner field private and communicates the NewType'iness of the instance better than `.0` does (because the reader can't tell for certain if this is a newtype or a larger tuple struct with `.1,.2,...` .

(BTW performance-wise this method will likely get inlined anyway)
</blockquote></details>

@elin, what so you think?
___
*[`crates/blockifier/src/execution/call_info.rs` line 73 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnsuDIs158ENQrKxC3g:-NoQepWrDk97KJfsjnMo:b-m14nu4) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0195fd77deba2cf64a2749a8f5af0c0093d647/crates/blockifier/src/execution/call_info.rs#L73)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think she meant the syntax, it's the serialization API that `serde` exposes for defining a custom serialization scheme for a struct that doesn't derive(Serialize) in the normal way.
I think a better api for it could have been `let mut custom_serializer = serializer.begin_custom_serialization_for("NameOfStructYouWantToSerializeNow",...)`
</blockquote></details>

@giladchase, can you please tell me how to use this API?
I couldn't find such a method in the serializer.


<!-- Sent from Reviewable.io -->

2024-01-18 11:17 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: 6 of 17 files reviewed, 4 unresolved discussions (waiting on @elin and @elintul)

___
*[`crates/blockifier/src/execution/call_info.rs` line 73 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NnsuDIs158ENQrKxC3g:-NoRHKHt3STdmK7JTS9O:b1sg19d) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0195fd77deba2cf64a2749a8f5af0c0093d647/crates/blockifier/src/execution/call_info.rs#L73)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

@giladchase, can you please tell me how to use this API?
I couldn't find such a method in the serializer.
</blockquote></details>

Ahh this doesn't exist, i was just giving an example for a better name for this that would have made this action more obvious that "serialize_struct" (which doesn't imply that it is opening a `state`).


<!-- Sent from Reviewable.io -->

2024-01-21 10:00 UTC, elintul requested changes
> Reviewed 2 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: 7 of 17 files reviewed, 7 unresolved discussions (waiting on @elin, @giladchase, and @MohammadNassar1)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 88 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NofSN985dwvYumiOXj5:-NofSN985dwvYumiOXj6:bwz79f9) ([raw file](https://github.com/starkware-libs/blockifier/blob/d42b9ff8098858dafe99cd2b6c733c8d0cb1374b/crates/native_blockifier/src/py_block_executor.rs#L88)):*
> ```XML
>         tx: &PyAny,
>         raw_contract_class: Option<&str>,
>     ) -> NativeBlockifierResult<(Vec<u8>, PyBouncerInfo)> {
> ```

Please define an alias: `RawTransactionExecutionInfo`.



_Code quote:_
```XML
Vec<u8>
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 74 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NofSUneAm339jzKvT2e:-NofSUneAm339jzKvT2f:bcupspm) ([raw file](https://github.com/starkware-libs/blockifier/blob/d42b9ff8098858dafe99cd2b6c733c8d0cb1374b/crates/native_blockifier/src/py_validator.rs#L74)):*
> ```XML
>         // so they are skipped here.
>         if let AccountTransaction::DeployAccount(_deploy_account_tx) = account_tx {
>             let (_bytes_tx_execution_info, _py_bouncer_info) =
> ```

In other locations as well.



_Suggestion:_
```XML
_raw_tx_execution_info
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 90 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NofSdRQ82xZFQYR50-4:-NofSdRQ82xZFQYR50-5:bng3gj0) ([raw file](https://github.com/starkware-libs/blockifier/blob/d42b9ff8098858dafe99cd2b6c733c8d0cb1374b/crates/native_blockifier/src/transaction_executor.rs#L90)):*
> ```XML
>                 tx_visited_storage_entries.extend(tx_execution_info.get_visited_storage_entries());
>                 let bytes_tx_execution_info =
>                     serde_json::to_string(&tx_execution_info).unwrap().into_bytes();
> ```

Please return `SerdeError` instead of `unwrap`ing.



_Code quote:_
```XML
unwrap()
```


<!-- Sent from Reviewable.io -->

2024-01-21 11:29 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: 4 of 17 files reviewed, 6 unresolved discussions (waiting on @elin, @elintul, and @giladchase)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 88 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NofSN985dwvYumiOXj5:-NofgmUK1hKrtLLDZRa1:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d42b9ff8098858dafe99cd2b6c733c8d0cb1374b/crates/native_blockifier/src/py_block_executor.rs#L88)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please define an alias: `RawTransactionExecutionInfo`.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 90 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NofSdRQ82xZFQYR50-4:-NoffvDYE7B8m4XwwTtA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d42b9ff8098858dafe99cd2b6c733c8d0cb1374b/crates/native_blockifier/src/transaction_executor.rs#L90)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please return `SerdeError` instead of `unwrap`ing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-25 11:31 UTC, elintul requested changes
> Reviewed 1 of 5 files at r8, 5 of 10 files at r9, 4 of 7 files at r11, 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 8 unresolved discussions (waiting on @elin and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/call_info.rs` line 58 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Nnsv-Ce2XtpbSCT6WfP:-Np-Nnqu1wgdTcQkq6z_:bmvryqm) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0195fd77deba2cf64a2749a8f5af0c0093d647/crates/blockifier/src/execution/call_info.rs#L58)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

@elin, what so you think?
</blockquote></details>

I'd prefer to encapsulate the fact we're using a wrapper as much as possible, but not if the effort is too big (this is temporary).
___
*[`crates/blockifier/src/execution/call_info.rs` line 58 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Np-LeUi1d8qfM2osEIe:-Np-LeUjEf9QzUduLL-x:b-j1g5tu) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b0c5cdebb0208e218f375e26d43f0d6df0a434f/crates/blockifier/src/execution/call_info.rs#L58)):*
> ```XML
> }
> 
> #[derive(Debug, Default, Eq, PartialEq, derive_more::Deref, derive_more::From)]
> ```

Please alphabetize.



_Code quote:_
```XML
Debug, Default, Eq, PartialEq, derive_more::Deref, derive_more::From
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 65 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Np-LrCbANRvO8JrA13B:-Np-LrCbANRvO8JrA13C:bjtnw6u) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b0c5cdebb0208e218f375e26d43f0d6df0a434f/crates/blockifier/src/execution/call_info.rs#L65)):*
> ```XML
>         VmExecutionResourcesWrapper(vm_execution_resources)
>     }
> }
> ```

I thought it would save some of the changes, but it doesn't. You can revert.



_Code quote:_
```XML
impl VmExecutionResourcesWrapper {
    pub fn new(vm_execution_resources: VmExecutionResources) -> Self {
        VmExecutionResourcesWrapper(vm_execution_resources)
    }
}
```
___
*[`crates/blockifier/src/test_utils/prices.rs` line 85 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Noq3DC91DOG0JROqBdk:-Noq3DC91DOG0JROqBdl:b-fqzclv) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b0c5cdebb0208e218f375e26d43f0d6df0a434f/crates/blockifier/src/test_utils/prices.rs#L85)):*
> ```XML
>         .unwrap()
>         .vm_resources
>         .0
> ```

Still necessary?



_Code quote:_
```XML
        .0
```
___
*[`crates/blockifier/src/transaction/transaction_types.rs` line 8 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Noq3IqrABuSnVy_anlq:-Noq3IqrABuSnVy_anlr:b-j1g5tu) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b0c5cdebb0208e218f375e26d43f0d6df0a434f/crates/blockifier/src/transaction/transaction_types.rs#L8)):*
> ```XML
> use crate::transaction::errors::ParseError;
> 
> #[derive(Clone, Copy, Debug, Deserialize, Serialize, EnumIter, Eq, Hash, PartialEq)]
> ```

Please alphabetize.



_Code quote:_
```XML
Clone, Copy, Debug, Deserialize, Serialize, EnumIter, Eq, Hash, PartialEq
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 29 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Noq44QI9GE6z0e8QDCV:-Noq44QJ2RjpOJwJ7YXd:b-68fbro) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b0c5cdebb0208e218f375e26d43f0d6df0a434f/crates/native_blockifier/src/transaction_executor.rs#L29)):*
> ```XML
> use crate::py_transaction_execution_info::{PyBouncerInfo, PyVmExecutionResources};
> use crate::py_utils::PyFelt;
> ```

Can the new `pub`lic definitions you added be `pub(crate)`? In case they are not part of the public API and only needed for other modules _in the same crate_.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 35 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Noq3TUfCn9msCQ3efFW:-Noq3TUfCn9msCQ3efFX:b-ilurpx) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b0c5cdebb0208e218f375e26d43f0d6df0a434f/crates/native_blockifier/src/transaction_executor.rs#L35)):*
> ```XML
> #[derive(Debug, Serialize)]
> pub struct TypedTransactionExecutionInfo {
>     #[serde(flatten)]
> ```

When does it mean?



_Code quote:_
```XML
#[serde(flatten)]
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 110 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Np-MuH6AioKp1L46792:-Np-MuH6AioKp1L46793:b-mbcx97) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b0c5cdebb0208e218f375e26d43f0d6df0a434f/crates/native_blockifier/src/transaction_executor.rs#L110)):*
> ```XML
>                 let raw_typed_tx_execution_info = serde_json::to_string(&typed_tx)
>                     .map(|s| s.into_bytes())
>                     .map_err(NativeBlockifierError::SerdeError)?;
> ```

ChatGPT's suggestion, is it good?



_Suggestion:_
```XML
                let typed_tx_execution_info = TypedTransactionExecutionInfo {
                    info: tx_execution_info,
                    tx_type: tx_type.to_string(),
                };
                let raw_tx_execution_info = serde_json::to_vec(&typed_tx_execution_info)
                    .map_err(NativeBlockifierError::SerdeError)?;
```


<!-- Sent from Reviewable.io -->

2024-01-25 11:31 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 9 unresolved discussions (waiting on @elin and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Np-Nwqj9TH1AM_qfbMK:-Np-Nwqj9TH1AM_qfbML:b-njnib5) (no related file):*
Please open a PR to LC's repo. when you can.

___


<!-- Sent from Reviewable.io -->

2024-01-25 11:32 UTC, elintul reviewed
> Reviewed 1 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 9 unresolved discussions (waiting on @elin and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-01-25 13:57 UTC, elintul requested changes
> Reviewed 9 of 9 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 4 unresolved discussions (waiting on @elin and @MohammadNassar1)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 110 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Np-MuH6AioKp1L46792:-Np-uBrFDItUzzOexM1R:bco1vew) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b0c5cdebb0208e218f375e26d43f0d6df0a434f/crates/native_blockifier/src/transaction_executor.rs#L110)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

ChatGPT's suggestion, is it good?
</blockquote></details>

Remove blank line?


<!-- Sent from Reviewable.io -->

2024-01-25 15:28 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: 14 of 18 files reviewed, 4 unresolved discussions (waiting on @elin and @elintul)

___
*[`crates/blockifier/src/execution/call_info.rs` line 58 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Nnsv-Ce2XtpbSCT6WfP:-Np0CHZuBE3CcrC_rG5N:b-j82787) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0195fd77deba2cf64a2749a8f5af0c0093d647/crates/blockifier/src/execution/call_info.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'd prefer to encapsulate the fact we're using a wrapper as much as possible, but not if the effort is too big (this is temporary).
</blockquote></details>

For using `inner` method, we still need to add `.inner` in the code.
I implement from, to be able to use `.into()`.
However, I still need to use `.0` in one place in the code.
___
*[`crates/blockifier/src/execution/call_info.rs` line 65 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Np-LrCbANRvO8JrA13B:-Np-RaNKE_392C2YU6K9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b0c5cdebb0208e218f375e26d43f0d6df0a434f/crates/blockifier/src/execution/call_info.rs#L65)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I thought it would save some of the changes, but it doesn't. You can revert.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/prices.rs` line 85 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Noq3DC91DOG0JROqBdk:-Np-g4U_6PP6EPXzIMjP:b-aihnkw) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b0c5cdebb0208e218f375e26d43f0d6df0a434f/crates/blockifier/src/test_utils/prices.rs#L85)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Still necessary?
</blockquote></details>

We still need it. but it can be replaced with `.into()`.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 29 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Noq44QI9GE6z0e8QDCV:-Np-b1Ib1NkZqtdSXnIz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b0c5cdebb0208e218f375e26d43f0d6df0a434f/crates/native_blockifier/src/transaction_executor.rs#L29)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can the new `pub`lic definitions you added be `pub(crate)`? In case they are not part of the public API and only needed for other modules _in the same crate_.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 35 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Noq3TUfCn9msCQ3efFW:-Np-ZTIOBic66YkHw8hb:b-pu7zqj) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b0c5cdebb0208e218f375e26d43f0d6df0a434f/crates/native_blockifier/src/transaction_executor.rs#L35)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

When does it mean?
</blockquote></details>

It removes the new hierarchy (info) during serialization. 
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 110 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Np-MuH6AioKp1L46792:-Np-_m7Q7alhkBSSt-bI:buwk63q) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b0c5cdebb0208e218f375e26d43f0d6df0a434f/crates/native_blockifier/src/transaction_executor.rs#L110)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

ChatGPT's suggestion, is it good?
</blockquote></details>

Yeah, it works.
Updated,


<!-- Sent from Reviewable.io -->

2024-01-27 15:10 UTC, elintul requested changes
> Reviewed 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 35 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Noq3TUfCn9msCQ3efFW:-NpAT9Tt6upFuNabxoaw:b4hdgp2) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b0c5cdebb0208e218f375e26d43f0d6df0a434f/crates/native_blockifier/src/transaction_executor.rs#L35)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It removes the new hierarchy (info) during serialization.
</blockquote></details>

But we _do_ need it in Python, right?


<!-- Sent from Reviewable.io -->

2024-01-27 18:49 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 35 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Noq3TUfCn9msCQ3efFW:-NpBEHC-4WABZdN19NJb:bzdpr49) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b0c5cdebb0208e218f375e26d43f0d6df0a434f/crates/native_blockifier/src/transaction_executor.rs#L35)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

But we _do_ need it in Python, right?
</blockquote></details>

In `TxExecutionInfo`, it has `tx_type` as part of the struct in the same hierarchy of other fields of the Rust struct, that's why I need to add `flatten` to be included as part of the struct and not in a separate hierarchy.
Maybe there is some confusion regarding the `info` hierarchy in `TxExecutionInfoWritten`, which is an additional hierarchy.


<!-- Sent from Reviewable.io -->

2024-01-28 05:59 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 35 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Noq3TUfCn9msCQ3efFW:-NpDdRmj-c0SDf_YIGRs:blxk76y) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b0c5cdebb0208e218f375e26d43f0d6df0a434f/crates/native_blockifier/src/transaction_executor.rs#L35)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

In `TxExecutionInfo`, it has `tx_type` as part of the struct in the same hierarchy of other fields of the Rust struct, that's why I need to add `flatten` to be included as part of the struct and not in a separate hierarchy.
Maybe there is some confusion regarding the `info` hierarchy in `TxExecutionInfoWritten`, which is an additional hierarchy.
</blockquote></details>

Got it. Do we have a way to add the "info" indentation in Rust? Is it worth it?


<!-- Sent from Reviewable.io -->

2024-01-28 08:20 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 35 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Noq3TUfCn9msCQ3efFW:-NpE8O8a4sllB0Z6OjeS:b-2g9mv8) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b0c5cdebb0208e218f375e26d43f0d6df0a434f/crates/native_blockifier/src/transaction_executor.rs#L35)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Got it. Do we have a way to add the "info" indentation in Rust? Is it worth it?
</blockquote></details>

Note that in Python, we are using both `TransactionExecutionInfo` and `TransactionExecutionInfoWritten` structs. If we want to send `TxExecutionInfoWritten` from Rust, we need to extract `TxExecutionInfo` from it in Python (or maybe using property).


<!-- Sent from Reviewable.io -->

2024-01-28 09:34 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-:-NpEPu11CL_WS4ovYJoi:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Np-Nwqj9TH1AM_qfbMK:-NpEPsok2ONieBkb1UCi:bpzhpqd) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please open a PR to LC's repo. when you can.
</blockquote></details>

ACK this?

___


<!-- Sent from Reviewable.io -->

2024-01-28 10:10 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Np-Nwqj9TH1AM_qfbMK:-NpEXhc-EGY07bFdQJQf:b-rzkpuc) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

ACK this?
</blockquote></details>

I'm not sure how to open this,
let's do it together tomorrow in the office?

___


<!-- Sent from Reviewable.io -->

2024-01-28 10:23 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Np-Nwqj9TH1AM_qfbMK:-NpEa43d9Xno7KiUmaAf:br0g9x2) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I'm not sure how to open this,
let's do it together tomorrow in the office?
</blockquote></details>

Add to Monday and shortly check in Google in the meantime?

___


<!-- Sent from Reviewable.io -->

2024-01-28 10:23 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-01-28 11:07 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Np-Nwqj9TH1AM_qfbMK:-NpEjqed6gFgXlNrAces:bb6un1j) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add to Monday and shortly check in Google in the meantime?
</blockquote></details>

Done

___


<!-- Sent from Reviewable.io -->

2024-01-28 12:38 UTC, elintul submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-01-28 13:21 UTC, elintul requested changes
> Reviewed 1 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 115 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpFDqMY60xOA136SmSR:-NpFDqMY60xOA136SmSS:b28693o) ([raw file](https://github.com/starkware-libs/blockifier/blob/575c149fafbad1a76913c947aec8a05c29693725/crates/native_blockifier/src/transaction_executor.rs#L115)):*
> ```XML
>                         .collect::<Vec<&CallInfo>>()
>                         .into_iter();
>                 let MessageL1CostInfo { l2_to_l1_payload_lengths: _, message_segment_length } =
> ```

Can you remove Ayelet's changes from this PR?


<!-- Sent from Reviewable.io -->

2024-01-28 13:25 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 115 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpFDqMY60xOA136SmSR:-NpFEdK94pF5BLQxpAcf:b-hiuzm0) ([raw file](https://github.com/starkware-libs/blockifier/blob/575c149fafbad1a76913c947aec8a05c29693725/crates/native_blockifier/src/transaction_executor.rs#L115)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you remove Ayelet's changes from this PR?
</blockquote></details>

It's not part of this PR.
I've rebased after Ayelet's merge.


<!-- Sent from Reviewable.io -->

2024-01-28 13:33 UTC, elintul requested changes
> Reviewed 1 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 6 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 110 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpFGEi0DjJ8lU2Z3nQz:-NpFGEi0DjJ8lU2Z3nR-:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/575c149fafbad1a76913c947aec8a05c29693725/crates/native_blockifier/src/transaction_executor.rs#L110)):*
> ```XML
>                 tx_visited_storage_entries.extend(tx_execution_info.get_visited_storage_entries());
>                 let call_infos: IntoIter<&CallInfo> =
>                     [&tx_execution_info.validate_call_info, &tx_execution_info.execute_call_info]
> ```





_Suggestion:_
```XML
                // TODO(Elin, 01/06/2024): consider traversing the calls to collect data once.
                // TODO(Elin, 01/06/2024): consider moving Bouncer logic to a function.
                tx_executed_class_hashes.extend(tx_execution_info.get_executed_class_hashes());
                tx_visited_storage_entries.extend(tx_execution_info.get_visited_storage_entries());
                
                                
                // Count message to L1 resources.
                let call_infos: IntoIter<&CallInfo> =
                    [&tx_execution_info.validate_call_info, &tx_execution_info.execute_call_info]
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 115 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpFDqMY60xOA136SmSR:-NpFFe3N47Al6fWJ9tZW:b-r3k72h) ([raw file](https://github.com/starkware-libs/blockifier/blob/575c149fafbad1a76913c947aec8a05c29693725/crates/native_blockifier/src/transaction_executor.rs#L115)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It's not part of this PR.
I've rebased after Ayelet's merge.
</blockquote></details>

Can you merge this PR without depending on hers? I don't want her to block you.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 119 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpFGM4zEjN-LAl8Wvp6:-NpFGM4zEjN-LAl8Wvp7:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/575c149fafbad1a76913c947aec8a05c29693725/crates/native_blockifier/src/transaction_executor.rs#L119)):*
> ```XML
> 
>                 // TODO(Elin, 01/06/2024): consider moving Bouncer logic to a function.
>                 let mut additional_os_resources = get_casm_hash_calculation_resources(
> ```





_Suggestion:_
```XML
                // Count additional OS resources.
                let mut additional_os_resources = get_casm_hash_calculation_resources(
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 128 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpFGSdO498jifexT1le:-NpFGSdO498jifexT1lf:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/575c149fafbad1a76913c947aec8a05c29693725/crates/native_blockifier/src/transaction_executor.rs#L128)):*
> ```XML
>                     &tx_visited_storage_entries,
>                 )?;
>                 let state_diff_size = 0;
> ```





_Suggestion:_
```XML
                )?;
                
                // Count blob resources.
                let state_diff_size = 0;
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 139 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpFGb2a-0p9hfFNbSYR:-NpFGb2a-0p9hfFNbSYS:b-eaji4b) ([raw file](https://github.com/starkware-libs/blockifier/blob/575c149fafbad1a76913c947aec8a05c29693725/crates/native_blockifier/src/transaction_executor.rs#L139)):*
> ```XML
>                 self.staged_for_commit_state = Some(
>                     transactional_state.stage(tx_executed_class_hashes, tx_visited_storage_entries),
>                 );
> ```

Can this be moved after the `extend`s above?



_Code quote:_
```XML
                self.staged_for_commit_state = Some(
                    transactional_state.stage(tx_executed_class_hashes, tx_visited_storage_entries),
                );
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 146 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpFGe4p2BHkvZJpgY-0:-NpFGe4p2BHkvZJpgY-1:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/575c149fafbad1a76913c947aec8a05c29693725/crates/native_blockifier/src/transaction_executor.rs#L146)):*
> ```XML
> 
>                 let raw_tx_execution_info = serde_json::to_vec(&typed_tx_execution_info)
>                     .map_err(NativeBlockifierError::SerdeError)?;
> ```





_Suggestion:_
```XML
                
                let typed_tx_execution_info = TypedTransactionExecutionInfo {
                    info: tx_execution_info,
                    tx_type: tx_type.to_string(),
                };
                let raw_tx_execution_info = serde_json::to_vec(&typed_tx_execution_info)
                    .map_err(NativeBlockifierError::SerdeError)?;
```


<!-- Sent from Reviewable.io -->

2024-01-28 14:17 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: 17 of 18 files reviewed, 5 unresolved discussions (waiting on @elintul)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 110 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpFGEi0DjJ8lU2Z3nQz:-NpFIhWkDH7jaRy3XCSZ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/575c149fafbad1a76913c947aec8a05c29693725/crates/native_blockifier/src/transaction_executor.rs#L110)):*
> ```XML
>                 tx_visited_storage_entries.extend(tx_execution_info.get_visited_storage_entries());
>                 let call_infos: IntoIter<&CallInfo> =
>                     [&tx_execution_info.validate_call_info, &tx_execution_info.execute_call_info]
> ```

Done.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 115 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpFDqMY60xOA136SmSR:-NpFIiec4zpwSaOt-IgT:b-egn9eu) ([raw file](https://github.com/starkware-libs/blockifier/blob/575c149fafbad1a76913c947aec8a05c29693725/crates/native_blockifier/src/transaction_executor.rs#L115)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you merge this PR without depending on hers? I don't want her to block you.
</blockquote></details>

She has merged her PR.
I had conflicts and had to rebase my PR.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 119 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpFGM4zEjN-LAl8Wvp6:-NpFJ4kI3ZAjopAeNstq:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/575c149fafbad1a76913c947aec8a05c29693725/crates/native_blockifier/src/transaction_executor.rs#L119)):*
> ```XML
> 
>                 // TODO(Elin, 01/06/2024): consider moving Bouncer logic to a function.
>                 let mut additional_os_resources = get_casm_hash_calculation_resources(
> ```

Done.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 128 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpFGSdO498jifexT1le:-NpFJAX22M7DROsM1GU6:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/575c149fafbad1a76913c947aec8a05c29693725/crates/native_blockifier/src/transaction_executor.rs#L128)):*
> ```XML
>                     &tx_visited_storage_entries,
>                 )?;
>                 let state_diff_size = 0;
> ```

Done.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 139 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpFGb2a-0p9hfFNbSYR:-NpFMOlF-Dj54o3Fdt9m:b-x93kt4) ([raw file](https://github.com/starkware-libs/blockifier/blob/575c149fafbad1a76913c947aec8a05c29693725/crates/native_blockifier/src/transaction_executor.rs#L139)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can this be moved after the `extend`s above?
</blockquote></details>

In [this](https://github.com/starkware-libs/blockifier/blob/575c149fafbad1a76913c947aec8a05c29693725/crates/native_blockifier/src/transaction_executor.rs#L125-L134) code it borrows the `transactional_state`, so to move it above we need to clone it.


<!-- Sent from Reviewable.io -->

2024-01-28 15:41 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: 17 of 18 files reviewed, all discussions resolved (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-01-28 15:42 UTC, elintul requested changes
> Reviewed 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 134 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpFiu85A9hrUJhX1ElN:-NpFiu85A9hrUJhX1ElO:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/52bbf86615c3491a541c1695cebcfa42e5485e79/crates/native_blockifier/src/transaction_executor.rs#L134)):*
> ```XML
>                 // Count blob resources.
>                 let state_diff_size = 0;
>                 let actual_resources = tx_execution_info.actual_resources.0.clone();
> ```





_Suggestion:_
```XML
                let state_diff_size = 0;
                
                // Finalize counting logic.
                let actual_resources = tx_execution_info.actual_resources.0.clone();
```


<!-- Sent from Reviewable.io -->

2024-01-28 15:42 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-01-30 12:08 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/execution/call_info.rs` line 89 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpPEqm7A9cJRXPnZOzJ:-NpPEqm7A9cJRXPnZOzK:b-nkxqtc) ([raw file](https://github.com/starkware-libs/blockifier/blob/551c4f76818c878dda6b77dd35d00a7913209eb3/crates/blockifier/src/execution/call_info.rs#L89)):*
> ```XML
>         wrapper.0
>     }
> }
> ```

The name is somewhat confusing, it doens't generate an "Into", it generates the exact from you wrote.
The derive_more::From before it genreates the reverse From (bad api on their part...)



_Suggestion:_
```XML
#[derive(Debug, Default, derive_more::Deref, derive_more::From, derive_more::Into Eq, PartialEq)]
pub struct VmExecutionResourcesWrapper(pub VmExecutionResources);
```


<!-- Sent from Reviewable.io -->

2024-01-30 12:11 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/execution/call_info.rs` line 58 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Nnsv-Ce2XtpbSCT6WfP:-NpPGd3e7-Yu-wFKktyr:bzgocim) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0195fd77deba2cf64a2749a8f5af0c0093d647/crates/blockifier/src/execution/call_info.rs#L58)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

For using `inner` method, we still need to add `.inner` in the code.
I implement from, to be able to use `.into()`.
However, I still need to use `.0` in one place in the code.
</blockquote></details>

You mean in `calculate_tx_weights` which ownership on the inner vlaue?
 I think the function can be changed to get the value by ref (doens't seem to do anything with the ownership), and then Deref can be used.


<!-- Sent from Reviewable.io -->

2024-01-30 12:22 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-01-31 09:14 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: 6 of 18 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/execution/call_info.rs` line 58 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-Nnsv-Ce2XtpbSCT6WfP:-NpTkLu2D9kL8OzAdAT9:b1wu8ej) ([raw file](https://github.com/starkware-libs/blockifier/blob/fc0195fd77deba2cf64a2749a8f5af0c0093d647/crates/blockifier/src/execution/call_info.rs#L58)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

You mean in `calculate_tx_weights` which ownership on the inner vlaue?
 I think the function can be changed to get the value by ref (doens't seem to do anything with the ownership), and then Deref can be used.
</blockquote></details>

Following @giladchase suggestion, I removed the wrapper and used Serde to derive Serialize as explained [here](https://serde.rs/remote-derive.html#deriving-deserialize-for-type-in-a-different-crate).
___
*[`crates/blockifier/src/execution/call_info.rs` line 89 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpPEqm7A9cJRXPnZOzJ:-NpTkfZu51jZzHoUzhy4:b-8vjbcz) ([raw file](https://github.com/starkware-libs/blockifier/blob/551c4f76818c878dda6b77dd35d00a7913209eb3/crates/blockifier/src/execution/call_info.rs#L89)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

The name is somewhat confusing, it doens't generate an "Into", it generates the exact from you wrote.
The derive_more::From before it genreates the reverse From (bad api on their part...)
</blockquote></details>

This code was removed.
See the above comment.


<!-- Sent from Reviewable.io -->

2024-01-31 15:46 UTC, elintul submitted a review, later dismissed
> Reviewed 12 of 12 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/call_info.rs` line 83 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpVBaWiAdsV9ezRen2Z:-NpVBaWjBfiQ-jIU-CAv:bax35rd) ([raw file](https://github.com/starkware-libs/blockifier/blob/5fc61f237ddf051e02a48299563d4175bebff0c3/crates/blockifier/src/execution/call_info.rs#L83)):*
> ```XML
> // This struct is just a copy of the remote `VmExecutionResources` Struct.
> // The remote attribute gives the path to the actual type we intend to derive
> // Serialize and Deserialize for.
> ```

I think it's enough to say it is used to implement `serde` functionality on `VmExecutionResources` which is not defined inside the crate.



_Code quote:_
```XML
// This struct is just a copy of the remote `VmExecutionResources` Struct.
// The remote attribute gives the path to the actual type we intend to derive
// Serialize and Deserialize for.
```
___
*[`crates/blockifier/src/execution/call_info.rs` line 98 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpV5DSVDYNOQdVtKs1d:-NpV5DSVDYNOQdVtKs1e:bhzpjfd) ([raw file](https://github.com/starkware-libs/blockifier/blob/5fc61f237ddf051e02a48299563d4175bebff0c3/crates/blockifier/src/execution/call_info.rs#L98)):*
> ```XML
>     pub execution: CallExecution,
>     // It gives the path to the definition for the remote type.
>     #[serde(with = "VmExecutionResourcesDef")]
> ```

I think the comment doesn't add information.



_Suggestion:_
```XML
    #[serde(with = "VmExecutionResourcesDef")]
```


<!-- Sent from Reviewable.io -->

2024-01-31 16:17 UTC, giladchase approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: 9 of 18 files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 39 at r20](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpVIEdH9RATHqfNXklU:-NpVIEdH9RATHqfNXklV:bc1dfev) ([raw file](https://github.com/starkware-libs/blockifier/blob/3179a58799f0f44e2c18372aafd82460a942f7ff/crates/native_blockifier/src/transaction_executor.rs#L39)):*
> ```XML
>     #[serde(flatten)]
>     info: TransactionExecutionInfo,
>     tx_type: String,
> ```

Can this be `TransactionType`?



_Code quote:_
```XML
    tx_type: String,
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 153 at r20](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpVIpv08DYGvGVJ2Bna:-NpVIpv11ME6pai_v7o6:b-ur5skb) ([raw file](https://github.com/starkware-libs/blockifier/blob/3179a58799f0f44e2c18372aafd82460a942f7ff/crates/native_blockifier/src/transaction_executor.rs#L153)):*
> ```XML
>                 };
>                 let raw_tx_execution_info = serde_json::to_vec(&typed_tx_execution_info)
>                     .map_err(NativeBlockifierError::SerdeError)?;
> ```

I think this will still work, the `?` runs `into` behind the scenes on the error



_Suggestion:_
```XML
                let raw_tx_execution_info = serde_json::to_vec(&typed_tx_execution_info)?;
```


<!-- Sent from Reviewable.io -->

2024-01-31 16:18 UTC, giladchase approved these changes
> Reviewed 1 of 10 files at r9, 1 of 6 files at r12, 1 of 9 files at r13, 5 of 12 files at r19, 9 of 9 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-01-31 16:30 UTC, elintul approved these changes
> Reviewed 9 of 9 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-01-31 16:34 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 39 at r20](https://reviewable.io/reviews/starkware-libs/blockifier/1315#-NpVIEdH9RATHqfNXklU:-NpVMZ192I_lTQwPkL5C:b-ynoodt) ([raw file](https://github.com/starkware-libs/blockifier/blob/3179a58799f0f44e2c18372aafd82460a942f7ff/crates/native_blockifier/src/transaction_executor.rs#L39)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can this be `TransactionType`?
</blockquote></details>

It doesn't work.


<!-- Sent from Reviewable.io -->

2024-01-31 16:34 UTC, giladchase approved these changes
> Reviewed 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1315)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-01-31 16:35 UTC, merged