Make `BlockContext` a newtype around `BlockInfo`
starkware-libs/blockifier pull request #1323
Opened 2024-01-10 13:53 UTC by giladchase

The crux of this commit is the change in `block_context.rs`, which converts `BlockContext` into a wrapper around `BlockInfo` (which used to be `BlockContext`).

Everything else is just delegating the accessors to the internal block_info, made by search-and-replace (no other changes).

Motivation:
- This change the groundwork for future refactor and consolidation of contexts.
- Subsequent commits will extract non block-specific constants from `BlockInfo` into separate `ChainInfo` and `VersionedConstants` structs, which will be siblings of `block_info` inside `BlockContext`.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1323)

2024-01-11 10:41 UTC, elintul requested changes
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1323)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 215 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-Nns5VUk2vy0idYQJazM:-Nns5VUk2vy0idYQJazN:b69hzcy) ([raw file](https://github.com/starkware-libs/blockifier/blob/9e6b96fbb23423a38a0603fdc5456247863bb24d/crates/blockifier/src/execution/entry_point.rs#L215)):*
> ```XML
>         limit_steps_by_resources: bool,
>     ) -> TransactionExecutionResult<usize> {
>         let block_upper_bound = match mode {
> ```

- Define a `BlockInfo` variable so that accesses to fields aren't too long? Especially in functions that access more than one field.
- Change functions that only access fields from `BlockInfo` to receive this type instead of `BlockContext`.


<!-- Sent from Reviewable.io -->

2024-01-14 12:53 UTC, elintul requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1323)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 215 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-No71CND1fbx8wSA6nG_:-No71CNE7HqzhY8_865j:b-79k4nf) ([raw file](https://github.com/starkware-libs/blockifier/blob/210fd6221de5bf663c1aec46cc5a776a1e81e0a6/crates/blockifier/src/execution/entry_point.rs#L215)):*
> ```XML
>         limit_steps_by_resources: bool,
>     ) -> TransactionExecutionResult<usize> {
>         let block_info = &block_context.block_info;
> ```

Why not make this function receive only block info?



_Code quote:_
```XML
let block_info = &block_context.block_info;
```


<!-- Sent from Reviewable.io -->

2024-01-14 12:56 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1323)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 215 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-Nns5VUk2vy0idYQJazM:-No70DPYAIDgRACYsqKi:bguco2b) ([raw file](https://github.com/starkware-libs/blockifier/blob/9e6b96fbb23423a38a0603fdc5456247863bb24d/crates/blockifier/src/execution/entry_point.rs#L215)):*
>   Define a `BlockInfo` variable so that accesses to fields aren't too long? Especially in functions that access more than one field.

Done

> Change functions that only access fields from `BlockInfo` to receive this type instead of `BlockContext`.

Also thought of that, but then discovered that ot will end up changing again in every subsequent PR.
So i think it's better do that as the last PR in the stack, after all the variables have been split between the various contexts.
WDYT?


<!-- Sent from Reviewable.io -->

2024-01-14 12:57 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1323)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 215 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-No71CND1fbx8wSA6nG_:-No71qJj8GmQbtsy3Zye:b-8s0i80) ([raw file](https://github.com/starkware-libs/blockifier/blob/210fd6221de5bf663c1aec46cc5a776a1e81e0a6/crates/blockifier/src/execution/entry_point.rs#L215)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not make this function receive only block info?
</blockquote></details>

See comment below, basically perhaps now it takes block_info, but in the next PR some of the vars will no longer be in BlockInfo (they'll be ChainInfo, or part of VersionedConstants), so i'll have to switch it back to BlockContext


<!-- Sent from Reviewable.io -->

2024-01-14 13:15 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1323)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 215 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-Nns5VUk2vy0idYQJazM:-No75p0AAj1LojgjVWhA:bqdtj3z) ([raw file](https://github.com/starkware-libs/blockifier/blob/9e6b96fbb23423a38a0603fdc5456247863bb24d/crates/blockifier/src/execution/entry_point.rs#L215)):*
> will end up changing again in every subsequent PR

WDYM? Because it's a stack? In that case okay, but don't forget, please. :grimacing: 
___
*[`crates/blockifier/src/execution/entry_point.rs` line 215 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-No71CND1fbx8wSA6nG_:-No764P-DEgvMYVnUDZM:b-7mowb5) ([raw file](https://github.com/starkware-libs/blockifier/blob/210fd6221de5bf663c1aec46cc5a776a1e81e0a6/crates/blockifier/src/execution/entry_point.rs#L215)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

See comment below, basically perhaps now it takes block_info, but in the next PR some of the vars will no longer be in BlockInfo (they'll be ChainInfo, or part of VersionedConstants), so i'll have to switch it back to BlockContext
</blockquote></details>

I meant for functions that only use fields from block info right now.


<!-- Sent from Reviewable.io -->

2024-01-16 11:04 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1323)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 215 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-Nns5VUk2vy0idYQJazM:-NoGvroc6Ni4C4gH8RnF:b-vqrcv1) ([raw file](https://github.com/starkware-libs/blockifier/blob/9e6b96fbb23423a38a0603fdc5456247863bb24d/crates/blockifier/src/execution/entry_point.rs#L215)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

> will end up changing again in every subsequent PR

WDYM? Because it's a stack? In that case okay, but don't forget, please. :grimacing:
</blockquote></details>

Yep, won't forget, this burns me eyeballs in a constant basis :grimacing: 
___
*[`crates/blockifier/src/execution/entry_point.rs` line 215 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-No71CND1fbx8wSA6nG_:-NoGw6hv1Iy2VhBRT8me:b-yucktu) ([raw file](https://github.com/starkware-libs/blockifier/blob/210fd6221de5bf663c1aec46cc5a776a1e81e0a6/crates/blockifier/src/execution/entry_point.rs#L215)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I meant for functions that only use fields from block info right now.
</blockquote></details>

I can do that, but keep in mind that in the next PR (the [ChainInfo one](https://reviewable.io/reviews/starkware-libs/blockifier/1324#-)) some of these changes will be reverted back to BlockContext, in case where the function needs fields from both `BlockInfo` and `ChainInfo` (this will happen cause `ChainInfo` is composed of fields extracted from `BlockInfo`).


<!-- Sent from Reviewable.io -->

2024-01-16 12:11 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1323)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 215 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-No71CND1fbx8wSA6nG_:-NoHAm1h86bdU_6hX9LM:b-e90hr9) ([raw file](https://github.com/starkware-libs/blockifier/blob/210fd6221de5bf663c1aec46cc5a776a1e81e0a6/crates/blockifier/src/execution/entry_point.rs#L215)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I can do that, but keep in mind that in the next PR (the [ChainInfo one](https://reviewable.io/reviews/starkware-libs/blockifier/1324#-)) some of these changes will be reverted back to BlockContext, in case where the function needs fields from both `BlockInfo` and `ChainInfo` (this will happen cause `ChainInfo` is composed of fields extracted from `BlockInfo`).
</blockquote></details>

Talked offline.


<!-- Sent from Reviewable.io -->

2024-01-16 12:44 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1323)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 215 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-No71CND1fbx8wSA6nG_:-NoHI1gr4uP9L3vIwLxX:b8jaymu) ([raw file](https://github.com/starkware-libs/blockifier/blob/210fd6221de5bf663c1aec46cc5a776a1e81e0a6/crates/blockifier/src/execution/entry_point.rs#L215)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Talked offline.
</blockquote></details>

Only one place used `BlockInfo`-specific stuff (also added more `block_info` variables instead of repeated accesses to `context.block_info`)


<!-- Sent from Reviewable.io -->

2024-01-17 07:24 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1323)* status: 6 of 20 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/block_context.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-NoLGr3JCfyft4t_6UbU:-NoLGr3JCfyft4t_6UbV:bgw9g1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/082c9054ded5198d74c3d6ee3853448dcd58cd7e/crates/blockifier/src/block_context.rs#L36)):*
> ```XML
>     pub invoke_tx_max_n_steps: u32,
>     pub validate_max_n_steps: u32,
>     pub max_recursion_depth: usize,
> ```

Didn't we agree to put the constants and the env vars in a different struct?
(also, to be consistent with python)
Constants (version-wise)
```
    pub vm_resource_fee_cost: Arc<HashMap<String, f64>>,
    pub invoke_tx_max_n_steps: u32,
    pub validate_max_n_steps: u32,
    pub max_recursion_depth: usize,
```
Chain args
```
    pub fee_token_addresses: FeeTokenAddresses,
    pub chain_id: ChainId,
```



_Code quote:_
```XML
    // Fee-related.
    pub sequencer_address: ContractAddress,
    pub fee_token_addresses: FeeTokenAddresses,
    pub vm_resource_fee_cost: Arc<HashMap<String, f64>>,
    pub gas_prices: GasPrices,
    pub use_kzg_da: bool,

    // Limits.
    pub invoke_tx_max_n_steps: u32,
    pub validate_max_n_steps: u32,
    pub max_recursion_depth: usize,
```


<!-- Sent from Reviewable.io -->

2024-01-17 08:11 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1323)* status: 6 of 20 files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/block_context.rs` line 36 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-NoLGr3JCfyft4t_6UbU:-NoLSYb89X2Fy06UQ6GB:b-1v9cn1) ([raw file](https://github.com/starkware-libs/blockifier/blob/082c9054ded5198d74c3d6ee3853448dcd58cd7e/crates/blockifier/src/block_context.rs#L36)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Didn't we agree to put the constants and the env vars in a different struct?
(also, to be consistent with python)
Constants (version-wise)
```
    pub vm_resource_fee_cost: Arc<HashMap<String, f64>>,
    pub invoke_tx_max_n_steps: u32,
    pub validate_max_n_steps: u32,
    pub max_recursion_depth: usize,
```
Chain args
```
    pub fee_token_addresses: FeeTokenAddresses,
    pub chain_id: ChainId,
```
</blockquote></details>

Yep its further up the stack: see [this pr](https://reviewable.io/reviews/starkware-libs/blockifier/1324#-) for the chain args.

The stack is: 
1) Rename BlockContext into BlockInfo and wrap it with BlockContext
2) extract chain args from BlockInfo and add to a new ChainInfo which sits also in BlockContext
WIP) extract more stuff from BlockInfo into VersionedConstants and add to BlockContext


<!-- Sent from Reviewable.io -->

2024-01-17 08:59 UTC, elintul requested changes
> Reviewed 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1323)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 300 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-NoLdJWYEd-NY1H36cZQ:-NoLdJWZ0QXpWTnUv0kM:b-dhzn3w) ([raw file](https://github.com/starkware-libs/blockifier/blob/082c9054ded5198d74c3d6ee3853448dcd58cd7e/crates/native_blockifier/src/py_block_executor.rs#L300)):*
> ```XML
>             vm_resource_fee_cost: general_config.cairo_resource_fee_weights.clone(),
>             gas_prices: GasPrices {
>                 eth_l1_gas_price: block_info.gas_prices.eth_l1_gas_price,
> ```

Define a variable?



_Code quote:_
```XML
block_info.gas_prices
```


<!-- Sent from Reviewable.io -->

2024-01-17 13:39 UTC, giladchase reviewed
One of the revisions is bad due to a merge of a second level of the stack into this one by mistake, reverted.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-:-NoMdOSv1NI9S0_h_IRc:b-5ehfwa)* status: 4 of 25 files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 300 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-NoLdJWYEd-NY1H36cZQ:-NoMdMHwBohAWweG1a8D:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/082c9054ded5198d74c3d6ee3853448dcd58cd7e/crates/native_blockifier/src/py_block_executor.rs#L300)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Define a variable?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-17 15:50 UTC, elintul requested changes
> Reviewed 21 of 21 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1323)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-NoN6J5B2daBOxcba3dZ:-NoN6J5B2daBOxcba3d_:b-sqkhi4) (no related file):*
Please go over `block_context.[chain,block]_info.*` that is done more than once in the same scope and define variables where possible.

___
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 157 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-NoN6AbRAlAvdpuOwpc0:-NoN6AbRAlAvdpuOwpc1:b-dhzn4d) ([raw file](https://github.com/starkware-libs/blockifier/blob/d5a4971e2fc41a0b019ff47bcd96cb3c22261f8d/crates/blockifier/src/transaction/test_utils.rs#L157)):*
> ```XML
>     let test_account_address = contract_address!(account_address);
>     let test_strk_token_address =
>         block_context.block_info.fee_token_addresses.strk_fee_token_address;
> ```

Define a variable.



_Code quote:_
```XML
block_context.block_info.fee_token_addresses
```


<!-- Sent from Reviewable.io -->

2024-01-18 05:20 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1323)* status: 20 of 26 files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-NoN6J5B2daBOxcba3dZ:-NoQ-W-H3ulWYhrWKj2c:bpdbmuo) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please go over `block_context.[chain,block]_info.*` that is done more than once in the same scope and define variables where possible.
</blockquote></details>

Done.
I think these came up in some of the rebases which is why i didn't catch them the previous times i went over all fields.

___
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 157 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-NoN6AbRAlAvdpuOwpc0:-NoQ-UaG68GVTQgwXlaT:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/d5a4971e2fc41a0b019ff47bcd96cb3c22261f8d/crates/blockifier/src/transaction/test_utils.rs#L157)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Define a variable.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-01-18 09:26 UTC, elintul submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-:-NoQt3CP4yYgeLsM0H2B:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-01-18 09:31 UTC, elintul approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1323)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-01-18 09:32 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1323#-:-NoQu_4H5gcv-e8EMbwU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-01-18 09:37 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1323)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-01-18 09:57 UTC, merged