Extract from `BlockInfo` into `ChainInfo`
starkware-libs/blockifier pull request #1324
Opened 2024-01-10 14:23 UTC by giladchase

`BlockInfo` should only contain block-level info, whereas chain-level information should be held at the `BlockContext` level, encapsulated in a dedicated `ChainInfo` struct.

Changes:
Only extract from `BlockInfo` and store in `BlockContext.chain_info: ChainInfo`. All other changes are search-replace + moving the fee_token_address getter into `ChainInfo`.

TODO: extract more stuff from BlockInfo: version-dependant constants should be extracted into a dedicated VersionedConstants, which will be a member of BlockContext

2024-01-10 14:32 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1324)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/block_context.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1324#-Nnnm3lfCezVL9FzjHFl:-Nnnm3lfCezVL9FzjHFm:b-lun7dg) ([raw file](https://github.com/starkware-libs/blockifier/blob/c69eb026f9adf49c09c689e2877491d157f14d97/crates/blockifier/src/block_context.rs#L34)):*
> ```XML
> pub struct ChainInfo {
>     pub chain_id: ChainId,
>     pub fee_token_addresses: FeeTokenAddresses,
> ```

Are these the only ones that need to be here? I recall you saying that `sequencer_address` should remain in `BlockInfo`, and vm_resource_fee_cost + the `limits` part will all move to the Config part.



_Code quote:_
```XML
    pub chain_id: ChainId,
    pub fee_token_addresses: FeeTokenAddresses,
```


<!-- Sent from Reviewable.io -->

2024-01-11 10:47 UTC, elintul requested changes
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1324)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @Yoni-Starkware)

___
*[`crates/blockifier/src/block_context.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1324#-Nnnm3lfCezVL9FzjHFl:-Nns6Z9h-b2Q6swSB9a-:b-nts3oy) ([raw file](https://github.com/starkware-libs/blockifier/blob/c69eb026f9adf49c09c689e2877491d157f14d97/crates/blockifier/src/block_context.rs#L34)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Are these the only ones that need to be here? I recall you saying that `sequencer_address` should remain in `BlockInfo`, and vm_resource_fee_cost + the `limits` part will all move to the Config part.
</blockquote></details>

- `sequencer_address` should stay in `BlockInfo`, as a preparation for decentralization.
- Costs and limits are indeed versioned constants.
- `max_recursion_depth` should be configurable through Python (for the case a transaction bloats the stack and we want to reject it), and might change during a version.
___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1324#-Nns7cCF0phx2c8R_j2i:-Nns7cCF0phx2c8R_j2j:b-rrpcdy) ([raw file](https://github.com/starkware-libs/blockifier/blob/c69eb026f9adf49c09c689e2877491d157f14d97/crates/blockifier/src/test_utils/initial_test_state.rs#L50)):*
> ```XML
>     // Declare and deploy account and ERC20 contracts.
>     let erc20 = FeatureContract::ERC20;
>     class_hash_to_class.insert(erc20.get_class_hash(), erc20.get_class());
> ```

-  Define a `ChainInfo` variable so that accesses to fields aren't too long? Especially in functions that access more than one field.
-   Change functions that only access fields from `ChainInfo` to receive this type instead of `BlockContext`.
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1324#-Nns7TSl0jJwX9G98Zyl:-Nns7TSl0jJwX9G98Zym:bgp672g) ([raw file](https://github.com/starkware-libs/blockifier/blob/c69eb026f9adf49c09c689e2877491d157f14d97/crates/blockifier/src/test_utils/struct_impls.rs#L121)):*
> ```XML
>         BlockContext {
>             chain_info: ChainInfo::create_for_testing(),
>             block_info: BlockInfo::create_for_testing(),
> ```

Swap order, as in struct definition?



_Code quote:_
```XML
            chain_info: ChainInfo::create_for_testing(),
            block_info: BlockInfo::create_for_testing(),
```


<!-- Sent from Reviewable.io -->

2024-01-16 15:11 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1324)* status: 3 of 21 files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/block_context.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1324#-Nnnm3lfCezVL9FzjHFl:-NoH73RtBYomy-nkkQvw:b9ldnbq) ([raw file](https://github.com/starkware-libs/blockifier/blob/c69eb026f9adf49c09c689e2877491d157f14d97/crates/blockifier/src/block_context.rs#L34)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

- `sequencer_address` should stay in `BlockInfo`, as a preparation for decentralization.
- Costs and limits are indeed versioned constants.
- `max_recursion_depth` should be configurable through Python (for the case a transaction bloats the stack and we want to reject it), and might change during a version.
</blockquote></details>

Cool, thanks!
___
*[`crates/blockifier/src/test_utils/initial_test_state.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1324#-Nns7cCF0phx2c8R_j2i:-NoHomVf7AkWAkHsFOtN:b-wm4jxv) ([raw file](https://github.com/starkware-libs/blockifier/blob/c69eb026f9adf49c09c689e2877491d157f14d97/crates/blockifier/src/test_utils/initial_test_state.rs#L50)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

-  Define a `ChainInfo` variable so that accesses to fields aren't too long? Especially in functions that access more than one field.
-   Change functions that only access fields from `ChainInfo` to receive this type instead of `BlockContext`.
</blockquote></details>

Done 
This was a good one, lots of places that used to take the whole blockContext now take just chainInfo


<!-- Sent from Reviewable.io -->

2024-01-17 09:03 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 17 of 18 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1324#-:-NoLeF5--acnVYQ75QGk:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-01-17 13:34 UTC, merged

2024-01-17 13:37 UTC, giladchase commented
@elintul  Sorry i merged this by mistake into the block_info branch, i reverted the merge and reopened this PR (no other changes): https://reviewable.io/reviews/starkware-libs/blockifier/1344