Replace PyBouncerInfo's additional_os_resources fiels to tx_weights f…
starkware-libs/blockifier pull request #1347
Opened 2024-01-18 10:00 UTC by ayeletstarkware

…ield and _calculate_tx_weights in Rust instead of in Python

2024-01-22 12:31 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1347)* status: 0 of 3 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-Nol8kv88v09p2g9BxPF:-Nol8kv93-RVlvULjt3a:b-a20h2j) (no related file):*
Python's PR:
https://reviewable.io/reviews/starkware-industries/starkware/33522

___


<!-- Sent from Reviewable.io -->

2024-01-23 11:48 UTC, MohammadNassar1 requested changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1347)* status: all files reviewed, 5 unresolved discussions (waiting on @ayeletstarkware and @elintul)

___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 94 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-Noq-OPw5-PheuOIC6nj:-Noq-OPw5-PheuOIC6nk:b-10gpm6) ([raw file](https://github.com/starkware-libs/blockifier/blob/83744713d45c41d73cd12b9760f0bc5db1b55d8c/crates/blockifier/src/transaction/transaction_utils.rs#L94)):*
> ```XML
>     for (key, value) in x {
>         result.insert(key.clone(), value);
>     }
> ```

It can be replaced by cloning x.



_Code quote:_
```XML
    // Insert values from x into result
    for (key, value) in x {
        result.insert(key.clone(), value);
    }
```
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-Noq-VL51fF-iicSuqMv:-Noq-VL51fF-iicSuqMw:b-df1ypx) ([raw file](https://github.com/starkware-libs/blockifier/blob/83744713d45c41d73cd12b9760f0bc5db1b55d8c/crates/blockifier/src/transaction/transaction_utils.rs#L98)):*
> ```XML
>     // Add values from y to result
>     for (key, value) in y {
>         let entry = result.entry(key.clone()).or_insert(0);
> ```

Why do you need clone here?



_Code quote:_
```XML
clone()
```
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 115 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-Noq2NnYAM-iGxkYcyum:-Noq2NnYAM-iGxkYcyun:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/83744713d45c41d73cd12b9760f0bc5db1b55d8c/crates/blockifier/src/transaction/transaction_utils.rs#L115)):*
> ```XML
>         tx_weights.insert("gas_weight".to_string(), value);
>         cairo_resource_usage.remove("l1_gas_usage");
>     }
> ```





_Suggestion:_
```XML
    if let Some(&value) = cairo_resource_usage.remove("l1_gas_usage") {
        tx_weights.insert("gas_weight".to_string(), value);
    }
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-Noq8CTa1a4HHmyH_abN:-Noq8CTa1a4HHmyH_abO:bmixj27) ([raw file](https://github.com/starkware-libs/blockifier/blob/83744713d45c41d73cd12b9760f0bc5db1b55d8c/crates/native_blockifier/src/transaction_executor.rs#L105)):*
> ```XML
>                 let message_segment_length = 0;
>                 let tx_weights = calculate_tx_weights(
>                     additional_os_resources.clone(),
> ```

Why clone?



_Code quote:_
```XML
.clone(),
```


<!-- Sent from Reviewable.io -->

2024-01-23 11:48 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1347)* status: all files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-Noq8bmGCc76yqZeRgPg:-Noq8bmGCc76yqZeRgPh:b-83sjoh) (no related file):*
Nice!

___


<!-- Sent from Reviewable.io -->

2024-01-23 15:50 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1347)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 98 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-Noq-VL51fF-iicSuqMv:-Noqubq24ksAk0QjBdba:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/83744713d45c41d73cd12b9760f0bc5db1b55d8c/crates/blockifier/src/transaction/transaction_utils.rs#L98)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why do you need clone here?
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-Noq8CTa1a4HHmyH_abN:-Noqvuz93ro1t4ywebGX:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/83744713d45c41d73cd12b9760f0bc5db1b55d8c/crates/native_blockifier/src/transaction_executor.rs#L105)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why clone?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-24 09:42 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1347)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @elintul, and @MohammadNassar1)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-Nounr913vtH7-uwbgoS:-NouqBlt0tAojGBs8Xex:b5r3kzf) ([raw file](https://github.com/starkware-libs/blockifier/blob/7212ae21d84b12de1d18ad7fcd1da116b1e3b6f7/crates/native_blockifier/src/transaction_executor.rs#L110)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Maybe out of bounds for this PR, but why is `message_segment_length` both in the struct `BouncerInfo` and also inside the `tx_weights`?
</blockquote></details>

Maybe it can be removed now that tx_weights is a part of boucer_info in rust. 
Can be done in a different PR.


<!-- Sent from Reviewable.io -->

2024-01-24 09:46 UTC, ArniStarkware commented
*[`crates/native_blockifier/src/transaction_executor.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-Nounr913vtH7-uwbgoS:-NouoBqUAkMfuTeoaNBn:b-l95tn2) ([raw file](https://github.com/starkware-libs/blockifier/blob/7212ae21d84b12de1d18ad7fcd1da116b1e3b6f7/crates/native_blockifier/src/transaction_executor.rs#L110)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Maybe it can be removed now that tx_weights is a part of boucer_info in rust. 
Can be done in a different PR.
</blockquote></details>

OK.
The same is true for `state_diff_size` (which implies `state_diff_size` should be a parameter of `calculate_tx_weights`, and be added same as `message_segment_length`).
Again, might be out of scope for this PR.


<!-- Sent from Reviewable.io -->

2024-01-24 09:47 UTC, ArniStarkware commented
*[`crates/native_blockifier/src/transaction_executor.rs` line 103 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-NourSXS687RS3d5SNia:-NourSXS687RS3d5SNib:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7212ae21d84b12de1d18ad7fcd1da116b1e3b6f7/crates/native_blockifier/src/transaction_executor.rs#L103)):*
> ```XML
>                     &tx_visited_storage_entries,
>                 )?;
>                 let message_segment_length = 0;
> ```





_Suggestion:_
```XML
let message_segment_length = 0;
let state_diff_size = 0;
```


<!-- Sent from Reviewable.io -->

2024-01-24 12:00 UTC, MohammadNassar1 requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1347)* status: all files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @elintul)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 87 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-NovKJN00LYALdOWem2g:-NovKJN1847SaoJSVdgv:b-heatkc) ([raw file](https://github.com/starkware-libs/blockifier/blob/7212ae21d84b12de1d18ad7fcd1da116b1e3b6f7/crates/native_blockifier/src/transaction_executor.rs#L87)):*
> ```XML
>         match tx_execution_result {
>             Ok(tx_execution_info) => {
>                 let actual_resources = tx_execution_info.actual_resources.0.clone();
> ```

Do you need a clone here?



_Code quote:_
```XML
let actual_resources = tx_execution_info.actual_resources.0.clone();
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-NovKm5D6ootHwRzTM2b:-NovKm5D6ootHwRzTM2c:bu5jph9) ([raw file](https://github.com/starkware-libs/blockifier/blob/7212ae21d84b12de1d18ad7fcd1da116b1e3b6f7/crates/native_blockifier/src/transaction_executor.rs#L110)):*
> ```XML
>                 );
>                 let py_bouncer_info =
>                     PyBouncerInfo { message_segment_length, state_diff_size: 0, tx_weights };
> ```

Please add a todo to remove the `message_segment_length` and `state_diff_size`.



_Code quote:_
```XML
 PyBouncerInfo { message_segment_length, state_diff_size: 0, tx_weights };
```


<!-- Sent from Reviewable.io -->

2024-01-24 14:13 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1347)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @elintul, and @MohammadNassar1)

___
*[`crates/native_blockifier/src/transaction_executor.rs` line 87 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-NovKJN00LYALdOWem2g:-NovNg9L9hERJpzmQqYA:by6uo1n) ([raw file](https://github.com/starkware-libs/blockifier/blob/7212ae21d84b12de1d18ad7fcd1da116b1e3b6f7/crates/native_blockifier/src/transaction_executor.rs#L87)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Do you need a clone here?
</blockquote></details>

yes, it's being changed both in caluclate_tx_weights and in this line:



_Code snippet:_
```XML
let py_tx_execution_info = PyTransactionExecutionInfo::from(tx_execution_info);
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 103 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-NourSXS687RS3d5SNia:-NovMYHB1F1oUanj-9GD:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7212ae21d84b12de1d18ad7fcd1da116b1e3b6f7/crates/native_blockifier/src/transaction_executor.rs#L103)):*
> ```XML
>                     &tx_visited_storage_entries,
>                 )?;
>                 let message_segment_length = 0;
> ```

Done.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-NovKm5D6ootHwRzTM2b:-NovNf1I7BnEQ8QnzIAz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7212ae21d84b12de1d18ad7fcd1da116b1e3b6f7/crates/native_blockifier/src/transaction_executor.rs#L110)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please add a todo to remove the `message_segment_length` and `state_diff_size`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-24 16:16 UTC, MohammadNassar1 requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1347)* status: all files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @elintul)

___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 86 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-NowDNyRDQChd74xr0TK:-NowDNyRDQChd74xr0TL:bttou) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a8d899081b1c0394e967abd5ca4cab0bc6134b5/crates/blockifier/src/transaction/transaction_utils.rs#L86)):*
> ```XML
> 
> // TODO(Ayelet, 01/02/2024): Move to VmExecutionResourcesWrapper when merged.
> pub fn to_dict(execution_resources: VmExecutionResources) -> HashMap<String, usize> {
> ```

Please change the function's name.
Maybe `VmExecutionResources_to_HashMap`



_Code quote:_
```XML
to_dict
```


<!-- Sent from Reviewable.io -->

2024-01-25 07:52 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1347)* status: all files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @elintul, and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 86 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-NowDNyRDQChd74xr0TK:-NozaWki4zbiTSecaORe:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a8d899081b1c0394e967abd5ca4cab0bc6134b5/crates/blockifier/src/transaction/transaction_utils.rs#L86)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please change the function's name.
Maybe `VmExecutionResources_to_HashMap`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-25 11:15 UTC, MohammadNassar1 requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1347)* status: all files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @elintul)

___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 95 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-Np-BDNTBcCEyRqBnRQf:-Np-BDNTBcCEyRqBnRQg:b-vxeip5) ([raw file](https://github.com/starkware-libs/blockifier/blob/65e769b443f35c0d669345605597d9ae1aa0bf89/crates/blockifier/src/transaction/transaction_utils.rs#L95)):*
> ```XML
> }
> 
> fn add_counters(
> ```

What do you think about a generic implementation?
Something like:
fn add_counters<K, V>(x: HashMap<K, V>, y: HashMap<K, V>) -> HashMap<K, V>
 where 
K: std::hash::Hash + Eq + Clone, 
V: std::ops::AddAssign + Default + Clone, 
{ 
.
.
.
}



_Code quote:_
```XML
fn add_counters(
```
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 95 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-Np-JUPaE19f8xDCfRJ9:-Np-JUPaE19f8xDCfRJA:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/65e769b443f35c0d669345605597d9ae1aa0bf89/crates/blockifier/src/transaction/transaction_utils.rs#L95)):*
> ```XML
> }
> 
> fn add_counters(
> ```





_Suggestion:_
```XML
add_hashmaps
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-NovKm5D6ootHwRzTM2b:-Np-KBo23we67NDsmGWe:b9r52qt) ([raw file](https://github.com/starkware-libs/blockifier/blob/7212ae21d84b12de1d18ad7fcd1da116b1e3b6f7/crates/native_blockifier/src/transaction_executor.rs#L110)):*
<details><summary><i>Previously, ayeletstarkware (Ayelet Zilber) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Cannot see it.
Did you forget to push?


<!-- Sent from Reviewable.io -->

2024-01-25 11:39 UTC, elintul submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1347)* status: all files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-01-25 15:28 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1347)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 95 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-Np-JUPaE19f8xDCfRJ9:-Np0Cfs47DjnPhWE-gpH:b-heiv0t) ([raw file](https://github.com/starkware-libs/blockifier/blob/65e769b443f35c0d669345605597d9ae1aa0bf89/crates/blockifier/src/transaction/transaction_utils.rs#L95)):*
> ```XML
> }
> 
> fn add_counters(
> ```

maybe merge_hashmaps?
moved func to utills
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 110 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-NovKm5D6ootHwRzTM2b:-Np-puVP1YqMT4GO3utY:b-ywsqdr) ([raw file](https://github.com/starkware-libs/blockifier/blob/7212ae21d84b12de1d18ad7fcd1da116b1e3b6f7/crates/native_blockifier/src/transaction_executor.rs#L110)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Cannot see it.
Did you forget to push?
</blockquote></details>

it's here
https://github.com/starkware-libs/blockifier/blob/65e769b443f35c0d669345605597d9ae1aa0bf89/crates/native_blockifier/src/py_transaction_execution_info.rs#L184

and will be fixed very soon. 


<!-- Sent from Reviewable.io -->

2024-01-25 15:35 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1347)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @ayeletstarkware, @elintul, and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 113 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-Np0EdLtE5ZkS4ubVLM3:-Np0EdLu-p0lFrK3-Xvz:b-sxu9l7) ([raw file](https://github.com/starkware-libs/blockifier/blob/65e769b443f35c0d669345605597d9ae1aa0bf89/crates/blockifier/src/transaction/transaction_utils.rs#L113)):*
> ```XML
> ) -> HashMap<String, usize> {
>     let mut tx_weights: HashMap<String, usize> = HashMap::new();
>     let mut cairo_resource_usage: HashMap<String, usize> = actual_resources;
> ```

Does this mean we change the input `actual_resources`?



_Code quote:_
```XML
    let mut cairo_resource_usage: HashMap<String, usize> = actual_resources;
```
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 116 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-Np0F6NI9c604gc2yTpM:-Np0F6NI9c604gc2yTpN:bhaiimd) ([raw file](https://github.com/starkware-libs/blockifier/blob/65e769b443f35c0d669345605597d9ae1aa0bf89/crates/blockifier/src/transaction/transaction_utils.rs#L116)):*
> ```XML
>     if let Some(value) = cairo_resource_usage.remove("l1_gas_usage") {
>         tx_weights.insert("gas_weight".to_string(), value);
>     }
> ```

Should we raise an error if `l1_gas_usage` is not a value in the dict?



_Suggestion:_
```XML
    if let Some(value) = cairo_resource_usage.remove("l1_gas_usage") {
        tx_weights.insert("gas_weight".to_string(), value);
    } else {...}
```


<!-- Sent from Reviewable.io -->

2024-01-25 16:02 UTC, ArniStarkware commented
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 103 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-Np0JuQ7EqBP4PTuryOq:-Np0JuQ7EqBP4PTuryOr:bm3em88) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1d4f3f839a6dc4ace1c0b6fea75979f56ee40fd/crates/blockifier/src/transaction/transaction_utils.rs#L103)):*
> ```XML
>     actual_resources: HashMap<String, usize>,
>     message_segment_length: usize,
> ) -> HashMap<String, usize> {
> ```

If we use the type for `HashMap<String, usize>`, we can consider setting an alias for it (Where it is used in this context).

I am unsure if this is a good idea (it might be an overkill).



_Suggestion:_
```XML
// In a proper file:
type Resources_Map = HashMap<String, size>;

// here:
pub fn calculate_tx_weights(
    additional_os_resources: VmExecutionResources,
    actual_resources: Resources_Map,
    message_segment_length: usize,
) -> Resources_Map {
```


<!-- Sent from Reviewable.io -->

2024-01-27 15:15 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1347)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @ayeletstarkware and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-01-28 07:52 UTC, MohammadNassar1 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-:-NpE2bXwChJDopXoVf64:bnfp4nl)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @ayeletstarkware, and @elintul)



<!-- Sent from Reviewable.io -->

2024-01-28 09:54 UTC, ayeletstarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1347)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @elintul, and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 113 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-Np0EdLtE5ZkS4ubVLM3:-Np0GM783SNbveWKBnnk:b-dm4yxz) ([raw file](https://github.com/starkware-libs/blockifier/blob/65e769b443f35c0d669345605597d9ae1aa0bf89/crates/blockifier/src/transaction/transaction_utils.rs#L113)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Does this mean we change the input `actual_resources`?
</blockquote></details>

I think that's the case, but - the initial data from 'transaction_executor' is cloned before passing it to this function. 
The term "cairo_resource_usage" is the name used in the original Python code.
___
*[`crates/blockifier/src/transaction/transaction_utils.rs` line 116 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1347#-Np0F6NI9c604gc2yTpM:-NpERlMU0yoGbbBkE5Ej:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/65e769b443f35c0d669345605597d9ae1aa0bf89/crates/blockifier/src/transaction/transaction_utils.rs#L116)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Should we raise an error if `l1_gas_usage` is not a value in the dict?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-28 10:18 UTC, MohammadNassar1 approved these changes
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1347)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @elintul)



<!-- Sent from Reviewable.io -->

2024-01-28 11:32 UTC, ArniStarkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1347)* status: all files reviewed, 1 unresolved discussion (waiting on @ayeletstarkware)



<!-- Sent from Reviewable.io -->

2024-01-28 12:08 UTC, merged