pre_process_block refactor for full_nodes usage
starkware-libs/blockifier pull request #1349
Opened 2024-01-18 11:34 UTC by Yael-Starkware

2024-01-22 09:48 UTC, giladchase requested changes
Can you please add what changes are included here other than creating `BlockContext` inside pre_process_block? 
Asking cause i saw CachedState being added to places 

> Reviewed 2 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-:-NokXKVLCbvFkY0iqx1g:bcfkmuh)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @elintul and @Yael-Starkware)

___
*[`crates/blockifier/src/block_execution.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NokBHPb7oGBLfv6G4Ff:-NokBHPb7oGBLfv6G4Fg:bxcl5m) ([raw file](https://github.com/starkware-libs/blockifier/blob/d602d639cd34fecddb02e332bbd3a40a36224aa7/crates/blockifier/src/block_execution.rs#L31)):*
> ```XML
> }
> 
> impl Default for BlockContextArgs {
> ```

Which field is preventing the `derive` from working?



_Code quote:_
```XML
impl Default for BlockContextArgs {
```
___
*[`crates/blockifier/src/block_execution.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NokVqagE-Zssno5G4lJ:-NokVqagE-Zssno5G4lK:b-kvuv7o) ([raw file](https://github.com/starkware-libs/blockifier/blob/d602d639cd34fecddb02e332bbd3a40a36224aa7/crates/blockifier/src/block_execution.rs#L61)):*
> ```XML
> pub fn pre_process_block(
>     state: &mut dyn State,
>     old_block_number_and_hash: BlockNumberAndHash,
> ```

What causes this to no longer be optional?



_Code quote:_
```XML
    old_block_number_and_hash: BlockNumberAndHash,
```
___
*[`crates/blockifier/src/block_execution_test.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NokWAudCyYOMFlp3-8w:-NokWAudCyYOMFlp3-8x:bclwk4w) ([raw file](https://github.com/starkware-libs/blockifier/blob/d602d639cd34fecddb02e332bbd3a40a36224aa7/crates/blockifier/src/block_execution_test.rs#L23)):*
> ```XML
>             block_number: BlockNumber(block_number),
>             block_hash: BlockHash(block_hash),
>         },
> ```

minor: consider adding to `BlockNumberAndHash ` the constructor`pub fn new(u64, StarkFelt)`



_Code quote:_
```XML
        BlockNumberAndHash {
            block_number: BlockNumber(block_number),
            block_hash: BlockHash(block_hash),
        },
```
___
*[`crates/native_blockifier/src/py_block_executor_test.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NokXfHV7DbqnaTpdmaf:-NokXfHV7DbqnaTpdmag:b-i3ednv) ([raw file](https://github.com/starkware-libs/blockifier/blob/d602d639cd34fecddb02e332bbd3a40a36224aa7/crates/native_blockifier/src/py_block_executor_test.rs#L20)):*
> ```XML
>     // Initialize executor and set a contract class on the state.
>     let temp_storage_path = tempfile::tempdir().unwrap().into_path();
>     let old_block_number_and_hash = (u64::default(), PyFelt::default());
> ```

Makes type-inference figure out the types: it's OK to do here because this is just initialization of defaults, so we don't want to help the reader not have to read too much into this.



_Suggestion:_
```XML
    let old_block_number_and_hash = Default::default();
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NokZILN2_UdC8tDCW1s:-NokZILN2_UdC8tDCW1t:b7jf3nk) ([raw file](https://github.com/starkware-libs/blockifier/blob/d602d639cd34fecddb02e332bbd3a40a36224aa7/crates/native_blockifier/src/py_validator.rs#L45)):*
> ```XML
>         let global_contract_cache = GlobalContractCache::default();
>         let state_reader = PyStateReader::new(state_reader_proxy);
>         let mut state = CachedState::new(state_reader, global_contract_cache);
> ```

I see these were hoisted up from inside `TransactionExecutor::new`, can they no longer stay there under this implementation? (asking can this seems to introduce duplication)



_Code quote:_
```XML
        let global_contract_cache = GlobalContractCache::default();
        let state_reader = PyStateReader::new(state_reader_proxy);
        let mut state = CachedState::new(state_reader, global_contract_cache);
```


<!-- Sent from Reviewable.io -->

2024-01-22 13:59 UTC, Yael-Starkware commented
The corresponding [PR in python](https://reviewable.io/reviews/starkware-industries/starkware/33478)

2024-01-22 15:55 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1349)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/block_execution.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NokBHPb7oGBLfv6G4Ff:-NolTdVE0IwPKGzsX3l0:b-b7ypia) ([raw file](https://github.com/starkware-libs/blockifier/blob/d602d639cd34fecddb02e332bbd3a40a36224aa7/crates/blockifier/src/block_execution.rs#L31)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Which field is preventing the `derive` from working?
</blockquote></details>

chain_id
___
*[`crates/blockifier/src/block_execution.rs` line 61 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NokVqagE-Zssno5G4lJ:-NolTfg16Qnkqyl2gTWJ:b5dvmpp) ([raw file](https://github.com/starkware-libs/blockifier/blob/d602d639cd34fecddb02e332bbd3a40a36224aa7/crates/blockifier/src/block_execution.rs#L61)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

What causes this to no longer be optional?
</blockquote></details>

spoke to Yoni and Ariel. changing it back to Option and adding a check that it is none only for block_number <=10
___
*[`crates/blockifier/src/block_execution_test.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NokWAudCyYOMFlp3-8w:-NoldduK0e4I3vccjr-U:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/d602d639cd34fecddb02e332bbd3a40a36224aa7/crates/blockifier/src/block_execution_test.rs#L23)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

minor: consider adding to `BlockNumberAndHash ` the constructor`pub fn new(u64, StarkFelt)`
</blockquote></details>

done
___
*[`crates/native_blockifier/src/py_block_executor_test.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NokXfHV7DbqnaTpdmaf:-Noldyrw6WYUeQkAYYWk:b-fe4ja) ([raw file](https://github.com/starkware-libs/blockifier/blob/d602d639cd34fecddb02e332bbd3a40a36224aa7/crates/native_blockifier/src/py_block_executor_test.rs#L20)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Makes type-inference figure out the types: it's OK to do here because this is just initialization of defaults, so we don't want to help the reader not have to read too much into this.
</blockquote></details>

deleted this line
___
*[`crates/native_blockifier/src/py_validator.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NokZILN2_UdC8tDCW1s:-Nole3MA5yZSQLUbLCBF:bf0mkx7) ([raw file](https://github.com/starkware-libs/blockifier/blob/d602d639cd34fecddb02e332bbd3a40a36224aa7/crates/native_blockifier/src/py_validator.rs#L45)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I see these were hoisted up from inside `TransactionExecutor::new`, can they no longer stay there under this implementation? (asking can this seems to introduce duplication)
</blockquote></details>

each of them (py_validator an py_block_executer) uses a different state_reader so I'm not sure I can have one function for both. but maybe there is some generic way that I am missing?


<!-- Sent from Reviewable.io -->

2024-01-22 15:57 UTC, Yael-Starkware reviewed
there are no other changes.
I need to get the state for both pre_process_block and TransactionExecution::new() . lets talk if this doesnt seem to be the best way

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-:-NolsjgwCBjpzvJay-L2:b-u30b02)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)



<!-- Sent from Reviewable.io -->

2024-01-23 16:29 UTC, giladchase requested changes
> Reviewed 1 of 2 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1349)* status: all files reviewed, 7 unresolved discussions (waiting on @elintul and @Yael-Starkware)

___
*[`crates/blockifier/src/block_execution.rs` line 58 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Nor4EB31kqIn1dZA5EW:-Nor4EB31kqIn1dZA5EX:bsvyuhr) ([raw file](https://github.com/starkware-libs/blockifier/blob/22ecb70812d384b501ecd706a972f43fe48adca0/crates/blockifier/src/block_execution.rs#L58)):*
> ```XML
>     pub fn new(block_number: BlockNumber, block_hash: BlockHash) -> BlockNumberAndHash {
>         BlockNumberAndHash { block_number, block_hash }
>     }
> ```

These should be `u64` and `StarkFelt`, since this is a convenience constructor.
In other words, if the caller already has a BlockNumber and BlockHash, they can just use the public constructor.
If they have only the raw data (u64 and StarkFelt), this will make things nicer for them.



_Code quote:_
```XML
    pub fn new(block_number: BlockNumber, block_hash: BlockHash) -> BlockNumberAndHash {
        BlockNumberAndHash { block_number, block_hash }
    }
```
___
*[`crates/blockifier/src/block_execution.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NoqwujT5T7F2C-17k_4:-NoqwujU2-XXW8nkvMmj:b-uqewf8) ([raw file](https://github.com/starkware-libs/blockifier/blob/22ecb70812d384b501ecd706a972f43fe48adca0/crates/blockifier/src/block_execution.rs#L71)):*
> ```XML
>     block_context_args: BlockContextArgs,
> ) -> StateResult<BlockContext> {
>     // check of old_block_number_and_hash is None
> ```

Not necessary, but let's add a very short comment above the `None` branch though, explaining why we only allow up None to that constant.
___
*[`crates/blockifier/src/block_execution.rs` line 87 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Noqzyu_12blK04EDqUk:-Noqzyu_12blK04EDqUl:b-dq4bl9) ([raw file](https://github.com/starkware-libs/blockifier/blob/22ecb70812d384b501ecd706a972f43fe48adca0/crates/blockifier/src/block_execution.rs#L87)):*
> ```XML
>             )?;
>         }
>     }
> ```

nit: do the `Some` branch first, since it is more important (as a rule of thumb the more important something is the higher it goes in the file).
nit 2: might be more readeable to convert the `None` into a
```rust
 Some(...) => ...,
 None if block_context_args,... => return Err(...),
 None => {}
```



_Code quote:_
```XML
    match old_block_number_and_hash {
        None => {
            if block_context_args.block_number >= BlockNumber(STORED_BLOCK_HASH_BUFFER) {
                return Err(StateError::OldBlockHashNotProvided);
            }
        }
        Some(BlockNumberAndHash { block_number, block_hash }) => {
            state.set_storage_at(
                ContractAddress::try_from(StarkFelt::from(constants::BLOCK_HASH_CONTRACT_ADDRESS))
                    .expect("Failed to convert `BLOCK_HASH_CONTRACT_ADDRESS` to ContractAddress."),
                StorageKey::try_from(StarkFelt::from(block_number.0))
                    .expect("Failed to convert BlockNumber to StorageKey."),
                block_hash.0,
            )?;
        }
    }
```
___
*[`crates/blockifier/src/block_execution_test.rs` line 16 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Nor5psO63viwUnBQEMT:-Nor5psO63viwUnBQEMU:b-6tiv5f) ([raw file](https://github.com/starkware-libs/blockifier/blob/22ecb70812d384b501ecd706a972f43fe48adca0/crates/blockifier/src/block_execution_test.rs#L16)):*
> ```XML
> 
>     let block_number: u64 = 10;
>     let block_hash = StarkFelt::from(20u32);
> ```

Didn't know you could omit the underscore :scream: 
But i think it's more readable this way (also u8 suffices)



_Suggestion:_
```XML
20_u8
```
___
*[`crates/blockifier/src/block_execution_test.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Nor5Wnl8-lFJGu_u2yb:-Nor5Wnl8-lFJGu_u2yc:bhp3pw8) ([raw file](https://github.com/starkware-libs/blockifier/blob/22ecb70812d384b501ecd706a972f43fe48adca0/crates/blockifier/src/block_execution_test.rs#L34)):*
> ```XML
>     let block_context_args =
>         BlockContextArgs { block_number: BlockNumber(10), ..Default::default() };
>     assert!(pre_process_block(&mut state, None, block_context_args).is_err());
> ```

minor: consider adding an additional one of these with `STORED_BLOCK_HASH_BUFFER - 1` (with `is_ok()`), to show that it is a boundary value.



_Suggestion:_
```XML
    // Test that the function returns error when old_block_number_and_hash is None and block_number
    // >= 10
    let block_context_args =
        BlockContextArgs { block_number: BlockNumber(STORED_BLOCK_HASH_BUFFER), ..Default::default() };
    assert!(pre_process_block(&mut state, None, block_context_args).is_err());
```
___
*[`crates/blockifier/src/state/errors.rs` line 23 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Nor625n36znIf_WgxTo:-Nor625n36znIf_WgxTp:bjzan2j) ([raw file](https://github.com/starkware-libs/blockifier/blob/22ecb70812d384b501ecd706a972f43fe48adca0/crates/blockifier/src/state/errors.rs#L23)):*
> ```XML
>     #[error("Failed to read from state: {0}.")]
>     StateReadError(String),
>     #[error("A block hash must be provided for block number >{}.", STORED_BLOCK_HASH_BUFFER)]
> ```

If this works (it might not...) then it's more readable



_Suggestion:_
```XML
  #[error("A block hash must be provided for block number > {STORED_BLOCK_HASH_BUFFER}.")]
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 318 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Nor6pfk5cmhhTpFXjZi:-Nor6pfk5cmhhTpFXjZj:b-4n8r0k) ([raw file](https://github.com/starkware-libs/blockifier/blob/22ecb70812d384b501ecd706a972f43fe48adca0/crates/native_blockifier/src/py_block_executor.rs#L318)):*
> ```XML
>         max_recursion_depth,
>         chain_id: chain_info.chain_id,
>         fee_token_addresses: chain_info.fee_token_addresses,
> ```

Unused? i think you can remove from BlockContextArgs (probably due to a rebase?)



_Code quote:_
```XML
      fee_token_addresses: chain_info.fee_token_addresses,
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 325 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Nor75q2CHwBSTc4u45B:-Nor75q2CHwBSTc4u45C:bcir30b) ([raw file](https://github.com/starkware-libs/blockifier/blob/22ecb70812d384b501ecd706a972f43fe48adca0/crates/native_blockifier/src/py_block_executor.rs#L325)):*
> ```XML
> 
> // Block pre-processing; see `block_execution::pre_process_block` documentation.
> pub fn pre_process_block(
> ```

Maybe make this a private method on `PyBlockExecutor`, it's taking



_Code quote:_
```XML
pub fn pre_process_block(
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NokZILN2_UdC8tDCW1s:-Nor7cIG6-CodrdRcLLU:bcl1rej) ([raw file](https://github.com/starkware-libs/blockifier/blob/d602d639cd34fecddb02e332bbd3a40a36224aa7/crates/native_blockifier/src/py_validator.rs#L45)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

each of them (py_validator an py_block_executer) uses a different state_reader so I'm not sure I can have one function for both. but maybe there is some generic way that I am missing?
</blockquote></details>

I meant that previously CachedState (and others) were initialized inside tx_executor, and are now initialized higher up the stack (in the validator/block_executor).

It wasn't obvious why this was necessary or relevant to this PR, I figured it out (due to an implementation constraint of pre_process_block which requires `state`), but in the future plz consider adding non-obvious changes to the PR description (as in, it isn't obviously related to the task at hand), it'll make reviewing easier (less c [...]

2024-01-23 16:38 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1349)* status: all files reviewed, 7 unresolved discussions (waiting on @elintul and @Yael-Starkware)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NorAvxUDfb_iBUe4j9h):*
I think the PR title needs to match this string and it'll appease commitlint



_Code quote:_
```
refactor(execution): pre_process_block refactor for full_nodes simulate transaction
```


<!-- Sent from Reviewable.io -->

2024-01-24 13:48 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1349)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/block_execution.rs` line 58 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Nor4EB31kqIn1dZA5EW:-NovdZTd6skjmyxCS6M8:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/22ecb70812d384b501ecd706a972f43fe48adca0/crates/blockifier/src/block_execution.rs#L58)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

These should be `u64` and `StarkFelt`, since this is a convenience constructor.
In other words, if the caller already has a BlockNumber and BlockHash, they can just use the public constructor.
If they have only the raw data (u64 and StarkFelt), this will make things nicer for them.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/block_execution.rs` line 71 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NoqwujT5T7F2C-17k_4:-Novd_1R6jjhpINVK6sG:bvcu4ct) ([raw file](https://github.com/starkware-libs/blockifier/blob/22ecb70812d384b501ecd706a972f43fe48adca0/crates/blockifier/src/block_execution.rs#L71)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Not necessary, but let's add a very short comment above the `None` branch though, explaining why we only allow up None to that constant.
</blockquote></details>

oops the comment was left there by mistake
done.
___
*[`crates/blockifier/src/block_execution.rs` line 87 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Noqzyu_12blK04EDqUk:-NovfgDt9B2fi_sLd95q:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/22ecb70812d384b501ecd706a972f43fe48adca0/crates/blockifier/src/block_execution.rs#L87)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

nit: do the `Some` branch first, since it is more important (as a rule of thumb the more important something is the higher it goes in the file).
nit 2: might be more readeable to convert the `None` into a
```rust
 Some(...) => ...,
 None if block_context_args,... => return Err(...),
 None => {}
```
</blockquote></details>

done
___
*[`crates/blockifier/src/block_execution_test.rs` line 16 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Nor5psO63viwUnBQEMT:-NovfnsA0kvDDxrcWGAt:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/22ecb70812d384b501ecd706a972f43fe48adca0/crates/blockifier/src/block_execution_test.rs#L16)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Didn't know you could omit the underscore :scream: 
But i think it's more readable this way (also u8 suffices)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/block_execution_test.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Nor5Wnl8-lFJGu_u2yb:-NovgwDY54L1abKm9a7r:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/22ecb70812d384b501ecd706a972f43fe48adca0/crates/blockifier/src/block_execution_test.rs#L34)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

minor: consider adding an additional one of these with `STORED_BLOCK_HASH_BUFFER - 1` (with `is_ok()`), to show that it is a boundary value.
</blockquote></details>

done
___
*[`crates/blockifier/src/state/errors.rs` line 23 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Nor625n36znIf_WgxTo:-Novh3H57-9pyupi1BCc:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/22ecb70812d384b501ecd706a972f43fe48adca0/crates/blockifier/src/state/errors.rs#L23)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

If this works (it might not...) then it's more readable
</blockquote></details>

done
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 318 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Nor6pfk5cmhhTpFXjZi:-NovhJh4BG-1jaQPrc7T:b7mdox2) ([raw file](https://github.com/starkware-libs/blockifier/blob/22ecb70812d384b501ecd706a972f43fe48adca0/crates/native_blockifier/src/py_block_executor.rs#L318)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Unused? i think you can remove from BlockContextArgs (probably due to a rebase?)
</blockquote></details>

not sure I understand, why are you saying it is unused?
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 325 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Nor75q2CHwBSTc4u45B:-Novhe3PBfWwiWDmBUZb:b-14pyw2) ([raw file](https://github.com/starkware-libs/blockifier/blob/22ecb70812d384b501ecd706a972f43fe48adca0/crates/native_blockifier/src/py_block_executor.rs#L325)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Maybe make this a private method on `PyBlockExecutor`, it's taking
</blockquote></details>

I did, but it needs to be used by the py_validator in the future.|
maybe need to locate it in a different place? or maybe think about it in the future when adding this to the validator.
___
*[`crates/native_blockifier/src/py_validator.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NokZILN2_UdC8tDCW1s:-Novi5pvDfbgvxD99IWK:bgfpgh) ([raw file](https://github.com/starkware-libs/blockifier/blob/d602d639cd34fecddb02e332bbd3a40a36224aa7/crates/native_blockifier/src/py_validator.rs#L45)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I meant that previously CachedState (and others) were initialized inside tx_executor, and are now initialized higher up the stack (in the validator/block_executor).

It wasn't obvious why this was necessary or relevant to this PR, I figured it out (due to an implementation constraint of pre_process_block which requires `state`), but in the future plz consider adding non-obvious changes to the PR description (as in, it isn't obviously related to the task at hand), it'll make reviewing easier (less cognitive load on the reviewer while reading through).
</blockquote></details>

Ok sure I'll try to be more explicit next time.
Cognitive load is definitely the worst.


<!-- Sent from Reviewable.io -->

2024-01-24 13:48 UTC, Yael-Starkware commented
Please note that I removed all changes related to the py_validator in order to take this one as a task for the future.

2024-01-25 07:54 UTC, giladchase requested changes
> Reviewed 2 of 2 files at r5, 2 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1349)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @Yael-Starkware)

___
*[`crates/blockifier/src/block_context.rs` line 13 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NozZH6i2GfjUeS_c1Hg:-NozZH6i2GfjUeS_c1Hh:bl3cjpy) ([raw file](https://github.com/starkware-libs/blockifier/blob/628ba2fa929086e8fbafc2edba56248415f8894e/crates/blockifier/src/block_context.rs#L13)):*
> ```XML
> pub struct BlockContext {
>     // At least one of the following fields should be pub(crate) to make the constructore private.
>     pub(crate) block_info: BlockInfo,
> ```

Add a getter (for external users)?



_Code quote:_
```XML
    pub(crate) block_info: BlockInfo,
```
___
*[`crates/blockifier/src/block_context.rs` line 15 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NozZE_PAnz1C2w4bX4v:-NozZE_PAnz1C2w4bX4w:b-5j4p3q) ([raw file](https://github.com/starkware-libs/blockifier/blob/628ba2fa929086e8fbafc2edba56248415f8894e/crates/blockifier/src/block_context.rs#L15)):*
> ```XML
>     pub(crate) block_info: BlockInfo,
>     pub chain_info: ChainInfo,
> }
> ```

We wanna focus on the purpose (to ensure correctness) rather than the implementation details, and also point them to where they should go to create one:  this is a breaking change and we want it to be an easy fix for users.



_Suggestion:_
```XML
/// Create via [`crate::block_execution::pre_process_block`] to ensure correctness.
#[derive(Clone, Debug)]
pub struct BlockContext {
    pub(crate) block_info: BlockInfo,
    pub chain_info: ChainInfo,
}
```
___
*[`crates/blockifier/src/block_context.rs` line 18 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Noz_ZLPDgjb69qNKQHh:-Noz_ZLQ0J3_OOaZA1Kx:bvz1arc) ([raw file](https://github.com/starkware-libs/blockifier/blob/628ba2fa929086e8fbafc2edba56248415f8894e/crates/blockifier/src/block_context.rs#L18)):*
> ```XML
> 
> impl BlockContext {
>     pub fn new_unchecked(block_context_args: BlockContextArgs) -> Self {
> ```

Always warn about using unchecked stuff :smiling_face_with_tear: 



_Suggestion:_
```XML
    /// Note: Prefer using the recommended constructor methods as detailed in the struct documentation.
    /// This method is intended for internal use and will be deprecated in future versions.
    pub fn new_unchecked(block_context_args: BlockContextArgs) -> Self {
```
___
*[`crates/blockifier/src/block_execution.rs` line 48 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NozYZuwA1SwaT9djde2:-NozYZuwA1SwaT9djde3:b-4s2p8x) ([raw file](https://github.com/starkware-libs/blockifier/blob/628ba2fa929086e8fbafc2edba56248415f8894e/crates/blockifier/src/block_execution.rs#L48)):*
> ```XML
>         }
>     }
> }
> ```

Move these to block_context.rs?



_Code quote:_
```XML
pub struct BlockContextArgs {
    pub chain_id: ChainId,
    pub block_number: BlockNumber,
    pub block_timestamp: BlockTimestamp,
    pub sequencer_address: ContractAddress,
    pub fee_token_addresses: FeeTokenAddresses,
    pub vm_resource_fee_cost: Arc<HashMap<String, f64>>,
    pub use_kzg_da: bool,
    pub gas_prices: GasPrices,
    pub invoke_tx_max_n_steps: u32,
    pub validate_max_n_steps: u32,
    pub max_recursion_depth: usize,
}

impl Default for BlockContextArgs {
    fn default() -> Self {
        Self {
            chain_id: ChainId("0x0".to_string()),
            block_number: BlockNumber::default(),
            block_timestamp: BlockTimestamp::default(),
            sequencer_address: ContractAddress::default(),
            fee_token_addresses: FeeTokenAddresses::default(),
            vm_resource_fee_cost: Default::default(),
            use_kzg_da: false,
            gas_prices: GasPrices::default(),
            invoke_tx_max_n_steps: 0,
            validate_max_n_steps: 0,
            max_recursion_depth: 0,
        }
    }
}
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 318 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Nor6pfk5cmhhTpFXjZi:-NozXFyP38Lj6VCxV9B9:b-a2bhxk) ([raw file](https://github.com/starkware-libs/blockifier/blob/22ecb70812d384b501ecd706a972f43fe48adca0/crates/native_blockifier/src/py_block_executor.rs#L318)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

not sure I understand, why are you saying it is unused?
</blockquote></details>

My bad, srry. 
I got confused, i missed that this is now creating `BlockContextArgs`, rather than `BlockContext`
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 325 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Nor75q2CHwBSTc4u45B:-NozS2JY5IF77E4QTYvt:b-fmx6d6) ([raw file](https://github.com/starkware-libs/blockifier/blob/22ecb70812d384b501ecd706a972f43fe48adca0/crates/native_blockifier/src/py_block_executor.rs#L325)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I did, but it needs to be used by the py_validator in the future.|
maybe need to locate it in a different place? or maybe think about it in the future when adding this to the validator.
</blockquote></details>

Oh i sent a half finished comment, srry :sweat_smile: 
Ya let's not worry about it now


<!-- Sent from Reviewable.io -->

2024-01-25 09:52 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1349)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/block_context.rs` line 13 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NozZH6i2GfjUeS_c1Hg:-Np--Ccn9ijak-zezgiS:btiketx) ([raw file](https://github.com/starkware-libs/blockifier/blob/628ba2fa929086e8fbafc2edba56248415f8894e/crates/blockifier/src/block_context.rs#L13)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Add a getter (for external users)?
</blockquote></details>

added for both block_info and chain_info for symmetry. 
done.
___
*[`crates/blockifier/src/block_context.rs` line 15 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NozZE_PAnz1C2w4bX4v:-Np--OLP2HNeNXwet_xh:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/628ba2fa929086e8fbafc2edba56248415f8894e/crates/blockifier/src/block_context.rs#L15)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

We wanna focus on the purpose (to ensure correctness) rather than the implementation details, and also point them to where they should go to create one:  this is a breaking change and we want it to be an easy fix for users.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/block_context.rs` line 18 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Noz_ZLPDgjb69qNKQHh:-Np--VUKBJesA3aSQyDE:bpdvj3r) ([raw file](https://github.com/starkware-libs/blockifier/blob/628ba2fa929086e8fbafc2edba56248415f8894e/crates/blockifier/src/block_context.rs#L18)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Always warn about using unchecked stuff :smiling_face_with_tear:
</blockquote></details>

Done.

I agree it's very important to see things from the user's perspective, should've thought about it myself as a product person.
___
*[`crates/blockifier/src/block_execution.rs` line 48 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NozYZuwA1SwaT9djde2:-Np--tn_5RzqsKmCrzvn:b3j2mrk) ([raw file](https://github.com/starkware-libs/blockifier/blob/628ba2fa929086e8fbafc2edba56248415f8894e/crates/blockifier/src/block_execution.rs#L48)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Move these to block_context.rs?
</blockquote></details>

I was debating this one myself, not sure why I decided not to.
done.


<!-- Sent from Reviewable.io -->

2024-01-25 12:24 UTC, giladchase approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-:-Np-_5ad-Z6Gt2RwHbSr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @Yael-Starkware)

___
*[`crates/blockifier/src/block_context.rs` line 13 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NozZH6i2GfjUeS_c1Hg:-Np-ZQkABn21Kuq0j-nb:btsxss5) ([raw file](https://github.com/starkware-libs/blockifier/blob/628ba2fa929086e8fbafc2edba56248415f8894e/crates/blockifier/src/block_context.rs#L13)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

added for both block_info and chain_info for symmetry. 
done.
</blockquote></details>

In that case plz make chain_info pub(crate) as well, otherwise a getter for a public field is confusing.
___
*[`crates/blockifier/src/block_context.rs` line 18 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Noz_ZLPDgjb69qNKQHh:-Np-ZcS2-dQoLiYajcgL:b-mn7wch) ([raw file](https://github.com/starkware-libs/blockifier/blob/628ba2fa929086e8fbafc2edba56248415f8894e/crates/blockifier/src/block_context.rs#L18)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Done.

I agree it's very important to see things from the user's perspective, should've thought about it myself as a product person.
</blockquote></details>

It's totally cool :blush: we always forget stuff, even basic stuff, it happens :)


<!-- Sent from Reviewable.io -->

2024-01-25 12:29 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1349)* status: all files reviewed, 7 unresolved discussions (waiting on @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Np-a1yrCqAOOiiuTKOf:-Np-a1yrCqAOOiiuTKOg:bctqv0j) (no related file):*
This PR, while self-contained, is a bit too big. Let's separate prep. changes for this feature to their own PRs, which will make reviewing them easier.

___


<!-- Sent from Reviewable.io -->

2024-01-28 08:08 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1349)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/block_context.rs` line 13 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-NozZH6i2GfjUeS_c1Hg:-NpE65ZT5M9ljgMetS9w:b-xwdats) ([raw file](https://github.com/starkware-libs/blockifier/blob/628ba2fa929086e8fbafc2edba56248415f8894e/crates/blockifier/src/block_context.rs#L13)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

In that case plz make chain_info pub(crate) as well, otherwise a getter for a public field is confusing.
</blockquote></details>

so I'll delete the function :) I remember I had trouble making it public
___
*[`crates/blockifier/src/block_context.rs` line 18 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Noz_ZLPDgjb69qNKQHh:-NpE64hz6t0wKue7gHEn:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/628ba2fa929086e8fbafc2edba56248415f8894e/crates/blockifier/src/block_context.rs#L18)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

It's totally cool :blush: we always forget stuff, even basic stuff, it happens :)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/block_context.rs` line 11 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Np-_qkW7IvdCaK55aK3:-NpE6DV07vcuBoOamAvW:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/1763f9d158847d2e6f7e4b75090e3c91209c1f6d/crates/blockifier/src/block_context.rs#L11)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please separate `BlockContext` c-tor changes to its own PR.
</blockquote></details>

done.
___
*[`crates/blockifier/src/block_execution.rs` line 15 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Np-_l7E4ZjFfMhqg4lH:-NpE5wT1-UZPh9UEoky4:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/1763f9d158847d2e6f7e4b75090e3c91209c1f6d/crates/blockifier/src/block_execution.rs#L15)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please separate this change to its own PR; it's unrelated to the `pre_process` change.
</blockquote></details>

done
___
*[`crates/blockifier/src/block_execution.rs` line 15 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Np-_Wx76dQXMza_iQfN:-NpE5xzI-29N_KUfTfVk:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/1763f9d158847d2e6f7e4b75090e3c91209c1f6d/crates/blockifier/src/block_execution.rs#L15)):*
> ```XML
> pub mod test;
> 
> pub struct BlockNumberAndHash {
> ```

done
___
*[`crates/blockifier/src/block_execution.rs` line 17 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Np-_Zv80H0VUOgFu_Vx:-NpE5vq6DEJn2Wwisvhr:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/1763f9d158847d2e6f7e4b75090e3c91209c1f6d/crates/blockifier/src/block_execution.rs#L17)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

If `hash` isn't taken.
</blockquote></details>

done
___
*[`crates/blockifier/src/block_execution.rs` line 21 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1349#-Np-_fgD6m0Siec_xDsr:-NpE5zT758tL7Cj-lfNv:b-ppoeus) ([raw file](https://github.com/starkware-libs/blockifier/blob/1763f9d158847d2e6f7e4b75090e3c91209c1f6d/crates/blockifier/src/block_execution.rs#L21)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Should the regular c-tor remain `pub`lic?
</blockquote></details>

yes because the native_blockifier uses it


<!-- Sent from Reviewable.io -->

2024-01-28 09:40 UTC, closed without merging

2024-01-28 09:40 UTC, Yael-Starkware commented
This PR was split to 3 separate PRs