feat(fee): adding a slope parameters to the os resources
starkware-libs/blockifier pull request #1362
Opened 2024-01-22 09:22 UTC by noaov1

2024-01-22 11:03 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: 0 of 7 files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/fee/os_resources.rs` line 247 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Nokp1MPAt5R-3CUxcQf:-Nokp1MQ3y_qXh00CTld:b-n9xuy6) ([raw file](https://github.com/starkware-libs/blockifier/blob/63a73bd5c633e7cee26273c38ac6c46cbda6a0ce/crates/blockifier/src/fee/os_resources.rs#L247)):*
> ```XML
>                     "n_memory_holes": 0,
>                     "n_steps": 0
>                 }
> ```

I set the numbers to zero so tests will not fail. Next PR I will set the correct numbers + fix tests.



_Code quote:_
```XML
                "Slope": {
                    "builtin_instance_counter": {
                        "pedersen_builtin": 0,
                        "range_check_builtin": 0
                    },
                    "n_memory_holes": 0,
                    "n_steps": 0
                }
```


<!-- Sent from Reviewable.io -->

2024-01-25 11:38 UTC, elintul requested changes
> Reviewed 2 of 4 files at r1, 1 of 5 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: all files reviewed, 10 unresolved discussions (waiting on @MohammadNassar1, @noaov1, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-PA6s6frYRPH2_yRc:-Np-PA6s6frYRPH2_yRd:b-blf23x) (no related file):*
How come both slope and constant are VM resources? I think I'm missing something.

___
___
*[`crates/blockifier/src/fee/os_resources.rs` line 232 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-OQKL9xhfzIXVnX_5:-Np-OQKL9xhfzIXVnX_6:b-5scqpu) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/fee/os_resources.rs#L232)):*
> ```XML
>         "execute_txs_inner": {
>             "Declare": {
>                     "Constant": {
> ```

How come it's not in the same indentation as "Slope"?



_Code quote:_
```XML
"Constant": {
```
___
*[`crates/blockifier/src/fee/os_resources.rs` line 250 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-OXKnE4dT_xORrqmM:-Np-OXKnE4dT_xORrqmN:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/fee/os_resources.rs#L250)):*
> ```XML
>             },
>                 "DeployAccount": {
>                 "Constant": {
> ```





_Suggestion:_
```XML
            "DeployAccount": {
                "Constant": {
```
___
*[`crates/blockifier/src/fee/os_resources.rs` line 268 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-O_uh2VIva8flSJly:-Np-O_uh2VIva8flSJlz:b-k02u8i) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/fee/os_resources.rs#L268)):*
> ```XML
>             },
>                 "InvokeFunction": {
>                     "Constant": {
> ```

Please make sure tab is four characters throughout the file, format the file using a text editor.



_Code quote:_
```XML
                "InvokeFunction": {
                    "Constant": {
```
___
*[`crates/blockifier/src/fee/os_usage.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-OnK41RkjQzN27LRC:-Np-OnK41RkjQzN27LRD:b-2rwxmq) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/fee/os_usage.rs#L29)):*
> ```XML
>     fn from_str(resources_role: &str) -> Result<Self, Self::Err> {
>         match resources_role {
>             "Constant" | "CONSTANT" => Ok(ResourcesRole::Constant),
> ```

Why both cases?



_Code quote:_
```XML
"Constant" | "CONSTANT"
```
___
*[`crates/blockifier/src/fee/os_usage.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-PPQb98Cd-QxhsO1w:-Np-PPQb98Cd-QxhsO1x:b-6qe881) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/fee/os_usage.rs#L49)):*
> ```XML
> 
> impl OsResources {
>     fn resources_for_tx_type_by_resource_role(
> ```

Consider returning a struct (slope + constant).



_Code quote:_
```XML
resources_for_tx_type_by_resource_role
```
___
*[`crates/blockifier/src/fee/os_usage.rs` line 62 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-PLioBFRPNoglv4VB:-Np-PLioBFRPNoglv4VC:b-r8l1wf) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/fee/os_usage.rs#L62)):*
> ```XML
> 
>     pub fn resources_for_tx_type(
>         &self,
> ```

Not in use?



_Code quote:_
```XML
&self,
```
___
*[`crates/blockifier/src/fee/os_usage_test.rs` line 35 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-PaXHE17NclOR_Odo:-Np-PaXHE17NclOR_Odp:b-fecszp) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/fee/os_usage_test.rs#L35)):*
> ```XML
>     let tx_resources =
>         OS_RESOURCES.execute_txs_inner.values().flat_map(|resources| resources.values());
>     for resources in OS_RESOURCES.execute_syscalls.values().chain(tx_resources) {
> ```

Explain this change?



_Code quote:_
```XML
    let tx_resources =
        OS_RESOURCES.execute_txs_inner.values().flat_map(|resources| resources.values());
    for resources in OS_RESOURCES.execute_syscalls.values().chain(tx_resources) {
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 111 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-PGanAvMffWg3P6rm:-Np-PGanAvMffWg3P6rn:b-v53drf) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/transaction/errors.rs#L111)):*
> ```XML
>     UnknownTransactionType(String),
>     #[error("Unsupported resources role: {0}")]
>     UnknownResourcesRole(String),
> ```

Keep alphabetized.



_Code quote:_
```XML
UnknownResourcesRole
```


<!-- Sent from Reviewable.io -->

2024-01-27 19:18 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: 4 of 7 files reviewed, 6 unresolved discussions (waiting on @elintul, @giladchase, @MohammadNassar1, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-PA6s6frYRPH2_yRc:-Np5fUOx8FyBk9HvijqD:b9pteor) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How come both slope and constant are VM resources? I think I'm missing something.
</blockquote></details>

It is a vector. For each resource `r` we have a `r_0 + r_m * calldata_length`, where `r_0` is the constant and `r_m` is the slope (for this resource).  In total: `additional_os_resources = vm_resources_0 + slope * calldata_length`.

___
___
*[`crates/blockifier/src/fee/os_usage.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-OnK41RkjQzN27LRC:-Np5gzpf4rzm5BL46R07:b4kfa3q) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/fee/os_usage.rs#L29)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why both cases?
</blockquote></details>

Good question. I followed the implantation of [TransactionType](https://github.com/starkware-libs/blockifier/blob/94ee1a7058a7806ee59a39c578420ff6df5c2a9f/crates/blockifier/src/transaction/transaction_types.rs#L19).
I think it is because in the python file we use capital letters. I removed for now (will check with @giladchase what will be the format).
___
*[`crates/blockifier/src/fee/os_usage.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-PPQb98Cd-QxhsO1w:-Np5jcD2Dz3dniG_drwQ:bxn3flk) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/fee/os_usage.rs#L49)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider returning a struct (slope + constant).
</blockquote></details>

Q- Then I will have to repeat the extraction code, no?



_Code snippet:_
```XML
self.execute_txs_inner
            .get(tx_type)
            .unwrap_or_else(|| panic!("should contain transaction type '{tx_type:?}'."))
            .get(resources_role)
            .unwrap_or_else(|| panic!("should contain constant resources '{resources_role:?}'."))
```
___
*[`crates/blockifier/src/fee/os_usage.rs` line 62 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-PLioBFRPNoglv4VB:-Np5kolB2IOB14aZ8L2m:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/fee/os_usage.rs#L62)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not in use?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/os_usage_test.rs` line 35 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-PaXHE17NclOR_Odo:-Np5hul-BIxewF4cBvxz:bj0b27j) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/fee/os_usage_test.rs#L35)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Explain this change?
</blockquote></details>

Now, `execute_txs_inner` is a map of maps, so to extract the values I needed to flatten the second map.


<!-- Sent from Reviewable.io -->

2024-01-28 05:41 UTC, elintul requested changes
> Reviewed 1 of 3 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @giladchase, @MohammadNassar1, @noaov1, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-PA6s6frYRPH2_yRc:-NpD_GqaC88j-Fcc9MO0:byro49i) (no related file):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It is a vector. For each resource `r` we have a `r_0 + r_m * calldata_length`, where `r_0` is the constant and `r_m` is the slope (for this resource).  In total: `additional_os_resources = vm_resources_0 + slope * calldata_length`.
</blockquote></details>

Consider shortly documenting this (sorry if you already did and I missed it): that there's constant calldata-related work done for each transaction, and then additional work done per each felt in the calldata.

___


<!-- Sent from Reviewable.io -->

2024-01-28 08:45 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @elintul, @giladchase, @MohammadNassar1, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-PA6s6frYRPH2_yRc:-NpEEkIR3sSqxWml7KkX:b-qpatb6) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider shortly documenting this (sorry if you already did and I missed it): that there's constant calldata-related work done for each transaction, and then additional work done per each felt in the calldata.
</blockquote></details>

Done. WDYT?

___


<!-- Sent from Reviewable.io -->

2024-01-28 09:31 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/os_usage.rs` line 19 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-NpEP3bV57McehvpQa7l:-NpEP3bW7sKXFY6sRgBg:b-6ciro0) ([raw file](https://github.com/starkware-libs/blockifier/blob/e793c9ebc7760de947ccbf7a06e8a9214873e884/crates/blockifier/src/fee/os_usage.rs#L19)):*
> ```XML
> 
> #[derive(Clone, Copy, Debug, Deserialize, EnumIter, Eq, Hash, PartialEq)]
> pub enum ResourcesRole {
> ```

Alphabetize? Also in the `match` below.



_Code quote:_
```XML
ResourcesRole
```


<!-- Sent from Reviewable.io -->

2024-01-29 08:01 UTC, elintul reviewed
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/os_resources.rs` line 231 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-NpFEX9QA3y8IYjT58nq:-NpFEX9REBK6Syq8Ru5N:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e793c9ebc7760de947ccbf7a06e8a9214873e884/crates/blockifier/src/fee/os_resources.rs#L231)):*
> ```XML
>         },
>         // For each resource r, a transaction consumes r according to following formula:
>         // r_0 + r_m * calldata_length, where r_0 is a constant and r_m is the calldata factor.
> ```





_Suggestion:_
```XML
        // For each transaction the OS uses a constant amount of VM resources, and an
        // additional variable amount that depends on the calldata length.
```
___
*[`crates/blockifier/src/fee/os_resources.rs` line 242 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-NpFETusAKmm-ui3yDnl:-NpFETusAKmm-ui3yDnm:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e793c9ebc7760de947ccbf7a06e8a9214873e884/crates/blockifier/src/fee/os_resources.rs#L242)):*
> ```XML
>                     "n_steps": 2843
>                 },
>                 "CallDataFactor": {
> ```





_Suggestion:_
```XML
Calldata
```


<!-- Sent from Reviewable.io -->

2024-01-29 08:52 UTC, Yoni-Starkware reviewed
> Reviewed 2 of 4 files at r6, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/fee/os_usage.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-PPQb98Cd-QxhsO1w:-NpJOxb_-b7m7SJp2g5m:bsjup8e) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/fee/os_usage.rs#L49)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Q- Then I will have to repeat the extraction code, no?
</blockquote></details>

How about using a simple, nameless tuple? 
It is okay IMO to assume the natural order `a_0 + a_1 * x + a_2 * x**2...`


<!-- Sent from Reviewable.io -->

2024-01-29 08:53 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/fee/os_usage.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-PPQb98Cd-QxhsO1w:-NpJQ9bk3sH255cbHhQV:buf8nso) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/fee/os_usage.rs#L49)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

How about using a simple, nameless tuple? 
It is okay IMO to assume the natural order `a_0 + a_1 * x + a_2 * x**2...`
</blockquote></details>

And then `resources_vector_for_tx_type`


<!-- Sent from Reviewable.io -->

2024-01-29 09:09 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/fee/os_usage.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-PPQb98Cd-QxhsO1w:-NpJTC9SE7YQ2mrV2RK1:b2czbft) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/fee/os_usage.rs#L49)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

And then `resources_vector_for_tx_type`
</blockquote></details>

Or, as Elin said, a struct:
```rust
execute_txs_inner: HashMap<TransactionType, HashMap<ResourcesRole, VmExecutionResources>>,
```
-->
```
execute_txs_inner: HashMap<TransactionType, ResourcesVector>,
```
and get it with a single dict access.


<!-- Sent from Reviewable.io -->

2024-01-30 06:44 UTC, elintul requested changes
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: all files reviewed, 6 unresolved discussions (waiting on @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/os_usage.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-PPQb98Cd-QxhsO1w:-NpO5nF-C-KhISS6h65Q:bb7867z) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/fee/os_usage.rs#L49)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Or, as Elin said, a struct:
```rust
execute_txs_inner: HashMap<TransactionType, HashMap<ResourcesRole, VmExecutionResources>>,
```
-->
```
execute_txs_inner: HashMap<TransactionType, ResourcesVector>,
```
and get it with a single dict access.
</blockquote></details>

Yup.


<!-- Sent from Reviewable.io -->

2024-01-30 09:58 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/os_usage.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-PPQb98Cd-QxhsO1w:-NpO5GZ_7aaC60CTpBF4:bf4qutj) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/fee/os_usage.rs#L49)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Yup.
</blockquote></details>

Oh, I see. Like. Done


<!-- Sent from Reviewable.io -->

2024-01-30 10:30 UTC, elintul reviewed
> Reviewed 1 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/fee/os_usage.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-PPQb98Cd-QxhsO1w:-NpOukHc8z1tuFjQJhUG:b32vhw) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/fee/os_usage.rs#L49)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Oh, I see. Like. Done
</blockquote></details>

:)


<!-- Sent from Reviewable.io -->

2024-01-30 11:01 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 4 files at r6, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/fee/os_usage.rs` line 19 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-NpP0me73QvCuZcVTQO_:-NpP0me73QvCuZcVTQOa:b-vijckn) ([raw file](https://github.com/starkware-libs/blockifier/blob/cea8bbfb718a22019739d42655b298a403b1eda0/crates/blockifier/src/fee/os_usage.rs#L19)):*
> ```XML
> pub struct ResourcesVector {
>     pub calldata_factor: VmExecutionResources,
>     pub constant: VmExecutionResources,
> ```

Swap order?



_Code quote:_
```XML
    pub calldata_factor: VmExecutionResources,
    pub constant: VmExecutionResources,
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 111 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-NpP0rG0-GaVeHFBwGWv:-NpP0rG0-GaVeHFBwGWw:ba3dfna) ([raw file](https://github.com/starkware-libs/blockifier/blob/cea8bbfb718a22019739d42655b298a403b1eda0/crates/blockifier/src/transaction/errors.rs#L111)):*
> ```XML
> pub enum ParseError {
>     #[error("Unsupported resources role: {0}")]
>     UnknownResourcesRole(String),
> ```

Remove?



_Code quote:_
```XML
    #[error("Unsupported resources role: {0}")]
    UnknownResourcesRole(String),
```


<!-- Sent from Reviewable.io -->

2024-01-30 11:42 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/os_usage.rs` line 19 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-NpP0me73QvCuZcVTQO_:-NpPA4B62lU79QrHY8wM:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cea8bbfb718a22019739d42655b298a403b1eda0/crates/blockifier/src/fee/os_usage.rs#L19)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Swap order?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/errors.rs` line 111 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-NpP0rG0-GaVeHFBwGWv:-NpPAEFlE_AIaJ6Iovnf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cea8bbfb718a22019739d42655b298a403b1eda0/crates/blockifier/src/transaction/errors.rs#L111)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-30 12:26 UTC, elintul requested changes
> Reviewed 1 of 3 files at r8, 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: all files reviewed, 5 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/fee/os_usage.rs` line 17 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-NpPJvte1Rn24MkYgONz:-NpPJvtfBErOvlj9bLvM:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/22d482164d8e70418a58daa3de2df96a0f215caa/crates/blockifier/src/fee/os_usage.rs#L17)):*
> ```XML
> 
> #[derive(Debug, Deserialize)]
> pub struct ResourcesVector {
> ```





_Suggestion:_
```XML
TransactionOsResources
```
___
*[`crates/blockifier/src/fee/os_usage.rs` line 33 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-NpPK0U0-pwS5MttbGck:-NpPK0U0-pwS5MttbGcl:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/22d482164d8e70418a58daa3de2df96a0f215caa/crates/blockifier/src/fee/os_usage.rs#L33)):*
> ```XML
> 
> impl OsResources {
>     fn resources_vector_for_tx_type(&self, tx_type: &TransactionType) -> &ResourcesVector {
> ```





_Suggestion:_
```XML
os_resources_for_tx_type
```
___
*[`crates/blockifier/src/fee/os_usage.rs` line 45 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-NpPKCdn2-hRFWs7RERR:-NpPKCdn2-hRFWs7RERS:bjhdssi) ([raw file](https://github.com/starkware-libs/blockifier/blob/22d482164d8e70418a58daa3de2df96a0f215caa/crates/blockifier/src/fee/os_usage.rs#L45)):*
> ```XML
>     ) -> VmExecutionResources {
>         let resources_vector = self.resources_vector_for_tx_type(tx_type);
>         &resources_vector.constant + &(&(resources_vector.calldata_factor) * calldata_length)
> ```

Any chance to simplify the dereferencing here?



_Code quote:_
```XML
&(&(resources_vector.calldata_factor)
```
___
*[`crates/blockifier/src/fee/os_usage_test.rs` line 35 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-PaXHE17NclOR_Odo:-NpPKId8BEeY7TEz-WFD:bnr7xxd) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/fee/os_usage_test.rs#L35)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Now, `execute_txs_inner` is a map of maps, so to extract the values I needed to flatten the second map.
</blockquote></details>

Please use a more idiomatic loop.


<!-- Sent from Reviewable.io -->

2024-01-30 12:43 UTC, elintul reviewed
> Reviewed 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: all files reviewed, 5 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)



<!-- Sent from Reviewable.io -->

2024-01-30 14:03 UTC, Yoni-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/fee/os_usage.rs` line 17 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-NpPJvte1Rn24MkYgONz:-NpPfJfCEFngASeYN26m:b7gqczj) ([raw file](https://github.com/starkware-libs/blockifier/blob/22d482164d8e70418a58daa3de2df96a0f215caa/crates/blockifier/src/fee/os_usage.rs#L17)):*
> ```XML
> 
> #[derive(Debug, Deserialize)]
> pub struct ResourcesVector {
> ```

No need to restrict the name IMO, I'm planning to use this for other linear resources


<!-- Sent from Reviewable.io -->

2024-01-30 17:09 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: all files reviewed, 5 unresolved discussions (waiting on @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/os_usage.rs` line 17 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-NpPJvte1Rn24MkYgONz:-NpQL6WKAOCPc-P7xDaM:b81wv06) ([raw file](https://github.com/starkware-libs/blockifier/blob/22d482164d8e70418a58daa3de2df96a0f215caa/crates/blockifier/src/fee/os_usage.rs#L17)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

No need to restrict the name IMO, I'm planning to use this for other linear resources
</blockquote></details>

Okay, can you elaborate?


<!-- Sent from Reviewable.io -->

2024-01-31 08:32 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: 3 of 7 files reviewed, 4 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/os_usage.rs` line 33 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-NpPK0U0-pwS5MttbGck:-NpQ39ar1fMR8SHeA4An:b-5ektmh) ([raw file](https://github.com/starkware-libs/blockifier/blob/22d482164d8e70418a58daa3de2df96a0f215caa/crates/blockifier/src/fee/os_usage.rs#L33)):*
> ```XML
> 
> impl OsResources {
>     fn resources_vector_for_tx_type(&self, tx_type: &TransactionType) -> &ResourcesVector {
> ```

How does it indicate that we return the vector? It may be confusing with the method below `resources_for_tx_type`, no?
___
*[`crates/blockifier/src/fee/os_usage.rs` line 45 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-NpPKCdn2-hRFWs7RERR:-NpQ7qpr5Ku6n7jQbaF8:b-qiaefg) ([raw file](https://github.com/starkware-libs/blockifier/blob/22d482164d8e70418a58daa3de2df96a0f215caa/crates/blockifier/src/fee/os_usage.rs#L45)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Any chance to simplify the dereferencing here?
</blockquote></details>

It is not possible :( We only have implementation of `add` for `&ExecutionResources`.
___
*[`crates/blockifier/src/fee/os_usage_test.rs` line 35 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-Np-PaXHE17NclOR_Odo:-NpQ2qVnAErGCKPkTB2v:b-7zi8ni) ([raw file](https://github.com/starkware-libs/blockifier/blob/6d108fa70dc927a92cd9d5ee2d0e7610292505ff/crates/blockifier/src/fee/os_usage_test.rs#L35)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please use a more idiomatic loop.
</blockquote></details>

WDYT?


<!-- Sent from Reviewable.io -->

2024-01-31 15:04 UTC, elintul approved these changes
> Reviewed 2 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/fee/os_usage.rs` line 33 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-NpPK0U0-pwS5MttbGck:-NpUnn2HBoFGzbxI1udC:b-yiwxin) ([raw file](https://github.com/starkware-libs/blockifier/blob/22d482164d8e70418a58daa3de2df96a0f215caa/crates/blockifier/src/fee/os_usage.rs#L33)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

How does it indicate that we return the vector? It may be confusing with the method below `resources_for_tx_type`, no?
</blockquote></details>

The fact that it's plural is enough, IMO.
___
*[`crates/blockifier/src/fee/os_usage.rs` line 17 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-NpUnZA4BngMcgKcB_k6:-NpUnZA4BngMcgKcB_k7:b-m9p2pa) ([raw file](https://github.com/starkware-libs/blockifier/blob/f31cfd4799ca020ac65faa73faa469dd8db11c57/crates/blockifier/src/fee/os_usage.rs#L17)):*
> ```XML
> 
> #[derive(Debug, Deserialize)]
> pub struct ResourcesVector {
> ```

The fact that it's a vector is embedded in the fact that it's a struct.



_Suggestion:_
```XML
Resources
```


<!-- Sent from Reviewable.io -->

2024-01-31 15:12 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/fee/os_usage.rs` line 17 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-NpUnZA4BngMcgKcB_k6:-NpV3mSvCMwBIvfivroK:brmh2wz) ([raw file](https://github.com/starkware-libs/blockifier/blob/f31cfd4799ca020ac65faa73faa469dd8db11c57/crates/blockifier/src/fee/os_usage.rs#L17)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

The fact that it's a vector is embedded in the fact that it's a struct.
</blockquote></details>

`ResourcesParams`? `Resources` can be too generic and might confusing. WDYT?


<!-- Sent from Reviewable.io -->

2024-01-31 15:41 UTC, elintul approved these changes
> Reviewed 2 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/fee/os_usage.rs` line 17 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-NpUnZA4BngMcgKcB_k6:-NpVA_Q_CQFInDB7l948:bb7867z) ([raw file](https://github.com/starkware-libs/blockifier/blob/f31cfd4799ca020ac65faa73faa469dd8db11c57/crates/blockifier/src/fee/os_usage.rs#L17)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

`ResourcesParams`? `Resources` can be too generic and might confusing. WDYT?
</blockquote></details>

Yup.


<!-- Sent from Reviewable.io -->

2024-01-31 16:34 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1362#-:-NpVMmp2CzWGaasvS2-G:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-01-31 16:36 UTC, merged