Gilad/account tx info
starkware-libs/blockifier pull request #1365
Opened 2024-01-22 13:53 UTC by giladchase

2024-01-23 10:10 UTC, elintul reviewed
> Reviewed 1 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 1 of 23 files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-01-25 13:33 UTC, noaov1 requested changes
> Reviewed 5 of 23 files at r1, 2 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 7 of 23 files reviewed, 5 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/context.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-c0wW8ujRX7ZjNfDD:-Np-c0wW8ujRX7ZjNfDE:b2tv2q8) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/context.rs#L9)):*
> ```XML
> #[derive(Clone, Debug)]
> pub struct TransactionContext {
>     pub block_context: BlockContext,
> ```

Does it make sense?



_Suggestion:_
```XML
    pub block_context: Arc<BlockContext>,
```
___
*[`crates/blockifier/src/context.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-YDXg4UEtADxPnDQD:-Np-YDXg4UEtADxPnDQE:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/context.rs#L41)):*
> ```XML
>     // TODO(Gilad): since fee_type is comes from TransactionInfo, we can make move this method into
>     // TransactionContext, which has both the chain_info (through BlockContext) and the tx_info.
>     // That is, add to BlockContext with the signature `pub fn fee_token_address(&self)`.
> ```





_Suggestion:_
```XML
    // TODO(Gilad): since fee_type comes from TransactionInfo, we can move this method into
    // TransactionContext, which has both the chain_info (through BlockContext) and the tx_info.
    // That is, add to BlockContext with the signature `pub fn fee_token_address(&self)`.
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-Zmhq1lGKKJ5W8CpN:-Np-Zmhq1lGKKJ5W8CpO:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/test_utils/struct_impls.rs#L42)):*
> ```XML
>     }
> 
>     pub fn execute_directly_given_account_context(
> ```





_Suggestion:_
```XML
pub fn execute_directly_given_tx_info(
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-_Fh445TBwQ6q3Atg:-Np-_Fh445TBwQ6q3Ath:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/test_utils/struct_impls.rs#L69)):*
> ```XML
>     }
> 
>     pub fn execute_directly_given_account_context_in_validate_mode(
> ```





_Suggestion:_
```XML
pub fn execute_directly_given_tx_info_in_validate_mode(
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-_UIk5ooxjuCp2FDu:-Np-_UIk5ooxjuCp2FDv:bcs1os8) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/transaction/transactions.rs#L70)):*
> ```XML
>     }
> 
>     // FIXME: not transactional, maybe remove from trait.
> ```

Can you please elaborate?



_Code quote:_
```XML
    // FIXME: not transactional, maybe remove from trait.
```


<!-- Sent from Reviewable.io -->

2024-01-25 13:54 UTC, elintul requested changes
> Reviewed 13 of 23 files at r1, 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: all files reviewed, 14 unresolved discussions (waiting on @giladchase)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 144 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-qg2VAdxkzddtphn2:-Np-qg2VAdxkzddtphn3:b-oxunkh) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/execution/entry_point.rs#L144)):*
> ```XML
> #[derive(Debug)]
> pub struct EntryPointExecutionContext {
>     pub tx_context: Arc<TransactionContext>,
> ```

Consider shortly documenting the use of `Arc`.



_Code quote:_
```XML
pub tx_context: Arc<TransactionContext>
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 201 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-quzdDcXmK0wjBaJz:-Np-quzdDcXmK0wjBaK-:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/execution/entry_point.rs#L201)):*
> ```XML
>         limit_steps_by_resources: bool,
>     ) -> TransactionExecutionResult<usize> {
>         let block_context = &tx_context.block_context;
> ```





_Suggestion:_
```XML
let block_info = &tx_context.block_context.block_info;
```
___
*[`crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs` line 312 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-r7Da2yTwxa8qpFDM:-Np-r7Da2yTwxa8qpFDN:b-mtakka) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs#L312)):*
> ```XML
>     ) -> DeprecatedSyscallResult<Relocatable> {
>         let tx_signature_start_ptr = self.get_or_allocate_tx_signature_segment(vm)?;
>         let TransactionContext { block_context, tx_info } = self.context.tx_context.as_ref();
> ```

Coolio!
Did you unpack where possible?



_Code quote:_
```XML
let TransactionContext { block_context, tx_info }
```
___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 399 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-rJd73w87ezD6LBGp:-Np-rJd73w87ezD6LBGq:bppazow) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L399)):*
> ```XML
>     syscall_handler: &mut DeprecatedSyscallHintProcessor<'_>,
> ) -> DeprecatedSyscallResult<GetBlockNumberResponse> {
>     // TODO(Yoni, 1/5/2024): disable for validate.
> ```

:(
Maybe start with getters on the hint processors?
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 471 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-rRLd4EzzS1teEkoL:-Np-rRLd4EzzS1teEkoM:b-jodhs1) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/execution/syscalls/hint_processor.rs#L471)):*
> ```XML
>         let (tx_signature_start_ptr, tx_signature_end_ptr) =
>             &self.allocate_data_segment(vm, tx_info.signature().0)?;
>         let tx_info = tx_info.clone();
> ```

Must we?



_Code quote:_
```XML
let tx_info = tx_info.clone();
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-rjQB6NR9xhYjRZ_l:-Np-rjQB6NR9xhYjRZ_m:bteujxb) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/fee/actual_cost.rs#L27)):*
> ```XML
> 
> impl ActualCost {
>     pub fn builder_for_l1_handler<'a>(
> ```

Why suddenly needed?



_Code quote:_
```XML
<'a>
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-roJ23_pcSeohH4WY:-Np-roJ23_pcSeohH4WZ:b-fhtbn7) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/fee/actual_cost.rs#L60)):*
> ```XML
>         Self {
>             sender_address: Some(tx_context.tx_info.sender_address()),
>             account_tx_context: tx_context,
> ```

Rename? Also additional such arguments.



_Code quote:_
```XML
account_tx_context
```
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-s-UZ6ZH7efZupV48:-Np-s-U_0ymWLw4lD3j6:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/fee/fee_checks.rs#L91)):*
> ```XML
>         let ActualCost { actual_fee, actual_resources } = actual_cost;
> 
>         let versioned_constants = &tx_context.block_context.versioned_constants;
> ```





_Suggestion:_
```XML
        let ActualCost { actual_fee, actual_resources } = actual_cost;
        let versioned_constants = &tx_context.block_context.versioned_constants;
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-smo5-s614BjCZC5C:-Np-smo5-s614BjCZC5D:bwwbecg) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/test_utils/struct_impls.rs#L48)):*
> ```XML
>         limit_steps_by_resources: bool,
>     ) -> EntryPointExecutionResult<CallInfo> {
>         let block_context = BlockContext::create_for_testing();
> ```

Pass directly, x2.



_Code quote:_
```XML
BlockContext::create_for_testing()
```


<!-- Sent from Reviewable.io -->

2024-01-28 07:20 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 20 of 23 files reviewed, 13 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/context.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-c0wW8ujRX7ZjNfDD:-NpDovDh9K3F3ftANX16:b1wyiuv) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/context.rs#L9)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Does it make sense?
</blockquote></details>

Good idea! But i'm wondering about how friendly it will be to force the API users to create an Arc :thinking:  It's an implementation detail, which they might not support (no-std users come to mind).

How about we make `BlockContext` a trait that requires `Clone` implementation, and implement it as `ArcBlockContext`?
That way we'll get the Arc and users can also use it, but can also opt out by not using our Arc implementation, and instead use regular Clones.
(Everything will be documented of course.)

WDYT? 
___
*[`crates/blockifier/src/context.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-YDXg4UEtADxPnDQD:-NpDkGVC9VDqawmPkSrQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/context.rs#L41)):*
> ```XML
>     // TODO(Gilad): since fee_type is comes from TransactionInfo, we can make move this method into
>     // TransactionContext, which has both the chain_info (through BlockContext) and the tx_info.
>     // That is, add to BlockContext with the signature `pub fn fee_token_address(&self)`.
> ```

Done.
___
*[`crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs` line 312 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-r7Da2yTwxa8qpFDM:-NpDrEGi1HLQ-ZivXm1V:bgqmhfm) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs#L312)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Coolio!
Did you unpack where possible?
</blockquote></details>

Yep, up to this point, though more potential usages might free up when moving up the stack, i'll go over everything onces we're done and hunt for more usages (we already put a monday task for it)


<!-- Sent from Reviewable.io -->

2024-01-28 07:20 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 20 of 23 files reviewed, 12 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 399 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-rJd73w87ezD6LBGp:-NpDwFf7AwT48d6p70Pc:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L399)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

:(
Maybe start with getters on the hint processors?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-01-28 07:46 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 18 of 23 files reviewed, 11 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 471 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-rRLd4EzzS1teEkoL:-NpDwiYn3i2w13CrxF7H:bgzt1bm) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/execution/syscalls/hint_processor.rs#L471)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Must we?
</blockquote></details>

Done.

Had to change some stuff though to make this work without any clones (the only clone there is of tx_context, which is an Arc :muscle: explanation below):
(I can undo and put in a separate PR, it's a bit out of scope here maybe?)

- The `clone()` (of the Arc) is needed due to `allocate_data_segment` requiring &mut **self**: if we'd have defined
```rust
let tx_info = &self.context.tx_context.tx_info; // & is bound to self
```
 then the reference will be bound to `self` (because it is a field on self), which would block `allcoate_data_segment` from taking `&mut self`. After the clone, we have:
```rust
let tx_info = &self.context.tx_context.clone().tx_info; // & is bound to the cloned tx_context.clone()
````
which bounds the & to the cloned tx_context, which does not prevent `allocate_data_segment` from `&mut`ting `self`.

- Made allocate_data_segment take `&[T]` instead of `Vec<T>`: ownership not needed, also `&[T]` is better than `&Vec<T>` [due to deref coercion](https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/style.md#useless-types). 

- This allowed one `to_vec` call to be removed (saves an allocation).

- The collect statement in the current module required an explicit `Vec<StarkFelt>` annotation: otherwise collect would type-infer `&[StarkFelt]`, which is impossible there since this array is dynamically generated and it's size is not known at compile time. (This isn't a new allocation, previously it just type-inferred a `Vec` implicitly, before we changed the function signature). I added a PR comment there as well.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 342 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-NpE-Hss-xJd5lE38Kex:-NpE-Hst-87E5hd4M9n0:bflk09h) ([raw file](https://github.com/starkware-libs/blockifier/blob/078220f1a7b8b1836c5b691e0036f23856eddb6e/crates/blockifier/src/execution/syscalls/hint_processor.rs#L342)):*
> ```XML
>                 ]
>             })
>             .collect();
> ```

Without type annotation it infers `&[StarkFelt]`, which fails compilation due to this array being dynamically generated.
This is due to `allocate_data_segment` now requiring the more useful `&[StarkFelt]` over `Vec<StarkFelt>`.



_Code quote:_
```XML
        let flat_resource_bounds: Vec<StarkFelt> = context
            .resource_bounds
            .0
            .iter()
            })
            .collect();
```


<!-- Sent from Reviewable.io -->

2024-01-28 07:57 UTC, elintul reviewed
> Reviewed 1 of 23 files at r1, 3 of 3 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 22 of 23 files reviewed, 12 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 145 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-NpE3CDn2vOc15BI7dUB:-NpE3CDn2vOc15BI7dUC:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/078220f1a7b8b1836c5b691e0036f23856eddb6e/crates/blockifier/src/execution/entry_point.rs#L145)):*
> ```XML
> pub struct EntryPointExecutionContext {
>     // EntryPoints can recursively create other EntryPoints, we use `Arc` to avoid the clone of
>     // this potentially large object.
> ```





_Suggestion:_
```XML
    // We use `Arc` to avoid the clone of this potentially large object, as inner calls
    // are created during execution.
```
___
*[`crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs` line 312 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-r7Da2yTwxa8qpFDM:-NpE3PHP1L--yLZaXzNt:b-ucfknh) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs#L312)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Yep, up to this point, though more potential usages might free up when moving up the stack, i'll go over everything onces we're done and hunt for more usages (we already put a monday task for it)
</blockquote></details>

Thanks!
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 342 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-NpE-Hss-xJd5lE38Kex:-NpE3YGg5u90zH2IZdsX:buxpez0) ([raw file](https://github.com/starkware-libs/blockifier/blob/078220f1a7b8b1836c5b691e0036f23856eddb6e/crates/blockifier/src/execution/syscalls/hint_processor.rs#L342)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Without type annotation it infers `&[StarkFelt]`, which fails compilation due to this array being dynamically generated.
This is due to `allocate_data_segment` now requiring the more useful `&[StarkFelt]` over `Vec<StarkFelt>`.
</blockquote></details>

Can you elaborate more? What changed here?


<!-- Sent from Reviewable.io -->

2024-01-28 07:58 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 22 of 23 files reviewed, 12 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-rjQB6NR9xhYjRZ_l:-NpE2X6K9QMlVOHlT-7r:b-biqswr) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/fee/actual_cost.rs#L27)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why suddenly needed?
</blockquote></details>

Because it's getting an argument by reference (the Arc) and returning an value that contains a reference of the same type (ActualCostBuilder holds this arc as well).
The compiler can't decide in such cases if the lifetime to fill instead of the `'_` is the lifetime of the argument `tx_context` or the lifetime of the returned `ActualCostBuilder` itself (in our case it's the lifetime of the builder that matters).

Only half of this condition held previously: We did get `BlockContext` by reference as an argument, but `ActualCostBuilder` didn't hold a reference to it (only to other types, which weren't also passed as args).
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 60 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-roJ23_pcSeohH4WY:-NpE3pXMCpGzheWXxwD-:b-sygy0j) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/fee/actual_cost.rs#L60)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Rename? Also additional such arguments.
</blockquote></details>

Whoops i thought i caught all of them. Tnx!
Done (here and in fee_checks.rs).


<!-- Sent from Reviewable.io -->

2024-01-28 08:09 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 17 of 23 files reviewed, 11 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-Zmhq1lGKKJ5W8CpN:-NpE4LKoAGdfF7ECweQs:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/test_utils/struct_impls.rs#L42)):*
> ```XML
>     }
> 
>     pub fn execute_directly_given_account_context(
> ```

Done.
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-smo5-s614BjCZC5C:-NpE4ipr9NkZtQPrdhMI:b-3fas62) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/test_utils/struct_impls.rs#L48)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Pass directly, x2.
</blockquote></details>

To be sure i understand, you want me to pass blockContext from outside into this function?

This means adding a block_context fixture for every test that calls this function.

If we want to pass the entire tx_context from outside, it'll be an additional fixture + initializing the tx_context inside the test.
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-_Fh445TBwQ6q3Atg:-NpE6UC0B2Xt3VN5Yvf5:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/test_utils/struct_impls.rs#L69)):*
> ```XML
>     }
> 
>     pub fn execute_directly_given_account_context_in_validate_mode(
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-01-28 08:14 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 17 of 23 files reviewed, 11 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-_UIk5ooxjuCp2FDu:-NpE6w3R-5i0chofdw5r:b-7t5n3p) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/transaction/transactions.rs#L70)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please elaborate?
</blockquote></details>

Elin spotted it: unlike `execute` which executes and then commits/aborts based on the result (== "in a transactional manner), `execute_raw` only executes, and doesn't commit/abort, hence isn't "in a transactional manner".
It does say that the state may become corrupted, which is true, but the line on transactional probably isn't accurate.

RE removing from trait, not sure if that's necessary.


<!-- Sent from Reviewable.io -->

2024-01-28 08:21 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 17 of 23 files reviewed, 9 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 342 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-NpE-Hss-xJd5lE38Kex:-NpE7qBV6Rd2bHD_pOwp:b-eiaiui) ([raw file](https://github.com/starkware-libs/blockifier/blob/078220f1a7b8b1836c5b691e0036f23856eddb6e/crates/blockifier/src/execution/syscalls/hint_processor.rs#L342)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you elaborate more? What changed here?
</blockquote></details>

This follows from the next comment below. 

But in short: `allocate_data_segment` used to take a `Vec<StarkFelt>` argument, which the `collect` type-inferred correctly and generated the `Vec`.
Now that `allocate_data_segment` takes `&[StarkFelt]`, the `collect` infers `&[StarkFelt]` from the signature, and fails, cause it can't create it (`collect` can only generate owned collections).

Therefore we explicitly ask it to generate a `Vec<StarkFelt>`, which we then pass to the function as `&Vec<StarkFelt>` (that is deref-coerced automatically into `&[StarkFelt]`).


<!-- Sent from Reviewable.io -->

2024-01-28 09:36 UTC, elintul reviewed
> Reviewed 3 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 20 of 23 files reviewed, 10 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 466 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-NpEQ--n5tImVMV0lcNN:-NpEQ--n5tImVMV0lcNO:b7u96ry) ([raw file](https://github.com/starkware-libs/blockifier/blob/952adc1c1f4235469f83cee381769152fb29ee6a/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L466)):*
> ```XML
>     });
>     let result =
>         entry_point_call.execute_directly_given_tx_info(&mut state, tx_info, true).unwrap();
> ```

Give this a name, please.



_Code quote:_
```XML
true
```
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-smo5-s614BjCZC5C:-NpEQNP76nNTW38fiPjY:b-8qdtbb) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/test_utils/struct_impls.rs#L48)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

To be sure i understand, you want me to pass blockContext from outside into this function?

This means adding a block_context fixture for every test that calls this function.

If we want to pass the entire tx_context from outside, it'll be an additional fixture + initializing the tx_context inside the test.
</blockquote></details>

I meant, to lose the `block_context` variable.


<!-- Sent from Reviewable.io -->

2024-01-28 10:39 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 19 of 23 files reviewed, 9 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-smo5-s614BjCZC5C:-NpEdeMD2C5bQ7GTzhJm:b-4dr2og) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/test_utils/struct_impls.rs#L48)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I meant, to lose the `block_context` variable.
</blockquote></details>

Oh right, done


<!-- Sent from Reviewable.io -->

2024-01-29 07:27 UTC, elintul reviewed
> Reviewed 3 of 3 files at r6, 13 of 14 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 23 of 24 files reviewed, 7 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/fee/fee_test.rs` line 94 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-NpJ6AAW7CGv72X2n4yl:-NpJ6AAW7CGv72X2n4ym:bbqgdai) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe0dad094d7247d01df714bd5c1cecc1d7450046/crates/blockifier/src/fee/fee_test.rs#L94)):*
> ```XML
>     };
>     let report =
>         PostExecutionReport::new(&mut state, &block_context.to_tx_context(&tx), &actual_cost, true)
> ```

Give it a name?



_Code quote:_
```XML
true
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 70 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-_UIk5ooxjuCp2FDu:-NpJ6Hsq6WqTQ8dY2dSN:b6wr4ar) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/transaction/transactions.rs#L70)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Elin spotted it: unlike `execute` which executes and then commits/aborts based on the result (== "in a transactional manner), `execute_raw` only executes, and doesn't commit/abort, hence isn't "in a transactional manner".
It does say that the state may become corrupted, which is true, but the line on transactional probably isn't accurate.

RE removing from trait, not sure if that's necessary.
</blockquote></details>

Can you fix the existing comment instead?


<!-- Sent from Reviewable.io -->

2024-01-29 19:40 UTC, elintul reviewed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 22 of 24 files reviewed, 5 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-01-31 15:45 UTC, elintul reviewed
> Reviewed 7 of 34 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 16 of 44 files reviewed, 5 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-01-31 16:00 UTC, elintul reviewed
> Reviewed 4 of 34 files at r10, 2 of 26 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 13 of 44 files reviewed, 5 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-01-31 16:50 UTC, elintul requested changes
> Reviewed 1 of 8 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 10 of 44 files reviewed, 6 unresolved discussions (waiting on @giladchase and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-NpVQSc2EK18mhLqXIs7:-NpVQSc33vo_AybHJa7s:b81xx7n) (no related file):*
Bad `rebase`?

___


<!-- Sent from Reviewable.io -->

2024-01-31 16:53 UTC, elintul reviewed
> Reviewed 1 of 1 files at r8, 6 of 34 files at r10, 20 of 26 files at r11, 7 of 8 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @noaov1)



<!-- Sent from Reviewable.io -->

2024-01-31 16:53 UTC, elintul reviewed
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @noaov1)



<!-- Sent from Reviewable.io -->

2024-01-31 16:53 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-:-NpVRA8x-R_MMycAYP43:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @noaov1)



<!-- Sent from Reviewable.io -->

2024-01-31 16:55 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-NpVQSc2EK18mhLqXIs7:-NpVRUkUEY0Vgwneq3XF:b-896fix) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Bad `rebase`?
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2024-01-31 16:55 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: all files reviewed, 4 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-02-01 07:46 UTC, noaov1 reviewed
> Reviewed 1 of 23 files at r1, 1 of 3 files at r3, 1 of 1 files at r8, 3 of 34 files at r10, 2 of 26 files at r11, 1 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 42 of 44 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/context.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-c0wW8ujRX7ZjNfDD:-NpPGEm22zINInTKJRTx:bheqqqn) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/context.rs#L9)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Good idea! But i'm wondering about how friendly it will be to force the API users to create an Arc :thinking:  It's an implementation detail, which they might not support (no-std users come to mind).

How about we make `BlockContext` a trait that requires `Clone` implementation, and implement it as `ArcBlockContext`?
That way we'll get the Arc and users can also use it, but can also opt out by not using our Arc implementation, and instead use regular Clones.
(Everything will be documented of course.)

WDYT?
</blockquote></details>

Sounds good. I think users also use `EntryPointExecutionContext` (that contains an `Arc`). Let's talk offline (when running "only" one transaction at a time it's not that significant, I guess)
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 322 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-NpYY-mxARjexCxjNiST:-NpYY-mxARjexCxjNiSU:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/38af9685730b970dceca87019426607fbfa72096/crates/blockifier/src/execution/syscalls/hint_processor.rs#L322)):*
> ```XML
>         &mut self,
>         vm: &mut VirtualMachine,
>         context: &CurrentTransactionInfo,
> ```





_Suggestion:_
```XML
        tx_info: &CurrentTransactionInfo,
```


<!-- Sent from Reviewable.io -->

2024-02-01 10:57 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 41 of 44 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/context.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-Np-c0wW8ujRX7ZjNfDD:-NpZIEaFBAO07Jr43iki:b-h5arp3) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c2e2ffc1183b469998286569412076128568727/crates/blockifier/src/context.rs#L9)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Sounds good. I think users also use `EntryPointExecutionContext` (that contains an `Arc`). Let's talk offline (when running "only" one transaction at a time it's not that significant, I guess)
</blockquote></details>

How about i add it to monday in the concurrency board? we can talk about during the discussions then, since the assumption of "one tx at a time" will be broken soon...)


<!-- Sent from Reviewable.io -->

2024-02-01 11:03 UTC, noaov1 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 41 of 44 files reviewed, all discussions resolved (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-02-01 12:03 UTC, noaov1 approved these changes
> Reviewed 1 of 23 files at r1, 1 of 5 files at r5, 2 of 34 files at r10, 2 of 8 files at r12, 1 of 3 files at r13, 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 42 of 44 files reviewed, all discussions resolved (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-02-01 12:27 UTC, noaov1 approved these changes
> Reviewed 1 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 43 of 44 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 98 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-NpZb7bb4LkwRkrimkma:-NpZb7bb4LkwRkrimkmb:b-wrsx8n) ([raw file](https://github.com/starkware-libs/blockifier/blob/d1a4fe065d3da4e0857480b2650f151c1f41b1dc/crates/blockifier/src/fee/fee_utils.rs#L98)):*
> ```XML
>     block_context: &BlockContext,
>     fee_type: &FeeType,
> ) -> TransactionFeeResult<Fee> {
> ```

In another PR.



_Suggestion:_
```XML
pub fn calculate_tx_fee(
    resources: &ResourcesMapping,
    tx_context: &TransactionContext,
) -> TransactionFeeResult<Fee> {
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 207 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-NpZ_pMeEzg2bXCVbv6T:-NpZ_pMfBpkYtixYMngo:be5i2zi) ([raw file](https://github.com/starkware-libs/blockifier/blob/d1a4fe065d3da4e0857480b2650f151c1f41b1dc/crates/blockifier/src/fee/gas_usage.rs#L207)):*
> ```XML
> /// Return an estimated lower bound for the L1 gas on an account transaction.
> pub fn estimate_minimal_gas_vector(
>     tx_context: &TransactionContext,
> ```

Isn't `block_context` enough?



_Code quote:_
```XML
    tx_context: &TransactionContext,
```


<!-- Sent from Reviewable.io -->

2024-02-01 12:28 UTC, noaov1 approved these changes
> Reviewed 1 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)



<!-- Sent from Reviewable.io -->

2024-02-01 13:04 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: 39 of 44 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 245 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-NpZkgbZ8uS5G0B_zPp9:-NpZkgbZ8uS5G0B_zPpA:bpdclyw) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0a957e722d9da654c56170e8ad59c0b4e79fc77/crates/blockifier/src/execution/entry_point.rs#L245)):*
> ```XML
>                     );
>                     usize::MAX
>                 })
> ```

Looks like on main-v0.13.1 this test depends on this cast to be saturating in order to pass, so i had to do this in order to preserve the previous behavior.
@elintul should we task someone to investigate and fix this? 



_Code quote:_
```XML
                // FIXME: This is saturating in the python bootstrapping test. Fix the value so
                // that it'll fit in a usize and remove the `as`.
                usize::try_from(max_cairo_steps).unwrap_or_else(|_| {
                    log::error!(
                        "Performed a saturating cast from u128 to usize: {max_cairo_steps:?}"
                    );
                    usize::MAX
                })
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 98 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-NpZb7bb4LkwRkrimkma:-NpZdKGEAzmB16hpz9Eu:b-8kn7zm) ([raw file](https://github.com/starkware-libs/blockifier/blob/d1a4fe065d3da4e0857480b2650f151c1f41b1dc/crates/blockifier/src/fee/fee_utils.rs#L98)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

In another PR.
</blockquote></details>

Ya i started doing that, but then i hit a [hardcoded fee type](https://github.com/starkware-libs/blockifier/blob/d1a4fe065d3da4e0857480b2650f151c1f41b1dc/crates/blockifier/src/fee/fee_checks.rs#L81)so i let it go, i don't think i have runway to investigate it :(
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 207 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-NpZ_pMeEzg2bXCVbv6T:-NpZkcO0A-tDHfi35sT0:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/d1a4fe065d3da4e0857480b2650f151c1f41b1dc/crates/blockifier/src/fee/gas_usage.rs#L207)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Isn't `block_context` enough?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-02-04 10:40 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1365)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 98 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1365#-NpZb7bb4LkwRkrimkma:-NpngMXj94P1JgPKyAeR:bgb7ckw) ([raw file](https://github.com/starkware-libs/blockifier/blob/d1a4fe065d3da4e0857480b2650f151c1f41b1dc/crates/blockifier/src/fee/fee_utils.rs#L98)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider adding a TODO/Monday task.
</blockquote></details>

Done: https://starkware.monday.com/boards/5536734411/pulses/5994267610


<!-- Sent from Reviewable.io -->

2024-02-04 10:41 UTC, merged