feat: add more constants to`VersionedConstants`
starkware-libs/blockifier pull request #1369
Opened 2024-01-24 12:21 UTC by giladchase

- Add gateway constants, these are only for transparency, and aren't used directly by the Blockifier whatsoever.
- Pass `validate_max_n_steps` into the blockifier via native_blockifier, to override versioned constants defaults.

2024-01-25 10:10 UTC, elintul requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1369)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1369#-Np-4tFq5siYb24lw3Ks):*
Why add them then?



_Code quote:_
```
  - Add gateway constants, these are only for transparency, and aren't
    used directly by the Blockifier whatsoever.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1369#-Np-4yuq-rrdSoXxKVsv:-Np-4yuq-rrdSoXxKVsw:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/73319e21878f6af6099366595c37a0151bf3d360/crates/blockifier/src/versioned_constants.rs#L16)):*
> ```XML
> });
> 
> /// `VersionedConstants` contains constants for the Blockifier that may vary between versions.
> ```





_Suggestion:_
```XML
Contains
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1369#-Np-56YH7qm4rzrJAbjF:-Np-56YH7qm4rzrJAbjG:b-60id9t) ([raw file](https://github.com/starkware-libs/blockifier/blob/73319e21878f6af6099366595c37a0151bf3d360/crates/native_blockifier/src/py_block_executor.rs#L41)):*
> ```XML
>     pub fn create(
>         general_config: PyGeneralConfig,
>         validate_max_n_steps: u32,
> ```

What about max number of steps for execute? Also, why not inside general config?



_Code quote:_
```XML
validate_max_n_steps
```


<!-- Sent from Reviewable.io -->

2024-01-25 14:27 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1369)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1369#-Np-4tFq5siYb24lw3Ks):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why add them then?
</blockquote></details>

Lior asked for it during the design review, for transparency, and to make the blockifier a single source of truth for constants relating to its operation.
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1369#-Np-56YH7qm4rzrJAbjF:-Np-pWlK2gYKqg6x7hgT:b-bg363x) ([raw file](https://github.com/starkware-libs/blockifier/blob/73319e21878f6af6099366595c37a0151bf3d360/crates/native_blockifier/src/py_block_executor.rs#L41)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What about max number of steps for execute? Also, why not inside general config?
</blockquote></details>

It came up in the design review as well, Lior wanted this one to be configurable but not the execute, we didn't have enough time in the meeting to enquire why.


<!-- Sent from Reviewable.io -->

2024-01-25 15:26 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1369)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1369#-Np-4tFq5siYb24lw3Ks):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How is it a single source of truth if they aren't used? :(
</blockquote></details>

Single source of truth for both python and blockifier.
Python downloads the json file via bazel (downloads it from the blockifier repo) and extracts these constants from there.


<!-- Sent from Reviewable.io -->

2024-01-29 07:28 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1369#-:-NpJ6_zfBq-X3DscWYjG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-01-31 16:54 UTC, elintul submitted a review, later dismissed
> Reviewed 2 of 26 files at r4, 26 of 26 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1369)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-02-04 11:01 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1369)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1369#-Np-56YH7qm4rzrJAbjF:-NpnlKMM87lvgkEDsb48:b-dmjdw8) ([raw file](https://github.com/starkware-libs/blockifier/blob/73319e21878f6af6099366595c37a0151bf3d360/crates/native_blockifier/src/py_block_executor.rs#L41)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's try to understand, maybe in Slack? 
Also understand where did the invoke max steps go. :grimacing:
</blockquote></details>

`Resolved f2f. Closing.`


<!-- Sent from Reviewable.io -->

2024-02-04 11:08 UTC, noaov1 approved these changes
> Reviewed 1 of 4 files at r1, 1 of 4 files at r3, 1 of 26 files at r4, 2 of 26 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1369)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 42 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1369#-NpnnA235ktNCsDthPc_:-NpnnA242CFee1pb4ILY:b-8uxj9i) ([raw file](https://github.com/starkware-libs/blockifier/blob/38fd92e4d5b8f1b800d4aaadc121bee27740f193/crates/native_blockifier/src/py_block_executor.rs#L42)):*
> ```XML
>         general_config: PyGeneralConfig,
>         validate_max_n_steps: u32,
>         max_recursion_depth: usize,
> ```

Out of curiosity- Do we always want to pass it? Why not making it optional? 



_Code quote:_
```XML
        validate_max_n_steps: u32,
        max_recursion_depth: usize,
```


<!-- Sent from Reviewable.io -->

2024-02-04 11:15 UTC, giladchase reviewed
Note that the gateway constants will also be overriden in the native blockifier just as the validate constant is at this PR.

We'll handle this separately from this PR in an upcoming gateway. 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1369#-:-Npno2G8-5HJPzOdpQm8:b-az4enq)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 42 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1369#-NpnnA235ktNCsDthPc_:-NpnoR87Cha2GTmvah_4:b1rgqzh) ([raw file](https://github.com/starkware-libs/blockifier/blob/38fd92e4d5b8f1b800d4aaadc121bee27740f193/crates/native_blockifier/src/py_block_executor.rs#L42)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Out of curiosity- Do we always want to pass it? Why not making it optional?
</blockquote></details>

Just to simplify the implementation.
As an optional, it'll require the python config to also hold this optionally, and we'll have to match on it here.


<!-- Sent from Reviewable.io -->

2024-02-04 11:35 UTC, noaov1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1369)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 42 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1369#-NpnnA235ktNCsDthPc_:-Npnt_eJ5IvUngcYfwS8:b726fsf) ([raw file](https://github.com/starkware-libs/blockifier/blob/38fd92e4d5b8f1b800d4aaadc121bee27740f193/crates/native_blockifier/src/py_block_executor.rs#L42)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Just to simplify the implementation.
As an optional, it'll require the python config to also hold this optionally, and we'll have to match on it here.
</blockquote></details>

Okay. So we plan to have a copy of this constants in the python repository that will be "fed" to the blockifier? 


<!-- Sent from Reviewable.io -->

2024-02-04 11:42 UTC, noaov1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1369#-:-NpnvNYZCMdP5_k1ZQAz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @giladchase)



<!-- Sent from Reviewable.io -->

2024-02-04 11:43 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1369)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 42 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1369#-NpnnA235ktNCsDthPc_:-Npnv-LW8enKQ94e27jf:b-so1mlh) ([raw file](https://github.com/starkware-libs/blockifier/blob/38fd92e4d5b8f1b800d4aaadc121bee27740f193/crates/native_blockifier/src/py_block_executor.rs#L42)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Okay. So we plan to have a copy of this constants in the python repository that will be "fed" to the blockifier?
</blockquote></details>

Xactly, see the python PR for how it is passed.
In the upcoming Prs, once the infra is ready, python will no longer have copy of the default value from versioned_constants.json, it'll take it directly from the blockifier, so that the only case where they'll be different is if they are  explicitly replaced at runtime or if someone overrides the defaults in one of the python presets.


<!-- Sent from Reviewable.io -->

2024-02-04 11:44 UTC, noaov1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1369)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-02-04 11:44 UTC, noaov1 approved these changes
> Reviewed 24 of 26 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1369)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-02-04 12:44 UTC, merged