feat: Add Cairo constants to `VersionedConstants` - unused
starkware-libs/blockifier pull request #1379
Opened 2024-01-25 12:10 UTC by giladchase

Currently not using them, just adding the deserialization logic and tests.
In upcoming commits this will replace `constants.rs`.

FYI @Yael-Starkware

2024-01-25 12:16 UTC, elintul reviewed
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/resources/versioned_constants.json` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-Np-XIoq2cOOW1nNV6vv:-Np-XIoq2cOOW1nNV6vw:b-f4sqw5) ([raw file](https://github.com/starkware-libs/blockifier/blob/4dd1156c027ec78a45859bc3665a1512d693698e/crates/blockifier/resources/versioned_constants.json#L1)):*
> ```JSON
> {
> ```

Consider alphabetizing (in each section - constants, nested JSONs).
Also, please point me to the origin so I can compare.
___
*[`crates/blockifier/resources/versioned_constants.json` line 2 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-Np-XYLz5SHgel50PZYR:-Np-XYLz5SHgel50PZYS:b-7ijxf0) ([raw file](https://github.com/starkware-libs/blockifier/blob/4dd1156c027ec78a45859bc3665a1512d693698e/crates/blockifier/resources/versioned_constants.json#L2)):*
> ```JSON
> {
>   "cairo_os_constants": {
> ```

`[starknet_]os_resources`



_Code quote:_
```JSON
cairo_os_constants
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-Np-Y1Wo54pnmfOPawQz:-Np-Y1Wo54pnmfOPawR-:b-bqne5k) ([raw file](https://github.com/starkware-libs/blockifier/blob/4dd1156c027ec78a45859bc3665a1512d693698e/crates/blockifier/src/versioned_constants.rs#L37)):*
> ```XML
>     // Cairo OS constants.
>     // Note: if loaded from a json file, there are some assumptions made on its structure.
>     // See the struct's docstring for more details.
> ```

How is it different from the current `OsResources`? Maybe we should use this name



_Suggestion:_
```XML
    // Starknet OS constants.
    // Note: if loaded from a json file, there are some assumptions made on its structure.
    // See the struct's docstring for more details.
```


<!-- Sent from Reviewable.io -->

2024-01-27 15:15 UTC, elintul reviewed
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @giladchase and @noaov1)



<!-- Sent from Reviewable.io -->

2024-01-28 06:10 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/resources/versioned_constants.json` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-Np-XIoq2cOOW1nNV6vv:-Np0EXQV2X1HFRhjLVQU:bbu28i0) ([raw file](https://github.com/starkware-libs/blockifier/blob/4dd1156c027ec78a45859bc3665a1512d693698e/crates/blockifier/resources/versioned_constants.json#L1)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider alphabetizing (in each section - constants, nested JSONs).
Also, please point me to the origin so I can compare.
</blockquote></details>

Did it for the other sections (as per your request on a previous PR :grimacing: ) but for cairo constants we can't do it, it is ordered in a different way: the constants appearing as keys in object types must appear before the object type used them.
For example:
`FEE_TRANSFER_GAS_COST` must appear _after_ `ENTRY_POINT_GAS_COST`, because the former's value references `ENTRY_POINT_GAS_COST` (ya here alphabetized also works here but you know what i mean :) )
___
*[`crates/blockifier/src/versioned_constants.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-Np-Y1Wo54pnmfOPawQz:-Np0FOGn9F_dOQR9PEqu:b-jg4xxq) ([raw file](https://github.com/starkware-libs/blockifier/blob/4dd1156c027ec78a45859bc3665a1512d693698e/crates/blockifier/src/versioned_constants.rs#L37)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How is it different from the current `OsResources`? Maybe we should use this name
</blockquote></details>

Looks like versioned constants only includes gas costs, whereas os resources includes different info, like n_memory holes and n_steps.
 For example, for GetExecutionInfo in os resources we have:
```json
            "GetExecutionInfo": {
                "builtin_instance_counter": {
                    "range_check_builtin": 1
                },
                "n_memory_holes": 0,
                "n_steps": 62
            },
```
but in versioned constants it's
```json
    "GET_EXECUTION_INFO_GAS_COST": {
      "SYSCALL_BASE_GAS_COST": 1,
      "STEP_GAS_COST": 10
    },
```


<!-- Sent from Reviewable.io -->

2024-01-28 07:58 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-01-28 07:58 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @giladchase and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpE3vlkBPRawGmCbxhF:-NpE3vlkBPRawGmCbxhG:b33ob07) (no related file):*
Let's go over this PR together?

___


<!-- Sent from Reviewable.io -->

2024-01-29 07:28 UTC, elintul reviewed
> Reviewed 2 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: 2 of 9 files reviewed, 3 unresolved discussions (waiting on @giladchase and @noaov1)



<!-- Sent from Reviewable.io -->

2024-01-30 15:04 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: 2 of 9 files reviewed, 3 unresolved discussions (waiting on @elintul and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpE3vlkBPRawGmCbxhF:-NpPsWeQ9gfPEd3UxJz6:b-896fix) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's go over this PR together?
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2024-01-30 17:08 UTC, elintul reviewed
> Reviewed 1 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: 3 of 9 files reviewed, 2 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-01-31 17:51 UTC, elintul reviewed
> Reviewed 1 of 9 files at r6, 3 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-02-03 13:05 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-02-04 12:48 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/resources/versioned_constants.json` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-Np-XIoq2cOOW1nNV6vv:-Npo9AFf77leJ2DFGGst:bmcrsu) ([raw file](https://github.com/starkware-libs/blockifier/blob/4dd1156c027ec78a45859bc3665a1512d693698e/crates/blockifier/resources/versioned_constants.json#L1)):*
> Also, please point me to the origin so I can compare.

missed that, [here it is](https://github.com/starkware-industries/starkware/blob/daaa8ef1e466a1905f88749bb0dde2142e1bc9d7/src/starkware/starknet/core/os/constants.cairo#L1).  


<!-- Sent from Reviewable.io -->

2024-02-04 14:20 UTC, noaov1 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @giladchase, and @Yael-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 3 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpoOJlk1Ekx_HRug1zN:-NpoOJll6_ibkhF7LiCC:blueopu) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/resources/versioned_constants.json#L3)):*
> ```JSON
> {
>   "starknet_os_constants": {
>     "nop_entry_point_offset": -1,
> ```

Is it possible to add documentation? 



_Code quote:_
```JSON
    "nop_entry_point_offset": -1,
```
___
*[`crates/blockifier/resources/versioned_constants.json` line 144 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpoU5xFE_7mNO7z6t8w:-NpoU5xFE_7mNO7z6t8x:b-fgubja) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/resources/versioned_constants.json#L144)):*
> ```JSON
>     "l2_gas": "'L2_GAS'",
>     "l1_gas_index": 0,
>     "l2_gas_index": 1
> ```

Those are not used is the blockifier. Do we want to add them anyway?



_Code quote:_
```JSON
    "l1_gas": "'L1_GAS'",
    "l2_gas": "'L2_GAS'",
    "l1_gas_index": 0,
    "l2_gas_index": 1
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 28 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpoUUBs4sx4G7w28TWR:-NpoUUBtBohwLMAuxEjQ:b-phfds5) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants.rs#L28)):*
> ```XML
> pub struct VersionedConstants {
>     // Limits.
>     pub invoke_tx_max_n_steps: u32,
> ```

Do we want it to be `pub`?



_Code quote:_
```XML
    pub invoke_tx_max_n_steps: u32,
```


<!-- Sent from Reviewable.io -->

2024-02-04 16:27 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 3 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpoOJlk1Ekx_HRug1zN:-Npouq19EWktiqKabtIs:bpcbwu7) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/resources/versioned_constants.json#L3)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it possible to add documentation?
</blockquote></details>

Not really :( no comments in json.
If it helps, this variable isn't used, it's just here cause this part contains all the consts in `constants.cairo` (see link in pr description).

All that's used in the blockifier are the constants that end with `_cost`.
___
*[`crates/blockifier/resources/versioned_constants.json` line 144 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpoU5xFE_7mNO7z6t8w:-Npov83L2liR0VJaXUmE:b-sqyo29) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/resources/versioned_constants.json#L144)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Those are not used is the blockifier. Do we want to add them anyway?
</blockquote></details>

True, also everything else that doesn't end with _gas_cost isn't used (except for one that ends with _intial_budget).

Yep we want to load up all constants that have any relation to the blockifier into here, even if they aren't used, for the sake of transparency.
___
*[`crates/blockifier/src/versioned_constants.rs` line 28 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpoUUBs4sx4G7w28TWR:-NpovnliBQDTI5v6jzJx:b-4qtkel) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants.rs#L28)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do we want it to be `pub`?
</blockquote></details>

Ya, we want this to be easily overridable by our users, to make it easier to run execute/validate with modified stats.

I blocked for the hashmaps just because they have invariants on them (must contain fixed keys).
We can create a specialized setter for them, but there are already plans for making them structs instead of hashmaps (@dorimedini-starkware already started with vm_resource_fee_costs), which solves this issue completely without any setters.


<!-- Sent from Reviewable.io -->

2024-02-05 05:57 UTC, elintul requested changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @giladchase, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 244 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NprpjyB-X1zFHoArYMm:-NprpjyC9EGsc3DJgp3H:b-v5muhc) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants.rs#L244)):*
> ```XML
> 
> #[derive(Debug, Error)]
> pub enum StarknetConstantsSerdeError {
> ```

Are those only OS constants in the end?
Also, please alphabetize the variants.



_Suggestion:_
```XML
OsConstantsSerdeError
```


<!-- Sent from Reviewable.io -->

2024-02-05 09:14 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @elintul, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 2 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpsXJcW0tUE0OeIka2z:-NpsXJcW0tUE0OeIka3-:b34tynz) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/resources/versioned_constants.json#L2)):*
> ```JSON
> {
>   "starknet_os_constants": {
> ```

FYI @noaov1 

After offline talk with @dorimedini-starkware we decided that it'd be better to dispense with the order of the keys, this would change the parsing logic, from a 1-pass parse, into a fixed-point iteration parse.

However, since this requires non-trivial changes, we'll add this in 13.2 (i'll get on implementing it right away though, but open the PR directly on 13.2).

The motivation for removing the order is  due to: relying on sorting in an unsorted format like json is hackish, also the rest of the fields are sorted, and this one isn't, which is awkward. 
___
*[`crates/blockifier/src/versioned_constants.rs` line 244 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NprpjyB-X1zFHoArYMm:-NpsX99BBjHz0xZ9mog6:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants.rs#L244)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are those only OS constants in the end?
Also, please alphabetize the variants.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-05 11:16 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 9 files at r6, 1 of 4 files at r8, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: all files reviewed, 11 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 28 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpoUUBs4sx4G7w28TWR:-Npsm_ZbAbkXm_hOzeTK:bk593cg) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants.rs#L28)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Ya, we want this to be easily overridable by our users, to make it easier to run execute/validate with modified stats.

I blocked for the hashmaps just because they have invariants on them (must contain fixed keys).
We can create a specialized setter for them, but there are already plans for making them structs instead of hashmaps (@dorimedini-starkware already started with vm_resource_fee_costs), which solves this issue completely without any setters.
</blockquote></details>

By design, if we need to store values per builtin, we want to keep hashmaps with builtins as keys (for flexibility).
Not sure how it's relevant to this comment but that's my two cents
___
*[`crates/blockifier/src/versioned_constants.rs` line 68 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpsnX8G7PSKXuEBFORa:-NpsnX8G7PSKXuEBFORb:bk7jjea) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants.rs#L68)):*
> ```XML
>                     "Only gas costs listed in `StarknetOsConstants::GAS_COSTS` should be \
>                      requested, got: {}",
>                     name
> ```

can you output `StarknetOSConstants::ALLOWED_GAS_COST_NAMES` in this panic?



_Code quote:_
```XML
                    "Only gas costs listed in `StarknetOsConstants::GAS_COSTS` should be \
                     requested, got: {}",
                    name
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 108 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpsnnDt9FQXYJ5QXh8o:-NpsnnDt9FQXYJ5QXh8p:b-ommnlh) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants.rs#L108)):*
> ```XML
> // FIXME FOLLOWUP: if we switch from JSON, we can switch to strongly typed fields, instead of an
> // internal indexmap: using strongly typed fields breaks the order under serialization, making
> // testing very difficult.
> ```

how painful is it to remove this order assumption, in this PR?
i.e. a recursive implementation / while loop implementation that does not rely on intermediate values appearing before their first usage?



_Code quote:_
```XML
// FIXME: JSON doesn't guarantee order, serde seems to work for this use-case, buit there is no
// guarantee that it will stay that way. Seriously consider switching to serde_yaml/other format.
// FIXME FOLLOWUP: if we switch from JSON, we can switch to strongly typed fields, instead of an
// internal indexmap: using strongly typed fields breaks the order under serialization, making
// testing very difficult.
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 151 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-Npso1Rf9DkPspAK4Hbd:-Npso1Rf9DkPspAK4Hbe:b-vkp1jx) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants.rs#L151)):*
> ```XML
>         "secp256r1_new_gas_cost",
>         "keccak_gas_cost",
>         "keccak_round_cost_gas_cost",
> ```

alphabetize?



_Code quote:_
```XML
        "step_gas_cost",
        "range_check_gas_cost",
        "memory_hole_gas_cost",
        "initial_gas_cost",
        "entry_point_initial_budget",
        "syscall_base_gas_cost",
        "entry_point_gas_cost",
        "fee_transfer_gas_cost",
        "transaction_gas_cost",
        "call_contract_gas_cost",
        "deploy_gas_cost",
        "get_block_hash_gas_cost",
        "get_execution_info_gas_cost",
        "library_call_gas_cost",
        "replace_class_gas_cost",
        "storage_read_gas_cost",
        "storage_write_gas_cost",
        "emit_event_gas_cost",
        "send_message_to_l1_gas_cost",
        "secp256k1_add_gas_cost",
        "secp256k1_get_point_from_x_gas_cost",
        "secp256k1_get_xy_gas_cost",
        "secp256k1_mul_gas_cost",
        "secp256k1_new_gas_cost",
        "secp256r1_add_gas_cost",
        "secp256r1_get_point_from_x_gas_cost",
        "secp256r1_get_xy_gas_cost",
        "secp256r1_mul_gas_cost",
        "secp256r1_new_gas_cost",
        "keccak_gas_cost",
        "keccak_round_cost_gas_cost",
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 178 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-Npsohef3ylYzZdkYXGh:-Npsohef3ylYzZdkYXGi:b-zf1leu) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants.rs#L178)):*
> ```XML
>         let gas_cost_whitelist: IndexSet<_> =
>             Self::ALLOWED_GAS_COST_NAMES.iter().copied().collect();
>         for (key, value) in raw_json_data.raw_json_file_as_dict {
> ```

I think this inner loop can easily be made recursive (input: key, output: value + updates the gas costs in-place).
base case: check if the key is already in gas_costs, if so return the value.
then you don't need it sorted specifically.
WDYT?



_Code quote:_
```XML
(key, value) in raw_json_data.raw_json_file_as_dict {
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 247 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpswmJc1ZsLCUPmu9Tl:-NpswmJc1ZsLCUPmu9Tm:bwvrf34) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants.rs#L247)):*
> ```XML
>     #[error("Validation failed: {0}")]
>     ValidationError(String),
>     #[error("Value {1} for key '{0}' is out of range and cannot be cast into u64")]
> ```

aren't these backwards?



_Code quote:_
```XML
{1} for key '{0}'
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 250 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpswsLG7wwAHOlY1Ix-:-NpswsLG7wwAHOlY1Ix0:bp6xvv7) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants.rs#L250)):*
> ```XML
>     OutOfRange(String, Number),
>     #[error(
>         "Value {1} used to create value for key '{0}' is out of range and cannot be cast into u64"
> ```

backwards? 0 and 1?



_Code quote:_
```XML
{1} used to create value for key '{0}'
```
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 29 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-Npsy9TH7-a4Jgc0XKp-:-Npsy9TH7-a4Jgc0XKp0:br49dx2) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants_test.rs#L29)):*
> ```XML
> 
>     // entry_point_intial_budget * 4 + step_gas_cost * 5.
>     assert_eq!(versioned_constants.gas_cost("entry_point_gas_cost"), 34);
> ```

document by using expressions



_Suggestion:_
```XML
    assert_eq!(versioned_constants.gas_cost("step_gas_cost"), 2);
    assert_eq!(versioned_constants.gas_cost("entry_point_initial_budget"), 2 * 3); // step_gas_cost * 3.

    // entry_point_intial_budget * 4 + step_gas_cost * 5.
    assert_eq!(versioned_constants.gas_cost("entry_point_gas_cost"), 6 * 4 + 2 * 5);
```


<!-- Sent from Reviewable.io -->

2024-02-05 11:16 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: all files reviewed, 11 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 2 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpsXJcW0tUE0OeIka2z:-NpsyxCo5r33ZGZ1Bbxs:b792jvm) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/resources/versioned_constants.json#L2)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

FYI @noaov1 

After offline talk with @dorimedini-starkware we decided that it'd be better to dispense with the order of the keys, this would change the parsing logic, from a 1-pass parse, into a fixed-point iteration parse.

However, since this requires non-trivial changes, we'll add this in 13.2 (i'll get on implementing it right away though, but open the PR directly on 13.2).

The motivation for removing the order is  due to: relying on sorting in an unsorted format like json is hackish, also the rest of the fields are sorted, and this one isn't, which is awkward.
</blockquote></details>

wonder f we should revisit this... see below (non blocking)


<!-- Sent from Reviewable.io -->

2024-02-05 11:19 UTC, elintul approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: all files reviewed, 10 unresolved discussions (waiting on @giladchase, @noaov1, and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-02-05 12:02 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: all files reviewed, 10 unresolved discussions (waiting on @dorimedini-starkware, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 28 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpoUUBs4sx4G7w28TWR:-Npt0q8WE8DDmypykytf:b-kqd71w) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants.rs#L28)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

By design, if we need to store values per builtin, we want to keep hashmaps with builtins as keys (for flexibility).
Not sure how it's relevant to this comment but that's my two cents
</blockquote></details>

Let's discuss this once it becomes relevant, post 13.1 probably :sweat_smile: 
___
*[`crates/blockifier/src/versioned_constants.rs` line 68 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpsnX8G7PSKXuEBFORa:-Npt1XNl0_8HMZ9uI-bO:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants.rs#L68)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you output `StarknetOSConstants::ALLOWED_GAS_COST_NAMES` in this panic?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 108 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpsnnDt9FQXYJ5QXh8o:-Npt1ZPK-RaA0eXkp7QN:b-2u3mxa) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants.rs#L108)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

how painful is it to remove this order assumption, in this PR?
i.e. a recursive implementation / while loop implementation that does not rely on intermediate values appearing before their first usage?
</blockquote></details>

Let's handle this in a refactor, to be added _very soon_ after we're done with 13.1.
Srry for the mess.
___
*[`crates/blockifier/src/versioned_constants.rs` line 151 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-Npso1Rf9DkPspAK4Hbd:-Npt4IEBEIlSx7POgnjo:bb80plh) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants.rs#L151)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

alphabetize?
</blockquote></details>

Can't :grimacing:  because of order sensitivity.
___
*[`crates/blockifier/src/versioned_constants.rs` line 178 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-Npsohef3ylYzZdkYXGh:-Npt6d3G1McIbRXrNWCM:b-l5s6m1) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants.rs#L178)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think this inner loop can easily be made recursive (input: key, output: value + updates the gas costs in-place).
base case: check if the key is already in gas_costs, if so return the value.
then you don't need it sorted specifically.
WDYT?
</blockquote></details>

Talked offline, will be handled post 13.1.
___
*[`crates/blockifier/src/versioned_constants.rs` line 247 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpswmJc1ZsLCUPmu9Tl:-Npt7nZx14KuD6QK8yJD:b-kvr9k8) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants.rs#L247)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

aren't these backwards?
</blockquote></details>

Nope it's Value `{value} for key {key}`, made it into a struct now to clarify.


<!-- Sent from Reviewable.io -->

2024-02-05 12:05 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: 7 of 9 files reviewed, 10 unresolved discussions (waiting on @dorimedini-starkware, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 250 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpswsLG7wwAHOlY1Ix-:-Npt8ltg-caix-RMP2pF:b-icou9o) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants.rs#L250)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

backwards? 0 and 1?
</blockquote></details>

Nope, like the rev comment, made it into a struct now to clarify.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 29 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-Npsy9TH7-a4Jgc0XKp-:-Npt91tN-_7Ejgc-L2VS:bpc5830) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/src/versioned_constants_test.rs#L29)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

document by using expressions
</blockquote></details>

Done. i kept the comments though  cause they help with eplxaining it.


<!-- Sent from Reviewable.io -->

2024-02-05 12:37 UTC, noaov1 reviewed
> Reviewed 1 of 9 files at r6, 1 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 144 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpoU5xFE_7mNO7z6t8w:-Npt2sg10Lnnw4y-EU9I:bd5n6xc) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/resources/versioned_constants.json#L144)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

True, also everything else that doesn't end with _gas_cost isn't used (except for one that ends with _intial_budget).

Yep we want to load up all constants that have any relation to the blockifier into here, even if they aren't used, for the sake of transparency.
</blockquote></details>

A suggestion (if you like it you can add a TODO): use the constants in this file instead of the file `crates/blockifier/src/abi/constants.rs`.


<!-- Sent from Reviewable.io -->

2024-02-05 13:08 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 144 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-NpoU5xFE_7mNO7z6t8w:-NptMvu91CCxSs2MH8ir:beljwiv) ([raw file](https://github.com/starkware-libs/blockifier/blob/86a95e130fbb12d1c80b6ad8bebeb86caed69e28/crates/blockifier/resources/versioned_constants.json#L144)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

A suggestion (if you like it you can add a TODO): use the constants in this file instead of the file `crates/blockifier/src/abi/constants.rs`.
</blockquote></details>

Started with that, but it's a can of worms.

If i use some of the constants from here rather than in constants.rs, i'll have to use all of them, for consistency, otherwise it'd be confusing why some constants are used and some aren't.

However, if we use them all, then the parsing logic would have to support also strings, and negative numbers, which will noticeably complicate the parsing logic, and the getters will be more complicated, and so on.

Better tackle that later.


<!-- Sent from Reviewable.io -->

2024-02-05 13:15 UTC, noaov1 reviewed
> Reviewed 2 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-02-05 13:33 UTC, merged

2024-02-06 15:44 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1379)* status: all files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/src/versioned_constants_test.rs` line 3 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1379#-Npz4y9zBrxKaK_DWrrL:-Npz4y9zBrxKaK_DWrrM:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/bd185f339fe8ece048f8d6ad3ed7246eb5bb9a60/crates/blockifier/src/versioned_constants_test.rs#L3)):*
> ```XML
> use pretty_assertions::assert_eq;
> 
> use super::*;
> ```

?



_Code quote:_
```XML
use super::*;
```


<!-- Sent from Reviewable.io -->