refactor(execution): pre_process_block refactor for full_nodes simula…
starkware-libs/blockifier pull request #1387
Opened 2024-01-28 08:26 UTC by Yael-Starkware

…te transaction

2024-01-28 09:57 UTC, elintul reviewed
> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/blockifier/src/state/errors.rs` line 6 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpEU5WL8mLyK0QJrilO:-NpEU5WL8mLyK0QJrilP:bfmv1j2) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c8794cf9e9a0db025acabf96b38eb1668e14caf/crates/blockifier/src/state/errors.rs#L6)):*
> ```XML
> use thiserror::Error;
> 
> use crate::abi::constants::STORED_BLOCK_HASH_BUFFER;
> ```

Import the whole module, as we do throughout the code.



_Code quote:_
```XML
use crate::abi::constants::STORED_BLOCK_HASH_BUFFER;
```
___
*[`crates/blockifier/src/state/errors.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpEU1G96LY3WESX6E_F:-NpEU1GA16qjwt1oGILZ:b-v53drf) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c8794cf9e9a0db025acabf96b38eb1668e14caf/crates/blockifier/src/state/errors.rs#L9)):*
> ```XML
> 
> #[derive(Debug, Error)]
> pub enum StateError {
> ```

Keep alphabetized.



_Code quote:_
```XML
StateError
```
___
*[`crates/native_blockifier/src/py_block_executor_test.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpEUFNY6jJEsfZIZUYo:-NpEUFNZAcdSdWdWMCOu:b5s87qk) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c8794cf9e9a0db025acabf96b38eb1668e14caf/crates/native_blockifier/src/py_block_executor_test.rs#L22)):*
> ```XML
>     let mut block_executor =
>         PyBlockExecutor::create_for_testing(PyGeneralConfig::default(), temp_storage_path);
>     block_executor.setup_block_execution(PyBlockInfo::default(), None).unwrap();
> ```

Give this a name.



_Code quote:_
```XML
None
```


<!-- Sent from Reviewable.io -->

2024-01-28 10:35 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: 2 of 7 files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/blockifier/src/state/errors.rs` line 6 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpEU5WL8mLyK0QJrilO:-NpEbqhz-OagGtl-hBS1:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c8794cf9e9a0db025acabf96b38eb1668e14caf/crates/blockifier/src/state/errors.rs#L6)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Import the whole module, as we do throughout the code.
</blockquote></details>

done.
___
*[`crates/blockifier/src/state/errors.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpEU1G96LY3WESX6E_F:-NpEbrm3-MZktm4M7_nC:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c8794cf9e9a0db025acabf96b38eb1668e14caf/crates/blockifier/src/state/errors.rs#L9)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Keep alphabetized.
</blockquote></details>

done.
___
*[`crates/native_blockifier/src/py_block_executor_test.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpEUFNY6jJEsfZIZUYo:-NpEbsil1ZuR0U_a7DxC:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c8794cf9e9a0db025acabf96b38eb1668e14caf/crates/native_blockifier/src/py_block_executor_test.rs#L22)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Give this a name.
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2024-01-28 12:52 UTC, elintul requested changes
> Reviewed 4 of 7 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: all files reviewed, 8 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/blockifier/src/block_execution.rs` line 49 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpF5qif9-lFhXRiLceR:-NpF5qig2hnmOXW8eKFa:b4yuv1b) ([raw file](https://github.com/starkware-libs/blockifier/blob/af1b281adece5b697404657d8b4912100fda3e50/crates/blockifier/src/block_execution.rs#L49)):*
> ```XML
>             // We allow None value for block_number < STORED_BLOCK_HASH_BUFFER because we update
>             // the hash table in STORED_BLOCK_HASH_BUFFER blocks delay. This is done since the
>             // hash computation has a delay.
> ```

Not sure I understand this comment.



_Code quote:_
```XML
            // We allow None value for block_number < STORED_BLOCK_HASH_BUFFER because we update
            // the hash table in STORED_BLOCK_HASH_BUFFER blocks delay. This is done since the
            // hash computation has a delay.
```
___
*[`crates/blockifier/src/block_execution_test.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpF69ww2bd4mT8PgCXZ:-NpF69ww2bd4mT8PgCX_:b-idka97) ([raw file](https://github.com/starkware-libs/blockifier/blob/af1b281adece5b697404657d8b4912100fda3e50/crates/blockifier/src/block_execution_test.rs#L32)):*
> ```XML
> 
>     // Test that the function returns ok when block_number < 10 and an error when
>     // block_number >= 10 for old_block_number_and_hash = None
> ```

This comment is repeating the code, instead try to phrase documentation in a more behavioral way: "Test that block pre-process is successful only within the allowed block number interval.".  



_Code quote:_
```XML
    // Test that the function returns ok when block_number < 10 and an error when
    // block_number >= 10 for old_block_number_and_hash = None
```
___
*[`crates/blockifier/src/state/errors.rs` line 6 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpEU5WL8mLyK0QJrilO:-NpF6Yu88SZk-pHNaBcB:b-iuxp3t) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c8794cf9e9a0db025acabf96b38eb1668e14caf/crates/blockifier/src/state/errors.rs#L6)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

done.
</blockquote></details>

Same in test?
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 325 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpF6gyv-jWYyW3tgF-m:-NpF6gyv-jWYyW3tgF-n:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/af1b281adece5b697404657d8b4912100fda3e50/crates/native_blockifier/src/py_block_executor.rs#L325)):*
> ```XML
> }
> 
> // Block pre-processing; see `block_execution::pre_process_block` documentation.
> ```





_Suggestion:_
```XML
// Executes block pre-processing;
```
___
*[`crates/native_blockifier/src/py_block_executor_test.rs` line 22 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpF6upl0NcY-KwhumQS:-NpF6upl0NcY-KwhumQT:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/af1b281adece5b697404657d8b4912100fda3e50/crates/native_blockifier/src/py_block_executor_test.rs#L22)):*
> ```XML
>     let mut block_executor =
>         PyBlockExecutor::create_for_testing(PyGeneralConfig::default(), temp_storage_path);
>     let empty_block_number_and_hash = None; // This field should be None for block 0.
> ```





_Suggestion:_
```XML
let sentinel_block_number_and_hash = None; // Information does not exist for block 0.
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 46 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpF76V45RJ-VF35oZpj:-NpF76V45RJ-VF35oZpk:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/af1b281adece5b697404657d8b4912100fda3e50/crates/native_blockifier/src/py_validator.rs#L46)):*
> ```XML
>         let state_reader = PyStateReader::new(state_reader_proxy);
>         let state = CachedState::new(state_reader, global_contract_cache);
>         let block_context_args =
> ```





_Suggestion:_
```XML
        let state = CachedState::new(state_reader, global_contract_cache);
        
        let block_context_args =
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpF78NEDpo6vZz6Zv1w:-NpF78NEDpo6vZz6Zv1x:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/af1b281adece5b697404657d8b4912100fda3e50/crates/native_blockifier/src/py_validator.rs#L51)):*
> ```XML
>         // TODO(Yael 24/01/24): calc block_context using pre_process_block
>         let tx_executor = TransactionExecutor::new(state, block_context)?;
>         let validator = Self {
> ```





_Suggestion:_
```XML
        let tx_executor = TransactionExecutor::new(state, block_context)?;
        
        let validator = Self {
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 118 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpF7AM54mi-SMPGDqS1:-NpF7AM54mi-SMPGDqS2:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/af1b281adece5b697404657d8b4912100fda3e50/crates/native_blockifier/src/py_validator.rs#L118)):*
> ```XML
>         let global_contract_cache = GlobalContractCache::default();
>         let state = CachedState::new(state_reader, global_contract_cache);
>         let block_context_args =
> ```





_Suggestion:_
```XML
        let state = CachedState::new(state_reader, global_contract_cache);
        
        let block_context_args =
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 123 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpF7FhM888QmWtSHKAA:-NpF7FhM888QmWtSHKAB:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/af1b281adece5b697404657d8b4912100fda3e50/crates/native_blockifier/src/py_validator.rs#L123)):*
> ```XML
>         // TODO(Yael 24/01/24): calc block_context using pre_process_block
>         let tx_executor = TransactionExecutor::new(state, block_context)?;
>         Ok(Self {
> ```





_Suggestion:_
```XML
        let tx_executor = TransactionExecutor::new(state, block_context)?;
        
        Ok(Self {
```


<!-- Sent from Reviewable.io -->

2024-01-28 13:33 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/block_execution.rs` line 49 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpF5qif9-lFhXRiLceR:-NpFDy2l0WwzF0ljkqwz:bxwi3mo) ([raw file](https://github.com/starkware-libs/blockifier/blob/af1b281adece5b697404657d8b4912100fda3e50/crates/blockifier/src/block_execution.rs#L49)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure I understand this comment.
</blockquote></details>

now better?
___
*[`crates/blockifier/src/block_execution_test.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpF69ww2bd4mT8PgCXZ:-NpFEIje0u3A4yp9gkkS:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/af1b281adece5b697404657d8b4912100fda3e50/crates/blockifier/src/block_execution_test.rs#L32)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This comment is repeating the code, instead try to phrase documentation in a more behavioral way: "Test that block pre-process is successful only within the allowed block number interval.".
</blockquote></details>

done.
___
*[`crates/blockifier/src/state/errors.rs` line 6 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpEU5WL8mLyK0QJrilO:-NpFEKrZ5BWhNGpjUjdL:b2nign6) ([raw file](https://github.com/starkware-libs/blockifier/blob/6c8794cf9e9a0db025acabf96b38eb1668e14caf/crates/blockifier/src/state/errors.rs#L6)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Same in test?
</blockquote></details>

yes
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 325 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpF6gyv-jWYyW3tgF-m:-NpFEM50Dzpe3xtETxd2:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/af1b281adece5b697404657d8b4912100fda3e50/crates/native_blockifier/src/py_block_executor.rs#L325)):*
> ```XML
> }
> 
> // Block pre-processing; see `block_execution::pre_process_block` documentation.
> ```

done.
___
*[`crates/native_blockifier/src/py_validator.rs` line 46 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpF76V45RJ-VF35oZpj:-NpFF0ORAjSnpuECbzer:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/af1b281adece5b697404657d8b4912100fda3e50/crates/native_blockifier/src/py_validator.rs#L46)):*
> ```XML
>         let state_reader = PyStateReader::new(state_reader_proxy);
>         let state = CachedState::new(state_reader, global_contract_cache);
>         let block_context_args =
> ```

done
___
*[`crates/native_blockifier/src/py_validator.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpF78NEDpo6vZz6Zv1w:-NpFF13R5Kgx7A6QhCYD:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/af1b281adece5b697404657d8b4912100fda3e50/crates/native_blockifier/src/py_validator.rs#L51)):*
> ```XML
>         // TODO(Yael 24/01/24): calc block_context using pre_process_block
>         let tx_executor = TransactionExecutor::new(state, block_context)?;
>         let validator = Self {
> ```

done
___
*[`crates/native_blockifier/src/py_validator.rs` line 118 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpF7AM54mi-SMPGDqS1:-NpFF1l48lY5-WNtf-UF:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/af1b281adece5b697404657d8b4912100fda3e50/crates/native_blockifier/src/py_validator.rs#L118)):*
> ```XML
>         let global_contract_cache = GlobalContractCache::default();
>         let state = CachedState::new(state_reader, global_contract_cache);
>         let block_context_args =
> ```

done
___
*[`crates/native_blockifier/src/py_validator.rs` line 123 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpF7FhM888QmWtSHKAA:-NpFF2Sn8QiW23fE6WF0:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/af1b281adece5b697404657d8b4912100fda3e50/crates/native_blockifier/src/py_validator.rs#L123)):*
> ```XML
>         // TODO(Yael 24/01/24): calc block_context using pre_process_block
>         let tx_executor = TransactionExecutor::new(state, block_context)?;
>         Ok(Self {
> ```

done


<!-- Sent from Reviewable.io -->

2024-01-28 13:37 UTC, elintul approved these changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/blockifier/src/block_execution.rs` line 6 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpFHJQz9VGm98_Z0j3y:-NpFHJQz9VGm98_Z0j3z:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9dd34c54e0f0a2ee324d07a0871b2e815ed1ad36/crates/blockifier/src/block_execution.rs#L6)):*
> ```XML
> use starknet_api::state::StorageKey;
> 
> use crate::abi::constants::{self, STORED_BLOCK_HASH_BUFFER};
> ```





_Suggestion:_
```XML
;
```
___
*[`crates/blockifier/src/block_execution.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpFH2Cw2Vh4-WR5hTWb:-NpFH2Cx0qXW8YQJAY0z:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9dd34c54e0f0a2ee324d07a0871b2e815ed1ad36/crates/blockifier/src/block_execution.rs#L47)):*
> ```XML
>         }
>         None if block_context_args.block_number >= BlockNumber(STORED_BLOCK_HASH_BUFFER) => {
>             // For the first STORED_BLOCK_HASH_BUFFER blocks, the old block hash is not available.
> ```





_Suggestion:_
```XML
// Block hash is not available for the first `constants::STORED_BLOCK_HASH_BUFFER` blocks.
```
___
*[`crates/native_blockifier/src/py_block_executor_test.rs` line 22 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpF6upl0NcY-KwhumQS:-NpFGtkv3jRQFVIfva2_:b-xas2u8) ([raw file](https://github.com/starkware-libs/blockifier/blob/af1b281adece5b697404657d8b4912100fda3e50/crates/native_blockifier/src/py_block_executor_test.rs#L22)):*
> ```XML
>     let mut block_executor =
>         PyBlockExecutor::create_for_testing(PyGeneralConfig::default(), temp_storage_path);
>     let empty_block_number_and_hash = None; // This field should be None for block 0.
> ```

I think "sentinel" is better here, since it's `None` and not `(0, 0)`.


<!-- Sent from Reviewable.io -->

2024-01-29 06:10 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/block_execution.rs` line 6 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpFHJQz9VGm98_Z0j3y:-NpIojKL9K4_kzFObUn0:b-zfqr6b) ([raw file](https://github.com/starkware-libs/blockifier/blob/9dd34c54e0f0a2ee324d07a0871b2e815ed1ad36/crates/blockifier/src/block_execution.rs#L6)):*
> ```XML
> use starknet_api::state::StorageKey;
> 
> use crate::abi::constants::{self, STORED_BLOCK_HASH_BUFFER};
> ```

oh sorry I don't know how I missed this one. 
done.
___
*[`crates/blockifier/src/block_execution.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpFH2Cw2Vh4-WR5hTWb:-NpIpHPQ4tXtGvY1paaL:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/9dd34c54e0f0a2ee324d07a0871b2e815ed1ad36/crates/blockifier/src/block_execution.rs#L47)):*
> ```XML
>         }
>         None if block_context_args.block_number >= BlockNumber(STORED_BLOCK_HASH_BUFFER) => {
>             // For the first STORED_BLOCK_HASH_BUFFER blocks, the old block hash is not available.
> ```

done
___
*[`crates/native_blockifier/src/py_block_executor_test.rs` line 22 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpF6upl0NcY-KwhumQS:-NpIpJ5H8RIxou-LkW2F:b1f1gdk) ([raw file](https://github.com/starkware-libs/blockifier/blob/af1b281adece5b697404657d8b4912100fda3e50/crates/native_blockifier/src/py_block_executor_test.rs#L22)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think "sentinel" is better here, since it's `None` and not `(0, 0)`.
</blockquote></details>

learned a new word :)
done


<!-- Sent from Reviewable.io -->

2024-01-29 07:32 UTC, elintul approved these changes
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/blockifier/src/block_execution.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpFH2Cw2Vh4-WR5hTWb:-NpJ7SNd2stDj1qQmr0E:bvnztu) ([raw file](https://github.com/starkware-libs/blockifier/blob/9dd34c54e0f0a2ee324d07a0871b2e815ed1ad36/crates/blockifier/src/block_execution.rs#L47)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

done
</blockquote></details>

I actually don't understand this case and why it's suddenly needed.


<!-- Sent from Reviewable.io -->

2024-01-29 07:32 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpJ7Zx-0MJjHyGr6_IE:-NpJ7Zx-0MJjHyGr6_IF:b-m2asqv) (no related file):*
Please open a corresponding Python PR.

___


<!-- Sent from Reviewable.io -->

2024-01-29 12:03 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/blockifier/src/block_execution.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpFH2Cw2Vh4-WR5hTWb:-NpK4VUu2oZTighNnD02:bokcbn6) ([raw file](https://github.com/starkware-libs/blockifier/blob/9dd34c54e0f0a2ee324d07a0871b2e815ed1ad36/crates/blockifier/src/block_execution.rs#L47)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I actually don't understand this case and why it's suddenly needed.
</blockquote></details>

This is to protect from full nodes putting always None as the old_block_number_and_hash input.
Sorry I didn't tell you before, It was discussed f2f with Ariel an Yoni in the previous iteration of the code review with Gilad (but not documented here).


<!-- Sent from Reviewable.io -->

2024-01-29 12:08 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpJ7Zx-0MJjHyGr6_IE:-NpK6nof5T3NAaLr4k9d:b-j5at1h) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please open a corresponding Python PR.
</blockquote></details>

https://github.com/starkware-industries/starkware/pull/33478

___


<!-- Sent from Reviewable.io -->

2024-01-30 06:40 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/blockifier/src/block_execution.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpFH2Cw2Vh4-WR5hTWb:-NpO2Ieb2KQNY9f4Gy0a:b-6i5zav) ([raw file](https://github.com/starkware-libs/blockifier/blob/9dd34c54e0f0a2ee324d07a0871b2e815ed1ad36/crates/blockifier/src/block_execution.rs#L47)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

This is to protect from full nodes putting always None as the old_block_number_and_hash input.
Sorry I didn't tell you before, It was discussed f2f with Ariel an Yoni in the previous iteration of the code review with Gilad (but not documented here).
</blockquote></details>

That's okay, a PR is a good place for me to find out. :)
Okay, then let's do the following:
```rs
let should_block_hash_be_provided = 
    block_context_args.block_number >= BlockNumber(constants::STORED_BLOCK_HASH_BUFFER);
if let Some(BlockNumberHashPair { number: block_number, hash: block_hash }) = old_block_number_and_hash {
    ...
} else if should_block_hash_be_provided { 
    return Err(StateError::OldBlockHashNotProvided); 
}
```
___
*[`crates/blockifier/src/block_execution.rs` line 37 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpO3uJX9ix8E1Hj9gMX:-NpO3uJX9ix8E1Hj9gMY:b-3ec0jb) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c689b5a8fabe58ee40e984513ebc131ce4b60b5/crates/blockifier/src/block_execution.rs#L37)):*
> ```XML
> ) -> StateResult<BlockContext> {
>     match old_block_number_and_hash {
>         Some(BlockNumberHashPair { number: block_number, hash: block_hash }) => {
> ```

Do we want to check that it's larger than `10`?



_Code quote:_
```XML
number: block_number
```
___
*[`crates/blockifier/src/block_execution.rs` line 40 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpO2u6EBhTdv6Tn6Xtg:-NpO2u6EBhTdv6Tn6Xth:brd87i2) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c689b5a8fabe58ee40e984513ebc131ce4b60b5/crates/blockifier/src/block_execution.rs#L40)):*
> ```XML
>             state.set_storage_at(
>                 ContractAddress::try_from(StarkFelt::from(constants::BLOCK_HASH_CONTRACT_ADDRESS))
>                     .expect("Failed to convert `BLOCK_HASH_CONTRACT_ADDRESS` to ContractAddress."),
> ```

Can this be built using a constant c-tor/one that doesn't fail?
Also, give it a name: `block_hash_contract_address`.



_Code quote:_
```XML
                ContractAddress::try_from(StarkFelt::from(constants::BLOCK_HASH_CONTRACT_ADDRESS))
                    .expect("Failed to convert `BLOCK_HASH_CONTRACT_ADDRESS` to ContractAddress."),
```
___
*[`crates/blockifier/src/block_execution.rs` line 42 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpO3ib13U9MTj42mYRt:-NpO3ib13U9MTj42mYRu:bv7jc2u) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c689b5a8fabe58ee40e984513ebc131ce4b60b5/crates/blockifier/src/block_execution.rs#L42)):*
> ```XML
>                     .expect("Failed to convert `BLOCK_HASH_CONTRACT_ADDRESS` to ContractAddress."),
>                 StorageKey::try_from(StarkFelt::from(block_number.0))
>                     .expect("Failed to convert BlockNumber to StorageKey."),
> ```

Can this be built using a constant c-tor/one that doesn't fail?
Also, give it a name: `block_number_as_storage_key`.



_Code quote:_
```XML
                StorageKey::try_from(StarkFelt::from(block_number.0))
                    .expect("Failed to convert BlockNumber to StorageKey."),
```


<!-- Sent from Reviewable.io -->

2024-01-30 10:28 UTC, elintul reviewed
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-01-31 09:23 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/block_execution.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpFH2Cw2Vh4-WR5hTWb:-NpTnTbU-zGDBh_LpYSk:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/9dd34c54e0f0a2ee324d07a0871b2e815ed1ad36/crates/blockifier/src/block_execution.rs#L47)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

That's okay, a PR is a good place for me to find out. :)
Okay, then let's do the following:
```rs
let should_block_hash_be_provided = 
    block_context_args.block_number >= BlockNumber(constants::STORED_BLOCK_HASH_BUFFER);
if let Some(BlockNumberHashPair { number: block_number, hash: block_hash }) = old_block_number_and_hash {
    ...
} else if should_block_hash_be_provided { 
    return Err(StateError::OldBlockHashNotProvided); 
}
```
</blockquote></details>

done.
___
*[`crates/blockifier/src/block_execution.rs` line 37 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpO3uJX9ix8E1Hj9gMX:-NpTl3qB6K0fs0182iM5:b-45nic0) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c689b5a8fabe58ee40e984513ebc131ce4b60b5/crates/blockifier/src/block_execution.rs#L37)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we want to check that it's larger than `10`?
</blockquote></details>

I think it's ok like this because anyway the entity that calls this function is trusted to send the correct block_hash and number , we don't check them. 
___
*[`crates/blockifier/src/block_execution.rs` line 40 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpO2u6EBhTdv6Tn6Xtg:-NpTorOPDRtgSID_AYwz:b-ukngq9) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c689b5a8fabe58ee40e984513ebc131ce4b60b5/crates/blockifier/src/block_execution.rs#L40)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can this be built using a constant c-tor/one that doesn't fail?
Also, give it a name: `block_hash_contract_address`.
</blockquote></details>

done.
wow great improvement.


<!-- Sent from Reviewable.io -->

2024-01-31 09:24 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/block_execution.rs` line 42 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpO3ib13U9MTj42mYRt:-NpTpNiR0qAmm1WRbMR_:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c689b5a8fabe58ee40e984513ebc131ce4b60b5/crates/blockifier/src/block_execution.rs#L42)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can this be built using a constant c-tor/one that doesn't fail?
Also, give it a name: `block_number_as_storage_key`.
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2024-01-31 11:01 UTC, elintul requested changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/blockifier/src/block_execution.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpFH2Cw2Vh4-WR5hTWb:-NpUALDN1X36l8uD-F1s:b-iwdljr) ([raw file](https://github.com/starkware-libs/blockifier/blob/9dd34c54e0f0a2ee324d07a0871b2e815ed1ad36/crates/blockifier/src/block_execution.rs#L47)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

done.
</blockquote></details>

Please use `if let` instead of `match` if possible, I think it's much clearer.
___
*[`crates/blockifier/src/block_execution.rs` line 37 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpO3uJX9ix8E1Hj9gMX:-NpUAXOu0l-0lDI6CI6S:b-7zi8tj) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c689b5a8fabe58ee40e984513ebc131ce4b60b5/crates/blockifier/src/block_execution.rs#L37)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think it's ok like this because anyway the entity that calls this function is trusted to send the correct block_hash and number , we don't check them.
</blockquote></details>

WDYM?


<!-- Sent from Reviewable.io -->

2024-01-31 11:22 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/block_execution.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpFH2Cw2Vh4-WR5hTWb:-NpUEDJzAt-F7Ziq2s6u:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/9dd34c54e0f0a2ee324d07a0871b2e815ed1ad36/crates/blockifier/src/block_execution.rs#L47)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please use `if let` instead of `match` if possible, I think it's much clearer.
</blockquote></details>

done.
___
*[`crates/blockifier/src/block_execution.rs` line 37 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpO3uJX9ix8E1Hj9gMX:-NpUDB192aDmPgJa6X5C:bhdekbq) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c689b5a8fabe58ee40e984513ebc131ce4b60b5/crates/blockifier/src/block_execution.rs#L37)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

The full nodes can call pre_process_block with any block number and any block hash.
we do not check the content of this struct, we just write it to the memory. 

So I don't think that checking specifically about block_number >10 adds much because they can write what they want anyway.


<!-- Sent from Reviewable.io -->

2024-02-03 13:06 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-02-04 13:41 UTC, elintul requested changes
> Reviewed 5 of 10 files at r9, 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/blockifier/src/block.rs` line 84 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-Npo3vpN4SPeT67qXcFD:-Npo3vpN4SPeT67qXcFE:b9sx6xr) ([raw file](https://github.com/starkware-libs/blockifier/blob/307291804d57f5cd5980b324d4622b92feb420a5/crates/blockifier/src/block.rs#L84)):*
> ```XML
>         block_info: block_info.clone(),
>         chain_info: chain_info.clone(),
>         versioned_constants: versioned_constants.clone(),
> ```

Are `clone`-s a must here?



_Code quote:_
```XML
        block_info: block_info.clone(),
        chain_info: chain_info.clone(),
        versioned_constants: versioned_constants.clone(),
```
___
*[`crates/blockifier/src/block_test.rs` line 30 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-Npo4DI55i1OAaPdjM4-:-Npo4DI55i1OAaPdjM40:b-n64wuy) ([raw file](https://github.com/starkware-libs/blockifier/blob/307291804d57f5cd5980b324d4622b92feb420a5/crates/blockifier/src/block_test.rs#L30)):*
> ```XML
>     let written_hash = state.get_storage_at(
>         ContractAddress::try_from(StarkFelt::from(constants::BLOCK_HASH_CONTRACT_ADDRESS)).unwrap(),
>         StorageKey::try_from(StarkFelt::from(block_number)).unwrap(),
> ```

Can you simplify the variable creation here as well?



_Code quote:_
```XML
        ContractAddress::try_from(StarkFelt::from(constants::BLOCK_HASH_CONTRACT_ADDRESS)).unwrap(),
        StorageKey::try_from(StarkFelt::from(block_number)).unwrap(),
```
___
*[`crates/blockifier/src/block_test.rs` line 49 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-Npo4QA00K-rbvNqARCb:-Npo4QA00K-rbvNqARCc:bwzp55b) ([raw file](https://github.com/starkware-libs/blockifier/blob/307291804d57f5cd5980b324d4622b92feb420a5/crates/blockifier/src/block_test.rs#L49)):*
> ```XML
>         )
>         .is_ok()
>     );
> ```

This is actually checked above, right?



_Code quote:_
```XML
    let block_info = BlockInfo {
        block_number: BlockNumber(constants::STORED_BLOCK_HASH_BUFFER - 1),
        ..Default::default()
    };
    assert!(
        pre_process_block(
            &mut state,
            None,
            &block_info,
            &ChainInfo::default(),
            &VersionedConstants::default()
        )
        .is_ok()
    );
```
___
*[`crates/blockifier/src/block_test.rs` line 62 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-Npo4UYQDf3WL29TGm1H:-Npo4UYQDf3WL29TGm1I:bck422f) ([raw file](https://github.com/starkware-libs/blockifier/blob/307291804d57f5cd5980b324d4622b92feb420a5/crates/blockifier/src/block_test.rs#L62)):*
> ```XML
>             &VersionedConstants::default()
>         )
>         .is_err()
> ```

Consider comparing error variants for future-proofing.



_Code quote:_
```XML
.is_err()
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 300 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpoL7Wt9ksHCWvMcTNp:-NpoL7Wt9ksHCWvMcTNq:b-te4w16) ([raw file](https://github.com/starkware-libs/blockifier/blob/307291804d57f5cd5980b324d4622b92feb420a5/crates/native_blockifier/src/py_block_executor.rs#L300)):*
> ```XML
> }
> 
> pub fn into_block_info_and_chain_info(
> ```

I think the previous name was better (encapsulation-wise).



_Code quote:_
```XML
into_block_info_and_chain_info
```


<!-- Sent from Reviewable.io -->

2024-02-05 06:20 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: 8 of 12 files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/block.rs` line 84 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-Npo3vpN4SPeT67qXcFD:-NprrEL639RSGa1n3lhG:byiid6a) ([raw file](https://github.com/starkware-libs/blockifier/blob/307291804d57f5cd5980b324d4622b92feb420a5/crates/blockifier/src/block.rs#L84)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are `clone`-s a must here?
</blockquote></details>

changed it a bit to avoid 2 clones. still had to use a clone for the versioned_constants since it originally belonged to a mutable reference and doesn't implement the copy trait.
___
*[`crates/blockifier/src/block_test.rs` line 30 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-Npo4DI55i1OAaPdjM4-:-NprtdCn9t4Wc1WD5Iq8:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/307291804d57f5cd5980b324d4622b92feb420a5/crates/blockifier/src/block_test.rs#L30)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you simplify the variable creation here as well?
</blockquote></details>

done.
___
*[`crates/blockifier/src/block_test.rs` line 49 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-Npo4QA00K-rbvNqARCb:-NprqcIW0mZ0CE3bRJpX:bip3x5h) ([raw file](https://github.com/starkware-libs/blockifier/blob/307291804d57f5cd5980b324d4622b92feb420a5/crates/blockifier/src/block_test.rs#L49)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This is actually checked above, right?
</blockquote></details>

yes, to be honest Gilad told me to add it for readability  , but I'll happily delete it.
___
*[`crates/blockifier/src/block_test.rs` line 62 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-Npo4UYQDf3WL29TGm1H:-Npru-Bv2C4LPEraK6sO:b-tnizcz) ([raw file](https://github.com/starkware-libs/blockifier/blob/307291804d57f5cd5980b324d4622b92feb420a5/crates/blockifier/src/block_test.rs#L62)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider comparing error variants for future-proofing.
</blockquote></details>

I can't because the error can't implement the partialEq trait.
Do we have some workaround for that? The Full node had a macro assert_match to deal with these kind of problems.
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 300 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpoL7Wt9ksHCWvMcTNp:-NpruOv-6UxtXIdYwpd1:b-33wq5z) ([raw file](https://github.com/starkware-libs/blockifier/blob/307291804d57f5cd5980b324d4622b92feb420a5/crates/native_blockifier/src/py_block_executor.rs#L300)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think the previous name was better (encapsulation-wise).
</blockquote></details>

changed it back.
done


<!-- Sent from Reviewable.io -->

2024-02-05 07:31 UTC, elintul requested changes
> Reviewed 2 of 4 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/blockifier/src/block_test.rs` line 49 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-Npo4QA00K-rbvNqARCb:-Nps9pB549ncaYo-IgLG:b9uvsr6) ([raw file](https://github.com/starkware-libs/blockifier/blob/307291804d57f5cd5980b324d4622b92feb420a5/crates/blockifier/src/block_test.rs#L49)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

yes, to be honest Gilad told me to add it for readability  , but I'll happily delete it.
</blockquote></details>

I would pass an explicit block number in the test case above and add a comment about it also checking positive flow of pre-processing the block inside the allowed block number interval. 
___
*[`crates/blockifier/src/block_test.rs` line 62 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-Npo4UYQDf3WL29TGm1H:-NpsABeM7CUlJ6Qfu9uV:bsb0xnn) ([raw file](https://github.com/starkware-libs/blockifier/blob/307291804d57f5cd5980b324d4622b92feb420a5/crates/blockifier/src/block_test.rs#L62)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I can't because the error can't implement the partialEq trait.
Do we have some workaround for that? The Full node had a macro assert_match to deal with these kind of problems.
</blockquote></details>

Not sure I understand the problem, can you elaborate?
Also, PTAL at other places in the code, I think we match strings


<!-- Sent from Reviewable.io -->

2024-02-05 09:11 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/block_test.rs` line 49 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-Npo4QA00K-rbvNqARCb:-NpsWI4KDNP1bRFQDqMw:b-5is48r) ([raw file](https://github.com/starkware-libs/blockifier/blob/307291804d57f5cd5980b324d4622b92feb420a5/crates/blockifier/src/block_test.rs#L49)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I would pass an explicit block number in the test case above and add a comment about it also checking positive flow of pre-processing the block inside the allowed block number interval.
</blockquote></details>

Actually the test case that I deleted was not the same, so I brought it back.
now we have three test cases: 
1. pre_process good flows - with block_number =10 and block_hash != None
2. Pre_process  good flow -  with block_number<10 and block_hash == None
3. pre_process bad flow - with block_number=10 and block_hash==None

also added what you asked.
done.
___
*[`crates/blockifier/src/block_test.rs` line 62 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-Npo4UYQDf3WL29TGm1H:-NpsPuXFCfBimbjkIBPh:b-vxhsoh) ([raw file](https://github.com/starkware-libs/blockifier/blob/307291804d57f5cd5980b324d4622b92feb420a5/crates/blockifier/src/block_test.rs#L62)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure I understand the problem, can you elaborate?
Also, PTAL at other places in the code, I think we match strings
</blockquote></details>

found a reference, done.


<!-- Sent from Reviewable.io -->

2024-02-05 09:13 UTC, elintul submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-:-NpsXkZA7E0HFpdHstNo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-02-05 10:44 UTC, elintul approved these changes
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-02-05 10:45 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpsrnVj6qZkVUgcZM9X:-NpsrnVj6qZkVUgcZM9Y:b-uwynae) (no related file):*
How come this PR is mergeable with coverage failing?

___


<!-- Sent from Reviewable.io -->

2024-02-05 10:46 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @Yael-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1387#-NpsrnVj6qZkVUgcZM9X:-Npss9o8-IjZbXtlPkRU:b-m113j0) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How come this PR is mergeable with coverage failing?
</blockquote></details>

@giladchase 

___


<!-- Sent from Reviewable.io -->

2024-02-05 11:37 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1387)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-02-05 11:38 UTC, merged