Use gas costs only from `VersionedConstants`
starkware-libs/blockifier pull request #1392
Opened 2024-01-29 06:59 UTC by giladchase

- Remove from constants module and replace all usages with `VersionedConstants#gas_cost(..)`
  - Move all comments from the constants module into the const whitelist in `VersionedConstants`.
- Add gas cost getter to `EntryPointExecutionContext`, for readability
  - enclose in closure inside hint_processor.rs for even more brevity.
- Move `Transaction::Initial_gas` into `VersionedConstants`: it is now derived from the constants json.
- No other logic changes.

2024-01-29 07:42 UTC, elintul requested changes
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1392)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1392#-NpJ9U7X4Zptn76KnpuX:-NpJ9U7X4Zptn76KnpuY:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/a32eb8911a7d0ba47252af937325647480e639a3/crates/blockifier/src/versioned_constants.rs#L54)):*
> ```XML
>         let os_consts = &self.starknet_os_constants;
> 
>         os_consts.gas_costs["initial_gas_cost"] - os_consts.gas_costs["transaction_gas_cost"]
> ```





_Suggestion:_
```XML
        let os_consts = &self.starknet_os_constants;
        os_consts.gas_costs["initial_gas_cost"] - os_consts.gas_costs["transaction_gas_cost"]
```
___
*[`crates/blockifier/src/abi/constants.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1392#-NpJ9lBG7MTxoQkiF3oV:-NpJ9lBG7MTxoQkiF3oW:b-9ukirf) ([raw file](https://github.com/starkware-libs/blockifier/blob/e74a992f48c00a93cbf3a20b3bd196d6d65619e9/crates/blockifier/src/abi/constants.rs#L41)):*
> ```XML
> 
> // Gas Cost.
> // See documentation in core/os/constants.cairo.
> ```

Is moving those part of an unmerged PR?


<!-- Sent from Reviewable.io -->

2024-01-29 12:45 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1392)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/abi/constants.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1392#-NpJ9lBG7MTxoQkiF3oV:-NpKEHFA2_2mEQMzdig5:bljpoys) ([raw file](https://github.com/starkware-libs/blockifier/blob/e74a992f48c00a93cbf3a20b3bd196d6d65619e9/crates/blockifier/src/abi/constants.rs#L41)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is moving those part of an unmerged PR?
</blockquote></details>

WDYM by part of an unmerged PR?

I'm removing them because they are now stored in the `StarknetOSConstants`, and are accessible via `versioned_constants.get_gas_cost("name_of_const")`.
That is, they are no longer `const`s, since they are dynamically loaded from a json file.


<!-- Sent from Reviewable.io -->

2024-02-04 12:21 UTC, elintul approved these changes
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1392)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-02-04 12:21 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1392#-:-Npo3Apy0Bln81-LYKVP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-02-05 12:40 UTC, elintul submitted a review, later dismissed
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1392)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-02-05 15:06 UTC, noaov1 submitted a review, later dismissed
> Reviewed 4 of 14 files at r1, 6 of 11 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1392)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase)

___
*[`crates/blockifier/src/test_utils.rs` line 215 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1392#-NpteiusCF2qbCo_4dFr:-NpteiusCF2qbCo_4dFs:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/406eda992e0f23705b848a8b46d4e2e062f38613/crates/blockifier/src/test_utils.rs#L215)):*
> ```XML
>         caller_address: ContractAddress::default(),
>         call_type: CallType::Call,
>         initial_gas: VersionedConstants::create_for_account_testing().gas_cost("initial_gas_cost"),
> ```





_Suggestion:_
```XML
VersionedConstants::create_for_testing().gas_cost("initial_gas_cost"),
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 81 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1392#-NptnTIS9El53a34oiFv:-NptnTITEFRB-TEejBej:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/406eda992e0f23705b848a8b46d4e2e062f38613/crates/blockifier/src/transaction/transactions_test.rs#L81)):*
> ```XML
> 
> #[fixture]
> fn initial_gas() -> u64 {
> ```





_Suggestion:_
```XML
fn tx_initial_gas() -> u64 {
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1392#-NptnD-g1DbLwPJQ1QJl:-NptnD-g1DbLwPJQ1QJm:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/406eda992e0f23705b848a8b46d4e2e062f38613/crates/blockifier/src/transaction/transactions_test.rs#L82)):*
> ```XML
> #[fixture]
> fn initial_gas() -> u64 {
>     VersionedConstants::latest_constants().tx_initial_gas()
> ```

?



_Suggestion:_
```XML
    VersionedConstants::create_for_testing().tx_initial_gas()
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 313 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1392#-NptnaPk-qwMxRfnncwt:-NptnaPk-qwMxRfnncwu:b998uvo) ([raw file](https://github.com/starkware-libs/blockifier/blob/406eda992e0f23705b848a8b46d4e2e062f38613/crates/blockifier/src/transaction/transactions_test.rs#L313)):*
> ```XML
>         validate_gas_consumed: 0,
>         execute_gas_consumed: 0,
>         inner_call_initial_gas: VersionedConstants::create_for_account_testing().gas_cost("initial_gas_cost"),
> ```

Create a fixture?



_Code quote:_
```XML
inner_call_initial_gas: VersionedConstants::create_for_account_testing().gas_cost("initial_gas_cost"),
```


<!-- Sent from Reviewable.io -->

2024-02-05 16:06 UTC, noaov1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1392#-:-Npu0Ds4DINOUk5wQ_rt:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 88 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1392#-Npu01Pa8zTGXt0GaH6Y:-Npu01Pa8zTGXt0GaH6Z:brslu85) ([raw file](https://github.com/starkware-libs/blockifier/blob/1af90d31e5d5ce123486355ef7668f747da567dc/crates/blockifier/src/transaction/transactions_test.rs#L88)):*
> ```XML
> fn versioned_constants_for_account_testing() -> VersionedConstants {
>     VersionedConstants::create_for_account_testing()
> }
> ```

Create a fixture for versioned constants?



_Code quote:_
```XML
#[fixture]
fn tx_initial_gas() -> u64 {
    VersionedConstants::create_for_testing().tx_initial_gas()
}

#[fixture]
fn versioned_constants_for_account_testing() -> VersionedConstants {
    VersionedConstants::create_for_account_testing()
}
```


<!-- Sent from Reviewable.io -->

2024-02-05 16:10 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1392)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 88 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1392#-Npu01Pa8zTGXt0GaH6Y:-Npu1Bxn2I3ApvNboZgX:b7hpazh) ([raw file](https://github.com/starkware-libs/blockifier/blob/1af90d31e5d5ce123486355ef7668f747da567dc/crates/blockifier/src/transaction/transactions_test.rs#L88)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Create a fixture for versioned constants?
</blockquote></details>

Called explicitly later down, complicates this.


<!-- Sent from Reviewable.io -->

2024-02-05 16:10 UTC, merged