fix(build): fix build for mac + unused import
starkware-libs/blockifier pull request #1406
Opened 2024-01-31 11:24 UTC by LucasLvy

It's impossible to build the native blockifier on a mac without those flags.
Import constant only for the necessary feature otherwise compilation fails

2024-01-31 16:59 UTC, elintul requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1406)* status: all files reviewed, 2 unresolved discussions (waiting on @LucasLvy)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1406#-NpVSSfc0ZXrfTmjHQs9:-NpVSSfd4vi6lSnV692s:b-yd4t6z) (no related file):*
Please open this PR on top of `main-v0.13.1`.

___
___
*[`.cargo/config.toml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1406#-NpVSZsz15VAjkky_u06:-NpVSZsz15VAjkky_u07:bb1az1f) ([raw file](https://github.com/starkware-libs/blockifier/blob/197cbaf4873458dfb16ad0a2f6d5e12a06b1a9de/.cargo/config.toml#L5)):*
> ```TOML
> # This should be large enough for `MAX_ENTRY_POINT_RECURSION_DEPTH` recursive entry point calls.
> RUST_MIN_STACK = "4194304" #  4 MiB
> ```

@alon-dotan-starkware - can you PTAL?


<!-- Sent from Reviewable.io -->

2024-02-05 11:13 UTC, LucasLvy reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1406)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware)

___
*[`.cargo/config.toml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1406#-NpVSZsz15VAjkky_u06:-NpsyEuA9fTFWpTvXV2a:b-1i8ufu) ([raw file](https://github.com/starkware-libs/blockifier/blob/197cbaf4873458dfb16ad0a2f6d5e12a06b1a9de/.cargo/config.toml#L5)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

@alon-dotan-starkware - can you PTAL?
</blockquote></details>

Note that i didn't touch the stack size, i only added the flags for compilation on macs


<!-- Sent from Reviewable.io -->

2024-02-05 11:18 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1406)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware and @LucasLvy)

___
*[`.cargo/config.toml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1406#-NpVSZsz15VAjkky_u06:-NpszLew6ydG1HK6C-y4:bj4x2o) ([raw file](https://github.com/starkware-libs/blockifier/blob/197cbaf4873458dfb16ad0a2f6d5e12a06b1a9de/.cargo/config.toml#L5)):*
<details><summary><i>Previously, LucasLvy (Lucas @ StarkWare) wrote…</i></summary><blockquote>

Note that i didn't touch the stack size, i only added the flags for compilation on macs
</blockquote></details>

Can you elaborate on them? I'm unfamiliar.


<!-- Sent from Reviewable.io -->

2024-02-05 11:39 UTC, LucasLvy reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1406)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware)

___
*[`.cargo/config.toml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1406#-NpVSZsz15VAjkky_u06:-Npt2bXxA5erDbqgqWvE:b8yg0uj) ([raw file](https://github.com/starkware-libs/blockifier/blob/197cbaf4873458dfb16ad0a2f6d5e12a06b1a9de/.cargo/config.toml#L5)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you elaborate on them? I'm unfamiliar.
</blockquote></details>

It prevents Pyo3 from linking with `libpython` (default behavior) which is forbidden on macos. [Here](https://pyo3.rs/v0.20.2/building_and_distribution.html?highlight=link-arg%3D-undefined#the-extension-module-feature) is their doc about it


<!-- Sent from Reviewable.io -->

2024-02-05 14:18 UTC, LucasLvy reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1406)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware)

___
*[`.cargo/config.toml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1406#-NpVSZsz15VAjkky_u06:-NptcYVZ-d14fOVoO76d:bc4d2in) ([raw file](https://github.com/starkware-libs/blockifier/blob/197cbaf4873458dfb16ad0a2f6d5e12a06b1a9de/.cargo/config.toml#L5)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`native_blockifier` is not a published crate and shouldn't be used outside SW, it only exists for integration with our main repo.; how does it affect Madara?
</blockquote></details>

It does not affect madara at all, it just doesn't build on a mac


<!-- Sent from Reviewable.io -->

2024-02-06 12:28 UTC, alon-dotan-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1406)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @LucasLvy)

___
*[`.cargo/config.toml` line 5 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1406#-NpVSZsz15VAjkky_u06:-NpyN_b525TmL4QITvP8:b-l71stv) ([raw file](https://github.com/starkware-libs/blockifier/blob/197cbaf4873458dfb16ad0a2f6d5e12a06b1a9de/.cargo/config.toml#L5)):*
<details><summary><i>Previously, LucasLvy (Lucas @ StarkWare) wrote…</i></summary><blockquote>

It does not affect madara at all, it just doesn't build on a mac
</blockquote></details>

Looks legit its compile flags affect only Mac archs


<!-- Sent from Reviewable.io -->

2024-02-06 12:39 UTC, alon-dotan-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1406#-:-NpyQSsyAbOF-RTn5SQu:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @LucasLvy)



<!-- Sent from Reviewable.io -->

2024-02-07 13:32 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1406#-:-Nq2lFpF2vw-n5qR5Miy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LucasLvy)



<!-- Sent from Reviewable.io -->

2024-02-07 14:37 UTC, LucasLvy commented
Changed base branch to be `main-v0.13.1`

2024-02-07 14:46 UTC, elintul approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1406)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LucasLvy)



<!-- Sent from Reviewable.io -->

2024-02-07 14:51 UTC, merged