feat(execution): implement a versioned storage data structure for imp…
starkware-libs/blockifier pull request #1421
Opened 2024-02-04 08:03 UTC by MohammadNassar1

…lementing concurrency

2024-02-04 16:51 UTC, elintul submitted a review, later dismissed
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: all files reviewed, 6 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Npp0H2X4jMdkXnkO_ZW:-Npp0H2X4jMdkXnkO_ZX:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1fccc19cfa5e4d2fadc41dcccc3971893880d2/crates/blockifier/src/concurrency/versioned_storage.rs#L11)):*
> ```XML
> pub mod test;
> 
> type ReadCallback<CellId, V> = dyn Fn(CellId) -> Option<V>;
> ```





_Suggestion:_
```XML
K
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Npp0Kwg6KgbhDBgVsIV:-Npp0Kwg6KgbhDBgVsIW:bb76mu4) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1fccc19cfa5e4d2fadc41dcccc3971893880d2/crates/blockifier/src/concurrency/versioned_storage.rs#L11)):*
> ```XML
> pub mod test;
> 
> type ReadCallback<CellId, V> = dyn Fn(CellId) -> Option<V>;
> ```

Why?



_Code quote:_
```XML
dyn
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Npp0O7R6PodHg0ZYNLz:-Npp0O7R6PodHg0ZYNM-:b-93r5aa) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1fccc19cfa5e4d2fadc41dcccc3971893880d2/crates/blockifier/src/concurrency/versioned_storage.rs#L13)):*
> ```XML
> type ReadCallback<CellId, V> = dyn Fn(CellId) -> Option<V>;
> 
> pub struct VersionedStorage<V> {
> ```

Please add a succinct docstring.



_Code quote:_
```XML
VersionedStorage
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Npp0kcN9IhuXWgwAZWd:-Npp0kcOEZ78Nw4sbu-9:b-7mq6ae) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1fccc19cfa5e4d2fadc41dcccc3971893880d2/crates/blockifier/src/concurrency/versioned_storage.rs#L35)):*
> ```XML
>     pub fn _get_cell(&mut self, cell_id: CellId) -> &mut VersionedCell<V> {
>         self.versioned_cells.entry(cell_id).or_insert_with(|| {
>             let base_value = (self.base_value_read_callback)(cell_id).unwrap();
> ```

Is it possible?



_Suggestion:_
```XML
self.base_value_read_callback
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Npp0nPY0bskoXwZDaUN:-Npp0nPY0bskoXwZDaUO:bijr7wz) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1fccc19cfa5e4d2fadc41dcccc3971893880d2/crates/blockifier/src/concurrency/versioned_storage.rs#L35)):*
> ```XML
>     pub fn _get_cell(&mut self, cell_id: CellId) -> &mut VersionedCell<V> {
>         self.versioned_cells.entry(cell_id).or_insert_with(|| {
>             let base_value = (self.base_value_read_callback)(cell_id).unwrap();
> ```

Please define an error enum and return a result.



_Code quote:_
```XML
unwrap()
```
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 6 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Npp0wHG0vhNru0hVAhZ:-Npp0wHHBp7ACFMuft6d:b-qwjkb2) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1fccc19cfa5e4d2fadc41dcccc3971893880d2/crates/blockifier/src/concurrency/versioned_storage_test.rs#L6)):*
> ```XML
> 
> #[test]
> fn test_versioned_cell() {
> ```

Please make sure the test is equivalent to the Pythonic one (inc. comments).
If you think they should be different, please explain why.



_Code quote:_
```XML
test_versioned_cell
```


<!-- Sent from Reviewable.io -->

2024-02-05 05:27 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: all files reviewed, 7 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 3 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NpriplTBJxrFqIuM_np:-NpriplTBJxrFqIuM_nq:b-mkdqes) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1fccc19cfa5e4d2fadc41dcccc3971893880d2/crates/blockifier/src/concurrency/versioned_storage.rs#L3)):*
> ```XML
> use std::collections::HashMap;
> 
> use super::versioned_cell::{VersionId, VersionedCell};
> ```

Absolute imports plz.

You can add "rust-analyzer.imports.prefix": "crate",` to your settings.json and save the file, it should replace them with an absolute path import.



_Code quote:_
```XML
use super::versioned_cell::{VersionId, VersionedCell};
```


<!-- Sent from Reviewable.io -->

2024-02-05 07:47 UTC, Yoni-Starkware reviewed
I don't don't think we need these structs in Rust impl (once we don't need to keep track on reads).

Consider (and think this through before) using a simple variant of CachedState:

```rust
pub struct VersionedStateCache {

// Reader's cached information; initial values, read before any write operation (per cell).
Same....

// Writer's cached information.
nonce_writes: HashMap<ContractAddress, BTreeMap<VersionId, Nonce>>,
class_hash_writes: HashMap<ContractAddress, BTreeMap<VersionId, ClassHash>>,
storage_writes: HashMap<StorageEntry, BTreeMap<VersionId, StarkFelt>>,
compiled_class_hash_writes: HashMap<ClassHash, BTreeMap<VersionId, CompiledClassHash>>,

}
```

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-:-NpsBpSDDDnswp6SDv2h:b-ryrylx)* status: all files reviewed, 7 unresolved discussions (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-02-05 07:49 UTC, elintul reviewed
Can you elaborate on how it relates to read tracking? 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-:-NpsEMdsE5sTnlx2hwWC:bkzpzdi)* status: all files reviewed, 7 unresolved discussions (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-02-05 07:58 UTC, Yoni-Starkware reviewed
Maybe it doesn't. It made the python impl more complex, so maybe the complex structures are not needed now. 
I'm saying we should think about the simplest required structure, given the required functionality. 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-:-NpsEu02DsW6nYM47vdf:bro0odz)* status: all files reviewed, 7 unresolved discussions (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-02-08 06:41 UTC, Yoni-Starkware reviewed
@MohammadNassar1, I think that versioned cell is for sure redundant, and versioned storage may be nice to save some code duplication. But it is similar to the regular CachedState in this sense. I.e., why not do it also for Cached state?  

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-:-Nq6RCsD5DQwzAeuYugd:b9slq4x)* status: all files reviewed, 7 unresolved discussions (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-02-19 14:22 UTC, giladchase requested changes
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 2 of 4 files reviewed, 14 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/lib.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr0_tVOCMZqtwch_Fhs:-Nr0_tVOCMZqtwch_Fht:b6gmw67) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f16a9cbcc6f721ba188a8750978b536247d7398/crates/blockifier/src/lib.rs#L3)):*
> ```XML
> pub mod abi;
> pub mod blockifier;
> pub mod concurrency;
> ```

@elintul Are we planning on feature-gating this module? (use `cfg(feature = "concurrency")` to not compile it for users that can't/won't run concurrently)

We can worry about it later, but it might be easier to start the separation now, to save headaches later.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr0fGe9DzEpbkZBAlQQ:-Nr0fGe9DzEpbkZBAlQR:brvwusq) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f16a9cbcc6f721ba188a8750978b536247d7398/crates/blockifier/src/concurrency/versioned_storage.rs#L18)):*
> ```XML
>     V: Clone + std::fmt::Debug,
> {
>     pub base_value_read_callback: Box<ReadCallback<K, V>>,
> ```

The box is because the callback is generic so it can't figure out what the size of this field would be otherwise?



_Code quote:_
```XML
    pub base_value_read_callback: Box<ReadCallback<K, V>>,
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr0dXQtDZTV3PhaRJ9b:-Nr0dXQtDZTV3PhaRJ9c:b2ni0zo) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f16a9cbcc6f721ba188a8750978b536247d7398/crates/blockifier/src/concurrency/versioned_storage.rs#L32)):*
> ```XML
> 
>     pub fn read(&mut self, cell_id: K, version: Version) -> V {
>         dbg!("version: ", version);
> ```

dbg
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 33 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr0dq0cChkHCwQobAlz:-Nr0dq0cChkHCwQobAm-:b-wpvu0r) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f16a9cbcc6f721ba188a8750978b536247d7398/crates/blockifier/src/concurrency/versioned_storage.rs#L33)):*
> ```XML
>     pub fn read(&mut self, cell_id: K, version: Version) -> V {
>         dbg!("version: ", version);
>         match self.writes.entry(cell_id.clone()).or_default().range(..=version).next_back() {
> ```

do we need a clone here?



_Code quote:_
```XML
cell_id.clone()
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 34 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr0eHDZDqH1NqP1V5ed:-Nr0eHDZDqH1NqP1V5ee:b-h9ywwp) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f16a9cbcc6f721ba188a8750978b536247d7398/crates/blockifier/src/concurrency/versioned_storage.rs#L34)):*
> ```XML
>         dbg!("version: ", version);
>         match self.writes.entry(cell_id.clone()).or_default().range(..=version).next_back() {
>             Some((_, value)) => value.clone(),
> ```

Is it possible for this function to return the reference, and let the caller decide if to clone or not?



_Code quote:_
```XML
        Some((_, value)) => value.clone(),
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr0ezrcB3HCa_dB49Qb:-Nr0ezrcB3HCa_dB49Qc:b1tdqf2) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f16a9cbcc6f721ba188a8750978b536247d7398/crates/blockifier/src/concurrency/versioned_storage.rs#L37)):*
> ```XML
>             None => {
>                 let base_value = (self.base_value_read_callback)(cell_id);
>                 base_value.expect("Base value read callback returned an error")
> ```

can we enforce this at the callback level?
That is, make the type return a value, rather than a result, and have the call back do the expect (not sure it makes sense, just asking here)



_Code quote:_
```XML
                base_value.expect("Base value read callback returned an error")
```
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 17 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr0cXvOD1H4F9NQ3H2z:-Nr0cXvOD1H4F9NQ3H3-:b1829i8) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f16a9cbcc6f721ba188a8750978b536247d7398/crates/blockifier/src/concurrency/versioned_storage_test.rs#L17)):*
> ```XML
>     storage.write(1, 1, 42);
>     let value = storage.read(1, 2);
>     assert_eq!(value, 42);
> ```

Maybe add another case with a larger number, say read(1,123), to make it clear that it doesn't have to be the sequential number after 1.



_Code quote:_
```XML
    // Write.
    storage.write(1, 1, 42);
    let value = storage.read(1, 2);
    assert_eq!(value, 42);
```
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 21 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr0cPJzB4zr2Gtdf7TC:-Nr0cPJzB4zr2Gtdf7TD:b-w3veva) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f16a9cbcc6f721ba188a8750978b536247d7398/crates/blockifier/src/concurrency/versioned_storage_test.rs#L21)):*
> ```XML
>     // Read initial value.
>     let value = storage.read(5, 1);
>     assert_eq!(value, 31);
> ```

Is this case the same as the first one?



_Code quote:_
```XML
    // Read initial value.
    let value = storage.read(5, 1);
    assert_eq!(value, 31);
```


<!-- Sent from Reviewable.io -->

2024-02-19 16:04 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 2 of 4 files reviewed, 14 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 34 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr0eHDZDqH1NqP1V5ed:-Nr15MeO9iJ9XV9bY32O:b3ucvs6) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f16a9cbcc6f721ba188a8750978b536247d7398/crates/blockifier/src/concurrency/versioned_storage.rs#L34)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Is it possible for this function to return the reference, and let the caller decide if to clone or not?
</blockquote></details>

This deref clones the the felt, right?
https://github.com/starkware-libs/blockifier/blob/d26f4b8a5bbb0b8c9db1226928d18c13016dae0f/crates/blockifier/src/state/cached_state.rs#L205

It's not possible for a deref of an immutable reference to move the value, right? 
If so, why * and not clone?


<!-- Sent from Reviewable.io -->

2024-02-20 09:26 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 2 of 4 files reviewed, 14 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 34 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr0eHDZDqH1NqP1V5ed:-Nr4m5JqCUngSg69bAD8:bqd3iwh) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f16a9cbcc6f721ba188a8750978b536247d7398/crates/blockifier/src/concurrency/versioned_storage.rs#L34)):*
> This deref clones the the felt, right?

Ya, though it `Copy`'s it to be exact; `clone` is only called explicitly, never implicitly as a result of another op, like the way `Copy` was trigged here.

> It's not possible for a deref of an immutable reference to move the value, right?

Correct

> If so, why \* and not clone?

Cause `StarFelt` implements `Copy` which is basically an "implicit clone that is basically free, and that the compiler will use automatically whenever it hits an ownership issue that a copy can solve".
Similar to how if you dereference a &u32, you expect the compiler to automatically clone the value, since it's a very cheap op.

Therefore, since it is so cheap to copy, in general we never clone a `Copy` type (or even pass it by reference to functions, always by value), because we consider it to be as cheap as a primitive.

In other words, a `clone()` typically implies an expensive op (with some exceptions like `Arc`s), so it isn't used on `Copy` types, which are always cloned implicitely via `*`, or by unpacking structs/collections, or passing by-value to functions.

(BTW, if StarkFelt hand't been a copy type, and we'd try to * a &StarkFelt type, we'd get a compiler error for the exact reason you stated, since it's an immutable ref.)


<!-- Sent from Reviewable.io -->

2024-02-20 13:54 UTC, MohammadNassar1 reviewed
Following our discussion, we have settled on two hierarchies:

1.  `VersionedStorage`: This hierarchy provides a generic API for reading and writing data from storage (e.g, nonce and class hash, etc). It helps eliminate code duplication.
2.  `VersionedState`: This hierarchy extends the API to include access to all four types of storage, and implements the state API i.e.,`get_storage_at`, `get_nonce_at`, etc. While also considering the transaction version.

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-:-Nr4mHVk3lvdDLKmA0-Z:be2e0n7)* status: 1 of 6 files reviewed, 12 unresolved discussions (waiting on @elintul, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/lib.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr0_tVOCMZqtwch_Fhs:-Nr4s9Xk4e4b7n4Z78nW:bl1fsdv) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f16a9cbcc6f721ba188a8750978b536247d7398/crates/blockifier/src/lib.rs#L3)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

@elintul Are we planning on feature-gating this module? (use `cfg(feature = "concurrency")` to not compile it for users that can't/won't run concurrently)

We can worry about it later, but it might be easier to start the separation now, to save headaches later.
</blockquote></details>

Good point!
I've added a feature for concurrency.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 3 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NpriplTBJxrFqIuM_np:-NqhQZls6Efpdsb-1FeE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1fccc19cfa5e4d2fadc41dcccc3971893880d2/crates/blockifier/src/concurrency/versioned_storage.rs#L3)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Absolute imports plz.

You can add "rust-analyzer.imports.prefix": "crate",` to your settings.json and save the file, it should replace them with an absolute path import.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Npp0Kwg6KgbhDBgVsIV:-Nr4vpWg6zWq9F2BxrLF:b-tj8vw2) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1fccc19cfa5e4d2fadc41dcccc3971893880d2/crates/blockifier/src/concurrency/versioned_storage.rs#L11)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

As the compiler does not know the concrete type that is being passed.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Npp0O7R6PodHg0ZYNLz:-Nq1H0ca4t8WX-AJy0JA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1fccc19cfa5e4d2fadc41dcccc3971893880d2/crates/blockifier/src/concurrency/versioned_storage.rs#L13)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please add a succinct docstring.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Npp0nPY0bskoXwZDaUN:-Nr5cOcbDNRN6XKZcSlj:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1fccc19cfa5e4d2fadc41dcccc3971893880d2/crates/blockifier/src/concurrency/versioned_storage.rs#L35)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please define an error enum and return a result.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr0fGe9DzEpbkZBAlQQ:-Nr4xx8B-IFLwDaTYnIj:b-1vijnq) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f16a9cbcc6f721ba188a8750978b536247d7398/crates/blockifier/src/concurrency/versioned_storage.rs#L18)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

The box is because the callback is generic so it can't figure out what the size of this field would be otherwise?
</blockquote></details>

Exactly!
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr0dXQtDZTV3PhaRJ9b:-Nr4kWq99e9350up_izP:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f16a9cbcc6f721ba188a8750978b536247d7398/crates/blockifier/src/concurrency/versioned_storage.rs#L32)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

dbg
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 33 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr0dq0cChkHCwQobAlz:-Nr4y9s44fo347GZ1w_9:b-ebp87v) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f16a9cbcc6f721ba188a8750978b536247d7398/crates/blockifier/src/concurrency/versioned_storage.rs#L33)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

do we need a clone here?
</blockquote></details>

It is used below after being moved.
Removed, I decided to add a Copy trait for K.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 34 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr0eHDZDqH1NqP1V5ed:-Nr5YvIE8tLKe8EmvO10:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f16a9cbcc6f721ba188a8750978b536247d7398/crates/blockifier/src/concurrency/versioned_storage.rs#L34)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

> This deref clones the the felt, right?

Ya, though it `Copy`'s it to be exact; `clone` is only called explicitly, never implicitly as a result of another op, like the way `Copy` was trigged here.

> It's not possible for a deref of an immutable reference to move the value, right?

Correct

> If so, why \* and not clone?

Cause `StarFelt` implements `Copy` which is basically an "implicit clone that is basically free, and that the compiler will use automatically whenever it hits an ownership issue that a copy can solve".
Similar to how if you dereference a &u32, you expect the compiler to automatically clone the value, since it's a very cheap op.

Therefore, since it is so cheap to copy, in general we never clone a `Copy` type (or even pass it by reference to functions, always by value), because we consider it to be as cheap as a primitive.

In other words, a `clone()` typically implies an expensive op (with some exceptions like `Arc`s), so it isn't used on `Copy` types, which are always cloned implicitely via `*`, or by unpacking structs/collections, or passing by-value to functions.

(BTW, if StarkFelt hand't been a copy type, and we'd try to * a &StarkFelt type, we'd get a compiler error for the exact reason you stated, since it's an immutable ref.)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr0ezrcB3HCa_dB49Qb:-Nr5c6xH9KAYu2savJIR:b-o6zgn5) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f16a9cbcc6f721ba188a8750978b536247d7398/crates/blockifier/src/concurrency/versioned_storage.rs#L37)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

can we enforce this at the callback level?
That is, make the type return a value, rather than a result, and have the call back do the expect (not sure it makes sense, just asking here)
</blockquote></details>

I would like the function to return a `stateError` if the key is not found.
What do you think?
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 6 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Npp0wHG0vhNru0hVAhZ:-Nr5mk3Y-tQWxbWLXLBg:b-bw8e14) ([raw file](https://github.com/starkware-libs/blockifier/blob/9c1fccc19cfa5e4 [...]

2024-02-20 13:54 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 1 of 6 files reviewed, 12 unresolved discussions (waiting on @elintul, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr0dXQtDZTV3PhaRJ9b:-Nr5n0F04PLn_UomWoMZ:b-hfpv0l) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f16a9cbcc6f721ba188a8750978b536247d7398/crates/blockifier/src/concurrency/versioned_storage.rs#L32)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2024-02-21 08:50 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 1 of 6 files reviewed, 7 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr0ezrcB3HCa_dB49Qb:-Nr9qp510rsxDes10GBr:b-hfghm4) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f16a9cbcc6f721ba188a8750978b536247d7398/crates/blockifier/src/concurrency/versioned_storage.rs#L37)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I would like the function to return a `stateError` if the key is not found.
What do you think?
</blockquote></details>

Sounds good
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr9ZJqh1oEiN9lpDIxC:-Nr9ZJqh1oEiN9lpDIxD:b5u6nnk) ([raw file](https://github.com/starkware-libs/blockifier/blob/b6d4b40ce9d0a8e73dba69cc52707b8dfa526555/crates/blockifier/src/concurrency/versioned_storage.rs#L33)):*
> ```XML
> 
>     pub fn read(&mut self, cell_id: K, version: Version) -> StateResult<&V> {
>         match self.writes.entry(cell_id).or_default().range(..=version).next_back() {
> ```

We should avoid `&mut self` on read-only APIs (we already made that mistake before...), it should be `&self` for reads.
A `&mut self` on reads is not intuitive, it limits the possibility of concurrent reads, and in general, &mut self is quite limiting.

So instead of `or_default`, either return the default by value (which should be relatively cheap?), or `Mutex` the `writes` field.

In fact, is this DB intended to be threadsafe? As in, will multiple threads be reading/writing into it concurrently? If so, then `writes` _should_ be `Mutex`'ed anyway.



_Code quote:_
```XML
    pub fn read(&mut self, cell_id: K, version: Version) -> StateResult<&V> {
        match self.writes.entry(cell_id).or_default().range(..=version).next_back() {
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr9lQu8D_SsvQUD10yj:-Nr9lQu8D_SsvQUD10yk:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b6d4b40ce9d0a8e73dba69cc52707b8dfa526555/crates/blockifier/src/concurrency/versioned_storage.rs#L34)):*
> ```XML
>     pub fn read(&mut self, cell_id: K, version: Version) -> StateResult<&V> {
>         match self.writes.entry(cell_id).or_default().range(..=version).next_back() {
>             Some((_, _value)) => Ok(_value),
> ```





_Suggestion:_
```XML
Some((_, value)) => Ok(value),
```


<!-- Sent from Reviewable.io -->

2024-02-21 11:56 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 1 of 6 files reviewed, 7 unresolved discussions (waiting on @elintul, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr0ezrcB3HCa_dB49Qb:-NrA5Vp0Erg4nAEqfdFd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f16a9cbcc6f721ba188a8750978b536247d7398/crates/blockifier/src/concurrency/versioned_storage.rs#L37)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Sounds good
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 33 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr9ZJqh1oEiN9lpDIxC:-NrAVftw5ErMsdPLfUl1:bnukkg9) ([raw file](https://github.com/starkware-libs/blockifier/blob/b6d4b40ce9d0a8e73dba69cc52707b8dfa526555/crates/blockifier/src/concurrency/versioned_storage.rs#L33)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

We should avoid `&mut self` on read-only APIs (we already made that mistake before...), it should be `&self` for reads.
A `&mut self` on reads is not intuitive, it limits the possibility of concurrent reads, and in general, &mut self is quite limiting.

So instead of `or_default`, either return the default by value (which should be relatively cheap?), or `Mutex` the `writes` field.

In fact, is this DB intended to be threadsafe? As in, will multiple threads be reading/writing into it concurrently? If so, then `writes` _should_ be `Mutex`'ed anyway.
</blockquote></details>

I think for now I shouldn't use `or_default`, so I was able to avoid `mut` by removing the `or_default()`.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nr9lQu8D_SsvQUD10yj:-NrA5LHO1TUzk74dmTaI:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b6d4b40ce9d0a8e73dba69cc52707b8dfa526555/crates/blockifier/src/concurrency/versioned_storage.rs#L34)):*
> ```XML
>     pub fn read(&mut self, cell_id: K, version: Version) -> StateResult<&V> {
>         match self.writes.entry(cell_id).or_default().range(..=version).next_back() {
>             Some((_, _value)) => Ok(_value),
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-02-25 07:32 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 47 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NrU9ytM1BEpMB3tIv0y:-NrU9ytM1BEpMB3tIv0z:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/985e1fe582aa7cfc3758ac3dd26e1dd22870d8d5/crates/blockifier/src/concurrency/versioned_storage.rs#L47)):*
> ```XML
>                 match initial_value {
>                     Some(value) => Ok(Box::leak(Box::new(value))),
>                     None => Err(StateError::StateReadError(format!("{:?}", cell_id))),
> ```





_Suggestion:_
```XML
      None => Err(StateError::StateReadError(format!("{cell_id:?}")))
```


<!-- Sent from Reviewable.io -->

2024-02-29 16:24 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 47 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NrU9ytM1BEpMB3tIv0y:-Nrpf754-2G7wLSDby9j:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/985e1fe582aa7cfc3758ac3dd26e1dd22870d8d5/crates/blockifier/src/concurrency/versioned_storage.rs#L47)):*
> ```XML
>                 match initial_value {
>                     Some(value) => Ok(Box::leak(Box::new(value))),
>                     None => Err(StateError::StateReadError(format!("{:?}", cell_id))),
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-03-07 08:57 UTC, noaov1 reviewed
> Reviewed 1 of 5 files at r4, 1 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 4 of 6 files reviewed, 7 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 12 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsN6Mk77cCS_xvveiap:-NsN6Mk77cCS_xvveiaq:bq5z96g) ([raw file](https://github.com/starkware-libs/blockifier/blob/21583c916de81f6e2fc143137c07ff18d497a477/crates/blockifier/src/concurrency/versioned_storage.rs#L12)):*
> ```XML
> pub mod test;
> 
> pub type ReadCallback<K, V> = dyn Fn(K) -> Option<V>;
> ```

Can you please explain why it returns an option? 



_Code quote:_
```XML
pub type ReadCallback<K, V> = dyn Fn(K) -> Option<V>;
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 42 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsMz41REXXpKvvEQMTP:-NsMz41REXXpKvvEQMTQ:b71knti) ([raw file](https://github.com/starkware-libs/blockifier/blob/21583c916de81f6e2fc143137c07ff18d497a477/crates/blockifier/src/concurrency/versioned_storage.rs#L42)):*
> ```XML
>             .and_then(|writes_map| writes_map.range(..=version).next_back());
>         match value {
>             Some((_, value)) => Ok(value.clone()),
> ```

Why do you need clone if it's copyable?



_Code quote:_
```XML
            Some((_, value)) => Ok(value.clone()),
```


<!-- Sent from Reviewable.io -->

2024-03-07 12:38 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 3 of 6 files reviewed, 7 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 12 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsN6Mk77cCS_xvveiap:-NsNsKFDDz1Dft4vnZQE:b-utyq66) ([raw file](https://github.com/starkware-libs/blockifier/blob/21583c916de81f6e2fc143137c07ff18d497a477/crates/blockifier/src/concurrency/versioned_storage.rs#L12)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain why it returns an option?
</blockquote></details>

Please note that I have removed the callback function from storage.
It describes the values written in papyrus storage, and it returns none if a key doesn't exist.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 42 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsMz41REXXpKvvEQMTP:-NsNunju4wQIPITIlFFd:b-bfhpak) ([raw file](https://github.com/starkware-libs/blockifier/blob/21583c916de81f6e2fc143137c07ff18d497a477/crates/blockifier/src/concurrency/versioned_storage.rs#L42)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why do you need clone if it's copyable?
</blockquote></details>

No, the value is not copyable.


<!-- Sent from Reviewable.io -->

2024-03-07 13:04 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 4 files at r3, 1 of 5 files at r4, 2 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 4 of 6 files reviewed, 13 unresolved discussions (waiting on @elintul, @giladchase, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 10 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsNyraZDdrvNoxKsW4U:-NsNyra_-8s3wK3gbGvy:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/69fd4b0af0ebc568ffc179520aeacaf29ab852b0/crates/blockifier/src/concurrency/versioned_storage.rs#L10)):*
> ```XML
> 
> /// A storage unit.
> /// It is versioned in the sense that it holds a state of read and writes operation done on it by
> ```





_Suggestion:_
```XML
tate of write operation don
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 19 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsNyy1y0zW33VSqUPhQ:-NsNyy1y0zW33VSqUPhR:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/69fd4b0af0ebc568ffc179520aeacaf29ab852b0/crates/blockifier/src/concurrency/versioned_storage.rs#L19)):*
> ```XML
>     V: Clone + std::fmt::Debug,
> {
>     pub cached_initial_value: HashMap<K, V>,
> ```





_Suggestion:_
```XML

pub cached_initial_values: HashMap<K, V>,
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 32 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsO-NM_A_Bp8hgLcRxz:-NsO-NM_A_Bp8hgLcRy-:b-hzxkn6) ([raw file](https://github.com/starkware-libs/blockifier/blob/69fd4b0af0ebc568ffc179520aeacaf29ab852b0/crates/blockifier/src/concurrency/versioned_storage.rs#L32)):*
> ```XML
>     }
> 
>     pub fn read(&self, cell_id: K, version: Version) -> Option<V> {
> ```

Can you please start with `version`? also for `write`



_Code quote:_
```XML
&self, cell_id: K, version: Version)
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 32 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsO-dOm6UPZXnYGNhxZ:-NsO-dOm6UPZXnYGNhx_:b-xo7jp6) ([raw file](https://github.com/starkware-libs/blockifier/blob/69fd4b0af0ebc568ffc179520aeacaf29ab852b0/crates/blockifier/src/concurrency/versioned_storage.rs#L32)):*
> ```XML
>     }
> 
>     pub fn read(&self, cell_id: K, version: Version) -> Option<V> {
> ```

`key` is okay



_Code quote:_
```XML
cell_id
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 44 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsNzZ7S-rDsFtujlmLp:-NsNzZ7S-rDsFtujlmLq:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/69fd4b0af0ebc568ffc179520aeacaf29ab852b0/crates/blockifier/src/concurrency/versioned_storage.rs#L44)):*
> ```XML
> 
>     pub fn write(&mut self, cell_id: K, version: Version, value: V) {
>         let writes_map = self.writes.entry(cell_id).or_default();
> ```





_Suggestion:_
```XML
let cell
```
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 13 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsO-8fv9d6uKrJvSqUt:-NsO-8fv9d6uKrJvSqUu:blpkjng) ([raw file](https://github.com/starkware-libs/blockifier/blob/69fd4b0af0ebc568ffc179520aeacaf29ab852b0/crates/blockifier/src/concurrency/versioned_storage_test.rs#L13)):*
> ```XML
>     assert!(value.is_none());
> 
>     storage.set_initial_value(1, 31_i32);
> ```

Is this necessary? hard to read the test



_Code quote:_
```XML
_i32
```


<!-- Sent from Reviewable.io -->

2024-03-07 13:25 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 4 of 6 files reviewed, 13 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 10 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsNyraZDdrvNoxKsW4U:-NsO0vW6E9fYpcSaZ6sj:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/69fd4b0af0ebc568ffc179520aeacaf29ab852b0/crates/blockifier/src/concurrency/versioned_storage.rs#L10)):*
> ```XML
> 
> /// A storage unit.
> /// It is versioned in the sense that it holds a state of read and writes operation done on it by
> ```

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 19 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsNyy1y0zW33VSqUPhQ:-NsO10GO0qqi0km78lL4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/69fd4b0af0ebc568ffc179520aeacaf29ab852b0/crates/blockifier/src/concurrency/versioned_storage.rs#L19)):*
> ```XML
>     V: Clone + std::fmt::Debug,
> {
>     pub cached_initial_value: HashMap<K, V>,
> ```

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 32 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsO-NM_A_Bp8hgLcRxz:-NsO1Ao26U2o_KdPSY-z:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/69fd4b0af0ebc568ffc179520aeacaf29ab852b0/crates/blockifier/src/concurrency/versioned_storage.rs#L32)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you please start with `version`? also for `write`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 32 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsO-dOm6UPZXnYGNhxZ:-NsO1BC_DjqpJwiAt29I:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/69fd4b0af0ebc568ffc179520aeacaf29ab852b0/crates/blockifier/src/concurrency/versioned_storage.rs#L32)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

`key` is okay
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 44 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsNzZ7S-rDsFtujlmLp:-NsO1F8J17psgUjj2agL:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/69fd4b0af0ebc568ffc179520aeacaf29ab852b0/crates/blockifier/src/concurrency/versioned_storage.rs#L44)):*
> ```XML
> 
>     pub fn write(&mut self, cell_id: K, version: Version, value: V) {
>         let writes_map = self.writes.entry(cell_id).or_default();
> ```

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 13 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsO-8fv9d6uKrJvSqUt:-NsO4RLd1MMjNsh-Sh5O:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/69fd4b0af0ebc568ffc179520aeacaf29ab852b0/crates/blockifier/src/concurrency/versioned_storage_test.rs#L13)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Is this necessary? hard to read the test
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-07 13:42 UTC, noaov1 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 4 of 6 files reviewed, 7 unresolved discussions (waiting on @elintul, @giladchase, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-03-07 14:15 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 4 of 6 files reviewed, 10 unresolved discussions (waiting on @elintul, @giladchase, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 12 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsN6Mk77cCS_xvveiap:-NsOE3ov8uWTI3Pk9-4J:b-fkrd0b) ([raw file](https://github.com/starkware-libs/blockifier/blob/21583c916de81f6e2fc143137c07ff18d497a477/crates/blockifier/src/concurrency/versioned_storage.rs#L12)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Please note that I have removed the callback function from storage.
It describes the values written in papyrus storage, and it returns none if a key doesn't exist.
</blockquote></details>

Thanks (though the state reader api has a result as a return value (I may be confusing unrelated subjects)).
Can you please explain why it was decided to remove it?
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 34 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsODo8K0d8b59oaryv5:-NsODo8K0d8b59oaryv6:bg1gjqj) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L34)):*
> ```XML
>     pub fn read(&self, version: Version, key: K) -> Option<V> {
>         let value =
>             self.writes.get(&key).and_then(|writes_map| writes_map.range(..=version).next_back());
> ```

Isn't `next_back()` removes the element?



_Code quote:_
```XML
            self.writes.get(&key).and_then(|writes_map| writes_map.range(..=version).next_back());
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 43 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsOEVQ138QPvXQl43eX:-NsOEVQ138QPvXQl43eY:b-2xmwoc) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L43)):*
> ```XML
>     pub fn write(&mut self, version: Version, key: K, value: V) {
>         let cell = self.writes.entry(key).or_default();
>         cell.insert(version, value);
> ```

When `cell = BTreeMap::default`, will it be updated in `self.writes`?
Consider use `and_modify`.



_Code quote:_
```XML
        cell.insert(version, value);
```


<!-- Sent from Reviewable.io -->

2024-03-07 14:57 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 4 of 6 files reviewed, 10 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 12 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsN6Mk77cCS_xvveiap:-NsOMS200le7BaL37ikB:bm5lkch) ([raw file](https://github.com/starkware-libs/blockifier/blob/21583c916de81f6e2fc143137c07ff18d497a477/crates/blockifier/src/concurrency/versioned_storage.rs#L12)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Thanks (though the state reader api has a result as a return value (I may be confusing unrelated subjects)).
Can you please explain why it was decided to remove it?
</blockquote></details>

We moved it to the versioned state. In this state, we provide the initial state (papyrus). If the storage returns none (indicating it hasn't been written by any version yet), it reads from papyrus and writes to `cached_initial_values`. Similar behavior to what we do in cached state.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 34 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsODo8K0d8b59oaryv5:-NsOO5Yp71CaZFJ2l-Dj:be602sk) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L34)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Isn't `next_back()` removes the element?
</blockquote></details>

No, it doesn't remove the element.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 43 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsOEVQ138QPvXQl43eX:-NsOPNwT9_XG_kXRyGGy:bx2xao0) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L43)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

When `cell = BTreeMap::default`, will it be updated in `self.writes`?
Consider use `and_modify`.
</blockquote></details>

`or_default` updated the writes map.
It inserts an empty field:
`entry.insert(Default::default())`


<!-- Sent from Reviewable.io -->

2024-03-07 14:59 UTC, Yoni-Starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-:-NsOQIQB2oeMHbFo1cvJ:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @giladchase, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 10 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsOQA5R8ICJ9BUkOF1Y:-NsOQA5R8ICJ9BUkOF1Z:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L10)):*
> ```XML
> 
> /// A storage unit.
> /// It is versioned in the sense that it holds a state of write operation done on it by
> ```





_Suggestion:_
```XML
perations don
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 34 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsOQ5W9BBh_zVs3T4aG:-NsOQ5W9BBh_zVs3T4aH:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L34)):*
> ```XML
>     pub fn read(&self, version: Version, key: K) -> Option<V> {
>         let value =
>             self.writes.get(&key).and_then(|writes_map| writes_map.range(..=version).next_back());
> ```





_Suggestion:_
```XML
cell| cell
```


<!-- Sent from Reviewable.io -->

2024-03-07 16:34 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase and @MohammadNassar1)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 34 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsODo8K0d8b59oaryv5:-NsOjTgU7MsZGemucGel:b-5826i) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L34)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

No, it doesn't remove the element.
</blockquote></details>

I think that it is but we don't care since it mutates the `Range`. Resolved.
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 6 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsOiadbARBZxaS_rrKc:-NsOiadbARBZxaS_rrKd:bctijn3) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage_test.rs#L6)):*
> ```XML
> 
> #[test]
> fn test_versioned_storage() {
> ```

Note that it seems that the remote `cargo test` did not run this test. Maybe it has something to do with `feature = "concurrency"`?


<!-- Sent from Reviewable.io -->

2024-03-10 10:09 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase)

___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 6 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsOiadbARBZxaS_rrKc:-NsbpGSe5ZIqd6ejIqa8:baqtyqv) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage_test.rs#L6)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Note that it seems that the remote `cargo test` did not run this test. Maybe it has something to do with `feature = "concurrency"`?
</blockquote></details>

Very weird!
@giladchase, why the CI doesn't run the concurrency feature?


<!-- Sent from Reviewable.io -->

2024-03-10 15:13 UTC, giladchase requested changes
Python PR / did you run blockifier/flow test in python?
This might break pyo3 due to the added feature

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-:-Nscc3-v7fjpghMQCaZS:b-5qz4g1)* status: all files reviewed, 7 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 47 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NrU9ytM1BEpMB3tIv0y:-NscVeHu52jglKCJ48yv:b-7j964s) ([raw file](https://github.com/starkware-libs/blockifier/blob/985e1fe582aa7cfc3758ac3dd26e1dd22870d8d5/crates/blockifier/src/concurrency/versioned_storage.rs#L47)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

stale
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 3 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nscv2DeAT_lPAjuDT3N:-Nscv2DeAT_lPAjuDT3O:b-aonr0n) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L3)):*
> ```XML
> use std::collections::{BTreeMap, HashMap};
> 
> pub(crate) type Version = u64;
> ```

 Can/should this be private?
Asking cause `Version` will probably clash with some other type at some point.



_Code quote:_
```XML
pub(crate) type Version = u64;
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 17 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsccbkW1tyZTP0u97Qb:-NsccbkW1tyZTP0u97Qc:b-28czsw) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L17)):*
> ```XML
> where
>     K: Clone + Copy + Eq + std::hash::Hash + std::fmt::Debug,
>     V: Clone + std::fmt::Debug,
> ```

Add imports.
The common std types are conventionally imported without fullpath, everyone knows where they come from (as opposed to derive_more types for example) 



_Suggestion:_
```XML
    K: Clone + Copy + Eq + Hash + Debug,
    V: Clone + Debug,
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 30 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NscdBRw8J_TtlOIvbmt:-NscdBRw8J_TtlOIvbmu:b-bcl2va) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L30)):*
> ```XML
>     pub fn new() -> Self {
>         VersionedStorage { cached_initial_values: HashMap::new(), writes: HashMap::new() }
>     }
> ```

[Equivalent to default()](https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/style.md#constructors)
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 38 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nsct5lG0YsIGUZBg8cu:-Nsct5lG0YsIGUZBg8cv:b-r8qedm) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L38)):*
> ```XML
>             Some((_, value)) => Some(value.clone()),
>             None => self.cached_initial_values.get(&key).cloned(),
>         }
> ```

Only because of the duplicated clones, otherwise the match was probably a bit more readable, but not sure about that.

(FYI, technically, you don't really need the value tmp var, you can continue the chain after the  `and_then`, but that's probably is not very readable, too much chaining... :sweat_smile:)



_Suggestion:_
```XML
        value
            .map(|(_, value)| value)
            .or_else(|| self.cached_initial_values.get(&key))
            .cloned()
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 48 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NscunnE8Y_aV67Fvjq6:-NscunnE8Y_aV67Fvjq7:brbypm2) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L48)):*
> ```XML
>     pub fn set_initial_value(&mut self, key: K, value: V) {
>         self.cached_initial_values.insert(key, value);
>     }
> ```

Maybe doc this? it might not be obvious to users why this one's needed.
Yr call



_Code quote:_
```XML
    pub fn set_initial_value(&mut self, key: K, value: V) {
        self.cached_initial_values.insert(key, value);
    }
```
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 6 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsOiadbARBZxaS_rrKc:-NscaE2a1F0QJS8gQABr:b-gflo24) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage_test.rs#L6)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Very weird!
@giladchase, why the CI doesn't run the concurrency feature?
</blockquote></details>

ya its caues carg test is run without this feature

The fix is to add a to ci.yml an additional cargo test with this feature turned on --- we want to test both the non-concurrent and the concurrent ones separately, to make sure the lib is usable for both types of users.

This feature issue will appear in more places in the context of this task, and most of the time the solution will be like here, to add support which separates the concurrent and non-concurrent.
At some point we'll probably need [assert_cfg](https://docs.rs/static_assertions/latest/static_assertions/macro.assert_cfg.html) (external crate) to assert a piece of code is run only if the feature is on or not, and so on


<!-- Sent from Reviewable.io -->

2024-03-11 09:56 UTC, MohammadNassar1 reviewed
I ran a local test, and it passed.
I'll open a python PR for it.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-:-Nsgv3oV7fQUs_ttl6lI:bu7avjy)* status: 5 of 6 files reviewed, 6 unresolved discussions (waiting on @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 3 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nscv2DeAT_lPAjuDT3N:-NsgqS_M7bznEZcyIpkx:b-tvzzhz) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L3)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can/should this be private?
Asking cause `Version` will probably clash with some other type at some point.
</blockquote></details>

It's used in the versioned state and versioned client state.
So it cannot be private.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 10 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsOQA5R8ICJ9BUkOF1Y:-Nsg_Uyx1A19RY8KWbgM:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L10)):*
> ```XML
> 
> /// A storage unit.
> /// It is versioned in the sense that it holds a state of write operation done on it by
> ```

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 17 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NsccbkW1tyZTP0u97Qb:-Nsg_ogU9aFX0RBgqGEi:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L17)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Add imports.
The common std types are conventionally imported without fullpath, everyone knows where they come from (as opposed to derive_more types for example)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 30 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NscdBRw8J_TtlOIvbmt:-Nsgk9T61yVxEaJng0kV:b-aoig9p) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L30)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

[Equivalent to default()](https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/style.md#constructors)
</blockquote></details>

Correct, but `default()` requires adding a Default trait, which ContractClass doesn't implement.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 38 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nsct5lG0YsIGUZBg8cu:-NsgliggAZSUOIFCa0fY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L38)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Only because of the duplicated clones, otherwise the match was probably a bit more readable, but not sure about that.

(FYI, technically, you don't really need the value tmp var, you can continue the chain after the  `and_then`, but that's probably is not very readable, too much chaining... :sweat_smile:)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-12 13:18 UTC, noaov1 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-:-Nsmo96f-N77FKZ1ZNm5:bnfp4nl)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @giladchase and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-03-12 13:56 UTC, Yoni-Starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-:-Nsmwqy82E_PBtwuEE4Z:bnfp4nl)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-03-12 14:32 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nsn41xD-puHs4f0l8rq:-Nsn41xD-puHs4f0l8rr:be6k8rd) (no related file):*
Python PR:
https://reviewable.io/reviews/starkware-industries/starkware/34361

___


<!-- Sent from Reviewable.io -->

2024-03-13 07:13 UTC, giladchase requested changes
> Reviewed 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @elintul, @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 3 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-Nscv2DeAT_lPAjuDT3N:-NsqciJt0bBlOdSxFVi1:bdtaldg) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L3)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

It's used in the versioned state and versioned client state.
So it cannot be private.
</blockquote></details>

If we move it to concurrency.rs i think it can be private, since it is only used inside the concurrency submodules (it's an okay move when something is heavily shared by the submodules).
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 30 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NscdBRw8J_TtlOIvbmt:-NsqddNU1T5CCqARVTOa:b-cq6zj1) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L30)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Correct, but `default()` requires adding a Default trait, which ContractClass doesn't implement.
</blockquote></details>

I think there's a disconnect: I claim that you can remove this `new` and replace every `VersionedStorage::new` with `VersionedStorage::default()`, which itilizes the _existing_ `derive(Default)`
Is there some future usage that makes this no longer the case?


<!-- Sent from Reviewable.io -->

2024-03-13 07:55 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 30 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NscdBRw8J_TtlOIvbmt:-Nsqm6NO9ntrgUL14YAs:b-g1zb3q) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L30)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think there's a disconnect: I claim that you can remove this `new` and replace every `VersionedStorage::new` with `VersionedStorage::default()`, which itilizes the _existing_ `derive(Default)`
Is there some future usage that makes this no longer the case?
</blockquote></details>

Exactly.
In the [second PR](https://reviewable.io/reviews/starkware-libs/blockifier/1528)  `contractClass` is used as a value for compiled contract classes versioned storage. `ContractClass` doesn't Implement default.


<!-- Sent from Reviewable.io -->

2024-03-13 12:44 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)



<!-- Sent from Reviewable.io -->

2024-03-13 12:45 UTC, Yoni-Starkware reviewed
@giladchase can we merge this?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-:-NsrpqbyCAhThfopX_Cc:bsl5yzf)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)



<!-- Sent from Reviewable.io -->

2024-03-13 15:55 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 30 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NscdBRw8J_TtlOIvbmt:-NssAfmnDFa2iQ9TTv9M:bm6mgwt) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L30)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Exactly.
In the [second PR](https://reviewable.io/reviews/starkware-libs/blockifier/1528)  `contractClass` is used as a value for compiled contract classes versioned storage. `ContractClass` doesn't Implement default.
</blockquote></details>

The `ContractClass` is taking the role of `V`so it does not need to implement default trait for the `VersionedStorage` to implement default, no?


<!-- Sent from Reviewable.io -->

2024-03-13 19:11 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 30 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NscdBRw8J_TtlOIvbmt:-NstBr3e618tcbRu3122:b-zdwi7i) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L30)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

The `ContractClass` is taking the role of `V`so it does not need to implement default trait for the `VersionedStorage` to implement default, no?
</blockquote></details>

For `VersionedStorage` to implement default, it requires both `K` and `V` to implement it.


<!-- Sent from Reviewable.io -->

2024-03-14 08:13 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @elintul, @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 30 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NscdBRw8J_TtlOIvbmt:-NsvwHED0BXHLFlc-uuk:bwt91tr) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L30)):*
>The `ContractClass` is taking the role of `V`so it does not need to implement default trait for the `VersionedStorage` to implement default, no?

Correct. However, it looks like [derive(X) adds the trait bound](https://users.rust-lang.org/t/trait-default-for-generic-type-required-but-useless/67609) `X` on  all generic params of the type, even if they aren't necessary in order to implement the trait., as is the case for us.

>For `VersionedStorage` to implement default, it requires both `K` and `V` to implement it.

Correct but only for the derive usage, due to the above paragraph. 
We should remove the derive(default) (which isn't usable by us in practice due to the ContractClass issue) and `impl` default manually:

```rust
impl<K, V> Default for VersionedStorage<K, V>
where
    K: Clone + Copy + Eq + Hash + Debug,
    V: Clone + Debug,
{
    fn default() -> Self {
        // We cannot derive `Default` since the derive requires that both `K` and `V` impl `Default`. 
        VersionedStorage { cached_initial_values: Default::default(), writes: Default::default() }
    }
}
```


<!-- Sent from Reviewable.io -->

2024-03-14 08:25 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 30 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1421#-NscdBRw8J_TtlOIvbmt:-Nsw3K0003Qdc3WA3dcm:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/71169930e21b4e1662045d393a247b48efafcb77/crates/blockifier/src/concurrency/versioned_storage.rs#L30)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

>The `ContractClass` is taking the role of `V`so it does not need to implement default trait for the `VersionedStorage` to implement default, no?

Correct. However, it looks like [derive(X) adds the trait bound](https://users.rust-lang.org/t/trait-default-for-generic-type-required-but-useless/67609) `X` on  all generic params of the type, even if they aren't necessary in order to implement the trait., as is the case for us.

>For `VersionedStorage` to implement default, it requires both `K` and `V` to implement it.

Correct but only for the derive usage, due to the above paragraph. 
We should remove the derive(default) (which isn't usable by us in practice due to the ContractClass issue) and `impl` default manually:

```rust
impl<K, V> Default for VersionedStorage<K, V>
where
    K: Clone + Copy + Eq + Hash + Debug,
    V: Clone + Debug,
{
    fn default() -> Self {
        // We cannot derive `Default` since the derive requires that both `K` and `V` impl `Default`. 
        VersionedStorage { cached_initial_values: Default::default(), writes: Default::default() }
    }
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-14 08:36 UTC, noaov1 approved these changes
> Reviewed 1 of 4 files at r6, 1 of 2 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-03-14 08:47 UTC, noaov1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-03-14 08:49 UTC, MohammadNassar1 reviewed
> Dismissed @giladchase from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-03-14 08:51 UTC, noaov1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-03-14 08:51 UTC, MohammadNassar1 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1421)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-03-14 08:53 UTC, merged