refactor: add Bouncer add function to the blockifier
starkware-libs/blockifier pull request #1444
Opened 2024-02-06 13:05 UTC by Yael-Starkware

2024-02-11 19:09 UTC, Yael-Starkware reviewed
As part of the parallelism effort, we are moving the bouncer to the blockifier.
This is the first PR to implement the bouncer, it defines the struct Bouncer and an add() function that gets tx_weights and adds them to the batch accumulated weights. If there is no more room in this batch , it returns an erros.
It also gets a tx_timestamp and updates the batch oldest timestamp if needed.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-:-NqOZ9BaE0POgGwqMma2:bljxs71)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @elintul and @noaov1)



<!-- Sent from Reviewable.io -->

2024-02-13 07:58 UTC, noaov1 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @elintul and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqWQePj89d4r_LU9Gwn:-NqWQePj89d4r_LU9Gwo:b4eqvc9) ([raw file](https://github.com/starkware-libs/blockifier/blob/64e11cbafc2b6e37da711c80b7c96a19ae8855be/crates/blockifier/src/bouncer.rs#L36)):*
> ```XML
> #[allow(dead_code)]
> pub struct Bouncer {
>     max_block_weights: HashMap<String, u64>,
> ```

Is this a property of the bouncer or a configurable value?
Same question for `max_tx_lifespan`.



_Code quote:_
```XML
max_block_weights: HashMap<String, u64>,
```
___
*[`crates/blockifier/src/bouncer.rs` line 37 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqWQQhQ3R2vuUzSpHR1:-NqWQQhQ3R2vuUzSpHR2:baau7fl) ([raw file](https://github.com/starkware-libs/blockifier/blob/64e11cbafc2b6e37da711c80b7c96a19ae8855be/crates/blockifier/src/bouncer.rs#L37)):*
> ```XML
> pub struct Bouncer {
>     max_block_weights: HashMap<String, u64>,
>     accumulated_block_weights: HashMap<String, u64>,
> ```

Consider defining an enum instead of using strings.



_Code quote:_
```XML
    accumulated_block_weights: HashMap<String, u64>,
```
___
*[`crates/blockifier/src/bouncer.rs` line 61 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqWR0rGDQZ1LOU_F3x2:-NqWR0rGDQZ1LOU_F3x3:b-wegath) ([raw file](https://github.com/starkware-libs/blockifier/blob/64e11cbafc2b6e37da711c80b7c96a19ae8855be/crates/blockifier/src/bouncer.rs#L61)):*
> ```XML
>             if !self.max_block_weights.contains_key(key) {
>                 continue;
>             }
> ```

Can you please explain why?
Are there weights with no upper bound?



_Code quote:_
```XML
        for (key, weight) in weights.iter() {
            if !self.max_block_weights.contains_key(key) {
                continue;
            }
```


<!-- Sent from Reviewable.io -->

2024-02-13 10:33 UTC, Yael-Starkware reviewed
done.

this change kind of mixed everything here , sorry for that

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-:-NqX0mQA-OFNvZDRGD13:buln15b)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/bouncer.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqWQePj89d4r_LU9Gwn:-NqX0QCP9g8afRILzrGD:bc2glky) ([raw file](https://github.com/starkware-libs/blockifier/blob/64e11cbafc2b6e37da711c80b7c96a19ae8855be/crates/blockifier/src/bouncer.rs#L36)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is this a property of the bouncer or a configurable value?
Same question for `max_tx_lifespan`.
</blockquote></details>

added a TODO for now, asking @giladchase  if this should be in versioned_constants
___
*[`crates/blockifier/src/bouncer.rs` line 37 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqWQQhQ3R2vuUzSpHR1:-NqX0bbu1z_ylvEwji0d:b-896fjx) ([raw file](https://github.com/starkware-libs/blockifier/blob/64e11cbafc2b6e37da711c80b7c96a19ae8855be/crates/blockifier/src/bouncer.rs#L37)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider defining an enum instead of using strings.
</blockquote></details>

Done
___
*[`crates/blockifier/src/bouncer.rs` line 61 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqWR0rGDQZ1LOU_F3x2:-NqX0dF77cJDTU-PyXYf:b-j2ezr8) ([raw file](https://github.com/starkware-libs/blockifier/blob/64e11cbafc2b6e37da711c80b7c96a19ae8855be/crates/blockifier/src/bouncer.rs#L61)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain why?
Are there weights with no upper bound?
</blockquote></details>

following our huddle, I replaced the continue with an assert.


<!-- Sent from Reviewable.io -->

2024-02-13 11:42 UTC, elintul reviewed
> Reviewed 3 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @giladchase, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 2 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqXG6OH4HjRgmTWssK6:-NqXG6OH4HjRgmTWssK7:breh292) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f2b486c303f7171f1ecc6c6ed6eba7b3a8dfd88/crates/blockifier/src/bouncer.rs#L2)):*
> ```XML
> pub mod counting_bouncer;
> pub mod errors;
> ```

Do you foresee additional files in this directory?
Maybe we should start with `src/bouncer[_test].rs`?



_Code quote:_
```XML
pub mod counting_bouncer;
pub mod errors;
```


<!-- Sent from Reviewable.io -->

2024-02-13 11:45 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: 3 of 6 files reviewed, 7 unresolved discussions (waiting on @giladchase, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer/counting_bouncer.rs` line 13 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqXGdJ90SPY9CtOFOGI:-NqXGdJ90SPY9CtOFOGJ:b-suv37y) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f2b486c303f7171f1ecc6c6ed6eba7b3a8dfd88/crates/blockifier/src/bouncer/counting_bouncer.rs#L13)):*
> ```XML
> pub type BouncerResult<T> = Result<T, BouncerError>;
> 
> #[derive(Eq, PartialEq, Hash, Clone, Display)]
> ```

Alphabetize.



_Code quote:_
```XML
Eq, PartialEq, Hash, Clone, Display
```
___
*[`crates/blockifier/src/bouncer/counting_bouncer.rs` line 15 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqXGjAV97lUbDpli9F5:-NqXGjAV97lUbDpli9F6:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f2b486c303f7171f1ecc6c6ed6eba7b3a8dfd88/crates/blockifier/src/bouncer/counting_bouncer.rs#L15)):*
> ```XML
> #[derive(Eq, PartialEq, Hash, Clone, Display)]
> pub enum BouncerWeights {
>     GasWeight,
> ```





_Suggestion:_
```XML
Gas
```
___
*[`crates/blockifier/src/bouncer/counting_bouncer.rs` line 18 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqXGl2kEXtk7zCW23Ag:-NqXGl2kEXtk7zCW23Ah:b93cxbn) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f2b486c303f7171f1ecc6c6ed6eba7b3a8dfd88/crates/blockifier/src/bouncer/counting_bouncer.rs#L18)):*
> ```XML
>     MessageSegmentLength,
>     NSteps,
>     NStepsWithKeccak, // TODO: how to handle Keccak?
> ```

Let's add a TODO to handle Keccak separately.



_Suggestion:_
```XML
    NumberOfSteps,
```
___
*[`crates/blockifier/src/bouncer/counting_bouncer.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqXHCzCANcryuEp2_sk:-NqXHCzD37UPQVXPdjHo:b8eka3b) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f2b486c303f7171f1ecc6c6ed6eba7b3a8dfd88/crates/blockifier/src/bouncer/counting_bouncer.rs#L20)):*
> ```XML
>     NStepsWithKeccak, // TODO: how to handle Keccak?
>     StateDiffSize,
>     StateDiffSizeWithKzg,
> ```

This too.



_Code quote:_
```XML
StateDiffSizeWithKzg,
```


<!-- Sent from Reviewable.io -->

2024-02-15 10:16 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: 1 of 8 files reviewed, 7 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/bouncer.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqWQePj89d4r_LU9Gwn:-NqgFCEX312lG_-8mo2X:b-nzvswq) ([raw file](https://github.com/starkware-libs/blockifier/blob/64e11cbafc2b6e37da711c80b7c96a19ae8855be/crates/blockifier/src/bouncer.rs#L36)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

added a TODO for now, asking @giladchase  if this should be in versioned_constants
</blockquote></details>

added to versioned constants
done
___
*[`crates/blockifier/src/bouncer.rs` line 2 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqXG6OH4HjRgmTWssK6:-NqgFW-27ZaO9Mvzl_MO:ba66e3e) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f2b486c303f7171f1ecc6c6ed6eba7b3a8dfd88/crates/blockifier/src/bouncer.rs#L2)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do you foresee additional files in this directory?
Maybe we should start with `src/bouncer[_test].rs`?
</blockquote></details>

That was what I did initially, but @noaov1 suggested to move to a dedicated directory. whatever you decide if fine with me.


<!-- Sent from Reviewable.io -->

2024-02-15 15:24 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: 1 of 8 files reviewed, 4 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/bouncer/counting_bouncer.rs` line 15 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqXGjAV97lUbDpli9F5:-NqhLoOyEt6g7JWq-4ul:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f2b486c303f7171f1ecc6c6ed6eba7b3a8dfd88/crates/blockifier/src/bouncer/counting_bouncer.rs#L15)):*
> ```XML
> #[derive(Eq, PartialEq, Hash, Clone, Display)]
> pub enum BouncerWeights {
>     GasWeight,
> ```

done
___
*[`crates/blockifier/src/bouncer/counting_bouncer.rs` line 18 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqXGl2kEXtk7zCW23Ag:-NqhMUfu83S4JZesJIFf:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f2b486c303f7171f1ecc6c6ed6eba7b3a8dfd88/crates/blockifier/src/bouncer/counting_bouncer.rs#L18)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's add a TODO to handle Keccak separately.
</blockquote></details>

done
___
*[`crates/blockifier/src/bouncer/counting_bouncer.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqXHCzCANcryuEp2_sk:-NqhLtWJ3pOkYQ2OlfnW:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f2b486c303f7171f1ecc6c6ed6eba7b3a8dfd88/crates/blockifier/src/bouncer/counting_bouncer.rs#L20)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This too.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-02-18 06:20 UTC, elintul requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: 1 of 8 files reviewed, 4 unresolved discussions (waiting on @giladchase, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqWQePj89d4r_LU9Gwn:-NqurWTZ12pYOL2sySGQ:b-1x9mju) ([raw file](https://github.com/starkware-libs/blockifier/blob/64e11cbafc2b6e37da711c80b7c96a19ae8855be/crates/blockifier/src/bouncer.rs#L36)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

added to versioned constants
done
</blockquote></details>

They should also be configurable from Python, please make sure they are (
___
*[`crates/blockifier/src/bouncer/counting_bouncer.rs` line 30 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqurmE_CrN9KiXVcDA_:-NqurmE_CrN9KiXVcDAa:b-nsu7dy) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca2da72d8c2d6ecaebd911487b5d30d4ceb1febc/crates/blockifier/src/bouncer/counting_bouncer.rs#L30)):*
> ```XML
>     type Output = Self;
> 
>     fn add(self, other: Self) -> Self {
> ```

Do we need this, or is `derive_more::Add` is enough?



_Code quote:_
```XML
add
```


<!-- Sent from Reviewable.io -->

2024-02-18 06:24 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: 1 of 8 files reviewed, 6 unresolved discussions (waiting on @giladchase, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer/counting_bouncer.rs` line 46 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqusYhU7yZXzbUKtU6Z:-NqusYhU7yZXzbUKtU6_:b-qaz2if) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca2da72d8c2d6ecaebd911487b5d30d4ceb1febc/crates/blockifier/src/bouncer/counting_bouncer.rs#L46)):*
> ```XML
> #[allow(dead_code)]
> impl BouncerWeights {
>     pub fn exceeds_limit(self, versioned_constants: &VersionedConstants) -> bool {
> ```

Let's use [`CheckedSub` trait](https://docs.rs/num/latest/num/trait.CheckedSub.html) instead.



_Code quote:_
```XML
exceeds_limit
```
___
*[`crates/blockifier/src/bouncer/counting_bouncer.rs` line 61 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nqusipx-mizWbxws-JO:-Nqusipx-mizWbxws-JP:bcadh4z) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca2da72d8c2d6ecaebd911487b5d30d4ceb1febc/crates/blockifier/src/bouncer/counting_bouncer.rs#L61)):*
> ```XML
> #[allow(dead_code)]
> #[derive(Default)]
> pub struct Bouncer {
> ```

Let's move to another PR and only include `BouncerWeights` here.



_Code quote:_
```XML
Bouncer
```


<!-- Sent from Reviewable.io -->

2024-02-18 06:25 UTC, elintul reviewed
> Reviewed 1 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: 2 of 8 files reviewed, 6 unresolved discussions (waiting on @giladchase, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqWQePj89d4r_LU9Gwn:-NqustIRBAUZUAtVAdeK:boi1h0k) ([raw file](https://github.com/starkware-libs/blockifier/blob/64e11cbafc2b6e37da711c80b7c96a19ae8855be/crates/blockifier/src/bouncer.rs#L36)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

They should also be configurable from Python, please make sure they are (
</blockquote></details>

I think the fact they're `pub` is enough, but let's make sure). This also should be a part of a different PR.
___
*[`crates/blockifier/src/bouncer.rs` line 2 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqXG6OH4HjRgmTWssK6:-Nqut1GY4K_FbXmt-zyF:b-rxt5km) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f2b486c303f7171f1ecc6c6ed6eba7b3a8dfd88/crates/blockifier/src/bouncer.rs#L2)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

That was what I did initially, but @noaov1 suggested to move to a dedicated directory. whatever you decide if fine with me.
</blockquote></details>

Let's continue this way and decide if to consolidate in the end. Add a TODO, please?


<!-- Sent from Reviewable.io -->

2024-02-18 06:27 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: 2 of 8 files reviewed, 7 unresolved discussions (waiting on @giladchase, @noaov1, and @Yael-Starkware)

___
*[`-- commits` line 2 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqutAZg2w3mz43RbNHP):*
Let's try to keep PRs as self-contained as possible.



_Suggestion:_
```
add BouncerWeights
```


<!-- Sent from Reviewable.io -->

2024-02-18 06:32 UTC, elintul submitted a review, later dismissed
> Reviewed 3 of 7 files at r6, 1 of 1 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: all files reviewed, 11 unresolved discussions (waiting on @giladchase, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer/counting_bouncer.rs` line 1 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nquu3iS7LynVK2Q2S9p:-Nquu3iT4HaTSLke9ROG:b-r34fb5) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca2da72d8c2d6ecaebd911487b5d30d4ceb1febc/crates/blockifier/src/bouncer/counting_bouncer.rs#L1)):*
> ```XML
> use std::ops::Add;
> ```

`bouncer.rs`, we'll only have one kind (in Python we previously thought of more than one implementation).
___
*[`crates/blockifier/src/bouncer/counting_bouncer.rs` line 22 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NquuKK32L3RfGyQzn3k:-NquuKK32L3RfGyQzn3l:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca2da72d8c2d6ecaebd911487b5d30d4ceb1febc/crates/blockifier/src/bouncer/counting_bouncer.rs#L22)):*
> ```XML
>     message_segment_length: u64,
>     state_diff_size: u64,
>     state_diff_size_with_kzg: u64,
> ```





_Suggestion:_
```XML
    gas: u64,
    n_steps: u64,
    message_segment_length: u64,
    state_diff_size: u64,
```
___
*[`crates/blockifier/src/bouncer/counting_bouncer.rs` line 23 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NquuQKgEKadfyULVU_N:-NquuQKgEKadfyULVU_O:b4ow0b5) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca2da72d8c2d6ecaebd911487b5d30d4ceb1febc/crates/blockifier/src/bouncer/counting_bouncer.rs#L23)):*
> ```XML
>     state_diff_size: u64,
>     state_diff_size_with_kzg: u64,
>     // TODO(yael) add more weights (n_memory_holes, builtin_steps)
> ```

No need for memory holes, they are counted as steps. 
You can add the builtins now.



_Code quote:_
```XML
// TODO(yael) add more weights (n_memory_holes, builtin_steps)
```
___
*[`crates/blockifier/src/bouncer/counting_bouncer.rs` line 24 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NquuWat8TH0Dm7GNeKl:-NquuWat8TH0Dm7GNeKm:bq1qqr0) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca2da72d8c2d6ecaebd911487b5d30d4ceb1febc/crates/blockifier/src/bouncer/counting_bouncer.rs#L24)):*
> ```XML
>     state_diff_size_with_kzg: u64,
>     // TODO(yael) add more weights (n_memory_holes, builtin_steps)
>     // TODO(yael) understand n_steps_with_keccak and state_diff_size_with_kzg special handling
> ```

This affect the max weights.



_Code quote:_
```XML
// TODO(yael) understand n_steps_with_keccak and state_diff_size_with_kzg special handling
```


<!-- Sent from Reviewable.io -->

2024-02-19 09:45 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: 1 of 8 files reviewed, 10 unresolved discussions (waiting on @elintul, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/bouncer/counting_bouncer.rs` line 30 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqurmE_CrN9KiXVcDA_:-Nr-kLHa0FJDbNo2Blkv:bnkzou3) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca2da72d8c2d6ecaebd911487b5d30d4ceb1febc/crates/blockifier/src/bouncer/counting_bouncer.rs#L30)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Nice!
done
</blockquote></details>

deleted this for checked_sub


<!-- Sent from Reviewable.io -->

2024-02-19 10:36 UTC, elintul reviewed
> Reviewed 5 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: 6 of 8 files reviewed, 9 unresolved discussions (waiting on @giladchase, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 36 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqWQePj89d4r_LU9Gwn:-Nr-vmGICek96XiM1Jrh:b-af3nij) ([raw file](https://github.com/starkware-libs/blockifier/blob/64e11cbafc2b6e37da711c80b7c96a19ae8855be/crates/blockifier/src/bouncer.rs#L36)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

what should be configurable?
</blockquote></details>

The capacities. Let's move this offline.
___
*[`crates/blockifier/src/bouncer.rs` line 10 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr-v3Fv7m4xACE5bWtD:-Nr-v3Fv7m4xACE5bWtE:b-lbgjn5) ([raw file](https://github.com/starkware-libs/blockifier/blob/6933f8e529d8176435d6a1ca0d2d591ac2bbe2b2/crates/blockifier/src/bouncer.rs#L10)):*
> ```XML
> mod test;
> 
> pub trait CheckedSub: Sized + Sub<Self, Output = Self> {
> ```

Why redefine, can't we `use` the Rust one?



_Code quote:_
```XML
CheckedSub
```
___
*[`crates/blockifier/src/bouncer.rs` line 14 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr-vFbw-uPybT--7v8k:-Nr-vFbw-uPybT--7v8l:b-7zi8tj) ([raw file](https://github.com/starkware-libs/blockifier/blob/6933f8e529d8176435d6a1ca0d2d591ac2bbe2b2/crates/blockifier/src/bouncer.rs#L14)):*
> ```XML
> }
> 
> // TODO decide if a separate directory is needed for the bouncer.
> ```

WDYM?



_Code quote:_
```XML
// TODO decide if a separate directory is needed for the bouncer.
```
___
*[`crates/blockifier/src/bouncer.rs` line 16 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr-vCWOEGSFWO6XnhvP:-Nr-vCWOEGSFWO6XnhvQ:b-ojdhj8) ([raw file](https://github.com/starkware-libs/blockifier/blob/6933f8e529d8176435d6a1ca0d2d591ac2bbe2b2/crates/blockifier/src/bouncer.rs#L16)):*
> ```XML
> // TODO decide if a separate directory is needed for the bouncer.
> #[allow(dead_code)]
> #[derive(Clone, Copy, Debug, Default, Deserialize, PartialEq, Sub)]
> ```

Alphabetize, throughout the file.



_Code quote:_
```XML
derive
```
___
*[`crates/blockifier/src/bouncer.rs` line 16 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr-vHDe9kQcUnrcmeqZ:-Nr-vHDe9kQcUnrcmeq_:b-ljo1ms) ([raw file](https://github.com/starkware-libs/blockifier/blob/6933f8e529d8176435d6a1ca0d2d591ac2bbe2b2/crates/blockifier/src/bouncer.rs#L16)):*
> ```XML
> // TODO decide if a separate directory is needed for the bouncer.
> #[allow(dead_code)]
> #[derive(Clone, Copy, Debug, Default, Deserialize, PartialEq, Sub)]
> ```

Fully qualified name, so it's clear where the trait is coming from.
BTW, is there a `derive_more::CheckedSub`?



_Suggestion:_
```XML
derive_more::Sub
```
___
*[`crates/blockifier/src/bouncer.rs` line 18 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr-vPgpC0zviB2FIxoz:-Nr-vPgpC0zviB2FIxp-:bhljc9k) ([raw file](https://github.com/starkware-libs/blockifier/blob/6933f8e529d8176435d6a1ca0d2d591ac2bbe2b2/crates/blockifier/src/bouncer.rs#L18)):*
> ```XML
> #[derive(Clone, Copy, Debug, Default, Deserialize, PartialEq, Sub)]
> // TODO how to initialize the max values
> pub struct BouncerWeights {
> ```

Please add a short docstring.



_Code quote:_
```XML
BouncerWeights
```
___
*[`crates/blockifier/src/bouncer.rs` line 24 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr-vVbfECwkR2lQFZeh:-Nr-vVbfECwkR2lQFZei:bra1ij2) ([raw file](https://github.com/starkware-libs/blockifier/blob/6933f8e529d8176435d6a1ca0d2d591ac2bbe2b2/crates/blockifier/src/bouncer.rs#L24)):*
> ```XML
>     state_diff_size: u64,
>     builtin_count: BuiltinCount,
>     // TODO(yael) understand n_steps_with_keccak and state_diff_size_with_kzg special handling
> ```

This TODO belongs in the area we decide on the capacity of the bouncer.



_Code quote:_
```XML
// TODO(yael) understand n_steps_with_keccak and state_diff_size_with_kzg special handling
```
___
*[`crates/blockifier/src/bouncer/counting_bouncer.rs` line 30 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NqurmE_CrN9KiXVcDA_:-Nr-vtEWDATzQgNwN2mn:b32vhw) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca2da72d8c2d6ecaebd911487b5d30d4ceb1febc/crates/blockifier/src/bouncer/counting_bouncer.rs#L30)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

deleted this for checked_sub
</blockquote></details>

:)


<!-- Sent from Reviewable.io -->

2024-02-20 08:29 UTC, giladchase requested changes
> Reviewed 1 of 7 files at r6, 6 of 7 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 10 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr-v3Fv7m4xACE5bWtD:-Nr4Upb86rMM5TIruW7F:bul32x5) ([raw file](https://github.com/starkware-libs/blockifier/blob/6933f8e529d8176435d6a1ca0d2d591ac2bbe2b2/crates/blockifier/src/bouncer.rs#L10)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

it is not implemented for this type, only for native types.
maybe I should define it just as a regular impl and not a trait?
</blockquote></details>

Ya i don't think rust has a trait for checked_sub, so better not define one to prevent confusion and use a regular method.
(Note that [CheckedSub trait seen here](https://docs.rs/num/latest/num/trait.CheckedSub.html) is not part of `std::num`, but an external crate called `num`)
___
*[`crates/blockifier/src/bouncer.rs` line 14 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr-vFbw-uPybT--7v8k:-Nr4bdJ63oDGZVdPOOr5:b4qjm43) ([raw file](https://github.com/starkware-libs/blockifier/blob/6933f8e529d8176435d6a1ca0d2d591ac2bbe2b2/crates/blockifier/src/bouncer.rs#L14)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

just a TODO that came from one of our previous discussions here, regarding the location of the files.
deleting the todo from here and moving to my notes
</blockquote></details>

In rust things are usually kept as flat as possible, adding submodule directories only when it's really necessary
___
*[`crates/blockifier/src/bouncer.rs` line 16 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr-vCWOEGSFWO6XnhvP:-Nr4_UjL1K_F9NNY6_Xq:bbhsz5j) ([raw file](https://github.com/starkware-libs/blockifier/blob/6933f8e529d8176435d6a1ca0d2d591ac2bbe2b2/crates/blockifier/src/bouncer.rs#L16)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Am I really bad in English? it feels alphabetised to me
</blockquote></details>

derive_more?
___
*[`crates/blockifier/src/bouncer.rs` line 1 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr4Tvn97xNmL-a8RT5u:-Nr4Tvn97xNmL-a8RT5v:b-68rdd4) ([raw file](https://github.com/starkware-libs/blockifier/blob/d1fef1dab23d40c14d8a8749c85b2c9d163e6a63/crates/blockifier/src/bouncer.rs#L1)):*
> ```XML
> use std::ops::Sub;
> ```

So excited to finally see this file name in the blockifier :star_struck: 
___
*[`crates/blockifier/src/bouncer.rs` line 26 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr4YLaD4gNHRcKW2RXl:-Nr4YLaD4gNHRcKW2RXm:bebpjd5) ([raw file](https://github.com/starkware-libs/blockifier/blob/d1fef1dab23d40c14d8a8749c85b2c9d163e6a63/crates/blockifier/src/bouncer.rs#L26)):*
> ```XML
> 
> impl CheckedSub for BouncerWeights {
>     fn checked_sub(&self, v: &Self) -> Option<Self> {
> ```

`Copy` types are always passed by value: more useful that way, and since it's `Copy`, the implicit "clone" is virtually free.



_Suggestion:_
```XML
    fn checked_sub(self, v: Self) -> Option<Self> {
```
___
*[`crates/blockifier/src/bouncer.rs` line 61 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr4Zy8K2LeV3TlATbtZ:-Nr4Zy8K2LeV3TlATbt_:bgiqwsf) ([raw file](https://github.com/starkware-libs/blockifier/blob/d1fef1dab23d40c14d8a8749c85b2c9d163e6a63/crates/blockifier/src/bouncer.rs#L61)):*
> ```XML
>             pedersen: self.pedersen.checked_sub(v.pedersen)?,
>             poseidon: self.poseidon.checked_sub(v.poseidon)?,
>             range_check: self.range_check.checked_sub(v.range_check)?,
> ```

Consider defining a `impl_checked_sub` macro to implement this method here and in `BouncerWeights`.
IMO it's a classic macro use case, where a very simple macro can abstract away repetition.



_Code quote:_
```XML
            bitwise: self.bitwise.checked_sub(v.bitwise)?,
            ecdsa: self.ecdsa.checked_sub(v.ecdsa)?,
            ec_op: self.ec_op.checked_sub(v.ec_op)?,
            keccak: self.keccak.checked_sub(v.keccak)?,
            output: self.output.checked_sub(v.output)?,
            pedersen: self.pedersen.checked_sub(v.pedersen)?,
            poseidon: self.poseidon.checked_sub(v.poseidon)?,
            range_check: self.range_check.checked_sub(v.range_check)?,
```


<!-- Sent from Reviewable.io -->

2024-02-20 13:29 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/bouncer.rs` line 10 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr-v3Fv7m4xACE5bWtD:-Nr5NzViD2XkGcgWXtaS:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/6933f8e529d8176435d6a1ca0d2d591ac2bbe2b2/crates/blockifier/src/bouncer.rs#L10)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Ya i don't think rust has a trait for checked_sub, so better not define one to prevent confusion and use a regular method.
(Note that [CheckedSub trait seen here](https://docs.rs/num/latest/num/trait.CheckedSub.html) is not part of `std::num`, but an external crate called `num`)
</blockquote></details>

done
___
*[`crates/blockifier/src/bouncer.rs` line 16 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr-vCWOEGSFWO6XnhvP:-Nr5O1aTEqtRUwpgf-bu:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/6933f8e529d8176435d6a1ca0d2d591ac2bbe2b2/crates/blockifier/src/bouncer.rs#L16)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

derive_more?
</blockquote></details>

done
___
*[`crates/blockifier/src/bouncer.rs` line 1 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr4Tvn97xNmL-a8RT5u:-Nr5NfPG3poU0-v7gy2G:bghrl2f) ([raw file](https://github.com/starkware-libs/blockifier/blob/d1fef1dab23d40c14d8a8749c85b2c9d163e6a63/crates/blockifier/src/bouncer.rs#L1)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

So excited to finally see this file name in the blockifier :star_struck:
</blockquote></details>


:sunglasses:  was nice but gone now 
___
*[`crates/blockifier/src/bouncer.rs` line 26 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr4YLaD4gNHRcKW2RXl:-Nr5Q6rm5VYPxFRYc5j9:b-854h5u) ([raw file](https://github.com/starkware-libs/blockifier/blob/d1fef1dab23d40c14d8a8749c85b2c9d163e6a63/crates/blockifier/src/bouncer.rs#L26)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

`Copy` types are always passed by value: more useful that way, and since it's `Copy`, the implicit "clone" is virtually free.
</blockquote></details>

are you sure?
I wrote a small test to check it and I don't think that's the case 

anyway I changed it for the macro


fn modify_gas(bouncer_weights: &mut BouncerWeights, gas: u64) -> BouncerWeights {
    bouncer_weights.gas = gas;
    *bouncer_weights
}

fn modify_gas_copy(mut bouncer_weights: BouncerWeights, gas: u64) -> BouncerWeights {
    bouncer_weights.gas = gas;
    bouncer_weights
}

#[test]
fn test_copy_with_reference() {
    let mut copy_type = BouncerWeights::default();
    modify_gas(&mut copy_type, 10);

    // will be 10 if it is passed by reference
    assert!(copy_type.gas == 10);  //This did not raise an assert

    // will be 0 if it is passed by value
    assert!(copy_type.gas == 0);

    modify_gas_copy(copy_type, 5);

    // will be 5 if it is passed by reference
    assert!(copy_type.gas == 5);

    // will be 10 if it is passed by value
    assert!(copy_type.gas == 10); //this did not raise an assert
}
___
*[`crates/blockifier/src/bouncer.rs` line 61 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr4Zy8K2LeV3TlATbtZ:-Nr5eiiFDQihf3IOHBXY:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/d1fef1dab23d40c14d8a8749c85b2c9d163e6a63/crates/blockifier/src/bouncer.rs#L61)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Consider defining a `impl_checked_sub` macro to implement this method here and in `BouncerWeights`.
IMO it's a classic macro use case, where a very simple macro can abstract away repetition.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-02-20 13:32 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/bouncer.rs` line 26 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr4YLaD4gNHRcKW2RXl:-Nr5hoDODvxdYY_45fpI:b-bftsjw) ([raw file](https://github.com/starkware-libs/blockifier/blob/d1fef1dab23d40c14d8a8749c85b2c9d163e6a63/crates/blockifier/src/bouncer.rs#L26)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

are you sure?
I wrote a small test to check it and I don't think that's the case 

anyway I changed it for the macro


fn modify_gas(bouncer_weights: &mut BouncerWeights, gas: u64) -> BouncerWeights {
    bouncer_weights.gas = gas;
    *bouncer_weights
}

fn modify_gas_copy(mut bouncer_weights: BouncerWeights, gas: u64) -> BouncerWeights {
    bouncer_weights.gas = gas;
    bouncer_weights
}

#[test]
fn test_copy_with_reference() {
    let mut copy_type = BouncerWeights::default();
    modify_gas(&mut copy_type, 10);

    // will be 10 if it is passed by reference
    assert!(copy_type.gas == 10);  //This did not raise an assert

    // will be 0 if it is passed by value
    assert!(copy_type.gas == 0);

    modify_gas_copy(copy_type, 5);

    // will be 5 if it is passed by reference
    assert!(copy_type.gas == 5);

    // will be 10 if it is passed by value
    assert!(copy_type.gas == 10); //this did not raise an assert
}
</blockquote></details>

I actually need to change it for the macro only for BuiltinCount


<!-- Sent from Reviewable.io -->

2024-02-20 13:44 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 26 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr4YLaD4gNHRcKW2RXl:-Nr5juoH-XOfU9rwxUl3:b-6ym1c6) ([raw file](https://github.com/starkware-libs/blockifier/blob/d1fef1dab23d40c14d8a8749c85b2c9d163e6a63/crates/blockifier/src/bouncer.rs#L26)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I actually need to change it for the macro only for BuiltinCount
</blockquote></details>

I don't quite follow how this related to my comment :sweat_smile: 

Are you saying that Copy doesn't work? or that checked_sub with Copy doesn't work?
The tests you added seem to explicitly require to modify self, which is not the case here.
Here you only want a reference to self, and are outputting a new value.


<!-- Sent from Reviewable.io -->

2024-02-20 13:45 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 26 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr4YLaD4gNHRcKW2RXl:-Nr5koZ58jcNALuzHYpB:b-vagnlq) ([raw file](https://github.com/starkware-libs/blockifier/blob/d1fef1dab23d40c14d8a8749c85b2c9d163e6a63/crates/blockifier/src/bouncer.rs#L26)):*
> I actually need to change it for the macro only for BuiltinCount

Also what are you referring to here? :sweat_smile:  what's the `it`?


<!-- Sent from Reviewable.io -->

2024-02-20 13:53 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/bouncer.rs` line 26 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr4YLaD4gNHRcKW2RXl:-Nr5moK70aPA6uPoqHJl:b67s8g0) ([raw file](https://github.com/starkware-libs/blockifier/blob/d1fef1dab23d40c14d8a8749c85b2c9d163e6a63/crates/blockifier/src/bouncer.rs#L26)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

> I actually need to change it for the macro only for BuiltinCount

Also what are you referring to here? :sweat_smile:  what's the `it`?
</blockquote></details>

resolved offline


<!-- Sent from Reviewable.io -->

2024-02-20 14:11 UTC, noaov1 reviewed
> Reviewed 3 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-02-20 14:20 UTC, giladchase submitted a review, later dismissed
> Reviewed 1 of 2 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 15 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr5sApb9JtbJwXqjVET:-Nr5sApb9JtbJwXqjVEU:beexap7) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c0f74d7fcce35d3290b58dfb2199831d56833c4/crates/blockifier/src/bouncer.rs#L15)):*
> ```XML
>         })
>     };
> }
> ```

Is it possible to add the whole `fn checked_sub(self, v: Self) -> Option<Self> {` into the macro as well? 
That sig part is also repetative now.
Only if the macro is still relatively simple looking and this doesn't give any trouble.



_Code quote:_
```XML
macro_rules! checked_sub_struct {
    ($self:expr, $other:expr, $( $field:ident ),*) => {
        Some(Self {
            $(
                $field: $self.$field.checked_sub($other.$field)?,
            )*
        })
    };
}
```


<!-- Sent from Reviewable.io -->

2024-02-21 06:25 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/blockifier/src/bouncer.rs` line 15 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr5sApb9JtbJwXqjVET:-Nr9KgYaCs6PxdjYzwrv:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/4c0f74d7fcce35d3290b58dfb2199831d56833c4/crates/blockifier/src/bouncer.rs#L15)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Is it possible to add the whole `fn checked_sub(self, v: Self) -> Option<Self> {` into the macro as well? 
That sig part is also repetative now.
Only if the macro is still relatively simple looking and this doesn't give any trouble.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-02-21 07:16 UTC, giladchase approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-02-21 07:17 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 21 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr9WYoH2xP_W0IwtD_Q:-Nr9WYoH2xP_W0IwtD_R:bad60e9) ([raw file](https://github.com/starkware-libs/blockifier/blob/519278e6c3f9be13a2564a927d1a5b1bf3030419/crates/blockifier/src/bouncer.rs#L21)):*
> ```XML
> }
> 
> #[allow(dead_code)]
> ```

Is this necessary?



_Code quote:_
```XML
#[allow(dead_code)]
```


<!-- Sent from Reviewable.io -->

2024-02-21 07:17 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 21 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr9WYoH2xP_W0IwtD_Q:-Nr9Wevk4yb-I12RrB22:brl8cdd) ([raw file](https://github.com/starkware-libs/blockifier/blob/519278e6c3f9be13a2564a927d1a5b1bf3030419/crates/blockifier/src/bouncer.rs#L21)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Is this necessary?
</blockquote></details>

ditto for `BouncerWeights`


<!-- Sent from Reviewable.io -->

2024-02-21 07:18 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/blockifier/src/bouncer.rs` line 21 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr9WYoH2xP_W0IwtD_Q:-Nr9WqQO-7Lce47nH7Kt:b1libda) ([raw file](https://github.com/starkware-libs/blockifier/blob/519278e6c3f9be13a2564a927d1a5b1bf3030419/crates/blockifier/src/bouncer.rs#L21)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

ditto for `BouncerWeights`
</blockquote></details>

yes, otherwise there are many warnings


<!-- Sent from Reviewable.io -->

2024-02-21 07:18 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/blockifier/src/bouncer.rs` line 21 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr9WYoH2xP_W0IwtD_Q:-Nr9WuvoEjmwUfCqHyTn:b-s4eghz) ([raw file](https://github.com/starkware-libs/blockifier/blob/519278e6c3f9be13a2564a927d1a5b1bf3030419/crates/blockifier/src/bouncer.rs#L21)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

yes, otherwise there are many warnings
</blockquote></details>

will deleted all of them once code is used.


<!-- Sent from Reviewable.io -->

2024-02-21 08:29 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 21 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-Nr9WYoH2xP_W0IwtD_Q:-Nr9lqkI8gSVLyjtbuVw:b-ovcyz7) ([raw file](https://github.com/starkware-libs/blockifier/blob/519278e6c3f9be13a2564a927d1a5b1bf3030419/crates/blockifier/src/bouncer.rs#L21)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

will deleted all of them once code is used.
</blockquote></details>

Unused code shouldn't be a problem for public interface, only for private functions.
I think the macro is generating a private method instead of a public method, that should fix the issue and allow removing the dead_code.


<!-- Sent from Reviewable.io -->

2024-02-21 11:02 UTC, giladchase approved these changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-02-21 11:31 UTC, elintul submitted a review, later dismissed
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 23 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-NrAQOdz9I_OMohIPT2u:-NrAQOe-0hRP5rJzkReJ:b-ci702t) ([raw file](https://github.com/starkware-libs/blockifier/blob/60b9bf226a3ed2536da295dc8b8e3a25978814f5/crates/blockifier/src/bouncer.rs#L23)):*
> ```XML
> #[derive(Clone, Copy, Debug, Default, derive_more::Sub, Deserialize, PartialEq)]
> /// Counted weights of the execution of transactions in a block.
> /// These weights are limited by the block's maximum weights.
> ```

Move before the `derive`. A shorter suggestion: "Represents the execution resources counted throughout block creation.`.  



_Code quote:_
```XML
/// Counted weights of the execution of transactions in a block.
/// These weights are limited by the block's maximum weights.
```


<!-- Sent from Reviewable.io -->

2024-02-21 13:43 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r12, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1444#-:-NrAu4lW4dDaTG77gGP3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-02-21 14:34 UTC, merged