feat(fee): add events gas cost
starkware-libs/blockifier pull request #1458
Opened 2024-02-07 20:17 UTC by barak-b-starkware

2024-02-08 08:32 UTC, avi-starkware commented
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq6pIPOCmyTnBXkcsRA:-Nq6pIPP82yQ8OljcXeA:b-hyk1ig) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4c840ae0b0f05b48e32cda5f9e7d1b5ac2c3f12/crates/blockifier/src/fee/eth_gas_constants.rs#L31)):*
> ```XML
> // Every key and every data word is a StarkFelt which contains 32 bytes.
> pub const MILLI_GAS_PER_KEY: usize = 32 * MILLI_GAS_PER_KEY_BYTE;
> pub const MILLI_GAS_PER_DATA_WORD: usize = 32 * MILLI_GAS_PER_DATA_BYTE;
> ```

These constants should be moved to `versioned_constants.json` (see #1426).
The file `eth_gas_constants.rs` is supposed to only include ETH constants that don't change (are part of the ETH protocol).
Constants that change between versions should be in `versioned_constants.json`.



_Code quote:_
```XML
// L2 Events.
pub const MILLI_GAS_PER_KEY_BYTE: usize = 40;
pub const MILLI_GAS_PER_DATA_BYTE: usize = 2 * MILLI_GAS_PER_KEY_BYTE;
// TODO(barak, 18/03/2024): Remove calculation per StarkFelt.
// Every key and every data word is a StarkFelt which contains 32 bytes.
pub const MILLI_GAS_PER_KEY: usize = 32 * MILLI_GAS_PER_KEY_BYTE;
pub const MILLI_GAS_PER_DATA_WORD: usize = 32 * MILLI_GAS_PER_DATA_BYTE;
```


<!-- Sent from Reviewable.io -->

2024-02-08 08:32 UTC, avi-starkware commented
*[`crates/blockifier/src/fee/gas_usage.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq6q9em15EBMwdOW6ye:-Nq6q9em15EBMwdOW6yf:b-8nkkff) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4c840ae0b0f05b48e32cda5f9e7d1b5ac2c3f12/crates/blockifier/src/fee/gas_usage.rs#L33)):*
> ```XML
>     Ok(get_messages_gas_cost(call_infos.clone(), l1_handler_payload_size)?
>         + get_da_gas_cost(state_changes_count, use_kzg_da)
>         + get_events_gas_cost(call_infos))
> ```

There should be a test where this number is not 0.



_Code quote:_
```XML
        + get_events_gas_cost(call_infos))
```


<!-- Sent from Reviewable.io -->

2024-02-08 12:17 UTC, barak-b-starkware commented
*[`crates/blockifier/src/fee/gas_usage.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq757L79oF3n3w5cYNy:-Nq7ckY70DhRoQPXP0z9:bqepz0o) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4c840ae0b0f05b48e32cda5f9e7d1b5ac2c3f12/crates/blockifier/src/fee/gas_usage.rs#L31)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

This does not clone the call infos, right?
</blockquote></details>

AFAIU it doesn't look [here](https://stackoverflow.com/questions/45195454/does-cloning-an-iterator-copy-the-entire-underlying-vector), but I can't say I understand 100% what happens there.


<!-- Sent from Reviewable.io -->

2024-02-08 12:21 UTC, barak-b-starkware commented
IIUC the test that runs `calculate_tx_gas_usage_vector` uses `CallInfo` without events.
You can see [here](https://github.com/starkware-libs/blockifier/blob/8fe05a45a9d490431d9e5c237577c77ab703f4d8/crates/blockifier/src/transaction/transactions_test.rs#L402C13-L408C33).





<!-- Sent from Reviewable.io -->

2024-02-08 12:21 UTC, barak-b-starkware commented
*[`crates/blockifier/src/fee/eth_gas_constants.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq6pIPOCmyTnBXkcsRA:-Nq7NVbs9eOKS36up1ym:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4c840ae0b0f05b48e32cda5f9e7d1b5ac2c3f12/crates/blockifier/src/fee/eth_gas_constants.rs#L31)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

These constants should be moved to `versioned_constants.json` (see #1426).
The file `eth_gas_constants.rs` is supposed to only include ETH constants that don't change (are part of the ETH protocol).
Constants that change between versions should be in `versioned_constants.json`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-08 14:24 UTC, barak-b-starkware reviewed
A unit test was added.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-:-Nq85eAn4b3-GhahAfMU:b-s1rl1h)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq6q9em15EBMwdOW6ye:-Nq85buE-9vHJ607gfpQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4c840ae0b0f05b48e32cda5f9e7d1b5ac2c3f12/crates/blockifier/src/fee/gas_usage.rs#L33)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

There should be a test where this number is not 0.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-08 19:02 UTC, giladchase requested changes
> Reviewed 6 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1458)* status: all files reviewed, 13 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, @barak-b-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 11 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq8RY7XA-aUxXMVfsN5:-Nq8RY7XA-aUxXMVfsN6:b9fu9qn) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/resources/versioned_constants.json#L11)):*
> ```JSON
>     "milligas_per_data_word": 2560,
>     "invoke_tx_max_n_steps": 3000000,
>     "max_recursion_depth": 50,
> ```

Top level keys are alphabetized



_Suggestion:_
```JSON
    "invoke_tx_max_n_steps": 3000000,
    "max_recursion_depth": 50,
    "milligas_per_key_byte": 40,
    "milligas_per_data_byte": 80,
    "milligas_per_key": 1280,
    "milligas_per_data_word": 2560,
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq8wHch2I8G6o9a5kbZ:-Nq8wHch2I8G6o9a5kb_:b-t7dbrj) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/versioned_constants.rs#L41)):*
> ```XML
>     pub milligas_per_data_byte: usize,
>     pub milligas_per_key: usize,
>     pub milligas_per_data_word: usize,
> ```

I'm getting confused about the types :sweat_smile:.

Gas is u128 (based on `GasVector`'s inner types) but miligas is usize? Isn't GasVector also used to represent miligas?



_Code quote:_
```XML
    pub milligas_per_key_byte: usize,
    pub milligas_per_data_byte: usize,
    pub milligas_per_key: usize,
    pub milligas_per_data_word: usize,
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq93vU28rh-IlDE21ZO:-Nq93vU28rh-IlDE21ZP:b-4dv94u) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/versioned_constants.rs#L41)):*
> ```XML
>     pub milligas_per_data_byte: usize,
>     pub milligas_per_key: usize,
>     pub milligas_per_data_word: usize,
> ```

These smell like tight coupling.

If that's the case plz pack into an appropriate struct with the same derives of VersionedConstants --- in the json this will add a nesting level under the key with the chosen name of the field that holds the new struct.



_Code quote:_
```XML
    pub milligas_per_key_byte: usize,
    pub milligas_per_data_byte: usize,
    pub milligas_per_key: usize,
    pub milligas_per_data_word: usize,
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq757L79oF3n3w5cYNy:-Nq93NME28T1-sdiAnoE:b-bq90up) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4c840ae0b0f05b48e32cda5f9e7d1b5ac2c3f12/crates/blockifier/src/fee/gas_usage.rs#L31)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

AFAIU it doesn't look [here](https://stackoverflow.com/questions/45195454/does-cloning-an-iterator-copy-the-entire-underlying-vector), but I can't say I understand 100% what happens there.
</blockquote></details>

Yep it's just cloning the iterator, which is a cheap op.
In general though, passing by & is preferred unless the type is `Copy` or ownership is explicitly needed.

But if it requires changing a bunch of out of scope stuff clone is fine here, otherwise, if passing by & is easy to change, remove the `+ Clone` trait bound.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq8ckpOEP1rZiGO0uVQ:-Nq8ckpOEP1rZiGO0uVR:b-tutpl6) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/fee/gas_usage.rs#L25)):*
> ```XML
> /// e.g., a message from L2 to L1 is followed by a storage write operation in Starknet L1 contract
> /// which requires gas.
> pub fn calculate_tx_gas_usage_vector<'a>(
> ```

Consider moving this as a method on `ActualCostBuilder`.
It is the only user, and two args appearing multiple times here are its fields.



_Code quote:_
```XML
pub fn calculate_tx_gas_usage_vector<'a>(
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq8efuh9kASuDHHwhdn:-Nq8efuiADpS7Oa9qqKs:b-lhlpug) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/fee/gas_usage.rs#L51)):*
> ```XML
>         l1_gas: milli_gas_vector.l1_gas / 1000,
>         l1_data_gas: milli_gas_vector.l1_data_gas / 1000,
>     }
> ```

Add `derive_more::Div` to `GasVector` for this to work (it already has Add/Sum).
Also add `Copy`, it's applicable.

Prefer sum over fold for summing.


BTW, if this were part of a method on ActualCostBuilder, the map could have been
 ```rust
map(self.get_events_milligas_cost_from_events)
```



_Suggestion:_
```XML
    let milli_gas_vector: GasVector = call_infos
        .map(|call_info| get_events_milligas_cost_from_events(call_info, versioned_constants))
        .sum();
        
    milli_gas_vector / 1000
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq8mp9d3kVMeQY6cYIi:-Nq8mp9d3kVMeQY6cYIj:b-jfy5x4) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/fee/gas_usage.rs#L51)):*
> ```XML
>         l1_gas: milli_gas_vector.l1_gas / 1000,
>         l1_data_gas: milli_gas_vector.l1_data_gas / 1000,
>     }
> ```

GasVector is used to represent both gas units and milli-gas units? Can we use different types? 



_Code quote:_
```XML
    GasVector {
        l1_gas: milli_gas_vector.l1_gas / 1000,
        l1_data_gas: milli_gas_vector.l1_data_gas / 1000,
    }
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 70 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq8swvWD6Fv1m3UxcrJ:-Nq8swvWD6Fv1m3UxcrK:b-q6umos) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/fee/gas_usage.rs#L70)):*
> ```XML
>                 l1_data_gas: 0_u128,
>             }
>         },
> ```

Prefer chaining and iterators whenever possible (unless it's forced), and try keeping nesting depth low.

Rust iterators are lazy: they do nothing until they are consumed (so this iterates only once even though there are two `map`s).

Also, if the lengths of both of these fields has meaning (i'm not well acquainted with this type),
consider adding to OrderedEvent something like `pub fn length(&self) -> (usize, usize)` to hide the `len` logic.



_Suggestion:_
```XML
let total_gas_vector = call_info
    .execution
    .events
    .iter()
    .map(|OrderedEvent { event, .. }| {
        let keys_gas = event.keys.len() * versioned_constants.milligas_per_key;
        let data_gas = event.data.0.len() * versioned_constants.milligas_per_data_word;
        u128_from_usize(keys_gas + data_gas)
            .expect("Could not convert starknet gas usage from usize to u128.")
    })
    .map(|l1_gas| GasVector { l1_gas, ..Default::default() })
    .sum();
```
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq91RNW3HLXTACuLnUc:-Nq91RNW3HLXTACuLnUd:buvikxw) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/fee/gas_usage_test.rs#L25)):*
> ```XML
>     serde_json::from_str(DEFAULT_CONSTANTS_JSON)
>         .expect("Versioned constants JSON file is malformed")
> });
> ```

or if you need ownership:
```rust
#[fixture]
#[once] [...]

2024-02-08 19:08 UTC, giladchase reviewed
I added a bunch of blocking comments, but due to the time constraints for this release, if you have no time to implement/challange the feel free to dismiss them all and add a monday task to revisit them, even for the sake of discussion.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-:-Nq969pe1nootqZFW9vc:b-scdliu)* status: all files reviewed, 13 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, @barak-b-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq8efuh9kASuDHHwhdn:-Nq95fdj5YJSxMEAILyz:b-vmebt0) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/fee/gas_usage.rs#L51)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Add `derive_more::Div` to `GasVector` for this to work (it already has Add/Sum).
Also add `Copy`, it's applicable.

Prefer sum over fold for summing.


BTW, if this were part of a method on ActualCostBuilder, the map could have been
 ```rust
map(self.get_events_milligas_cost_from_events)
```
</blockquote></details>

maybe even 
```rust
...
let gas_vector = milli_gas_vector / 1000
gas_vector
```
for more readability 


<!-- Sent from Reviewable.io -->

2024-02-09 06:46 UTC, Yoni-Starkware requested changes
> Reviewed 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1458)* status: all files reviewed, 12 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, and @barak-b-starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq7qDNh4mYmEo8pEQj2:-Nq7qDNh4mYmEo8pEQj3:bxszqmy) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca43491b24b22f32fb0ee71f3cc973a1190962de/crates/blockifier/src/fee/gas_usage.rs#L42)):*
> ```XML
>     versioned_constants: &VersionedConstants,
> ) -> GasVector {
>     let milli_gas_vector = call_infos.fold(
> ```

I think you should work here with an integer (rather than gas vector)
And wrap it up just to return



_Suggestion:_
```XML
milligas_vector = call_infos.fold(
```


<!-- Sent from Reviewable.io -->

2024-02-10 16:29 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1458)* status: 1 of 10 files reviewed, 11 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 11 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq8RY7XA-aUxXMVfsN5:-NqH0IWyCdmvIfcuPyFQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/resources/versioned_constants.json#L11)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Top level keys are alphabetized
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq8wHch2I8G6o9a5kbZ:-NqH0eotDKn2WAEBVqXN:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/versioned_constants.rs#L41)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I'm getting confused about the types :sweat_smile:.

Gas is u128 (based on `GasVector`'s inner types) but miligas is usize? Isn't GasVector also used to represent miligas?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq93vU28rh-IlDE21ZO:-NqHpDi49b9VOmBs_5q4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/versioned_constants.rs#L41)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

These smell like tight coupling.

If that's the case plz pack into an appropriate struct with the same derives of VersionedConstants --- in the json this will add a nesting level under the key with the chosen name of the field that holds the new struct.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq757L79oF3n3w5cYNy:-NqIKHML8ZpO6bTkXXf6:b-op4th8) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4c840ae0b0f05b48e32cda5f9e7d1b5ac2c3f12/crates/blockifier/src/fee/gas_usage.rs#L31)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Yep it's just cloning the iterator, which is a cheap op.
In general though, passing by & is preferred unless the type is `Copy` or ownership is explicitly needed.

But if it requires changing a bunch of out of scope stuff clone is fine here, otherwise, if passing by & is easy to change, remove the `+ Clone` trait bound.
</blockquote></details>

Passing by reference is possible, but it should be passed twice, and the first time will consume the iterator, so what do you prefer here?
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq7qDNh4mYmEo8pEQj2:-NqIKoVm12LX35BjVCYW:ba2uxq9) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca43491b24b22f32fb0ee71f3cc973a1190962de/crates/blockifier/src/fee/gas_usage.rs#L42)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I think you should work here with an integer (rather than gas vector)
And wrap it up just to return
</blockquote></details>

Changed according to @giladchase's suggestion. LMK if you like it or not (:
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq8ckpOEP1rZiGO0uVQ:-NqImJemCqLwvW8UvcvU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/fee/gas_usage.rs#L25)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Consider moving this as a method on `ActualCostBuilder`.
It is the only user, and two args appearing multiple times here are its fields.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq8efuh9kASuDHHwhdn:-NqIP5fi9Cz6h4lLwYGr:b-5cungi) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/fee/gas_usage.rs#L51)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

maybe even 
```rust
...
let gas_vector = milli_gas_vector / 1000
gas_vector
```
for more readability
</blockquote></details>

Done.
I added `Copy` but why to do that if it's not necessary right now?
Regarding your second suggestion, Clippy complains of `unnecessary 'let' binding`.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq8mp9d3kVMeQY6cYIi:-NqIS5NJBXBBbVCehUYv:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/fee/gas_usage.rs#L51)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

GasVector is used to represent both gas units and milli-gas units? Can we use different types?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 70 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq8swvWD6Fv1m3UxcrJ:-NqIVgwC6Q9FR6_QopHW:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/fee/gas_usage.rs#L70)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Prefer chaining and iterators whenever possible (unless it's forced), and try keeping nesting depth low.

Rust iterators are lazy: they do nothing until they are consumed (so this iterates only once even though there are two `map`s).

Also, if the lengths of both of these fields has meaning (i'm not well acquainted with this type),
consider adding to OrderedEvent something like `pub fn length(&self) -> (usize, usize)` to hide the `len` logic.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq91RNW3HLXTACuLnUc:-NqIY48V-c58KKr77aKD:b-ijjiqq) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/fee/gas_usage_test.rs#L25)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

or if you need ownership:
```rust
#[fixture]
#[once]
fn versioned_constants() -> VersionedConstants {
    VersionedConstants::latest_constants().clone()
}
```
</blockquote></details>

Done.
Didn't find any documentation or examples in our repo for `#[once]`, WDYM?
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 113 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq8SEJo3_1xPMpTr7-A:-NqHm8KkAx4Hut-dW8FF:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/fee/gas_usage_test.rs#L113)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Plz split into two separate tests without parameterization.

Unparameterized tests are easier to debug in general (less macros == easier debugging), and if there isn't too much duplication in the test itself (which is the case here) the complicated parameterization isn't worth it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-11 07:35 UTC, barak-b-starkware commented
*[`crates/blockifier/src/fee/gas_usage.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq8efuh9kASuDHHwhdn:-NqM4UZZ6pxabgJad5Yp:b6atjs1) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/fee/gas_usage.rs#L51)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Done.
I added `Copy` but why to do that if it's not necessary right now?
Regarding your second suggestion, Clippy complains of `unnecessary 'let' binding`.
</blockquote></details>

I agree that adding the `Copy` derivation is a good thing to do, it saves some redundant "clones" and it holds only two `u128` which are `Copy` too... good idea (: 


<!-- Sent from Reviewable.io -->

2024-02-11 08:26 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1458)* status: 1 of 10 files reviewed, 17 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, @barak-b-starkware, and @giladchase)

___
*[`crates/blockifier/resources/versioned_constants.json` line 8 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqM881M2y1baTVgmhZg:-NqM881M2y1baTVgmhZh:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5f98a031ae12cda4a7a19c62bbc9f52dc37258c7/crates/blockifier/resources/versioned_constants.json#L8)):*
> ```JSON
>     "event_gas_cost": {
>         "milligas_per_data_word": 2560,
>         "milligas_per_key": 1280
> ```





_Suggestion:_
```JSON
"event_key_factor": 2
```
___
*[`crates/blockifier/resources/versioned_constants.json` line 9 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqM7hWU-xhq0a824zr1:-NqM7hWU-xhq0a824zr2:b-2md9m7) ([raw file](https://github.com/starkware-libs/blockifier/blob/5f98a031ae12cda4a7a19c62bbc9f52dc37258c7/crates/blockifier/resources/versioned_constants.json#L9)):*
> ```JSON
>         "milligas_per_data_word": 2560,
>         "milligas_per_key": 1280
>     },
> ```

L2_resources



_Code quote:_
```JSON
    "event_gas_cost": {
        "milligas_per_data_word": 2560,
        "milligas_per_key": 1280
    },
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 55 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqMGQTW1ueFReTEmmhQ:-NqMGQTXEqPP8mTkIv8d:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4d31291dba17689fdfe6c7cf8244900376d49536/crates/blockifier/src/versioned_constants.rs#L55)):*
> ```XML
>     os_constants: Arc<OSConstants>,
> 
>     event_gas_cost: Arc<EventGasCost>,
> ```





_Suggestion:_
```XML
 l2_resource_gas_costs: Arc<EventGasCost>,
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 21 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqMBEcz6pfFNidHLCdL:-NqMBEcz6pfFNidHLCdM:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5f98a031ae12cda4a7a19c62bbc9f52dc37258c7/crates/blockifier/src/fee/gas_usage.rs#L21)):*
> ```XML
> pub mod test;
> 
> pub fn get_events_gas_cost<'a>(
> ```





_Suggestion:_
```XML
pub fn get_tx_events_gas_cost<'a>(
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 31 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqMBGubEm2NeAhjRaGg:-NqMBGubEm2NeAhjRaGh:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5f98a031ae12cda4a7a19c62bbc9f52dc37258c7/crates/blockifier/src/fee/gas_usage.rs#L31)):*
> ```XML
> }
> 
> pub fn get_events_milligas_cost_from_events(
> ```





_Suggestion:_
```XML
pub fn get_events_milligas_cost(
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 32 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqMCCnn-vlYoW__uYW6:-NqMCCnn-vlYoW__uYW7:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5f98a031ae12cda4a7a19c62bbc9f52dc37258c7/crates/blockifier/src/fee/gas_usage.rs#L32)):*
> ```XML
> 
> pub fn get_events_milligas_cost_from_events(
>     call_info: &CallInfo,
> ```





_Suggestion:_
```XML
events: &Vec<...>,
```


<!-- Sent from Reviewable.io -->

2024-02-11 08:50 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1458)* status: 1 of 10 files reviewed, 16 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 8 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqM881M2y1baTVgmhZg:-NqMKYP-2ABbSokRs95F:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5f98a031ae12cda4a7a19c62bbc9f52dc37258c7/crates/blockifier/resources/versioned_constants.json#L8)):*
> ```JSON
>     "event_gas_cost": {
>         "milligas_per_data_word": 2560,
>         "milligas_per_key": 1280
> ```

Done.
___
*[`crates/blockifier/resources/versioned_constants.json` line 9 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqM7hWU-xhq0a824zr1:-NqMKdeC7Lc40qwRYvvN:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5f98a031ae12cda4a7a19c62bbc9f52dc37258c7/crates/blockifier/resources/versioned_constants.json#L9)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

L2_resources
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 55 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqMGQTW1ueFReTEmmhQ:-NqMKrP4D-S0nl33r_Bx:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4d31291dba17689fdfe6c7cf8244900376d49536/crates/blockifier/src/versioned_constants.rs#L55)):*
> ```XML
>     os_constants: Arc<OSConstants>,
> 
>     event_gas_cost: Arc<EventGasCost>,
> ```

Done.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 31 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqMBGubEm2NeAhjRaGg:-NqMKw94DqpE--fbB02L:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5f98a031ae12cda4a7a19c62bbc9f52dc37258c7/crates/blockifier/src/fee/gas_usage.rs#L31)):*
> ```XML
> }
> 
> pub fn get_events_milligas_cost_from_events(
> ```

Done.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 32 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqMCCnn-vlYoW__uYW6:-NqMKwvuCfAFs84-RixU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5f98a031ae12cda4a7a19c62bbc9f52dc37258c7/crates/blockifier/src/fee/gas_usage.rs#L32)):*
> ```XML
> 
> pub fn get_events_milligas_cost_from_events(
>     call_info: &CallInfo,
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-02-11 11:53 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1458)* status: 1 of 10 files reviewed, 12 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, @barak-b-starkware, and @giladchase)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 46 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqN-taVCNbfu3YEYaeE:-NqN-taVCNbfu3YEYaeF:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b18f3cad00cdde0a709308c79a0cc1a527cf783/crates/blockifier/src/fee/gas_usage.rs#L46)):*
> ```XML
>             // num_bytes_data.
>             let num_keys = safe_u128_from_usize(event.keys.len());
>             let num_data_words = safe_u128_from_usize(event.data.0.len());
> ```





_Suggestion:_
```XML
            let keys_size = safe_u128_from_usize(event.keys.len());
            let data_size = safe_u128_from_usize(event.data.0.len());
```


<!-- Sent from Reviewable.io -->

2024-02-11 12:01 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1458)* status: 1 of 10 files reviewed, 13 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, @barak-b-starkware, and @giladchase)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 54 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqN1bc21xoa3Cc14CI1:-NqN1bc30LWM06kS4Jh5:b-luyffo) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b18f3cad00cdde0a709308c79a0cc1a527cf783/crates/blockifier/src/fee/gas_usage_test.rs#L54)):*
> ```XML
>             ..Default::default()
>         },
>         CallInfo {
> ```

Move this call to be an inner call of the first one (to check iteration)



_Code quote:_
```XML
       CallInfo {
```


<!-- Sent from Reviewable.io -->

2024-02-11 12:12 UTC, giladchase submitted a review, later dismissed
> Reviewed 2 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1458)* status: 1 of 10 files reviewed, 12 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, @barak-b-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 395 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqLyibp5jgl57kSO69v:-NqLyibp5jgl57kSO69w:b-77x3vc) ([raw file](https://github.com/starkware-libs/blockifier/blob/ed39d628935bd0cb3983d66d2fd6ec129d3c05d9/crates/blockifier/src/test_utils.rs#L395)):*
> ```XML
>         calldata: execute_calldata,
>     }
> }
> ```

Optional (maybe in a separate PR, or not at all):

Make this an associated function of `InvokeTxArgs` plz (create an `impl` block for it in invoke.rs and add it there with `Self` return type).



_Code quote:_
```XML
pub fn default_invoke_tx_args(
    account_contract_address: ContractAddress,
    test_contract_address: ContractAddress,
) -> InvokeTxArgs {
    let execute_calldata = create_calldata(
        test_contract_address,
        "return_result",
        &[stark_felt!(2_u8)], // Calldata: num.
    );

    invoke_tx_args! {
        max_fee: Fee(MAX_FEE),
        signature: TransactionSignature::default(),
        nonce: Nonce::default(),
        sender_address: account_contract_address,
        calldata: execute_calldata,
    }
}
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqMwsjR5SEiCDz9vGLK:-NqMwsjS5foI-Gp9UHnO:b-r9imq9) ([raw file](https://github.com/starkware-libs/blockifier/blob/ed39d628935bd0cb3983d66d2fd6ec129d3c05d9/crates/blockifier/src/versioned_constants.rs#L55)):*
> ```XML
>     os_constants: Arc<OSConstants>,
> 
>     event_gas_cost: Arc<EventGasCost>,
> ```

Is there some invariant over the values that require them to be private?
If there is, plz document it.

In general, we keep things public unless there is some invariant over the types that we don't want changed.

For example, the private fields in this struct all have hashmap fields that must contained a fixed set of keys, and removing any of them can cause runtime panics.



_Code quote:_
```XML
event_gas_cost: Arc<EventGasCost>,
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 148 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqM-1g5B_28PyUaMWPb:-NqM-1g5B_28PyUaMWPc:b3724vs) ([raw file](https://github.com/starkware-libs/blockifier/blob/ed39d628935bd0cb3983d66d2fd6ec129d3c05d9/crates/blockifier/src/fee/actual_cost.rs#L148)):*
> ```XML
>     }
> 
>     /// Returns an estimation of the L1 gas amount that will be used (by Starknet's state update and
> ```

Should the function be called `calculate` then? Or is `estimate` too overloaded in our context?



_Code quote:_
```XML
 estimation 
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 151 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqM-cl3E2CjmmdrQRlk:-NqM-cl3E2CjmmdrQRll:b-vsl2sv) ([raw file](https://github.com/starkware-libs/blockifier/blob/ed39d628935bd0cb3983d66d2fd6ec129d3c05d9/crates/blockifier/src/fee/actual_cost.rs#L151)):*
> ```XML
>     /// the Verifier) following the addition of a transaction with the given parameters to a batch;
>     /// e.g., a message from L2 to L1 is followed by a storage write operation in Starknet L1
>     /// contract which requires gas.
> ```

Active voice.



_Suggestion:_
```XML
    /// Calculates an estimated gas usage for a transaction on L1, based on the provided parameters.
    /// This function estimates the amount of L1 gas required for processing state updates and
    /// verification after adding a transaction to a batch. This includes scenarios such as L2 to L1
    /// messages, which result in storage write operations on the StarkNet L1 contract, consuming
    /// gas.
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 163 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqM0ybO1x6edN135hqz:-NqM0ybO1x6edN135hr-:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ed39d628935bd0cb3983d66d2fd6ec129d3c05d9/crates/blockifier/src/fee/actual_cost.rs#L163)):*
> ```XML
>             + get_da_gas_cost(state_changes_count, use_kzg_da)
>             + get_events_gas_cost(call_infos, versioned_constants))
>     }
> ```





_Suggestion:_
```XML
    fn calculate_tx_gas_usage_vector(
        call_infos: impl Iterator<Item = &'a CallInfo> + Clone,
        state_changes_count: StateChangesCount,
        use_kzg_da: bool,
    ) -> TransactionExecutionResult<GasVector> {
        let versioned_constants = &self.tx_context.block_context.versioned_constants,
        // TODO(barak, 18/03/2024): Iterate over call_infos once without cloning.
        Ok(get_messages_gas_cost(call_infos.clone(), self.l1_payload_size)?
            + get_da_gas_cost(state_changes_count, use_kzg_da)
            + get_events_gas_cost(call_infos, versioned_constants))
    }
```
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq8efuh9kASuDHHwhdn:-NqLsw_OEphuR-a54or3:b-v6udhd) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/fee/gas_usage.rs#L51)):*
Tnx.

> I added `Copy` but why to do that if it's not necessary right now?

Just cause if you were already messing with its derive then adding Copy will help anyone using this type (i think this made you remove a few clones here in this PR?)

Ya clippy is right i guess, but the `From` makes it unnecessary anyway, now that the types are explicit.
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 37 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqLsTr_3pBUD3Ed83YV:-NqLsTr_3pBUD3Ed83YW:btov00o) ([raw file](https://github.com/starkware-libs/blockifier/blob/ed39d628935bd0cb3983d66d2fd6ec129d3c05d9/crates/blockifier/src/fee/gas_usage.rs#L37)):*
> ```XML
>     let (key_factor, data_word_factor) = versioned_constants.get_event_milligas_cost();
>     let safe_u128_from_usize =
>         |x| u128_from_usize(x).expect("Could not convert starknet gas usage from usize to u128.");
> ```

Nice :star_struck: : 

(I really wish that expect had been part of the u128_from_usize so this wouldn't have been necesssary, but that change is obviously out of scope here.)



_Code quote:_
```XML
    let safe_u128_from_usize =
        |x| u128_from_usize(x).expect("Could not convert starknet gas usage from usize to u128.");
```
___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq91RNW3HLXTACuLnUc:-NqLrdoXAg2FyTjgWrzm:b-anxg4b) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/fee/gas_usage_test.rs#L25)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Done.
Didn't find any documentation or examples in our repo for `#[once]`, WDYM?
</blockquote></details>

Tnx.

It creates a static instance, rather than cloning it every time, but upon reading the docs i realized [it must be passed by reference](https://docs.rs/rstest/latest/rstest/attr.fixture.html#once-fixture), so not relevant for ownership :smiling_face_with_tear: 


<!-- Sent from Reviewable.io -->

2024-02-11 12:16 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1458)* status: 1 of 10 files reviewed, 12 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, @barak-b-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq757L79oF3n3w5cYNy:-NqN56teE84QmszKW7l3:byq2mk3) ([raw file](https://github.com/starkware-libs/blockifier/blob/f4c840ae0b0f05b48e32cda5f9e7d1b5ac2c3f12/crates/blockifier/src/fee/gas_usage.rs#L31)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Passing by reference is possible, but it should be passed twice, and the first time will consume the iterator, so what do you prefer here?
</blockquote></details>

Yaaa i was stupid, an immutable ref wouldn't have worked anyway, since iterating over an iterator requires &mut, and indeed consumes it, like you said.
Clone it is :grimacing: 


<!-- Sent from Reviewable.io -->

2024-02-11 12:19 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1458)* status: 1 of 12 files reviewed, 12 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, @barak-b-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq7qDNh4mYmEo8pEQj2:-NqN5fN52ljQxaCnpXD3:b1i89ez) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca43491b24b22f32fb0ee71f3cc973a1190962de/crates/blockifier/src/fee/gas_usage.rs#L42)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Changed according to @giladchase's suggestion. LMK if you like it or not (:
</blockquote></details>

Oh if Yoni explicitly requesed something go with what he said, i'm just HAPASH


<!-- Sent from Reviewable.io -->

2024-02-11 12:25 UTC, barak-b-starkware commented
*[`crates/blockifier/src/fee/gas_usage.rs` line 46 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqN-taVCNbfu3YEYaeE:-NqN7Jzw4gI3L-5eILTv:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b18f3cad00cdde0a709308c79a0cc1a527cf783/crates/blockifier/src/fee/gas_usage.rs#L46)):*
> ```XML
>             // num_bytes_data.
>             let num_keys = safe_u128_from_usize(event.keys.len());
>             let num_data_words = safe_u128_from_usize(event.data.0.len());
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-02-11 12:53 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1458)* status: 2 of 12 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, @barak-b-starkware, and @giladchase)

___
*[`crates/blockifier/src/versioned_constants.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqMwsjR5SEiCDz9vGLK:-NqNDV1T3muajlBCo8SI:bh0ygsn) ([raw file](https://github.com/starkware-libs/blockifier/blob/ed39d628935bd0cb3983d66d2fd6ec129d3c05d9/crates/blockifier/src/versioned_constants.rs#L55)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Is there some invariant over the values that require them to be private?
If there is, plz document it.

In general, we keep things public unless there is some invariant over the types that we don't want changed.

For example, the private fields in this struct all have hashmap fields that must contained a fixed set of keys, and removing any of them can cause runtime panics.
</blockquote></details>

Avi changed it to `pub l2_resource_gas_costs: L2ResourceGasCosts`


<!-- Sent from Reviewable.io -->

2024-02-11 12:59 UTC, barak-b-starkware commented
*[`crates/blockifier/src/fee/gas_usage.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-Nq8efuh9kASuDHHwhdn:-NqNEznq8rM1UaqOBv7W:b310a6g) ([raw file](https://github.com/starkware-libs/blockifier/blob/03c157be75e887e98e8a83be793585116599d7e8/crates/blockifier/src/fee/gas_usage.rs#L51)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Tnx.

> I added `Copy` but why to do that if it's not necessary right now?

Just cause if you were already messing with its derive then adding Copy will help anyone using this type (i think this made you remove a few clones here in this PR?)

Ya clippy is right i guess, but the `From` makes it unnecessary anyway, now that the types are explicit.
</blockquote></details>

Blocking by mistake? Or did you ask for something here?


<!-- Sent from Reviewable.io -->

2024-02-11 13:00 UTC, barak-b-starkware commented
*[`crates/blockifier/src/fee/gas_usage.rs` line 37 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqLsTr_3pBUD3Ed83YV:-NqNFH_m2dSnV0ly_jKC:b310a6g) ([raw file](https://github.com/starkware-libs/blockifier/blob/ed39d628935bd0cb3983d66d2fd6ec129d3c05d9/crates/blockifier/src/fee/gas_usage.rs#L37)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Nice :star_struck: : 

(I really wish that expect had been part of the u128_from_usize so this wouldn't have been necesssary, but that change is obviously out of scope here.)
</blockquote></details>

Blocking by mistake? Or did you ask for something here?


<!-- Sent from Reviewable.io -->

2024-02-11 13:16 UTC, barak-b-starkware commented
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 54 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqN1bc21xoa3Cc14CI1:-NqNJ2x09qh8SIj09AeO:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7b18f3cad00cdde0a709308c79a0cc1a527cf783/crates/blockifier/src/fee/gas_usage_test.rs#L54)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Move this call to be an inner call of the first one (to check iteration)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-11 13:19 UTC, barak-b-starkware commented
*[`crates/blockifier/src/versioned_constants.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqMwsjR5SEiCDz9vGLK:-NqNJeAC10Ge-8IJbP_J:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ed39d628935bd0cb3983d66d2fd6ec129d3c05d9/crates/blockifier/src/versioned_constants.rs#L55)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Avi changed it to `pub l2_resource_gas_costs: L2ResourceGasCosts`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-11 13:22 UTC, barak-b-starkware commented
*[`crates/blockifier/src/fee/actual_cost.rs` line 163 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqM0ybO1x6edN135hqz:-NqNK6963z5EWlA76_CM:b-kknrje) ([raw file](https://github.com/starkware-libs/blockifier/blob/ed39d628935bd0cb3983d66d2fd6ec129d3c05d9/crates/blockifier/src/fee/actual_cost.rs#L163)):*
> ```XML
>             + get_da_gas_cost(state_changes_count, use_kzg_da)
>             + get_events_gas_cost(call_infos, versioned_constants))
>     }
> ```

At @Yoni-Starkware 's request, it moved back, so the changes you requested can't be done (using `self`).


<!-- Sent from Reviewable.io -->

2024-02-11 14:44 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1458)* status: 2 of 12 files reviewed, 8 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, @barak-b-starkware, and @giladchase)

___
*[`crates/blockifier/src/fee/gas_usage.rs` line 24 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqNa1gxDnqfWir_cevj:-NqNa1gxDnqfWir_cevk:b-jre3oa) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ebaf431c2da7fb5f813f4620c07a183d97f7f7/crates/blockifier/src/fee/gas_usage.rs#L24)):*
> ```XML
> /// Returns an estimation of the L1 gas amount that will be used (by Starknet's state update and
> /// the Verifier) following the addition of a transaction with the given parameters to a batch;
> /// e.g., a message from L2 to L1 is followed by a storage write operation in Starknet L1 contract
> ```

Document as follows:



_Suggestion:_
```XML
/// Returns the gas usage of a transaction, specifically: 
/// * L1 gas, used by Starknet's state update and the Verifier, 
///   e.g., a message from L2 to L1 is followed by a storage write operation on L1.
/// * L1 data gas, for publishing data availability.
/// * L2 resources cost, e.g., for storing transaction calldata.
```


<!-- Sent from Reviewable.io -->

2024-02-11 14:46 UTC, barak-b-starkware commented
*[`crates/blockifier/src/fee/gas_usage.rs` line 24 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqNa1gxDnqfWir_cevj:-NqNcX44CkDeu3RKPdo0:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/98ebaf431c2da7fb5f813f4620c07a183d97f7f7/crates/blockifier/src/fee/gas_usage.rs#L24)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Document as follows:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-11 14:47 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1458)* status: 2 of 12 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, @barak-b-starkware, and @giladchase)

___
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 37 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqNcpTg-qhWJKDD35dG:-NqNcpTg-qhWJKDD35dH:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/023a59b4247234e6cef4d4a850a8670da9f02f35/crates/blockifier/src/fee/gas_usage_test.rs#L37)):*
> ```XML
>     assert_eq!(GasVector::default(), get_tx_events_gas_cost(call_infos, versioned_constants));
> 
>     let create_trivial_ordered_event_from_keys_and_data_sizes =
> ```





_Suggestion:_
```XML
create_event
```


<!-- Sent from Reviewable.io -->

2024-02-11 14:48 UTC, barak-b-starkware commented
*[`crates/blockifier/src/fee/gas_usage_test.rs` line 37 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-NqNcpTg-qhWJKDD35dG:-NqNd3qbD0Iaz4LL1miq:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/023a59b4247234e6cef4d4a850a8670da9f02f35/crates/blockifier/src/fee/gas_usage_test.rs#L37)):*
> ```XML
>     assert_eq!(GasVector::default(), get_tx_events_gas_cost(call_infos, versioned_constants));
> 
>     let create_trivial_ordered_event_from_keys_and_data_sizes =
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-02-11 14:51 UTC, Yoni-Starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 6 files at r7, 1 of 5 files at r10, 6 of 7 files at r12, 1 of 3 files at r15, 1 of 1 files at r16, 1 of 1 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1458#-:-NqNde_wAdFV2t7z9sWn:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, and @giladchase)



<!-- Sent from Reviewable.io -->

2024-02-11 15:32 UTC, Yoni-Starkware approved these changes
> Reviewed 3 of 3 files at r19, all commit messages.
> Dismissed @giladchase from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1458)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @avi-starkware, and @giladchase)



<!-- Sent from Reviewable.io -->

2024-02-11 15:33 UTC, Yoni-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1458)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware, @avi-starkware, and @giladchase)



<!-- Sent from Reviewable.io -->

2024-02-11 15:35 UTC, merged