feat(execution): round block_number and timestamp for the execution info syscall in validate_mode
starkware-libs/blockifier pull request #1467
Opened 2024-02-08 14:10 UTC by TzahiTaub

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1467)

2024-02-08 14:36 UTC, ArniStarkware commented
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-Nq88HcV9yyleRONlm6A:-Nq88HcV9yyleRONlm6B:bf808p7) ([raw file](https://github.com/starkware-libs/blockifier/blob/b2f4c3ee6cca92fcb948e8e57b23e39e7dda06a6/crates/blockifier/src/execution/syscalls/hint_processor.rs#L146)):*
> ```XML
> pub const VALIDATE_BLOCK_NUMBER_FLOORING: u64 = 100;
> // "Ceiling factor for timestamp in validate mode";
> pub const VALIDATE_TIMESTAMP_ROUNDING_CEILING: u64 = 3600;
> ```

These constants are not related to ` Error codes`.

Write a regular doc string, and add a TODO to move to the correct constants file.



_Code quote:_
```XML
// "Flooring factor for block number in validate mode";
pub const VALIDATE_BLOCK_NUMBER_FLOORING: u64 = 100;
// "Ceiling factor for timestamp in validate mode";
pub const VALIDATE_TIMESTAMP_ROUNDING_CEILING: u64 = 3600;
```


<!-- Sent from Reviewable.io -->

2024-02-08 14:40 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 146 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-Nq88HcV9yyleRONlm6A:-Nq89RIS6nA-Y7SVW5a0:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b2f4c3ee6cca92fcb948e8e57b23e39e7dda06a6/crates/blockifier/src/execution/syscalls/hint_processor.rs#L146)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

These constants are not related to ` Error codes`.

Write a regular doc string, and add a TODO to move to the correct constants file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-08 14:41 UTC, ArniStarkware reviewed
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-02-08 14:41 UTC, ArniStarkware reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-02-08 16:03 UTC, ArniStarkware reviewed
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-02-11 11:27 UTC, ArniStarkware commented
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 125 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqMuK0j6XFeUurhntV0:-NqMuK0j6XFeUurhntV1:b-xpnt98) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d1bf7779050152391b9f9f0e6759401702b2c20/crates/blockifier/src/test_utils/struct_impls.rs#L125)):*
> ```XML
>             use_kzg_da: false,
>         }
>     }
> ```

To improve maintainability (Not change all other irrelevant instances of create_for_testing, I would create a function that accepts the validate mode flag.



_Suggestion:_
```XML
    pub fn create_for_testing() -> Self {
        Self::create_for_validation_mode_testing(false)
    }
    
    pub fn create_for_validation_mode_testing(is_validate: bool) -> Self {
        let block_number = if is_validate {
            (CURRENT_BLOCK_NUMBER / VALIDATE_BLOCK_NUMBER_ROUNDING) * VALIDATE_BLOCK_NUMBER_ROUNDING
        } else {
            CURRENT_BLOCK_NUMBER
        };
        let timestamp = if is_validate {
            (CURRENT_BLOCK_TIMESTAMP / VALIDATE_TIMESTAMP_ROUNDING) * VALIDATE_TIMESTAMP_ROUNDING
        } else {
            CURRENT_BLOCK_TIMESTAMP
        };
        Self {
            block_number: BlockNumber(block_number),
            block_timestamp: BlockTimestamp(timestamp),
            sequencer_address: contract_address!(TEST_SEQUENCER_ADDRESS),
            gas_prices: GasPrices {
                eth_l1_gas_price: DEFAULT_ETH_L1_GAS_PRICE.try_into().unwrap(),
                strk_l1_gas_price: DEFAULT_STRK_L1_GAS_PRICE.try_into().unwrap(),
                eth_l1_data_gas_price: DEFAULT_ETH_L1_DATA_GAS_PRICE.try_into().unwrap(),
                strk_l1_data_gas_price: DEFAULT_STRK_L1_DATA_GAS_PRICE.try_into().unwrap(),
            },
            use_kzg_da: false,
        }
    }
```


<!-- Sent from Reviewable.io -->

2024-02-11 11:31 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqMvpib8G8LxhB9VTfI:-NqMvpicB96gk3b0fRNs:bta0nby) (no related file):*
Python PR?

___


<!-- Sent from Reviewable.io -->

2024-02-11 11:31 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 409 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqMvrxE7UIn_2LtvyRD:-NqMvrxE7UIn_2LtvyRE:bbykzej) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d1bf7779050152391b9f9f0e6759401702b2c20/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L409)):*
> ```XML
>         ),
>         false => block_number,
>     };
> ```

When a new execution mode is added, we want the compiler to scream.



_Suggestion:_
```XML
    let block_number = match syscall_handler.execution_mode() {
        ExecutionMode::Validate => BlockNumber(
            (block_number.0 / VALIDATE_BLOCK_NUMBER_ROUNDING) * VALIDATE_BLOCK_NUMBER_ROUNDING,
        ),
        ExecutionMode::Execute => block_number,
    };
```


<!-- Sent from Reviewable.io -->

2024-02-11 11:32 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 435 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqMw7R23i3MC_fI-FtS:-NqMw7R23i3MC_fI-FtT:bj8bld6) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d1bf7779050152391b9f9f0e6759401702b2c20/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L435)):*
> ```XML
> ) -> DeprecatedSyscallResult<GetBlockTimestampResponse> {
>     let block_timestamp = syscall_handler.get_block_info().block_timestamp;
>     let block_timestamp = match syscall_handler.is_validate_mode() {
> ```

same as above.



_Suggestion:_
```XML
    let block_timestamp = match syscall_handler.execution_mode() {
```


<!-- Sent from Reviewable.io -->

2024-02-11 11:35 UTC, ArniStarkware commented
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 102 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqMwNYtE9bDfeOzWO8Q:-NqMwNYtE9bDfeOzWO8R:b1ikh0d) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d1bf7779050152391b9f9f0e6759401702b2c20/crates/blockifier/src/test_utils/struct_impls.rs#L102)):*
> ```XML
> 
> impl BlockInfo {
>     pub fn create_for_testing(is_validate: bool) -> Self {
> ```

Another, non-conflicting comment about `create_for_testing`:
use the execution mode as the parameter that affects the sequencer address.



_Suggestion:_
```XML
pub fn create_for_testing(execution_mode: ExecutionMode) -> Self {
```


<!-- Sent from Reviewable.io -->

2024-02-11 11:36 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 3 of 8 files reviewed, 6 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 116 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqMwxgO9Oq7MgQ0PlJ9:-NqMwxgP388lJUJPpl7y:b-48vwu7) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d1bf7779050152391b9f9f0e6759401702b2c20/crates/blockifier/src/test_utils/struct_impls.rs#L116)):*
> ```XML
>             block_number: BlockNumber(block_number),
>             block_timestamp: BlockTimestamp(timestamp),
>             sequencer_address: contract_address!(TEST_SEQUENCER_ADDRESS),
> ```

The sequencer address should be `0` on execution mode `Validate`.



_Code quote:_
```XML
contract_address!(TEST_SEQUENCER_ADDRESS),
```


<!-- Sent from Reviewable.io -->

2024-02-11 12:09 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 3 of 8 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @elintul, and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqMvpib8G8LxhB9VTfI:-NqMxlTF1akIDDN3DU80:b-u7bdcx) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Python PR?
</blockquote></details>

https://reviewable.io/reviews/starkware-industries/starkware/33887#-
(and also this https://reviewable.io/reviews/starkware-industries/starkware/33896#- though it's for deprecated code)

___
___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 409 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqMvrxE7UIn_2LtvyRD:-NqMyXFNAS1x-wAWRsIM:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d1bf7779050152391b9f9f0e6759401702b2c20/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L409)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

When a new execution mode is added, we want the compiler to scream.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 435 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqMw7R23i3MC_fI-FtS:-NqMyX2S3neBj3Co0E-Q:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d1bf7779050152391b9f9f0e6759401702b2c20/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L435)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 102 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqMwNYtE9bDfeOzWO8Q:-NqN-cJC0Qj_XCHKtSfU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d1bf7779050152391b9f9f0e6759401702b2c20/crates/blockifier/src/test_utils/struct_impls.rs#L102)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Another, non-conflicting comment about `create_for_testing`:
use the execution mode as the parameter that affects the sequencer address.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 116 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqMwxgO9Oq7MgQ0PlJ9:-NqN095p0ZNUMWu5AalX:b8qrael) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d1bf7779050152391b9f9f0e6759401702b2c20/crates/blockifier/src/test_utils/struct_impls.rs#L116)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The sequencer address should be `0` on execution mode `Validate`.
</blockquote></details>

Um, OK. Done.
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 125 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqMuK0j6XFeUurhntV0:-NqN3YxBCOWkzTfXlNzb:bkk367o) ([raw file](https://github.com/starkware-libs/blockifier/blob/8d1bf7779050152391b9f9f0e6759401702b2c20/crates/blockifier/src/test_utils/struct_impls.rs#L125)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

To improve maintainability (Not change all other irrelevant instances of create_for_testing, I would create a function that accepts the validate mode flag.
</blockquote></details>

I think this is OK.


<!-- Sent from Reviewable.io -->

2024-02-11 13:02 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @elintul and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 24 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNCklq51ZStAs7m2cL:-NqNCklq51ZStAs7m2cM:b-a9jwm3) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/execution/syscalls/hint_processor.rs#L24)):*
> ```XML
> use starknet_api::state::StorageKey;
> use starknet_api::transaction::{Calldata, Resource};
> use starknet_api::{stark_felt, StarknetApiError};
> ```

This macro is for tests only, it uses unwrap injudiciously (see its definition).
It's unfortunantely available in non-test modules due to implementation constraints.

Use regular constructors for StarkFelt plz



_Code quote:_
```XML
:{stark_felt, 
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 494 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNFRWeCRtsAio5kyDP:-NqNFRWeCRtsAio5kyDQ:b-xeh3zb) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/execution/syscalls/hint_processor.rs#L494)):*
> ```XML
>             let block_number_u64: u64 = block_number.try_into()?;
>             let rounded_block_number = (block_number_u64 / VALIDATE_BLOCK_NUMBER_ROUNDING)
>                 * VALIDATE_BLOCK_NUMBER_ROUNDING;
> ```

Ditto for the other one.



_Suggestion:_
```XML
            // Round down to the nearest multiple of VALIDATE_BLOCK_NUMBER_ROUNDING.
            let rounded_block_number = (block_number_u64 / VALIDATE_BLOCK_NUMBER_ROUNDING)
                * VALIDATE_BLOCK_NUMBER_ROUNDING;
```


<!-- Sent from Reviewable.io -->

2024-02-11 13:09 UTC, ArniStarkware commented
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 78 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNH80CEuTisuKM_8gl:-NqNH80CEuTisuKM_8gm:b8knpct) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/test_utils/struct_impls.rs#L78)):*
> ```XML
>             ),
>             tx_info,
>         };
> ```

Do we want to change the block context, given that we are in validate mode?



_Code quote:_
```XML
        let tx_context = TransactionContext {
            block_context: BlockContext::create_for_validation_mode_testing(
                ExecutionMode::Validate,
            ),
            tx_info,
        };
```


<!-- Sent from Reviewable.io -->

2024-02-11 13:12 UTC, liorgold2 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @elintul)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 78 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNH80CEuTisuKM_8gl:-NqNHsuC0jDmSKSebuaz:burlfdh) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/test_utils/struct_impls.rs#L78)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Do we want to change the block context, given that we are in validate mode?
</blockquote></details>

IIUC, tx_context shouldn't depend on validate mode. It's for the entire tx.


<!-- Sent from Reviewable.io -->

2024-02-11 13:13 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @elintul, and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 111 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNI9GgCX7ixINId0md:-NqNI9GgCX7ixINId0me:b-i8w5su) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/test_utils/struct_impls.rs#L111)):*
> ```XML
>     }
> 
>     pub fn create_for_validation_mode_testing(execution_mode: ExecutionMode) -> Self {
> ```

I don't think this should be there. @giladchase ?


<!-- Sent from Reviewable.io -->

2024-02-11 13:13 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @elintul)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 78 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNH80CEuTisuKM_8gl:-NqNI9Mw1tzyxiCqfICJ:b-abdc5y) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/test_utils/struct_impls.rs#L78)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

IIUC, tx_context shouldn't depend on validate mode. It's for the entire tx.
</blockquote></details>

At least from the what I see in the fields - THe context holds BlockInfo that holds the block_number and timestamp (which are dependant in the validate_mode)


<!-- Sent from Reviewable.io -->

2024-02-11 13:17 UTC, liorgold2 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @elintul, and @TzahiTaub)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 412 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNItjs0yWoNcp6U_bC:-NqNItjtDQMmV9RdUKAZ:brb8y9l) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L412)):*
> ```XML
> #[test_case(
>     ExecutionMode::Validate, "block_number", calldata![stark_felt!(
>         (CURRENT_BLOCK_NUMBER / VALIDATE_BLOCK_NUMBER_ROUNDING) * VALIDATE_BLOCK_NUMBER_ROUNDING)];
> ```

Add a constant `CURRENT_BLOCK_NUMBER_FOR_VALIDATE = 2000` next to `CURRENT_BLOCK_NUMBER`. This will allow the reader to be convinced that the values are correct.



_Code quote:_
```XML
(CURRENT_BLOCK_NUMBER / VALIDATE_BLOCK_NUMBER_ROUNDING) * VALIDATE_BLOCK_NUMBER_ROUNDING
```


<!-- Sent from Reviewable.io -->

2024-02-11 13:17 UTC, ArniStarkware commented
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 78 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNH80CEuTisuKM_8gl:-NqNIXwnE8TesrB97AcH:bs87k65) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/test_utils/struct_impls.rs#L78)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

At least from the what I see in the fields - THe context holds BlockInfo that holds the block_number and timestamp (which are dependant in the validate_mode)
</blockquote></details>

The confusing thing is this: there are two (sets of) related numbers.

The block number (and block timestamp) and the returned block number (timestamp) by the syscall in validate mode.
The block number should not be changed. We are only affecting the returned value.


<!-- Sent from Reviewable.io -->

2024-02-11 13:20 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @liorgold2 and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 24 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNCklq51ZStAs7m2cL:-NqNCklq51ZStAs7m2cM:b5eklic) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/execution/syscalls/hint_processor.rs#L24)):*
> ```XML
> use starknet_api::state::StorageKey;
> use starknet_api::transaction::{Calldata, Resource};
> use starknet_api::{stark_felt, StarknetApiError};
> ```

This macro is for tests only, it uses unwrap injudiciously (see its definition).
It's unfortunantely available in non-test modules due to implementation constraints (we'll fix it at another time).

Use regular constructors for StarkFelt plz



_Code quote:_
```XML
:{stark_felt, 
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 494 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNFRWeCRtsAio5kyDP:-NqNFRWeCRtsAio5kyDQ:b5oa425) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/execution/syscalls/hint_processor.rs#L494)):*
> ```XML
>             let block_number_u64: u64 = block_number.try_into()?;
>             let rounded_block_number = (block_number_u64 / VALIDATE_BLOCK_NUMBER_ROUNDING)
>                 * VALIDATE_BLOCK_NUMBER_ROUNDING;
> ```


Ditto for the other one.
If you do it one more time then usse a utility function



_Suggestion:_
```XML
            // Round down to the nearest multiple of VALIDATE_BLOCK_NUMBER_ROUNDING.
            let rounded_block_number = (block_number_u64 / VALIDATE_BLOCK_NUMBER_ROUNDING)
                * VALIDATE_BLOCK_NUMBER_ROUNDING;
```


<!-- Sent from Reviewable.io -->

2024-02-11 13:20 UTC, Yoni-Starkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 3 of 8 files reviewed, 6 unresolved discussions (waiting on @elintul, @liorgold2, and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 494 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNJMSc2m5HxSQ_1TaX:-NqNJMSc2m5HxSQ_1TaY:b-ooqfvr) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/execution/syscalls/hint_processor.rs#L494)):*
> ```XML
>             let block_number_u64: u64 = block_number.try_into()?;
>             let rounded_block_number = (block_number_u64 / VALIDATE_BLOCK_NUMBER_ROUNDING)
>                 * VALIDATE_BLOCK_NUMBER_ROUNDING;
> ```

Add a `round` util (non-blocking)



_Code quote:_
```XML
            let rounded_block_number = (block_number_u64 / VALIDATE_BLOCK_NUMBER_ROUNDING)
                * VALIDATE_BLOCK_NUMBER_ROUNDING;
```


<!-- Sent from Reviewable.io -->

2024-02-11 13:21 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 3 of 8 files reviewed, 7 unresolved discussions (waiting on @elintul, @liorgold2, and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 497 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNK2vO4kGnv-rh-8Qo:-NqNK2vO4kGnv-rh-8Qp:b3kqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/execution/syscalls/hint_processor.rs#L497)):*
> ```XML
>             let block_timestamp_u64: u64 = block_timestamp.try_into()?;
>             let rounded_timestamp =
>                 (block_timestamp_u64 / VALIDATE_TIMESTAMP_ROUNDING) * VALIDATE_TIMESTAMP_ROUNDING;
> ```

.



_Suggestion:_
```XML
        let block_data: Vec<StarkFelt> = if self.is_validate_mode() {
            let rounded_block_number = (block_info.block_number.0 / VALIDATE_BLOCK_NUMBER_ROUNDING)
                * VALIDATE_BLOCK_NUMBER_ROUNDING;
            let rounded_timestamp =
                (block_info.block_timestamp.0 / VALIDATE_TIMESTAMP_ROUNDING) * VALIDATE_TIMESTAMP_ROUNDING;
```


<!-- Sent from Reviewable.io -->

2024-02-11 13:27 UTC, liorgold2 reviewed
> Reviewed 1 of 3 files at r1, 1 of 5 files at r5, 1 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 5 of 8 files reviewed, 7 unresolved discussions (waiting on @elintul and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-02-11 13:27 UTC, Yoni-Starkware submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 5 of 8 files reviewed, 8 unresolved discussions (waiting on @elintul, @liorgold2, and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 499 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNLYYe8P7V3CzveC1J:-NqNLYYe8P7V3CzveC1K:bt36bn0) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/execution/syscalls/hint_processor.rs#L499)):*
> ```XML
>                 (block_timestamp_u64 / VALIDATE_TIMESTAMP_ROUNDING) * VALIDATE_TIMESTAMP_ROUNDING;
> 
>             vec![stark_felt!(rounded_block_number), stark_felt!(rounded_timestamp), StarkFelt::ZERO]
> ```

Use StarkFelt::from



_Code quote:_
```XML
stark_felt!(rounded_block_number),
```


<!-- Sent from Reviewable.io -->

2024-02-11 13:31 UTC, liorgold2 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 5 of 8 files reviewed, 9 unresolved discussions (waiting on @elintul and @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 494 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNMAduBqv7Bu0ZTBij:-NqNMAduBqv7Bu0ZTBik:b-hljt63) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/execution/syscalls/hint_processor.rs#L494)):*
> ```XML
>             let block_number_u64: u64 = block_number.try_into()?;
>             let rounded_block_number = (block_number_u64 / VALIDATE_BLOCK_NUMBER_ROUNDING)
>                 * VALIDATE_BLOCK_NUMBER_ROUNDING;
> ```

For later (non-blocking): this can become a function of BlockNumber: `round_for_validate()`



_Code quote:_
```XML
            let rounded_block_number = (block_number_u64 / VALIDATE_BLOCK_NUMBER_ROUNDING)
                * VALIDATE_BLOCK_NUMBER_ROUNDING;
```


<!-- Sent from Reviewable.io -->

2024-02-11 13:33 UTC, liorgold2 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 5 of 8 files reviewed, 9 unresolved discussions (waiting on @elintul, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 499 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNLYYe8P7V3CzveC1J:-NqNMksaBd2Ntg1Yagxy:bbha6g7) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/execution/syscalls/hint_processor.rs#L499)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Use StarkFelt::from
</blockquote></details>

or `into`?


<!-- Sent from Reviewable.io -->

2024-02-11 13:36 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 5 of 8 files reviewed, 9 unresolved discussions (waiting on @elintul, @giladchase, @liorgold2, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs` line 412 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNItjs0yWoNcp6U_bC:-NqNKuW3BCaBVpKOEODx:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs#L412)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Add a constant `CURRENT_BLOCK_NUMBER_FOR_VALIDATE = 2000` next to `CURRENT_BLOCK_NUMBER`. This will allow the reader to be convinced that the values are correct.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 24 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNCklq51ZStAs7m2cL:-NqNLAxRAl_FCu3bnR2L:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/execution/syscalls/hint_processor.rs#L24)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This macro is for tests only, it uses unwrap injudiciously (see its definition).
It's unfortunantely available in non-test modules due to implementation constraints (we'll fix it at another time).

Use regular constructors for StarkFelt plz
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 494 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNFRWeCRtsAio5kyDP:-NqNM7EHDRQaWaD0RqC1:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/execution/syscalls/hint_processor.rs#L494)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Ditto for the other one.
If you do it one more time then usse a utility function
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 494 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNMAduBqv7Bu0ZTBij:-NqNMui9AAp0RXilFCq3:b-8uxl8e) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/execution/syscalls/hint_processor.rs#L494)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

For later (non-blocking): this can become a function of BlockNumber: `round_for_validate()`
</blockquote></details>

Just to be sure - a method we add locally for the outer starknet_api crate right? Where should such thing be defined?
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 497 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNK2vO4kGnv-rh-8Qo:-NqNLnqtDIFPiJLerilE:bhbyb9z) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/execution/syscalls/hint_processor.rs#L497)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

.
</blockquote></details>

The `block_number` and `block_timestamp` are needed in the else clause.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 499 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNLYYe8P7V3CzveC1J:-NqNLsJS4FudnMl0YECe:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/execution/syscalls/hint_processor.rs#L499)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Use StarkFelt::from
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-11 13:41 UTC, liorgold2 reviewed
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 1 of 8 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-02-11 13:46 UTC, liorgold2 reviewed
> Reviewed 2 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 3 of 8 files reviewed, 8 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 494 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNMAduBqv7Bu0ZTBij:-NqNPSUsBYXusRSajRrB:bkfvr9c) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/execution/syscalls/hint_processor.rs#L494)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Just to be sure - a method we add locally for the outer starknet_api crate right? Where should such thing be defined?
</blockquote></details>

I see, `BlockNumber` is defined in SN api. So in this case either just a function that gets and returns `BlockNumber` or trait+impl (probably the former). In any case, this shouldn't reach SN API.


<!-- Sent from Reviewable.io -->

2024-02-11 13:49 UTC, noaov1 reviewed
> Reviewed 1 of 3 files at r1, 3 of 4 files at r6, 2 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 6 of 8 files reviewed, 11 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, @liorgold2, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/deprecated_syscalls/mod.rs` line 24 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNJiAe9JxGZRV4mgHJ:-NqNJiAf4xMcrKW_cy7J:b-savntt) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/execution/deprecated_syscalls/mod.rs#L24)):*
> ```XML
> use super::syscalls::hint_processor::{
>     VALIDATE_BLOCK_NUMBER_ROUNDING, VALIDATE_TIMESTAMP_ROUNDING,
> };
> ```

Please avoid using `super` (non-blocking)



_Code quote:_
```XML
use super::common_hints::ExecutionMode;
use super::syscalls::hint_processor::{
    VALIDATE_BLOCK_NUMBER_ROUNDING, VALIDATE_TIMESTAMP_ROUNDING,
};
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 492 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNPpMi0Hbg8odULwaN:-NqNPpMi0Hbg8odULwaO:bmvq1v8) ([raw file](https://github.com/starkware-libs/blockifier/blob/e061dc5a43987c53389d21bf428967fc2d227be9/crates/blockifier/src/execution/syscalls/hint_processor.rs#L492)):*
> ```XML
>         let block_number = StarkFelt::from(block_info.block_number.0);
>         let block_data: Vec<StarkFelt> = if self.is_validate_mode() {
>             let block_number_u64: u64 = block_number.try_into()?;
> ```

Why not use `block_info.block_number.0` and wrapping with `StarkFelt` only in the else clause? 



_Code quote:_
```XML
let block_number_u64: u64 = block_number.try_into()?;
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 496 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNPyJvA6pBviBFjmV7:-NqNPyJvA6pBviBFjmV8:bdkb5p0) ([raw file](https://github.com/starkware-libs/blockifier/blob/e061dc5a43987c53389d21bf428967fc2d227be9/crates/blockifier/src/execution/syscalls/hint_processor.rs#L496)):*
> ```XML
>             let rounded_block_number = (block_number_u64 / VALIDATE_BLOCK_NUMBER_ROUNDING)
>                 * VALIDATE_BLOCK_NUMBER_ROUNDING;
>             let block_timestamp_u64: u64 = block_timestamp.try_into()?;
> ```

Why not use `block_info.block_timestamp.0`?



_Code quote:_
```XML
let block_timestamp_u64: u64 = block_timestamp.try_into()?;
```


<!-- Sent from Reviewable.io -->

2024-02-11 13:51 UTC, liorgold2 reviewed
> Reviewed 2 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 7 of 8 files reviewed, 11 unresolved discussions (waiting on @elintul, @giladchase, @TzahiTaub, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-02-11 13:52 UTC, liorgold2 reviewed
> Reviewed 2 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 7 of 8 files reviewed, 11 unresolved discussions (waiting on @elintul, @giladchase, @TzahiTaub, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-02-11 13:53 UTC, liorgold2 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 7 of 8 files reviewed, 11 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, @TzahiTaub, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 78 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNH80CEuTisuKM_8gl:-NqNR9_cC_yZEv9sRCWj:b-ice1gf) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/test_utils/struct_impls.rs#L78)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The confusing thing is this: there are two (sets of) related numbers.

The block number (and block timestamp) and the returned block number (timestamp) by the syscall in validate mode.
The block number should not be changed. We are only affecting the returned value.
</blockquote></details>

(The block number itself is independent of validate mode. Only the block number that's returned by the syscall (which is not the real block number) depends on validate mode.)


<!-- Sent from Reviewable.io -->

2024-02-11 14:01 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 7 of 8 files reviewed, 8 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 492 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNPpMi0Hbg8odULwaN:-NqNS5oAD2SaIAq0q9G7:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/e061dc5a43987c53389d21bf428967fc2d227be9/crates/blockifier/src/execution/syscalls/hint_processor.rs#L492)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why not use `block_info.block_number.0` and wrapping with `StarkFelt` only in the else clause?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-02-11 14:08 UTC, noaov1 reviewed
> Reviewed 2 of 4 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 7 of 8 files reviewed, 8 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, @TzahiTaub, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-02-11 14:10 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 7 of 8 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, and @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-02-11 14:12 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @elintul, @liorgold2, and @TzahiTaub)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 111 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNI9GgCX7ixINId0md:-NqNVldFBInqPvlXLeoq:b-mmscjb) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/test_utils/struct_impls.rs#L111)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I don't think this should be there. @giladchase ?
</blockquote></details>

Right.
 I'm with tzahi now talking about this.


<!-- Sent from Reviewable.io -->

2024-02-11 14:25 UTC, TzahiTaub reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @elintul, and @liorgold2)

___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 78 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNH80CEuTisuKM_8gl:-NqNYcSq2XA4CoJFx2HI:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/test_utils/struct_impls.rs#L78)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

(The block number itself is independent of validate mode. Only the block number that's returned by the syscall (which is not the real block number) depends on validate mode.)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils/struct_impls.rs` line 111 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNI9GgCX7ixINId0md:-NqNYbwzAwDOXAqj78jp:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c46fa6cdcba5e2b824a1e3b3d89278febc95614/crates/blockifier/src/test_utils/struct_impls.rs#L111)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Right.
 I'm with tzahi now talking about this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-11 14:28 UTC, TzahiTaub reviewed
> Dismissed @liorgold2 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @elintul)



<!-- Sent from Reviewable.io -->

2024-02-11 14:30 UTC, TzahiTaub reviewed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @elintul)



<!-- Sent from Reviewable.io -->

2024-02-11 14:32 UTC, TzahiTaub reviewed
> Dismissed @ArniStarkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @elintul, @liorgold2, and @noaov1)



<!-- Sent from Reviewable.io -->

2024-02-11 14:32 UTC, giladchase approved these changes

2024-02-11 14:33 UTC, TzahiTaub reviewed
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-02-11 14:33 UTC, TzahiTaub reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-02-11 14:37 UTC, elintul approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-02-11 14:38 UTC, TzahiTaub reviewed
> Reviewed 2 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-02-11 14:40 UTC, noaov1 approved these changes
> Reviewed 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 294 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1467#-NqNamOMBRZZGDnMBd3A:-NqNamOMBRZZGDnMBd3B:buaoh7k) ([raw file](https://github.com/starkware-libs/blockifier/blob/634bdd54b38b01c990e13fa5404d956be27972a7/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L294)):*
> ```XML
>             // Rounded timestamp.
>             stark_felt!(CURRENT_BLOCK_TIMESTAMP_FOR_VALIDATE),
>             StarkFelt::ZERO,
> ```

You can use the sequencer address :) It is set to 0 (or even delete this argument and use the constants directly ) (non- blocking)



_Code quote:_
```XML
            StarkFelt::ZERO,
```


<!-- Sent from Reviewable.io -->

2024-02-11 14:40 UTC, ArniStarkware approved these changes
> Reviewed 3 of 4 files at r6, 1 of 4 files at r7, 2 of 2 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-02-11 14:42 UTC, TzahiTaub reviewed
> Dismissed @liorgold2 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-02-11 14:43 UTC, TzahiTaub reviewed
> Dismissed @Yoni-Starkware from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-02-11 14:44 UTC, ArniStarkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1467)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)



<!-- Sent from Reviewable.io -->

2024-02-11 14:44 UTC, merged