refactor: replaced default_invoke_tx_args with macro that enforces to explicitly define max_fee
starkware-libs/blockifier pull request #1510
Opened 2024-02-14 11:49 UTC by nimrod-starkware

refactor: replaced default_invoke_tx_args with macro that enforces to explicitly define max_fee

2024-02-14 11:56 UTC, dorimedini-starkware requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1510)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @nimrod-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 377 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1510#-NqbTL2RCyxpQUY1Ixmu:-NqbTL2RCyxpQUY1Ixmv:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a54550bc12598f87325f8cd2d32f7cb1cb046d7/crates/blockifier/src/test_utils.rs#L377)):*
> ```XML
> }
> 
> pub fn create_trivial_calldata(test_contract_address: ContractAddress) -> Calldata {
> ```





_Suggestion:_
```XML
/// Calldata for a trivial entry point in the test contract.
pub fn create_trivial_calldata(test_contract_address: ContractAddress) -> Calldata {
```


<!-- Sent from Reviewable.io -->

2024-02-14 12:37 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1510#-:-NqbbqS8CecUbA0USTH2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)



<!-- Sent from Reviewable.io -->

2024-02-15 06:59 UTC, barak-b-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1510#-:-NqfZ3pCC6EtBVojDsWC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-02-15 08:26 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1510)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-02-15 10:44 UTC, merged