feat: add versioned_constants_13_0.json
starkware-libs/blockifier pull request #1520
Opened 2024-02-15 14:15 UTC by giladchase

Changes between this and the current versioned_constants:
- no `event_size_limit`
- invoke_tx_max_n_steps is 3_000_000 instead of 4_000_000
- no `l2_resource_gas_costs`
- multiple value changes in os_resources
- `vm_resource_fee_cost` is X2 for all values.

No other changes (in particular, os constants is indeed _unchanged_)

2024-02-15 14:32 UTC, elintul requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1520#-NqhAkab70DSKwDfe1UX):*
WDYM?



_Code quote:_
```
- `vm_resource_fee_cost` is X2 for all values.
```
___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1520#-NqhAW7c1J3jn0ligPcR):*
What would happen if 0.13.1 Blockifier runs with 0.13.0 file? Will missing entries cause an error? If so, we should add them with sentinel values.


<!-- Sent from Reviewable.io -->

2024-02-15 15:02 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul, @noaov1, and @Yoni-Starkware)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1520#-NqhAkab70DSKwDfe1UX):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

n_steps was halved in 13.1, from 0.005 into 0.0025.
In turn, this made all other costs half as big, since they are derived from it.


<!-- Sent from Reviewable.io -->

2024-02-15 15:19 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul, @noaov1, and @Yoni-Starkware)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1520#-NqhAW7c1J3jn0ligPcR):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What would happen if 0.13.1 Blockifier runs with 0.13.0 file? Will missing entries cause an error? If so, we should add them with sentinel values.
</blockquote></details>

hmm, moved offline.


<!-- Sent from Reviewable.io -->

2024-02-15 15:21 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1520#-NqhAkab70DSKwDfe1UX):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

n_steps was halved in 13.1, from 0.005 into 0.0025.
In turn, this made all other costs half as big, since they are derived from it.
</blockquote></details>

Oh, I thought it repeats two times. :woman_facepalming: 


<!-- Sent from Reviewable.io -->

2024-02-15 15:22 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul, @noaov1, and @Yoni-Starkware)

___
*[`-- commits` line 9 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1520#-NqhAkab70DSKwDfe1UX):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Oh, I thought it repeats two times. :woman_facepalming:
</blockquote></details>

Yr right, i wrote it wrong :see_no_evil: 


<!-- Sent from Reviewable.io -->

2024-02-15 15:43 UTC, elintul approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @Yoni-Starkware)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1520#-NqhR07YDoTvoh8EDgb5):*
Another change: two constants of block number and timestamp rounding.


<!-- Sent from Reviewable.io -->

2024-02-15 15:50 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @noaov1, and @Yoni-Starkware)

___
*[`-- commits` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1520#-NqhR07YDoTvoh8EDgb5):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Another change: two constants of block number and timestamp rounding.
</blockquote></details>

ohh right.
Thanks!
___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 379 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1520#-NqhQU4gEAIr17Fl6SvO:-NqhSRM65aKc85_XDUFG:b-18z4r1) ([raw file](https://github.com/starkware-libs/blockifier/blob/e76d1e9858defc32d1973b41f3d63d74406d6436/crates/blockifier/resources/versioned_constants_13_0.json#L379)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Need to add the `calldata_factor` with zeroed values.
</blockquote></details>

Did those exist in 13_0?


<!-- Sent from Reviewable.io -->

2024-02-15 15:52 UTC, elintul approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 379 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1520#-NqhQU4gEAIr17Fl6SvO:-NqhSjZH0SROkBKgnog8:bf4onpe) ([raw file](https://github.com/starkware-libs/blockifier/blob/e76d1e9858defc32d1973b41f3d63d74406d6436/crates/blockifier/resources/versioned_constants_13_0.json#L379)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Did those exist in 13_0?
</blockquote></details>

Nope.
Also, I believe there was an indentation added? TAL [here](https://reviewable.io/reviews/starkware-libs/blockifier/1362).


<!-- Sent from Reviewable.io -->

2024-02-15 16:19 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 379 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1520#-NqhQU4gEAIr17Fl6SvO:-NqhYu4W5IThD7msnZaS:b-u4ku4u) ([raw file](https://github.com/starkware-libs/blockifier/blob/e76d1e9858defc32d1973b41f3d63d74406d6436/crates/blockifier/resources/versioned_constants_13_0.json#L379)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Nope.
Also, I believe there was an indentation added? TAL [here](https://reviewable.io/reviews/starkware-libs/blockifier/1362).
</blockquote></details>

So i'm not adding them, yes?

Regarding the indentation, i think that was added along with calldata_factor, when the current values were grouped under `constant`.


<!-- Sent from Reviewable.io -->

2024-02-15 16:33 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 379 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1520#-NqhQU4gEAIr17Fl6SvO:-NqhbBkK-m2cUap9vVh9:b-o180hj) ([raw file](https://github.com/starkware-libs/blockifier/blob/e76d1e9858defc32d1973b41f3d63d74406d6436/crates/blockifier/resources/versioned_constants_13_0.json#L379)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

So i'm not adding them, yes?

Regarding the indentation, i think that was added along with calldata_factor, when the current values were grouped under `constant`.
</blockquote></details>

I think we _do_ need them.
And didn't understand the second sentence. :grimacing: 


<!-- Sent from Reviewable.io -->

2024-02-15 17:25 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 379 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1520#-NqhQU4gEAIr17Fl6SvO:-NqhmnxHBr3EX9Xu9gQe:brxrr4w) ([raw file](https://github.com/starkware-libs/blockifier/blob/e76d1e9858defc32d1973b41f3d63d74406d6436/crates/blockifier/resources/versioned_constants_13_0.json#L379)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we _do_ need them.
And didn't understand the second sentence. :grimacing:
</blockquote></details>

I'll have add more sentinel values then inside the parsing logic.
I can't fake values inside 13_0, they didn't exist when it was launched.


<!-- Sent from Reviewable.io -->

2024-02-18 06:17 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 379 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1520#-NqhQU4gEAIr17Fl6SvO:-NqhqNdM6sMBPZjCVTfY:b-4hvi0m) ([raw file](https://github.com/starkware-libs/blockifier/blob/e76d1e9858defc32d1973b41f3d63d74406d6436/crates/blockifier/resources/versioned_constants_13_0.json#L379)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I'll have add more sentinel values then inside the parsing logic.
I can't fake values inside 13_0, they didn't exist when it was launched.
</blockquote></details>

Got it.


<!-- Sent from Reviewable.io -->

2024-02-18 08:17 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 379 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1520#-NqhQU4gEAIr17Fl6SvO:-NqvHZeYDpDbi_1tD67w:bugpmsi) ([raw file](https://github.com/starkware-libs/blockifier/blob/e76d1e9858defc32d1973b41f3d63d74406d6436/crates/blockifier/resources/versioned_constants_13_0.json#L379)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Got it.
</blockquote></details>

Adding parser support here: https://reviewable.io/reviews/starkware-libs/blockifier/1529


<!-- Sent from Reviewable.io -->

2024-02-18 08:48 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-02-18 09:38 UTC, Yoni-Starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 379 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1520#-NqhQU4gEAIr17Fl6SvO:-NqvZq8J5L2oVyGY2sBH:bkof1tb) ([raw file](https://github.com/starkware-libs/blockifier/blob/e76d1e9858defc32d1973b41f3d63d74406d6436/crates/blockifier/resources/versioned_constants_13_0.json#L379)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Adding parser support here: https://reviewable.io/reviews/starkware-libs/blockifier/1529
</blockquote></details>

Why can't you? This file (0.13.0) is meant for blockifier v0.13.1, right?


<!-- Sent from Reviewable.io -->

2024-02-18 09:46 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-02-18 10:52 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 379 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1520#-NqhQU4gEAIr17Fl6SvO:-Nqvk2pS0HJ7AcijBSHY:bgn9mhu) ([raw file](https://github.com/starkware-libs/blockifier/blob/e76d1e9858defc32d1973b41f3d63d74406d6436/crates/blockifier/resources/versioned_constants_13_0.json#L379)):*
> is meant for blockifier v0.13.1, right?
IIUC it's the opposite; it's for users of 13_0 who don't want to upgrade to 13_1 blockifier, but only take in the prices.

Therefore, this file is used for reference by users.
If we change it here, it might be confusing for 13_0 users (the blockifier they're using will have one version, and blockifier 13_1 will have a different one).
If they use the "wrong" version of 13_0, at best, it won't compile; at worst, they'll get panics, or incorrect values for 13_0 constants.

Additionally, if we start retroactively changing historic files, it might have scaling issues.
Say we add a breaking change in constants in version 0.14.0, that means we have to go over every json file we've published (they should all be retained inside `resources` dir) and change them to fit the new format.


<!-- Sent from Reviewable.io -->

2024-02-18 10:53 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-02-18 10:53 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520#-:-NqvqTUf1WebXEI9dFcZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-02-18 11:26 UTC, Yoni-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-02-18 11:33 UTC, noaov1 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-02-18 11:40 UTC, noaov1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1520)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-02-18 11:40 UTC, merged