chore: move validate consts into os constants
starkware-libs/blockifier pull request #1523
Opened 2024-02-15 15:07 UTC by giladchase

Had to bump serde_json due to some apparent bug with the recent stable rust.

2024-02-15 15:49 UTC, elintul submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Thanks!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1523#-:-NqhSO3W6tgqamh8LBvp:b9benhj)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`Cargo.lock` line 3035 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1523#-NqhOYBqAmPogpuSt_Qd:-NqhOYBqAmPogpuSt_Qe:b-qicabr) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a4ce9fb11703500d6450f689be9a647c31fcc31/Cargo.lock#L3035)):*
> ```TOML
> [[package]]
> name = "serde_json"
> version = "1.0.113"
> ```

How come it changed?



_Code quote:_
```TOML
version = "1.0.113"
```
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1523#-NqhSEJFCHtnoAYLjy0n:-NqhSEJGBteyWB0ky2dt:b-9sxwfv) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a4ce9fb11703500d6450f689be9a647c31fcc31/crates/blockifier/src/versioned_constants_test.rs#L59)):*
> ```XML
>     json_data_raw.insert("validate_timestamp_rounding".to_string(), 0.into());
> 
>     let amended_json_data = &serde_json::to_string(&json_data_raw).unwrap();
> ```

Can we use the same variable name?



_Code quote:_
```XML
 amended_json_data
```


<!-- Sent from Reviewable.io -->

2024-02-15 15:58 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1523)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @Yael-Starkware)

___
*[`Cargo.lock` line 3035 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1523#-NqhOYBqAmPogpuSt_Qd:-NqhU6MGDRdRemKdCA7V:b-mfbtrn) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a4ce9fb11703500d6450f689be9a647c31fcc31/Cargo.lock#L3035)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How come it changed?
</blockquote></details>

They seemed to clash with the recent stable rust for some reason so i had to bump them.
Python didn't mind.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1523#-NqhSEJFCHtnoAYLjy0n:-NqhUBxpCYH_Zpx-ZXUk:bb7oryy) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a4ce9fb11703500d6450f689be9a647c31fcc31/crates/blockifier/src/versioned_constants_test.rs#L59)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we use the same variable name?
</blockquote></details>

sure


<!-- Sent from Reviewable.io -->

2024-02-15 16:00 UTC, elintul submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1523)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-02-15 16:31 UTC, elintul approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1523)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase and @Yael-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 319 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1523#-NqhaqxeC2Q36hViH_Vu:-NqhaqxeC2Q36hViH_Vv:bhy028w) ([raw file](https://github.com/starkware-libs/blockifier/blob/b200cd51bed36ee9c0e8fce6c06ae2ca6dcab049/crates/blockifier/src/versioned_constants.rs#L319)):*
> ```XML
> pub struct OSConstants {
>     #[serde(default)]
>     #[serde(flatten)]
> ```

What do they mean?



_Code quote:_
```XML
    #[serde(default)]
    #[serde(flatten)]
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 446 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1523#-NqhakCI1HWdvjxYYPqA:-NqhakCI1HWdvjxYYPqB:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b200cd51bed36ee9c0e8fce6c06ae2ca6dcab049/crates/blockifier/src/versioned_constants.rs#L446)):*
> ```XML
> 
>         let os_constants =
>             OSConstants { gas_costs, validate_rounding_consts: validate_rounding_costs };
> ```





_Suggestion:_
```XML
validate_rounding_consts
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 499 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1523#-Nqha_2IDJOriDeWS8nb:-Nqha_2J8_oZY6SWgJEs:b-suv37h) ([raw file](https://github.com/starkware-libs/blockifier/blob/b200cd51bed36ee9c0e8fce6c06ae2ca6dcab049/crates/blockifier/src/versioned_constants.rs#L499)):*
> ```XML
> }
> 
> #[derive(Debug, Clone, Serialize, Deserialize)]
> ```

Alphabetize?



_Code quote:_
```XML
Debug, Clone, Serialize, Deserialize
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 500 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1523#-NqhacGCDEVi8sX0X3eG:-NqhacGCDEVi8sX0X3eH:b3gjhm0) ([raw file](https://github.com/starkware-libs/blockifier/blob/b200cd51bed36ee9c0e8fce6c06ae2ca6dcab049/crates/blockifier/src/versioned_constants.rs#L500)):*
> ```XML
> 
> #[derive(Debug, Clone, Serialize, Deserialize)]
> struct ValidateRoundingConsts {
> ```

Why is this struct needed?



_Code quote:_
```XML
ValidateRoundingConsts
```


<!-- Sent from Reviewable.io -->

2024-02-15 17:22 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1523)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @elintul and @Yael-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 319 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1523#-NqhaqxeC2Q36hViH_Vu:-Nqhm7dl1Sdtzyn3Aw3W:b-7j964s) ([raw file](https://github.com/starkware-libs/blockifier/blob/b200cd51bed36ee9c0e8fce6c06ae2ca6dcab049/crates/blockifier/src/versioned_constants.rs#L319)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What do they mean?
</blockquote></details>

stale
___
*[`crates/blockifier/src/versioned_constants.rs` line 446 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1523#-NqhakCI1HWdvjxYYPqA:-Nqhm8jl7klAQ3xB5bux:b-7j964s) ([raw file](https://github.com/starkware-libs/blockifier/blob/b200cd51bed36ee9c0e8fce6c06ae2ca6dcab049/crates/blockifier/src/versioned_constants.rs#L446)):*
> ```XML
> 
>         let os_constants =
>             OSConstants { gas_costs, validate_rounding_consts: validate_rounding_costs };
> ```

stale
___
*[`crates/blockifier/src/versioned_constants.rs` line 500 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1523#-NqhacGCDEVi8sX0X3eG:-NqhmJZW5hs9b2jivUFy:b-giusz1) ([raw file](https://github.com/starkware-libs/blockifier/blob/b200cd51bed36ee9c0e8fce6c06ae2ca6dcab049/crates/blockifier/src/versioned_constants.rs#L500)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is this struct needed?
</blockquote></details>

In order to define a dedicated function that constructs the values with the custom default values (1).


<!-- Sent from Reviewable.io -->

2024-02-15 17:33 UTC, elintul requested changes
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1523)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-02-15 17:41 UTC, elintul reviewed
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1523)* status: all files reviewed, 1 unresolved discussion (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-02-18 08:47 UTC, elintul approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1523)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-02-18 09:10 UTC, merged