feat(execution): implement a versioned validator for implementing con…
starkware-libs/blockifier pull request #1578
Opened 2024-02-22 14:43 UTC by MohammadNassar1

…currency

2024-03-11 08:19 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @elintul, @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/validator.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsgDSrW57Wj69-QEQr0:-NsgDSrW57Wj69-QEQr1:b-37wvcv) ([raw file](https://github.com/starkware-libs/blockifier/blob/501987ddf7ecba5c617992f3506ce0cb18b45006/crates/blockifier/src/concurrency/validator.rs#L8)):*
> ```XML
> 
> use super::versioned_state::VersionedState;
> use super::versioned_storage::Version;
> ```

Use absolute imports plz



_Code quote:_
```XML
use super::versioned_state::VersionedState;
use super::versioned_storage::Version;
```
___
*[`crates/blockifier/src/concurrency/validator.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsgEHNVDijIPR9Gj-E2:-NsgEHNVDijIPR9Gj-E3:b-7i0upg) ([raw file](https://github.com/starkware-libs/blockifier/blob/501987ddf7ecba5c617992f3506ce0cb18b45006/crates/blockifier/src/concurrency/validator.rs#L16)):*
> ```XML
> 
> pub struct StorageEntry {
>     arg: Box<dyn Any>,
> ```

Can this be an Enum?
Perhaps something like
```rust
enum StateArgument { // or better name?
   GetStorageAt {contract_address: ContractAddress, storage_key: StorageKey"},
   GetNonceAt {contract_address: ContractAddress},
  ...
}
```
AFAIK `dyn Any` should be reserved for cases where all you know is that the value is "some type", or there are a great many possible types, or if it significantly implies the logic.

Also heavily relying on `dyn` and untyped code probably loses out on many compile-time performance optimizations (due to dynamic dispatch and `Any` not giving the compiler a lot to work with), but I might be underestimating the compiler :)



_Code quote:_
```XML
    arg: Box<dyn Any>,
```
___
*[`crates/blockifier/src/concurrency/validator.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsgEjeID_GW35OocOFI:-NsgEjeID_GW35OocOFJ:bx1dpky) ([raw file](https://github.com/starkware-libs/blockifier/blob/501987ddf7ecba5c617992f3506ce0cb18b45006/crates/blockifier/src/concurrency/validator.rs#L18)):*
> ```XML
>     arg: Box<dyn Any>,
>     storage_type: StorageType,
>     value: Box<dyn Any>,
> ```

Same as comment on `arg` above; enum on result types?



_Code quote:_
```XML
   value: Box<dyn Any>
```
___
*[`crates/blockifier/src/concurrency/validator.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsgZ_N-33Nbkr6kZBuB:-NsgZ_N-33Nbkr6kZBuC:bnwqf3) ([raw file](https://github.com/starkware-libs/blockifier/blob/501987ddf7ecba5c617992f3506ce0cb18b45006/crates/blockifier/src/concurrency/validator.rs#L28)):*
> ```XML
> }
> 
> pub fn validate_read_set<S: StateReader>(
> ```

Should this be `pub`?



_Code quote:_
```XML
pub fn validate_read_set<S: StateReader>(
```
___
*[`crates/blockifier/src/concurrency/validator.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsgHCvF72BJo88e4IqR:-NsgHCvF72BJo88e4IqS:b-ibl9bq) ([raw file](https://github.com/starkware-libs/blockifier/blob/501987ddf7ecba5c617992f3506ce0cb18b45006/crates/blockifier/src/concurrency/validator.rs#L39)):*
> ```XML
>                 let arg = read.arg.downcast_ref::<(ContractAddress, StorageKey)>().expect(
>                     "Failed to downcast read value to a tuple of (ContractAddress, StorageKey)",
>                 );
> ```

If this function is part of the API, then it should return an error.
Also, note the coupling between StorageEntry's 3 fields: if storage_type is Storage, then necessarily the arg must be this, and the `value` field must be something else.
See if there's a way of eliminating this coupling.



_Code quote:_
```XML
                let arg = read.arg.downcast_ref::<(ContractAddress, StorageKey)>().expect(
                    "Failed to downcast read value to a tuple of (ContractAddress, StorageKey)",
                );
```
___
*[`crates/blockifier/src/concurrency/validator.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-Nsg_Sz20v7BT4_4qJlN:-Nsg_Sz20v7BT4_4qJlO:b-vkk5ht) ([raw file](https://github.com/starkware-libs/blockifier/blob/501987ddf7ecba5c617992f3506ce0cb18b45006/crates/blockifier/src/concurrency/validator.rs#L41)):*
> ```XML
>                 );
>                 let value = versioned_state.get_storage_at(version, arg.0, arg.1);
>                 assert!(value.is_ok());
> ```

Can't this hit the usually db-type errors? for example, if this ends up having to hit the DB, then network issues are possible.



_Code quote:_
```XML
                let value = versioned_state.get_storage_at(version, arg.0, arg.1);
                assert!(value.is_ok());
```
___
*[`crates/blockifier/src/concurrency/validator.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-Nsg_xh-5102xiseov4n:-Nsg_xh-5102xiseov4o:b-iwp29g) ([raw file](https://github.com/starkware-libs/blockifier/blob/501987ddf7ecba5c617992f3506ce0cb18b45006/crates/blockifier/src/concurrency/validator.rs#L78)):*
> ```XML
>                 if read_value != &value.unwrap() {
>                     return false;
>                 }
> ```

When can this happen?



_Code quote:_
```XML
                if read_value != &value.unwrap() {
                    return false;
                }
```


<!-- Sent from Reviewable.io -->

2024-03-12 09:54 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/validator.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsgDSrW57Wj69-QEQr0:-NslyOa80GCiObsDZam4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/501987ddf7ecba5c617992f3506ce0cb18b45006/crates/blockifier/src/concurrency/validator.rs#L8)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Use absolute imports plz
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/validator.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsgEHNVDijIPR9Gj-E2:-NslyTh42stK8928nihg:b96m1ru) ([raw file](https://github.com/starkware-libs/blockifier/blob/501987ddf7ecba5c617992f3506ce0cb18b45006/crates/blockifier/src/concurrency/validator.rs#L16)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can this be an Enum?
Perhaps something like
```rust
enum StateArgument { // or better name?
   GetStorageAt {contract_address: ContractAddress, storage_key: StorageKey"},
   GetNonceAt {contract_address: ContractAddress},
  ...
}
```
AFAIK `dyn Any` should be reserved for cases where all you know is that the value is "some type", or there are a great many possible types, or if it significantly implies the logic.

Also heavily relying on `dyn` and untyped code probably loses out on many compile-time performance optimizations (due to dynamic dispatch and `Any` not giving the compiler a lot to work with), but I might be underestimating the compiler :)
</blockquote></details>

Good idea!
I've replaced it with an enum.
___
*[`crates/blockifier/src/concurrency/validator.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsgEjeID_GW35OocOFI:-Nslyc1SAOIt49oJmH9A:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/501987ddf7ecba5c617992f3506ce0cb18b45006/crates/blockifier/src/concurrency/validator.rs#L18)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Same as comment on `arg` above; enum on result types?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/validator.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsgZ_N-33Nbkr6kZBuB:-NslyhOZDffE7vpB7APx:b-h7x8l3) ([raw file](https://github.com/starkware-libs/blockifier/blob/501987ddf7ecba5c617992f3506ce0cb18b45006/crates/blockifier/src/concurrency/validator.rs#L28)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Should this be `pub`?
</blockquote></details>

Maybe I'll consider using pub(crate).
A worker/scheduler should use it.
___
*[`crates/blockifier/src/concurrency/validator.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-Nsg_xh-5102xiseov4n:-Nsm-Grc9oxx-Z8cQGtK:be8gusr) ([raw file](https://github.com/starkware-libs/blockifier/blob/501987ddf7ecba5c617992f3506ce0cb18b45006/crates/blockifier/src/concurrency/validator.rs#L78)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

When can this happen?
</blockquote></details>

When a read occurs before a write of a lower version.


<!-- Sent from Reviewable.io -->

2024-03-12 09:56 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/validator.rs` line 39 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsgHCvF72BJo88e4IqR:-Nsm4VbW5s7Vy9s-3ZPr:b-yhucpm) ([raw file](https://github.com/starkware-libs/blockifier/blob/501987ddf7ecba5c617992f3506ce0cb18b45006/crates/blockifier/src/concurrency/validator.rs#L39)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

If this function is part of the API, then it should return an error.
Also, note the coupling between StorageEntry's 3 fields: if storage_type is Storage, then necessarily the arg must be this, and the `value` field must be something else.
See if there's a way of eliminating this coupling.
</blockquote></details>

I used enum instead, so I think this comment is not relevant.


<!-- Sent from Reviewable.io -->

2024-03-12 10:02 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/validator.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-Nsg_Sz20v7BT4_4qJlN:-Nsm5Y1D-rQODSqGp0p5:baepk9p) ([raw file](https://github.com/starkware-libs/blockifier/blob/501987ddf7ecba5c617992f3506ce0cb18b45006/crates/blockifier/src/concurrency/validator.rs#L41)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Can't this hit the usually db-type errors? for example, if this ends up having to hit the DB, then network issues are possible.
</blockquote></details>

To make sure that I got your suggestion.
Are you suggesting that the function should return `StateResult`?`


<!-- Sent from Reviewable.io -->

2024-03-13 12:23 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 0 of 6 files reviewed, 8 unresolved discussions (waiting on @elintul, @giladchase, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 13 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsrkXzO1zvCHHqhBALJ:-NsrkXzP-UIV3EK0UbFT:bnghrdn) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ea021dcf72695e09196f917b13a97160f4eae49/crates/blockifier/src/concurrency/concurrency_utils.rs#L13)):*
> ```XML
> pub mod test;
> 
> pub fn validate_read_set<S: StateReader>(
> ```

Make this a method of versionedState (and versionedStorage), to decouple the lock from the implementation



_Code quote:_
```XML
pub fn validate_read_set<S: StateReader>(
```


<!-- Sent from Reviewable.io -->

2024-03-13 12:25 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 0 of 6 files reviewed, 10 unresolved discussions (waiting on @elintul, @giladchase, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 15 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsrlQa051B564GJPn2e:-NsrlQa051B564GJPn2f:b7law4p) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ea021dcf72695e09196f917b13a97160f4eae49/crates/blockifier/src/concurrency/concurrency_utils.rs#L15)):*
> ```XML
> pub fn validate_read_set<S: StateReader>(
>     version: Version,
>     transactional_state: &mut CachedState<VersionedClientState<CachedState<S>>>,
> ```

Can you pass here just the cache?



_Code quote:_
```XML
transactional_state: &mut CachedState<VersionedClientState<CachedState<S>>>,
```
___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-Nsrl8Yn-pUdcubaazrD:-Nsrl8Yn-pUdcubaazrE:b-ftm8lr) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ea021dcf72695e09196f917b13a97160f4eae49/crates/blockifier/src/concurrency/concurrency_utils.rs#L22)):*
> ```XML
> 
>     for (key, expected_value) in &cache.storage_initial_values {
>         let value = versioned_state.lock().unwrap().get_storage_at(version, key.0, key.1);
> ```

Is this inclusive? it might be `version - 1` 



_Code quote:_
```XML
version
```


<!-- Sent from Reviewable.io -->

2024-03-13 14:22 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 0 of 6 files reviewed, 11 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 13 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsrkXzO1zvCHHqhBALJ:-NssB45H14Ow9-icATAx:b66hyzc) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ea021dcf72695e09196f917b13a97160f4eae49/crates/blockifier/src/concurrency/concurrency_utils.rs#L13)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Make this a method of versionedState (and versionedStorage), to decouple the lock from the implementation
</blockquote></details>

Can you elaborate?
The client should run the validation method, right?
___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 15 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsrlQa051B564GJPn2e:-Nss5zzk9ufnjKxJmqPG:be67u56) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ea021dcf72695e09196f917b13a97160f4eae49/crates/blockifier/src/concurrency/concurrency_utils.rs#L15)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you pass here just the cache?
</blockquote></details>

To do so, I need to use another parameter, as parameter S is shared between the two arguments.
___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-Nsrl8Yn-pUdcubaazrD:-Nss9ugtC7dq-67aENk7:b-9hpu1w) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ea021dcf72695e09196f917b13a97160f4eae49/crates/blockifier/src/concurrency/concurrency_utils.rs#L22)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Is this inclusive? it might be `version - 1`
</blockquote></details>

Should be identical, right?
In case of a write operation within the same transaction, the value would be read from the cache and not updated in initial_values.


<!-- Sent from Reviewable.io -->

2024-03-13 15:44 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 0 of 6 files reviewed, 11 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 57 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsrlZy84BSp5hQoqFnP:-NssT2dE31ys7ImqF9oU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ea021dcf72695e09196f917b13a97160f4eae49/crates/blockifier/src/concurrency/concurrency_utils.rs#L57)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Same, and rename to `apply_writes`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-14 09:16 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 0 of 6 files reviewed, 11 unresolved discussions (waiting on @elintul, @giladchase, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 13 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsrkXzO1zvCHHqhBALJ:-NswE99CB-bkJ9yY8CFi:br6mn4h) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ea021dcf72695e09196f917b13a97160f4eae49/crates/blockifier/src/concurrency/concurrency_utils.rs#L13)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Can you elaborate?
The client should run the validation method, right?
</blockquote></details>

The worker thread (not the client state) should be able to do:
```
versioned_state.lock().validate_read_set(...)
```
___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 15 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsrlQa051B564GJPn2e:-NswERRrAGph7VvC2oj4:b-jhe99v) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ea021dcf72695e09196f917b13a97160f4eae49/crates/blockifier/src/concurrency/concurrency_utils.rs#L15)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

To do so, I need to use another parameter, as parameter S is shared between the two arguments.
</blockquote></details>

Just the `StateCache`
___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-Nsrl8Yn-pUdcubaazrD:-NswEcbf7OUtRmOI0i2z:b-uhm1f8) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ea021dcf72695e09196f917b13a97160f4eae49/crates/blockifier/src/concurrency/concurrency_utils.rs#L22)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Should be identical, right?
In case of a write operation within the same transaction, the value would be read from the cache and not updated in initial_values.
</blockquote></details>

No. 
Read-set should only include `initial_values`. You don't want to validate an initial value against a self-write that happened later on


<!-- Sent from Reviewable.io -->

2024-03-14 16:41 UTC, noaov1 requested changes
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 2 of 6 files reviewed, 15 unresolved discussions (waiting on @elintul, @giladchase, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 22 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-Nsxp8mX6jzaYZonyK1c:-Nsxp8mX6jzaYZonyK1d:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/51f38bcbd0d56272ee10ce8ed39224d0aba9b51f/crates/blockifier/src/concurrency/concurrency_utils.rs#L22)):*
> ```XML
> 
>     for (key, expected_value) in &cache.storage_initial_values {
>         let value = versioned_state.lock().unwrap().get_storage_at(version, key.0, key.1);
> ```





_Suggestion:_
```XML
    for ((contract_address, storage_key), expected_value) in &cache.storage_initial_values {
        let value = versioned_state.lock().unwrap().get_storage_at(version, contract_address, storage_key);
```
___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 23 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsxnHRy4EL6Ji3SVchC:-NsxnHRy4EL6Ji3SVchD:bpsxrpy) ([raw file](https://github.com/starkware-libs/blockifier/blob/51f38bcbd0d56272ee10ce8ed39224d0aba9b51f/crates/blockifier/src/concurrency/concurrency_utils.rs#L23)):*
> ```XML
>     for (key, expected_value) in &cache.storage_initial_values {
>         let value = versioned_state.lock().unwrap().get_storage_at(version, key.0, key.1);
>         assert!(value.is_ok());
> ```

Why is it must be okay? Why can't we get `StateReadError`?



_Code quote:_
```XML
 assert!(value.is_ok());
```
___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 65 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-Nsxnw_74h0E4HAM5OUM:-Nsxnw_74h0E4HAM5OUN:b-hdptn0) ([raw file](https://github.com/starkware-libs/blockifier/blob/51f38bcbd0d56272ee10ce8ed39224d0aba9b51f/crates/blockifier/src/concurrency/concurrency_utils.rs#L65)):*
> ```XML
> }
> 
> /// Note: This function should be called after `update_initial_values_of_write_only_access`.
> ```

Did you mean to write it above `validate_read_set`? Can you please explain?



_Suggestion:_
```XML
// Note: This function should be called after `update_initial_values_of_write_only_access`.
```


<!-- Sent from Reviewable.io -->

2024-03-17 07:28 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 0 of 8 files reviewed, 14 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 13 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsrkXzO1zvCHHqhBALJ:-NsyRIei2d1W9_0Qy9kZ:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ea021dcf72695e09196f917b13a97160f4eae49/crates/blockifier/src/concurrency/concurrency_utils.rs#L13)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

The worker thread (not the client state) should be able to do:
```
versioned_state.lock().validate_read_set(...)
```
</blockquote></details>

Done
___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 15 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsrlQa051B564GJPn2e:-NsyIYLG2zACDqU9qylv:b-w3gndc) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ea021dcf72695e09196f917b13a97160f4eae49/crates/blockifier/src/concurrency/concurrency_utils.rs#L15)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Just the `StateCache`
</blockquote></details>

But `class_hash_to_class` mapping (which includes the contract class mapping) is not part of the `StateCache`.
Instead, I can pass both of them. WDYT?
___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-Nsrl8Yn-pUdcubaazrD:-NsyRPVf4mI9ib7OMuP2:b-d35xla) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ea021dcf72695e09196f917b13a97160f4eae49/crates/blockifier/src/concurrency/concurrency_utils.rs#L22)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

No. 
Read-set should only include `initial_values`. You don't want to validate an initial value against a self-write that happened later on
</blockquote></details>

Not sure I got it.
The validation process occurs before the `apply_writes` process. Therefore, during validation, the value being read is compared to the corresponding value in the versioned state, and as writes values are not updated in the versioned state yet, it should be identical. 
What am I missing here?
___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 65 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-Nsxnw_74h0E4HAM5OUM:-NsyW_1N5WTFOINIPbqE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/51f38bcbd0d56272ee10ce8ed39224d0aba9b51f/crates/blockifier/src/concurrency/concurrency_utils.rs#L65)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Did you mean to write it above `validate_read_set`? Can you please explain?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-17 07:30 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 0 of 8 files reviewed, 15 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAIvt9C8m79uqbiLnR:-NtAIvt9C8m79uqbiLnS:b-iahnpf) (no related file):*
Please note that I've moved the validate read set method and apply write set method to the `versioned_state_proxy` file.

___


<!-- Sent from Reviewable.io -->

2024-03-17 10:09 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 0 of 8 files reviewed, 20 unresolved discussions (waiting on @elintul, @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 42 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAg_eV6V8Mj_KOncOQ:-NtAg_eV6V8Mj_KOncOR:b-yvej5x) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L42)):*
> ```XML
>     }
> 
>     pub fn validate_read_set(
> ```

Any way to refactor the duplicated logic below?
Maybe some duplication can't be removed, due to the subtle differences, but try to remove as much as you can without making things complicated/unreadable.
For example, I think `version-1` can be extracted into a variable.
Consider using `iter().all(...)` instead of `for` for checking boolean conditions on every iteration, which might help remove the duplicated `if expected ... return false` thingie



_Code quote:_
```XML
  pub fn validate_read_set(
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 46 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAKIYI6omatGIN-iyo:-NtAKIYJ6NWSmIk0Y6OP:ba3dfna) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L46)):*
> ```XML
>         version: Version,
>         transactional_state: &mut CachedState<VersionedStateProxy<CachedState<S>>>,
>         // versioned_state: &mut Arc<Mutex<VersionedState<CachedState<S>>>>,
> ```

Remove?



_Code quote:_
```XML
       // versioned_state: &mut Arc<Mutex<VersionedState<CachedState<S>>>>,
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 48 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtArcPv1jOU3_L_GmjB:-NtArcPv1jOU3_L_GmjC:bpt5ffi) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L48)):*
> ```XML
>         // versioned_state: &mut Arc<Mutex<VersionedState<CachedState<S>>>>,
>     ) -> bool {
>         let cache = transactional_state.cache.borrow();
> ```

Note that this is a RefCell operation, which is not threadsafe (it used `unsafe` behind the scenes). 
This might be OK, because this whole code is guarded behind a Mutex, but keep this in mind...



_Code quote:_
```XML
.borrow();
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAdkrr8fpXxs4rnxbv:-NtAdkrr8fpXxs4rnxbw:b-21fbvz) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L49)):*
> ```XML
>     ) -> bool {
>         let cache = transactional_state.cache.borrow();
>         for ((contract_address, storage_key), expected_value) in &cache.storage_initial_values {
> ```

Then remove the `*`, ditto for the other loops below, less boilerplate.



_Suggestion:_
```XML
        for (&(contract_address, storage_key), &expected_value) in &cache.storage_initial_values {
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 53 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAlNUCDyfnegp-QEuU:-NtAlNUCDyfnegp-QEuV:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L53)):*
> ```XML
>                 Some(value) => Ok(value),
>                 None => self.initial_state.get_storage_at(*contract_address, *storage_key),
>             };
> ```





_Suggestion:_
```XML
            let value = match self.storage.read(version - 1, (*contract_address, *storage_key))
                .ok_or_else(|| self.initial_state.get_storage_at(*contract_address, *storage_key));
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 54 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAhngs2PLjd4nT0Rlr:-NtAhngs2PLjd4nT0Rls:bb6z3q3) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L54)):*
> ```XML
>                 None => self.initial_state.get_storage_at(*contract_address, *storage_key),
>             };
>             if *expected_value != value.unwrap() {
> ```

I think this can be a DB error (if its the result of `initial_state.get_storage_at`).
If that's the case, we need to return the error rather than panic.
Can you use `?` and return a result from this func?



_Code quote:_
```XML
value.unwrap()
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 99 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAnk_F7Ij-eRdWvFdv:-NtAnk_F7Ij-eRdWvFdw:b3kbg1k) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L99)):*
> ```XML
>     }
> 
>     pub fn apply_writes(
> ```

Both here and in `validate_read_set` and `apply_writes` it looks like all fields of the struct are accessed in tandem.
Any way of doing a kind of "vector operation" here? 



_Code quote:_
```XML
    pub fn apply_writes(
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 180 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAqYgvCLIN07lFeRhK:-NtAqYgvCLIN07lFeRhL:bkbvv33) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L180)):*
> ```XML
>         let mut state = self.state();
>         state.compiled_contract_classes.write(self.version, class_hash, contract_class);
>     }
> ```

Are these covered by the `State` trait? if so then impl the trait.



_Code quote:_
```XML
    pub fn set_class_hash_at(&mut self, contract_address: ContractAddress, class_hash: ClassHash) {
        let mut state = self.state();
        state.class_hashes.write(self.version, contract_address, class_hash);
    }

    pub fn set_nonce_at(&mut self, contract_address: ContractAddress, nonce: Nonce) {
        let mut state = self.state();
        state.nonces.write(self.version, contract_address, nonce);
    }

    pub fn set_compiled_class_hash(
        &mut self,
        class_hash: ClassHash,
        compiled_class_hash: CompiledClassHash,
    ) {
        let mut state = self.state();
        state.compiled_class_hashes.write(self.version, class_hash, compiled_class_hash);
    }

    pub fn set_compiled_contract_class(
        &mut self,
        class_hash: ClassHash,
        contract_class: ContractClass,
    ) {
        let mut state = self.state();
        state.compiled_contract_classes.write(self.version, class_hash, contract_class);
    }
```
___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 3 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAH13SDl5UXBmPcavp:-NtAH13SDl5UXBmPcavq:b-4cp508) ([raw file](https://github.com/starkware-libs/blockifier/blob/51f38bcbd0d56272ee10ce8ed39224d0aba9b51f/crates/blockifier/src/concurrency/concurrency_utils.rs#L3)):*
> ```XML
> use std::sync::{Arc, Mutex};
> 
> use super::versioned_client_state::VersionedClientState;
> ```

Absolute imports plz.
Consider adding to settings.json: `"rust-analyzer.imports.prefix": "crate",` to make this automatic.



_Code quote:_
```XML
use super::versioned_client_state::VersionedClientState;
```
___
*[`crates/blockifier/src/concurrency/validator.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsgEHNVDijIPR9Gj-E2:-NtAqxX0-cA5QJVgqjKH:b-khk451) ([raw file](https://gi [...]

2024-03-17 15:01 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 0 of 8 files reviewed, 20 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 42 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAg_eV6V8Mj_KOncOQ:-NtBthti5sF5bhaTYi77:bq81mgo) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L42)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Any way to refactor the duplicated logic below?
Maybe some duplication can't be removed, due to the subtle differences, but try to remove as much as you can without making things complicated/unreadable.
For example, I think `version-1` can be extracted into a variable.
Consider using `iter().all(...)` instead of `for` for checking boolean conditions on every iteration, which might help remove the duplicated `if expected ... return false` thingie
</blockquote></details>

I have removed the duplicated logic that validates the expected value.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 46 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAKIYI6omatGIN-iyo:-NtB8dFoBWvbBPugqZK6:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L46)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 48 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtArcPv1jOU3_L_GmjB:-NtBKnbl1XjVHLok7enx:bgpx7e6) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L48)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Note that this is a RefCell operation, which is not threadsafe (it used `unsafe` behind the scenes). 
This might be OK, because this whole code is guarded behind a Mutex, but keep this in mind...
</blockquote></details>

Exactly. This function is protected by a Mutex.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAdkrr8fpXxs4rnxbv:-NtBLgXE8Xbe6dQmkPhi:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L49)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Then remove the `*`, ditto for the other loops below, less boilerplate.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 53 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAlNUCDyfnegp-QEuU:-NtBu-Hy6qGkWRhCmTQx:b-q556ex) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L53)):*
> ```XML
>                 Some(value) => Ok(value),
>                 None => self.initial_state.get_storage_at(*contract_address, *storage_key),
>             };
> ```

Your suggested code returns `Result<StarkFelt, Result<...>>`
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 54 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAhngs2PLjd4nT0Rlr:-NtBSh3f6ALc5ZLXICaI:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L54)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think this can be a DB error (if its the result of `initial_state.get_storage_at`).
If that's the case, we need to return the error rather than panic.
Can you use `?` and return a result from this func?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 180 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAqYgvCLIN07lFeRhK:-NtBe1SN1uZ40IydYiDg:b-o8bwga) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L180)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Are these covered by the `State` trait? if so then impl the trait.
</blockquote></details>

I've implemented this fix in the [previous PR](https://reviewable.io/reviews/starkware-libs/blockifier/1528) where this code was originally introduced.
___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 3 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAH13SDl5UXBmPcavp:-NtBgx5u2xAR0vw83uD2:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/51f38bcbd0d56272ee10ce8ed39224d0aba9b51f/crates/blockifier/src/concurrency/concurrency_utils.rs#L3)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Absolute imports plz.
Consider adding to settings.json: `"rust-analyzer.imports.prefix": "crate",` to make this automatic.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 23 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsxnHRy4EL6Ji3SVchC:-NtBX2ViC2Nuc9Zd00e4:b9votix) ([raw file](https://github.com/starkware-libs/blockifier/blob/51f38bcbd0d56272ee10ce8ed39224d0aba9b51f/crates/blockifier/src/concurrency/concurrency_utils.rs#L23)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it must be okay? Why can't we get `StateReadError`?
</blockquote></details>

fixed.
Now it returns `StateResult`.
___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 60 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NswX6OV3Co8Zb--OvUd:-NtBWthK-EU8VJcMzdJ6:b-cqik8e) ([raw file](https://github.com/starkware-libs/blockifier/blob/51f38bcbd0d56272ee10ce8ed39224d0aba9b51f/crates/blockifier/src/concurrency/concurrency_utils.rs#L60)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider the following scenario:
Tx0 declares a contract.
Tx1 deploys it.
Tx1 is executed before tx0. Then tx1 will fail but its `class_hash_to_class` mapping will not be updated, hence we will not invalidate it.
</blockquote></details>

Added a TODO.
Let's think about how to solve this scenario.
___
*[`crates/blockifier/src/concurrency/validator.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NsgEHNVDijIPR9Gj-E2:-NtBXPEzBpn7pHRsQxWE:b2nign6) ([raw file](https://github.com/starkware-libs/blockifier/blob/501987ddf7ecba5c617992f3506ce0cb18b45006/crates/blockifier/src/concurrency/validator.rs#L16)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

stale?
</blockquote></details>

yes
___
*[`crates/blockifier/src/concurrency/validator.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-Nsg_Sz20v7BT4_4qJlN:-NtBXRjKCArwayG2gnCx:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/501987ddf7ecba5c617992f3506ce0cb18b45006/crates/blockifier/src/concurrency/validator.rs#L41)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

If this hits the DB then ya, always result, because it can fail due to connection issues, not enough space in DB, etc.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/validator.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-Nsg_xh-5102xiseov4n:-NtBXXLd86l9ZSAT6n6h:b-896fix) ([raw file] [...]

2024-03-18 16:01 UTC, noaov1 reviewed
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 1 of 8 files reviewed, 19 unresolved discussions (waiting on @elintul, @giladchase, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 65 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-Nsxnw_74h0E4HAM5OUM:-NtGpRFD1hHmD-eMsA8E:b21ubal) ([raw file](https://github.com/starkware-libs/blockifier/blob/51f38bcbd0d56272ee10ce8ed39224d0aba9b51f/crates/blockifier/src/concurrency/concurrency_utils.rs#L65)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Are you? :)
Please add an explanation(suggestion (draft): If a transaction writes a value that was already written, we do not charge for it. Hence, a change of a write only cell, may affect the fee and should lead to a re-execution).


<!-- Sent from Reviewable.io -->

2024-03-18 16:05 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 1 of 8 files reviewed, 19 unresolved discussions (waiting on @elintul, @giladchase, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-Nsrl8Yn-pUdcubaazrD:-NtHIl-w9u57957IUjtN:b-856mnd) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ea021dcf72695e09196f917b13a97160f4eae49/crates/blockifier/src/concurrency/concurrency_utils.rs#L22)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Not sure I got it.
The validation process occurs before the `apply_writes` process. Therefore, during validation, the value being read is compared to the corresponding value in the versioned state, and as writes values are not updated in the versioned state yet, it should be identical. 
What am I missing here?
</blockquote></details>

The validation might happen more than once


<!-- Sent from Reviewable.io -->

2024-03-19 12:30 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 1 of 8 files reviewed, 13 unresolved discussions (waiting on @elintul, @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 48 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtArcPv1jOU3_L_GmjB:-NtFF8Va4dGcOo05_vq6:b-wuw2y6) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L48)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Exactly. This function is protected by a Mutex.
</blockquote></details>

I wonder if that's legit, because the mutex protection occurs only in `VersionedStateProxy` ,whereas `VersionedState` is a separate `pub`lic struct, which users see in our API.
Its docs say it is meant to be shared between workers, but that isn't possible really if it uses a refcel, it makes it only usable if guarded behind a mutex.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAdkrr8fpXxs4rnxbv:-NtFFaCE8ku8LGFxNpMj:b-u6hwjt) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L49)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You can omit the `&` in `&expected_value` since you are adding it back later when passing to `validate_value`.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 53 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAlNUCDyfnegp-QEuU:-NtFH4gQ86vesudsvYxl:bmrnpip) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L53)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Your suggested code returns `Result<StarkFelt, Result<...>>`
</blockquote></details>

ya yr right, my bad.

I guess this is what I was going for, but it's less readable probably

```rust
         let value = self
                .storage
                .read(read_version, (address, storage_key))
                .map_or_else(|| self.initial_state.get_storage_at(address, storage_key), Ok)?;
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 58 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtLfb2m0kkrAEnvkFWc:-NtLfb2m0kkrAEnvkFWd:bwmj7nq) ([raw file](https://github.com/starkware-libs/blockifier/blob/399386acaa5e73f7b9c86c595003650e60c55421/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L58)):*
> ```XML
>         transactional_state: &mut CachedState<VersionedStateProxy<CachedState<S>>>,
>     ) -> StateResult<bool> {
>         let read_version = version - 1;
> ```

prev_version maybe?



_Code quote:_
```XML
read_version
```


<!-- Sent from Reviewable.io -->

2024-03-19 12:30 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 1 of 8 files reviewed, 14 unresolved discussions (waiting on @elintul, @MohammadNassar1, @noaov1, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-03-19 12:45 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 1 of 8 files reviewed, 16 unresolved discussions (waiting on @elintul, @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 125 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtLity64dEy4cGu8g-a:-NtLity64dEy4cGu8g-b:b-i4y6k8) ([raw file](https://github.com/starkware-libs/blockifier/blob/399386acaa5e73f7b9c86c595003650e60c55421/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L125)):*
> ```XML
>         for (key, value) in &cache.storage_writes {
>             self.storage.write(version, *key, *value);
>         }
> ```

unpack instead of *



_Code quote:_
```XML
        for (key, value) in &cache.storage_writes {
            self.storage.write(version, *key, *value);
        }
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 139 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtLjFik9ke_JoUCFY2b:-NtLjFik9ke_JoUCFY2c:b-khgkqg) ([raw file](https://github.com/starkware-libs/blockifier/blob/399386acaa5e73f7b9c86c595003650e60c55421/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L139)):*
> ```XML
>             self.compiled_contract_classes.write(version, *key, value.clone());
>         }
>     }
> ```

This feels too similar to TransactionState's commit action, there might be a shared trait that both can use, needs some thinking though.

In general, any _behavior_ that versionedStorage has that is virtually the same as that in CachedState, should probably be shared.
We want a shared interface between two states that (should) look like they behave in the same way, up to some internal threading/no-threading implementation that should be as hidden as possible.



_Code quote:_
```XML
    pub fn apply_writes(
        &mut self,
        version: Version,
        transactional_state: &mut CachedState<VersionedStateProxy<CachedState<S>>>,
    ) {
        let cache = transactional_state.cache.borrow();

        for (key, value) in &cache.storage_writes {
            self.storage.write(version, *key, *value);
        }
        for (key, value) in &cache.nonce_writes {
            self.nonces.write(version, *key, *value);
        }
        for (key, value) in &cache.class_hash_writes {
            self.class_hashes.write(version, *key, *value);
        }
        for (key, value) in &cache.compiled_class_hash_writes {
            self.compiled_class_hashes.write(version, *key, *value);
        }
        let class_hash_to_class = transactional_state.class_hash_to_class.borrow();
        for (key, value) in &*class_hash_to_class {
            self.compiled_contract_classes.write(version, *key, value.clone());
        }
    }
```


<!-- Sent from Reviewable.io -->

2024-03-19 15:39 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 1 of 8 files reviewed, 16 unresolved discussions (waiting on @elintul, @giladchase, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAdkrr8fpXxs4rnxbv:-NtMLFsT0CeKJUmB6BLD:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L49)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

You can omit the `&` in `&expected_value` since you are adding it back later when passing to `validate_value`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 58 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtLfb2m0kkrAEnvkFWc:-NtMKuUy4t08wL6_F7CY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/399386acaa5e73f7b9c86c595003650e60c55421/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L58)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

prev_version maybe?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 125 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtLity64dEy4cGu8g-a:-NtMM4y-DGBn6I4blKRU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/399386acaa5e73f7b9c86c595003650e60c55421/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L125)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

unpack instead of *
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 22 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-Nsrl8Yn-pUdcubaazrD:-NtMJWeP8c-ajl9VQPur:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ea021dcf72695e09196f917b13a97160f4eae49/crates/blockifier/src/concurrency/concurrency_utils.rs#L22)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

The validation might happen more than once
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/concurrency_utils.rs` line 65 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-Nsxnw_74h0E4HAM5OUM:-NtMKgqp-ASNsHzVMboI:b-jzstpm) ([raw file](https://github.com/starkware-libs/blockifier/blob/51f38bcbd0d56272ee10ce8ed39224d0aba9b51f/crates/blockifier/src/concurrency/concurrency_utils.rs#L65)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Are you? :)
Please add an explanation(suggestion (draft): If a transaction writes a value that was already written, we do not charge for it. Hence, a change of a write only cell, may affect the fee and should lead to a re-execution).
</blockquote></details>

Sorry, my bad.
updated now.


<!-- Sent from Reviewable.io -->

2024-03-20 08:52 UTC, noaov1 reviewed
> Reviewed 2 of 6 files at r4, 1 of 3 files at r5, 2 of 5 files at r6, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: all files reviewed, 15 unresolved discussions (waiting on @elintul, @giladchase, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 48 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtArcPv1jOU3_L_GmjB:-NtPuiXOA-0vpFvBWCMY:b-j341no) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L48)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I wonder if that's legit, because the mutex protection occurs only in `VersionedStateProxy` ,whereas `VersionedState` is a separate `pub`lic struct, which users see in our API.
Its docs say it is meant to be shared between workers, but that isn't possible really if it uses a refcel, it makes it only usable if guarded behind a mutex.
</blockquote></details>

Good point (this applies also for the `class_hash_to_class` field).
We may need to consider storing the read set directly on the `VersionedState`.
@MohammadNassar1 - can you please add a TODO and explain the issue?
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 33 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtM13n2Asjah54_Svjq:-NtM13n2Asjah54_Svjr:b-5iqc6t) ([raw file](https://github.com/starkware-libs/blockifier/blob/399386acaa5e73f7b9c86c595003650e60c55421/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L33)):*
> ```XML
> fn validate_value<T, E>(value_result: Result<T, E>, expected_value: &T) -> Result<bool, E>
> where
>     T: PartialEq,
> ```

Out of curiosity- why not use `Eq`?



_Code quote:_
```XML
    T: PartialEq,
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 93 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtPwoSoEzIALUWLXVmI:-NtPwoSoEzIALUWLXVmJ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/14bbd8456475326b4bdbf098d7bdb4410c660d2d/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L93)):*
> ```XML
>         }
> 
>         for (&class_hash, expected_value) in &cache.compiled_class_hash_initial_values {
> ```





_Suggestion:_
```XML
        // Added for symmetry. We currently do not update this initial mapping.
        for (&class_hash, expected_value) in &cache.compiled_class_hash_initial_values {
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 104 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtQ1EIu08fgqQDSbFRD:-NtQ1EIu08fgqQDSbFRE:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/14bbd8456475326b4bdbf098d7bdb4410c660d2d/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L104)):*
> ```XML
> 
>         // TODO(Mohammad, 01/04/2024): Consider invalidating a deploy transaction that precedes a
>         // declare transaction.
> ```





_Suggestion:_
```XML
        // TODO(Mohammad, 01/04/2024): Edit the code to handle the case of a deploy preceding a decalre transaction.
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 122 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtQ1zR_7NhXly1jTsl-:-NtQ1zR_7NhXly1jTsl0:b4beflp) ([raw file](https://github.com/starkware-libs/blockifier/blob/14bbd8456475326b4bdbf098d7bdb4410c660d2d/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L122)):*
> ```XML
>         &mut self,
>         version: Version,
>         transactional_state: &mut CachedState<VersionedStateProxy<CachedState<S>>>,
> ```

Does it have to be a `VersionedState`?



_Suggestion:_
```XML
        transactional_state: &mut CachedState<S>,
```


<!-- Sent from Reviewable.io -->

2024-03-20 09:26 UTC, giladchase submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: all files reviewed, 11 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 48 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtArcPv1jOU3_L_GmjB:-NtQAbmV5fOguwILWZHu:b6han97) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L48)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Good point (this applies also for the `class_hash_to_class` field).
We may need to consider storing the read set directly on the `VersionedState`.
@MohammadNassar1 - can you please add a TODO and explain the issue?
</blockquote></details>

+ monday task
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 99 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAnk_F7Ij-eRdWvFdv:-NtQ6eW7DY7KtdwjBbVY:bsw21i3) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L99)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Both here and in `validate_read_set` and `apply_writes` it looks like all fields of the struct are accessed in tandem.
Any way of doing a kind of "vector operation" here?
</blockquote></details>

Unblocking, but add a monday item to check it out plz.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 139 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtLjFik9ke_JoUCFY2b:-NtQAAxW-zNzPsNGxZJj:bsw21i3) ([raw file](https://github.com/starkware-libs/blockifier/blob/399386acaa5e73f7b9c86c595003650e60c55421/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L139)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This feels too similar to TransactionState's commit action, there might be a shared trait that both can use, needs some thinking though.

In general, any _behavior_ that versionedStorage has that is virtually the same as that in CachedState, should probably be shared.
We want a shared interface between two states that (should) look like they behave in the same way, up to some internal threading/no-threading implementation that should be as hidden as possible.
</blockquote></details>

Unblocking, but add a monday item to check it out plz.


<!-- Sent from Reviewable.io -->

2024-03-20 09:27 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: all files reviewed, 9 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 139 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtLjFik9ke_JoUCFY2b:-NtQAs-G5-FKWjQnKiuf:b-9aqest) ([raw file](https://github.com/starkware-libs/blockifier/blob/399386acaa5e73f7b9c86c595003650e60c55421/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L139)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Unblocking, but add a monday item to check it out plz.
</blockquote></details>

unblocking


<!-- Sent from Reviewable.io -->

2024-03-20 12:29 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 7 of 8 files reviewed, 7 unresolved discussions (waiting on @elintul, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 33 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtM13n2Asjah54_Svjq:-NtQjoaN6zQzyxAYSEEO:b-298ls5) ([raw file](https://github.com/starkware-libs/blockifier/blob/399386acaa5e73f7b9c86c595003650e60c55421/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L33)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Out of curiosity- why not use `Eq`?
</blockquote></details>

`PartialEq` is used to implement the `==` and `!=` comparison operators. which is exactly what I need for this method.
`Eq` implements `PartialEq` and requires more properties.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 122 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtQ1zR_7NhXly1jTsl-:-NtQoGK77N7tj6VahxjG:b-t9pcdk) ([raw file](https://github.com/starkware-libs/blockifier/blob/14bbd8456475326b4bdbf098d7bdb4410c660d2d/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L122)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Does it have to be a `VersionedState`?
</blockquote></details>

No, but note that `S` here is used for the state used in `VersionedState` struct.


<!-- Sent from Reviewable.io -->

2024-03-20 13:00 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 7 of 8 files reviewed, 9 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 59 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtQtkbJ4ch0jz3g43Q0:-NtQtkbKA2wPYXYARXW-:ban5ghp) ([raw file](https://github.com/starkware-libs/blockifier/blob/d33dd0968896abc980e7c744d1ecf7f9e594d729/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L59)):*
> ```XML
>         &mut self,
>         version: Version,
>         transactional_state: &mut CachedState<VersionedStateProxy<CachedState<S>>>,
> ```

We would need to keep the reads and writes in the versioned state.
So, to start with, we can pass here some struct - something similar to StateCache but cleaner, without functions. This struct creation should consume the cached state.

cc @noaov1 



_Code quote:_
```XML
transactional_state: &mut CachedState<VersionedStateProxy<CachedState<S>>>,
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 66 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtQukX_AVhNLCQyW3zc:-NtQukXa7KH45AaFKP_g:b6fy62m) ([raw file](https://github.com/starkware-libs/blockifier/blob/d33dd0968896abc980e7c744d1ecf7f9e594d729/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L66)):*
> ```XML
>             let value = match self.storage.read(prev_version, (contract_address, storage_key)) {
>                 Some(value) => Ok(value),
>                 None => self.initial_state.get_storage_at(contract_address, storage_key),
> ```

This arm must be unreachable. I prefer to unwarp or something. @noaov1 wdyt?



_Code quote:_
```XML
None => self.initial_state.get_storage_at(contract_address, storage_key),
```


<!-- Sent from Reviewable.io -->

2024-03-20 13:01 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 7 of 8 files reviewed, 10 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 61 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtQwiXx4a0Muwh4rFyg:-NtQwiXx4a0Muwh4rFyh:b-t9meik) ([raw file](https://github.com/starkware-libs/blockifier/blob/d33dd0968896abc980e7c744d1ecf7f9e594d729/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L61)):*
> ```XML
>         transactional_state: &mut CachedState<VersionedStateProxy<CachedState<S>>>,
>     ) -> StateResult<bool> {
>         let prev_version = version - 1;
> ```

What about version 0?
...you don't need to validate version 0 reads. You can just return in this case
Document that



_Code quote:_
```XML
let prev_version = version - 1;
```


<!-- Sent from Reviewable.io -->

2024-03-21 08:09 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 7 of 8 files reviewed, 10 unresolved discussions (waiting on @elintul, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 48 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtArcPv1jOU3_L_GmjB:-NtSKInfAWbsU6K5XC_a:b-2ernpt) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L48)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

+ monday task
</blockquote></details>

both a  TODO and a Monday task were added:
https://starkware.monday.com/boards/6234683038/pulses/6258205282
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 99 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtAnk_F7Ij-eRdWvFdv:-NtR-emDDhM9ACfbE_DX:b-2pastc) ([raw file](https://github.com/starkware-libs/blockifier/blob/e8fb6d61352445b9c34ac4e208499c7a8f4a6133/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L99)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Unblocking, but add a monday item to check it out plz.
</blockquote></details>

Added
https://starkware.monday.com/boards/6234683038/pulses/6293773093
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 139 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtLjFik9ke_JoUCFY2b:-NtR20Gj02aUvysuWsU8:b-2p9j0a) ([raw file](https://github.com/starkware-libs/blockifier/blob/399386acaa5e73f7b9c86c595003650e60c55421/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L139)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

unblocking
</blockquote></details>

Added
https://starkware.monday.com/boards/6234683038/pulses/6293775024
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 59 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtQtkbJ4ch0jz3g43Q0:-NtSP59m0pO_vJVkQ9rf:bok81yb) ([raw file](https://github.com/starkware-libs/blockifier/blob/d33dd0968896abc980e7c744d1ecf7f9e594d729/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L59)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

We would need to keep the reads and writes in the versioned state.
So, to start with, we can pass here some struct - something similar to StateCache but cleaner, without functions. This struct creation should consume the cached state.

cc @noaov1
</blockquote></details>

I've added a TODO for that.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 61 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtQwiXx4a0Muwh4rFyg:-NtR8KkOBTD8nTZ2DMyN:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d33dd0968896abc980e7c744d1ecf7f9e594d729/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L61)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

What about version 0?
...you don't need to validate version 0 reads. You can just return in this case
Document that
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-21 08:19 UTC, noaov1 reviewed
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: all files reviewed (commit messages unreviewed), 9 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 122 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtQ1zR_7NhXly1jTsl-:-NtV4cWkCmpqA4cVwOnp:b5fb1cp) ([raw file](https://github.com/starkware-libs/blockifier/blob/14bbd8456475326b4bdbf098d7bdb4410c660d2d/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L122)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

No, but note that `S` here is used for the state used in `VersionedState` struct.
</blockquote></details>

I see. Does it matter? 
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 66 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtQukX_AVhNLCQyW3zc:-NtV3II43tLz7O1z3VLk:b-wcn427) ([raw file](https://github.com/starkware-libs/blockifier/blob/d33dd0968896abc980e7c744d1ecf7f9e594d729/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L66)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

This arm must be unreachable. I prefer to unwarp or something. @noaov1 wdyt?
</blockquote></details>

Please use `except`


<!-- Sent from Reviewable.io -->

2024-03-21 10:20 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: all files reviewed (commit messages unreviewed), 8 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 59 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtQtkbJ4ch0jz3g43Q0:-NtVWQ7u6BvOW1C9Qk4S:b2drafk) ([raw file](https://github.com/starkware-libs/blockifier/blob/d33dd0968896abc980e7c744d1ecf7f9e594d729/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L59)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you at least pass the StateCache directly to this function and to `apply_writes`?
</blockquote></details>

You can use `StateCache` only and remove the use of `class_hash_to_class` (since it's currently irrelevant)


<!-- Sent from Reviewable.io -->

2024-03-21 11:45 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: all files reviewed (commit messages unreviewed), 8 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 66 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtQukX_AVhNLCQyW3zc:-NtVnvbp0guq575VMPyd:b-a2qpsk) ([raw file](https://github.com/starkware-libs/blockifier/blob/d33dd0968896abc980e7c744d1ecf7f9e594d729/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L66)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please use `except`
</blockquote></details>

Wait. 
What is the expected behaviour if someone who is using the blockifier crate runs the `validate_read_set`method out of the blue? 
(the unreachable statement is under the assumption that we will run this method after executing the transaction).
Maybe it is a reasonable assumption.


<!-- Sent from Reviewable.io -->

2024-03-21 12:35 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: all files reviewed (commit messages unreviewed), 8 unresolved discussions (waiting on @elintul, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 122 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtQ1zR_7NhXly1jTsl-:-NtVv1wE0CF7G1nDixCX:b-oixmpp) ([raw file](https://github.com/starkware-libs/blockifier/blob/14bbd8456475326b4bdbf098d7bdb4410c660d2d/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L122)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I see. Does it matter?
</blockquote></details>

In this case, I should use a different generic parameter (not `S`). It also implements `StateRead`.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 66 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtQukX_AVhNLCQyW3zc:-NtW-9t72XO8eHO3PJBr:btwkobs) ([raw file](https://github.com/starkware-libs/blockifier/blob/d33dd0968896abc980e7c744d1ecf7f9e594d729/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L66)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Wait. 
What is the expected behaviour if someone who is using the blockifier crate runs the `validate_read_set`method out of the blue? 
(the unreachable statement is under the assumption that we will run this method after executing the transaction).
Maybe it is a reasonable assumption.
</blockquote></details>

Maybe this method should be `pub(crate)` to prevent others from using it.


<!-- Sent from Reviewable.io -->

2024-03-21 13:04 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 7 of 8 files reviewed, 8 unresolved discussions (waiting on @elintul, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 59 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtQtkbJ4ch0jz3g43Q0:-NtW67UK4_VQ__Bd0Gqe:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d33dd0968896abc980e7c744d1ecf7f9e594d729/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L59)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

You can use `StateCache` only and remove the use of `class_hash_to_class` (since it's currently irrelevant)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-21 13:09 UTC, noaov1 approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: all files reviewed, 11 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 54 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtW6XtD3BC2PUfKbZRV:-NtW6XtD3BC2PUfKbZRW:b82zmna) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1b16a3599411a239e0dda8bd0aeb68894ceae14/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L54)):*
> ```XML
>         &mut self,
>         version: Version,
>         transactional_state: &mut StateCache,
> ```

Will be `read_set` in the future.



_Suggestion:_
```XML
        state_cache: &mut StateCache,
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 62 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtW6Tbj6GyOEZSQkTFF:-NtW6TbkCdVEoGfiy7om:ba3dfna) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1b16a3599411a239e0dda8bd0aeb68894ceae14/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L62)):*
> ```XML
>         }
>         let prev_version = version - 1;
>         // let cache = transactional_state.cache.borrow();
> ```

Remove?



_Code quote:_
```XML
        // let cache = transactional_state.cache.borrow();
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 110 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtW6ox18Ay3efb-QM6x:-NtW6ox18Ay3efb-QM6y:b-n2uwo9) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1b16a3599411a239e0dda8bd0aeb68894ceae14/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L110)):*
> ```XML
>         &mut self,
>         version: Version,
>         transactional_state: &mut StateCache,
> ```

Will be `write_set` in the future.



_Suggestion:_
```XML
state_cache: &mut StateCache,
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 112 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtW6lz11_gw25lw2Twz:-NtW6lz11_gw25lw2Tx-:ba3dfna) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1b16a3599411a239e0dda8bd0aeb68894ceae14/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L112)):*
> ```XML
>         transactional_state: &mut StateCache,
>         class_hash_to_class: ContractClassMapping,
>         // transactional_state: &mut CachedState<VersionedStateProxy<CachedState<S>>>,
> ```

Remove?



_Code quote:_
```XML
        // transactional_state: &mut CachedState<VersionedStateProxy<CachedState<S>>>,
```


<!-- Sent from Reviewable.io -->

2024-03-21 14:02 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: all files reviewed, 8 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 66 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtQukX_AVhNLCQyW3zc:-NtWIyyt19jRxMEnBGX1:b-ap29yz) ([raw file](https://github.com/starkware-libs/blockifier/blob/d33dd0968896abc980e7c744d1ecf7f9e594d729/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L66)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Maybe this method should be `pub(crate)` to prevent others from using it.
</blockquote></details>

I prefer to be as strict as possible :)
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 55 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtWJEA7-hnSuN1QI8aN:-NtWJEA7-hnSuN1QI8aO:b4s59rz) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1b16a3599411a239e0dda8bd0aeb68894ceae14/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L55)):*
> ```XML
>         version: Version,
>         transactional_state: &mut StateCache,
>     ) -> StateResult<bool> {
> ```

Not needed anymore, right?



_Suggestion:_
```XML
) -> bool {
```


<!-- Sent from Reviewable.io -->

2024-03-21 14:21 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @elintul, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 55 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtWJEA7-hnSuN1QI8aN:-NtWNMctBMeEjDWtTu3J:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a1b16a3599411a239e0dda8bd0aeb68894ceae14/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L55)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Not needed anymore, right?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-21 15:42 UTC, noaov1 submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-:-NtWfHwH-BN1K_QngPPo:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-03-21 15:53 UTC, Yoni-Starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-:-NtWhc00DYkdOaEFBMrw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-03-21 19:18 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/call_info.rs` line 240 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtXPlM6Dvc8xQ9Y84hu:-NtXPlM6Dvc8xQ9Y84hv:b-ht6u5h) ([raw file](https://github.com/starkware-libs/blockifier/blob/3dd541df7d5782a3c9929c4f9d5f7f52603c2355/crates/blockifier/src/execution/call_info.rs#L240)):*
> ```XML
> 
>     fn next(&mut self) -> Option<Self::Item> {
>         let call_info = self.call_infos.pop()?;
> ```

Clippy check fails on the below error.
I've updated the code according to the suggestion below, and it works.
It appears that the CI was updated by someone recently without ensuring that it is passing as expected.



_Code quote (i):_
```XML
        let call_info = self.call_infos.pop()?;
```



_Code snippet (ii):_
```XML
error: this `let...else` may be rewritten with the `?` operator
   --> crates/blockifier/src/execution/call_info.rs:240:9
    |
240 | /         let Some(call_info) = self.call_infos.pop() else {
241 | |             return None;
242 | |         };
    | |__________^ help: replace it with: `let call_info = self.call_infos.pop()?;`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#question_mark
    = note: `-D clippy::question-mark` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::question_mark)]`
```


<!-- Sent from Reviewable.io -->

2024-03-24 08:25 UTC, noaov1 approved these changes
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/call_info.rs` line 240 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtXPlM6Dvc8xQ9Y84hu:-NtjYaCT3xZ3ew9YBeqC:b24apzy) ([raw file](https://github.com/starkware-libs/blockifier/blob/3dd541df7d5782a3c9929c4f9d5f7f52603c2355/crates/blockifier/src/execution/call_info.rs#L240)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Clippy check fails on the below error.
I've updated the code according to the suggestion below, and it works.
It appears that the CI was updated by someone recently without ensuring that it is passing as expected.
</blockquote></details>

Interesting. You can use a question mark on an option:



_Code snippet:_
```XML
if option.is_none() {
    return None;
}
Could be written:

option?;
```


<!-- Sent from Reviewable.io -->

2024-03-24 09:32 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/call_info.rs` line 240 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtXPlM6Dvc8xQ9Y84hu:-NtjnLPO-d2_gx4YtIl4:b7jlfqp) ([raw file](https://github.com/starkware-libs/blockifier/blob/3dd541df7d5782a3c9929c4f9d5f7f52603c2355/crates/blockifier/src/execution/call_info.rs#L240)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Interesting. You can use a question mark on an option:
</blockquote></details>

Yes, check the [link](https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/reference/expressions/operator-expr.html#:~:text=The%20question%20mark%20operator%20(%20%3F%20),%3E%20type%2C%20it%20propagates%20errors.).
"The question mark operator (`?`) unwraps valid values or returns errornous values, propagating them to the calling function. It is a unary postfix operator that can only be applied to the types `Result<T, E>` and `Option<T>`.


<!-- Sent from Reviewable.io -->

2024-03-24 09:34 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/call_info.rs` line 240 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtXPlM6Dvc8xQ9Y84hu:-NtjnigJ02YfIQf2HT4_:b-sisoc9) ([raw file](https://github.com/starkware-libs/blockifier/blob/3dd541df7d5782a3c9929c4f9d5f7f52603c2355/crates/blockifier/src/execution/call_info.rs#L240)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Yes, check the [link](https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/reference/expressions/operator-expr.html#:~:text=The%20question%20mark%20operator%20(%20%3F%20),%3E%20type%2C%20it%20propagates%20errors.).
"The question mark operator (`?`) unwraps valid values or returns errornous values, propagating them to the calling function. It is a unary postfix operator that can only be applied to the types `Result<T, E>` and `Option<T>`.
</blockquote></details>

Could be a new lint in clippy, or the existing lint was fixed to cover more cases, and you were just unlucky enough to be hit with it on your pr :)


<!-- Sent from Reviewable.io -->

2024-03-24 09:58 UTC, noaov1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-03-24 09:58 UTC, noaov1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2024-03-24 10:01 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1578)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/execution/call_info.rs` line 240 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1578#-NtXPlM6Dvc8xQ9Y84hu:-NtjtZPaEeJO6XywUvP0:b-7loa6f) ([raw file](https://github.com/starkware-libs/blockifier/blob/3dd541df7d5782a3c9929c4f9d5f7f52603c2355/crates/blockifier/src/execution/call_info.rs#L240)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Could be a new lint in clippy, or the existing lint was fixed to cover more cases, and you were just unlucky enough to be hit with it on your pr :)
</blockquote></details>

Ops! :'(
Why didn't it fail for the one that updated the new lint in clippy?


<!-- Sent from Reviewable.io -->

2024-03-24 10:02 UTC, merged