refactor: add recursive error stack handling
starkware-libs/blockifier pull request #1614
Opened 2024-03-04 12:16 UTC by zuphitf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1614)

2024-03-04 14:32 UTC, dorimedini-starkware requested changes
> Reviewed 5 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1614)* status: all files reviewed, 29 unresolved discussions (waiting on @zuphitf)

___
*[`crates/blockifier/src/execution/errors.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8OwI99qMAJBsAXuTh:-Ns8OwI99qMAJBsAXuTi:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/91cd65362f3a516b3fa23d233c5e2a79b4389470/crates/blockifier/src/execution/errors.rs#L182)):*
> ```XML
> }
> 
> pub fn match_execute_directly(error: &CairoRunError, storage_address: StarkFelt) -> String {
> ```





_Suggestion:_
```XML
pub(crate) fn
```
___
*[`crates/blockifier/src/execution/errors.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8i5Pr7JiAyiTfiexc:-Ns8i5Pr7JiAyiTfiexd:b-pl305) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L1)):*
> ```XML
> use cairo_vm::types::errors::math_errors::MathError;
> ```

the `match_...` naming convension isn't great
how about `extract_stack_trace_...`?
___
*[`crates/blockifier/src/execution/errors.rs` line 190 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8iUoe3kW1QDpjYdhb:-Ns8iUoe3kW1QDpjYdhc:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L190)):*
> ```XML
>     error_stack = match_cairo_run_error(error_stack, error);
> 
>     // Temp hack to match existing regression. This is to be deleted shortly.
> ```





_Suggestion:_
```XML
// TODO(Zuphit, 1/4/2024): Temp hack to match existing regression. This is to be deleted shortly.
```
___
*[`crates/blockifier/src/execution/errors.rs` line 214 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8ijylCf9TRWCgeVpH:-Ns8ijylCf9TRWCgeVpI:b-vk3cef) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L214)):*
> ```XML
>     error_stack.push(error.to_string());
>     error_stack
> }
> ```

same runtime (or better, I think), and less lines



_Suggestion:_
```XML
fn match_cairo_run_error(error_stack: &mut Vec<String>, error: &CairoRunError) {
    if let CairoRunError::VmException(vm_exception) = error {
        return match_vm_exception(error_stack, vm_exception);
    }
    error_stack.push(error.to_string());
}
```
___
*[`crates/blockifier/src/execution/errors.rs` line 216 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8j4Kx6l-pfKgIj15s:-Ns8j4Kx6l-pfKgIj15t:byr4ffv) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L216)):*
> ```XML
> }
> 
> fn match_vm_exception(mut error_stack: Vec<String>, vm_exception: &VmException) -> Vec<String> {
> ```

see above



_Suggestion:_
```XML
error_stack: &mut Vec<String>
```
___
*[`crates/blockifier/src/execution/errors.rs` line 216 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8jWj898r7ao8E4UK_:-Ns8jWj898r7ao8E4UKa:b7pjndu) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L216)):*
> ```XML
> }
> 
> fn match_vm_exception(mut error_stack: Vec<String>, vm_exception: &VmException) -> Vec<String> {
> ```

add a docstring explaining what this function does (i.e. what the inner exception represents)



_Code quote:_
```XML
match_vm_exception
```
___
*[`crates/blockifier/src/execution/errors.rs` line 217 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8j9ox7DbnH4o-7hCC:-Ns8j9ox7DbnH4o-7hCD:bb7phvt) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L217)):*
> ```XML
> 
> fn match_vm_exception(mut error_stack: Vec<String>, vm_exception: &VmException) -> Vec<String> {
>     let vm_exception_preemble = format!("Error at pc=0:{}:", vm_exception.pc);
> ```

typo



_Suggestion:_
```XML
preamble
```
___
*[`crates/blockifier/src/execution/errors.rs` line 220 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8jFIuC6o427SUon8u:-Ns8jFIuC6o427SUon8v:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L220)):*
> ```XML
>     error_stack.push(vm_exception_preemble);
> 
>     // This match us temporarily here to match existing regression. This is to be deleted shortly.
> ```





_Suggestion:_
```XML
// TODO(Zuphit, 1/4/2024): This match is temporarily here to match existing regression. This is to be deleted shortly.
```
___
*[`crates/blockifier/src/execution/errors.rs` line 223 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8jM728ylcR7EyLatH:-Ns8jM728ylcR7EyLatI:b64yghf) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L223)):*
> ```XML
>     match &vm_exception.inner_exc {
>         VirtualMachineError::Hint(_) => {
>             error_stack.push(String::from("Got an exception while executing a hint."));
> ```

consistency



_Suggestion:_
```XML
"Got an exception while executing a hint.".to_string()
```
___
*[`crates/blockifier/src/execution/errors.rs` line 238 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8ji940fosRBpAQJeC:-Ns8ji940fosRBpAQJeD:byr4ffv) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L238)):*
> ```XML
> 
> fn match_virtual_machine_error(
>     mut error_stack: Vec<String>,
> ```

see above



_Suggestion:_
```XML
error_stack: &mut Vec<String>
```
___
*[`crates/blockifier/src/execution/errors.rs` line 242 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8jndhC0q75vtF_JRn:-Ns8jndhC0q75vtF_JRo:bqfsbnu) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L242)):*
> ```XML
> ) -> Vec<String> {
>     match vm_error {
>         VirtualMachineError::Hint(ref bx) => {
> ```

boxed_hint_error



_Code quote:_
```XML
bx
```
___
*[`crates/blockifier/src/execution/errors.rs` line 251 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8kJM05TPqZI3hhy8-:-Ns8kJM05TPqZI3hhy80:b-mhiv9x) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L251)):*
> ```XML
>             let syscall_exec_err = anyhow_error.downcast_ref::<SyscallExecutionError>();
>             if syscall_exec_err.is_some() {
>                 let downcast_anyhow = syscall_exec_err.unwrap();
> ```

better, and no `unwrap`.
if it doesn't work, change the unwrap to `expect("Successful downcast should not fail to unwrap.")`



_Suggestion:_
```XML
            if let Some(downcast_anyhow) = syscall_exec_err {
```
___
*[`crates/blockifier/src/execution/errors.rs` line 257 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8kWnYBc72rxpbWi5I:-Ns8kWnYBc72rxpbWi5J:b-7ropln) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L257)):*
> ```XML
>                     anyhow_error.downcast_ref::<DeprecatedSyscallExecutionError>();
>                 if deprecated_syscall_exec_err.is_some() {
>                     let downcast_anyhow = deprecated_syscall_exec_err.unwrap();
> ```

ditto



_Code quote:_
```XML
                if deprecated_syscall_exec_err.is_some() {
                    let downcast_anyhow = deprecated_syscal [...]

2024-03-06 15:34 UTC, zuphitf reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1614)* status: all files reviewed, 23 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/errors.rs` line 182 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8OwI99qMAJBsAXuTh:-NsDplIE5LGpj4PKKbPu:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/91cd65362f3a516b3fa23d233c5e2a79b4389470/crates/blockifier/src/execution/errors.rs#L182)):*
> ```XML
> }
> 
> pub fn match_execute_directly(error: &CairoRunError, storage_address: StarkFelt) -> String {
> ```

Done.
___
*[`crates/blockifier/src/execution/errors.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8i5Pr7JiAyiTfiexc:-NsJ9E9o0o7m3BkKjjAH:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L1)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the `match_...` naming convension isn't great
how about `extract_stack_trace_...`?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/errors.rs` line 190 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8iUoe3kW1QDpjYdhb:-NsJGk350XDi0MBQ6mg5:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L190)):*
> ```XML
>     error_stack = match_cairo_run_error(error_stack, error);
> 
>     // Temp hack to match existing regression. This is to be deleted shortly.
> ```

Done.
___
*[`crates/blockifier/src/execution/errors.rs` line 214 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8ijylCf9TRWCgeVpH:-NsJGl500AFVYT02BeqS:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L214)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

same runtime (or better, I think), and less lines
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/errors.rs` line 216 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8j4Kx6l-pfKgIj15s:-NsJGlR1-x1ayRJF1Jg-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L216)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/errors.rs` line 220 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8jFIuC6o427SUon8u:-NsJH0wc9jKX9ZK1tLez:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L220)):*
> ```XML
>     error_stack.push(vm_exception_preemble);
> 
>     // This match us temporarily here to match existing regression. This is to be deleted shortly.
> ```

Done.
___
*[`crates/blockifier/src/execution/errors.rs` line 223 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8jM728ylcR7EyLatH:-NsEAhBG2YcjqASHJkl5:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L223)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

consistency
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/errors.rs` line 238 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8ji940fosRBpAQJeC:-NsJH2Oz4CCbEQOwYBFp:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L238)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/errors.rs` line 242 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8jndhC0q75vtF_JRn:-NsEAxCrDGTUtho5QKP4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L242)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

boxed_hint_error
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/errors.rs` line 251 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8kJM05TPqZI3hhy8-:-NsEC0W0DhqF5wE6ajHS:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L251)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

better, and no `unwrap`.
if it doesn't work, change the unwrap to `expect("Successful downcast should not fail to unwrap.")`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/errors.rs` line 257 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8kWnYBc72rxpbWi5I:-NsECifu2QUqqEuiOQ9t:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L257)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/errors.rs` line 267 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8kciB2t8iUByzSyva:-NsJJrVF3CcTwQpF4C0e:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L267)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. shouldn't the `vm_error.to_string()` be placed in the wildcard match branch?
2. write it as a TODO
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/errors.rs` line 271 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8klXFDH3i8d7d90jT:-NsJJsS41V3oXAnMEXgQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L271)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/errors.rs` line 282 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8l1tGEjdAyAVmKCew:-NsJJy-pAg2wI5Ls3Fj_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L282)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you may not end up doing it but your name should appear
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/errors.rs` line 301 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8lXPkEf4Tye9NEdT-:-NsJJz0jDeRARVRZYBna:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L301)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/errors.rs` line 306 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8l_LH8dNU8oDNJ3bS:-NsEDFI0DrEqGZo1cT-t:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L306)):*
> ```XML
>     match syscall_error {
>         DeprecatedSyscallExecutionError::CallContractExecutionError { storage_addres [...]

2024-03-06 17:02 UTC, dorimedini-starkware reviewed
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1614)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)



<!-- Sent from Reviewable.io -->

2024-03-10 08:43 UTC, zuphitf commented
*[`crates/blockifier/src/execution/errors.rs` line 216 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-Ns8jWj898r7ao8E4UK_:-NsbWy0m9Cvk-g-MKZtQ:b-wrbmn5) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a3a292af2ac2aca5f60490122bbc82f08fed628/crates/blockifier/src/execution/errors.rs#L216)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add a docstring explaining what this function does (i.e. what the inner exception represents)
</blockquote></details>

Added a doc for the temporary lookahead, like we discussed 


<!-- Sent from Reviewable.io -->

2024-03-10 09:43 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1614#-:-NsbjpYh638jlxI6nyCl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zuphitf)



<!-- Sent from Reviewable.io -->

2024-03-10 09:44 UTC, merged