refactor: fill os_constants in test_successful_parsing
starkware-libs/blockifier pull request #1615
Opened 2024-03-04 12:43 UTC by OriStarkware

2024-03-05 09:36 UTC, noaov1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @giladchase and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants_test.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsCy0-W-OIFaQxHNrLN:-NsCy0-W-OIFaQxHNrLO:b-sljf8e) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L23)):*
> ```XML
> 
> #[test]
> fn test_successful_parsing() {
> ```

I wonder if this test is still relevant now that we use struct. @giladchase ?



_Code quote:_
```XML
fn test_successful_parsing() {
```


<!-- Sent from Reviewable.io -->

2024-03-05 13:34 UTC, barak-b-starkware requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: all files reviewed, 8 unresolved discussions (waiting on @giladchase and @OriStarkware)

___
*[`crates/blockifier/src/test_utils.rs` line 345 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDcRB20F-6DKvXpHYT:-NsDcRB3C_tzIRAw9xFR:b-166tem) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/test_utils.rs#L345)):*
> ```XML
> pub fn update_json_value(base: &mut serde_json::Value, update: &serde_json::Value) {
>     if let (serde_json::Value::Object(base_map), serde_json::Value::Object(update_map)) =
>         (base, update)
> ```

Which argument will not match the `(serde_json::Value::Object(base_map), serde_json::Value::Object(update_map))` pattern? or in which case it happens?



_Code quote:_
```XML
(base, update)
```
___
*[`crates/blockifier/src/test_utils.rs` line 349 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDdt4V1bDOia7mBDC-:-NsDdt4V1bDOia7mBDC0:b-mhbd88) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/test_utils.rs#L349)):*
> ```XML
>         for (key, update_value) in update_map {
>             base_map.insert(key.clone(), update_value.clone());
>         }
> ```

WDYT about: (see [comment](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDe58W-MLcxZj-DwpL) below)



_Suggestion:_
```XML
        base_map.extend(update_map)
```
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDlInh-IOS_52XKSLs:-NsDlInh-IOS_52XKSLt:b-ku88ko) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L8)):*
> ```XML
> // TODO: Test Starknet OS validation.
> 
> fn fill_and_load_os_constants(json_data: &str) -> Result<Arc<OSConstants>, OsConstantsSerdeError> {
> ```

Something like:



_Suggestion:_
```XML
fn update_default_os_constants(updated_data: &str)
```
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDlY8C3gDr2DrxCYld:-NsDlY8C3gDr2DrxCYle:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L9)):*
> ```XML
> 
> fn fill_and_load_os_constants(json_data: &str) -> Result<Arc<OSConstants>, OsConstantsSerdeError> {
>     let json_value: Value =
> ```





_Suggestion:_
```XML
updated_values
```
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDlb0RCyBiAgtJku5z:-NsDlb0RCyBiAgtJku6-:b-51yvgp) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L10)):*
> ```XML
> fn fill_and_load_os_constants(json_data: &str) -> Result<Arc<OSConstants>, OsConstantsSerdeError> {
>     let json_value: Value =
>         serde_json::from_str(json_data).expect("The input data must be a vaild json.");
> ```

AFAIK the convention in tests is to use unwraps, do you think it's better to use `expect(...)` here?



_Suggestion:_
```XML
.unwrap()
```
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDlgBg6SuX7YVPSxe1:-NsDlgBg6SuX7YVPSxe2:b-51yvgp) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L15)):*
> ```XML
>     let mut os_constants: Value = default_versioned_constants
>         .get("os_constants")
>         .expect("The default versioned constants should contain os_constants.")
> ```

AFAIK the convention in tests is to use unwraps, do you think it's better to use `expect(...)` here?



_Suggestion:_
```XML
.unwrap()
```
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDe58W-MLcxZj-DwpL:-NsDe58XExux6kL7bVO2:b-vcckry) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L17)):*
> ```XML
>         .expect("The default versioned constants should contain os_constants.")
>         .clone();
>     update_json_value(&mut os_constants, &json_value);
> ```

Since the `update_json_value` only does 'map.extend(map)` I think this line should be replaced by that. 

If you think otherwise, in order to make the comment above work, you need to move ownership:



_Suggestion:_
```XML
update_json_value(&mut os_constants, json_value);
```
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsCy0-W-OIFaQxHNrLN:-NsDjhq63AUKKVwiQPIZ:b-4jkmur) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L23)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I wonder if this test is still relevant now that we use struct. @giladchase ?
</blockquote></details>

AFAIU it's the only place in the test where the `gas_cost` method of `VersionedConstants` is called and the only place where the `get_gas_costs`method of `OsConstantsRawJson` is called (as part of the`impl TryFrom<OsConstantsRawJson> for OSConstants`). Still, maybe I missed something in this file.
I suggest adding a todo to split this "unit test" into two real unit tests, one for each method.



_Suggestion:_
```XML
// TODO: Split into two tests, one for .. and another one for ..
fn test_successful_parsing() {
```


<!-- Sent from Reviewable.io -->

2024-03-05 15:21 UTC, giladchase requested changes
I missing the motivation for this: is this prep for making OsConstants into a struct?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-:-NsDcezo6ZDleyp7Y1nA:b-s6fo89)* status: all files reviewed, 10 unresolved discussions (waiting on @noaov1 and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants_test.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDdyKB9VQF_U0Til7X:-NsDdyKB9VQF_U0Til7Y:b-u4j4tb) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L20)):*
> ```XML
>     let os_constants: Arc<OSConstants> = serde_json::from_value(os_constants).unwrap();
>     Ok(os_constants)
> }
> ```

String manipulation is too flakey in most cases, also complicated to follow, best to avoid it unless absolutely necessary.

Add `create_for_testing` into both `VersionedConstants` and `OsConstants` (with cfg testing/test, like in other `create_for_testing` we have) where the former uses the latter --- this also aligns better with our testing constructors for other types.

The os constants' one should be something like
```rust
fn create_for_testing(subset_of_os_constants: HashMap) -> Osconstants
DEFAULT_VERSIONED_CONSTANTS.os_constants.clone().extend(serde_json::from_str(subset_of_os_constants)
```
(note that cloning the struct should be roughly the same complexity as creating the `default_versioned_constants` below, so complexity should remain similar



_Code quote:_
```XML
fn fill_and_load_os_constants(json_data: &str) -> Result<Arc<OSConstants>, OsConstantsSerdeError> {
    let json_value: Value =
        serde_json::from_str(json_data).expect("The input data must be a vaild json.");
    let default_versioned_constants: Value = serde_json::from_str(DEFAULT_CONSTANTS_JSON)
        .expect("The default versioned constants must be a valid json.");
    let mut os_constants: Value = default_versioned_constants
        .get("os_constants")
        .expect("The default versioned constants should contain os_constants.")
        .clone();
    update_json_value(&mut os_constants, &json_value);
    let os_constants: Arc<OSConstants> = serde_json::from_value(os_constants).unwrap();
    Ok(os_constants)
}
```
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsCy0-W-OIFaQxHNrLN:-NsDb6s2B3_scrgigR6g:bqdwr37) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L23)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I wonder if this test is still relevant now that we use struct. @giladchase ?
</blockquote></details>

I nameed this test badly, it should be "test_successful_os_resources_parsing_algorithm" or something to that effect, it is meant to showcase a simple successful parsing of the os constants (it should complement the documentation, in other words).

So I think it should stay, it shouldn't be affected by the representation of the constants as a struct, only the parsing of the JSON (IIUYC)
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDjJSl5jAy1R7klx5p:-NsDjJSl5jAy1R7klx5q:b-ib8e6i) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L49)):*
> ```XML
> 
>     // Only the 31 values in the whitelist should be present, the rest are ignored.
>     assert_eq!(versioned_constants.os_constants.gas_costs.len(), 31);
> ```

No point in tracking the number, now that it has a high-level meaning which is self-documenting.
(Perhaps the name of the const should change to something that explains that this isn't just _allowed_ but 



_Suggestion:_
```XML
    assert_eq!(versioned_constants.os_constants.gas_costs.len(), ALLOWED_GAS_COST_NAMES.len());
```


<!-- Sent from Reviewable.io -->

2024-03-09 18:21 UTC, OriStarkware reviewed
Yes, this test will fail when I change OSConstants to a struct in a future PR. I am fixing it in advance.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-:-NsHcbao1a-uDmrTDW3c:bn0jnfo)* status: 0 of 2 files reviewed, 10 unresolved discussions (waiting on @barak-b-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 345 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDcRB20F-6DKvXpHYT:-NsHbMy76zGvHoSDmxTQ:b-f6q3x5) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/test_utils.rs#L345)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Which argument will not match the `(serde_json::Value::Object(base_map), serde_json::Value::Object(update_map))` pattern? or in which case it happens?
</blockquote></details>

When one of the arguments is not a valid json.
___
*[`crates/blockifier/src/test_utils.rs` line 349 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDdt4V1bDOia7mBDC-:-NsHgf8wBSgFxsaY_8g7:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/test_utils.rs#L349)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

WDYT about: (see [comment](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDe58W-MLcxZj-DwpL) below)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDlInh-IOS_52XKSLs:-NsHc0HCDgoZuu5-RUjJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L8)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Something like:
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDlY8C3gDr2DrxCYld:-NsHc8xY3FswGznwMKrH:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L9)):*
> ```XML
> 
> fn fill_and_load_os_constants(json_data: &str) -> Result<Arc<OSConstants>, OsConstantsSerdeError> {
>     let json_value: Value =
> ```

Done.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDlb0RCyBiAgtJku5z:-NsHcKO08q6wVxXnZL9J:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L10)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

AFAIK the convention in tests is to use unwraps, do you think it's better to use `expect(...)` here?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDlgBg6SuX7YVPSxe1:-NsHcY0r2zc1nmYEonSP:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L15)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

AFAIK the convention in tests is to use unwraps, do you think it's better to use `expect(...)` here?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDe58W-MLcxZj-DwpL:-NsHghSVA7f76u3qbtwJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L17)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Since the `update_json_value` only does 'map.extend(map)` I think this line should be replaced by that. 

If you think otherwise, in order to make the comment above work, you need to move ownership:
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDdyKB9VQF_U0Til7X:-NsZQiQj--f62Nd6qBU1:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L20)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

String manipulation is too flakey in most cases, also complicated to follow, best to avoid it unless absolutely necessary.

Add `create_for_testing` into both `VersionedConstants` and `OsConstants` (with cfg testing/test, like in other `create_for_testing` we have) where the former uses the latter --- this also aligns better with our testing constructors for other types.

The os constants' one should be something like
```rust
fn create_for_testing(subset_of_os_constants: HashMap) -> Osconstants
DEFAULT_VERSIONED_CONSTANTS.os_constants.clone().extend(serde_json::from_str(subset_of_os_constants)
```
(note that cloning the struct should be roughly the same complexity as creating the `default_versioned_constants` below, so complexity should remain similar
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsCy0-W-OIFaQxHNrLN:-NsIp0KY9WBqDUc6Svcv:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L23)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I nameed this test badly, it should be "test_successful_os_resources_parsing_algorithm" or something to that effect, it is meant to showcase a simple successful parsing of the os constants (it should complement the documentation, in other words).

So I think it should stay, it shouldn't be affected by the representation of the constants as a struct, only the parsing of the JSON (IIUYC)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDjJSl5jAy1R7klx5p:-NsIovXn0JJY2LKguu-B:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L49)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

No point in tracking the number, now that it has a high-level meaning which is self-documenting.
(Perhaps the name of the const should change to something that explains that this isn't just _allowed_ but
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-10 08:17 UTC, OriStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 345 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDcRB20F-6DKvXpHYT:-NsbQTLIA07iZiOsLzBT:b-ffia6v) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/test_utils.rs#L345)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

In this case, don't you want to return some error?
</blockquote></details>

Correcting myself, the other case is when the json contains different types of keys.


<!-- Sent from Reviewable.io -->

2024-03-10 08:18 UTC, barak-b-starkware commented
*[`crates/blockifier/src/test_utils.rs` line 345 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDcRB20F-6DKvXpHYT:-NsbR6Br6dNSEIb9Rs56:b-816r98) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/test_utils.rs#L345)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Correcting myself, the other case is when the json contains different types of keys.
</blockquote></details>

Something like:
```
    match base.as_object_mut() {
        Some(d) => d.extend(*update.as_object().unwrap()),
        None => Some error...
    }
```


<!-- Sent from Reviewable.io -->

2024-03-10 09:43 UTC, OriStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 345 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsDcRB20F-6DKvXpHYT:-NsbjmuX-7uXNIyJpet9:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/test_utils.rs#L345)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Something like:
```
    match base.as_object_mut() {
        Some(d) => d.extend(*update.as_object().unwrap()),
        None => Some error...
    }
```
</blockquote></details>

Done
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 16 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsbKICbEoOV6gieUdG9:-NsbSaoj7iOTsVaKR400:bnqwr5j) ([raw file](https://github.com/starkware-libs/blockifier/blob/a4f51de0776333a15f6b588305e446057ec856e4/crates/blockifier/src/versioned_constants_test.rs#L16)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Out of curiosity, did you consider updating the struct `OSConstants` with some method? (and not to update the JSONs themselves) It might be safer?
</blockquote></details>

It will be too complicated for testing.


<!-- Sent from Reviewable.io -->

2024-03-10 12:33 UTC, barak-b-starkware requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase, @noaov1, and @OriStarkware)

___
*[`-- commits` line 8 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NscKqD346C5sqUcgWcl):*
Why do you split the work into two different commits?



_Code quote:_
```
New commits in r5 (same as r3) on 09/03/2024 at 20:25, probably rebased from r2:
- a579101: refactor: fill os_constants in test_successful_parsing

New commits in r6 on 10/03/2024 at 11:43, probably rebased from r4:
- d7a2425: refactor: fill os_constants in test_successful_parsing, pr fixes
```


<!-- Sent from Reviewable.io -->

2024-03-11 09:18 UTC, barak-b-starkware commented
*[`crates/blockifier/src/versioned_constants_test.rs` line 9 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsgnXEXEe3oxlwkW1-t:-NsgnXEXEe3oxlwkW1-u:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7a2425fcff34023646b44b6825aedc4f841ba64/crates/blockifier/src/versioned_constants_test.rs#L9)):*
> ```XML
> 
> impl OSConstants {
>     fn create_for_testing(subset_of_os_constants: &str) -> OSConstants {
> ```





_Suggestion:_
```XML
fn create_from_subset(subset_of_os_constants: &str) -> OSConstants {
```


<!-- Sent from Reviewable.io -->

2024-03-11 09:19 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants_test.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsCy0-W-OIFaQxHNrLN:-NsgnfroDBa4KPnyzG_C:b-yfyq7h) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L23)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What was done here at the end? did you change something?


<!-- Sent from Reviewable.io -->

2024-03-11 09:42 UTC, OriStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/versioned_constants_test.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsCy0-W-OIFaQxHNrLN:-NsgsBoiCDhH8bUyHrVb:bkahroq) ([raw file](https://github.com/starkware-libs/blockifier/blob/867956eda63599f84198b8cf2340244a0326e67f/crates/blockifier/src/versioned_constants_test.rs#L23)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

What was done here at the end? did you change something?
</blockquote></details>

No, I agree with Gilad that it should stay and that there is nothing else to do.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 9 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsgnXEXEe3oxlwkW1-t:-NsgszjyBtYHGooGHOVY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7a2425fcff34023646b44b6825aedc4f841ba64/crates/blockifier/src/versioned_constants_test.rs#L9)):*
> ```XML
> 
> impl OSConstants {
>     fn create_for_testing(subset_of_os_constants: &str) -> OSConstants {
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-03-11 11:12 UTC, barak-b-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-:-NshCbDu9eWbf6jcKTgI:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @noaov1)



<!-- Sent from Reviewable.io -->

2024-03-11 12:30 UTC, barak-b-starkware requested changes
> Reviewed 3 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: 3 of 4 files reviewed, 9 unresolved discussions (waiting on @giladchase, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/utils.rs` line 46 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NshUNDqBPtW5VmbC0kK:-NshUNDqBPtW5VmbC0kL:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/69bfa16c028583090d79a097ee7adc65764ef087/crates/blockifier/src/utils.rs#L46)):*
> ```XML
>         _ => panic!("Both base and update should be of type serde_json::Value::Object."),
>     }
> }
> ```





_Suggestion:_
```XML
pub fn update_json_value(base: &mut serde_json::Value, update: serde_json::Value) -> ResultSomething {
    match (base, update) {
        (serde_json::Value::Object(base_map), serde_json::Value::Object(update_map)) => {
            base_map.extend(update_map);
        }
        _ => not panic outside of tests,
    }
}
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 24 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NshTFIj4hB1-Ro5NbRk:-NshTFIj4hB1-Ro5NbRl:b-oavmwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/69bfa16c028583090d79a097ee7adc65764ef087/crates/blockifier/src/versioned_constants.rs#L24)):*
> ```XML
> use crate::transaction::transaction_types::TransactionType;
> #[cfg(test)]
> use crate::utils::update_json_value;
> ```

See comment below.
___
*[`crates/blockifier/src/versioned_constants.rs` line 453 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NshU1_u8bIIGhXnRYEk:-NshU1_v2PHn_8aVRoDA:bvfagxu) ([raw file](https://github.com/starkware-libs/blockifier/blob/69bfa16c028583090d79a097ee7adc65764ef087/crates/blockifier/src/versioned_constants.rs#L453)):*
> ```XML
> 
>     #[cfg(test)]
>     fn create_from_subset(subset_of_os_constants: &str) -> OSConstants {
> ```

Return some result (maybe there exists one in this file)



_Code quote:_
```XML
fn create_from_subset(subset_of_os_constants: &str) -> OSConstants {
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 454 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NshTd5g5FyzsmpY1d_5:-NshTd5g5FyzsmpY1d_6:b-anlxqz) ([raw file](https://github.com/starkware-libs/blockifier/blob/69bfa16c028583090d79a097ee7adc65764ef087/crates/blockifier/src/versioned_constants.rs#L454)):*
> ```XML
>     #[cfg(test)]
>     fn create_from_subset(subset_of_os_constants: &str) -> OSConstants {
>         let subset_of_os_constants: Value = serde_json::from_str(subset_of_os_constants).unwrap();
> ```

Something like with (`VersionedConstantsError`)



_Suggestion:_
```XML
let subset_of_os_constants: Value = match { Some(...) => ..., None => Err(..) };
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 461 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NshUGRzBGdApdTFhAz3:-NshUGRzBGdApdTFhAz4:b2nreh6) ([raw file](https://github.com/starkware-libs/blockifier/blob/69bfa16c028583090d79a097ee7adc65764ef087/crates/blockifier/src/versioned_constants.rs#L461)):*
> ```XML
>             .clone();
>         update_json_value(&mut os_constants, subset_of_os_constants);
>         let os_constants: OSConstants = serde_json::from_value(os_constants).unwrap();
> ```

Same as above.



_Suggestion:_
```XML
let os_constants: OSConstants = serde_json::from_value(os_constants);
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 463 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NshT1DV9YCn1J55nRFt:-NshT1DV9YCn1J55nRFu:bru2qif) ([raw file](https://github.com/starkware-libs/blockifier/blob/69bfa16c028583090d79a097ee7adc65764ef087/crates/blockifier/src/versioned_constants.rs#L463)):*
> ```XML
>         let os_constants: OSConstants = serde_json::from_value(os_constants).unwrap();
>         os_constants
>     }
> ```

I think the following is better (and also consistent with the other examples you've already inserted in this repo)



_Suggestion:_
```XML
    #[cfg(test)]
    fn create_from_subset(subset_of_os_constants: &str) -> OSConstants {
        use crate::utils::update_json_value;

        let subset_of_os_constants: Value = serde_json::from_str(subset_of_os_constants).unwrap();
        let mut os_constants: Value = serde_json::from_str::<Value>(DEFAULT_CONSTANTS_JSON)
            .unwrap()
            .get("os_constants")
            .unwrap()
            .clone();
        update_json_value(&mut os_constants, subset_of_os_constants);
        let os_constants: OSConstants = serde_json::from_value(os_constants).unwrap();
        os_constants
    }
```


<!-- Sent from Reviewable.io -->

2024-03-11 15:14 UTC, OriStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @barak-b-starkware and @giladchase)

___
*[`crates/blockifier/src/utils.rs` line 46 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NshUNDqBPtW5VmbC0kK:-NshyV7u7OFGv7vUi83c:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/69bfa16c028583090d79a097ee7adc65764ef087/crates/blockifier/src/utils.rs#L46)):*
> ```XML
>         _ => panic!("Both base and update should be of type serde_json::Value::Object."),
>     }
> }
> ```

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 24 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NshTFIj4hB1-Ro5NbRk:-NshyjSeE6p1ZdCdDY26:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/69bfa16c028583090d79a097ee7adc65764ef087/crates/blockifier/src/versioned_constants.rs#L24)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

See comment below.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 453 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NshU1_u8bIIGhXnRYEk:-Nsi-la76znxbk1NI-mf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/69bfa16c028583090d79a097ee7adc65764ef087/crates/blockifier/src/versioned_constants.rs#L453)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Return some result (maybe there exists one in this file)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 454 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NshTd5g5FyzsmpY1d_5:-Nsi1wEL0sQ0yBzkQYjt:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/69bfa16c028583090d79a097ee7adc65764ef087/crates/blockifier/src/versioned_constants.rs#L454)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Something like with (`VersionedConstantsError`)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 461 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NshUGRzBGdApdTFhAz3:-Nsi3oyb6M-bvIOxOfvG:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/69bfa16c028583090d79a097ee7adc65764ef087/crates/blockifier/src/versioned_constants.rs#L461)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 463 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NshT1DV9YCn1J55nRFt:-Nsi24hP9oAxkvqpe9w1:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/69bfa16c028583090d79a097ee7adc65764ef087/crates/blockifier/src/versioned_constants.rs#L463)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I think the following is better (and also consistent with the other examples you've already inserted in this repo)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-12 12:17 UTC, barak-b-starkware requested changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: all files reviewed, 6 unresolved discussions (waiting on @giladchase, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/utils.rs` line 14 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsmYbYQDxWqiAd8jo0y:-NsmYbYQDxWqiAd8jo0z:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/37c939c174f4622bca4bd8199f0d796844d2f8bd/crates/blockifier/src/utils.rs#L14)):*
> ```XML
> pub enum UtilsError {
>     #[error("Invalid JSON as an input")]
>     InvalidJSONObject,
> ```





_Suggestion:_
```XML
    #[error("Input should be of type serde_json::Value::Object")]
    InvalidJSONValue,
```
___
*[`crates/blockifier/src/utils.rs` line 46 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsmVuFy6I3bkJySy6gZ:-NsmVuFy6I3bkJySy6g_:buexxt1) ([raw file](https://github.com/starkware-libs/blockifier/blob/37c939c174f4622bca4bd8199f0d796844d2f8bd/crates/blockifier/src/utils.rs#L46)):*
> ```XML
> }
> 
> /// Update the `base` json's values with the values of the `update` json.
> ```

I think it's clear from the function names and arguments. WDYT?
___
*[`crates/blockifier/src/versioned_constants.rs` line 454 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsmZg0n2w4jO9f2WpzA:-NsmZg0o0AuX8AGnrIsu:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/37c939c174f4622bca4bd8199f0d796844d2f8bd/crates/blockifier/src/versioned_constants.rs#L454)):*
> ```XML
>     fn create_from_subset(
>         subset_of_os_constants: &str,
>     ) -> Result<OSConstants, VersionedConstantsError> {
> ```





_Suggestion:_
```XML
) -> Result<OSConstants, OsConstantsSerdeError> {
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 581 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-Nsm_EQ19EAwSDT0Fd__:-Nsm_EQ19EAwSDT0Fd_a:bt5ivfz) ([raw file](https://github.com/starkware-libs/blockifier/blob/37c939c174f4622bca4bd8199f0d796844d2f8bd/crates/blockifier/src/versioned_constants.rs#L581)):*
> ```XML
>     ParseError(#[from] serde_json::Error),
>     #[error("VersionedConstants must include OSConstants")]
>     MissingOSConstants,
> ```

Nice (: change the order (alphabetize)



_Suggestion:_
```XML
    #[error("VersionedConstants must include OSConstants")]
    MissingOSConstants,
    #[error("JSON file cannot be serialized into VersionedConstants: {0}")]
    ParseError(#[from] serde_json::Error),
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 603 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-Nsm_df5Bu8Bc_m05PQ6:-Nsm_df5Bu8Bc_m05PQ7:b67bvgt) ([raw file](https://github.com/starkware-libs/blockifier/blob/37c939c174f4622bca4bd8199f0d796844d2f8bd/crates/blockifier/src/versioned_constants.rs#L603)):*
> ```XML
>     #[error("Validation failed: {0}")]
>     ValidationError(String),
> }
> ```

please also change the `OsConstants..` to `OSConstants..` everywhere (maybe pr8)



_Suggestion:_
```XML
}

#[derive(Debug, Error)]
pub enum OSConstantsSerdeError {
    #[error("Value cannot be cast into u64: {0}")]
    InvalidFactorFormat(Value),
    #[error(transparent)]
    InvalidJSONValue(#[from] utils::UtilsError),
    #[error("Unknown key '{inner_key}' used to create value for '{key}'")]
    KeyNotFound { key: String, inner_key: String },
    #[error("Value {value} for key '{key}' is out of range and cannot be cast into u64")]
    OutOfRange { key: String, value: Number },
    #[error(
        "Value {value} used to create value for key '{key}' is out of range and cannot be cast \
         into u64"
    )]
    OutOfRangeFactor { key: String, value: Value },
    #[error("Unhandled value type: {0}")]
    UnhandledValueType(Value),
    #[error("Validation failed: {0}")]
    ValidationError(String),
}
```


<!-- Sent from Reviewable.io -->

2024-03-12 12:41 UTC, OriStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/utils.rs` line 14 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsmYbYQDxWqiAd8jo0y:-Nsme1Ip7s4S27fJVSlW:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/37c939c174f4622bca4bd8199f0d796844d2f8bd/crates/blockifier/src/utils.rs#L14)):*
> ```XML
> pub enum UtilsError {
>     #[error("Invalid JSON as an input")]
>     InvalidJSONObject,
> ```

Done.
___
*[`crates/blockifier/src/utils.rs` line 46 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsmVuFy6I3bkJySy6gZ:-NsmeEIQDzp_LtALWH_s:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/37c939c174f4622bca4bd8199f0d796844d2f8bd/crates/blockifier/src/utils.rs#L46)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I think it's clear from the function names and arguments. WDYT?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 454 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsmZg0n2w4jO9f2WpzA:-NsmeZ3ZAgakHtznKZ_6:b-e4bhtv) ([raw file](https://github.com/starkware-libs/blockifier/blob/37c939c174f4622bca4bd8199f0d796844d2f8bd/crates/blockifier/src/versioned_constants.rs#L454)):*
> ```XML
>     fn create_from_subset(
>         subset_of_os_constants: &str,
>     ) -> Result<OSConstants, VersionedConstantsError> {
> ```

I disagree. This function can throw `VersionedConstantsError::MissingOSConstants` as an error which is not a n`OsConstantsSerdeError`.
___
*[`crates/blockifier/src/versioned_constants.rs` line 603 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-Nsm_df5Bu8Bc_m05PQ6:-NsmfM8e-F9_C6pZqlrm:b-w7w21z) ([raw file](https://github.com/starkware-libs/blockifier/blob/37c939c174f4622bca4bd8199f0d796844d2f8bd/crates/blockifier/src/versioned_constants.rs#L603)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

please also change the `OsConstants..` to `OSConstants..` everywhere (maybe pr8)
</blockquote></details>

I will do it in PR8 after we finish with the current 7


<!-- Sent from Reviewable.io -->

2024-03-12 13:29 UTC, barak-b-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-:-NsmqeA47P8ou3DQSZ3P:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 454 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsmZg0n2w4jO9f2WpzA:-NsmqRuZCepiP508Y6nt:b-83tbtb) ([raw file](https://github.com/starkware-libs/blockifier/blob/37c939c174f4622bca4bd8199f0d796844d2f8bd/crates/blockifier/src/versioned_constants.rs#L454)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

I disagree. This function can throw `VersionedConstantsError::MissingOSConstants` as an error which is not a n`OsConstantsSerdeError`.
</blockquote></details>

OK (:


<!-- Sent from Reviewable.io -->

2024-03-12 15:57 UTC, barak-b-starkware commented
*[`crates/blockifier/src/versioned_constants.rs` line 584 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsnNG_e6qktYILfg1a8:-NsnNG_e6qktYILfg1a9:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/79abcc05897aa2dee6dd71bc9257253e575b1b05/crates/blockifier/src/versioned_constants.rs#L584)):*
> ```XML
>     #[error(transparent)]
>     InvalidJSONValue(#[from] utils::UtilsError),
> }
> ```





_Suggestion:_
```XML
pub enum VersionedConstantsError {
    #[error(transparent)]
    InvalidJSONValue(#[from] utils::UtilsError),
    #[error(transparent)]
    IoError(#[from] io::Error),
    #[error("VersionedConstants must include OSConstants")]
    MissingOSConstants,
    #[error("JSON file cannot be serialized into VersionedConstants: {0}")]
    ParseError(#[from] serde_json::Error),
}
```


<!-- Sent from Reviewable.io -->

2024-03-13 09:33 UTC, OriStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 584 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsnNG_e6qktYILfg1a8:-Nsr9CSrAsyRfBPX5VWX:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/79abcc05897aa2dee6dd71bc9257253e575b1b05/crates/blockifier/src/versioned_constants.rs#L584)):*
> ```XML
>     #[error(transparent)]
>     InvalidJSONValue(#[from] utils::UtilsError),
> }
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-03-13 11:21 UTC, barak-b-starkware requested changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 584 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsrXNH18gK4KH3GNTaL:-NsrXNH18gK4KH3GNTaM:bpl6tz1) ([raw file](https://github.com/starkware-libs/blockifier/blob/40d84a704e1bd579aef3fa66c5a27520133dd84c/crates/blockifier/src/versioned_constants.rs#L584)):*
> ```XML
>     #[error("JSON file cannot be serialized into VersionedConstants: {0}")]
>     ParseError(#[from] serde_json::Error),
> }
> ```

At the beginning of the file: `use crate::utils::UtilsError`.
(sorry, I missed it in the previous comment, we don't use the transparent mechanism for specific variants)



_Suggestion:_
```XML
pub enum VersionedConstantsError {
    #[error(transparent)]
    IoError(#[from] io::Error),
    #[error("VersionedConstants must include OSConstants")]
    MissingOSConstants,
    #[error("JSON file cannot be serialized into VersionedConstants: {0}")]
    ParseError(#[from] serde_json::Error),
    #[error(transparent)]
    UtilsError(#[from] UtilsError),
}
```


<!-- Sent from Reviewable.io -->

2024-03-13 14:59 UTC, OriStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 584 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NsrXNH18gK4KH3GNTaL:-NssJrQY41ztUf5dIfIm:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/40d84a704e1bd579aef3fa66c5a27520133dd84c/crates/blockifier/src/versioned_constants.rs#L584)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

At the beginning of the file: `use crate::utils::UtilsError`.
(sorry, I missed it in the previous comment, we don't use the transparent mechanism for specific variants)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-13 15:10 UTC, barak-b-starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-:-NssM5fh05gpjsBC3EC0:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @noaov1)



<!-- Sent from Reviewable.io -->

2024-03-21 14:23 UTC, noaov1 requested changes
> Reviewed 1 of 4 files at r8, 1 of 3 files at r9, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: all files reviewed, 9 unresolved discussions (waiting on @giladchase and @OriStarkware)

___
*[`crates/blockifier/src/utils.rs` line 46 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NtW-wuM6N-JJhrtT4Ef:-NtW-wuM6N-JJhrtT4Eg:bsyts4g) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b3f0926d254bf4e8edb7f418a30afc3e5eb34e0/crates/blockifier/src/utils.rs#L46)):*
> ```XML
> }
> 
> pub fn update_json_value(
> ```

Is it used in a non-test methods?



_Code quote:_
```XML
pub fn update_json_value(
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 490 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NtVwnxADjmfzioAnZTp:-NtVwnxADjmfzioAnZTq:barlf44) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b3f0926d254bf4e8edb7f418a30afc3e5eb34e0/crates/blockifier/src/versioned_constants.rs#L490)):*
> ```XML
> 
>     #[cfg(test)]
>     fn create_from_subset(
> ```

Consider defining it as method for `OSConstants` in the file `structs_impls.rs` (see other `create_for_testing` methods).



_Suggestion:_
```XML
    fn create_for_testing(
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 492 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NtVvarc8-u8hlP0dje_:-NtVvarc8-u8hlP0djea:b-25lfnn) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b3f0926d254bf4e8edb7f418a30afc3e5eb34e0/crates/blockifier/src/versioned_constants.rs#L492)):*
> ```XML
>     fn create_from_subset(
>         subset_of_os_constants: &str,
>     ) -> Result<OSConstants, VersionedConstantsError> {
> ```

If it used in tests only, no need to return a result, we can just panic.



_Suggestion:_
```XML
) -> Self {
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 493 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NtVUPFG77x8MQYcuuYX:-NtVUPFG77x8MQYcuuYY:b-qp2bgu) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b3f0926d254bf4e8edb7f418a30afc3e5eb34e0/crates/blockifier/src/versioned_constants.rs#L493)):*
> ```XML
>         subset_of_os_constants: &str,
>     ) -> Result<OSConstants, VersionedConstantsError> {
>         use crate::utils::update_json_value;
> ```

Why here?



_Code quote:_
```XML
        use crate::utils::update_json_value;
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 502 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NtVzQ7T0lzB5a2TSEGg:-NtVzQ7T0lzB5a2TSEGh:bl6ac4t) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b3f0926d254bf4e8edb7f418a30afc3e5eb34e0/crates/blockifier/src/versioned_constants.rs#L502)):*
> ```XML
>         update_json_value(&mut os_constants, subset_of_os_constants)?;
>         let os_constants: OSConstants = serde_json::from_value(os_constants)?;
>         Ok(os_constants)
> ```

Is it working?
Will it be problematic since we change the `gas_costs` to a struct?
If so, this should become a method of `GasCost` (that may need some changes)



_Suggestion:_
```XML
        let mut os_constants = DEFAULT_CONSTANTS.os_constants.clone();
        os_constants.gas_costs.extend(serde_json::from_str(subset_of_os_constants));
        
        Ok(os_constants)
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 617 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NtVw06m97yci0xR9UVs:-NtVw06m97yci0xR9UVt:b7qomp1) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b3f0926d254bf4e8edb7f418a30afc3e5eb34e0/crates/blockifier/src/versioned_constants.rs#L617)):*
> ```XML
>     IoError(#[from] io::Error),
>     #[error("VersionedConstants must include OSConstants")]
>     MissingOSConstants,
> ```

Where is it used?



_Code quote:_
```XML
    #[error("VersionedConstants must include OSConstants")]
    MissingOSConstants,
```
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 8 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NtVyChwCURYyWBujf4l:-NtVyChwCURYyWBujf4m:b2nhkyh) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b3f0926d254bf4e8edb7f418a30afc3e5eb34e0/crates/blockifier/src/versioned_constants_test.rs#L8)):*
> ```XML
> 
> #[test]
> fn test_successful_parsing() {
> ```

No?



_Suggestion:_
```XML
fn test_successful_gas_constants_parsing() {
```


<!-- Sent from Reviewable.io -->

2024-03-21 16:04 UTC, barak-b-starkware commented
*[`crates/blockifier/src/versioned_constants.rs` line 490 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NtVwnxADjmfzioAnZTp:-NtWjXvT8-wIag6NC99T:b-r6kkvt) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b3f0926d254bf4e8edb7f418a30afc3e5eb34e0/crates/blockifier/src/versioned_constants.rs#L490)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider defining it as method for `OSConstants` in the file `structs_impls.rs` (see other `create_for_testing` methods).
</blockquote></details>

I suggested `create_from_subset` since it's not a classic `create_for_testing` use case. It has some non-mandatory argument to initialize it so I thought that the function name should be more explanatory.
A `create_for_testing` method implies some default behavior, which isn't necessarily the case here and might be needed in the future. Anyway, `create_for_testing` is also fine by me (:


<!-- Sent from Reviewable.io -->

2024-03-23 20:23 UTC, noaov1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: all files reviewed, 9 unresolved discussions (waiting on @barak-b-starkware, @giladchase, and @OriStarkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 490 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NtVwnxADjmfzioAnZTp:-NtgwNWQB9P6GEfTs6kv:b-42fyc1) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b3f0926d254bf4e8edb7f418a30afc3e5eb34e0/crates/blockifier/src/versioned_constants.rs#L490)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I suggested `create_from_subset` since it's not a classic `create_for_testing` use case. It has some non-mandatory argument to initialize it so I thought that the function name should be more explanatory.
A `create_for_testing` method implies some default behavior, which isn't necessarily the case here and might be needed in the future. Anyway, `create_for_testing` is also fine by me (:
</blockquote></details>

I see.
Note, it is not created from the subset itself, but rather the subset values overrides the default values (which used in tests).
You can name it `create_for_testing_from_subset`


<!-- Sent from Reviewable.io -->

2024-03-25 14:22 UTC, OriStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: all files reviewed, 6 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 490 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NtVwnxADjmfzioAnZTp:-Ntpr8HKBiyQKqs3UKXE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b3f0926d254bf4e8edb7f418a30afc3e5eb34e0/crates/blockifier/src/versioned_constants.rs#L490)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I see.
Note, it is not created from the subset itself, but rather the subset values overrides the default values (which used in tests).
You can name it `create_for_testing_from_subset`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 492 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NtVvarc8-u8hlP0dje_:-NtprAkfE_aQ6TDivwq9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b3f0926d254bf4e8edb7f418a30afc3e5eb34e0/crates/blockifier/src/versioned_constants.rs#L492)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

If it used in tests only, no need to return a result, we can just panic.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 8 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NtVyChwCURYyWBujf4l:-NtpygN5DnYO503qSjwV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b3f0926d254bf4e8edb7f418a30afc3e5eb34e0/crates/blockifier/src/versioned_constants_test.rs#L8)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

No?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-26 07:08 UTC, noaov1 approved these changes
> Reviewed 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase and @OriStarkware)

___
*[`crates/blockifier/src/utils.rs` line 15 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1615#-NttVucs9PHpfvVLGjQj:-NttVucs9PHpfvVLGjQk:ba3dfna) ([raw file](https://github.com/starkware-libs/blockifier/blob/c0c53d3265ffdcdba575b1b81c2380fc16af86ae/crates/blockifier/src/utils.rs#L15)):*
> ```XML
>     #[error("Input should be of type serde_json::Value::Object")]
>     InvalidJSONValue,
> }
> ```

Remove?



_Code quote:_
```XML
#[derive(Debug, Error)]
pub enum UtilsError {
    #[error("Input should be of type serde_json::Value::Object")]
    InvalidJSONValue,
}
```


<!-- Sent from Reviewable.io -->

2024-03-26 07:33 UTC, noaov1 approved these changes
> Reviewed 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @giladchase and @OriStarkware)



<!-- Sent from Reviewable.io -->

2024-03-26 07:50 UTC, noaov1 approved these changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-03-26 08:14 UTC, noaov1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1615)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2024-03-26 11:55 UTC, merged