reformat(execution): bouncer update function
starkware-libs/blockifier pull request #1644
Opened 2024-03-07 09:22 UTC by Yael-Starkware

2024-03-18 06:50 UTC, Yael-Starkware reviewed
Context:  
This PR contains the high level parts of the update flow of the bouncer, and is the most loaded I think and apologize.
The bouncer update function (previously known as add() in python) will proceed in the following steps:

1.  update_auxiliary_info
2.  update_capacity (BouncerWeights)  
    a. get_tx_weights  
    b. check if keccak was used and update the capacity accordingly  
    c. check if the tx is too big to fit any batch, if so ->error
    d. try to update the bouncer by subtracting the tx_weights  
       if succeeds -> commit the new values, OK  
       else -> keep the old bouncer values, Error

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-:-NtFJE9aBBeVEOqPaEOx:bmhxycc)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @ayeletstarkware, @noaov1, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-03-18 07:03 UTC, Yael-Starkware reviewed
The logic here should be the same as the logic of the python bouncer add() function.
The only logic that remains in the python bouncer is the logic that handles time : The logic that check that each that lifespan hasn't passed since the oldest transaction arrived to the system and the logic that limits the block creation rate.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-:-NtFMGvJ2d-b01Ze56LD:b-7lv60t)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-03-19 07:48 UTC, ArniStarkware requested changes
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 1 of 4 files reviewed, 8 unresolved discussions (waiting on @noaov1, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 139 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtKWbeR0U9kvSNav9al:-NtKWbeR0U9kvSNav9am:b-7zi8ni) ([raw file](https://github.com/starkware-libs/blockifier/blob/a9602c92f8a35a5283359035d68144d5083be560/crates/blockifier/src/bouncer.rs#L139)):*
> ```XML
>             block_contains_keccak,
>         }
>     }
> ```

WDYT?



_Suggestion:_
```XML
    pub fn new(available_capacity: BouncerWeights, block_contains_keccak: bool) -> Self {
        Bouncer {
            executed_class_hashes: HashSet::new(),
            state_changes_keys: StateChangesKeys::default(),
            visited_storage_entries: HashSet::new(),
            available_capacity: capacity,
            block_contains_keccak,
        }
    }
```
___
*[`crates/blockifier/src/bouncer.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtKX9Q6A5F7cdNfZiJs:-NtKX9Q6A5F7cdNfZiJt:b-dmcpie) ([raw file](https://github.com/starkware-libs/blockifier/blob/a9602c92f8a35a5283359035d68144d5083be560/crates/blockifier/src/bouncer.rs#L160)):*
> ```XML
>     // The transaction bouncer can be modified only through the update method.
>     transactional: Bouncer,
> }
> ```

Transactional vs transactional_bouncer, I don't mind. Leaning towards the former.



_Suggestion:_
```XML
pub struct TransactionalBouncer {
    // The block bouncer can be modified only through the merge method.
    block_bouncer: Bouncer,
    // The transaction bouncer can be modified only through the update method.
    transactional: Bouncer,
}
```
___
*[`crates/blockifier/src/bouncer.rs` line 169 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtKXpXzCmHvzIdXoYNQ:-NtKXpXzCmHvzIdXoYNR:bu9soln) ([raw file](https://github.com/starkware-libs/blockifier/blob/a9602c92f8a35a5283359035d68144d5083be560/crates/blockifier/src/bouncer.rs#L169)):*
> ```XML
>     }
> 
>     pub fn update<S: StateReader>(
> ```

Document, please. In what context is this function called? also, the next function.



_Code quote:_
```XML
    pub fn update<S: StateReader>(
```
___
*[`crates/blockifier/src/bouncer.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtKdhMyAiJmYpbNvyfm:-NtKdhMyAiJmYpbNvyfn:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/a9602c92f8a35a5283359035d68144d5083be560/crates/blockifier/src/bouncer.rs#L189)):*
> ```XML
>     }
> 
>     fn update_capacity<S: StateReader>(
> ```

?



_Suggestion:_
```XML
fn update_available_capacity<S: StateReader>(
```
___
*[`crates/blockifier/src/bouncer.rs` line 206 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtKe3vGBWJVeuCQAj-g:-NtKe3vHA2eXSo2AcAZb:b-10tqvp) ([raw file](https://github.com/starkware-libs/blockifier/blob/a9602c92f8a35a5283359035d68144d5083be560/crates/blockifier/src/bouncer.rs#L206)):*
> ```XML
>         if !self.transactional.block_contains_keccak && tx_weights.builtin_count.keccak > 0 {
>             self.update_available_capacity_with_keccak(bouncer_config)?;
>         }
> ```

If it is true, please rephrase (and pass through Grammarly etc). 



_Suggestion:_
```XML
        if !self.transactional.block_contains_keccak && tx_weights.builtin_count.keccak > 0 {
            // This is update is the first update to contain keccak in this block.
            self.update_available_capacity_with_keccak(bouncer_config)?;
        }
```
___
*[`crates/blockifier/src/bouncer.rs` line 229 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtKedsW1zuXopi_XcHB:-NtKedsW1zuXopi_XcHC:bctez8z) ([raw file](https://github.com/starkware-libs/blockifier/blob/a9602c92f8a35a5283359035d68144d5083be560/crates/blockifier/src/bouncer.rs#L229)):*
> ```XML
>     ) -> TransactionExecutorResult<()> {
>         // First zero the keccak capacity to be able to subtract the max_capacity_with_keccak from
>         // max_capacity (that is without keccak).
> ```

You explain here that max_capacity is without keccak. This is because of the assumptions of when we call this function, is it?
If so - please document this in the tx's docstring under assumptions.

(Good job writing it out at all; it made it easy to review).



_Code quote:_
```XML
        // First zero the keccak capacity to be able to subtract the max_capacity_with_keccak from
        // max_capacity (that is without keccak).
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtKW1iG4WYpZDQLfPc0:-NtKW1iG4WYpZDQLfPc1:b-c0wg8f) ([raw file](https://github.com/starkware-libs/blockifier/blob/a9602c92f8a35a5283359035d68144d5083be560/crates/blockifier/src/transaction/errors.rs#L55)):*
> ```XML
> pub enum TransactionExecutionError {
>     #[error("Transaction cannot be added to the current block, block capacity reached.")]
>     BlockFull,
> ```

There should be a test for this scenario.



_Code quote:_
```XML
    #[error("Transaction cannot be added to the current block, block capacity reached.")]
    BlockFull,
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtKWBCt6lLceHxcOXHP:-NtKWBCu00BWfY3CqrZ2:b-c0wg8f) ([raw file](https://github.com/starkware-libs/blockifier/blob/a9602c92f8a35a5283359035d68144d5083be560/crates/blockifier/src/transaction/errors.rs#L91)):*
> ```XML
>     TryFromIntError(#[from] std::num::TryFromIntError),
>     #[error("Transaction size exceeds the maximum block capacity.")]
>     TxTooLarge,
> ```

There should be a test for this scenario.



_Code quote:_
```XML
    #[error("Transaction size exceeds the maximum block capacity.")]
    TxTooLarge,
```


<!-- Sent from Reviewable.io -->

2024-03-19 10:47 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 139 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtKWbeR0U9kvSNav9al:-NtLGrfZ85PGwu8Tc3gP:bba2h23) ([raw file](https://github.com/starkware-libs/blockifier/blob/a9602c92f8a35a5283359035d68144d5083be560/crates/blockifier/src/bouncer.rs#L139)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

agreed, done.
___
*[`crates/blockifier/src/bouncer.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtKX9Q6A5F7cdNfZiJs:-NtKg4PC4eH0UzorlsWF:bnlgjgo) ([raw file](https://github.com/starkware-libs/blockifier/blob/a9602c92f8a35a5283359035d68144d5083be560/crates/blockifier/src/bouncer.rs#L160)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Transactional vs transactional_bouncer, I don't mind. Leaning towards the former.
</blockquote></details>

Actually we already had this naming discussion , with both Yoni and Elin. So I prefer to keep the former. (though I also suggested to call it block :) )
___
*[`crates/blockifier/src/bouncer.rs` line 169 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtKXpXzCmHvzIdXoYNQ:-NtLGunp1AIZCcc1ZSnC:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/a9602c92f8a35a5283359035d68144d5083be560/crates/blockifier/src/bouncer.rs#L169)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Document, please. In what context is this function called? also, the next function.
</blockquote></details>

done.
___
*[`crates/blockifier/src/bouncer.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtKdhMyAiJmYpbNvyfm:-NtLHKWg0XK4vosGcotb:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/a9602c92f8a35a5283359035d68144d5083be560/crates/blockifier/src/bouncer.rs#L189)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

?
</blockquote></details>

done.
___
*[`crates/blockifier/src/bouncer.rs` line 206 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtKe3vGBWJVeuCQAj-g:-NtLHmfg7bxQ-iIemWu8:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a9602c92f8a35a5283359035d68144d5083be560/crates/blockifier/src/bouncer.rs#L206)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

If it is true, please rephrase (and pass through Grammarly etc).
</blockquote></details>

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 229 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtKedsW1zuXopi_XcHB:-NtLIeVUBCsr5h_0hiH-:bff6jn7) ([raw file](https://github.com/starkware-libs/blockifier/blob/a9602c92f8a35a5283359035d68144d5083be560/crates/blockifier/src/bouncer.rs#L229)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

You explain here that max_capacity is without keccak. This is because of the assumptions of when we call this function, is it?
If so - please document this in the tx's docstring under assumptions.

(Good job writing it out at all; it made it easy to review).
</blockquote></details>

Thanks.
Done.
not sure what you mean by the tx's docstring under assumptions, I hope I did it right.
___
*[`crates/blockifier/src/transaction/errors.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtKW1iG4WYpZDQLfPc0:-NtLIu259AH3TP7pE5HG:b-97x3or) ([raw file](https://github.com/starkware-libs/blockifier/blob/a9602c92f8a35a5283359035d68144d5083be560/crates/blockifier/src/transaction/errors.rs#L55)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

There should be a test for this scenario.
</blockquote></details>

Added a pretty comprehensive test now. Was indeed needed here. 
___
*[`crates/blockifier/src/transaction/errors.rs` line 91 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtKWBCt6lLceHxcOXHP:-NtLJ3BC6d_Dd5SQg6G_:bb73xfv) ([raw file](https://github.com/starkware-libs/blockifier/blob/a9602c92f8a35a5283359035d68144d5083be560/crates/blockifier/src/transaction/errors.rs#L91)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

There should be a test for this scenario.
</blockquote></details>

Same


<!-- Sent from Reviewable.io -->

2024-03-19 10:49 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 1 of 4 files reviewed, 8 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtLK1kVCWtQVUSD50Q1:-NtLK1kVCWtQVUSD50Q2:b1znur2) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfcd2fac439ac0eb6129aac4ad8d9bd0ad7a7d10/crates/blockifier/src/bouncer.rs#L74)):*
> ```XML
>     fn from(data: ExecutionResources) -> Self {
>         BouncerWeights {
>             n_steps: data.n_steps + data.n_memory_holes,
> ```

Changed this code since the ExecutionResources only contain hash resources.
double checking with @Yoni-Starkware that is makes sense.


<!-- Sent from Reviewable.io -->

2024-03-19 11:15 UTC, ArniStarkware requested changes
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @noaov1, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 240 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtLPZFx2tM1Ctlhnl48:-NtLPZFx2tM1Ctlhnl49:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfcd2fac439ac0eb6129aac4ad8d9bd0ad7a7d10/crates/blockifier/src/bouncer.rs#L240)):*
> ```XML
>     /// This function is called only if the block does not contain keccak yet.
>     /// Assumption: max_capacity without keccak is smaller than max_capacity with keccak and has
>     /// keccak capacity zero.
> ```





_Suggestion:_
```XML
    /// Assumption: the block does not contain keccak yet.
```


<!-- Sent from Reviewable.io -->

2024-03-19 12:07 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 240 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtLPZFx2tM1Ctlhnl48:-NtLb3M-EF-TfA4LHCOi:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfcd2fac439ac0eb6129aac4ad8d9bd0ad7a7d10/crates/blockifier/src/bouncer.rs#L240)):*
> ```XML
>     /// This function is called only if the block does not contain keccak yet.
>     /// Assumption: max_capacity without keccak is smaller than max_capacity with keccak and has
>     /// keccak capacity zero.
> ```

done.


<!-- Sent from Reviewable.io -->

2024-03-19 12:39 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @noaov1, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 264 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtLgJqW02W2JEWCglxR:-NtLgJqW02W2JEWCglxS:btl6aq0) ([raw file](https://github.com/starkware-libs/blockifier/blob/9636c7311362d1f9236ee46db62e2afd43176d41/crates/blockifier/src/bouncer.rs#L264)):*
> ```XML
>         self.transactional.block_contains_keccak = true;
>         Ok(())
>     }
> ```

Sorry for not suggesting this from the beginning.
How about something like this, and then call it another way?



_Suggestion:_
```XML
    /// Updates the available capacity in case until this moment the block did not contain keccak, and now it does.
    fn optionally_update_available_capacity_for_keccak(
        &mut self,
        bouncer_config: &BouncerConfig,
        keccak_builtin_counter: usize, //whatever should be here.
    ) -> TransactionExecutorResult<()> {
        if self.transactional.block_contains_keccak || keccak_builtin_counter == 0 {
            return Ok(());
        } // This is almost like an assert!(!self.transactional.block_contains_keccak && ...);
        
        // First zero the keccak capacity to be able to subtract the max_capacity_with_keccak from
        // max_capacity (that is without keccak).
        let mut max_capacity_with_keccak_tmp = bouncer_config.block_max_capacity_with_keccak;
        max_capacity_with_keccak_tmp.builtin_count.keccak = 0;
        // compute the diff between the max_capacity and the max_capacity_with_keccak.
        let max_capacity_with_keccak_diff = bouncer_config
            .block_max_capacity
            .checked_sub(max_capacity_with_keccak_tmp)
            .expect("max_capacity_with_keccak should be smaller than max_capacity");
        // Subtract the diff from the available capacity.
        self.transactional.available_capacity = self
            .transactional
            .available_capacity
            .checked_sub(max_capacity_with_keccak_diff)
            .ok_or(TransactionExecutionError::BlockFull)?;
        // Add back the keccack capacity that was reset at the beggining.
        self.transactional.available_capacity.builtin_count.keccak =
            bouncer_config.block_max_capacity_with_keccak.builtin_count.keccak;
        // Mark this block as contains keccak.
        self.transactional.block_contains_keccak = true;
        Ok(())
    }
```


<!-- Sent from Reviewable.io -->

2024-03-19 12:53 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 264 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtLgJqW02W2JEWCglxR:-NtLjsX45iX5Vy1U0bMW:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/9636c7311362d1f9236ee46db62e2afd43176d41/crates/blockifier/src/bouncer.rs#L264)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Sorry for not suggesting this from the beginning.
How about something like this, and then call it another way?
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2024-03-19 12:54 UTC, ArniStarkware commented
*[`crates/blockifier/src/bouncer.rs` line 264 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtLgJqW02W2JEWCglxR:-NtLlj0IB8Ugm8MRZl3x:b-vr4p06) ([raw file](https://github.com/starkware-libs/blockifier/blob/9636c7311362d1f9236ee46db62e2afd43176d41/crates/blockifier/src/bouncer.rs#L264)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

done.
</blockquote></details>

I don't see it.


<!-- Sent from Reviewable.io -->

2024-03-19 12:55 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 264 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtLgJqW02W2JEWCglxR:-NtLm2HVDgBav5OtFKxy:bdsmwef) ([raw file](https://github.com/starkware-libs/blockifier/blob/9636c7311362d1f9236ee46db62e2afd43176d41/crates/blockifier/src/bouncer.rs#L264)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I don't see it.
</blockquote></details>

oh sorry, now should be fine


<!-- Sent from Reviewable.io -->

2024-03-19 12:58 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 264 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtLgJqW02W2JEWCglxR:-NtLmf37-fZd57kuRggW:b-ttfhrn) ([raw file](https://github.com/starkware-libs/blockifier/blob/9636c7311362d1f9236ee46db62e2afd43176d41/crates/blockifier/src/bouncer.rs#L264)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Please update the docstring. There are no assumptions now :) They are enforced inside the first `if` :)
</blockquote></details>

oh shoot, missed it
done


<!-- Sent from Reviewable.io -->

2024-03-19 12:58 UTC, ArniStarkware commented
*[`crates/blockifier/src/bouncer.rs` line 238 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtLmXXD9KT4W_tLh5tb:-NtLmXXD9KT4W_tLh5tc:b1xpm9u) ([raw file](https://github.com/starkware-libs/blockifier/blob/58e1e632b7904bd3897e89129cf6230e5cd8a28a/crates/blockifier/src/bouncer.rs#L238)):*
> ```XML
>         &mut self,
>         tx_weights: &BouncerWeights,
>         bouncer_config: &BouncerConfig,
> ```

No need to pass all of the weights. Let us pass only what the function needs.



_Suggestion:_
```XML
    fn update_available_capacity_with_keccak_if_needed(
        &mut self,
        keccak_builtin_count: usize,
        bouncer_config: &BouncerConfig,
```


<!-- Sent from Reviewable.io -->

2024-03-19 13:01 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 238 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtLmXXD9KT4W_tLh5tb:-NtLnHUN5NUVa1dSlmKd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/58e1e632b7904bd3897e89129cf6230e5cd8a28a/crates/blockifier/src/bouncer.rs#L238)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

No need to pass all of the weights. Let us pass only what the function needs.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-19 13:10 UTC, ArniStarkware commented
*[`crates/blockifier/src/bouncer_test.rs` line 189 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtLolmc40EahD2W39no:-NtLolmc40EahD2W39np:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/58e1e632b7904bd3897e89129cf6230e5cd8a28a/crates/blockifier/src/bouncer_test.rs#L189)):*
> ```XML
>     bouncer_resources.insert(constants::L1_GAS_USAGE.to_string(), 1);
>     bouncer_resources.insert(constants::N_STEPS_RESOURCE.to_string(), 1);
>     bouncer_resources.insert(constants::N_MEMORY_HOLES.to_string(), 1);
> ```





_Suggestion:_
```XML
    let mut bouncer_resources: HashMap<String, usize> = HashMap::from([
    (BuiltinName::bitwise.name().to_string(), 1),
    (BuiltinName::ecdsa.name().to_string(), 1),
    (BuiltinName::ec_op.name().to_string(), 1),
    // Keccak is 0 since it has special handling, which will be tested separately.
    (BuiltinName::keccak.name().to_string(), 0), ...])
```


<!-- Sent from Reviewable.io -->

2024-03-19 13:31 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer_test.rs` line 189 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtLolmc40EahD2W39no:-NtLuGhE-5ZExF1C4bvO:b-4xv941) ([raw file](https://github.com/starkware-libs/blockifier/blob/58e1e632b7904bd3897e89129cf6230e5cd8a28a/crates/blockifier/src/bouncer_test.rs#L189)):*
> ```XML
>     bouncer_resources.insert(constants::L1_GAS_USAGE.to_string(), 1);
>     bouncer_resources.insert(constants::N_STEPS_RESOURCE.to_string(), 1);
>     bouncer_resources.insert(constants::N_MEMORY_HOLES.to_string(), 1);
> ```

Fully agree.
done.


<!-- Sent from Reviewable.io -->

2024-03-19 13:42 UTC, ArniStarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-:-NtLwfhXCKVDTH3Cqkqm:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-03-19 15:31 UTC, ArniStarkware submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-03-20 06:43 UTC, ArniStarkware approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-03-20 07:21 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtLK1kVCWtQVUSD50Q1:-NtPj1IF6zOGR_v2Z2MD:b-clbk22) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfcd2fac439ac0eb6129aac4ad8d9bd0ad7a7d10/crates/blockifier/src/bouncer.rs#L74)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Changed this code since the ExecutionResources only contain hash resources.
double checking with @Yoni-Starkware that is makes sense.
</blockquote></details>

Need to consider all builtins


<!-- Sent from Reviewable.io -->

2024-03-20 08:23 UTC, Yoni-Starkware requested changes
Wait

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-:-NtPxH7a5K7CFHfKrON9:bb76hay)* status: all files reviewed, 5 unresolved discussions (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 179 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtPqlObDe6iM56niryy:-NtPqlObDe6iM56niryz:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/998efdcaacd6d9099be183146e2a9534a70b8a06/crates/blockifier/src/bouncer.rs#L179)):*
> ```XML
>     }
> 
>     /// Updates the bouncer with a new transaction info and weights after execution.
> ```





_Suggestion:_
```XML
/// Updates the transactional bouncer.
```
___
*[`crates/blockifier/src/bouncer.rs` line 200 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtPqyBm6_ttkR4gYl_q:-NtPqyBm6_ttkR4gYl_r:bmjd38e) ([raw file](https://github.com/starkware-libs/blockifier/blob/998efdcaacd6d9099be183146e2a9534a70b8a06/crates/blockifier/src/bouncer.rs#L200)):*
> ```XML
>     }
> 
>     /// This function is called by the update function to update the bouncer capacity.
> ```

The function name is good enough
___
*[`crates/blockifier/src/bouncer.rs` line 219 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtPrER59Zh4xgDMekzE:-NtPrER59Zh4xgDMekzF:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/998efdcaacd6d9099be183146e2a9534a70b8a06/crates/blockifier/src/bouncer.rs#L219)):*
> ```XML
>             tx_weights.builtin_count.keccak,
>             bouncer_config,
>         )?;
> ```





_Suggestion:_
```XML
        if self.
        self.update_available_capacity_with_keccak_if_needed(
            tx_weights.builtin_count.keccak,
            bouncer_config,
        )?;
```
___
*[`crates/blockifier/src/transaction/errors.rs` line 95 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtPm0m1C4nfa28Ai8lL:-NtPm0m24F6M-T-3hhZ1:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/998efdcaacd6d9099be183146e2a9534a70b8a06/crates/blockifier/src/transaction/errors.rs#L95)):*
> ```XML
>     TryFromIntError(#[from] std::num::TryFromIntError),
>     #[error("Transaction size exceeds the maximum block capacity.")]
>     TxTooLarge,
> ```





_Suggestion:_
```XML
TransactionTooLarge,
```


<!-- Sent from Reviewable.io -->

2024-03-20 08:51 UTC, ArniStarkware commented
*[`crates/blockifier/src/bouncer.rs` line 219 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtPrER59Zh4xgDMekzE:-NtQ1xp_4vD4Jhi2xwZy:bxrsjbf) ([raw file](https://github.com/starkware-libs/blockifier/blob/998efdcaacd6d9099be183146e2a9534a70b8a06/crates/blockifier/src/bouncer.rs#L219)):*
> ```XML
>             tx_weights.builtin_count.keccak,
>             bouncer_config,
>         )?;
> ```

We had a discussion about it.
I suggested moving the checks inside the function. This design makes it so the function "update_available_capacity_with_keccak" has no assumptions on the time it is called. The assumptions are checked when you enter the function.

I see why it is less readable as is, but the alternative is also somewhat cumbersome.


<!-- Sent from Reviewable.io -->

2024-03-20 08:58 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: all files reviewed, 6 unresolved discussions (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 138 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtQ33OCDiR8FtOme_o_:-NtQ33OCDiR8FtOme_oa:bt87j6x) ([raw file](https://github.com/starkware-libs/blockifier/blob/998efdcaacd6d9099be183146e2a9534a70b8a06/crates/blockifier/src/bouncer.rs#L138)):*
> ```XML
>     // The capacity is calculated based of the values of the other Bouncer fields.
>     available_capacity: BouncerWeights,
> }
> ```

Suggestion



_Suggestion:_
```XML
#[derive(Clone, Default)]
pub struct Bouncer {
    pub executed_class_hashes: HashSet<ClassHash>,
    pub visited_storage_entries: HashSet<StorageEntry>,
    pub state_changes_keys: StateChangesKeys,
    // The capacity is calculated based of the values of the other Bouncer fields.
    bouncer_config: BouncerConfig,
    available_capacity: BouncerWeights,
}

fn try_update(...)
    // calc aux info
    // get tx weights
    // call try_add()
    // update aux info
    
fn try_add(...)
    // clone current capacity
    // add
    // according to keccak, check <= max
    // update current capacity
```


<!-- Sent from Reviewable.io -->

2024-03-20 08:59 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: all files reviewed, 6 unresolved discussions (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 138 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtQ33OCDiR8FtOme_o_:-NtQ4SeW5CkEj0psILlJ:b2m5bhg) ([raw file](https://github.com/starkware-libs/blockifier/blob/998efdcaacd6d9099be183146e2a9534a70b8a06/crates/blockifier/src/bouncer.rs#L138)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Suggestion
</blockquote></details>

(Use better names, `try_` is probably not needed)


<!-- Sent from Reviewable.io -->

2024-03-21 08:52 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: all files reviewed, 5 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtLK1kVCWtQVUSD50Q1:-NtVBxEIDgmXuxaznxvp:b-b22buw) ([raw file](https://github.com/starkware-libs/blockifier/blob/cfcd2fac439ac0eb6129aac4ad8d9bd0ad7a7d10/crates/blockifier/src/bouncer.rs#L74)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Need to consider all builtins
</blockquote></details>

ok, ass discussed I am using the regular from HashMap conversion with defaults instead of except()
___
*[`crates/blockifier/src/bouncer.rs` line 138 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtQ33OCDiR8FtOme_o_:-NtVBl0E09o7DbMhSPnv:bans9a0) ([raw file](https://github.com/starkware-libs/blockifier/blob/998efdcaacd6d9099be183146e2a9534a70b8a06/crates/blockifier/src/bouncer.rs#L138)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

(Use better names, `try_` is probably not needed)
</blockquote></details>

done. 
did not do exactly what you wrote here, but refactored in that spirit. let me know what you think.
___
*[`crates/blockifier/src/bouncer.rs` line 179 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtPqlObDe6iM56niryy:-NtVASiyDrRXcF4nWQan:blzmfag) ([raw file](https://github.com/starkware-libs/blockifier/blob/998efdcaacd6d9099be183146e2a9534a70b8a06/crates/blockifier/src/bouncer.rs#L179)):*
> ```XML
>     }
> 
>     /// Updates the bouncer with a new transaction info and weights after execution.
> ```

there is no transactional bouncer. But I shortened it a bit.
___
*[`crates/blockifier/src/bouncer.rs` line 219 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtPrER59Zh4xgDMekzE:-NtVAN3g-C6Z7sRGA3zr:bs107rt) ([raw file](https://github.com/starkware-libs/blockifier/blob/998efdcaacd6d9099be183146e2a9534a70b8a06/crates/blockifier/src/bouncer.rs#L219)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

We had a discussion about it.
I suggested moving the checks inside the function. This design makes it so the function "update_available_capacity_with_keccak" has no assumptions on the time it is called. The assumptions are checked when you enter the function.

I see why it is less readable as is, but the alternative is also somewhat cumbersome.
</blockquote></details>

this is irrelevant now.
___
*[`crates/blockifier/src/transaction/errors.rs` line 95 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtPm0m1C4nfa28Ai8lL:-NtVAFYZ52hgrBRoaXmc:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/998efdcaacd6d9099be183146e2a9534a70b8a06/crates/blockifier/src/transaction/errors.rs#L95)):*
> ```XML
>     TryFromIntError(#[from] std::num::TryFromIntError),
>     #[error("Transaction size exceeds the maximum block capacity.")]
>     TxTooLarge,
> ```

done


<!-- Sent from Reviewable.io -->

2024-03-21 09:01 UTC, Yael-Starkware reviewed
Large refactor of this PR includes:
1. removal of the transactional_bouncer 
2. change the capacity/checked_sub mechanism with accumulated_weights/add
3. conversion from ExecutionResources will use the regular HashMap From function (with default values)
4. removal of the function update_auxiliary_info. instead I use the values directly from ExecutionSummary and calculate state_changeS_keys.
5. insertion of the bouncer_config into the bouncer object

These changes enabled deletion of the following: 
1. The function that handles keccak, and the field "block_contains_keccak"
2. impl_checked_sub macro

note: I am using an inner_update function for testing - the inputs parameter are easier to produce for tests.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-:-NtVCxPB6zHisBoBdQpW:bwg2954)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-03-21 09:28 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 56 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVD8lj3OY8inRQSRHv:-NtVD8lkDq0gRs27x_tP:b-phf8k0) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer.rs#L56)):*
> ```XML
>             return true;
>         }
>         false
> ```

Can you use some fancy `derive`? like `Eq`?



_Code quote:_
```XML
    pub fn exceeds(&self, other: &Self) -> bool {
        if self.gas > other.gas
            || self.message_segment_length > other.message_segment_length
            || self.n_events > other.n_events
            || self.n_steps > other.n_steps
            || self.state_diff_size > other.state_diff_size
            || self.builtin_count.exceeds(other.builtin_count)
        {
            return true;
        }
        false
```


<!-- Sent from Reviewable.io -->

2024-03-21 09:36 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 56 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVD8lj3OY8inRQSRHv:-NtVLbv3CSTTEp5sr_Ym:b-sr7w4o) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer.rs#L56)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you use some fancy `derive`? like `Eq`?
</blockquote></details>

yeah I was looking for one , but couldn't find one that does what we need.
The PartialOrd and Ord derive , compare the structs in a lexicographic order and thats not good for us.


<!-- Sent from Reviewable.io -->

2024-03-21 09:40 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 134 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVLuJz1jqCh5R9eWdo:-NtVLuJz1jqCh5R9eWdp:b-11mtcb) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer.rs#L134)):*
> ```XML
>     }
> 
>     fn merge(
> ```

This name implies that the input should be a Bouncer object.
Consider a different name (e.g., `try_update` for `update`, and `_update` for this one)



_Code quote:_
```XML
    fn merge(
```
___
*[`crates/blockifier/src/bouncer.rs` line 169 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVLVNBBGRnyamnILzU:-NtVLVNBBGRnyamnILzV:b8eaa9c) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer.rs#L169)):*
> ```XML
>         l1_handler_payload_size: Option<usize>,
>     ) -> TransactionExecutorResult<()> {
>         let state_changes_keys = self.get_state_changes_keys(state)?;
> ```

Remove the inner



_Suggestion:_
```XML
    ) -> TransactionExecutorResult<()> {
        let tx_execution_summary = tx_execution_info.summarize();
        let state_changes_keys = self.get_state_changes_keys(state)?;
```
___
*[`crates/blockifier/src/bouncer.rs` line 169 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVNX8_2NqMMjql_Zvj:-NtVNX8_2NqMMjql_Zvk:b-d2j9yy) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer.rs#L169)):*
> ```XML
>         l1_handler_payload_size: Option<usize>,
>     ) -> TransactionExecutorResult<()> {
>         let state_changes_keys = self.get_state_changes_keys(state)?;
> ```

Can you push this inside `get_tx_weights`? (for consistency)



_Code quote:_
```XML
let state_changes_keys = self.get_state_changes_keys(state)?;
```


<!-- Sent from Reviewable.io -->

2024-03-21 09:49 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 1 of 4 files reviewed, 8 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 169 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVNX8_2NqMMjql_Zvj:-NtVOMAb1q_9XElWzUKi:bj6jl78) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer.rs#L169)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you push this inside `get_tx_weights`? (for consistency)
</blockquote></details>

yeah I know it's ugly but I need the state_changes_keys for the merge/_update function.
___
*[`crates/blockifier/src/bouncer.rs` line 234 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVONLO3NoK9e8cP9wd:-NtVPRpVEesUwGtzojXP:bgzfaa2) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer.rs#L234)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

.
</blockquote></details>

I need the StateChangesKeys for the future merge to the bouncer. 


<!-- Sent from Reviewable.io -->

2024-03-21 12:29 UTC, ArniStarkware requested changes
> Reviewed 1 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 4 files reviewed, 11 unresolved discussions (waiting on @noaov1, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer_test.rs` line 56 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVwEam7N03xqGoAQln:-NtVwEam7N03xqGoAQlo:b2frai9) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer_test.rs#L56)):*
> ```XML
>     };
> 
>     assert!(!bouncer_weights.exceeds(&max_bouncer_weights));
> ```

Please add a few more cases.
Cases regarding the builtin_counts/ the other weights etc. Positive and negative.

Fold in the test using `bouncer_weights_exceeds_max` into this test parametrization schema.

As I see it - there are at least 4 cases: The regular wights exceed/ not. The builtin wights exceed/not. (Three negative cases, one positive).



_Suggestion:_
```XML
#[rstest]
#[case(BouncerWeights {
        builtin_count: BuiltinCount {
            bitwise: 6,
            ecdsa: 7,
            ec_op: 7,
            keccak: 8,
            pedersen: 7,
            poseidon: 9,
            range_check: 10,
        },
        gas: 7,
        message_segment_length: 10,
        n_steps: 0,
        n_events: 2,
        state_diff_size: 7,
    }, false)]
fn test_bouncer_exeecds(#[case] bouncer_weights, #[case] is_exeecds) {
    let max_bouncer_weights = BouncerWeights {
        builtin_count: BuiltinCount {
            bitwise: 10,
            ecdsa: 10,
            ec_op: 10,
            keccak: 10,
            pedersen: 10,
            poseidon: 10,
            range_check: 10,
        },
        gas: 10,
        message_segment_length: 10,
        n_events: 10,
        n_steps: 10,
        state_diff_size: 10,
    };

    let bouncer_weights = BouncerWeights {
        builtin_count: BuiltinCount {
            bitwise: 6,
            ecdsa: 7,
            ec_op: 7,
            keccak: 8,
            pedersen: 7,
            poseidon: 9,
            range_check: 10,
        },
        gas: 7,
        message_segment_length: 10,
        n_steps: 0,
        n_events: 2,
        state_diff_size: 7,
    };

    assert!(bouncer_weights.exceeds(&max_bouncer_weights) == is_exceedes);
```
___
*[`crates/blockifier/src/bouncer_test.rs` line 135 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVtyvvEJCj4ZnwKzcu:-NtVtyvw8mxv3GKn1qSu:brr2xl4) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer_test.rs#L135)):*
> ```XML
>     };
> 
>     // TODO (yael): test also state_changes_keys merge with real values.
> ```

Should we follow through with this todo sooner rather than later?



_Suggestion:_
```XML
    // TODO (yael 25/03/2024): test also state_changes_keys merge with real values.
```
___
*[`crates/blockifier/src/bouncer_test.rs` line 139 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVuDmu7i7DTYhzmOtN:-NtVuDmv-3OrufMSwzdy:bn71t0m) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer_test.rs#L139)):*
> ```XML
> 
>     let mut merged_bouncer = initial_bouncer.clone();
>     merged_bouncer.merge(
> ```

If you indeed change the name of this function, rename the test as well.



_Code quote:_
```XML
merge(
```
___
*[`crates/blockifier/src/bouncer_test.rs` line 143 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVxxzHA4eAz-JQG9_R:-NtVxxzHA4eAz-JQG9_S:bqc67sr) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer_test.rs#L143)):*
> ```XML
>         &execution_summary_to_merge,
>         &state_changes_keys_to_merge,
>     );
> ```

Does this make sense? To try to merge to an existing sturct?

Anyway - it is interesting to merge into an empty and a non-empty struct.



_Suggestion:_
```XML
    let mut merged_bouncer = initial_bouncer.clone();
    merged_bouncer.merge(
        weights_to_merge,
        &execution_summary_to_merge,
        &state_changes_keys_to_merge,
    );
    
    // Tests on merged_bouncer...
    
    merged_bouncer.merge(
        more_weights_to_merge, ...);
```
___
*[`crates/blockifier/src/bouncer_test.rs` line 255 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVye8c1SOnuVporXFB:-NtVye8c1SOnuVporXFC:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer_test.rs#L255)):*
> ```XML
>     );
> 
>     // Test for TxTooLarge error.
> ```





_Suggestion:_
```XML
TransactionTooLarge error.
```
___
*[`crates/blockifier/src/bouncer_test.rs` line 269 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVyw6GBs5pixX3by8n:-NtVyw6GBs5pixX3by8o:b65vvfm) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer_test.rs#L269)):*
> ```XML
>         ))
>     );
>     bouncer_resources.0.insert(BuiltinName::bitwise.name().to_string(), 1);
> ```

Test for transaction too large with/ without keccak?

Check that other weight (not keccak) is out of bounds according to the config with keccak.



_Code quote:_
```XML
    bouncer_resources.0.insert(BuiltinName::bitwise.name().to_string(), 21);
    let result = bouncer.update_inner(
        &mut transactional_state,
        &execution_summary,
        &bouncer_resources,
        None,
    );
    assert_matches!(
        result,
        Err(TransactionExecutorError::TransactionExecutionError(
            TransactionExecutionError::TransactionTooLarge
        ))
    );
    bouncer_resources.0.insert(BuiltinName::bitwise.name().to_string(), 1);
```


<!-- Sent from Reviewable.io -->

2024-03-21 14:06 UTC, Yoni-Starkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 4 files reviewed, 10 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-03-24 07:39 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 5 files reviewed, 9 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 56 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVD8lj3OY8inRQSRHv:-NtjJ49p01-Vv6zznIGJ:b-usvrv6) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer.rs#L56)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

yeah I was looking for one , but couldn't find one that does what we need.
The PartialOrd and Ord derive , compare the structs in a lexicographic order and thats not good for us.
</blockquote></details>

as we discussed, I brought back the checked_sub from this check.
___
*[`crates/blockifier/src/bouncer.rs` line 134 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVLuJz1jqCh5R9eWdo:-NtVnYxt59XqSVbAY06u:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer.rs#L134)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

This name implies that the input should be a Bouncer object.
Consider a different name (e.g., `try_update` for `update`, and `_update` for this one)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 169 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVLVNBBGRnyamnILzU:-NtVndEMCJqq3_XIWc6j:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer.rs#L169)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Remove the inner
</blockquote></details>

done
___
*[`crates/blockifier/src/bouncer_test.rs` line 56 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVwEam7N03xqGoAQln:-NtjJIEJ8qZ0w7uZt6lB:b9fl1rl) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer_test.rs#L56)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Please add a few more cases.
Cases regarding the builtin_counts/ the other weights etc. Positive and negative.

Fold in the test using `bouncer_weights_exceeds_max` into this test parametrization schema.

As I see it - there are at least 4 cases: The regular wights exceed/ not. The builtin wights exceed/not. (Three negative cases, one positive).
</blockquote></details>

Eventually I've deleted the function exceeds() so no need to test it anymore.
___
*[`crates/blockifier/src/bouncer_test.rs` line 135 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVtyvvEJCj4ZnwKzcu:-NtjM1VY8P6Y814zTLD0:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer_test.rs#L135)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Should we follow through with this todo sooner rather than later?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/bouncer_test.rs` line 139 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVuDmu7i7DTYhzmOtN:-NtjLwSo5SOzMMr-ux9n:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer_test.rs#L139)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

If you indeed change the name of this function, rename the test as well.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/bouncer_test.rs` line 143 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVxxzHA4eAz-JQG9_R:-NtjMa9s8NlZlNWb0LXL:b-8ovfpb) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer_test.rs#L143)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Does this make sense? To try to merge to an existing sturct?

Anyway - it is interesting to merge into an empty and a non-empty struct.
</blockquote></details>

I think merging twice is redundant since the first merge already test the merge functionality, the second one will just do the same, no new functionality.
regarding merging into an empty struct, I think that it is enough to merge into a non-empty struct since empty is a private-case of non empty. But I can add if you insist :)
___
*[`crates/blockifier/src/bouncer_test.rs` line 255 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVye8c1SOnuVporXFB:-NtjJeCM8UPxQZNi66gj:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer_test.rs#L255)):*
> ```XML
>     );
> 
>     // Test for TxTooLarge error.
> ```

Done.
___
*[`crates/blockifier/src/bouncer_test.rs` line 269 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVyw6GBs5pixX3by8n:-NtjKOE-65r33utKIRV0:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer_test.rs#L269)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Test for transaction too large with/ without keccak?

Check that other weight (not keccak) is out of bounds according to the config with keccak.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-24 07:46 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @noaov1, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer_test.rs` line 143 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVxxzHA4eAz-JQG9_R:-NtjQ-Bz2Rk2ivSFdB03:b-4pemek) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer_test.rs#L143)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

I think merging twice is redundant since the first merge already test the merge functionality, the second one will just do the same, no new functionality.
regarding merging into an empty struct, I think that it is enough to merge into a non-empty struct since empty is a private-case of non empty. But I can add if you insist :)
</blockquote></details>

Yes. Please have both cases.


<!-- Sent from Reviewable.io -->

2024-03-24 08:18 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer_test.rs` line 143 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtVxxzHA4eAz-JQG9_R:-NtjX_fA7BJwe40UNKeb:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e197cd41be1cc78b98e2d9510dd92a09a693385/crates/blockifier/src/bouncer_test.rs#L143)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Yes. Please have both cases.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-24 14:41 UTC, ArniStarkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 5 files reviewed, 13 unresolved discussions (waiting on @noaov1, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 57 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtkpqNbDsgu_1P868Sz:-NtkpqNbDsgu_1P868T-:b-4bkkiw) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer.rs#L57)):*
> ```XML
>     Deserialize,
>     PartialEq,
>     PartialOrd,
> ```

Where is this used?



_Code quote:_
```XML
    PartialOrd,
```
___
*[`crates/blockifier/src/bouncer.rs` line 99 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtkpuLCEETszze_Gcvr:-NtkpuLCEETszze_Gcvs:b-4bkkiw) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer.rs#L99)):*
> ```XML
>     Deserialize,
>     PartialEq,
>     PartialOrd,
> ```

Where is this used?



_Code quote:_
```XML
    PartialOrd,
```
___
*[`crates/blockifier/src/bouncer_test.rs` line 85 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntkq7uZ7PgFawejLGTB:-Ntkq7uZ7PgFawejLGTC:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer_test.rs#L85)):*
> ```XML
> #[rstest]
> #[case(Bouncer::new(BouncerConfig::default()))]
> #[case(Bouncer {
> ```





_Suggestion:_
```XML
#[case::empty_initial_bouncer(Bouncer::new(BouncerConfig::default()))]
#[case::non_empty_initial_bouncer(Bouncer {
```
___
*[`crates/blockifier/src/bouncer_test.rs` line 113 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtkqOaN8sDQZPN5m0iA:-NtkqOaN8sDQZPN5m0iB:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer_test.rs#L113)):*
> ```XML
> })]
> 
> fn test_bouncer_update(#[case] initial_bouncer: Bouncer) {
> ```





_Suggestion:_
```XML
    },
})]
fn test_bouncer_update(#[case] initial_bouncer: Bouncer) {
```
___
*[`crates/blockifier/src/bouncer_test.rs` line 153 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntkqj8J1swnbHGhN_fo:-Ntkqj8J1swnbHGhN_fp:b-23qa6r) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer_test.rs#L153)):*
> ```XML
>     );
> 
>     let mut expected_bouncer = initial_bouncer.clone();
> ```

initial_bouncer is never used after this point.



_Suggestion:_
```XML
    let mut expected_bouncer = initial_bouncer;
```
___
*[`crates/blockifier/src/bouncer_test.rs` line 167 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtkscNWEWUKLXiloIM0:-NtkscNWEWUKLXiloIM1:b-8u77r5) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer_test.rs#L167)):*
> ```XML
> 
> #[test]
> fn test_bouncer_try_update() {
> ```

Parametrize this test.

Name the cases like: `#[case::positive_flow(..)]` `#[case::positive_flow_with_keccak(..)]` 



_Suggestion:_
```XML
#[rstest]
fn test_bouncer_try_update(
    #[case] bouncer_resources: ResourcesMapping,
    #[case] expected_result: Result<(), TransactionExecutorError>,
) {
    
    // Setup...
    // ..
    
    let result =
        bouncer.try_update(&mut transactional_state, &execution_summary, &bouncer_resources, None);
    // Maybe even assert_eq?
    assert_matches!(result, expected_result);

    
    
```
___
*[`crates/blockifier/src/bouncer_test.rs` line 169 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtkrXId0dCn4qrWDwrP:-NtkrXId0dCn4qrWDwrQ:b-xb9qx0) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer_test.rs#L169)):*
> ```XML
> fn test_bouncer_try_update() {
>     let state = &mut test_state(&BlockContext::create_for_account_testing().chain_info, 0, &[]);
>     let mut transactional_state = CachedState::create_transactional(state);
> ```

Add a comment explaining that you do some setup before you start running through scenarios. 



_Suggestion:_
```XML
#[test]
fn test_bouncer_try_update() {
    // Setup bouncer.
    let state = &mut test_state(&BlockContext::create_for_account_testing().chain_info, 0, &[]);
    let mut transactional_state = CachedState::create_transactional(state);
```
___
*[`crates/blockifier/src/bouncer_test.rs` line 227 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntkr8hL52pVYkOCjhX8:-Ntkr8hM6SIHpqp3ogmb:b-rkv8ir) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer_test.rs#L227)):*
> ```XML
>         (constants::N_MEMORY_HOLES.to_string(), 1),
>     ]);
>     let mut bouncer_resources = ResourcesMapping(bouncer_resources);
> ```

Use `HashMap<String, usize>` if `HashMap` does not work.



_Suggestion:_
```XML
    let mut bouncer_resources = ResourcesMapping(HashMap<String, usize>::from([
        (BuiltinName::bitwise.name().to_string(), 1),
        (BuiltinName::ecdsa.name().to_string(), 1),
        (BuiltinName::ec_op.name().to_string(), 1),
        // Keccak is 0 since it has special handling, which will be tested separately.
        (BuiltinName::keccak.name().to_string(), 0),
        (BuiltinName::pedersen.name().to_string(), 1),
        (BuiltinName::poseidon.name().to_string(), 1),
        (BuiltinName::range_check.name().to_string(), 1),
        (constants::BLOB_GAS_USAGE.to_string(), 1),
        (constants::L1_GAS_USAGE.to_string(), 1),
        (constants::N_STEPS_RESOURCE.to_string(), 1),
        (constants::N_MEMORY_HOLES.to_string(), 1),
    ]);
```
___
*[`crates/blockifier/src/bouncer_test.rs` line 261 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtksEuU5i4xcuRMLc0f:-NtksEuU5i4xcuRMLc0g:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer_test.rs#L261)):*
> ```XML
>     let result =
>         bouncer.try_update(&mut transactional_state, &execution_summary, &bouncer_resources, None);
>     assert_matches!(result, Ok(()));
> ```





_Suggestion:_
```XML
    // Test for success with keccak.
    bouncer_resources.0.insert(BuiltinName::keccak.name().to_string(), 1);
    let result =
        bouncer.try_update(&mut transactional_state, &execution_summary, &bouncer_resources, None);
    assert_matches!(result, Ok(()));
```
___
*[`crates/blockifier/src/bouncer_test.rs` line 271 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntktu2f7StwJBRjB6M_:-Ntktu2f7StwJBRjB6Ma:brnfvfl) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer_test.rs#L271)):*
> ```XML
>             TransactionExecutionError::BlockFull
>         ))
>     );
> ```

I like the fact that this case happened even without editing the bouncer_resources.... I don't know how to reflect that within the `cases` architecture...
Maybe there is no easy way to do that.



_Code quote:_
```XML
    // Test for BlockFull error with keccak.
    let result =
        bouncer.try_update(&mut transactional_state, &execution_summary, &bouncer_resources, None);
    assert_matches!(
        result,
        Err(TransactionExecutorError::TransactionExecutionError(
            TransactionExecutionError::BlockFull
        ))
    );
```


<!-- Sent from Reviewable.io -->

2024-03-25 07:37 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 5 files reviewed, 14 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 158 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtoXY-e2rqrH-6jTup-:-NtoXY-e2rqrH-6jTup0:bexw154) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer.rs#L158)):*
> ```XML
>         state_changes_keys: &StateChangesKeys,
>     ) {
>         self.accumulated_weights = self.accumulated_weights + tx_weights;
> ```

There's no `+=` in rust?



_Code quote:_
```XML
self.accumulated_weights = self.accumulated_weights + tx_weights;
```
___
*[`crates/blockifier/src/bouncer.rs` line 188 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtoXPmc8zG_FjfU2U7z:-NtoXPmc8zG_FjfU2U8-:b-muerku) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer.rs#L188)):*
> ```XML
> 
>         // Check if the transaction is too large to fit any block.
>         if max_capacity.checked_sub(tx_weights).is_none() {
> ```

Make it a method of BouncerWeights



_Code quote:_
```XML
max_capacity.checked_sub(tx_weights).is_none()
```
___
*[`crates/blockifier/src/bouncer.rs` line 189 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtoXkEC3G7Xk_RvO7Qt:-NtoXkEC3G7Xk_RvO7Qu:b-2y506o) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer.rs#L189)):*
> ```XML
>         // Check if the transaction is too large to fit any block.
>         if max_capacity.checked_sub(tx_weights).is_none() {
>             Err(TransactionExecutionError::TransactionTooLarge)?
> ```

Why do you need this?



_Code quote:_
```XML
)?
```


<!-- Sent from Reviewable.io -->

2024-03-25 08:40 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 5 files reviewed, 14 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 57 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtkpqNbDsgu_1P868Sz:-Nto_zqI8gW6mgoHbytE:b-lo63fe) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer.rs#L57)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Where is this used?
</blockquote></details>

leftovers, deleted. done
___
*[`crates/blockifier/src/bouncer.rs` line 99 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtkpuLCEETszze_Gcvr:-Ntoa2098joySnhJTC21:b9jone2) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer.rs#L99)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Where is this used?
</blockquote></details>

deleted, done
___
*[`crates/blockifier/src/bouncer.rs` line 158 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtoXY-e2rqrH-6jTup-:-Ntob5zE9zzoAmCcgHKq:b-hvr1sa) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer.rs#L158)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

There's no `+=` in rust?
</blockquote></details>

had to use and additional derive for this - derive_more::AddAssign
done.
___
*[`crates/blockifier/src/bouncer.rs` line 188 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtoXPmc8zG_FjfU2U7z:-NtobDCSB47fDc6fFpOK:bq1zu98) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer.rs#L188)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Make it a method of BouncerWeights
</blockquote></details>

it is a function of BouncerWeights. max_capacity is of type BouncerWeights.
___
*[`crates/blockifier/src/bouncer.rs` line 189 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtoXkEC3G7Xk_RvO7Qt:-NtobNRb0tAQghHwn7M7:b-ah0sx4) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer.rs#L189)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why do you need this?
</blockquote></details>

since the error is a TransactionExecutionError and the function returns a different type - TransactionExecutorError, so the "?" is converting it to the required return type.

I can add the errors to the list of TransactionExecutorError and then then the conversion won't be necessary.
___
*[`crates/blockifier/src/bouncer_test.rs` line 85 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntkq7uZ7PgFawejLGTB:-Ntoc_Y-0aDGVkp2v1SV:b31n4ff) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer_test.rs#L85)):*
> ```XML
> #[rstest]
> #[case(Bouncer::new(BouncerConfig::default()))]
> #[case(Bouncer {
> ```

oh , I was asking chatGPT how to document the test cases and he didn't tell me that!
___
*[`crates/blockifier/src/bouncer_test.rs` line 113 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtkqOaN8sDQZPN5m0iA:-Ntod4nJ9nT9i-0FCmlg:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer_test.rs#L113)):*
> ```XML
> })]
> 
> fn test_bouncer_update(#[case] initial_bouncer: Bouncer) {
> ```

Done.
___
*[`crates/blockifier/src/bouncer_test.rs` line 153 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntkqj8J1swnbHGhN_fo:-NtodIrl5UcENRe8T6D9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer_test.rs#L153)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

initial_bouncer is never used after this point.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/bouncer_test.rs` line 167 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtkscNWEWUKLXiloIM0:-NtokHTJEaY5Xw8fwPqh:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer_test.rs#L167)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Parametrize this test.

Name the cases like: `#[case::positive_flow(..)]` `#[case::positive_flow_with_keccak(..)]`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/bouncer_test.rs` line 169 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtkrXId0dCn4qrWDwrP:-NtokyfY-lXjWpGt_Y-y:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer_test.rs#L169)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Add a comment explaining that you do some setup before you start running through scenarios.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/bouncer_test.rs` line 227 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntkr8hL52pVYkOCjhX8:-NtodziH4bbJEt81aQ9H:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer_test.rs#L227)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Use `HashMap<String, usize>` if `HashMap` does not work.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/bouncer_test.rs` line 261 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtksEuU5i4xcuRMLc0f:-Ntol-3q2AFHNO62irpD:b-1nlhfm) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer_test.rs#L261)):*
> ```XML
>     let result =
>         bouncer.try_update(&mut transactional_state, &execution_summary, &bouncer_resources, None);
>     assert_matches!(result, Ok(()));
> ```

documented in the test cases
___
*[`crates/blockifier/src/bouncer_test.rs` line 271 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntktu2f7StwJBRjB6M_:-Ntol4542p8_eKgz1oEF:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer_test.rs#L271)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I like the fact that this case happened even without editing the bouncer_resources.... I don't know how to reflect that within the `cases` architecture...
Maybe there is no easy way to do that.
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2024-03-25 08:51 UTC, ArniStarkware commented
*[`crates/blockifier/src/state/cached_state.rs` line 718 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtoncVY474Bk-15n4Up:-NtoncVY474Bk-15n4Uq:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/36a927c6ca3c64cf7c963c341041b7bbebcd12b2/crates/blockifier/src/state/cached_state.rs#L718)):*
> ```XML
>     pub fn create_for_testing(nonce_keys: HashSet<ContractAddress>) -> Self {
>         Self { nonce_keys, ..Default::default() }
>     }
> ```





_Suggestion:_
```XML
    #[cfg(any(feature = "testing", test))]
    pub fn create_for_testing(nonce_keys: HashSet<ContractAddress>) -> Self {
        Self { nonce_keys, ..Default::default() }
    }
```


<!-- Sent from Reviewable.io -->

2024-03-25 09:00 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @noaov1, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer_test.rs` line 85 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntkq7uZ7PgFawejLGTB:-Ntolv3f4qxy-I_wZaBr:brp9v0q) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer_test.rs#L85)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

oh , I was asking chatGPT how to document the test cases and he didn't tell me that!
</blockquote></details>

ChatGPT is a looser!
___
*[`crates/blockifier/src/bouncer_test.rs` line 167 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtkscNWEWUKLXiloIM0:-Ntom4lO5iz3ucymCq0-:bxt22mu) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer_test.rs#L167)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You are a hero!


<!-- Sent from Reviewable.io -->

2024-03-25 09:41 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 718 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtoncVY474Bk-15n4Up:-NtoyuSG10hpHqbxhIzd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/36a927c6ca3c64cf7c963c341041b7bbebcd12b2/crates/blockifier/src/state/cached_state.rs#L718)):*
> ```XML
>     pub fn create_for_testing(nonce_keys: HashSet<ContractAddress>) -> Self {
>         Self { nonce_keys, ..Default::default() }
>     }
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-03-25 10:06 UTC, ArniStarkware requested changes
> Reviewed 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 3 of 5 files reviewed, 8 unresolved discussions (waiting on @noaov1, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer_test.rs` line 201 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntp2RxL-EQg3BGSryEt:-Ntp2RxL-EQg3BGSryEu:b1nb0f4) ([raw file](https://github.com/starkware-libs/blockifier/blob/03da3cf660db8f26ab0e4486d8f4982538df1603/crates/blockifier/src/bouncer_test.rs#L201)):*
> ```XML
>         TransactionExecutionError::TransactionTooLarge
>     ))
> )]
> ```

Am I correct with the other scenario?


Also, with these two tests, I want the update to theoretically succeed if `block_max_capacity` is used and fail because `block_max_capacity_with_keccak` is used.



_Suggestion:_
```XML
#[case::transaction_too_large_with_keccak(
    0,
    0,
    2,
    Err(TransactionExecutorError::TransactionExecutionError(
        TransactionExecutionError::TransactionTooLarge
    ))
)]
#[case::transaction_too_large_with_keccak_ecdsa_too_large(
    0,
    21,
    1,
    Err(TransactionExecutorError::TransactionExecutionError(
        TransactionExecutionError::TransactionTooLarge
    ))
)]
```
___
*[`crates/blockifier/src/bouncer_test.rs` line 211 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntp16os7Nj1pWVZNE-G:-Ntp16os7Nj1pWVZNE-H:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/03da3cf660db8f26ab0e4486d8f4982538df1603/crates/blockifier/src/bouncer_test.rs#L211)):*
> ```XML
> )]
> 
> fn test_bouncer_try_update(
> ```





_Suggestion:_
```XML
)]
fn test_bouncer_try_update(
```
___
*[`crates/blockifier/src/bouncer_test.rs` line 215 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntp-Dy60NOJPseKG4EI:-Ntp-Dy79A3yLHBJL9bE:b78bbzv) ([raw file](https://github.com/starkware-libs/blockifier/blob/03da3cf660db8f26ab0e4486d8f4982538df1603/crates/blockifier/src/bouncer_test.rs#L215)):*
> ```XML
>     #[case] added_ecdsa: usize,
>     #[case] added_keccak: usize,
>     #[case] _expected_result: TransactionExecutorResult<()>,
> ```

why `_`?



_Suggestion:_
```XML
    #[case] expected_result: TransactionExecutorResult<()>,
```
___
*[`crates/blockifier/src/bouncer_test.rs` line 260 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntp-Jg73tMeq35YvKjw:-Ntp-Jg73tMeq35YvKjx:bnt8o1w) ([raw file](https://github.com/starkware-libs/blockifier/blob/03da3cf660db8f26ab0e4486d8f4982538df1603/crates/blockifier/src/bouncer_test.rs#L260)):*
> ```XML
>         bouncer_config,
>         ..Default::default()
>     };
> ```

Similar to `block_max_capacity`



_Suggestion:_
```XML
    accumulated_weights: BouncerWeights {
            builtin_count: BuiltinCount {
                bitwise: 10,
                ecdsa: 10,
                ec_op: 10,
                keccak: initial_keccak,
                pedersen: 10,
                poseidon: 10,
                range_check: 10,
            },
            gas: 10,
            message_segment_length: 10,
            n_steps: 10,
            n_events: 10,
            state_diff_size: 10,
        }
    let mut bouncer = Bouncer {
        accumulated_weights,
        bouncer_config,
        ..Default::default()
    };
```


<!-- Sent from Reviewable.io -->

2024-03-27 09:47 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 188 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtoXPmc8zG_FjfU2U7z:-NtzC88YB2moLle_OAMC:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/df24fd68dfe69ab186fe5a826a7f0d00ddf71251/crates/blockifier/src/bouncer.rs#L188)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I mean, put this piece of code `checked_sub(tx_weights).is_none()` in a function `has_room`/`has_capacity`/something
</blockquote></details>

Done.
___
*[`crates/blockifier/src/bouncer.rs` line 143 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtpgEo83lsR0iadLgks:-Ntz0IcRDiUOLkp7DN6d:b-epic46) ([raw file](https://github.com/starkware-libs/blockifier/blob/03da3cf660db8f26ab0e4486d8f4982538df1603/crates/blockifier/src/bouncer.rs#L143)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Trivial
</blockquote></details>

Gilad asked me to add a comment explaining why this field is private and what are the constraints.
___
*[`crates/blockifier/src/bouncer_test.rs` line 201 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntp2RxL-EQg3BGSryEt:-NtzCY5oDu1nVdi_yUNP:b6k9r3d) ([raw file](https://github.com/starkware-libs/blockifier/blob/03da3cf660db8f26ab0e4486d8f4982538df1603/crates/blockifier/src/bouncer_test.rs#L201)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Am I correct with the other scenario?


Also, with these two tests, I want the update to theoretically succeed if `block_max_capacity` is used and fail because `block_max_capacity_with_keccak` is used.
</blockquote></details>

Done, the test case is good.
not sure I understand the question.
___
*[`crates/blockifier/src/bouncer_test.rs` line 211 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntp16os7Nj1pWVZNE-G:-NtzCcFg5qM38Zyu7d-a:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/03da3cf660db8f26ab0e4486d8f4982538df1603/crates/blockifier/src/bouncer_test.rs#L211)):*
> ```XML
> )]
> 
> fn test_bouncer_try_update(
> ```

Done.
___
*[`crates/blockifier/src/bouncer_test.rs` line 215 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntp-Dy60NOJPseKG4EI:-NtzHACZ5kmRFQxGFlgt:b9xt45y) ([raw file](https://github.com/starkware-libs/blockifier/blob/03da3cf660db8f26ab0e4486d8f4982538df1603/crates/blockifier/src/bouncer_test.rs#L215)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

why `_`?
</blockquote></details>

discussed f2f and solved with format!
___
*[`crates/blockifier/src/bouncer_test.rs` line 260 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntp-Jg73tMeq35YvKjw:-NtzIGOL00AYvF9OBXQE:b-7rl0jd) ([raw file](https://github.com/starkware-libs/blockifier/blob/03da3cf660db8f26ab0e4486d8f4982538df1603/crates/blockifier/src/bouncer_test.rs#L260)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Similar to `block_max_capacity`
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2024-03-27 10:03 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @noaov1, @Yael-Starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer_test.rs` line 286 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtzMDB326bbYBnGINC5:-NtzMDB326bbYBnGINC6:b-z2fess) ([raw file](https://github.com/starkware-libs/blockifier/blob/934bd6960635d38d9489073ba6458048f1470488/crates/blockifier/src/bouncer_test.rs#L286)):*
> ```XML
>         bouncer.try_update(&mut transactional_state, &execution_summary, &bouncer_resources, None);
> 
>     assert_eq!(format!("{:?}", result), format!("{:?}", expected_result));
> ```

I don't like it - but I don't like anything.



_Code quote:_
```XML
assert_eq!(format!("{:?}", result), format!("{:?}", expected_result));
```


<!-- Sent from Reviewable.io -->

2024-03-27 10:51 UTC, Yoni-Starkware requested changes
Almost done :)
(didn't review the test, that's on @ArniStarkware to approve)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-:-NtzWuoY2ejqF6weGmgQ:b-8p2npm)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 143 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtpgEo83lsR0iadLgks:-NtzVcs21cGd01M7VDJp:b-c8wotd) ([raw file](https://github.com/starkware-libs/blockifier/blob/03da3cf660db8f26ab0e4486d8f4982538df1603/crates/blockifier/src/bouncer.rs#L143)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Gilad asked me to add a comment explaining why this field is private and what are the constraints.
</blockquote></details>

Perhaps the other way around
```rust
pub struct Bouncer {
    accumulated_weights: BouncerWeights,
    
    // Additional info; maintained and used to calculate the residual contribution of a transaction to the accumulated weights.
    pub executed_class_hashes: HashSet<ClassHash>,
    pub visited_storage_entries: HashSet<StorageEntry>,
    pub state_changes_keys: StateChangesKeys,
    pub bouncer_config: BouncerConfig,


```
___
*[`crates/blockifier/src/bouncer.rs` line 232 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtzXF6C0aW_cHoo_di9:-NtzXF6C0aW_cHoo_diA:bgggh9e) ([raw file](https://github.com/starkware-libs/blockifier/blob/934bd6960635d38d9489073ba6458048f1470488/crates/blockifier/src/bouncer.rs#L232)):*
> ```XML
>         let mut tx_weights = BouncerWeights::from(additional_os_resources) + execution_info_weights;
> 
>         tx_weights.state_diff_size = get_onchain_data_segment_length(&state_changes_keys.count());
> ```

Waiting for the rebase


<!-- Sent from Reviewable.io -->

2024-03-27 11:34 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 143 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtpgEo83lsR0iadLgks:-Ntzg6_M33mJpn4Pq3VP:bc6hudd) ([raw file](https://github.com/starkware-libs/blockifier/blob/03da3cf660db8f26ab0e4486d8f4982538df1603/crates/blockifier/src/bouncer.rs#L143)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Perhaps the other way around
```rust
pub struct Bouncer {
    accumulated_weights: BouncerWeights,
    
    // Additional info; maintained and used to calculate the residual contribution of a transaction to the accumulated weights.
    pub executed_class_hashes: HashSet<ClassHash>,
    pub visited_storage_entries: HashSet<StorageEntry>,
    pub state_changes_keys: StateChangesKeys,
    pub bouncer_config: BouncerConfig,


```
</blockquote></details>

Gilad taught me that private variables are after public.


<!-- Sent from Reviewable.io -->

2024-03-27 11:37 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 232 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtzXF6C0aW_cHoo_di9:-NtzgmDIBeEuGmXxlKU8:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/934bd6960635d38d9489073ba6458048f1470488/crates/blockifier/src/bouncer.rs#L232)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Waiting for the rebase
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-27 11:37 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 143 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-NtpgEo83lsR0iadLgks:-NtzgpIl85HX1sG1B04R:b-258hsn) ([raw file](https://github.com/starkware-libs/blockifier/blob/03da3cf660db8f26ab0e4486d8f4982538df1603/crates/blockifier/src/bouncer.rs#L143)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

Gilad taught me that private variables are after public.
</blockquote></details>

other than that , done.


<!-- Sent from Reviewable.io -->

2024-03-27 11:38 UTC, ArniStarkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> (no tests)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-:-Ntzh3Do0Kq2lpTbnf4F:b-1fm0wi)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-03-27 11:38 UTC, ArniStarkware commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> (on tests)





<!-- Sent from Reviewable.io -->

2024-03-27 12:19 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 4 files at r2, 1 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @noaov1, and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer.rs` line 135 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntzq3cEAYEhAaywtIPR:-Ntzq3cEAYEhAaywtIPS:b-9mc8bf) ([raw file](https://github.com/starkware-libs/blockifier/blob/eace8d52ccd556dd75d32615930f08c0f3fcded3/crates/blockifier/src/bouncer.rs#L135)):*
> ```XML
>     pub bouncer_config: BouncerConfig,
> 
>     accumulated_weights: BouncerWeights,
> ```

Do wee need all of them to be pub?



_Suggestion:_
```XML
    // Additional info; maintained and used to calculate the residual contribution of a transaction
    // to the accumulated weights.
    pub executed_class_hashes: HashSet<ClassHash>,
    pub visited_storage_entries: HashSet<StorageEntry>,
    pub state_changes_keys: StateChangesKeys,
    
    pub bouncer_config: BouncerConfig,

    accumulated_weights: BouncerWeights,
```


<!-- Sent from Reviewable.io -->

2024-03-27 12:19 UTC, Yoni-Starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-:-NtzqTlOB_TPMcGJdQ0X:bnfp4nl)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @noaov1, and @Yael-Starkware)



<!-- Sent from Reviewable.io -->

2024-03-27 12:24 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @ArniStarkware, @giladchase, and @noaov1)

___
*[`crates/blockifier/src/bouncer.rs` line 135 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntzq3cEAYEhAaywtIPR:-Ntzr-__69Aq8v06V1Sa:b-5j8iig) ([raw file](https://github.com/starkware-libs/blockifier/blob/eace8d52ccd556dd75d32615930f08c0f3fcded3/crates/blockifier/src/bouncer.rs#L135)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Do wee need all of them to be pub?
</blockquote></details>

@giladchase  said that every field should be public unless there is a real constraint. 


<!-- Sent from Reviewable.io -->

2024-03-27 12:42 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 3 files at r17, 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @ArniStarkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-03-27 12:43 UTC, ArniStarkware submitted a review, later dismissed
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-03-27 12:48 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yael-Starkware)

___
*[`crates/blockifier/src/bouncer_test.rs` line 22 at r20](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntzwy9f1Yoawj1VtHYc:-Ntzwy9f1Yoawj1VtHYd:b162fna) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5f195dac3e93417d0ef8feb8dbfc5c13f24277c/crates/blockifier/src/bouncer_test.rs#L22)):*
> ```XML
> 
> #[test]
> fn test_block_weights_sub_checked() {
> ```

Rename and adjust a little to test `has_room`?
___
*[`crates/blockifier/src/state/cached_state.rs` line 717 at r20](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntzwjy87dIg6R0-aryL:-Ntzwjy87dIg6R0-aryM:bem9xp0) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5f195dac3e93417d0ef8feb8dbfc5c13f24277c/crates/blockifier/src/state/cached_state.rs#L717)):*
> ```XML
> 
>     #[cfg(any(feature = "testing", test))]
>     pub fn create_for_testing(nonce_keys: HashSet<ContractAddress>) -> Self {
> ```

According to @noaov1, this should be defined in `struct_impls.rs` 



_Code quote:_
```XML
    #[cfg(any(feature = "testing", test))]
    pub fn create_for_testing(nonce_keys: HashSet<ContractAddress>) -> Self {
```


<!-- Sent from Reviewable.io -->

2024-03-27 14:56 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/bouncer_test.rs` line 22 at r20](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntzwy9f1Yoawj1VtHYc:-Nu-PBza23CFgrq9tkEq:beu33rb) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5f195dac3e93417d0ef8feb8dbfc5c13f24277c/crates/blockifier/src/bouncer_test.rs#L22)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Rename and adjust a little to test `has_room`?
</blockquote></details>

oopsy, done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 717 at r20](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntzwjy87dIg6R0-aryL:-Nu-OqZqDP6AkP8ES9ic:bj5r52m) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5f195dac3e93417d0ef8feb8dbfc5c13f24277c/crates/blockifier/src/state/cached_state.rs#L717)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

According to @noaov1, this should be defined in `struct_impls.rs`
</blockquote></details>

couldn't move it since the fields of StateChangesKeys are private so you can't access them outside of the module the object was defined in.
@noaov1 approved to keep this function here.


<!-- Sent from Reviewable.io -->

2024-03-27 16:26 UTC, Yoni-Starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-:-Nu-iubCBT-2lkP8Um4e:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-03-28 07:02 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/bouncer.rs` line 135 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntzq3cEAYEhAaywtIPR:-Nu2rMVY2AP6R0abVeYZ:b-x8gow) ([raw file](https://github.com/starkware-libs/blockifier/blob/eace8d52ccd556dd75d32615930f08c0f3fcded3/crates/blockifier/src/bouncer.rs#L135)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

@giladchase  said that every field should be public unless there is a real constraint.
</blockquote></details>

Constraint ==> Invariant 
:P


<!-- Sent from Reviewable.io -->

2024-03-28 07:22 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/bouncer.rs` line 135 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-Ntzq3cEAYEhAaywtIPR:-Nu2vurMAYmDGAOFksGb:bcbsq3l) ([raw file](https://github.com/starkware-libs/blockifier/blob/eace8d52ccd556dd75d32615930f08c0f3fcded3/crates/blockifier/src/bouncer.rs#L135)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Constraint ==> Invariant 
:P
</blockquote></details>

yes exactly :)


<!-- Sent from Reviewable.io -->

2024-03-28 07:29 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1644#-:-Nu2xiNF9vUyPMAI5icf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-03-28 07:30 UTC, merged