Nimrod/starknet resources refactor
starkware-libs/blockifier pull request #1655
Opened 2024-03-11 10:31 UTC by nimrod-starkware

2024-03-12 18:18 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: all files reviewed, 23 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/call_info.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsmuOea-_9ljfNl7qJ8:-NsnML6rEHBgHsY1FuRg:bz7og00) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/execution/call_info.rs#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

It's not :)
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 186 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-Nsmqmo34Qv90ZomBakl:-Nsnss0rAUrKv0yW7rqU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/fee/actual_cost.rs#L186)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this part is a mess of different abstraction levels IMO...
1. let's start by some cleanup so it's easier to read
2. `get_onchain_data_segment_length` should be a method of `StarknetResources`
3. `get_additional_os_tx_resources` should get a reference to `StarknetResources` as input, instead of separate resources
</blockquote></details>

Done.
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 192 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsmqWNn22Qyzbrx1MZk:-NsnTMeKCfxrvkh2v39f:baubv7o) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/fee/actual_cost.rs#L192)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Is it possible at this point to create a BouncerInfo object and use it instead of TransactionResources?
i.e. `impl From<TransactionResources> for BouncerInfo`?
</blockquote></details>

I'm not sure it's possible at this stage, I'll check that when I'll implement your comment below.
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 195 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-Nsms2FA-sgskRiYUpvi:-NsnPAgE9_sUn1LP17Nr:b-r1xb22) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/fee/actual_cost.rs#L195)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

here's my game plan, WDYT?
</blockquote></details>

sounds good! I'm afraid it will make this PR much larger though.
I'll add this TODO and will do it in a future PR
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 49 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-Nsmsy5p2fpx5X-gF3qR:-NsnUGBm1RdFaTWIh68X:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/fee/fee_utils.rs#L49)):*
> ```XML
> ) -> TransactionFeeResult<GasVector> {
>     let vm_resource_fee_costs = versioned_constants.vm_resource_fee_cost();
>     let vm_resource_names =
> ```

Done.
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-Nsmt92P1QQnQG6I_2vz:-NsnUQM336YSmxbkgig9:b-kkfw02) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/fee/fee_utils.rs#L80)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

for clarity
</blockquote></details>

I think your comment is incorrect, the cost is the most expensive resource and not the sum
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsmtJ5M04LbXyHifZw5:-NsnVwhwAAjnFTc9mIMd:b-7m74ox) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/fee/fee_utils.rs#L87)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

enforce it now :)
</blockquote></details>

nice!
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsmtTr68sFf_Tvy_QFC:-NsnX64CBU6YrmVNOksL:b44zsps) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/fee/fee_utils.rs#L96)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this looks like this function now computes something different: you don't count n_steps (or memory holes).
this *should* break tests that use it; why aren't they broken?
</blockquote></details>

This function is used only at tests. 
At the regular flow when we cast `TransactionResources` to `ResourcesMapping` we take into account `total_n_steps` which is a combination of `n_steps`, `n_memory_holes`, and `segment_arena_builtin`.  This combination is mapped as `n_steps`. It's the same logic that was before. 
___
*[`crates/blockifier/src/fee/gas_usage.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-Nsmtr3IAuZVB9R7_9vN:-Nsnd3XP8rqxNwNK5Rb7:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/fee/gas_usage.rs#L209)):*
> ```XML
>     let resources = ExecutionResources { n_steps: os_steps_for_type, ..Default::default() };
>     Ok(GasVector { l1_gas: gas_cost, l1_data_gas: blob_gas_cost }
>         + calculate_l1_gas_by_vm_usage(versioned_constants, &resources)?)
> ```

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 801 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsmuLlA9S4YvRxJOJue:-Nsndt8W0dkANZYarTmz:b7mo8bk) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/state/cached_state.rs#L801)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

it's not :)
___
*[`crates/blockifier/src/transaction/objects.rs` line 260 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsmuRTG4d8NzASVMh_P:-Nsne1BEBf6gJxSdw5J2:b-hfpv0l) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/transaction/objects.rs#L260)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

removed
___
*[`crates/blockifier/src/transaction/objects.rs` line 339 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsmutCI927mPivPyqN-:-NsneiIL35QjPOUqVjNJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/transaction/objects.rs#L339)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why? this is the last usage in the block, you can move it
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 412 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsmuUnd51EtX1MUx5aY:-NsneCNsB_v8zGJ4ej4m:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/transaction/objects.rs#L412)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 413 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsmuVE9-A_ahXtgZvHw:-NsneCd714CzIEWWvZlv:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/transaction/objects.rs#L413 [...]

2024-03-13 04:45 UTC, dorimedini-starkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: 10 of 19 files reviewed, 23 unresolved discussions (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-03-13 05:51 UTC, dorimedini-starkware requested changes
> Reviewed 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: all files reviewed, 8 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 173 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsqJ11Q6f9LAEkcE8TU:-NsqJ11Q6f9LAEkcE8TV:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a51e31b4d3a33e6587585678c7acab02d67f107/crates/blockifier/src/fee/actual_cost.rs#L173)):*
> ```XML
>         self.tx_resources
>             .starknet_resources
>             .set_events_and_messages_resources(non_optional_call_infos)?;
> ```





_Suggestion:_
```XML

        // Set the events and messages resources from the transaction's call infos.
        let non_optional_call_infos =
            self.validate_call_info.into_iter().chain(self.execute_call_info);
        self.tx_resources
            .starknet_resources
            .set_events_and_messages_resources(non_optional_call_infos)?;
```
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 186 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsqIlUR0dj0AToMBzBJ:-NsqIlUR0dj0AToMBzBK:bhp9tdh) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a51e31b4d3a33e6587585678c7acab02d67f107/crates/blockifier/src/fee/actual_cost.rs#L186)):*
> ```XML
>                     use_kzg_da,
>                 )?
>                 .filter_unused_builtins();
> ```

otherwise you won't filter the unused builtins in `execution_resources`



_Suggestion:_
```XML
        self.tx_resources.vm_resources = (execution_resources
            + &self
                .tx_context
                .block_context
                .versioned_constants
                .get_additional_os_tx_resources(
                    self.tx_type,
                    &self.tx_resources.starknet_resources,
                    use_kzg_da,
                )?)
                .filter_unused_builtins();
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-Nsmt92P1QQnQG6I_2vz:-NsqJUpiAwg3z3vTDyjp:b-s3jtbz) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/fee/fee_utils.rs#L80)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I think your comment is incorrect, the cost is the most expensive resource and not the sum
</blockquote></details>

ah, right, my bad
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 96 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsmtTr68sFf_Tvy_QFC:-NsqLogI4nTB3QDCK7pO:bnun1vh) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/fee/fee_utils.rs#L96)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

This function is used only at tests. 
At the regular flow when we cast `TransactionResources` to `ResourcesMapping` we take into account `total_n_steps` which is a combination of `n_steps`, `n_memory_holes`, and `segment_arena_builtin`.  This combination is mapped as `n_steps`. It's the same logic that was before.
</blockquote></details>

see comment below (in the other place you added `#[cfg(test)]`)
___
*[`crates/blockifier/src/transaction/objects.rs` line 403 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsqK-6b2DwozHtV6uME:-NsqK-6b2DwozHtV6uMF:bs71p6y) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a51e31b4d3a33e6587585678c7acab02d67f107/crates/blockifier/src/transaction/objects.rs#L403)):*
> ```XML
>     pub fn get_onchain_data_segment_length(&self) -> usize {
>         get_onchain_data_segment_length(&self.state_changes_count)
>     }
> ```

please add a TODO to delete the standalone `get_onchain_data_segment_length` function



_Code quote:_
```XML
    pub fn get_onchain_data_segment_length(&self) -> usize {
        get_onchain_data_segment_length(&self.state_changes_count)
    }
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 271 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsmvhJr0bc2O_cz9TTg:-NsqKLZV2UhXB9z5tE_r:bv1wv0p) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/transaction/test_utils.rs#L271)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

At the 'natural' flow we calculate the user's fee like this:
`TransactionResources` -> `GasVector` -> `Fee`. The tests that use this function are checking that the fee calculation was done correctly. They get as a result `TransactionExecutionInfo` which has `ResourceMapping`.  Along the way `TransactionResources` converted to `ResourcesMapping`. This cast cannot go the other way (from `ResourcesMapping` to `TransactionResources`).
This function is for calculating fee from `ResourceMapping` which is not part of the natural flow.
</blockquote></details>

`TransactionExecutionInfo` should not contain `ResourcesMapping`, it should contain `TransactionResources`; which should solve this problem and remove the need for this (and the other `#[cfg(test)]`ified function).
it would help to review this PR if I could see a PR with this suggested change (current PR is already large enough); when I am convinced transitioning away from ResourcesMapping doesn't break tests I'll unblock
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsmvlkL9XbJgt5AKBwG:-NsqLwV2ACmGINCWh9lg:bubji2t) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/transaction/transaction_execution.rs#L147)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

That's what i wanted to do first, but then i noticed that in order to do the casting correctly i need the block context (which includes `versioned_constants` and `use_kzg_da`) and it seemed right to cast it here.
I can figure out in a future PR how to do that...
</blockquote></details>

It doesn't have to be `impl From`, you can directly implement some `from(&BlockContext, &TransactionExecutionInfo) -> Self` function, as long as the calling location has access to the block context (which I think it should)


<!-- Sent from Reviewable.io -->

2024-03-18 09:56 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: 6 of 23 files reviewed, 8 unresolved discussions (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-03-18 13:14 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: 6 of 23 files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/actual_cost.rs` line 173 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsqJ11Q6f9LAEkcE8TU:-NtAF1vN9Cz4RAmnw2CY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a51e31b4d3a33e6587585678c7acab02d67f107/crates/blockifier/src/fee/actual_cost.rs#L173)):*
> ```XML
>         self.tx_resources
>             .starknet_resources
>             .set_events_and_messages_resources(non_optional_call_infos)?;
> ```

Done.
___
*[`crates/blockifier/src/fee/actual_cost.rs` line 186 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsqIlUR0dj0AToMBzBJ:-NtAFAVw2HDWCyYWU2Xt:b-m9lld0) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a51e31b4d3a33e6587585678c7acab02d67f107/crates/blockifier/src/fee/actual_cost.rs#L186)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

otherwise you won't filter the unused builtins in `execution_resources`
</blockquote></details>

איזה חדות!
___
*[`crates/blockifier/src/fee/fee_checks.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-Nsmst0Y5AJ8-nwBZRBd:-NtAdvGS-XpzHvN5sqCN:bs578v3) ([raw file](https://github.com/starkware-libs/blockifier/blob/1fec21d49d9949cdc8694ed173bb37807f604002/crates/blockifier/src/fee/fee_checks.rs#L108)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this function still used?
if so, where?
</blockquote></details>

removed it :)
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 625 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsmudA5CqDz1pkyZ33X:-NtAdpvyCtDyWxShiZ-q:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/transaction/account_transaction.rs#L625)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

change the type on `TransactionExecutionInfo`, use `to_resources_mapping` when converting to `ThinTransactionExecutionInfo`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/objects.rs` line 403 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsqK-6b2DwozHtV6uME:-NtAehUICoUbAagXK_Ms:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a51e31b4d3a33e6587585678c7acab02d67f107/crates/blockifier/src/transaction/objects.rs#L403)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a TODO to delete the standalone `get_onchain_data_segment_length` function
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 147 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsmvlkL9XbJgt5AKBwG:-NtAerEs0flq6dOUcb8I:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/transaction/transaction_execution.rs#L147)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

It doesn't have to be `impl From`, you can directly implement some `from(&BlockContext, &TransactionExecutionInfo) -> Self` function, as long as the calling location has access to the block context (which I think it should)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 271 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NsmvhJr0bc2O_cz9TTg:-NtAzESt1i_b8v6WmmUI:b-cfix2l) ([raw file](https://github.com/starkware-libs/blockifier/blob/77d4aa9ab9de456fb3ed402476a48876c991f798/crates/blockifier/src/transaction/test_utils.rs#L271)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`TransactionExecutionInfo` should not contain `ResourcesMapping`, it should contain `TransactionResources`; which should solve this problem and remove the need for this (and the other `#[cfg(test)]`ified function).
it would help to review this PR if I could see a PR with this suggested change (current PR is already large enough); when I am convinced transitioning away from ResourcesMapping doesn't break tests I'll unblock
</blockquote></details>

i removed it :) it's not needed


<!-- Sent from Reviewable.io -->

2024-03-18 13:51 UTC, dorimedini-starkware requested changes
> Reviewed 16 of 18 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: 22 of 23 files reviewed, 15 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 618 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGKYAT8xgOC2-UfGDC:-NtGKYAT8xgOC2-UfGDD:buk2wue) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/blockifier/src/transaction/account_transaction.rs#L618)):*
> ```XML
>             actual_resources: final_resources,
>             revert_error,
>             bouncer_resources,
> ```

please add a TODO here to remove this field: there should be a `reverted_steps` field in `actual_resources`, and a `to_bouncer_info` method on `TransactionExecutionInfo` that computes bouncer info given `actual_resources` (by ignoring the reverted steps).



_Code quote:_
```XML
bouncer_resources,
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 490 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGL7ypBXtUDzz6Prhx:-NtGL7yqAmAAciwwU4z-:b-7hsmks) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/blockifier/src/transaction/account_transactions_test.rs#L490)):*
> ```XML
>     if bouncer_steps >= actual_steps {
>         panic!("Expected {} < {}.", bouncer_steps, actual_steps);
>     }
> ```

don't we have `assert_le` or something for this?



_Code quote:_
```XML
    if bouncer_steps >= actual_steps {
        panic!("Expected {} < {}.", bouncer_steps, actual_steps);
    }
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 500 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGKuDF-lx0yrjoYLIO:-NtGKuDF-lx0yrjoYLIP:bk6ac4f) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/blockifier/src/transaction/account_transactions_test.rs#L500)):*
> ```XML
>         bouncer_resources.vm_resources.n_memory_holes,
>         actual_resources.vm_resources.n_memory_holes
>     );
> ```

compare by elimination - i.e, you know only the n_steps differ, so just nullify them and then compare the entire object.
this is good because it will automatically compare new fields if they are added



_Suggestion:_
```XML
    let mut bouncer_resources = tx_execution_info.bouncer_resources.clone();
    let mut actual_resources = tx_execution_info.actual_resources.clone();
    let bouncer_steps = bouncer_resources.vm_resources.n_steps;
    let actual_steps = actual_resources.vm_resources.n_steps;
    if bouncer_steps >= actual_steps {
        panic!("Expected {} < {}.", bouncer_steps, actual_steps);
    }
    // Bouncer resources and actual resources should be identical apart from n_steps.
    bouncer_resources.vm_resources.n_steps = 0;
    actual_resources.vm_resources.n_steps = 0;
    assert_eq!(bouncer_resources, actual_resources);
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 422 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGQ1ZR3doHtVfws_J5:-NtGQ1ZR3doHtVfws_J6:b-d54tih) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a51e31b4d3a33e6587585678c7acab02d67f107/crates/blockifier/src/transaction/objects.rs#L422)):*
> ```XML
>     pub starknet_resources: StarknetResources,
>     pub vm_resources: ExecutionResources,
>     pub n_reverted_steps: usize,
> ```

why is this removed...? you will do it in a subsequent PR?



_Code quote:_
```XML
pub n_reverted_steps: usize,
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 262 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGQ7tP5vhvMLVjCfSV:-NtGQ7tP5vhvMLVjCfSW:b-z3icz7) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/blockifier/src/transaction/objects.rs#L262)):*
> ```XML
> 
> /// Containes all the L2 resources consumed by a transaction
> #[derive(Clone, Debug, Default, PartialEq)]
> ```

why was this added?



_Code quote:_
```XML
PartialEq
```
___
*[`crates/blockifier/src/transaction/objects.rs` line 418 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGQ5895j0Eua9CB_aB:-NtGQ5895j0Eua9CB_aC:b-z3icz7) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/blockifier/src/transaction/objects.rs#L418)):*
> ```XML
>     }
> }
> #[derive(Default, Clone, Debug, PartialEq)]
> ```

why was this added?



_Code quote:_
```XML
 PartialEq
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 331 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGn-fy1Oe5S6VKhgOE:-NtGn-fy1Oe5S6VKhgOF:b-ap8us7) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/blockifier/src/transaction/transactions_test.rs#L331)):*
> ```XML
>             .and_modify(|v| *v += value)
>             .or_insert(value);
>     });
> ```

no need for extra variable now



_Suggestion:_
```XML
    target.n_steps += os_kzg_da_resources.n_steps;

    os_kzg_da_resources.builtin_instance_counter.into_iter().for_each(|(key, value)| {
        target
            .builtin_instance_counter
            .entry(key.to_string())
            .and_modify(|v| *v += value)
            .or_insert(value);
    });
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1327 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGnkpjCuqQGL5z7dee:-NtGnkpjCuqQGL5z7def:b-rtagwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/blockifier/src/transaction/transactions_test.rs#L1327)):*
> ```XML
>     let actual_resources =
>         TransactionResources { starknet_resources, vm_resources: expected_cairo_resources };
>     // get_actual_resources(expected_cairo_resources, da_gas);
> ```

delete
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1337 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGnn8zCvqcy8OlakiF:-NtGnn8zCvqcy8OlakiG:b6q6u4e) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/blockifier/src/transaction/transactions_test.rs#L1337)):*
> ```XML
>         actual_resources: actual_resources.clone(),
>         bouncer_resources: actual_resources,
>     };
> ```

does this work? (non-blocking, as it's a test)



_Suggestion:_
```XML
    let starknet_resources = &actual_execution_info.actual_resources.starknet_resources;

    let state_changes_count = StateChangesCount {
        n_storage_updates: 1,
        n_modified_contracts: 1,
        n_class_hash_updates: 1,
        ..StateChangesCount::default()
    };
    let da_gas = get_da_gas_cost(&state_changes_count, use_kzg_da);
    let expected_cairo_resources = get_expected_cairo_resources(
        &block_context.versioned_constants,
        TransactionType::DeployAccount,
        starknet_resources,
        vec![&expected_validate_call_info, &expected_execute_call_info],
    );

    let actual_resources =
        TransactionResources { starknet_resources: *starknet_resources, vm_resources: expected_cairo_resources };
    // get_actual_resources(expected_cairo_resources, da_gas);
    let mut expected_execution_info = TransactionExecutionInfo {
        validate_call_info: expected_validate_call_info,
        execute_call_info: expected_execute_call_info,
        fee_transfer_call_info: expected_fee_transfer_call_info,
        actual_fee: expected_actual_fee,
        da_gas,
        revert_error: None,
        actual_resources: actual_resources.clone(),
        bouncer_resources: actual_resources,
    };
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 67 at r5](https://reviewable.io/reviews/starkware-libs/blockif [...]

2024-03-18 14:20 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: all files reviewed, 17 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/fee/fee_test.rs` line 77 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGvpzh2FNC_Rlnw2Ms:-NtGvpzh2FNC_Rlnw2Mt:bkjwziy) ([raw file](https://github.com/starkware-libs/blockifier/blob/28bf7ff3eea878399d8304fb28721d717da980ff/crates/blockifier/src/fee/fee_test.rs#L77)):*
> ```XML
> // #[case::expensive_dg_no_dg_within_bounds(10, 1000, 10, 0, 10, false)]
> // #[case::expensive_dg_with_dg_overdraft(10, 1000, 10, 1, 109, true)]
> // #[case::expensive_dg_with_dg_within_bounds(10, 1000, 10, 1, 110, false)]
> ```

reinstate these cases



_Suggestion:_
```XML
#[case::both_gases_overdraft(1000, 10, 10000, 5000, 10000, true)]
#[case::expensive_dg_no_dg_within_bounds(10, 1000, 10, 0, 10, false)]
#[case::expensive_dg_with_dg_overdraft(10, 1000, 10, 1, 109, true)]
#[case::expensive_dg_with_dg_within_bounds(10, 1000, 10, 1, 110, false)]
```
___
*[`crates/blockifier/src/fee/fee_test.rs` line 120 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGvUIP3LEJU7fQfQFp:-NtGvUIP3LEJU7fQfQFq:b-yiflij) ([raw file](https://github.com/starkware-libs/blockifier/blob/28bf7ff3eea878399d8304fb28721d717da980ff/crates/blockifier/src/fee/fee_test.rs#L120)):*
> ```XML
>         expected_gas_vector,
>         actual_resources.to_gas_vector(&block_context.versioned_constants, use_kzg_da,).unwrap()
>     );
> ```

explain what you're doing when you start, not only when you assert you succeeded



_Suggestion:_
```XML
    
    // Construct a resources report that should cost the expected gas vector, and assert the
    // derived gas cost is as expected.
    let state_changes_count = StateChangesCount {
        n_storage_updates: 0,
        n_modified_contracts: l1_data_gas_used / (DATA_GAS_PER_FIELD_ELEMENT * 2),
        n_class_hash_updates: 0,
        ..StateChangesCount::default()
    };
    let starknet_resources =
        StarknetResources::new(0, 0, None, state_changes_count, None, std::iter::empty()).unwrap();
    let actual_resources = TransactionResources {
        starknet_resources,
        vm_resources: ExecutionResources { n_steps: l1_gas_used, ..Default::default() },
    };
    let expected_gas_vector = GasVector {
        l1_gas: u128_from_usize(l1_gas_used),
        l1_data_gas: u128_from_usize(l1_data_gas_used),
    };
    assert_eq!(
        expected_gas_vector,
        actual_resources.to_gas_vector(&block_context.versioned_constants, use_kzg_da,).unwrap()
    );
```


<!-- Sent from Reviewable.io -->

2024-03-19 08:00 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: all files reviewed, 18 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/fee/fee_test.rs` line 41 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtKi5Fv9v5k1jkrK3SR:-NtKi5Fv9v5k1jkrK3SS:b-p3m8hw) ([raw file](https://github.com/starkware-libs/blockifier/blob/4177b43102c12e623d36dc621f4b0031a0ea4a1b/crates/blockifier/src/fee/fee_test.rs#L41)):*
> ```XML
>         StarknetResources::new(0, 0, None, state_changes_count, None, std::iter::empty()).unwrap();
>     TransactionResources { starknet_resources, vm_resources }
> }
> ```

this actually depends on versioned_constants... `ExecutionResources { n_steps: l1_gas, ..Default::default() };` relies on the fact that 1 step == 1 gas.
I would pass the versioned constants as input, or at least document this assumption



_Code quote:_
```XML
fn get_tx_resources_from_gas_usages(l1_gas: usize, l1_data_gas: usize) -> TransactionResources {
    let vm_resources = ExecutionResources { n_steps: l1_gas, ..Default::default() };
    let state_changes_count = StateChangesCount {
        n_class_hash_updates: l1_data_gas / DATA_GAS_PER_FIELD_ELEMENT,
        ..StateChangesCount::default()
    };
    let starknet_resources =
        StarknetResources::new(0, 0, None, state_changes_count, None, std::iter::empty()).unwrap();
    TransactionResources { starknet_resources, vm_resources }
}
```


<!-- Sent from Reviewable.io -->

2024-03-19 09:54 UTC, dorimedini-starkware reviewed
> Reviewed 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: all files reviewed, 18 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 331 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtL6zxS2S7F2MlWj2Pn:-NtL6zxS2S7F2MlWj2Po:b6bk7l2) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8f5023ce810d4756a9013a19a4df9603790714f/crates/blockifier/src/fee/actual_cost_test.rs#L331)):*
> ```XML
>         tx_execution_info
>             .actual_resources
>             .starknet_resources
> ```

what about the gas cost of the VM resources? why do you need to ignore them here in the test?



_Code quote:_
```XML
        tx_execution_info
            .actual_resources
            .starknet_resources
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1785 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtL7Wxc16ccGlCMDhIN:-NtL7Wxc16ccGlCMDhIO:b-3y41dz) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8f5023ce810d4756a9013a19a4df9603790714f/crates/blockifier/src/transaction/transactions_test.rs#L1785)):*
> ```XML
>         actual_execution_info
>             .actual_resources
>             .starknet_resources
> ```

why ignore gas cost of VM resources here?



_Code quote:_
```XML
        actual_execution_info
            .actual_resources
            .starknet_resources
```


<!-- Sent from Reviewable.io -->

2024-03-19 10:03 UTC, dorimedini-starkware reviewed
> Reviewed 10 of 10 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: all files reviewed, 18 unresolved discussions (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-03-19 12:15 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: all files reviewed, 18 unresolved discussions (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-03-19 14:33 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: 18 of 26 files reviewed, 18 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 331 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtL6zxS2S7F2MlWj2Pn:-NtLTW_T0TrZN2Jf768r:b-qdnexo) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8f5023ce810d4756a9013a19a4df9603790714f/crates/blockifier/src/fee/actual_cost_test.rs#L331)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what about the gas cost of the VM resources? why do you need to ignore them here in the test?
</blockquote></details>

we talked about it F2F. 
it's because actual resources only contained starknet resources as l1_gas and l1_data_gas.
___
*[`crates/blockifier/src/fee/fee_test.rs` line 77 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGvpzh2FNC_Rlnw2Ms:-NtL2XZb5k-W-CcCaG1-:b-6xoaza) ([raw file](https://github.com/starkware-libs/blockifier/blob/28bf7ff3eea878399d8304fb28721d717da980ff/crates/blockifier/src/fee/fee_test.rs#L77)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

reinstate these cases
</blockquote></details>

see above comment
___
*[`crates/blockifier/src/fee/fee_test.rs` line 120 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGvUIP3LEJU7fQfQFp:-NtL2ZqJ41_ENmll2cgp:b-6xoaza) ([raw file](https://github.com/starkware-libs/blockifier/blob/28bf7ff3eea878399d8304fb28721d717da980ff/crates/blockifier/src/fee/fee_test.rs#L120)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

explain what you're doing when you start, not only when you assert you succeeded
</blockquote></details>

see above comment
___
*[`crates/blockifier/src/fee/fee_test.rs` line 41 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtKi5Fv9v5k1jkrK3SR:-NtL2BsbAPNGcL7DsNBH:blz09ts) ([raw file](https://github.com/starkware-libs/blockifier/blob/4177b43102c12e623d36dc621f4b0031a0ea4a1b/crates/blockifier/src/fee/fee_test.rs#L41)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this actually depends on versioned_constants... `ExecutionResources { n_steps: l1_gas, ..Default::default() };` relies on the fact that 1 step == 1 gas.
I would pass the versioned constants as input, or at least document this assumption
</blockquote></details>

I removed all these changes.
I added `actual_gas_cost` field to `ActualCost` that solves this problem.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 618 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGKYAT8xgOC2-UfGDC:-NtL4QW2BRYTdPzIXl-_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/blockifier/src/transaction/account_transaction.rs#L618)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a TODO here to remove this field: there should be a `reverted_steps` field in `actual_resources`, and a `to_bouncer_info` method on `TransactionExecutionInfo` that computes bouncer info given `actual_resources` (by ignoring the reverted steps).
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 490 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGL7ypBXtUDzz6Prhx:-NtL4b4n0NhSRIBMTluA:biv14rf) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/blockifier/src/transaction/account_transactions_test.rs#L490)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't we have `assert_le` or something for this?
</blockquote></details>

you wrote that ;)
added `assert_lt`
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 500 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGKuDF-lx0yrjoYLIO:-NtM01avBSSGUfIbdTop:b-3dql03) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/blockifier/src/transaction/account_transactions_test.rs#L500)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

compare by elimination - i.e, you know only the n_steps differ, so just nullify them and then compare the entire object.
this is good because it will automatically compare new fields if they are added
</blockquote></details>

nice :)
___
*[`crates/blockifier/src/transaction/objects.rs` line 422 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGQ1ZR3doHtVfws_J5:-NtLV7Tp2vo9_b3dav0q:b-r3mw91) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a51e31b4d3a33e6587585678c7acab02d67f107/crates/blockifier/src/transaction/objects.rs#L422)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this removed...? you will do it in a subsequent PR?
</blockquote></details>

yes i'll do that later (in another PR)
___
*[`crates/blockifier/src/transaction/objects.rs` line 262 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGQ7tP5vhvMLVjCfSV:-NtLVNA45sEBWWKFirK6:b-2g9vtj) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/blockifier/src/transaction/objects.rs#L262)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why was this added?
</blockquote></details>

Some tests compare `TransactionExecutionInfo`. since it contains `TransactionResources` they need to compare that field as well. (which recursively enforces `StarknetResources` to derive that as well.)
___
*[`crates/blockifier/src/transaction/objects.rs` line 418 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGQ5895j0Eua9CB_aB:-NtLWBPQD7NBi158p1Re:b2ss7xm) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/blockifier/src/transaction/objects.rs#L418)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why was this added?
</blockquote></details>

see comment above
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 331 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGn-fy1Oe5S6VKhgOE:-NtLev7k2OvPTIqDLV0X:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/blockifier/src/transaction/transactions_test.rs#L331)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no need for extra variable now
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1327 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGnkpjCuqQGL5z7dee:-NtLkzY98nc8r-GH2UBX:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/blockifier/src/transaction/transactions_test.rs#L1327)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1337 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGnn8zCvqcy8OlakiF:-NtLwUzX2qNhb5msEgrB:b-mrpp8m) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/blockifier/src/transaction/transactions_test.rs#L1337)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does this work? (non-blocking, as it's a test)
</blockquote></details>

doesn't work...
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1785 at r8](https://reviewable.io/reviews/starkware-l [...]

2024-03-19 15:08 UTC, dorimedini-starkware requested changes
> Reviewed 8 of 8 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: all files reviewed, 5 unresolved discussions (waiting on @nimrod-starkware)

___
*[`Cargo.toml` line 35 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtMF8VQ7GgHGNLiUc_Y:-NtMF8VQ7GgHGNLiUc_Z:b-rphf0w) ([raw file](https://github.com/starkware-libs/blockifier/blob/39781ce9b008d321e103400f02ece6c6e3fed462/Cargo.toml#L35)):*
> ```TOML
> keccak = "0.1.3"
> log = "0.4"
> more-asserts = "0.3.1"
> ```

need approval by @elintul 



_Code quote:_
```TOML
more-asserts = "0.3.1"
```
___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 331 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtL6zxS2S7F2MlWj2Pn:-NtMEHXT6UGqF269hYaA:b-r51pgj) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8f5023ce810d4756a9013a19a4df9603790714f/crates/blockifier/src/fee/actual_cost_test.rs#L331)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

we talked about it F2F. 
it's because actual resources only contained starknet resources as l1_gas and l1_data_gas.
</blockquote></details>

add a TODO to test regression w.r.t. all resources (including VM)
___
*[`crates/blockifier/src/fee/fee_test.rs` line 77 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGvpzh2FNC_Rlnw2Ms:-NtMEZEZEWSN6pIAPf31:bgzj03x) ([raw file](https://github.com/starkware-libs/blockifier/blob/28bf7ff3eea878399d8304fb28721d717da980ff/crates/blockifier/src/fee/fee_test.rs#L77)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

see above comment
</blockquote></details>

not sure what you mean but unblocking (cases are back)
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 490 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGL7ypBXtUDzz6Prhx:-NtMEhIcA2Sqxf73fbiD:bwsloog) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/blockifier/src/transaction/account_transactions_test.rs#L490)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

you wrote that ;)
added `assert_lt`
</blockquote></details>

ah... need an external dependency I see. this needs approval from Elin, please ask her to TAL at the addition, or revert to what it was... sorry about that
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 43 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGovgU0NRPgQ1w_eWJ:-NtMF5644Rh7gMfgFnvj:b-cbix8) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/native_blockifier/src/py_transaction_execution_info.rs#L43)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nope :)


<!-- Sent from Reviewable.io -->

2024-03-19 15:24 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: 24 of 26 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtKhsHT3CSaJVsbJxHK:-NtMGKEGEOnR7oa0_h05:b-oadw2x) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Please paste a link to a python-side PR bumping the blockifier commit
</blockquote></details>

python side [PR](https://github.com/starkware-industries/starkware/pull/34444)

___
___
*[`crates/blockifier/src/fee/actual_cost_test.rs` line 331 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtL6zxS2S7F2MlWj2Pn:-NtMIaBkADGbypvNqhqE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8f5023ce810d4756a9013a19a4df9603790714f/crates/blockifier/src/fee/actual_cost_test.rs#L331)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add a TODO to test regression w.r.t. all resources (including VM)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 490 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGL7ypBXtUDzz6Prhx:-NtMJAsb8wY5ugafu2F_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/blockifier/src/transaction/account_transactions_test.rs#L490)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah... need an external dependency I see. this needs approval from Elin, please ask her to TAL at the addition, or revert to what it was... sorry about that
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_transaction_execution_info.rs` line 43 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtGovgU0NRPgQ1w_eWJ:-NtMGfJD0jipfdkaobYm:b-7lj87c) ([raw file](https://github.com/starkware-libs/blockifier/blob/24b8c44ae64ae44d93faca13422713d97a1470f7/crates/native_blockifier/src/py_transaction_execution_info.rs#L43)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

nope :)
</blockquote></details>

oops 


<!-- Sent from Reviewable.io -->

2024-03-19 15:42 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-03-19 16:29 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/Cargo.toml` line 36 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtMXrwm6nAWcpLDuUP6:-NtMXrwm6nAWcpLDuUP7:b-uaa8tv) ([raw file](https://github.com/starkware-libs/blockifier/blob/e44d0f263053d508c66ecd243ce0ace69cac90f2/crates/blockifier/Cargo.toml#L36)):*
> ```TOML
> keccak.workspace = true
> log.workspace = true
> more-asserts.workspace = true
> ```

I think this needs to be in `dev-dependencies` for `udeps` to pass



_Code quote:_
```TOML
more-asserts.workspace = true
```


<!-- Sent from Reviewable.io -->

2024-03-20 08:11 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-03-20 08:44 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 37 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtQ11nLBx6eFJTX0yJe:-NtQ11nLBx6eFJTX0yJf:b-udlts9) ([raw file](https://github.com/starkware-libs/blockifier/blob/a79f6799902ced750f9f8e8728c151eea5ea79a9/crates/blockifier/src/fee/fee_utils.rs#L37)):*
> ```XML
>     // TODO(Nimrod, 1/5/2024): We don't remove `SEGMENT_ARENA_BUILTIN_NAME` from VM resources when
>     // we calculate total_n_steps. Should we do that? vm_resource_fee_costs doesn't contain it.
>     vm_builtin_names.remove(&SEGMENT_ARENA_BUILTIN_NAME.to_string());
> ```

@noaov1 or @Yoni-Starkware ?



_Code quote:_
```XML
    // TODO(Nimrod, 1/5/2024): We don't remove `SEGMENT_ARENA_BUILTIN_NAME` from VM resources when
    // we calculate total_n_steps. Should we do that? vm_resource_fee_costs doesn't contain it.
    vm_builtin_names.remove(&SEGMENT_ARENA_BUILTIN_NAME.to_string());
```


<!-- Sent from Reviewable.io -->

2024-03-20 11:46 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: all files reviewed, 6 unresolved discussions (waiting on @nimrod-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 41 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtQG_qg-L1STZVt4acM:-NtQfcAp8X64FpKydiF5:b-ykor5j) ([raw file](https://github.com/starkware-libs/blockifier/blob/a79f6799902ced750f9f8e8728c151eea5ea79a9/crates/blockifier/src/fee/fee_utils.rs#L41)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Use `assert!` instead - if this is true, it's a bug. (non-blocking, cc @dorimedini-starkware )
</blockquote></details>

Why is panicking better than rejecting the tx? `assert!` can in theory crash the batcher


<!-- Sent from Reviewable.io -->

2024-03-20 11:53 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: all files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 41 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtQG_qg-L1STZVt4acM:-NtQgvNuAv6uqqJFMHIt:beel1aq) ([raw file](https://github.com/starkware-libs/blockifier/blob/a79f6799902ced750f9f8e8728c151eea5ea79a9/crates/blockifier/src/fee/fee_utils.rs#L41)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Why is panicking better than rejecting the tx? `assert!` can in theory crash the batcher
</blockquote></details>

Because it's a bug. The tx should not be rejected - rejecting will hide the bug.


<!-- Sent from Reviewable.io -->

2024-03-20 11:53 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: all files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @noaov1)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 41 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtQG_qg-L1STZVt4acM:-NtQhM3hDEAZS5G8XyhA:be3608y) ([raw file](https://github.com/starkware-libs/blockifier/blob/a79f6799902ced750f9f8e8728c151eea5ea79a9/crates/blockifier/src/fee/fee_utils.rs#L41)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Because it's a bug. The tx should not be rejected - rejecting will hide the bug.
</blockquote></details>

The batcher must crash in such cases


<!-- Sent from Reviewable.io -->

2024-03-20 13:48 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: 20 of 26 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 43 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtQpfFV3u4_K430wGNv:-NtR6XSQ1DqvT6vg6cE8:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c744d8dab7b73c1aeaef4f4a76047c916ac9796c/crates/blockifier/src/fee/fee_utils.rs#L43)):*
> ```XML
>         vm_builtin_names,
>     );
>     let total_n_steps = vm_resource_usage.total_n_steps();
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-03-20 14:04 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 5 files at r16, 1 of 2 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-:-NtRAIpl0p_Awf4hJ2AM:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 45 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtR9zRe9SKn5xQY9HdI:-NtR9zRe9SKn5xQY9HdJ:b-8rlkqz) ([raw file](https://github.com/starkware-libs/blockifier/blob/13be307b6445f6c63e75c3c468365e13a91a977e/crates/blockifier/src/fee/fee_utils.rs#L45)):*
> ```XML
>         "{:#?} should contain {:#?}",
>         vm_resource_fee_costs.keys(),
>         vm_builtin_names,
> ```

this is how `assert!` works...? don't you need `format!` as well?



_Code quote:_
```XML
        "{:#?} should contain {:#?}",
        vm_resource_fee_costs.keys(),
        vm_builtin_names,
```


<!-- Sent from Reviewable.io -->

2024-03-20 15:13 UTC, nimrod-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 45 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtR9zRe9SKn5xQY9HdI:-NtRPLfG9jnqy5dl5EFr:b4i54mq) ([raw file](https://github.com/starkware-libs/blockifier/blob/13be307b6445f6c63e75c3c468365e13a91a977e/crates/blockifier/src/fee/fee_utils.rs#L45)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is how `assert!` works...? don't you need `format!` as well?
</blockquote></details>

don't think so.. 
it derives #[(debug)] so i can use it
https://stackoverflow.com/questions/72637174/pretty-print-struct-in-rust


<!-- Sent from Reviewable.io -->

2024-03-20 15:18 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 45 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-NtR9zRe9SKn5xQY9HdI:-NtRR1D77LZ-OC8uSDa8:b-p7xww4) ([raw file](https://github.com/starkware-libs/blockifier/blob/13be307b6445f6c63e75c3c468365e13a91a977e/crates/blockifier/src/fee/fee_utils.rs#L45)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

don't think so.. 
it derives #[(debug)] so i can use it
https://stackoverflow.com/questions/72637174/pretty-print-struct-in-rust
</blockquote></details>

what I'm asking is: don't you need:
```
assert!(
        vm_builtin_names.is_subset(&HashSet::from_iter(vm_resource_fee_costs.keys())),
        format!(
            "{:#?} should contain {:#?}",
            vm_resource_fee_costs.keys(),
            vm_builtin_names,
        )
    );
```
?


<!-- Sent from Reviewable.io -->

2024-03-20 16:23 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655#-:-NtRf7HCDsq2hMLhkX9o:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-03-20 23:59 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-03-21 06:01 UTC, Yoni-Starkware approved these changes
> Reviewed 2 of 10 files at r9, 1 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1655)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)



<!-- Sent from Reviewable.io -->

2024-03-21 06:30 UTC, merged