refactor: create validator struct and use it in py_validator
starkware-libs/blockifier pull request #1678
Opened 2024-03-18 07:32 UTC by ArniStarkware

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1678)

2024-03-19 13:24 UTC, Yael-Starkware reviewed
> Reviewed 7 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1678)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @elintul)

___
*[`crates/blockifier/src/blockifier/validator.rs` line 62 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtLpiSG4KG13TI13HzN:-NtLpiSG4KG13TI13HzO:b-kyfjot) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f91e4eeaabab1e9094dbe88d8e9d5d4834d1ed2/crates/blockifier/src/blockifier/validator.rs#L62)):*
> ```XML
>         let state = CachedState::new(state_reader, global_contract_cache);
> 
>         // TODO(Arni, 30/04/2024): Get block_info and chain_info from the most logical place.
> ```

The missing todo about the pre_process_block should appear here.
___
*[`crates/blockifier/src/blockifier/validator.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtLrDW23Lz1Kl3lZ3lg:-NtLrDW23Lz1Kl3lZ3lh:b-gsf777) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f91e4eeaabab1e9094dbe88d8e9d5d4834d1ed2/crates/blockifier/src/blockifier/validator.rs#L82)):*
> ```XML
>         // so they are skipped here.
>         if let AccountTransaction::DeployAccount(_) = account_tx {
>             let (_tx_execution_info, _py_bouncer_info) = self.execute(account_tx)?;
> ```

_bouncer_info



_Code quote:_
```XML
_py_bouncer_info
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtHCML13oFnKPDz4gp9:-NtHCML13oFnKPDz4gpA:b-f1ps7s) ([raw file](https://github.com/starkware-libs/blockifier/blob/adee3ef8a7ac0260cae5ac783af66f23cda81c72/crates/native_blockifier/src/py_validator.rs#L52)):*
> ```XML
> 
>         let (block_info, chain_info) = into_block_context_args(&general_config, &next_block_info)?;
>         // TODO(Yael 24/01/24): calc block_context using pre_process_block
> ```

please keep the todo, we need to call pre_processs_block here so that the hash of block_number-10 will be written to the hash table


<!-- Sent from Reviewable.io -->

2024-03-19 13:38 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1678)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @elintul and @Yael-Starkware)

___
*[`crates/blockifier/src/blockifier/validator.rs` line 62 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtLpiSG4KG13TI13HzN:-NtLumqFAkvaV728NS36:b-94wf0h) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f91e4eeaabab1e9094dbe88d8e9d5d4834d1ed2/crates/blockifier/src/blockifier/validator.rs#L62)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

The missing todo about the pre_process_block should appear here.
</blockquote></details>

Done. Thank you for pointing out both lines of code.
___
*[`crates/blockifier/src/blockifier/validator.rs` line 82 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtLrDW23Lz1Kl3lZ3lg:-NtLuF-BD6Mt_LXfC49O:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f91e4eeaabab1e9094dbe88d8e9d5d4834d1ed2/crates/blockifier/src/blockifier/validator.rs#L82)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

_bouncer_info
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/py_validator.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtHCML13oFnKPDz4gp9:-NtLugRgDyCIfizi6uXF:bs7wumx) ([raw file](https://github.com/starkware-libs/blockifier/blob/adee3ef8a7ac0260cae5ac783af66f23cda81c72/crates/native_blockifier/src/py_validator.rs#L52)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

please keep the todo, we need to call pre_processs_block here so that the hash of block_number-10 will be written to the hash table
</blockquote></details>

Done. 


<!-- Sent from Reviewable.io -->

2024-03-20 07:08 UTC, ArniStarkware commented
*[`crates/blockifier/src/blockifier/validator.rs` line 110 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtPg2ztE1UQtDyZS7Xy:-NtPg2ztE1UQtDyZS7Xz:b-3mo0so) ([raw file](https://github.com/starkware-libs/blockifier/blob/a9f5495f8632e4cf100d2f67ed4823a20b23e745/crates/blockifier/src/blockifier/validator.rs#L110)):*
> ```XML
>         // Post validations.
>         // TODO(Ayelet, 09/11/2023): Check call succeeded.
>         PostValidationReport::verify(&tx_context, &actual_cost)?;
> ```

Replaces: `perform_post_validation_stage`. There is no need for a method here - as `self` was never used.



_Code quote:_
```XML
        PostValidationReport::verify(&tx_context, &actual_cost)?;
```


<!-- Sent from Reviewable.io -->

2024-03-20 07:15 UTC, ArniStarkware commented
Python side PR: https://github.com/starkware-industries/starkware/pull/34448




<!-- Sent from Reviewable.io -->

2024-03-24 08:46 UTC, elintul reviewed
> Reviewed 2 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1678)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/blockifier/src/blockifier/validator.rs` line 1 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjbaKyCbOY8lq1d5jS:-NtjbaKyCbOY8lq1d5jT:b-3c0jkb) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L1)):*
> ```XML
> use starknet_api::core::Nonce;
> ```

Consider renaming to `StatefulValidator` (file as well); validator is too generic.


<!-- Sent from Reviewable.io -->

2024-03-24 09:17 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1678)* status: 2 of 9 files reviewed, 13 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/blockifier/src/blockifier/validator.rs` line 22 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-Ntjd1I18lrWb_wc3Va1:-Ntjd1I18lrWb_wc3Va2:b-j1g5tu) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L22)):*
> ```XML
> 
> #[derive(Debug, Error)]
> pub enum ValidatorError {
> ```

Please alphabetize.



_Code quote:_
```XML
ValidatorError
```
___
*[`crates/blockifier/src/blockifier/validator.rs` line 31 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjgzD56vRq3lkszP_a:-NtjgzD56vRq3lkszP_b:bhjqkge) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L31)):*
> ```XML
> }
> 
> impl From<TransactionExecutionError> for ValidatorError {
> ```

Why is it needed?



_Code quote:_
```XML
From<TransactionExecutionError> for ValidatorError
```
___
*[`crates/blockifier/src/blockifier/validator.rs` line 42 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-Ntjh9xa1G8npYXN8iK6:-Ntjh9xa1G8npYXN8iK7:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L42)):*
> ```XML
> pub struct Validator<S: StateReader> {
>     pub max_nonce_for_validation_skip: Nonce,
>     pub tx_executor: TransactionExecutor<S>,
> ```





_Suggestion:_
```XML
    max_nonce_for_validation_skip: Nonce,
    tx_executor: TransactionExecutor<S>,
```
___
*[`crates/blockifier/src/blockifier/validator.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjhDV10PSnC60prmnJ:-NtjhDV2-F8Uq2EtOTNy:b-liheku) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L49)):*
> ```XML
>         validate_max_n_steps: u32,
>         max_recursion_depth: usize,
>         global_contract_cache_size: usize,
> ```

Move down.
We should think of bundling those in a more natural struct; please add a TODO.



_Code quote:_
```XML
        validate_max_n_steps: u32,
        max_recursion_depth: usize,
        global_contract_cache_size: usize,
```
___
*[`crates/blockifier/src/blockifier/validator.rs` line 64 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-Ntji9Rt-nDkWTyKmu6s:-Ntji9Rt-nDkWTyKmu6t:b6nanqf) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L64)):*
> ```XML
>         // TODO(Yael 24/01/24): calc block_context using pre_process_block
> 
>         // TODO(Arni, 30/04/2024): Get block_info and chain_info from the most logical place.
> ```

Move up, above those arguments.



_Code quote:_
```XML
// TODO(Arni, 30/04/2024): Get block_info and chain_info from the most logical place.
```
___
*[`crates/blockifier/src/blockifier/validator.rs` line 71 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjiC5i0sgFn3gnPpFZ:-NtjiC5i0sgFn3gnPpF_:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L71)):*
> ```XML
>         let validator = Self { max_nonce_for_validation_skip, tx_executor };
> 
>         Ok(validator)
> ```





_Suggestion:_
```XML
        // TODO(Yael 24/01/24): calc block_context using pre_process_block
        let block_context =
            BlockContext::new_unchecked(&block_info, &chain_info, &versioned_constants);
        let tx_executor = TransactionExecutor::new(state, block_context);
        
        Ok(Self { max_nonce_for_validation_skip, tx_executor })
```
___
*[`crates/blockifier/src/blockifier/validator.rs` line 76 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjiLa10LJyksWqSu7T:-NtjiLa10LJyksWqSu7U:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L76)):*
> ```XML
>     pub fn perform_validations(
>         &mut self,
>         account_tx: AccountTransaction,
> ```





_Suggestion:_
```XML
tx: AccountTransaction
```
___
*[`crates/blockifier/src/blockifier/validator.rs` line 77 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjiQhi0W4vTYpGTlpE:-NtjiQhi0W4vTYpGTlpF:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L77)):*
> ```XML
>         &mut self,
>         account_tx: AccountTransaction,
>         deploy_account_tx_hash: Option<StarkFelt>,
> ```





_Suggestion:_
```XML
TransactionHash
```
___
*[`crates/blockifier/src/blockifier/validator.rs` line 87 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjiYcb6mMMkwHghZi2:-NtjiYcc2stTUPZ_72-y:b-cdez6r) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L87)):*
> ```XML
>             // TODO(Ayelet, 09/11/2023): Check call succeeded.
> 
>             return Ok(());
> ```

Move Ayelet's TODO to a Monday task instead. x2



_Suggestion:_
```XML
            let (_tx_execution_info, _bouncer_info) = self.execute(account_tx)?;
            return Ok(());
```
___
*[`crates/blockifier/src/blockifier/validator.rs` line 115 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjirZZAD3h0LYvkrD2:-NtjirZZAD3h0LYvkrD3:b-ev7vlp) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L115)):*
> ```XML
>     }
> 
>     pub fn create_for_testing(
> ```

Consider marking as `cfg testing`.



_Suggestion:_
```XML
pub(crate)
```
___
*[`crates/blockifier/src/blockifier/validator.rs` line 130 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjjzLn8YjWKpAoccoc:-NtjjzLn8YjWKpAoccod:b8p8zy6) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L130)):*
> ```XML
>             VersionedConstants::latest_constants(),
>         );
>         // TODO(Yael 24/01/24): calc block_context using pre_process_block
> ```

These too, should be moved to Monday. x2



_Code quote:_
```XML
// TODO(Yael 24/01/24): calc block_context using pre_process_block
```


<!-- Sent from Reviewable.io -->

2024-03-24 11:39 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1678)* status: 2 of 9 files reviewed, 13 unresolved discussions (waiting on @ArniStarkware and @elintul)

___
*[`crates/blockifier/src/blockifier/validator.rs` line 130 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjjzLn8YjWKpAoccoc:-NtkFZbE0yNKjsRWNxgA:b-p2wdqg) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L130)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

These too, should be moved to Monday. x2
</blockquote></details>

already there : https://starkware.monday.com/boards/5536734411/pulses/5945099530


<!-- Sent from Reviewable.io -->

2024-03-24 12:13 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1678)* status: 2 of 9 files reviewed, 13 unresolved discussions (waiting on @ArniStarkware)



<!-- Sent from Reviewable.io -->

2024-03-24 12:14 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1678)* status: 2 of 9 files reviewed, 13 unresolved discussions (waiting on @ArniStarkware and @Yael-Starkware)

___
*[`crates/blockifier/src/blockifier/validator.rs` line 130 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjjzLn8YjWKpAoccoc:-NtkNNIM8JnAhJRp3BGT:b-ygiowc) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L130)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

already there : https://starkware.monday.com/boards/5536734411/pulses/5945099530
</blockquote></details>

Then no need to leave in code, since you're probably won't be the one implementing. :)


<!-- Sent from Reviewable.io -->

2024-03-24 12:15 UTC, Yael-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1678)* status: 2 of 9 files reviewed, 13 unresolved discussions (waiting on @ArniStarkware and @elintul)

___
*[`crates/blockifier/src/blockifier/validator.rs` line 130 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjjzLn8YjWKpAoccoc:-NtkNhpv-CkWshukweEm:b-29zxyr) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L130)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Then no need to leave in code, since you're probably won't be the one implementing. :)
</blockquote></details>

:+1::skin-tone-3:


<!-- Sent from Reviewable.io -->

2024-03-24 13:18 UTC, elintul reviewed
> Reviewed 2 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1678)* status: 4 of 9 files reviewed, 13 unresolved discussions (waiting on @ArniStarkware)



<!-- Sent from Reviewable.io -->

2024-03-24 13:38 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1678)* status: 2 of 9 files reviewed, 5 unresolved discussions (waiting on @elintul and @Yael-Starkware)

___
*[`crates/blockifier/src/blockifier/validator.rs` line 1 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjbaKyCbOY8lq1d5jS:-NtjygVj5ekKLF6bV6PS:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L1)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider renaming to `StatefulValidator` (file as well); validator is too generic.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/validator.rs` line 22 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-Ntjd1I18lrWb_wc3Va1:-NtkNhyW1UNqf-jgft0R:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L22)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please alphabetize.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/validator.rs` line 31 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjgzD56vRq3lkszP_a:-Ntkasyy4K5XIzO8D7jR:b-ad4gwo) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L31)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is it needed?
</blockquote></details>

Done.  The issue was that I misunderstood `Execution` vs `Executor`.


Writing this for the record: Please ignore this discussion of me with myself if you like how the code is.
about `Execution` vs `Executor`
We can wrap each `TransactionExecutionError` into a `TransactionExecutorError` (writing this comment made me realize that leaving the code as submitted here is best - Some errors are of the execution. Not all execution errors pass through the executor. Also, there are errors of the executor that are unrelated to execution).

https://github.com/starkware-libs/blockifier/blob/301ec5e1bb88399ffb9f67f4954653c3e72d940f/crates/blockifier/src/blockifier/transaction_executor.rs#L31-L37
___
*[`crates/blockifier/src/blockifier/validator.rs` line 42 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-Ntjh9xa1G8npYXN8iK6:-NtkNms6AhHcygFveB7Z:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L42)):*
> ```XML
> pub struct Validator<S: StateReader> {
>     pub max_nonce_for_validation_skip: Nonce,
>     pub tx_executor: TransactionExecutor<S>,
> ```

Done.
___
*[`crates/blockifier/src/blockifier/validator.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjhDV10PSnC60prmnJ:-NtkO8JHBrSEgkf5BZca:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L49)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move down.
We should think of bundling those in a more natural struct; please add a TODO.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/validator.rs` line 64 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-Ntji9Rt-nDkWTyKmu6s:-NtkOQzE6aw4Gi7UuByA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L64)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move up, above those arguments.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/validator.rs` line 71 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjiC5i0sgFn3gnPpFZ:-NtkOYrR6L6yqCIwTTEq:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L71)):*
> ```XML
>         let validator = Self { max_nonce_for_validation_skip, tx_executor };
> 
>         Ok(validator)
> ```

Done.
___
*[`crates/blockifier/src/blockifier/validator.rs` line 76 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjiLa10LJyksWqSu7T:-NtkOnEl2TeKaWLC_x-J:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L76)):*
> ```XML
>     pub fn perform_validations(
>         &mut self,
>         account_tx: AccountTransaction,
> ```

Done.
___
*[`crates/blockifier/src/blockifier/validator.rs` line 77 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjiQhi0W4vTYpGTlpE:-NtkPxk17Lz27qLok-Hf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L77)):*
> ```XML
>         &mut self,
>         account_tx: AccountTransaction,
>         deploy_account_tx_hash: Option<StarkFelt>,
> ```

Done.
___
*[`crates/blockifier/src/blockifier/validator.rs` line 87 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjiYcb6mMMkwHghZi2:-NtkZHWU8KQpBD3Gifra:bzcnn44) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L87)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move Ayelet's TODO to a Monday task instead. x2
</blockquote></details>

Done. See: https://starkware.monday.com/boards/5536734411/pulses/6318033163
___
*[`crates/blockifier/src/blockifier/validator.rs` line 115 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjirZZAD3h0LYvkrD2:-NtkQaf18Sm-Ez35daTQ:b-8iwzor) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L115)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider marking as `cfg testing`.
</blockquote></details>

The use of this function is not from within the same `crate`

The `StatefulValidator` is in `blockifier`.
It is used in the `create_for_testing` method of `PyValidator` in `native_blockifier`.

Does that mean this is not really a `create_for_testing` method? Or does this code belong in `PyValidator`?
___
*[`crates/blockifier/src/blockifier/validator.rs` line 130 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjjzLn8YjWKpAoccoc:-NtkVAjn5sDWyTGQaiHW:b-wnfmk9) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L130)):*
<details><summary><i>Previously, Yael-Starkware (YaelD) wrote…</i></summary><blockquote>

:+1::skin-tone-3:
</blockquote></details>

Done. Removed.


<!-- Sent from Reviewable.io -->

2024-03-24 13:53 UTC, ArniStarkware reviewed
A refactor of the stateful transaction validator.

Motivation: We want to use this module in the mempool. We separate the logic of the Validator from the PyObject implementation.

In this PR:
1. We create a new file: `stateful_validator.rs`, and move into it the logic of the validator.
2. We create a new error enum: `StatefulValidatorError`. This transparent error holds everything that might go wrong while running the validator. Note that before this refactor, all these errors were converted into `NativeBlockifierError`.
3. We write an implementation that converts Each `StatefulValidatorError` into a `NativeBlockifierError`, as the Native blockifier was not refactored as a part of this PR.
4. The public functions of the StatefulValidator are: `create` and `perform_validations`

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-:-NtkgFaQ9yCb-kgunG9f:bg4foma)* status: 2 of 9 files reviewed, 5 unresolved discussions (waiting on @elintul and @Yael-Starkware)

___
*[`crates/blockifier/src/blockifier/validator.rs` line 115 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjirZZAD3h0LYvkrD2:-NtkizCB0l_UWNehThJO:b2jvs8h) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L115)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

The use of this function is not from within the same `crate`

The `StatefulValidator` is in `blockifier`.
It is used in the `create_for_testing` method of `PyValidator` in `native_blockifier`.

Does that mean this is not really a `create_for_testing` method? Or does this code belong in `PyValidator`?
</blockquote></details>

Do we want `create_for_testing` to be a part of the public API?


<!-- Sent from Reviewable.io -->

2024-03-25 08:27 UTC, dafnamatsry reviewed
> Reviewed 1 of 7 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1678)* status: all files reviewed, 7 unresolved discussions (waiting on @ArniStarkware, @elintul, and @Yael-Starkware)

___
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 36 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtoXr7R8IJFaU2w4APY:-NtoXr7R8IJFaU2w4APZ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/cdd5839da2bb9dd4b5c868fce7e64060fe00f614/crates/blockifier/src/blockifier/stateful_validator.rs#L36)):*
> ```XML
> pub type StatefulValidatorResult<T> = Result<T, StatefulValidatorError>;
> 
> /// Manages transaction validation for pre-execution flows.
> ```





_Suggestion:_
```XML
state related validations
```
___
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 45 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtocKQj6zh8bpkETOPn:-NtocKQj6zh8bpkETOPo:bkgkc3d) ([raw file](https://github.com/starkware-libs/blockifier/blob/cdd5839da2bb9dd4b5c868fce7e64060fe00f614/crates/blockifier/src/blockifier/stateful_validator.rs#L45)):*
> ```XML
>     pub fn create(
>         state_reader: S,
>         max_nonce_for_validation_skip: Nonce,
> ```

Can this also be part of the configurations struct mentioned in the TODO below?


<!-- Sent from Reviewable.io -->

2024-03-25 11:16 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1678)* status: 6 of 9 files reviewed, 7 unresolved discussions (waiting on @dafnamatsry, @elintul, and @Yael-Starkware)

___
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 36 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtoXr7R8IJFaU2w4APY:-NtpHphy4l6GjuLIyjBI:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cdd5839da2bb9dd4b5c868fce7e64060fe00f614/crates/blockifier/src/blockifier/stateful_validator.rs#L36)):*
> ```XML
> pub type StatefulValidatorResult<T> = Result<T, StatefulValidatorError>;
> 
> /// Manages transaction validation for pre-execution flows.
> ```

Done.
___
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 45 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtocKQj6zh8bpkETOPn:-NtpIcTMAzx_UFOTayoE:b98jfmf) ([raw file](https://github.com/starkware-libs/blockifier/blob/cdd5839da2bb9dd4b5c868fce7e64060fe00f614/crates/blockifier/src/blockifier/stateful_validator.rs#L45)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Can this also be part of the configurations struct mentioned in the TODO below?
</blockquote></details>

In the main repo, this value came from a blockifier validator config. https://github.com/starkware-industries/starkware/blob/0f38c76deb14afe964a10809cb1d82fb4ce166d8/src/starkware/starknet/business_logic/blockifier/blockifier.py#L461


<!-- Sent from Reviewable.io -->

2024-03-25 11:44 UTC, ArniStarkware commented
*[`crates/native_blockifier/src/errors.rs` line 79 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtpQ8ci1C549BFMULjw:-NtpQ8ci1C549BFMULjx:bc3iksn) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f79c568ee8938f18d849ada972108b1d4661b4a/crates/native_blockifier/src/errors.rs#L79)):*
> ```XML
> 
> // TODO(Arni, 21/3/2024): Add ValidatorError to the enum NativeBlockifierError and remove this
> // implementation.
> ```

TODO is addressed here: #1713.



_Code quote:_
```XML
// TODO(Arni, 21/3/2024): Add ValidatorError to the enum NativeBlockifierError and remove this
// implementation.
```


<!-- Sent from Reviewable.io -->

2024-03-25 11:59 UTC, ArniStarkware commented
*[`crates/native_blockifier/src/errors.rs` line 79 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtpQ8ci1C549BFMULjw:-NtpTa5t0YBo2IzX08cc:bqdnpdr) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f79c568ee8938f18d849ada972108b1d4661b4a/crates/native_blockifier/src/errors.rs#L79)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

TODO is addressed here: #1713.
</blockquote></details>

Should we just squash that PR into this PR?


<!-- Sent from Reviewable.io -->

2024-03-25 12:39 UTC, ArniStarkware commented
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 107 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtpbjBuBD8E70q_KAyq:-NtpbjBuBD8E70q_KAyr:b-vh2zt4) ([raw file](https://github.com/starkware-libs/blockifier/blob/b7fb1901131b104431d5aa032403af59bc3b5a46/crates/blockifier/src/blockifier/stateful_validator.rs#L107)):*
> ```XML
>     }
> 
>     // TODO(Arni, 30/04/2024): Use the create method to implement create_for_testing.
> ```

See: #1714



_Code quote:_
```XML
    // TODO(Arni, 30/04/2024): Use the create method to implement create_for_testing.
```


<!-- Sent from Reviewable.io -->

2024-03-25 13:51 UTC, ArniStarkware commented
*[`crates/blockifier/src/blockifier/validator.rs` line 31 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjgzD56vRq3lkszP_a:-NtpsMJa0rzKh4c2LKV-:b-9c5ixc) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L31)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.  The issue was that I misunderstood `Execution` vs `Executor`.


Writing this for the record: Please ignore this discussion of me with myself if you like how the code is.
about `Execution` vs `Executor`
We can wrap each `TransactionExecutionError` into a `TransactionExecutorError` (writing this comment made me realize that leaving the code as submitted here is best - Some errors are of the execution. Not all execution errors pass through the executor. Also, there are errors of the executor that are unrelated to execution).

https://github.com/starkware-libs/blockifier/blob/301ec5e1bb88399ffb9f67f4954653c3e72d940f/crates/blockifier/src/blockifier/transaction_executor.rs#L31-L37
</blockquote></details>

Please ignore the previous message. Done. 


<!-- Sent from Reviewable.io -->

2024-03-26 06:48 UTC, ArniStarkware commented
*[`crates/blockifier/src/blockifier/validator.rs` line 115 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-NtjirZZAD3h0LYvkrD2:-NttW5Bo-eaVbnpjCgJv:bveiw7i) ([raw file](https://github.com/starkware-libs/blockifier/blob/7cee00791c6ce106143aa22360e6967dfb5345e0/crates/blockifier/src/blockifier/validator.rs#L115)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Do we want `create_for_testing` to be a part of the public API?
</blockquote></details>

No longer relevant.
The method was removed in: #1716 


<!-- Sent from Reviewable.io -->

2024-03-27 13:46 UTC, giladchase requested changes
> Reviewed 1 of 7 files at r7, 1 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1678)* status: 7 of 9 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, @elintul, and @Yael-Starkware)

___
*[`crates/native_blockifier/src/errors.rs` line 95 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-Nu-16jF98mcpe48InVy:-Nu-16jF98mcpe48InVz:bis5ypo) ([raw file](https://github.com/starkware-libs/blockifier/blob/06849633ed2701852d2c559bb9c59123807977ae/crates/native_blockifier/src/errors.rs#L95)):*
> ```XML
>         }
>     }
> }
> ```

Can you utilize thiserror's `#[from]` for these?
You might need to look at `native_blockifier_errors!`, which generates the `NativeBlockifierError` enum with these `From`'s pre-loaded.



_Code quote:_
```XML
impl From<StatefulValidatorError> for NativeBlockifierError {
    fn from(error: StatefulValidatorError) -> Self {
        match error {
            StatefulValidatorError::StateError(error) => NativeBlockifierError::StateError(error),
            StatefulValidatorError::TransactionExecutorError(error) => {
                NativeBlockifierError::TransactionExecutorError(error)
            }
            StatefulValidatorError::TransactionExecutionError(error) => {
                NativeBlockifierError::TransactionExecutionError(error)
            }
            StatefulValidatorError::TransactionPreValidationError(error) => {
                NativeBlockifierError::TransactionPreValidationError(error)
            }
        }
    }
}
```
___
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 52 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-Ntym-CJBMnYXnjdfwVn:-Ntym-CJBMnYXnjdfwVo:bru3o5k) ([raw file](https://github.com/starkware-libs/blockifier/blob/9a3e8057d1883969f4cacbba9e3341038cf4d217/crates/blockifier/src/blockifier/stateful_validator.rs#L52)):*
> ```XML
>         max_recursion_depth: usize,
>         global_contract_cache_size: usize,
>         max_nonce_for_validation_skip: Nonce,
> ```

Unrelated to this PR, but i think some of these can be removed and have this take a BlockContext.
It'll incliude block_info, chain_info and versioned_constants, where the latter that includes other args.



_Code quote:_
```XML
        state_reader: S,
        // TODO(Arni, 30/04/2024): Get block_info and chain_info from the most logical place.
        block_info: BlockInfo,
        chain_info: ChainInfo,
        // TODO(Arni, 30/04/2024): Consider bundling these variables into a struct.
        validate_max_n_steps: u32,
        max_recursion_depth: usize,
        global_contract_cache_size: usize,
        max_nonce_for_validation_skip: Nonce,
```
___
*[`crates/blockifier/src/blockifier/stateful_validator.rs` line 2 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/1678#-Nu-96ce3l4X20LpE76G:-Nu-96ce3l4X20LpE76H:b31ro1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/06849633ed2701852d2c559bb9c59123807977ae/crates/blockifier/src/blockifier/stateful_validator.rs#L2)):*
> ```XML
> use starknet_api::core::Nonce;
> use starknet_api::hash::StarkFelt;
> ```

Can you plz denote what changes were made here?
I gather that most of the diff here is just due to the file rename, but there are also new additions


<!-- Sent from Reviewable.io -->

2024-03-28 11:46 UTC, ArniStarkware commented
Replaced with #1733

2024-03-28 11:46 UTC, closed without merging