feat(execution): implement commit chunk method
starkware-libs/blockifier pull request #1680
Opened 2024-03-18 12:12 UTC by MohammadNassar1

2024-04-17 13:49 UTC, Yoni-Starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

___
*[`.vscode/settings.json` line 26 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvgGMR9-n0OcF1Mgls0:-NvgGMR9-n0OcF1Mgls1:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/.vscode/settings.json#L26)):*
> ```JSON
>     "rust-analyzer.linkedProjects": [
>         "./crates/blockifier/Cargo.toml"
>     ]
> ```

?



_Code quote:_
```JSON
    "rust-analyzer.linkedProjects": [
        "./crates/blockifier/Cargo.toml"
    ]
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 45 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvgHBgSE07N2sp28h3S:-NvgHBgSE07N2sp28h3T:b8vkrvm) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L45)):*
> ```XML
>     }
> 
>     pub fn commit_chunk<T>(&mut self, upper_index: TxIndex, block_state: &mut CachedState<T>)
> ```

Add a short docstring



_Suggestion:_
```XML
pub fn commit<T>(&mut self, from_index: TxIndex, parent_state: &mut CachedState<T>)
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvgINC12Zgj31RHOnh1:-NvgINC12Zgj31RHOnh2:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L49)):*
> ```XML
>         T: StateReader,
>     {
>         // Storage
> ```





_Suggestion:_
```XML
// Storage.
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 51 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvgIJY5-7UOi2NgGbJ5:-NvgIJY5-7UOi2NgGbJ6:b-9yk3bs) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L51)):*
> ```XML
>         // Storage
>         for (&(contract_address, storage_key), _) in self.storage.get_writes().iter() {
>             let value = self.storage.read(upper_index, (contract_address, storage_key)).unwrap();
> ```

Why not `?`?



_Code quote:_
```XML
.unwrap()
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 65 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvgIwTPD0fUpnw9jtqG:-NvgIwTPD0fUpnw9jtqH:b-a6hhj7) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L65)):*
> ```XML
> 
>             for _ in 0..n_versions {
>                 block_state.increment_nonce(contract_address).unwrap();
> ```

I think we should add `set_nonce_at`
BTW, do you have access to the cache itself?



_Code quote:_
```XML
.increment_nonce(c
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 81 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvgJLHoAgRvMiVz-eiA:-NvgJLHoAgRvMiVz-eiB:b5uynkm) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L81)):*
> ```XML
> 
>         // Compiled class hash
>         for (&class_hash, _) in self.compiled_class_hashes.get_writes().iter() {
> ```

What's this?



_Code quote:_
```XML
_
```


<!-- Sent from Reviewable.io -->

2024-04-17 14:13 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 50 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvgOakF5tPvLZXKNatl:-NvgOakF5tPvLZXKNatm:b-2airhw) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L50)):*
> ```XML
>     {
>         // Storage
>         for (&(contract_address, storage_key), _) in self.storage.get_writes().iter() {
> ```

Can you iterate over the keys?



_Suggestion:_
```XML
.get_writes().keys()
```


<!-- Sent from Reviewable.io -->

2024-04-18 08:02 UTC, noaov1 requested changes
> Reviewed 2 of 4 files at r5, 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680)* status: 4 of 5 files reviewed, 9 unresolved discussions (waiting on @MohammadNassar1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 52 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvkA2Ha3N10x3gP5k2i:-NvkA2Ha3N10x3gP5k2j:b-txv79q) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L52)):*
> ```XML
>         for (&(contract_address, storage_key), _) in self.storage.get_writes().iter() {
>             let value = self.storage.read(upper_index, (contract_address, storage_key)).unwrap();
>             block_state.set_storage_at(contract_address, storage_key, value).unwrap();
> ```

Note- we can add a write of a non-written value:
Assume `upper_index = 50` and `tx_51` was the first to write to some storage key. Then we will write the initial value(in case a read was made) or get a `None` (in this case the `unwrap` is problematic) .
I guess it does not matter since we ignore it in the state diff. 
Is it possible to ignore it (ignore the writes after `upper_index`)? If not, consider adding a note.



_Code quote:_
```XML
            block_state.set_storage_at(contract_address, storage_key, value).unwrap();
```


<!-- Sent from Reviewable.io -->

2024-04-24 15:33 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 45 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvgHBgSE07N2sp28h3S:-NwFeJTn30_n9Lb1BQbc:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L45)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Add a short docstring
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvgINC12Zgj31RHOnh1:-NwFajXH9oQmDblRjBwR:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L49)):*
> ```XML
>         T: StateReader,
>     {
>         // Storage
> ```

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 50 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvgOakF5tPvLZXKNatl:-NwFbG-g0xyztguapleO:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L50)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you iterate over the keys?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 51 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvgIJY5-7UOi2NgGbJ5:-NwFbXeFBCSOUjrzSlYg:b-um791a) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L51)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why not `?`?
</blockquote></details>

The operator can only be used in a method that returns `Result`.
Here, we read the values for the second time; then, it retrieves the data from the cache and never returns an error.+
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 51 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-Nvjzaxg0l1I4wfK-iP1:-NwFdLAK4-tV_MVEdohY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L51)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think it should be `upper_index + 1` to include the write of `upper_index`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 52 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvkA2Ha3N10x3gP5k2i:-NwFj6PW7S0zr0rTDGAE:bkr49td) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L52)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Note- we can add a write of a non-written value:
Assume `upper_index = 50` and `tx_51` was the first to write to some storage key. Then we will write the initial value(in case a read was made) or get a `None` (in this case the `unwrap` is problematic) .
I guess it does not matter since we ignore it in the state diff. 
Is it possible to ignore it (ignore the writes after `upper_index`)? If not, consider adding a note.
</blockquote></details>

I think it will read the initial value and then be ignored in the state diff. So it's not problematic. Right?
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 65 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvgIwTPD0fUpnw9jtqG:-NwFdhZnEllbs7k6_jnd:betne6l) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L65)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I think we should add `set_nonce_at`
BTW, do you have access to the cache itself?
</blockquote></details>

There is no such interface in `state_api`.
Yeah, we have access to the state.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 81 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvgJLHoAgRvMiVz-eiA:-NwFddxx0eHsGzNKLysv:bgb2i1x) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L81)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

What's this?
</blockquote></details>

changed to keys().
___
*[`.vscode/settings.json` line 26 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvgGMR9-n0OcF1Mgls0:-NwFeEy51E-sCyb8tVJl:bss4a2b) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/.vscode/settings.json#L26)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

?
</blockquote></details>

Removed.


<!-- Sent from Reviewable.io -->

2024-04-25 09:06 UTC, Yoni-Starkware requested changes
> Reviewed 2 of 4 files at r5, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 51 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvgIJY5-7UOi2NgGbJ5:-NwJU8vH6sC-k5uwzVAt:b-sdj4xk) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L51)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

The operator can only be used in a method that returns `Result`.
Here, we read the values for the second time; then, it retrieves the data from the cache and never returns an error.+
</blockquote></details>

I see, you are right. But please use except + short message, as this is the convention I think
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 45 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NwJUc5J3HWcqpMEMBTp:-NwJUc5J3HWcqpMEMBTq:b-5hvkdf) ([raw file](https://github.com/starkware-libs/blockifier/blob/b35e169815ce759a9c6f93020fd8d61ccede47aa/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L45)):*
> ```XML
>     }
> 
>     pub fn commit<T>(&mut self, from_index: TxIndex, parent_state: &mut CachedState<T>)
> ```

Please define 
```rust
pub fn get_writes<T>(&mut self, from_index: TxIndex) -> StateMaps
```
and then, implement `commit` by calling
```
parent_state.update_cache(writes)
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 51 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NwJTt_y6uqEs8xG2GZt:-NwJTt_y6uqEs8xG2GZu:byr4fm0) ([raw file](https://github.com/starkware-libs/blockifier/blob/f17234dc5667057ff467d162d22885fb56a4ef46/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L51)):*
> ```XML
>     // object (probabily `VersionedState`). As RefCell operations are not thread-safe. Therefore,
>     // accessing this function should be protected by a mutex to ensure thread safety.
>     pub fn validate_read_set(&mut self, tx_index: TxIndex, state_cache: &mut StateCache) -> bool {
> ```

Right?



_Suggestion:_
```XML
state_cache: &StateCache
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 87 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NwJTYkcBk-bWWcU2wUM:-NwJTYkcBk-bWWcU2wUN:b-fulkv0) ([raw file](https://github.com/starkware-libs/blockifier/blob/b35e169815ce759a9c6f93020fd8d61ccede47aa/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L87)):*
> ```XML
> 
>         // Compiled contract class
>         for (&class_hash, _) in self.compiled_contract_classes.get_writes().iter() {
> ```

Also here



_Code quote:_
```XML
for (&class_hash, _) in self.compiled_contract_classes.get_writes().iter() {
```


<!-- Sent from Reviewable.io -->

2024-04-25 12:03 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 84 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NwK7d_SEOy4frdgkX6l:-NwK7d_T1hz_QzSZdbQJ:b-rppvvu) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a3ef75f61a3c345858643104400e6fd7db54455/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L84)):*
> ```XML
>     {
>         let writes = StateCache { writes: self.get_writes(from_index), ..Default::default() };
>         parent_state.update_cache(writes);
> ```

Change this function to get `writes: StateMaps` instead



_Code quote:_
```XML
update_cache(writes);
```


<!-- Sent from Reviewable.io -->

2024-04-25 12:42 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 52 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NwK6Z1SCHgWr9-3H-Qa:-NwKGocp9fXdzqswVp5P:b-3kepe4) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a3ef75f61a3c345858643104400e6fd7db54455/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L52)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

We can save a lot of code by defining this `get_writes(from_index)` in the storage level
</blockquote></details>

Great idea!
Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 84 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NwK7d_SEOy4frdgkX6l:-NwKEJnk0oZ12y8viz-4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a3ef75f61a3c345858643104400e6fd7db54455/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L84)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Change this function to get `writes: StateMaps` instead
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-25 12:51 UTC, Yoni-Starkware requested changes
> Reviewed 2 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 51 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NwKHlLR5poD_CxegoaH:-NwKHlLS9QynLI_XjnBd:b3oyxlc) ([raw file](https://github.com/starkware-libs/blockifier/blob/f114a828407fa784262fe98280f21aa556814290/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L51)):*
> ```XML
>         let compiled_class_hashes = self.compiled_class_hashes.get_writes_from_index(from_index);
> 
>         StateMaps { storage, nonces, class_hashes, compiled_class_hashes, ..Default::default() }
> ```

Please avoid using this and put here the last mapping explicitly. 
@OriStarkware should replace it with non-default map.
I want the compiler to fail if we add a new mapping to StateMaps and forget to update it here



_Code quote:_
```XML
, ..Default::default() }
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 63 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NwKIPuj3EQdyp8MyKmu:-NwKIPuj3EQdyp8MyKmv:b3kjdco) ([raw file](https://github.com/starkware-libs/blockifier/blob/f114a828407fa784262fe98280f21aa556814290/crates/blockifier/src/concurrency/versioned_storage.rs#L63)):*
> ```XML
>     pub(crate) fn get_writes(&self) -> &HashMap<K, BTreeMap<TxIndex, V>> {
>         &self.writes
>     }
> ```

Remove this; rename `get_writes_from_index` -> `get_writes`, and use it for the compiled classes as well, by calling `update_contract_class_cache`



_Code quote:_
```XML
    pub(crate) fn get_writes(&self) -> &HashMap<K, BTreeMap<TxIndex, V>> {
        &self.writes
    }
```


<!-- Sent from Reviewable.io -->

2024-04-25 13:18 UTC, Yoni-Starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 67 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NwKOyG-4EJf5ZMwgawv:-NwKOyG09J_EW-oTMJgO:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e57a99cc4f01fd2c110265a134ae50d4dc5da15f/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L67)):*
> ```XML
>         {
>             parent_state.set_contract_class(class_hash, contract_class).unwrap();
>         }
> ```





_Suggestion:_
```XML
        parent_state.update_contract_class_cache(self.compiled_contract_classes.get_writes(from_index));
```


<!-- Sent from Reviewable.io -->

2024-04-25 13:19 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 51 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NwKHlLR5poD_CxegoaH:-NwKK65xBdn1fks_yaZW:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f114a828407fa784262fe98280f21aa556814290/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L51)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Please avoid using this and put here the last mapping explicitly. 
@OriStarkware should replace it with non-default map.
I want the compiler to fail if we add a new mapping to StateMaps and forget to update it here
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 63 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NwKIPuj3EQdyp8MyKmu:-NwKPGwM8omEV9AhJvNA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f114a828407fa784262fe98280f21aa556814290/crates/blockifier/src/concurrency/versioned_storage.rs#L63)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Remove this; rename `get_writes_from_index` -> `get_writes`, and use it for the compiled classes as well, by calling `update_contract_class_cache`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-25 15:35 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 67 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NwKOyG-4EJf5ZMwgawv:-NwKsmkp6poIY4YRLmNJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e57a99cc4f01fd2c110265a134ae50d4dc5da15f/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L67)):*
> ```XML
>         {
>             parent_state.set_contract_class(class_hash, contract_class).unwrap();
>         }
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-04-25 15:49 UTC, Yoni-Starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r11, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-:-NwKwVI0Bxm7R6TMYJZ_:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 51 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NwKw_Nx9T5kdv4f9lse:-NwKw_Nx9T5kdv4f9lsf:b37osax) ([raw file](https://github.com/starkware-libs/blockifier/blob/3027e324bd1f24c75aa45ee4ffef2a7a1e34b40a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L51)):*
> ```XML
>             class_hashes: self.class_hashes.get_writes_from_index(from_index),
>             compiled_class_hashes: self.compiled_class_hashes.get_writes_from_index(from_index),
>             declared_contracts: HashMap::new(),
> ```

@OriStarkware FYI (you need to complete this)


<!-- Sent from Reviewable.io -->

2024-04-27 13:08 UTC, noaov1 requested changes
> Reviewed 1 of 2 files at r7, 1 of 3 files at r9, 1 of 2 files at r11, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680)* status: all files reviewed, 5 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 52 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvkA2Ha3N10x3gP5k2i:-NwUaHQP-1H41kZl0_tU:b-f9zefd) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L52)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I think it will read the initial value and then be ignored in the state diff. So it's not problematic. Right?
</blockquote></details>

It will not necessarily be in the initial values (if no previous transaction read this cell, or a read was done after the write), no?
I think that the `expect` below can panic.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 45 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NwU_tT_DukxCeP07wwE:-NwU_tT_DukxCeP07wwF:bqsqghl) ([raw file](https://github.com/starkware-libs/blockifier/blob/3027e324bd1f24c75aa45ee4ffef2a7a1e34b40a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L45)):*
> ```XML
>     }
> 
>     pub fn get_writes(&mut self, from_index: TxIndex) -> StateMaps {
> ```

Why did we chose `from_index`? What does the from stands for?



_Code quote:_
```XML
    pub fn get_writes(&mut self, from_index: TxIndex) -> StateMaps {
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 63 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NwUdloa-E3COShDVsse:-NwUdloa-E3COShDVssf:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/3027e324bd1f24c75aa45ee4ffef2a7a1e34b40a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L63)):*
> ```XML
> 
>         // Update the contract class cache.
>         parent_state.update_contract_class_cache(
> ```





_Suggestion:_
```XML
        parent_state.update_cache(writes);
        parent_state.update_contract_class_cache(
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 65 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NwUaYNP8-GcVWJcTypD:-NwUaYNP8-GcVWJcTypE:b51kifk) ([raw file](https://github.com/starkware-libs/blockifier/blob/3027e324bd1f24c75aa45ee4ffef2a7a1e34b40a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L65)):*
> ```XML
>         parent_state.update_contract_class_cache(
>             self.compiled_contract_classes.get_writes_from_index(from_index),
>         );
> ```

@Yoni-Starkware - we need to think of when we update the visited pcs cache. 


<!-- Sent from Reviewable.io -->

2024-04-28 08:22 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 52 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvkA2Ha3N10x3gP5k2i:-NwYlfiq2r5X2hptS4ed:b-uqzq19) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L52)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It will not necessarily be in the initial values (if no previous transaction read this cell, or a read was done after the write), no?
I think that the `expect` below can panic.
</blockquote></details>

Good point!
The code was updated.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 45 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NwU_tT_DukxCeP07wwE:-NwYdZfZBU5iqHXRFM_-:bdocgm8) ([raw file](https://github.com/starkware-libs/blockifier/blob/3027e324bd1f24c75aa45ee4ffef2a7a1e34b40a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L45)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why did we chose `from_index`? What does the from stands for?
</blockquote></details>

It says that the function will start fetching the writes `from` the specified `index`.


<!-- Sent from Reviewable.io -->

2024-04-30 04:58 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 52 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvkA2Ha3N10x3gP5k2i:-NwhL9y20CE0JI1JyRby:bmhzwrq) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L52)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Good point!
The code was updated.
</blockquote></details>

(Actually, without bugs, the initial value must always be cached)
@MohammadNassar1 can you include just concrete writes, without initial values?
E.g., share this code
```rust
        let value = self.writes.get(&key).and_then(|cell| cell.range(..tx_index).next_back());
        value.map(|(_, value)| value)

```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 65 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NwUaYNP8-GcVWJcTypD:-NwhL3pZ7Bv6ojW7kqLB:b1ijenh) ([raw file](https://github.com/starkware-libs/blockifier/blob/3027e324bd1f24c75aa45ee4ffef2a7a1e34b40a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L65)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

@Yoni-Starkware - we need to think of when we update the visited pcs cache.
</blockquote></details>

Right :) added to monday


<!-- Sent from Reviewable.io -->

2024-04-30 06:14 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 52 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-NvkA2Ha3N10x3gP5k2i:-NwhcrAY768rwHPGnKOb:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/75dc5baec74f850eb82a677c10c1ff7204a72d9a/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L52)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

(Actually, without bugs, the initial value must always be cached)
@MohammadNassar1 can you include just concrete writes, without initial values?
E.g., share this code
```rust
        let value = self.writes.get(&key).and_then(|cell| cell.range(..tx_index).next_back());
        value.map(|(_, value)| value)

```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-30 06:20 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 66 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-Nwhe5Cd4UGDWWoCmMgh:-Nwhe5Cd4UGDWWoCmMgi:b3kqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/9d3095be74a385c191d6a5ae5d9f2dbd27571302/crates/blockifier/src/concurrency/versioned_storage.rs#L66)):*
> ```XML
>             if let Some(value) =
>                 self.writes.get(&key).and_then(|cell| cell.range(..=from_index).next_back())
>             {
> ```

.



_Suggestion:_
```XML
        for (&key, &cell) in self.writes.iter() {
            if let Some(value) = cell.range(..=from_index).next_back())
            {
```


<!-- Sent from Reviewable.io -->

2024-04-30 06:25 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 66 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-Nwhe5Cd4UGDWWoCmMgh:-NwhfReZB3ebNhxT6ljn:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9d3095be74a385c191d6a5ae5d9f2dbd27571302/crates/blockifier/src/concurrency/versioned_storage.rs#L66)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-30 06:40 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r14, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-:-Nwhj-SBCJmfuNQD5rg6:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-04-30 06:56 UTC, noaov1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r14, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1680#-:-NwhmJXV-IcCe9q_Dbf8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2024-04-30 06:58 UTC, merged