test(concurrency): add versioned state proxy flow test
starkware-libs/blockifier pull request #1748
Opened 2024-04-01 14:26 UTC by MohammadNassar1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1748)

2024-04-02 14:24 UTC, barak-b-starkware requested changes
Hi, I have some thoughts:
1. IMO, it's not a flow test. It's a test for `validate_read_set`, which we do need.
2. I suggest redesigning it into a unit test with several flows (using `cases` if possible): the happy flow, the "re-execution flow", the tx zero flow, etc.
3. At this point, I think the flow test can be simpler (only happy flow) and more straightforward.
4. Suggest not adding the `Clone` derivation rather than changing the read- and write-sets abstraction (implementing a new `CachedState` for the concurrency project.

Let's discuss it offline and think together about how we proceed, I put some comments but ignored the "heart" of the test for now.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-:-NuTkrU093Oc1x0NNrr4:b-f0v25a)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NuTbbPjEeCJI-yN25RE):*




_Suggestion:_
```
Test(concurrency)
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NuTd88iAb4wpTGcfXdJ:-NuTd88iAb4wpTGcfXdK:bgzle7l) ([raw file](https://github.com/starkware-libs/blockifier/blob/83b8b6dfb4b3a9e70b02ce7c8f80ac8106609d57/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L223)):*
> ```XML
>         CachedState::from(DictStateReader { address_to_class_hash, ..Default::default() });
>     Arc::new(Mutex::new(VersionedState::new(cached_state)))
> }
> ```

Move to `crates/blockifier/src/test_utils/struct_impls.rs`



_Suggestion:_
```XML
fn versioned_state_for_testing(
    initial_state: impl StateReader,
) -> Arc<Mutex<VersionedState<CachedState<DictStateReader>>>> {
    Arc::new(Mutex::new(VersionedState::new(initial_state)))
}
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 228 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NuTfWeo53wxUGX0MkLA:-NuTfWeo53wxUGX0MkLB:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/83b8b6dfb4b3a9e70b02ce7c8f80ac8106609d57/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L228)):*
> ```XML
>     let contract_address = contract_address!("0x1");
>     let init_class_hash = ClassHash(stark_felt!(27_u8));
>     let versioned_state = versioned_state_for_testing(contract_address, init_class_hash);
> ```





_Suggestion:_
```XML
    let address_to_class_hash = HashMap::from(contract_address!("0x1"), ClassHash(stark_felt!(27_u8)));
    let initial_state = CachedState::from(....);
    let versioned_state = versioned_state_for_testing(initial_state);
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 239 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NuTj4c25A-mkzGyKHUG:-NuTj4c25A-mkzGyKHUH:bq6b7n5) ([raw file](https://github.com/starkware-libs/blockifier/blob/83b8b6dfb4b3a9e70b02ce7c8f80ac8106609d57/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L239)):*
> ```XML
>     transactional_states[1].get_nonce_at(contract_address).unwrap();
> 
>     transactional_states[1].get_actual_state_changes().unwrap();
> ```

Should be in some unit test that checks the correctness and validity of the creation of the transactional state?



_Code quote:_
```XML
    transactional_states[1].get_class_hash_at(contract_address).unwrap();
    transactional_states[1].get_nonce_at(contract_address).unwrap();

    transactional_states[1].get_actual_state_changes().unwrap();
```


<!-- Sent from Reviewable.io -->

2024-04-16 14:21 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NuTbbPjEeCJI-yN25RE):*
Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NuTd88iAb4wpTGcfXdJ:-NvbGMQfAm1pRV17Srx0:b-moyhfa) ([raw file](https://github.com/starkware-libs/blockifier/blob/83b8b6dfb4b3a9e70b02ce7c8f80ac8106609d57/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L223)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Move to `crates/blockifier/src/test_utils/struct_impls.rs`
</blockquote></details>

When creating different versioned states, I use an argument to avoid duplicating the code for creating `stateReader`.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 228 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NuTfWeo53wxUGX0MkLA:-NvbGmZs1gTpnlyxts_-:b71wco4) ([raw file](https://github.com/starkware-libs/blockifier/blob/83b8b6dfb4b3a9e70b02ce7c8f80ac8106609d57/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L228)):*
> ```XML
>     let contract_address = contract_address!("0x1");
>     let init_class_hash = ClassHash(stark_felt!(27_u8));
>     let versioned_state = versioned_state_for_testing(contract_address, init_class_hash);
> ```

See above.
I think the current code reduces duplication.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 239 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NuTj4c25A-mkzGyKHUG:-NvbG6fi-QYRnwtacjoS:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/83b8b6dfb4b3a9e70b02ce7c8f80ac8106609d57/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L239)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Should be in some unit test that checks the correctness and validity of the creation of the transactional state?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-17 05:19 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NuTbbPjEeCJI-yN25RE):*
Done.


<!-- Sent from Reviewable.io -->

2024-04-18 08:19 UTC, barak-b-starkware requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: all files reviewed, 19 unresolved discussions (waiting on @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-Nvk-5W77lDvYt-KtaxQ):*




_Suggestion:_
```
test(concurrency): add versioned state proxy tests
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NuTd88iAb4wpTGcfXdJ:-Nvk14Uk5AxDnOmtHLfI:b-6u384s) ([raw file](https://github.com/starkware-libs/blockifier/blob/83b8b6dfb4b3a9e70b02ce7c8f80ac8106609d57/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L223)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

When creating different versioned states, I use an argument to avoid duplicating the code for creating `stateReader`.
</blockquote></details>

The point is that the `DictStateReader` has 5 fields (and not only the `address_to_class_hash`) so this generalization will not end here. I suggest creating a macro as a test util to allow the creation of `VersionedState` with different state readers or a macro as a test util for the `DictStateReader`.
WDYT? (It can be added as a TODO here) I feel that the current form of this util lacks some indirections. 

To save code duplication in this file, you can add a fixture that does what the comment below suggests:
```
    let address_to_class_hash = HashMap::from(contract_address!("0x1"), ClassHash(stark_felt!(27_u8)));
    let initial_state = CachedState::from(....);
    let versioned_state = versioned_state_for_testing(initial_state);
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 225 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-Nvk4KG18S1RSAArs2Uo:-Nvk4KG18S1RSAArs2Up:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L225)):*
> ```XML
> }
> 
> #[test]
> ```





_Suggestion:_
```XML
use rstest:{fixture, rstest};
.
.
.
#[rstest]
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 240 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkD7mA5oJf7wxIRRAG:-NvkD7mA5oJf7wxIRRAH:b-6u583) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L240)):*
> ```XML
>             .lock()
>             .unwrap()
>             .validate_read_set(0, transactional_state.cache.borrow().clone())
> ```

The transactional state was pinned with version number 1. I would expect it to fail.
Add a TODO above `validate_read_set` to couple the tx_index and the read set so that passing incompatible tx index and read set would fail the validation.



_Code quote:_
```XML
.validate_read_set(0, transactional_state.cache.borrow().clone())
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 243 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkBXcH6M9bjactGyI-:-NvkBXcH6M9bjactGyI0:b-qefs9u) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L243)):*
> ```XML
>     );
> 
>     transactional_state.get_storage_at(contract_address, storage_key).unwrap();
> ```

Before and after each "get" call, add an assertion to show the reader what was empty before and that it's not empty after.



_Suggestion:_
```XML
assert(show something is empty)
transactional_state.get_storage_at(contract_address, storage_key).unwrap();
assert(show that some "set_initial.." took action)
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 246 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkB2n89TfiOTJMMt-Y:-NvkB2n89TfiOTJMMt-Z:bd4nhdb) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L246)):*
> ```XML
>     transactional_state.get_class_hash_at(contract_address).unwrap();
>     transactional_state.get_nonce_at(contract_address).unwrap();
>     transactional_state.get_compiled_class_hash(class_hash).unwrap();
> ```

Is it relevant to add the last one?



_Suggestion:_
```XML
    transactional_state.get_storage_at(contract_address, storage_key).unwrap();
    transactional_state.get_class_hash_at(contract_address).unwrap();
    transactional_state.get_nonce_at(contract_address).unwrap();
    transactional_state.get_compiled_class_hash(class_hash).unwrap();
    transactional_state.get_compiled_contract_class(class_hash).unwrap();
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 248 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkAn5QCXiwq4HdC1hV:-NvkAn5REu2UWPI21Ks-:b9v5q25) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L248)):*
> ```XML
>     transactional_state.get_compiled_class_hash(class_hash).unwrap();
> 
>     transactional_state.get_actual_state_changes().unwrap();
> ```

Why is it needed? Does it intrigue some "set_initial..." that was not intrigued before? Tx level or chunk level? 



_Code quote:_
```XML
transactional_state.get_actual_state_changes().unwrap();
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 257 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkGpp-AyRoJuMG6_s0:-NvkGpp-AyRoJuMG6_s1:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L257)):*
> ```XML
> }
> 
> #[test]
> ```





_Suggestion:_
```XML
#[rstest]
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 266 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkF66uDHq1dchGPn1v:-NvkF66uDHq1dchGPn1w:b-pmein3) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L266)):*
> ```XML
>     let mut transactional_states: Vec<
>         CachedState<VersionedStateProxy<CachedState<DictStateReader>>>,
>     > = (0..2).map(|i| CachedState::from(safe_versioned_state.pin_version(i))).collect();
> ```

Use this pattern to create two different txs in the `test_validate_read_set` as well.
Since the "0" tx is not really needed there, add a comment that it should be checked once the tx index and the read set will be coupled somehow.



_Code quote:_
```XML
    let mut transactional_states: Vec<
        CachedState<VersionedStateProxy<CachedState<DictStateReader>>>,
    > = (0..2).map(|i| CachedState::from(safe_versioned_state.pin_version(i))).collect();
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 272 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkGJZ249y59T1QbRC0:-NvkGJZ249y59T1QbRC1:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L272)):*
> ```XML
>     transactional_states[0].set_class_hash_at(contract_address, class_hash_0).unwrap();
> 
>     versioned_state.lock().unwrap().apply_writes(
> ```





_Suggestion:_
```XML
    transactional_states[0].set_class_hash_at(contract_address, class_hash_0).unwrap();
    assert(show that it's still empty)
    versioned_state.lock().unwrap().apply_writes(
```
___
*[`crates/blockifier/src/concurrency/ve [...]

2024-04-25 15:20 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: 0 of 2 files reviewed, 19 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-Nvk-5W77lDvYt-KtaxQ):*
Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NuTd88iAb4wpTGcfXdJ:-NwKUodYBmuWwfwnm3-V:bchhr5r) ([raw file](https://github.com/starkware-libs/blockifier/blob/83b8b6dfb4b3a9e70b02ce7c8f80ac8106609d57/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L223)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

The point is that the `DictStateReader` has 5 fields (and not only the `address_to_class_hash`) so this generalization will not end here. I suggest creating a macro as a test util to allow the creation of `VersionedState` with different state readers or a macro as a test util for the `DictStateReader`.
WDYT? (It can be added as a TODO here) I feel that the current form of this util lacks some indirections. 

To save code duplication in this file, you can add a fixture that does what the comment below suggests:
```
    let address_to_class_hash = HashMap::from(contract_address!("0x1"), ClassHash(stark_felt!(27_u8)));
    let initial_state = CachedState::from(....);
    let versioned_state = versioned_state_for_testing(initial_state);
```
</blockquote></details>

@meship-starkware wants to use this util, and move it to `test_util`.
I agree that it can be generalized.
I'm adding a TODO.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 225 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-Nvk4KG18S1RSAArs2Uo:-NwFjtbl4Ojo0TBYqtSZ:bb76mu4) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L225)):*
> ```XML
> }
> 
> #[test]
> ```

Why?
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 240 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkD7mA5oJf7wxIRRAG:-NwKZWxC2vhuStf8LYEQ:b-5kh6fv) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L240)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

The transactional state was pinned with version number 1. I would expect it to fail.
Add a TODO above `validate_read_set` to couple the tx_index and the read set so that passing incompatible tx index and read set would fail the validation.
</blockquote></details>

I'm not sure I understand it. How would you check that?
The read set doesn't include the version number.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 243 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkBXcH6M9bjactGyI-:-NwKcBaXB1-5Xwj7_anB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L243)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Before and after each "get" call, add an assertion to show the reader what was empty before and that it's not empty after.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 246 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkB2n89TfiOTJMMt-Y:-NwKebeE7Amn5pGF-imv:b-hnaxcl) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L246)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Is it relevant to add the last one?
</blockquote></details>

Removed.
You're right, it's not part of the validate_read_set.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 248 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkAn5QCXiwq4HdC1hV:-NwKew1d3GMZXKk8ZAvJ:b7gk03j) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L248)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Why is it needed? Does it intrigue some "set_initial..." that was not intrigued before? Tx level or chunk level?
</blockquote></details>

Correct, AFAIK, this is the flow.
@noaov1, can you please approve?
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 257 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkGpp-AyRoJuMG6_s0:-NwKf28J89iYnUOXxvJT:bb7r2f0) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L257)):*
> ```XML
> }
> 
> #[test]
> ```

why?
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 266 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkF66uDHq1dchGPn1v:-NwKjAHb3vk28cIVLwKv:b-7uab7x) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L266)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Use this pattern to create two different txs in the `test_validate_read_set` as well.
Since the "0" tx is not really needed there, add a comment that it should be checked once the tx index and the read set will be coupled somehow.
</blockquote></details>

See the above comment.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 272 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkGJZ249y59T1QbRC0:-NwKjZMB-SzCV_TGObhU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L272)):*
> ```XML
>     transactional_states[0].set_class_hash_at(contract_address, class_hash_0).unwrap();
> 
>     versioned_state.lock().unwrap().apply_writes(
> ```

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 275 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkG-0w-sG084djd5oJ:-NwKjtQyAqtZ2zOMO_c3:b-7zi8tj) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L275)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Add something that this map will also be changed. and check it with another assertion.
</blockquote></details>

WDYM?
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 280 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkGrP67SubC2EYTvGo:-NwKjv1WC8sV3jzLVDrc:bb7r2f0) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L280)):*
> ```XML
> }
> 
> #[test]
> ```

why?
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 297 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkGVfwD6lK0LzyRzxi:-NwKk6EH2g3uwQo2ahK3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L297)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Add a comment to explain what t [...]

2024-04-25 15:27 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: 0 of 2 files reviewed, 19 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 354 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkH6Mj3ogfK1fF1E3S:-NwKrS_q80Ucarpsd3yu:b-wjhdba) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L354)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

[New PR](https://reviewable.io/reviews/starkware-libs/blockifier/1828) 


<!-- Sent from Reviewable.io -->

2024-04-27 06:52 UTC, barak-b-starkware requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: all files reviewed, 14 unresolved discussions (waiting on @meship-starkware, @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NuTd88iAb4wpTGcfXdJ:-NwTBVVI4v-ZiXUL04DV:b-jxvik4) ([raw file](https://github.com/starkware-libs/blockifier/blob/83b8b6dfb4b3a9e70b02ce7c8f80ac8106609d57/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L223)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

@meship-starkware wants to use this util, and move it to `test_util`.
I agree that it can be generalized.
I'm adding a TODO.
</blockquote></details>

@meship-starkware is there any chance that you can open a PR for that now so @MohammadNassar1 can rebase this PR on yours?
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 225 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-Nvk4KG18S1RSAArs2Uo:-NwTBoNx3ZhW5MdYOeyE:bczktea) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L225)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

For consistency and as an easier platform to expand the tests in the future.
Right now, there is no need for any features from `rstest`, but notice that in the Python repo, we always test our tests with the `pytest` framework. So, I think it's good practice to test all our tests in the `blockifier` repo with `rstest`.
Anyway, the `fixture` in the `use` statement is definitely redundant so `use rstest::tstest` is enough.
WDYT? it's better to leave it as is (`#[test]`)?
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 240 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkD7mA5oJf7wxIRRAG:-NwTDQnY022WJ1FWaRvv:bophmzh) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L240)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I'm not sure I understand it. How would you check that?
The read set doesn't include the version number.
</blockquote></details>

For example, the `pin_version` method can output `VersionedStateProxyWithTxIndex` instead of `VersionedStateProxy` where:
```
struct VersionedStateProxyWithTxIndex {
    pub state VersionedStateProxy;
    pub tx_index TxIndex;
}
```
 It's just a trivial solution, and I'm not sure it's the right way.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 246 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkB2n89TfiOTJMMt-Y:-NwTGoe34cytwFSTATkj:b-kkcwc4) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L246)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Removed.
You're right, it's not part of the validate_read_set.
</blockquote></details>

I meant to add another getter, not to remove the last one.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 275 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkG-0w-sG084djd5oJ:-NwTI9Uq2WRjxx67Opdz:b-im4bwz) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L275)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

The `set_class_hash_at` modifies the `STATE.cache.writes.class_hashes` dictionary, which is part of the write-set as it appears in the `StateCache`.
The `STATE.class_hash_to_class` is not part of the `STATE.cache`, and it's passed separately for the `apply_writes` method, so I want to check that it's modified correctly too by some setter, so we'll have something like:
```
    assert!(transactional_states[0].class_hash_to_class.is_empty());
    transactional_states[0].<some setter that can do the work>;
    assert_eq!(transactional_states[0].class_hash_to_class.len(), 1);
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 354 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkH6Mj3ogfK1fF1E3S:-NwTJczhCFmbucHIvIIz:buok54e) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L354)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

[New PR](https://reviewable.io/reviews/starkware-libs/blockifier/1828)
</blockquote></details>

Thanks! Can you mark me as a reviewer so it would appear in my Reviewable reviews :pray: 
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 256 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwTH7bJ81aTnndbipva:-NwTH7bJ81aTnndbipvb:bk15obb) ([raw file](https://github.com/starkware-libs/blockifier/blob/461631ef3f46f42010136a2ea8a8c2d06db194a4/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L256)):*
> ```XML
>     assert_eq!(transactional_state.cache.borrow().initial_reads.storage.len(), 1);
>     assert_eq!(transactional_state.cache.borrow().initial_reads.nonces.len(), 1);
>     assert_eq!(transactional_state.cache.borrow().initial_reads.class_hashes.len(), 1);
> ```

WDYT about the following form? (gathering assertion + getter + assertion for each getter so the reader can easily understand which method affects which dictionary)



_Suggestion:_
```XML
    assert!(transactional_state.cache.borrow().initial_reads.storage.is_empty());
    transactional_state.get_storage_at(contract_address, storage_key).unwrap();
    assert_eq!(transactional_state.cache.borrow().initial_reads.storage.len(), 1);
    
    assert!(transactional_state.cache.borrow().initial_reads.nonces.is_empty());
    transactional_state.get_class_hash_at(contract_address).unwrap();
    assert_eq!(transactional_state.cache.borrow().initial_reads.nonces.len(), 1);
    
    assert!(transactional_state.cache.borrow().initial_reads.class_hashes.is_empty());
    transactional_state.get_nonce_at(contract_address).unwrap();
    assert_eq!(transactional_state.cache.borrow().initial_reads.class_hashes.len(), 1);
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 355 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwTG7vZER311WqpdNRx:-NwTG7vZER311WqpdNRy:b-7snps9) ([raw file](https://github.com/starkware-libs/blockifier/blob/461631ef3f46f42010136a2ea8a8c2d06db194a4/crates/blockifier/src/state/cached_state.rs#L355)):*
> ```XML
>     pub(crate) storage: HashMap<StorageEntry, StarkFelt>,
>     pub(crate) compiled_class_hashes: HashMap<ClassHash, CompiledClassHash>,
>     pub(crate) declared_contracts: HashMap<ClassHash, bool>,
> ```

This is @Yoni-Starkware 's change. I think you need to rebase your PRs over `main` (:



_Code quote:_
```XML
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct StateMaps {
    pub(crate) nonces: HashMap<ContractAddress, Nonce>,
    pub(crate) class_hashes: HashMap<ContractAddress, ClassHash>,
    pub(crate) storage: HashMap<StorageEntry, StarkFelt>,
    pub(crate) compiled_class_hashes: HashMap<ClassHash, CompiledClassHash>,
    pub(crate) declared_contracts: HashMap<ClassHash, bool>,
```


<!-- Sent from Reviewable.io -->

2024-04-28 09:03 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: 1 of 2 files reviewed, 14 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 225 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-Nvk4KG18S1RSAArs2Uo:-NwYvVsX8PMfpj0JChEh:brjhrpd) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L225)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

For consistency and as an easier platform to expand the tests in the future.
Right now, there is no need for any features from `rstest`, but notice that in the Python repo, we always test our tests with the `pytest` framework. So, I think it's good practice to test all our tests in the `blockifier` repo with `rstest`.
Anyway, the `fixture` in the `use` statement is definitely redundant so `use rstest::tstest` is enough.
WDYT? it's better to leave it as is (`#[test]`)?
</blockquote></details>

I suggest we keep using `#[test]` unless we need a feature from `rstest`.
Note that in this repo, we tend to use `test`.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 240 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkD7mA5oJf7wxIRRAG:-NwYtnuHD6riN-eEei_M:b-wgfqle) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L240)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

For example, the `pin_version` method can output `VersionedStateProxyWithTxIndex` instead of `VersionedStateProxy` where:
```
struct VersionedStateProxyWithTxIndex {
    pub state VersionedStateProxy;
    pub tx_index TxIndex;
}
```
 It's just a trivial solution, and I'm not sure it's the right way.
</blockquote></details>

Your suggestion is a bit problematic; `validate_read_set` is part of the `versionedState`  methods and not `versionedStateProxy`, as the validation can be done several times by different clients. Then, adding an index to the struct wouldn't solve the issue.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 246 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkB2n89TfiOTJMMt-Y:-NwYptnwD6KMgpH1_CQq:bklvoax) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L246)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I meant to add another getter, not to remove the last one.
</blockquote></details>

Note that `validate_read_set` doesn't validate contract classes, so the last one is irrelevant.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 275 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkG-0w-sG084djd5oJ:-NwYt06j9dyGzkz5J5Mc:b-rhfqo8) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L275)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

The `set_class_hash_at` modifies the `STATE.cache.writes.class_hashes` dictionary, which is part of the write-set as it appears in the `StateCache`.
The `STATE.class_hash_to_class` is not part of the `STATE.cache`, and it's passed separately for the `apply_writes` method, so I want to check that it's modified correctly too by some setter, so we'll have something like:
```
    assert!(transactional_states[0].class_hash_to_class.is_empty());
    transactional_states[0].<some setter that can do the work>;
    assert_eq!(transactional_states[0].class_hash_to_class.len(), 1);
```
</blockquote></details>

Not sure I got it :/
The `apply_writes` doesn't modify the `class_hash_to_class`
We check the set_class_hash_to_clss in `test_versioned_state_proxy` test.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 354 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkH6Mj3ogfK1fF1E3S:-NwYnZHC19NXxS_Yd4It:bas4jz7) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L354)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Thanks! Can you mark me as a reviewer so it would appear in my Reviewable reviews :pray:
</blockquote></details>

You're already marked as reviewer:
![image.png](https://files.reviewableusercontent.io/images/reviewable/130282237/yJg2XaeUS9MXAFvvby-eYqyd/image.png)
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 256 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwTH7bJ81aTnndbipva:-NwYquv94aba53AhiG1E:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/461631ef3f46f42010136a2ea8a8c2d06db194a4/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L256)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

WDYT about the following form? (gathering assertion + getter + assertion for each getter so the reader can easily understand which method affects which dictionary)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 355 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwTG7vZER311WqpdNRx:-NwYtdaN5vXQ0GLpq004:b9jc19v) ([raw file](https://github.com/starkware-libs/blockifier/blob/461631ef3f46f42010136a2ea8a8c2d06db194a4/crates/blockifier/src/state/cached_state.rs#L355)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

This is @Yoni-Starkware 's change. I think you need to rebase your PRs over `main` (:
</blockquote></details>

It's already rebased :).


<!-- Sent from Reviewable.io -->

2024-04-29 19:45 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: 1 of 2 files reviewed, 14 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 342 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkHHQs9yO4e3YSG3WB:-NwfNNE48VXBmRCE-w31:b-abwncb) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/state/cached_state.rs#L342)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

you're right.
I was unable to figure out a method to enable cloning only for testing.
</blockquote></details>

Try using: `#[cfg_attr(test, derive(Clone))]`. It applies the `derive(Clone)` attribute to the struct if the `test` configuration flag is enabled.
(you may need to use `any(feature = "testing", test)`)


<!-- Sent from Reviewable.io -->

2024-04-30 11:42 UTC, barak-b-starkware requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: all files reviewed, 11 unresolved discussions (waiting on @meship-starkware, @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 225 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-Nvk4KG18S1RSAArs2Uo:-Nwik1PL9kYeJhNztwE4:bd0dbe6) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L225)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I suggest we keep using `#[test]` unless we need a feature from `rstest`.
Note that in this repo, we tend to use `test`.
</blockquote></details>

OK, if it's the convention it's fine by me, @noaov1 WDYT?
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 240 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkD7mA5oJf7wxIRRAG:-NwikXta5JSY1cpF2qIs:b-tle28a) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L240)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Your suggestion is a bit problematic; `validate_read_set` is part of the `versionedState`  methods and not `versionedStateProxy`, as the validation can be done several times by different clients. Then, adding an index to the struct wouldn't solve the issue.
</blockquote></details>

I'm not saying it's a good solution, but I suggest adding a TODO.
WDYT about starting the message with "Consider ..." so whether to do it or not would be up to the TODO resolver?
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 275 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkG-0w-sG084djd5oJ:-NwilrHk7Dldf5J9xORT:b-d7lh3w) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L275)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Not sure I got it :/
The `apply_writes` doesn't modify the `class_hash_to_class`
We check the set_class_hash_to_clss in `test_versioned_state_proxy` test.
</blockquote></details>

`apply_write` contains 5 `for` loops, 5 for the `StateMaps` members (`nonces`, `class_hashes`, `storage`, `compiled_class_hashes`), and one more for the `ContractClassMapping`
I think that we should have at least one change for one member in the `StateMaps` (in this test you chose `class_hashes`) and one change for `ContractClassMapping`

What do I miss here?
___
*[`crates/blockifier/src/state/cached_state.rs` line 342 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkHHQs9yO4e3YSG3WB:-NwinOtACeaG0jnB3jYT:br7q18v) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/state/cached_state.rs#L342)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Try using: `#[cfg_attr(test, derive(Clone))]`. It applies the `derive(Clone)` attribute to the struct if the `test` configuration flag is enabled.
(you may need to use `any(feature = "testing", test)`)
</blockquote></details>

Nice, I didn't know this trick


<!-- Sent from Reviewable.io -->

2024-04-30 13:56 UTC, barak-b-starkware commented
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NuTd88iAb4wpTGcfXdJ:-NwjHcPe1jxOzF91YVga:b-2due3z) ([raw file](https://github.com/starkware-libs/blockifier/blob/83b8b6dfb4b3a9e70b02ce7c8f80ac8106609d57/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L223)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

@meship-starkware is there any chance that you can open a PR for that now so @MohammadNassar1 can rebase this PR on yours?
</blockquote></details>

Please rebase over @meship-starkware 's [PR](https://reviewable.io/reviews/starkware-libs/blockifier/1835) and use this test util


<!-- Sent from Reviewable.io -->

2024-04-30 18:48 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NuTd88iAb4wpTGcfXdJ:-NwkFiTE7aet1I7wBpgy:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/83b8b6dfb4b3a9e70b02ce7c8f80ac8106609d57/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L223)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Please rebase over @meship-starkware 's [PR](https://reviewable.io/reviews/starkware-libs/blockifier/1835) and use this test util
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 240 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkD7mA5oJf7wxIRRAG:-NwkGBtv07socYFoa47s:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L240)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I'm not saying it's a good solution, but I suggest adding a TODO.
WDYT about starting the message with "Consider ..." so whether to do it or not would be up to the TODO resolver?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 275 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkG-0w-sG084djd5oJ:-NwkK0da--rKsyF97-Uy:b-ypden1) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L275)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

`apply_write` contains 5 `for` loops, 5 for the `StateMaps` members (`nonces`, `class_hashes`, `storage`, `compiled_class_hashes`), and one more for the `ContractClassMapping`
I think that we should have at least one change for one member in the `StateMaps` (in this test you chose `class_hashes`) and one change for `ContractClassMapping`

What do I miss here?
</blockquote></details>

Got you.
Added!
___
*[`crates/blockifier/src/state/cached_state.rs` line 342 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkHHQs9yO4e3YSG3WB:-NwkI0rtBgxze3NGLmnF:bwuv9uq) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/state/cached_state.rs#L342)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Nice, I didn't know this trick
</blockquote></details>

Nice!!


<!-- Sent from Reviewable.io -->

2024-05-01 11:15 UTC, barak-b-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @meship-starkware, @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 71 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwnqV0KA4fWsxIwiI9y:-NwnqV0KA4fWsxIwiI9z:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/3a226d42719eca8531010bdb3048986200e164ac/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L71)):*
> ```XML
>     // accessing this function should be protected by a mutex to ensure thread safety.
>     // TODO: Consider coupling the tx_index with the read_set to ensure that any mismatch between
>     // the transaction index and read set will cause the validation to fail.
> ```





_Suggestion:_
```XML
    // TODO: Consider coupling the tx index with the read set to ensure any mismatch between them will cause the validation to fail.
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NuTd88iAb4wpTGcfXdJ:-NwnrQsA08Mj0K8PKwSi:b-23o7gz) ([raw file](https://github.com/starkware-libs/blockifier/blob/83b8b6dfb4b3a9e70b02ce7c8f80ac8106609d57/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L223)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you please rebase again? it was changed


<!-- Sent from Reviewable.io -->

2024-05-01 15:43 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: 0 of 4 files reviewed, 10 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 71 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwnqV0KA4fWsxIwiI9y:-NwooQAc9cNLwHonu8Dr:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/3a226d42719eca8531010bdb3048986200e164ac/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L71)):*
> ```XML
>     // accessing this function should be protected by a mutex to ensure thread safety.
>     // TODO: Consider coupling the tx_index with the read_set to ensure that any mismatch between
>     // the transaction index and read set will cause the validation to fail.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 223 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NuTd88iAb4wpTGcfXdJ:-NwooRIL3bt9SyjMmfDX:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/83b8b6dfb4b3a9e70b02ce7c8f80ac8106609d57/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L223)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Can you please rebase again? it was changed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-02 06:17 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: 0 of 4 files reviewed, 10 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 342 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkHHQs9yO4e3YSG3WB:-Nwrvfda1M9V62RSiMUR:bgpyo87) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/state/cached_state.rs#L342)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Nice!!
</blockquote></details>

Do we still need to clone the StateCache?


<!-- Sent from Reviewable.io -->

2024-05-02 06:35 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, @MohammadNassar1, and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 36 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-Nws-x6B1kVXpaKAA48V:-Nws-x6CElDbpxR0FJM_:b-24ve8o) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa36d7840561d440b1e173908f3a318fba7505fe/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L36)):*
> ```XML
> pub fn versioned_state() -> Arc<Mutex<VersionedState<DictStateReader>>> {
>     let contract_address = contract_address!("0x1");
>     let class_hash = ClassHash(stark_felt!(27_u8));
> ```

In this file



_Suggestion:_
```XML
class_hash!(27_u8)
```


<!-- Sent from Reviewable.io -->

2024-05-02 08:07 UTC, noaov1 reviewed
> Reviewed 1 of 4 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: all files reviewed, 18 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, and @MohammadNassar1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 225 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-Nvk4KG18S1RSAArs2Uo:-Nws7CGn3C8Q0WhLlL10:brxp9sq) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L225)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

OK, if it's the convention it's fine by me, @noaov1 WDYT?
</blockquote></details>

Sounds good.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 248 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkAn5QCXiwq4HdC1hV:-Nws8G2V71XYHMYlG3nU:bq1e35w) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L248)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Correct, AFAIK, this is the flow.
@noaov1, can you please approve?
</blockquote></details>

I think it's not relevant here since you don't have any write only cells. This method (and more concretely, the `update_initial_values_of_write_only_access` method), updates cache with initial cell values for write-only access.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 34 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-Nws6pVc1e3_-KrCcXB4:-Nws6pVc1e3_-KrCcXB5:bfn0q0i) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa36d7840561d440b1e173908f3a318fba7505fe/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L34)):*
> ```XML
> 
> #[fixture]
> pub fn versioned_state() -> Arc<Mutex<VersionedState<DictStateReader>>> {
> ```

Why not use `ThreadSafeVersionedState`? Same question for `versioned_state_for_testing`. 
(may need to change the inner field to public)



_Code quote:_
```XML
pub fn versioned_state() -> Arc<Mutex<VersionedState<DictStateReader>>> {
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 40 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwsCgSc-QpKLfnT6DCy:-NwsCgSc-QpKLfnT6DCz:b5p97r2) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa36d7840561d440b1e173908f3a318fba7505fe/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L40)):*
> ```XML
>         storage_view: HashMap::default(),
>         address_to_nonce: HashMap::default(),
>         address_to_class_hash: HashMap::from([(contract_address, class_hash)]),
> ```

Why did you fill this and this only?



_Code quote:_
```XML
        address_to_class_hash: HashMap::from([(contract_address, class_hash)]),
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 243 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwsBFP5BXt0MQI3Bi7Y:-NwsBFP5BXt0MQI3Bi7Z:b12y8e3) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa36d7840561d440b1e173908f3a318fba7505fe/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L243)):*
> ```XML
>             .lock()
>             .unwrap()
>             .validate_read_set(0, &transactional_state.cache.borrow().initial_reads)
> ```

The `initial_reads` is empty, right? Why not simply pass a default `StateMaps`?



_Code quote:_
```XML
            .validate_read_set(0, &transactional_state.cache.borrow().initial_reads)
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 280 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwsCOTADOWd8NQf_bii:-NwsCOTB7jcqmfNJjQpB:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa36d7840561d440b1e173908f3a318fba7505fe/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L280)):*
> ```XML
>         (0..2).map(|i| CachedState::from(safe_versioned_state.pin_version(i))).collect();
> 
>     // Client 0 class hash.
> ```

?



_Suggestion:_
```XML
    //Transaction 0 class hash.
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 319 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwsK5kA2_JDowuxyC3t:-NwsK5kA2_JDowuxyC3u:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa36d7840561d440b1e173908f3a318fba7505fe/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L319)):*
> ```XML
>     transactional_states[0].set_class_hash_at(contract_address, class_hash_0).unwrap();
> 
>     // As the transaction is not committed, the class hash should not be updated.
> ```





_Suggestion:_
```XML
    // As transaction 0 hasn't written to the shared state yet, the class hash should not be updated.
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 329 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwsKS_v5AggwUfkcGwH:-NwsKS_v5AggwUfkcGwI:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa36d7840561d440b1e173908f3a318fba7505fe/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L329)):*
> ```XML
>         &transactional_states[0].class_hash_to_class.borrow().clone(),
>     );
>     // Although it has been committed, version 1 needs to be re-executed to see the new value.
> ```





_Suggestion:_
```XML
    // Although transaction 0 wrote to the shared state, version 1 needs to be re-executed to see the new value (its read value has already benn cached).
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 334 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwsKhrm5ppXExvmxvuf:-NwsKhrm5ppXExvmxvug:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa36d7840561d440b1e173908f3a318fba7505fe/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L334)):*
> ```XML
>     );
> 
>     // Re-execute the transaction.
> ```





_Suggestion:_
```XML
    // "Re-execute" the transaction.
```


<!-- Sent from Reviewable.io -->

2024-05-02 10:19 UTC, barak-b-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: all files reviewed, 14 unresolved discussions (waiting on @MohammadNassar1 and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 274 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwsZ9Fq7z3hlrfZqLLC:-NwsZ9Fq7z3hlrfZqLLD:b-owil8f) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa36d7840561d440b1e173908f3a318fba7505fe/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L274)):*
> ```XML
> fn test_apply_writes(versioned_state: Arc<Mutex<VersionedState<DictStateReader>>>) {
>     let contract_address = contract_address!("0x1");
>     let class_hash = ClassHash(stark_felt!(27_u8));
> ```

Extract the `contract_Address` and the `class_hash` from the fixture.



_Code quote:_
```XML
    let contract_address = contract_address!("0x1");
    let class_hash = ClassHash(stark_felt!(27_u8));
```


<!-- Sent from Reviewable.io -->

2024-05-02 10:49 UTC, barak-b-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: all files reviewed, 14 unresolved discussions (waiting on @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 246 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkB2n89TfiOTJMMt-Y:-Nwsp7kcAgH65u9VwsYW:boov1x5) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L246)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Note that `validate_read_set` doesn't validate contract classes, so the last one is irrelevant.
</blockquote></details>

Please add a TODO on @OriStarkware to add a check for `get_compiled_contract_class` once the deploy account preceding a declare flow is solved.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 248 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkAn5QCXiwq4HdC1hV:-NwssTek7ma4tEJIC8uu:bn94b3k) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L248)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think it's not relevant here since you don't have any write only cells. This method (and more concretely, the `update_initial_values_of_write_only_access` method), updates cache with initial cell values for write-only access.
</blockquote></details>

Remove this line from the test and add another test that checks the `validate_read_set` after simulating some kind of "write-only" transaction. There, call `get_actual_state_changes()` to intrigue the `update_initial_values_of_write_only_access` and add assertions before and after to see what was changed.


<!-- Sent from Reviewable.io -->

2024-05-02 12:15 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: 1 of 4 files reviewed, 8 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 246 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkB2n89TfiOTJMMt-Y:-Nwt807c6nfI2XU8xyuB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L246)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Please add a TODO on @OriStarkware to add a check for `get_compiled_contract_class` once the deploy account preceding a declare flow is solved.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 248 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkAn5QCXiwq4HdC1hV:-NwtCUaHCRFFhjjCOMgA:b-v086au) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L248)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Remove this line from the test and add another test that checks the `validate_read_set` after simulating some kind of "write-only" transaction. There, call `get_actual_state_changes()` to intrigue the `update_initial_values_of_write_only_access` and add assertions before and after to see what was changed.
</blockquote></details>

Added a todo for that.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 266 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkF66uDHq1dchGPn1v:-NwtALm15LgATdiHbxcg:b-khk451) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L266)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

See @noaov1 's comment [here](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwsBFP5BXt0MQI3Bi7Y), it solves for me the issue
</blockquote></details>

stale?
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 34 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-Nws6pVc1e3_-KrCcXB4:-Nwt3Huu-jGmFmcfSwrt:b-84070u) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa36d7840561d440b1e173908f3a318fba7505fe/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L34)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why not use `ThreadSafeVersionedState`? Same question for `versioned_state_for_testing`. 
(may need to change the inner field to public)
</blockquote></details>

Currently, we don't have `new` method for `ThreadSafeVersionedState`.
I think it can be done in a separate PR, wdyt?
Added a TODO.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 40 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwsCgSc-QpKLfnT6DCy:-Nwt47xQ5SRWFvpKK18O:bqz00za) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa36d7840561d440b1e173908f3a318fba7505fe/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L40)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why did you fill this and this only?
</blockquote></details>

In `test_versioned_state_proxy` we check all the fields.
In other test, I used a single field, to check other features (e.g. apply_writes, validate, etc).
So to simple the test, I only check `class_hash`.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 233 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwsVQLM7IM71kZa0adB:-NwtCTbSClfH6uMrvSvz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa36d7840561d440b1e173908f3a318fba7505fe/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L233)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Extract the `contract_Address` and the `class_hash` from the fixture.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 274 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwsZ9Fq7z3hlrfZqLLC:-NwtD0Zh1zEgFluhTNFd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa36d7840561d440b1e173908f3a318fba7505fe/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L274)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Extract the `contract_Address` and the `class_hash` from the fixture.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 342 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkHHQs9yO4e3YSG3WB:-NwtDH5E0QFU9pSjLN9G:bol12hk) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/state/cached_state.rs#L342)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Do we still need to clone the StateCache?
</blockquote></details>

You're right, we don't.
Removed.


<!-- Sent from Reviewable.io -->

2024-05-02 13:36 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 252 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwtUYyZ43wKck1aZvZ9:-NwtW5nU-3PkNMZ2xSwQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c6f980d7dff4d778397d5ddf00ce3823bd6842bd/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L252)):*
> ```XML
>     let contract_address = contract_address_for_testing;
>     let storage_key = storage_key!("0x10");
>     let class_hash = class_hash_for_testing;
> ```

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 294 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwtUyASEdedFoQPLLfd:-NwtW6_n3wrbP02p4LIB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c6f980d7dff4d778397d5ddf00ce3823bd6842bd/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L294)):*
> ```XML
> ) {
>     let contract_address = contract_address_for_testing;
>     let class_hash = class_hash_for_testing;
> ```

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 331 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwtV3LS6a3SM9jlVFeH:-NwtW6rB7kk2xAktVOEH:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c6f980d7dff4d778397d5ddf00ce3823bd6842bd/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L331)):*
> ```XML
> ) {
>     let contract_address = contract_address_for_testing;
>     let init_class_hash = class_hash_for_testing;
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-05-02 14:52 UTC, noaov1 reviewed
> Reviewed 2 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware and @MohammadNassar1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 248 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkAn5QCXiwq4HdC1hV:-NwtmKF69kWA3rtv2KZL:b7iebew) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L248)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Added a todo for that.
</blockquote></details>

I'm not sure it's needed. We assume the read set contains the values read by the transaction. 
In case of a write-only, the transaction makes a read (for the fee calculation, to see if the write has made an actual change). In any case, the read set are the values read by the transaction (in execution or for fee calculation).
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 31 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-Nwtkxit0er2hQczo1CN:-Nwtkxit0er2hQczo1CO:brejra4) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f8203b7224161a19364a5e6bfdf49f81b45d05d/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L31)):*
> ```XML
> 
> #[fixture]
> pub fn contract_address_for_testing() -> ContractAddress {
> ```

Same below



_Suggestion:_
```XML
pub fn contract_address() -> ContractAddress {
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 301 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NwtmX6FC--exVa1Cnbo:-NwtmX6FC--exVa1Cnbp:b32vhw) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f8203b7224161a19364a5e6bfdf49f81b45d05d/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L301)):*
> ```XML
>     assert_eq!(transactional_states[0].cache.borrow().writes.class_hashes.len(), 1);
> 
>     // Client 0 contract class.
> ```

:)



_Suggestion:_
```XML
// Transaction 0 contract class.
```


<!-- Sent from Reviewable.io -->

2024-05-05 11:55 UTC, barak-b-starkware commented
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 248 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-NvkAn5QCXiwq4HdC1hV:-Nx6s7Fc10eO6Rp53lwv:b-tlhz9r) ([raw file](https://github.com/starkware-libs/blockifier/blob/15bf64346bc20a7b124a188d33724e4e7f8bfaf3/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L248)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I'm not sure it's needed. We assume the read set contains the values read by the transaction. 
In case of a write-only, the transaction makes a read (for the fee calculation, to see if the write has made an actual change). In any case, the read set are the values read by the transaction (in execution or for fee calculation).
</blockquote></details>

After discussing offline with @noaov1 - it's OK to remove it:
For the record - it does change the read set, but since all `for` loops are already being tested by the previous getters, it's redundant, and the right way to check this functionality is by testing it in the `CachedState` related unit-tests.


<!-- Sent from Reviewable.io -->

2024-05-05 11:57 UTC, barak-b-starkware commented
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 243 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-Nx7bRU8A-Zpsk09htuJ:-Nx7bRU8A-Zpsk09htuK:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f8203b7224161a19364a5e6bfdf49f81b45d05d/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L243)):*
> ```XML
> // It checks the `validate_read_set` after simulating some kind of "write-only" transaction. There,
> // call `get_actual_state_changes` to intrigue the `update_initial_values_of_write_only_access` and
> // add assertions before and after to see what was changed.
> ```




<!-- Sent from Reviewable.io -->

2024-05-05 12:04 UTC, barak-b-starkware requested changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: all files reviewed, 5 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 351 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-Nx7cgaJ5KehWiYbZAiK:-Nx7cgaJ5KehWiYbZAiL:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f8203b7224161a19364a5e6bfdf49f81b45d05d/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L351)):*
> ```XML
>     );
>     // Although transaction 0 wrote to the shared state, version 1 needs to be re-executed to see
>     // the new value (its read value has already benn cached).
> ```





_Suggestion:_
```XML
    // Although transaction 0 wrote to the shared state, version 1 needs to be re-executed to see
    // the new value (its read value has already been cached).
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 358 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-Nx7cisK1Fk6CZA_Bw_o:-Nx7cisK1Fk6CZA_Bw_p:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f8203b7224161a19364a5e6bfdf49f81b45d05d/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L358)):*
> ```XML
> 
>     // "Re-execute" the transaction.
>     transactional_states[1] = CachedState::from(safe_versioned_state.pin_version(1));
> ```





_Suggestion:_
```XML
    // TODO: Use re-execution native util once it's ready.
    // "Re-execute" the transaction.
    transactional_states[1] = CachedState::from(safe_versioned_state.pin_version(1));
```


<!-- Sent from Reviewable.io -->

2024-05-05 12:26 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 31 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-Nwtkxit0er2hQczo1CN:-Nx7i0iD366jvkpAKlVF:b-bw8e14) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f8203b7224161a19364a5e6bfdf49f81b45d05d/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L31)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Same below
</blockquote></details>

Updated.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 243 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-Nx7bRU8A-Zpsk09htuJ:-Nx7gamh-A7N_ToukvEs:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f8203b7224161a19364a5e6bfdf49f81b45d05d/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L243)):*
> ```XML
> // It checks the `validate_read_set` after simulating some kind of "write-only" transaction. There,
> // call `get_actual_state_changes` to intrigue the `update_initial_values_of_write_only_access` and
> // add assertions before and after to see what was changed.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 351 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-Nx7cgaJ5KehWiYbZAiK:-Nx7gl5l9wwQ0vXwVMQz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f8203b7224161a19364a5e6bfdf49f81b45d05d/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L351)):*
> ```XML
>     );
>     // Although transaction 0 wrote to the shared state, version 1 needs to be re-executed to see
>     // the new value (its read value has already benn cached).
> ```

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 358 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-Nx7cisK1Fk6CZA_Bw_o:-Nx7gpzj5y_Y9N7ibz3Y:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4f8203b7224161a19364a5e6bfdf49f81b45d05d/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L358)):*
> ```XML
> 
>     // "Re-execute" the transaction.
>     transactional_states[1] = CachedState::from(safe_versioned_state.pin_version(1));
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-05-05 12:29 UTC, barak-b-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1748#-:-Nx7io_r6ioEaR2s5TX3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-05-05 12:31 UTC, merged