added sha256 syscall
starkware-libs/blockifier pull request #1754
Opened 2024-04-03 14:21 UTC by TomerStarkware

2024-04-04 07:47 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 140 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nuc3pOTCZhZGv8BxWHK:-Nuc3pOTCZhZGv8BxWHL:b3vcyvw) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fc99220b1cf73029612d7d2b333733c449ca936/crates/blockifier/resources/versioned_constants_13_0.json#L140)):*
> ```JSON
>         },
>         "keccak_round_cost_gas_cost": 180000,
>         "sha256_process_block_gas_cost": {
> ```

@noaov1  do we need to add it here?
The syscall wasn't supported in that version.



_Code quote:_
```JSON
 "sha256_process_block_gas_cost": {
```


<!-- Sent from Reviewable.io -->

2024-04-04 07:48 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/versioned_constants_test.rs` line 201 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nuc40oX3Zt2fgftn5Zt:-Nuc40oX3Zt2fgftn5Zu:b-l6hdjr) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb32e769e4c69beb95ee679a5327d0942c8608d7/crates/blockifier/src/versioned_constants_test.rs#L201)):*
> ```XML
>     for file in files.map(Result::unwrap) {
>         serde_json::from_reader::<_, VersionedConstants>(&std::fs::File::open(&file).unwrap())
>             .unwrap_or_else(|_| panic!("Versioned constants JSON file {file:#?} is malformed"));
> ```

revert



_Code quote:_
```XML
  .unwrap_or_else(|_| panic!("Versioned constants JSON file {file:#?} is malformed"));
```


<!-- Sent from Reviewable.io -->

2024-04-04 07:48 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/entry_point_test.rs` line 720 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nuc4CGF7xoUsp5-JbQ3:-Nuc4CGF7xoUsp5-JbQ4:b-sp8mru) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fc99220b1cf73029612d7d2b333733c449ca936/crates/blockifier/src/execution/entry_point_test.rs#L720)):*
> ```XML
> #[case(CairoVersion::Cairo0, "invoke_call_chain", "Couldn't compute operand op0. Unknown value for memory cell 1:37", (1081_u16, 1127_u16))]
> #[case(CairoVersion::Cairo0, "fail", "An ASSERT_EQ instruction failed: 1 != 0.", (1184_u16, 1135_u16))]
> #[case(CairoVersion::Cairo1, "invoke_call_chain", "0x4469766973696f6e2062792030 ('Division by 0')", (0_u16, 0_u16))]
> ```

this should probably be done in a preliminary PR.



_Code quote:_
```XML
x4469766973696f6e2062792030 ('Division by 0')
```


<!-- Sent from Reviewable.io -->

2024-04-04 08:03 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 759 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nuc7bAs7yVp1AEdCbTW:-Nuc7bAtBsPFihdPSrpl:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fc99220b1cf73029612d7d2b333733c449ca936/crates/blockifier/src/execution/syscalls/mod.rs#L759)):*
> ```XML
> #[derive(Debug, Eq, PartialEq)]
> pub struct SHA256ProcessBlockResponse {
>     pub state: Relocatable,
> ```





_Suggestion:_
```XML
state_ptr
```


<!-- Sent from Reviewable.io -->

2024-04-04 10:39 UTC, orizi requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: 7 of 17 files reviewed, 7 unresolved discussions (waiting on @noaov1 and @TomerStarkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 809 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nucg0-C6ipiZQmqD1xM:-Nucg0-C6ipiZQmqD1xN:b3kqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fc99220b1cf73029612d7d2b333733c449ca936/crates/blockifier/src/execution/syscalls/mod.rs#L809)):*
> ```XML
>         .collect_vec()
>         .try_into()
>         .unwrap();
> ```

.



_Suggestion:_
```XML
    let mut state_as_words: [u32; SHA256_STATE_SIZE] = 
    core::array::from_fn(|i| prev_state[i].to_bigint().to_u32().unwrap());
```


<!-- Sent from Reviewable.io -->

2024-04-04 11:22 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: 6 of 17 files reviewed, 7 unresolved discussions (waiting on @ilyalesokhin-starkware, @noaov1, and @orizi)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 720 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nuc4CGF7xoUsp5-JbQ3:-Nuclu9rAQKax65CQTMZ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fc99220b1cf73029612d7d2b333733c449ca936/crates/blockifier/src/execution/entry_point_test.rs#L720)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

this should probably be done in a preliminary PR.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 759 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nuc7bAs7yVp1AEdCbTW:-NucpuWbCgqVkJEVCXiG:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fc99220b1cf73029612d7d2b333733c449ca936/crates/blockifier/src/execution/syscalls/mod.rs#L759)):*
> ```XML
> #[derive(Debug, Eq, PartialEq)]
> pub struct SHA256ProcessBlockResponse {
>     pub state: Relocatable,
> ```

Done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 794 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nuc7v2F9WaVFddrhmkW:-NucnbW9E83bR2LIrOyj:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fc99220b1cf73029612d7d2b333733c449ca936/crates/blockifier/src/execution/syscalls/mod.rs#L794)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

this was already done here:
https://github.com/starkware-libs/blockifier/blob/940fc056cb57f33b584ee918c0bee2cc762cc370/crates/blockifier/src/execution/syscalls/hint_processor.rs#L471
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 807 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nuc8uHtCBz77VUfmuCf:-Nucnv93EVhVJKRofMQs:b-pnkh6j) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fc99220b1cf73029612d7d2b333733c449ca936/crates/blockifier/src/execution/syscalls/mod.rs#L807)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

is there a ways to do it without building a vector?
</blockquote></details>

used Ori's solution
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 809 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nucg0-C6ipiZQmqD1xM:-Nucnt4Y3Bj-m3jHaBqB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fc99220b1cf73029612d7d2b333733c449ca936/crates/blockifier/src/execution/syscalls/mod.rs#L809)):*
<details><summary><i>Previously, orizi wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 201 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nuc40oX3Zt2fgftn5Zt:-Nuc48t-5El8K2jMLwwa:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb32e769e4c69beb95ee679a5327d0942c8608d7/crates/blockifier/src/versioned_constants_test.rs#L201)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-07 12:04 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: 5 of 17 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @orizi)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 140 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nuc3pOTCZhZGv8BxWHK:-Nurzb-a6QmQ1RMUBR0R:b-raqyri) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fc99220b1cf73029612d7d2b333733c449ca936/crates/blockifier/resources/versioned_constants_13_0.json#L140)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

@noaov1  do we need to add it here?
The syscall wasn't supported in that version.
</blockquote></details>

Yes, for backward compatibility. Please set all the values to 0 in the files 13.0, 13.1 and 13.1.1


<!-- Sent from Reviewable.io -->

2024-04-07 12:51 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: 5 of 17 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware, @noaov1, and @orizi)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 140 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nuc3pOTCZhZGv8BxWHK:-NusbHF60vb8-fySZhM0:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fc99220b1cf73029612d7d2b333733c449ca936/crates/blockifier/resources/versioned_constants_13_0.json#L140)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Yes, for backward compatibility. Please set all the values to 0 in the files 13.0, 13.1 and 13.1.1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-09 09:19 UTC, orizi reviewed
> Reviewed 1 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: 4 of 19 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-04-09 10:03 UTC, orizi approved these changes

2024-04-09 10:49 UTC, noaov1 requested changes
> Reviewed 4 of 15 files at r1, 1 of 8 files at r2, 2 of 3 files at r3, 1 of 3 files at r4, 1 of 2 files at r5, 1 of 2 files at r7, 3 of 5 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: 13 of 19 files reviewed, 14 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @TomerStarkware)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 140 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nuc3pOTCZhZGv8BxWHK:-Nv1JdoB1e8i0Rm03xMf:bffc30k) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fc99220b1cf73029612d7d2b333733c449ca936/crates/blockifier/resources/versioned_constants_13_0.json#L140)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you please add here ` "range_check_gas_cost": 0`?
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 27 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv1Jxb63bIBy5-YKdSB:-Nv1Jxb63bIBy5-YKdSC:bgnl20x) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/hint_processor.rs#L27)):*
> ```XML
> use thiserror::Error;
> 
> use super::sha_256_process_block;
> ```

Please avoid using `super`.



_Code quote:_
```XML
use super::sha_256_process_block;
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 207 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv1Po933eJdK5Hx0TIx:-Nv1Po933eJdK5Hx0TIy:brumjko) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/hint_processor.rs#L207)):*
> ```XML
>     pub secp256r1_hint_processor: SecpHintProcessor<ark_secp256r1::Config>,
> 
>     pub sha256_segment: Option<Relocatable>,
> ```

Please add documentation.
Is this a segment per entry point execution (not including inner calls)?



_Suggestion:_
```XML
    pub sha256_segment_start_ptr: Option<Relocatable>,
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 731 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv1NTuh0zbcyDcQor1b:-Nv1NTuh0zbcyDcQor1c:b-qlg5d9) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/mod.rs#L731)):*
> ```XML
>     })
> }
> ```

It is a cairo1 syscall, right?
Is the syscall named sha256_process_block?
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 768 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv1P2eABxbAAmbwNlrr:-Nv1P2eABxbAAmbwNlrs:b-n9py3l) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/mod.rs#L768)):*
> ```XML
> }
> 
> pub fn sha_256_process_block(
> ```

Not sure if it's better.



_Suggestion:_
```XML
pub fn sha256_process_block(
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 791 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv1O_i-27FU6VmyiwaT:-Nv1O_i-27FU6VmyiwaU:b90sijf) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/mod.rs#L791)):*
> ```XML
> 
>     let data_as_bytes = sha2::digest::generic_array::GenericArray::from_exact_iter(
>         data.iter().flat_map(|felt| felt.to_bigint().to_u32().unwrap().to_be_bytes()),
> ```

Does it work?



_Suggestion:_
```XML
        data.iter().flat_map(|felt| felt.to_be_bytes()),
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 793 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv1OjbsChPTIiitboYJ:-Nv1OjbsChPTIiitboYK:bwxfxof) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/mod.rs#L793)):*
> ```XML
>         data.iter().flat_map(|felt| felt.to_bigint().to_u32().unwrap().to_be_bytes()),
>     )
>     .unwrap();
> ```

Please use expect explaining why this should not panic.



_Code quote:_
```XML
    .unwrap();
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 795 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv1RUjl4Z39UMDYxofX:-Nv1RUjl4Z39UMDYxofY:b-bcmza8) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/mod.rs#L795)):*
> ```XML
>     .unwrap();
>     let mut state_as_words: [u32; SHA256_STATE_SIZE] =
>         core::array::from_fn(|i| prev_state[i].to_bigint().to_u32().unwrap());
> ```

What will happen if the felt is bigger than one word?



_Code quote:_
```XML
rev_state[i].to_bigint().to_u32().unwrap()
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 804 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv1SKri4kveCyuPUIPz:-Nv1SKri4kveCyuPUIQ-:b90sijf) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/mod.rs#L804)):*
> ```XML
>     for felt in state_as_words {
>         write_felt(vm, &mut segment, Felt252::from(felt))?;
>     }
> ```

Does it work?



_Suggestion:_
```XML
    let data: Vec<MaybeRelocatable> =
        state_as_words.iter().map(|&arg| MaybeRelocatable::from(arg)).collect();
    vm.load_data(segment, data)?;
```


<!-- Sent from Reviewable.io -->

2024-04-09 11:20 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 207 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv1Po933eJdK5Hx0TIx:-Nv1_Rxq2LjjQKLyf4Lt:b-6n9ux9) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/hint_processor.rs#L207)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please add documentation.
Is this a segment per entry point execution (not including inner calls)?
</blockquote></details>

The system call advances it so it actually point to the end of the segment.


<!-- Sent from Reviewable.io -->

2024-04-09 11:20 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 731 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv1NTuh0zbcyDcQor1b:-Nv1_Xm5Dla4XvLBkQjG:b2nign6) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/mod.rs#L731)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It is a cairo1 syscall, right?
Is the syscall named sha256_process_block?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2024-04-09 11:22 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 207 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv1Po933eJdK5Hx0TIx:-Nv1_kG18KtmC3-k_slS:b-cc5x57) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/hint_processor.rs#L207)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

The system call advances it so it actually point to the end of the segment.
</blockquote></details>

Aren't all the segments in the blockifer per entry point?


<!-- Sent from Reviewable.io -->

2024-04-09 15:08 UTC, noaov1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: 13 of 19 files reviewed, 14 unresolved discussions (waiting on @ilyalesokhin-starkware, @orizi, and @TomerStarkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 207 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv1Po933eJdK5Hx0TIx:-Nv2OdoI9B-aHpG3qN8c:bb1q7bc) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/hint_processor.rs#L207)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Aren't all the segments in the blockifer per entry point?
</blockquote></details>

I see, thanks. Consider renaming it to`sha256_segment_end_ptr`. And yes.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 807 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv2NIwK19X-zxTfhsfO:-Nv2NIwK19X-zxTfhsfP:bk2wnaa) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/mod.rs#L807)):*
> ```XML
>     syscall_handler.sha256_segment = Some(segment);
> 
>     Ok(SHA256ProcessBlockResponse { state_ptr: respone })
> ```

Out of curiosity- do we return the end pointer of the segment? What is it used for?



_Code quote:_
```XML
    Ok(SHA256ProcessBlockResponse { state_ptr: respone })
```


<!-- Sent from Reviewable.io -->

2024-04-09 17:31 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: 11 of 19 files reviewed, 14 unresolved discussions (waiting on @ilyalesokhin-starkware, @noaov1, and @orizi)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 140 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nuc3pOTCZhZGv8BxWHK:-Nv2eknj2Tf6EObg_lSt:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fc99220b1cf73029612d7d2b333733c449ca936/crates/blockifier/resources/versioned_constants_13_0.json#L140)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please add here ` "range_check_gas_cost": 0`?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 27 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv1Jxb63bIBy5-YKdSB:-Nv2fJSe7cFS3IQhi37K:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/hint_processor.rs#L27)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please avoid using `super`.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 207 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv1Po933eJdK5Hx0TIx:-Nv2fXPI-kKshX92FZrd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/hint_processor.rs#L207)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I see, thanks. Consider renaming it to`sha256_segment_end_ptr`. And yes.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 768 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv1P2eABxbAAmbwNlrr:-Nv2trtMEJ4RyP3WAajI:bi1ssi2) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/mod.rs#L768)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Not sure if it's better.
</blockquote></details>

its inconsistent with other places
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 791 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv1O_i-27FU6VmyiwaT:-Nv2haia6Z5_iNWbrtOA:b-ysztsg) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/mod.rs#L791)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Does it work?
</blockquote></details>

felt.to_bytes() gives 32 bytes and we need 4,
I can use felt.to\_be\_bytes().into\_iter().skip(28) instead
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 793 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv1OjbsChPTIiitboYJ:-Nv2lQqoCSYDny9uBt3S:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/mod.rs#L793)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please use expect explaining why this should not panic.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 795 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv1RUjl4Z39UMDYxofX:-Nv2mdgBC_f6ZdEjIz5C:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/mod.rs#L795)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What will happen if the felt is bigger than one word?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 804 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv1SKri4kveCyuPUIPz:-Nv2qe4HBvUnR2JpgA7r:bn3ojr1) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/mod.rs#L804)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Does it work?
</blockquote></details>

Still need to convert arg to felt
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 807 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nv2NIwK19X-zxTfhsfO:-Nv2rtaM8LdP_S9XEXhN:b-lk6lgb) ([raw file](https://github.com/starkware-libs/blockifier/blob/b38bc9b5c1604ec70ff23c589423ed4eb498b3bc/crates/blockifier/src/execution/syscalls/mod.rs#L807)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Out of curiosity- do we return the end pointer of the segment? What is it used for?
</blockquote></details>

it points to the last 8 words of the segment which are the hash (or current state of the hash if the input does not fit into one block)


<!-- Sent from Reviewable.io -->

2024-04-14 11:41 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 140 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nuc3pOTCZhZGv8BxWHK:-NvRPCFi17swzBo9jR6v:b-ozkwcn) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fc99220b1cf73029612d7d2b333733c449ca936/crates/blockifier/resources/versioned_constants_13_0.json#L140)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why do we need to files belonging to new versions when we add a new syscall?


<!-- Sent from Reviewable.io -->

2024-04-14 11:50 UTC, ilyalesokhin-starkware reviewed
> Reviewed 1 of 15 files at r1, 1 of 3 files at r3, 1 of 2 files at r5, 2 of 5 files at r8, 1 of 1 files at r9, 8 of 9 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: 17 of 19 files reviewed, 8 unresolved discussions (waiting on @noaov1 and @orizi)



<!-- Sent from Reviewable.io -->

2024-05-01 12:55 UTC, noaov1 requested changes
> Reviewed 1 of 2 files at r5, 1 of 2 files at r11, 9 of 9 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: all files reviewed, 6 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 225 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nwo3MYyAQj4ZGzlyzZ5:-Nwo3MYyAQj4ZGzlyzZ6:buii5dh) ([raw file](https://github.com/starkware-libs/blockifier/blob/06f624e213c6a8f84d03952e018124a1212496cc/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L225)):*
> ```Cairo
> 
>     #[external(v0)]
>     fn test_sha256(ref self: ContractState) {
> ```

Can you please explain what you test here?



_Code quote:_
```Cairo
    fn test_sha256(ref self: ContractState) {
```
___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 140 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nuc3pOTCZhZGv8BxWHK:-Nwo1cuNARKxRMQYIo9A:b-lbut5x) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fc99220b1cf73029612d7d2b333733c449ca936/crates/blockifier/resources/versioned_constants_13_0.json#L140)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why do we need to files belonging to new versions when we add a new syscall?
</blockquote></details>

What do you mean?
___
*[`crates/blockifier/resources/versioned_constants_13_2.json` line 1 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nwo20SN1WvSOxmujlpe:-Nwo20SN1WvSOxmujlpf:b-zi7nlt) ([raw file](https://github.com/starkware-libs/blockifier/blob/06f624e213c6a8f84d03952e018124a1212496cc/crates/blockifier/resources/versioned_constants_13_2.json#L1)):*
> ```JSON
> {
> ```

Why did you add this file?
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 789 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-NwoASdW23c-MuG_Wil5:-NwoASdW23c-MuG_Wil6:be2emrj) ([raw file](https://github.com/starkware-libs/blockifier/blob/06f624e213c6a8f84d03952e018124a1212496cc/crates/blockifier/src/execution/syscalls/mod.rs#L789)):*
> ```XML
>     let prev_state = vm.get_integer_range(request.state_ptr, SHA256_STATE_SIZE)?;
> 
>     let data_as_bytes =
> ```

Each element is a word represented in bytes, right?



_Code quote:_
```XML
    let data_as_bytes =
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 796 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nwo8sxj7ImAZ4LSGTk5:-Nwo8sxkDr9aTc3rwzQ2:bcaqhgm) ([raw file](https://github.com/starkware-libs/blockifier/blob/06f624e213c6a8f84d03952e018124a1212496cc/crates/blockifier/src/execution/syscalls/mod.rs#L796)):*
> ```XML
>                 .to_be_bytes()
>         }))
>         .expect("u32.to_be_bytes() always returns an array of 4 bytes.");
> ```

Where do you define the size for the `GenericArray`?
I see that the method `compress256` expects  `GenericArray<u8, U64>`.



_Code quote:_
```XML
.expect("u32.to_be_bytes() always returns an array of 4 bytes.");
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 797 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-NwoAbZ02Yp3nSC2dCQ8:-NwoAbZ02Yp3nSC2dCQ9:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/06f624e213c6a8f84d03952e018124a1212496cc/crates/blockifier/src/execution/syscalls/mod.rs#L797)):*
> ```XML
>         }))
>         .expect("u32.to_be_bytes() always returns an array of 4 bytes.");
>     let mut state_as_words: [u32; SHA256_STATE_SIZE] = core::array::from_fn(|i| {
> ```





_Suggestion:_
```XML

let mut state_as_words: [u32; SHA256_STATE_SIZE] = core::array::from_fn(|i| {
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 807 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-NwoByurDNKqBLW_1Tua:-NwoByurDNKqBLW_1Tub:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/06f624e213c6a8f84d03952e018124a1212496cc/crates/blockifier/src/execution/syscalls/mod.rs#L807)):*
> ```XML
>     let segment = syscall_handler.sha256_segment_end_ptr.unwrap_or(vm.add_memory_segment());
> 
>     let respone = segment;
> ```





_Suggestion:_
```XML
    let response = segment;
```


<!-- Sent from Reviewable.io -->

2024-05-01 13:27 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: 12 of 19 files reviewed, 6 unresolved discussions (waiting on @ilyalesokhin-starkware, @noaov1, and @orizi)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 225 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nwo3MYyAQj4ZGzlyzZ5:-NwoGL2tDm-ZOn4ihyzV:b-697fwt) ([raw file](https://github.com/starkware-libs/blockifier/blob/06f624e213c6a8f84d03952e018124a1212496cc/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L225)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain what you test here?
</blockquote></details>

added doc
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 789 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-NwoASdW23c-MuG_Wil5:-NwoG_rODz8Gw-3RK0QT:b2nign6) ([raw file](https://github.com/starkware-libs/blockifier/blob/06f624e213c6a8f84d03952e018124a1212496cc/crates/blockifier/src/execution/syscalls/mod.rs#L789)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Each element is a word represented in bytes, right?
</blockquote></details>

yes
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 796 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nwo8sxj7ImAZ4LSGTk5:-NwoHlyvCRmWUR5tWdLM:b-to4732) ([raw file](https://github.com/starkware-libs/blockifier/blob/06f624e213c6a8f84d03952e018124a1212496cc/crates/blockifier/src/execution/syscalls/mod.rs#L796)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Where do you define the size for the `GenericArray`?
I see that the method `compress256` expects  `GenericArray<u8, U64>`.
</blockquote></details>

Its inferenced from the call to compress256,

the input in `sha256 block` is 64 bytes, and we have checked that the data has a length of 16 and each element 4 bytes.  
___
*[`crates/blockifier/resources/versioned_constants_13_2.json` line 1 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nwo20SN1WvSOxmujlpe:-NwoGUTs2EyIqKPwUS57:bvth56w) ([raw file](https://github.com/starkware-libs/blockifier/blob/06f624e213c6a8f84d03952e018124a1212496cc/crates/blockifier/resources/versioned_constants_13_2.json#L1)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why did you add this file?
</blockquote></details>

reverted


<!-- Sent from Reviewable.io -->

2024-05-01 15:54 UTC, noaov1 reviewed
> Reviewed 4 of 7 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: 16 of 19 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-05-02 05:54 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 140 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nuc3pOTCZhZGv8BxWHK:-NwrrW2u4AGt9O3fr4hI:bzdmfue) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fc99220b1cf73029612d7d2b333733c449ca936/crates/blockifier/resources/versioned_constants_13_0.json#L140)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

Sorry, I meant:

Why do we need to add new system calls to old versions where those system calls weren't even supported.


<!-- Sent from Reviewable.io -->

2024-05-02 09:49 UTC, noaov1 reviewed
> Reviewed 2 of 7 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 233 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-NwsgG6d5ha_l8MrGROu:-NwsgG6d5ha_l8MrGROv:b-3zje6p) ([raw file](https://github.com/starkware-libs/blockifier/blob/7c1a5f004b8c6755e516a96ae149330e09c28958/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L233)):*
> ```Cairo
>         assert(res == 0x61be55a8, 'Wrong hash value');
> 
>         // Test that the sha256 syscall fails when the input length is not a multiple of 4.
> ```

Where can I see we check it in the code? I see you verify `input_length == SHA256_BLOCK_SIZE = 16`



_Code quote:_
```Cairo
        // Test that the sha256 syscall fails when the input length is not a multiple of 4.
```
___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 140 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nuc3pOTCZhZGv8BxWHK:-NwseZZ40U3socqkL65V:b5r4b1i) ([raw file](https://github.com/starkware-libs/blockifier/blob/7fc99220b1cf73029612d7d2b333733c449ca936/crates/blockifier/resources/versioned_constants_13_0.json#L140)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Sorry, I meant:

Why do we need to add new system calls to old versions where those system calls weren't even supported.
</blockquote></details>

Good question. We want to support running older versions of this file using the current code. 
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 796 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nwo8sxj7ImAZ4LSGTk5:-NwsgkMDEgc2XUhfg3w7:b-rokfd4) ([raw file](https://github.com/starkware-libs/blockifier/blob/06f624e213c6a8f84d03952e018124a1212496cc/crates/blockifier/src/execution/syscalls/mod.rs#L796)):*
<details><summary><i>Previously, TomerStarkware wrote…</i></summary><blockquote>

Its inferenced from the call to compress256,

the input in `sha256 block` is 64 bytes, and we have checked that the data has a length of 16 and each element 4 bytes.
</blockquote></details>

I see. Can you please write this explanation in the expect? 


<!-- Sent from Reviewable.io -->

2024-05-02 09:59 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: 17 of 19 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 233 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-NwsgG6d5ha_l8MrGROu:-NwsivhP8e1bxTMlCsgd:bykyw1f) ([raw file](https://github.com/starkware-libs/blockifier/blob/7c1a5f004b8c6755e516a96ae149330e09c28958/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L233)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Where can I see we check it in the code? I see you verify `input_length == SHA256_BLOCK_SIZE = 16`
</blockquote></details>

its suppose to be 16,
fixed doc


<!-- Sent from Reviewable.io -->

2024-05-02 10:02 UTC, noaov1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-:-Nwsk3kS3BOGx-4oOFUw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-05-16 10:12 UTC, ilyalesokhin-starkware reviewed
> Reviewed 1 of 8 files at r2, 1 of 2 files at r7, 1 of 2 files at r11, 5 of 7 files at r14, 1 of 1 files at r15, 2 of 2 files at r16, 5 of 6 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-05-21 13:57 UTC, orizi approved these changes
> Reviewed 1 of 6 files at r17, 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: all files reviewed, 1 unresolved discussion (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-05-29 16:56 UTC, noaov1 reviewed
> Reviewed 10 of 10 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: all files reviewed, 2 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 96 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nz4GXMq4c9opO8-5nQ2:-Nz4GXMq4c9opO8-5nQ3:b-vj68f1) ([raw file](https://github.com/starkware-libs/blockifier/blob/b2ae16382e4e4b53296a0b087cf2b885592e052e/crates/blockifier/resources/versioned_constants.json#L96)):*
> ```JSON
>             "step_gas_cost": 11822,
>             "range_check_gas_cost": 448
>         },
> ```

What is it used for?



_Code quote:_
```JSON
        "sha256_batch_gas_cost": {
            "step_gas_cost": 11822,
            "range_check_gas_cost": 448
        },
```


<!-- Sent from Reviewable.io -->

2024-05-29 17:47 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: 18 of 20 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/resources/versioned_constants.json` line 89 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Ny-sh4p56TDBcLWdjSc:-Nz4P8IW1nqgzvjam2Wh:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5d38931807f01de4453e394598f1a7716fbc5188/crates/blockifier/resources/versioned_constants.json#L89)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

how come there is no
bitwise_builtin?
</blockquote></details>

Done.
___
*[`crates/blockifier/resources/versioned_constants.json` line 96 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-Nz4GXMq4c9opO8-5nQ2:-Nz4P91i3178K4Ls1j6O:b5ev6xw) ([raw file](https://github.com/starkware-libs/blockifier/blob/b2ae16382e4e4b53296a0b087cf2b885592e052e/crates/blockifier/resources/versioned_constants.json#L96)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What is it used for?
</blockquote></details>

we split the hint validation of the syscall into two parts, the first part copies the input of an array in the os, 
 the second which does the actual output validation is executed after all the transactions and validates all calls in batches of 7 calls at a time.
This is the price of validating all 7 syscalls,
the price of `sha256_process_block_gas_cost` is the combined price of the parts  


<!-- Sent from Reviewable.io -->

2024-05-30 06:10 UTC, ilyalesokhin-starkware reviewed
> Reviewed 1 of 2 files at r18, 6 of 10 files at r19, 2 of 2 files at r20.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-06-03 13:38 UTC, ilyalesokhin-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 10 files at r19, 3 of 3 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-:-NzTJb7T2g8FcSioICYL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-06-04 07:33 UTC, noaov1 reviewed
> Reviewed 2 of 6 files at r17, 1 of 2 files at r18, 1 of 2 files at r20, 3 of 3 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: all files reviewed, 3 unresolved discussions (waiting on @TomerStarkware)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 148 at r21](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-NzX8TJ22s5P8_10fB2x:-NzX8TJ22s5P8_10fB2y:ba3dfna) ([raw file](https://github.com/starkware-libs/blockifier/blob/64b44588e544329baded248a56498affe9851d57/crates/blockifier/resources/versioned_constants_13_0.json#L148)):*
> ```JSON
>             "step_gas_cost": 0,
>             "range_check_gas_cost": 0
>         },
> ```

Remove?



_Code quote:_
```JSON
        "sha256_batch_gas_cost": {
            "step_gas_cost": 0,
            "range_check_gas_cost": 0
        },
```
___
*[`crates/blockifier/resources/versioned_constants_13_1_1.json` line 169 at r21](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-NzX8XdU1ftFZhQx5lTZ:-NzX8XdU1ftFZhQx5lT_:ba3dfna) ([raw file](https://github.com/starkware-libs/blockifier/blob/64b44588e544329baded248a56498affe9851d57/crates/blockifier/resources/versioned_constants_13_1_1.json#L169)):*
> ```JSON
>             "step_gas_cost": 0,
>             "range_check_gas_cost": 0
>         },
> ```

Remove?



_Code quote:_
```JSON
        "sha256_batch_gas_cost": {
            "step_gas_cost": 0,
            "range_check_gas_cost": 0
        },
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 438 at r21](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-NzX8_uT-KP_I_24Erk_:-NzX8_uT-KP_I_24Erka:bxtub52) ([raw file](https://github.com/starkware-libs/blockifier/blob/64b44588e544329baded248a56498affe9851d57/crates/blockifier/src/versioned_constants.rs#L438)):*
> ```XML
>     pub keccak_gas_cost: u64,
>     pub keccak_round_cost_gas_cost: u64,
>     pub sha256_process_block_gas_cost: u64,
> ```

Is it needed?



_Code quote:_
```XML
    pub sha256_process_block_gas_cost: u64,
```


<!-- Sent from Reviewable.io -->

2024-06-04 08:45 UTC, TomerStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: 18 of 20 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 148 at r21](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-NzX8TJ22s5P8_10fB2x:-NzXPvU7BPX0KuWQ5RF4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/64b44588e544329baded248a56498affe9851d57/crates/blockifier/resources/versioned_constants_13_0.json#L148)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.
___
*[`crates/blockifier/resources/versioned_constants_13_1_1.json` line 169 at r21](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-NzX8XdU1ftFZhQx5lTZ:-NzXPw-E0ZRWUuoX9flp:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/64b44588e544329baded248a56498affe9851d57/crates/blockifier/resources/versioned_constants_13_1_1.json#L169)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 438 at r21](https://reviewable.io/reviews/starkware-libs/blockifier/1754#-NzX8_uT-KP_I_24Erk_:-NzXQ0BW0Zxu-OE2ICPI:bvozvus) ([raw file](https://github.com/starkware-libs/blockifier/blob/64b44588e544329baded248a56498affe9851d57/crates/blockifier/src/versioned_constants.rs#L438)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it needed?
</blockquote></details>

this one is the full cost, which still exists in version_constants.json


<!-- Sent from Reviewable.io -->

2024-06-04 10:32 UTC, noaov1 approved these changes
> Reviewed 2 of 2 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-06-14 11:16 UTC, noaov1 approved these changes
> Reviewed 3 of 3 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1754)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TomerStarkware)



<!-- Sent from Reviewable.io -->

2024-06-16 06:22 UTC, merged