concurrency: create an enveloper state for fee transfer
starkware-libs/blockifier pull request #1766
Opened 2024-04-08 12:58 UTC by meship-starkware

2024-04-08 13:04 UTC, meship-starkware commented
The final commit, which will update the sequencer balance,  still needs to be written.  I will add another commit with tests to this method.

2024-04-09 11:20 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 346 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv0vFPCBYLd3pUjxP9P:-Nv1_ZzBBy8Lr3-H3CAN:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb626247aa41ea47e2b97602413455c3095bee1a/crates/blockifier/src/transaction/account_transaction.rs#L346)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please document.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 349 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv0vPD44b9ZfP502Zcq:-Nv1_cgy1PfQLGe7HXbC:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bb626247aa41ea47e2b97602413455c3095bee1a/crates/blockifier/src/transaction/account_transaction.rs#L349)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please document.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-09 11:47 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-NuxxO72D1E2ngFw8JPW:-NuxxO72D1E2ngFw8JPX:b3kqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/df8d9e9e9981abbc50cdfeb913e70c95c6532343/crates/blockifier/src/transaction/account_transaction.rs#L289)):*
> ```XML
>         }
>         let fee_transfer_call_info = if concurrecy {
>             Self::concurecy_execute_fee_transfer(state, tx_context, actual_fee)?
> ```

.



_Suggestion:_
```XML
concurrency
```


<!-- Sent from Reviewable.io -->

2024-04-09 14:38 UTC, noaov1 requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: all files reviewed, 7 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 319 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv2CXnh39cfuZa-XsIG:-Nv2CXni8pES6SdNpZoK:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/45e4fcf904eee171457a7dd15035eeda23bf152b/crates/blockifier/src/transaction/account_transaction.rs#L319)):*
> ```XML
>             caller_address: tx_info.sender_address(),
>             call_type: CallType::Call,
>             // The fee-token contract is a Cairo 0 contract, hence the initial gas is irrelevant.
> ```





_Suggestion:_
```XML
      // We take the gas usage of the fee transfer into account in the transaction execution. 
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 330 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv2HQu797F8185Ky_Wm:-Nv2HQu797F8185Ky_Wn:borreg2) ([raw file](https://github.com/starkware-libs/blockifier/blob/45e4fcf904eee171457a7dd15035eeda23bf152b/crates/blockifier/src/transaction/account_transaction.rs#L330)):*
> ```XML
>     }
> 
>     fn concurecy_execute_fee_transfer<S: StateReader>(
> ```

Please document.



_Code quote:_
```XML
    fn concurecy_execute_fee_transfer<S: StateReader>(
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 338 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv2H6MVDlL_j6K56JRj:-Nv2H6MVDlL_j6K56JRk:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/45e4fcf904eee171457a7dd15035eeda23bf152b/crates/blockifier/src/transaction/account_transaction.rs#L338)):*
> ```XML
>         let storage_address = block_context.chain_info.fee_token_address(&tx_info.fee_type());
>         let sequencer_address = block_context.block_info.sequencer_address;
>         let sequencer_key = get_fee_token_var_address(sequencer_address);
> ```





_Suggestion:_
```XML
        let sequencer_balance_key_low = get_fee_token_var_address(sequencer_address);
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 342 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv2BriX6GPY17OvxTJC:-Nv2BriX6GPY17OvxTJD:b-krnovg) ([raw file](https://github.com/starkware-libs/blockifier/blob/45e4fcf904eee171457a7dd15035eeda23bf152b/crates/blockifier/src/transaction/account_transaction.rs#L342)):*
> ```XML
> 
>         // Set the initail value of the storage key of the sequencer balance to
>         // a dummy value to avoid tarnishing the read set of the transaction state cahe.
> ```

Do we read only the first (LSB) storage cell?
I think you should add `next_storage_key(&sequencer_balance_key_low)` 



_Suggestion:_
```XML
        // Sets the initail value of the storage key of the sequencer balance to
        // a dummy value to avoid tarnishing the read set of the transaction state cahe.
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 350 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv1wYJm9bME-vh-WjJd:-Nv1wYJnCFUb1qLK037Q:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/45e4fcf904eee171457a7dd15035eeda23bf152b/crates/blockifier/src/transaction/account_transaction.rs#L350)):*
> ```XML
>         let result =
>             AccountTransaction::execute_fee_transfer(&mut transfer_state, tx_context, actual_fee);
>         // delete the update of the sequencer balance from the write set.
> ```





_Suggestion:_
```XML
        // Remove the write to the sequencer balance.
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 351 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv2Hmcu1Lz6lBP5DhWG:-Nv2Hmcu1Lz6lBP5DhWH:b-1rf14q) ([raw file](https://github.com/starkware-libs/blockifier/blob/45e4fcf904eee171457a7dd15035eeda23bf152b/crates/blockifier/src/transaction/account_transaction.rs#L351)):*
> ```XML
>             AccountTransaction::execute_fee_transfer(&mut transfer_state, tx_context, actual_fee);
>         // delete the update of the sequencer balance from the write set.
>         transfer_state.cache.get_mut().storage_writes.remove(&(storage_address, sequencer_key));
> ```

Please remove the balance high key as well. It will probably be 0, but just in case. 



_Code quote:_
```XML
transfer_state.cache.get_mut().storage_writes.remove(&(storage_address, sequencer_key));
```


<!-- Sent from Reviewable.io -->

2024-04-10 11:47 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 289 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-NuxxO72D1E2ngFw8JPW:-Nv1iJhp12Wj4DuwUH1E:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/df8d9e9e9981abbc50cdfeb913e70c95c6532343/crates/blockifier/src/transaction/account_transaction.rs#L289)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 338 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv2H6MVDlL_j6K56JRj:-Nv6pAs9Dz4_JUnvB8zH:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/45e4fcf904eee171457a7dd15035eeda23bf152b/crates/blockifier/src/transaction/account_transaction.rs#L338)):*
> ```XML
>         let storage_address = block_context.chain_info.fee_token_address(&tx_info.fee_type());
>         let sequencer_address = block_context.block_info.sequencer_address;
>         let sequencer_key = get_fee_token_var_address(sequencer_address);
> ```

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 350 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv1wYJm9bME-vh-WjJd:-Nv6pCnE3ZJUuyE1Q6kC:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/45e4fcf904eee171457a7dd15035eeda23bf152b/crates/blockifier/src/transaction/account_transaction.rs#L350)):*
> ```XML
>         let result =
>             AccountTransaction::execute_fee_transfer(&mut transfer_state, tx_context, actual_fee);
>         // delete the update of the sequencer balance from the write set.
> ```

Done.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 351 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv2Hmcu1Lz6lBP5DhWG:-Nv6pEvs1lsM16omYCC3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/45e4fcf904eee171457a7dd15035eeda23bf152b/crates/blockifier/src/transaction/account_transaction.rs#L351)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please remove the balance high key as well. It will probably be 0, but just in case.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-10 13:23 UTC, noaov1 requested changes
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: all files reviewed, 12 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 341 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv76IDO22G1THD-UBlW:-Nv76IDO22G1THD-UBlX:b-j4000m) ([raw file](https://github.com/starkware-libs/blockifier/blob/6afe77e19cfa5b88116f9ff331bda2b2690f21bc/crates/blockifier/src/transaction/account_transaction.rs#L341)):*
> ```XML
>         let sequencer_balance_key_low = get_fee_token_var_address(sequencer_address);
>         let sequencer_balance_key_high = next_storage_key(&sequencer_balance_key_low)
>             .expect("Cannot get sequencer balance high key.");
> ```

Do we want to panic in this case?
Maybe yes, since it's not a transaction failure but more of an internal requirement.
For the higher key of the account contract we return an error (which makes sense, since it relates directly to the transaction).



_Code quote:_
```XML
        let sequencer_balance_key_high = next_storage_key(&sequencer_balance_key_low)
            .expect("Cannot get sequencer balance high key.");
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 355 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv73MvZ-HzJyC1FcVyZ:-Nv73Mv_9z1RI073_uP1:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6afe77e19cfa5b88116f9ff331bda2b2690f21bc/crates/blockifier/src/transaction/account_transaction.rs#L355)):*
> ```XML
>             sequencer_balance_key_high,
>             StarkFelt::from(0_u8),
>         );
> ```





_Suggestion:_
```XML
        let cache = transfer_state.cache.get_mut();
        cache.set_storage_initial_value(
            storage_address,
            sequencer_balance_key_low,
            StarkFelt::from_u128(actual_fee.0),
        );
        cache.set_storage_initial_value(
            storage_address,
            sequencer_balance_key_high,
            StarkFelt::from(0_u8),
        );
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 358 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv77sNl6i4Is0Gyim7J:-Nv77sNmAgf5jSFPLB6p:b-fqssiv) ([raw file](https://github.com/starkware-libs/blockifier/blob/6afe77e19cfa5b88116f9ff331bda2b2690f21bc/crates/blockifier/src/transaction/account_transaction.rs#L358)):*
> ```XML
>         let result =
>             AccountTransaction::execute_fee_transfer(&mut transfer_state, tx_context, actual_fee);
>         // Remove the write to the sequencer balance.
> ```

My bad :)



_Suggestion:_
```XML
        // Removes the write to the sequencer balance.
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 368 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv738gBA9ef_tf4EuoG:-Nv738gBA9ef_tf4EuoH:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6afe77e19cfa5b88116f9ff331bda2b2690f21bc/crates/blockifier/src/transaction/account_transaction.rs#L368)):*
> ```XML
>             .get_mut()
>             .storage_writes
>             .remove(&(storage_address, sequencer_balance_key_high));
> ```





_Suggestion:_
```XML
        let mut storage_writes = &mut transfer_state
            .cache
            .get_mut()
            .storage_writes;
        storage_writes.remove(&(storage_address, sequencer_balance_key_low));
        storage_writes.remove(&(storage_address, sequencer_balance_key_high));
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1189 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv78rr7EV8kTnBiAvjO:-Nv78rr7EV8kTnBiAvjP:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6afe77e19cfa5b88116f9ff331bda2b2690f21bc/crates/blockifier/src/transaction/account_transactions_test.rs#L1189)):*
> ```XML
>     let tx_context = Arc::new(block_context.to_tx_context(&account_tx));
>     let storage_address =
>         block_context.chain_info.fee_token_address(&tx_context.tx_info.fee_type());
> ```





_Suggestion:_
```XML
    let fee_token_address =
        block_context.chain_info.fee_token_address(&tx_context.tx_info.fee_type());
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1193 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv78vnPCdq2xDqMOHrU:-Nv78vnPCdq2xDqMOHrV:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6afe77e19cfa5b88116f9ff331bda2b2690f21bc/crates/blockifier/src/transaction/account_transactions_test.rs#L1193)):*
> ```XML
>     let sequencer_balance_key_low = get_fee_token_var_address(sequencer_address);
>     let sequencer_balance_key_high = next_storage_key(&sequencer_balance_key_low)
>         .expect("Cannot get sequencer balance high key.");
> ```





_Suggestion:_
```XML
    let sequencer_balance_key_high = next_storage_key(&sequencer_balance_key_low)
        .unwrap();
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1196 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv79NWEBXX3wOMBE0Hv:-Nv79NWF9oSQX4SfF6Zd:b5ze5iy) ([raw file](https://github.com/starkware-libs/blockifier/blob/6afe77e19cfa5b88116f9ff331bda2b2690f21bc/crates/blockifier/src/transaction/account_transactions_test.rs#L1196)):*
> ```XML
> 
>     // Case 1: The transaction did not read form/ write to the sequenser balance before executing
>     // fee transfer.
> ```

Please add a TODO + Monday task to use the entire account transaction flow once it's supported.



_Code quote:_
```XML
    // Case 1: The transaction did not read form/ write to the sequenser balance before executing
    // fee transfer.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1208 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv795tcARmPC2oka48n:-Nv795tcARmPC2oka48o:bmkk2eb) ([raw file](https://github.com/starkware-libs/blockifier/blob/6afe77e19cfa5b88116f9ff331bda2b2690f21bc/crates/blockifier/src/transaction/account_transactions_test.rs#L1208)):*
> ```XML
>         transactional_state
>             .cache
>             .borrow()
> ```

Please define a variable for the cache.



_Code quote:_
```XML
        transactional_state
            .cache
            .borrow()
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1257 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv79lkG9dkPnCxnTwOE:-Nv79lkG9dkPnCxnTwOF:b-2hyngs) ([raw file](https://github.com/starkware-libs/blockifier/blob/6afe77e19cfa5b88116f9ff331bda2b2690f21bc/crates/blockifier/src/transaction/account_transactions_test.rs#L1257)):*
> ```XML
>         sequencer_balance_key_high,
>         StarkFelt::from(147_u8),
>     );
> ```

Please use the method `get_storage_at` which triggers this exact behaviour. 



_Code quote:_
```XML
    transactional_state_1.cache.get_mut().set_storage_initial_value(
        storage_address,
        sequencer_balance_key_low,
        StarkFelt::from_u128(158_u128),
    );
    transactional_state_1.cache.get_mut().set_storage_initial_value(
        storage_address,
        sequencer_balance_key_high,
        StarkFelt::from(147_u8),
    );
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1267 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv7A6gz919Zy3HFUeoC:-Nv7A6gz919Zy3HFUeoD:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6afe77e19cfa5b88116f9ff331bda2b2690f21bc/crates/blockifier/src/transaction/account_transactions_test.rs#L1267)):*
> ```XML
>     let storage_initial_values =
>         transactional_state_1.cache.borrow().storage_initial_values.clone();
>     let sequnser_read_value_low =
> ```





_Suggestion:_
```XML
    let sequence [...]

2024-04-16 06:08 UTC, Yoni-Starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: 1 of 3 files reviewed, 7 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 320 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv_OIMT0mY1TVbtjRsf:-Nv_OIMU-l4Oyd8_GT2F:bdrvidi) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transaction.rs#L320)):*
> ```XML
>         // TODO(Amos, 8/04/2024): Add test for this assert.
>         Self::assert_actual_fee_in_bounds(&tx_context, actual_fee)?;
>         let fee_transfer_call_info = if block_context().block_info.concurrency_mode {
> ```

Rebase :)



_Code quote:_
```XML
.block_info.concurrency_mode
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 368 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv_QRrU1QJYVDZ6lnP2:-Nv_QRrU1QJYVDZ6lnP3:bh2ug31) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transaction.rs#L368)):*
> ```XML
>     // The function create a transactional state, execute the fee transfer on it
>     // and then erase the read and write set of the sequencer balance.
>     fn concurrency_execute_fee_transfer<S: StateReader>(
> ```

Something a bit less specific
```
/// Handles fee transfer in concurrent execution.
///
/// Accessing and updating the sequencer balance at this stage is a bottleneck; this function manipulates the state to avoid that part.
/// Note: the returned transfer call info is partial, and should be completed at the commit stage, as well as the actual sequencer balance.
```



_Code quote:_
```XML
    // This is a wrapper function to execute fee transfer in a concurrency mode.
    // The function create a transactional state, execute the fee transfer on it
    // and then erase the read and write set of the sequencer balance.
    fn concurrency_execute_fee_transfer<S: StateReader>(
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 374 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv_UIxS5PLhEPcS--OD:-Nv_UIxS5PLhEPcS--OE:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transaction.rs#L374)):*
> ```XML
>     ) -> TransactionExecutionResult<CallInfo> {
>         let TransactionContext { block_context, tx_info } = tx_context.as_ref();
>         let storage_address = block_context.chain_info.fee_token_address(&tx_info.fee_type());
> ```





_Suggestion:_
```XML
fee_address
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 382 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv_URdb5wvhXbosbAg3:-Nv_URdb5wvhXbosbAg4:bp2hgwu) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transaction.rs#L382)):*
> ```XML
> 
>         // Sets the initail value of the storage key of the sequencer balance to
>         // a dummy value to avoid tarnishing the read set of the transaction state cahe.
> ```

Comments are in ציווי



_Suggestion:_
```XML
        // Set the initial sequencer balance to avoid tarnishing the read-set of the transaction.
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 394 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv_VVNpC-W_BvF8lnBk:-Nv_VVNpC-W_BvF8lnBl:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transaction.rs#L394)):*
> ```XML
>         storage_writes.remove(&(storage_address, sequencer_balance_key_low));
>         storage_writes.remove(&(storage_address, sequencer_balance_key_high));
>         transfer_state.commit();
> ```





_Suggestion:_
```XML
        let result =
            AccountTransaction::execute_fee_transfer(&mut transfer_state, tx_context, actual_fee);
        
        // Commit without updating the sequencer balance.
        let storage_writes = &mut transfer_state.cache.get_mut().storage_writes;
        storage_writes.remove(&(storage_address, sequencer_balance_key_low));
        storage_writes.remove(&(storage_address, sequencer_balance_key_high));
        transfer_state.commit();
```


<!-- Sent from Reviewable.io -->

2024-04-16 06:31 UTC, noaov1 reviewed
> Reviewed 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: 2 of 3 files reviewed, 9 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 10 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-NvXW2OW9L3JJtfodHsi:-NvXW2OW9L3JJtfodHsj:bguvqjn) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transaction.rs#L10)):*
> ```XML
> use starknet_api::transaction::{Calldata, Fee, ResourceBounds, TransactionVersion};
> 
> use super::test_utils::block_context;
> ```

Please avoid using super



_Code quote:_
```XML
use super::test_utils::block_context;
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 386 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv__4DD8uiKb5GO8svG:-Nv__4DECWcsdwXTMUNa:ba4iygm) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transaction.rs#L386)):*
> ```XML
>         for key in [sequencer_balance_key_low, sequencer_balance_key_high] {
>             cache.set_storage_initial_value(storage_address, key, StarkFelt::from(0_u8));
>         }
> ```

I think we want to set the sequencer balance low key to the actual fee (in case the sequencer sends a transaction).



_Code quote:_
```XML
        for key in [sequencer_balance_key_low, sequencer_balance_key_high] {
            cache.set_storage_initial_value(storage_address, key, StarkFelt::from(0_u8));
        }
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 389 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv__bu82OWkI1aiCPoV:-Nv__bu82OWkI1aiCPoW:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transaction.rs#L389)):*
> ```XML
> 
>         let result =
>             AccountTransaction::execute_fee_transfer(&mut transfer_state, tx_context, actual_fee);
> ```





_Suggestion:_
```XML
        let fee_transfer_call_info =
            AccountTransaction::execute_fee_transfer(&mut transfer_state, tx_context, actual_fee);
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 667 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv_aSp9ARJIzR7o8x-m:-Nv_aSp9ARJIzR7o8x-n:ba3dfna) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transaction.rs#L667)):*
> ```XML
>             charge_fee,
>         )?;
>         // TODO(Meshi 05/05/2024) add a concurreny flag to tx context.
> ```

Remove?



_Code quote:_
```XML
        // TODO(Meshi 05/05/2024) add a concurreny flag to tx context.
```


<!-- Sent from Reviewable.io -->

2024-04-16 06:32 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: 2 of 3 files reviewed, 13 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1165 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv_WWEREKQWlRisJjwh:-Nv_WWEREKQWlRisJjwi:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transactions_test.rs#L1165)):*
> ```XML
> 
> #[rstest]
> fn test_concurrncy_execute_fee_transfer(block_context: BlockContext) {
> ```





_Suggestion:_
```XML
fn test_concurrency_execute_fee_transfer
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1183 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv_aIMYDqQu71_qlbDg:-Nv_aIMYDqQu71_qlbDh:b-kjb888) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transactions_test.rs#L1183)):*
> ```XML
>             resource_bounds: l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE),
>             class_hash,
>         },
> ```

No need since it's version 3



_Suggestion:_
```XML
        declare_tx_args! {
            sender_address,
            version: TransactionVersion::THREE,
            resource_bounds: l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE),
            class_hash,
        },
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1185 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv_ZGEW8TzN2zTAn796:-Nv_ZGEW8TzN2zTAn797:b-xj5jsp) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transactions_test.rs#L1185)):*
> ```XML
>         },
>         class_info.clone(),
>     );
> ```

To make this bootstrap shorter, try to use
```rust
    let TestInitData { state, account_address, contract_address, mut nonce_manager } =
        create_test_init_data(&block_context.chain_info, CairoVersion::Cairo1);
```
+ 
```rust
let account_tx = 
```



_Code quote:_
```XML
    let empty_contract = FeatureContract::Empty(CairoVersion::Cairo1);
    let account = FeatureContract::AccountWithoutValidations(CairoVersion::Cairo1);
    let chain_info = &block_context.chain_info;
    let state = &mut test_state(chain_info, BALANCE, &[(account, 1)]);
    let class_hash = empty_contract.get_class_hash();
    let class_info = calculate_class_info_for_testing(empty_contract.get_class());
    let sender_address = account.get_instance_address(0);

    let account_tx = declare_tx(
        declare_tx_args! {
            max_fee: Fee(MAX_FEE),
            sender_address,
            version: TransactionVersion::THREE,
            resource_bounds: l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE),
            class_hash,
        },
        class_info.clone(),
    );
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1217 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv_atfW8ZpXzqcogf8K:-Nv_atfW8ZpXzqcogf8L:bwhauqh) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transactions_test.rs#L1217)):*
> ```XML
>     fund_account(chain_info, sequencer_address, 150_u128, state);
>     let mut transactional_state_1 = CachedState::create_transactional(state);
>     let tx_context_1 = Arc::new(block_context.to_tx_context(&account_tx));
> ```

Is this needed?



_Code quote:_
```XML
let tx_context_1 = Arc::new(block_context.to_tx_context(&account_tx));
```


<!-- Sent from Reviewable.io -->

2024-04-16 06:34 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: 2 of 3 files reviewed, 12 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1185 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv_ZGEW8TzN2zTAn796:-Nv_azx93gxJVxWNFsHw:bgukxra) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transactions_test.rs#L1185)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

To make this bootstrap shorter, try to use
```rust
    let TestInitData { state, account_address, contract_address, mut nonce_manager } =
        create_test_init_data(&block_context.chain_info, CairoVersion::Cairo1);
```
+ 
```rust
let account_tx = 
```
</blockquote></details>

+ invoke_tx(...)

But never mind, it's not significant.


<!-- Sent from Reviewable.io -->

2024-04-16 10:10 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`.vscode/settings.json` line 26 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nva16d_-EcjSNI8llBt:-NvaNeH0-QTWtSBbcyiA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/411fca83f186caeebf755f995f51f0294c796918/.vscode/settings.json#L26)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Revert
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-16 13:06 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 386 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv__4DD8uiKb5GO8svG:-Nvb-1HO5XXeLSynUaB-:b-xive1e) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transaction.rs#L386)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think we want to set the sequencer balance low key to the actual fee (in case the sequencer sends a transaction).
</blockquote></details>

@noa what if the sequencer balance is lower then the actual fee?
If this code is reachable in such case, it may pass a tx that should have been rejected.

Anyway, consider placing the "if sender_address == sequencer_address" somewhere before this line, to avoid it  


<!-- Sent from Reviewable.io -->

2024-04-16 13:21 UTC, noaov1 reviewed
> Reviewed 1 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 386 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv__4DD8uiKb5GO8svG:-Nvb0liJ-s7inK7edkdV:b1b3fxm) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transaction.rs#L386)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@noa what if the sequencer balance is lower then the actual fee?
If this code is reachable in such case, it may pass a tx that should have been rejected.

Anyway, consider placing the "if sender_address == sequencer_address" somewhere before this line, to avoid it
</blockquote></details>

In the pre-execution checks we verify that `account_balance >= fee_bounds`. In the post execution, we verify `actual_fee <= fee_bounds` so we get that necessarily:  `actual_fee <= account_balance`.
Assuming we add a problem with one of this checks, we will catch it in the commit stage (where we run the non-modified fee transfer in case sender_address == sequencer_address).
@meship-starkware suggested to set it to the actual sequencer balance just before the current block. That requires passing this info to the modified fee charge method (via block context).

WDYT?


<!-- Sent from Reviewable.io -->

2024-04-16 13:59 UTC, noaov1 reviewed
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @meship-starkware, @noa, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 386 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv__4DD8uiKb5GO8svG:-NvbA3BFD0Up4gcnS6RU:b3kqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transaction.rs#L386)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

In the pre-execution checks we verify that `account_balance >= fee_bounds`. In the post execution, we verify `actual_fee <= fee_bounds` so we get that necessarily:  `actual_fee <= account_balance`.
Assuming we add a problem with one of this checks, we will catch it in the commit stage (where we run the non-modified fee transfer in case sender_address == sequencer_address).
@meship-starkware suggested to set it to the actual sequencer balance just before the current block. That requires passing this info to the modified fee charge method (via block context).

WDYT?
</blockquote></details>

.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1165 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-NvbBPWHBdr1jLbUwFWf:-NvbBPWHBdr1jLbUwFWg:b-bafctl) ([raw file](https://github.com/starkware-libs/blockifier/blob/78ed6c1e853cf6916d5fc7784f15abe11f5924fd/crates/blockifier/src/transaction/account_transactions_test.rs#L1165)):*
> ```XML
> 
> #[rstest]
> fn test_concurrency_execute_fee_transfer(block_context: BlockContext) {
> ```

Consider using an invoke transaction and running `execute_raw` with concurrency flag turned on.
That way, it's easier to simulate a case where the transaction writes and read from the sequencer balance, before the fee transfer.



_Code quote:_
```XML
fn test_concurrency_execute_fee_transfer(block_context: BlockContext) {
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1214 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-NvbByuI9LE531V-0HEw:-NvbByuJ31iPBo3n101o:bt6uq8a) ([raw file](https://github.com/starkware-libs/blockifier/blob/78ed6c1e853cf6916d5fc7784f15abe11f5924fd/crates/blockifier/src/transaction/account_transactions_test.rs#L1214)):*
> ```XML
>     // Case 2: The transaction read from and write to the sequenser balance before executing fee
>     // transfer.
>     fund_account(chain_info, sequencer_address, 150_u128, state);
> ```

Can you please explain why is it needed?



_Code quote:_
```XML
    fund_account(chain_info, sequencer_address, 150_u128, state);
```


<!-- Sent from Reviewable.io -->

2024-04-16 13:59 UTC, noaov1 reviewed
> Reviewed 1 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: all files reviewed, 4 unresolved discussions (waiting on @meship-starkware, @noa, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-04-16 14:57 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: all files reviewed, 4 unresolved discussions (waiting on @meship-starkware and @noa)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 386 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv__4DD8uiKb5GO8svG:-NvbOF0E0Rp-ViOVTlGT:b-9xbixq) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transaction.rs#L386)):*
@noa these checks are not enough. What if, during the `execute` phase, the sequencer loses some of his balance?

> Assuming we add a problem with one of these checks, we will catch it in the commit stage (where we run the non-modified fee transfer in case sender\_address == sequencer\_address).

If you run it within the `handle_fee`, you won't have to deal with this in the commit stage.
I.e., if it's the sequencer, run the fee normally (and do nothing in the commit stage)

> [@meship-starkware](https://github.com/meship-starkware) suggested to set it to the actual sequencer balance just before the current block. That requires passing this info to the modified fee charge method (via block context).

Didn't understand


<!-- Sent from Reviewable.io -->

2024-04-17 08:32 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: all files reviewed, 4 unresolved discussions (waiting on @noa, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1214 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-NvbByuI9LE531V-0HEw:-Nvf9VY4EBZeluELnBvR:bgmeorp) ([raw file](https://github.com/starkware-libs/blockifier/blob/78ed6c1e853cf6916d5fc7784f15abe11f5924fd/crates/blockifier/src/transaction/account_transactions_test.rs#L1214)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain why is it needed?
</blockquote></details>

I want to make sure the value hasn't changed. If I don't do this, the value will be zero, and I won't know if I override zero with zero or if it hasn't changed the sequencer balance.


<!-- Sent from Reviewable.io -->

2024-04-17 09:07 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 386 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv__4DD8uiKb5GO8svG:-Nvf9Gx9ASy-0XhRUTpI:b-xpqoey) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transaction.rs#L386)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@noa these checks are not enough. What if, during the `execute` phase, the sequencer loses some of his balance?

> Assuming we add a problem with one of these checks, we will catch it in the commit stage (where we run the non-modified fee transfer in case sender\_address == sequencer\_address).

If you run it within the `handle_fee`, you won't have to deal with this in the commit stage.
I.e., if it's the sequencer, run the fee normally (and do nothing in the commit stage)

> [@meship-starkware](https://github.com/meship-starkware) suggested to set it to the actual sequencer balance just before the current block. That requires passing this info to the modified fee charge method (via block context).

Didn't understand
</blockquote></details>

Oh, sorry, I omitted a check: post execution we check `balance >=  actual fee`.
It is all irrelevant since the sequencer balance is going to be in the read set anyway, so we might as well run the non-modified charge fee.
To sum up, I agree :)


<!-- Sent from Reviewable.io -->

2024-04-17 10:36 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-04-17 12:01 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1165 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-NvbBPWHBdr1jLbUwFWf:-NvfgeH32_DOEVPPsbJP:b-gfebhj) ([raw file](https://github.com/starkware-libs/blockifier/blob/78ed6c1e853cf6916d5fc7784f15abe11f5924fd/crates/blockifier/src/transaction/account_transactions_test.rs#L1165)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider using an invoke transaction and running `execute_raw` with concurrency flag turned on.
That way, it's easier to simulate a case where the transaction writes and read from the sequencer balance, before the fee transfer.
</blockquote></details>

The invoke TX next pr. 


<!-- Sent from Reviewable.io -->

2024-04-18 07:07 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 386 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv__4DD8uiKb5GO8svG:-NvgLhBV-UZayL90JBU1:b-7xt2jw) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transaction.rs#L386)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@meship-starkware can you set the key_low to be 0?
</blockquote></details>

Yes. 


<!-- Sent from Reviewable.io -->

2024-04-18 07:28 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 380 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nvk5DGS5oGzzyzC6Mxn:-Nvk5DGT32IPEW8v8QTt:bvw342t) ([raw file](https://github.com/starkware-libs/blockifier/blob/78ed6c1e853cf6916d5fc7784f15abe11f5924fd/crates/blockifier/src/transaction/account_transaction.rs#L380)):*
> ```XML
>         let sequencer_balance_key_low = get_fee_token_var_address(sequencer_address);
>         let sequencer_balance_key_high = next_storage_key(&sequencer_balance_key_low)
>             .expect("Cannot get sequencer balance high key.");
> ```

(can be in a separate PR): define a function for these three lines: `get_balance_storage_keys`.
And refactor the code the use it



_Code quote:_
```XML
        let sequencer_balance_key_low = get_fee_token_var_address(sequencer_address);
        let sequencer_balance_key_high = next_storage_key(&sequencer_balance_key_low)
            .expect("Cannot get sequencer balance high key.");
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 390 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nvk5eBB-UghgO37vsf7:-Nvk5eBB-UghgO37vsf8:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f6b4bea959ddbe5a44e4581b9191fb0bf2a250f1/crates/blockifier/src/transaction/account_transaction.rs#L390)):*
> ```XML
>         let cache = transfer_state.cache.get_mut();
>         for key in [sequencer_balance_key_low, sequencer_balance_key_high] {
>             cache.set_storage_initial_value(fee_address, key, StarkFelt::from(0_u8));
> ```





_Suggestion:_
```XML
StarkFelt::ZERO)
```


<!-- Sent from Reviewable.io -->

2024-04-18 09:24 UTC, noaov1 approved these changes
> Reviewed 1 of 2 files at r11, 1 of 2 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: all files reviewed, 7 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1212 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-NvkG2xNAPTl1rxbL9hI:-NvkG2xNAPTl1rxbL9hJ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f6b4bea959ddbe5a44e4581b9191fb0bf2a250f1/crates/blockifier/src/transaction/account_transactions_test.rs#L1212)):*
> ```XML
>     // Set the sequencer balance to a constant value to check that the read set did not changed.
>     fund_account(chain_info, sequencer_address, STORAGE_READ_LOW, state);
>     let mut transactional_state_1 = CachedState::create_transactional(state);
> ```





_Suggestion:_
```XML
    let mut transactional_state = CachedState::create_transactional(state);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1219 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-NvkUAtmBmkD1dF5kg-D:-NvkUAtmBmkD1dF5kg-E:b-5kay4n) ([raw file](https://github.com/starkware-libs/blockifier/blob/be6abfc9ddff25e9bffc4c28c851aab9baaaf14b/crates/blockifier/src/transaction/account_transactions_test.rs#L1219)):*
> ```XML
>         .unwrap();
>     let seq_read_low_value_before =
>         transactional_state_1.get_storage_at(fee_token_address, sequencer_balance_key_low).unwrap();
> ```

Why is the result needed? You know the balance (you funded it).



_Suggestion:_
```XML
    // TODO(Meshi, some date): Use an invoke transaction to change the value of the sequencer balance in execute.
    let (_sequencer_balance_low, _sequencer_balance_high) =
        state.get_fee_token_balance(sequencer_address, fee_token_address)
        .unwrap();
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1245 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-NvkVNauAD8hJ-xS_XpA:-NvkVNauAD8hJ-xS_XpB:b2nhkyh) ([raw file](https://github.com/starkware-libs/blockifier/blob/be6abfc9ddff25e9bffc4c28c851aab9baaaf14b/crates/blockifier/src/transaction/account_transactions_test.rs#L1245)):*
> ```XML
>             storage_initial_values.get(&(fee_token_address, sequencer_balance_key_low)),
>             seq_read_low_value_before,
>         ),
> ```

No?



_Suggestion:_
```XML
        (
            storage_initial_values.get(&(fee_token_address, sequencer_balance_key_low)),
            STORAGE_READ_LOW,,
        ),
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1253 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-NvkVQoJ2LkSApNj0X2a:-NvkVQoJ2LkSApNj0X2b:b2nhkyh) ([raw file](https://github.com/starkware-libs/blockifier/blob/be6abfc9ddff25e9bffc4c28c851aab9baaaf14b/crates/blockifier/src/transaction/account_transactions_test.rs#L1253)):*
> ```XML
>             storage_initial_values.get(&(fee_token_address, sequencer_balance_key_high)),
>             seq_read_high_value_before,
>         ),
> ```

No?



_Suggestion:_
```XML
        (
            storage_initial_values.get(&(fee_token_address, sequencer_balance_key_high)),
            0,
        ),
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1255 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-NvkVWtd-Rbie8MBcbJc:-NvkVWtd-Rbie8MBcbJd:b-ale2y6) ([raw file](https://github.com/starkware-libs/blockifier/blob/be6abfc9ddff25e9bffc4c28c851aab9baaaf14b/crates/blockifier/src/transaction/account_transactions_test.rs#L1255)):*
> ```XML
>         ),
>     ] {
>         assert!(seq_write_val.is_some());
> ```

Not needed. You will catch it in the `unwrap` below.


<!-- Sent from Reviewable.io -->

2024-04-18 10:21 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: all files reviewed, 5 unresolved discussions (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-04-24 07:23 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 368 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-Nv_QRrU1QJYVDZ6lnP2:-NwDxjyZCprAkc0jhMew:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/047b67fc1f2ce01df83168cfa117bf7b01db6bd7/crates/blockifier/src/transaction/account_transaction.rs#L368)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Something a bit less specific
```
/// Handles fee transfer in concurrent execution.
///
/// Accessing and updating the sequencer balance at this stage is a bottleneck; this function manipulates the state to avoid that part.
/// Note: the returned transfer call info is partial, and should be completed at the commit stage, as well as the actual sequencer balance.
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-24 07:30 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 1 files at r10, 1 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-04-24 08:06 UTC, Yoni-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-04-24 10:24 UTC, noaov1 approved these changes
> Reviewed 1 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1217 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1766#-NwEbuWxEcz56nQMcdYn:-NwEbuWy0PiR8awGpkps:b-rzrhti) ([raw file](https://github.com/starkware-libs/blockifier/blob/28747ee1e19218e586e891486c9fd5d018e56836/crates/blockifier/src/transaction/account_transactions_test.rs#L1217)):*
> ```XML
>     // Set the sequencer balance write set to a constant value.
>     // Note that it is enough to set the storage_write as execute_raw will update the
>     // storage_initial_values.
> ```

Something like that :)



_Suggestion:_
```XML
    // Note that during execution we update the cache with initial cell values (read value) for write-only access.
    // Therefore, we don't need to update the initial values manually.
```


<!-- Sent from Reviewable.io -->

2024-04-24 10:24 UTC, noaov1 approved these changes
> Reviewed 1 of 2 files at r15.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1766)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-04-24 11:38 UTC, merged