concurrency: add fee utils to concurrecy and fix call info
starkware-libs/blockifier pull request #1773
Opened 2024-04-09 10:38 UTC by meship-starkware

2024-04-16 11:53 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-Nvajy0mE_aVSEj1V-V1:-Nvajy0mE_aVSEj1V-V2:bhyzun0) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ba581be28b589e4f59bdeceffab731e8c1f49cb/crates/blockifier/src/concurrency/fee_utils.rs#L9)):*
> ```XML
> mod test;
> 
> const STORAGE_READ_SEQUENCER_BALANCE_INDEXES: (usize, usize) = (4, 6);
> ```

Add a comment



_Suggestion:_
```XML
const STORAGE_READ_SEQUENCER_BALANCE_INDICES:
```
___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 10 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NvajfHf192Qj0_TWHmx:-NvajfHf192Qj0_TWHmy:brt5cg1) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ba581be28b589e4f59bdeceffab731e8c1f49cb/crates/blockifier/src/concurrency/fee_utils.rs#L10)):*
> ```XML
> 
> const STORAGE_READ_SEQUENCER_BALANCE_INDEXES: (usize, usize) = (4, 6);
> pub fn fix_call_info(call_info: &mut CallInfo, sequencer_balance: StarkFelt) {
> ```

Please choose a more informative name and document



_Code quote:_
```XML
fix_call_info
```


<!-- Sent from Reviewable.io -->

2024-04-16 12:02 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NvamJcE45qnq4rboLwj:-NvamJcE45qnq4rboLwk:b2iaa49) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ba581be28b589e4f59bdeceffab731e8c1f49cb/crates/blockifier/src/concurrency/fee_utils.rs#L12)):*
> ```XML
> pub fn fix_call_info(call_info: &mut CallInfo, sequencer_balance: StarkFelt) {
>     call_info.storage_read_values[STORAGE_READ_SEQUENCER_BALANCE_INDEXES.0] = sequencer_balance;
>     call_info.storage_read_values[STORAGE_READ_SEQUENCER_BALANCE_INDEXES.1] = sequencer_balance;
> ```

For sanity, assert that the previous values are as expected



_Code quote:_
```XML
    call_info.storage_read_values[STORAGE_READ_SEQUENCER_BALANCE_INDEXES.0] = sequencer_balance;
    call_info.storage_read_values[STORAGE_READ_SEQUENCER_BALANCE_INDEXES.1] = sequencer_balance;
```
___
*[`crates/blockifier/src/concurrency/fee_utils_test.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NvalaZjDyKwuZlL1_Av:-NvalaZjDyKwuZlL1_Aw:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ba581be28b589e4f59bdeceffab731e8c1f49cb/crates/blockifier/src/concurrency/fee_utils_test.rs#L35)):*
> ```XML
>     let account_tx = declare_tx(
>         declare_tx_args! {
>             max_fee: Fee(MAX_FEE),
> ```


___
*[`crates/blockifier/src/concurrency/fee_utils_test.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NvalcaP2RGNicQoWeIt:-NvalcaP2RGNicQoWeIu:b1gzv30) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ba581be28b589e4f59bdeceffab731e8c1f49cb/crates/blockifier/src/concurrency/fee_utils_test.rs#L42)):*
> ```XML
>         },
>         class_info.clone(),
>     );
> ```

This is duplicated, can you share it?



_Code quote:_
```XML
    let empty_contract = FeatureContract::Empty(CairoVersion::Cairo1);
    let account = FeatureContract::AccountWithoutValidations(CairoVersion::Cairo1);
    let chain_info = &block_context.chain_info;
    let state = &mut test_state(chain_info, BALANCE, &[(account, 1)]);
    let class_hash = empty_contract.get_class_hash();
    let class_info = calculate_class_info_for_testing(empty_contract.get_class());
    let sender_address = account.get_instance_address(0);

    let account_tx = declare_tx(
        declare_tx_args! {
            max_fee: Fee(MAX_FEE),
            sender_address,
            version: TransactionVersion::THREE,
            resource_bounds: l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE),
            class_hash,
        },
        class_info.clone(),
    );
```
___
*[`crates/blockifier/src/concurrency/fee_utils_test.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-Nval6V18RUv-7gbdH8g:-Nval6V18RUv-7gbdH8h:b-ndd9b) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ba581be28b589e4f59bdeceffab731e8c1f49cb/crates/blockifier/src/concurrency/fee_utils_test.rs#L56)):*
> ```XML
>             StarkFelt::from_u128(100_u128),
>         )
>         .unwrap();
> ```

Can you use `fund_account` instead?



_Code quote:_
```XML
    let fee_token_address =
        block_context.chain_info.fee_token_address(&tx_context.tx_info.fee_type());
    let sequencer_address = block_context.block_info.sequencer_address;
    let sequencer_balance_key_low = get_fee_token_var_address(sequencer_address);

    state
        .set_storage_at(
            fee_token_address,
            sequencer_balance_key_low,
            StarkFelt::from_u128(100_u128),
        )
        .unwrap();
```
___
*[`crates/blockifier/src/concurrency/fee_utils_test.rs` line 73 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NvalCCV8IT98TfGCyst:-NvalCCV8IT98TfGCysu:btbz8x6) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ba581be28b589e4f59bdeceffab731e8c1f49cb/crates/blockifier/src/concurrency/fee_utils_test.rs#L73)):*
> ```XML
>     .unwrap();
>     fix_call_info(&mut call_info, StarkFelt::from(100_u8));
>     assert_eq!(call_info, expected_call_info);
> ```

For sanity



_Suggestion:_
```XML
    // Before.
    assert_ne!(call_info, expected_call_info);
    
    fix_call_info(&mut call_info, StarkFelt::from(100_u8));
    // After.
    assert_eq!(call_info, expected_call_info);
```


<!-- Sent from Reviewable.io -->

2024-04-17 08:24 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-Nvajy0mE_aVSEj1V-V1:-NverCncEU2gUGasMRAO:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ba581be28b589e4f59bdeceffab731e8c1f49cb/crates/blockifier/src/concurrency/fee_utils.rs#L9)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Add a comment
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 10 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NvajfHf192Qj0_TWHmx:-Nvf8sW8-Xwv_zcQKNbd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ba581be28b589e4f59bdeceffab731e8c1f49cb/crates/blockifier/src/concurrency/fee_utils.rs#L10)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Please choose a more informative name and document
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NvamJcE45qnq4rboLwj:-NvesrJW0XWZ1OnunoYH:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ba581be28b589e4f59bdeceffab731e8c1f49cb/crates/blockifier/src/concurrency/fee_utils.rs#L12)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

For sanity, assert that the previous values are as expected
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/fee_utils_test.rs` line 35 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NvalaZjDyKwuZlL1_Av:-NvezFsgBTUOShWk8hHN:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ba581be28b589e4f59bdeceffab731e8c1f49cb/crates/blockifier/src/concurrency/fee_utils_test.rs#L35)):*
> ```XML
>     let account_tx = declare_tx(
>         declare_tx_args! {
>             max_fee: Fee(MAX_FEE),
> ```

Done.
___
*[`crates/blockifier/src/concurrency/fee_utils_test.rs` line 56 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-Nval6V18RUv-7gbdH8g:-NvezDYd4oZnFLF3G0Gr:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ba581be28b589e4f59bdeceffab731e8c1f49cb/crates/blockifier/src/concurrency/fee_utils_test.rs#L56)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you use `fund_account` instead?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/fee_utils_test.rs` line 73 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NvalCCV8IT98TfGCyst:-NvetGeYEX5MaJUCh983:bfank1c) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ba581be28b589e4f59bdeceffab731e8c1f49cb/crates/blockifier/src/concurrency/fee_utils_test.rs#L73)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

For sanity
</blockquote></details>

if the actual_fee == sequencer_balance it might be problematic. but we can ignore it for this test.


<!-- Sent from Reviewable.io -->

2024-04-27 13:58 UTC, noaov1 requested changes
> Reviewed 1 of 7 files at r1, 1 of 5 files at r2, 1 of 2 files at r3, 2 of 6 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: all files reviewed, 16 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-Nvajy0mE_aVSEj1V-V1:-NwUk8olB1IbIG3yMe9V:beg8mk7) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ba581be28b589e4f59bdeceffab731e8c1f49cb/crates/blockifier/src/concurrency/fee_utils.rs#L9)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please explain the 4 and the 6. For inspiration: 
You may note that we assume the sequencer balance is of size that fits one felt.



_Code snippet:_
```XML
// We read account balance (sender), write (which starts with read) the account balance. We then do the same for
// the sequencer balance (recipient). The balance is of type `Uint256`, consist of two felts (lsb, msb).
// Hence, storage read values = [account_balance, 0, account_balance, 0, sequencer_balance, 0, sequencer_balance, 0]
```
___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 9 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwUi3DlBCssGooRe_i8:-NwUi3DlBCssGooRe_i9:btxi76p) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c6be588a8b9363554f1bc4a46cd62fcb957dbb/crates/blockifier/src/concurrency/fee_utils.rs#L9)):*
> ```XML
> 
> const STORAGE_READ_SEQUENCER_BALANCE_INDICES: (usize, usize) = (4, 6);
> // In concurrency  run we create a call info where the sequencer balance is the actual fee.
> ```

Or something similar.



_Suggestion:_
```XML
// In concurrency mode we execute the fee transfer with false sequencer balance values.
```
___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 17 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwUiKaPArKqUpfXmHNZ:-NwUiKaQAl4M2vgUCRUB:bdx73hr) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c6be588a8b9363554f1bc4a46cd62fcb957dbb/crates/blockifier/src/concurrency/fee_utils.rs#L17)):*
> ```XML
>     assert!(
>         call_info.storage_read_values.len() > 6,
>         "Storage read values should have at least 7 elements"
> ```

Why? I think it usually have 8 elements, no?
Maybe it's better to assert it directly. 



_Code quote:_
```XML
        "Storage read values should have at least 7 elements"
```
___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 22 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwUj0x27GgfJziSHIYW:-NwUj0x27GgfJziSHIYX:b1f1e7x) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c6be588a8b9363554f1bc4a46cd62fcb957dbb/crates/blockifier/src/concurrency/fee_utils.rs#L22)):*
> ```XML
>         call_info.storage_read_values[STORAGE_READ_SEQUENCER_BALANCE_INDICES.0],
>         StarkFelt::ZERO,
>         "Sequencer balance should be the actual fee"
> ```

Please fix in all relevant places.



_Suggestion:_
```XML
        "Sequencer balance should be zero"
```
___
*[`crates/blockifier/src/concurrency/fee_utils_test.rs` line 15 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwUp_h-BA6Ci4XlXjSS:-NwUp_h-BA6Ci4XlXjST:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c6be588a8b9363554f1bc4a46cd62fcb957dbb/crates/blockifier/src/concurrency/fee_utils_test.rs#L15)):*
> ```XML
> pub fn test_fix_call_info(
>     block_context: BlockContext,
>     #[values(50_u128, 100_u128, 150_u128)] sequencer_balance: u128,
> ```





_Suggestion:_
```XML
    #[values(0_u128, 100_u128)] sequencer_balance: u128,
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 157 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwUgAK72RPfkkXvuZoh:-NwUgAK72RPfkkXvuZoi:b-4kn575) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c6be588a8b9363554f1bc4a46cd62fcb957dbb/crates/blockifier/src/fee/fee_utils.rs#L157)):*
> ```XML
>     let sequencer_balance_key_high = if should_panic {
>         next_storage_key(&sequencer_balance_key_low)
>             .expect("Cannot get sequencer balance high key.")
> ```

`expect` panics as well (with an informative message). I think we will always want to panic (returning an error and failing the transactions does not make any sense).
Please remove the `should_panic` input parameter.



_Code quote:_
```XML
            .expect("Cannot get sequencer balance high key.")
```
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 161 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwUlXr644voMKiLMF8w:-NwUlXr644voMKiLMF8x:b-gw98nj) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c6be588a8b9363554f1bc4a46cd62fcb957dbb/crates/blockifier/src/fee/fee_utils.rs#L161)):*
> ```XML
>         next_storage_key(&sequencer_balance_key_low).unwrap()
>     };
>     (sequencer_address, sequencer_balance_key_low, sequencer_balance_key_high)
> ```

Why is the `sequencer_address` needed in the output?



_Code quote:_
```XML
    (sequencer_address, sequencer_balance_key_low, sequencer_balance_key_high)
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1202 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwUo3sC5zjav1WhWb2K:-NwUo3sC5zjav1WhWb2L:b-tp66fk) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c6be588a8b9363554f1bc4a46cd62fcb957dbb/crates/blockifier/src/transaction/account_transactions_test.rs#L1202)):*
> ```XML
>     // Set the sequencer balance write set to a constant value.
>     // Note that during execution we update the cache with initial cell values (read value) for
>     // write-only access. Therefore, we don't need to update the initial values manually.
> ```

Consider letting the transaction do it (less "dirty"). See [here](https://github.com/starkware-libs/blockifier/blob/f17234dc5667057ff467d162d22885fb56a4ef46/crates/blockifier/src/transaction/account_transactions_test.rs#L1023) for reference.



_Code quote:_
```XML
    // Set the sequencer balance write set to a constant value.
    // Note that during execution we update the cache with initial cell values (read value) for
    // write-only access. Therefore, we don't need to update the initial values manually.
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 299 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwUnyYH9WT_SYZXSm9B:-NwUnyYH9WT_SYZXSm9C:bxtub52) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c6be588a8b9363554f1bc4a46cd62fcb957dbb/crates/blockifier/src/transaction/test_utils.rs#L299)):*
> ```XML
> }
> 
> pub fn create_invoke_account_tx() -> (AccountTransaction, FeatureContract) {
> ```

Is it needed?



_Code quote:_
```XML
pub fn create_invoke_account_tx() -> (AccountTransaction, FeatureContract) {
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 304 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwUnaOf065ZqY9GHnDB:-NwUnaOf065ZqY9GHnDC:bfrsx1q) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c6be588a8b9363554f1bc4a46cd62fcb957dbb/crates/blockifier/src/transaction/test_utils.rs#L304)):*
> ```XML
>         sender_address: account.get_instance_address(0),
>         resource_bounds: l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE),
>         version: TransactionVersion::THREE
> ```

Which entry point are you running? You did not mention any calldata



_Code quote:_
```XML
    let account_tx = account_invoke_tx(invoke_tx_args! {
        sender_address: account.get_instance_address(0),
        resource_bounds: l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE),
        version: TransactionVersion::THREE
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 309 at r7](https:// [...]

2024-04-30 12:49 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: 4 of 10 files reviewed, 15 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 17 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwUiKaPArKqUpfXmHNZ:-Nwi55b-350r6AA-x0YB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c6be588a8b9363554f1bc4a46cd62fcb957dbb/crates/blockifier/src/concurrency/fee_utils.rs#L17)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why? I think it usually have 8 elements, no?
Maybe it's better to assert it directly.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 22 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwUj0x27GgfJziSHIYW:-Nwi56St0tlE7OD0CmO9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c6be588a8b9363554f1bc4a46cd62fcb957dbb/crates/blockifier/src/concurrency/fee_utils.rs#L22)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please fix in all relevant places.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/fee_utils_test.rs` line 15 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwUp_h-BA6Ci4XlXjSS:-Nwi59Cp-i3y56dM4zb1:b-4ac8kf) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c6be588a8b9363554f1bc4a46cd62fcb957dbb/crates/blockifier/src/concurrency/fee_utils_test.rs#L15)):*
> ```XML
> pub fn test_fix_call_info(
>     block_context: BlockContext,
>     #[values(50_u128, 100_u128, 150_u128)] sequencer_balance: u128,
> ```

zero is problematic because it's the seq balance in tests, so the call information will be the same.  
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 157 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwUgAK72RPfkkXvuZoh:-Nwi8SHa2jwTtO31kpcN:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c6be588a8b9363554f1bc4a46cd62fcb957dbb/crates/blockifier/src/fee/fee_utils.rs#L157)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

`expect` panics as well (with an informative message). I think we will always want to panic (returning an error and failing the transactions does not make any sense).
Please remove the `should_panic` input parameter.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 299 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwUnyYH9WT_SYZXSm9B:-NwiOVNbCAgVKHtrS52V:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c6be588a8b9363554f1bc4a46cd62fcb957dbb/crates/blockifier/src/transaction/test_utils.rs#L299)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it needed?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 304 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwUnaOf065ZqY9GHnDB:-NwizERF3jVNoVZgBi8b:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c6be588a8b9363554f1bc4a46cd62fcb957dbb/crates/blockifier/src/transaction/test_utils.rs#L304)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Which entry point are you running? You did not mention any calldata
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 309 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwUpwWB0raTxwwITBr9:-NwiAyNq4-j5g60b6JBi:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c6be588a8b9363554f1bc4a46cd62fcb957dbb/crates/blockifier/src/transaction/test_utils.rs#L309)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider moving it to the concurrency module.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-02 07:14 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: 3 of 10 files reviewed, 13 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-Nvajy0mE_aVSEj1V-V1:-Nws8tnoAhp3CLixPBWH:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ba581be28b589e4f59bdeceffab731e8c1f49cb/crates/blockifier/src/concurrency/fee_utils.rs#L9)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please explain the 4 and the 6. For inspiration: 
You may note that we assume the sequencer balance is of size that fits one felt.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-02 15:39 UTC, noaov1 requested changes
> Reviewed 2 of 6 files at r8, 4 of 5 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: all files reviewed, 10 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 43 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwtwDg21wsPuGkduEfz:-NwtwDg21wsPuGkduEg-:b-mz1rgg) ([raw file](https://github.com/starkware-libs/blockifier/blob/9fdf0c164bdbeaab3ca2367bafc0ec16b7acbd5a/crates/blockifier/src/concurrency/fee_utils.rs#L43)):*
> ```XML
> }
> 
> pub fn create_fee_transfer_call_data<S: StateReader>(
> ```

Is it used other than for testing? If no, consider moving it to `test_utils` or adding an appropriate decorator. 



_Code quote:_
```XML
pub fn create_fee_transfer_call_data<S: StateReader>(
```
___
*[`crates/blockifier/src/concurrency/fee_utils_test.rs` line 15 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwUp_h-BA6Ci4XlXjSS:-Nwtw4G97oU3GNpZh7HY:b4vdm1t) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c6be588a8b9363554f1bc4a46cd62fcb957dbb/crates/blockifier/src/concurrency/fee_utils_test.rs#L15)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

zero is problematic because it's the seq balance in tests, so the call information will be the same.
</blockquote></details>

What is the difference (test-wise) between 50 and 100?
___
*[`crates/blockifier/src/fee/fee_utils.rs` line 148 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-Nwtwf5sD5HWdtiENEUM:-Nwtwf5tA0zuFtJIlJlG:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9fdf0c164bdbeaab3ca2367bafc0ec16b7acbd5a/crates/blockifier/src/fee/fee_utils.rs#L148)):*
> ```XML
> }
> 
> pub fn get_sequencer_address_and_keys(block_context: &BlockContext) -> (StorageKey, StorageKey) {
> ```





_Suggestion:_
```XML
pub fn get_sequencer_balance_keys(block_context: &BlockContext) -> (StorageKey, StorageKey) {
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1167 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwtxLjnAeTmrCtO0xS-:-NwtxLjnAeTmrCtO0xS0:bqio18i) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c6be588a8b9363554f1bc4a46cd62fcb957dbb/crates/blockifier/src/transaction/account_transactions_test.rs#L1167)):*
> ```XML
> #[rstest]
> fn test_concurrency_execute_fee_transfer(#[values(FeeType::Eth, FeeType::Strk)] fee_type: FeeType) {
>     const STORAGE_WRITE_HIGH: u128 = 150;
> ```

Are you planning to test the case where high balance key is changed? 



_Code quote:_
```XML
    const STORAGE_WRITE_HIGH: u128 = 150;
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1220 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-Nwtx9xiCmZOG-sFJr7e:-Nwtx9xiCmZOG-sFJr7f:b-rll82e) ([raw file](https://github.com/starkware-libs/blockifier/blob/9fdf0c164bdbeaab3ca2367bafc0ec16b7acbd5a/crates/blockifier/src/transaction/account_transactions_test.rs#L1220)):*
> ```XML
>     let mut transactional_state = CachedState::create_transactional(state);
> 
>     // Set the sequencer balance write set to a constant value.
> ```

Please fix.



_Code quote:_
```XML
    // Set the sequencer balance write set to a constant value.
```


<!-- Sent from Reviewable.io -->

2024-05-05 06:05 UTC, meship-starkware commented
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1167 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NwtxLjnAeTmrCtO0xS-:-Nx6LDiv-rnw_bDcaEQL:b7izf20) ([raw file](https://github.com/starkware-libs/blockifier/blob/e0c6be588a8b9363554f1bc4a46cd62fcb957dbb/crates/blockifier/src/transaction/account_transactions_test.rs#L1167)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Are you planning to test the case where high balance key is changed?
</blockquote></details>

I did, but it is a bit complicated (the fund account gets u128), so testing the initial would be problematic. I think I'll add a todo and will return to it later.  


<!-- Sent from Reviewable.io -->

2024-05-05 09:43 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: 5 of 11 files reviewed, 8 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/fee/fee_utils.rs` line 148 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-Nwtwf5sD5HWdtiENEUM:-Nx6rTkZBC32cezESDDa:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9fdf0c164bdbeaab3ca2367bafc0ec16b7acbd5a/crates/blockifier/src/fee/fee_utils.rs#L148)):*
> ```XML
> }
> 
> pub fn get_sequencer_address_and_keys(block_context: &BlockContext) -> (StorageKey, StorageKey) {
> ```

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1220 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-Nwtx9xiCmZOG-sFJr7e:-Nx6w7Dw3nQxxm5FBcmZ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9fdf0c164bdbeaab3ca2367bafc0ec16b7acbd5a/crates/blockifier/src/transaction/account_transactions_test.rs#L1220)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please fix.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-05 10:46 UTC, noaov1 reviewed
> Reviewed 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: all files reviewed, 6 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 10 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-Nx7LzIh5mObiPZ_bjYl:-Nx7LzIi-UZRScUXFma7:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/ed200828f2aad0063c5bfc0cab9e072b461c009c/crates/blockifier/src/concurrency/fee_utils.rs#L10)):*
> ```XML
> // In concurrency mode we execute the fee transfer with false sequencer balance values.
> // This function fixes the call info to have the correct sequencer balance.
> pub fn fill_sequencer_balance_reads(
> ```

?



_Suggestion:_
```XML
pub fn fill_sequencer_balance_reads_cairo0(
```


<!-- Sent from Reviewable.io -->

2024-05-05 11:24 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: all files reviewed, 6 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 10 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-Nx7LzIh5mObiPZ_bjYl:-Nx7TdUGBawGEbvogu7E:b-tuq97r) ([raw file](https://github.com/starkware-libs/blockifier/blob/ed200828f2aad0063c5bfc0cab9e072b461c009c/crates/blockifier/src/concurrency/fee_utils.rs#L10)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

?
</blockquote></details>

I don't think there is a need for two separate functions. We can either pass it as an argument or, for now, do as Yoni suggests and distinguish by the storage_read_values length.  


<!-- Sent from Reviewable.io -->

2024-05-06 09:07 UTC, noaov1 reviewed
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: all files reviewed, 5 unresolved discussions (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-05-06 13:56 UTC, noaov1 requested changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: all files reviewed, 8 unresolved discussions (waiting on @meship-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 18 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NxDA39L2j-auEQWFsg7:-NxDA39L2j-auEQWFsg8:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/90b91f348fbc5ab7c34a05dd0f861afc9c4c39c3/crates/blockifier/src/concurrency/fee_utils.rs#L18)):*
> ```XML
>         fee_transfer_call_info.storage_read_values.len(),
>         4,
>         "Storage read values should have 8 elements"
> ```





_Suggestion:_
```XML
        "Storage read values should have 4 elements"
```
___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 24 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NxDAaxT3TXrikabi4Nn:-NxDAaxT3TXrikabi4No:b-7fbrxr) ([raw file](https://github.com/starkware-libs/blockifier/blob/90b91f348fbc5ab7c34a05dd0f861afc9c4c39c3/crates/blockifier/src/concurrency/fee_utils.rs#L24)):*
> ```XML
>     // `Uint256`, consist of two felts (lsb, msb). Hence, storage read values =
>     // [account_balance, 0, sequencer_balance, 0]
>     for index in 2..4 {
> ```

I think it's better to have constants, 2 and 3.



_Suggestion:_
```XML
    // We read account balance (sender), and sequencer balance (receiver). The balance is of type
    // `Uint256`, consist of two felts (lsb, msb). Hence, storage read values =
    // [account_balance, 0, sequencer_balance, 0]
    for index in 2..4 {
```
___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 28 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NxDAWbGEiPz1a2HTn92:-NxDAWbH1WSsA8rKMsVS:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/90b91f348fbc5ab7c34a05dd0f861afc9c4c39c3/crates/blockifier/src/concurrency/fee_utils.rs#L28)):*
> ```XML
>             fee_transfer_call_info.storage_read_values[index],
>             StarkFelt::ZERO,
>             "Sequencer balance should be the zero"
> ```





_Suggestion:_
```XML
            "Sequencer balance should be zero"
```


<!-- Sent from Reviewable.io -->

2024-05-06 14:49 UTC, Yoni-Starkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: all files reviewed, 5 unresolved discussions (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-05-07 06:30 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: 10 of 11 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 18 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NxDA39L2j-auEQWFsg7:-NxGjCjqBB3eELiVzpXl:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/90b91f348fbc5ab7c34a05dd0f861afc9c4c39c3/crates/blockifier/src/concurrency/fee_utils.rs#L18)):*
> ```XML
>         fee_transfer_call_info.storage_read_values.len(),
>         4,
>         "Storage read values should have 8 elements"
> ```

Done.
___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 24 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NxDAaxT3TXrikabi4Nn:-NxGjDY38-pQvGYlrsXC:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/90b91f348fbc5ab7c34a05dd0f861afc9c4c39c3/crates/blockifier/src/concurrency/fee_utils.rs#L24)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think it's better to have constants, 2 and 3.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-07 08:23 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: 10 of 11 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/fee_utils_test.rs` line 73 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NvalCCV8IT98TfGCyst:-NxH8cKa8OTpDVaRX-3K:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ba581be28b589e4f59bdeceffab731e8c1f49cb/crates/blockifier/src/concurrency/fee_utils_test.rs#L73)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

if the actual_fee == sequencer_balance it might be problematic. but we can ignore it for this test.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-07 09:09 UTC, noaov1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-:-NxHIwJD8dNOOpKowSws:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-05-08 08:09 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 35 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NxMCd7L17WrqE9gmJMw:-NxMCd7L17WrqE9gmJMx:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/270d343afbdc66ed0e1ab095c3bac086853af403/crates/blockifier/src/concurrency/fee_utils.rs#L35)):*
> ```XML
>             if index % 2 == 0 { sequencer_balance_low } else { sequencer_balance_high };
>     }
> }
> ```





_Suggestion:_
```XML
const STORAGE_READ_SEQUENCER_BALANCE_INDEXES: (usize, usize) = (2, 3);

// Completes the fee transfer execution by fixing the call info to have the correct sequencer balance.
//
// In concurrency mode, the fee transfer is executed with a false (constant) sequencer balance. 
// This affects the call info.
pub fn fill_sequencer_balance_reads(
    fee_transfer_call_info: &mut CallInfo,
    sequencer_balance_low: StarkFelt,
    sequencer_balance_high: StarkFelt,
) {
    let mut storage_read_values = fee_transfer_call_info.storage_read_values;
    assert_eq!(
        storage_read_values.len(),
        4,
        "Storage read values should have 4 elements"
    );

    for index in STORAGE_READ_SEQUENCER_BALANCE_INDEXES {
        assert_eq!(
            storage_read_values[index],
            StarkFelt::ZERO,
            "Sequencer balance should be zero"
        );
    }
    let (low_index, high_index) = STORAGE_READ_SEQUENCER_BALANCE_INDEXES;
    storage_read_values[low_index] = sequencer_balance_low;
    storage_read_values[high_index] = sequencer_balance_high;
}
```
___
*[`crates/blockifier/src/concurrency/fee_utils_test.rs` line 15 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NxMEogN3CpH32IAKI5B:-NxMEogN3CpH32IAKI5C:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/270d343afbdc66ed0e1ab095c3bac086853af403/crates/blockifier/src/concurrency/fee_utils_test.rs#L15)):*
> ```XML
> 
> #[rstest]
> pub fn test_fix_call_info(block_context: BlockContext) {
> ```





_Suggestion:_
```XML
test_fill_sequencer_balance_reads
```


<!-- Sent from Reviewable.io -->

2024-05-08 08:13 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 6 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: all files reviewed, 4 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 45 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NxMFi8F57iZyFkYFRT6:-NxMFi8G5JhJsft6Dypm:b3kqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/270d343afbdc66ed0e1ab095c3bac086853af403/crates/blockifier/src/concurrency/test_utils.rs#L45)):*
> ```XML
> }
> 
> pub fn create_fee_transfer_call_data<S: StateReader>(
> ```

.



_Suggestion:_
```XML
nsfer_call_info
```


<!-- Sent from Reviewable.io -->

2024-05-08 08:25 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: all files reviewed, 4 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 54 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NxMIS-K8KgsK4y6TB-y:-NxMIS-K8KgsK4y6TB-z:b-lcnu7r) ([raw file](https://github.com/starkware-libs/blockifier/blob/270d343afbdc66ed0e1ab095c3bac086853af403/crates/blockifier/src/concurrency/test_utils.rs#L54)):*
> ```XML
>     let mut transactional_state = CachedState::create_transactional(state);
>     let execution_info =
>         account_tx.execute_raw(&mut transactional_state, &block_context, true, false).unwrap();
> ```

A bit confusing



_Suggestion:_
```XML
/// Note: this function does not mutate the state.
pub fn create_fee_transfer_call_data<S: StateReader>(
    state: &mut CachedState<S>,
    account_tx: &AccountTransaction,
    concurrency_mode: bool,
) -> CallInfo {
    let block_context =
        BlockContext::create_for_account_testing_with_concurrency_mode(concurrency_mode);
    let mut transactional_state = CachedState::create_transactional(state);
    let execution_info =
        account_tx.execute_raw(&mut transactional_state, &block_context, true, false).unwrap();
    transactional_state.abort();
```


<!-- Sent from Reviewable.io -->

2024-05-08 08:27 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: all files reviewed, 5 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1242 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NxMIwwm8PSeAu94BPuf:-NxMIwwm8PSeAu94BPug:bst0ar6) ([raw file](https://github.com/starkware-libs/blockifier/blob/270d343afbdc66ed0e1ab095c3bac086853af403/crates/blockifier/src/transaction/account_transactions_test.rs#L1242)):*
> ```XML
> 
>     let (sequencer_balance_key_low, sequencer_balance_key_high) =
>         get_sequencer_balance_keys(&block_context);
> ```

Next time, please do it in a separate PR



_Code quote:_
```XML
    let (sequencer_balance_key_low, sequencer_balance_key_high) =
        get_sequencer_balance_keys(&block_context);
```


<!-- Sent from Reviewable.io -->

2024-05-08 08:54 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: 8 of 11 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 35 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NxMCd7L17WrqE9gmJMw:-NxMKNy3CFQgNUjAmJY1:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/270d343afbdc66ed0e1ab095c3bac086853af403/crates/blockifier/src/concurrency/fee_utils.rs#L35)):*
> ```XML
>             if index % 2 == 0 { sequencer_balance_low } else { sequencer_balance_high };
>     }
> }
> ```

Done.
___
*[`crates/blockifier/src/concurrency/fee_utils_test.rs` line 15 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NxMEogN3CpH32IAKI5B:-NxMKVnK1JClW7Wzdu_k:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/270d343afbdc66ed0e1ab095c3bac086853af403/crates/blockifier/src/concurrency/fee_utils_test.rs#L15)):*
> ```XML
> 
> #[rstest]
> pub fn test_fix_call_info(block_context: BlockContext) {
> ```

Done.
___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 54 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NxMIS-K8KgsK4y6TB-y:-NxMNy_o8h_CwntDAht3:bilbtu4) ([raw file](https://github.com/starkware-libs/blockifier/blob/270d343afbdc66ed0e1ab095c3bac086853af403/crates/blockifier/src/concurrency/test_utils.rs#L54)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

A bit confusing
</blockquote></details>

When I wrote this function, I only cared about the call info. If you think it will be less confusing, I can commit the changes to the state or make it a private function of fee_utils_test so it is clear that the only use is to get the call info. 


<!-- Sent from Reviewable.io -->

2024-05-08 08:54 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: 8 of 11 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 45 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NxMFi8F57iZyFkYFRT6:-NxMPHut-Hwfzp896BxT:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/270d343afbdc66ed0e1ab095c3bac086853af403/crates/blockifier/src/concurrency/test_utils.rs#L45)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-09 05:16 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1290 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NxO8XznEzJ3FiavnDQF:-NxQdOdp62a9T3r2J09m:b-v34bkz) ([raw file](https://github.com/starkware-libs/blockifier/blob/6539532d21d328f8cf0840d032c705f8abcb0eea/crates/blockifier/src/transaction/account_transactions_test.rs#L1290)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Is this still relevant? can you explain the change here?
</blockquote></details>

This is a case where we transferred money to the sequencer before the fee transfer method, and we want to confirm that the changes we made in the sequencer balance during the fee transfer did not affect the prior transfer. 


<!-- Sent from Reviewable.io -->

2024-05-09 06:11 UTC, Yoni-Starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r18.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-:-NxQybs78AZLahiON4cI:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1290 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NxO8XznEzJ3FiavnDQF:-NxQwvAQ83Q7LSt63boz:bxacm4u) ([raw file](https://github.com/starkware-libs/blockifier/blob/6539532d21d328f8cf0840d032c705f8abcb0eea/crates/blockifier/src/transaction/account_transactions_test.rs#L1290)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

This is a case where we transferred money to the sequencer before the fee transfer method, and we want to confirm that the changes we made in the sequencer balance during the fee transfer did not affect the prior transfer.
</blockquote></details>

Oh, ok
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1292 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NxQyCgKDn3iM3PjPuK_:-NxQyCgLC3zEStoRF2rD:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6539532d21d328f8cf0840d032c705f8abcb0eea/crates/blockifier/src/transaction/account_transactions_test.rs#L1292)):*
> ```XML
>     // Check that the sequencer balance was not changed.
>     let storage_write = transactional_state.cache.borrow().writes.storage.clone();
>     let storage_initial_values = transactional_state.cache.borrow().initial_reads.storage.clone();
> ```





_Suggestion:_
```XML
    let storage_writes = transactional_state.cache.borrow().writes.storage.clone();
    let storage_initial_reads = transactional_state.cache.borrow().initial_reads.storage.clone();
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1297 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-NxQyP_e8RZdi6V0M-Lx:-NxQyP_e8RZdi6V0M-Ly:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6539532d21d328f8cf0840d032c705f8abcb0eea/crates/blockifier/src/transaction/account_transactions_test.rs#L1297)):*
> ```XML
>         (
>             storage_write.get(&(fee_token_address, sequencer_balance_key_low)),
>             stark_felt!(STORAGE_WRITE_LOW + STORAGE_READ_LOW),
> ```





_Suggestion:_
```XML
// Balance after `execute` and without the fee transfer.
stark_felt!(STORAGE_WRITE_LOW + STORAGE_READ_LOW),
```


<!-- Sent from Reviewable.io -->

2024-05-09 06:21 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r19, 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1773#-:-NxR-rev1TCF0GEAnMUc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-05-09 06:22 UTC, merged