feat(concurrency): write commit transaction
starkware-libs/blockifier pull request #1843
Opened 2024-05-01 08:14 UTC by meship-starkware

2024-05-02 08:40 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 24 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NwsP7p--90gZd9x1TTM:-NwsP7p--90gZd9x1TTN:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ef28a968eb2092a4e89443cf6674434a7dee28/crates/blockifier/src/concurrency/worker_logic.rs#L24)):*
> ```XML
> // Therefore we need to check that the value read by the transaction is still valid.
> // This function is relevant for transactions that read the sequencer balance before the fee
> // transfer
> ```





_Suggestion:_
```XML
// Checks that the sequencer balance reads made by a given transaction are still valid.
// All transactions update the sequencer balance only when they are committed.
// These changes are not visible to other transactions during execution and validation.
// Therefore, revalidation of these reads is needed before committing a transaction.
```


<!-- Sent from Reviewable.io -->

2024-05-02 08:50 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 24 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NwsP7p--90gZd9x1TTM:-NwsUdN-2ONsz_X7_2UY:b-hxrr3a) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ef28a968eb2092a4e89443cf6674434a7dee28/crates/blockifier/src/concurrency/worker_logic.rs#L24)):*
> ```XML
> // Therefore we need to check that the value read by the transaction is still valid.
> // This function is relevant for transactions that read the sequencer balance before the fee
> // transfer
> ```

Added this to the previous PR.


<!-- Sent from Reviewable.io -->

2024-05-02 15:23 UTC, avi-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 0 of 16 files reviewed, 7 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nwtq1HN-5-BI7igUnOm:-Nwtq1HN-5-BI7igUnOn:b-rdix09) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ef28a968eb2092a4e89443cf6674434a7dee28/crates/blockifier/src/concurrency/scheduler.rs#L187)):*
> ```XML
>     pub tx_index: TxIndex,
>     pub wave: usize,
> }
> ```

Let's leave this for a later PR
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nwtq8Tk8-k4v6vSLrlE:-Nwtq8Tk8-k4v6vSLrlF:b-2nz2yw) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ef28a968eb2092a4e89443cf6674434a7dee28/crates/blockifier/src/concurrency/worker_logic.rs#L62)):*
> ```XML
>     read_set: &StateMaps,
>     transactions_info: &mut [TransactionExecutionResult<TransactionExecutionInfo>],
>     commit_status: &mut CommitStatus,
> ```

I think this function should just get a tx_index and try to commit it.
To indicate whether the commit_status should be incremented, we can simply have it return a `bool` (`true` for committed, `false` for not committed).
If you add this `bool`, we should change the name of the function to `try_commit_transaction`, to make it clear that it doesn't always succeed. 
We can also leave this for after we integrate the bouncer into the commit process. (If so, leave a TODO indicating this.)
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 88 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nwtrm9N2l59LFZ7gJLv:-Nwtrm9N2l59LFZ7gJLw:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ef28a968eb2092a4e89443cf6674434a7dee28/crates/blockifier/src/concurrency/worker_logic.rs#L88)):*
> ```XML
> 
>     if !revalidate_sequencer_balance_reads(versioned_state, *tx_index, &tx_context, read_set) {
>         // revalidate seq reads failed rexecute the transaction and commit.
> ```





_Suggestion:_
```XML
Revalidate sequencer balance reads failed: re-execute the transaction, and commit.
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 111 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NwtsHY6Bn_Z5bhzn8UU:-NwtsHY6Bn_Z5bhzn8UV:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ef28a968eb2092a4e89443cf6674434a7dee28/crates/blockifier/src/concurrency/worker_logic.rs#L111)):*
> ```XML
>     }
> 
>     // revalidateseq reads passed
> ```





_Suggestion:_
```XML
 // Revalidate sequencer balance reads succeeded.
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 113 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NwtsRIgA-E1eDFbvE1p:-NwtsRIgA-E1eDFbvE1q:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ef28a968eb2092a4e89443cf6674434a7dee28/crates/blockifier/src/concurrency/worker_logic.rs#L113)):*
> ```XML
>     // revalidateseq reads passed
>     if let Ok(tx_info) = result_tx_info.as_mut() {
>         // todo check if it has place in the bouncer
> ```





_Suggestion:_
```XML
TODO(Meshi, 01/06/2024): check if this is also needed in the bouncer.
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NwtsiKP0IAgKGzEuWR_:-NwtsiKQ9tvTUeFdkfgP:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ef28a968eb2092a4e89443cf6674434a7dee28/crates/blockifier/src/concurrency/worker_logic.rs#L115)):*
> ```XML
>         // todo check if it has place in the bouncer
> 
>         // fix the call info
> ```





_Suggestion:_
```XML
Fix the call info.
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 123 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NwtsljYB7SXt2Pj9hj9:-NwtsljYB7SXt2Pj9hjA:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ef28a968eb2092a4e89443cf6674434a7dee28/crates/blockifier/src/concurrency/worker_logic.rs#L123)):*
> ```XML
>         }
> 
>         // update sequencer balance
> ```





_Suggestion:_
```XML
 // Update sequencer balance.
```


<!-- Sent from Reviewable.io -->

2024-05-05 07:20 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 0 of 16 files reviewed, 7 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 62 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nwtq8Tk8-k4v6vSLrlE:-Nx6bqj49jeWT9aiT5Ax:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ef28a968eb2092a4e89443cf6674434a7dee28/crates/blockifier/src/concurrency/worker_logic.rs#L62)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I think this function should just get a tx_index and try to commit it.
To indicate whether the commit_status should be incremented, we can simply have it return a `bool` (`true` for committed, `false` for not committed).
If you add this `bool`, we should change the name of the function to `try_commit_transaction`, to make it clear that it doesn't always succeed. 
We can also leave this for after we integrate the bouncer into the commit process. (If so, leave a TODO indicating this.)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 88 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nwtrm9N2l59LFZ7gJLv:-Nx6btBHEcL6obazRFf4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ef28a968eb2092a4e89443cf6674434a7dee28/crates/blockifier/src/concurrency/worker_logic.rs#L88)):*
> ```XML
> 
>     if !revalidate_sequencer_balance_reads(versioned_state, *tx_index, &tx_context, read_set) {
>         // revalidate seq reads failed rexecute the transaction and commit.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 111 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NwtsHY6Bn_Z5bhzn8UU:-Nx6bvSx-toEPH2u4vHp:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ef28a968eb2092a4e89443cf6674434a7dee28/crates/blockifier/src/concurrency/worker_logic.rs#L111)):*
> ```XML
>     }
> 
>     // revalidateseq reads passed
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 113 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NwtsRIgA-E1eDFbvE1p:-Nx6bwzF3ipKtzRGaz5W:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ef28a968eb2092a4e89443cf6674434a7dee28/crates/blockifier/src/concurrency/worker_logic.rs#L113)):*
> ```XML
>     // revalidateseq reads passed
>     if let Ok(tx_info) = result_tx_info.as_mut() {
>         // todo check if it has place in the bouncer
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 115 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NwtsiKP0IAgKGzEuWR_:-Nx6bxqi2qo60FSyTG_M:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ef28a968eb2092a4e89443cf6674434a7dee28/crates/blockifier/src/concurrency/worker_logic.rs#L115)):*
> ```XML
>         // todo check if it has place in the bouncer
> 
>         // fix the call info
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 123 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NwtsljYB7SXt2Pj9hj9:-Nx6byZR7my-gVfwFE3_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ef28a968eb2092a4e89443cf6674434a7dee28/crates/blockifier/src/concurrency/worker_logic.rs#L123)):*
> ```XML
>         }
> 
>         // update sequencer balance
> ```

Done.
___
*[`crates/blockifier/src/concurrency/scheduler.rs` line 187 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nwtq1HN-5-BI7igUnOm:-Nx6bzPG-FGKIcL7vJlt:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ef28a968eb2092a4e89443cf6674434a7dee28/crates/blockifier/src/concurrency/scheduler.rs#L187)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Let's leave this for a later PR
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-05 10:44 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 20 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7LH4dBqb8arvg3oJt:-Nx7LH4dBqb8arvg3oJu:buar9yh) ([raw file](https://github.com/starkware-libs/blockifier/blob/73382c170e4bdac3a71a038528afce4ed5e5325e/crates/blockifier/src/concurrency/worker_logic.rs#L20)):*
> ```XML
> pub fn try_commit_transaction<S: StateReader>(
>     versioned_state: &mut ThreadSafeVersionedState<S>,
>     tx_index: &TxIndex,
> ```

`TxIndex` is `usize`, so no need to borrow it.



_Suggestion:_
```XML
    tx_index: TxIndex,
```


<!-- Sent from Reviewable.io -->

2024-05-05 11:17 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 0 of 16 files reviewed, 8 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 20 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7LH4dBqb8arvg3oJt:-Nx7T6acEUZ90bZwh0TL:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/73382c170e4bdac3a71a038528afce4ed5e5325e/crates/blockifier/src/concurrency/worker_logic.rs#L20)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

`TxIndex` is `usize`, so no need to borrow it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-05 11:26 UTC, avi-starkware requested changes
> Reviewed 2 of 15 files at r3, 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 0 of 16 files reviewed, 4 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 24 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7MqA6BDIC77-Ih0VW:-Nx7MqA77zmLDfP546IR:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/73382c170e4bdac3a71a038528afce4ed5e5325e/crates/blockifier/src/concurrency/worker_logic.rs#L24)):*
> ```XML
>     tx_list: Vec<&AccountTransaction>,
>     read_set: &StateMaps,
>     transactions_info: &mut [TransactionExecutionResult<TransactionExecutionInfo>],
> ```





_Suggestion:_
```XML
    transaction_infos: &mut [TransactionExecutionResult<TransactionExecutionInfo>],
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 36 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7R3MA1mxRZf5l3rjt:-Nx7R3MA1mxRZf5l3rju:b89bn22) ([raw file](https://github.com/starkware-libs/blockifier/blob/73382c170e4bdac3a71a038528afce4ed5e5325e/crates/blockifier/src/concurrency/worker_logic.rs#L36)):*
> ```XML
>     // mode.
>     let mut cached_state = CachedState::from(versioned_state.pin_version(*tx_index));
>     let mut transactional_state = CachedState::create_transactional(&mut cached_state);
> ```

@noaov1 
Does it make sense to create a transactional state for each transaction?
Can't we manage all the changes in the versioned state and only create a transactional state when the block is ready?
If not, we should probably maintain a single transactional state for all commits in the same worker loop iteration.



_Code quote:_
```XML
    let mut cached_state = CachedState::from(versioned_state.pin_version(*tx_index));
    let mut transactional_state = CachedState::create_transactional(&mut cached_state);
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 44 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7T5e91X-3DkgvOZqF:-Nx7T5e91X-3DkgvOZqG:b-lwprx3) ([raw file](https://github.com/starkware-libs/blockifier/blob/73382c170e4bdac3a71a038528afce4ed5e5325e/crates/blockifier/src/concurrency/worker_logic.rs#L44)):*
> ```XML
>         block_context.concurrency_mode = false;
>         transactions_info[*tx_index] =
>             account_tx.execute_raw(&mut transactional_state, block_context, true, true);
> ```

We have to let the scheduler know that there has been an execution here. So that it can lower the validation index to tx_index + 1 (a re-execution always implies that higher transactions have to be invalidated.

We don't have this functionality in the scheduler yet. In Aptos it is called [finish_execution_during_commit](https://github.com/igor-aptos/aptos-core/blob/main/aptos-move/block-executor/src/executor.rs#L484). So you can add a TODO(Avi, 20/5/2024): Add finish_execution_during_commit to the scheduler and use it here.

Additionally, I think we should add another `validate_read_set` after this final execution as a sanity check and panic if it fails.


<!-- Sent from Reviewable.io -->

2024-05-05 11:33 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 36 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7R3MA1mxRZf5l3rjt:-Nx7VXcYBMro0jW92Nq5:bl7ap6n) ([raw file](https://github.com/starkware-libs/blockifier/blob/73382c170e4bdac3a71a038528afce4ed5e5325e/crates/blockifier/src/concurrency/worker_logic.rs#L36)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

@noaov1 
Does it make sense to create a transactional state for each transaction?
Can't we manage all the changes in the versioned state and only create a transactional state when the block is ready?
If not, we should probably maintain a single transactional state for all commits in the same worker loop iteration.
</blockquote></details>

This is a temporary cheat to call execute raw. When Ori merges his trait PR we won't need this anymore. Maybe the TODO should be more informative.   


<!-- Sent from Reviewable.io -->

2024-05-05 11:36 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 67 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7WgEm5A_4tUz8xH7d:-Nx7WgEnEMo11i4Djaav:b-m2l45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L67)):*
> ```XML
>             let sequencer_balance_high = versioned_state
>                 .pin_version(tx_index)
>                 .get_storage_at(tx_context.fee_token_address(), sequencer_balance_key_high);
> ```

This makes three times we call the method `pin_version`. Each such invocation creates a new versioned state proxy.
Wouldn't it be better to have `let mut pinned_versioned_state = versioned_state.pin_version(tx_index)` and thus only use this method once?



_Code quote:_
```XML
            let sequencer_balance_low = versioned_state
                .pin_version(tx_index)
                .get_storage_at(tx_context.fee_token_address(), sequencer_balance_key_low);
            let sequencer_balance_high = versioned_state
                .pin_version(tx_index)
                .get_storage_at(tx_context.fee_token_address(), sequencer_balance_key_high);
```


<!-- Sent from Reviewable.io -->

2024-05-05 11:36 UTC, noaov1 requested changes
> Reviewed 11 of 15 files at r3, 1 of 4 files at r4, 1 of 2 files at r5, 2 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 15 of 16 files reviewed, 11 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 154 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7UcZx0EemBKqCJa4c:-Nx7UcZx0EemBKqCJa4d:b-2xd07a) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L154)):*
> ```XML
>     }
> 
>     pub fn apply_writes(
> ```

Already done in this [PR](https://reviewable.io/reviews/starkware-libs/blockifier/1860). Make sure to align your code.



_Code quote:_
```XML
    pub fn validate_read_set(&self, tx_index: TxIndex, read_set: &StateMaps) -> bool {
        let mut state = self.0.lock().expect("Failed to acquire state lock.");
        state.validate_read_set(tx_index, read_set)
    }

    pub fn apply_writes(
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 22 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7VBp7BjpX0oOyxLEQ:-Nx7VBp7BjpX0oOyxLER:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L22)):*
> ```XML
>     tx_index: TxIndex,
>     block_context: &mut BlockContext,
>     tx_list: Vec<&AccountTransaction>,
> ```





_Suggestion:_
```XML
    txs_chunk:&[Transaction],
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 23 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7VV8g81CCodE8et5Y:-Nx7VV8g81CCodE8et5Z:by4b7oe) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L23)):*
> ```XML
>     block_context: &mut BlockContext,
>     tx_list: Vec<&AccountTransaction>,
>     read_set: &StateMaps,
> ```

Maybe it makes sense to get a reference to an array with the read set (for consistency)



_Code quote:_
```XML
    read_set: &StateMaps,
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 31 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7VoS41BoPOxf0jY77:-Nx7VoS41BoPOxf0jY78:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L31)):*
> ```XML
>     }
> 
>     let account_tx = tx_list[tx_index];
> ```





_Suggestion:_
```XML
    let tx = tx_list[tx_index];
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 51 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7WlXr1ehr9wBmutBs:-Nx7WlXr1ehr9wBmutBt:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L51)):*
> ```XML
>             tx_index,
>             &transactional_state.cache.borrow_mut().writes,
>             &ContractClassMapping::default(),
> ```





_Suggestion:_
```XML
            &transactional_state.cache.borrow().writes,
            &transactional_state.cache.borrow().class_hash_to_class,
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 58 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7XKFS5jmOtokLDSA-:-Nx7XKFS5jmOtokLDSA0:b-5ljdob) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L58)):*
> ```XML
> 
>     // Revalidate succeeded
>     if let Ok(tx_info) = result_tx_info.as_mut() {
> ```

It must be okay at this point, no?



_Code quote:_
```XML
    if let Ok(tx_info) = result_tx_info.as_mut() {
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 59 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7XPJr0sU4WNbFS1yh:-Nx7XPJs2R7QGWhGchg_:b-uqr83e) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L59)):*
> ```XML
>     // Revalidate succeeded
>     if let Ok(tx_info) = result_tx_info.as_mut() {
>         // TODO(Meshi, 01/06/2024): check if this is also needed in the bouncer.
> ```

The bouncer should be checked last. Can you please unify the bouncer check for the two cases? 



_Code quote:_
```XML
        // TODO(Meshi, 01/06/2024): check if this is also needed in the bouncer.
```


<!-- Sent from Reviewable.io -->

2024-05-05 11:46 UTC, noaov1 requested changes
> Reviewed 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: all files reviewed, 12 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 36 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7R3MA1mxRZf5l3rjt:-Nx7YYMN37ksCPchH8LQ:b1mvlz4) ([raw file](https://github.com/starkware-libs/blockifier/blob/73382c170e4bdac3a71a038528afce4ed5e5325e/crates/blockifier/src/concurrency/worker_logic.rs#L36)):*
Note- we will create transactional state for each transaction needs to be re-executed (we apply the writes at the end).
Consider creating it only in that case (validation failed).
> If not, we should probably maintain a single transactional state for all commits in the same worker loop iteration.

WDYM? each transaction has its own writes that are needed to be "flushed" to the versioned state. 
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 67 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7Y2uyC9gYqn8AR7bj:-Nx7Y2uzA2XIEFj0gpQe:be69f0l) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L67)):*
> ```XML
>             let sequencer_balance_high = versioned_state
>                 .pin_version(tx_index)
>                 .get_storage_at(tx_context.fee_token_address(), sequencer_balance_key_high);
> ```

Avoid using `unwrap`s :)



_Suggestion:_
```XML
            let sequencer_balance_low = versioned_state
                .pin_version(tx_index)
                .get_storage_at(tx_context.fee_token_address(), sequencer_balance_key_low)?;
            let sequencer_balance_high = versioned_state
                .pin_version(tx_index)
                .get_storage_at(tx_context.fee_token_address(), sequencer_balance_key_high)?;
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 89 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7YPxo0xVPeEi2LZZl:-Nx7YPxo0xVPeEi2LZZm:baf1qvt) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L89)):*
> ```XML
>                     felt_to_stark_felt(&value),
>                 )
>                 .unwrap();
> ```

Can you please explain the following? Why is it needed?



_Code quote:_
```XML
            // Update sequencer balance.
            let seq_balance_key = get_fee_token_var_address(tx_context.fee_token_address());
            let seq_balance_value = transactional_state
                .get_storage_at(tx_context.fee_token_address(), seq_balance_key)
                .unwrap();
            let value = stark_felt_to_felt(seq_balance_value) + Felt252::from(tx_info.actual_fee.0);
            transactional_state
                .set_storage_at(
                    tx_context.fee_token_address(),
                    seq_balance_key,
                    felt_to_stark_felt(&value),
                )
                .unwrap();
```


<!-- Sent from Reviewable.io -->

2024-05-05 11:53 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 89 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7YPxo0xVPeEi2LZZl:-Nx7_V_26Rl7wDG-11xg:biqht3s) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L89)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain the following? Why is it needed?
</blockquote></details>

Doesn't it update the sequencer balance in storage?


<!-- Sent from Reviewable.io -->

2024-05-05 11:59 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 89 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7YPxo0xVPeEi2LZZl:-Nx7_V_26Rl7wDG-11xg:biqht3s) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L89)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain the following? Why is it needed?
</blockquote></details>

Doesn't it update the sequencer balance in storage?


<!-- Sent from Reviewable.io -->

2024-05-05 11:59 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 36 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7R3MA1mxRZf5l3rjt:-Nx7aFpE7_NJrxcc9Fi2:b-2nk2p6) ([raw file](https://github.com/starkware-libs/blockifier/blob/73382c170e4bdac3a71a038528afce4ed5e5325e/crates/blockifier/src/concurrency/worker_logic.rs#L36)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Note- we will create transactional state for each transaction needs to be re-executed (we apply the writes at the end).
Consider creating it only in that case (validation failed).
> If not, we should probably maintain a single transactional state for all commits in the same worker loop iteration.

WDYM? each transaction has its own writes that are needed to be "flushed" to the versioned state.
</blockquote></details>

I mean that if the same thread commits many transactions one after the other, we might be able to keep using the same transactional state as long as there are more transactions that can be committed.


<!-- Sent from Reviewable.io -->

2024-05-05 13:37 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 10 of 18 files reviewed, 10 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 24 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7MqA6BDIC77-Ih0VW:-Nx7wc1NE_9jej7wX6Wp:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/73382c170e4bdac3a71a038528afce4ed5e5325e/crates/blockifier/src/concurrency/worker_logic.rs#L24)):*
> ```XML
>     tx_list: Vec<&AccountTransaction>,
>     read_set: &StateMaps,
>     transactions_info: &mut [TransactionExecutionResult<TransactionExecutionInfo>],
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 22 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7VBp7BjpX0oOyxLEQ:-Nx7wdSeE6DUC690YfJj:b-t8qhms) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L22)):*
> ```XML
>     tx_index: TxIndex,
>     block_context: &mut BlockContext,
>     tx_list: Vec<&AccountTransaction>,
> ```

is there a way to call execute_raw from Transaction and not AccountTransaction?
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 51 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7WlXr1ehr9wBmutBs:-Nx7wqy01H40bnOk82oV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L51)):*
> ```XML
>             tx_index,
>             &transactional_state.cache.borrow_mut().writes,
>             &ContractClassMapping::default(),
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 58 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7XKFS5jmOtokLDSA-:-Nx7ZDzvC19sjcHQl1L2:bm221vu) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L58)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

It must be okay at this point, no?
</blockquote></details>

Yes, but it was the only way we convinced him that we could use tx_info. and the resone  
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 67 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7WgEm5A_4tUz8xH7d:-Nx7wuD78w4hQIjA-BWj:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L67)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

This makes three times we call the method `pin_version`. Each such invocation creates a new versioned state proxy.
Wouldn't it be better to have `let mut pinned_versioned_state = versioned_state.pin_version(tx_index)` and thus only use this method once?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 67 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7Y2uyC9gYqn8AR7bj:-Nx7wvAbBIcmlIaSsebK:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L67)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Avoid using `unwrap`s :)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 89 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7YPxo0xVPeEi2LZZl:-Nx7afsb5bCdtAyeVKKb:b-nzvxlo) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L89)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain the following? Why is it needed?
</blockquote></details>

We need to update the sequencer balance, as we deleted these chances. The first part only fixes the call info. Now, we need to add the actual fee to the sequencer balance.


<!-- Sent from Reviewable.io -->

2024-05-05 14:22 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 9 of 18 files reviewed, 8 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 154 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7UcZx0EemBKqCJa4c:-Nx87XtZ8wXV0hf4hv4h:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L154)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Already done in this [PR](https://reviewable.io/reviews/starkware-libs/blockifier/1860). Make sure to align your code.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 22 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7VBp7BjpX0oOyxLEQ:-Nx87dfn2HWP7RyeiYy1:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L22)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

is there a way to call execute_raw from Transaction and not AccountTransaction?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-06 09:06 UTC, noaov1 requested changes
> Reviewed 1 of 8 files at r8, 7 of 8 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: all files reviewed, 14 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 17 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxC5PoCEPPnC8N2Tl0k:-NxC5PoCEPPnC8N2Tl0l:bgwxnl3) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f9483ac597dd64e17c8c6dace7cb637adb8b2c/crates/blockifier/src/concurrency/fee_utils.rs#L17)):*
> ```XML
>     let sequencer_balance_indecies = if fee_transfer_call_info.storage_read_values.len() == 4 {
>         2..4
>     } else {
> ```

I this change relevant to this PR?



_Code quote:_
```XML
    let sequencer_balance_indecies = if fee_transfer_call_info.storage_read_values.len() == 4 {
        2..4
    } else {
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 144 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxBnIWe2u5OSjyqKqOO:-NxBnIWe2u5OSjyqKqOP:b4eptf1) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f9483ac597dd64e17c8c6dace7cb637adb8b2c/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L144)):*
> ```XML
> }
> 
> pub struct ThreadSafeVersionedState<S: StateReader>(pub Arc<Mutex<VersionedState<S>>>);
> ```

Is the `pub` needed?



_Code quote:_
```XML
pub struct ThreadSafeVersionedState<S: StateReader>(pub Arc<Mutex<VersionedState<S>>>);
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 36 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7R3MA1mxRZf5l3rjt:-NxC63Zo6ZdEoQvsiYz9:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/73382c170e4bdac3a71a038528afce4ed5e5325e/crates/blockifier/src/concurrency/worker_logic.rs#L36)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I mean that if the same thread commits many transactions one after the other, we might be able to keep using the same transactional state as long as there are more transactions that can be committed.
</blockquote></details>

?
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 58 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7XKFS5jmOtokLDSA-:-NxC7IeB4-FjJgr6Dw89:b-er7zo5) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L58)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Yes, but it was the only way we convinced him that we could use tx_info. and the resone
</blockquote></details>

Maybe add an assert? For sanity check
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 89 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7YPxo0xVPeEi2LZZl:-NxC7RN39aOisf9GxBWG:b-cajdlx) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L89)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

We need to update the sequencer balance, as we deleted these chances. The first part only fixes the call info. Now, we need to add the actual fee to the sequencer balance.
</blockquote></details>

Great. Please define a method. 
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 35 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxC5solDg3OC6u0nmTm:-NxC5solDg3OC6u0nmTn:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f9483ac597dd64e17c8c6dace7cb637adb8b2c/crates/blockifier/src/concurrency/worker_logic.rs#L35)):*
> ```XML
>     let tx_context = Arc::new(block_context.to_tx_context(tx));
>     // TODO(meshi 20/05/2024): chenge this when the chached state will be updated to fit concurrency
>     // mode.
> ```





_Suggestion:_
```XML
    // TODO(meshi 20/05/2024): remove the redundant cached state.
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 39 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxC79l87G-qBt6-sekS:-NxC79l87G-qBt6-sekT:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f9483ac597dd64e17c8c6dace7cb637adb8b2c/crates/blockifier/src/concurrency/worker_logic.rs#L39)):*
> ```XML
>     let mut cached_state = CachedState::from(versioned_state.pin_version(tx_index));
>     let mut transactional_state = CachedState::create_transactional(&mut cached_state);
>     let pinned_versioned_state = versioned_state.pin_version(tx_index);
> ```





_Suggestion:_
```XML
    let tx_versioned_state = versioned_state.pin_version(tx_index);
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 47 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxC6o9tADAmbVgMrnnG:-NxC6o9u1d03Qgm_AZU9:bpkbpvx) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f9483ac597dd64e17c8c6dace7cb637adb8b2c/crates/blockifier/src/concurrency/worker_logic.rs#L47)):*
> ```XML
>         block_context.concurrency_mode = false;
>         transaction_infos[tx_index] =
>             tx.execute_raw(&mut transactional_state, block_context, true, true);
> ```

Please define variables for the `charge_fee` and `validate` arguments.



_Code quote:_
```XML
            tx.execute_raw(&mut transactional_state, block_context, true, true);
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 50 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxC6wHk9u4lQlUX8UaU:-NxC6wHk9u4lQlUX8UaV:b4lme9a) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f9483ac597dd64e17c8c6dace7cb637adb8b2c/crates/blockifier/src/concurrency/worker_logic.rs#L50)):*
> ```XML
>         if transaction_infos[tx_index].is_err() {
>             return Ok(true);
>         }
> ```

Please add a TODO to delete the transaction writes.



_Code quote:_
```XML
        if transaction_infos[tx_index].is_err() {
            return Ok(true);
        }
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 55 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxC7wtaEGBNGMS5n6p8:-NxC7wtaEGBNGMS5n6p9:bamga6) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f9483ac597dd64e17c8c6dace7cb637adb8b2c/crates/blockifier/src/concurrency/worker_logic.rs#L55)):*
> ```XML
>             &transactional_state.class_hash_to_class.borrow(),
>         );
>         // TODO(Meshi, 01/06/2024): check if this is also needed in the bouncer.
> ```

Can be done at the end? (of both cases)



_Code quote:_
```XML
 // TODO(Meshi, 01/06/2024): check if this is also needed in the bouncer.
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 59 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxC84oD36LiYX4NiqYZ:-NxC84oD36LiYX4NiqY_:b-9cbmd4) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f9483ac597dd64e17c8c6dace7cb637adb8b2c/crates/blockifier/src/concurrency/worker_logic.rs#L59)):*
> ```XML
>     // Revalidate succeeded
>     else if let Ok(tx_info) = result_tx_info.as_mut() {
>         if tx_context.tx_info.sender_address() != block_context.block_info.sequencer_address {
> ```

Please add a documentation to explain this if.



_Code quote:_
```XML
 if tx_context.tx_info.sender_address() != block_context.block_info.sequencer_address {
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 77 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxC8Q_MDHNS_BeB-RJj:-NxC8Q_MDHNS_BeB-RJk:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f9483ac597dd64e17c8c6dace7cb637adb8b2c/crates/blockifier/src/concurrency/worker_logic.rs#L77)):*
> ```XML
>             let seq_balance_key = get_fee_token_var_address(tx_context.fee_to [...]

2024-05-06 13:24 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 15 of 18 files reviewed, 9 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 89 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7YPxo0xVPeEi2LZZl:-NxD166L7QUhdh4uNmmo:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L89)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Great. Please define a method.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 47 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxC6o9tADAmbVgMrnnG:-NxCWqHo8bY-gFhtL06F:b-jantxf) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f9483ac597dd64e17c8c6dace7cb637adb8b2c/crates/blockifier/src/concurrency/worker_logic.rs#L47)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please define variables for the `charge_fee` and `validate` arguments.
</blockquote></details>

Too many arguments :( I can add a todo to make a struct that contains some of the fields or make this struct.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 50 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxC6wHk9u4lQlUX8UaU:-NxD3uYSB1NP0-1yGAGt:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f9483ac597dd64e17c8c6dace7cb637adb8b2c/crates/blockifier/src/concurrency/worker_logic.rs#L50)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please add a TODO to delete the transaction writes.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 55 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxC7wtaEGBNGMS5n6p8:-NxD18bj6m90SLhDujmr:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f9483ac597dd64e17c8c6dace7cb637adb8b2c/crates/blockifier/src/concurrency/worker_logic.rs#L55)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can be done at the end? (of both cases)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 85 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxC8d6H4as3hdpCq2nB:-NxD14yw6sFudsKkGA9c:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f9483ac597dd64e17c8c6dace7cb637adb8b2c/crates/blockifier/src/concurrency/worker_logic.rs#L85)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

This need to be done on the shared versioned state (using `apply_writes`).
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 17 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxC5PoCEPPnC8N2Tl0k:-NxD1vQ17RwIbsJU9-q0:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f9483ac597dd64e17c8c6dace7cb637adb8b2c/crates/blockifier/src/concurrency/fee_utils.rs#L17)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I this change relevant to this PR?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-07 06:34 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 15 of 18 files reviewed, 8 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 44 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7T5e91X-3DkgvOZqF:-NxGk9_3DCWRhbB44hiI:bvzhhqg) ([raw file](https://github.com/starkware-libs/blockifier/blob/73382c170e4bdac3a71a038528afce4ed5e5325e/crates/blockifier/src/concurrency/worker_logic.rs#L44)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

We have to let the scheduler know that there has been an execution here. So that it can lower the validation index to tx_index + 1 (a re-execution always implies that higher transactions have to be invalidated.

We don't have this functionality in the scheduler yet. In Aptos it is called [finish_execution_during_commit](https://github.com/igor-aptos/aptos-core/blob/main/aptos-move/block-executor/src/executor.rs#L484). So you can add a TODO(Avi, 20/5/2024): Add finish_execution_during_commit to the scheduler and use it here.

Additionally, I think we should add another `validate_read_set` after this final execution as a sanity check and panic if it fails.
</blockquote></details>

Done. In this PR https://reviewable.io/reviews/starkware-libs/blockifier/1871


<!-- Sent from Reviewable.io -->

2024-05-07 12:08 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 31 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxHuv6o3BoKSpRi3Sai:-NxHwpPqEqAjk7JrFsuA:bq6tyqo) ([raw file](https://github.com/starkware-libs/blockifier/blob/423965fb04d1a24e36e9e58d008c4f5f48d4b511/crates/blockifier/src/concurrency/worker_logic.rs#L31)):*
> ```XML
> }
> 
> pub fn try_commit_transaction<S: StateReader>(
> ```

Actually, we should make it `try_commit` to be consistent with other names in the concurrency module.


<!-- Sent from Reviewable.io -->

2024-05-07 12:10 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 36 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7R3MA1mxRZf5l3rjt:-NxHxOMF2kBJB3b1Xa7c:byv04e8) ([raw file](https://github.com/starkware-libs/blockifier/blob/73382c170e4bdac3a71a038528afce4ed5e5325e/crates/blockifier/src/concurrency/worker_logic.rs#L36)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

?
</blockquote></details>

Nevermind, creating the transactional state is probably not a big deal.


<!-- Sent from Reviewable.io -->

2024-05-07 12:14 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: all files reviewed, 9 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 31 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxHuv6o3BoKSpRi3Sai:-NxHy4fbEc48CDwUrYG5:bg0yqtw) ([raw file](https://github.com/starkware-libs/blockifier/blob/423965fb04d1a24e36e9e58d008c4f5f48d4b511/crates/blockifier/src/concurrency/worker_logic.rs#L31)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Actually, we should make it `try_commit` to be consistent with other names in the concurrency module.
</blockquote></details>

I think that the `try_commit` method will run `try_commit_tx` (after running the scheduler `try_commit`, meaning, after catching the commit lock and verifying the relevant transaction status). WDYT?


<!-- Sent from Reviewable.io -->

2024-05-07 13:18 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: all files reviewed, 9 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 44 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7T5e91X-3DkgvOZqF:-NxI6Irt-vMWA5xk4usn:b-94vcqe) ([raw file](https://github.com/starkware-libs/blockifier/blob/73382c170e4bdac3a71a038528afce4ed5e5325e/crates/blockifier/src/concurrency/worker_logic.rs#L44)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Done. In this PR https://reviewable.io/reviews/starkware-libs/blockifier/1871
</blockquote></details>

I am going to use the execute method that already calls the  
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 89 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7YPxo0xVPeEi2LZZl:-NxIBpFzDq1C_S-u7dVN:b8qrvsh) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L89)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Not yet :)
</blockquote></details>

In PR https://reviewable.io/reviews/starkware-libs/blockifier/1870
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 50 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxC6wHk9u4lQlUX8UaU:-NxIBhyC991FUDOLo2-W:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f9483ac597dd64e17c8c6dace7cb637adb8b2c/crates/blockifier/src/concurrency/worker_logic.rs#L50)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I'm sorry, I cited the wrong code. I meant after re-validation had failed.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 42 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxHvlU49Kg59m9aaJZJ:-NxI6AHDBz0gJErzJv-I:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/423965fb04d1a24e36e9e58d008c4f5f48d4b511/crates/blockifier/src/concurrency/worker_logic.rs#L42)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Don't we want to re-validate first?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-07 13:21 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 17 of 18 files reviewed, 8 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 44 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7T5e91X-3DkgvOZqF:-NxICNH49fiXJmmQtZk4:b-x8dt13) ([raw file](https://github.com/starkware-libs/blockifier/blob/73382c170e4bdac3a71a038528afce4ed5e5325e/crates/blockifier/src/concurrency/worker_logic.rs#L44)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I am going to use the execute method that already calls the
</blockquote></details>

Sorry, please ignore the last note. It was a draft that I published by accident.  


<!-- Sent from Reviewable.io -->

2024-05-08 09:04 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 31 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxHuv6o3BoKSpRi3Sai:-NxMRavEDo00o8YB4P1q:bb71kmx) ([raw file](https://github.com/starkware-libs/blockifier/blob/423965fb04d1a24e36e9e58d008c4f5f48d4b511/crates/blockifier/src/concurrency/worker_logic.rs#L31)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think that the `try_commit` method will run `try_commit_tx` (after running the scheduler `try_commit`, meaning, after catching the commit lock and verifying the relevant transaction status). WDYT?
</blockquote></details>

Okay


<!-- Sent from Reviewable.io -->

2024-05-08 09:06 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 44 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7T5e91X-3DkgvOZqF:-NxMRmb13L-ZkRf35EvX:bekcn3j) ([raw file](https://github.com/starkware-libs/blockifier/blob/73382c170e4bdac3a71a038528afce4ed5e5325e/crates/blockifier/src/concurrency/worker_logic.rs#L44)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Sorry, please ignore the last note. It was a draft that I published by accident.
</blockquote></details>

What about adding another validation after the execution?


<!-- Sent from Reviewable.io -->

2024-05-08 09:07 UTC, avi-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 17 of 18 files reviewed, 6 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`-- commits` line 3 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxMSJEh73OXgudLQ4wa):*
I think a rebase got messed up.



_Code quote:_
```
- 2c9d31f: test(concurrency): add unitests for concurrency fee transfer
```


<!-- Sent from Reviewable.io -->

2024-05-08 10:05 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 11 of 18 files reviewed, 6 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`-- commits` line 3 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxMSJEh73OXgudLQ4wa):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I think a rebase got messed up.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-08 12:49 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 50 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxNDWp69Z0mn2_IpukZ:-NxNDWp69Z0mn2_Ipuk_:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d612ce701e7bdcf2117435a744ba54699f5cca66/crates/blockifier/src/concurrency/worker_logic.rs#L50)):*
> ```XML
>     let tx_versioned_state = versioned_state.pin_version(tx_index);
> 
>     // Fisrt, re-validate the transaction.
> ```





_Suggestion:_
```XML
    // First, re-validate the transaction.
```


<!-- Sent from Reviewable.io -->

2024-05-09 06:31 UTC, meship-starkware reviewed
I'm in the middle of trying to fit try_commit _tx to Noa's chances. There is no need to check it yet I pushed it because of the rebases. 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-:-NxR1lCH-WuFmX95vV-u:bec2ttc)* status: 10 of 18 files reviewed, 8 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 50 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxNDWp69Z0mn2_IpukZ:-NxNVXor-KJSNBV9JtTo:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d612ce701e7bdcf2117435a744ba54699f5cca66/crates/blockifier/src/concurrency/worker_logic.rs#L50)):*
> ```XML
>     let tx_versioned_state = versioned_state.pin_version(tx_index);
> 
>     // Fisrt, re-validate the transaction.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 69 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxNGqlG1DZ9xv3GNouj:-NxNVR6XDSLIkMwVMSTf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a77a9cfb62bd26412b10a8134dcdb94e6c27ef3/crates/blockifier/src/concurrency/worker_logic.rs#L69)):*
> ```XML
>         return Ok(true);
>     }
>     // Revalidate succeeded
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 75 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxNFTB9DbXs-NRVG5Mz:-NxNVVzMEMmOXrZEheNr:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a77a9cfb62bd26412b10a8134dcdb94e6c27ef3/crates/blockifier/src/concurrency/worker_logic.rs#L75)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

This sentence is out of context.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-09 06:45 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 10 of 18 files reviewed, 8 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 72 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxNHF_l1vtFZEvgP-gf:-NxR2smH-NJP1hTGMfOt:b5qh7yg) ([raw file](https://github.com/starkware-libs/blockifier/blob/2a77a9cfb62bd26412b10a8134dcdb94e6c27ef3/crates/blockifier/src/concurrency/worker_logic.rs#L72)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Why do we return `true` when there's an error?
</blockquote></details>

This is where the validation passed, so the execution before the commit is the last. This means this transaction is invalid, but it does not corner the commit. From the commit point of view, it committed this transaction, and the commit index should increase. Anyway, it should not return false because the meaning of this function returning false is that we are done. We can return the error, but it's part of the execution results array, so I do not see the need.  


<!-- Sent from Reviewable.io -->

2024-05-09 07:18 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 122 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxRAbj56O4XNtQmSmRM:-NxRAbj56O4XNtQmSmRN:b-m0y4fj) ([raw file](https://github.com/starkware-libs/blockifier/blob/63f29c58f40ba1d5238acd5f5a561ac785e64204/crates/blockifier/src/concurrency/worker_logic.rs#L122)):*
> ```XML
>     if result_tx_info.is_err() {
>         return Ok(true);
>     }
> ```

I think the error is confusing because it is unrelated to concurrency, so we need to add a comment that explains the context.



_Suggestion:_
```XML
    if result_tx_info.is_err() {
        // Transaction reverted and successfully committed.
        return Ok(true);
    }
```


<!-- Sent from Reviewable.io -->

2024-05-09 14:20 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 7 of 20 files reviewed, 9 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 122 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxRAbj56O4XNtQmSmRM:-NxSg-ja6PUVuavssfU7:b-jpjspz) ([raw file](https://github.com/starkware-libs/blockifier/blob/63f29c58f40ba1d5238acd5f5a561ac785e64204/crates/blockifier/src/concurrency/worker_logic.rs#L122)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I think the error is confusing because it is unrelated to concurrency, so we need to add a comment that explains the context.
</blockquote></details>

I'm not sure failed is the right word, but it's not reverted because if the tx was reverted, we had to change the sequencer balance.  I'm not 100% sure what the difference is. Maybe @noaov1 could explain better.


<!-- Sent from Reviewable.io -->

2024-05-09 14:29 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 7 of 20 files reviewed, 11 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 113 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxSjKrN6v62ubSujK9F:-NxSjKrO1tkHBjdHQc4r:brsnw95) ([raw file](https://github.com/starkware-libs/blockifier/blob/611f13550ea0ce4b5aaba43dd8256aa958010a21/crates/blockifier/src/concurrency/worker_logic.rs#L113)):*
> ```XML
>     }
> 
>     pub fn try_commit_transaction(&mut self, tx_index: TxIndex) -> StateResult<bool> {
> ```

I tried to call the lock_mutex_in_array only once, but it screamed at me that I couldn't borrow execution_task_outputs as mutable and immutable. I also tried to drop execution_task_outputs, but it did not work. To say the least, the test passes this way. 
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 129 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxSirOT0O5Ggbzb4U23:-NxSirOT0O5Ggbzb4U24:b4wzmoa) ([raw file](https://github.com/starkware-libs/blockifier/blob/611f13550ea0ce4b5aaba43dd8256aa958010a21/crates/blockifier/src/concurrency/worker_logic.rs#L129)):*
> ```XML
>         if !tx_versioned_state.validate_reads(read_set) {
>             // Revalidate failed: re-execute the transaction, and commit.
> ```

I am not sure it was the best way to change the concurrency mode, but it worked. It might be problematic to ask for &mut self. 


<!-- Sent from Reviewable.io -->

2024-05-15 11:52 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 7 of 22 files reviewed, 12 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 30 at r21](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nxw4_yTCaShcWM-L4Q5:-Nxw4_yTCaShcWM-L4Q6:b-6minpl) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ee602ee40623c912c19caeb873d251a8859a050/crates/blockifier/src/concurrency/worker_logic.rs#L30)):*
> ```XML
> #[path = "worker_logic_test.rs"]
> pub mod test;
> ```

Ignore this function. For some reason, it does not accept this as the change of the previous PR. It is only relevant for this PR https://reviewable.io/reviews/starkware-libs/blockifier/1870
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 19 at r21](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nxw3e7L6J19tmCzCHEl:-Nxw3e7L6J19tmCzCHEm:b-no8lrh) ([raw file](https://github.com/starkware-libs/blockifier/blob/6ee602ee40623c912c19caeb873d251a8859a050/crates/blockifier/src/concurrency/worker_logic_test.rs#L19)):*
> ```XML
> use crate::test_utils::dict_state_reader::DictStateReader;
> use crate::transaction::objects::FeeType;
> ```

Ignore this file. For some reason, it does not accept this as the change of the previous PR. It is only relevant for this PR https://reviewable.io/reviews/starkware-libs/blockifier/1870


<!-- Sent from Reviewable.io -->

2024-05-16 05:59 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 7 of 22 files reviewed, 11 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 122 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxRAbj56O4XNtQmSmRM:-NxzymLL0JORouHEdrVv:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/63f29c58f40ba1d5238acd5f5a561ac785e64204/crates/blockifier/src/concurrency/worker_logic.rs#L122)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I'm not sure failed is the right word, but it's not reverted because if the tx was reverted, we had to change the sequencer balance.  I'm not 100% sure what the difference is. Maybe @noaov1 could explain better.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-16 07:20 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 129 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxSirOT0O5Ggbzb4U23:-Ny-GXEn78tqr5VkYNkw:b-old9p6) ([raw file](https://github.com/starkware-libs/blockifier/blob/611f13550ea0ce4b5aaba43dd8256aa958010a21/crates/blockifier/src/concurrency/worker_logic.rs#L129)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I am not sure it was the best way to change the concurrency mode, but it worked. It might be problematic to ask for &mut self.
</blockquote></details>

Looks fine to me.


<!-- Sent from Reviewable.io -->

2024-05-16 07:34 UTC, avi-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 7 of 22 files reviewed, 7 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 27 at r25](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-IQRcEBq0jUQtUeif:-Ny-IQRcEBq0jUQtUeig:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9215eb5ae9c19fcc00676f14b8f3bff3ed96f59/crates/blockifier/src/concurrency/worker_logic.rs#L27)):*
> ```XML
> use crate::transaction::transactions::ExecutableTransaction;
> 
> const EXECUTION_OUTPUTS_UNWRAP_ERROR: &str = "execution task outpust should not be None.";
> ```





_Suggestion:_
```XML
const EXECUTION_OUTPUTS_UNWRAP_ERROR: &str = "execution task outputs should not be None.";
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 65 at r25](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-IdCwDRql9Hn7Si_p:-Ny-IdCwDRql9Hn7Si_q:b-xwbhzn) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9215eb5ae9c19fcc00676f14b8f3bff3ed96f59/crates/blockifier/src/concurrency/worker_logic.rs#L65)):*
> ```XML
>     pub result: TransactionExecutionResult<TransactionExecutionInfo>,
> }
> pub struct WorkersExecutor<S: StateReader> {
> ```

Add an empty line between scopes.



_Suggestion:_
```XML
}

pub struct WorkersExecutor<S: StateReader> {
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 72 at r25](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-IkBR86Ydbh3QRtc9:-Ny-IkBS48VS4WZzpzxB:bwjzq08) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9215eb5ae9c19fcc00676f14b8f3bff3ed96f59/crates/blockifier/src/concurrency/worker_logic.rs#L72)):*
> ```XML
>     pub block_context: BlockContext,
> }
> impl<S: StateReader> WorkersExecutor<S> {
> ```

Add an empty line between scopes.
(Also everywhere else there is no empty line.)



_Suggestion:_
```XML
}

impl<S: StateReader> WorkersExecutor<S> {
```


<!-- Sent from Reviewable.io -->

2024-05-16 07:38 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 27 at r25](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-Key_7lCPTeCLPW5W:-Ny-Key_7lCPTeCLPW5X:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9215eb5ae9c19fcc00676f14b8f3bff3ed96f59/crates/blockifier/src/concurrency/worker_logic.rs#L27)):*
> ```XML
> use crate::transaction::transactions::ExecutableTransaction;
> 
> const EXECUTION_OUTPUTS_UNWRAP_ERROR: &str = "execution task outpust should not be None.";
> ```





_Suggestion:_
```XML
const EXECUTION_OUTPUTS_UNWRAP_ERROR: &str = "Execution task outputs should not be None.";
```


<!-- Sent from Reviewable.io -->

2024-05-16 07:41 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 186 at r25](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-LD5G9GLqwFxutLpd:-Ny-LD5G9GLqwFxutLpe:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9215eb5ae9c19fcc00676f14b8f3bff3ed96f59/crates/blockifier/src/concurrency/worker_logic.rs#L186)):*
> ```XML
> 
>             let tx_info =
>                 result_tx_info.as_mut().expect("Transaction info should not be an error here.");
> ```





_Suggestion:_
```XML
                result_tx_info.as_mut().expect("Transaction info should not be an error here - rejected transactions pay no fee.");
```


<!-- Sent from Reviewable.io -->

2024-05-16 08:07 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 7 of 22 files reviewed, 9 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 27 at r25](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-IQRcEBq0jUQtUeif:-Ny-RBCSBH3spvDNJEk8:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9215eb5ae9c19fcc00676f14b8f3bff3ed96f59/crates/blockifier/src/concurrency/worker_logic.rs#L27)):*
> ```XML
> use crate::transaction::transactions::ExecutableTransaction;
> 
> const EXECUTION_OUTPUTS_UNWRAP_ERROR: &str = "execution task outpust should not be None.";
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 27 at r25](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-Key_7lCPTeCLPW5W:-Ny-RBU48d4JgnlAThHB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9215eb5ae9c19fcc00676f14b8f3bff3ed96f59/crates/blockifier/src/concurrency/worker_logic.rs#L27)):*
> ```XML
> use crate::transaction::transactions::ExecutableTransaction;
> 
> const EXECUTION_OUTPUTS_UNWRAP_ERROR: &str = "execution task outpust should not be None.";
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 65 at r25](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-IdCwDRql9Hn7Si_p:-Ny-RD-i5f_qGoT2lnlS:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9215eb5ae9c19fcc00676f14b8f3bff3ed96f59/crates/blockifier/src/concurrency/worker_logic.rs#L65)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Add an empty line between scopes.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 72 at r25](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-IkBR86Ydbh3QRtc9:-Ny-RDLNBooX8Zz1rgX5:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9215eb5ae9c19fcc00676f14b8f3bff3ed96f59/crates/blockifier/src/concurrency/worker_logic.rs#L72)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Add an empty line between scopes.
(Also everywhere else there is no empty line.)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 186 at r25](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-LD5G9GLqwFxutLpd:-Ny-REGn1ekp2NCUQ7q-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9215eb5ae9c19fcc00676f14b8f3bff3ed96f59/crates/blockifier/src/concurrency/worker_logic.rs#L186)):*
> ```XML
> 
>             let tx_info =
>                 result_tx_info.as_mut().expect("Transaction info should not be an error here.");
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-05-16 08:13 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 7 of 22 files reviewed, 9 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 89 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Nx7YPxo0xVPeEi2LZZl:-Ny-SeZE88i-ZDj_pX_y:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/31799ab5329cebb41ae2bc5fdb383513bf9dae80/crates/blockifier/src/concurrency/worker_logic.rs#L89)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

In PR https://reviewable.io/reviews/starkware-libs/blockifier/1870
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-16 08:21 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 141 at r25](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-T-jpAa11crJaSBI8:-Ny-T-jpAa11crJaSBI9:bv25ici) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9215eb5ae9c19fcc00676f14b8f3bff3ed96f59/crates/blockifier/src/concurrency/worker_logic.rs#L141)):*
> ```XML
> 
>         let read_set =
>             &execution_task_outputs.as_ref().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR).reads;
> ```

Would it make sense to add a method `get_read_set` and a method `get_tx_execution_info` that accept a `tx_index` and both lock the mutex and return the relevant value (ref for read_set mut for execution_info)?
This would make it a bit more readable and take care of managing the locks (i.e., we won't need `drop`).
@noaov1 what do you think?



_Suggestion:_
```XML
        let read_set =
            &execution_task_outputs.as_ref().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR).reads;`
```


<!-- Sent from Reviewable.io -->

2024-05-16 08:21 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 209 at r25](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-LzAj92iSmGroMGET:-Ny-LzAj92iSmGroMGEU:b-b1dnfn) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9215eb5ae9c19fcc00676f14b8f3bff3ed96f59/crates/blockifier/src/concurrency/worker_logic.rs#L209)):*
> ```XML
>                     sequencer_balance_key_low,
>                     sequencer_balance_value_high,
>                     sequencer_balance_value_low,
> ```

First `low` then `high` - to be consistent with other functions used here (also, the `low` key has a lower address, so it makes sense it would come first).



_Suggestion:_
```XML
                    sequencer_balance_key_low,
                    sequencer_balance_key_high,
                    sequencer_balance_value_low,
                    sequencer_balance_value_high,
```


<!-- Sent from Reviewable.io -->

2024-05-16 08:23 UTC, avi-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 7 of 22 files reviewed, 6 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 141 at r25](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-T-jpAa11crJaSBI8:-Ny-UjZyC8LhzyPCdxLB:b-nhm2h6) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9215eb5ae9c19fcc00676f14b8f3bff3ed96f59/crates/blockifier/src/concurrency/worker_logic.rs#L141)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Would it make sense to add a method `get_read_set` and a method `get_tx_execution_info` that accept a `tx_index` and both lock the mutex and return the relevant value (ref for read_set mut for execution_info)?
This would make it a bit more readable and take care of managing the locks (i.e., we won't need `drop`).
@noaov1 what do you think?
</blockquote></details>

Ignore the ` I added to the end of the line. It is a typo.


<!-- Sent from Reviewable.io -->

2024-05-16 08:23 UTC, avi-starkware reviewed
> Reviewed 7 of 15 files at r3, 10 of 12 files at r19, 2 of 4 files at r20, 1 of 2 files at r23, 1 of 1 files at r25, 1 of 1 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: all files reviewed, 6 unresolved discussions (waiting on @meship-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-05-16 08:38 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 21 of 22 files reviewed, 6 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 209 at r25](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-LzAj92iSmGroMGET:-Ny-XuFr3JCrXk0xzUiO:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9215eb5ae9c19fcc00676f14b8f3bff3ed96f59/crates/blockifier/src/concurrency/worker_logic.rs#L209)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

First `low` then `high` - to be consistent with other functions used here (also, the `low` key has a lower address, so it makes sense it would come first).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-16 08:46 UTC, avi-starkware submitted a review, later dismissed
> Reviewed 1 of 1 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: all files reviewed, 5 unresolved discussions (waiting on @meship-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-05-16 09:45 UTC, noaov1 requested changes
> Reviewed 1 of 1 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: all files reviewed, 12 unresolved discussions (waiting on @avi-starkware and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 122 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-NxRAbj56O4XNtQmSmRM:-Ny-kmLA7KlpaSZaMAxi:b-bmtuj0) ([raw file](https://github.com/starkware-libs/blockifier/blob/63f29c58f40ba1d5238acd5f5a561ac785e64204/crates/blockifier/src/concurrency/worker_logic.rs#L122)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

In case of reverted, we have a transaction execution info as the output (and not an error). It contains the information of the `__validate___` and fee charge execution.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 141 at r25](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-T-jpAa11crJaSBI8:-Ny-egvp4Om1HU9TBERF:b2hplon) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9215eb5ae9c19fcc00676f14b8f3bff3ed96f59/crates/blockifier/src/concurrency/worker_logic.rs#L141)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Ignore the ` I added to the end of the line. It is a typo.
</blockquote></details>

Why would it avoid the `drop`?
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 66 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-dg0v0_ireXAFAdmJ:-Ny-dg0v0_ireXAFAdmK:b659m67) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L66)):*
> ```XML
> }
> 
> pub struct WorkersExecutor<S: StateReader> {
> ```

Why did you add the `s`?



_Code quote:_
```XML
pub struct WorkersExecutor<S: StateReader> {
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 137 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-hthcB-9ZHkrydceo:-Ny-hthcB-9ZHkrydcep:b-ir5t70) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L137)):*
> ```XML
> 
>     pub fn try_commit_transaction(&mut self, tx_index: TxIndex) -> StateResult<bool> {
>         let execution_task_outputs = lock_mutex_in_array(&self.execution_outputs, tx_index);
> ```

Through the entire file. if you find this name not good, please change it in the `execute_tx` method as well.



_Suggestion:_
```XML
        let execution_output = lock_mutex_in_array(&self.execution_outputs, tx_index);
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 147 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-jC0VEZlxcSRRgO28:-Ny-jC0VEZlxcSRRgO29:b-cac809) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L147)):*
> ```XML
>         if !tx_versioned_state.validate_reads(read_set) {
>             // Revalidate failed: re-execute the transaction, and commit.
>             self.block_context =
> ```

Since you are not running the worker executor `validate` method.



_Suggestion:_
```XML
            // Revalidate failed: re-execute the transaction, and commit.
            // TODO(Meshi, 01/06/2024): Delete the transaction writes. 
            self.block_context =
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 148 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-fAJ6B-Uikq0cwLxB:-Ny-fAJ6B-Uikq0cwLxC:bannri1) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L148)):*
> ```XML
>             // Revalidate failed: re-execute the transaction, and commit.
>             self.block_context =
>                 BlockContext { concurrency_mode: false, ..self.block_context.clone() };
> ```

Not good. It is shared between all the threads.
Two options:
1. Run in concurrency mode (need to fix call info and sequencer balance)
2. Add a parameter to the `execute_tx` method that affect the (local) block context.



_Code quote:_
```XML
            self.block_context =
                BlockContext { concurrency_mode: false, ..self.block_context.clone() };
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 155 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-iH1C9f6dagoBiFUf:-Ny-iH1C9f6dagoBiFUg:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L155)):*
> ```XML
>                 &mut execution_task_outputs.as_mut().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR).result;
>             if result_tx_info.is_err() {
>                 // Transaction rejected.
> ```





_Suggestion:_
```XML
                // Transaction failed.
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 157 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-iTgt4DmrOBu9U7rQ:-Ny-iTgt4DmrOBu9U7rR:bdgzfxs) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L157)):*
> ```XML
>                 // Transaction rejected.
>                 // TODO(Meshi, 01/06/2024): Rvert the chanches of the execution before the
>                 // re-execution.
> ```

WDYM? Note that if the execution failed, we do not apply the writes. 



_Code quote:_
```XML
                // TODO(Meshi, 01/06/2024): Rvert the chanches of the execution before the
                // re-execution.
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 158 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-jkc3EfTmSIstzrlc:-Ny-jkc3EfTmSIstzrld:btbr654) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L158)):*
> ```XML
>                 // TODO(Meshi, 01/06/2024): Rvert the chanches of the execution before the
>                 // re-execution.
>                 todo!()
> ```

What should be done here?



_Code quote:_
```XML
                todo!()
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 169 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-kBCJ1lEd8Wsliz3J:-Ny-kBCJ1lEd8Wsliz3K:bwqu31t) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L169)):*
> ```XML
> 
>         // Revalidate succeeded.
>         drop(execution_task_outputs);
> ```

Consider dropping it after you finish validate the read set above (you can store the result in a variable)



_Code quote:_
```XML
        drop(execution_task_outputs);
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 173 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-lT2M2R4dUiQyl1l5:-Ny-lT2M2R4dUiQyl1l6:b-glz8xc) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L173)):*
> ```XML
>         let result_tx_info =
>             &mut execution_task_outputs.as_mut().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR).result;
>         if result_tx_info.is_err() {
> ```

Please use `if let` (that way, you can avoid the expect below)



_Code quote:_
```XML
 if result_tx_info.is_err() {
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 174 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-kUMR9XiOGFsQQWxW:-Ny-kUMR9XiOGFsQQWxX:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a1 [...]

2024-05-16 09:46 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 141 at r25](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-T-jpAa11crJaSBI8:-Ny-mjQX0E97OmAtfXBC:b-5tpbf9) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9215eb5ae9c19fcc00676f14b8f3bff3ed96f59/crates/blockifier/src/concurrency/worker_logic.rs#L141)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why would it avoid the `drop`?
</blockquote></details>

I suggested the method will also take the lock on the mutex, so once the method ends the lock goes out of scope and gets dropped automatically.


<!-- Sent from Reviewable.io -->

2024-05-16 09:48 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 148 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-fAJ6B-Uikq0cwLxB:-Ny-nCFI7--TE3CHgTFZ:bf86h4h) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L148)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Not good. It is shared between all the threads.
Two options:
1. Run in concurrency mode (need to fix call info and sequencer balance)
2. Add a parameter to the `execute_tx` method that affect the (local) block context.
</blockquote></details>

Why would the concurrency_mode change in the worker logic? Shouldn't it be set in the executor?


<!-- Sent from Reviewable.io -->

2024-05-16 09:52 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 155 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-iH1C9f6dagoBiFUf:-Ny-nbsS1ueAdI-jnMzm:bn2e8x9) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L155)):*
> ```XML
>                 &mut execution_task_outputs.as_mut().expect(EXECUTION_OUTPUTS_UNWRAP_ERROR).result;
>             if result_tx_info.is_err() {
>                 // Transaction rejected.
> ```

I think the distinction here is important. Failed could mean either rejected or reverted. This flow is only reached when the transaction is rejected, not when it is reverted, so why not be explicit about it in the comment?


<!-- Sent from Reviewable.io -->

2024-05-16 10:12 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 21 of 22 files reviewed, 12 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 66 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-dg0v0_ireXAFAdmJ:-Ny-sbEP3sQb_N-rLsTV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L66)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why did you add the `s`?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 147 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-jC0VEZlxcSRRgO28:-Ny-sYcX6IRKFADDgV-Q:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L147)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Since you are not running the worker executor `validate` method.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 148 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-fAJ6B-Uikq0cwLxB:-Ny-ptCOAonqcSO_kHIW:b-jn13wl) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L148)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Why would the concurrency_mode change in the worker logic? Shouldn't it be set in the executor?
</blockquote></details>

The reason we want to change the concurrency mode here is to avoid fixing the call info and sequencer balance after re-execution. I think we should go for option 1 now and many rethink it later.    
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 157 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-iTgt4DmrOBu9U7rQ:-Ny-n0-s2DIWy4jOyOvH:bdc4nqk) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L157)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM? Note that if the execution failed, we do not apply the writes.
</blockquote></details>

// TODO(Meshi, 01/06/2024): Delete the transaction writes. this is what I meant but if we do this but we do this even if the execution succussed  so its irrelevant. 
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 158 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-jkc3EfTmSIstzrlc:-Ny-pMyG0tm_AlXg5YcJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L158)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What should be done here?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 169 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-kBCJ1lEd8Wsliz3J:-Ny-qPHm4oiBli0OdjAi:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L169)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider dropping it after you finish validate the read set above (you can store the result in a variable)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 173 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-lT2M2R4dUiQyl1l5:-Ny-rGtG7ZCpVZFk5PYV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L173)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please use `if let` (that way, you can avoid the expect below)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-16 10:18 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 141 at r25](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-T-jpAa11crJaSBI8:-Ny-u7Bz77LQ090Zy3jV:b-v0wk3) ([raw file](https://github.com/starkware-libs/blockifier/blob/f9215eb5ae9c19fcc00676f14b8f3bff3ed96f59/crates/blockifier/src/concurrency/worker_logic.rs#L141)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can we release the lock while still holding a (mutable) reference to it?
</blockquote></details>

We can't... :facepalm: 


<!-- Sent from Reviewable.io -->

2024-05-16 10:24 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 155 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-iH1C9f6dagoBiFUf:-Ny-urQXD7PP3bj_2fuq:b-6967un) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L155)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I am not familiar with associating reverted with failed. I think that failed is more explicit, but it's just a suggestion.
What does it mean rejected?
</blockquote></details>

Rejected means the transaction failed `__validate__`, so we are not going to charge fee for it nor include it in a block. Reverted means the transaction failed during `__execute__`, so we are going to charge fee and include it in a block. "Failed" could mean either of the two, but in this flow we don't include reverted transactions, only rejected.


<!-- Sent from Reviewable.io -->

2024-05-16 10:38 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 148 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-fAJ6B-Uikq0cwLxB:-Ny-uUovCa8OcTd-Bxij:b-x86qot) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L148)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

The reason we want to change the concurrency mode here is to avoid fixing the call info and sequencer balance after re-execution. I think we should go for option 1 now and many rethink it later.
</blockquote></details>

Option 1 simply means we need to not return at the end of this scope right?
Just move on to the final part of this method where we update the sequencer balance?
If so, it sounds good.


<!-- Sent from Reviewable.io -->

2024-05-16 11:13 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 173 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-lT2M2R4dUiQyl1l5:-Ny02tGxA5wyx9uJtucw:bkvncv1) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L173)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I meant with an `else` (including the error case)
</blockquote></details>

I think that we can ignore the else 
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 136 at r30](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-zY90EpJ_98mwyoEC:-Ny04W-d-NFz_fqgJm7G:b-7h4ga4) ([raw file](https://github.com/starkware-libs/blockifier/blob/490c7f9ae2df0218f065f7f61f11e614e383d474/crates/blockifier/src/concurrency/worker_logic.rs#L136)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please add a documentation that explains the try commit flow:
</blockquote></details>

We wanted to question the bouncer before fixing the call info and updating the sequencer balance, right? It's more like the flow needs to be as flow. If there is not enough space in the bouncer, then return false. If there is enough space but this transaction is too big, then fix all the values and return false.  


<!-- Sent from Reviewable.io -->

2024-05-16 11:23 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 21 of 22 files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 148 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-fAJ6B-Uikq0cwLxB:-Ny081-NDDYlSPeIOR08:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L148)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Option 1 simply means we need to not return at the end of this scope right?
Just move on to the final part of this method where we update the sequencer balance?
If so, it sounds good.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 136 at r30](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-zY90EpJ_98mwyoEC:-Ny07qz9B1JeTvJRd09j:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/490c7f9ae2df0218f065f7f61f11e614e383d474/crates/blockifier/src/concurrency/worker_logic.rs#L136)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

We wanted to question the bouncer before fixing the call info and updating the sequencer balance, right? It's more like the flow needs to be as flow. If there is not enough space in the bouncer, then return false. If there is enough space but this transaction is too big, then fix all the values and return false.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 157 at r30](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny00CMRBgkU40LgdNmA:-Ny06zbi1YTAuEXXytbB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/490c7f9ae2df0218f065f7f61f11e614e383d474/crates/blockifier/src/concurrency/worker_logic.rs#L157)):*
> ```XML
>         }
> 
>         // Revalidate succeeded.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-05-16 11:26 UTC, noaov1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 21 of 22 files reviewed, 3 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 173 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-lT2M2R4dUiQyl1l5:-Ny087ox6lyG6hCKFfUo:b-nd097s) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L173)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I think that we can ignore the else
</blockquote></details>

Why? In case of an error we want to return true, no?
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 136 at r30](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-zY90EpJ_98mwyoEC:-Ny07mUf6hhoj0MQuxuR:bn9won8) ([raw file](https://github.com/starkware-libs/blockifier/blob/490c7f9ae2df0218f065f7f61f11e614e383d474/crates/blockifier/src/concurrency/worker_logic.rs#L136)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You are right. We don't need the execution info in case the transaction has no room in the block.  
If the transaction is too big then we should store the error in the result field (and not fixing the call info).


<!-- Sent from Reviewable.io -->

2024-05-16 11:27 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 21 of 22 files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 173 at r27](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-lT2M2R4dUiQyl1l5:-Ny09-lfCetzWkndmSE8:b-abae0j) ([raw file](https://github.com/starkware-libs/blockifier/blob/614f0bdc56aca4f9b9c7d7b6339a93c5a13dbc4b/crates/blockifier/src/concurrency/worker_logic.rs#L173)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why? In case of an error we want to return true, no?
</blockquote></details>

Yes but we return true at the end anyway


<!-- Sent from Reviewable.io -->

2024-05-16 11:29 UTC, noaov1 reviewed
> Reviewed 10 of 12 files at r19, 2 of 4 files at r20, 1 of 2 files at r23, 1 of 1 files at r25, 1 of 1 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-05-16 11:35 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 136 at r30](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-zY90EpJ_98mwyoEC:-Ny0Ankg3OMSsQLfPHRA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/490c7f9ae2df0218f065f7f61f11e614e383d474/crates/blockifier/src/concurrency/worker_logic.rs#L136)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

You are right. We don't need the execution info in case the transaction has no room in the block.  
If the transaction is too big then we should store the error in the result field (and not fixing the call info).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-16 12:26 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843)* status: 21 of 22 files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 136 at r30](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny-zY90EpJ_98mwyoEC:-Ny0MQOU-DtzRhsvFRfE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/490c7f9ae2df0218f065f7f61f11e614e383d474/crates/blockifier/src/concurrency/worker_logic.rs#L136)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Also the TODO (only in case of success)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 143 at r32](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-Ny0BbljDpTlDnrYQP_c:-Ny0MPYo4k61ELSaRcBL:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/146cf6d6bd27a55028810f8d6f52d4fc06355262/crates/blockifier/src/concurrency/worker_logic.rs#L143)):*
> ```XML
>     /// Only if there is room we commit the transaction.
>     /// If execution failed, this transaction is considered commited.
>     /// Else, we fix the call info and update the sequencer balance.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-05-16 12:28 UTC, noaov1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r33, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1843#-:-Ny0MtVI33k0Ot7AADyF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-05-16 12:28 UTC, merged