refactor(concurrency): add declared_contracts to versioned_state
starkware-libs/blockifier pull request #1887
Opened 2024-05-08 12:01 UTC by OriStarkware

2024-05-16 12:24 UTC, barak-b-starkware requested changes
1. Rebase over [delete_writes PR](https://github.com/starkware-libs/blockifier/pull/1892) and add the last `for` loop.
2. Add a test (:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-:-Ny0HGKb5M5kZHjLr-G5:b38euei)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 146 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny0JcQZ3zm6fh25-SLP:-Ny0JcQZ3zm6fh25-SLQ:b-fi5sg1) ([raw file](https://github.com/starkware-libs/blockifier/blob/9243b84c8cb46822f081715e0fd3b5787aa8aa78/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L146)):*
> ```XML
>         for (&key, &value) in &writes.declared_contracts {
>             self.declared_contracts.write(tx_index, key, value);
>         }
> ```

I'm unsure if we want to panic here or propagate an error (and then change the return type), but the invariant you've mentioned near the struct member should be checked somehow. For example:

It's worth thinking about — where do we want to check it? `validate_read_set`, `apply_writes`, `delete_writes`, or any combination of the three?



_Suggestion:_
```XML
        for (&key, &value) in &writes.declared_contracts {
            self.declared_contracts.write(tx_index, key, value);
            assert_eq!(self.compiled_contract_classes.get_writes_from_index(tx_index).contains_key(&key), value)
        }
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 238 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny0Ljyv3n9JKggHz1PQ:-Ny0Ljyv3n9JKggHz1PR:b-38kvoc) ([raw file](https://github.com/starkware-libs/blockifier/blob/9243b84c8cb46822f081715e0fd3b5787aa8aa78/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L238)):*
> ```XML
>     }
> 
>     fn get_compiled_contract_class(&self, class_hash: ClassHash) -> StateResult<ContractClass> {
> ```

What about other implementations of this method? In the `CachedState`, for example, or somewhere else?
Nothing should be changed?



_Code quote:_
```XML
fn get_compiled_contract_class(&self, class_hash: ClassHash) -> StateResult<ContractClass> {
```


<!-- Sent from Reviewable.io -->

2024-05-16 19:17 UTC, noaov1 requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny1oAbt0x6br6mmqkMb:-Ny1oAbuAa1sE83QmGWe:bzqrb5) ([raw file](https://github.com/starkware-libs/blockifier/blob/9243b84c8cb46822f081715e0fd3b5787aa8aa78/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L244)):*
> ```XML
>             None => match state.initial_state.get_compiled_contract_class(class_hash) {
>                 Ok(initial_value) => {
>                     state.declared_contracts.set_initial_value(class_hash, true);
> ```

We want it to be versioned.



_Suggestion:_
```XML
state.declared_contracts.write(tx_index, class_hash, true);
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 251 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny1oeyo0I1Xk9f3ycIy:-Ny1oeyo0I1Xk9f3ycIz:b-eobmds) ([raw file](https://github.com/starkware-libs/blockifier/blob/9243b84c8cb46822f081715e0fd3b5787aa8aa78/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L251)):*
> ```XML
>                 }
>                 Err(StateError::UndeclaredClassHash(class_hash)) => {
>                     state.declared_contracts.set_initial_value(class_hash, false);
> ```

I'm wondering if we need it in the initial value as well



_Suggestion:_
```XML
                    state.declared_contracts.write(tx_index, class_hash, false);
```


<!-- Sent from Reviewable.io -->

2024-05-19 08:51 UTC, noaov1 reviewed
Sounds good.
Please add tests to versioned state proxy test (you can use the existing tests)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-:-NyEzYNM33yrtSP-4PhO:b-qp7ds1)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @OriStarkware, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-05-19 12:55 UTC, barak-b-starkware submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887)* status: all files reviewed, 2 unresolved discussions (waiting on @OriStarkware and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-05-20 14:23 UTC, OriStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny1oAbt0x6br6mmqkMb:-NyKY7nBBAzGlHvvmMVV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9243b84c8cb46822f081715e0fd3b5787aa8aa78/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L244)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

We want it to be versioned.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 251 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny1oeyo0I1Xk9f3ycIy:-NyKY86F3ZLUAzRVf8Zt:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9243b84c8cb46822f081715e0fd3b5787aa8aa78/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L251)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I'm wondering if we need it in the initial value as well
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 16:33 UTC, noaov1 reviewed
> Reviewed 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-05-21 07:38 UTC, noaov1 requested changes
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @OriStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 33 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyOsYZLAf1rX7HUVv4M:-NyOsYZLAf1rX7HUVv4N:bj2d96c) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe3d6c6a90d912ac1d61a1aa0bc09c2d03404aea/crates/blockifier/src/concurrency/versioned_state.rs#L33)):*
> ```XML
>     // For each key in declared_contracts with value True, the key have to appear in
>     // compiled_contract_classes. For each key in declared_contracts with value False, the key
>     // sohuld not apprear in compiled_contract_classes.
> ```

I prefer to avoid fields(+structs) names in documentation (it adds "garbage" to searches)



_Suggestion:_
```XML
    // Invariant: each key in this mapping with value equals true, appears in also in
    // the compiled contract classes mapping. Each key with value false, sohuld not apprear 
    // in the compiled contract classes mapping.
```
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 162 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyOtV_624rd-EWisjeH:-NyOtV_624rd-EWisjeI:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe3d6c6a90d912ac1d61a1aa0bc09c2d03404aea/crates/blockifier/src/concurrency/versioned_state.rs#L162)):*
> ```XML
>             assert_eq!(
>                 value,
>                 self.compiled_contract_classes.get_writes_up_to_index(tx_index).contains_key(&key)
> ```





_Suggestion:_
```XML
self.compiled_class_hashes.read(tx_index, class_hash).expect(READ_ERR).is_some();
```


<!-- Sent from Reviewable.io -->

2024-05-21 09:11 UTC, noaov1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @OriStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 162 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyOtV_624rd-EWisjeH:-NyPMzdn7BVsdd_zNxv8:bz0a92l) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe3d6c6a90d912ac1d61a1aa0bc09c2d03404aea/crates/blockifier/src/concurrency/versioned_state.rs#L162)):*
> ```XML
>             assert_eq!(
>                 value,
>                 self.compiled_contract_classes.get_writes_up_to_index(tx_index).contains_key(&key)
> ```

I meant 



_Code snippet:_
```XML
self.compiled_contract_classes.read(tx_index, class_hash).expect(READ_ERR).is_some();
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyPG1hj5gtjeM_PUNkp:-NyPG1hk98nNl7LoMmJS:b-ojcazl) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe3d6c6a90d912ac1d61a1aa0bc09c2d03404aea/crates/blockifier/src/concurrency/versioned_state_test.rs#L75)):*
> ```XML
>         (0..20).map(|i| safe_versioned_state.pin_version(i)).collect();
> 
>     versioned_state_proxys[0].state().declared_contracts.set_initial_value(class_hash, true);
> ```

Why is it needed?
It will be added in the call to `get_compiled_contract_class`, no?



_Code quote:_
```XML
    versioned_state_proxys[0].state().declared_contracts.set_initial_value(class_hash, true);
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 79 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyPNbG2C3olQajpAuYb:-NyPNbG39JWtCab6tVdM:b2g6gk1) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe3d6c6a90d912ac1d61a1aa0bc09c2d03404aea/crates/blockifier/src/concurrency/versioned_state_test.rs#L79)):*
> ```XML
>         .state()
>         .declared_contracts
>         .set_initial_value(undeclared_class_hash, false);
> ```

Consider making sure you get ` Err(StateError::UndeclaredClassHash(undeclared_class_hash))`



_Suggestion:_
```XML
versioned_state_proxys[7].get_compiled_contract_class(undeclared_class_hash).unwrap_err();
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 118 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyPNU17-dOE-2oO9dWb:-NyPNU17-dOE-2oO9dWc:b-fcsbmw) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe3d6c6a90d912ac1d61a1aa0bc09c2d03404aea/crates/blockifier/src/concurrency/versioned_state_test.rs#L118)):*
> ```XML
>             .read(7, undeclared_class_hash)
>             .unwrap()
>     );
> ```

I think that checking in 0 only is enough. 



_Suggestion:_
```XML
    assert!(
        !versioned_state_proxys[0]
            .state()
            .declared_contracts
            .read(0, undeclared_class_hash)
            .unwrap()
    );
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 133 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyPOuTt6if0Ad1eJuRi:-NyPOuTuB2B5rh92MBGn:b-khr9an) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe3d6c6a90d912ac1d61a1aa0bc09c2d03404aea/crates/blockifier/src/concurrency/versioned_state_test.rs#L133)):*
> ```XML
>         undeclared_class_hash,
>         contract_class.clone(),
>     );
> ```

Please add it to the apply writes below and use a different contract class (it is already declared :))



_Code quote:_
```XML
    versioned_state_proxys[3].state().compiled_contract_classes.write(
        3,
        undeclared_class_hash,
        contract_class.clone(),
    );
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 221 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyPPh0q5fhXBoJoSFaZ:-NyPPh0q5fhXBoJoSFa_:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe3d6c6a90d912ac1d61a1aa0bc09c2d03404aea/crates/blockifier/src/concurrency/versioned_state_test.rs#L221)):*
> ```XML
>             .read(7, undeclared_class_hash)
>             .unwrap()
>     );
> ```





_Suggestion:_
```XML
    assert!(
        !versioned_state_proxys[0]
            .state()
            .declared_contracts
            .read(0, undeclared_class_hash)
            .unwrap()
    );
    assert!(
        versioned_state_proxys[4]
            .state()
            .declared_contracts
            .read(4, undeclared_class_hash)
            .unwrap()
    );
```


<!-- Sent from Reviewable.io -->

2024-05-21 10:08 UTC, noaov1 requested changes
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887)* status: all files reviewed, 9 unresolved discussions (waiting on @OriStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 403 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyPaqdW5wv7GGQaqAuD:-NyPaqdW5wv7GGQaqAuE:b-t2sdlj) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe3d6c6a90d912ac1d61a1aa0bc09c2d03404aea/crates/blockifier/src/concurrency/versioned_state_test.rs#L403)):*
> ```XML
>             .get(&class_hash)
>             .unwrap()
>     );
> ```

Note that we want to test the field in the versioned state. Consider adding a getter for testing. 



_Code quote:_
```XML
    assert!(
        transactional_states[1]
            .cache
            .borrow()
            .initial_reads
            .declared_contracts
            .get(&class_hash)
            .unwrap()
    );
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 510 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyPbkKt1LopMiKcikOI:-NyPbkKt1LopMiKcikOJ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe3d6c6a90d912ac1d61a1aa0bc09c2d03404aea/crates/blockifier/src/concurrency/versioned_state_test.rs#L510)):*
> ```XML
>         )]),
>         compiled_class_hashes: HashMap::from([(class_hash!("0x1"), compiled_class_hash!("0x1"))]),
>         declared_contracts: HashMap::from([(class_hash!("0x1"), false)]),
> ```





_Suggestion:_
```XML
        compiled_class_hashes: HashMap::from([(feature_contract.get_class_hash(), compiled_class_hash!("0x1"))]),
        declared_contracts: HashMap::from([(feature_contract.get_class_hash(), true)]),
```


<!-- Sent from Reviewable.io -->

2024-05-22 12:52 UTC, OriStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887)* status: 2 of 4 files reviewed, 8 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyPG1hj5gtjeM_PUNkp:-NyVJXGl9T_euZIy2rcw:bss4a2b) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe3d6c6a90d912ac1d61a1aa0bc09c2d03404aea/crates/blockifier/src/concurrency/versioned_state_test.rs#L75)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it needed?
It will be added in the call to `get_compiled_contract_class`, no?
</blockquote></details>

Removed.
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 79 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyPNbG2C3olQajpAuYb:-NyVJZXD894TDfLOWU4E:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe3d6c6a90d912ac1d61a1aa0bc09c2d03404aea/crates/blockifier/src/concurrency/versioned_state_test.rs#L79)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider making sure you get ` Err(StateError::UndeclaredClassHash(undeclared_class_hash))`
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 118 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyPNU17-dOE-2oO9dWb:-NyVJgPi5wSo_SpWwjHx:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe3d6c6a90d912ac1d61a1aa0bc09c2d03404aea/crates/blockifier/src/concurrency/versioned_state_test.rs#L118)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think that checking in 0 only is enough.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-22 13:08 UTC, noaov1 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @OriStarkware and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-05-22 13:47 UTC, noaov1 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @OriStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 162 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyOtV_624rd-EWisjeH:-NyVWnRUBBAXDRZHjyNS:bgrlg60) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe3d6c6a90d912ac1d61a1aa0bc09c2d03404aea/crates/blockifier/src/concurrency/versioned_state.rs#L162)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I meant
</blockquote></details>

Sorry, last edit:



_Code snippet:_
```XML
// Reads the write made by the current transaction.
self.compiled_contract_classes.read(tx_index + 1, class_hash).is_some()
```


<!-- Sent from Reviewable.io -->

2024-05-22 13:57 UTC, OriStarkware reviewed
Done.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-:-NyVQ3Sd-LmVcVaLkEJD:b-896fix)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 162 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyOtV_624rd-EWisjeH:-NyVZsGX7g37ftCicIUs:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe3d6c6a90d912ac1d61a1aa0bc09c2d03404aea/crates/blockifier/src/concurrency/versioned_state.rs#L162)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Sorry, last edit:
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 133 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyPOuTt6if0Ad1eJuRi:-NyVZjbP8DiDToPGXJHA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe3d6c6a90d912ac1d61a1aa0bc09c2d03404aea/crates/blockifier/src/concurrency/versioned_state_test.rs#L133)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please add it to the apply writes below and use a different contract class (it is already declared :))
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 403 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyPaqdW5wv7GGQaqAuD:-NyVXnYd29P1kn-73cGt:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fe3d6c6a90d912ac1d61a1aa0bc09c2d03404aea/crates/blockifier/src/concurrency/versioned_state_test.rs#L403)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Note that we want to test the field in the versioned state. Consider adding a getter for testing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-22 15:43 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @noaov1 and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 291 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyVwbPE2LrjJy7Y71md:-NyVwbPE2LrjJy7Y71me:bmoigr2) ([raw file](https://github.com/starkware-libs/blockifier/blob/adb52f6497721f76cf70b4d141aa367e8f8f5825/crates/blockifier/src/concurrency/versioned_state.rs#L291)):*
> ```XML
>             Some(value) => {
>                 state.declared_contracts.write(self.tx_index, class_hash, true);
>                 Ok(value)
> ```

You cannot write in a read method; you can only cache the previous read. 
`write` means that the tx is declaring a contract.



_Suggestion:_
```XML
            Some(value) => {
                Ok(value)
```
___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 306 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyVxNdS0YAW6S8MTglj:-NyVxNdS0YAW6S8MTglk:b-pb2auq) ([raw file](https://github.com/starkware-libs/blockifier/blob/adb52f6497721f76cf70b4d141aa367e8f8f5825/crates/blockifier/src/concurrency/versioned_state.rs#L306)):*
> ```XML
>                 }
>                 Err(error) => Err(error)?,
>             },
> ```

Simpler (and equivalent) I think



_Suggestion:_
```XML
            None => {
                let initial_value = state.initial_state.get_compiled_contract_class(class_hash)?;
                state
                    .compiled_contract_classes
                    .set_initial_value(class_hash, initial_value.clone());
                state.declared_contracts.set_initial_value(class_hash, true);
                Ok(initial_value)
            }
```


<!-- Sent from Reviewable.io -->

2024-05-22 15:46 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 306 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyVxNdS0YAW6S8MTglj:-NyVye-P4lKP0U6eZ4Zq:b1g8vnn) ([raw file](https://github.com/starkware-libs/blockifier/blob/adb52f6497721f76cf70b4d141aa367e8f8f5825/crates/blockifier/src/concurrency/versioned_state.rs#L306)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Simpler (and equivalent) I think
</blockquote></details>

Sorry, you are right


<!-- Sent from Reviewable.io -->

2024-05-23 08:10 UTC, OriStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state.rs` line 291 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyVwbPE2LrjJy7Y71md:-NyZUs4c6gmkppeVXJtR:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/adb52f6497721f76cf70b4d141aa367e8f8f5825/crates/blockifier/src/concurrency/versioned_state.rs#L291)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

You cannot write in a read method; you can only cache the previous read. 
`write` means that the tx is declaring a contract.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-23 11:16 UTC, noaov1 reviewed
> Reviewed 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887)* status: all files reviewed, 6 unresolved discussions (waiting on @OriStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 82 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny_8miC-eH901hFFST6:-Ny_8miC-eH901hFFST7:bgqg1nd) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f92ddde8eb8d6988e00925301cc1fbff8ac0f43/crates/blockifier/src/concurrency/versioned_state_test.rs#L82)):*
> ```XML
>         StateError::UndeclaredClassHash(class_hash) if
>         another_class_hash == class_hash
>     );
> ```

Please move near the `declared_contracts` check.



_Code quote:_
```XML
    assert_matches!(
        versioned_state_proxys[7].get_compiled_contract_class(another_class_hash).unwrap_err(),
        StateError::UndeclaredClassHash(class_hash) if
        another_class_hash == class_hash
    );
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 175 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyZp13f-q7ucMb2ViMT:-NyZp13f-q7ucMb2ViMU:b-fq6oay) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f92ddde8eb8d6988e00925301cc1fbff8ac0f43/crates/blockifier/src/concurrency/versioned_state_test.rs#L175)):*
> ```XML
>     );
>     assert!(
>         versioned_state_proxys[4].state().declared_contracts.read(4, another_class_hash).unwrap()
> ```

Personal preference



_Suggestion:_
```XML
    assert_eq!(
        versioned_state_proxys[0].state().declared_contracts.read(0, another_class_hash).unwrap(), false
    );
    assert_eq!(
        versioned_state_proxys[4].state().declared_contracts.read(4, another_class_hash).unwrap(), true
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 360 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny_95JTE1zfojAYvygk:-Ny_95JTE1zfojAYvygl:b-etcl40) ([raw file](https://github.com/starkware-libs/blockifier/blob/ee8e9bd45d49e709e1e47aa2ecc7a1bb5aebcecf/crates/blockifier/src/concurrency/versioned_state_test.rs#L360)):*
> ```XML
>             .get(&class_hash)
>             .unwrap()
>     );
> ```

What do you test here?



_Code quote:_
```XML
    assert!(
        transactional_states[1]
            .cache
            .borrow()
            .initial_reads
            .declared_contracts
            .get(&class_hash)
            .unwrap()
    );
```
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 470 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny_9D0H7UVYmZ6uiB6X:-Ny_9D0H7UVYmZ6uiB6Y:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/ee8e9bd45d49e709e1e47aa2ecc7a1bb5aebcecf/crates/blockifier/src/concurrency/versioned_state_test.rs#L470)):*
> ```XML
>         )]),
>         compiled_class_hashes: HashMap::from([(class_hash!("0x1"), compiled_class_hash!("0x1"))]),
>         declared_contracts: HashMap::from([(class_hash!("0x2"), false)]),
> ```

?



_Suggestion:_
```XML
declared_contracts: HashMap::from([(class_hash!("0x1"), true)]),
```
___
*[`crates/blockifier/src/test_utils/dict_state_reader.rs` line 20 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny_8faBCJX7KOTbqmXy:-Ny_8faBCJX7KOTbqmXz:bhjqkge) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f92ddde8eb8d6988e00925301cc1fbff8ac0f43/crates/blockifier/src/test_utils/dict_state_reader.rs#L20)):*
> ```XML
>     pub class_hash_to_class: HashMap<ClassHash, ContractClass>,
>     pub class_hash_to_compiled_class_hash: HashMap<ClassHash, CompiledClassHash>,
>     pub declared_contracts: HashMap<ClassHash, bool>,
> ```

Why is it needed?



_Code quote:_
```XML
    pub declared_contracts: HashMap<ClassHash, bool>,
```


<!-- Sent from Reviewable.io -->

2024-05-23 11:35 UTC, OriStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 82 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny_8miC-eH901hFFST6:-Ny_BJmE4B3jxWgMuF4L:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f92ddde8eb8d6988e00925301cc1fbff8ac0f43/crates/blockifier/src/concurrency/versioned_state_test.rs#L82)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please move near the `declared_contracts` check.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 175 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyZp13f-q7ucMb2ViMT:-Ny_DidqDuqFKyraki3i:btlz3rn) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f92ddde8eb8d6988e00925301cc1fbff8ac0f43/crates/blockifier/src/concurrency/versioned_state_test.rs#L175)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Personal preference
</blockquote></details>

The compiler says that this is the shorter, more elegant way. Should I change it anyway?
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 360 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny_95JTE1zfojAYvygk:-Ny_CupI6o_mXkKj6fQZ:bkcznko) ([raw file](https://github.com/starkware-libs/blockifier/blob/ee8e9bd45d49e709e1e47aa2ecc7a1bb5aebcecf/crates/blockifier/src/concurrency/versioned_state_test.rs#L360)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What do you test here?
</blockquote></details>

We check that after the get_compiled_contract_class, the class appears with a true value in the declared_contracts mapping.
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 470 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny_9D0H7UVYmZ6uiB6X:-Ny_C_vY4ZPp3ifrEEZN:b-n4x4l6) ([raw file](https://github.com/starkware-libs/blockifier/blob/ee8e9bd45d49e709e1e47aa2ecc7a1bb5aebcecf/crates/blockifier/src/concurrency/versioned_state_test.rs#L470)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

?
</blockquote></details>

fature_contract is the one that should be set to true.
___
*[`crates/blockifier/src/test_utils/dict_state_reader.rs` line 20 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny_8faBCJX7KOTbqmXy:-Ny_Clg5C6iqVbAJQczM:b7fal1q) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f92ddde8eb8d6988e00925301cc1fbff8ac0f43/crates/blockifier/src/test_utils/dict_state_reader.rs#L20)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it needed?
</blockquote></details>

We need this to test declared _contracts in test_versioned_state_proxy.


<!-- Sent from Reviewable.io -->

2024-05-23 12:30 UTC, noaov1 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @OriStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 175 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-NyZp13f-q7ucMb2ViMT:-Ny_QE04-OOeu2aNa5vN:br6rrro) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f92ddde8eb8d6988e00925301cc1fbff8ac0f43/crates/blockifier/src/concurrency/versioned_state_test.rs#L175)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

The compiler says that this is the shorter, more elegant way. Should I change it anyway?
</blockquote></details>

Nope :)
___
*[`crates/blockifier/src/test_utils/dict_state_reader.rs` line 20 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny_8faBCJX7KOTbqmXy:-Ny_QPOTBXywFdXSUbCY:bc5oawm) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f92ddde8eb8d6988e00925301cc1fbff8ac0f43/crates/blockifier/src/test_utils/dict_state_reader.rs#L20)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

We need this to test declared _contracts in test_versioned_state_proxy.
</blockquote></details>

Please elaborate


<!-- Sent from Reviewable.io -->

2024-05-23 14:33 UTC, Yoni-Starkware approved these changes
Unblocking - but didn't review all files

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-:-Ny_rZglBesI8e7fQ766:b-6u3g17)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @noaov1 and @OriStarkware)



<!-- Sent from Reviewable.io -->

2024-05-24 13:17 UTC, noaov1 requested changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887)* status: all files reviewed, 4 unresolved discussions (waiting on @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 360 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny_95JTE1zfojAYvygk:-Nyejcgw1ZcssPGYVzbd:by8rh3w) ([raw file](https://github.com/starkware-libs/blockifier/blob/ee8e9bd45d49e709e1e47aa2ecc7a1bb5aebcecf/crates/blockifier/src/concurrency/versioned_state_test.rs#L360)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

We check that after the get_compiled_contract_class, the class appears with a true value in the declared_contracts mapping.
</blockquote></details>

I think it is a test for the `CcahedState` struct. 
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 470 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny_9D0H7UVYmZ6uiB6X:-Nyeie-29hbDyCfhR_28:bps6zbe) ([raw file](https://github.com/starkware-libs/blockifier/blob/ee8e9bd45d49e709e1e47aa2ecc7a1bb5aebcecf/crates/blockifier/src/concurrency/versioned_state_test.rs#L470)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

fature_contract is the one that should be set to true.
</blockquote></details>

There is an inconsistency between the different fields. 
You have a declared contract `feature_contract` with some class hash.
It does not appear in the `compiled_class_hashes`. It is possible if it was a cairo0 contract, but even if so, what is the contract that appear there (and deployed)?


<!-- Sent from Reviewable.io -->

2024-05-26 08:31 UTC, OriStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 360 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny_95JTE1zfojAYvygk:-Nynnc3d9gxaDHm-eRDJ:ba3dfob) ([raw file](https://github.com/starkware-libs/blockifier/blob/ee8e9bd45d49e709e1e47aa2ecc7a1bb5aebcecf/crates/blockifier/src/concurrency/versioned_state_test.rs#L360)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think it is a test for the `CcahedState` struct.
</blockquote></details>

Removed
___
*[`crates/blockifier/src/concurrency/versioned_state_test.rs` line 470 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny_9D0H7UVYmZ6uiB6X:-NynvsED9TepyVigFsy3:b-3pmbrk) ([raw file](https://github.com/starkware-libs/blockifier/blob/ee8e9bd45d49e709e1e47aa2ecc7a1bb5aebcecf/crates/blockifier/src/concurrency/versioned_state_test.rs#L470)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

There is an inconsistency between the different fields. 
You have a declared contract `feature_contract` with some class hash.
It does not appear in the `compiled_class_hashes`. It is possible if it was a cairo0 contract, but even if so, what is the contract that appear there (and deployed)?
</blockquote></details>

As requested, changed class_hash!("0x1") to feature_contract.get_class_hash().
___
*[`crates/blockifier/src/test_utils/dict_state_reader.rs` line 20 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-Ny_8faBCJX7KOTbqmXy:-Nyo0DHd7E2cPfTyMLng:ba3dfob) ([raw file](https://github.com/starkware-libs/blockifier/blob/1f92ddde8eb8d6988e00925301cc1fbff8ac0f43/crates/blockifier/src/test_utils/dict_state_reader.rs#L20)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please elaborate
</blockquote></details>

Removed


<!-- Sent from Reviewable.io -->

2024-05-26 08:43 UTC, noaov1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-:-Nyo3Qbj8KhjIgdAbwa0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)



<!-- Sent from Reviewable.io -->

2024-05-26 08:48 UTC, merged