feat(concurrency): delete writes
starkware-libs/blockifier pull request #1892
Opened 2024-05-09 10:03 UTC by barak-b-starkware

2024-05-09 10:54 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/test_utils.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxRz6EL0768HWQ5tS6O:-NxRz6EMB3l1ZechcNdl:b-8ot6wm) ([raw file](https://github.com/starkware-libs/blockifier/blob/25b259bc51c59607bf85c9fab6348d933b5c3f3e/crates/blockifier/src/concurrency/test_utils.rs#L16)):*
> ```XML
> // Fixtures.
> 
> const TEST_CONTRACT_ADDRESS: &str = "0x1";
> ```

I think contract address `0x1` is a reserved address used for saving the block hash or something similar.



_Code quote:_
```XML
const TEST_CONTRACT_ADDRESS: &str = "0x1";
```


<!-- Sent from Reviewable.io -->

2024-05-09 11:03 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxS-bel2-zWAut34IEq:-NxS-bel2-zWAut34IEr:bh3q3kl) ([raw file](https://github.com/starkware-libs/blockifier/blob/25b259bc51c59607bf85c9fab6348d933b5c3f3e/crates/blockifier/src/concurrency/versioned_storage.rs#L55)):*
> ```XML
>     pub fn delete_writes(&mut self, tx_index: TxIndex) {
>         for (_, inner_map) in self.writes.iter_mut() {
>             inner_map.retain(|&index, _| index != tx_index);
> ```

Doesn't this `retain` method iterate over all the keys?
This would mean you iterate over all keys in the versioned storage every time a validation fails...
Can't we use the method `remove` to delete the entry with key `tx_index`?



_Code quote:_
```XML
            inner_map.retain(|&index, _| index != tx_index);
```


<!-- Sent from Reviewable.io -->

2024-05-09 11:35 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxS7CptEZ3rYDD6UU8G:-NxS7CptEZ3rYDD6UU8H:bmphqz0) ([raw file](https://github.com/starkware-libs/blockifier/blob/25b259bc51c59607bf85c9fab6348d933b5c3f3e/crates/blockifier/src/concurrency/versioned_storage_test.rs#L55)):*
> ```XML
>         writes: HashMap::from([(
>             contract_address,
>             BTreeMap::from([(1, nonce!(18_u8)), (2, nonce!(19_u8))]),
> ```

I think this test should have writes in multiple addresses, and make sure the deleted version is removed from all whereas all other entries remain unchanged.


<!-- Sent from Reviewable.io -->

2024-05-09 11:52 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxRz6EL0768HWQ5tS6O:-NxS9v7J-q7eZdZkaAlt:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/25b259bc51c59607bf85c9fab6348d933b5c3f3e/crates/blockifier/src/concurrency/test_utils.rs#L16)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I think contract address `0x1` is a reserved address used for saving the block hash or something similar.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxS-bel2-zWAut34IEq:-NxSAXHT-80C6ib6SJV4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/25b259bc51c59607bf85c9fab6348d933b5c3f3e/crates/blockifier/src/concurrency/versioned_storage.rs#L55)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Doesn't this `retain` method iterate over all the keys?
This would mean you iterate over all keys in the versioned storage every time a validation fails...
Can't we use the method `remove` to delete the entry with key `tx_index`?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxS7CptEZ3rYDD6UU8G:-NxSAcnZAOpHNFDUs1nx:b-11fkdh) ([raw file](https://github.com/starkware-libs/blockifier/blob/25b259bc51c59607bf85c9fab6348d933b5c3f3e/crates/blockifier/src/concurrency/versioned_storage_test.rs#L55)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I think this test should have writes in multiple addresses, and make sure the deleted version is removed from all whereas all other entries remain unchanged.
</blockquote></details>

I thought I would implement what you suggested in the `versioned_state_proxy_test.rs` where I added a `todo!()`.
And here to leave the check only for the functionality, WDYT?


<!-- Sent from Reviewable.io -->

2024-05-09 12:21 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxS7CptEZ3rYDD6UU8G:-NxSHiRU9OvfUUf5iaFJ:b-6c7uzr) ([raw file](https://github.com/starkware-libs/blockifier/blob/25b259bc51c59607bf85c9fab6348d933b5c3f3e/crates/blockifier/src/concurrency/versioned_storage_test.rs#L55)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I thought I would implement what you suggested in the `versioned_state_proxy_test.rs` where I added a `todo!()`.
And here to leave the check only for the functionality, WDYT?
</blockquote></details>

I think it makes sense to test this here as well.
In the `versioned_state_proxy_test`, we should test that the deletes are consistent between the different `VersionedStorage` fields. Here we should check across different addresses.


<!-- Sent from Reviewable.io -->

2024-05-09 14:01 UTC, avi-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxScKMC1vF-Q8-vAzhJ:-NxScKMC1vF-Q8-vAzhK:b-1olzqz) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ff57c5e0ecd0fc988aecfb92b8697d19da52cca/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L165)):*
> ```XML
>         }
>     }
> }
> ```

I think it's cleaner to do the for loop in the versioned storage and they just have 5 calls to `delete_writes` in this function. This is also a functionality that is natural for the VersionedStorage struct to have.

Why did you do it like this? To avoid passing the `writes` through? 



_Code quote:_
```XML
    fn delete_writes(
        &mut self,
        tx_index: TxIndex,
        writes: &StateMaps,
        class_hash_to_class: &ContractClassMapping,
    ) {
        for &key in writes.storage.keys() {
            self.storage.delete_write(key, tx_index);
        }
        for &key in writes.nonces.keys() {
            self.nonces.delete_write(key, tx_index);
        }
        for &key in writes.class_hashes.keys() {
            self.class_hashes.delete_write(key, tx_index);
        }
        for &key in writes.compiled_class_hashes.keys() {
            self.compiled_class_hashes.delete_write(key, tx_index);
        }
        for &key in class_hash_to_class.keys() {
            self.compiled_contract_classes.delete_write(key, tx_index);
        }
    }
}
```


<!-- Sent from Reviewable.io -->

2024-05-12 07:04 UTC, MohammadNassar1 requested changes
> Reviewed 1 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @noaov1, and @OriStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxfaErt-Ka3cIM9Cjpa:-NxfaErt-Ka3cIM9Cjpb:b6oaoy8) (no related file):*
Nice!

Q - Why do not you need to pass only `index` for the delete method? Are there cases where you only want to delete a specific key instead of all keys in the index?

Q - Could you please explain why you implemented the deletion method for proxy? who will run this method?

___


<!-- Sent from Reviewable.io -->

2024-05-12 08:05 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxfaErt-Ka3cIM9Cjpa:-NxfnUSa8vxIfmBWRy1l:b8w6ifx) (no related file):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Nice!

Q - Why do not you need to pass only `index` for the delete method? Are there cases where you only want to delete a specific key instead of all keys in the index?

Q - Could you please explain why you implemented the deletion method for proxy? who will run this method?
</blockquote></details>

Thanks!
A - You can pass only the `tx_index`, but passing the `write_set` will allow you to iterate only over the cells you wrote to and not over all the keys (it's an optimization).

A - You can use `delete_writes` **only** via `VersionedStateProxy` as well as `validate_read_set` and `apply_writes`. Notice that these methods are private in `VersionedState` (a new change I'm not sure you're familiar with).

___
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxScKMC1vF-Q8-vAzhJ:-Nxfn-UOC6y5THz5Zwx6:b9rynms) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ff57c5e0ecd0fc988aecfb92b8697d19da52cca/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L165)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I think it's cleaner to do the for loop in the versioned storage and they just have 5 calls to `delete_writes` in this function. This is also a functionality that is natural for the VersionedStorage struct to have.

Why did you do it like this? To avoid passing the `writes` through?
</blockquote></details>

Done.
Yes (: passing the writes complicates the task a bit (parameters-wise and testing-wise), but I managed to do that, and I agree that it's cleaner
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxS7CptEZ3rYDD6UU8G:-NxfnRg-BCGG-wiyFYJy:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/25b259bc51c59607bf85c9fab6348d933b5c3f3e/crates/blockifier/src/concurrency/versioned_storage_test.rs#L55)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Now the method is `delete_write` and the multiple addresses functionality moved to the `for` loop in the `VersionedState`, WDYT now?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-12 08:38 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxS7CptEZ3rYDD6UU8G:-Nxfwyid53_NT_Sp90e5:b-83sjoh) ([raw file](https://github.com/starkware-libs/blockifier/blob/25b259bc51c59607bf85c9fab6348d933b5c3f3e/crates/blockifier/src/concurrency/versioned_storage_test.rs#L55)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice!


<!-- Sent from Reviewable.io -->

2024-05-12 08:47 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 9 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Nxfz-3fCDZWP9P4uARc:-Nxfz-3fCDZWP9P4uARd:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7c2bd3bc71631473962e330e830bb30c996f787/crates/blockifier/src/concurrency/versioned_storage_test.rs#L9)):*
> ```XML
> use starknet_api::{class_hash, contract_address, patricia_key};
> 
> // use crate::concurrency::test_utils::contract_address;
> ```




<!-- Sent from Reviewable.io -->

2024-05-12 09:03 UTC, avi-starkware submitted a review, later dismissed
> Reviewed 3 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @noaov1, and @OriStarkware)



<!-- Sent from Reviewable.io -->

2024-05-12 11:20 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxScKMC1vF-Q8-vAzhJ:-NxgVL6V2XH4WD6Ty4xq:bcgsrbf) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ff57c5e0ecd0fc988aecfb92b8697d19da52cca/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L165)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Note that in `apply_writes` we have this `for` loops. 
I think that it's because the versioned storage is not aware of multiple writes (this is something that is managed by the proxy), but only know, given a value, to write it. 
Either way, it's important to be consistent.
</blockquote></details>

Sorry Barak, I didn't notice that apply_writes and validate_read_set both have these annoying for-loops. I agree we should be consistent, so if we don't want to change these two, you should revert to the for-loop implementation. However, I do think we should get rid of these for-loops in all three methods (unless there is some good design justification I am not seeing).


<!-- Sent from Reviewable.io -->

2024-05-12 12:40 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 62 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxgDBwu0jjpucvykXVs:-NxgHP_58JXt-M7YZSfU:bp99ffc) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7c2bd3bc71631473962e330e830bb30c996f787/crates/blockifier/src/concurrency/versioned_storage.rs#L62)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think it can panic.
</blockquote></details>

Maybe not.


<!-- Sent from Reviewable.io -->

2024-05-12 15:02 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1 and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxScKMC1vF-Q8-vAzhJ:-NxhJepI7h9JL0qEKXJi:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ff57c5e0ecd0fc988aecfb92b8697d19da52cca/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L165)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Sorry Barak, I didn't notice that apply_writes and validate_read_set both have these annoying for-loops. I agree we should be consistent, so if we don't want to change these two, you should revert to the for-loop implementation. However, I do think we should get rid of these for-loops in all three methods (unless there is some good design justification I am not seeing).
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 201 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxgAI9rDUic3ggjycON:-NxhJb3GAXKS1vHA6xxq:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7c2bd3bc71631473962e330e830bb30c996f787/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L201)):*
> ```XML
>     ) {
>         self.state().delete_writes(tx_index, writes, class_hash_to_class);
>     }
> ```

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 9 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Nxfz-3fCDZWP9P4uARc:-Nxgurvr5M_dkU7esfP2:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f7c2bd3bc71631473962e330e830bb30c996f787/crates/blockifier/src/concurrency/versioned_storage_test.rs#L9)):*
> ```XML
> use starknet_api::{class_hash, contract_address, patricia_key};
> 
> // use crate::concurrency::test_utils::contract_address;
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-05-15 07:20 UTC, noaov1 requested changes
> Reviewed 3 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 19 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Nxuf_yyEYs1dgk3HyO9:-Nxuf_yyEYs1dgk3HyOA:b-nzgb7h) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L19)):*
> ```XML
> // Fixtures.
> 
> const TEST_CONTRACT_ADDRESS: &str = "0x18031991";
> ```

Why not use the one defined in the non-concurrency test util?



_Code quote:_
```XML
const TEST_CONTRACT_ADDRESS: &str = "0x18031991";
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 46 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Nxuua_w4gnRNV2vnwkl:-Nxuua_w4gnRNV2vnwkm:bvrszww) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L46)):*
> ```XML
>     }
> 
>     pub fn get_writes_from_index(&mut self, tx_index: TxIndex) -> StateMaps {
> ```

I don't think this name describes correctly the method.



_Code quote:_
```XML
    pub fn get_writes_from_index(&mut self, tx_index: TxIndex) -> StateMaps {
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 56 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxuuLFP1XAzdhAChwhm:-NxuuLFP1XAzdhAChwhn:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L56)):*
> ```XML
>     }
> 
>     #[cfg(test)]
> ```





_Suggestion:_
```XML
    #[cfg(any(feature = "testing", test))]
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 175 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Nxuv4-U2xnOTF6YjDT7:-Nxuv4-U2xnOTF6YjDT8:bmto4sa) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L175)):*
> ```XML
>         for &key in class_hash_to_class.keys() {
>             self.compiled_contract_classes.delete_writes(key, tx_index);
>         }
> ```

Please add `declared_contracts`.



_Code quote:_
```XML
        }
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 403 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxuwM64AUf4hWM7pkXY:-NxuwM64AUf4hWM7pkXZ:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L403)):*
> ```XML
>         );
>         // TODO(OriF, 01/07/2025): Test compiled_contract_classes once deploy account preceding
>         // declare flow is solved.
> ```

?



_Code quote:_
```XML
        // TODO(OriF, 01/07/2025): Test compiled_contract_classes once deploy account preceding
        // declare flow is solved.
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 82 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxuwuAB74Ama7u0zc5B:-NxuwuAB74Ama7u0zc5C:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_storage.rs#L82)):*
> ```XML
>     }
> 
>     #[cfg(test)]
> ```





_Suggestion:_
```XML
    #[cfg(any(feature = "testing", test))]
```
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxuvW_gBhcQpzRm4itT:-NxuvW_gBhcQpzRm4itU:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_storage_test.rs#L49)):*
> ```XML
> 
> #[rstest]
> fn test_adelete_writes(
> ```





_Suggestion:_
```XML
fn test_delete_writes(
```


<!-- Sent from Reviewable.io -->

2024-05-15 14:13 UTC, OriStarkware requested changes
> Reviewed 3 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: 4 of 5 files reviewed, 14 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 15 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwGBzb60DD_uoVZVq4:-NxwGBzb60DD_uoVZVq5:bl36lip) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L15)):*
> ```XML
> use crate::transaction::transactions::ExecutableTransaction;
> 
> // Public Consts.
> ```

Why do we have this comment if there are no public consts?
___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 19 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwGU8_35Izi_Z5S1lw:-NxwGU8_35Izi_Z5S1lx:bv1tege) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L19)):*
> ```XML
> // Fixtures.
> 
> const TEST_CONTRACT_ADDRESS: &str = "0x18031991";
> ```

What is this address?
___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 26 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwHjMW66tXUhiTATFE:-NxwHjMW66tXUhiTATFF:bqudx2h) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L26)):*
> ```XML
> }
> 
> const TEST_CLASS_HASH: u8 = 27_u8;
> ```

Please move this const next to the previous one.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 24 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwKFhc6P4RyPdMNqlH:-NxwKFhc6P4RyPdMNqlI:bghxlbc) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L24)):*
> ```XML
> /// This state facilitates concurrent operations.
> /// Reader functionality is injected through initial state.
> #[derive(Debug)]
> ```

Why do we need that?



_Code quote:_
```XML
#[derive(Debug)]
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 52 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwJdyF-oSJuhGzVpvo:-NxwJdyG342fu5yGpvo6:b51vb49) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L52)):*
> ```XML
>             class_hashes: self.class_hashes.get_writes_from_index(tx_index),
>             compiled_class_hashes: self.compiled_class_hashes.get_writes_from_index(tx_index),
>             declared_contracts: HashMap::new(),
> ```

Please add a TODO on me to fix that.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 63 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwKNVc9K0IqG4-HY-Y:-NxwKNVc9K0IqG4-HY-Z:b51vb49) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L63)):*
> ```XML
>             class_hashes: self.class_hashes.get_writes_of_index(tx_index),
>             compiled_class_hashes: self.compiled_class_hashes.get_writes_of_index(tx_index),
>             declared_contracts: HashMap::new(),
> ```

Please add a TODO on me to fix that.
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 52 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Nxwa8H941O6x-nSmY0k:-Nxwa8H941O6x-nSmY0l:bce4fw9) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_storage_test.rs#L52)):*
> ```XML
>     contract_address: ContractAddress,
>     class_hash: ClassHash,
>     #[values(0, 1, 2)] tx_index_to_delete_writes: TxIndex,
> ```

Why do we need 3 different values?


<!-- Sent from Reviewable.io -->

2024-05-16 08:01 UTC, noaov1 reviewed
> Reviewed 1 of 5 files at r6, 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: 3 of 5 files reviewed, 16 unresolved discussions (waiting on @barak-b-starkware and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 376 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Ny-PCRU7EKyJmm68zMD:-Ny-PCRU7EKyJmm68zME:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L376)):*
> ```XML
>     let contract_addresses = [contract_address!("0x100"), contract_address!("0x200")];
>     let contract_class = FeatureContract::TestContract(CairoVersion::Cairo1).get_class();
>     for tx in transactional_states.iter_mut().take(num_of_txs) {
> ```





_Suggestion:_
```XML
    for tx_state in transactional_states.iter_mut().take(num_of_txs) {
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 367 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Ny-PhxYAqdtYcFJjvIY:-Ny-PhxZ5hJXHtEfgWMe:b68m7b1) ([raw file](https://github.com/starkware-libs/blockifier/blob/1b121d458f662f6ff9c06d4745c8246f2463aa5c/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L367)):*
> ```XML
> #[rstest]
> fn test_delete_writes(
>     #[values(0, 1, 2)] tx_index_to_delete_writes: TxIndex,
> ```

What is the difference between each case?



_Code quote:_
```XML
    #[values(0, 1, 2)] tx_index_to_delete_writes: TxIndex,
```


<!-- Sent from Reviewable.io -->

2024-05-16 08:02 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: 3 of 5 files reviewed, 14 unresolved discussions (waiting on @avi-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 15 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwGBzb60DD_uoVZVq4:-Ny-D-j7-hTTLtjaoP_8:bbpphu) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L15)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Why do we have this comment if there are no public consts?
</blockquote></details>

In the next PR I move here the `DEFAULT_CHUNK_SIZE` and it makes sense to have this this section in the test utils file but I can remove it and add it only later if you prefer.
___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 19 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwGU8_35Izi_Z5S1lw:-Ny-DRaw6B5hqFFj3TRt:bitu92d) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L19)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

What is this address?
</blockquote></details>

It's some random string I put after @avi-starkware 's comment [here](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxRz6EL0768HWQ5tS6O) 
___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 19 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Nxuf_yyEYs1dgk3HyO9:-Ny-Dz_y8wrVcyxVyi9J:b-cni72o) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L19)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why not use the one defined in the non-concurrency test util?
</blockquote></details>

which one you want me to use?
in blockifier (non-concurrency):
```
pub const TEST_SEQUENCER_ADDRESS: &str = "0x1000";
pub const TEST_ERC20_CONTRACT_ADDRESS: &str = "0x1001";
pub const TEST_ERC20_CONTRACT_ADDRESS2: &str = "0x1002";
pub const TEST_ERC20_CONTRACT_CLASS_HASH: &str = "0x1010";
```

in native blockifier:
`pub const TOKEN_FOR_TESTING_CLASS_HASH: &str = "0x30";`

Maybe there is another one that I missed...
___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 26 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwHjMW66tXUhiTATFE:-Ny-FFug--VIRZA46d0D:b-9ignfx) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L26)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Please move this const next to the previous one.
</blockquote></details>

Actually I like it more near the fixture that uses it, it serves only the fixture. Why you think it should be near the other constant (except for the obvious that constants will be near other constants).
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 24 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwKFhc6P4RyPdMNqlH:-Ny-FhPwDtQis9su3sRQ:b-xizi5j) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L24)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Why do we need that?
</blockquote></details>

It helps debugging, and I see no reason to add it manually every time I run some test that needs it, so I added it (:
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 46 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Nxuua_w4gnRNV2vnwkl:-Ny-G6HY5Eajq512M6ER:b-vyydgv) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L46)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I don't think this name describes correctly the method.
</blockquote></details>

This is the old name (that was in the `versioned_storage` file). Do you want to change it in this PR?
My try: `get_newest_writes_as_of_index`
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 52 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwJdyF-oSJuhGzVpvo:-Ny-KHGy0WBg5MIvK3aj:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L52)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Please add a TODO on me to fix that.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 63 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwKNVc9K0IqG4-HY-Y:-Ny-KbsV9TQO6hfJ1LIg:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L63)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Please add a TODO on me to fix that.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 175 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Nxuv4-U2xnOTF6YjDT7:-Ny-Ks83BJi9SUq-1iNq:bsch3pn) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L175)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please add `declared_contracts`.
</blockquote></details>

I suggest @OriStarkware will add it in [this](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-) PR
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 403 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxuwM64AUf4hWM7pkXY:-Ny-LgFUDdwcCzicOqIO:bhma0xw) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L403)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

?
</blockquote></details>

I added the necessary lines.
I was confused between two different things.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 367 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Ny-PhxYAqdtYcFJjvIY:-Ny-PuV85CB4uzYi27JD:b-pxwqm2) ([raw file](https://github.com/starkware-libs/blockifier/blob/1b121d458f662f6ff9c06d4745c8246f2463aa5c/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L367)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What is the difference between each case?
</blockquote></details>

See [here](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Nxwa8H941O6x-nSmY0k)
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 82 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxuwuAB74Ama7u0zc5B:-Ny-P8kr5AVHywevURi_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_storage.rs#L82)):*
> ```XML
>     }
> 
>     #[cfg(test)]
> ```

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 49 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxuvW_gBhcQpzRm4itT:-Ny-PHyb9KkMrgHY11aN:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_s [...]

2024-05-16 08:27 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 46 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Nxuua_w4gnRNV2vnwkl:-Ny-Vc-K1gHv_78m69rQ:b-cbpz68) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L46)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

This is the old name (that was in the `versioned_storage` file). Do you want to change it in this PR?
My try: `get_newest_writes_as_of_index`
</blockquote></details>

How about:
`get_last_writes_up_to_index`?
or just
`get_last_writes`?


<!-- Sent from Reviewable.io -->

2024-05-16 11:39 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: 1 of 5 files reviewed, 14 unresolved discussions (waiting on @noaov1 and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 46 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Nxuua_w4gnRNV2vnwkl:-Ny0B_xR3nKwesq-hwBP:bxs6bhf) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L46)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

How about:
`get_last_writes_up_to_index`?
or just
`get_last_writes`?
</blockquote></details>

`get_last_writes_up_to_index` sounds good.
Done.


<!-- Sent from Reviewable.io -->

2024-05-19 05:00 UTC, noaov1 requested changes
> Reviewed 2 of 2 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: all files reviewed, 13 unresolved discussions (waiting on @barak-b-starkware and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 19 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Nxuf_yyEYs1dgk3HyO9:-NyE6xFF9g2BvXJC6A0U:b-fhmng6) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L19)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

which one you want me to use?
in blockifier (non-concurrency):
```
pub const TEST_SEQUENCER_ADDRESS: &str = "0x1000";
pub const TEST_ERC20_CONTRACT_ADDRESS: &str = "0x1001";
pub const TEST_ERC20_CONTRACT_ADDRESS2: &str = "0x1002";
pub const TEST_ERC20_CONTRACT_CLASS_HASH: &str = "0x1010";
```

in native blockifier:
`pub const TOKEN_FOR_TESTING_CLASS_HASH: &str = "0x30";`

Maybe there is another one that I missed...
</blockquote></details>

I meant: `let contract_address = contract.get_instance_address(0);`, where `contract` is the `FeatureContract` you use in the test (if used).
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 403 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxuwM64AUf4hWM7pkXY:-NyECoUVDdOR4TOTbHgH:bknl8eh) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L403)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I added the necessary lines.
I was confused between two different things.
</blockquote></details>

You mean for @OriStarkware to test that the `declared_contract` mapping was deleted?
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 379 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyEC3znB1bIVOVl68gQ:-NyEC3znB1bIVOVl68gR:bofd3vk) ([raw file](https://github.com/starkware-libs/blockifier/blob/9aae1d93ec7ae3c40d03cd7f35f8dc2d44db4ded/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L379)):*
> ```XML
>         for contract_address in contract_addresses.iter() {
>             // Class hash values are not checked in this test.
>             tx_state.set_class_hash_at(*contract_address, class_hash).unwrap();
> ```

Why 2 contract addresses?



_Suggestion:_
```XML
            // Class hash values are not checked in this test.
            // Deploy 2 instances of the contract.
            tx_state.set_class_hash_at(*contract_address, class_hash).unwrap();
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 380 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyEBpur35ndP5d8NQiH:-NyEBpur35ndP5d8NQiI:buvtyjj) ([raw file](https://github.com/starkware-libs/blockifier/blob/9aae1d93ec7ae3c40d03cd7f35f8dc2d44db4ded/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L380)):*
> ```XML
>             // Class hash values are not checked in this test.
>             tx_state.set_class_hash_at(*contract_address, class_hash).unwrap();
>             tx_state.set_contract_class(class_hash, contract_class.clone()).unwrap();
> ```

Can be in the outer loop, no?



_Suggestion:_
```XML
            // Declare the contract.
            tx_state.set_contract_class(class_hash, contract_class.clone()).unwrap();
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 384 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyECL8dAz4H5eaNKpW5:-NyECL8e9fCGnsXSEg5l:bs7k66q) ([raw file](https://github.com/starkware-libs/blockifier/blob/9aae1d93ec7ae3c40d03cd7f35f8dc2d44db4ded/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L384)):*
> ```XML
>         tx_state.state.apply_writes(
>             &tx_state.cache.borrow().writes,
>             &tx_state.class_hash_to_class.borrow().clone(),
> ```

Why is the `clone` needed? You use `&`
Same below.



_Code quote:_
```XML
            &tx_state.class_hash_to_class.borrow().clone(),
```
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 60 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyEAqwm-RR6n9FjQELE:-NyEAqwm-RR6n9FjQELF:b-7zi8tj) ([raw file](https://github.com/starkware-libs/blockifier/blob/9aae1d93ec7ae3c40d03cd7f35f8dc2d44db4ded/crates/blockifier/src/concurrency/versioned_storage_test.rs#L60)):*
> ```XML
>         writes: HashMap::from([(
>             contract_address,
>             // Class hash values are not checked in this test.
> ```

WDYM?



_Code quote:_
```XML
            // Class hash values are not checked in this test.
```


<!-- Sent from Reviewable.io -->

2024-05-19 07:49 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: all files reviewed, 13 unresolved discussions (waiting on @avi-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 19 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Nxuf_yyEYs1dgk3HyO9:-NyEeyCHBjFOT0lJQ7_Y:bufku3v) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L19)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I meant: `let contract_address = contract.get_instance_address(0);`, where `contract` is the `FeatureContract` you use in the test (if used).
</blockquote></details>

Done. (change in `versioned_state_proxy_test.rs` IIUC)
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 403 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxuwM64AUf4hWM7pkXY:-NyEm62E-PAAh2s_b2mZ:b16odlv) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L403)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

You mean for @OriStarkware to test that the `declared_contract` mapping was deleted?
</blockquote></details>

Removed, mistakenly remained in last revision.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 379 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyEC3znB1bIVOVl68gQ:-NyEjlsQ8fYKjpnWVKWu:b-q9sxt0) ([raw file](https://github.com/starkware-libs/blockifier/blob/9aae1d93ec7ae3c40d03cd7f35f8dc2d44db4ded/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L379)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why 2 contract addresses?
</blockquote></details>

See @avi-starkware 's comment [here](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxS7CptEZ3rYDD6UU8G).
I put 2 addresses to ensure that `delete_writes` removes information from multiple keys.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 380 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyEBpur35ndP5d8NQiH:-NyEkPdh-KcDBEpZSzJt:baqdp9m) ([raw file](https://github.com/starkware-libs/blockifier/blob/9aae1d93ec7ae3c40d03cd7f35f8dc2d44db4ded/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L380)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can be in the outer loop, no?
</blockquote></details>

I suggested similar comments that focus more on the modified members, LMK if you like it.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 384 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyECL8dAz4H5eaNKpW5:-NyEm1tq7pZe37znLteR:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9aae1d93ec7ae3c40d03cd7f35f8dc2d44db4ded/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L384)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is the `clone` needed? You use `&`
Same below.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage_test.rs` line 60 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyEAqwm-RR6n9FjQELE:-NyEoJEQ0go7U2w-uFFf:b-x0b670) ([raw file](https://github.com/starkware-libs/blockifier/blob/9aae1d93ec7ae3c40d03cd7f35f8dc2d44db4ded/crates/blockifier/src/concurrency/versioned_storage_test.rs#L60)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

I mean that the test only checks that the values were removed, and there is no meaning to the values themselves, so no assertions on them in the following lines will be found.


<!-- Sent from Reviewable.io -->

2024-05-19 09:36 UTC, noaov1 submitted a review, later dismissed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: all files reviewed, 11 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 19 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Nxuf_yyEYs1dgk3HyO9:-NyFAYkrA0KWLgXzatKz:brmrd61) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L19)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Done. (change in `versioned_state_proxy_test.rs` IIUC)
</blockquote></details>

I meant to remove it. No need in this PR. See my comments below.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 379 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyEC3znB1bIVOVl68gQ:-NyFCFORDrJsTWWy7uiu:be5cgp9) ([raw file](https://github.com/starkware-libs/blockifier/blob/9aae1d93ec7ae3c40d03cd7f35f8dc2d44db4ded/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L379)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

See @avi-starkware 's comment [here](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxS7CptEZ3rYDD6UU8G).
I put 2 addresses to ensure that `delete_writes` removes information from multiple keys.
</blockquote></details>

Got it. Nice. (you can document it)
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 374 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFAF1h4FR5fkFbs4EE:-NyFAF1h4FR5fkFbs4EF:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L374)):*
> ```XML
>         (0..num_of_txs).map(|i| CachedState::from(safe_versioned_state.pin_version(i))).collect();
>     // Setting 2 instances of the contract to ensure `delete_writes` removes information from
>     // nultiple keys. Class hash values are not checked in this test.
> ```





_Suggestion:_
```XML
    // multiple keys. Class hash values are not checked in this test.
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 379 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFAmIt9CqZ-0HlUjou:-NyFAmIt9CqZ-0HlUjov:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L379)):*
> ```XML
>         (contract_address!("0x200"), class_hash!(21_u8)),
>     ];
>     let feature_contract = FeatureContract::TestContract(CairoVersion::Cairo1);
> ```





_Suggestion:_
```XML
    let feature_contract = FeatureContract::TestContract(CairoVersion::Cairo1);
    let contract_addresses = [
        (feature_contract.get_instance_address(0), feature_contract.get_class_hash()),
        (feature_contract.get_instance_address(1), feature_contract.get_class_hash()),
    ];
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 396 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFBY878srLN9lVE8XS:-NyFBY878srLN9lVE8XT:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L396)):*
> ```XML
>     transactional_states[tx_index_to_delete_writes].state.delete_writes(
>         &transactional_states[tx_index_to_delete_writes].cache.borrow().writes,
>         &transactional_states[tx_index_to_delete_writes].class_hash_to_class.borrow().clone(),
> ```





_Suggestion:_
```XML
        &transactional_states[tx_index_to_delete_writes].class_hash_to_class.borrow(),
```


<!-- Sent from Reviewable.io -->

2024-05-19 10:53 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: all files reviewed, 14 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 19 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwGU8_35Izi_Z5S1lw:-NyF4QCN6ZNHlumgvdEv:bua6jf4) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L19)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

It's some random string I put after @avi-starkware 's comment [here](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxRz6EL0768HWQ5tS6O)
</blockquote></details>

18/3/1991 :)
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 57 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFTV5GCDSLg36iJGYH:-NyFTV5GCDSLg36iJGYI:byuhkcs) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L57)):*
> ```XML
>     }
> 
>     #[cfg(any(feature = "testing", test))]
> ```

Not for now, but can we define test utils in a dedicated file, such as this one?
https://github.com/starkware-libs/blockifier/blob/9c5b2d0a66b24f16de76ab1c461a724fd529bb9b/crates/blockifier/src/test_utils/struct_impls.rs#L201

(is there a reason not to stick with this convention? I like it since it keeps the important files clean)



_Code quote:_
```XML
#[cfg(any(feature = "testing", test))]
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 54 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFRZ-R4BGjhLD8v8Lu:-NyFRZ-S5NRDVbBPtSfX:b-pysxb6) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_storage.rs#L54)):*
> ```XML
>     }
> 
>     pub fn delete_writes(&mut self, key: K, tx_index: TxIndex) {
> ```

`delete` or `delete_write` (singular)



_Code quote:_
```XML
pub fn delete_writes(&mut self, key: K, tx_index: TxIndex) {
```
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 72 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFStXe6-r8o8yllQFy:-NyFStXe6-r8o8yllQFz:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_storage.rs#L72)):*
> ```XML
>     }
> 
>     pub(crate) fn get_last_writes_up_to_index(&self, index: TxIndex) -> HashMap<K, V> {
> ```





_Suggestion:_
```XML
get_writes_up_to_index
```


<!-- Sent from Reviewable.io -->

2024-05-19 11:12 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: 1 of 5 files reviewed, 12 unresolved discussions (waiting on @avi-starkware, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 57 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFTV5GCDSLg36iJGYH:-NyFV-rX9-9QN2urR01B:bj3q4ta) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L57)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Not for now, but can we define test utils in a dedicated file, such as this one?
https://github.com/starkware-libs/blockifier/blob/9c5b2d0a66b24f16de76ab1c461a724fd529bb9b/crates/blockifier/src/test_utils/struct_impls.rs#L201

(is there a reason not to stick with this convention? I like it since it keeps the important files clean)
</blockquote></details>

@noaov1 do you want to add it as a task to Monday?
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 379 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyEC3znB1bIVOVl68gQ:-NyFWGRs0iL-IXbqnbxY:b-lb2pz5) ([raw file](https://github.com/starkware-libs/blockifier/blob/9aae1d93ec7ae3c40d03cd7f35f8dc2d44db4ded/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L379)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Got it. Nice. (you can document it)
</blockquote></details>

I did this here: (this is what you mean?)



_Code quote:_
```XML
    // Setting 2 instances of the contract to ensure `delete_writes` removes information from
    // nultiple keys. Class hash values are not checked in this test.
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 374 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFAF1h4FR5fkFbs4EE:-NyFVG0S5HAft-nAV3Ic:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L374)):*
> ```XML
>         (0..num_of_txs).map(|i| CachedState::from(safe_versioned_state.pin_version(i))).collect();
>     // Setting 2 instances of the contract to ensure `delete_writes` removes information from
>     // nultiple keys. Class hash values are not checked in this test.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 379 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFAmIt9CqZ-0HlUjou:-NyFViNJ0fuF5hamN6aa:b-tbd2bo) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L379)):*
> ```XML
>         (contract_address!("0x200"), class_hash!(21_u8)),
>     ];
>     let feature_contract = FeatureContract::TestContract(CairoVersion::Cairo1);
> ```

Combining the feature contract with the `class_hashes` mapping modification might be confusing.
I want to use the `feature_contract` only to modify the `class_hash_to_class` mapping.
WDYT?
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 396 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFBY878srLN9lVE8XS:-NyFWVi_6wT-F6QgWyN-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L396)):*
> ```XML
>     transactional_states[tx_index_to_delete_writes].state.delete_writes(
>         &transactional_states[tx_index_to_delete_writes].cache.borrow().writes,
>         &transactional_states[tx_index_to_delete_writes].class_hash_to_class.borrow().clone(),
> ```

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 54 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFRZ-R4BGjhLD8v8Lu:-NyFWdaG4fSZkZkzdtlS:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_storage.rs#L54)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

`delete` or `delete_write` (singular)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/versioned_storage.rs` line 72 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFStXe6-r8o8yllQFy:-NyFWy2z2lBb5RKRKCO5:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_storage.rs#L72)):*
> ```XML
>     }
> 
>     pub(crate) fn get_last_writes_up_to_index(&self, index: TxIndex) -> HashMap<K, V> {
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-05-19 11:15 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: 1 of 5 files reviewed, 15 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 26 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwHjMW66tXUhiTATFE:-NyFUHMWAPP9BM1V8BB0:b-l90ija) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L26)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Actually I like it more near the fixture that uses it, it serves only the fixture. Why you think it should be near the other constant (except for the obvious that constants will be near other constants).
</blockquote></details>

If it serves just the fixture, do we need it outside the fixture? Do we need it at all?
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxScKMC1vF-Q8-vAzhJ:-NyFV5fLDOgiTaPGzdhL:b-6c5n0e) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ff57c5e0ecd0fc988aecfb92b8697d19da52cca/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L165)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe we don't need `write` at all, we can have just `apply_writes` exposed. 
But not important and not for this PR
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 157 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFXwgI8wQkeRCOHEWc:-NyFXwgI8wQkeRCOHEWd:b-6xhemf) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L157)):*
> ```XML
>     }
> 
>     fn delete_writes(
> ```

Better to have at least one test that creates a `StateMaps` object with all maps non-trivial, and checks that you didn't miss any map. I.e., simple as 
```
maps = StateMaps {...}
apply_writes(maps)
delete_writes(maps)
assert get_writes() == StateMaps::default()
```

(That way, the test will fail to compile when a new map is added to StateMap - which is not the case currently)
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 380 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFWTiy79MN65YIu8Z3:-NyFWTiy79MN65YIu8Z4:bad60e9) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L380)):*
> ```XML
>     ];
>     let feature_contract = FeatureContract::TestContract(CairoVersion::Cairo1);
>     for tx_state in transactional_states.iter_mut().take(num_of_txs) {
> ```

Is this necessary?



_Code quote:_
```XML
.take(num_of_txs)
```
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 385 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFVrVJ5yhWruacI0Yu:-NyFVrVJ5yhWruacI0Yv:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L385)):*
> ```XML
>             tx_state.set_class_hash_at(*contract_address, *class_hash).unwrap();
>         }
>         // Modify the `class_hash_to_class` memboer of the CachedState.
> ```





_Suggestion:_
```XML
 member 
```


<!-- Sent from Reviewable.io -->

2024-05-19 11:20 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-:-NyF_5gi8_29SsX4q7Es:bnfp4nl)* status: 1 of 5 files reviewed, 13 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @noaov1, and @OriStarkware)



<!-- Sent from Reviewable.io -->

2024-05-19 11:27 UTC, OriStarkware requested changes
> Reviewed 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: 1 of 5 files reviewed, 11 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 15 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwGBzb60DD_uoVZVq4:-NyEaJdv1RbGO2dLquKA:b-g9fta) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L15)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

In the next PR I move here the `DEFAULT_CHUNK_SIZE` and it makes sense to have this this section in the test utils file but I can remove it and add it only later if you prefer.
</blockquote></details>

Yes, please do that.
___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 19 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwGU8_35Izi_Z5S1lw:-NyEaYvX6pg6KM1iy62P:b-mv66m9) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L19)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

It's some random string I put after @avi-starkware 's comment [here](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxRz6EL0768HWQ5tS6O)
</blockquote></details>

Please document this choice.
___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 26 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwHjMW66tXUhiTATFE:-NyEagbeENRLlmXTEndG:b-seppvc) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L26)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Actually I like it more near the fixture that uses it, it serves only the fixture. Why you think it should be near the other constant (except for the obvious that constants will be near other constants).
</blockquote></details>

It is a convention that constants are defined at the top and all together. If I see a constant in a test, I will look for it at the beginning of the file. The current position is confusing and inconsistent with the majority of our code.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 24 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwKFhc6P4RyPdMNqlH:-NyEbCuS8xnnQjiw3VQx:b-ktf8jo) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L24)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

It helps debugging, and I see no reason to add it manually every time I run some test that needs it, so I added it (:
</blockquote></details>

Does it come with performance issues? 
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 175 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Nxuv4-U2xnOTF6YjDT7:-NyEbXq94hqyjsXJK0N1:b88j0kh) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L175)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I suggest @OriStarkware will add it in [this](https://reviewable.io/reviews/starkware-libs/blockifier/1887#-) PR
</blockquote></details>

If you don't add it, please add a TODO.


<!-- Sent from Reviewable.io -->

2024-05-19 11:31 UTC, barak-b-starkware commented
*[`crates/blockifier/src/concurrency/test_utils.rs` line 26 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwHjMW66tXUhiTATFE:-NyFZnoO3wJlpLxUpsdD:bun5q4c) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L26)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

It is a convention that constants are defined at the top and all together. If I see a constant in a test, I will look for it at the beginning of the file. The current position is confusing and inconsistent with the majority of our code.
</blockquote></details>

@Yoni-Starkware - Good question, @MohammadNassar1 inserted it this way in [this](https://reviewable.io/reviews/starkware-libs/blockifier/1748) PR.
@noaov1, @MohammadNassar1, and I discussed this fixture.
The options were:
1. `contract_address` - I didn't like it because it doesn't have any "test" meaning
2. `contract_address_for_testing` - @noaov1 didn't like it because the `_for_testing` suffix is unnecessary, and you get it from the context.
3. `test_contract_address` - this form appears only in Python.
4. Use a constant instead of a fixture.
5. Combine the constant with (1) - some form that can be found in `crates/blockifier/src/transaction/test_utils.rs` under `max_fee`, for example (but there, the constant is used in other places too).

I don't like this form either, and I think option 2 is better.
@noaov1 and I don't have strong opinions regarding which form to choose.

@OriStarkware - OK, what do you suggest? leave it as is and just move the constant?


<!-- Sent from Reviewable.io -->

2024-05-19 12:49 UTC, OriStarkware reviewed
> Reviewed 3 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: 4 of 5 files reviewed, 10 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @MohammadNassar1, and @noaov1)



<!-- Sent from Reviewable.io -->

2024-05-19 13:12 UTC, noaov1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-:-NyFyib07AjkEpCfQ7Im:bnfp4nl)* status: all files reviewed, 9 unresolved discussions (waiting on @barak-b-starkware, @MohammadNassar1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 57 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFTV5GCDSLg36iJGYH:-NyFbROn5H0lybh4lwgO:b-sm9nd7) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L57)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

@noaov1 do you want to add it as a task to Monday?
</blockquote></details>

Good idea. Added.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 379 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFAmIt9CqZ-0HlUjou:-NyFazqd-e_ls9tB1Tte:b-ddlos1) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L379)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Combining the feature contract with the `class_hashes` mapping modification might be confusing.
I want to use the `feature_contract` only to modify the `class_hash_to_class` mapping.
WDYT?
</blockquote></details>

Why?
It can be the same class hash, no?


<!-- Sent from Reviewable.io -->

2024-05-19 13:53 UTC, noaov1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: all files reviewed, 9 unresolved discussions (waiting on @barak-b-starkware, @MohammadNassar1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 157 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFXwgI8wQkeRCOHEWc:-NyG67YTDrBP2GLbtiEb:b-nk6qfa) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L157)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Better to have at least one test that creates a `StateMaps` object with all maps non-trivial, and checks that you didn't miss any map. I.e., simple as 
```
maps = StateMaps {...}
apply_writes(maps)
delete_writes(maps)
assert get_writes() == StateMaps::default()
```

(That way, the test will fail to compile when a new map is added to StateMap - which is not the case currently)
</blockquote></details>

Nice!
Same can be done for testing `apply_writes`:
(maybe also for `validate_reads`)
(can be done in a separate PR)



_Code snippet:_
```XML
maps = StateMaps {...}
apply_writes(maps)
assert get_writes_of_index == maps
```


<!-- Sent from Reviewable.io -->

2024-05-19 13:54 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: all files reviewed, 6 unresolved discussions (waiting on @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 15 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwGBzb60DD_uoVZVq4:-NyFjX8X-GxKgsKJq5L_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L15)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Yes, please do that.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 19 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwGU8_35Izi_Z5S1lw:-NyFjebW7g3HzTJEIORn:b9b8qiy) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L19)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Please document this choice.
</blockquote></details>

I'm unsure I understand what to write in the documentation for this contact. Can you suggest?
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxScKMC1vF-Q8-vAzhJ:-NyFlrI90l_Kj_2m6a3A:b-mj2xru) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ff57c5e0ecd0fc988aecfb92b8697d19da52cca/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L165)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Maybe we don't need `write` at all, we can have just `apply_writes` exposed. 
But not important and not for this PR
</blockquote></details>

WDYM? Do you want to remove the `write` method from `VersionedStorage`?
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 24 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwKFhc6P4RyPdMNqlH:-NyFwSaK2_Rx7J9cbUbA:bcq0cje) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L24)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Does it come with performance issues?
</blockquote></details>

AFAIK it doesn't come with performance issues.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 175 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-Nxuv4-U2xnOTF6YjDT7:-NyFkg_x8lwaOPtbUi8t:bmpozz8) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L175)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

If you don't add it, please add a TODO.
</blockquote></details>

I can't add it to this PR. Adding it requires adding the member to the `VersionedState`, modifying the constructor, and modifying the tests I've added.

I added a TODO, but IMO It's weird to add the `declared_contracts` TODO to this PR so that this `for` loop will be added to `delete_writes` (but not to `apply_writes` or to `validate_read_set`).
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 157 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFXwgI8wQkeRCOHEWc:-NyFzbtY1Dklpfs623M-:b-qbtzzf) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L157)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Better to have at least one test that creates a `StateMaps` object with all maps non-trivial, and checks that you didn't miss any map. I.e., simple as 
```
maps = StateMaps {...}
apply_writes(maps)
delete_writes(maps)
assert get_writes() == StateMaps::default()
```

(That way, the test will fail to compile when a new map is added to StateMap - which is not the case currently)
</blockquote></details>

Done.
It's still not complete since we have the `class_hash_to_class` mapping outside of the `StateMaps` (and potentially new mappings can be added that way).
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 379 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFAmIt9CqZ-0HlUjou:-NyG3M007NIvuDvIJLgD:b-71i83) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L379)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why?
It can be the same class hash, no?
</blockquote></details>

Yes, it can be any class hash that we want, but what do you save here? The macro calling? I'm trying to say that it isn't worth the potential connection that the reader might make, which can make him wonder what the connection between the two operations is and why it's relevant for this test (it's not).
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 380 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFWTiy79MN65YIu8Z3:-NyFmRoh53F6Zh3qjx9D:bss4a2b) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L380)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Is this necessary?
</blockquote></details>

Removed.
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy_test.rs` line 385 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NyFVrVJ5yhWruacI0Yu:-NyFmZCi-z6TfvlHP7mG:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/66b9e708afc0b4cc392ef24280f90a32d2ed6f0e/crates/blockifier/src/concurrency/versioned_state_proxy_test.rs#L385)):*
> ```XML
>             tx_state.set_class_hash_at(*contract_address, *class_hash).unwrap();
>         }
>         // Modify the `class_hash_to_class` memboer of the CachedState.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-05-19 14:37 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: 3 of 7 files reviewed, 6 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 19 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwGU8_35Izi_Z5S1lw:-NyGFMtl5nEVfTHTDwDW:bsmdsup) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L19)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I'm unsure I understand what to write in the documentation for this contact. Can you suggest?
</blockquote></details>

No need, it's an arbitrary address for testing
___
*[`crates/blockifier/src/concurrency/versioned_state_proxy.rs` line 165 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxScKMC1vF-Q8-vAzhJ:-NyGH1Y_DsH416P8cTSa:b-taxip7) ([raw file](https://github.com/starkware-libs/blockifier/blob/5ff57c5e0ecd0fc988aecfb92b8697d19da52cca/crates/blockifier/src/concurrency/versioned_state_proxy.rs#L165)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

WDYM? Do you want to remove the `write` method from `VersionedStorage`?
</blockquote></details>

If it's not needed by itself בדיעבד - maybe


<!-- Sent from Reviewable.io -->

2024-05-19 14:59 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 4 files at r11, 4 of 5 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-:-NyGMJJHEnsHIGtp89GM:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @MohammadNassar1, @noaov1, and @OriStarkware)



<!-- Sent from Reviewable.io -->

2024-05-19 15:09 UTC, noaov1 approved these changes
> Reviewed 4 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: all files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1 and @OriStarkware)



<!-- Sent from Reviewable.io -->

2024-05-19 15:10 UTC, noaov1 submitted a review, later dismissed
> Reviewed 1 of 5 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: all files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1 and @OriStarkware)



<!-- Sent from Reviewable.io -->

2024-05-20 10:14 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 26 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-NxwHjMW66tXUhiTATFE:-NyKUeOO0irhlJwaTqWx:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2c2448fae6c4921d9de5d555edcc1c03a71b28e0/crates/blockifier/src/concurrency/test_utils.rs#L26)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

I suggest we either move the constant to the beginning of the file or define the const inside the fixture.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-20 10:22 UTC, OriStarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 5 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1892#-:-NyKWQCFErV5nAFnNgaW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)



<!-- Sent from Reviewable.io -->

2024-05-20 11:57 UTC, merged