test(concurrency): write a test for commit transaction
starkware-libs/blockifier pull request #1893
Opened 2024-05-09 14:32 UTC by meship-starkware

2024-05-15 11:53 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 195 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nxw59cw7j-34vZU27t4:-Nxw59cw7j-34vZU27t5:b-hn8ndn) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea060da1cb8bb7636e914fa1fac7a00d21f17c05/crates/blockifier/src/concurrency/worker_logic_test.rs#L195)):*
> ```XML
>     }
> }
> ```

Ignore this test. For some reason, it does not accept this as the change of the previous PR. It is only relevant for this PR [https://reviewable.io/reviews/starkware-libs/blockifier/1870](https://reviewable.io/reviews/starkware-libs/blockifier/1870)


<!-- Sent from Reviewable.io -->

2024-05-26 14:49 UTC, avi-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 107 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypM0yz9M3nZFtrF3tK:-NypM0yz9M3nZFtrF3tL:b1b5cx3) ([raw file](https://github.com/starkware-libs/blockifier/blob/9218f7352605220d0b18d2b9e26223af3d5efc8f/crates/blockifier/src/concurrency/worker_logic_test.rs#L107)):*
> ```XML
> 
> #[fixture]
> fn defulted_execution_task_output() -> ExecutionTaskOutput {
> ```

Where do you use this fixture?



_Suggestion:_
```XML
fn default_execution_task_output() -> ExecutionTaskOutput {
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 172 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypL9bkCKz4VLY72fjh:-NypL9bkCKz4VLY72fji:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9218f7352605220d0b18d2b9e26223af3d5efc8f/crates/blockifier/src/concurrency/worker_logic_test.rs#L172)):*
> ```XML
>     let mut sequencer_balance = 0_u128;
> 
>     // create transactions
> ```





_Suggestion:_
```XML
// Create transactions.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 209 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypKxGo3PWZVToYFUlP:-NypKxGo3PWZVToYFUlQ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9218f7352605220d0b18d2b9e26223af3d5efc8f/crates/blockifier/src/concurrency/worker_logic_test.rs#L209)):*
> ```XML
>         execution_outputs: execution_task_output,
>         scheduler: Scheduler::default(),
>     };
> ```





_Suggestion:_
```XML
    // create executor for commit tx test.
    let execution_task_output: Box<[Mutex<Option<ExecutionTaskOutput>>]> =
        execution_task_output_vec.into_boxed_slice();
    let executor = WorkerExecutor {
        state: versioned_state,
        chunk: &transactions_array,
        block_context,
        execution_outputs: execution_task_output,
        scheduler: Scheduler::default(),
    };
```


<!-- Sent from Reviewable.io -->

2024-05-26 15:23 UTC, avi-starkware requested changes
> Reviewed 1 of 6 files at r1, 1 of 4 files at r2, 5 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 189 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypNobT4cVzAl12eB6i:-NypNobT4cVzAl12eB6j:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9218f7352605220d0b18d2b9e26223af3d5efc8f/crates/blockifier/src/concurrency/worker_logic_test.rs#L189)):*
> ```XML
>         // flow: failed execute -> failed revalidate -> passed re-execute ->fixed and commit.
>         Transaction::AccountTransaction(trivial_call_data_transaction(account, 4_u16)),
>     ];
> ```





_Suggestion:_
```XML
    let txs = [
        // flow: pass execute -> pass re-validate ->  fixed and commit.
        Transaction::AccountTransaction(trivial_call_data_tx(account, 0_u16)),
        // flow: pass execute -> fail re-validate ->  pass re-executed -> fixed and commit.
        Transaction::AccountTransaction(sequencer_transfer_tx(
            account,
            &block_context,
            1_u16,
            transfer_ammount,
        )),
        // flow: failed execute -> pass re-validate -> commit.
        Transaction::AccountTransaction(invalid_tx(account, 2_u16)),
        // flow: passed execute ->  failed re-validate ->  failed re-execute (rejected) -> commit.
        Transaction::AccountTransaction(trivial_call_data_tx(account, 3_u16)),
        // flow: failed execute -> failed revalidate -> passed re-execute ->fixed and commit.
        Transaction::AccountTransaction(trivial_call_data_tx(account, 4_u16)),
    ];
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 200 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypO6gA-Qe-U1cFmz99:-NypO6gB22x6kbiADCqu:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/9218f7352605220d0b18d2b9e26223af3d5efc8f/crates/blockifier/src/concurrency/worker_logic_test.rs#L200)):*
> ```XML
>         (0..transactions_array.len()).map(|_| Mutex::new(Option::None)).collect();
> 
>     // create executer for commit tx test.
> ```





_Suggestion:_
```XML
   // Create executor.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 220 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypOi33Ewy6hZ549dP3:-NypOi33Ewy6hZ549dP4:b-touxm8) ([raw file](https://github.com/starkware-libs/blockifier/blob/9218f7352605220d0b18d2b9e26223af3d5efc8f/crates/blockifier/src/concurrency/worker_logic_test.rs#L220)):*
> ```XML
>                 executer.block_context.chain_info.fee_token_address(&FeeType::Strk),
>                 StarkFelt::ZERO,
>             );
> ```

Add a comment explaining why the account balance needs to change for transaction 4.



_Code quote:_
```XML
            change_account_balance(
                account,
                &mut executer.state.pin_version(tx_index - 1),
                4_u16,
                executer.block_context.chain_info.fee_token_address(&FeeType::Strk),
                StarkFelt::ZERO,
            );
```


<!-- Sent from Reviewable.io -->

2024-05-26 15:45 UTC, avi-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: 7 of 8 files reviewed, 11 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 223 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypWGyzE07DbD5Oek81:-NypWGyzE07DbD5Oek82:b-yfj7w3) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L223)):*
> ```XML
>     // Test commit tx after execution for txes with flows:
>     // Flow1: pass execute -> pass re-validate ->  fix and commit.
>     // Flow2: pass execute -> fail re-validate ->  pass re-executed -> fixed and commit.
> ```

In the second flow, how can you tell that the transaction was re-executed?
Shouldn't something different happen compared to the first flow?



_Suggestion:_
```XML
    // Test commit tx for txs 0 and 1 with the following expected flows:
    // tx 0: pass execute -> pass re-validate ->  fix and commit.
    // tx 1: pass execute -> fail re-validate ->  pass re-executed -> fixed and commit.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 226 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypXtXf8z8j76bU1Jh1:-NypXtXgEE-vkvu1eJoZ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L226)):*
> ```XML
>     let account_balance = BALANCE;
>     for (tx_index, transfer_ammount, account_id) in
>         [(0, 0_u128, 0_u16), (1, transfer_ammount, 1_u16)]
> ```





_Suggestion:_
```XML
    for (tx_index, transfer_amount, account_id) in
        [(0, 0_u128, 0_u16), (1, transfer_amount, 1_u16)]
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 268 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypYWxAEK1jNcj7RaLs:-NypYWxAEK1jNcj7RaLt:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L268)):*
> ```XML
> 
>     // Test commit tx after execution for tx with flow:
>     // failed execute -> pass re-validate -> commit.
> ```





_Suggestion:_
```XML
    // Test commit tx for tx 2 with the following expected flow:
    // failed execute -> pass re-validate -> commit.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 303 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypZ-5QA4kmYweQkwnz:-NypZ-5QA4kmYweQkwo-:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L303)):*
> ```XML
> 
>     // Test commit tx after execution for tx with flow:
>     // passed execute ->  failed re-validate ->  failed re-execute (rejected) -> commit.
> ```





_Suggestion:_
```XML
    // Test commit tx for tx 3 with the following expected flow:
    // passed execute ->  failed re-validate ->  failed re-execute (rejected) -> commit.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 336 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypZeSSEvxiOlf0rfh-:-NypZeSSEvxiOlf0rfh0:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L336)):*
> ```XML
>     assert!(execution_result.is_err());
>     drop(execution_task_outputs);
>     // Check fee transfer after commit. all changes should be reverted in this case.
> ```





_Suggestion:_
```XML
  // Check fee transfer after commit. All changes should be reverted in this case.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 346 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypZiBM-sxmsnJw3QKE:-NypZiBM-sxmsnJw3QKF:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L346)):*
> ```XML
> 
>     // Test commit tx after execution for tx with flow:
>     // failed execute -> failed revalidate -> passed re-execute -> commit.
> ```





_Suggestion:_
```XML
    // Test commit tx for tx 4 with the following expected flow:
    // failed execute -> failed revalidate -> passed re-execute -> commit.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 374 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypVh_JC6tKH4r7Ff_3:-NypVh_JC6tKH4r7Ff_4:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L374)):*
> ```XML
>     let execution_task_outputs = lock_mutex_in_array(&executor.execution_outputs, tx_index);
>     let actual_fee = get_actual_fee(&execution_task_outputs);
>     // Check fee transfer after commit. both the account and sequencer balance should be apdated.
> ```





_Suggestion:_
```XML
 // Check fee transfer after commit. Both the account and sequencer balance should be updated.
```


<!-- Sent from Reviewable.io -->

2024-05-26 15:48 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 35 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nyp_f4n5GEOvXmdyHAK:-Nyp_f4n5GEOvXmdyHAL:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L35)):*
> ```XML
> use crate::{invoke_tx_args, nonce, storage_key};
> 
> fn trivial_call_data_transaction(
> ```





_Suggestion:_
```XML
fn trivial_calldata_transaction(
```


<!-- Sent from Reviewable.io -->

2024-05-27 05:20 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 63 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NysUbp4-JrVv3gaaZAi:-NysUbp4-JrVv3gaaZAj:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L63)):*
> ```XML
>         TRANSFER_ENTRY_POINT_NAME,
>         &[*sequencer_address.0.key(), stark_felt!(transfer_ammount), stark_felt!(0_u8)],
>     );
> ```





_Suggestion:_
```XML
fn sequencer_transfer_transaction(
    account: FeatureContract,
    block_context: &BlockContext,
    instance_id: u16,
    transfer_amount: u128,
    nonce_manager: &mut NonceManager,
) -> AccountTransaction {
    let sequencer_address = block_context.block_info.sequencer_address;
    let account_address = account.get_instance_address(instance_id);
    let transfer_calldata = create_calldata(
        block_context.chain_info().fee_token_address(&FeeType::Strk),
        TRANSFER_ENTRY_POINT_NAME,
        &[*sequencer_address.0.key(), stark_felt!(transfer_amount), stark_felt!(0_u8)],
    );
```


<!-- Sent from Reviewable.io -->

2024-05-27 05:42 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 122 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NysZXHWBfl8pQfyu8fP:-NysZXHWBfl8pQfyu8fQ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L122)):*
> ```XML
> fn change_account_balance(
>     account: FeatureContract,
>     version_state: &mut VersionedStateProxy<impl StateReader>,
> ```





_Suggestion:_
```XML
    versioned_state: &mut VersionedStateProxy<impl StateReader>,
```


<!-- Sent from Reviewable.io -->

2024-05-27 07:09 UTC, avi-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: 7 of 8 files reviewed, 17 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 88 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NysVCaaDQ1L8qVxqPBB:-NysVCaaDQ1L8qVxqPBC:b-6trhhh) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L88)):*
> ```XML
>         nonce: nonce_manager.next(account_address),
>     })
> }
> ```

What makes this transaction invalid? The fact that it has no calldata?
Please explain in a comment.



_Suggestion:_
```XML
fn invalid_transaction(
    account: FeatureContract,
    instance_id: u16,
    nonce_manager: &mut NonceManager,
) -> AccountTransaction {
    let account_address = account.get_instance_address(instance_id);
    account_invoke_tx(invoke_tx_args! {
        sender_address: account_address,
        resource_bounds: l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE),
        version: TransactionVersion::THREE,
        nonce: nonce_manager.next(account_address),
    })
}
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 102 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NysXOtSDpcH4yH77qwL:-NysXOtSDpcH4yH77qwM:b4b9bv4) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L102)):*
> ```XML
>     let (sequencer_balance_key_low, sequencer_balance_key_high) =
>         get_sequencer_balance_keys(block_context);
>     // Check that before commiting the sender balance is updated and the sequencer balance is not.
> ```

This comment refers to things outside the scope of the function. The function doesn't have any commit logic; it simply compares the expected values it is given with the values in storage.

I think this comment belongs in the body of the test, if at all.



_Code quote:_
```XML
    // Check that before commiting the sender balance is updated and the sequencer balance is not.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 120 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nysbj-UA_DrWDtsvXtW:-Nysbj-UA_DrWDtsvXtX:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L120)):*
> ```XML
> }
> 
> fn change_account_balance(
> ```





_Suggestion:_
```XML
fn write_account_balance_at_versioned_state(
```


<!-- Sent from Reviewable.io -->

2024-05-28 06:58 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: 6 of 8 files reviewed, 16 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 189 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypNobT4cVzAl12eB6i:-NyxycY81QEBwUe80jbU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9218f7352605220d0b18d2b9e26223af3d5efc8f/crates/blockifier/src/concurrency/worker_logic_test.rs#L189)):*
> ```XML
>         // flow: failed execute -> failed revalidate -> passed re-execute ->fixed and commit.
>         Transaction::AccountTransaction(trivial_call_data_transaction(account, 4_u16)),
>     ];
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 200 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypO6gA-Qe-U1cFmz99:-Nyxygi01eSEqqZbR5t-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9218f7352605220d0b18d2b9e26223af3d5efc8f/crates/blockifier/src/concurrency/worker_logic_test.rs#L200)):*
> ```XML
>         (0..transactions_array.len()).map(|_| Mutex::new(Option::None)).collect();
> 
>     // create executer for commit tx test.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 220 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypOi33Ewy6hZ549dP3:-NyxyiJ5BeAoZOZtdfFD:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9218f7352605220d0b18d2b9e26223af3d5efc8f/crates/blockifier/src/concurrency/worker_logic_test.rs#L220)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Add a comment explaining why the account balance needs to change for transaction 4.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 35 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nyp_f4n5GEOvXmdyHAK:-NyxwzCj9M8Z6w7N5Qld:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L35)):*
> ```XML
> use crate::{invoke_tx_args, nonce, storage_key};
> 
> fn trivial_call_data_transaction(
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 63 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NysUbp4-JrVv3gaaZAi:-NyxwzftBUYOQQ90abLn:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L63)):*
> ```XML
>         TRANSFER_ENTRY_POINT_NAME,
>         &[*sequencer_address.0.key(), stark_felt!(transfer_ammount), stark_felt!(0_u8)],
>     );
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 88 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NysVCaaDQ1L8qVxqPBB:-Nyxxqa-2I8jeKqtHkqi:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L88)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

What makes this transaction invalid? The fact that it has no calldata?
Please explain in a comment.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 120 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nysbj-UA_DrWDtsvXtW:-NyxyYODAz4Z_mybu4ls:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L120)):*
> ```XML
> }
> 
> fn change_account_balance(
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 122 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NysZXHWBfl8pQfyu8fP:-NyxyYpK75QZqp_l6CmU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L122)):*
> ```XML
> fn change_account_balance(
>     account: FeatureContract,
>     version_state: &mut VersionedStateProxy<impl StateReader>,
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 223 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypWGyzE07DbD5Oek81:-NyxzHB5B2cHnLMu1bVz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L223)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

In the second flow, how can you tell that the transaction was re-executed?
Shouldn't something different happen compared to the first flow?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 226 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypXtXf8z8j76bU1Jh1:-NyxyxNe7mze-wb0F2BM:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L226)):*
> ```XML
>     let account_balance = BALANCE;
>     for (tx_index, transfer_ammount, account_id) in
>         [(0, 0_u128, 0_u16), (1, transfer_ammount, 1_u16)]
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 268 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypYWxAEK1jNcj7RaLs:-NyxzE0x5xIT7s3yKorI:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L268)):*
> ```XML
> 
>     // Test commit tx after execution for tx with flow:
>     // failed execute -> pass re-validate -> commit.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 303 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypZ-5QA4kmYweQkwnz:-Nyxyub_4Qw6P5u7RUeL:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L303)):*
> ```XML
> 
>     // Test commit tx after execution for tx with flow:
>     // passed execute ->  failed re-validate ->  failed re-execute (rejected) -> commit.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 336 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypZeSSEvxiOlf0rfh-:-NyxysvK1F-7M2krUX3l:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L336)):*
> ```XML
>     assert!(execution_result.is_err());
>     drop(execution_task_outputs);
>     // Check fee transfer after commit. all changes should be reverted in this case.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 346 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypZiBM-sxmsnJw3QKE:-NyxzEpx0LrPN1Ae7LZy:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L346)):*
> ```XML
> 
>     // Test commit tx after execution for tx with flow:
>     // failed execute -> failed revalidate -> passed re-execute -> commit.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 374 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NypVh_JC6tKH4r7Ff_3:-NyxyrUa8j8WpyBr1vBl:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L374)):*
> ```XML
>     let execution_task_outputs = lock_mutex_in_array(&executor.execution_outputs, tx_index) [...]

2024-05-28 07:02 UTC, meship-starkware reviewed
I changed many of the comments, so I marked done over all the things I thought were no longer relevant.
If you think I ignored some crucial comments, feel free to tell me. 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-:-NyxzdA9E1lmf8OiE412:biiebd3)* status: 6 of 8 files reviewed, 16 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 102 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NysXOtSDpcH4yH77qwL:-NyxzbYH13op2euqNOct:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e9c306ef1bc909e800ec1271fb1eab17bf8e14af/crates/blockifier/src/concurrency/worker_logic_test.rs#L102)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

This comment refers to things outside the scope of the function. The function doesn't have any commit logic; it simply compares the expected values it is given with the values in storage.

I think this comment belongs in the body of the test, if at all.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-30 12:27 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 251 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nz8SyqXBppOqRvGpOki:-Nz8SyqXBppOqRvGpOkj:b-83sjoh) ([raw file](https://github.com/starkware-libs/blockifier/blob/aab0ad43bbd218017631457f64a9a5321c013e39/crates/blockifier/src/concurrency/worker_logic_test.rs#L251)):*
> ```XML
>     .into_iter()
>     .map(Transaction::AccountTransaction)
>     .collect::<Vec<Transaction>>();
> ```

Nice!



_Code quote:_
```XML
    .into_iter()
    .map(Transaction::AccountTransaction)
    .collect::<Vec<Transaction>>();
```


<!-- Sent from Reviewable.io -->

2024-05-30 12:34 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 295 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nz8TdyKCyGv_xybA6vf:-Nz8TdyKCyGv_xybA6vg:b-qe4zq6) ([raw file](https://github.com/starkware-libs/blockifier/blob/aab0ad43bbd218017631457f64a9a5321c013e39/crates/blockifier/src/concurrency/worker_logic_test.rs#L295)):*
> ```XML
>     // This is an invoke transaction with calldata that transfers an amount to the sequencer
>     // balance. We change the sequencer balance in the write set, thus the transaction should
>     // fail the re-validate in the commit phase, but pass the re-execute.
> ```

The phrase "We change the sequencer balance in the write set" is not clear, but I am not sure what to change it to. When do we change the balance? Why does it make validation fail?



_Suggestion:_
```XML
    // This transaction transfers funds to the sequencer. We change the sequencer balance in the write set, 
    // thus the transaction should fail the re-validate in the commit phase but pass the re-execute.
```


<!-- Sent from Reviewable.io -->

2024-05-30 12:39 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 326 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nz8UvXv1v3uZ6nRx7D8:-Nz8UvXv1v3uZ6nRx7D9:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/aab0ad43bbd218017631457f64a9a5321c013e39/crates/blockifier/src/concurrency/worker_logic_test.rs#L326)):*
> ```XML
>     // This is an invoke transaction with no call data, thus it should fail execution,
>     // we do not change any values in the read and write sets, thus the transaction should pass the
>     // re-validate in the commit phase.
> ```





_Suggestion:_
```XML
    // This is an invalid transaction, so it should fail execution.
    // We do not change any values in the read and write sets. Thus, the transaction should pass
    // re-validation in the commit phase.
```


<!-- Sent from Reviewable.io -->

2024-05-30 12:39 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 352 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nz8VNhz8bPNPa4x-i8s:-Nz8VNhz8bPNPa4x-i8t:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/aab0ad43bbd218017631457f64a9a5321c013e39/crates/blockifier/src/concurrency/worker_logic_test.rs#L352)):*
> ```XML
>     );
> 
>     sequencer_balance_low += actual_fee;
> ```





_Suggestion:_
```XML
    );
    sequencer_balance_low += actual_fee;
```


<!-- Sent from Reviewable.io -->

2024-05-30 12:42 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 357 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nz8VXmyDo3ad4L-pZK2:-Nz8VXmz3_HSKcngkZIL:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/aab0ad43bbd218017631457f64a9a5321c013e39/crates/blockifier/src/concurrency/worker_logic_test.rs#L357)):*
> ```XML
>     // commit. This is an invoke transaction with trivial calldata. we change the account
>     // balance in the write set, thus the transaction should fail the re-validate in the commit
>     // phase, and becuse the ne account balance is zero, the re-execute should fail as well.
> ```





_Suggestion:_
```XML
    // commit. This is an invoke transaction with trivial calldata. We manually change the account
    // balance in the write set post-execution to make the transaction fail the re-validate in the commit
    // phase. The re-execute should fail as well, because we set the account balance to zero.
```


<!-- Sent from Reviewable.io -->

2024-05-30 12:42 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 385 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nz8WYG60iyKxmHhLvgX:-Nz8WYG60iyKxmHhLvgY:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/aab0ad43bbd218017631457f64a9a5321c013e39/crates/blockifier/src/concurrency/worker_logic_test.rs#L385)):*
> ```XML
>     executor.commit_tx(tx_index).unwrap();
> 
>     should_fail = true;
> ```





_Suggestion:_
```XML
    let should_fail = true;
```


<!-- Sent from Reviewable.io -->

2024-05-30 12:45 UTC, avi-starkware requested changes
> Reviewed 1 of 6 files at r9, 4 of 5 files at r10, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: all files reviewed, 6 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 401 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nz8Wl6tDkg7ok2ACqTZ:-Nz8Wl6tDkg7ok2ACqT_:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/aab0ad43bbd218017631457f64a9a5321c013e39/crates/blockifier/src/concurrency/worker_logic_test.rs#L401)):*
> ```XML
>     // This is an invoke transaction with trivial calldata. we change the account balance to zero
>     // before the first execution, thus the transaction should fail the execution, then we change
>     // the account balance back to BALANCE, thus the transaction should fail re-validate and pass
> ```





_Suggestion:_
```XML
    // tx4: failed execute -> failed revalidate -> passed re-execute -> commit.
    // This is an invoke transaction with trivial calldata. We manually change the account balance to zero
    // before the first execution to make the transaction fail the execution, then we change
    // the account balance back to BALANCE, to make the transaction fail re-validate and pass
```


<!-- Sent from Reviewable.io -->

2024-05-30 14:06 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: 7 of 8 files reviewed, 6 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 295 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nz8TdyKCyGv_xybA6vf:-Nz8fqmoEoIt0wOnQkMM:b61u37i) ([raw file](https://github.com/starkware-libs/blockifier/blob/aab0ad43bbd218017631457f64a9a5321c013e39/crates/blockifier/src/concurrency/worker_logic_test.rs#L295)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

The phrase "We change the sequencer balance in the write set" is not clear, but I am not sure what to change it to. When do we change the balance? Why does it make validation fail?
</blockquote></details>

I tried to explain it, got confused, checked again to see that it failed to re-validate, and discovered it passed. So, right now, this case is the same as tx0. @noaov1 I would like your thoughts about it. For now, we can change the account balance after execution for this test as well.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 326 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nz8UvXv1v3uZ6nRx7D8:-Nz8mgH_EqfOn9ozFjAO:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/aab0ad43bbd218017631457f64a9a5321c013e39/crates/blockifier/src/concurrency/worker_logic_test.rs#L326)):*
> ```XML
>     // This is an invoke transaction with no call data, thus it should fail execution,
>     // we do not change any values in the read and write sets, thus the transaction should pass the
>     // re-validate in the commit phase.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 352 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nz8VNhz8bPNPa4x-i8s:-Nz8mgkZ9jFO3NJczibf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/aab0ad43bbd218017631457f64a9a5321c013e39/crates/blockifier/src/concurrency/worker_logic_test.rs#L352)):*
> ```XML
>     );
> 
>     sequencer_balance_low += actual_fee;
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 357 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nz8VXmyDo3ad4L-pZK2:-Nz8mh5Q8mluaDxwYwwL:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/aab0ad43bbd218017631457f64a9a5321c013e39/crates/blockifier/src/concurrency/worker_logic_test.rs#L357)):*
> ```XML
>     // commit. This is an invoke transaction with trivial calldata. we change the account
>     // balance in the write set, thus the transaction should fail the re-validate in the commit
>     // phase, and becuse the ne account balance is zero, the re-execute should fail as well.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 385 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nz8WYG60iyKxmHhLvgX:-Nz8mh_GDqHg8XwaZC9i:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/aab0ad43bbd218017631457f64a9a5321c013e39/crates/blockifier/src/concurrency/worker_logic_test.rs#L385)):*
> ```XML
>     executor.commit_tx(tx_index).unwrap();
> 
>     should_fail = true;
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 401 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nz8Wl6tDkg7ok2ACqTZ:-Nz8mi1bDJ7RIVxwPOoh:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/aab0ad43bbd218017631457f64a9a5321c013e39/crates/blockifier/src/concurrency/worker_logic_test.rs#L401)):*
> ```XML
>     // This is an invoke transaction with trivial calldata. we change the account balance to zero
>     // before the first execution, thus the transaction should fail the execution, then we change
>     // the account balance back to BALANCE, thus the transaction should fail re-validate and pass
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-05-30 14:18 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 416 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nz8rSwiDN7dpyCktAvX:-Nz8rSwiDN7dpyCktAvY:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c96d815bf218b48e265a8bda5a314c4f998866b3/crates/blockifier/src/concurrency/worker_logic_test.rs#L416)):*
> ```XML
>     // to zero before the first execution to make the transaction fail the execution, then we
>     // change the account balance back to BALANCE, to make the transaction fail re-validate and
>     // pass
> ```





_Suggestion:_
```XML
    // pass the re-execute in the commit phase.
```


<!-- Sent from Reviewable.io -->

2024-06-02 08:37 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 295 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nz8TdyKCyGv_xybA6vf:-NzN-rVsBYmLky7jtg3G:bgcs62s) ([raw file](https://github.com/starkware-libs/blockifier/blob/aab0ad43bbd218017631457f64a9a5321c013e39/crates/blockifier/src/concurrency/worker_logic_test.rs#L295)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I tried to explain it, got confused, checked again to see that it failed to re-validate, and discovered it passed. So, right now, this case is the same as tx0. @noaov1 I would like your thoughts about it. For now, we can change the account balance after execution for this test as well.
</blockquote></details>

Talking with Noa offline, I understood the reason it should fail is in the flow execute tx0 -> execute tx1 -> commit tx0 -> commit tx1
The reason is that when executing tx1, the sequencer balance is the sequencer balance before committing tx0 + transfer amount. When committing tx1 (after committing tx0), the sequencer balance in the read_set is the sequencer balance after committing tx0, which is different than the write set. 
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 416 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nz8rSwiDN7dpyCktAvX:-NzN52xu4p9dgxhYH6aV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c96d815bf218b48e265a8bda5a314c4f998866b3/crates/blockifier/src/concurrency/worker_logic_test.rs#L416)):*
> ```XML
>     // to zero before the first execution to make the transaction fail the execution, then we
>     // change the account balance back to BALANCE, to make the transaction fail re-validate and
>     // pass
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-06-02 15:30 UTC, avi-starkware requested changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 278 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzOZIezB7SThABfckpL:-NzOZIezB7SThABfckpM:b-gvm81w) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L278)):*
> ```XML
>     let account_id = 0_u16;
>     let account_balance = BALANCE;
>     let should_fail = false;
> ```

I think we need to change it everywhere. Currently, it is hard to understand which part of the flow "should fail".



_Suggestion:_
```XML
    let should_fail_execute = false;
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 282 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzOVwOQDlxBtOz3TKNe:-NzOVwOQDlxBtOz3TKNf:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L282)):*
> ```XML
>     executor.execute_tx(tx_index);
>     // We have to execute the next tx before commiting this tx to fail the re-validate of the
>     // next tx.
> ```





_Suggestion:_
```XML
    // Execute the tx1 before committing tx0 to fail the re-validate of tx1.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 310 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzOWBab8-SkLoFm5Kvi:-NzOWBab8-SkLoFm5Kvj:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L310)):*
> ```XML
>     // sequencer balance to be sequencer balance + transfer amount then we commit tx0 that
>     // changes the sequencer balance to be sequencer balance + actual fee, so the value changes as
>     // we revalidate the sequencer balance reads when committing tx1.
> ```





_Suggestion:_
```XML
    // tx1: pass execute -> fail re-validate ->  pass re-executed -> fixed and commit.
    // This transaction transfers funds to the sequencer, changing the sequencer balance
    // and forcing it to be a part of the read set.
    // Note that committing tx0 changed the sequencer balance after we executed tx1, making
    // inconsistent with the value in tx1's read set.
    // Therefore, the re-validate of tx1 should fail.
```


<!-- Sent from Reviewable.io -->

2024-06-02 15:31 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 310 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzOWBab8-SkLoFm5Kvi:-NzOZiRF5HOMbKIFn-H3:b-k1c258) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L310)):*
> ```XML
>     // sequencer balance to be sequencer balance + transfer amount then we commit tx0 that
>     // changes the sequencer balance to be sequencer balance + actual fee, so the value changes as
>     // we revalidate the sequencer balance reads when committing tx1.
> ```

*making it inconsistent with...


<!-- Sent from Reviewable.io -->

2024-06-02 15:39 UTC, avi-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: all files reviewed, 4 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 183 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzO_3gR8RDB64bBwrap:-NzO_3gR8RDB64bBwraq:bm8lea) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L183)):*
> ```XML
> // fee transfer callinfo was filled correctly,
> // It additionally checks that the actual fee was subtracted from the account balance
> // and added to the sequencer balance.
> ```

Please try to break lines in the middle of a sentence only when reaching the maximum line length (throughout the code). 

* Note: your formatter should insert line breaks automatically when exceeding the maximum line length.



_Suggestion:_
```XML
// This function checks the state of a transaction after committing.
// It checks that the storage read of the sequencer balance during fee transfer 
// callinfo was filled in correctly.
// It additionally checks that the actual fee was subtracted from the account balance
// and added to the sequencer balance.
```


<!-- Sent from Reviewable.io -->

2024-06-02 15:41 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 183 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzO_3gR8RDB64bBwrap:-NzOayjW76OpxeDolsoI:b1me4gj) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L183)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Please try to break lines in the middle of a sentence only when reaching the maximum line length (throughout the code). 

* Note: your formatter should insert line breaks automatically when exceeding the maximum line length.
</blockquote></details>

Sorry, don't change "in the" to "during". I misunderstood the sentence.


<!-- Sent from Reviewable.io -->

2024-06-02 15:45 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 373 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzObsw9DfqUqWcPF2dt:-NzObsw9DfqUqWcPF2du:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L373)):*
> ```XML
>     // balance in the write set post-execution to make the transaction fail the re-validate in the
>     // commit phase. The re-execute should fail as well, because we set the account balance to
>     // zero.
> ```





_Suggestion:_
```XML
    // tx3: passed execute ->  failed re-validate ->  failed re-execute (rejected) -> fixed and
    // commit. This is an invoke transaction with trivial calldata. We manually change the account
    // balance in the write set post-execution to make the transaction fail the re-validate in the
    // commit phase. The re-execute should fail as well, because we set the account balance to
    // zero, so it is insufficient for fee payment.
```


<!-- Sent from Reviewable.io -->

2024-06-02 15:47 UTC, noaov1 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: all files reviewed, 11 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 247 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzOInct-n7ZZPhxBDNL:-NzOIncu4uVfyjNV8iGi:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L247)):*
> ```XML
> 
>     // Create transactions.
>     let transactions_array = [
> ```





_Suggestion:_
```XML
    let txs = [
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 248 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzOI4HD6JVZ85WQHdbm:-NzOI4HD6JVZ85WQHdbn:b-pa4dvt) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L248)):*
> ```XML
>     // Create transactions.
>     let transactions_array = [
>         trivial_calldata_invoke_tx(account.get_instance_address(0_u16), &mut nonce_manager),
> ```

Please change it in the entire file.



_Suggestion:_
```XML
trivial_calldata_invoke_tx(account.get_instance_address(0), &mut nonce_manager),
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 253 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzOII9x8hGkhlD1pFCM:-NzOII9x8hGkhlD1pFCN:b-kpvzgp) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L253)):*
> ```XML
>             &block_context,
>             transfer_amount,
>             &mut nonce_manager,
> ```

Do you need to pass the same nonce manager?
You use a different account
Why do you use different accounts?



_Code quote:_
```XML
            &mut nonce_manager,
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 271 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzONnzQDq7EiKxv-B8C:-NzONnzQDq7EiKxv-B8D:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L271)):*
> ```XML
>     let mut executor = WorkerExecutor::new(versioned_state, &transactions_array, block_context);
> 
>     // tx0: pass execute -> pass re-validate ->  fix and commit.
> ```





_Suggestion:_
```XML
    // Sucsseful execution. Re-validate in the commit phase pass.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 283 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzOOzjd-5DxJR0tdQhb:-NzOOzjd-5DxJR0tdQhc:b3aikmh) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L283)):*
> ```XML
>     // We have to execute the next tx before commiting this tx to fail the re-validate of the
>     // next tx.
>     executor.execute_tx(tx_index + 1);
> ```

Is it possible to execute all the transaction at the beginning?



_Code quote:_
```XML
    // We have to execute the next tx before commiting this tx to fail the re-validate of the
    // next tx.
    executor.execute_tx(tx_index + 1);
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 306 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzONvsw3WfosPaZRE3w:-NzONvsw3WfosPaZRE3x:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L306)):*
> ```XML
>     sequencer_balance_low += actual_fee;
> 
>     // tx1: pass execute -> fail re-validate ->  pass re-executed -> fixed and commit.
> ```





_Suggestion:_
```XML
    // Successful execution.Re-validate n the commit phase pass, re-execution pass.
```


<!-- Sent from Reviewable.io -->

2024-06-02 15:51 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 283 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzOOzjd-5DxJR0tdQhb:-NzOcu3d5oC9SLdnBBug:b9xjxuc) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L283)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it possible to execute all the transaction at the beginning?
</blockquote></details>

This is what was done initially. The problem was that we needed to change the account balance manually before tx4, which needed a weird condition that is hard to explain out of context.


<!-- Sent from Reviewable.io -->

2024-06-02 15:53 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 271 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzONnzQDq7EiKxv-B8C:-NzOdTxf2k_zYHu-cZ99:bjyucvh) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L271)):*
> ```XML
>     let mut executor = WorkerExecutor::new(versioned_state, &transactions_array, block_context);
> 
>     // tx0: pass execute -> pass re-validate ->  fix and commit.
> ```

Noa please take a look at all the comment before, suggesting changes to these "flow comments".
I think it will be harder to parse and compare the cases as a sentence like you suggest.


<!-- Sent from Reviewable.io -->

2024-06-03 08:32 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: 7 of 8 files reviewed, 8 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 253 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzOII9x8hGkhlD1pFCM:-NzRxgs4-unZCTosQzjk:bjum6vq) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L253)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do you need to pass the same nonce manager?
You use a different account
Why do you use different accounts?
</blockquote></details>

So that I won't have to remember the changes I did with the account balance in every tx, I can use the same account and keep track of the balance changes. 
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 278 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzOZIezB7SThABfckpL:-NzRxbDqDKGlZpLVEbdD:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L278)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I think we need to change it everywhere. Currently, it is hard to understand which part of the flow "should fail".
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 282 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzOVwOQDlxBtOz3TKNe:-NzRxbWc4Oy6xC9FZA3k:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L282)):*
> ```XML
>     executor.execute_tx(tx_index);
>     // We have to execute the next tx before commiting this tx to fail the re-validate of the
>     // next tx.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 310 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzOWBab8-SkLoFm5Kvi:-NzRxJCI4EUNzdWe4gWL:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L310)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

*making it inconsistent with...
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 373 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzObsw9DfqUqWcPF2dt:-NzRxJtX3zGbrqsjWJh8:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L373)):*
> ```XML
>     // balance in the write set post-execution to make the transaction fail the re-validate in the
>     // commit phase. The re-execute should fail as well, because we set the account balance to
>     // zero.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-06-03 13:02 UTC, avi-starkware approved these changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: all files reviewed, 4 unresolved discussions (waiting on @meship-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-06-05 13:03 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 253 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzOII9x8hGkhlD1pFCM:-NzcUquXDbkVvW3tdrJy:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L253)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

So that I won't have to remember the changes I did with the account balance in every tx, I can use the same account and keep track of the balance changes.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 283 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzOOzjd-5DxJR0tdQhb:-NzcUtgP1G75P7N2sMNE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6b1b60e52ac406e2d1b1673485bb99f14a9a8f7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L283)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

This is what was done initially. The problem was that we needed to change the account balance manually before tx4, which needed a weird condition that is hard to explain out of context.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-06 08:31 UTC, avi-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 112 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzgXpaFAG3Wy6LGxO6X:-NzgXpaFAG3Wy6LGxO6Y:b6gk9go) ([raw file](https://github.com/starkware-libs/blockifier/blob/574cc104597989fca81de60e12ca7f217d5d4b8c/crates/blockifier/src/concurrency/worker_logic_test.rs#L112)):*
> ```XML
>     // nonce of 0 therefore executing tx1 before tx0 should fail it. tx2 has the nonce of 1, so
>     // executing it after tx0 should succeed. tx3 has a nonce of 10 where there are only four
>     // transactions, so it should fail regardless of the execution order.
> ```

Making these descriptions follow a consistent pattern would make them easier to parse.



_Suggestion:_
```XML
    // Imply a concurrent run by executing tx1 before tx0.
    // tx1 should fail execution since it has a nonce of 1, and it is being executed before tx0, which has a nonce of 0.
    // tx0 should pass execution.
    // tx2 should pass execution since it has a nonce of 1, so executing it after tx0 should succeed.
    // tx3 should fail execution regardless of execution order, since it has a nonce of 10 where
    // there are only four transactions.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 128 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzgYGyl3FvUpLvsPZpk:-NzgYGym2Xfvi-BwIOCf:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/574cc104597989fca81de60e12ca7f217d5d4b8c/crates/blockifier/src/concurrency/worker_logic_test.rs#L128)):*
> ```XML
>     // commit. note that when tx1 re-executed it chenges the nonce value thus tx2 should fail the
>     // re-validation then when re-executing it should fail becuse it has the same nonce as tx1.
>     // tx3 should pass re-validation and commit.
> ```





_Suggestion:_
```XML
    // Commit all transactions in sequential order. 
    // * tx0 should pass revalidation, fix the sequencer balance, fix the callinfo (fee transfer) and commit. 
    // * tx1 should fail re-validation since its read-set contains the nonce from before tx0 incremented it. 
    //   tx1 should pass re-execution (since tx0 incremented the nonce), fix the sequencer balance, fix the 
    //   callinfo (fee transfer) and commit.
    // * tx2 should fail re-validation since its read-set contains the nonce from before tx1 re-executed and
    //   incremented it. tx2 should fail re-execution because it has the same nonce as tx1.
    // * tx3 should pass re-validation and commit.
```


<!-- Sent from Reviewable.io -->

2024-06-06 08:34 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 161 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzgfnZICXkiQRvk4JnR:-NzgfnZICXkiQRvk4JnS:b-j80z95) ([raw file](https://github.com/starkware-libs/blockifier/blob/574cc104597989fca81de60e12ca7f217d5d4b8c/crates/blockifier/src/concurrency/worker_logic_test.rs#L161)):*
> ```XML
>             }
>         }
>         drop(execution_task_outputs);
> ```

Do you still need to drop it?



_Code quote:_
```XML
        drop(execution_task_outputs);
```


<!-- Sent from Reviewable.io -->

2024-06-06 08:34 UTC, avi-starkware reviewed
> Reviewed 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: all files reviewed, 5 unresolved discussions (waiting on @meship-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-06-06 09:41 UTC, avi-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-:-Nzgv7ZkAyGQ9DVlCQ64:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-06-06 12:15 UTC, noaov1 approved these changes
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: all files reviewed, 11 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 107 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nzh0UtQEBaZGAX1Aejk:-Nzh0UtRAEDosGlHmpZc:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/20be25f3a9213821d93e25868fd0fff2400728c3/crates/blockifier/src/concurrency/worker_logic_test.rs#L107)):*
> ```XML
>         test_state(&block_context.chain_info, expected_account_balance, &[(account, 1)]);
>     let versioned_state = safe_versioned_state_for_testing(cached_state);
>     let executor = WorkerExecutor::new(versioned_state, &txs, block_context);
> ```





_Suggestion:_
```XML
    
    let cached_state =
        test_state(&block_context.chain_info, expected_account_balance, &[(account, 1)]);
    let versioned_state = safe_versioned_state_for_testing(cached_state);
    let executor = WorkerExecutor::new(versioned_state, &txs, block_context);
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 116 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nzh0i_iE5qCie2xE81q:-Nzh0i_iE5qCie2xE81r:b-83sjoh) ([raw file](https://github.com/starkware-libs/blockifier/blob/20be25f3a9213821d93e25868fd0fff2400728c3/crates/blockifier/src/concurrency/worker_logic_test.rs#L116)):*
> ```XML
>     // succeed.
>     // tx3 should fail execution regardless of execution order, since it has a nonce
>     // of 10 where there are only four transactions.
> ```

Nice!



_Suggestion:_
```XML
    // Execute transactions.
    // Simulate a concurrent run by executing tx1 before tx0.
    // tx1 should fail execution since it has nonce equals 1, and it is being executed before tx0,
    // which has nonce eqauls 0.
    // tx0 should pass execution.
    // tx2 should pass execution since it has nonce equals 1, so executing it after tx0 should
    // succeed.
    // tx3 should fail execution regardless of execution order, since it has nonce
    // equals 10 where there are only four transactions.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 123 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzhNsbNESnWupn2XHT_:-NzhNsbNESnWupn2XHTa:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/20be25f3a9213821d93e25868fd0fff2400728c3/crates/blockifier/src/concurrency/worker_logic_test.rs#L123)):*
> ```XML
>         let execution_task_outputs =
>             lock_mutex_in_array(&executor.execution_outputs, conncurent_run_idx);
>         assert_eq!(execution_task_outputs.as_ref().unwrap().result.is_err(), should_fail_execution);
> ```





_Suggestion:_
```XML
let result = execution_task_outputs.as_ref().unwrap().result
assert_eq!(result.is_err(), should_fail_execution);
if !should_fail_execution{
    assert!(!result.unwrap().is_reverted());
}
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 135 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzhP4HV6RhmgQbUcrHl:-NzhP4HV6RhmgQbUcrHm:b-83sjoh) ([raw file](https://github.com/starkware-libs/blockifier/blob/20be25f3a9213821d93e25868fd0fff2400728c3/crates/blockifier/src/concurrency/worker_logic_test.rs#L135)):*
> ```XML
>     //   re-executed and incremented it. tx2 should fail re-execution because it has the same nonce
>     //   as tx1.
>     // * tx3 should pass re-validation and commit.
> ```

Nice!



_Suggestion:_
```XML
    // Commit all transactions in sequential order.
    // * tx0 should pass revalidation, fix the sequencer balance, fix the call info (fee transfer)
    //   and commit.
    // * tx1 should fail re-validation (it read the noce before tx0
    //   incremented it). It should pass re-execution (since tx0 incremented the nonce), fix the
    //   sequencer balance, fix the call info (fee transfer) and commit.
    // * tx2 should fail re-validation (it read the noce before tx1 
    //   re-executed and incremented it. It should fail re-execution because it has the same nonce
    //   as tx1.
    // * tx3 should pass re-validation and commit.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 136 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzhPp310Wn1j0oKMVOo:-NzhPp310Wn1j0oKMVOp:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/20be25f3a9213821d93e25868fd0fff2400728c3/crates/blockifier/src/concurrency/worker_logic_test.rs#L136)):*
> ```XML
>     //   as tx1.
>     // * tx3 should pass re-validation and commit.
>     for &(sequential_run_idx, should_fail_execution) in
> ```





_Suggestion:_
```XML
    for &(commit_idx, should_fail_execution) in
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 143 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzhRG2PBUewcqvZ6QLH:-NzhRG2Q0XgLDJRXOfVd:bdbpnvl) ([raw file](https://github.com/starkware-libs/blockifier/blob/20be25f3a9213821d93e25868fd0fff2400728c3/crates/blockifier/src/concurrency/worker_logic_test.rs#L143)):*
> ```XML
>             lock_mutex_in_array(&executor.execution_outputs, sequential_run_idx);
>         let execution_result = &execution_task_outputs.as_ref().unwrap().result;
>         let expected_sequencer_balance_high = 0_u128;
> ```

I think we can ignore it (no need to test it)



_Code quote:_
```XML
        let expected_sequencer_balance_high = 0_u128;
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 147 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzhS8CJA72HfpWHjFIg:-NzhS8CJA72HfpWHjFIh:b-7knhsm) ([raw file](https://github.com/starkware-libs/blockifier/blob/20be25f3a9213821d93e25868fd0fff2400728c3/crates/blockifier/src/concurrency/worker_logic_test.rs#L147)):*
> ```XML
>         // Extract the actual fee. If the transaction fails, no fee should be charged.
>         let actual_fee =
>             if should_fail_execution { 0 } else { execution_result.as_ref().unwrap().actual_fee.0 };
> ```

Are you using if when `should_fail_execution = true`? If not, consider defining it inside the `if`



_Code quote:_
```XML
        let actual_fee =
            if should_fail_execution { 0 } else { execution_result.as_ref().unwrap().actual_fee.0 };
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 148 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzhSP3Q9hahdGkSA_cU:-NzhSP3R4ibfZc9Z2F1A:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/20be25f3a9213821d93e25868fd0fff2400728c3/crates/blockifier/src/concurrency/worker_logic_test.rs#L148)):*
> ```XML
>         let actual_fee =
>             if should_fail_execution { 0 } else { execution_result.as_ref().unwrap().actual_fee.0 };
>         if !should_fail_execution {
> ```





_Suggestion:_
```XML
if !should_fail_execution {
    assert!(!result.unwrap().is_reverted());
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 150 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzhQ3O976X6lU0b-VPi:-NzhQ3O976X6lU0b-VPj:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/20be25f3a9213821d93e25868fd0fff2400728c3/crates/blockifier/src/concurrency/worker_logic_test.rs#L150)):*
> ```XML
>         if !should_fail_execution {
>             // Check that the storage reads of the fee transfer callinfo are the sequencer balance
>             // before adding the actual fee.
> ```





_Suggestion:_
```XML
            // Check that the call info was fixed.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 168 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzhRwt32YHSc-49pdAo:-NzhRwt32YHSc-49pdAp:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/20be25f3a9213821d93e25868fd0fff2 [...]

2024-06-06 14:20 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 143 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzhRG2PBUewcqvZ6QLH:-Nzh_6sv3YqjPxEceeSX:b7x8vwc) ([raw file](https://github.com/starkware-libs/blockifier/blob/20be25f3a9213821d93e25868fd0fff2400728c3/crates/blockifier/src/concurrency/worker_logic_test.rs#L143)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think we can ignore it (no need to test it)
</blockquote></details>

We do change it in the fill_sequencer_balance function in the commit. 
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 147 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzhS8CJA72HfpWHjFIg:-Nzho9Z3DfpvzfuR-RPp:bxl7cam) ([raw file](https://github.com/starkware-libs/blockifier/blob/20be25f3a9213821d93e25868fd0fff2400728c3/crates/blockifier/src/concurrency/worker_logic_test.rs#L147)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Are you using if when `should_fail_execution = true`? If not, consider defining it inside the `if`
</blockquote></details>

We want to check that we do not charge a fee if the transaction is rejected, so I do validate the sequencer balance in the  case that the result is an error


<!-- Sent from Reviewable.io -->

2024-06-06 16:19 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 151 at r20](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NziKva9-TyEk0Q3nuzW:-NziKva9-TyEk0Q3nuzX:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e74a38e08cb59d96e10bc666cb1e981a54553654/crates/blockifier/src/concurrency/worker_logic_test.rs#L151)):*
> ```XML
>     // * tx3 should pass re-validation and commit.
>     for &(commit_idx, should_fail_execution) in
>         [(0, false), (1, false), (2, true), (3, true)].iter()
> ```





_Suggestion:_
```XML
    // Commit all transactions in sequential order.
    // * tx0 should pass revalidation, fix the sequencer balance, fix the call info (fee transfer)
    //   and commit.
    // * tx1 should fail revalidation (it read the nonce before tx0 incremented it). It should pass
    //   re-execution (since tx0 incremented the nonce), fix the sequencer balance, fix the call
    //   info (fee transfer) and commit.
    // * tx2 should fail revalidation (it read the nonce before tx1 re-executed and incremented it).
    //   It should fail re-execution because it has the same nonce as tx1.
    // * tx3 should pass revalidation and commit.
    for &(commit_idx, should_fail_execution) in
        [(0, false), (1, false), (2, true), (3, true)].iter()
```


<!-- Sent from Reviewable.io -->

2024-06-06 16:20 UTC, avi-starkware requested changes
> Reviewed 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: all files reviewed, 6 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 66 at r20](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NziIuUFBzr_corTCGHf:-NziIuUFBzr_corTCGHg:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/e74a38e08cb59d96e10bc666cb1e981a54553654/crates/blockifier/src/concurrency/worker_logic_test.rs#L66)):*
> ```XML
> 
> /// Checks that the storage values of the account and sequencer balances in the
> /// versioned state of tx_index equals the expected values.
> ```





_Suggestion:_
```XML
/// Checks that the sequencer balances at version tx_index in the versioned state
/// equals the expected sequencer balance plus the actual fee.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 127 at r20](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NziK2lYCUhikJnB4cIf:-NziK2lYCUhikJnB4cIg:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e74a38e08cb59d96e10bc666cb1e981a54553654/crates/blockifier/src/concurrency/worker_logic_test.rs#L127)):*
> ```XML
>     // succeed.
>     // tx3 should fail execution regardless of execution order, since it has nonce
>     // equals 10 where there are only four transactions.
> ```





_Suggestion:_
```XML
    // tx1 should fail execution since its nonce equals 1, and it is being executed before tx0,
    // whose nonce equals 0.
    // tx0 should pass execution.
    // tx2 should pass execution since its nonce equals 1, so executing it after tx0 should
    // succeed.
    // tx3 should fail execution regardless of execution order since its nonce
    // equals 10, where there are only four transactions.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 182 at r20](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NziKpSz-viqKFEP0xyO:-NziKpT-5xQR0wCWm5v0:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e74a38e08cb59d96e10bc666cb1e981a54553654/crates/blockifier/src/concurrency/worker_logic_test.rs#L182)):*
> ```XML
>             }
>         }
>         // Check that the sequencer balance was updated correctly in the state
> ```





_Suggestion:_
```XML
        // Check that the sequencer balance was updated correctly in the state.
```


<!-- Sent from Reviewable.io -->

2024-06-09 06:12 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @avi-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 66 at r20](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NziIuUFBzr_corTCGHf:-NzvVCTS63w8DeSwKOGl:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e74a38e08cb59d96e10bc666cb1e981a54553654/crates/blockifier/src/concurrency/worker_logic_test.rs#L66)):*
> ```XML
> 
> /// Checks that the storage values of the account and sequencer balances in the
> /// versioned state of tx_index equals the expected values.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 127 at r20](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NziK2lYCUhikJnB4cIf:-NzvVC6iE5x7ZIXLNZdV:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e74a38e08cb59d96e10bc666cb1e981a54553654/crates/blockifier/src/concurrency/worker_logic_test.rs#L127)):*
> ```XML
>     // succeed.
>     // tx3 should fail execution regardless of execution order, since it has nonce
>     // equals 10 where there are only four transactions.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 151 at r20](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NziKva9-TyEk0Q3nuzW:-NzvVBfL9Lnc9MkSPDUf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e74a38e08cb59d96e10bc666cb1e981a54553654/crates/blockifier/src/concurrency/worker_logic_test.rs#L151)):*
> ```XML
>     // * tx3 should pass re-validation and commit.
>     for &(commit_idx, should_fail_execution) in
>         [(0, false), (1, false), (2, true), (3, true)].iter()
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 182 at r20](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NziKpSz-viqKFEP0xyO:-NzvV3uIAEo9E3NxowYG:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e74a38e08cb59d96e10bc666cb1e981a54553654/crates/blockifier/src/concurrency/worker_logic_test.rs#L182)):*
> ```XML
>             }
>         }
>         // Check that the sequencer balance was updated correctly in the state
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-06-09 07:08 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 66 at r20](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NziIuUFBzr_corTCGHf:-NzvomWQ9ZmNfYNYUihi:bed2kmb) ([raw file](https://github.com/starkware-libs/blockifier/blob/e74a38e08cb59d96e10bc666cb1e981a54553654/crates/blockifier/src/concurrency/worker_logic_test.rs#L66)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Change it back to `///`.
Nonblocking.


<!-- Sent from Reviewable.io -->

2024-06-09 07:10 UTC, avi-starkware requested changes
> Reviewed 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 127 at r20](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NziK2lYCUhikJnB4cIf:-Nzvp4fM8IhbZK2kjoNd:b-pxzrmw) ([raw file](https://github.com/starkware-libs/blockifier/blob/e74a38e08cb59d96e10bc666cb1e981a54553654/crates/blockifier/src/concurrency/worker_logic_test.rs#L127)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see any changes.


<!-- Sent from Reviewable.io -->

2024-06-09 08:09 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @avi-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 127 at r20](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NziK2lYCUhikJnB4cIf:-Nzw1hXf0GTd1hFTFTFr:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/e74a38e08cb59d96e10bc666cb1e981a54553654/crates/blockifier/src/concurrency/worker_logic_test.rs#L127)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I don't see any changes.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-09 10:05 UTC, avi-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-:-NzwSVuh9pATzXd-K842:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-06-09 12:54 UTC, noaov1 requested changes
> Reviewed 1 of 2 files at r18, 1 of 2 files at r20, 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: all files reviewed, 3 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 11 at r24](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nzx2tdG3dkaUhX010Za:-Nzx2tdG3dkaUhX010Zb:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/5bd10538e2d181b9640b97a87c3b1b78c6f3ea33/crates/blockifier/src/concurrency/fee_utils.rs#L11)):*
> ```XML
> // `Uint256`, consist of two felts (lsb, msb). Hence, storage read values =
> // [account_balance, 0, sequencer_balance, 0]
> pub const STORAGE_READ_SEQUENCER_BALANCE_INDICES: (usize, usize) = (2, 3);
> ```





_Suggestion:_
```XML
pub(crate) const STORAGE_READ_SEQUENCER_BALANCE_INDICES: (usize, usize) = (2, 3);
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 143 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-NzhRG2PBUewcqvZ6QLH:-Nzx0F3XDn7rwTAvJEbK:b-gu6e00) ([raw file](https://github.com/starkware-libs/blockifier/blob/20be25f3a9213821d93e25868fd0fff2400728c3/crates/blockifier/src/concurrency/worker_logic_test.rs#L143)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

We do change it in the fill_sequencer_balance function in the commit.
</blockquote></details>

Oh, I see. So never mind.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 177 at r24](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nzx2kQa8SeKLvcaVo80:-Nzx2kQa8SeKLvcaVo81:b2nhkyh) ([raw file](https://github.com/starkware-libs/blockifier/blob/5bd10538e2d181b9640b97a87c3b1b78c6f3ea33/crates/blockifier/src/concurrency/worker_logic_test.rs#L177)):*
> ```XML
>             actual_fee,
>         );
>         expected_sequencer_balance_low += actual_fee;
> ```

No?



_Suggestion:_
```XML
        expected_sequencer_balance_low += actual_fee;
        verify_sequencer_balance_update(
            &executor,
            commit_idx,
            expected_sequencer_balance_low,
            actual_fee,
        );
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1163 at r24](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nzx37tvEKr4gr7HuHfo:-Nzx37tw1xTURMOOQ6ZU:bl84e85) ([raw file](https://github.com/starkware-libs/blockifier/blob/5bd10538e2d181b9640b97a87c3b1b78c6f3ea33/crates/blockifier/src/transaction/account_transactions_test.rs#L1163)):*
> ```XML
> }
> 
> // TODO(Meshi, 01/06/2024): change the triviale call data to a non reverted call data.
> ```

Still relevant?



_Code quote:_
```XML
// TODO(Meshi, 01/06/2024): change the triviale call data to a non reverted call data.
```


<!-- Sent from Reviewable.io -->

2024-06-10 06:16 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 177 at r24](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nzx2kQa8SeKLvcaVo80:-O--m39o7eTlBxAxRERJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5bd10538e2d181b9640b97a87c3b1b78c6f3ea33/crates/blockifier/src/concurrency/worker_logic_test.rs#L177)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

No?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 1163 at r24](https://reviewable.io/reviews/starkware-libs/blockifier/1893#-Nzx37tvEKr4gr7HuHfo:-O--jNbCD2Te-b_a522R:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5bd10538e2d181b9640b97a87c3b1b78c6f3ea33/crates/blockifier/src/transaction/account_transactions_test.rs#L1163)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Still relevant?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-10 07:50 UTC, noaov1 submitted a review, later dismissed
> Reviewed 2 of 3 files at r25, 1 of 1 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-06-10 08:25 UTC, noaov1 approved these changes
> Reviewed 1 of 1 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1893)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-06-10 08:28 UTC, merged