test(concurrency): add utilities for commit tx test
starkware-libs/blockifier pull request #1922
Opened 2024-05-28 12:55 UTC by meship-starkware

2024-05-30 06:34 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7C12H5O3DJdq4Z-Kt:-Nz7C12H5O3DJdq4Z-Ku:b-2skoqt) ([raw file](https://github.com/starkware-libs/blockifier/blob/395f1a41c8695f00671b39d9220a187260917215/crates/blockifier/src/concurrency/fee_utils.rs#L11)):*
> ```XML
> // `Uint256`, consist of two felts (lsb, msb). Hence, storage read values =
> // [account_balance, 0, sequencer_balance, 0]
> pub const STORAGE_READ_SEQUENCER_BALANCE_INDICES: (usize, usize) = (2, 3);
> ```

please make this change in #1923, where the constant is used.



_Code quote:_
```XML
pub const STORAGE_READ_SEQUENCER_BALANCE_INDICES: (usize, usize) = (2, 3);
```


<!-- Sent from Reviewable.io -->

2024-05-30 06:34 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/test_utils.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7Bvwh1u00TxIno8zY:-Nz7Bvwh1u00TxIno8zZ:b-qvuzn4) ([raw file](https://github.com/starkware-libs/blockifier/blob/395f1a41c8695f00671b39d9220a187260917215/crates/blockifier/src/concurrency/test_utils.rs#L71)):*
> ```XML
> ) -> CallInfo {
>     let block_context = BlockContext::create_for_testing_with_concurrency_mode(concurrency_mode);
>     let mut transactional_state = CachedState::create_transactional(state);
> ```

Why change it?
Isn't it the same method?



_Code quote:_
```XML
    let mut transactional_state = CachedState::create_transactional(state);
```


<!-- Sent from Reviewable.io -->

2024-05-30 06:34 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7CFit3FIk9DoWOJbd:-Nz7CFit3FIk9DoWOJbe:b-kt8i8v) ([raw file](https://github.com/starkware-libs/blockifier/blob/395f1a41c8695f00671b39d9220a187260917215/crates/blockifier/src/concurrency/worker_logic.rs#L31)):*
> ```XML
> 
> const EXECUTION_OUTPUTS_UNWRAP_ERROR: &str = "Execution task outputs should not be None.";
> #[derive(Debug)]
> ```

Restore the empty line.



_Suggestion:_
```XML
const EXECUTION_OUTPUTS_UNWRAP_ERROR: &str = "Execution task outputs should not be None.";

#[derive(Debug)]
```


<!-- Sent from Reviewable.io -->

2024-05-30 06:38 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7CavNARgyVBvmkrH0:-Nz7CavNARgyVBvmkrH1:b-n0nmpp) ([raw file](https://github.com/starkware-libs/blockifier/blob/395f1a41c8695f00671b39d9220a187260917215/crates/blockifier/src/concurrency/worker_logic_test.rs#L47)):*
> ```XML
> }
> 
> fn _sequencer_transfer_invoke_tx(
> ```

Transfer is always invoke



_Suggestion:_
```XML
fn _transfer_to_sequencer_tx(
```


<!-- Sent from Reviewable.io -->

2024-05-30 06:41 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7DhpB2KMG30l8DJrC:-Nz7DhpB2KMG30l8DJrD:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/395f1a41c8695f00671b39d9220a187260917215/crates/blockifier/src/concurrency/worker_logic_test.rs#L57)):*
> ```XML
>         block_context.chain_info().fee_token_address(&FeeType::Strk),
>         TRANSFER_ENTRY_POINT_NAME,
>         &[*sequencer_address.0.key(), stark_felt!(transfer_amount), stark_felt!(0_u8)],
> ```





_Suggestion:_
```XML
        &[
            *sequencer_address.0.key(),     // Recipient address.
            stark_felt!(transfer_amount),   // Amount low.
            stark_felt!(0_u8)               // Amount high.
        ],
```


<!-- Sent from Reviewable.io -->

2024-05-30 06:49 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7EZYR30IQ_I8SxvDT:-Nz7EZYR30IQ_I8SxvDU:bnx9khf) ([raw file](https://github.com/starkware-libs/blockifier/blob/395f1a41c8695f00671b39d9220a187260917215/crates/blockifier/src/concurrency/worker_logic_test.rs#L88)):*
> ```XML
>     account_address: ContractAddress,
>     tx_index: usize,
>     expected_storage_values: (StarkFelt, StarkFelt, StarkFelt, StarkFelt),
> ```

You are allowed 7 arguments. Let's make it easier to understand what the input of this function should be.

* Alternatively, you can add a comment explaining what each felt represents.



_Suggestion:_
```XML
    account_balance_low: StarkFelt,
    account_balance_high: StarkFelt,
    sequencer_balance_low: StarkFelt,
    sequencer_balance_high: StarkFelt,
```


<!-- Sent from Reviewable.io -->

2024-05-30 06:50 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7EZYR30IQ_I8SxvDT:-Nz7FlVM062Z8h43cv-c:b-tgvbbd) ([raw file](https://github.com/starkware-libs/blockifier/blob/395f1a41c8695f00671b39d9220a187260917215/crates/blockifier/src/concurrency/worker_logic_test.rs#L88)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

You are allowed 7 arguments. Let's make it easier to understand what the input of this function should be.

* Alternatively, you can add a comment explaining what each felt represents.
</blockquote></details>

Sorry, please add the prefix `expected_` to each of the argument names I proposed.


<!-- Sent from Reviewable.io -->

2024-05-30 07:06 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1922)* status: 0 of 6 files reviewed, 7 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/fee_utils.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7C12H5O3DJdq4Z-Kt:-Nz7IJvJ54EJFjiVty6_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/395f1a41c8695f00671b39d9220a187260917215/crates/blockifier/src/concurrency/fee_utils.rs#L11)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

please make this change in #1923, where the constant is used.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/test_utils.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7Bvwh1u00TxIno8zY:-Nz7CwqP9jiAdK48tV_o:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/395f1a41c8695f00671b39d9220a187260917215/crates/blockifier/src/concurrency/test_utils.rs#L71)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Why change it?
Isn't it the same method?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7CFit3FIk9DoWOJbd:-Nz7IWw7DyZcWod8vsVZ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/395f1a41c8695f00671b39d9220a187260917215/crates/blockifier/src/concurrency/worker_logic.rs#L31)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Restore the empty line.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-30 07:16 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7LYyDAcZADI0dVa9P:-Nz7LYyDAcZADI0dVa9Q:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/395f1a41c8695f00671b39d9220a187260917215/crates/blockifier/src/concurrency/worker_logic_test.rs#L112)):*
> ```XML
>         );
>     }
> }
> ```





_Suggestion:_
```XML
    let (sequencer_balance_key_low, sequencer_balance_key_high) =
        get_sequencer_balance_keys(&executor.block_context);
    for (expected_balance, storage_key) in [
        (expected_storage_values.0, account_balance_key_low),
        (expected_storage_values.1, account_balance_key_high),
        (expected_storage_values.2, sequencer_balance_key_low),
        (expected_storage_values.3, sequencer_balance_key_high),
    ] {
        let actual_balance = tx_version_state
            .get_storage_at(
                executor.block_context.chain_info.fee_token_address(&FeeType::Strk),
                storage_key
            )
            .unwrap();
        assert_eq!(actual_balance, expected_balance);
    }
}
```


<!-- Sent from Reviewable.io -->

2024-05-30 07:20 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7MMpNB7zFcUG96uSb:-Nz7MMpNB7zFcUG96uSc:b2n21ua) ([raw file](https://github.com/starkware-libs/blockifier/blob/818b4f3e962c626fbc427c667c6d0cc1c2a3bf7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L114)):*
> ```XML
> }
> 
> fn _write_account_balance_at_versioned_state(
> ```

Sorry, I know I proposed the name, but I think it is confusing.



_Suggestion:_
```XML
fn _change_account_balance_at_version(
```


<!-- Sent from Reviewable.io -->

2024-05-30 07:24 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7MMpNB7zFcUG96uSb:-Nz7N-NE-QW3NYY6js9F:b-jig5lc) ([raw file](https://github.com/starkware-libs/blockifier/blob/818b4f3e962c626fbc427c667c6d0cc1c2a3bf7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L114)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Sorry, I know I proposed the name, but I think it is confusing.
</blockquote></details>

Maybe add a dock string to make this function clearer:



_Code snippet:_
```XML
/// Changes an account's balance observed by transaction `tx_index`. Used to cause a transaction to 
/// either pass or fail validation in tests.
```


<!-- Sent from Reviewable.io -->

2024-05-30 07:26 UTC, avi-starkware reviewed
> Reviewed 5 of 6 files at r1, 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1922)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @meship-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-05-30 08:07 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1922)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 47 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7CavNARgyVBvmkrH0:-Nz7TDyp6RrQuR9g6z6y:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/395f1a41c8695f00671b39d9220a187260917215/crates/blockifier/src/concurrency/worker_logic_test.rs#L47)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Transfer is always invoke
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7GEp4DSoUHoBtYOr9:-Nz7KBMr3uQEtWDPXJGh:b-4dz08o) ([raw file](https://github.com/starkware-libs/blockifier/blob/395f1a41c8695f00671b39d9220a187260917215/crates/blockifier/src/concurrency/worker_logic_test.rs#L70)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

I liked the name invalid transaction. It makes it easy to understand what it is going to be used for. I think it's better to explain why it is invalid in a comment to make it easy to understand for someone who is reading the function for the first time.
</blockquote></details>

It is; if we run with the validation flag as false, it will pass.  
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7EZYR30IQ_I8SxvDT:-Nz7TaJ0EdbkfyZH8860:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/395f1a41c8695f00671b39d9220a187260917215/crates/blockifier/src/concurrency/worker_logic_test.rs#L88)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Sorry, please add the prefix `expected_` to each of the argument names I proposed.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7LYyDAcZADI0dVa9P:-Nz7V6hNEnCGvECdT-KQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/395f1a41c8695f00671b39d9220a187260917215/crates/blockifier/src/concurrency/worker_logic_test.rs#L112)):*
> ```XML
>         );
>     }
> }
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7MMpNB7zFcUG96uSb:-Nz7V71y3q6T--Xne0Gn:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/818b4f3e962c626fbc427c667c6d0cc1c2a3bf7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L114)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Maybe add a dock string to make this function clearer:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-30 11:50 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 61 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz8KS2WCnLLSyT76snx:-Nz8KS2WCnLLSyT76sny:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7c984b1465f9f7a5f3f3051af87e8799d9dc1ec5/crates/blockifier/src/concurrency/worker_logic_test.rs#L61)):*
> ```XML
>             stark_felt!(transfer_amount), // Amount low.
>             stark_felt!(0_u8),
>         ], // Amount high.
> ```





_Suggestion:_
```XML
            stark_felt!(0_u8),      // Amount high.
        ],
```


<!-- Sent from Reviewable.io -->

2024-05-30 11:51 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 105 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz8KiEZ92wHUlG6zv2-:-Nz8KiEZ92wHUlG6zv20:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7c984b1465f9f7a5f3f3051af87e8799d9dc1ec5/crates/blockifier/src/concurrency/worker_logic_test.rs#L105)):*
> ```XML
>     for (expected_balance, storage_key) in [
>         (expected_account_balance_low, account_balance_key_low),
>         // In tests we assume accout balane can be represented as u128.
> ```





_Suggestion:_
```XML
 // In tests, we assume that the account balance can be represented as u128.
```


<!-- Sent from Reviewable.io -->

2024-05-30 12:09 UTC, avi-starkware reviewed
> Reviewed 2 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1922)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-05-30 14:06 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1922)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7DhpB2KMG30l8DJrC:-Nz8Mns40zoMepYxqfhD:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/395f1a41c8695f00671b39d9220a187260917215/crates/blockifier/src/concurrency/worker_logic_test.rs#L57)):*
> ```XML
>         block_context.chain_info().fee_token_address(&FeeType::Strk),
>         TRANSFER_ENTRY_POINT_NAME,
>         &[*sequencer_address.0.key(), stark_felt!(transfer_amount), stark_felt!(0_u8)],
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 114 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz7MMpNB7zFcUG96uSb:-Nz8UX4-BhqbgVHCWaU7:b-oowu79) ([raw file](https://github.com/starkware-libs/blockifier/blob/818b4f3e962c626fbc427c667c6d0cc1c2a3bf7b/crates/blockifier/src/concurrency/worker_logic_test.rs#L114)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

What do you mean `, or filling the account balance high.`?
I looked at all the use cases in #1893, and all I saw was either making a transaction fail validation or pass validation.
</blockquote></details>

There is another PR that I haven't pushed yet that checks u128 overflow, and it uses this function to update the sequencer balance high. But it might not be needed, so maybe I'll add it to the dedicated PR

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 61 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz8KS2WCnLLSyT76snx:-Nz8MpdaAzkUxm1D180w:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7c984b1465f9f7a5f3f3051af87e8799d9dc1ec5/crates/blockifier/src/concurrency/worker_logic_test.rs#L61)):*
> ```XML
>             stark_felt!(transfer_amount), // Amount low.
>             stark_felt!(0_u8),
>         ], // Amount high.
> ```

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 105 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nz8KiEZ92wHUlG6zv2-:-Nz8YMEs29k_t8lM0JnK:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7c984b1465f9f7a5f3f3051af87e8799d9dc1ec5/crates/blockifier/src/concurrency/worker_logic_test.rs#L105)):*
> ```XML
>     for (expected_balance, storage_key) in [
>         (expected_account_balance_low, account_balance_key_low),
>         // In tests we assume accout balane can be represented as u128.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-05-30 14:19 UTC, avi-starkware approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1922)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-05-30 14:19 UTC, avi-starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-:-Nz8rkXo3E7fu-kEyNn-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-06-03 11:56 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1922)* status: all files reviewed, 5 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 74 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-NzNof6C311NR7RaIuuR:-NzNof6C311NR7RaIuuS:b-r2oe3n) ([raw file](https://github.com/starkware-libs/blockifier/blob/02cec2c20076fe81af9672855a459ed30d769378/crates/blockifier/src/concurrency/worker_logic_test.rs#L74)):*
> ```XML
> }
> 
> /// Creates an invalid transaction. The transaction has no calldata, making it fail validation.
> ```

IMO the failure reason is not clear enough.
Consider using an invalid nonce.



_Code quote:_
```XML
/// Creates an invalid transaction. The transaction has no calldata, making it fail validation.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 82 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-NzNpFcZEM_I3VdbwGkc:-NzNpFcZEM_I3VdbwGkd:bc423l0) ([raw file](https://github.com/starkware-libs/blockifier/blob/02cec2c20076fe81af9672855a459ed30d769378/crates/blockifier/src/concurrency/worker_logic_test.rs#L82)):*
> ```XML
>         sender_address: account_address,
>         resource_bounds: l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE),
>         version: TransactionVersion::THREE,
> ```

Will setting the default version in `invoke_tx_args!` to `THREE` works?



_Code quote:_
```XML
        version: TransactionVersion::THREE,
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 88 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-NzOEEf1Ca8xzX6TV0Y8:-NzOEEf1Ca8xzX6TV0Y9:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/02cec2c20076fe81af9672855a459ed30d769378/crates/blockifier/src/concurrency/worker_logic_test.rs#L88)):*
> ```XML
> 
> // This function checks that the storage values of the account and sequencer balances in the
> // versioned state of tx_index are equal to the expected_storage_values.
> ```





_Suggestion:_
```XML
/// Checks that the storage values of the account and sequencer balances in the
/// versioned state of tx_index equals the expected values.
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 112 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-NzNqvo4BpVZU88hbQrq:-NzNqvo5EjMNERoNoSbS:bpku99t) ([raw file](https://github.com/starkware-libs/blockifier/blob/02cec2c20076fe81af9672855a459ed30d769378/crates/blockifier/src/concurrency/worker_logic_test.rs#L112)):*
> ```XML
>         let actual_balance = tx_version_state
>             .get_storage_at(
>                 executor.block_context.chain_info.fee_token_address(&FeeType::Strk),
> ```

Are we willing to test V3 transactions only?



_Code quote:_
```XML
                executor.block_context.chain_info.fee_token_address(&FeeType::Strk),
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 131 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-NzNrbKv29vWQ3-PWT0b:-NzNrbKv29vWQ3-PWT0c:b-e8vto3) ([raw file](https://github.com/starkware-libs/blockifier/blob/02cec2c20076fe81af9672855a459ed30d769378/crates/blockifier/src/concurrency/worker_logic_test.rs#L131)):*
> ```XML
>     let mut versioned_state = state.pin_version(tx_index - 1);
>     let account_balance_key_low = get_fee_token_var_address(account_address);
>     let account_balance_key_high = next_storage_key(&account_balance_key_low).unwrap();
> ```

Consider adding a util (similar to `get_sequencer_balance_keys`)



_Code quote:_
```XML
    let account_balance_key_low = get_fee_token_var_address(account_address);
    let account_balance_key_high = next_storage_key(&account_balance_key_low).unwrap();
```


<!-- Sent from Reviewable.io -->

2024-06-04 06:09 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1922)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 74 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-NzNof6C311NR7RaIuuR:-NzTf4eF2eyGR2PzKsFk:bj0sjj9) ([raw file](https://github.com/starkware-libs/blockifier/blob/02cec2c20076fe81af9672855a459ed30d769378/crates/blockifier/src/concurrency/worker_logic_test.rs#L74)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

IMO the failure reason is not clear enough.
Consider using an invalid nonce.
</blockquote></details>

I am removing the invalid tx and will create one with an Invalid Nonce using  trivial_calldata_invoke_tx
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 82 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-NzNpFcZEM_I3VdbwGkc:-NzTfPlE9nUOwlXA8m1a:b-x4vsob) ([raw file](https://github.com/starkware-libs/blockifier/blob/02cec2c20076fe81af9672855a459ed30d769378/crates/blockifier/src/concurrency/worker_logic_test.rs#L82)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Will setting the default version in `invoke_tx_args!` to `THREE` works?
</blockquote></details>

In another PR
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 112 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-NzNqvo4BpVZU88hbQrq:-NzTfcAb7F8wrpGf5Mlp:bx85mez) ([raw file](https://github.com/starkware-libs/blockifier/blob/02cec2c20076fe81af9672855a459ed30d769378/crates/blockifier/src/concurrency/worker_logic_test.rs#L112)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Are we willing to test V3 transactions only?
</blockquote></details>

That's a good question, I can change the function that creates the invoke tx to get a version and return the right account, 
and from there use cases in the test.   
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 131 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-NzNrbKv29vWQ3-PWT0b:-NzThSvP6O2MxaSLNZGH:b-9bb0i2) ([raw file](https://github.com/starkware-libs/blockifier/blob/02cec2c20076fe81af9672855a459ed30d769378/crates/blockifier/src/concurrency/worker_logic_test.rs#L131)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider adding a util (similar to `get_sequencer_balance_keys`)
</blockquote></details>

I did this in this PR. Tell me if you think this should be in a different PR 


<!-- Sent from Reviewable.io -->

2024-06-04 14:44 UTC, avi-starkware requested changes
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1922)* status: all files reviewed, 4 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 72 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-NzYh48rAqMIxRPIqwWS:-NzYh48rAqMIxRPIqwWT:bb76mu4) ([raw file](https://github.com/starkware-libs/blockifier/blob/73d88b2f0665c2e3e2ed78142052b70f676d6e0d/crates/blockifier/src/concurrency/worker_logic_test.rs#L72)):*
> ```XML
>         sender_address: account_address,
>         calldata: transfer_calldata,
>         resource_bounds: l1_resource_bounds(5*MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE),
> ```

Why?



_Code quote:_
```XML
        resource_bounds: l1_resource_bounds(5*MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE),
```


<!-- Sent from Reviewable.io -->

2024-06-05 13:19 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1922)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 72 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-NzYh48rAqMIxRPIqwWS:-NzcYQkR4c9I8AyFfy8d:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/73d88b2f0665c2e3e2ed78142052b70f676d6e0d/crates/blockifier/src/concurrency/worker_logic_test.rs#L72)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-06 07:51 UTC, avi-starkware submitted a review, later dismissed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1922)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-06-06 13:49 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1922)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @avi-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 51 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-NzhSU_MCj6RvR7XO9QX:-NzhU2G75M7UX9xQdgdu:b-d8y7jw) ([raw file](https://github.com/starkware-libs/blockifier/blob/7e88771a6e2f2fbba426090e57dd9ffbbf9a13e8/crates/blockifier/src/concurrency/worker_logic_test.rs#L51)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why do we need to check the account balance?
</blockquote></details>

We don't need to. It's a reminder of the way the test was before.
Done.


<!-- Sent from Reviewable.io -->

2024-06-06 15:43 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 45 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-NziCvhA8CTUvu4IO0mB:-NziCvhA8CTUvu4IO0mC:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/019ac9653b881704ca7d0e8b9a3d9104cf29fb0b/crates/blockifier/src/concurrency/worker_logic_test.rs#L45)):*
> ```XML
>     nonce: Nonce,
> ) -> AccountTransaction {
>     // let some_other_account_address = account_contract.get_instance_address(17);
> ```




<!-- Sent from Reviewable.io -->

2024-06-06 15:43 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 40 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-NziD-rt2A6lx78YJbdV:-NziD-rt2A6lx78YJbdW:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/019ac9653b881704ca7d0e8b9a3d9104cf29fb0b/crates/blockifier/src/concurrency/worker_logic_test.rs#L40)):*
> ```XML
> use crate::{declare_tx_args, invoke_tx_args, nonce, storage_key};
> 
> fn _trivial_transfer_tx(
> ```





_Suggestion:_
```XML
// Creates a tx that transfers 0 to self.
fn _trivial_transfer_tx(
```


<!-- Sent from Reviewable.io -->

2024-06-06 15:48 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 69 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-NziDvkx0L8dIj9gkbNO:-NziDvkx0L8dIj9gkbNP:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/019ac9653b881704ca7d0e8b9a3d9104cf29fb0b/crates/blockifier/src/concurrency/worker_logic_test.rs#L69)):*
> ```XML
>     executor: &WorkerExecutor<'_, S>,
>     tx_index: usize,
>     // We assume balance < 2^128.
> ```





_Suggestion:_
```XML
    // We assume the balance is at most 2^128, so the "low" value is sufficient.
```


<!-- Sent from Reviewable.io -->

2024-06-06 16:07 UTC, avi-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 66 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-NziDmYGBfAKQfwfMaCR:-NziIC6VD2jJcf-plAm5:b7rcrfm) ([raw file](https://github.com/starkware-libs/blockifier/blob/019ac9653b881704ca7d0e8b9a3d9104cf29fb0b/crates/blockifier/src/concurrency/worker_logic_test.rs#L66)):*
> ```XML
> /// Checks that the storage values of the account and sequencer balances in the
> /// versioned state of tx_index equals the expected values.
> fn _verify_sequencer_balance_update<S: StateReader>(
> ```

Retracted. The old name is a better fit for the changes you make to this function in the next PR.


<!-- Sent from Reviewable.io -->

2024-06-09 07:10 UTC, avi-starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-:-NzvpUlz-yuDy9Y0-Tmj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-06-09 12:39 UTC, noaov1 approved these changes
> Reviewed 1 of 2 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1922)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 53 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-Nzx-EYU4Ql4AyR7Q4Bk:-Nzx-EYV4K6XYiFmLtdl:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ede3d202f8d41a1f7798e9a69124a6733dfaa41/crates/blockifier/src/concurrency/worker_logic_test.rs#L53)):*
> ```XML
> 
> /// Checks that the storage values of the account and sequencer balances in the
> /// versioned state of tx_index equals the expected values.
> ```





_Suggestion:_
```XML
/// Checks that the sequencer balance was updated as expected in the state.
```


<!-- Sent from Reviewable.io -->

2024-06-09 17:05 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1922)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 69 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-NzxxLZtA_986xsiZD2C:-NzxxLZtA_986xsiZD2D:blxaofh) ([raw file](https://github.com/starkware-libs/blockifier/blob/7ede3d202f8d41a1f7798e9a69124a6733dfaa41/crates/blockifier/src/concurrency/worker_logic_test.rs#L69)):*
> ```XML
>         let actual_balance = tx_version_state
>             .get_storage_at(
>                 executor.block_context.chain_info.fee_token_address(&FeeType::Strk),
> ```

Please extract it from the transaction context



_Code quote:_
```XML
&FeeType::Strk
```


<!-- Sent from Reviewable.io -->

2024-06-10 07:05 UTC, noaov1 approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1922)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 54 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-O--uACSAfqjs-fabm1L:-O--uACSAfqjs-fabm1M:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/192388a8ce43d1a06f914a602c6d9f05ecddc877/crates/blockifier/src/concurrency/worker_logic_test.rs#L54)):*
> ```XML
> /// Checks that the sequencer balance was updated as expected in the state.
> fn _verify_sequencer_balance_update<S: StateReader>(
>     executor: &WorkerExecutor<'_, S>,
> ```





_Suggestion:_
```XML
    state: ThreadSafeVersionedState<S>,
```


<!-- Sent from Reviewable.io -->

2024-06-10 07:13 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1922)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 54 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1922#-O--uACSAfqjs-fabm1L:-O--zbMU73ZlKCX_UhTr:b-4y3sra) ([raw file](https://github.com/starkware-libs/blockifier/blob/192388a8ce43d1a06f914a602c6d9f05ecddc877/crates/blockifier/src/concurrency/worker_logic_test.rs#L54)):*
> ```XML
> /// Checks that the sequencer balance was updated as expected in the state.
> fn _verify_sequencer_balance_update<S: StateReader>(
>     executor: &WorkerExecutor<'_, S>,
> ```

next PR


<!-- Sent from Reviewable.io -->

2024-06-10 07:47 UTC, noaov1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1922)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-06-10 07:59 UTC, merged