feat(concurrency): implement execute_chunk
starkware-libs/blockifier pull request #1953
Opened 2024-06-04 09:23 UTC by barak-b-starkware

2024-06-04 11:55 UTC, avi-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware, @MohammadNassar1, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzY30t38W2Uxl0JVbO3:-NzY30t38W2Uxl0JVbO4:b-d8yahs) ([raw file](https://github.com/starkware-libs/blockifier/blob/2d1c422472d71b5e2694fb35422a3561cd8bfb98/crates/blockifier/src/blockifier/transaction_executor.rs#L152)):*
> ```XML
>         // WorkerExecutor instead of Arc::clone it.
>         let worker_executor =
>             Arc::new(WorkerExecutor::new(chunk_state.clone(), chunk, self.block_context.clone()));
> ```

Could we perhaps use the worker_executor as sort of a context_manager?
Where this block of code happens in `WorkerExecutor::new`, and the block of code starting at `drop(worker_executor)` and ending at replacing the `block_state` would happen in the implementation of the `Drop` trait for `WorkerExecutor`?

I think it would be cleaner to do it this way if possible.

Non-blocking.



_Code quote:_
```XML
        let block_state = self.block_state.take().expect("The block state should be `Some`.");

        let versioned_state = VersionedState::new(block_state);
        let chunk_state = ThreadSafeVersionedState::new(versioned_state);
        // TODO(barak, 01/08/2024): Consider moving `chunk_state` and lock it inside the
        // WorkerExecutor instead of Arc::clone it.
        let worker_executor =
            Arc::new(WorkerExecutor::new(chunk_state.clone(), chunk, self.block_context.clone()));
```
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzY00XECVtHvzJn24wr:-NzY00XFBhdTgVzs9qS8:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/2d1c422472d71b5e2694fb35422a3561cd8bfb98/crates/blockifier/src/blockifier/transaction_executor.rs#L190)):*
> ```XML
> 
>         // We must verify that we have only one strong reference to the versioned state before
>         // consuming it. Drop the wroker executor that holds a refernce to the versioned state so we
> ```





_Suggestion:_
```XML
        // consuming it. Drop the worker executor that holds a reference to the versioned state so we
```
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzY-L2z9RaOl1l3Sjwn:-NzY-L3-9dtoCAq0INLk:b-dvhqec) ([raw file](https://github.com/starkware-libs/blockifier/blob/2d1c422472d71b5e2694fb35422a3561cd8bfb98/crates/blockifier/src/blockifier/transaction_executor.rs#L197)):*
> ```XML
> 
>         let block_state_after_use = versioned_state_after_use.consume_block_state();
>         self.block_state.replace(block_state_after_use);
> ```

What happens if the method crashes after "taking" `block_state` and before "replacing" it?

Does rust have to drop `worker_executor` if the method panics while it still exists?
If so, implementing the `Drop` trait for `WorkerExecutor` and doing the `replace` inside `drop` might be enough to force rust to replace the `block_state` when panicking.



_Code quote:_
```XML
        self.block_state.replace(block_state_after_use);
```


<!-- Sent from Reviewable.io -->

2024-06-04 11:56 UTC, avi-starkware reviewed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware, @MohammadNassar1, @noaov1, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-06-04 14:16 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzY00XECVtHvzJn24wr:-NzY_FbB4UPE_JTVM5yG:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2d1c422472d71b5e2694fb35422a3561cd8bfb98/crates/blockifier/src/blockifier/transaction_executor.rs#L190)):*
> ```XML
> 
>         // We must verify that we have only one strong reference to the versioned state before
>         // consuming it. Drop the wroker executor that holds a refernce to the versioned state so we
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-06-05 09:59 UTC, noaov1 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @MohammadNassar1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzb4TYr79Wk9nVCfx4v:-Nzb4TYr79Wk9nVCfx4w:bb70b9v) ([raw file](https://github.com/starkware-libs/blockifier/blob/66d2cdf3409216c5a68639a40221461baed08082/crates/blockifier/src/blockifier/transaction_executor.rs#L151)):*
> ```XML
>         let chunk_state = ThreadSafeVersionedState::new(versioned_state);
>         // TODO(barak, 01/08/2024): Consider moving `chunk_state` and lock it inside the
>         // WorkerExecutor instead of Arc::clone it.
> ```

Why not do it now?



_Code quote:_
```XML
        // TODO(barak, 01/08/2024): Consider moving `chunk_state` and lock it inside the
        // WorkerExecutor instead of Arc::clone it.
```
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 199 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzboTua8sWUpthWW0XG:-NzboTua8sWUpthWW0XH:b-ejlptx) ([raw file](https://github.com/starkware-libs/blockifier/blob/66d2cdf3409216c5a68639a40221461baed08082/crates/blockifier/src/blockifier/transaction_executor.rs#L199)):*
> ```XML
>         drop(worker_executor);
>         let mut versioned_state_after_use = chunk_state.into_inner_state();
>         versioned_state_after_use.commit(committed_chunk_size);
> ```

And call it only if `committed_chunk_size > 0`.
Alternatively, edit the `commit` method (to allow an empty commit).
Thanks @Yoni-Starkware!



_Suggestion:_
```XML
        versioned_state_after_use.commit(committed_chunk_size-1);
```


<!-- Sent from Reviewable.io -->

2024-06-05 10:15 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware, @MohammadNassar1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzbt55xDukRnQoOsLc9:-Nzbt55xDukRnQoOsLcA:b-8zv0py) ([raw file](https://github.com/starkware-libs/blockifier/blob/66d2cdf3409216c5a68639a40221461baed08082/crates/blockifier/src/blockifier/transaction_executor.rs#L57)):*
> ```XML
> }
> 
> impl<S: StateReader + Send + Sync> TransactionExecutor<S> {
> ```

Is this necessary? (same re stateful validator)
If so, please move `execute_chunk` to a separate impl block



_Code quote:_
```XML
r + Send + Sync>
```


<!-- Sent from Reviewable.io -->

2024-06-05 10:36 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzY-L2z9RaOl1l3Sjwn:-Nzby1Dv574JGc1ySEmS:b-2dp066) ([raw file](https://github.com/starkware-libs/blockifier/blob/2d1c422472d71b5e2694fb35422a3561cd8bfb98/crates/blockifier/src/blockifier/transaction_executor.rs#L197)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

What happens if the method crashes after "taking" `block_state` and before "replacing" it?

Does rust have to drop `worker_executor` if the method panics while it still exists?
If so, implementing the `Drop` trait for `WorkerExecutor` and doing the `replace` inside `drop` might be enough to force rust to replace the `block_state` when panicking.
</blockquote></details>

The run ends after panic, so it should not matter
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 199 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzboTua8sWUpthWW0XG:-NzbxMD4DUneeyIblRzD:b-2gjxsr) ([raw file](https://github.com/starkware-libs/blockifier/blob/66d2cdf3409216c5a68639a40221461baed08082/crates/blockifier/src/blockifier/transaction_executor.rs#L199)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

And call it only if `committed_chunk_size > 0`.
Alternatively, edit the `commit` method (to allow an empty commit).
Thanks @Yoni-Starkware!
</blockquote></details>

Let's be consistent - either `commit_index` (non-inclusive) or `chunk_size`/`n_committed_txs` everywhere (non-blocking for this PR)

I vote for `commit_index`


<!-- Sent from Reviewable.io -->

2024-06-05 13:35 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 152 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzY30t38W2Uxl0JVbO3:-Nzc_zRtDdxBXvzZQB1W:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2d1c422472d71b5e2694fb35422a3561cd8bfb98/crates/blockifier/src/blockifier/transaction_executor.rs#L152)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Could we perhaps use the worker_executor as sort of a context_manager?
Where this block of code happens in `WorkerExecutor::new`, and the block of code starting at `drop(worker_executor)` and ending at replacing the `block_state` would happen in the implementation of the `Drop` trait for `WorkerExecutor`?

I think it would be cleaner to do it this way if possible.

Non-blocking.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 197 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzY-L2z9RaOl1l3Sjwn:-NzcaV5nEU1s9s7zp2_C:b-yutgvz) ([raw file](https://github.com/starkware-libs/blockifier/blob/2d1c422472d71b5e2694fb35422a3561cd8bfb98/crates/blockifier/src/blockifier/transaction_executor.rs#L197)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

The run ends after panic, so it should not matter
</blockquote></details>

Done. As discussed offline.
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzb4TYr79Wk9nVCfx4v:-Nzc_xG406mtuvTlW_Hf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/66d2cdf3409216c5a68639a40221461baed08082/crates/blockifier/src/blockifier/transaction_executor.rs#L151)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why not do it now?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-05 13:52 UTC, barak-b-starkware commented
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzbt55xDukRnQoOsLc9:-Nzce_-b4Wpx0abFk5vt:bk0u9vp) ([raw file](https://github.com/starkware-libs/blockifier/blob/66d2cdf3409216c5a68639a40221461baed08082/crates/blockifier/src/blockifier/transaction_executor.rs#L57)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Is this necessary? (same re stateful validator)
If so, please move `execute_chunk` to a separate impl block
</blockquote></details>

It is necessary, If you want another `impl` block we need to also move `execute_txs` that calls to `execute_chunk`, so we would get one block with `execute_txs` and `execute_chunk` and another block with the rest, WDYT?


<!-- Sent from Reviewable.io -->

2024-06-05 14:17 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzbt55xDukRnQoOsLc9:-Nzcjzz7892y-bqqq_VZ:b-7c0hro) ([raw file](https://github.com/starkware-libs/blockifier/blob/66d2cdf3409216c5a68639a40221461baed08082/crates/blockifier/src/blockifier/transaction_executor.rs#L57)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

It is necessary, If you want another `impl` block we need to also move `execute_txs` that calls to `execute_chunk`, so we would get one block with `execute_txs` and `execute_chunk` and another block with the rest, WDYT?
</blockquote></details>

It makes sense, actually. And maybe it could solve the `concurrency` feature easily—put the entire impl under the feature flag. There would be no execute_txs at all without it.


<!-- Sent from Reviewable.io -->

2024-06-05 14:35 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 200 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzcoXUz8JQ-1XVqwuOV:-NzcoXUz8JQ-1XVqwuOW:b38eukn) ([raw file](https://github.com/starkware-libs/blockifier/blob/d59d2766589b3f2ddc4a253552bcef968fffb0d2/crates/blockifier/src/blockifier/transaction_executor.rs#L200)):*
> ```XML
>             })
>             .commit_chunk_and_recover_block_state(commit_index);
>         self.block_state.replace(block_state_after_commit);
> ```

Why not?
Sounds like you should use `replace` if you care about the old value. In our case, it must always be None.



_Suggestion:_
```XML
self.block_state = Some(block_state_after_commit);
```


<!-- Sent from Reviewable.io -->

2024-06-05 14:43 UTC, avi-starkware commented
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 200 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzcoXUz8JQ-1XVqwuOV:-Nzcpf8cC37X30TFize4:b-rzndi4) ([raw file](https://github.com/starkware-libs/blockifier/blob/d59d2766589b3f2ddc4a253552bcef968fffb0d2/crates/blockifier/src/blockifier/transaction_executor.rs#L200)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why not?
Sounds like you should use `replace` if you care about the old value. In our case, it must always be None.
</blockquote></details>

It's not exactly the same thing. `replace` (see [docs](https://doc.rust-lang.org/std/mem/fn.replace.html)) puts the value inside the existing `Some` wrapper without dropping it. Your suggestion will drop the old `Some` and create a new wrapper. I'm not sure it is significant, but the reciprocal operation of `take` is `replace`, so I think what barak did is the correct way to do it. 


<!-- Sent from Reviewable.io -->

2024-06-05 14:50 UTC, avi-starkware commented
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 199 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzcqlIIASGnnCEYNHhQ:-NzcqlIIASGnnCEYNHhR:b-7w2h9u) ([raw file](https://github.com/starkware-libs/blockifier/blob/d59d2766589b3f2ddc4a253552bcef968fffb0d2/crates/blockifier/src/blockifier/transaction_executor.rs#L199)):*
> ```XML
>                 )
>             })
>             .commit_chunk_and_recover_block_state(commit_index);
> ```

This is incorrect and confusing. See my suggestion for the correct code.

Note: 
* The array `tx_execution_results` should be of length `n_committed_txs`. The current code makes it of length `n_committed_txs - 1`.
* I think we should use a variable named something like `last_committed_tx_index` to make it clear what the argument provided to `commit_chunk_and_recover_block_state` needs to be. Just putting `- 1` in the input is unclear.



_Suggestion:_
```XML
        let n_committed_txs = worker_executor_factory.scheduler.get_n_committed_txs();
        let tx_execution_results = worker_executor_factory
            .execution_outputs
            .iter()
            .fold_while(Vec::new(), |mut results, execution_output| {
                if results.len() > n_committed_txs {
                    Done(results)
                } else {
                    let locked_execution_output = execution_output
                        .lock()
                        .expect("Failed to lock execution output.")
                        .take()
                        .expect("Output must be ready.");
                    results.push(
                        locked_execution_output.result.map_err(TransactionExecutorError::from),
                    );
                    Continue(results)
                }
            })
            .into_inner();
        
        let last_committed_tx_index = n_committed_txs - 1
        let block_state_after_commit = Arc::try_unwrap(worker_executor_factory)
            .unwrap_or_else(|_| {
                panic!(
                    "To consume the block state, you must have only one strong reference to the \
                     worker executor factory. Consider dropping objects that hold a reference to \
                     it."
                )
            })
            .commit_chunk_and_recover_block_state(last_committed_tx_index);
```


<!-- Sent from Reviewable.io -->

2024-06-05 15:11 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzbt55xDukRnQoOsLc9:-NzcwEkL3U0hM2Hmc_9M:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/66d2cdf3409216c5a68639a40221461baed08082/crates/blockifier/src/blockifier/transaction_executor.rs#L57)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

It makes sense, actually. And maybe it could solve the `concurrency` feature easily—put the entire impl under the feature flag. There would be no execute_txs at all without it.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 170 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzcp8919ip_2exd4Ymv:-NzcweMX5Xe0mi2I6isC:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d59d2766589b3f2ddc4a253552bcef968fffb0d2/crates/blockifier/src/blockifier/transaction_executor.rs#L170)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What will happen when `n_commited_txs = 0`? Will we get 0 or -1?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 199 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzcqlIIASGnnCEYNHhQ:-NzcwcPY-m8v2LD-a6pl:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d59d2766589b3f2ddc4a253552bcef968fffb0d2/crates/blockifier/src/blockifier/transaction_executor.rs#L199)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

This is incorrect and confusing. See my suggestion for the correct code.

Note: 
* The array `tx_execution_results` should be of length `n_committed_txs`. The current code makes it of length `n_committed_txs - 1`.
* I think we should use a variable named something like `last_committed_tx_index` to make it clear what the argument provided to `commit_chunk_and_recover_block_state` needs to be. Just putting `- 1` in the input is unclear.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-05 15:33 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzbt55xDukRnQoOsLc9:-Nzd14SQB7Xc-ohsim7E:broepoi) ([raw file](https://github.com/starkware-libs/blockifier/blob/66d2cdf3409216c5a68639a40221461baed08082/crates/blockifier/src/blockifier/transaction_executor.rs#L57)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove the send + sync from here and from the stateful validator


<!-- Sent from Reviewable.io -->

2024-06-05 15:43 UTC, noaov1 requested changes
> Reviewed 3 of 5 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 6 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @MohammadNassar1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 170 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzcp8919ip_2exd4Ymv:-Nzd-E3R1w-1PH8PT9ij:bl4qojv) ([raw file](https://github.com/starkware-libs/blockifier/blob/d59d2766589b3f2ddc4a253552bcef968fffb0d2/crates/blockifier/src/blockifier/transaction_executor.rs#L170)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

WDYM?
I think it will panic. See my comment below.
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 262 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzd1sIsD1tsfy5OV1hr:-Nzd1sIsD1tsfy5OV1hs:b2nhkyh) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ba035e73441c82a05f39cc5e01eaae91cf709c4/crates/blockifier/src/blockifier/transaction_executor.rs#L262)):*
> ```XML
>         });
> 
>         let n_committed_txs = worker_executor_factory.scheduler.get_n_committed_txs() - 1;
> ```

No?



_Suggestion:_
```XML
        let n_committed_txs = worker_executor_factory.scheduler.get_n_committed_txs() ;
```
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 283 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzd1wXO3cddGcvWFLDy:-Nzd1wXO3cddGcvWFLDz:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ba035e73441c82a05f39cc5e01eaae91cf709c4/crates/blockifier/src/blockifier/transaction_executor.rs#L283)):*
> ```XML
>             .into_inner();
> 
>         let last_committed_tx_index = n_committed_txs - 1;
> ```





_Suggestion:_
```XML
        if n_committed_txs > 0 {
            let last_committed_tx_index = n_committed_txs - 1;
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 56 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzd2Sdo3EavlfUj9Epv:-Nzd2Sdo3EavlfUj9Epw:b104dkf) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ba035e73441c82a05f39cc5e01eaae91cf709c4/crates/blockifier/src/concurrency/worker_logic.rs#L56)):*
> ```XML
> impl<'a, S: StateReader> WorkerExecutor<'a, S> {
>     pub fn new(
>         state: ThreadSafeVersionedState<CachedState<S>>,
> ```

Why cached state?



_Suggestion:_
```XML
        state: ThreadSafeVersionedState<S>,
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 70 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzd2XwyCHzoZMTuLVQ1:-Nzd2XwyCHzoZMTuLVQ2:b-uwm7hn) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ba035e73441c82a05f39cc5e01eaae91cf709c4/crates/blockifier/src/concurrency/worker_logic.rs#L70)):*
> ```XML
>     // TODO(barak, 01/08/2024): Remove the `new` method or move it to test utils.
>     pub fn create_factory(
>         state: CachedState<S>,
> ```

Will this work?



_Suggestion:_
```XML
        state: S,
```


<!-- Sent from Reviewable.io -->

2024-06-05 15:47 UTC, avi-starkware commented
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 262 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzd1sIsD1tsfy5OV1hr:-Nzd4Fb84KwEwOmWIIHD:b-qldd7s) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ba035e73441c82a05f39cc5e01eaae91cf709c4/crates/blockifier/src/blockifier/transaction_executor.rs#L262)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

No?
</blockquote></details>

You are correct Noa


<!-- Sent from Reviewable.io -->

2024-06-05 15:47 UTC, avi-starkware commented
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 283 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzd1wXO3cddGcvWFLDy:-Nzd4-546hUO6qyB1lfl:brfmolf) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ba035e73441c82a05f39cc5e01eaae91cf709c4/crates/blockifier/src/blockifier/transaction_executor.rs#L283)):*
> ```XML
>             .into_inner();
> 
>         let last_committed_tx_index = n_committed_txs - 1;
> ```

Maybe put it inside `commit_chunk_and_recover_block_state` (condition and variable)?


<!-- Sent from Reviewable.io -->

2024-06-05 22:01 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzbt55xDukRnQoOsLc9:-NzeLAsyALnt_5UkF4vh:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/66d2cdf3409216c5a68639a40221461baed08082/crates/blockifier/src/blockifier/transaction_executor.rs#L57)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Remove the send + sync from here and from the stateful validator
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 170 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzcp8919ip_2exd4Ymv:-NzeLW8x3IAdz5KP0E7m:b-x5xj07) ([raw file](https://github.com/starkware-libs/blockifier/blob/d59d2766589b3f2ddc4a253552bcef968fffb0d2/crates/blockifier/src/blockifier/transaction_executor.rs#L170)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM?
I think it will panic. See my comment below.
</blockquote></details>

Done.
The `-1` was left by mistake.
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 262 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzd1sIsD1tsfy5OV1hr:-NzeLbPM3ApnZxSgdQjQ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ba035e73441c82a05f39cc5e01eaae91cf709c4/crates/blockifier/src/blockifier/transaction_executor.rs#L262)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

You are correct Noa
</blockquote></details>

Done.
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 283 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzd1wXO3cddGcvWFLDy:-NzeLscD-qQKs-wIPC8e:bz9w3p5) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ba035e73441c82a05f39cc5e01eaae91cf709c4/crates/blockifier/src/blockifier/transaction_executor.rs#L283)):*
<details><summary><i>Previously, avi-starkware wrote…</i></summary><blockquote>

Maybe put it inside `commit_chunk_and_recover_block_state` (condition and variable)?
</blockquote></details>

Done.
see [here](https://reviewable.io/reviews/starkware-libs/blockifier/1948) also
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 56 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzd2Sdo3EavlfUj9Epv:-NzeOU229XXyEN0CDC_Y:b-g7lj31) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ba035e73441c82a05f39cc5e01eaae91cf709c4/crates/blockifier/src/concurrency/worker_logic.rs#L56)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I guess that implementing `commit_chunk_and_recover_block_state` in this struct enforces this
</blockquote></details>

```
expected `ThreadSafeVersionedState<S>`, found `ThreadSafeVersionedState<CachedState<...>>`
```
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 70 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzd2XwyCHzoZMTuLVQ1:-NzeOgOzDWCBntsQLaX6:b-kv2yol) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ba035e73441c82a05f39cc5e01eaae91cf709c4/crates/blockifier/src/concurrency/worker_logic.rs#L70)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Will this work?
</blockquote></details>

```
expected `ThreadSafeVersionedState<CachedState<...>>`, found `ThreadSafeVersionedState<S>`
```


<!-- Sent from Reviewable.io -->

2024-06-05 22:25 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 11 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzeVLkvE9wnxb6yZ_t_:-NzeVLkvE9wnxb6yZ_ta:bb895c6) ([raw file](https://github.com/starkware-libs/blockifier/blob/cbbff6255b708e57da19edcd736759eca1c61ad8/crates/blockifier/src/blockifier/transaction_executor.rs#L11)):*
> ```XML
> use crate::blockifier::config::TransactionExecutorConfig;
> use crate::bouncer::{Bouncer, BouncerWeights};
> use crate::concurrency::worker_logic::WorkerExecutor;
> ```

Currently doesn't pass CI.
@Yoni-Starkware 
@noaov1 



_Code quote:_
```XML
use crate::concurrency::worker_logic::WorkerExecutor;
```
___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 204 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzeVE051h2gXkv36iU2:-NzeVE051h2gXkv36iU3:bdfdzd4) ([raw file](https://github.com/starkware-libs/blockifier/blob/cbbff6255b708e57da19edcd736759eca1c61ad8/crates/blockifier/src/blockifier/transaction_executor.rs#L204)):*
> ```XML
> }
> 
> #[cfg(feature = "concurrency")]
> ```

Currently doesn't pass CI
@Yoni-Starkware 
@noaov1 



_Code quote:_
```XML
#[cfg(feature = "concurrency")]
```


<!-- Sent from Reviewable.io -->

2024-06-06 04:42 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 11 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzeVLkvE9wnxb6yZ_t_:-Nzfp6jM0jjMO_ea-_AA:b-7ofovg) ([raw file](https://github.com/starkware-libs/blockifier/blob/cbbff6255b708e57da19edcd736759eca1c61ad8/crates/blockifier/src/blockifier/transaction_executor.rs#L11)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Currently doesn't pass CI.
@Yoni-Starkware 
@noaov1
</blockquote></details>

Add `#[cfg(feature = "concurrency")]` above my test, that's okay https://github.com/starkware-libs/blockifier/blob/d90e9b9bdf1f1e484ce412e7756394f1fc6ee794/crates/blockifier/src/blockifier/transaction_executor_test.rs#L273

We need to solve @avi-starkware `execute_chunk_of_transfers`. Make it work somehow and we'll clean later, this is a test util


<!-- Sent from Reviewable.io -->

2024-06-06 04:42 UTC, Yoni-Starkware reviewed
> Reviewed 2 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)



<!-- Sent from Reviewable.io -->

2024-06-06 05:52 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 11 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzeVLkvE9wnxb6yZ_t_:-Nzg5iDpEfZGYYnLxUuU:bivue7v) ([raw file](https://github.com/starkware-libs/blockifier/blob/cbbff6255b708e57da19edcd736759eca1c61ad8/crates/blockifier/src/blockifier/transaction_executor.rs#L11)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Add `#[cfg(feature = "concurrency")]` above my test, that's okay https://github.com/starkware-libs/blockifier/blob/d90e9b9bdf1f1e484ce412e7756394f1fc6ee794/crates/blockifier/src/blockifier/transaction_executor_test.rs#L273

We need to solve @avi-starkware `execute_chunk_of_transfers`. Make it work somehow and we'll clean later, this is a test util
</blockquote></details>

Sorry, it's more complicated


<!-- Sent from Reviewable.io -->

2024-06-06 07:32 UTC, noaov1 reviewed
> Reviewed 1 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 11 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzeVLkvE9wnxb6yZ_t_:-NzgRIC2DT3BYR9aNiZw:b-an1ry) ([raw file](https://github.com/starkware-libs/blockifier/blob/cbbff6255b708e57da19edcd736759eca1c61ad8/crates/blockifier/src/blockifier/transaction_executor.rs#L11)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Sorry, it's more complicated
</blockquote></details>

A suggestion:
Move `execute_txs` to the regular impl (is it posiible?). Define:
Will that help?



_Code snippet:_
```XML
cfg(not(feature = "concurrency"))
pub fn execute_chunk(...){
    unimplemented!()
}
```


<!-- Sent from Reviewable.io -->

2024-06-06 07:40 UTC, noaov1 reviewed
> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @MohammadNassar1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 56 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzd2Sdo3EavlfUj9Epv:-NzgTwJD1Jyo89p83gqy:b-3fg62y) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ba035e73441c82a05f39cc5e01eaae91cf709c4/crates/blockifier/src/concurrency/worker_logic.rs#L56)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

```
expected `ThreadSafeVersionedState<S>`, found `ThreadSafeVersionedState<CachedState<...>>`
```
</blockquote></details>

A suggestion:
Change `CachedState<S>` to `S` and define (removing this method from the "regular" impl):



_Code snippet:_
```XML
impl<'a, U: UpdatableState> WorkerExecutor<'a, U> {
    pub fn commit_chunk_and_recover_block_state(self, n_committed_txs: usize) -> U {
        self.state.into_inner_state().commit_chunk_and_recover_block_state(n_committed_txs)
    }
}
```


<!-- Sent from Reviewable.io -->

2024-06-06 08:22 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 5 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 11 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzeVLkvE9wnxb6yZ_t_:-NzgcEbYDRh1CrNvpOi0:b7zobpk) ([raw file](https://github.com/starkware-libs/blockifier/blob/cbbff6255b708e57da19edcd736759eca1c61ad8/crates/blockifier/src/blockifier/transaction_executor.rs#L11)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

A suggestion:
Move `execute_txs` to the regular impl (is it posiible?). Define:
Will that help?
</blockquote></details>

It doesn't work, see the previous discussion [here](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzbt55xDukRnQoOsLc9)

Didn't understand your suggestion, the `execute_chunk` is the heart of the feature, you want to configure it w/ "not(feature = "concurrency")"?
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 56 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzd2Sdo3EavlfUj9Epv:-Nzgd0eqAbE7UWZEaWA1:b-kw9g6r) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ba035e73441c82a05f39cc5e01eaae91cf709c4/crates/blockifier/src/concurrency/worker_logic.rs#L56)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

A suggestion:
Change `CachedState<S>` to `S` and define (removing this method from the "regular" impl):
</blockquote></details>

WDYM by "this method"?


<!-- Sent from Reviewable.io -->

2024-06-06 08:51 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 11 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzeVLkvE9wnxb6yZ_t_:-NzgjmhT0aeaHaEH8iOW:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cbbff6255b708e57da19edcd736759eca1c61ad8/crates/blockifier/src/blockifier/transaction_executor.rs#L11)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

It doesn't work, see the previous discussion [here](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzbt55xDukRnQoOsLc9)

Didn't understand your suggestion, the `execute_chunk` is the heart of the feature, you want to configure it w/ "not(feature = "concurrency")"?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/concurrency/worker_logic.rs` line 56 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzd2Sdo3EavlfUj9Epv:-Nzgi5Tw2S1cqRUGDMCf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8ba035e73441c82a05f39cc5e01eaae91cf709c4/crates/blockifier/src/concurrency/worker_logic.rs#L56)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

WDYM by "this method"?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-06 08:57 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 242 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzgl3Ol6HD7UYbe2eUZ:-Nzgl3Ol6HD7UYbe2eU_:b-gixiwm) ([raw file](https://github.com/starkware-libs/blockifier/blob/88b89ddf231904584beedf29a397bee37296ed58/crates/blockifier/src/blockifier/transaction_executor.rs#L242)):*
> ```XML
>                 .into_inner()
>         }
>     }
> ```

You can move this to the regular impl block (I think it's required)



_Code quote:_
```XML
    pub fn execute_txs(
        &mut self,
        txs: &[Transaction],
        charge_fee: bool,
    ) -> Vec<TransactionExecutorResult<TransactionExecutionInfo>> {
        if !self.config.concurrency_config.enabled {
            self.execute_txs_sequentially(txs, charge_fee)
        } else {
            txs.chunks(self.config.concurrency_config.chunk_size)
                .fold_while(Vec::new(), |mut results, chunk| {
                    let chunk_results = self.execute_chunk(chunk, charge_fee);
                    if chunk_results.len() < chunk.len() {
                        // Block is full.
                        results.extend(chunk_results);
                        Done(results)
                    } else {
                        results.extend(chunk_results);
                        Continue(results)
                    }
                })
                .into_inner()
        }
    }
```


<!-- Sent from Reviewable.io -->

2024-06-06 10:03 UTC, noaov1 reviewed
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 3 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @MohammadNassar1, and @OriStarkware)



<!-- Sent from Reviewable.io -->

2024-06-06 10:49 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @MohammadNassar1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 242 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-Nzgl3Ol6HD7UYbe2eUZ:-Nzh9SPG35ybFDWuzR0c:b-703idb) ([raw file](https://github.com/starkware-libs/blockifier/blob/88b89ddf231904584beedf29a397bee37296ed58/crates/blockifier/src/blockifier/transaction_executor.rs#L242)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

You can move this to the regular impl block (I think it's required)
</blockquote></details>

When I move it it complains about the trait bounds:
```
the method `execute_chunk` exists for mutable reference `&mut TransactionExecutor<S>`, but its trait bounds were not satisfied
```


<!-- Sent from Reviewable.io -->

2024-06-06 11:13 UTC, Yoni-Starkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @MohammadNassar1, and @OriStarkware)



<!-- Sent from Reviewable.io -->

2024-06-06 11:39 UTC, noaov1 reviewed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @MohammadNassar1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 253 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzhKlDv1xiewBFw0Bfk:-NzhKlDw0a5zR3q846Bg:bs1uchv) ([raw file](https://github.com/starkware-libs/blockifier/blob/955fba28753380abe15c30fa9a2f620ad847810f/crates/blockifier/src/blockifier/transaction_executor.rs#L253)):*
> ```XML
>         let block_state = self.block_state.take().expect("The block state should be `Some`.");
>         // TODO(barak, 01/08/2024): Make the transaction executor's block context's concurrency mode
>         // true from the context it was called.
> ```

WDYM?
Consider adding an assert `block_context..concurrency_mode = true`.



_Code quote:_
```XML
        // TODO(barak, 01/08/2024): Make the transaction executor's block context's concurrency mode
        // true from the context it was called.
```


<!-- Sent from Reviewable.io -->

2024-06-06 11:41 UTC, avi-starkware commented
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 262 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzhKsFq1CjJTE7TAoKL:-NzhKsFq1CjJTE7TAoKM:b-faeyj7) ([raw file](https://github.com/starkware-libs/blockifier/blob/955fba28753380abe15c30fa9a2f620ad847810f/crates/blockifier/src/blockifier/transaction_executor.rs#L262)):*
> ```XML
>             concurrent_block_context,
>             Mutex::new(&mut self.bouncer),
>         ));
> ```

As I said offline, I don't think "factory" fits here. You have a single `WorkerExecutor` instance and each thread gets a pointer to it. The word factory implies that the object generates other objects and it does not.

Nonblocking



_Suggestion:_
```XML
        let worker_executor = Arc::new(WorkerExecutor::initialize(
            block_state,
            chunk,
            concurrent_block_context,
            Mutex::new(&mut self.bouncer),
        ));
```


<!-- Sent from Reviewable.io -->

2024-06-06 11:45 UTC, avi-starkware commented
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 306 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzhMIAR6-Okc4kFVg0-:-NzhMIASBkbYCO48eFby:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/955fba28753380abe15c30fa9a2f620ad847810f/crates/blockifier/src/blockifier/transaction_executor.rs#L306)):*
> ```XML
>                      it."
>                 )
>             })
> ```





_Suggestion:_
```XML
            .except(
                "To consume the block state, you must have only one strong reference to the \
                worker executor factory. Consider dropping objects that hold a reference to \
                it."
            )
```


<!-- Sent from Reviewable.io -->

2024-06-06 12:39 UTC, avi-starkware submitted a review, later dismissed
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware, @MohammadNassar1, and @OriStarkware)



<!-- Sent from Reviewable.io -->

2024-06-06 12:59 UTC, noaov1 approved these changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 2 unresolved discussions (waiting on @avi-starkware, @barak-b-starkware, @MohammadNassar1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 253 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzhKlDv1xiewBFw0Bfk:-Nzhbzgv5hVVLXPHw4Wi:b4cygzl) ([raw file](https://github.com/starkware-libs/blockifier/blob/955fba28753380abe15c30fa9a2f620ad847810f/crates/blockifier/src/blockifier/transaction_executor.rs#L253)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I mean that when someone generates the `TransactionExecutor` or something that might call the method `execute_chunk`, he needs to ensure that the `concurrency_mode` is on.
Do you want to add an assertion here?
</blockquote></details>

Where there any tests that did not do it?
I think that yes. If concurrency mode is not enabled, then we will not want to execute the transactions concurrently, no?


<!-- Sent from Reviewable.io -->

2024-06-06 13:02 UTC, avi-starkware commented
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 306 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzhMIAR6-Okc4kFVg0-:-Nzhcg5PDNqpGp3C_zcc:bbb5saa) ([raw file](https://github.com/starkware-libs/blockifier/blob/955fba28753380abe15c30fa9a2f620ad847810f/crates/blockifier/src/blockifier/transaction_executor.rs#L306)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

The `except` method requires deriving `Debug` for the `WorkerExecutor`, the `ThreadSafeVersionedState`, the `PapyrusReader`, and the `StorageReader`.
The last one is from the `papyrus_storage` crate and doesn't derive `Debug` there.
It also requires `+ std::fmt::Debug` in the second `impl` block of the `TransactionExecutor`.

What would you like to do?
</blockquote></details>

Keep it as it was. I thought it is a small change.


<!-- Sent from Reviewable.io -->

2024-06-06 13:04 UTC, barak-b-starkware commented
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 253 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzhKlDv1xiewBFw0Bfk:-Nzhcd5t3spbnHIQfoHj:b3r63fh) ([raw file](https://github.com/starkware-libs/blockifier/blob/955fba28753380abe15c30fa9a2f620ad847810f/crates/blockifier/src/blockifier/transaction_executor.rs#L253)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Where there any tests that did not do it?
I think that yes. If concurrency mode is not enabled, then we will not want to execute the transactions concurrently, no?
</blockquote></details>

I'm not sure.
The "clone and field changing" that I've added here is not the best solution for what we want, but it's the shorter one.
I thought you might want to merge it today, so I chose the shorter one with a TODO for the "block_context passing" issue.
I'll open a new PR with a nicer solution, and I'll rebase this one on top of it (or the opposite). I'll ping you once it's ready.


<!-- Sent from Reviewable.io -->

2024-06-06 13:10 UTC, avi-starkware approved these changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 262 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzhKsFq1CjJTE7TAoKL:-NzhdJ1p3qaSISJrEyXn:bsvbcck) ([raw file](https://github.com/starkware-libs/blockifier/blob/955fba28753380abe15c30fa9a2f620ad847810f/crates/blockifier/src/blockifier/transaction_executor.rs#L262)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Done.
For the record, I think the `WorkerExecutor` is a factory, so you will never use the instance that was first created to call the `run` method. We use `Arc::clone()` to create references that can call the `run` method, so the single worker terminology here is confusing.
The struct's name can be `WrokerExecutorFactory` or something similar, and we should remove the `new` method to ensure consistent use everywhere.

Notice that now we have:
```
let worker_executor = Arc::clone(&worker_executor);
```
Which is confusing IMO.
</blockquote></details>

[Arc::clone](https://doc.rust-lang.org/std/sync/struct.Arc.html#impl-Clone-for-Arc%3CT,+A%3E)(&worker_executor) simply creates another pointer to the existing worker executor. It doesn't create a new WorkerExecutor instance, it only clones the Arc wrapper around it.

Calling run on `worker_executor` is syntactic sugar of the Arc implementation. Behind the scenes, it dereferences the Arc ref and then calls the method from the (single) `WorkerExecutor` instance.


<!-- Sent from Reviewable.io -->

2024-06-06 14:03 UTC, barak-b-starkware commented
*[`crates/blockifier/src/blockifier/transaction_executor.rs` line 253 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-NzhKlDv1xiewBFw0Bfk:-Nzhr4En4VKYB2iDkQuX:b8si0pd) ([raw file](https://github.com/starkware-libs/blockifier/blob/955fba28753380abe15c30fa9a2f620ad847810f/crates/blockifier/src/blockifier/transaction_executor.rs#L253)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I'm not sure.
The "clone and field changing" that I've added here is not the best solution for what we want, but it's the shorter one.
I thought you might want to merge it today, so I chose the shorter one with a TODO for the "block_context passing" issue.
I'll open a new PR with a nicer solution, and I'll rebase this one on top of it (or the opposite). I'll ping you once it's ready.
</blockquote></details>

[New PR](https://reviewable.io/reviews/starkware-libs/blockifier/1966) to eliminate the comment and the clone.


<!-- Sent from Reviewable.io -->

2024-06-06 14:14 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @avi-starkware, @MohammadNassar1, @noaov1, and @OriStarkware)



<!-- Sent from Reviewable.io -->

2024-06-06 14:34 UTC, Yoni-Starkware approved these changes
> Reviewed 1 of 2 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1, @noaov1, and @OriStarkware)



<!-- Sent from Reviewable.io -->

2024-06-09 06:37 UTC, noaov1 approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @OriStarkware)



<!-- Sent from Reviewable.io -->

2024-06-09 15:54 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-:-NzxhETq6fJU6Ti9YgTl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @OriStarkware)



<!-- Sent from Reviewable.io -->

2024-06-10 05:33 UTC, noaov1 approved these changes
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @OriStarkware)



<!-- Sent from Reviewable.io -->

2024-06-10 05:35 UTC, noaov1 approved these changes
> Reviewed 1 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @MohammadNassar1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/config.rs` line 7 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-O--d1Wb7henOeb5PaN5:-O--d1Wb7henOeb5PaN6:b-wwuctj) ([raw file](https://github.com/starkware-libs/blockifier/blob/bfc00d7dba548046f2bef6311bcb8df47f334e4e/crates/blockifier/src/blockifier/config.rs#L7)):*
> ```XML
> 
> #[derive(Debug, Clone)]
> #[cfg_attr(not(feature = "concurrency"), derive(Default))]
> ```

Why do we want default only when the concurrency feature is off?



_Code quote:_
```XML
#[cfg_attr(not(feature = "concurrency"), derive(Default))]
```


<!-- Sent from Reviewable.io -->

2024-06-10 05:44 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: all files reviewed, 1 unresolved discussion (waiting on @MohammadNassar1, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/blockifier/config.rs` line 7 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/1953#-O--d1Wb7henOeb5PaN5:-O--eff_-HwMKi4tUiFb:bk9isij) ([raw file](https://github.com/starkware-libs/blockifier/blob/bfc00d7dba548046f2bef6311bcb8df47f334e4e/crates/blockifier/src/blockifier/config.rs#L7)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why do we want default only when the concurrency feature is off?
</blockquote></details>

This `Default` derivation gives `enabled: false, n_workers: 0, chunk_size: 0`.
We have another default 10 lines below for the concurrency mode:



_Code quote:_
```XML
#[cfg(feature = "concurrency")]
impl Default for ConcurrencyConfig {
    fn default() -> Self {
        Self { enabled: true, n_workers: 4, chunk_size: 64 }
    }
}
```


<!-- Sent from Reviewable.io -->

2024-06-10 06:20 UTC, noaov1 approved these changes
> Reviewed 2 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1953)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1 and @OriStarkware)



<!-- Sent from Reviewable.io -->

2024-06-10 06:29 UTC, merged