fix(transaction): set default transaction version to three in invoke …
starkware-libs/blockifier pull request #1967
Opened 2024-06-06 14:28 UTC by meship-starkware

…function macro

2024-06-09 07:08 UTC, OriStarkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-:-NzvorFS3DnddWyhWmQI:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-NzvnmEG7dRjcizBKlM3:-NzvnmEG7dRjcizBKlM4:bxerglo) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c11aae051ab3345dcaf88e5a0dfecbdd56a95c3/crates/blockifier/src/concurrency/worker_logic_test.rs#L240)):*
> ```XML
> 
>     // Both transactions change the same storage key.
>     let account_tx0 = account_invoke_tx(invoke_tx_args! {
> ```

Shouldn't this be V1?
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-Nzvn_idD4UkCc2ktoyn:-Nzvn_idD4UkCc2ktoyo:b-3pvzah) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c11aae051ab3345dcaf88e5a0dfecbdd56a95c3/crates/blockifier/src/concurrency/worker_logic_test.rs#L247)):*
> ```XML
>             &[*storage_key.0.key(),storage_value0 ], // Calldata:  address, value.
>         ),
>         resource_bounds: l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE),
> ```

Why is this change necessary?



_Code quote:_
```XML
resource_bounds: l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE),
```
___
*[`crates/blockifier/src/test_utils/invoke.rs` line 39 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-NzvlaDt2RZala8WNKw5:-NzvlaDt2RZala8WNKw6:b30bdo) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c11aae051ab3345dcaf88e5a0dfecbdd56a95c3/crates/blockifier/src/test_utils/invoke.rs#L39)):*
> ```XML
>             sender_address: ContractAddress::default(),
>             calldata: calldata![],
>             // TODO(Dori, 10/10/2023): Change to THREE when supported.
> ```

Consider removing the TODO.


<!-- Sent from Reviewable.io -->

2024-06-09 07:59 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 240 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-NzvnmEG7dRjcizBKlM3:-NzvpFyi2hnluH3yArgA:b8dmk8e) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c11aae051ab3345dcaf88e5a0dfecbdd56a95c3/crates/blockifier/src/concurrency/worker_logic_test.rs#L240)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Shouldn't this be V1?
</blockquote></details>

I talked to Noa, and we decided that if there isn't a good reason for the transaction to be a V1 TX, then it should be V3.
So if it passes the test as V3 I changed it. @noaov1, if you have something to add, feel free.
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-Nzvn_idD4UkCc2ktoyn:-Nzvq9I235A3Nna_C9cz:b-mvgbyu) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c11aae051ab3345dcaf88e5a0dfecbdd56a95c3/crates/blockifier/src/concurrency/worker_logic_test.rs#L247)):*
<details><summary><i>Previously, OriStarkware wrote…</i></summary><blockquote>

Why is this change necessary?
</blockquote></details>

In some cases, it is not necessary. But when the taxes were V1, there was a max fee, so now that there are V3, I changed it for symmetry. 


<!-- Sent from Reviewable.io -->

2024-06-09 08:00 UTC, OriStarkware approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-06-09 14:46 UTC, barak-b-starkware requested changes
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1712 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-NzxSgLxA0vZ27i4R2Kq:-NzxSgLxA0vZ27i4R2Kr:b6se6kn) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7937a091fa9bbd8810c8d9f950932f5c5ff1952/crates/blockifier/src/transaction/transactions_test.rs#L1712)):*
> ```XML
>     let invoke_tx = crate::test_utils::invoke::invoke_tx(
>         invoke_tx_args! { calldata: execute_calldata, max_fee, sender_address, only_query, version: TransactionVersion::ONE},
>     );
> ```

Missing space



_Suggestion:_
```XML
    let invoke_tx = crate::test_utils::invoke::invoke_tx(
        invoke_tx_args! { calldata: execute_calldata, max_fee, sender_address, only_query, version: TransactionVersion::ONE },
    );
```


<!-- Sent from Reviewable.io -->

2024-06-10 05:39 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1712 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-NzxSgLxA0vZ27i4R2Kq:-O--eB1R-xuWDyvwI7DG:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7937a091fa9bbd8810c8d9f950932f5c5ff1952/crates/blockifier/src/transaction/transactions_test.rs#L1712)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Missing space
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-10 06:06 UTC, barak-b-starkware submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1712 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-NzxSgLxA0vZ27i4R2Kq:-O--jHNl1ltvMhg96fNk:bspn3bj) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7937a091fa9bbd8810c8d9f950932f5c5ff1952/crates/blockifier/src/transaction/transactions_test.rs#L1712)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Notice that for test files (I think), the formatter doesn't do its thing (I'm not sure why, by the way).
So, it is preferable to stick to our conventions manually, for example, short lines (shorter than 100, I think).
Non-blocking, you can do it in another PR if you want or try to apply the formatter on test files somehow or just leave it as is if it's not bothering you (: 



_Suggestion:_
```XML
    let invoke_tx = crate::test_utils::invoke::invoke_tx(
        invoke_tx_args! {
            calldata: execute_calldata,
            max_fee,
            sender_address,
            only_query,
            version: TransactionVersion::ONE
        },
    );
```


<!-- Sent from Reviewable.io -->

2024-06-13 13:31 UTC, noaov1 requested changes
> Reviewed 2 of 7 files at r1, 1 of 1 files at r2, 3 of 5 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: all files reviewed, 4 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 247 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-0Nap0CEkGbBIHBQwK:-O-0Nap0CEkGbBIHBQwL:bdqbywx) ([raw file](https://github.com/starkware-libs/blockifier/blob/f0962370fb6b7c3d44894da393e02fbb07ed9462/crates/blockifier/src/concurrency/worker_logic_test.rs#L247)):*
> ```XML
>             &[*storage_key.0.key(),storage_value0 ], // Calldata:  address, value.
>         ),
>         resource_bounds: l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE),
> ```

Consider defining a variable



_Code quote:_
```XML
l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE)
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 226 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-1EDwO45-xSMelujF4:-O-1EDwO45-xSMelujF5:b-bn40e3) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbd691d8660d3328b197830bce048da8a91b8a8b/crates/blockifier/src/concurrency/worker_logic_test.rs#L226)):*
> ```XML
>             &[*storage_key.0.key(),storage_value ], // Calldata:  address, value.
>         ),
>         version: TransactionVersion::ONE,
> ```

Can it be three as well?
Same question below.



_Code quote:_
```XML
        version: TransactionVersion::ONE,
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 887 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-Gmeii-seUrTB1pyo0:-O-Gmeii-seUrTB1pyo1:b-otywaw) ([raw file](https://github.com/starkware-libs/blockifier/blob/31ba7614e283a73fe833e372f31edd3eb91a8ac6/crates/blockifier/src/transaction/transactions_test.rs#L887)):*
> ```XML
>     let invalid_max_fee = Fee(minimal_fee.0 - 1);
>     let invalid_v1_tx = account_invoke_tx(
>         invoke_tx_args! { max_fee: invalid_max_fee, version: TransactionVersion::ONE,  ..valid_invoke_tx_args.clone() },
> ```

Why using max fee in V3 transaction?



_Code quote:_
```XML
    let invalid_v1_tx = account_invoke_tx(
        invoke_tx_args! { max_fee: invalid_max_fee, version: TransactionVersion::ONE,  ..valid_invoke_tx_args.clone() },
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1719 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-GmpZtBpnagHJpQ9Kd:-O-GmpZtBpnagHJpQ9Ke:b-k4r0b0) ([raw file](https://github.com/starkware-libs/blockifier/blob/31ba7614e283a73fe833e372f31edd3eb91a8ac6/crates/blockifier/src/transaction/transactions_test.rs#L1719)):*
> ```XML
>         sender_address,
>         only_query,
>         version: TransactionVersion::ONE
> ```

Can you please explain why should it be one?
Same below



_Code quote:_
```XML
        version: TransactionVersion::ONE
```


<!-- Sent from Reviewable.io -->

2024-06-16 06:31 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 226 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-1EDwO45-xSMelujF4:-O-UiLdJDHWDP67AzePO:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bbd691d8660d3328b197830bce048da8a91b8a8b/crates/blockifier/src/concurrency/worker_logic_test.rs#L226)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can it be three as well?
Same question below.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 887 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-Gmeii-seUrTB1pyo0:-O-GnTzF9O3AIPegsXhl:b-h0s2bz) ([raw file](https://github.com/starkware-libs/blockifier/blob/31ba7614e283a73fe833e372f31edd3eb91a8ac6/crates/blockifier/src/transaction/transactions_test.rs#L887)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why using max fee in V3 transaction?
</blockquote></details>

This is version one. Since it's in the variable's name, I assumed it needed to stay this way.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1719 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-GmpZtBpnagHJpQ9Kd:-O-UhroTEfhMUj8mEa-b:bmleyeo) ([raw file](https://github.com/starkware-libs/blockifier/blob/31ba7614e283a73fe833e372f31edd3eb91a8ac6/crates/blockifier/src/transaction/transactions_test.rs#L1719)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please explain why should it be one?
Same below
</blockquote></details>

I don't know if it should be ONE, but I haven't found a way to modify the expected tx info to pass the test when the version is THREE.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 981 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-UX3Vj2M9b-mdQP03s:-O-UX3Vk9Ir-UX66hXwI:b-faryp5) ([raw file](https://github.com/starkware-libs/blockifier/blob/65ffb1d2c0b2dde88125378ae754d3592ea66a1a/crates/blockifier/src/transaction/transactions_test.rs#L981)):*
> ```XML
>     println!("{:?}", execution_error);
>     assert!(execution_error.starts_with("Insufficient max L1 gas:"));
>     // Test that fee was charged.
> ```

I am not sure if this is the right way to test that the fee was charged in V3 TX.  


<!-- Sent from Reviewable.io -->

2024-06-16 07:34 UTC, barak-b-starkware reviewed
> Reviewed 1 of 5 files at r6, 2 of 2 files at r7, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: all files reviewed, 5 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 214 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-Up4QS5ZDpISYX1VtK:-O-Up4QT20AhKYEzy1TP:b1wxs36) ([raw file](https://github.com/starkware-libs/blockifier/blob/2f928ff737a729b6f4a8a522111d470d2a2efb92/crates/blockifier/src/concurrency/worker_logic_test.rs#L214)):*
> ```XML
>             &[*storage_key.0.key(),storage_value ], // Calldata:  address, value.
>         ),
>         resource_bounds: resource_bounds.clone(),
> ```

I wonder if we want to add `#[derive(Copy)]` to `pub struct ResourceBoundsMapping(pub BTreeMap<Resource, ResourceBounds>)`.
On one hand, it's a map that potentially can grow uncontrolled. On the other hand, in the near future, it will only have 2 keys, and in the long run, maybe 5. The redundant `clone()` everywhere is annoying but maybe it's only me, WDYT?
Another option (out of this PR scope) is to implement the `pub struct ResourceBoundsMapping` w/o `(pub BTreeMap<_, _>)`.
cc @noaov1 



_Suggestion:_
```XML
resource_bounds: resource_bounds,
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 981 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-UX3Vj2M9b-mdQP03s:-O-UtdIH5WUz5wY-kh9_:b-p1c5rd) ([raw file](https://github.com/starkware-libs/blockifier/blob/65ffb1d2c0b2dde88125378ae754d3592ea66a1a/crates/blockifier/src/transaction/transactions_test.rs#L981)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I am not sure if this is the right way to test that the fee was charged in V3 TX.
</blockquote></details>

Did you try playing with the two values? (for example, by changing the `minimal_fee` calculation by passing different `minimal_resource_bounds`)


<!-- Sent from Reviewable.io -->

2024-06-16 08:37 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 981 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-UX3Vj2M9b-mdQP03s:-O-VA5Hp9MFTa19nj5-y:brnciw8) ([raw file](https://github.com/starkware-libs/blockifier/blob/65ffb1d2c0b2dde88125378ae754d3592ea66a1a/crates/blockifier/src/transaction/transactions_test.rs#L981)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Did you try playing with the two values? (for example, by changing the `minimal_fee` calculation by passing different `minimal_resource_bounds`)
</blockquote></details>

Yes, and it fails if they are different. I also know that max_fee = max_amount*max_gas_price.


<!-- Sent from Reviewable.io -->

2024-06-16 11:38 UTC, barak-b-starkware reviewed
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: all files reviewed, 4 unresolved discussions (waiting on @meship-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-06-16 11:42 UTC, noaov1 requested changes
> Reviewed 1 of 2 files at r8, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 214 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-Up4QS5ZDpISYX1VtK:-O-VecIGDHe0ZnO6QSdF:b-l0nbpa) ([raw file](https://github.com/starkware-libs/blockifier/blob/2f928ff737a729b6f4a8a522111d470d2a2efb92/crates/blockifier/src/concurrency/worker_logic_test.rs#L214)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I wonder if we want to add `#[derive(Copy)]` to `pub struct ResourceBoundsMapping(pub BTreeMap<Resource, ResourceBounds>)`.
On one hand, it's a map that potentially can grow uncontrolled. On the other hand, in the near future, it will only have 2 keys, and in the long run, maybe 5. The redundant `clone()` everywhere is annoying but maybe it's only me, WDYT?
Another option (out of this PR scope) is to implement the `pub struct ResourceBoundsMapping` w/o `(pub BTreeMap<_, _>)`.
cc @noaov1
</blockquote></details>

Good point.
If we will add copy, then what might come an heavy struct, will be copied without us noticing it.
Is it needed for non-tests purpose?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 969 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-VqdfS7NE925JMp5Ht:-O-VqdfS7NE925JMp5Hu:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c803abe4c4946166ce91ca3cb57e1f0ce717eab4/crates/blockifier/src/transaction/transactions_test.rs#L969)):*
> ```XML
>     let minimal_resource_bounds = l1_resource_bounds(
>         u64::try_from(minimal_l1_gas).unwrap(),
>         u128::from(block_context.block_info.gas_prices.eth_l1_gas_price),
> ```





_Suggestion:_
```XML
 u128::from(block_context.block_info.gas_prices.strk_l1_gas_price),
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 981 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-VqYvk3YcM0rEANLfS:-O-VqYvk3YcM0rEANLfT:b3kre) ([raw file](https://github.com/starkware-libs/blockifier/blob/c803abe4c4946166ce91ca3cb57e1f0ce717eab4/crates/blockifier/src/transaction/transactions_test.rs#L981)):*
> ```XML
>     assert!(execution_error.starts_with("Insufficient max L1 gas:"));
>     // Test that fee was charged.
>     assert_eq!(execution_result.transaction_receipt.fee, minimal_fee);
> ```

?



_Suggestion:_
```XML
assert_eq!(execution_result.transaction_receipt.fee, minimal_resource_bounds);
```


<!-- Sent from Reviewable.io -->

2024-06-16 11:54 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 214 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-Up4QS5ZDpISYX1VtK:-O-VspyVBKUntpROKgQ6:b3zvrll) ([raw file](https://github.com/starkware-libs/blockifier/blob/2f928ff737a729b6f4a8a522111d470d2a2efb92/crates/blockifier/src/concurrency/worker_logic_test.rs#L214)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Good point.
If we will add copy, then what might come an heavy struct, will be copied without us noticing it.
Is it needed for non-tests purpose?
</blockquote></details>

It is used here: https://github.com/starkware-libs/blockifier/blob/966013b72c394c0208de400bc5f8f7271f05caa8/crates/blockifier/src/transaction/transactions.rs#L237
for non-test purpose 


<!-- Sent from Reviewable.io -->

2024-06-16 12:01 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 981 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-VqYvk3YcM0rEANLfS:-O-VtclZ-fJnqGiPKZod:b-3y61kk) ([raw file](https://github.com/starkware-libs/blockifier/blob/c803abe4c4946166ce91ca3cb57e1f0ce717eab4/crates/blockifier/src/transaction/transactions_test.rs#L981)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

?
</blockquote></details>

This check was present when the TX was version 1, and I did not know with what check I should replace it. 


<!-- Sent from Reviewable.io -->

2024-06-16 12:18 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 969 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-VqdfS7NE925JMp5Ht:-O-Vz5MSB4G3TUexcWBk:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c803abe4c4946166ce91ca3cb57e1f0ce717eab4/crates/blockifier/src/transaction/transactions_test.rs#L969)):*
> ```XML
>     let minimal_resource_bounds = l1_resource_bounds(
>         u64::try_from(minimal_l1_gas).unwrap(),
>         u128::from(block_context.block_info.gas_prices.eth_l1_gas_price),
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-06-16 13:16 UTC, noaov1 requested changes
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @barak-b-starkware and @meship-starkware)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 981 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-VqYvk3YcM0rEANLfS:-O-W9JG21UcaJr6PDb9K:bkfbcpa) ([raw file](https://github.com/starkware-libs/blockifier/blob/c803abe4c4946166ce91ca3cb57e1f0ce717eab4/crates/blockifier/src/transaction/transactions_test.rs#L981)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

This check was present when the TX was version 1, and I did not know with what check I should replace it.
</blockquote></details>

I think it should be `minimal_resource_bounds` (you can delete the `minimal_fee`).
See [here](https://github.com/starkware-libs/blockifier/blob/7140ce87a3ee8c65fccc0cde4b2467a27016aee2/crates/blockifier/src/fee/fee_checks.rs#L73)


<!-- Sent from Reviewable.io -->

2024-06-16 13:20 UTC, barak-b-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 214 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-Up4QS5ZDpISYX1VtK:-O-WBiak5bt2-SrmMPo7:b-fjdoli) ([raw file](https://github.com/starkware-libs/blockifier/blob/2f928ff737a729b6f4a8a522111d470d2a2efb92/crates/blockifier/src/concurrency/worker_logic_test.rs#L214)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

It is used here: https://github.com/starkware-libs/blockifier/blob/966013b72c394c0208de400bc5f8f7271f05caa8/crates/blockifier/src/transaction/transactions.rs#L237
for non-test purpose
</blockquote></details>

What is the meaning of "then what might come an heavy struct"?
I'm trying to say that it can't be heavy, not soon, and not in the long run.


<!-- Sent from Reviewable.io -->

2024-06-16 13:20 UTC, barak-b-starkware reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-06-16 14:36 UTC, noaov1 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: all files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @meship-starkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 214 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-Up4QS5ZDpISYX1VtK:-O-WTAHW9HgD9uM7g0gi:b-rvkl69) ([raw file](https://github.com/starkware-libs/blockifier/blob/2f928ff737a729b6f4a8a522111d470d2a2efb92/crates/blockifier/src/concurrency/worker_logic_test.rs#L214)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

What is the meaning of "then what might come an heavy struct"?
I'm trying to say that it can't be heavy, not soon, and not in the long run.
</blockquote></details>

Some external user of the blockifier can choose to have a heavy struct (as you mentioned, it can grow uncontrollably).


<!-- Sent from Reviewable.io -->

2024-06-17 10:41 UTC, barak-b-starkware commented
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 214 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-Up4QS5ZDpISYX1VtK:-O-_mMZd5AfpmRBnUlgL:b4wix0i) ([raw file](https://github.com/starkware-libs/blockifier/blob/2f928ff737a729b6f4a8a522111d470d2a2efb92/crates/blockifier/src/concurrency/worker_logic_test.rs#L214)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Some external user of the blockifier can choose to have a heavy struct (as you mentioned, it can grow uncontrollably).
</blockquote></details>

Understood (:


<!-- Sent from Reviewable.io -->

2024-06-17 14:14 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 981 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-VqYvk3YcM0rEANLfS:-O-aXz2x5pgx8d4k-ZL3:bn3472a) ([raw file](https://github.com/starkware-libs/blockifier/blob/c803abe4c4946166ce91ca3cb57e1f0ce717eab4/crates/blockifier/src/transaction/transactions_test.rs#L981)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think it should be `minimal_resource_bounds` (you can delete the `minimal_fee`).
See [here](https://github.com/starkware-libs/blockifier/blob/7140ce87a3ee8c65fccc0cde4b2467a27016aee2/crates/blockifier/src/fee/fee_checks.rs#L73)
</blockquote></details>

resolved offline
Done.


<!-- Sent from Reviewable.io -->

2024-06-17 21:50 UTC, barak-b-starkware reviewed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2024-06-19 08:31 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 607 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-eN2FLCC0pH4r0Xebh:-O-eN2FLCC0pH4r0Xebi:bpsmqem) ([raw file](https://github.com/starkware-libs/blockifier/blob/66dcc7b54959560ad31c1c54baa2a39d740692b8/crates/blockifier/src/execution/stack_trace_test.rs#L607)):*
> ```XML
>         account_address,
>     )
>     .unwrap();
> ```

using the MAX_GAS_PRICE and MAX_GA_AMOUNT might be sufficient here but the test used BALANCE so I wanted to be consistent, 


<!-- Sent from Reviewable.io -->

2024-06-19 09:04 UTC, barak-b-starkware reviewed
> Reviewed 2 of 3 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 607 at r13](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-eN2FLCC0pH4r0Xebh:-O-jiPRw2VWnXmlwaY6o:b7hh8j7) ([raw file](https://github.com/starkware-libs/blockifier/blob/66dcc7b54959560ad31c1c54baa2a39d740692b8/crates/blockifier/src/execution/stack_trace_test.rs#L607)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

using the MAX_GAS_PRICE and MAX_GA_AMOUNT might be sufficient here but the test used BALANCE so I wanted to be consistent,
</blockquote></details>

AFAIU the `BALANCE` constant, should represent the balance of the account, so it's natural to use it in the:
```let state = &mut test_state(chain_info, BALANCE, &[(account, 1), (faulty_ctor, 0)]);```
If it's not tested (if it doesn't affect the error message at the end of the test), I suggest using the "natural" constants.
But maybe there is some other consistency that I miss here


<!-- Sent from Reviewable.io -->

2024-06-20 10:46 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1675 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-pEaJh4nSCEEpjFOFD:-O-pEaJh4nSCEEpjFOFE:b-6yj59w) ([raw file](https://github.com/starkware-libs/blockifier/blob/d51cee731ba3c804b8c72ccfd75f6a143101a343/crates/blockifier/src/transaction/transactions_test.rs#L1675)):*
> ```XML
>     let sender_address = account.get_instance_address(0);
>     let test_contract_address = test_contract.get_instance_address(0);
>     let expected_tx_info = vec![
> ```

I can add  expected_resource_bounds and expected_unsupported_fields to expected_tx_info if that's better. I just took inspiration from https://github.com/starkware-libs/blockifier/blob/b22fb076a7db5e0fcdd2048a6fb579b0b1d25561/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L343


<!-- Sent from Reviewable.io -->

2024-06-20 13:09 UTC, barak-b-starkware commented
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1686 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-pl1_d6y84NvDiyERW:-O-pl1_d6y84NvDiyERX:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d51cee731ba3c804b8c72ccfd75f6a143101a343/crates/blockifier/src/transaction/transactions_test.rs#L1686)):*
> ```XML
> 
>     let expected_resource_bounds = vec![
>         StarkFelt::from(2u32),          // Length of ResourceBounds array.
> ```





_Suggestion:_
```XML
StarkFelt::TWO
```


<!-- Sent from Reviewable.io -->

2024-06-20 13:12 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 1686 at r17](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-pl1_d6y84NvDiyERW:-O-plkU9Ch12eCAyLnqE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d51cee731ba3c804b8c72ccfd75f6a143101a343/crates/blockifier/src/transaction/transactions_test.rs#L1686)):*
> ```XML
> 
>     let expected_resource_bounds = vec![
>         StarkFelt::from(2u32),          // Length of ResourceBounds array.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-06-20 14:10 UTC, barak-b-starkware reviewed
Add a TODO in `crates/blockifier/src/test_utils/deploy_account.rs` in the `impl Default for DeployAccountTxArgs`, to change the version.

> Reviewed 1 of 2 files at r16, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-:-O-py1X64V30Rav5iJMd:b-ewsuyl)* status: all files reviewed, 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 104 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-pyjJeBefllxbujmvF:-O-pyjJfE4CuxyIqrm6B:b-akacxk) ([raw file](https://github.com/starkware-libs/blockifier/blob/578cd06523570c058ca5c998df2913bf08bf76ce/crates/blockifier/src/transaction/account_transactions_test.rs#L104)):*
> ```XML
> 
> // TODO(Dori, 15/9/2023): Convert version variance to attribute macro.
> // TODO(Dori, 10/10/2023): Add V3 case once `create_tx_info` is supported for V3.
> ```

Solve this TODO if it's easy.



_Code quote:_
```XML
// TODO(Dori, 10/10/2023): Add V3 case once `create_tx_info` is supported for V3.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 134 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-pyXXd11gJsvO432Wt:-O-pyXXd11gJsvO432Wu:b-akacxk) ([raw file](https://github.com/starkware-libs/blockifier/blob/578cd06523570c058ca5c998df2913bf08bf76ce/crates/blockifier/src/transaction/account_transactions_test.rs#L134)):*
> ```XML
> #[case(TransactionVersion::ZERO)]
> #[case(TransactionVersion::ONE)]
> // TODO(Nimrod, 10/10/2023): Add V3 case once `get_tx_info` is supported for V3.
> ```

Solve this TODO if it's easy.



_Code quote:_
```XML
// TODO(Nimrod, 10/10/2023): Add V3 case once `get_tx_info` is supported for V3.
```


<!-- Sent from Reviewable.io -->

2024-06-20 14:59 UTC, noaov1 submitted a review, later dismissed
> Reviewed 1 of 3 files at r13, 1 of 2 files at r16, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware, @meship-starkware, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 49 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-q5YQD6nnajosCj9iX:-O-q5YQD6nnajosCj9iY:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/578cd06523570c058ca5c998df2913bf08bf76ce/crates/blockifier/src/concurrency/worker_logic_test.rs#L49)):*
> ```XML
>         calldata: create_trivial_calldata(test_contract_address),
>         resource_bounds: l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE),
>         nonce: nonce,
> ```





_Suggestion:_
```XML
nonce,
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 615 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-q5gFKChqJqQGi_XGX:-O-q5gFKChqJqQGi_XGY:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/578cd06523570c058ca5c998df2913bf08bf76ce/crates/blockifier/src/concurrency/worker_logic_test.rs#L615)):*
> ```XML
>             class_hash: test_class_hash,
>             compiled_class_hash: test_compiled_class_hash,
>             version: TransactionVersion::THREE,
> ```


___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 212 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-q6G1GCwAwF4aJexF_:-O-q6G1H7xq9acTaINaV:bqaqmd0) ([raw file](https://github.com/starkware-libs/blockifier/blob/578cd06523570c058ca5c998df2913bf08bf76ce/crates/blockifier/src/transaction/account_transactions_test.rs#L212)):*
> ```XML
>         &block_context,
>         invoke_tx_args! {
>             resource_bounds: l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE),
> ```

Consider defining a fixture (same as `max_fee`)



_Code quote:_
```XML
resource_bounds: l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE),
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 968 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-q8S7cAMf3c6q9uvE-:-O-q8S7cAMf3c6q9uvE0:b-1s7g3e) ([raw file](https://github.com/starkware-libs/blockifier/blob/578cd06523570c058ca5c998df2913bf08bf76ce/crates/blockifier/src/transaction/transactions_test.rs#L968)):*
> ```XML
>     let minimal_l1_gas = estimate_minimal_gas_vector(block_context, tx).unwrap().l1_gas;
>     let minimal_fee =
>         Fee(minimal_l1_gas * u128::from(block_context.block_info.gas_prices.strk_l1_gas_price));
> ```

Consider defining it only when needed (right before the `assert_eq!` below)



_Code quote:_
```XML
    let minimal_fee =
        Fee(minimal_l1_gas * u128::from(block_context.block_info.gas_prices.strk_l1_gas_price));
```


<!-- Sent from Reviewable.io -->

2024-06-23 07:00 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 615 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-q5gFKChqJqQGi_XGX:-O02oY7V2cPeHRDuWIwB:b1dezhl) ([raw file](https://github.com/starkware-libs/blockifier/blob/578cd06523570c058ca5c998df2913bf08bf76ce/crates/blockifier/src/concurrency/worker_logic_test.rs#L615)):*
> ```XML
>             class_hash: test_class_hash,
>             compiled_class_hash: test_compiled_class_hash,
>             version: TransactionVersion::THREE,
> ```

It is a declare tx, so it still needs to be TransactionVersion::THREE because the default is still ONE there 


<!-- Sent from Reviewable.io -->

2024-06-23 08:30 UTC, barak-b-starkware requested changes
> Reviewed 8 of 8 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: all files reviewed, 5 unresolved discussions (waiting on @meship-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 50 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O03CAG0DRXIulXXU8Hm:-O03CAG19tj9Ra1MxPAV:bzbxqnx) ([raw file](https://github.com/starkware-libs/blockifier/blob/0358cfcdee6dcd2de0d4e4d391e93217c6e8682d/crates/blockifier/src/concurrency/worker_logic_test.rs#L50)):*
> ```XML
>         sender_address: account_address,
>         calldata: create_trivial_calldata(test_contract_address),
>         resource_bounds: l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE),
> ```

There are still many `l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE)` in the code.
If it makes sense try to use the fixture everywhere, like this (not sure that this example makes sense):



_Suggestion:_
```XML
 resource_bounds: max_resource_bounds(),
```
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 287 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O03CM-jDdnju0XJ0G_n:-O03CM-jDdnju0XJ0G_o:bzbxqnx) ([raw file](https://github.com/starkware-libs/blockifier/blob/0358cfcdee6dcd2de0d4e4d391e93217c6e8682d/crates/blockifier/src/concurrency/worker_logic_test.rs#L287)):*
> ```XML
>         resource_bounds: resource_bounds.clone(),
>         nonce: nonce_manager.next(account_address)
>     });
> ```

There are still many `l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE)` in the code.
If it makes sense try to use the fixture everywhere, like this (not sure that this example makes sense):



_Suggestion:_
```XML
#[rstest]
fn test_worker_execute(max_resource_bounds: ResourceBoundsMapping) {
    // Settings.
    let concurrency_mode = true;
    let block_context =
        BlockContext::create_for_account_testing_with_concurrency_mode(concurrency_mode);
    let account_contract = FeatureContract::AccountWithoutValidations(CairoVersion::Cairo1);
    let test_contract = FeatureContract::TestContract(CairoVersion::Cairo0);
    let chain_info = &block_context.chain_info;

    // Create the state.
    let state = test_state(chain_info, BALANCE, &[(account_contract, 1), (test_contract, 1)]);
    let safe_versioned_state = safe_versioned_state_for_testing(state);

    // Create transactions.
    let test_contract_address = test_contract.get_instance_address(0);
    let account_address = account_contract.get_instance_address(0);
    let nonce_manager = &mut NonceManager::default();
    let storage_value = stark_felt!(93_u8);
    let storage_key = storage_key!(1993_u16);

    let tx_success = account_invoke_tx(invoke_tx_args! {
        sender_address: account_address,
        calldata: create_calldata(
            test_contract_address,
            "test_storage_read_write",
            &[*storage_key.0.key(),storage_value ], // Calldata:  address, value.
        ),
        resource_bounds: max_resource_bounds,
        nonce: nonce_manager.next(account_address)
    });
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 104 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-pyjJeBefllxbujmvF:-O03BcV077Yuq9_Q-Fdx:b-83sjoh) ([raw file](https://github.com/starkware-libs/blockifier/blob/578cd06523570c058ca5c998df2913bf08bf76ce/crates/blockifier/src/transaction/account_transactions_test.rs#L104)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Solve this TODO if it's easy.
</blockquote></details>

Nice!
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 134 at r18](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O-pyXXd11gJsvO432Wt:-O03Be5D6gJEcnVymiLi:b-83sjoh) ([raw file](https://github.com/starkware-libs/blockifier/blob/578cd06523570c058ca5c998df2913bf08bf76ce/crates/blockifier/src/transaction/account_transactions_test.rs#L134)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Solve this TODO if it's easy.
</blockquote></details>

Nice!
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 78 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O03AKnwD3xwJXn5PYyg:-O03AKnwD3xwJXn5PYyh:bmz0fd8) ([raw file](https://github.com/starkware-libs/blockifier/blob/0358cfcdee6dcd2de0d4e4d391e93217c6e8682d/crates/blockifier/src/transaction/test_utils.rs#L78)):*
> ```XML
> pub fn block_context() -> BlockContext {
>     BlockContext::create_for_account_testing()
> }
> ```

Add a TODO to consider moving these fixtures to `crates/blockifier/src/test_utils.rs` since they are also used elsewhere.
WDYT about it?



_Code quote:_
```XML
/// Test fixtures.

#[fixture]
pub fn max_fee() -> Fee {
    Fee(MAX_FEE)
}

#[fixture]
pub fn max_resource_bounds() -> ResourceBoundsMapping {
    l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE)
}

#[fixture]
pub fn block_context() -> BlockContext {
    BlockContext::create_for_account_testing()
}
```


<!-- Sent from Reviewable.io -->

2024-06-23 09:01 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 50 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O03CAG0DRXIulXXU8Hm:-O03EnhLE6Cdl7GsaH0x:b-fpjdwm) ([raw file](https://github.com/starkware-libs/blockifier/blob/0358cfcdee6dcd2de0d4e4d391e93217c6e8682d/crates/blockifier/src/concurrency/worker_logic_test.rs#L50)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

There are still many `l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE)` in the code.
If it makes sense try to use the fixture everywhere, like this (not sure that this example makes sense):
</blockquote></details>

Here is not a test, so I can either pass it as an argument or use l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE). I prefer using the Constance rather than chancing all the calls to this util, but I can do it if you think it would be better. 
___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 287 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O03CM-jDdnju0XJ0G_n:-O03H7UH1-nZt4wcLxge:b4t7et9) ([raw file](https://github.com/starkware-libs/blockifier/blob/0358cfcdee6dcd2de0d4e4d391e93217c6e8682d/crates/blockifier/src/concurrency/worker_logic_test.rs#L287)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

There are still many `l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE)` in the code.
If it makes sense try to use the fixture everywhere, like this (not sure that this example makes sense):
</blockquote></details>

I changed all appearances in the worker_logic test. The flavors test has too many arguments, and the max fee is also constant there, so I decided to keep it as is.  
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 78 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O03AKnwD3xwJXn5PYyg:-O03HwOu39Uxtn0XvNu2:b-1deg4) ([raw file](https://github.com/starkware-libs/blockifier/blob/0358cfcdee6dcd2de0d4e4d391e93217c6e8682d/crates/blockifier/src/transaction/test_utils.rs#L78)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Add a TODO to consider moving these fixtures to `crates/blockifier/src/test_utils.rs` since they are also used elsewhere.
WDYT about it?
</blockquote></details>

I am not sure I agree with this. These utils are still connected to a transaction, and we use transaction test utils in most of the tests even without these utils 


<!-- Sent from Reviewable.io -->

2024-06-23 10:45 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/concurrency/worker_logic_test.rs` line 50 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O03CAG0DRXIulXXU8Hm:-O03ghsE-Y42NEBLGwyx:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0358cfcdee6dcd2de0d4e4d391e93217c6e8682d/crates/blockifier/src/concurrency/worker_logic_test.rs#L50)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Here is not a test, so I can either pass it as an argument or use l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE). I prefer using the Constance rather than chancing all the calls to this util, but I can do it if you think it would be better.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-23 10:58 UTC, barak-b-starkware reviewed
> Reviewed 1 of 1 files at r21.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @noaov1)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 78 at r19](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-O03AKnwD3xwJXn5PYyg:-O03iWjm2EVWqdKtI0mD:b-83tbtb) ([raw file](https://github.com/starkware-libs/blockifier/blob/0358cfcdee6dcd2de0d4e4d391e93217c6e8682d/crates/blockifier/src/transaction/test_utils.rs#L78)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I am not sure I agree with this. These utils are still connected to a transaction, and we use transaction test utils in most of the tests even without these utils
</blockquote></details>

OK (:


<!-- Sent from Reviewable.io -->

2024-06-26 10:10 UTC, noaov1 approved these changes
> Reviewed 3 of 3 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware)



<!-- Sent from Reviewable.io -->

2024-06-26 11:56 UTC, barak-b-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>
Consider adding a comment in the only place you left `l1_resource_bounds(MAX_L1_GAS_AMOUNT, MAX_L1_GAS_PRICE)` that explains why it's there or add the "allow too many arguments" decorator above the test.

> Reviewed 3 of 3 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-:-O0JOO708EW5vnluNNKw:b-oqbqdy)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-06-26 12:40 UTC, OriStarkware reviewed
> Reviewed 1 of 3 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @barak-b-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2024-06-26 13:42 UTC, barak-b-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/1967#-:-O0Jm3Rr1w7C6LO6fumc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @meship-starkware)



<!-- Sent from Reviewable.io -->

2024-06-26 13:51 UTC, merged