fix(transaction): disallow declare of the same contract more than onc…
starkware-libs/blockifier pull request #2014
Opened 2024-06-30 11:07 UTC by meship-starkware

…e in declare V0 and V1

2024-06-30 11:08 UTC, meship-starkware commented
I still need to add a test to see that it works.

2024-06-30 11:18 UTC, noaov1 requested changes
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @meship-starkware)

___
*[`crates/blockifier/resources/versioned_constants.json` line 26 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0cqoP--vts7V0aTob9:-O0cqoP--vts7V0aTobA:brpnd39) ([raw file](https://github.com/starkware-libs/blockifier/blob/37684e7468f1940871711fd4b107720a4839403e/crates/blockifier/resources/versioned_constants.json#L26)):*
> ```JSON
>         ]
>     },
>     "allow_deprecated_multiple_declarations": false,
> ```

Since now we actively disabling it.
WDYT?



_Suggestion:_
```JSON
    "disable_cairo0_redeclaration": true,
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 199 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0crOTM1Lwr_RrKr4ix:-O0crOTM1Lwr_RrKr4iy:b64upbz) ([raw file](https://github.com/starkware-libs/blockifier/blob/37684e7468f1940871711fd4b107720a4839403e/crates/blockifier/src/transaction/transactions.rs#L199)):*
> ```XML
>                                 // (i.e., make sure the leaf is uninitialized).
>                                 Err(TransactionExecutionError::DeclareTransactionError { class_hash })
>                             }
> ```

Consider sharing code with declaration of  cairo1 contract



_Code quote:_
```XML
                        match state.get_compiled_contract_class(class_hash) {
                            Err(StateError::UndeclaredClassHash(_)) => {
                                // Class is undeclared; declare it.
                                state.set_contract_class(class_hash, self.contract_class())?;
                                Ok(None)
                            }
                            Err(error) => Err(error)?,
                            Ok(_) => {
                                // Class is already declared, cannot redeclare
                                // (i.e., make sure the leaf is uninitialized).
                                Err(TransactionExecutionError::DeclareTransactionError { class_hash })
                            }
```


<!-- Sent from Reviewable.io -->

2024-06-30 13:55 UTC, noaov1 requested changes
> Reviewed 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @meship-starkware)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 7 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0cwK1W77DateGi40Wh:-O0cwK1W77DateGi40Wi:beb7hf) ([raw file](https://github.com/starkware-libs/blockifier/blob/aabc691b3bba1a7a618b7f15a5e839f64abfaa2d/crates/blockifier/resources/versioned_constants_13_0.json#L7)):*
> ```JSON
>     },
>     "invoke_tx_max_n_steps": 3000000,
>     "disable_cairo0_redeclaration": true,
> ```

:)
Same for 13.1.1



_Suggestion:_
```JSON
   "disable_cairo0_redeclaration": false,
```


<!-- Sent from Reviewable.io -->

2024-06-30 14:53 UTC, barak-b-starkware requested changes
> Reviewed 6 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: all files reviewed, 4 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0d_M9-DEyd7JfLtRM0:-O0d_M9-DEyd7JfLtRM1:b8mwdvn) ([raw file](https://github.com/starkware-libs/blockifier/blob/2b1356660100611f85c217a435fd9ee00d23edd7/crates/blockifier/src/versioned_constants.rs#L51)):*
> ```XML
>     pub max_recursion_depth: usize,
>     pub disable_cairo0_redeclaration: bool,
>     pub validate_max_n_steps: u32,
> ```

Notice that `max_recursion_depth` and `validate_max_n_steps` are part of `VersionedConstantsOverrides`, so they are decoupled in some sense.



_Suggestion:_
```XML
    // Limits.
    #[serde(default = "EventLimits::max")]
    pub tx_event_limits: EventLimits,
    pub invoke_tx_max_n_steps: u32,
    #[serde(default)]
    pub l2_resource_gas_costs: L2ResourceGasCosts,
    pub max_recursion_depth: usize,
    pub validate_max_n_steps: u32,
    
    // Some new category?
    #[serde(default)]
    pub disable_cairo0_redeclaration: bool,
```
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0daU7g0R4f-ujQfJyp:-O0daU7g0R4f-ujQfJyq:b6jda32) ([raw file](https://github.com/starkware-libs/blockifier/blob/2b1356660100611f85c217a435fd9ee00d23edd7/crates/blockifier/src/versioned_constants_test.rs#L71)):*
> ```XML
>         "max_recursion_depth": 2,
>         "disable_cairo0_redeclaration": true
>     }"#;
> ```

Maybe I missed the reason for not defining it with a default value (as I suggested above)...



_Suggestion:_
```XML
        "max_recursion_depth": 2
    }"#;
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 199 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0crOTM1Lwr_RrKr4ix:-O0dc4wuAFBPyNau37zB:b9rrm6l) ([raw file](https://github.com/starkware-libs/blockifier/blob/37684e7468f1940871711fd4b107720a4839403e/crates/blockifier/src/transaction/transactions.rs#L199)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Consider sharing code with declaration of  cairo1 contract
</blockquote></details>

I would keep it separate, as the sharing forces us to pass an `Option` with the `compiled_class_hash` in the case of V3 tx.
Moreover, V0 and V1 are no longer supported, so we have a trade-off between keeping the V3 code cleaner and sharing code between V0, V1, and V3. IMO, we should prefer to keep the V3 code cleaner.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 164 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0daoZE7UQkiv-UCLbA:-O0daoZE7UQkiv-UCLbB:bd50xy2) ([raw file](https://github.com/starkware-libs/blockifier/blob/2b1356660100611f85c217a435fd9ee00d23edd7/crates/blockifier/src/transaction/transactions.rs#L164)):*
> ```XML
> }
> 
> fn try_declearing<S: State>(
> ```

Non-blocking



_Suggestion:_
```XML
fn try_decleare<S: State>(
```


<!-- Sent from Reviewable.io -->

2024-07-01 05:58 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/resources/versioned_constants_13_0.json` line 7 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0cwK1W77DateGi40Wh:-O0grr-M4l9KyB0J1dt5:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/aabc691b3bba1a7a618b7f15a5e839f64abfaa2d/crates/blockifier/resources/versioned_constants_13_0.json#L7)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

:)
Same for 13.1.1
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0d_M9-DEyd7JfLtRM0:-O0grstx7-xG4Bi-Hg1r:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2b1356660100611f85c217a435fd9ee00d23edd7/crates/blockifier/src/versioned_constants.rs#L51)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Notice that `max_recursion_depth` and `validate_max_n_steps` are part of `VersionedConstantsOverrides`, so they are decoupled in some sense.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/versioned_constants_test.rs` line 71 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0daU7g0R4f-ujQfJyp:-O0grxKt9qeQI2b_P0OY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2b1356660100611f85c217a435fd9ee00d23edd7/crates/blockifier/src/versioned_constants_test.rs#L71)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Maybe I missed the reason for not defining it with a default value (as I suggested above)...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-01 12:50 UTC, noaov1 reviewed
> Reviewed 5 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: all files reviewed, 7 unresolved discussions (waiting on @barak-b-starkware and @meship-starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 182 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0iKT1t5s1Ha94w4xUI:-O0iKT1uDjIwbyXqP3MV:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b9d4cf164f1c65fe75a62af74a42130a303b3384/crates/blockifier/src/transaction/transactions.rs#L182)):*
> ```XML
>         Ok(_) => {
>             // Class is already declared, cannot redeclare
>             // (i.e., make sure the leaf is uninitialized).
> ```





_Suggestion:_
```XML
            // (in cairo 1, make sure the leaf is uninitialized).
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 200 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0iKbMX1nat4AUBiFaF:-O0iKbMX1nat4AUBiFaG:b-hombt1) ([raw file](https://github.com/starkware-libs/blockifier/blob/b9d4cf164f1c65fe75a62af74a42130a303b3384/crates/blockifier/src/transaction/transactions.rs#L200)):*
> ```XML
>             context.tx_context.block_context.versioned_constants.disable_cairo0_redeclaration;
>         match &self.tx {
>             // No class commitment, so no need to check if the class is already declared.
> ```

Please move above the false.



_Code quote:_
```XML
            // No class commitment, so no need to check if the class is already declared.
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0iL3-G5nsd-1W4BOiU:-O0iL3-G5nsd-1W4BOiV:butpvwt) ([raw file](https://github.com/starkware-libs/blockifier/blob/b9d4cf164f1c65fe75a62af74a42130a303b3384/crates/native_blockifier/src/py_block_executor.rs#L348)):*
> ```XML
>         use blockifier::state::global_cache::GLOBAL_CONTRACT_CACHE_SIZE_FOR_TEST;
>         let mut versioned_constants = VersionedConstants::latest_constants().clone();
>         versioned_constants.disable_cairo0_redeclaration = true;
> ```

Will defining default = true help?



_Code quote:_
```XML
        versioned_constants.disable_cairo0_redeclaration = true;
```


<!-- Sent from Reviewable.io -->

2024-07-02 07:26 UTC, noaov1 reviewed
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: all files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware and @meship-starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 207 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0mHaRq8rvnvBxK618W:-O0mHaRrEeJr9VBnTEwG:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/58552008abb5671794bc41e84ddb04a8510a53a2/crates/blockifier/src/transaction/transactions.rs#L207)):*
> ```XML
>                         class_hash,
>                         self.contract_class(),
>                         CompiledClassHash(StarkFelt::ZERO),
> ```





_Suggestion:_
```XML
                        self.contract_class(),
                        // A default value (see `get_compiled_contract_class`).
                        CompiledClassHash(StarkFelt::ZERO),
```


<!-- Sent from Reviewable.io -->

2024-07-02 12:00 UTC, barak-b-starkware requested changes
> Reviewed 4 of 5 files at r4, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: all files reviewed, 8 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`-- commits` line 2 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0n9kkWCWwYyeoenm0G):*




_Suggestion:_
```
b5efa39: fix(transaction): disable cairo0 redeclaration
```
___
*[`crates/blockifier/src/versioned_constants.rs` line 54 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0nIvcO8oqo1y304TnN:-O0nIvcO8oqo1y304TnO:b2gqlmh) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5efa39faa487a6419c94a1abf7194210521dec1/crates/blockifier/src/versioned_constants.rs#L54)):*
> ```XML
>     // Transactions settings.
>     #[serde(default)]
>     pub disable_cairo0_redeclaration: bool,
> ```

I would guess that the default, in this case, is `false`, that's true? Is that what what we want?



_Code quote:_
```XML
    #[serde(default)]
    pub disable_cairo0_redeclaration: bool,
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 199 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0crOTM1Lwr_RrKr4ix:-O0nIdPy1cUMBD3oMRsc:b6zm3ab) ([raw file](https://github.com/starkware-libs/blockifier/blob/37684e7468f1940871711fd4b107720a4839403e/crates/blockifier/src/transaction/transactions.rs#L199)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I would keep it separate, as the sharing forces us to pass an `Option` with the `compiled_class_hash` in the case of V3 tx.
Moreover, V0 and V1 are no longer supported, so we have a trade-off between keeping the V3 code cleaner and sharing code between V0, V1, and V3. IMO, we should prefer to keep the V3 code cleaner.
</blockquote></details>

@noaov1 very nice solution with `CompiledClassHash(StarkFelt::ZERO)`, like!
___
*[`crates/blockifier/src/transaction/transactions.rs` line 164 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0nHyRa2EXaX0KGgdHH:-O0nHyRa2EXaX0KGgdHI:bc7vpmd) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5efa39faa487a6419c94a1abf7194210521dec1/crates/blockifier/src/transaction/transactions.rs#L164)):*
> ```XML
> }
> 
> fn try_decleare<S: State>(
> ```

Why it's not a method of `impl<S: State> Executable<S> for DeclareTransaction`?
1. Instead of passing the `state` and `contract_class` it can use `self`.
2. It's only used in this context.

But maybe I miss something here?



_Code quote:_
```XML
fn try_decleare<S: State>(
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 210 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0nHMDB4F__FQB28Dfr:-O0nHMDB4F__FQB28Dfs:b-l2aqdg) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5efa39faa487a6419c94a1abf7194210521dec1/crates/blockifier/src/transaction/transactions.rs#L210)):*
> ```XML
>                     ),
>                     // We allow redeclaration of the class for backward compatibility.
>                     // No class commitment, so no need to check if the class is already declared.
> ```

"No class commitment" is unclear to me, WDYM? Consider rephrasing the comment.



_Code quote:_
```XML
// No class commitment, so no need to check if the class is already declared.
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 216 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0nGLNeDeqq8b80dNbQ:-O0nGLNeDeqq8b80dNbR:bmhizji) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5efa39faa487a6419c94a1abf7194210521dec1/crates/blockifier/src/transaction/transactions.rs#L216)):*
> ```XML
>                     }
>                 }
>             }
> ```

Or at least push the variable initialization into the V0, V1 arm (place the `let` inside the arm since it's not used outside of it).



_Suggestion:_
```XML
        match &self.tx {
            starknet_api::transaction::DeclareTransaction::V0(_)
            | starknet_api::transaction::DeclareTransaction::V1(_) => {
                match context.tx_context.block_context.versioned_constants.disable_cairo0_redeclaration {
                    true => try_decleare(
                        state,
                        class_hash,
                        self.contract_class(),
                        // A default value (see `get_compiled_contract_class`).
                        CompiledClassHash(StarkFelt::ZERO),
                    ),
                    // We allow redeclaration of the class for backward compatibility.
                    // No class commitment, so no need to check if the class is already declared.
                    false => {
                        state.set_contract_class(class_hash, self.contract_class())?;
                        Ok(None)
                    }
                }
            }
```


<!-- Sent from Reviewable.io -->

2024-07-02 12:12 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 199 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0crOTM1Lwr_RrKr4ix:-O0io8-LCMYKR_84KL4V:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/37684e7468f1940871711fd4b107720a4839403e/crates/blockifier/src/transaction/transactions.rs#L199)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I would keep it separate, as the sharing forces us to pass an `Option` with the `compiled_class_hash` in the case of V3 tx.
Moreover, V0 and V1 are no longer supported, so we have a trade-off between keeping the V3 code cleaner and sharing code between V0, V1, and V3. IMO, we should prefer to keep the V3 code cleaner.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 210 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0nHMDB4F__FQB28Dfr:-O0nLUA68UK5yAFr7tmk:b-itlikf) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5efa39faa487a6419c94a1abf7194210521dec1/crates/blockifier/src/transaction/transactions.rs#L210)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

"No class commitment" is unclear to me, WDYM? Consider rephrasing the comment.
</blockquote></details>

I am not sure as well. I did not add this comment just changed its placement. I think it might be irrelevant @noaov1 WDYT?
___
*[`crates/blockifier/src/transaction/transactions.rs` line 216 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0nGLNeDeqq8b80dNbQ:-O0nM2Sj0KuvqT73krg3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5efa39faa487a6419c94a1abf7194210521dec1/crates/blockifier/src/transaction/transactions.rs#L216)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Or at least push the variable initialization into the V0, V1 arm (place the `let` inside the arm since it's not used outside of it).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-02 12:18 UTC, meship-starkware commented
*[`crates/blockifier/src/versioned_constants.rs` line 54 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0nIvcO8oqo1y304TnN:-O0nMxXVAHDInWXe-tzu:b-qz95sl) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5efa39faa487a6419c94a1abf7194210521dec1/crates/blockifier/src/versioned_constants.rs#L54)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I would guess that the default, in this case, is `false`, that's true? Is that what what we want?
</blockquote></details>

It's true by default, which surprised me as well. I have tried writing #[serde(default="true")]
but I got an error 


<!-- Sent from Reviewable.io -->

2024-07-02 12:29 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 54 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0nIvcO8oqo1y304TnN:-O0nNTAj6HebxKBtSYz9:bnq290r) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5efa39faa487a6419c94a1abf7194210521dec1/crates/blockifier/src/versioned_constants.rs#L54)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

It's true by default, which surprised me as well. I have tried writing #[serde(default="true")]
but I got an error
</blockquote></details>

That was not true. If there is no JSON file, the default will be false. I don't know how to make it true elegantly.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 164 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0nHyRa2EXaX0KGgdHH:-O0nMMT9BDDHwRybGM5W:b18c9l) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5efa39faa487a6419c94a1abf7194210521dec1/crates/blockifier/src/transaction/transactions.rs#L164)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Why it's not a method of `impl<S: State> Executable<S> for DeclareTransaction`?
1. Instead of passing the `state` and `contract_class` it can use `self`.
2. It's only used in this context.

But maybe I miss something here?
</blockquote></details>

Because it is not a member of Executable


<!-- Sent from Reviewable.io -->

2024-07-02 12:40 UTC, noaov1 submitted a review, later dismissed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 210 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0nHMDB4F__FQB28Dfr:-O0nRXwmDy_DBNBiMOnj:bxc717k) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5efa39faa487a6419c94a1abf7194210521dec1/crates/blockifier/src/transaction/transactions.rs#L210)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I am not sure as well. I did not add this comment just changed its placement. I think it might be irrelevant @noaov1 WDYT?
</blockquote></details>

In the past, we allowed re-declaration because there was no class commitment. 


<!-- Sent from Reviewable.io -->

2024-07-02 13:23 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 54 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0nIvcO8oqo1y304TnN:-O0nah0r935i9SBSquI9:bxfzchx) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5efa39faa487a6419c94a1abf7194210521dec1/crates/blockifier/src/versioned_constants.rs#L54)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

That was not true. If there is no JSON file, the default will be false. I don't know how to make it true elegantly.
</blockquote></details>

Adding this with false as default allows us to avoid adding this variable to the old versioned constants because if it's not 
in a file it will automatically get the value false. @noaov1 WDYT?
___
*[`crates/blockifier/src/transaction/transactions.rs` line 164 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0nHyRa2EXaX0KGgdHH:-O0nacMR0qMnks3-aZyh:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5efa39faa487a6419c94a1abf7194210521dec1/crates/blockifier/src/transaction/transactions.rs#L164)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Because it is not a member of Executable
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-02 13:57 UTC, barak-b-starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-:-O0ncoqSBmFZIdLfb2gt:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 215 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0ninMACU7mfmQEO0kb:-O0ninMB6ZeiYEJtpqZ5:b-ku88ko) ([raw file](https://github.com/starkware-libs/blockifier/blob/2528534d989765cb78a1df380881501ce93c98f9/crates/blockifier/src/transaction/transactions.rs#L215)):*
> ```XML
>                         state,
>                         class_hash,
>                         // A default value (see `get_compiled_contract_class`).
> ```

Something like:



_Suggestion:_
```XML
// In case of undeclarted contract class, we set cch(zero) in the state maps under compiled class hashes, so in order to get no diff we send cch(zero) from here.
```


<!-- Sent from Reviewable.io -->

2024-07-02 14:38 UTC, barak-b-starkware commented
*[`crates/blockifier/src/transaction/transactions.rs` line 218 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0nrhUB2fsodCy8sHwI:-O0nrhUB2fsodCy8sHwJ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ba074a0b51fd05e51a709e249a3a7ceea4a49/crates/blockifier/src/transaction/transactions.rs#L218)):*
> ```XML
>                         // is set to zero. Here, we take advantage of this fact and set
>                         // the CCH to zero in the writes compiled class hashes, so it will not
>                         // affect the diff between the initial and the writes.
> ```





_Suggestion:_
```XML
                        // For undeclared contract classes, when trying to get the compiled contract class, the initial compiled class hash
                        // is set to zero. Here, we take advantage of this fact and set
                        // the compiled class hash to zero to match the compiled class hashes writes and reads, so it will not
                        // affect the state diff.
```


<!-- Sent from Reviewable.io -->

2024-07-02 15:25 UTC, barak-b-starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @meship-starkware and @noaov1)

___
*[`crates/blockifier/src/versioned_constants.rs` line 53 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0o1uuo76YtTdHjIw5X:-O0o1uuo76YtTdHjIw5Y:bky2zwd) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ba074a0b51fd05e51a709e249a3a7ceea4a49/crates/blockifier/src/versioned_constants.rs#L53)):*
> ```XML
> 
>     // Transactions settings.
>     #[serde(default)]
> ```

`test_default_values()` in `crates/blockifier/src/versioned_constants_test.rs` should also check this value.



_Code quote:_
```XML
#[serde(default)]
```


<!-- Sent from Reviewable.io -->

2024-07-03 04:18 UTC, barak-b-starkware submitted a review, later dismissed
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: all files reviewed, 2 unresolved discussions (waiting on @meship-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 53 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0o1uuo76YtTdHjIw5X:-O0qnoi02km21LRseSUd:bgefcxe) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ba074a0b51fd05e51a709e249a3a7ceea4a49/crates/blockifier/src/versioned_constants.rs#L53)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

`test_default_values()` in `crates/blockifier/src/versioned_constants_test.rs` should also check this value.
</blockquote></details>

Non-blocking because I'm flying (:
___
*[`crates/blockifier/src/transaction/transactions.rs` line 218 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0nrhUB2fsodCy8sHwI:-O0qnuUh4YJawAqPxs8L:bgefcxe) ([raw file](https://github.com/starkware-libs/blockifier/blob/ea1ba074a0b51fd05e51a709e249a3a7ceea4a49/crates/blockifier/src/transaction/transactions.rs#L218)):*
> ```XML
>                         // is set to zero. Here, we take advantage of this fact and set
>                         // the CCH to zero in the writes compiled class hashes, so it will not
>                         // affect the diff between the initial and the writes.
> ```

Non-blocking because I'm flying (:


<!-- Sent from Reviewable.io -->

2024-07-03 08:37 UTC, noaov1 reviewed
> Reviewed 1 of 3 files at r9, 1 of 5 files at r10, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 54 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0nIvcO8oqo1y304TnN:-O0riQEC8WnbpE_zj-VA:b4s1rdt) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5efa39faa487a6419c94a1abf7194210521dec1/crates/blockifier/src/versioned_constants.rs#L54)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

Adding this with false as default allows us to avoid adding this variable to the old versioned constants because if it's not 
in a file it will automatically get the value false. @noaov1 WDYT?
</blockquote></details>

Interesting. Can you find a similar field that have similar behaviour?
___
*[`crates/blockifier/src/transaction/transactions.rs` line 210 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0nHMDB4F__FQB28Dfr:-O0nuW3f8beruMKfbYXH:b-czfot4) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5efa39faa487a6419c94a1abf7194210521dec1/crates/blockifier/src/transaction/transactions.rs#L210)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Still don't fully understand, @noaov1 do you think it's clear enough or you would like to suggest a new comment?
Non-blocking
</blockquote></details>

I would write:



_Code snippet:_
```XML
// In the past, we allowed redeclaration of cairo 0 contracts since there was 
// no class commitment (so no need to check if the class is already declared). 
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 219 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0riu2F-vXmanyl398S:-O0riu2F-vXmanyl398T:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/f74f542fb9dcf58e8c3e0eaad5b6dc0b8d502cca/crates/blockifier/src/transaction/transactions.rs#L219)):*
> ```XML
>                         // is set to zero. Here, we take advantage of this fact and set
>                         // the compiled class hash to zero to match the compiled class hashes
>                         // writes and reads, so it will not affect the state diff.
> ```





_Suggestion:_
```XML
                        // For undeclared contract classes, when trying to get the compiled
                        // contract class, the initial compiled class hash
                        // is set to zero. In cairo 0, where there is no compiled class hash, we take 
                        // advantage of this fact, and set the compiled class hash to zero.
```


<!-- Sent from Reviewable.io -->

2024-07-03 08:44 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: all files reviewed, 1 unresolved discussion (waiting on @meship-starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 54 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0nIvcO8oqo1y304TnN:-O0rkw1f8LQ3a2Bi4U_b:b-bklpfi) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5efa39faa487a6419c94a1abf7194210521dec1/crates/blockifier/src/versioned_constants.rs#L54)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Interesting. Can you find a similar field that have similar behaviour?
</blockquote></details>

I think this is a good example https://github.com/starkware-libs/blockifier/blob/f74f542fb9dcf58e8c3e0eaad5b6dc0b8d502cca/crates/blockifier/src/versioned_constants.rs#L48


<!-- Sent from Reviewable.io -->

2024-07-03 16:00 UTC, noaov1 submitted a review, later dismissed
> Reviewed 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @OriStarkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/versioned_constants.rs` line 54 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0nIvcO8oqo1y304TnN:-O0tIcv0BRH8UGkiPjP6:b2xahvb) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5efa39faa487a6419c94a1abf7194210521dec1/crates/blockifier/src/versioned_constants.rs#L54)):*
<details><summary><i>Previously, meship-starkware (Meshi Peled) wrote…</i></summary><blockquote>

I think this is a good example https://github.com/starkware-libs/blockifier/blob/f74f542fb9dcf58e8c3e0eaad5b6dc0b8d502cca/crates/blockifier/src/versioned_constants.rs#L48
</blockquote></details>

Okay, I see.
I wonder if it's better, for clarity, to add this field explicitly (out of this PR scope).


<!-- Sent from Reviewable.io -->

2024-07-04 06:24 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @meship-starkware and @OriStarkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 170 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0wNaq0CrwgSLF1Wueo:-O0wNaq13ixwUmGigs6U:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b6ab70347c359ddd9bf0a7a18af321449e42317f/crates/blockifier/src/transaction/transactions.rs#L170)):*
> ```XML
>     }
> 
>     fn try_decleare<S: State>(
> ```





_Suggestion:_
```XML
try_declare
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 211 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0wNpeH3wSm57kkdY5S:-O0wNpeH3wSm57kkdY5T:b-pe7koz) ([raw file](https://github.com/starkware-libs/blockifier/blob/b6ab70347c359ddd9bf0a7a18af321449e42317f/crates/blockifier/src/transaction/transactions.rs#L211)):*
> ```XML
>                     .versioned_constants
>                     .disable_cairo0_redeclaration
>                 {
> ```

Use if-else for a boolean



_Code quote:_
```XML
                match context
                    .tx_context
                    .block_context
                    .versioned_constants
                    .disable_cairo0_redeclaration
                {
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 220 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0wOd0oEt0m_QVPIqI-:-O0wOd0oEt0m_QVPIqI0:b-piejeb) ([raw file](https://github.com/starkware-libs/blockifier/blob/b6ab70347c359ddd9bf0a7a18af321449e42317f/crates/blockifier/src/transaction/transactions.rs#L220)):*
> ```XML
>                         // take advantage of this fact, and set the
>                         // compiled class hash to zero.
>                         CompiledClassHash(Felt::ZERO),
> ```

This should be okay, but let's not take that risk. 
Please pass `Option` and write the cch only if it's not None.



_Code quote:_
```XML
                        // For undeclared contract classes, when trying to get the compiled
                        // contract class, the initial compiled class hash
                        // is set to zero. In cairo 0, where there is no compiled class hash, we
                        // take advantage of this fact, and set the
                        // compiled class hash to zero.
                        CompiledClassHash(Felt::ZERO),
```


<!-- Sent from Reviewable.io -->

2024-07-04 06:43 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 170 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0wNaq0CrwgSLF1Wueo:-O0wTImG4NTqoHRGbtY1:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b6ab70347c359ddd9bf0a7a18af321449e42317f/crates/blockifier/src/transaction/transactions.rs#L170)):*
> ```XML
>     }
> 
>     fn try_decleare<S: State>(
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 211 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0wNpeH3wSm57kkdY5S:-O0wTJzi5AQVpMZCTC-M:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b6ab70347c359ddd9bf0a7a18af321449e42317f/crates/blockifier/src/transaction/transactions.rs#L211)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Use if-else for a boolean
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 220 at r14](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0wOd0oEt0m_QVPIqI-:-O0wTKgk6Zf4zMX0udrZ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b6ab70347c359ddd9bf0a7a18af321449e42317f/crates/blockifier/src/transaction/transactions.rs#L220)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

This should be okay, but let's not take that risk. 
Please pass `Option` and write the cch only if it's not None.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-04 06:48 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 7 files at r2, 1 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @meship-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 182 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0wUy4f-YOdQ-HoKrdC:-O0wUy4f-YOdQ-HoKrdD:b-kx9dis) ([raw file](https://github.com/starkware-libs/blockifier/blob/faab51f48833ab0c8909a3805afc6643aaa3119c/crates/blockifier/src/transaction/transactions.rs#L182)):*
> ```XML
>                 if compiled_class_hash.is_some() {
>                     state.set_compiled_class_hash(class_hash, compiled_class_hash.unwrap())?;
>                 }
> ```

Use the `if let` syntax to avoid the `unwarp`



_Code quote:_
```XML
                if compiled_class_hash.is_some() {
                    state.set_compiled_class_hash(class_hash, compiled_class_hash.unwrap())?;
                }
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 188 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0wUeLE6ehityeV24CM:-O0wUeLE6ehityeV24CN:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/faab51f48833ab0c8909a3805afc6643aaa3119c/crates/blockifier/src/transaction/transactions.rs#L188)):*
> ```XML
>             Ok(_) => {
>                 // Class is already declared, cannot redeclare
>                 // (in cairo 1, make sure the leaf is uninitialized).
> ```





_Suggestion:_
```XML
                // Class is already declared, cannot redeclare
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 212 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0wUqTi2lGgeyTtxG00:-O0wUqTi2lGgeyTtxG01:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/faab51f48833ab0c8909a3805afc6643aaa3119c/crates/blockifier/src/transaction/transactions.rs#L212)):*
> ```XML
>                 } else {
>                     // We allow redeclaration of the class for backward compatibility.
>                     // In the past, we allowed redeclaration of cairo 0 contracts since there was
> ```





_Suggestion:_
```XML
 of Cairo 0 con
```


<!-- Sent from Reviewable.io -->

2024-07-04 07:26 UTC, meship-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @noaov1, @OriStarkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 182 at r15](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0wUy4f-YOdQ-HoKrdC:-O0wcOZX9dTemJxMRWu9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/faab51f48833ab0c8909a3805afc6643aaa3119c/crates/blockifier/src/transaction/transactions.rs#L182)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Use the `if let` syntax to avoid the `unwarp`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-04 07:33 UTC, Yoni-Starkware requested changes
> Reviewed 1 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @meship-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 184 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0weLHC-q2nzjn3ossX:-O0weLHC-q2nzjn3ossY:bb71nyg) ([raw file](https://github.com/starkware-libs/blockifier/blob/28318b3bba99bb3e13aa82881f41e2498811ba58/crates/blockifier/src/transaction/transactions.rs#L184)):*
> ```XML
>                 }
>                 Ok(None)
>             }
> ```

Oops



_Suggestion:_
```XML
    ) -> TransactionExecutionResult<()> {
        match state.get_compiled_contract_class(class_hash) {
            Err(StateError::UndeclaredClassHash(_)) => {
                // Class is undeclared; declare it.
                state.set_contract_class(class_hash, self.contract_class())?;
                if let Some(compiled_class_hash) = compiled_class_hash {
                    state.set_compiled_class_hash(class_hash, compiled_class_hash)?;
                }
                Ok()
            }
```


<!-- Sent from Reviewable.io -->

2024-07-04 07:36 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @meship-starkware, @noaov1, and @OriStarkware)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 226 at r16](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-O0werlY-01BN-tBY5fp:-O0werlY-01BN-tBY5fq:b3kqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/28318b3bba99bb3e13aa82881f41e2498811ba58/crates/blockifier/src/transaction/transactions.rs#L226)):*
> ```XML
>             }) => self.try_declare(state, class_hash, Some(*compiled_class_hash)),
>         }
>     }
> ```

.



_Suggestion:_
```XML
        match &self.tx {
            starknet_api::transaction::DeclareTransaction::V0(_)
            | starknet_api::transaction::DeclareTransaction::V1(_) => {
                if context.tx_context.block_context.versioned_constants.disable_cairo0_redeclaration
                {
                    self.try_declare(state, class_hash, None)?
                } else {
                    // We allow redeclaration of the class for backward compatibility.
                    // In the past, we allowed redeclaration of Cairo 0 contracts since there was
                    // no class commitment (so no need to check if the class is already declared).
                    state.set_contract_class(class_hash, self.contract_class())?;
                }
            }
            starknet_api::transaction::DeclareTransaction::V2(DeclareTransactionV2 {
                compiled_class_hash,
                ..
            })
            | starknet_api::transaction::DeclareTransaction::V3(DeclareTransactionV3 {
                compiled_class_hash,
                ..
            }) => self.try_declare(state, class_hash, Some(*compiled_class_hash))?,
        }
        Ok(None)
    }
```


<!-- Sent from Reviewable.io -->

2024-07-04 09:04 UTC, noaov1 approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: all files reviewed, 2 unresolved discussions (waiting on @OriStarkware and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-07-04 09:05 UTC, noaov1 approved these changes
> Reviewed 3 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014)* status: all files reviewed, 2 unresolved discussions (waiting on @OriStarkware and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-07-04 09:26 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r9, 3 of 5 files at r10, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2014#-:-O0x38UQ4HdPMlTMAAu4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @OriStarkware)



<!-- Sent from Reviewable.io -->

2024-07-04 14:59 UTC, merged