Support holes in range_check96 segment.
starkware-libs/blockifier pull request #2085
Opened 2024-07-14 13:44 UTC by ilyalesokhin-starkware

2024-07-14 13:55 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1lWhdH8r_OBlsTld8u:-O1lWhdH8r_OBlsTld8v:b-cisohn) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3c8d25eb24ada62a9f8b113dbf13b7b3837e2f0/crates/blockifier/src/transaction/account_transactions_test.rs#L110)):*
> ```XML
>         nonce: nonce_manager.next(account_address)
>     };
>     let tx_execution_info = run_invoke_tx(
> ```

it seems that this is passing without the fix :(



_Code quote:_
```XML
run_invoke_tx(
```


<!-- Sent from Reviewable.io -->

2024-07-14 13:57 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 558 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1lWyGwE-2vBCZx-g5n:-O1lWyGwE-2vBCZx-g5o:bb7phvt) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3c8d25eb24ada62a9f8b113dbf13b7b3837e2f0/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L558)):*
> ```Cairo
> 
> 
>     // Add drop for AddInputResult as it only has PanicDesturct.
> ```

typo



_Code quote:_
```Cairo
Desturct
```
___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 565 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1lWo0P9jw95HdTVkha:-O1lWo0P9jw95HdTVkhb:b9wqi2h) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3c8d25eb24ada62a9f8b113dbf13b7b3837e2f0/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L565)):*
> ```Cairo
>         let in1 = CircuitElement::<CircuitInput<0>> {};
>         (in1,).new_inputs();
>     }
> ```

is this builtin available for cairo0?
if so please add a cairo0 implementation
(non blocking in case this builtin is unavailable)



_Code quote:_
```Cairo
    // Add drop for AddInputResult as it only has PanicDesturct.
    impl AddInputResultDrop<C> of Drop<core::circuit::AddInputResult<C>>;

    #[external(v0)]
    fn test_missing_rc96_values(ref self: ContractState) {
        let in1 = CircuitElement::<CircuitInput<0>> {};
        (in1,).new_inputs();
    }
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 286 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1lX4dY72FxA_-kq3hd:-O1lX4dY72FxA_-kq3he:bbglz7) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3c8d25eb24ada62a9f8b113dbf13b7b3837e2f0/crates/blockifier/src/execution/entry_point_execution.rs#L286)):*
> ```XML
>     program_segment_size: usize,
> ) -> EntryPointExecutionResult<()> {
>     let verify_secure = false;
> ```

what's this...? anyone who now calls `run_entry_point` should not verify security? how is this related to the memory holes issue?



_Code quote:_
```XML
let verify_secure = false;
```


<!-- Sent from Reviewable.io -->

2024-07-14 13:59 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 286 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1lX4dY72FxA_-kq3hd:-O1lXbu438zO_9axrnOj:b-we4b5d) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3c8d25eb24ada62a9f8b113dbf13b7b3837e2f0/crates/blockifier/src/execution/entry_point_execution.rs#L286)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what's this...? anyone who now calls `run_entry_point` should not verify security? how is this related to the memory holes issue?
</blockquote></details>

I call it manually.
I need to fill the holes before calling it.


<!-- Sent from Reviewable.io -->

2024-07-14 14:51 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 286 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1lX4dY72FxA_-kq3hd:-O1liSl84Q1poCN2aGXh:b-7moqis) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3c8d25eb24ada62a9f8b113dbf13b7b3837e2f0/crates/blockifier/src/execution/entry_point_execution.rs#L286)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I call it manually.
I need to fill the holes before calling it.
</blockquote></details>

is calling it manually after the `run_from_entrypoint` call equivalent to previous behavior...? even with recursive syscalls (call contract / libcall)?


<!-- Sent from Reviewable.io -->

2024-07-14 15:22 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 286 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1lX4dY72FxA_-kq3hd:-O1lpOWu8IZmvphFl22W:b-r0ldwe) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3c8d25eb24ada62a9f8b113dbf13b7b3837e2f0/crates/blockifier/src/execution/entry_point_execution.rs#L286)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is calling it manually after the `run_from_entrypoint` call equivalent to previous behavior...? even with recursive syscalls (call contract / libcall)?
</blockquote></details>

yes, look at the implementation of `run_from_entrypoint`
[https://github.com/lambdaclass/cairo-vm/blob/9ef2ab88d89a9b879553b55e045db1f4e148ac26/vm/src/cairo_run.rs#L178](https://github.com/lambdaclass/cairo-vm/blob/9ef2ab88d89a9b879553b55e045db1f4e148ac26/vm/src/vm/runners/cairo_runner.rs#L1136)


<!-- Sent from Reviewable.io -->

2024-07-14 15:22 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 565 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1lWo0P9jw95HdTVkha:-O1lpgu-6b52XKt-GcU2:bq18heu) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3c8d25eb24ada62a9f8b113dbf13b7b3837e2f0/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L565)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this builtin available for cairo0?
if so please add a cairo0 implementation
(non blocking in case this builtin is unavailable)
</blockquote></details>

you can't declare new cairo0 contracts.


<!-- Sent from Reviewable.io -->

2024-07-14 16:09 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 286 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1lX4dY72FxA_-kq3hd:-O1m-BDU6iePO1FsRBNI:bw5lhm1) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3c8d25eb24ada62a9f8b113dbf13b7b3837e2f0/crates/blockifier/src/execution/entry_point_execution.rs#L286)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

yes, look at the implementation of `run_from_entrypoint`
[https://github.com/lambdaclass/cairo-vm/blob/9ef2ab88d89a9b879553b55e045db1f4e148ac26/vm/src/cairo_run.rs#L178](https://github.com/lambdaclass/cairo-vm/blob/9ef2ab88d89a9b879553b55e045db1f4e148ac26/vm/src/vm/runners/cairo_runner.rs#L1136)
</blockquote></details>

For some reason, it does behave in a different manner I have to call `compute_effective_sizes`


<!-- Sent from Reviewable.io -->

2024-07-14 17:56 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 558 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1lWyGwE-2vBCZx-g5n:-O1mNvGp0rgdP8j4no2A:bb7f2mf) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3c8d25eb24ada62a9f8b113dbf13b7b3837e2f0/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L558)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

typo
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-07-15 04:58 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 301 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1ojgx-5VNNlkmt1QaC:-O1ojgx0BX8dSWYDUZde:beb58cj) ([raw file](https://github.com/starkware-libs/blockifier/blob/8154dc45f48e5123994685ada239062e779c23c7/crates/blockifier/src/execution/entry_point_execution.rs#L301)):*
> ```XML
> 
>     // Fill holes in the rc96 segment.
>     if let Some((rc_96_idx, rc96_builtin_runner)) =
> ```

either `rc96` or `rc_96` throughout the code



_Code quote:_
```XML
(rc_96_idx
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 313 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1oiBpF45QMqzyehWJe:-O1oiBpF45QMqzyehWJf:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/8154dc45f48e5123994685ada239062e779c23c7/crates/blockifier/src/execution/entry_point_execution.rs#L313)):*
> ```XML
>     {
>         // 'EntryPointReturnValues' is returned after the implicits and its size is 5.
>         let implicits_offsets = 5;
> ```





_Suggestion:_
```XML
let implicits_offset = 5;
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 318 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1oiOSj1oQhbAyXpCwX:-O1oiOSj1oQhbAyXpCwY:b-mlll78) ([raw file](https://github.com/starkware-libs/blockifier/blob/8154dc45f48e5123994685ada239062e779c23c7/crates/blockifier/src/execution/entry_point_execution.rs#L318)):*
> ```XML
>             .map_err(|err| CairoRunError::VirtualMachine(VirtualMachineError::Math(err)))?;
> 
>         let base = rc96_builtin_runner.base() as isize;
> ```

Can you use try_into?



_Code quote:_
```XML
base() as isize;
```
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 322 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1oicEE7EAVfDPpTvqo:-O1oicEE7EAVfDPpTvqp:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/8154dc45f48e5123994685ada239062e779c23c7/crates/blockifier/src/execution/entry_point_execution.rs#L322)):*
> ```XML
>         let Relocatable { segment_index, offset: stop_offset } =
>             runner.vm.get_relocatable(rc_96_stop_ptr).map_err(CairoRunError::MemoryError)?;
>         assert_eq!(segment_index, base);
> ```





_Suggestion:_
```XML
        let rc96_base = rc96_builtin_runner.base() as isize;

        let Relocatable { segment_index, offset: stop_offset } =
            runner.vm.get_relocatable(rc_96_stop_ptr).map_err(CairoRunError::MemoryError)?;
        assert_eq!(segment_index, rc96_base, "Unexpected segment index of range_check96.");
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1lWhdH8r_OBlsTld8u:-O1ok9Gn5IUJ2jAS8LtC:bze95a4) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3c8d25eb24ada62a9f8b113dbf13b7b3837e2f0/crates/blockifier/src/transaction/account_transactions_test.rs#L110)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

it seems that this is passing without the fix :(
</blockquote></details>

Still?


<!-- Sent from Reviewable.io -->

2024-07-15 06:49 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 110 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1lWhdH8r_OBlsTld8u:-O1p8qdOEmkjwMLyBVj5:b-ulkgvh) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3c8d25eb24ada62a9f8b113dbf13b7b3837e2f0/crates/blockifier/src/transaction/account_transactions_test.rs#L110)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Still?
</blockquote></details>

No, the problem was that holes at the end didn't trigger a failure.


<!-- Sent from Reviewable.io -->

2024-07-15 08:22 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 330 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1pU0yGAQNgvjj8NDLY:-O1pU0yGAQNgvjj8NDLZ:bcu7vgz) ([raw file](https://github.com/starkware-libs/blockifier/blob/8154dc45f48e5123994685ada239062e779c23c7/crates/blockifier/src/execution/entry_point_execution.rs#L330)):*
> ```XML
>         }
>     }
>     runner.vm.segments.compute_effective_sizes();
> ```

Any idea why this is needed?

There is no such call inside run_from_entrypoint



_Code quote:_
```XML
  runner.vm.segments.compute_effective_sizes();
```


<!-- Sent from Reviewable.io -->

2024-07-15 08:25 UTC, liorgold2 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: 0 of 4 files reviewed, 10 unresolved discussions (waiting on @dorimedini-starkware, @ilyalesokhin-starkware, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 302 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1pUTqb67YB7aGs95wM:-O1pUTqb67YB7aGs95wN:byg00un) ([raw file](https://github.com/starkware-libs/blockifier/blob/2eb6c99a66b1e2422ed972b8bd82ccb5583926f4/crates/blockifier/src/execution/entry_point_execution.rs#L302)):*
> ```XML
>     // Fill holes in the rc96 segment.
>     if let Some((rc96_offset, rc96_builtin_runner)) =
>         runner.vm.get_builtin_runners().iter().find_map(|builtin| {
> ```

For code simplicity, I suggest putting the result of this `find_map` call in a variable.
___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 303 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1pU2L4AluPhUA0xDfi:-O1pU2L4AluPhUA0xDfj:bh3kejk) ([raw file](https://github.com/starkware-libs/blockifier/blob/2eb6c99a66b1e2422ed972b8bd82ccb5583926f4/crates/blockifier/src/execution/entry_point_execution.rs#L303)):*
> ```XML
>     if let Some((rc96_offset, rc96_builtin_runner)) =
>         runner.vm.get_builtin_runners().iter().find_map(|builtin| {
>             let Some(rc96_offset) = opt_rc96_idx else { return None };
> ```

Isn't this line identical to `rc96_offset?` ?


<!-- Sent from Reviewable.io -->

2024-07-15 08:32 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware, @liorgold2, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 301 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1ojgx-5VNNlkmt1QaC:-O1p8lAM1I8AKv-OpTXf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8154dc45f48e5123994685ada239062e779c23c7/crates/blockifier/src/execution/entry_point_execution.rs#L301)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

either `rc96` or `rc_96` throughout the code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-15 08:32 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 303 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1pU2L4AluPhUA0xDfi:-O1pWSfb2S_W3ygYl_l2:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2eb6c99a66b1e2422ed972b8bd82ccb5583926f4/crates/blockifier/src/execution/entry_point_execution.rs#L303)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Isn't this line identical to `rc96_offset?` ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-15 08:41 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 330 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1pU0yGAQNgvjj8NDLY:-O1pYTB7-PKbahEmxMkm:b-hnzugh) ([raw file](https://github.com/starkware-libs/blockifier/blob/8154dc45f48e5123994685ada239062e779c23c7/crates/blockifier/src/execution/entry_point_execution.rs#L330)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Any idea why this is needed?

There is no such call inside run_from_entrypoint
</blockquote></details>

Ok, the issue was early return


<!-- Sent from Reviewable.io -->

2024-07-15 08:45 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 286 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1lX4dY72FxA_-kq3hd:-O1pZPj7BZmKNVSCzJCw:btvptqn) ([raw file](https://github.com/starkware-libs/blockifier/blob/a3c8d25eb24ada62a9f8b113dbf13b7b3837e2f0/crates/blockifier/src/execution/entry_point_execution.rs#L286)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

For some reason, it does behave in a different manner I have to call `compute_effective_sizes`
</blockquote></details>

The issue was early return.


<!-- Sent from Reviewable.io -->

2024-07-15 08:46 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware, @liorgold2, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 302 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1pUTqb67YB7aGs95wM:-O1pXGDR9CVMfgt_V3dd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/2eb6c99a66b1e2422ed972b8bd82ccb5583926f4/crates/blockifier/src/execution/entry_point_execution.rs#L302)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

For code simplicity, I suggest putting the result of this `find_map` call in a variable.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-15 08:47 UTC, orizi requested changes
> Reviewed 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: all files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware, @ilyalesokhin-starkware, @liorgold2, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 315 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1pZAZC8bCRxhfKemwn:-O1pZAZC8bCRxhfKemwo:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/5199dff6c84be53e5b8585a40ddd659ead8328f7/crates/blockifier/src/execution/entry_point_execution.rs#L315)):*
> ```XML
>         let implicits_offset = 6;
>         let rc_96_stop_ptr = (runner.vm.get_ap() - (implicits_offset + rc96_offset))
>             .map_err(|err| CairoRunError::VirtualMachine(VirtualMachineError::Math(err)))?;
> ```





_Suggestion:_
```XML
        const IMPLICITS_OFFSET: usize = 6;
        let rc_96_stop_ptr = (runner.vm.get_ap() - (IMPLICITS_OFFSET + rc96_offset))
            .map_err(|err| CairoRunError::VirtualMachine(VirtualMachineError::Math(err)))?;
```


<!-- Sent from Reviewable.io -->

2024-07-15 09:51 UTC, Yoni-Starkware requested changes
> Reviewed 2 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 338 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1pmcLS3e0NA2sPP3_H:-O1pmcLS3e0NA2sPP3_I:b-w9m3k7) ([raw file](https://github.com/starkware-libs/blockifier/blob/c35afdab3d1f59fe4a316acfb2c552baa0852a11/crates/blockifier/src/execution/entry_point_execution.rs#L338)):*
> ```XML
>                 .vm
>                 .insert_value(Relocatable { segment_index: rc96_segment, offset }, Felt::zero());
>         }
> ```

Please `match` the result, and ignore only `MemoryError::InconsistentMemory` 
(since this function raises more errors)

Alternatively, check with `get` before the insertion 



_Code quote:_
```XML
            // If the value is already set, ignore the error.
            let _ = runner
                .vm
                .insert_value(Relocatable { segment_index: rc96_segment, offset }, Felt::zero());
        }
```


<!-- Sent from Reviewable.io -->

2024-07-15 09:53 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 331 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1pntDz9ZDuyLVgHa46:-O1pntDz9ZDuyLVgHa47:bpi4tr5) ([raw file](https://github.com/starkware-libs/blockifier/blob/c35afdab3d1f59fe4a316acfb2c552baa0852a11/crates/blockifier/src/execution/entry_point_execution.rs#L331)):*
> ```XML
>             .as_mut()
>             .expect("Segments used sizes should be calculated at this point")[rc96_base] =
>             stop_offset;
> ```

Please add a comment about this



_Code quote:_
```XML
        runner
            .vm
            .segments
            .segment_used_sizes
            .as_mut()
            .expect("Segments used sizes should be calculated at this point")[rc96_base] =
            stop_offset;
```


<!-- Sent from Reviewable.io -->

2024-07-15 09:55 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 121 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1poEgED9G5dePqJyuN:-O1poEgF12c2uDzxoHc4:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c35afdab3d1f59fe4a316acfb2c552baa0852a11/crates/blockifier/src/transaction/account_transactions_test.rs#L121)):*
> ```XML
>     .unwrap();
> 
>     assert_eq!(tx_execution_info.revert_error, None);
> ```





_Suggestion:_
```XML
assert!(!tx_execution_info.is_reverted());
```


<!-- Sent from Reviewable.io -->

2024-07-15 10:16 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 121 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1poEgED9G5dePqJyuN:-O1pt5Kv7ATObjbtMYnS:b-lqq2fa) ([raw file](https://github.com/starkware-libs/blockifier/blob/c35afdab3d1f59fe4a316acfb2c552baa0852a11/crates/blockifier/src/transaction/account_transactions_test.rs#L121)):*
> ```XML
>     .unwrap();
> 
>     assert_eq!(tx_execution_info.revert_error, None);
> ```

assert_eq! prints the failure in case of error.


<!-- Sent from Reviewable.io -->

2024-07-15 10:19 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 121 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1poEgED9G5dePqJyuN:-O1ptC2y9SE4Kh9JCYXL:b-tcmmri) ([raw file](https://github.com/starkware-libs/blockifier/blob/c35afdab3d1f59fe4a316acfb2c552baa0852a11/crates/blockifier/src/transaction/account_transactions_test.rs#L121)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

assert_eq! prints the failure in case of error.
</blockquote></details>

but I guess we can fix all tests in a future PR.


<!-- Sent from Reviewable.io -->

2024-07-15 10:25 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 338 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1pmcLS3e0NA2sPP3_H:-O1pvBd90cVsfuqj2-XL:bjjglx7) ([raw file](https://github.com/starkware-libs/blockifier/blob/c35afdab3d1f59fe4a316acfb2c552baa0852a11/crates/blockifier/src/execution/entry_point_execution.rs#L338)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What happens if I get a different error?


<!-- Sent from Reviewable.io -->

2024-07-15 10:35 UTC, orizi approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2024-07-15 11:42 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-:-O1qBvu70R6lYy3ckwLw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 338 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1pmcLS3e0NA2sPP3_H:-O1qBas21F15i85mmPNR:b-xkvmnu) ([raw file](https://github.com/starkware-libs/blockifier/blob/c35afdab3d1f59fe4a316acfb2c552baa0852a11/crates/blockifier/src/execution/entry_point_execution.rs#L338)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

What happens if I get a different error?
</blockquote></details>

Panic I guess. Is there a recoverable error?


<!-- Sent from Reviewable.io -->

2024-07-15 11:48 UTC, Yoni-Starkware approved these changes
> Reviewed 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2024-07-15 11:49 UTC, Yoni-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 262 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1qDHIx84dgqrIpY861:-O1qDHIx84dgqrIpY862:b3i3ix3) ([raw file](https://github.com/starkware-libs/blockifier/blob/9d25009f7f2b7a2434d1e8ab8d9b16f07f004e81/crates/blockifier/src/execution/stack_trace_test.rs#L262)):*
> ```XML
> #[case(CairoVersion::Cairo0, "fail", "An ASSERT_EQ instruction failed: 1 != 0.", 0_u8, 0_u8, (37_u16, 1093_u16, 1184_u16, 1188_u16))]
> #[case(CairoVersion::Cairo0, "fail", "An ASSERT_EQ instruction failed: 1 != 0.", 0_u8, 1_u8, (49_u16, 1111_u16, 1184_u16, 1188_u16))]
> #[case(CairoVersion::Cairo1, "invoke_call_chain", "0x4469766973696f6e2062792030 ('Division by 0')", 1_u8, 0_u8, (9602_u16, 9602_u16, 0_u16, 0_u16))]
> ```

@dorimedini-starkware does this test always fail when changing `test_contract.cairo`?


<!-- Sent from Reviewable.io -->

2024-07-15 12:32 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 338 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1pmcLS3e0NA2sPP3_H:-O1qMmiS3aAEylqC8G_m:bgx2pfg) ([raw file](https://github.com/starkware-libs/blockifier/blob/c35afdab3d1f59fe4a316acfb2c552baa0852a11/crates/blockifier/src/execution/entry_point_execution.rs#L338)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Panic I guess. Is there a recoverable error?
</blockquote></details>

I don't know how to recover from that, that's why I ignore it in the previous solution.


<!-- Sent from Reviewable.io -->

2024-07-15 13:23 UTC, Yoni-Starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/entry_point_execution.rs` line 338 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1pmcLS3e0NA2sPP3_H:-O1qYvpP8IG0vNN5g6TB:b4z7iqz) ([raw file](https://github.com/starkware-libs/blockifier/blob/c35afdab3d1f59fe4a316acfb2c552baa0852a11/crates/blockifier/src/execution/entry_point_execution.rs#L338)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't know how to recover from that, that's why I ignore it in the previous solution.
</blockquote></details>

So panic is good


<!-- Sent from Reviewable.io -->

2024-07-15 13:41 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 262 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1qDHIx84dgqrIpY861:-O1qc-jK2zAJD6u1CaPA:b-gof1aa) ([raw file](https://github.com/starkware-libs/blockifier/blob/9d25009f7f2b7a2434d1e8ab8d9b16f07f004e81/crates/blockifier/src/execution/stack_trace_test.rs#L262)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

@dorimedini-starkware does this test always fail when changing `test_contract.cairo`?
</blockquote></details>

if PC locations of previous functions change, then yes


<!-- Sent from Reviewable.io -->

2024-07-15 13:49 UTC, ilyalesokhin-starkware reviewed
> Reviewed 2 of 4 files at r4, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-07-15 13:52 UTC, dorimedini-starkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-07-15 13:55 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-:-O1qfKfn9vybZGtlifEj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-07-15 15:12 UTC, Yoni-Starkware submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/execution/stack_trace_test.rs` line 262 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1qDHIx84dgqrIpY861:-O1qwbQOAZEYbfyFWgmg:bronwus) ([raw file](https://github.com/starkware-libs/blockifier/blob/9d25009f7f2b7a2434d1e8ab8d9b16f07f004e81/crates/blockifier/src/execution/stack_trace_test.rs#L262)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if PC locations of previous functions change, then yes
</blockquote></details>

Can we use a constant cairo contract for this, that won't be changed and recompiled?
(i.e., can you add this to Monday?)


<!-- Sent from Reviewable.io -->

2024-07-16 06:47 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-:-O1uHwrkA_DtYdHr0WQe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-07-16 06:48 UTC, ilyalesokhin-starkware reviewed
> Reviewed 1 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2024-07-16 06:51 UTC, merged

2024-07-16 06:56 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/2085)* status: all files reviewed, 1 unresolved discussion

___
*[`crates/blockifier/feature_contracts/cairo1/test_contract.cairo` line 564 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/2085#-O1uI3ay1atAHTcYhH55:-O1uI3ay1atAHTcYhH56:bm44cux) ([raw file](https://github.com/starkware-libs/blockifier/blob/9ff74f3539b00c6416989b9088036a40f9494663/crates/blockifier/feature_contracts/cairo1/test_contract.cairo#L564)):*
> ```Cairo
>     fn test_rc96_holes(ref self: ContractState) {
>         test_rc96_holes_helper();
>         test_rc96_holes_helper();
> ```

Add a call with eval here



_Suggestion:_
```Cairo
    fn test_rc96_holes(ref self: ContractState) {
        test_rc96_holes_helper();
        // here
        test_rc96_holes_helper();
```


<!-- Sent from Reviewable.io -->