Fix build script for native extension
starkware-libs/blockifier pull request #258
Opened 2023-02-01 15:07 UTC by giladchase

- added centos-release-scl and llvm-toolset to manylinux docker, for clang > 3.9 support.
  When `blockifier` is added as a dep (which will happen soon),
  one of the dependencies requires this clang dependency.

- Ditto for openssel-devel.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/258)

2023-02-01 15:10 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/258#-:-NNCWjheC5wc8iOgnm_9:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @alon-dotan-starkware, @alonh5, and @giladchase)

___
*[`crates/native_blockifier/build_wheels.sh` line 4 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/258#-NNCW_GP9m82HVznY2oa:-NNCW_GP9m82HVznY2ob:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/195c2e15389305e91a0d088420c1f8321e7bb1ea/crates/native_blockifier/build_wheels.sh#L4)):*
> ```Shell
> set -e
> 
> # Install crate dependencies
> ```





_Suggestion:_
```Shell
# Install crate dependencies.
```
___
*[`crates/native_blockifier/build_wheels.sh` line 9 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/258#-NNCWa5RCmkzgF3yrIXM:-NNCWa5RCmkzgF3yrIXN:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/195c2e15389305e91a0d088420c1f8321e7bb1ea/crates/native_blockifier/build_wheels.sh#L9)):*
> ```Shell
> 
> 
> # Install rust
> ```





_Suggestion:_
```Shell
# Install Rust.
```
___
*[`crates/native_blockifier/run_in_chroot.sh` line 7 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/258#-NNCWeVnCXX1OpfqTn48:-NNCWeVnCXX1OpfqTn49:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/195c2e15389305e91a0d088420c1f8321e7bb1ea/crates/native_blockifier/run_in_chroot.sh#L7)):*
> ```Shell
> pypy_bins=$(echo /opt/python/pp{37,38,39}*/bin)
> 
> # Compile wheels
> ```





_Suggestion:_
```Shell
# Compile wheels.
```
___
*[`crates/native_blockifier/run_in_chroot.sh` line 14 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/258#-NNCWgD_67SdDn5NqhQ3:-NNCWgD_67SdDn5NqhQ4:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/195c2e15389305e91a0d088420c1f8321e7bb1ea/crates/native_blockifier/run_in_chroot.sh#L14)):*
> ```Shell
> done
> 
> # Bundle external shared libraries into the wheels
> ```





_Suggestion:_
```Shell
# Bundle external shared libraries into the wheels.
```
___
*[`crates/native_blockifier/run_in_chroot.sh` line 19 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/258#-NNCWhHK474PkTU4aY1l:-NNCWhHL9hCnqTcsMSIn:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/195c2e15389305e91a0d088420c1f8321e7bb1ea/crates/native_blockifier/run_in_chroot.sh#L19)):*
> ```Shell
> done
> 
> # Install packages and test
> ```





_Suggestion:_
```Shell
# Install packages and test.
```


<!-- Sent from Reviewable.io -->

2023-02-01 15:25 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/258)* status: all files reviewed, 5 unresolved discussions (waiting on @alon-dotan-starkware and @giladchase)



<!-- Sent from Reviewable.io -->

2023-02-01 15:41 UTC, alon-dotan-starkware requested changes
https://serverfault.com/questions/751155/permanently-enable-a-scl

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/258#-:-NNCd1IPBTdz_kTwoLhu:b-9ak6q2)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-02-01 15:52 UTC, elintul approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/258)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-02-02 11:10 UTC, giladchase reviewed
I had to remove the `blockifier` dependency (which didn't really belong anyway here), since it won't pass the CI (it's an unused dep).

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/258#-:-NNGkTM78VciZKzNyRx0:bl84i3t)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2023-02-02 12:37 UTC, alon-dotan-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/258#-:-NNH7Q8h6huQettfDHzV:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2023-02-02 13:05 UTC, merged