Gilad/rust bindings for python 2
starkware-libs/blockifier pull request #263
Opened 2023-02-02 13:44 UTC by giladchase

2023-02-02 14:43 UTC, elintul requested changes
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/263)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/lib.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNHYu61BtEzCI5_78uw:-NNHYu61BtEzCI5_78ux:btdxhxl) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L54)):*
> ```XML
>     }
> 
>     // TODO: Do we want to return the stateDiff dropped?
> ```

No, why do we need to?



_Code quote:_
```XML
// TODO: Do we want to return the stateDiff dropped?
```
___
*[`crates/native_blockifier/src/lib.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNHYR4O7avCXisBgNJq:-NNHYR4O7avCXisBgNJr:bthrlhp) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L56)):*
> ```XML
>     // TODO: Do we want to return the stateDiff dropped?
>     pub fn revert_state_diff(&mut self, block_number: u64) -> NativeBlockifierResult<()> {
>         self.writer.begin_rw_txn()?.revert_state_diff(BlockNumber(block_number))?;
> ```

Is `self.writer.begin_rw_txn()?.do_stuff()?` the way to interact with Papyrus writer?



_Suggestion:_
```XML
        let write_txn = self.writer.begin_rw_txn()?;
        Ok(write_txn.revert_state_diff(BlockNumber(block_number))?)
```
___
*[`crates/native_blockifier/src/lib.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNHZ-w1A2zrRlMhl5Qt:-NNHZ-w2-TZFO3QDC_AB:b-qy8vap) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L63)):*
> ```XML
>         &mut self,
>         block_number: u64,
>         py_state_diff: &PyAny,
> ```

Is this the way to annotate Python objects?



_Code quote:_
```XML
&PyAny
```
___
*[`crates/native_blockifier/src/lib.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNH_1CK1aGzo5tWA5bO:-NNH_1CK1aGzo5tWA5bP:b-jgy8y3) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L83)):*
> ```XML
> 
> #[derive(FromPyObject)]
> pub struct PyStateDiff {
> ```

We need no use `BigInt`/`[u8]` for felts...



_Code quote:_
```XML
PyStateDiff
```


<!-- Sent from Reviewable.io -->

2023-02-02 14:49 UTC, elintul requested changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/263)* status: all files reviewed, 11 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/lib.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNH_1CK1aGzo5tWA5bO:-NNHaS30D0CSX5oSp2CH:bsjbvb9) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L83)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

We need no use `BigInt`/`[u8]` for felts...
</blockquote></details>

Also, perhaps we should implement `From [u8]` or something for the structs you build here?
___
*[`crates/native_blockifier/src/lib.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNHaFGt1FvS7_Jq8G6f:-NNHaFGt1FvS7_Jq8G6g:b-aj5zrm) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L94)):*
> ```XML
> 
>     fn try_from(state_diff: PyStateDiff) -> NativeBlockifierResult<Self> {
>         let mut deployed_contracts = IndexMap::new();
> ```

WDYT of adding annotation here in `<>`?



_Code quote:_
```XML
IndexMap
```
___
*[`crates/native_blockifier/src/lib.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNH_S4Y0r47y4B_wANG:-NNH_S4Y0r47y4B_wANH:b4cefj5) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L96)):*
> ```XML
>         let mut deployed_contracts = IndexMap::new();
>         for (address, class_hash) in state_diff.address_to_class_hash {
>             let contract_address = ContractAddress::try_from(StarkFelt::from(address))?;
> ```

Why not `from`? When can it fail?



_Code quote:_
```XML
ContractAddress::try_from
```
___
*[`crates/native_blockifier/src/lib.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNHabd2-QdvyL03bJtB:-NNHabd37ggyiLfawybt:b-l2dtd9) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L96)):*
> ```XML
>         let mut deployed_contracts = IndexMap::new();
>         for (address, class_hash) in state_diff.address_to_class_hash {
>             let contract_address = ContractAddress::try_from(StarkFelt::from(address))?;
> ```

Reuse `address`, everywhere.



_Code quote:_
```XML
contract_address
```
___
*[`crates/native_blockifier/src/lib.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNH_dho0Oz6lP-1o7yH:-NNH_dho0Oz6lP-1o7yI:b-te1ak2) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L105)):*
> ```XML
>             let contract_address = ContractAddress::try_from(StarkFelt::from(address))?;
>             storage_diffs.insert(contract_address, IndexMap::new());
>             for (storage_key, storage_value) in storage_mapping {
> ```

Add a blank line above.



_Suggestion:_
```XML
for (key, value) in storage_changes {
```
___
*[`crates/native_blockifier/src/lib.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNH_lT-4i1lFH5JecfY:-NNH_lT-4i1lFH5JecfZ:b4cefj5) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L106)):*
> ```XML
>             storage_diffs.insert(contract_address, IndexMap::new());
>             for (storage_key, storage_value) in storage_mapping {
>                 let storage_key = StorageKey::try_from(StarkFelt::from(storage_key))?;
> ```

Why not `from`? When can it fail?



_Code quote:_
```XML
StorageKey::try_from
```
___
*[`crates/native_blockifier/src/lib.rs` line 108 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNH_tqxERnih146LJBN:-NNH_tqxERnih146LJBO:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L108)):*
> ```XML
>                 let storage_key = StorageKey::try_from(StarkFelt::from(storage_key))?;
>                 let storage_value = StarkFelt::from(storage_value);
>                 storage_diffs.entry(contract_address).and_modify(|map| {
> ```





_Suggestion:_
```XML
changes
```
___
*[`crates/native_blockifier/src/lib.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNHa-mH94646-0QQr5y:-NNHa-mH94646-0QQr5z:b-6iq7hy) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L114)):*
> ```XML
>         }
> 
>         // TODO: this isn't present in Python's state_diff, where do i get this from?
> ```

From `class_hash_to_compiled_class_hash`?
Can you look at the Papyrus code? How to they build 



_Code quote:_
```XML
// TODO: this isn't present in Python's state_diff, where do i get this from?
```


<!-- Sent from Reviewable.io -->

2023-02-08 07:09 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/263)* status: all files reviewed, 9 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/native_blockifier/src/lib.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNHYu61BtEzCI5_78uw:-NNjjumY2R7qetZIotHz:b-i0ykr5) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L54)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No, why do we need to?
</blockquote></details>

Cause papyrus is returning it.
We can ignore their return value but just wanna make sure there isn't some reason for this.
___
*[`crates/native_blockifier/src/lib.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNHYR4O7avCXisBgNJq:-NNjk7-_B2tUz7ndo1Ol:bpjpsmy) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L56)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is `self.writer.begin_rw_txn()?.do_stuff()?` the way to interact with Papyrus writer?
</blockquote></details>

The only way papyrus expose, yes.
This starts a transaction, which then needs to be committed if it is a `rw_txn` (for `ro_txn` this isn't needed).

Which reminds me, I forgot to commit :grimacing: 
___
*[`crates/native_blockifier/src/lib.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNHZ-w1A2zrRlMhl5Qt:-NNjmEygC5_oEGjvC52a:b-uuo03g) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L63)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this the way to annotate Python objects?
</blockquote></details>

Primitive types don't need this, so if your passing a `foo: str` Python type as a parameter, in Rust this can just be `foo: String` and it'll cast it automatically.

For custom types, like Python's `StateDiff`, as far as i can tell ATM this is the way (by considering it an `Any` type, and then explicitly casting).

There might be better ways, but it'll take more digging into Pyo3's API.
___
*[`crates/native_blockifier/src/lib.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNH_1CK1aGzo5tWA5bO:-NNjn3urAwU4z_dxghhX:b3fhy3r) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L83)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Also, perhaps we should implement `From [u8]` or something for the structs you build here?
</blockquote></details>

I didn't understand the first sentence  :see_no_evil: (which is why I don't understand the `From` comment either :grimacing: )

Did you mean that you want python to cast everything to bytes (`[u8]`) before passing to Rust?
___
*[`crates/native_blockifier/src/lib.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNHaFGt1FvS7_Jq8G6f:-NNjpGGP-IKawM8guJ5t:bb70w76) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L94)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYT of adding annotation here in `<>`?
</blockquote></details>

Nice
___
*[`crates/native_blockifier/src/lib.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNH_S4Y0r47y4B_wANG:-NNjpJRQEe4r9OnLt2tT:b-b21j06) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L96)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not `from`? When can it fail?
</blockquote></details>

starknet-api doesn't expose a `From` cast.

The reason is that its field is a `PatriciaKey`, which is initialized from a `StarkHash` using a `try_from` (this can fail if the hash falls outside of the `CONTRACTADDRESS_DOMAIN_SIZE`).
___
*[`crates/native_blockifier/src/lib.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNH_dho0Oz6lP-1o7yH:-NNjpt1S6yvl02EmpIyc:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L105)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Add a blank line above.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/lib.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNH_lT-4i1lFH5JecfY:-NNjpw3M52oaW-zeLYTP:b-5vp0bb) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L106)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not `from`? When can it fail?
</blockquote></details>

Same reason as the `ContractAddress` above :(
___
*[`crates/native_blockifier/src/lib.rs` line 114 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNHa-mH94646-0QQr5y:-NNjq9FyEOc9y3du3Qyy:b2cgbh1) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L114)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

From `class_hash_to_compiled_class_hash`?
Can you look at the Papyrus code? How to they build 
</blockquote></details>

From our offline discussion, we decided on leaving this blank for now.
I'm removing the comment and moving to issue tracker.


<!-- Sent from Reviewable.io -->

2023-02-08 17:13 UTC, elintul requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/263)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/lib.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNH_1CK1aGzo5tWA5bO:-NNlwbSE8mJFs4A6Gu3o:b-6mk0c9) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L83)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I didn't understand the first sentence  :see_no_evil: (which is why I don't understand the `From` comment either :grimacing: )

Did you mean that you want python to cast everything to bytes (`[u8]`) before passing to Rust?
</blockquote></details>

`u64` isn't enough to represent `StarkFelt`s, so we either need to work with `BigInt` or `[u8]`.
___
*[`crates/native_blockifier/src/lib.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNHaFGt1FvS7_Jq8G6f:-NNlx1yj-9Wn2yrWpbl1:bg2nnbl) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L94)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Nice
</blockquote></details>

Can we instead move it to `IndexMap::<...>::new()`? So that `IndexMap` is not repeated?
___
*[`crates/native_blockifier/src/lib.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNlynhu9lSIvMKFayfG:-NNlynhu9lSIvMKFayfH:b-7zi8tj) ([raw file](https://github.com/starkware-libs/blockifier/blob/93a008027bcedd23fc3c90ead811b7beff44e9a3/crates/native_blockifier/src/lib.rs#L75)):*
> ```XML
>         let py_state_diff: PyStateDiff = py_state_diff.extract()?;
>         let state_diff = StateDiff::try_from(py_state_diff)?;
> ```

WDYM?



_Code quote:_
```XML
// TODO: This cast is tricky
```


<!-- Sent from Reviewable.io -->

2023-02-09 10:19 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/263)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/native_blockifier/src/lib.rs` line 83 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNH_1CK1aGzo5tWA5bO:-NNpeZ-G2ylGPN8OIRo3:bttc20e) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L83)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`u64` isn't enough to represent `StarkFelt`s, so we either need to work with `BigInt` or `[u8]`.
</blockquote></details>

Oh, i get it.

Ended up using `BigInt`, to avoid having to call `bytes()` on all the args in the python code (I don't think Pyo3 supports direct conversion from `int` to `[u8]`).

WDYT of how it came out? (I'm not 100% sure if this is "the best way" of doing this)
___
*[`crates/native_blockifier/src/lib.rs` line 94 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNHaFGt1FvS7_Jq8G6f:-NNpftcp65CFdnb7ZQZ-:b-q13988) ([raw file](https://github.com/starkware-libs/blockifier/blob/c7d09a30d89fb42821d6bb0dad37b921bd2f641b/crates/native_blockifier/src/lib.rs#L94)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we instead move it to `IndexMap::<...>::new()`? So that `IndexMap` is not repeated?
</blockquote></details>

Ya yr right.
Done.
___
*[`crates/native_blockifier/src/lib.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNlynhu9lSIvMKFayfG:-NNogJTI4504_zjSd0WC:btehmzl) ([raw file](https://github.com/starkware-libs/blockifier/blob/93a008027bcedd23fc3c90ead811b7beff44e9a3/crates/native_blockifier/src/lib.rs#L75)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYM?
</blockquote></details>

Ya TODO didn't help anyone :sweat_smile: 
Fixed TODO. 


<!-- Sent from Reviewable.io -->

2023-02-09 14:21 UTC, elintul requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/263)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5 and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNqXY_36SkGVcb8SnkP:-NNqXY_41vmvBCvL0-qA:b-ffqw0k) (no related file):*
Move all felts utils to `py_utils.rs`?

___
___
*[`crates/native_blockifier/src/lib.rs` line 112 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNqX03A7Zd4-v4rGo3n:-NNqX03A7Zd4-v4rGo3o:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/63865814e9a5e08c955fb00df29fdef21d25f9ff/crates/native_blockifier/src/lib.rs#L112)):*
> ```XML
> }
> 
> #[derive(FromPyObject, Hash, Eq, PartialEq)]
> ```





_Suggestion:_
```XML
#[derive(Eq, FromPyObject, Hash, PartialEq)]
```
___
*[`crates/native_blockifier/src/lib.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNqXwC1CFv4_rQe-vQ7:-NNqXwC1CFv4_rQe-vQ8:b-19s1kn) ([raw file](https://github.com/starkware-libs/blockifier/blob/63865814e9a5e08c955fb00df29fdef21d25f9ff/crates/native_blockifier/src/lib.rs#L119)):*
> ```XML
> }
> 
> fn big_uint_to_stark_felt(py_int: &PyAny) -> PyResult<StarkFelt> {
> ```

Not sure you need the `py_` prefix (it's understood from the type).
Maybe `value`?



_Code quote:_
```XML
py_int
```
___
*[`crates/native_blockifier/src/lib.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNqY9Kr8lvlKMuEFVbQ:-NNqY9Kr8lvlKMuEFVbR:btw6cnb) ([raw file](https://github.com/starkware-libs/blockifier/blob/63865814e9a5e08c955fb00df29fdef21d25f9ff/crates/native_blockifier/src/lib.rs#L119)):*
> ```XML
> }
> 
> fn big_uint_to_stark_felt(py_int: &PyAny) -> PyResult<StarkFelt> {
> ```

TAL at Alon's implementation. Do we think both of them?



_Code quote:_
```XML
big_uint_to_stark_felt
```


<!-- Sent from Reviewable.io -->

2023-02-12 06:34 UTC, elintul reviewed
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/263)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/lib.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NO3K65Y7SqbYmgTI6uN:-NO3K65Y7SqbYmgTI6uO:brgcixd) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2f0c7c235d53fab4e97bd2c1bcb0a615d4a2772/crates/native_blockifier/src/lib.rs#L118)):*
> ```XML
>     let biguint: BigUint = int.extract()?;
>     let biguint_hex = format!("{biguint:#x}");
>     StarkFelt::try_from(&*biguint_hex).map_err(|e| PyValueError::new_err(e.to_string()))
> ```

Can we make this more readable?



_Code quote:_
```XML
&*
```


<!-- Sent from Reviewable.io -->

2023-02-12 06:54 UTC, elintul reviewed
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/263)* status: all files reviewed, 7 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/lib.rs` line 75 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NO3OG-rCtuV8XrDmzQ9:-NO3OG-rCtuV8XrDmzQA:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2f0c7c235d53fab4e97bd2c1bcb0a615d4a2772/crates/native_blockifier/src/lib.rs#L75)):*
> ```XML
>     #[args(block_number)]
>     pub fn revert_state_diff(&mut self, block_number: u64) -> NativeBlockifierResult<()> {
>         let (txn, _) = self.writer.begin_rw_txn()?.revert_state_diff(BlockNumber(block_number))?;
> ```





_Suggestion:_
```XML
revert_txn
```
___
*[`crates/native_blockifier/src/lib.rs` line 93 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NO3OHj2450Tmmi_BbuC:-NO3OHj2450Tmmi_BbuD:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2f0c7c235d53fab4e97bd2c1bcb0a615d4a2772/crates/native_blockifier/src/lib.rs#L93)):*
> ```XML
>         let deployed_contract_class_definitions = IndexMap::<ClassHash, ContractClass>::new();
> 
>         let append_result = self.writer.begin_rw_txn()?.append_state_diff(
> ```





_Suggestion:_
```XML
append_txn
```
___
*[`crates/native_blockifier/src/lib.rs` line 112 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NO3OR5y8IifQOg6e0q-:-NO3OR5y8IifQOg6e0q0:b-szl0rp) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2f0c7c235d53fab4e97bd2c1bcb0a615d4a2772/crates/native_blockifier/src/lib.rs#L112)):*
> ```XML
> 
> #[derive(FromPyObject, Hash, Eq, PartialEq)]
> // Cannot use tuple struct since Pyo3 doesn't support `from_py_with` for them.
> ```

Not relevant anymore? :D



_Code quote:_
```XML
// Cannot use tuple struct since Pyo3 doesn't support `from_py_with` for them.
```


<!-- Sent from Reviewable.io -->

2023-02-13 08:53 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/263)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNqXY_36SkGVcb8SnkP:-NO8poTvEIaL9ex6YhK6:bdnnzwd) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move all felts utils to `py_utils.rs`?
</blockquote></details>

OK, i'll address all the comments below in a single revision, then move everything in the next revision, so you'll be able to see the changes.

___
___
*[`crates/native_blockifier/src/lib.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNqXwC1CFv4_rQe-vQ7:-NO8t7KI7eDrJo-S5M4O:b-bqsvf9) ([raw file](https://github.com/starkware-libs/blockifier/blob/63865814e9a5e08c955fb00df29fdef21d25f9ff/crates/native_blockifier/src/lib.rs#L119)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not sure you need the `py_` prefix (it's understood from the type).
Maybe `value`?
</blockquote></details>

This was for the struct value right? i think this is stale.
___
*[`crates/native_blockifier/src/lib.rs` line 119 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNqY9Kr8lvlKMuEFVbQ:-NO8v6p41qMTB94enxIS:b7rkdss) ([raw file](https://github.com/starkware-libs/blockifier/blob/63865814e9a5e08c955fb00df29fdef21d25f9ff/crates/native_blockifier/src/lib.rs#L119)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

TAL at Alon's implementation. Do we think both of them?
</blockquote></details>

Moved Alon's method to a new `utils.rs` module, and reused its logic.
I still need to have my own function since this function has a fixed signature (must take a `&PyAny` and return `Pyresult`
___
*[`crates/native_blockifier/src/lib.rs` line 112 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NO3OR5y8IifQOg6e0q-:-NO8sngH69Zn0oSxiucD:bthgi3m) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2f0c7c235d53fab4e97bd2c1bcb0a615d4a2772/crates/native_blockifier/src/lib.rs#L112)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not relevant anymore? :D
</blockquote></details>

Oh right :) their docs still say this isn't supported :facepalm:  I found out about this by just trying :sweat_smile: 
___
*[`crates/native_blockifier/src/lib.rs` line 118 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NO3K65Y7SqbYmgTI6uN:-NO8x9im3-s67TcnUAZ-:bkw2ms2) ([raw file](https://github.com/starkware-libs/blockifier/blob/a2f0c7c235d53fab4e97bd2c1bcb0a615d4a2772/crates/native_blockifier/src/lib.rs#L118)):*
> &*
Maybe
```rust
    let biguint_hex: &str = &*format!("{biguint:#x}");
    StarkFelt::try_from(biguint_hex).map_err(|e| PyValueError::new_err(e.to_string()))
```
Other than that, no other way that i know of :pensive:  

Generally deref-coercion is triggered in these instances (since we're converting &String -> &str), but for some reason this isn't triggered for From/TryFrom conventions (asked around about it and nobody knew why).


<!-- Sent from Reviewable.io -->

2023-02-13 09:05 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/263)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @alonh5 and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NNqXY_36SkGVcb8SnkP:-NO90Rsy7cTCrkZd6Ki0:bb6un1j) (no related file):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

OK, i'll address all the comments below in a single revision, then move everything in the next revision, so you'll be able to see the changes.
</blockquote></details>

Done

___


<!-- Sent from Reviewable.io -->

2023-02-13 12:03 UTC, elintul requested changes
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/263)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NO9e3fcE9aMtR6m8I4p:-NO9e3fcE9aMtR6m8I4q:bauisv5) (no related file):*
Move state diff.-related code to `py_state_diff.rs`?

___
___
*[`crates/native_blockifier/src/lib.rs` line 24 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NO9dOP354AGompPHBEN:-NO9dOP354AGompPHBEO:b-yffx8c) ([raw file](https://github.com/starkware-libs/blockifier/blob/b018304a721397a964f13507a87cd0891356b300/crates/native_blockifier/src/lib.rs#L24)):*
> ```XML
> #[pymodule]
> fn native_blockifier(_py: Python<'_>, py_module: &PyModule) -> PyResult<()> {
>     py_module.add_class::<Storage>()?;
> ```

Move after `PyTransactionExecutor`.



_Code quote:_
```XML
py_module.add_class::<Storage>()?;
```
___
*[`crates/native_blockifier/src/lib.rs` line 87 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NO9dWzI6HPNjYapPe42:-NO9dWzI6HPNjYapPe43:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b018304a721397a964f13507a87cd0891356b300/crates/native_blockifier/src/lib.rs#L87)):*
> ```XML
>         let deployed_contract_class_definitions = IndexMap::<ClassHash, ContractClass>::new();
> 
>         let append_txn = self.writer.begin_rw_txn()?.append_state_diff(
> ```





_Suggestion:_
```XML
        let append_txn = self.writer.begin_rw_txn()?.append_state_diff(
            block_number,
            state_diff,
            deployed_contract_class_definitions,
        )?;
        append_txn?.commit();
```


<!-- Sent from Reviewable.io -->

2023-02-13 13:16 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/263)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NO9e3fcE9aMtR6m8I4p:-NO9tNTa2kZJeTIGljAD:b-896fix) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move state diff.-related code to `py_state_diff.rs`?
</blockquote></details>

Done.

___
___
*[`crates/native_blockifier/src/lib.rs` line 87 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NO9dWzI6HPNjYapPe42:-NO9tixs2vFPN6p0SKam:b-jac1yn) ([raw file](https://github.com/starkware-libs/blockifier/blob/b018304a721397a964f13507a87cd0891356b300/crates/native_blockifier/src/lib.rs#L87)):*
> ```XML
>         let deployed_contract_class_definitions = IndexMap::<ClassHash, ContractClass>::new();
> 
>         let append_txn = self.writer.begin_rw_txn()?.append_state_diff(
> ```

Did you mean
```rust
     )?;
     append_txn.commit()?;
// or just
 )?.commit()?;
```
I'm not sure about both options, since IMO chaining anything after a multi-line parens is usually hard to spot.


<!-- Sent from Reviewable.io -->

2023-02-13 15:16 UTC, elintul approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/263)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/lib.rs` line 87 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NO9dWzI6HPNjYapPe42:-NOAKyyDCy7XYpCTIlSl:bgxsxor) ([raw file](https://github.com/starkware-libs/blockifier/blob/b018304a721397a964f13507a87cd0891356b300/crates/native_blockifier/src/lib.rs#L87)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Did you mean
```rust
     )?;
     append_txn.commit()?;
// or just
 )?.commit()?;
```
I'm not sure about both options, since IMO chaining anything after a multi-line parens is usually hard to spot.
</blockquote></details>

I meant choose if you do `let X_txn = ...; X_txn?.commit()?;` or `let X_txn = ...?; X_txn.commit()?;` - look at the first `?`; it's not symmetric in revert and append.


<!-- Sent from Reviewable.io -->

2023-02-13 15:16 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/263)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @giladchase)



<!-- Sent from Reviewable.io -->

2023-02-14 09:30 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/263)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @elintul)

___
*[`crates/native_blockifier/src/lib.rs` line 87 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/263#-NO9dWzI6HPNjYapPe42:-NOEEHsZDc2Mq46nfMl5:b-n1qivc) ([raw file](https://github.com/starkware-libs/blockifier/blob/b018304a721397a964f13507a87cd0891356b300/crates/native_blockifier/src/lib.rs#L87)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I meant choose if you do `let X_txn = ...; X_txn?.commit()?;` or `let X_txn = ...?; X_txn.commit()?;` - look at the first `?`; it's not symmetric in revert and append.
</blockquote></details>

Oh i get it now, but I think breaking the symmetry might be worth it, since they return different things.

Append returns the storage transaction, but revert also returns the state-diff dropped (which we currently ignore).
So in order to make them both `X_txn?.commit()?`, the revert has to be `revert_txn?.0.commit()?` :/

And the other option has a trailing "?" after a multiline parens, which I think isn't that readable.


<!-- Sent from Reviewable.io -->

2023-02-14 10:29 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/263#-:-NOETJBwCad-pUXIpqto:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)



<!-- Sent from Reviewable.io -->

2023-02-14 10:38 UTC, merged