Add logging
starkware-libs/blockifier pull request #324
Opened 2023-03-05 15:24 UTC by giladchase

Since Blockifier is a Lib crate, it suffices to put log statements where necessary, and let the binary user decide on log levels and configs.

In our case, the current user is the Python client, and the above decisions are delegated to it via `Pyo3-log`.

2023-03-05 18:04 UTC, dorimedini-starkware requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5, @elintul, and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NPmqwmC3IdMeULlsWdb:-NPmqwmC3IdMeULlsWdc:bjtig92) ([raw file](https://github.com/starkware-libs/blockifier/blob/cd86b47ac4da711f8d05e798e443fb9d1b9f3e02/crates/blockifier/src/transaction/account_transaction.rs#L153)):*
> ```XML
>         let validate_call_result = validate_call.execute(state, block_context, account_tx_context);
>         if validate_call_result.is_err() {
>             log::warn!("Transaction validation has failed.")
> ```

ummmm how  about defining some `log_if_error(res: Result<T>, msg: String) -> Result<T>` type thing for this? I see it a lot in this PR
then you could do
```
let validate_call_result = validate_call.execute(state, block_context, account_tx_context);
let validate_call_info = log_if_error(validate_call_result, "Transaction validation has failed.")?;
```



_Code quote:_
```XML
        if validate_call_result.is_err() {
            log::warn!("Transaction validation has failed.")
        }
        let validate_call_info = validate_call_result?;
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NPmwKtf28y4UVfWSkQL:-NPmwKtf28y4UVfWSkQM:b-gn0k55) ([raw file](https://github.com/starkware-libs/blockifier/blob/cd86b47ac4da711f8d05e798e443fb9d1b9f3e02/crates/blockifier/src/transaction/transactions.rs#L148)):*
> ```XML
>         let execute_result = execute_call.execute(state, block_context, account_tx_context);
>         if execute_result.is_err() {
>             log::warn!("Transaction execution Failed.")
> ```

define a const? this string is used often



_Code quote:_
```XML
"Transaction execution Failed."
```
___
*[`crates/native_blockifier/setup.py` line 6 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NPmwXo25DscXaTIEuK0:-NPmwXo25DscXaTIEuK1:bxkiav7) ([raw file](https://github.com/starkware-libs/blockifier/blob/cd86b47ac4da711f8d05e798e443fb9d1b9f3e02/crates/native_blockifier/setup.py#L6)):*
> ```Python
> setup(
>     name="native_blockifier",
>     version="0.12.0",
> ```

![image.png](https://files.reviewableusercontent.io/images/reviewable/76901494/0dPRIpmLQHgEaln28gAGA_gI/image.png)



_Code quote:_
```Python
version="0.12.0"
```


<!-- Sent from Reviewable.io -->

2023-03-05 18:05 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5, @elintul, and @giladchase)

___
*[`crates/native_blockifier/setup.py` line 6 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NPmwXo25DscXaTIEuK0:-NPmwmds6wyEwmdpmYaO:b-ttdh1f) ([raw file](https://github.com/starkware-libs/blockifier/blob/cd86b47ac4da711f8d05e798e443fb9d1b9f3e02/crates/native_blockifier/setup.py#L6)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

![image.png](https://files.reviewableusercontent.io/images/reviewable/76901494/0dPRIpmLQHgEaln28gAGA_gI/image.png)
</blockquote></details>

muahaha I merged


<!-- Sent from Reviewable.io -->

2023-03-05 18:10 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5, @elintul, and @giladchase)

___
*[`crates/native_blockifier/src/lib.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NPmxyIW1t3GbC879ycz:-NPmxyIW1t3GbC879yd-:bdg158l) ([raw file](https://github.com/starkware-libs/blockifier/blob/cd86b47ac4da711f8d05e798e443fb9d1b9f3e02/crates/native_blockifier/src/lib.rs#L23)):*
> ```XML
>     // Initialize Rust to Python logging.
>     // Usage: just create a Python logger as usual, and it'll capture Rust prints.
>     pyo3_log::init();
> ```

`logger = logging.getLogger(__name__)` is enough? how? curious


<!-- Sent from Reviewable.io -->

2023-03-06 08:23 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5, @elintul, and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NPmqwmC3IdMeULlsWdb:-NPq06Va6x5eHD14KhKB:bnjjot4) ([raw file](https://github.com/starkware-libs/blockifier/blob/cd86b47ac4da711f8d05e798e443fb9d1b9f3e02/crates/blockifier/src/transaction/account_transaction.rs#L153)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Good idea, this can be replaced by `inspect_err` once it is stabilized.

Another possibility that I wasn't sure about, WDYT about adding new error types `ValidationError`, `FeeTransferError` and `DeployTransactionError` (there are already Invoke and Declare types)?
This way, I'll be able to delete all prints, and only have a single `log::warn!("{}", err)` print [here](https://github.com/starkware-libs/blockifier/blob/cd86b47ac4da711f8d05e798e443fb9d1b9f3e02/crates/blockifier/src/transaction/transactions.rs#L46) instead of that trace log.
</blockquote></details>

:sgtm:


<!-- Sent from Reviewable.io -->

2023-03-07 07:59 UTC, dorimedini-starkware approved these changes
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5 and @elintul)



<!-- Sent from Reviewable.io -->

2023-03-07 08:05 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NPmqwmC3IdMeULlsWdb:-NPuyw4G40Bc-TetcWnG:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/cd86b47ac4da711f8d05e798e443fb9d1b9f3e02/crates/blockifier/src/transaction/account_transaction.rs#L153)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

:sgtm:
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 148 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NPmwKtf28y4UVfWSkQL:-NPv5NiR8D2w4mF0MHHm:bze417e) ([raw file](https://github.com/starkware-libs/blockifier/blob/cd86b47ac4da711f8d05e798e443fb9d1b9f3e02/crates/blockifier/src/transaction/transactions.rs#L148)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

define a const? this string is used often
</blockquote></details>

Stale.


<!-- Sent from Reviewable.io -->

2023-03-07 08:05 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5 and @elintul)



<!-- Sent from Reviewable.io -->

2023-03-08 09:22 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5 and @elintul)



<!-- Sent from Reviewable.io -->

2023-03-12 10:41 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: 6 of 10 files reviewed, 1 unresolved discussion (waiting on @alonh5, @elintul, and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 155 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NQKPBLHCvu5pDUfAvWE:-NQKPBLHCvu5pDUfAvWF:b-bry4as) ([raw file](https://github.com/starkware-libs/blockifier/blob/c75e07f48ceef93cc0f15179eb9c142d70111817/crates/blockifier/src/transaction/account_transaction.rs#L155)):*
> ```XML
>             log::warn!("Transaction validation has failed.")
>         }
>         let validate_call_info = validate_call_result?;
> ```

why was this reverted...? didn't work?
why not a `log_if_err(result, log_string) -> Result` function instead of this code dup?


<!-- Sent from Reviewable.io -->

2023-03-16 15:25 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @alonh5, @dorimedini-starkware, and @elintul)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 155 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NQKPBLHCvu5pDUfAvWE:-NQf0e4d9KaUG7Ze1qYZ:bthl70) ([raw file](https://github.com/starkware-libs/blockifier/blob/c75e07f48ceef93cc0f15179eb9c142d70111817/crates/blockifier/src/transaction/account_transaction.rs#L155)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why was this reverted...? didn't work?
why not a `log_if_err(result, log_string) -> Result` function instead of this code dup?
</blockquote></details>

Whoops, had a bad merge conflict.
Fixed.


<!-- Sent from Reviewable.io -->

2023-03-16 16:28 UTC, dorimedini-starkware approved these changes
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5 and @elintul)



<!-- Sent from Reviewable.io -->

2023-03-20 08:35 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @elintul, and @giladchase)

___
*[`crates/blockifier/src/transaction/errors.rs` line 64 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NQy8gi42sMjQCYI9J8r:-NQy8gi42sMjQCYI9J8s:b-2ykt9u) ([raw file](https://github.com/starkware-libs/blockifier/blob/91ce9ef1f6a8a48058b602613a7162c34dc959ae/crates/blockifier/src/transaction/errors.rs#L64)):*
> ```XML
>     #[error("Calling other contracts during '{entry_point_kind}' execution is forbidden.")]
>     UnauthorizedInnerCall { entry_point_kind: String },
>     #[error("Unknown chain ID '{chain_id:?}'.")]
> ```

why not like this...?



_Suggestion:_
```XML
#[derive(Debug, Error)]
pub enum TransactionExecutionError {
    #[error(transparent)]
    DeclareTransactionError(#[from] DeclareTransactionError),
    #[error("Transaction deployment has failed.")]
    DeployTransactionError(#[from] EntryPointExecutionError),
    #[error(transparent)]
    EntryPointExecutionError(#[from] EntryPointExecutionError),
    #[error(transparent)]
    UnauthorizedInnerCall { entry_point_kind: String },
    #[error("Unknown chain ID '{chain_id:?}'.")]
    UnknownChainId { chain_id: String },
    #[error("Transaction validation has failed.")]
    ValidateTransactionError(#[from] EntryPointExecutionError),
}
```


<!-- Sent from Reviewable.io -->

2023-03-20 08:42 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5, @dorimedini-starkware, and @elintul)

___
*[`crates/blockifier/src/transaction/errors.rs` line 64 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NQy8gi42sMjQCYI9J8r:-NQyAfzN--kuLXOlY32P:b-3z9rd1) ([raw file](https://github.com/starkware-libs/blockifier/blob/91ce9ef1f6a8a48058b602613a7162c34dc959ae/crates/blockifier/src/transaction/errors.rs#L64)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not like this...?
</blockquote></details>

Yr right, but i wanted to be consistent with the rest of the errors here.
I'll refactor in a subsequent PR?


<!-- Sent from Reviewable.io -->

2023-03-20 08:44 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324#-:-NQyB7Hn7DahaXiw_KYj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/transaction/errors.rs` line 64 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NQy8gi42sMjQCYI9J8r:-NQyBEMADVFBsLq8BxQN:b-ojx56k) ([raw file](https://github.com/starkware-libs/blockifier/blob/91ce9ef1f6a8a48058b602613a7162c34dc959ae/crates/blockifier/src/transaction/errors.rs#L64)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Well looking at it again, those errors have extra information in the error name, where mine doesn't have.
Fixing now
</blockquote></details>

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> anyway :P


<!-- Sent from Reviewable.io -->

2023-03-20 10:22 UTC, elintul approved these changes
> Reviewed 3 of 9 files at r1, 1 of 7 files at r3, 1 of 3 files at r6, 2 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/lib.rs` line 23 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NQyWl-uENmny7xzFyja:-NQyWl-uENmny7xzFyjb:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/91ce9ef1f6a8a48058b602613a7162c34dc959ae/crates/native_blockifier/src/lib.rs#L23)):*
> ```XML
> #[pymodule]
> fn native_blockifier(py: Python<'_>, py_module: &PyModule) -> PyResult<()> {
>     // Initialize Rust to Python logging.
> ```





_Suggestion:_
```XML
Rust-to-Python
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 248 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NQyX0EM04aKkaOcrKU_:-NQyX0EM04aKkaOcrKUa:bxh217o) ([raw file](https://github.com/starkware-libs/blockifier/blob/91ce9ef1f6a8a48058b602613a7162c34dc959ae/crates/native_blockifier/src/py_transaction.rs#L248)):*
> ```XML
>     ) -> NativeBlockifierResult<Self> {
>         // TODO(Elin,01/04/2023): think of how to decouple the args needed to instantiate
>         // executor and storage - (storage_path, max_size).
> ```

Add a log after: `log::debug!("Initialized transaction executor.");`.



_Suggestion:_
```XML
        log::debug!("Initializing transaction executor...");
        
        // TODO(Elin,01/04/2023): think of how to decouple the args needed to instantiate
        // executor and storage - (storage_path, max_size).
        let storage = Storage::new(storage_path, max_size)?;
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 273 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NQyXERt0zSNxAKebdjn:-NQyXERt0zSNxAKebdjo:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/91ce9ef1f6a8a48058b602613a7162c34dc959ae/crates/native_blockifier/src/py_transaction.rs#L273)):*
> ```XML
>     /// Returns the state diff resulting in executing transactions.
>     pub fn finalize(&mut self) -> PyStateDiff {
>         log::debug!("Finalizing execution.");
> ```





_Suggestion:_
```XML
        log::debug!("Finalizing execution...");
        PyStateDiff::from(self.borrow_state().to_state_diff())
        log::debug!("Finalized transaction executor.");
```
___
*[`crates/native_blockifier/src/storage.rs` line 32 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NQyXRLL3IMmrHc2GG9_:-NQyXRLL3IMmrHc2GG9a:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/91ce9ef1f6a8a48058b602613a7162c34dc959ae/crates/native_blockifier/src/storage.rs#L32)):*
> ```XML
>     #[args(path, max_size)]
>     pub fn new(path: String, max_size: usize) -> NativeBlockifierResult<Storage> {
>         log::info!("Initialize Blockifier storage.");
> ```





_Suggestion:_
```XML
        log::debug!("Initializing Blockifier storage...");
        let db_config = papyrus_storage::db::DbConfig { path, max_size };
        let (reader, writer) = papyrus_storage::open_storage(db_config)?;
        log::debug!("Initialized Blockifier storage...");
```
___
*[`crates/native_blockifier/src/storage.rs` line 79 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NQyXexyD32nSkyEdMK1:-NQyXexyD32nSkyEdMK2:bz2uh82) ([raw file](https://github.com/starkware-libs/blockifier/blob/91ce9ef1f6a8a48058b602613a7162c34dc959ae/crates/native_blockifier/src/storage.rs#L79)):*
> ```XML
>         log::debug!(
>             "Appending state diff with {block_id:?} for block_number: {}.",
>             py_block_info.block_number
> ```

Add a log in revert as well.



_Code quote:_
```XML
        log::debug!(
            "Appending state diff with {block_id:?} for block_number: {}.",
            py_block_info.block_number
        );
```


<!-- Sent from Reviewable.io -->

2023-03-26 13:37 UTC, dorimedini-starkware approved these changes
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @giladchase)



<!-- Sent from Reviewable.io -->

2023-03-26 13:50 UTC, elintul approved these changes
> Reviewed 4 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/storage.rs` line 60 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NRTAo3p1e1q3p7MdEtZ:-NRTAo3p1e1q3p7MdEt_:b223850) ([raw file](https://github.com/starkware-libs/blockifier/blob/53023e94ccb17818e18871eba6b7acf773c12042/crates/native_blockifier/src/storage.rs#L60)):*
> ```XML
>     #[args(block_number)]
>     pub fn revert_state_diff(&mut self, block_number: u64) -> NativeBlockifierResult<()> {
>         log::debug!("Reverting state diff for {block_number:?}.",);
> ```

Can the comma be deleted?



_Code quote:_
```XML
,
```


<!-- Sent from Reviewable.io -->

2023-03-26 13:51 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @giladchase)



<!-- Sent from Reviewable.io -->

2023-03-26 13:55 UTC, elintul requested changes
> Reviewed 1 of 5 files at r7, 2 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/blockifier/src/transaction/errors.rs` line 26 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NRTBmkBBStO8nfPf9Vw:-NRTBmkBBStO8nfPf9Vx:bp2t48r) ([raw file](https://github.com/starkware-libs/blockifier/blob/53023e94ccb17818e18871eba6b7acf773c12042/crates/blockifier/src/transaction/errors.rs#L26)):*
> ```XML
>     ClassAlreadyDeclared { class_hash: ClassHash },
> }
> ```

What about actual execution (running `__execute__`) and charging fee-related errors?
___
*[`crates/blockifier/src/transaction/errors.rs` line 29 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NRTB3Fb2m8XWyU3zuFr:-NRTB3Fb2m8XWyU3zuFs:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/53023e94ccb17818e18871eba6b7acf773c12042/crates/blockifier/src/transaction/errors.rs#L29)):*
> ```XML
> #[derive(Debug, Error)]
> pub enum DeployTransactionError {
>     #[error("Transaction deployment has failed.")]
> ```





_Suggestion:_
```XML
pub enum ContractConstructorExecutionError {
    #[error("Contract constructor execution has failed.")]
    ContractConstructorExecutionFailed(#[from] EntryPointExecutionError),
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 40 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NRTBFRi3huPy1G7Jg4R:-NRTBFRi3huPy1G7Jg4S:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/53023e94ccb17818e18871eba6b7acf773c12042/crates/blockifier/src/transaction/transactions.rs#L40)):*
> ```XML
>         block_context: &BlockContext,
>     ) -> TransactionExecutionResult<TransactionExecutionInfo> {
>         log::debug!("Executing Transaction.");
> ```





_Suggestion:_
```XML
log::debug!("Executing Transaction...");
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 48 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NRTBHMkCAX31RKTtgpd:-NRTBHMkCAX31RKTtgpe:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/53023e94ccb17818e18871eba6b7acf773c12042/crates/blockifier/src/transaction/transactions.rs#L48)):*
> ```XML
>                 transactional_state.commit();
>                 log::debug!("Transaction execution complete.");
>                 Ok(value)
> ```





_Suggestion:_
```XML
log::debug!("Transaction execution complete and committed.");
```


<!-- Sent from Reviewable.io -->

2023-03-26 13:55 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/native_blockifier/src/storage.rs` line 60 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NRTAo3p1e1q3p7MdEtZ:-NRTC1wSBKYuvTuW9JS5:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/53023e94ccb17818e18871eba6b7acf773c12042/crates/native_blockifier/src/storage.rs#L60)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can the comma be deleted?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-26 13:56 UTC, elintul reviewed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5 and @giladchase)



<!-- Sent from Reviewable.io -->

2023-03-26 14:00 UTC, dorimedini-starkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 4 unresolved discussions (waiting on @alonh5 and @giladchase)



<!-- Sent from Reviewable.io -->

2023-03-26 14:30 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/transaction/errors.rs` line 26 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NRTBmkBBStO8nfPf9Vw:-NRTJRaREsfRfDf50Jcz:b5fsy0z) ([raw file](https://github.com/starkware-libs/blockifier/blob/53023e94ccb17818e18871eba6b7acf773c12042/crates/blockifier/src/transaction/errors.rs#L26)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What about actual execution (running `__execute__`) and charging fee-related errors?
</blockquote></details>

For fee-related errors we raise `FeeTransferError`, and for general __execute__ I assumed not wrapping the `EntryPointExecutionError` with any of the other enums would suffice?
In other words, an `EntryPointExecutionError` that isn't wrapped with a FeeTransferError, ValidationError etc. is by elimination a __execute__ error.

Or is that too implicity?
___
*[`crates/blockifier/src/transaction/errors.rs` line 29 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NRTB3Fb2m8XWyU3zuFr:-NRTGZyi0X4UHuX_ZOiu:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/53023e94ccb17818e18871eba6b7acf773c12042/crates/blockifier/src/transaction/errors.rs#L29)):*
> ```XML
> #[derive(Debug, Error)]
> pub enum DeployTransactionError {
>     #[error("Transaction deployment has failed.")]
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-03-26 14:32 UTC, elintul requested changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/blockifier/src/transaction/errors.rs` line 44 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NRTKQUV9td4xXFxbi5w:-NRTKQUV9td4xXFxbi5x:b-v53drf) ([raw file](https://github.com/starkware-libs/blockifier/blob/3fdb04d96d4a2399219e6ea6a731413ba13008e6/crates/blockifier/src/transaction/errors.rs#L44)):*
> ```XML
>     DeclareTransactionError(#[from] DeclareTransactionError),
>     #[error(transparent)]
>     ContractConstructorExecutionFailed(#[from] ContractConstructorExecutionError),
> ```

Keep alphabetized.



_Code quote:_
```XML
    ContractConstructorExecutionFailed(#[from] ContractConstructorExecutionError),
```


<!-- Sent from Reviewable.io -->

2023-03-26 14:33 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/blockifier/src/transaction/errors.rs` line 26 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NRTBmkBBStO8nfPf9Vw:-NRTKbKRD18uLQt3c7e4:b-2sw7cy) ([raw file](https://github.com/starkware-libs/blockifier/blob/53023e94ccb17818e18871eba6b7acf773c12042/crates/blockifier/src/transaction/errors.rs#L26)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

For fee-related errors we raise `FeeTransferError`, and for general __execute__ I assumed not wrapping the `EntryPointExecutionError` with any of the other enums would suffice?
In other words, an `EntryPointExecutionError` that isn't wrapped with a FeeTransferError, ValidationError etc. is by elimination a __execute__ error.

Or is that too implicity?
</blockquote></details>

A bit implicit, but might be clear enough and not worth it only for logging. Can you show me where it's logged?


<!-- Sent from Reviewable.io -->

2023-03-26 14:40 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/transaction/errors.rs` line 26 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NRTBmkBBStO8nfPf9Vw:-NRTLmaqCZyRMDJQWNdg:b-c9fc5b) ([raw file](https://github.com/starkware-libs/blockifier/blob/53023e94ccb17818e18871eba6b7acf773c12042/crates/blockifier/src/transaction/errors.rs#L26)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

A bit implicit, but might be clear enough and not worth it only for logging. Can you show me where it's logged?
</blockquote></details>

Sure.
All execution-type errors/and success is logged [here](https://github.com/starkware-libs/blockifier/blob/3fdb04d96d4a2399219e6ea6a731413ba13008e6/crates/blockifier/src/transaction/transactions.rs#L51). 
___
*[`crates/blockifier/src/transaction/errors.rs` line 44 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NRTKQUV9td4xXFxbi5w:-NRTM7VE0dcHJHNgiHDW:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/3fdb04d96d4a2399219e6ea6a731413ba13008e6/crates/blockifier/src/transaction/errors.rs#L44)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Keep alphabetized.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-26 14:43 UTC, elintul requested changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @giladchase)

___
*[`crates/blockifier/src/transaction/errors.rs` line 26 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NRTBmkBBStO8nfPf9Vw:-NRTMikXDBO2btxZXroT:b-3vgp1g) ([raw file](https://github.com/starkware-libs/blockifier/blob/53023e94ccb17818e18871eba6b7acf773c12042/crates/blockifier/src/transaction/errors.rs#L26)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Sure.
All execution-type errors/and success is logged [here](https://github.com/starkware-libs/blockifier/blob/3fdb04d96d4a2399219e6ea6a731413ba13008e6/crates/blockifier/src/transaction/transactions.rs#L51). 
</blockquote></details>

Maybe explicit is better here, so that it'll be easier to recognize which errors got to this point by not being caught before.


<!-- Sent from Reviewable.io -->

2023-03-26 17:20 UTC, dorimedini-starkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @giladchase)



<!-- Sent from Reviewable.io -->

2023-03-27 07:38 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @giladchase)

___
*[`crates/blockifier/src/transaction/errors.rs` line 26 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NRTBmkBBStO8nfPf9Vw:-NRX-6ZH2DSpGQ_dO1_q:b-s94s9z) ([raw file](https://github.com/starkware-libs/blockifier/blob/53023e94ccb17818e18871eba6b7acf773c12042/crates/blockifier/src/transaction/errors.rs#L26)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Oh wait, my bad, there's already a `EntryPointExecutionError`, which is what you want.
</blockquote></details>

Not really, I prefer specifically to the execution of `__execute__`, which is one of three steps any transaction goes through; while `EntryPointExecutionError` is raised from the execution of _any_ EP.


<!-- Sent from Reviewable.io -->

2023-03-27 15:57 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @alonh5 and @elintul)

___
*[`crates/blockifier/src/transaction/errors.rs` line 26 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NRTBmkBBStO8nfPf9Vw:-NRYmQ4F2o_kgTzfEo5_:bl9z0f5) ([raw file](https://github.com/starkware-libs/blockifier/blob/53023e94ccb17818e18871eba6b7acf773c12042/crates/blockifier/src/transaction/errors.rs#L26)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not really, I prefer specifically to the execution of `__execute__`, which is one of three steps any transaction goes through; while `EntryPointExecutionError` is raised from the execution of _any_ EP.
</blockquote></details>

Ya yr right.
Fixed.
Also found an unrelated unnecessary `map_err` so removed it.


<!-- Sent from Reviewable.io -->

2023-03-27 18:37 UTC, dorimedini-starkware approved these changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5, @elintul, and @giladchase)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 102 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NRZLpe6AfzqrIBUhq4C:-NRZLpe6AfzqrIBUhq4D:bs9mt2o) ([raw file](https://github.com/starkware-libs/blockifier/blob/0898fa2cbd2bd35294cd7f5e7540f2b24b29caf6/crates/blockifier/src/transaction/transactions.rs#L102)):*
> ```XML
>             Ok(_) => {
>                 // Class is already declared; cannot redeclare.
>                 Err(DeclareTransactionError::ClassAlreadyDeclared { class_hash: self.class_hash })?
> ```

you can do that instead of wrapping with `TransactionExecutionResult::from`???
or is the `?` a mistake maybe?



_Code quote:_
```XML
?
```


<!-- Sent from Reviewable.io -->

2023-03-28 05:36 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5, @dorimedini-starkware, and @elintul)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 102 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NRZLpe6AfzqrIBUhq4C:-NRagfDyC8Vm5rKUHW7A:b-z4c0zt) ([raw file](https://github.com/starkware-libs/blockifier/blob/0898fa2cbd2bd35294cd7f5e7540f2b24b29caf6/crates/blockifier/src/transaction/transactions.rs#L102)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you can do that instead of wrapping with `TransactionExecutionResult::from`???
or is the `?` a mistake maybe?
</blockquote></details>

Ya, but I was sure if it's a legit thing to do, and your comment suggests that it isn't :sweat: should I revert this part?

What's going on is: the `?` trys to `unwrap` the result, or otherwise return the error _and apply `map_err` implicitly in order to match the function signature_.
Here, however, we necessarily have an error, since we applied `?` on a `Err(...)` obj, therefore `Err(...)?` is equivalent to `Err(...).map_err(<the_error_in_the _current_function_signature>)`.


<!-- Sent from Reviewable.io -->

2023-03-28 08:53 UTC, dorimedini-starkware approved these changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5, @elintul, and @giladchase)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 102 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NRZLpe6AfzqrIBUhq4C:-NRbPsUd-aXngZtQO2-x:bodafpm) ([raw file](https://github.com/starkware-libs/blockifier/blob/0898fa2cbd2bd35294cd7f5e7540f2b24b29caf6/crates/blockifier/src/transaction/transactions.rs#L102)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

OK i'm reverting :see_no_evil:  this helps no one :smiling_face_with_tear: : 
</blockquote></details>

what? I actually liked the `?` better
i was really asking
but nvm it's equivalent


<!-- Sent from Reviewable.io -->

2023-03-28 09:20 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324#-:-NRbW45e3i5vxLUqzhca:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/blockifier/src/transaction/errors.rs` line 40 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/324#-NRbA1RO45Ni5xBCCNPV:-NRbVwvFD1MzbAhLuzrF:b2m9l0e) ([raw file](https://github.com/starkware-libs/blockifier/blob/0898fa2cbd2bd35294cd7f5e7540f2b24b29caf6/crates/blockifier/src/transaction/errors.rs#L40)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Done.
But note that we now have both an `ExecuteTransactionError` and a `TransactionExecutionError`...
</blockquote></details>

It's okay for now, until we get confused.


<!-- Sent from Reviewable.io -->

2023-03-28 13:03 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)



<!-- Sent from Reviewable.io -->

2023-03-28 13:54 UTC, dorimedini-starkware approved these changes
> Reviewed 5 of 5 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)



<!-- Sent from Reviewable.io -->

2023-03-28 13:56 UTC, elintul approved these changes
> Reviewed 1 of 1 files at r14, 5 of 5 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/324)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)



<!-- Sent from Reviewable.io -->

2023-03-28 13:58 UTC, merged