Don't commit transactions before checking if they can be added
starkware-libs/blockifier pull request #343
Opened 2023-03-16 13:50 UTC by giladchase

Previously, transactions were committed onto the state if they succeeded, which is incorrect in cases where the transaction weight is too big.

Now accepting a python callback, which is given the `tx_weights` and raises an exception if they cannot be added.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/343)

2023-03-16 14:15 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/343)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQekql_1cU_IYM2vXFh:-NQekql_1cU_IYM2vXFi:bj5xhw2) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad4d96e3c17a53144ec969a49a61c7bf27feb3f7/crates/blockifier/src/transaction/transactions.rs#L54)):*
> ```XML
>     }
> 
>     fn execute_dry_run<'a>(
> ```

there is dupped logic here. maybe put it in an
```
fn execute_transactional(
    self,
    state: &mut TransactionalState<'_, S>,
    block_context: &BlockContext,
    dry_run: bool,
) -> TransactionExecutionResult<TransactionExecutionInfo>
```
with this change, `execute` will create the transactional state from it's input cached state, and pass it to `execute_transactional` with `dry_run=false`; `execute_dry_run` won't need to create the transactional state (it's input) and passes `true`.
WDYT?
Too much boilerplate for so little dup?
___
*[`crates/native_blockifier/src/py_transaction.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQej-3D12XzcIwhzJDc:-NQej-3D12XzcIwhzJDd:b-o1x0pm) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad4d96e3c17a53144ec969a49a61c7bf27feb3f7/crates/native_blockifier/src/py_transaction.rs#L275)):*
> ```XML
>         let block_context = &self.block_context;
> 
>         let tx_execution_result = storage.with_state_mut(|state| {
> ```

why the intermediate value? Why not add a `?` after `tx_info_result` and assign to `tx_execution_info` directly?



_Code quote:_
```XML
tx_execution_result
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 276 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQejsjs9C0-sogJITBy:-NQejsjs9C0-sogJITBz:b-f9h3sh) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad4d96e3c17a53144ec969a49a61c7bf27feb3f7/crates/native_blockifier/src/py_transaction.rs#L276)):*
> ```XML
> 
>         let tx_execution_result = storage.with_state_mut(|state| {
>             let mut transactional_state = CachedState::new(MutRefState::new(state));
> ```

calling `commit` on this object applies the `state` in `storage`?
can you unit test this somehow?



_Code quote:_
```XML
let mut transactional_state = CachedState::new(MutRefState::new(state));
```


<!-- Sent from Reviewable.io -->

2023-03-16 14:20 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/343)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQemkbUBRFmLS4NdnGh:-NQemkbUBRFmLS4NdnGi:b3fipso) (no related file):*
... how is your CI passing on the balagan branch?

___


<!-- Sent from Reviewable.io -->

2023-03-16 14:21 UTC, elintul approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/343)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 276 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQejsjs9C0-sogJITBy:-NQemk3TDl0TO-zjT-ay:bsfxqjh) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad4d96e3c17a53144ec969a49a61c7bf27feb3f7/crates/native_blockifier/src/py_transaction.rs#L276)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

calling `commit` on this object applies the `state` in `storage`?
can you unit test this somehow?
</blockquote></details>

No, only on the cached state `PyExecutor` is maintaining.
Rust doesn't write to Papyrus in the execution stage; only during alignment.


<!-- Sent from Reviewable.io -->

2023-03-16 14:27 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/343)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 276 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQejsjs9C0-sogJITBy:-NQeo7TF0nxvsC5K5kzo:b-iz39) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad4d96e3c17a53144ec969a49a61c7bf27feb3f7/crates/native_blockifier/src/py_transaction.rs#L276)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No, only on the cached state `PyExecutor` is maintaining.
Rust doesn't write to Papyrus in the execution stage; only during alignment.
</blockquote></details>

so `CachedState::new(MutRefState::new(state));` gives a mutable state object, such that if I call `.commit()` on it, it will update `state`?



_Code quote:_
```XML
CachedState::new(MutRefState::new(state));
```


<!-- Sent from Reviewable.io -->

2023-03-16 14:34 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/343)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 276 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQejsjs9C0-sogJITBy:-NQepsiP4BF4IiUZyWXI:btgzvcu) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad4d96e3c17a53144ec969a49a61c7bf27feb3f7/crates/native_blockifier/src/py_transaction.rs#L276)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

so `CachedState::new(MutRefState::new(state));` gives a mutable state object, such that if I call `.commit()` on it, it will update `state`?
</blockquote></details>

It's a wrapper for `state`, that doesn't modify the inner state until `commit()` is called.


<!-- Sent from Reviewable.io -->

2023-03-19 13:41 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/343)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQekql_1cU_IYM2vXFh:-NQu2BLi0T_DCFtwizlK:b-x2tdol) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad4d96e3c17a53144ec969a49a61c7bf27feb3f7/crates/blockifier/src/transaction/transactions.rs#L54)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there is dupped logic here. maybe put it in an
```
fn execute_transactional(
    self,
    state: &mut TransactionalState<'_, S>,
    block_context: &BlockContext,
    dry_run: bool,
) -> TransactionExecutionResult<TransactionExecutionInfo>
```
with this change, `execute` will create the transactional state from it's input cached state, and pass it to `execute_transactional` with `dry_run=false`; `execute_dry_run` won't need to create the transactional state (it's input) and passes `true`.
WDYT?
Too much boilerplate for so little dup?
</blockquote></details>

This would be tricky for a couple reasons, with the main one being:
`commit`/`abort` consume the transactional_state, which can't be done inside `execute_transactional`, since it holds a (mutable) reference to it (it would make a "dangling pointer").
 
In other words, execute_transactional isn't given ownership of the thing, so it can't consume it.

Why not give it ownership then and return the transactional_state when dry-running?
Because we can't have a function that conditionally consumes or returns a thing (at least not without some questionable typing).

Alternatively, we can just remove the `execute` function, which is not unused (only dry_run is).
@elintul said that it might be in use soon, but i don't remember the use-case.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQej-3D12XzcIwhzJDc:-NQsl4BBAY3fE3r18tQ-:b-usi2qa) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad4d96e3c17a53144ec969a49a61c7bf27feb3f7/crates/native_blockifier/src/py_transaction.rs#L275)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why the intermediate value? Why not add a `?` after `tx_info_result` and assign to `tx_execution_info` directly?
</blockquote></details>

I find `?`  after multi-line deep nested expressions hard to read, that is, I prefer:
```rust
let tx_execution_result = do_somthing((
//--many lines later--
     )
);
let tx_execution_info = tx_execution_result?;
```
over
```rust
let tx_execution_info = do_somthing((
//--many lines later--
    )
)?;
```
I think that trailing `?` messes with my instinct to skip over lines with just closing parens on them :thinking: 

On the other hand, I couldn't find any idiom/style-guide references to it... the closest thing is [this one](https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/style.md#functional-combinators) warding off against unnecessary chaining.

WDYT?
___
*[`crates/native_blockifier/src/py_transaction.rs` line 276 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQejsjs9C0-sogJITBy:-NQsj4s0Ag-EZMgkWkys:bj9fi9p) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad4d96e3c17a53144ec969a49a61c7bf27feb3f7/crates/native_blockifier/src/py_transaction.rs#L276)):*
>can you unit test this somehow?

Sure, but out of scope for this PR I think.
We've built up a bit of a testing debt which Elin said we'll pay off soon.


<!-- Sent from Reviewable.io -->

2023-03-19 13:43 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/343)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQemkbUBRFmLS4NdnGh:-NQu67AQ4vwbYB_mAB3I:bsjy0ui) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

... how is your CI passing on the balagan branch?
</blockquote></details>

Rebased over main

___


<!-- Sent from Reviewable.io -->

2023-03-19 13:58 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/343)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQemkbUBRFmLS4NdnGh:-NQu9aOs6koYil6Hwhut:b7cie6y) (no related file):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Rebased over main
</blockquote></details>

still see merge target balagan after refresh

___
___
*[`crates/blockifier/src/transaction/transactions.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQekql_1cU_IYM2vXFh:-NQu8amgBfgGkQqVTbST:b-ua72o0) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad4d96e3c17a53144ec969a49a61c7bf27feb3f7/crates/blockifier/src/transaction/transactions.rs#L54)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

This would be tricky for a couple reasons, with the main one being:
`commit`/`abort` consume the transactional_state, which can't be done inside `execute_transactional`, since it holds a (mutable) reference to it (it would make a "dangling pointer").
 
In other words, execute_transactional isn't given ownership of the thing, so it can't consume it.

Why not give it ownership then and return the transactional_state when dry-running?
Because we can't have a function that conditionally consumes or returns a thing (at least not without some questionable typing).

Alternatively, we can just remove the `execute` function, which is not unused (only dry_run is).
@elintul said that it might be in use soon, but i don't remember the use-case.
</blockquote></details>

hmmm... I guess this is a macro candidate but code-compressing can be done later, these functions are siblings it should be easy later
___
*[`crates/blockifier/src/transaction/transactions.rs` line 60 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQu8TcMBvDyPCvj22Vl:-NQu8TcMBvDyPCvj22Vm:b-5ub6j) ([raw file](https://github.com/starkware-libs/blockifier/blob/2620211d25d18d5fa2d376818c9b68f05bff3ce0/crates/blockifier/src/transaction/transactions.rs#L60)):*
> ```XML
>         match execution_result {
>             Ok(value) => Ok(value),
>             Err(error) => Err(error),
> ```

ummm isn't this equivalent?



_Suggestion:_
```XML
        execution_result
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQej-3D12XzcIwhzJDc:-NQu9A-J40oe-Ug8Vbt4:bmlijtq) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad4d96e3c17a53144ec969a49a61c7bf27feb3f7/crates/native_blockifier/src/py_transaction.rs#L275)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I find `?`  after multi-line deep nested expressions hard to read, that is, I prefer:
```rust
let tx_execution_result = do_somthing((
//--many lines later--
     )
);
let tx_execution_info = tx_execution_result?;
```
over
```rust
let tx_execution_info = do_somthing((
//--many lines later--
    )
)?;
```
I think that trailing `?` messes with my instinct to skip over lines with just closing parens on them :thinking: 

On the other hand, I couldn't find any idiom/style-guide references to it... the closest thing is [this one](https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/style.md#functional-combinators) warding off against unnecessary chaining.

WDYT?
</blockquote></details>

in the cairo repo, text-searching the regular expression `^[ })]*\?;` has 119 hits, or 167 if you drop the `;` requirement :P
I'm unblocking but I like the trailing `?`


<!-- Sent from Reviewable.io -->

2023-03-19 14:00 UTC, dorimedini-starkware reviewed
> Reviewed 1 of 5 files at r3, 1 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/343)* status: 2 of 13 files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)



<!-- Sent from Reviewable.io -->

2023-03-19 14:05 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/343)* status: 2 of 13 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQemkbUBRFmLS4NdnGh:-NQuB6ZjBq066fUT4yYH:bb6un1j) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

still see merge target balagan after refresh
</blockquote></details>

Done

___


<!-- Sent from Reviewable.io -->

2023-03-19 14:16 UTC, dorimedini-starkware reviewed
> Reviewed 2 of 5 files at r2, 1 of 5 files at r3, 5 of 7 files at r4, 1 of 3 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/343)* status: all files reviewed, 5 unresolved discussions (waiting on @giladchase)

___
*[`crates/blockifier/src/execution/execution_utils.rs` line 150 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQuB_qq8tU_LhmiwOhI:-NQuB_qq8tU_LhmiwOhJ:b-8gcpoe) ([raw file](https://github.com/starkware-libs/blockifier/blob/2620211d25d18d5fa2d376818c9b68f05bff3ce0/crates/blockifier/src/execution/execution_utils.rs#L150)):*
> ```XML
>     let mut vm = vm_execution_context.vm;
>     let mut runner = vm_execution_context.runner;
>     let mut syscall_handler = vm_execution_context.syscall_handler;
> ```

Does
```
let VmExecutionContext {
    vm: mut vm,
    runner: mut runner,
    syscall_handler: mut syscall_handler,
    initial_syscall_ptr,
    entry_point_pc,
} = initialize_execution_context(
    &call,
    class_hash,
    state,
    execution_context,
    block_context,
    account_tx_context,
)?;
```
work?
or is there no combination of `mut vm,`/`vm: mut vm` that gets these as mutable?
then you also get `initial_syscall_ptr` and `entry_point_pc` as a variables, don't see why you want some as variables and some not



_Code quote:_
```XML
    let vm_execution_context = initialize_execution_context(
        &call,
        class_hash,
        state,
        execution_context,
        block_context,
        account_tx_context,
    )?;
    let mut vm = vm_execution_context.vm;
    let mut runner = vm_execution_context.runner;
    let mut syscall_handler = vm_execution_context.syscall_handler;
```
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 201 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQuCZde5IB02UnTCCyM:-NQuCZdfDuT-Mxdp9X85:bt58rmr) ([raw file](https://github.com/starkware-libs/blockifier/blob/2620211d25d18d5fa2d376818c9b68f05bff3ce0/crates/blockifier/src/execution/execution_utils.rs#L201)):*
> ```XML
>         // When execution starts the stack holds the EP arguments + [ret_fp, ret_pc].
>         .sub_usize(n_total_args + 2)?;
>     vm.mark_address_range_as_accessed(args_ptr, n_total_args)?;
> ```

this seems unrelated...? what's going on here?



_Code quote:_
```XML
    n_total_args: usize,
) -> Result<CallInfo, PostExecutionError> {
    // The arguments and RO segments are touched by the OS and should not be counted as
    // holes, mark them as accessed.
    let args_ptr = runner
        .get_initial_fp()
        .expect("The initial_fp field should be initialized after running the entry point.")
        // When execution starts the stack holds the EP arguments + [ret_fp, ret_pc].
        .sub_usize(n_total_args + 2)?;
    vm.mark_address_range_as_accessed(args_ptr, n_total_args)?;
```
___
*[`crates/native_blockifier/src/py_utils.rs` line 36 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQuAvNg03eYYb0-XY6S:-NQuAvNg03eYYb0-XY6T:b2ni78k) ([raw file](https://github.com/starkware-libs/blockifier/blob/2620211d25d18d5fa2d376818c9b68f05bff3ce0/crates/native_blockifier/src/py_utils.rs#L36)):*
> ```XML
>         // Pad with 12 zeros.
>         let mut bytes = [0; 32];
>         bytes[12..32].copy_from_slice(&address_as_bytes);
> ```

lol


<!-- Sent from Reviewable.io -->

2023-03-19 14:21 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/343)* status: 1 of 13 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQej-3D12XzcIwhzJDc:-NQuDiFy0W8pga_Lrjto:bi1ltcx) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad4d96e3c17a53144ec969a49a61c7bf27feb3f7/crates/native_blockifier/src/py_transaction.rs#L275)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

in the cairo repo, text-searching the regular expression `^[ })]*\?;` has 119 hits, or 167 if you drop the `;` requirement :P
I'm unblocking but I like the trailing `?`
</blockquote></details>

Explain why i couldn't find any reference, it's probably just wrong :grimacing: 
I put the trailing back.
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 150 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQuB_qq8tU_LhmiwOhI:-NQuEluaB2KHohDs4rn9:b-i818y1) ([raw file](https://github.com/starkware-libs/blockifier/blob/2620211d25d18d5fa2d376818c9b68f05bff3ce0/crates/blockifier/src/execution/execution_utils.rs#L150)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Does
```
let VmExecutionContext {
    vm: mut vm,
    runner: mut runner,
    syscall_handler: mut syscall_handler,
    initial_syscall_ptr,
    entry_point_pc,
} = initialize_execution_context(
    &call,
    class_hash,
    state,
    execution_context,
    block_context,
    account_tx_context,
)?;
```
work?
or is there no combination of `mut vm,`/`vm: mut vm` that gets these as mutable?
then you also get `initial_syscall_ptr` and `entry_point_pc` as a variables, don't see why you want some as variables and some not
</blockquote></details>

Reverted, was a result of the rebase branch.
___
*[`crates/blockifier/src/execution/execution_utils.rs` line 201 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQuCZde5IB02UnTCCyM:-NQuEeIg8QwP07S8aZaR:bej95f2) ([raw file](https://github.com/starkware-libs/blockifier/blob/2620211d25d18d5fa2d376818c9b68f05bff3ce0/crates/blockifier/src/execution/execution_utils.rs#L201)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this seems unrelated...? what's going on here?
</blockquote></details>

Didn't touch this, it appeared because the rebase was over a different branch, reverted now.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQekql_1cU_IYM2vXFh:-NQuD0jC6XdMUmdnS30T:b-lrbgfk) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad4d96e3c17a53144ec969a49a61c7bf27feb3f7/crates/blockifier/src/transaction/transactions.rs#L54)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

hmmm... I guess this is a macro candidate but code-compressing can be done later, these functions are siblings it should be easy later
</blockquote></details>

See next comment plz :see_no_evil:  
___
*[`crates/blockifier/src/transaction/transactions.rs` line 60 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQu8TcMBvDyPCvj22Vl:-NQuBcImC1BYJTaP8HQ7:b-ulhgf6) ([raw file](https://github.com/starkware-libs/blockifier/blob/2620211d25d18d5fa2d376818c9b68f05bff3ce0/crates/blockifier/src/transaction/transactions.rs#L60)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ummm isn't this equivalent?
</blockquote></details>

yes :see_no_evil: 
It's even worse, the `let` is also unnecessary, so there is just the call to execute_raw, so the whole function can be deleted and I'll just call raw :facepalm: 
This solve the problem in the duplication comment as well.

For context, initially there was a `log::debug` in that match statement which I had to remove (logging hasn't been merged yet), but even if it was available, the logging might as well be inside `execute_raw`.
___
*[`crates/native_blockifier/src/py_utils.rs` line 36 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQuAvNg03eYYb0-XY6S:-NQuEVsq4S3VZR7dMuzv:b9z6rlo) ([raw file](https://github.com/starkware-libs/blockifier/blob/2620211d25d18d5fa2d376818c9b68f05bff3ce0/crates/native_blockifier/src/py_utils.rs#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

lol
</blockquote></details>

It happens :grimacing: 


<!-- Sent from Reviewable.io -->

2023-03-19 14:24 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 12 of 12 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/343#-:-NQuFMDK-sHzeptzTI2L:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQej-3D12XzcIwhzJDc:-NQuF4tnA6hlYxFZz3l6:b-3y3990) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad4d96e3c17a53144ec969a49a61c7bf27feb3f7/crates/native_blockifier/src/py_transaction.rs#L275)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Explain why i couldn't find any reference, it's probably just wrong :grimacing: 
I put the trailing back.
</blockquote></details>

it's just that, if i see the return type is `Result<...>`, I assume errors are propagated. Rust compiler shouts otherwise. Hidden `?`s make it easier to focus on happy-flow readin


<!-- Sent from Reviewable.io -->

2023-03-19 15:57 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/343)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/343#-NQej-3D12XzcIwhzJDc:-NQu_ULY0qzvO_0i-2CQ:bezc6dr) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad4d96e3c17a53144ec969a49a61c7bf27feb3f7/crates/native_blockifier/src/py_transaction.rs#L275)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

it's just that, if i see the return type is `Result<...>`, I assume errors are propagated. Rust compiler shouts otherwise. Hidden `?`s make it easier to focus on happy-flow readin
</blockquote></details>

I agree, as long as it is readable for other ppl then maybe it's just quirk I have :sweat: 


<!-- Sent from Reviewable.io -->

2023-03-19 15:57 UTC, merged