Consolidate Storage Access in `native_blockifier`.
starkware-libs/blockifier pull request #378
Opened 2023-03-30 11:53 UTC by giladchase

Creating two `Storage` instances is risky, because `papyrus_storage` panics if two storages open in the same location.

The idea is that the `Storage` should be initialized using a context-manager in Python when initializing the Batcher, thus guaranteeing only one instance, which is freed on `finally` using `close()` --- this explicit drop appears necessary, since Rust can't seem to track when the instance is dropped in Python, thus not triggering the drop in Rust.

By setting the fields as None, this guarantees a drop in Rust.

The above has the added benefit of not having to verify alignment, since the execution flow guarantees that the (unique!) `Storage` instance is aligned before it is sent to the executor.

2023-03-30 12:03 UTC, alonh5 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/378)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @elintul, and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/378#-NRmNKIG1CG_RrZpuee1:-NRmNKIG1CG_RrZpuee2:b66sgli) ([raw file](https://github.com/starkware-libs/blockifier/blob/6199c38a4532ffe8e1dbd348f1c43d3cd8f6aafa/crates/native_blockifier/src/py_transaction.rs#L244)):*
> ```XML
>         general_config: &PyAny,
>         block_info: &PyAny,
>         papyrus_storage: &Storage,
> ```

Did you test this works? I remember trying, and it wouldn't let me pass the `Storage` as an argument to the constructor in python.


<!-- Sent from Reviewable.io -->

2023-03-30 12:10 UTC, dorimedini-starkware reviewed
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/378)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)



<!-- Sent from Reviewable.io -->

2023-03-30 17:46 UTC, elintul requested changes
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/378)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 250 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/378#-NRmSdGp5bEU7qwA1fqV:-NRmSdGp5bEU7qwA1fqW:b-vw7xvj) ([raw file](https://github.com/starkware-libs/blockifier/blob/6199c38a4532ffe8e1dbd348f1c43d3cd8f6aafa/crates/native_blockifier/src/py_transaction.rs#L250)):*
> ```XML
>         // Assumption: storage is aligned.
>         let reader = papyrus_storage.reader().clone();
> ```

Are we also planning on closing it from Python?
___
*[`crates/native_blockifier/src/storage.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/378#-NRnbpc1B47PYLuLLd1x:-NRnbpc2-jyaKixYLEWX:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6199c38a4532ffe8e1dbd348f1c43d3cd8f6aafa/crates/native_blockifier/src/storage.rs#L43)):*
> ```XML
> 
>     /// Manually drop the storage reader and writer.
>     /// Python does not drop them instance is no longer live.
> ```





_Suggestion:_
```XML
    /// Manually drops the storage reader and writer.
    /// Python does not necessarily drop them even if instance is no longer live.
```
___
*[`crates/native_blockifier/src/storage.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/378#-NRnc-WA2UoErQwDY88V:-NRnc-WA2UoErQwDY88W:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/6199c38a4532ffe8e1dbd348f1c43d3cd8f6aafa/crates/native_blockifier/src/storage.rs#L132)):*
> ```XML
> }
> 
> // Internal getters, Python should not have access to them, and only use the API.
> ```





_Suggestion:_
```XML
the public API.
```


<!-- Sent from Reviewable.io -->

2023-03-30 17:46 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/378)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-03-31 06:05 UTC, elintul approved these changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/378)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-04-02 05:06 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/378)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/378#-NRmNKIG1CG_RrZpuee1:-NS-J_tIB6g-xx9gRcUH:b-7jyxia) ([raw file](https://github.com/starkware-libs/blockifier/blob/6199c38a4532ffe8e1dbd348f1c43d3cd8f6aafa/crates/native_blockifier/src/py_transaction.rs#L244)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Did you test this works? I remember trying, and it wouldn't let me pass the `Storage` as an argument to the constructor in python.
</blockquote></details>

Yep, passing a `pyclass` by reference always works.
We initially had problems when trying to pass by value, but found out that passing a `pyclass` by value implicitly **clones** the object (so in particular it must implement `Clone`), which is impossible for `Storage`, since its `writer` field is not cloneable (due to `&mut` rules).

The reason why Pyo3 bans "move"s from Python to Rust, is that it can't really make sure that the Python variables moved from aren't used after the move was issued.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 250 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/378#-NRmSdGp5bEU7qwA1fqV:-NS-LVhb-UfXZFZjv6il:b39ff8) ([raw file](https://github.com/starkware-libs/blockifier/blob/6199c38a4532ffe8e1dbd348f1c43d3cd8f6aafa/crates/native_blockifier/src/py_transaction.rs#L250)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Are we also planning on closing it from Python?
</blockquote></details>

Yep, in the "finally" clause of the storage context manager.


<!-- Sent from Reviewable.io -->

2023-04-02 06:41 UTC, giladchase reviewed
Python PR: https://reviewable.io/reviews/starkware-industries/starkware/29270

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/378#-:-NS-gn2v7GnL16-z-K-S:b60pfvq)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @alonh5, @dorimedini-starkware, and @elintul)



<!-- Sent from Reviewable.io -->

2023-04-02 06:45 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/378#-:-NS-hZUy1JB0I6f_1cKu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)



<!-- Sent from Reviewable.io -->

2023-04-02 09:09 UTC, elintul requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/378)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/setup.py` line 6 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/378#-NS0DQP_CDxMGMypLo-_:-NS0DQPa5Ernqa42Agla:byyxydz) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b1562a77b0ce8770969e20bbf37bb88d6562628/crates/native_blockifier/setup.py#L6)):*
> ```Python
> setup(
>     name="native_blockifier",
>     version="0.16.16",
> ```

Can we use the Bazel infra. instead? (And get rid of `pip_native_blockifier` dependency? 


<!-- Sent from Reviewable.io -->

2023-04-02 09:22 UTC, alonh5 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/378)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 244 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/378#-NRmNKIG1CG_RrZpuee1:-NS0GT_wEVpDQjvU0aPY:b-89q77x) ([raw file](https://github.com/starkware-libs/blockifier/blob/6199c38a4532ffe8e1dbd348f1c43d3cd8f6aafa/crates/native_blockifier/src/py_transaction.rs#L244)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Yep, passing a `pyclass` by reference always works.
We initially had problems when trying to pass by value, but found out that passing a `pyclass` by value implicitly **clones** the object (so in particular it must implement `Clone`), which is impossible for `Storage`, since its `writer` field is not cloneable (due to `&mut` rules).

The reason why Pyo3 bans "move"s from Python to Rust, is that it can't really make sure that the Python variables moved from aren't used after the move was issued.
</blockquote></details>

Cool!


<!-- Sent from Reviewable.io -->

2023-04-02 09:52 UTC, dorimedini-starkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/378)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-04-02 12:07 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/378)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-04-02 12:27 UTC, elintul approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/378)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-04-02 13:01 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/378)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/native_blockifier/setup.py` line 6 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/378#-NS0DQP_CDxMGMypLo-_:-NS12lymAAsPyQbcapDz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4b1562a77b0ce8770969e20bbf37bb88d6562628/crates/native_blockifier/setup.py#L6)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we use the Bazel infra. instead? (And get rid of `pip_native_blockifier` dependency? 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-02 13:01 UTC, merged