Bump Papyrus storage to `0772bf3`; SN API to `1e2f66c`.
starkware-libs/blockifier pull request #384
Opened 2023-04-03 04:38 UTC by elintul

Main changes:
- Fields changed in SN API `StateDiff` (previously `declared_classes` now appear in `deprecated_declared_classes`; rest new fields are currently unused).
- `DeclareTransaction` is now an enum; `InvokeTransaction` changed to `InvokeTransactionV1`.
- Many location changes in SN API (especially to `deprecated_contract_class.rs`).

2023-04-03 12:04 UTC, dorimedini-starkware requested changes
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/384)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/test_utils.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/384#-NS4Q5toDGEgXqPs3ext:-NS4Q5toDGEgXqPs3exu:b-i7170b) ([raw file](https://github.com/starkware-libs/blockifier/blob/4af067aca350b9cd131f47b966f77ec722dfbfe6/crates/blockifier/src/test_utils.rs#L9)):*
> ```XML
> use starknet_api::block::{BlockNumber, BlockTimestamp};
> use starknet_api::core::{
>     calculate_contract_address, ChainId, ClassHash, ContractAddress, EntryPointSelector, Nonce,
> ```

what about declare v0? don't we need to support that?
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 295 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/384#-NS5Z_St6RYRrM9FlB6Q:-NS5Z_SuC0fUVgmxCLot:b-u2f9y8) ([raw file](https://github.com/starkware-libs/blockifier/blob/a6758d3cc7d84c5aca5279630aca906160af5c9d/crates/blockifier/src/transaction/account_transaction.rs#L295)):*
> ```XML
>                 // Specifying an entry point selector is not allowed; `__execute__` is called, and
>                 // the inner selector appears in the calldata.
>                 if tx.entry_point_selector.is_some() {
> ```

why is this check removed?
___
*[`crates/native_blockifier/src/errors.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/384#-NS5pbCN4MeAaBrDr5K9:-NS5pbCN4MeAaBrDr5KA:b-gm8a7y) ([raw file](https://github.com/starkware-libs/blockifier/blob/4af067aca350b9cd131f47b966f77ec722dfbfe6/crates/native_blockifier/src/errors.rs#L48)):*
> ```XML
> 
> native_blockifier_errors!(
>     (NativeBlockifierInputError, NativeBlockifierInputError, PyNativeBlockifierInputError),
> ```

this requires a python-side update if this error is new...



_Code quote:_
```XML
(NativeBlockifierInputError, NativeBlockifierInputError, PyNativeBlockifierInputError),
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/384#-NS5qbxn4RWpypxVrf3R:-NS5qbxo389gJ4GbTMuS:b-z0bl3x) ([raw file](https://github.com/starkware-libs/blockifier/blob/4af067aca350b9cd131f47b966f77ec722dfbfe6/crates/native_blockifier/src/py_transaction.rs#L109)):*
> ```XML
> 
>     let version = usize::try_from(account_data_context.version.0)?;
>     match version {
> ```

is this legal rust???



_Code quote:_
```XML
    match version {
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/384#-NS6-3tx7uFOWibFkuhm:-NS6-3tx7uFOWibFkuhn:bc8r18d) ([raw file](https://github.com/starkware-libs/blockifier/blob/4af067aca350b9cd131f47b966f77ec722dfbfe6/crates/native_blockifier/src/py_transaction.rs#L127)):*
> ```XML
>         })),
>         _ => Err(NativeBlockifierInputError::UnsupportedTransactionVersion {
>             tx_type: "DECLARE".to_string(),
> ```

why not use [this enum](https://github.com/starkware-libs/blockifier/blob/main/crates/blockifier/src/transaction/transaction_types.rs#L5) as the type in the error?



_Code quote:_
```XML
tx_type: "DECLARE".to_string(),
```


<!-- Sent from Reviewable.io -->

2023-04-04 08:32 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/384)* status: 12 of 21 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/test_utils.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/384#-NS4Q5toDGEgXqPs3ext:-NSALoyg5n--I5CPUmFO:b-ypuyc0) ([raw file](https://github.com/starkware-libs/blockifier/blob/4af067aca350b9cd131f47b966f77ec722dfbfe6/crates/blockifier/src/test_utils.rs#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what about declare v0? don't we need to support that?
</blockquote></details>

We do, why not?
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 295 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/384#-NS5Z_St6RYRrM9FlB6Q:-NSALrTiAiXG4QKrAoOw:bbc55h6) ([raw file](https://github.com/starkware-libs/blockifier/blob/a6758d3cc7d84c5aca5279630aca906160af5c9d/crates/blockifier/src/transaction/account_transaction.rs#L295)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this check removed?
</blockquote></details>

No need anymore; `InvokeTransactionV1` doesn't have an EP selector field. :D
___
*[`crates/native_blockifier/src/errors.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/384#-NS5pbCN4MeAaBrDr5K9:-NSAM3Yl81gTY6yWwiam:b1rzgth) ([raw file](https://github.com/starkware-libs/blockifier/blob/4af067aca350b9cd131f47b966f77ec722dfbfe6/crates/native_blockifier/src/errors.rs#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this requires a python-side update if this error is new...
</blockquote></details>

I'll do that, thanks!
___
*[`crates/native_blockifier/src/py_transaction.rs` line 109 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/384#-NS5qbxn4RWpypxVrf3R:-NSAM6BoBjbkOTlVtW7N:b-z5lnqh) ([raw file](https://github.com/starkware-libs/blockifier/blob/4af067aca350b9cd131f47b966f77ec722dfbfe6/crates/native_blockifier/src/py_transaction.rs#L109)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this legal rust???
</blockquote></details>

Yeah, why not? Changed though.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/384#-NS6-3tx7uFOWibFkuhm:-NSAMC1G80EVoooO59MI:b-896fja) ([raw file](https://github.com/starkware-libs/blockifier/blob/4af067aca350b9cd131f47b966f77ec722dfbfe6/crates/native_blockifier/src/py_transaction.rs#L127)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not use [this enum](https://github.com/starkware-libs/blockifier/blob/main/crates/blockifier/src/transaction/transaction_types.rs#L5) as the type in the error?
</blockquote></details>

Done!


<!-- Sent from Reviewable.io -->

2023-04-04 08:58 UTC, dorimedini-starkware approved these changes
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/384)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/test_utils.rs` line 266 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/384#-NSATi5n2dqxdZCKTc-7:-NSATi5n2dqxdZCKTc-8:b-p66gm) ([raw file](https://github.com/starkware-libs/blockifier/blob/549d99148967bfc2c0656308a802013640940a70/crates/blockifier/src/test_utils.rs#L266)):*
> ```XML
>     max_fee: Fee,
> ) -> DeclareTransactionV0V1 {
>     DeclareTransactionV0V1 {
> ```

ummmm wat?
what's a declare V0V1?



_Code quote:_
```XML
V0V1
```
___
*[`crates/native_blockifier/src/errors.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/384#-NS5pbCN4MeAaBrDr5K9:-NSAU7N7CUq8pOHPsyIU:blsljn) ([raw file](https://github.com/starkware-libs/blockifier/blob/4af067aca350b9cd131f47b966f77ec722dfbfe6/crates/native_blockifier/src/errors.rs#L48)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I'll do that, thanks!
</blockquote></details>

BTW, once [this](https://reviewable.io/reviews/starkware-libs/blockifier/357#-) is merged, we can actually test all errors are accounted for in python


<!-- Sent from Reviewable.io -->

2023-04-04 09:05 UTC, dorimedini-starkware approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/384)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)



<!-- Sent from Reviewable.io -->

2023-04-04 09:06 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/384)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)

___
*[`crates/native_blockifier/src/errors.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/384#-NS5pbCN4MeAaBrDr5K9:-NSAW2QD9AYekfOv2C7H:bxdh81z) ([raw file](https://github.com/starkware-libs/blockifier/blob/4af067aca350b9cd131f47b966f77ec722dfbfe6/crates/native_blockifier/src/errors.rs#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

BTW, once [this](https://reviewable.io/reviews/starkware-libs/blockifier/357#-) is merged, we can actually test all errors are accounted for in python
</blockquote></details>

On it.


<!-- Sent from Reviewable.io -->

2023-04-04 09:06 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/384#-:-NSAW60yB2p2URimtOYt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-04-04 10:26 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/384)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-04-04 11:18 UTC, merged