Added nice stack trace for VM errors
starkware-libs/blockifier pull request #409
Opened 2023-04-14 18:49 UTC by dorimedini-starkware

2023-04-14 20:12 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/syscalls_test.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT0N3xM93O_tpPMKni3:-NT0N3xM93O_tpPMKni4:bpnkzbm) ([raw file](https://github.com/starkware-libs/blockifier/blob/900062c1ca2c2a78769eba4db5fa83481de39286/crates/blockifier/src/execution/syscalls_test.rs#L216)):*
> ```XML
> Cairo traceback (most recent call last):
> Unknown location (pc=0:6)
> Cairo traceback (most recent call last):
> ```

**TODO**: I don't like this trace.
1. It looks like traces are duplicated; `pc=0:6` is in all three, and `pc=0:2` is in the top two (I think they are dupped).
2. Only one of the three calls is to `OTHER_TEST_CONTRACT` (Address `0x300`); this is the only contract tiny enough to get locations like `pc=0:6` and `pc=0:2` IIUC. Why doesn't `0:2` appear in the third trace, alongside `0:6`?
3. I would expect the `ASSERT_EQ instruction failed: 1 != 0` to appear in the third frame (at `OTHER_TEST_CONTRACT`'s frame). Why is it in the two other frames, and only there?
4. The trace from the outermost call doesn't have a newline where there should be, for some reason... I think this comes from the VM itself:
```
Unknown location (pc=0:622)Unknown location (pc=0:605)
```



_Code quote:_
```XML
        "Error in the called contract ({}):
Error at pc=0:19:
Got an exception while executing a hint: Custom Hint Error: Error at pc=0:2:
An ASSERT_EQ instruction failed: 1 != 0.
Cairo traceback (most recent call last):
Unknown location (pc=0:6)
Cairo traceback (most recent call last):
Unknown location (pc=0:622)Unknown location (pc=0:605)

Error in the called contract ({}):
Error at pc=0:2:
An ASSERT_EQ instruction failed: 1 != 0.
Cairo traceback (most recent call last):
Unknown location (pc=0:6)

Error in the called contract ({}):
Cairo traceback (most recent call last):
Unknown location (pc=0:6)",
        pad_address_to_64(TEST_CONTRACT_ADDRESS),
        pad_address_to_64(TEST_CONTRACT_ADDRESS_2),
        pad_address_to_64(OTHER_TEST_CONTRACT_ADDRESS)
    );
```


<!-- Sent from Reviewable.io -->

2023-04-15 09:44 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/errors.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT3HsWCEBeF4ySIk7wX:-NT3HsWCEBeF4ySIk7wY:btf8877) ([raw file](https://github.com/starkware-libs/blockifier/blob/900062c1ca2c2a78769eba4db5fa83481de39286/crates/blockifier/src/execution/errors.rs#L117)):*
> ```XML
>     /// Unwrap inner VM exception and return it as a string. If unsuccessful, returns the debug
>     /// string of self.
>     pub fn try_to_vm_trace(&self) -> String {
> ```

Shouldn't this be a (backtracked) recursion here somewhere?
That is, if there are `n` levels of VirtualMachineError (say in a nested call of depth `n`), then it should recurse into them and collect the prints in each level?


<!-- Sent from Reviewable.io -->

2023-04-15 15:05 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/execution/errors.rs` line 117 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT3HsWCEBeF4ySIk7wX:-NT4RW6zBvYfTWiIMFZH:bj9a98w) ([raw file](https://github.com/starkware-libs/blockifier/blob/900062c1ca2c2a78769eba4db5fa83481de39286/crates/blockifier/src/execution/errors.rs#L117)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Shouldn't this be a (backtracked) recursion here somewhere?
That is, if there are `n` levels of VirtualMachineError (say in a nested call of depth `n`), then it should recurse into them and collect the prints in each level?
</blockquote></details>

Each call raises it's own VirtualMachineError, which I append in a vector in the execution context struct. This function is just a stringification of an individual error; the `error_trace` function collects the prints


<!-- Sent from Reviewable.io -->

2023-04-16 11:53 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/execution/syscalls_test.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT0N3xM93O_tpPMKni3:-NT8uGTrCYejsr3pZvX-:b-ehkes7) ([raw file](https://github.com/starkware-libs/blockifier/blob/900062c1ca2c2a78769eba4db5fa83481de39286/crates/blockifier/src/execution/syscalls_test.rs#L216)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

**TODO**: I don't like this trace.
1. It looks like traces are duplicated; `pc=0:6` is in all three, and `pc=0:2` is in the top two (I think they are dupped).
2. Only one of the three calls is to `OTHER_TEST_CONTRACT` (Address `0x300`); this is the only contract tiny enough to get locations like `pc=0:6` and `pc=0:2` IIUC. Why doesn't `0:2` appear in the third trace, alongside `0:6`?
3. I would expect the `ASSERT_EQ instruction failed: 1 != 0` to appear in the third frame (at `OTHER_TEST_CONTRACT`'s frame). Why is it in the two other frames, and only there?
4. The trace from the outermost call doesn't have a newline where there should be, for some reason... I think this comes from the VM itself:
```
Unknown location (pc=0:622)Unknown location (pc=0:605)
```
</blockquote></details>

OK! this looks better now... and the parsing is as expected:
```
In [1]: from starkware.cairo.lang.compiler.program import Program

In [2]: import json

In [3]: with open("../blockifier/crates/blockifier/feature_contracts/compiled/other_test_contract_compiled.json", "r") as other_contract_file:
   ...:     other_test_program = Program.load(json.load(other_contract_file)["program"])
   ...: 

In [4]: with open("../blockifier/crates/blockifier/feature_contracts/compiled/test_contract_compiled.json", "r") as other_contract_file:
   ...:     test_program = Program.load(json.load(other_contract_file)["program"])
   ...: 

In [5]: contracts = {0x100: test_program, 0x200: test_program, 0x300: other_test_program}

In [6]: from starkware.starknet.cli.reconstruct_starknet_traceback import reconstruct_starknet_traceback

In [7]: traceback_txt = """
   ...: Error in the called contract (0x100):
   ...: Error at pc=0:19: Got an exception while executing a hint. Cairo traceback (most recent call last):
   ...: Unknown location (pc=0:622)
   ...: Unknown location (pc=0:605)
   ...: 
   ...: Error in the called contract (0x200):
   ...: Error at pc=0:19: Got an exception while executing a hint. Cairo traceback (most recent call last):
   ...: Unknown location (pc=0:622)
   ...: Unknown location (pc=0:605)
   ...: 
   ...: Error in the called contract (0x300):
   ...: Error at pc=0:2: An ASSERT_EQ instruction failed: 1 != 0. Cairo traceback (most recent call last):
   ...: Unknown location (pc=0:6)"""

In [8]: print(reconstruct_starknet_traceback(contracts, traceback_txt))

Error in the called contract (0x100):
/home/dori/.local/lib/python3.9/site-packages/starkware/starknet/common/syscalls.cairo:56:23: Error at pc=0:19:
    let syscall_ptr = syscall_ptr + CallContract.SIZE;
                      ^*****************************^ Got an exception while executing a hint. Cairo traceback (most recent call last):
crates/blockifier/feature_contracts/test_contract.cairo:122:6
crates/blockifier/feature_contracts/test_contract.cairo:125:48

Error in the called contract (0x200):
/home/dori/.local/lib/python3.9/site-packages/starkware/starknet/common/syscalls.cairo:56:23: Error at pc=0:19:
    let syscall_ptr = syscall_ptr + CallContract.SIZE;
                      ^*****************************^ Got an exception while executing a hint. Cairo traceback (most recent call last):
crates/blockifier/feature_contracts/test_contract.cairo:122:6
crates/blockifier/feature_contracts/test_contract.cairo:125:48

Error in the called contract (0x300):
crates/blockifier/feature_contracts/other_test_contract.cairo:5:5: Error at pc=0:2: An ASSERT_EQ instruction failed: 1 != 0. Cairo traceback (most recent call last):
crates/blockifier/feature_contracts/other_test_contract.cairo:4:6
```


<!-- Sent from Reviewable.io -->

2023-04-16 12:03 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/errors.rs` line 128 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT8wXw27tysf5FaVQln:-NT8wXw27tysf5FaVQlo:b-isumok) ([raw file](https://github.com/starkware-libs/blockifier/blob/26e27b6d7433ca848bdbdcf32c3b05446795bcd8/crates/blockifier/src/execution/errors.rs#L128)):*
> ```XML
>                 // If inner error is a hint error, show generic text.
>                 match &vm_exception.inner_exc {
>                     VirtualMachineError::Hint(_, _) => {
> ```

@giladchase any idea how I can be certain that this is the only case where I need to filter the inner error text? or what the check should be?



_Code quote:_
```XML
VirtualMachineError::Hint(_, _)
```


<!-- Sent from Reviewable.io -->

2023-04-16 15:50 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/execution/errors.rs` line 123 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT9kSUZ2AmzQKBA9egE:-NT9kSUZ2AmzQKBA9egF:b7x6zzw) ([raw file](https://github.com/starkware-libs/blockifier/blob/984e587929a1bb2d1fc80d17e630c465bdb9ed3d/crates/blockifier/src/execution/errors.rs#L123)):*
> ```XML
>     /// Unwrap inner VM exception and return it as a string. If unsuccessful, returns the debug
>     /// string of self.
>     pub fn try_to_vm_trace(&self) -> String {
> ```

this function is terrible; and I don't know if it will be forward-stable with releases of cairo-rs.
@elintul do you think I should show LC this parsing function, and discuss some proper API to stack traces correctly?



_Code quote:_
```XML
try_to_vm_trace
```


<!-- Sent from Reviewable.io -->

2023-04-16 15:52 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT9kk9Q9agXFPYag-ys:-NT9kk9Q9agXFPYag-yt:b-nxzyg7) (no related file):*
Sorry for big PR... it contains:
1. Single-error formatting (`try_to_vm_trace`)
2. Error stack combination (`error_stack`)
3. Push-format-carry or error in the call to `execute_entry_point_call`
4. Extra test contract for testing
5. Extra deployment of two test contracts (to get different addresses in the stack...)
6. Stack trace test

___


<!-- Sent from Reviewable.io -->

2023-04-16 15:52 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT9kk9Q9agXFPYag-ys:-NT9l9gP5c2eQe_4aLxa:b9607vt) (no related file):*
> Push-format-carry or error in
*Push-format-carry *on* error in

___


<!-- Sent from Reviewable.io -->

2023-04-16 16:00 UTC, elintul requested changes
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: 2 of 6 files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT9mwZ98CgSG6kuSc7S:-NT9mwZ98CgSG6kuSc7T:bc11tx2) (no related file):*
Can I please see an example of the formatted output? :D

___
___
*[`crates/blockifier/feature_contracts/other_test_contract.cairo` line 2 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT9mMhi-ATy7u4EDFbj:-NT9mMhi-ATy7u4EDFbk:b7r2l4v) ([raw file](https://github.com/starkware-libs/blockifier/blob/984e587929a1bb2d1fc80d17e630c465bdb9ed3d/crates/blockifier/feature_contracts/other_test_contract.cairo#L2)):*
> ```Cairo
> %lang starknet
> ```

Why not initialize two instances of the existing test contract in the state?
___
*[`crates/blockifier/feature_contracts/compiled/other_test_contract_compiled.json` line 1 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT9mNs52P9VaWQmxjjo:-NT9mNs52P9VaWQmxjjp:b-jcyqii) ([raw file](https://github.com/starkware-libs/blockifier/blob/984e587929a1bb2d1fc80d17e630c465bdb9ed3d/crates/blockifier/feature_contracts/compiled/other_test_contract_compiled.json#L1)):*
> ```JSON
> {
> ```

Damn it... so many lines...
___
*[`crates/blockifier/src/execution/entry_point.rs` line 64 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT9mciT8ouYrlbBZaEf:-NT9mciT8ouYrlbBZaEg:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/984e587929a1bb2d1fc80d17e630c465bdb9ed3d/crates/blockifier/src/execution/entry_point.rs#L64)):*
> ```XML
> 
> impl ExecutionContext {
>     /// Combine individual errors into a single stack trace string, with contract addresses printed
> ```





_Suggestion:_
```XML
Combines
```
___
*[`crates/blockifier/src/execution/entry_point.rs` line 71 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT9mqRH9eAGaV9lEbTj:-NT9mqRH9eAGaV9lEbTk:b-jvkpei) ([raw file](https://github.com/starkware-libs/blockifier/blob/984e587929a1bb2d1fc80d17e630c465bdb9ed3d/crates/blockifier/src/execution/entry_point.rs#L71)):*
> ```XML
>             frame_errors.push(
>                 format!("Error in the called contract ({}):\n", contract_address.0.key())
>                     + trace_string,
> ```

Is this concatenation? Why not also format into the same string?



_Code quote:_
```XML
+ trace_string
```


<!-- Sent from Reviewable.io -->

2023-04-16 17:27 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT9mwZ98CgSG6kuSc7S:-NTA5mAsBzxkYUp2hCbx:by7vf34) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can I please see an example of the formatted output? :D
</blockquote></details>

tagged you in the relevant comment in this PR (in syscalls_test)

___
___
*[`crates/blockifier/feature_contracts/other_test_contract.cairo` line 2 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT9mMhi-ATy7u4EDFbj:-NTA5DR--Vs1Mx_P1idl:bzhvlma) ([raw file](https://github.com/starkware-libs/blockifier/blob/984e587929a1bb2d1fc80d17e630c465bdb9ed3d/crates/blockifier/feature_contracts/other_test_contract.cairo#L2)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not initialize two instances of the existing test contract in the state?
</blockquote></details>

So I can tell (by running the reconstruction script) that the correct class hash was used for the error.
If they are all the same contract, I won't detect (in the test) the case where all pc locations are from the initial contract, or things like that
___
*[`crates/blockifier/feature_contracts/compiled/other_test_contract_compiled.json` line 1 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT9mNs52P9VaWQmxjjo:-NTA57IuA-ETn-S9wzZ0:bdo2llz) ([raw file](https://github.com/starkware-libs/blockifier/blob/984e587929a1bb2d1fc80d17e630c465bdb9ed3d/crates/blockifier/feature_contracts/compiled/other_test_contract_compiled.json#L1)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Damn it... so many lines...
</blockquote></details>

it's verified by the compiler regression test... sorry, should have marked as reviewed
___
*[`crates/blockifier/src/execution/syscalls_test.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT0N3xM93O_tpPMKni3:-NTA5gu262XQgOaiieqg:b-2pmlkk) ([raw file](https://github.com/starkware-libs/blockifier/blob/900062c1ca2c2a78769eba4db5fa83481de39286/crates/blockifier/src/execution/syscalls_test.rs#L216)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

OK! this looks better now... and the parsing is as expected:
```
In [1]: from starkware.cairo.lang.compiler.program import Program

In [2]: import json

In [3]: with open("../blockifier/crates/blockifier/feature_contracts/compiled/other_test_contract_compiled.json", "r") as other_contract_file:
   ...:     other_test_program = Program.load(json.load(other_contract_file)["program"])
   ...: 

In [4]: with open("../blockifier/crates/blockifier/feature_contracts/compiled/test_contract_compiled.json", "r") as other_contract_file:
   ...:     test_program = Program.load(json.load(other_contract_file)["program"])
   ...: 

In [5]: contracts = {0x100: test_program, 0x200: test_program, 0x300: other_test_program}

In [6]: from starkware.starknet.cli.reconstruct_starknet_traceback import reconstruct_starknet_traceback

In [7]: traceback_txt = """
   ...: Error in the called contract (0x100):
   ...: Error at pc=0:19: Got an exception while executing a hint. Cairo traceback (most recent call last):
   ...: Unknown location (pc=0:622)
   ...: Unknown location (pc=0:605)
   ...: 
   ...: Error in the called contract (0x200):
   ...: Error at pc=0:19: Got an exception while executing a hint. Cairo traceback (most recent call last):
   ...: Unknown location (pc=0:622)
   ...: Unknown location (pc=0:605)
   ...: 
   ...: Error in the called contract (0x300):
   ...: Error at pc=0:2: An ASSERT_EQ instruction failed: 1 != 0. Cairo traceback (most recent call last):
   ...: Unknown location (pc=0:6)"""

In [8]: print(reconstruct_starknet_traceback(contracts, traceback_txt))

Error in the called contract (0x100):
/home/dori/.local/lib/python3.9/site-packages/starkware/starknet/common/syscalls.cairo:56:23: Error at pc=0:19:
    let syscall_ptr = syscall_ptr + CallContract.SIZE;
                      ^*****************************^ Got an exception while executing a hint. Cairo traceback (most recent call last):
crates/blockifier/feature_contracts/test_contract.cairo:122:6
crates/blockifier/feature_contracts/test_contract.cairo:125:48

Error in the called contract (0x200):
/home/dori/.local/lib/python3.9/site-packages/starkware/starknet/common/syscalls.cairo:56:23: Error at pc=0:19:
    let syscall_ptr = syscall_ptr + CallContract.SIZE;
                      ^*****************************^ Got an exception while executing a hint. Cairo traceback (most recent call last):
crates/blockifier/feature_contracts/test_contract.cairo:122:6
crates/blockifier/feature_contracts/test_contract.cairo:125:48

Error in the called contract (0x300):
crates/blockifier/feature_contracts/other_test_contract.cairo:5:5: Error at pc=0:2: An ASSERT_EQ instruction failed: 1 != 0. Cairo traceback (most recent call last):
crates/blockifier/feature_contracts/other_test_contract.cairo:4:6
```
</blockquote></details>

@elintul here


<!-- Sent from Reviewable.io -->

2023-04-16 17:34 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/errors.rs` line 123 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT9kSUZ2AmzQKBA9egE:-NTA7A_z4UT0yTctBdAH:bawzrv9) ([raw file](https://github.com/starkware-libs/blockifier/blob/984e587929a1bb2d1fc80d17e630c465bdb9ed3d/crates/blockifier/src/execution/errors.rs#L123)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this function is terrible; and I don't know if it will be forward-stable with releases of cairo-rs.
@elintul do you think I should show LC this parsing function, and discuss some proper API to stack traces correctly?
</blockquote></details>

Maybe we need to define this specific type of custom hint (anything that "opens a new frame", i.e. call_contract or library_call (right?) may need it's own API between blockifier and cairo-rs...?)


<!-- Sent from Reviewable.io -->

2023-04-16 18:55 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/errors.rs` line 128 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT8wXw27tysf5FaVQln:-NTAPsqS0v2PTu6X0uho:bc0dmmf) ([raw file](https://github.com/starkware-libs/blockifier/blob/26e27b6d7433ca848bdbdcf32c3b05446795bcd8/crates/blockifier/src/execution/errors.rs#L128)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@giladchase any idea how I can be certain that this is the only case where I need to filter the inner error text? or what the check should be?
</blockquote></details>

nvm... no longer relevant
___
*[`crates/blockifier/src/execution/errors.rs` line 123 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT9kSUZ2AmzQKBA9egE:-NTAPpTq9JjfGIEPzGn4:b-zge5tr) ([raw file](https://github.com/starkware-libs/blockifier/blob/984e587929a1bb2d1fc80d17e630c465bdb9ed3d/crates/blockifier/src/execution/errors.rs#L123)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Maybe we need to define this specific type of custom hint (anything that "opens a new frame", i.e. call_contract or library_call (right?) may need it's own API between blockifier and cairo-rs...?)
</blockquote></details>

nvm... I like it now


<!-- Sent from Reviewable.io -->

2023-04-16 19:13 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 114 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NTARumzCVcFlZdCswGj:-NTARumzCVcFlZdCswGk:b-vspexg) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd2c93293e3d5793638a87979fe97ec52dade9be/crates/blockifier/src/execution/entry_point.rs#L114)):*
> ```XML
>             // On VM error, pack the stack trace into the propagated error.
>             EntryPointExecutionError::VirtualMachineExecutionError(error) => {
>                 execution_context.error_stack.push((storage_address, error.try_to_vm_trace()));
> ```

this wastes memory and is probably slow... we don't need a `VirtualMachineExecutionErrorWithTrace` in every frame, with the entire stack string. We only need the error object in the outermost call to carry the trace.
Should I add this in each of validate/execute_transfer_fee? as another error layer?
```
#[derive(Debug, Error)]
pub enum TracedTransactionExecutionError {
    #[error("{trace}")]
    Error {
        trace: String,
        #[source]
        source: TransactionExecutionError
    }
}
```



_Code quote:_
```XML
        .map_err(|error| match error {
            // On VM error, pack the stack trace into the propagated error.
            EntryPointExecutionError::VirtualMachineExecutionError(error) => {
                execution_context.error_stack.push((storage_address, error.try_to_vm_trace()));
                EntryPointExecutionError::VirtualMachineExecutionErrorWithTrace {
                    trace: execution_context.error_trace(),
                    source: error,
                }
            }
            other_error => other_error,
        })
```


<!-- Sent from Reviewable.io -->

2023-04-17 03:40 UTC, elintul requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/feature_contracts/other_test_contract.cairo` line 2 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT9mMhi-ATy7u4EDFbj:-NTCHo_t80qbb5hX6N3p:b-pmvjii) ([raw file](https://github.com/starkware-libs/blockifier/blob/984e587929a1bb2d1fc80d17e630c465bdb9ed3d/crates/blockifier/feature_contracts/other_test_contract.cairo#L2)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

So I can tell (by running the reconstruction script) that the correct class hash was used for the error.
If they are all the same contract, I won't detect (in the test) the case where all pc locations are from the initial contract, or things like that
</blockquote></details>

Got it. Can't you use other existing contracts? We have some account contracts.


<!-- Sent from Reviewable.io -->

2023-04-17 12:04 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: 2 of 6 files reviewed, 4 unresolved discussions

___
*[`crates/blockifier/src/execution/entry_point.rs` line 114 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NTARumzCVcFlZdCswGj:-NTDgEK65G_Hna19i8td:b-832vlm) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd2c93293e3d5793638a87979fe97ec52dade9be/crates/blockifier/src/execution/entry_point.rs#L114)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this wastes memory and is probably slow... we don't need a `VirtualMachineExecutionErrorWithTrace` in every frame, with the entire stack string. We only need the error object in the outermost call to carry the trace.
Should I add this in each of validate/execute_transfer_fee? as another error layer?
```
#[derive(Debug, Error)]
pub enum TracedTransactionExecutionError {
    #[error("{trace}")]
    Error {
        trace: String,
        #[source]
        source: TransactionExecutionError
    }
}
```
</blockquote></details>

Talked to Sergei, they are prepared to risk performance hit for this trace. We can keep this like this now, I'll add a TODO to wrap top level error


<!-- Sent from Reviewable.io -->

2023-04-17 12:19 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/feature_contracts/other_test_contract.cairo` line 2 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT9mMhi-ATy7u4EDFbj:-NTE6juD5OtzHD8eIcd_:b-yj2041) ([raw file](https://github.com/starkware-libs/blockifier/blob/984e587929a1bb2d1fc80d17e630c465bdb9ed3d/crates/blockifier/feature_contracts/other_test_contract.cairo#L2)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Got it. Can't you use other existing contracts? We have some account contracts.
</blockquote></details>

no need for an account contract; I need a contract with an external endpoint I can call that always fails.
The only one I see is the "security_test_contract", I'll use it, but it will require a bit of moving around in the test_utils area.


<!-- Sent from Reviewable.io -->

2023-04-17 13:28 UTC, giladchase requested changes
> Reviewed 1 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: 1 of 7 files reviewed, 8 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/errors.rs` line 128 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT8wXw27tysf5FaVQln:-NTEO2NJ9op8L8Zk90tT:bebv7bu) ([raw file](https://github.com/starkware-libs/blockifier/blob/26e27b6d7433ca848bdbdcf32c3b05446795bcd8/crates/blockifier/src/execution/errors.rs#L128)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

nvm... no longer relevant
</blockquote></details>

Sorry :see_no_evil: 
___
*[`crates/blockifier/src/execution/errors.rs` line 113 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NTEMqP3Cz5hLWKI9DSZ:-NTEMqP44B7rSszVZiOE:brlii0i) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3a4f7117fe503d4af245960c08f8d287bd00b16/crates/blockifier/src/execution/errors.rs#L113)):*
> ```XML
>     #[error("{trace}")]
>     VirtualMachineExecutionErrorWithTrace {
>         trace: String,
> ```

Is this a good name for this?
`thiserror` assumed it is called `backtrace`, will calling this `backtrace` clash with `thiserror` or create problems? 

I'm asking just to be sure we're not clashing with reserved keyword, or alternatively, if we _should_ be using said reserved keywords.



_Code quote:_
```XML
trace
```
___
*[`crates/blockifier/src/execution/errors.rs` line 119 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NTELnq4AJateBjB2Yva:-NTELnq4AJateBjB2Yvb:bxtavz5) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3a4f7117fe503d4af245960c08f8d287bd00b16/crates/blockifier/src/execution/errors.rs#L119)):*
> ```XML
> }
> 
> impl VirtualMachineExecutionError {
> ```

Plz move right after the definition of `VirtualMachineExecutionError`. 



_Code quote:_
```XML
impl VirtualMachineExecutionError {
```
___
*[`crates/blockifier/src/execution/errors.rs` line 121 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NTENSka7HY91kTXSwFc:-NTENSkb7OV7RaszH8bm:b-a3wgm3) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3a4f7117fe503d4af245960c08f8d287bd00b16/crates/blockifier/src/execution/errors.rs#L121)):*
> ```XML
> impl VirtualMachineExecutionError {
>     /// Unwrap inner VM exception and return it as a string. If this is a call_contract exception,
>     /// the inner error (inner call errors) do not appear in the string.
> ```

will not? :thinking: 



_Code quote:_
```XML
do not
```
___
*[`crates/blockifier/src/execution/errors.rs` line 125 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NTENhruA3ymlBw81YMW:-NTENhruA3ymlBw81YMX:b-zb0ksg) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3a4f7117fe503d4af245960c08f8d287bd00b16/crates/blockifier/src/execution/errors.rs#L125)):*
> ```XML
>         match self {
>             VirtualMachineExecutionError::CairoRunError(
>                 cairo_vm_errors::cairo_run_errors::CairoRunError::VmException(vm_exception),
> ```

A bit too long, maybe `use` it `as CairoVmException`?



_Code quote:_
```XML
  cairo_vm_errors::cairo_run_errors::CairoRunError::VmException
```
___
*[`crates/blockifier/src/execution/syscalls_test.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT0N3xM93O_tpPMKni3:-NTEMcl1DZ0jZq-6T8sA:b-u5u8he) ([raw file](https://github.com/starkware-libs/blockifier/blob/900062c1ca2c2a78769eba4db5fa83481de39286/crates/blockifier/src/execution/syscalls_test.rs#L216)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@elintul here
</blockquote></details>

Noice!
MUCH better than before!


<!-- Sent from Reviewable.io -->

2023-04-17 13:43 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/execution/errors.rs` line 113 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NTEMqP3Cz5hLWKI9DSZ:-NTEOy1t4E17bTdw3_5H:badh4vv) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3a4f7117fe503d4af245960c08f8d287bd00b16/crates/blockifier/src/execution/errors.rs#L113)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Is this a good name for this?
`thiserror` assumed it is called `backtrace`, will calling this `backtrace` clash with `thiserror` or create problems? 

I'm asking just to be sure we're not clashing with reserved keyword, or alternatively, if we _should_ be using said reserved keywords.
</blockquote></details>

I think we shouldn't use reserved keywords; thiserror may be friends with the *rust* backtrace one day. This trace refers to the starknet call stack trace.
Also, this error variant itself is temporary (see my TODO)
___
*[`crates/blockifier/src/execution/errors.rs` line 119 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NTELnq4AJateBjB2Yva:-NTEQ8EhDQAzhVHVfd9e:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3a4f7117fe503d4af245960c08f8d287bd00b16/crates/blockifier/src/execution/errors.rs#L119)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Plz move right after the definition of `VirtualMachineExecutionError`. 
</blockquote></details>

Done.



_Code quote:_
```XML
impl VirtualMachineExecutionError
```
___
*[`crates/blockifier/src/execution/errors.rs` line 121 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NTENSka7HY91kTXSwFc:-NTEQChY3H3b6GGuvgAy:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3a4f7117fe503d4af245960c08f8d287bd00b16/crates/blockifier/src/execution/errors.rs#L121)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

will not? :thinking: 
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/errors.rs` line 125 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NTENhruA3ymlBw81YMW:-NTEQdrxDOd-UfEUFqBD:b-dcn311) ([raw file](https://github.com/starkware-libs/blockifier/blob/c3a4f7117fe503d4af245960c08f8d287bd00b16/crates/blockifier/src/execution/errors.rs#L125)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

A bit too long, maybe `use` it `as CairoVmException`?
</blockquote></details>

Done. dropped the `vm_` prefix in the var name to get two less lines :P



_Code quote:_
```XML
cairo_vm_errors::cairo_run_errors::CairoRunError::VmException
```
___
*[`crates/blockifier/src/execution/syscalls_test.rs` line 216 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NT0N3xM93O_tpPMKni3:-NTEQk6l-uUgTMH38OmQ:boclpdb) ([raw file](https://github.com/starkware-libs/blockifier/blob/900062c1ca2c2a78769eba4db5fa83481de39286/crates/blockifier/src/execution/syscalls_test.rs#L216)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Noice!
MUCH better than before!
</blockquote></details>

YASSSIR


<!-- Sent from Reviewable.io -->

2023-04-18 07:43 UTC, giladchase approved these changes
> Reviewed 1 of 3 files at r7, 5 of 6 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 114 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NTARumzCVcFlZdCswGj:-NTIGtni24tIW2R49VoK:bqrmis7) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd2c93293e3d5793638a87979fe97ec52dade9be/crates/blockifier/src/execution/entry_point.rs#L114)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Talked to Sergei, they are prepared to risk performance hit for this trace. We can keep this like this now, I'll add a TODO to wrap top level error
</blockquote></details>

Ya let's add it anyway, we'll soon see if this is really hitting us once we finish integrating the benchmarks into the repo.
___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 13 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NTIISKxAcJcQQVmLFwa:-NTIISKxAcJcQQVmLFwb:bdtclgk) ([raw file](https://github.com/starkware-libs/blockifier/blob/a24048a7e67366e32a101276982a25127065c1fe/crates/blockifier/src/execution/entry_point_test.rs#L13)):*
> ```XML
> use crate::abi::abi_utils::{get_storage_var_address, selector_from_name};
> use crate::execution::entry_point::{CallEntryPoint, CallExecution, CallInfo, Retdata};
> use crate::retdata;
> ```

What happened in this file? I can't quite follow :sweat_smile: 
In particular, how does it relate to the rest of the PR?
___
*[`crates/blockifier/src/execution/errors.rs` line 6 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NTIJ8KU9vsZCp4D8DPN:-NTIJ8KU9vsZCp4D8DPO:bs07w3s) ([raw file](https://github.com/starkware-libs/blockifier/blob/bf4a4de2e3664a2baf2ef624eb1614ff02d23e33/crates/blockifier/src/execution/errors.rs#L6)):*
> ```XML
> use cairo_vm::vm::errors::memory_errors::MemoryError;
> use cairo_vm::vm::errors::runner_errors::RunnerError;
> use cairo_vm::vm::errors::vm_errors::VirtualMachineError;
> ```

Danke.



_Code quote:_
```XML
use cairo_vm::vm::errors::cairo_run_errors::CairoRunError;
use cairo_vm::vm::errors::hint_errors::HintError;
use cairo_vm::vm::errors::memory_errors::MemoryError;
use cairo_vm::vm::errors::runner_errors::RunnerError;
use cairo_vm::vm::errors::vm_errors::VirtualMachineError;
```


<!-- Sent from Reviewable.io -->

2023-04-18 07:46 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 13 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NTIISKxAcJcQQVmLFwa:-NTIJYOIAi1btgUgcatD:b-ay0gjs) ([raw file](https://github.com/starkware-libs/blockifier/blob/a24048a7e67366e32a101276982a25127065c1fe/crates/blockifier/src/execution/entry_point_test.rs#L13)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

What happened in this file? I can't quite follow :sweat_smile: 
In particular, how does it relate to the rest of the PR?
</blockquote></details>

previously, two different types of tests ("security" and non-security) where initialized with different states: both had a deployed contract at address `TEST_CONTRACT_ADDRESS`, but security tests deployed a different implementation (same dummy class hash was used).
This is why there were two different test-state-init functions.
Now, I simply deploy both test classes, at different addresses, to be used by any test that needs them. Simpler, and allows me to use *both contracts* in my stack trace test.


<!-- Sent from Reviewable.io -->

2023-04-18 07:48 UTC, giladchase approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/entry_point_test.rs` line 13 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/409#-NTIISKxAcJcQQVmLFwa:-NTIKUoZ1HkQ0Httqa5G:b-fay6y5) ([raw file](https://github.com/starkware-libs/blockifier/blob/a24048a7e67366e32a101276982a25127065c1fe/crates/blockifier/src/execution/entry_point_test.rs#L13)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

previously, two different types of tests ("security" and non-security) where initialized with different states: both had a deployed contract at address `TEST_CONTRACT_ADDRESS`, but security tests deployed a different implementation (same dummy class hash was used).
This is why there were two different test-state-init functions.
Now, I simply deploy both test classes, at different addresses, to be used by any test that needs them. Simpler, and allows me to use *both contracts* in my stack trace test.
</blockquote></details>

Got it, tnx for explaining :)


<!-- Sent from Reviewable.io -->

2023-04-18 07:55 UTC, dorimedini-starkware reviewed
> Dismissed @elintul from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2023-04-18 07:56 UTC, dorimedini-starkware reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409#-:-NTIMHv6CyvTuZmxkUbC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2023-04-18 07:58 UTC, giladchase approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2023-04-18 07:58 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/409#-:-NTIMorp6dc9Z-CzUwRq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2023-04-18 07:59 UTC, merged