Use `add` callback instead of `add_weights` + simplify
starkware-libs/blockifier pull request #426
Opened 2023-04-24 13:37 UTC by giladchase

- No need to put everything inside `with_gil` which was only used for the `kwargs` object, which isn't essential anyway, so just removed it to be less surprising.
- Made it clearer as to what is returned and when.

Note: this is currently preserving the invariant of returning Ok even if execution failed (but transaction is aborted).

Python PR: https://reviewable.io/reviews/starkware-industries/starkware/29623

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/426)

2023-04-27 07:50 UTC, elintul requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/426)* status: all files reviewed, 2 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/426#-NU0fWUh59VpRdLi_CGW:-NU0fWUh59VpRdLi_CGX:b-dobu10) ([raw file](https://github.com/starkware-libs/blockifier/blob/6a617350c72a9a5354f6975dd616542043231fee/crates/native_blockifier/src/py_transaction.rs#L291)):*
> ```XML
> 
>             let py_tx_execution_info: PyTransactionExecutionInfo =
>                 tx_execution_result.unwrap().into();
> ```

Plan to leave that?



_Code quote:_
```XML
.unwrap().into()
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/426#-NU0faXjAvwMpPsk10ZW:-NU0faXjAvwMpPsk10ZX:b6gezq3) ([raw file](https://github.com/starkware-libs/blockifier/blob/6a617350c72a9a5354f6975dd616542043231fee/crates/native_blockifier/src/py_transaction.rs#L294)):*
> ```XML
>             let args = (py_tx_execution_info.clone(),);
>             // This is a callback to Python code.
>             let has_enough_room_for_tx = enough_room_for_tx.call1(args);
> ```

Weird name... where is this method coming from?



_Code quote:_
```XML
call1
```


<!-- Sent from Reviewable.io -->

2023-04-30 07:13 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/426)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/426#-NU0fWUh59VpRdLi_CGW:-NUFw27X3ABT8XSTTQzK:b-nmym6v) ([raw file](https://github.com/starkware-libs/blockifier/blob/6a617350c72a9a5354f6975dd616542043231fee/crates/native_blockifier/src/py_transaction.rs#L291)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Plan to leave that?
</blockquote></details>

Not sure what i was thinking :thinking: 
Fixed, thanks!
___
*[`crates/native_blockifier/src/py_transaction.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/426#-NU0faXjAvwMpPsk10ZW:-NUFv52G1WTP_jheqxJY:brqy0j) ([raw file](https://github.com/starkware-libs/blockifier/blob/6a617350c72a9a5354f6975dd616542043231fee/crates/native_blockifier/src/py_transaction.rs#L294)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Weird name... where is this method coming from?
</blockquote></details>

For sure, it's a [PYO3 function](https://pyo3.rs/v0.18.3/python_from_rust), and I guess they aren't that good with naming?
They have:
```
call0(...) // no args
call1(...) // with args
call(...) // with args and kwargs
call_method(...) // call method (add a self arg)
```
I guess they are needed because each has a difference signature and cause Rust doesn't have default args?


<!-- Sent from Reviewable.io -->

2023-04-30 10:15 UTC, elintul requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/426)* status: all files reviewed, 5 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 291 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/426#-NU0fWUh59VpRdLi_CGW:-NUGeJ7K6o2QfIBzFNyg:b32vhw) ([raw file](https://github.com/starkware-libs/blockifier/blob/6a617350c72a9a5354f6975dd616542043231fee/crates/native_blockifier/src/py_transaction.rs#L291)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Not sure what i was thinking :thinking: 
Fixed, thanks!
</blockquote></details>

:)
___
*[`crates/native_blockifier/src/py_transaction.rs` line 294 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/426#-NU0faXjAvwMpPsk10ZW:-NUGdn48AEGfzSBJgKAP:b-ekt87h) ([raw file](https://github.com/starkware-libs/blockifier/blob/6a617350c72a9a5354f6975dd616542043231fee/crates/native_blockifier/src/py_transaction.rs#L294)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

For sure, it's a [PYO3 function](https://pyo3.rs/v0.18.3/python_from_rust), and I guess they aren't that good with naming?
They have:
```
call0(...) // no args
call1(...) // with args
call(...) // with args and kwargs
call_method(...) // call method (add a self arg)
```
I guess they are needed because each has a difference signature and cause Rust doesn't have default args?
</blockquote></details>

חחחחחחחחחחחחחחחחחחח וואו
___
*[`crates/native_blockifier/src/py_transaction.rs` line 281 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/426#-NUGdGoF4E1sSCByGUA7:-NUGdGoF4E1sSCByGUA8:b-h82a0l) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a66b3ce4c20c520ab52de9e7736f6aa78c1337e/crates/native_blockifier/src/py_transaction.rs#L281)):*
> ```XML
>         self.with_mut(|executor| {
>             let mut transactional_state = CachedState::new(MutRefState::new(executor.state));
>             let py_tx_execution_info = match tx
> ```

Perhaps give `tx.execute(...).map_err(...)` a name, so this line is easier to read?



_Code quote:_
```XML
            let py_tx_execution_info = match tx
                .execute_raw(&mut transactional_state, executor.block_context)
                .map_err(NativeBlockifierError::from)
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 286 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/426#-NUGdfyC5r4FHUNDw-EJ:-NUGdfyC5r4FHUNDw-EK:b-b0z9ft) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a66b3ce4c20c520ab52de9e7736f6aa78c1337e/crates/native_blockifier/src/py_transaction.rs#L286)):*
> ```XML
>             {
>                 Ok(tx_execution_info) => PyTransactionExecutionInfo::from(tx_execution_info),
>                 Err(error) => {
> ```

Is this equivalent to the previous flow?



_Code quote:_
```XML
                Err(error) => {
                    transactional_state.abort();
                    return Err(error);
                }
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 292 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/426#-NUGdt6z75q0SuY9yMeX:-NUGdt6z75q0SuY9yMeY:b-i2o5et) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a66b3ce4c20c520ab52de9e7736f6aa78c1337e/crates/native_blockifier/src/py_transaction.rs#L292)):*
> ```XML
>             };
> 
>             let args = (py_tx_execution_info.clone(),);
> ```

That's a big object... :(
But okay, it's temporary.



_Code quote:_
```XML
py_tx_execution_info.clone()
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 308 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/426#-NUGe2d80F8GcOhlkQfs:-NUGe2d80F8GcOhlkQft:b-p7jtlf) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a66b3ce4c20c520ab52de9e7736f6aa78c1337e/crates/native_blockifier/src/py_transaction.rs#L308)):*
> ```XML
>                 }
>                 Ok(_) => {
>                     transactional_state.commit();
> ```

Move to be first? Intuitively, positive flows  should maybe appear first, if on the same level with negative (no early `return`, for example).



_Code quote:_
```XML
                Ok(_) => {
                    transactional_state.commit();
                    Ok(py_tx_execution_info)
                }
```


<!-- Sent from Reviewable.io -->

2023-05-02 17:07 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/426)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @alonh5 and @elintul)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 286 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/426#-NUGdfyC5r4FHUNDw-EJ:-NULObMU5CwiGsMrT7wO:b-8mala) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a66b3ce4c20c520ab52de9e7736f6aa78c1337e/crates/native_blockifier/src/py_transaction.rs#L286)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Is this equivalent to the previous flow?
</blockquote></details>

Ya, previously, this was an early return, which isn't as nice as this `match`.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 292 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/426#-NUGdt6z75q0SuY9yMeX:-NUSNlrKCXr_rrngrNK9:b-791aos) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a66b3ce4c20c520ab52de9e7736f6aa78c1337e/crates/native_blockifier/src/py_transaction.rs#L292)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

That's a big object... :(
But okay, it's temporary.
</blockquote></details>

Fixed.
I previously only cloned it cause I couldn't pass a reference to it to the Python callback (Python can't work with references to the Rust stack/heap).

Now allocating it directly on the Python heap, which allows Pyo3 to create a reference to it which Python can understand (the `.borrow()` added there outputs type `PyRef<_>`, which is exactly that)
___
*[`crates/native_blockifier/src/py_transaction.rs` line 308 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/426#-NUGe2d80F8GcOhlkQfs:-NUSNim75MbQ3uVcnuA4:b-ghgbui) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a66b3ce4c20c520ab52de9e7736f6aa78c1337e/crates/native_blockifier/src/py_transaction.rs#L308)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move to be first? Intuitively, positive flows  should maybe appear first, if on the same level with negative (no early `return`, for example).
</blockquote></details>

Ya yr right.


<!-- Sent from Reviewable.io -->

2023-05-02 18:09 UTC, elintul reviewed
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/426)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @alonh5)



<!-- Sent from Reviewable.io -->

2023-05-04 09:37 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/426)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 292 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/426#-NUGdt6z75q0SuY9yMeX:-NUa6luG1culs4iJ0_FS:bkcpsiw) ([raw file](https://github.com/starkware-libs/blockifier/blob/7a66b3ce4c20c520ab52de9e7736f6aa78c1337e/crates/native_blockifier/src/py_transaction.rs#L292)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Fixed.
I previously only cloned it cause I couldn't pass a reference to it to the Python callback (Python can't work with references to the Rust stack/heap).

Now allocating it directly on the Python heap, which allows Pyo3 to create a reference to it which Python can understand (the `.borrow()` added there outputs type `PyRef<_>`, which is exactly that)
</blockquote></details>

:crown: 


<!-- Sent from Reviewable.io -->

2023-05-04 10:05 UTC, elintul approved these changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/426)* status: all files reviewed, 3 unresolved discussions (waiting on @alonh5 and @giladchase)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 320 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/426#-NUaD7CSEizmAMIV6s8r:-NUaD7CSEizmAMIV6s8s:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca4ff5d2fbee7b81210a591967bd517142093558/crates/native_blockifier/src/py_transaction.rs#L320)):*
> ```XML
>                 let args = (py_tx_execution_info.borrow(py),);
>                 // This is a callback to Python code.
>                 enough_room_for_tx.call1(args)
> ```





_Suggestion:_
```XML
                // Can be done because `py_tx_execution_info` is a `Py<PyTransactionExecutionInfo>`,
                // hence is allocated on the Python heap.
                let args = (py_tx_execution_info.borrow(py),);
                enough_room_for_tx.call1(args)  // A callback to Python code.
```


<!-- Sent from Reviewable.io -->

2023-05-04 12:09 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/426#-:-NUaeeH81J2lX9uWR2Em:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)



<!-- Sent from Reviewable.io -->

2023-05-04 12:11 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/426)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 307 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/426#-NUa3u-r7Mk3qpL8s-S2:-NUadWsdEQfF8Ax7QXnK:b-4fjbpg) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca4ff5d2fbee7b81210a591967bd517142093558/crates/native_blockifier/src/py_transaction.rs#L307)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do we want the error messages inside `expect` to be capitalize and end with a period?
</blockquote></details>

Looked it up in The Book, they capitalize but don't use a period, that OK?
___
*[`crates/native_blockifier/src/py_transaction.rs` line 320 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/426#-NUaD7CSEizmAMIV6s8r:-NUadpo2Ekihg2rOX_bf:b6bp0u9) ([raw file](https://github.com/starkware-libs/blockifier/blob/ca4ff5d2fbee7b81210a591967bd517142093558/crates/native_blockifier/src/py_transaction.rs#L320)):*
> ```XML
>                 let args = (py_tx_execution_info.borrow(py),);
>                 // This is a callback to Python code.
>                 enough_room_for_tx.call1(args)
> ```

(I won't let me double-space before the `//`.)


<!-- Sent from Reviewable.io -->

2023-05-04 12:13 UTC, merged