Add `get\set_compiled_class_hash`.
starkware-libs/blockifier pull request #433
Opened 2023-04-30 13:43 UTC by noaov1

- Will be used in declare version 2: will be use to check that we have not already declared the given class. And if we did not declare it, we will add (using `set`) the relevant mapping.
- Should return `0` in declare version`<2`.
- Will be used in `get_compiled_class_by_class_hash(class_hash)-> CompiledClass` (which is used in deploy and in execute entry point (to initialize the runner)). Reason: given the `class_hash` we need to extract the `compiled_class_hash` and then we can get the compiled class.

2023-04-30 14:02 UTC, elintul requested changes
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/433)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 414 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/433#-NUHSxx38s8GCjz-GfMd:-NUHSxx38s8GCjz-GfMe:b1rbxz0) ([raw file](https://github.com/starkware-libs/blockifier/blob/c90337024c46392abff2c93d4743d63fdeafdb8e/crates/blockifier/src/state/cached_state.rs#L414)):*
> ```XML
>     }
> 
>     fn set_compiled_class_hash(
> ```

Move before `to_state_diff`.



_Code quote:_
```XML
set_compiled_class_hash
```
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/433#-NUHT6z-5OpN7LitBN6O:-NUHT6z-5OpN7LitBN6P:b-7vo65l) ([raw file](https://github.com/starkware-libs/blockifier/blob/c90337024c46392abff2c93d4743d63fdeafdb8e/crates/native_blockifier/src/papyrus_state.rs#L81)):*
> ```XML
>         &mut self,
>         _class_hash: ClassHash,
>     ) -> StateResult<starknet_api::core::CompiledClassHash> {
> ```

I think we don't have to use fully-qualified names in this file (also for `ClassHash`).



_Code quote:_
```XML
starknet_api::core::CompiledClassHash
```


<!-- Sent from Reviewable.io -->

2023-04-30 14:05 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/433)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/native_blockifier/src/papyrus_state.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/433#-NUHTm_k85sfkJehKHNl:-NUHTm_k85sfkJehKHNm:b-9a3ikw) ([raw file](https://github.com/starkware-libs/blockifier/blob/c90337024c46392abff2c93d4743d63fdeafdb8e/crates/native_blockifier/src/papyrus_state.rs#L82)):*
> ```XML
>         _class_hash: ClassHash,
>     ) -> StateResult<starknet_api::core::CompiledClassHash> {
>         todo!()
> ```

Can you let Dan know we need this change?



_Code quote:_
```XML
todo!()
```


<!-- Sent from Reviewable.io -->

2023-04-30 14:05 UTC, elintul reviewed
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/433)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase and @noaov1)



<!-- Sent from Reviewable.io -->

2023-04-30 14:56 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/433)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/state/cached_state.rs` line 414 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/433#-NUHSxx38s8GCjz-GfMd:-NUHZceNCW8S2b5Z0T6K:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c90337024c46392abff2c93d4743d63fdeafdb8e/crates/blockifier/src/state/cached_state.rs#L414)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move before `to_state_diff`.
</blockquote></details>

Done.
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 81 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/433#-NUHT6z-5OpN7LitBN6O:-NUHbb3dABFP-wgrhaB4:ba3dfob) ([raw file](https://github.com/starkware-libs/blockifier/blob/c90337024c46392abff2c93d4743d63fdeafdb8e/crates/native_blockifier/src/papyrus_state.rs#L81)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we don't have to use fully-qualified names in this file (also for `ClassHash`).
</blockquote></details>

Removed
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/433#-NUHTm_k85sfkJehKHNl:-NUHbdKS8PD79suPbhVl:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/c90337024c46392abff2c93d4743d63fdeafdb8e/crates/native_blockifier/src/papyrus_state.rs#L82)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you let Dan know we need this change?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-04-30 15:13 UTC, elintul approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/433)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/433#-NUHiHOREn9fSgAXD1J2:-NUHiHOREn9fSgAXD1J3:b4wtjdw) ([raw file](https://github.com/starkware-libs/blockifier/blob/c90337024c46392abff2c93d4743d63fdeafdb8e/crates/blockifier/src/state/cached_state_test.rs#L24)):*
> ```XML
>     assert!(state.cache == StateCache::default(), "Cache already initialized.");
> 
>     state.class_hash_to_compiled_class = class_hash_to_class;
> ```

I think it was a good renaming. Perhaps "to [executable/runnable]" is also an option.



_Code quote:_
```XML
state.class_hash_to_compiled_class = class_hash_to_class;
```


<!-- Sent from Reviewable.io -->

2023-05-01 06:14 UTC, giladchase approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/433#-:-NUKwlTX0CSXTZ0k2-H7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-05-01 06:19 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/433)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/433#-NUHiHOREn9fSgAXD1J2:-NUKwc3n4XHGR9iCDgGL:b-l4grgh) ([raw file](https://github.com/starkware-libs/blockifier/blob/c90337024c46392abff2c93d4743d63fdeafdb8e/crates/blockifier/src/state/cached_state_test.rs#L24)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think it was a good renaming. Perhaps "to [executable/runnable]" is also an option.
</blockquote></details>

Yes (I reverted the change because I wanted to do it in the same PR that changes `ContractClassMapping`)


<!-- Sent from Reviewable.io -->

2023-05-01 06:19 UTC, merged