Add declared classes to StateDiff.
starkware-libs/blockifier pull request #443
Opened 2023-05-03 11:59 UTC by noaov1

- Use `ThinStateDiff` (no need to maintain a mapping containing the contract classes)
- Add declared classes (cairo1) to `PyStateDiff`

2023-05-04 05:38 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/443)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NU_FxMS-S3_5izGdtcO:-NU_FxMS-S3_5izGdtcP:b7djj6b) (no related file):*
Can you move/copy `ThinStateDiff` so SN API instead?
Please let Dan know on Slack and Reviewable.

___


<!-- Sent from Reviewable.io -->

2023-05-04 06:58 UTC, giladchase requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/443)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/Cargo.toml` line 20 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUZt9Cr0vvZnPT_WsJD:-NUZt9Cr0vvZnPT_WsJE:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/afbe18fa64ec5176b3c3b1d16f5db09915995d0f/crates/blockifier/Cargo.toml#L20)):*
> ```TOML
> num-integer.workspace = true
> num-traits.workspace = true
> papyrus_storage = { workspace = true}
> ```





_Suggestion:_
```TOML
papyrus_storage.workspace = true
```
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NU_NTM4AnQPWAbJW8M_:-NU_NTM4AnQPWAbJW8Ma:bxek1ep) ([raw file](https://github.com/starkware-libs/blockifier/blob/afbe18fa64ec5176b3c3b1d16f5db09915995d0f/crates/native_blockifier/src/py_state_diff.rs#L92)):*
> ```XML
>         for (class_hash, compiled_class_hash) in state_diff.declared_classes {
>             class_hash_to_compiled_class_hash
>                 .insert(PyFelt(class_hash.0), PyFelt(compiled_class_hash.0));
> ```

With these i think there are enough instances of `PyFelt(class_hash.0)` to warrant a `From<ClassHash> for PyFelt`.
Can you please add it and changes in other places?



_Code quote:_
```XML
(PyFelt(class_hash.0), PyFelt(compiled_class_hash.0));
```
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NU_OGMC6vO2eEOSIoh5:-NU_OGMC6vO2eEOSIoh6:b-c4rrlz) ([raw file](https://github.com/starkware-libs/blockifier/blob/afbe18fa64ec5176b3c3b1d16f5db09915995d0f/crates/native_blockifier/src/py_state_diff.rs#L93)):*
> ```XML
>             class_hash_to_compiled_class_hash
>                 .insert(PyFelt(class_hash.0), PyFelt(compiled_class_hash.0));
>         }
> ```

We can also do this (here and in the rest of the for loops in this function), but honestly, I'm not sure if it's better :sweat_smile: 
So feel free to ignore if you want. :grimacing:  



_Suggestion:_
```XML
        let class_hash_to_compiled_class_hash = state_diff
            .declared_classes
            .iter()
            .map(|(class_hash, compiled_class_hash)| {
                (PyFelt(class_hash.0), PyFelt(compiled_class_hash.0))
            })
            .collect();
```


<!-- Sent from Reviewable.io -->

2023-05-04 06:58 UTC, giladchase reviewed
Can you please link to a Python PR that bumps the commit value? 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/443#-:-NU_YT-v0Q7UZPQnpi0s:b2e3c9o)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @elintul and @noaov1)



<!-- Sent from Reviewable.io -->

2023-05-04 09:16 UTC, elintul requested changes
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/443)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUa1y0n2VBrffXkB7KN:-NUa1y0n2VBrffXkB7KO:b-jlkinp) ([raw file](https://github.com/starkware-libs/blockifier/blob/afbe18fa64ec5176b3c3b1d16f5db09915995d0f/crates/blockifier/src/state/cached_state.rs#L191)):*
> ```XML
>         let deployed_contracts = state_cache.get_class_hash_updates();
>         let storage_diffs = state_cache.get_storage_updates();
>         let declared_classes = state_cache.compiled_class_hash_writes.clone();
> ```

Any way to avoid cloning?



_Code quote:_
```XML
state_cache.compiled_class_hash_writes.clone()
```


<!-- Sent from Reviewable.io -->

2023-05-07 08:09 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/443)* status: 1 of 8 files reviewed, 3 unresolved discussions (waiting on @elintul and @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NU_FxMS-S3_5izGdtcO:-NUovV1M03ln6SR9iC7A:b-714svm) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you move/copy `ThinStateDiff` so SN API instead?
Please let Dan know on Slack and Reviewable.
</blockquote></details>

Done. [PR](https://reviewable.io/reviews/starkware-libs/starknet-api/59#-NUaXD_p3tKtfvRVxPkZ)

___
___
*[`crates/blockifier/Cargo.toml` line 20 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUZt9Cr0vvZnPT_WsJD:-NUowKdh9OmibswAfhKv:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/afbe18fa64ec5176b3c3b1d16f5db09915995d0f/crates/blockifier/Cargo.toml#L20)):*
> ```TOML
> num-integer.workspace = true
> num-traits.workspace = true
> papyrus_storage = { workspace = true}
> ```

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUa1y0n2VBrffXkB7KN:-NUoxebeAnNIuj9o48wY:b-1e82q8) ([raw file](https://github.com/starkware-libs/blockifier/blob/afbe18fa64ec5176b3c3b1d16f5db09915995d0f/crates/blockifier/src/state/cached_state.rs#L191)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Any way to avoid cloning?
</blockquote></details>

I don't think so. All other fields are cloned as well (`subtract_mappings` clones every key and value pair).
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NU_NTM4AnQPWAbJW8M_:-NUoyJhV7IHKs_JwKIbM:b5gvamm) ([raw file](https://github.com/starkware-libs/blockifier/blob/afbe18fa64ec5176b3c3b1d16f5db09915995d0f/crates/native_blockifier/src/py_state_diff.rs#L92)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

With these i think there are enough instances of `PyFelt(class_hash.0)` to warrant a `From<ClassHash> for PyFelt`.
Can you please add it and changes in other places?
</blockquote></details>

Sure. Done
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NU_OGMC6vO2eEOSIoh5:-NUp0V6x1BQNolez4Rtc:b-qpatb6) ([raw file](https://github.com/starkware-libs/blockifier/blob/afbe18fa64ec5176b3c3b1d16f5db09915995d0f/crates/native_blockifier/src/py_state_diff.rs#L93)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

We can also do this (here and in the rest of the for loops in this function), but honestly, I'm not sure if it's better :sweat_smile: 
So feel free to ignore if you want. :grimacing:  
</blockquote></details>

Done. WDYT?


<!-- Sent from Reviewable.io -->

2023-05-07 09:56 UTC, elintul requested changes
> Reviewed 3 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/443)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/Cargo.toml` line 19 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUpcqF60vw_0mjTxh8Q:-NUpcqF60vw_0mjTxh8R:ble2c24) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7f0ee092c1c0317d3815b38f4d37808c27e9f83/crates/blockifier/Cargo.toml#L19)):*
> ```TOML
> num-bigint.workspace = true
> num-integer.workspace = true
> num-traits.workspace = true
> ```

Remove this depedency.


<!-- Sent from Reviewable.io -->

2023-05-07 10:17 UTC, elintul requested changes
> Reviewed 4 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/443)* status: all files reviewed, 6 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUa1y0n2VBrffXkB7KN:-NUphYJ_1TY98QxdG2TT:b-m8dxrz) ([raw file](https://github.com/starkware-libs/blockifier/blob/afbe18fa64ec5176b3c3b1d16f5db09915995d0f/crates/blockifier/src/state/cached_state.rs#L191)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I don't think so. All other fields are cloned as well (`subtract_mappings` clones every key and value pair).
</blockquote></details>

I think the method can be consuming of `self`; it's served its purpose and converted to a state diff.; WDYT? Perhaps there's something I'm missing.
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 249 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUphKYN2aw00V16lFxS:-NUphKYN2aw00V16lFxT:b-6je1a5) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7f0ee092c1c0317d3815b38f4d37808c27e9f83/crates/blockifier/src/state/cached_state_test.rs#L249)):*
> ```XML
>         storage_diffs: IndexMap::from_iter([(contract_address2, indexmap! {key_y => new_value})]),
>         declared_classes: IndexMap::from_iter([(class_hash, compiled_class_hash)]),
>         deprecated_declared_classes: vec![],
> ```

Let's also synthetically do an old declaration here.



_Code quote:_
```XML
deprecated_declared_classes: vec![],
```
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NU_OGMC6vO2eEOSIoh5:-NUph5eGC_JNcRdwf_p-:b456ult) ([raw file](https://github.com/starkware-libs/blockifier/blob/afbe18fa64ec5176b3c3b1d16f5db09915995d0f/crates/native_blockifier/src/py_state_diff.rs#L93)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Done. WDYT?
</blockquote></details>

Do you think for `storage_updates` it's better?
Aside for indentation, what's the runtime difference?
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUpgqsv32O-tnuiIirQ:-NUpgqsv32O-tnuiIirR:blhzj38) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7f0ee092c1c0317d3815b38f4d37808c27e9f83/crates/native_blockifier/src/py_state_diff.rs#L71)):*
> ```XML
> 
> impl From<ThinStateDiff> for PyStateDiff {
>     fn from(state_diff: ThinStateDiff) -> Self {
> ```

Add two headers: `// State commitment.` and `// Declared classes commitment`.


<!-- Sent from Reviewable.io -->

2023-05-08 10:08 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/443)* status: 3 of 9 files reviewed, 5 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/Cargo.toml` line 19 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUpcqF60vw_0mjTxh8Q:-NUuN3oM45bGu_0RXPBC:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7f0ee092c1c0317d3815b38f4d37808c27e9f83/crates/blockifier/Cargo.toml#L19)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Remove this depedency.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUa1y0n2VBrffXkB7KN:-NUqSMf_CbVUNNoDBAUL:bqsb8yu) ([raw file](https://github.com/starkware-libs/blockifier/blob/afbe18fa64ec5176b3c3b1d16f5db09915995d0f/crates/blockifier/src/state/cached_state.rs#L191)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think the method can be consuming of `self`; it's served its purpose and converted to a state diff.; WDYT? Perhaps there's something I'm missing.
</blockquote></details>

The only problem (\challenge) I see with it is with the struct `MutRefState<'a, S: State>(&'a mut S)`.
___
*[`crates/blockifier/src/state/cached_state_test.rs` line 249 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUphKYN2aw00V16lFxS:-NUqX3HZ7CMHEifCQOwk:b-1nt8rk) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7f0ee092c1c0317d3815b38f4d37808c27e9f83/crates/blockifier/src/state/cached_state_test.rs#L249)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's also synthetically do an old declaration here.
</blockquote></details>

WDYM? I haven't added this information to`ThinStateDiff` yet. (and I was wondering if we want to do it given the fact that python does not need it)
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NU_OGMC6vO2eEOSIoh5:-NUqY_e1-vMNnxUkqVrT:b-bgrf17) ([raw file](https://github.com/starkware-libs/blockifier/blob/afbe18fa64ec5176b3c3b1d16f5db09915995d0f/crates/native_blockifier/src/py_state_diff.rs#L93)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do you think for `storage_updates` it's better?
Aside for indentation, what's the runtime difference?
</blockquote></details>

I was wondering about that. The use of the map is less readable. I don't think the difference in running time is that significant. I changed it so that the code will be "uniform".


<!-- Sent from Reviewable.io -->

2023-05-08 19:53 UTC, elintul requested changes
> Reviewed 6 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/443)* status: 8 of 10 files reviewed, 7 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUa1y0n2VBrffXkB7KN:-NUwv6aQ-UZp_HEp-cgY:b-ghi8cy) ([raw file](https://github.com/starkware-libs/blockifier/blob/afbe18fa64ec5176b3c3b1d16f5db09915995d0f/crates/blockifier/src/state/cached_state.rs#L191)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

The only problem (\challenge) I see with it is with the struct `MutRefState<'a, S: State>(&'a mut S)`.
</blockquote></details>

Can you elaborate?
___
*[`crates/blockifier/src/state/cached_state.rs` line 188 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUwvCnBEvBibQzj4e1n:-NUwvCnBEvBibQzj4e1o:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/901203dae4fbf805626bf4a566ab02e4f27d90e2/crates/blockifier/src/state/cached_state.rs#L188)):*
> ```XML
>             subtract_mappings(&state_cache.nonce_writes, &state_cache.nonce_initial_values);
> 
>         let declared_classes = state_cache.compiled_class_hash_writes.clone();
> ```





_Suggestion:_
```XML
        let state_cache = &self.cache;
        let class_hash_updates = state_cache.get_class_hash_updates();
        let storage_diffs = state_cache.get_storage_updates();
        let nonces =
            subtract_mappings(&state_cache.nonce_writes, &state_cache.nonce_initial_values);
        let declared_classes = state_cache.compiled_class_hash_writes.clone();
```
___
*[`crates/blockifier/src/state/state_diff.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUwu1fEEw55XO0Mwyg6:-NUwu1fEEw55XO0Mwyg7:b-9iu3f) ([raw file](https://github.com/starkware-libs/blockifier/blob/901203dae4fbf805626bf4a566ab02e4f27d90e2/crates/blockifier/src/state/state_diff.rs#L8)):*
> ```XML
> /// Holds uncommitted changes induced on StarkNet contracts.
> #[derive(Debug, Clone, Eq, PartialEq)]
> pub struct CommitmentStateDiff {
> ```

Much better name!
Do you think it justifies a new file? Perhaps it belongs in `cached_state.py`?
In fact, maybe `to_state_diff` shouldn't be part of the state API; it's only implemented for `CacheState`.



_Code quote:_
```XML
CommitmentStateDiff
```
___
*[`crates/blockifier/src/state/state_diff.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUwuUg-CP2Zsj1D-MpO:-NUwuUg-CP2Zsj1D-MpP:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/901203dae4fbf805626bf4a566ab02e4f27d90e2/crates/blockifier/src/state/state_diff.rs#L12)):*
> ```XML
>     pub storage_updates: IndexMap<ContractAddress, IndexMap<StorageKey, StarkFelt>>,
>     pub class_hash_to_compiled_class_hash: IndexMap<ClassHash, CompiledClassHash>,
>     pub address_to_nonce: IndexMap<ContractAddress, Nonce>,
> ```





_Suggestion:_
```XML
    // Contract instance attributes (per address).
    pub address_to_class_hash: IndexMap<ContractAddress, ClassHash>,
    pub address_to_nonce: IndexMap<ContractAddress, Nonce>,
    pub storage_updates: IndexMap<ContractAddress, IndexMap<StorageKey, StarkFelt>>,
    
    // Global attributes.
    pub class_hash_to_compiled_class_hash: IndexMap<ClassHash, CompiledClassHash>,
```
___
*[`crates/native_blockifier/src/py_state_diff.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NU_OGMC6vO2eEOSIoh5:-NUwupop0-OtRuMuUrED:b-nth5lh) ([raw file](https://github.com/starkware-libs/blockifier/blob/afbe18fa64ec5176b3c3b1d16f5db09915995d0f/crates/native_blockifier/src/py_state_diff.rs#L93)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I was wondering about that. The use of the map is less readable. I don't think the difference in running time is that significant. I changed it so that the code will be "uniform".
</blockquote></details>

Your call, I'm good with both.


<!-- Sent from Reviewable.io -->

2023-05-08 20:02 UTC, elintul reviewed
> Reviewed 2 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/443)* status: all files reviewed, 7 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/state/cached_state_test.rs` line 249 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUphKYN2aw00V16lFxS:-NUwx9Bk6NUahOYDhIYl:b7a07ld) ([raw file](https://github.com/starkware-libs/blockifier/blob/d7f0ee092c1c0317d3815b38f4d37808c27e9f83/crates/blockifier/src/state/cached_state_test.rs#L249)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM? I haven't added this information to`ThinStateDiff` yet. (and I was wondering if we want to do it given the fact that python does not need it)
</blockquote></details>

You're right, disregard.


<!-- Sent from Reviewable.io -->

2023-05-09 07:22 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/443)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/state/cached_state.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUa1y0n2VBrffXkB7KN:-NUzDV5bE9pqQ3rAi4Nm:b-fxzqrd) ([raw file](https://github.com/starkware-libs/blockifier/blob/afbe18fa64ec5176b3c3b1d16f5db09915995d0f/crates/blockifier/src/state/cached_state.rs#L191)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you elaborate?
</blockquote></details>

If this method consumes `self` then it takes ownership of the receiver `self`and moves `*self.0`.  We cannot move out of `*self` which is behind a mutable reference.
___
*[`crates/blockifier/src/state/state_diff.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUwu1fEEw55XO0Mwyg6:-NUzI_Lm5mSJ9Fmn-yUn:b-8llwcz) ([raw file](https://github.com/starkware-libs/blockifier/blob/901203dae4fbf805626bf4a566ab02e4f27d90e2/crates/blockifier/src/state/state_diff.rs#L8)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Much better name!
Do you think it justifies a new file? Perhaps it belongs in `cached_state.py`?
In fact, maybe `to_state_diff` shouldn't be part of the state API; it's only implemented for `CacheState`.
</blockquote></details>

Not necessarily. I'll move it to `cached_state.py`.
It is also implemented for `MutRefState<'a, S: State>` (which assumes S is a cached state?). But maybe they both should implement it.


<!-- Sent from Reviewable.io -->

2023-05-09 10:09 UTC, noaov1 reviewed
[PR](https://reviewable.io/reviews/starkware-industries/starkware/29854)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/443#-:-NUp8uHR5UJnk6IPiKVX:b-fv5o79)* status: 5 of 10 files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)



<!-- Sent from Reviewable.io -->

2023-05-09 10:11 UTC, elintul reviewed
> Reviewed 3 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/443)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-05-09 10:29 UTC, elintul approved these changes
> Reviewed 2 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/443)* status: all files reviewed, 4 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUa1y0n2VBrffXkB7KN:-NV-2WKb5xImzU7M8h0b:b-hip0y1) ([raw file](https://github.com/starkware-libs/blockifier/blob/afbe18fa64ec5176b3c3b1d16f5db09915995d0f/crates/blockifier/src/state/cached_state.rs#L191)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

If this method consumes `self` then it takes ownership of the receiver `self`and moves `*self.0`.  We cannot move out of `*self` which is behind a mutable reference.
</blockquote></details>

Right... :(
___
*[`crates/blockifier/src/state/state_diff.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUwu1fEEw55XO0Mwyg6:-NV-29ZfCQq6_kMSxcmE:bk9txyg) ([raw file](https://github.com/starkware-libs/blockifier/blob/901203dae4fbf805626bf4a566ab02e4f27d90e2/crates/blockifier/src/state/state_diff.rs#L8)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Not necessarily. I'll move it to `cached_state.py`.
It is also implemented for `MutRefState<'a, S: State>` (which assumes S is a cached state?). But maybe they both should implement it.
</blockquote></details>

They both do. Oh, you mean not as a trait? Yeah.


<!-- Sent from Reviewable.io -->

2023-05-09 10:47 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/443)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/blockifier/src/state/state_diff.rs` line 8 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NUwu1fEEw55XO0Mwyg6:-NV-6CGc0IBrGszIp5n8:b-gvvyqg) ([raw file](https://github.com/starkware-libs/blockifier/blob/901203dae4fbf805626bf4a566ab02e4f27d90e2/crates/blockifier/src/state/state_diff.rs#L8)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

They both do. Oh, you mean not as a trait? Yeah.
</blockquote></details>

I just realised it is not possible to remove the method `to_state_diff` from the `State` trait since the only guarantee on `self.0` is that it implements the State trait.


<!-- Sent from Reviewable.io -->

2023-05-10 05:07 UTC, giladchase reviewed
> Reviewed 2 of 7 files at r2, 3 of 8 files at r3, 3 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/443)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)

___
*[`crates/native_blockifier/src/py_state_diff.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/443#-NU_OGMC6vO2eEOSIoh5:-NV31wPr6mLwmOWtLRmd:bkkockh) ([raw file](https://github.com/starkware-libs/blockifier/blob/afbe18fa64ec5176b3c3b1d16f5db09915995d0f/crates/native_blockifier/src/py_state_diff.rs#L93)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Your call, I'm good with both.
</blockquote></details>

Performance-wise chaining is usually a bit better than regular loops (according to The Book), but here readability is probably more important.


<!-- Sent from Reviewable.io -->

2023-05-10 05:08 UTC, giladchase approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/443#-:-NV32lsy8tSJxLJfkC6I:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-05-10 05:35 UTC, merged