Add `CasmContractClass`
starkware-libs/blockifier pull request #455
Opened 2023-05-09 09:22 UTC by giladchase

Continues the closed #445, which needed a bunch of changes after the Casm reader was made available.

- Add `PapyrusReader` which encapsulates the previous PapyrusStateReader, and also a Casm contract reader.
- Added minimal logic to get papyrus's `get_compiled_contract_class` to work with Casm contracts, setter and CachedState logic still unimplemented.
- Getter logic tries looking up a hash as a V1 contract class, then V0, and then raises an error.
- Hoisted contract getter logic from `initialize_execution_context` into `CallEntryPoint.execute`.
- test utils modified to assume V0 for now, will be generalized later.

2023-05-09 09:31 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 106 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NUzpYHB4YGGimyDD6qx:-NUzpYHB4YGGimyDD6qy:bhpdipq) ([raw file](https://github.com/starkware-libs/blockifier/blob/997371c56b9f36aa3800e4de870a59d0f6c508cf/crates/blockifier/src/execution/entry_point.rs#L106)):*
>elin: I thought we'd move the class-reading-from-state to the callsite (also for the c-tor flow).
gilad:Hoisted up one more level (is that what you meant by "callsite"? cause we already hoisted it up one level once from inside `initialize_execution_context`).
The caller where I moved it to (inside entry\_point.rs) is already in multiple places (so I'll have to put this code in many places if we want this higher up in the call stack).
elin: Only two places, right?

7, not including test locations (it's all places that call CallEntryPoint.execute):  

https://github.com/starkware-libs/blockifier/blob/b1f04ef9c0e262e956b3aee16559b69e81a1d3d1/crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs#L398
https://github.com/starkware-libs/blockifier/blob/ddf6c113d5ad58a4145e62a11bef3d96353cd924/crates/blockifier/src/execution/entry_point.rs#L319
https://github.com/starkware-libs/blockifier/blob/b1f04ef9c0e262e956b3aee16559b69e81a1d3d1/crates/blockifier/src/execution/syscalls/hint_processor.rs#L372
https://github.com/starkware-libs/blockifier/blob/d2660e200d1b8879e89cde873007bd8605200bfd/crates/blockifier/src/transaction/account_transaction.rs#L176
https://github.com/starkware-libs/blockifier/blob/d2660e200d1b8879e89cde873007bd8605200bfd/crates/blockifier/src/transaction/account_transaction.rs#L250
https://github.com/starkware-libs/blockifier/blob/35a6ee6a51482bdb4b4440d5fb72f937f086c082/crates/blockifier/src/transaction/transactions.rs#L174
https://github.com/starkware-libs/blockifier/blob/35a6ee6a51482bdb4b4440d5fb72f937f086c082/crates/blockifier/src/transaction/transactions.rs#L208

That being said, maybe I'm still misunderstanding what you mean by `callsite`, how high up do we want to go?


<!-- Sent from Reviewable.io -->

2023-05-09 10:39 UTC, elintul requested changes
> Reviewed 10 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: 10 of 16 files reviewed, 5 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`Cargo.toml` line 22 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV-2t526tVT48eqlJuU:-NV-2t526tVT48eqlJuV:bgdcnz2) ([raw file](https://github.com/starkware-libs/blockifier/blob/997371c56b9f36aa3800e4de870a59d0f6c508cf/Cargo.toml#L22)):*
> ```TOML
> num-traits = "0.2"
> ouroboros = "0.15.6"
> papyrus_storage = { git = "https://github.com/starkware-libs/papyrus", rev = "da70d83" }
> ```

Is `papyrus-storage` dependent on `cairo-lang-starknet`?
Do we also need to change `starknet-api`'s commit?



_Code quote:_
```TOML
rev = "da70d83"
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 16 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV-3GcyDdV963hzsWxO:-NV-3GcyDdV963hzsWxP:bco1vew) ([raw file](https://github.com/starkware-libs/blockifier/blob/997371c56b9f36aa3800e4de870a59d0f6c508cf/crates/blockifier/src/state/cached_state.rs#L16)):*
> ```XML
> #[cfg(test)]
> #[path = "cached_state_test.rs"]
> mod test;
> ```

Remove blank line?
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV-4JcG7JKtBoTPb7pO:-NV-4JcG7JKtBoTPb7pP:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/997371c56b9f36aa3800e4de870a59d0f6c508cf/crates/native_blockifier/src/papyrus_state.rs#L115)):*
> ```XML
> }
> 
> pub struct PapyrusContractReader<'env> {
> ```





_Suggestion:_
```XML
PapyrusExecutalbeClassReader
```
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 116 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV-3db59W7EkDH1lWyg:-NV-3db59W7EkDH1lWyh:ba3dfna) ([raw file](https://github.com/starkware-libs/blockifier/blob/997371c56b9f36aa3800e4de870a59d0f6c508cf/crates/native_blockifier/src/papyrus_state.rs#L116)):*
> ```XML
> 
> pub struct PapyrusContractReader<'env> {
>     // txn: &'env DbTransaction<'env, RO>,
> ```

Remove?



_Code quote:_
```XML
 // txn: &'env DbTransaction<'env, RO>,
```


<!-- Sent from Reviewable.io -->

2023-05-09 10:40 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: 10 of 16 files reviewed, 6 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/native_blockifier/src/papyrus_state.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV-5FbaE3bSrhpfiTX0:-NV-5FbaE3bSrhpfiTX1:b-hvmf45) ([raw file](https://github.com/starkware-libs/blockifier/blob/997371c56b9f36aa3800e4de870a59d0f6c508cf/crates/native_blockifier/src/papyrus_state.rs#L125)):*
> ```XML
>     }
>     fn get_casm(&self, class_hash: ClassHash) -> StorageResult<Option<CasmContractClass>> {
>         self.txn.get_casm(class_hash)
> ```

I thought the `get_casm` API is implemented by another reader trait, not the DB transaction itself.
Can you elaborate on this, please?



_Code quote:_
```XML
txn.get_casm
```


<!-- Sent from Reviewable.io -->

2023-05-09 10:53 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: 10 of 16 files reviewed, 8 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/native_blockifier/src/papyrus_state.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV-83l859ujBd2vnVua:-NV-83l859ujBd2vnVub:b-te1ak2) ([raw file](https://github.com/starkware-libs/blockifier/blob/997371c56b9f36aa3800e4de870a59d0f6c508cf/crates/native_blockifier/src/papyrus_state.rs#L124)):*
> ```XML
>         Self { txn }
>     }
>     fn get_casm(&self, class_hash: ClassHash) -> StorageResult<Option<CasmContractClass>> {
> ```

Add a blank line above.



_Code quote:_
```XML
fn get_casm(&self, class_hash: ClassHash) -> StorageResult<Option<CasmContractClass>> {
```
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 124 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV-8BGD167aReGcVxf8:-NV-8BGD167aReGcVxf9:b-pjtae) ([raw file](https://github.com/starkware-libs/blockifier/blob/997371c56b9f36aa3800e4de870a59d0f6c508cf/crates/native_blockifier/src/papyrus_state.rs#L124)):*
> ```XML
>         Self { txn }
>     }
>     fn get_casm(&self, class_hash: ClassHash) -> StorageResult<Option<CasmContractClass>> {
> ```

Why `Option`? That's unaligned to [the current contract class API](https://github.com/starkware-libs/blockifier-old/blob/e96e98a6aadfc21e90fe24944e46fdf0a8b6d3d6/crates/blockifier/src/state/state_api.rs#L33).



_Code quote:_
```XML
Option<CasmContractClass>
```


<!-- Sent from Reviewable.io -->

2023-05-09 13:43 UTC, yair-starkware commented
*[`crates/native_blockifier/src/papyrus_state.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV-Dxgc9azLJwOQYD05:-NV-i82m5p3a7Iz18XGT:b9txiz3) ([raw file](https://github.com/starkware-libs/blockifier/blob/931ecf15095f77a284de2022f78ac48d73c7ac38/crates/native_blockifier/src/papyrus_state.rs#L96)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

@yair-starkware, good point.
I understand it's not part of the state, but I'm worried we would get the Casm when we shouldn't and vice versa if we don't fix a block number.
</blockquote></details>

The block number indexing is required for responding to RPC calls.
Adding it will add more cost in space and performance where it is not required (you probably check that the class was declared before fetching its Casm anyways, right?)
It's not a problem to add it though...


<!-- Sent from Reviewable.io -->

2023-05-09 15:25 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: all files reviewed, 16 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/native_blockifier/src/papyrus_state.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV-Dxgc9azLJwOQYD05:-NV06Jd053tLsEX-VtaX:b-rjpj8f) ([raw file](https://github.com/starkware-libs/blockifier/blob/931ecf15095f77a284de2022f78ac48d73c7ac38/crates/native_blockifier/src/papyrus_state.rs#L96)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

The block number indexing is required for responding to RPC calls.
Adding it will add more cost in space and performance where it is not required (you probably check that the class was declared before fetching its Casm anyways, right?)
It's not a problem to add it though...
</blockquote></details>

That's how we check it was declared, since you don't hold the `sierra_hash -> compiled_hash` mapping...


<!-- Sent from Reviewable.io -->

2023-05-10 03:44 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: all files reviewed, 17 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/native_blockifier/src/papyrus_state.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV2kTkA9sHlw_OWAQl7:-NV2kTkA9sHlw_OWAQl8:b-qv0lya) ([raw file](https://github.com/starkware-libs/blockifier/blob/931ecf15095f77a284de2022f78ac48d73c7ac38/crates/native_blockifier/src/papyrus_state.rs#L82)):*
> ```XML
>         &mut self,
>         class_hash: &ClassHash,
>     ) -> StateResult<ContractClass> {
> ```

You should ask if the class was already defined _in this block of before it_ by querying [get_class_definition_at](https://github.com/starkware-libs/papyrus/blob/99beba08554a64de6e23f0f55c6592752781ebaf/crates/papyrus_storage/src/state/mod.rs#L236). Thanks, Noa, for pointing it out.


<!-- Sent from Reviewable.io -->

2023-05-10 12:02 UTC, elintul reviewed
> Reviewed 3 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: 12 of 16 files reviewed, 11 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-05-11 04:38 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: 8 of 19 files reviewed, 11 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/native_blockifier/src/papyrus_state.rs` line 31 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV85BYj7YscbMBeWlSN:-NV85BYj7YscbMBeWlSO:b-a9u4ip) ([raw file](https://github.com/starkware-libs/blockifier/blob/31b3eea73151b9cd2f62f1557b1a19c52f814e40/crates/native_blockifier/src/papyrus_state.rs#L31)):*
> ```XML
>     ) -> Self {
>         let state_reader =
>             storage_tx.get_state_reader().expect("should be able to initialize a state reader");
> ```

FYI - If i use the `?` operator instead of this `expect`, PYO3 crashes badly with `cc` linking errors.
Not sure why that is, but panicking here is OK I guess since the blockifier can't really do anything without a state reader.



_Code quote:_
```XML
storage_tx.get_state_reader().expect("should be able to initialize a state reader");
```


<!-- Sent from Reviewable.io -->

2023-05-11 07:16 UTC, elintul requested changes
> Reviewed 1 of 5 files at r2, 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: all files reviewed, 14 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/transaction/transaction_execution.rs` line 34 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV8elWd2RHczeoGJR7Q:-NV8elWd2RHczeoGJR7R:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/31b3eea73151b9cd2f62f1557b1a19c52f814e40/crates/blockifier/src/transaction/transaction_execution.rs#L34)):*
> ```XML
>                     tx: declare,
>                     contract_class: ContractClass::V0(
>                         contract_class.expect("Declare should be created with a ContractClass"),
> ```





_Suggestion:_
```XML
contract class.
```
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 31 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV8dR-d7MBdNlYGFRLz:-NV8dR-d7MBdNlYGFRM-:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/31b3eea73151b9cd2f62f1557b1a19c52f814e40/crates/native_blockifier/src/papyrus_state.rs#L31)):*
> ```XML
>     ) -> Self {
>         let state_reader =
>             storage_tx.get_state_reader().expect("should be able to initialize a state reader");
> ```





_Suggestion:_
```XML
Should be able to initialize a state reader.
```
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 87 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV8duqo1NrXBNinCdUL:-NV8duqo1NrXBNinCdUM:b-te2egg) ([raw file](https://github.com/starkware-libs/blockifier/blob/31b3eea73151b9cd2f62f1557b1a19c52f814e40/crates/native_blockifier/src/papyrus_state.rs#L87)):*
> ```XML
>     /// Returns a V1 contract if found, or a V0 contract if a V1 contract is not
>     /// found, or an `Error` otherwise.
>     fn get_compiled_contract_class(
> ```

Can't we use `?`s here too?



_Code quote:_
```XML
get_compiled_contract_class
```
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 101 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV8dhf47YmJB8iyCK2Y:-NV8dhf59hVzK0k22U76:bdk7ku9) ([raw file](https://github.com/starkware-libs/blockifier/blob/31b3eea73151b9cd2f62f1557b1a19c52f814e40/crates/native_blockifier/src/papyrus_state.rs#L101)):*
> ```XML
>             .reader
>             .get_class_definition_at(state_number, class_hash)
>             .map_err(|err| StateError::StateReadError(err.to_string()))?
> ```

Why is this needed?



_Code quote:_
```XML
.map_err(|err| StateError::StateReadError(err.to_string()))
```
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 102 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV8dZY49-pqQr3dPhAS:-NV8dZY49-pqQr3dPhAT:b-u8bd2r) ([raw file](https://github.com/starkware-libs/blockifier/blob/31b3eea73151b9cd2f62f1557b1a19c52f814e40/crates/native_blockifier/src/papyrus_state.rs#L102)):*
> ```XML
>             .get_class_definition_at(state_number, class_hash)
>             .map_err(|err| StateError::StateReadError(err.to_string()))?
>             .is_some()
> ```

Can we define a variable, so it's more readable? Or was that intentional?



_Code quote:_
```XML
        if self
            .state
            .reader
            .get_class_definition_at(state_number, class_hash)
            .map_err(|err| StateError::StateReadError(err.to_string()))?
            .is_some()
```
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 109 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV8doqW15Cx88sEIrkt:-NV8doqW15Cx88sEIrku:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/31b3eea73151b9cd2f62f1557b1a19c52f814e40/crates/native_blockifier/src/papyrus_state.rs#L109)):*
> ```XML
>                 .map_err(|err| StateError::StateReadError(err.to_string()))?
>                 .expect(
>                     "should be able to fetch a casm class if its definition exists, database is \
> ```





_Suggestion:_
```XML
Should
```
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 112 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV8e0bs4k6g0n4H17zG:-NV8e0bs4k6g0n4H17zH:b-te1ak2) ([raw file](https://github.com/starkware-libs/blockifier/blob/31b3eea73151b9cd2f62f1557b1a19c52f814e40/crates/native_blockifier/src/papyrus_state.rs#L112)):*
> ```XML
>                      inconsistent.",
>                 );
>             return Ok(ContractClass::V1(ContractClassV1::try_from(casm_contract_class)?));
> ```

Add a blank line above.



_Code quote:_
```XML
return Ok(ContractClass::V1(ContractClassV1::try_from(casm_contract_class)?));
```


<!-- Sent from Reviewable.io -->

2023-05-11 07:33 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: all files reviewed, 11 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/native_blockifier/src/papyrus_state.rs` line 31 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV8dR-d7MBdNlYGFRLz:-NV8fMbiDliFVJu2uJ_-:b6ffxcz) ([raw file](https://github.com/starkware-libs/blockifier/blob/31b3eea73151b9cd2f62f1557b1a19c52f814e40/crates/native_blockifier/src/papyrus_state.rs#L31)):*
> ```XML
>     ) -> Self {
>         let state_reader =
>             storage_tx.get_state_reader().expect("should be able to initialize a state reader");
> ```

Done.
Are we settled on this format?
Looking up standards on this (as well as in code), it seems like the convention is to Capitalize the first letter (which is usually part of the word "Should"), but no period at the end.
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 87 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV8duqo1NrXBNinCdUL:-NV8hEO75KqgmkIr3h44:by94gsk) ([raw file](https://github.com/starkware-libs/blockifier/blob/31b3eea73151b9cd2f62f1557b1a19c52f814e40/crates/native_blockifier/src/papyrus_state.rs#L87)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can't we use `?`s here too?
</blockquote></details>

We could, but i'm not sure if we want too :thinking: 

If this fails, it means that `get_class_definition_at` returned a SN API `ContractClass` (the V1 type not the deprecated one) that matches `class_hash`, but when fetching the contract itself from the DB via `get_casm` we got None.

Can this happen in a happy flow? That is, if the SN API `ContractClass` exists in the DB must the `CasmContractClass` also exist?

I assumed so, that is, there isn't some weird internal papyrus state where this can happen, which means that the DB is inconsistent.

If the DB is inconsistent, IMO we should panic, cause we don't want to allow any further actions on the blockifier until the inconsistency is resolved.
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 101 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV8dhf47YmJB8iyCK2Y:-NV8gOj3BN8PmVExlTQf:bw6v8v6) ([raw file](https://github.com/starkware-libs/blockifier/blob/31b3eea73151b9cd2f62f1557b1a19c52f814e40/crates/native_blockifier/src/papyrus_state.rs#L101)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

Good question.
Here, and in other places in the file, we use this exact `map_err` because many functions return papyrus_storage's `StorageError`, which isn't known variant of `StateError`.

To remove the duplication, we may add this variant into `StateError`, but I'm not sure if that's legit, since `StateError` is abstract, and `StorageError` is papyrus-state-specific, and not relevant for other state-readers that `impl` the `State trait.

WDYT?
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 102 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV8dZY49-pqQr3dPhAS:-NV8g9B51VGmk743a3VB:b-f1yx85) ([raw file](https://github.com/starkware-libs/blockifier/blob/31b3eea73151b9cd2f62f1557b1a19c52f814e40/crates/native_blockifier/src/papyrus_state.rs#L102)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we define a variable, so it's more readable? Or was that intentional?
</blockquote></details>

Done.
Not intentional, your way is better.
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 109 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV8doqW15Cx88sEIrkt:-NV8fthyEcnjEYJdQIma:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/31b3eea73151b9cd2f62f1557b1a19c52f814e40/crates/native_blockifier/src/papyrus_state.rs#L109)):*
> ```XML
>                 .map_err(|err| StateError::StateReadError(err.to_string()))?
>                 .expect(
>                     "should be able to fetch a casm class if its definition exists, database is \
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-05-11 09:32 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: 17 of 19 files reviewed, 6 unresolved discussions (waiting on @elintul and @yair-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV-7KxD3GGvGkq2UIYu:-NV8gFxz4sI8GPA4Zcnr:b-givjmj) ([raw file](https://github.com/starkware-libs/blockifier/blob/931ecf15095f77a284de2022f78ac48d73c7ac38/crates/blockifier/src/test_utils.rs#L90)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Done.
</blockquote></details>

On second thought, I think one mapping is better: `class_hash_to_class: HashMap<ClassHash, ContractClass>;`So the `get\set_compiled_class` is much simpler (you should just revert your changes. WDYT?
___
*[`crates/blockifier/src/state/cached_state.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV-A2HcCwqQ8Xuuhr8K:-NV97sxmBbCmmFdZQcb7:ba854ie) ([raw file](https://github.com/starkware-libs/blockifier/blob/931ecf15095f77a284de2022f78ac48d73c7ac38/crates/blockifier/src/state/cached_state.rs#L32)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Revert?
___
*[`crates/blockifier/src/state/cached_state.rs` line 104 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV-BVxx9iTfpdlpOr_I:-NV4qKqd4wUoZz-HJolk:b-tvhl98) ([raw file](https://github.com/starkware-libs/blockifier/blob/931ecf15095f77a284de2022f78ac48d73c7ac38/crates/blockifier/src/state/cached_state.rs#L104)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Not sure i understand, it doesn't exist yet :thinking: 
</blockquote></details>

Never mind :)


<!-- Sent from Reviewable.io -->

2023-05-14 07:39 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: 10 of 19 files reviewed, 6 unresolved discussions (waiting on @elintul, @noaov1, and @yair-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 90 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV-7KxD3GGvGkq2UIYu:-NVOBobXAUZO_mw8zyXh:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/931ecf15095f77a284de2022f78ac48d73c7ac38/crates/blockifier/src/test_utils.rs#L90)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

On second thought, I think one mapping is better: `class_hash_to_class: HashMap<ClassHash, ContractClass>;`So the `get\set_compiled_class` is much simpler (you should just revert your changes. WDYT?
</blockquote></details>

Done
___
*[`crates/blockifier/src/state/cached_state.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV-A2HcCwqQ8Xuuhr8K:-NVOBpzX6ByfqS4v-oHb:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/931ecf15095f77a284de2022f78ac48d73c7ac38/crates/blockifier/src/state/cached_state.rs#L32)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Revert?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-05-14 08:07 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: 10 of 19 files reviewed, 8 unresolved discussions (waiting on @elintul, @giladchase, and @yair-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 145 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NVOEQBFETnqb4OlOzwc:-NVOEQBFETnqb4OlOzwd:b-1xzlz5) ([raw file](https://github.com/starkware-libs/blockifier/blob/beadff174fa7dd99f2b641b85ecbf8ade3c058c6/crates/blockifier/src/test_utils.rs#L145)):*
> ```XML
>     let raw_contract_class = fs::read_to_string(path).unwrap();
>     let contract_class: ContractClassV0Inner = serde_json::from_str(&raw_contract_class).unwrap();
>     ContractClassV0::try_from(contract_class).unwrap()
> ```

Why not `from`?



_Code quote:_
```XML
try_from
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 71 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NVOH1spAh0FIW6rrjs7:-NVOH1spAh0FIW6rrjs8:bizk8ly) ([raw file](https://github.com/starkware-libs/blockifier/blob/beadff174fa7dd99f2b641b85ecbf8ade3c058c6/crates/blockifier/src/transaction/account_transactions_test.rs#L71)):*
> ```XML
> 
>     // Declare a contract.
>     let contract_class = get_contract_class_v0(TEST_CONTRACT_PATH);
> ```

When do you choose to use `get_contract_class_v0` (and not `get_contract_class_for_testing`)?



_Suggestion:_
```XML
get_contract_class_for_testing
```


<!-- Sent from Reviewable.io -->

2023-05-14 09:45 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: 4 of 19 files reviewed, 8 unresolved discussions (waiting on @elintul, @noaov1, and @yair-starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 145 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NVOEQBFETnqb4OlOzwc:-NVOV9BjAVNfurvH03YH:b-134c25) ([raw file](https://github.com/starkware-libs/blockifier/blob/beadff174fa7dd99f2b641b85ecbf8ade3c058c6/crates/blockifier/src/test_utils.rs#L145)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why not `from`?
</blockquote></details>

Missed it in the merge conflict, tnx.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 71 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NVOH1spAh0FIW6rrjs7:-NVOW2Q6CW9Mdovips2G:b-gk7avq) ([raw file](https://github.com/starkware-libs/blockifier/blob/beadff174fa7dd99f2b641b85ecbf8ade3c058c6/crates/blockifier/src/transaction/account_transactions_test.rs#L71)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

When do you choose to use `get_contract_class_v0` (and not `get_contract_class_for_testing`)?
</blockquote></details>

Currently only in `get_contract_class_for_testing`.

After rebasing main I had to make more changes, since the v1 contract was now added.

The reason why `get_contract_class_v{0,1}` exist is to help readability in v0/v1 specific tests.

Currently only the v1-specific tests are using this though, since differentiating between the v0-specific and general tests should probably be done in a separate PR?


<!-- Sent from Reviewable.io -->

2023-05-14 13:56 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: 3 of 19 files reviewed, 8 unresolved discussions (waiting on @elintul, @noaov1, and @yair-starkware)

___
*[`Cargo.toml` line 22 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV-2t526tVT48eqlJuU:-NVPXq70CZX-gbs8Vzwe:b-v0y02y) ([raw file](https://github.com/starkware-libs/blockifier/blob/931ecf15095f77a284de2022f78ac48d73c7ac38/Cargo.toml#L22)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Yep and yep.
https://reviewable.io/reviews/starkware-libs/starknet-api/61
papyrus is already pointing to the correct version so no PR there.
</blockquote></details>

I'm blocking this as well.

Everything's based on an [unmerged PR in papyrus](https://reviewable.io/reviews/starkware-libs/papyrus/659#-), once its merged we can change all the `rev`s and continue here.


<!-- Sent from Reviewable.io -->

2023-05-14 14:00 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: 3 of 19 files reviewed, 8 unresolved discussions (waiting on @elintul, @giladchase, and @yair-starkware)

___
*[`Cargo.toml` line 13 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NVPY2ehBTZ6ItEANknc:-NVPY2ehBTZ6ItEANknd:b-guw8b6) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e128919562a02f13563b7bc0091cd872c01d3b0/Cargo.toml#L13)):*
> ```TOML
> cairo-lang-casm = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
> cairo-lang-runner = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
> cairo-lang-starknet = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
> ```

Out of curiosity: what is `cairo-lang-casm\runner`? Why were they added now? And why do we use 'rev' as opposed to 'version'?



_Code quote:_
```TOML
cairo-lang-casm = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-runner = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
cairo-lang-starknet = { git = "https://github.com/starkware-libs/cairo", rev = "a0ead7c0b8e297d281c7213151cd43ac11de5042" }
```
___
*[`crates/blockifier/src/test_utils.rs` line 145 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NVOEQBFETnqb4OlOzwc:-NVPToQh21XRg3X85ISQ:b32vhw) ([raw file](https://github.com/starkware-libs/blockifier/blob/beadff174fa7dd99f2b641b85ecbf8ade3c058c6/crates/blockifier/src/test_utils.rs#L145)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Missed it in the merge conflict, tnx.
</blockquote></details>

:)
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 71 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NVOH1spAh0FIW6rrjs7:-NVPVpkD1knhlpWq99LY:b-4hvi0m) ([raw file](https://github.com/starkware-libs/blockifier/blob/beadff174fa7dd99f2b641b85ecbf8ade3c058c6/crates/blockifier/src/transaction/account_transactions_test.rs#L71)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Currently only in `get_contract_class_for_testing`.

After rebasing main I had to make more changes, since the v1 contract was now added.

The reason why `get_contract_class_v{0,1}` exist is to help readability in v0/v1 specific tests.

Currently only the v1-specific tests are using this though, since differentiating between the v0-specific and general tests should probably be done in a separate PR?

</blockquote></details>

Got it.


<!-- Sent from Reviewable.io -->

2023-05-14 14:04 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: 3 of 19 files reviewed, 8 unresolved discussions (waiting on @elintul, @noaov1, and @yair-starkware)

___
*[`Cargo.toml` line 13 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NVPY2ehBTZ6ItEANknc:-NVPZOPeDuZ9DfYAgC8V:b-kvkb61) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e128919562a02f13563b7bc0091cd872c01d3b0/Cargo.toml#L13)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Out of curiosity: what is `cairo-lang-casm\runner`? Why were they added now? And why do we use 'rev' as opposed to 'version'?
</blockquote></details>

No sure, Shahar added them.

`version` corresponds to identifiers in published crates (that is, they appear in crates.io).`
These identifiers are either version numbers (like 1.2.3) or git tags.

`rev` is only for commits on github, so takes a hash as an argument.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 71 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NVOH1spAh0FIW6rrjs7:-NVPZplK7zFesWvL3lCg:brvhkqz) ([raw file](https://github.com/starkware-libs/blockifier/blob/beadff174fa7dd99f2b641b85ecbf8ade3c058c6/crates/blockifier/src/transaction/account_transactions_test.rs#L71)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Got it.
</blockquote></details>

Still blocking :grimacing: 


<!-- Sent from Reviewable.io -->

2023-05-15 06:11 UTC, noaov1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: 3 of 19 files reviewed, 7 unresolved discussions (waiting on @elintul, @giladchase, and @yair-starkware)

___
*[`Cargo.toml` line 13 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NVPY2ehBTZ6ItEANknc:-NVT0nba4jk5CyheeSN2:b-j0cbnv) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e128919562a02f13563b7bc0091cd872c01d3b0/Cargo.toml#L13)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

No sure, Shahar added them.

`version` corresponds to identifiers in published crates (that is, they appear in crates.io).`
These identifiers are either version numbers (like 1.2.3) or git tags.

`rev` is only for commits on github, so takes a hash as an argument.
</blockquote></details>

Why did we choose to use `rev` now?


<!-- Sent from Reviewable.io -->

2023-05-16 10:31 UTC, elintul reviewed
> Reviewed 1 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: 4 of 19 files reviewed, 7 unresolved discussions (waiting on @noaov1 and @yair-starkware)

___
*[`Cargo.toml` line 13 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NVPY2ehBTZ6ItEANknc:-NVZ6JNdEZ0Cq4HJoU-4:b-fy9ara) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e128919562a02f13563b7bc0091cd872c01d3b0/Cargo.toml#L13)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why did we choose to use `rev` now?
</blockquote></details>

Because they haven't released a version yet.


<!-- Sent from Reviewable.io -->

2023-05-21 10:24 UTC, elintul reviewed
> Reviewed 5 of 13 files at r8, 4 of 11 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: 11 of 19 files reviewed, 11 unresolved discussions (waiting on @giladchase, @noaov1, and @yair-starkware)

___
*[`crates/blockifier/src/execution/contract_class.rs` line 34 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NVxoekc-Bovmsqsm3Rl:-NVxoekc-Bovmsqsm3Rm:b-hten0f) ([raw file](https://github.com/starkware-libs/blockifier/blob/282298e54cea42eccb3f6065ddc7bb899c48a7c2/crates/blockifier/src/execution/contract_class.rs#L34)):*
> ```XML
>     V0(ContractClassV0),
>     V1(ContractClassV1),
> }
> ```

Add blank lines between `impl`s too?
___
*[`crates/blockifier/src/state/cached_state.rs` line 17 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NVxomLG1HepclM-ubvI:-NVxomLG1HepclM-ubvJ:b-6fmzex) ([raw file](https://github.com/starkware-libs/blockifier/blob/282298e54cea42eccb3f6065ddc7bb899c48a7c2/crates/blockifier/src/state/cached_state.rs#L17)):*
> ```XML
> #[path = "cached_state_test.rs"]
> mod test;
> type ContractClassMapping = HashMap<ClassHash, ContractClass>;
> ```

Add a blank line above, move `pub type TransactionalState<'a, S>` after this one.
___
*[`crates/blockifier/src/state/cached_state.rs` line 123 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NVxoyL13y7KuRqLC_NU:-NVxoyL13y7KuRqLC_NV:b-cqqax9) ([raw file](https://github.com/starkware-libs/blockifier/blob/282298e54cea42eccb3f6065ddc7bb899c48a7c2/crates/blockifier/src/state/cached_state.rs#L123)):*
> ```XML
>             .get(class_hash)
>             .expect("The class hash must appear in the cache.");
>         Ok(contract_class).cloned()
> ```

What's the difference from before?



_Code quote:_
```XML
Ok(contract_class).cloned()
```
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 31 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV85BYj7YscbMBeWlSN:-NVxpEM77YUkRk_Ix7nu:bh630i5) ([raw file](https://github.com/starkware-libs/blockifier/blob/31b3eea73151b9cd2f62f1557b1a19c52f814e40/crates/native_blockifier/src/papyrus_state.rs#L31)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

FYI - If i use the `?` operator instead of this `expect`, PYO3 crashes badly with `cc` linking errors.
Not sure why that is, but panicking here is OK I guess since the blockifier can't really do anything without a state reader.
</blockquote></details>

I would like to check this out in Python, we wouldn't like to crash the whole service, but to start over the batch creation handler. Perhaps raising a `PanicError` in Python is due.
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 31 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NV8dR-d7MBdNlYGFRLz:-NVxpWNO35vZOCXPbI7m:b-c8oroo) ([raw file](https://github.com/starkware-libs/blockifier/blob/31b3eea73151b9cd2f62f1557b1a19c52f814e40/crates/native_blockifier/src/papyrus_state.rs#L31)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Done.
Are we settled on this format?
Looking up standards on this (as well as in code), it seems like the convention is to Capitalize the first letter (which is usually part of the word "Should"), but no period at the end.
</blockquote></details>

Let's follow the standards.
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 31 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NVxpTqE0kwRGT86w94r:-NVxpTqE0kwRGT86w94s:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/282298e54cea42eccb3f6065ddc7bb899c48a7c2/crates/native_blockifier/src/papyrus_state.rs#L31)):*
> ```XML
>     ) -> Self {
>         let state_reader =
>             storage_tx.get_state_reader().expect("Should be able to initialize a state reader./");
> ```





_Suggestion:_
```XML
.
```


<!-- Sent from Reviewable.io -->

2023-05-21 10:47 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: 11 of 19 files reviewed, 12 unresolved discussions (waiting on @giladchase, @noaov1, and @yair-starkware)

___
*[`crates/native_blockifier/src/papyrus_state.rs` line 60 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NVxqtGZBonf751kTsNy:-NVxqtGZBonf751kTsNz:bc7jtml) ([raw file](https://github.com/starkware-libs/blockifier/blob/31b3eea73151b9cd2f62f1557b1a19c52f814e40/crates/native_blockifier/src/papyrus_state.rs#L60)):*
> ```XML
>         key: StorageKey,
>     ) -> StateResult<StarkFelt> {
>         let state_number = StateNumber(*self.state.latest_block());
> ```

Should we add field getters? WDYT?


<!-- Sent from Reviewable.io -->

2023-05-21 10:47 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: 11 of 19 files reviewed, 12 unresolved discussions (waiting on @giladchase, @noaov1, and @yair-starkware)



<!-- Sent from Reviewable.io -->

2023-05-21 13:46 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/455)* status: 11 of 19 files reviewed, 13 unresolved discussions (waiting on @giladchase, @noaov1, and @yair-starkware)

___
*[`crates/native_blockifier/src/papyrus_state.rs` line 100 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/455#-NVyZ-Kc0VlSYd2wAHiA:-NVyZ-Kc0VlSYd2wAHiB:b-gws69j) ([raw file](https://github.com/starkware-libs/blockifier/blob/282298e54cea42eccb3f6065ddc7bb899c48a7c2/crates/native_blockifier/src/papyrus_state.rs#L100)):*
> ```XML
>             .state
>             .reader
>             .get_class_definition_at(state_number, class_hash)
> ```

You can now use: `get_class_definition_block_number(&ClassHash) -> Option<BlockNumber>`.



_Code quote:_
```XML
get_class_definition_at(state_number, class_hash)
```


<!-- Sent from Reviewable.io -->

2023-05-30 13:39 UTC, closed without merging