Start implementing `StateReader` for `PapyrusReader`
starkware-libs/blockifier pull request #508
Opened 2023-05-21 15:52 UTC by giladchase

Currently unused, will replace the impl on `PapyrusStateReader` soon. The impl is copy-pasted from `PapyrusStateReader`, with the following differences:
* `get_compiled_contract_class` also looks for V1 contract classes, before looking for V0 ones.
* getter for the state_reader now uses the getter method (since the reader is now a field inside PapyrusReader)

Too see exact diff, compare with https://reviewable.io/reviews/starkware-libs/blockifier/455#, which is almost the same (changes are after addressing comments there)

2023-05-21 15:53 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/508)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/papyrus_state.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/508#-NVz-sw_0tfw0PXID-nI:-NVz-sw_0tfw0PXID-nJ:b-2gd8yp) ([raw file](https://github.com/starkware-libs/blockifier/blob/7698fc8f3539859d2fabfa20435d0ee44dcb6be1/crates/native_blockifier/src/papyrus_state.rs#L50)):*
>Elin: You can now use: `get_class_definition_block_number(&ClassHash) -> Option<BlockNumber>`.

Done.

(Context: this was previously `get_class_definition_at`, which was inefficient)



_Code quote:_
```XML
.get_class_definition_block_number
```


<!-- Sent from Reviewable.io -->

2023-05-21 16:07 UTC, elintul requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/508)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/native_blockifier/src/papyrus_state.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/508#-NVz-sw_0tfw0PXID-nI:-NVz2w-SBd4ue9lLFMup:b-tgmery) ([raw file](https://github.com/starkware-libs/blockifier/blob/7698fc8f3539859d2fabfa20435d0ee44dcb6be1/crates/native_blockifier/src/papyrus_state.rs#L50)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

>Elin: You can now use: `get_class_definition_block_number(&ClassHash) -> Option<BlockNumber>`.

Done.

(Context: this was previously `get_class_definition_at`, which was inefficient)
</blockquote></details>

You need no check if the block number is sooner than the current number, right? 
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/508#-NVz32xS7prTrUMG4iqh:-NVz32xT-vNqSnj3J7x8:bvqdtaw) ([raw file](https://github.com/starkware-libs/blockifier/blob/7698fc8f3539859d2fabfa20435d0ee44dcb6be1/crates/native_blockifier/src/papyrus_state.rs#L59)):*
> ```XML
>                 .map_err(|err| StateError::StateReadError(err.to_string()))?
>                 .expect(
>                     "Should be able to fetch a casm class if its definition exists, database is \
> ```

`casm -> Casm` (in doc.). 


<!-- Sent from Reviewable.io -->

2023-05-21 16:12 UTC, elintul requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/508)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/508#-NVz4CQi1shRy8FE1Rk3:-NVz4CQi1shRy8FE1Rk4:b-nlmcah) (no related file):*
How come we didn't need those `map_err`s before? 

___


<!-- Sent from Reviewable.io -->

2023-05-21 16:33 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/508)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/508#-NVz4CQi1shRy8FE1Rk3:-NVz5GnJAyKq3xmOoyTm:b-axpjfi) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

How come we didn't need those `map_err`s before? 
</blockquote></details>

WDYM? Before what?
The PapyrusStateReader also has them.

The reason it's there is cause this error comes from PapyrusStorage, so is papyrus-specific, whereas the `StateError` returned from the function is generic.
Therefore, we can't do something like adding a transparent `PapyrusStorageError` variant to that enum, hence we manually cast it into string.

___
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/508#-NVz-sw_0tfw0PXID-nI:-NVz8mtu7SZXQQQ9qpE0:b2f7hml) ([raw file](https://github.com/starkware-libs/blockifier/blob/7698fc8f3539859d2fabfa20435d0ee44dcb6be1/crates/native_blockifier/src/papyrus_state.rs#L50)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

You need no check if the block number is sooner than the current number, right? 
</blockquote></details>

Done.
Is that `matches!` readable? 
Best alternative I found was `contract_class_definition_block_number.is_some() && contract_class_definition_block_number.unwrap() < state_number.0`
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/508#-NVz32xS7prTrUMG4iqh:-NVz8Wou3KT9HT3SfW8w:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/7698fc8f3539859d2fabfa20435d0ee44dcb6be1/crates/native_blockifier/src/papyrus_state.rs#L59)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

`casm -> Casm` (in doc.). 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-22 04:52 UTC, elintul approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/508)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/508#-NVz4CQi1shRy8FE1Rk3:-NW0nDg0Dnf_4ANN6r5h:bi2eok0) (no related file):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

WDYM? Before what?
The PapyrusStateReader also has them.

The reason it's there is cause this error comes from PapyrusStorage, so is papyrus-specific, whereas the `StateError` returned from the function is generic.
Therefore, we can't do something like adding a transparent `PapyrusStorageError` variant to that enum, hence we manually cast it into string.
</blockquote></details>

Got it, didn't know it was there before.

___
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/508#-NVz-sw_0tfw0PXID-nI:-NW0n3D70r1EVUhjHIUq:b-3x9fha) ([raw file](https://github.com/starkware-libs/blockifier/blob/7698fc8f3539859d2fabfa20435d0ee44dcb6be1/crates/native_blockifier/src/papyrus_state.rs#L50)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Done.
Is that `matches!` readable? 
Best alternative I found was `contract_class_definition_block_number.is_some() && contract_class_definition_block_number.unwrap() < state_number.0`
</blockquote></details>

Not very readable, and also `panic`s? :hushed: 
___
*[`crates/native_blockifier/src/papyrus_state.rs` line 77 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/508#-NW0mtxJ4dHR40dYqn37:-NW0mtxJ4dHR40dYqn38:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b84b2088bf62340ff26632707a8d7397f7b52ae3/crates/native_blockifier/src/papyrus_state.rs#L77)):*
> ```XML
>         let state_number = StateNumber(*self.state.latest_block());
> 
>         let contract_class_definition_block_number = self
> ```





_Suggestion:_
```XML
class_declaration_block_number
```


<!-- Sent from Reviewable.io -->

2023-05-22 04:52 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/508)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-05-22 05:36 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/508)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/papyrus_state.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/508#-NVz-sw_0tfw0PXID-nI:-NW0v-0F0kFXE9RvEr2O:bh865gd) ([raw file](https://github.com/starkware-libs/blockifier/blob/7698fc8f3539859d2fabfa20435d0ee44dcb6be1/crates/native_blockifier/src/papyrus_state.rs#L50)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not very readable, and also `panic`s? :hushed: 
</blockquote></details>

Which is more readable though, the `matches` or the `&&` one? (I don't a better alternative...)

RE the panic, you mean the `unwrap`? It's OK here, because before the `&&` I'm checking if it `is_some`. so that unwrap can't fail if it passed the `is_some` (doesn't mean I like it though :tipping_hand_man: _


<!-- Sent from Reviewable.io -->

2023-05-22 05:42 UTC, elintul requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/508)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/native_blockifier/src/papyrus_state.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/508#-NVz-sw_0tfw0PXID-nI:-NW0yJ5kAORPTguvsCQV:b-2ta16b) ([raw file](https://github.com/starkware-libs/blockifier/blob/7698fc8f3539859d2fabfa20435d0ee44dcb6be1/crates/native_blockifier/src/papyrus_state.rs#L50)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Which is more readable though, the `matches` or the `&&` one? (I don't a better alternative...)

RE the panic, you mean the `unwrap`? It's OK here, because before the `&&` I'm checking if it `is_some`. so that unwrap can't fail if it passed the `is_some` (doesn't mean I like it though :tipping_hand_man: _
</blockquote></details>

Does `matches!()` panic?
Give it a name:
```rs
let class_is_declared = matches!(
    class_declaration_block_number, Some(block_number) if block_number < state_number.0);
```
Also, I think it can be `<=`, right? The class can be declared then used in the same block.


<!-- Sent from Reviewable.io -->

2023-05-24 16:28 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/508)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/papyrus_state.rs` line 50 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/508#-NVz-sw_0tfw0PXID-nI:-NWD_F2Z1miUh5DJlmme:bxwluew) ([raw file](https://github.com/starkware-libs/blockifier/blob/7698fc8f3539859d2fabfa20435d0ee44dcb6be1/crates/native_blockifier/src/papyrus_state.rs#L50)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Does `matches!()` panic?
Give it a name:
```rs
let class_is_declared = matches!(
    class_declaration_block_number, Some(block_number) if block_number < state_number.0);
```
Also, I think it can be `<=`, right? The class can be declared then used in the same block.
</blockquote></details>

Done, thanks!

Doesn't panic, it's a `bool`, added to the definition of the variable for readability.


<!-- Sent from Reviewable.io -->

2023-05-24 17:22 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/508#-:-NWDm9Lx0lYO6BXrRVJk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-05-24 17:22 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/508)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/508#-NWDmCPk-t51C5YutYlV:-NWDmCPk-t51C5YutYlW:b-841hfo) (no related file):*
Rebase over `main-v0.12.0`.

___


<!-- Sent from Reviewable.io -->

2023-05-28 09:44 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/508)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/508#-NWDmCPk-t51C5YutYlV:-NWWjkET23n-KPusaMQF:b-896fix) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Rebase over `main-v0.12.0`.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2023-05-28 09:45 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/508)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @elintul)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/508#-NWDmCPk-t51C5YutYlV:-NWWjp7jCS_bfCYCSO2I:by7l3nz) (no related file):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Reminder: this is two commits, the second (==later) you already approved as a PR into this one.
The only new addition is the first commit ("start implementing...")

___


<!-- Sent from Reviewable.io -->

2023-05-28 09:50 UTC, elintul approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/508)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-05-28 09:55 UTC, merged