Add `PyContractClass`
starkware-libs/blockifier pull request #557
Opened 2023-06-04 06:17 UTC by giladchase

Sierra contract class in python has a field called `entry_points_by_type`, whereas in SN API it's called `entry_point_by_type`

2023-06-04 07:49 UTC, noaov1 requested changes
Are you planning to change it (in SN API)? (and maybe consider adding `contract_class_version` if needed)

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/557#-:-NX4IGOIEe3_Lm7_-e8e:b-140rz7)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul and @giladchase)

___
*[`crates/native_blockifier/src/py_contract_class.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/557#-NX4Kr-G8ZHS5a6ivqhy:-NX4Kr-G8ZHS5a6ivqhz:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/388213f13c247d1842d45fd6d14462ab3974f4b3/crates/native_blockifier/src/py_contract_class.rs#L9)):*
> ```XML
> // A contract class as represented in Python, which is represented slightly different than
> // in Starknet API.
> #[derive(Debug, Clone, Default, Eq, PartialEq, Deserialize, Serialize)]
> ```





_Suggestion:_
```XML
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
```
___
*[`crates/native_blockifier/src/py_contract_class.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/557#-NX4LrwB9ru96RQU9K10:-NX4LrwB9ru96RQU9K11:bhjqkge) ([raw file](https://github.com/starkware-libs/blockifier/blob/388213f13c247d1842d45fd6d14462ab3974f4b3/crates/native_blockifier/src/py_contract_class.rs#L9)):*
> ```XML
> // A contract class as represented in Python, which is represented slightly different than
> // in Starknet API.
> #[derive(Debug, Clone, Default, Eq, PartialEq, Deserialize, Serialize)]
> ```

Why is it needed?



_Code quote:_
```XML
Serialize
```


<!-- Sent from Reviewable.io -->

2023-06-04 11:18 UTC, giladchase reviewed
Why do we need it there? :thinking: 
The only reason this is needed is because python calls this field by a different name, but SN API doesn't know about Python.
(If I understood your intention that is.)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/557#-:-NX4Yqj24H6TPy7pUivj:b-prm6u9)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/native_blockifier/src/py_contract_class.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/557#-NX4Kr-G8ZHS5a6ivqhy:-NX57Ins1Kp3UhezVv-X:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/388213f13c247d1842d45fd6d14462ab3974f4b3/crates/native_blockifier/src/py_contract_class.rs#L9)):*
> ```XML
> // A contract class as represented in Python, which is represented slightly different than
> // in Starknet API.
> #[derive(Debug, Clone, Default, Eq, PartialEq, Deserialize, Serialize)]
> ```

Done.
___
*[`crates/native_blockifier/src/py_contract_class.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/557#-NX4LrwB9ru96RQU9K10:-NX57JPw00FpiJdifxpR:b4zjq7b) ([raw file](https://github.com/starkware-libs/blockifier/blob/388213f13c247d1842d45fd6d14462ab3974f4b3/crates/native_blockifier/src/py_contract_class.rs#L9)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Why is it needed?
</blockquote></details>

Not needed :)
tanks


<!-- Sent from Reviewable.io -->

2023-06-04 11:31 UTC, elintul requested changes
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/557)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/native_blockifier/src/py_contract_class.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/557#-NX5A1wdCKLAePqxd9Or:-NX5A1weE9z2HQHdxu_K:bn7nmw6) ([raw file](https://github.com/starkware-libs/blockifier/blob/8594c370eb286f74630c916b70799ac2c1805e0e/crates/native_blockifier/src/py_contract_class.rs#L10)):*
> ```XML
> // in Starknet API.
> #[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq)]
> pub struct PyContractClass {
> ```

I think we don't really need to pass the Sierra class from Python, it's not used in execution. We can instantiate all Sierra classes with `::default()` in `append_state_diff` instead.


<!-- Sent from Reviewable.io -->

2023-06-04 15:02 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/557)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/native_blockifier/src/py_contract_class.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/557#-NX5A1wdCKLAePqxd9Or:-NX5vNvKBLzXeautxSZW:ba14pia) ([raw file](https://github.com/starkware-libs/blockifier/blob/8594c370eb286f74630c916b70799ac2c1805e0e/crates/native_blockifier/src/py_contract_class.rs#L10)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we don't really need to pass the Sierra class from Python, it's not used in execution. We can instantiate all Sierra classes with `::default()` in `append_state_diff` instead.
</blockquote></details>

Right, and as discussed offline, we're keeping this open for now until Noa finishes implementing what you wrote, since it became part of her task.


<!-- Sent from Reviewable.io -->

2023-06-08 06:09 UTC, giladchase commented
Not relevant, a different solution merged already.

2023-06-08 06:09 UTC, closed without merging