Limit recursion depth for entrypoint calls
starkware-libs/blockifier pull request #612
Opened 2023-06-14 14:20 UTC by giladchase

Currently too many recursions hit stack-overflow panic, we don't want that.

Increasing the stack size to 72MB is required in order to have the same recursion depth as in CPython, 3000.
This is X36 times the 2MB default, is there a better way?

2023-06-14 14:23 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/612)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`.cargo/config.toml` line 14 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/612#-NXuHUln7_PNaoqFqHNr:-NXuHUln7_PNaoqFqHNs:b-z1gk6f) ([raw file](https://github.com/starkware-libs/blockifier/blob/36f4176be8171c5fd64fbb2fe218a9e8170b1eab/.cargo/config.toml#L14)):*
> ```TOML
> # Increase rust stack size.
> # This should be large enough for `MAX_ENTRY_POINT_RECURSION_DEPTH` recursive entry point calls.
> RUST_MIN_STACK = "75497728" #  72 MiB
> ```

Blocking.
Not sure about this at all.

Default stack size is 2MiB, this is a X36 increase, scary stuff.



_Code quote:_
```TOML
[env]
# Increase rust stack size.
# This should be large enough for `MAX_ENTRY_POINT_RECURSION_DEPTH` recursive entry point calls.
RUST_MIN_STACK = "75497728" #  72 MiB
```


<!-- Sent from Reviewable.io -->

2023-06-14 15:06 UTC, giladchase reviewed
TODO: add the error to python errors and add unit test for this.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/612#-:-NXuRQup5QAWhBumdxfI:b-y370io)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2023-06-14 16:11 UTC, elintul requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/612)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase)

___
*[`.cargo/config.toml` line 12 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/612#-NXuf4w2-QDaG4T0ZMk0:-NXuf4w332PKkCIUPGv0:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/36f4176be8171c5fd64fbb2fe218a9e8170b1eab/.cargo/config.toml#L12)):*
> ```TOML
> 
> [env]
> # Increase rust stack size.
> ```





_Suggestion:_
```TOML
Rust
```
___
*[`crates/blockifier/src/abi/constants.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/612#-NXuf9OJ4c4JCCjRrSyk:-NXuf9OJ4c4JCCjRrSyl:br5tor5) ([raw file](https://github.com/starkware-libs/blockifier/blob/36f4176be8171c5fd64fbb2fe218a9e8170b1eab/crates/blockifier/src/abi/constants.rs#L63)):*
> ```XML
> // Max number of recursions allows in an EntryPoint.
> // Compatible with CPython's max recursion depth.
> pub const MAX_ENTRY_POINT_RECURSION_DEPTH: usize = 3000;
> ```

Let's merge with `100`; fix comment about CPython, mention that limit should be lower.



_Suggestion:_
```XML
100
```


<!-- Sent from Reviewable.io -->

2023-06-15 12:42 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/612)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`.cargo/config.toml` line 14 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/612#-NXuHUln7_PNaoqFqHNr:-NXz40xp3WpaGS1BFvLh:btjflor) ([raw file](https://github.com/starkware-libs/blockifier/blob/36f4176be8171c5fd64fbb2fe218a9e8170b1eab/.cargo/config.toml#L14)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Blocking.
Not sure about this at all.

Default stack size is 2MiB, this is a X36 increase, scary stuff.
</blockquote></details>

Unblocking, for 100 depth limit we only need 4MB, which is 2X, not too bad.
___
*[`crates/blockifier/src/abi/constants.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/612#-NXuf9OJ4c4JCCjRrSyk:-NXz408d66ZUWETRgtsN:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/36f4176be8171c5fd64fbb2fe218a9e8170b1eab/crates/blockifier/src/abi/constants.rs#L63)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's merge with `100`; fix comment about CPython, mention that limit should be lower.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-15 12:56 UTC, merged