Add STORED_BLOCK_HASH_BUFFER and enforce it.
starkware-libs/blockifier pull request #641
Opened 2023-06-20 09:20 UTC by ArniStarkware

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/641)

2023-06-20 09:20 UTC, ArniStarkware commented
Also needs a test for the negative flow.




<!-- Sent from Reviewable.io -->

2023-06-22 10:12 UTC, dafnamatsry requested changes
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 329 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYXXEAI2lw_aBhyeBx5:-NYXXEAI2lw_aBhyeBx6:bhd1t6) ([raw file](https://github.com/starkware-libs/blockifier/blob/df5846d3a9961415d818a29dd021ee8f70f501f7/crates/blockifier/src/execution/syscalls/mod.rs#L329)):*
> ```XML
>     // buged, as the direct conversion from StarkFelt to usize can overflow, on 32 bit systems.
>     let request_block_number: u64 =
>         u64::try_from(usize::try_from(request.block_number)?).map_err(|_| {
> ```

Why is block_number a StarkFelt and not BlockNumber?
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 352 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYXYQMRBG7dYgKh2eaY:-NYXYQMRBG7dYgKh2eaZ:b-6m3pjr) ([raw file](https://github.com/starkware-libs/blockifier/blob/df5846d3a9961415d818a29dd021ee8f70f501f7/crates/blockifier/src/execution/syscalls/mod.rs#L352)):*
> ```XML
>             request_block_number,
>         });
>     }
> ```

You can replace the two checks with the following: 
```
let upper_bound_block_number = cmp::max(current_block_number - constants::STORED_BLOCK_HASH_BUFFER, 0)
if request_block_number > upper_bound_block_number {
    ....
}
```


<!-- Sent from Reviewable.io -->

2023-06-22 12:44 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/blockifier/src/abi/constants.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYWthgRBsZC9X0I4IKO:-NYWthgRBsZC9X0I4IKP:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/428788f50644c2dedcb492b7ebe3b05a5c2bb456/crates/blockifier/src/abi/constants.rs#L72)):*
> ```XML
> pub const BLOCK_HASH_CONTRACT_ADDRESS: u64 = 1;
> 
> // The block number -> block hash mapping is written for the current block number minus this number.
> ```





_Suggestion:_
```XML
At the beginning of each block, we update the `block_number -> block_hash` mapping with `block_number` equals the current block number minus the following number.
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYY7SdM3vQQi27Xis9E:-NYY7SdM3vQQi27Xis9F:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/428788f50644c2dedcb492b7ebe3b05a5c2bb456/crates/blockifier/src/execution/syscalls/hint_processor.rs#L53)):*
> ```XML
>          {request_block_number:?}."
>     )]
>     BlockNumberOutOfRange { upper_bound_block_number: u64, request_block_number: u64 },
> ```





_Suggestion:_
```XML
requested_block_number
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 170 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYWsdJU-NSHcFNBHHdU:-NYWsdJU-NSHcFNBHHdV:b-gc8fk8) ([raw file](https://github.com/starkware-libs/blockifier/blob/428788f50644c2dedcb492b7ebe3b05a5c2bb456/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L170)):*
> ```XML
>         upper_bound_block_number, request_block_number
>     );
>     assert!(error.contains(&expected_error));
> ```

Or some other names that you see fit. 



_Suggestion:_
```XML
    let error = entry_point_call.execute_directly(&mut state).unwrap_err();
    assert_matches!(
        error,
        SyscallExecutionError::BlockNumberOutOfRange {
            upper_bound,
            request,
        }
        if (upper_bound_, request) ==
        (upper_bound_block_number, request_block_number)
    );
```


<!-- Sent from Reviewable.io -->

2023-06-22 14:06 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry and @noaov1)

___
*[`crates/blockifier/src/abi/constants.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYWthgRBsZC9X0I4IKO:-NYYJMul8DdM1gOu9GV0:br5kdxz) ([raw file](https://github.com/starkware-libs/blockifier/blob/428788f50644c2dedcb492b7ebe3b05a5c2bb456/crates/blockifier/src/abi/constants.rs#L72)):*
> ```XML
> pub const BLOCK_HASH_CONTRACT_ADDRESS: u64 = 1;
> 
> // The block number -> block hash mapping is written for the current block number minus this number.
> ```

I wanted to be consistent with the documentation from this PR: https://github.com/starkware-industries/starkware/pull/30342
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYY7SdM3vQQi27Xis9E:-NYYKAm29jf_dUpIUM5u:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/428788f50644c2dedcb492b7ebe3b05a5c2bb456/crates/blockifier/src/execution/syscalls/hint_processor.rs#L53)):*
> ```XML
>          {request_block_number:?}."
>     )]
>     BlockNumberOutOfRange { upper_bound_block_number: u64, request_block_number: u64 },
> ```

Done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 329 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYXXEAI2lw_aBhyeBx5:-NYYG_Sy8BNnFAr3rxVg:bw6ih7s) ([raw file](https://github.com/starkware-libs/blockifier/blob/df5846d3a9961415d818a29dd021ee8f70f501f7/crates/blockifier/src/execution/syscalls/mod.rs#L329)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Why is block_number a StarkFelt and not BlockNumber?
</blockquote></details>

Now rebased over #604. Mind TAL?
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 352 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYXYQMRBG7dYgKh2eaY:-NYYIe_mDX6b6_mHU4XI:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/df5846d3a9961415d818a29dd021ee8f70f501f7/crates/blockifier/src/execution/syscalls/mod.rs#L352)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

You can replace the two checks with the following: 
```
let upper_bound_block_number = cmp::max(current_block_number - constants::STORED_BLOCK_HASH_BUFFER, 0)
if request_block_number > upper_bound_block_number {
    ....
}
```
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 170 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYWsdJU-NSHcFNBHHdU:-NYYQ-Qf5D_o9hBjVcom:b-wqb65z) ([raw file](https://github.com/starkware-libs/blockifier/blob/428788f50644c2dedcb492b7ebe3b05a5c2bb456/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L170)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Or some other names that you see fit. 
</blockquote></details>

This is why we test! Nice. I need to fix the error handling.  IIUC, we want the `entry_point_call` to return an error of type: `EntryPointExecutionError::ExecutionFailed`


<!-- Sent from Reviewable.io -->

2023-06-25 03:55 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 170 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYWsdJU-NSHcFNBHHdU:-NYkefdM8lgsTswgVa_Q:bvd09en) ([raw file](https://github.com/starkware-libs/blockifier/blob/428788f50644c2dedcb492b7ebe3b05a5c2bb456/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L170)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

This is why we test! Nice. I need to fix the error handling.  IIUC, we want the `entry_point_call` to return an error of type: `EntryPointExecutionError::ExecutionFailed`
</blockquote></details>

My last message was unclear.

I suggest this fix to the test. 
My question is - is this the error we want the `entry_point_call` to return in this case?


<!-- Sent from Reviewable.io -->

2023-06-25 07:19 UTC, dafnamatsry reviewed
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-06-25 08:49 UTC, ArniStarkware commented
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 170 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYWsdJU-NSHcFNBHHdU:-NYljKzm5GNz4h5BggY_:bmtmiy) ([raw file](https://github.com/starkware-libs/blockifier/blob/428788f50644c2dedcb492b7ebe3b05a5c2bb456/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L170)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

My last message was unclear.

I suggest this fix to the test. 
My question is - is this the error we want the `entry_point_call` to return in this case?
</blockquote></details>

Reverted to assertion with `.contains`.


<!-- Sent from Reviewable.io -->

2023-06-25 10:50 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 337 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYm3q9k1dQsvyFNLov3:-NYm3q9k1dQsvyFNLov4:bgdh53i) ([raw file](https://github.com/starkware-libs/blockifier/blob/5eb52287f5c5299138336e2d00d41e2e94555a65/crates/blockifier/src/execution/syscalls/mod.rs#L337)):*
> ```XML
>     let current_block_number = syscall_handler.context.block_context.block_number.0;
> 
>     // We use saturating_sub to avoid underflow. Only relevant when current_block_number is low.
> ```

I think it was not clear enough.
Is `0` a valid block number?
What about the case where `current_block_number = constants::STORED_BLOCK_HASH_BUFFER  -1` and `requested_block_number = 0`. The error message can be confusing, no?



_Suggestion:_
```XML
// We ensure the current block number is not too small and the requested block number is not too large.
// We use saturating_sub to avoid underflow.
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYm9znf4a0VDpaQDf-u:-NYm9znf4a0VDpaQDf-v:b-228k23) ([raw file](https://github.com/starkware-libs/blockifier/blob/5eb52287f5c5299138336e2d00d41e2e94555a65/crates/blockifier/src/execution/syscalls/mod.rs#L348)):*
> ```XML
>     }
> 
>     // TODO(Arni, 25/6/2023): Use fn try_from(felt: u64) -> Result<StorageKey, _>.
> ```

WDYM? Implement it in SN API? Why `try_from`?



_Code quote:_
```XML
 // TODO(Arni, 25/6/2023): Use fn try_from(felt: u64) -> Result<StorageKey, _>.
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 170 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYWsdJU-NSHcFNBHHdU:-NYlxhLk1ttmhDs2zsVV:b-n2a0t1) ([raw file](https://github.com/starkware-libs/blockifier/blob/428788f50644c2dedcb492b7ebe3b05a5c2bb456/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L170)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Reverted to assertion with `.contains`.
</blockquote></details>

Great. It does not work given the chain of error that is returned, sorry for the confusion.


<!-- Sent from Reviewable.io -->

2023-06-25 11:31 UTC, dafnamatsry reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 337 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYm3q9k1dQsvyFNLov3:-NYmHKt28xHf4EtAmowx:b-mdpdl3) ([raw file](https://github.com/starkware-libs/blockifier/blob/5eb52287f5c5299138336e2d00d41e2e94555a65/crates/blockifier/src/execution/syscalls/mod.rs#L337)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think it was not clear enough.
Is `0` a valid block number?
What about the case where `current_block_number = constants::STORED_BLOCK_HASH_BUFFER  -1` and `requested_block_number = 0`. The error message can be confusing, no?
</blockquote></details>

The case where `requested_block_number = 0` has a bug here - we will always accept it with the check below.
And the error message for 0 is also confusing: “Block number out of range; maximal allowed: 0?, got: 0”


<!-- Sent from Reviewable.io -->

2023-06-25 12:02 UTC, ArniStarkware commented
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYmQREHDMWVmnvzLeyL:-NYmQREI6fFMX6Ke3bK-:beyjuoh) ([raw file](https://github.com/starkware-libs/blockifier/blob/5eb52287f5c5299138336e2d00d41e2e94555a65/crates/blockifier/src/execution/syscalls/hint_processor.rs#L53)):*
> ```XML
>         "Block number out of range; maximal allowed: {upper_bound_block_number:?}, got: \
>          {requested_block_number:?}."
>     )]
> ```

Align with Cairo error message.



_Suggestion:_
```XML
    #[error(
        "Block number out of range"
    )]
```


<!-- Sent from Reviewable.io -->

2023-06-25 13:09 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @dafnamatsry and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 337 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYm3q9k1dQsvyFNLov3:-NYmeCSVBjrCh9P4qWEI:b-ohj3fb) ([raw file](https://github.com/starkware-libs/blockifier/blob/5eb52287f5c5299138336e2d00d41e2e94555a65/crates/blockifier/src/execution/syscalls/mod.rs#L337)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

The case where `requested_block_number = 0` has a bug here - we will always accept it with the check below.
And the error message for 0 is also confusing: “Block number out of range; maximal allowed: 0?, got: 0”

</blockquote></details>

I use `checked_sub` instead of `satueating_sub` to avoid the `requested_block_number = 0` bug.

Is the flow with `.map_or` readable now?
(This only works because we shortened the error message). 
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 348 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYm9znf4a0VDpaQDf-u:-NYmR0Gx9dXmeGgh0oCh:b-9q2qfr) ([raw file](https://github.com/starkware-libs/blockifier/blob/5eb52287f5c5299138336e2d00d41e2e94555a65/crates/blockifier/src/execution/syscalls/mod.rs#L348)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM? Implement it in SN API? Why `try_from`?
</blockquote></details>

Removed.
I did mean to implement it in the SN-API. This is a strange case, thus let's not deal with it.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 170 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYWsdJU-NSHcFNBHHdU:-NYmAofc7pIrlMGaYf99:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/428788f50644c2dedcb492b7ebe3b05a5c2bb456/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L170)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Great. It does not work given the chain of error that is returned, sorry for the confusion.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-25 13:38 UTC, dafnamatsry requested changes
> Reviewed 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 337 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYm3q9k1dQsvyFNLov3:-NYmjDKN4g5Shz8p1SBL:b8mj01z) ([raw file](https://github.com/starkware-libs/blockifier/blob/5eb52287f5c5299138336e2d00d41e2e94555a65/crates/blockifier/src/execution/syscalls/mod.rs#L337)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I use `checked_sub` instead of `satueating_sub` to avoid the `requested_block_number = 0` bug.

Is the flow with `.map_or` readable now?
(This only works because we shortened the error message). 
</blockquote></details>

Not so readable I think.
What about:

```
if current_block_number < STORED_BLOCK_HASH_BUFFER || request_block_number > upper_bound_block_number.expect("underflow") {
    return Err(...)
}
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 337 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYmlSbL2OKEIDTT9WYY:-NYmlSbL2OKEIDTT9WYZ:b-goyfo8) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef48eb7d8cb2542e441e453084c48a3240dff396/crates/blockifier/src/execution/syscalls/mod.rs#L337)):*
> ```XML
>     let current_block_number = syscall_handler.context.block_context.block_number.0;
> 
>     // We assure the requested block number is at least 10 blocks before the current block.
> ```

STORED_BLOCK_HASH_BUFFER



_Code quote:_
```XML
10
```


<!-- Sent from Reviewable.io -->

2023-06-25 14:57 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @dafnamatsry and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 337 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYm3q9k1dQsvyFNLov3:-NYmrQeq748dSgUtDVpc:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5eb52287f5c5299138336e2d00d41e2e94555a65/crates/blockifier/src/execution/syscalls/mod.rs#L337)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

Not so readable I think.
What about:

```
if current_block_number < STORED_BLOCK_HASH_BUFFER || request_block_number > upper_bound_block_number.expect("underflow") {
    return Err(...)
}
```
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 337 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYmlSbL2OKEIDTT9WYY:-NYmrQvH3JNhN0wLthp7:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef48eb7d8cb2542e441e453084c48a3240dff396/crates/blockifier/src/execution/syscalls/mod.rs#L337)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

STORED_BLOCK_HASH_BUFFER
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-26 06:35 UTC, dafnamatsry approved these changes
> Reviewed 1 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: all files reviewed, 5 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-06-26 09:13 UTC, noaov1 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: all files reviewed, 7 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/blockifier/src/abi/constants.rs` line 73 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYqnuoYByOuD-9PAWcw:-NYqnuoYByOuD-9PAWcx:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/186397211abf3912ac5cefcc926cfa7bacc81283/crates/blockifier/src/abi/constants.rs#L73)):*
> ```XML
> 
> // The block number -> block hash mapping is written for the current block number minus this number.
> pub const STORED_BLOCK_HASH_BUFFER: u64 = 10;
> ```





_Suggestion:_
```XML
BLOCK_NUMBER_MARGIN
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYmQREHDMWVmnvzLeyL:-NYn8zie-NKEntW4-7Oe:b-jkdfiy) ([raw file](https://github.com/starkware-libs/blockifier/blob/5eb52287f5c5299138336e2d00d41e2e94555a65/crates/blockifier/src/execution/syscalls/hint_processor.rs#L53)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Align with Cairo error message.
</blockquote></details>

WDYM by the Cairo error message?
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 337 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYm3q9k1dQsvyFNLov3:-NYqoT2k98tnsQwGPSlI:b-lby6ij) ([raw file](https://github.com/starkware-libs/blockifier/blob/5eb52287f5c5299138336e2d00d41e2e94555a65/crates/blockifier/src/execution/syscalls/mod.rs#L337)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice!
I think you can now remove the documentation (it does not add any information over the code).



_Code snippet:_
```XML
    // We assure the requested block number is at least STORED_BLOCK_HASH_BUFFER blocks before the
    // current block.
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 327 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYqnBnf7datLUsc96HN:-NYqnBng35wijoaJ0Fny:b-oxo3vu) ([raw file](https://github.com/starkware-libs/blockifier/blob/186397211abf3912ac5cefcc926cfa7bacc81283/crates/blockifier/src/execution/syscalls/mod.rs#L327)):*
> ```XML
> // Returns the block hash of a given block_number.
> // Returns the expected block hash if the given block was created at least
> // STORED_BLOCK_HASH_BUFFER=10 blocks before the current block. Otherwise, returns an error.
> ```

Don't know if it is good to use constants names.



_Suggestion:_
```XML
// Returns the block hash of a given block_number.
// Returns the expected block hash if the given block was created at least
// some (currently 10) blocks before the current block. Otherwise, returns an error.
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 339 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYqp4Mp3m5SJsTZJ8n_:-NYqp4Mp3m5SJsTZJ8na:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/186397211abf3912ac5cefcc926cfa7bacc81283/crates/blockifier/src/execution/syscalls/mod.rs#L339)):*
> ```XML
>     // We assure the requested block number is at least STORED_BLOCK_HASH_BUFFER blocks before the
>     // current block.
>     // We use checked_sub to avoid underflow when current_block_number < STORED_BLOCK_HASH_BUFFER.
> ```





_Suggestion:_
```XML
    // We use `checked_sub` to avoid underflow when current_block_number is too small.
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 346 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYqpwF44pM4Ljdp4Hy7:-NYqpwF44pM4Ljdp4Hy8:bdl06vs) ([raw file](https://github.com/starkware-libs/blockifier/blob/186397211abf3912ac5cefcc926cfa7bacc81283/crates/blockifier/src/execution/syscalls/mod.rs#L346)):*
> ```XML
>     {
>         return Err(SyscallExecutionError::BlockNumberOutOfRange);
>     }
> ```

Or either match.
I just refrain from using `unwrap()`.



_Suggestion:_
```XML
    if !upper_bound_block_number.is_some_and(|upper_bound_block_number| upper_bound_block_number >= requested_block_number)
        return Err(SyscallExecutionError::BlockNumberOutOfRange);
    }
```


<!-- Sent from Reviewable.io -->

2023-06-26 09:56 UTC, dafnamatsry submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: all files reviewed, 7 unresolved discussions (waiting on @ArniStarkware and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 327 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYqnBnf7datLUsc96HN:-NYr6avN7sraL2ga7XsG:b-d1z1ym) ([raw file](https://github.com/starkware-libs/blockifier/blob/186397211abf3912ac5cefcc926cfa7bacc81283/crates/blockifier/src/execution/syscalls/mod.rs#L327)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Don't know if it is good to use constants names.
</blockquote></details>

The number 10 shouldn't be in the comment. If it changes someday, the chances we will also change it here are very small, and the comment won't be true anymore.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 346 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYqpwF44pM4Ljdp4Hy7:-NYr707V6yh-bVmUq5Go:b-uu2mxr) ([raw file](https://github.com/starkware-libs/blockifier/blob/186397211abf3912ac5cefcc926cfa7bacc81283/crates/blockifier/src/execution/syscalls/mod.rs#L346)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Or either match.
I just refrain from using `unwrap()`.
</blockquote></details>

There is a check with is_none right before the unwrap, so there’s no issue.
The `!..is_some(...)` is much less readable IMO


<!-- Sent from Reviewable.io -->

2023-06-26 11:15 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @dafnamatsry and @noaov1)

___
*[`crates/blockifier/src/abi/constants.rs` line 73 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYqnuoYByOuD-9PAWcw:-NYrAc9L2dKgEMxlhARq:b6ljhiv) ([raw file](https://github.com/starkware-libs/blockifier/blob/186397211abf3912ac5cefcc926cfa7bacc81283/crates/blockifier/src/abi/constants.rs#L73)):*
> ```XML
> 
> // The block number -> block hash mapping is written for the current block number minus this number.
> pub const STORED_BLOCK_HASH_BUFFER: u64 = 10;
> ```

Keeping. This is consistent with the latest name suggested by Lior.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYmQREHDMWVmnvzLeyL:-NYrAxVGC4mvFiTNUGIp:b-e7j8m9) ([raw file](https://github.com/starkware-libs/blockifier/blob/5eb52287f5c5299138336e2d00d41e2e94555a65/crates/blockifier/src/execution/syscalls/hint_processor.rs#L53)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

WDYM by the Cairo error message?
</blockquote></details>

See. https://github.com/starkware-industries/starkware/blob/cairo-v0.12.0/src/starkware/starknet/core/os/constants.cairo#L102
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 337 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYm3q9k1dQsvyFNLov3:-NYrBl68DaR-iL_NuK0s:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5eb52287f5c5299138336e2d00d41e2e94555a65/crates/blockifier/src/execution/syscalls/mod.rs#L337)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Nice!
I think you can now remove the documentation (it does not add any information over the code).
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 327 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYqnBnf7datLUsc96HN:-NYrBSUL7yySu8Hwvplf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/186397211abf3912ac5cefcc926cfa7bacc81283/crates/blockifier/src/execution/syscalls/mod.rs#L327)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

The number 10 shouldn't be in the comment. If it changes someday, the chances we will also change it here are very small, and the comment won't be true anymore.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 339 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYqp4Mp3m5SJsTZJ8n_:-NYrBpws4sTNXYsFtFgD:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/186397211abf3912ac5cefcc926cfa7bacc81283/crates/blockifier/src/execution/syscalls/mod.rs#L339)):*
> ```XML
>     // We assure the requested block number is at least STORED_BLOCK_HASH_BUFFER blocks before the
>     // current block.
>     // We use checked_sub to avoid underflow when current_block_number < STORED_BLOCK_HASH_BUFFER.
> ```

Done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 346 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYqpwF44pM4Ljdp4Hy7:-NYrPQki4lnh0jwgN29e:bac9ix3) ([raw file](https://github.com/starkware-libs/blockifier/blob/186397211abf3912ac5cefcc926cfa7bacc81283/crates/blockifier/src/execution/syscalls/mod.rs#L346)):*
<details><summary><i>Previously, dafnamatsry wrote…</i></summary><blockquote>

There is a check with is_none right before the unwrap, so there’s no issue.
The `!..is_some(...)` is much less readable IMO
</blockquote></details>

Done. Post F2F discussion. 


<!-- Sent from Reviewable.io -->

2023-06-26 11:18 UTC, dafnamatsry submitted a review, later dismissed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: all files reviewed, 7 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-06-26 15:40 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @dafnamatsry)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYmQREHDMWVmnvzLeyL:-NYsBqeR-vBGDYG4mRJk:b-4iewfm) ([raw file](https://github.com/starkware-libs/blockifier/blob/5eb52287f5c5299138336e2d00d41e2e94555a65/crates/blockifier/src/execution/syscalls/hint_processor.rs#L53)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

See. https://github.com/starkware-industries/starkware/blob/cairo-v0.12.0/src/starkware/starknet/core/os/constants.cairo#L102
</blockquote></details>

So shouldn't we re
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 327 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYqnBnf7datLUsc96HN:-NYsD-T79sjC7QXODWhb:blekp1z) ([raw file](https://github.com/starkware-libs/blockifier/blob/186397211abf3912ac5cefcc926cfa7bacc81283/crates/blockifier/src/execution/syscalls/mod.rs#L327)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you please write [STORED_BLOCK_HASH_BUFFER] (so it reference the constant)?
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 346 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYsLgy3BzsJvBNAd_Tc:-NYsLgy3BzsJvBNAd_Td:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/bc61c6ce6880add14c6f09f42d47962b3db8687b/crates/blockifier/src/execution/syscalls/mod.rs#L346)):*
> ```XML
>             .map_err(SyscallExecutionError::from)?;
>         return Err(SyscallExecutionError::SyscallError { error_data: vec![out_of_gas_error] });
>     }
> ```





_Suggestion:_
```XML
    {
        let out_of_range = StarkFelt::try_from(BLOCK_NUMBER_OUT_OF_RANGE_ERROR)
            .map_err(SyscallExecutionError::from)?;
        return Err(SyscallExecutionError::SyscallError { error_data: vec![out_of_range] });
    }
```


<!-- Sent from Reviewable.io -->

2023-06-26 15:56 UTC, Yoni-Starkware reviewed
> Reviewed 2 of 5 files at r1, 2 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 100 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYsKb34DGegfZdpSyYy:-NYsKb34DGegfZdpSyYz:b-gkj4hy) ([raw file](https://github.com/starkware-libs/blockifier/blob/bc61c6ce6880add14c6f09f42d47962b3db8687b/crates/blockifier/src/test_utils.rs#L100)):*
> ```XML
> pub const DEFAULT_GAS_PRICE: u128 = 100 * u128::pow(10, 9); // Given in units of wei.
> 
> // Block Number.
> ```

The name is clear enough (next PR)


<!-- Sent from Reviewable.io -->

2023-06-27 05:58 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @dafnamatsry, @noaov1, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 100 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYsKb34DGegfZdpSyYy:-NYvPPK528DlWPFuXw5Q:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bc61c6ce6880add14c6f09f42d47962b3db8687b/crates/blockifier/src/test_utils.rs#L100)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

The name is clear enough (next PR)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYmQREHDMWVmnvzLeyL:-NYvPxkx8gs_GPCPrN5R:b8chhy4) ([raw file](https://github.com/starkware-libs/blockifier/blob/5eb52287f5c5299138336e2d00d41e2e94555a65/crates/blockifier/src/execution/syscalls/hint_processor.rs#L53)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

..turn it as a cairo 1 error? (with `failure_flag = 1`).
</blockquote></details>

We talked F2F.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 327 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYqnBnf7datLUsc96HN:-NYsQ3jU7xX9QMXozW5Z:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/186397211abf3912ac5cefcc926cfa7bacc81283/crates/blockifier/src/execution/syscalls/mod.rs#L327)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please write [STORED_BLOCK_HASH_BUFFER] (so it reference the constant)?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 346 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYsLgy3BzsJvBNAd_Tc:-NYvPwmN9R3xh-_JQVc_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bc61c6ce6880add14c6f09f42d47962b3db8687b/crates/blockifier/src/execution/syscalls/mod.rs#L346)):*
> ```XML
>             .map_err(SyscallExecutionError::from)?;
>         return Err(SyscallExecutionError::SyscallError { error_data: vec![out_of_gas_error] });
>     }
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-06-27 06:17 UTC, dafnamatsry submitted a review, later dismissed
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: all files reviewed, 3 unresolved discussions (waiting on @noaov1 and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2023-06-27 06:38 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware, @dafnamatsry, and @noaov1)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 341 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYvZbl_Cl9bzwnKMNxE:-NYvZbl_Cl9bzwnKMNxF:bx67jr1) ([raw file](https://github.com/starkware-libs/blockifier/blob/bc61c6ce6880add14c6f09f42d47962b3db8687b/crates/blockifier/src/execution/syscalls/mod.rs#L341)):*
> ```XML
>         || requested_block_number
>             > upper_bound_block_number
>                 .expect("Underflow occurred while computing upper_bound_block_number.")
> ```

Why is it needed, and why in this location?



_Code quote:_
```XML
.expect(
```


<!-- Sent from Reviewable.io -->

2023-06-27 06:42 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: all files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYN5hxm5kz7eX7i3QPA:-NYv_h_66WwgiAW_W9EE:bg7igkv) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Also needs a test for the negative flow.
</blockquote></details>

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

___


<!-- Sent from Reviewable.io -->

2023-06-27 06:45 UTC, noaov1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware)



<!-- Sent from Reviewable.io -->

2023-06-27 06:59 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @dafnamatsry and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 341 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/641#-NYvZbl_Cl9bzwnKMNxE:-NYvd2vN3HDB5mFJzGb9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/bc61c6ce6880add14c6f09f42d47962b3db8687b/crates/blockifier/src/execution/syscalls/mod.rs#L341)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why is it needed, and why in this location?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-27 07:37 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r13, 1 of 2 files at r14, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/641#-:-NYvmMmI8IKJjxy1pTqO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)



<!-- Sent from Reviewable.io -->

2023-06-27 07:41 UTC, merged