Adding Cairo1 account contract to test_declare_tx
starkware-libs/blockifier pull request #649
Opened 2023-06-22 15:42 UTC by MohammadNassar1

2023-06-27 06:24 UTC, noaov1 requested changes
Nice!

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/649#-:-NYvWST45QXmO5wbKu3N:b-83sjoh)* status: 0 of 35 files reviewed, 12 unresolved discussions (waiting on @alonh5 and @MohammadNassar1)

___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 15 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvOwJk7yTTWvNUCQpI:-NYvOwJl8Y0YSTVrjpW_:bxtub52) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/feature_contracts/cairo1/account.cairo#L15)):*
> ```Cairo
>     struct Storage {
>         public_key: felt252
>     }
> ```

Is it needed?



_Code quote:_
```Cairo
    #[storage]
    struct Storage {
        public_key: felt252
    }
```
___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 24 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvRkQRChXZ_nQTD2dg:-NYvRkQRChXZ_nQTD2dh:bwk9rfi) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/feature_contracts/cairo1/account.cairo#L24)):*
> ```Cairo
>     trait StorageTrait {
>         fn validate_transaction(self: @ContractState) -> felt252;
>     }
> ```

Do we need to define traits in order to define functions?



_Code quote:_
```Cairo
    trait StorageTrait {
        fn validate_transaction(self: @ContractState) -> felt252;
    }
```
___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 38 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvQZMi9SHg5KuMHQ6e:-NYvQZMi9SHg5KuMHQ6f:b4b5ikc) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/feature_contracts/cairo1/account.cairo#L38)):*
> ```Cairo
>             //     ),
>             //     'INVALID_SIGNATURE',
>             // );
> ```

Can you please remove?
Do we want to keep `validate_transaction` in case of a non-trivial validation? Do you think it's needed?



_Code quote:_
```Cairo
            // let tx_info = starknet::get_tx_info().unbox();
            // let signature = tx_info.signature;
            // assert(signature.len() == 2_u32, 'INVALID_SIGNATURE_LENGTH');
            // assert(
            //     check_ecdsa_signature(
            //         message_hash: tx_info.transaction_hash,
            //         public_key: self.public_key.read(),
            //         signature_r: *signature[0_u32],
            //         signature_s: *signature[1_u32],
            //     ),
            //     'INVALID_SIGNATURE',
            // );
```
___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 56 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvSCfK9EOg-2uwTbvL:-NYvSCfL6jdalBif5vuU:b-pzceyu) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/feature_contracts/cairo1/account.cairo#L56)):*
> ```Cairo
> 
>     #[external(v0)]
>     impl AccountContractImpl of starknet::account::AccountContract<ContractState> {
> ```

I wonder if we want to create that kind of dependency on the Cairo repo. What is the purpose of this trait and why is using it better than simply defining methods?



_Code quote:_
```Cairo
impl AccountContractImpl of starknet::account::AccountContract<ContractState>
```
___
*[`crates/blockifier/feature_contracts/cairo1/compiled/account_contract.sierra.json` line 1 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvLUCLA3cNZHI8rTgW:-NYvLUCLA3cNZHI8rTgX:b9rza9c) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/feature_contracts/cairo1/compiled/account_contract.sierra.json#L1)):*
> ```JSON
> {
> ```

Do we need the sierra file as well?
___
*[`crates/blockifier/src/test_utils.rs` line 48 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvLOTo3lB6C1p-O-tN:-NYvLOTo3lB6C1p-O-tO:bxtub52) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/src/test_utils.rs#L48)):*
> ```XML
> pub const TEST_ACCOUNT_CONTRACT_ADDRESS: &str = "0x101";
> pub const TEST_FAULTY_ACCOUNT_CONTRACT_ADDRESS: &str = "0x102";
> pub const TEST_CAIRO1_ACCOUNT_CONTRACT_ADDRESS: &str = "0x201";
> ```

Is it needed?



_Code quote:_
```XML
pub const TEST_CAIRO1_ACCOUNT_CONTRACT_ADDRESS: &str = "0x201";
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvEllM35SUKO1Bh-5Y:-NYvEllM35SUKO1Bh-5Z:b-n6d6dn) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/src/transaction/transactions_test.rs#L2)):*
> ```XML
> use std::collections::HashMap;
> // use std::default;
> ```

Please remove



_Code quote:_
```XML
// use std::default;
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 99 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvJO9d-kfKQQBQy65s:-NYvJO9d-kfKQQBQy65t:b2j9uow) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/src/transaction/transactions_test.rs#L99)):*
> ```XML
> }
> 
> fn create_cairo1_account_tx_test_state(
> ```

Is it possible to merge it with the existing function `create_account_tx_test_state`?



_Code quote:_
```XML
fn create_cairo1_account_tx_test_state(
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 113 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvFzp241fArxrA3jD5:-NYvFzp241fArxrA3jD6:b9fn81s) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/src/transaction/transactions_test.rs#L113)):*
> ```XML
>     let class_hash_to_class = HashMap::from([
>         (test_account_class_hash, ContractClassV1::from_file(account_path).into()),
>         (test_contract_class_hash, ContractClassV0::from_file(TEST_CONTRACT_PATH).into()),
> ```

Don't we want to use the Cairo 1 test contract?



_Suggestion:_
```XML
(test_contract_class_hash, ContractClassV1::from_file(TEST_CONTRACT_PATH).into()),
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 144 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvW6gt6zgWqJxw-vXg:-NYvW6gt6zgWqJxw-vXh:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/src/transaction/transactions_test.rs#L144)):*
> ```XML
>     class_hash: ClassHash,
>     entry_point_selector_name: &str,
>     expected_returned_data: Retdata,
> ```





_Suggestion:_
```XML
return_data: Retdata,
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 551 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvKhjCDYSATEFvNgB7:-NYvKhjCDYSATEFvNgB8:b-i011yi) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/src/transaction/transactions_test.rs#L551)):*
> ```XML
>     let expected_account_class_hash = ClassHash(stark_felt!(TEST_ACCOUNT_CONTRACT_CLASS_HASH));
>     let expected_account_address = ContractAddress(patricia_key!(TEST_ACCOUNT_CONTRACT_ADDRESS));
>     let expected_returned_data = if account_path.contains("cairo1") {
> ```

Can this be an input of `test_declare_tx()`?



_Code quote:_
```XML
let expected_returned_data = if account_path.contains("cairo1") {
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 589 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvLCaJD5XCoLhoQoP7:-NYvLCaJD5XCoLhoQoP8:b-ya81ng) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/src/transaction/transactions_test.rs#L589)):*
> ```XML
>             (HASH_ [...]

2023-07-02 11:56 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/649)* status: 0 of 35 files reviewed, 12 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 15 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvOwJk7yTTWvNUCQpI:-NZKmrPdCBprm5Uh94K5:bkmyoh2) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/feature_contracts/cairo1/account.cairo#L15)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it needed?
</blockquote></details>

Actually, it is needed for any Cairo 1.0 contract to have a storage.
Got this error when removing the storage:
`Contracts must define a 'Storage' struct.`
___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 24 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvRkQRChXZ_nQTD2dg:-NZKnHI98JIFsSkozBly:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/feature_contracts/cairo1/account.cairo#L24)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do we need to define traits in order to define functions?
</blockquote></details>

Done.
___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 38 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvQZMi9SHg5KuMHQ6e:-NZKnJNs4qWIQCKnm8RA:bss4a1y) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/feature_contracts/cairo1/account.cairo#L38)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can you please remove?
Do we want to keep `validate_transaction` in case of a non-trivial validation? Do you think it's needed?
</blockquote></details>

Removed!
___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 56 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvSCfK9EOg-2uwTbvL:-NZLSSpICa4qK71pPK5-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/feature_contracts/cairo1/account.cairo#L56)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I wonder if we want to create that kind of dependency on the Cairo repo. What is the purpose of this trait and why is using it better than simply defining methods?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils.rs` line 48 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvLOTo3lB6C1p-O-tN:-NZKnd-EA7vLre57MBUX:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/src/test_utils.rs#L48)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it needed?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 2 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvEllM35SUKO1Bh-5Y:-NZKne751_O7eXI5nhvr:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/src/transaction/transactions_test.rs#L2)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Please remove
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 99 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvJO9d-kfKQQBQy65s:-NZKqG_FA3-iQ7NIuK6_:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/src/transaction/transactions_test.rs#L99)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it possible to merge it with the existing function `create_account_tx_test_state`?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 113 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvFzp241fArxrA3jD5:-NZKqKjb4B1gk7Q1SJ6D:bwov9c) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/src/transaction/transactions_test.rs#L113)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Don't we want to use the Cairo 1 test contract?
</blockquote></details>

This is a good question. Meanwhile, I've started using only Cairo 1.0 account contract for other tests. The next step is to use Cairo 1.0 test contract.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 144 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvW6gt6zgWqJxw-vXg:-NZKr6Pr3PYYXzRFg7Jw:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/src/transaction/transactions_test.rs#L144)):*
> ```XML
>     class_hash: ClassHash,
>     entry_point_selector_name: &str,
>     expected_returned_data: Retdata,
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 551 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvKhjCDYSATEFvNgB7:-NZKrRsG5bZQS7ibw6j9:b-kzx2zs) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/src/transaction/transactions_test.rs#L551)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can this be an input of `test_declare_tx()`?
</blockquote></details>

Do you suggest to change the input to `expected_retured_data`? or a boolean variable of isCairo1Account?
___
*[`crates/blockifier/feature_contracts/cairo1/compiled/account_contract.sierra.json` line 1 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvLUCLA3cNZHI8rTgW:-NZKnbwNBiEgmQK0YcDd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/feature_contracts/cairo1/compiled/account_contract.sierra.json#L1)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Do we need the sierra file as well?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-03 09:16 UTC, noaov1 requested changes
> Reviewed 3 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/649)* status: 3 of 35 files reviewed, 12 unresolved discussions (waiting on @alonh5 and @MohammadNassar1)

___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 15 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvOwJk7yTTWvNUCQpI:-NZPht5Z9-3ryGAqWeXf:b-pcqtf8) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/feature_contracts/cairo1/account.cairo#L15)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Actually, it is needed for any Cairo 1.0 contract to have a storage.
Got this error when removing the storage:
`Contracts must define a 'Storage' struct.`
</blockquote></details>

Interesting. Can you please remove the public key?
___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 22 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZPjJzFB-RNR2i1NPhq:-NZPjJzFB-RNR2i1NPhr:bxtub52) ([raw file](https://github.com/starkware-libs/blockifier/blob/a220d98dde7727ba8606391512ad59e6ad394016/crates/blockifier/feature_contracts/cairo1/account.cairo#L22)):*
> ```Cairo
>         class_hash: felt252,
>         contract_address_salt: felt252,
>         public_key_: felt252
> ```

Is it needed?



_Code quote:_
```Cairo
        public_key_: felt252
```
___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 27 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZPjvrrDkEvAtwIbLSc:-NZPjvrrDkEvAtwIbLSd:b-3qedzp) ([raw file](https://github.com/starkware-libs/blockifier/blob/a220d98dde7727ba8606391512ad59e6ad394016/crates/blockifier/feature_contracts/cairo1/account.cairo#L27)):*
> ```Cairo
>     }
> 
>     #[external(v0)]
> ```

What is the meaning of this decorator? 
Why do we use  `#[external]` in `__validate_deploy__`?
Why isn't it needed for `__validate__` and `__execute__`?



_Code quote:_
```Cairo
#[external(v0)]
```
___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 42 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZPmN976rArmbFt_zIe:-NZPmN976rArmbFt_zIf:bhuovdb) ([raw file](https://github.com/starkware-libs/blockifier/blob/a220d98dde7727ba8606391512ad59e6ad394016/crates/blockifier/feature_contracts/cairo1/account.cairo#L42)):*
> ```Cairo
>         // Check the tx version here, since version 0 transaction skip the __validate__ function.
>         let tx_info = starknet::get_tx_info().unbox();
>         assert(tx_info.version != 0, 'INVALID_TX_VERSION');
> ```

What does it have to do with `__execute__`?
Invoke version 0 did not have to go via `__execute__`. 



_Code quote:_
```Cairo
        // Check the tx version here, since version 0 transaction skip the __validate__ function.
        let tx_info = starknet::get_tx_info().unbox();
        assert(tx_info.version != 0, 'INVALID_TX_VERSION');
```
___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 57 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZPmEcn47umB2QpZlP4:-NZPmEcn47umB2QpZlP5:bp47o1t) ([raw file](https://github.com/starkware-libs/blockifier/blob/a220d98dde7727ba8606391512ad59e6ad394016/crates/blockifier/feature_contracts/cairo1/account.cairo#L57)):*
> ```Cairo
>                 },
>                 Option::None(()) => {
>                     break; // Can't break result; because of 'variable was previously moved'
> ```

What does it mean? (out of curiosity :))



_Code quote:_
```Cairo
break; // Can't break result; because of 'variable was previously moved'
```
___
*[`crates/blockifier/src/test_utils.rs` line 64 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZPsmqB13Ru7L85hJs4:-NZPsmqB13Ru7L85hJs5:b-izkpme) ([raw file](https://github.com/starkware-libs/blockifier/blob/a220d98dde7727ba8606391512ad59e6ad394016/crates/blockifier/src/test_utils.rs#L64)):*
> ```XML
> pub const CAIRO1_ACCOUNT_CONTRACT_PATH: &str =
>     "./feature_contracts/cairo1/compiled/account_contract.casm.json";
> pub const ACCOUNT_CONTRACT_PATH: &str =
> ```

In a separate PR



_Suggestion:_
```XML
CAIRO0_ACCOUNT_CONTRACT_PATH
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 113 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvFzp241fArxrA3jD5:-NZPsKQm8b2YpkHlk-Gv:bna1tte) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/src/transaction/transactions_test.rs#L113)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

This is a good question. Meanwhile, I've started using only Cairo 1.0 account contract for other tests. The next step is to use Cairo 1.0 test contract.
</blockquote></details>

Got it. Great. Add a TODO?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 144 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvW6gt6zgWqJxw-vXg:-NZPsXIV7YbGfD4rmSHh:b-9agazq) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/src/transaction/transactions_test.rs#L144)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`return` :)
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 551 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvKhjCDYSATEFvNgB7:-NZQ0M4yDAHwtgybCPtS:bga4c0b) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/src/transaction/transactions_test.rs#L551)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Do you suggest to change the input to `expected_retured_data`? or a boolean variable of isCairo1Account?
</blockquote></details>

To add an input `expected_retured_data`.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 68 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZPs0t8Eee6FUVMaLMs:-NZPs0t926wBH1hKooW5:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/a220d98dde7727ba8606391512ad59e6ad394016/crates/blockifier/src/transaction/transactions_test.rs#L68)):*
> ```XML
>     let test_account_class_hash = ClassHash(stark_felt!(account_class_hash));
>     let test_erc20_class_hash = ClassHash(stark_felt!(TEST_ERC20_CONTRACT_CLASS_HASH));
>     let account_class_hash = if account_path.contains("cairo1") {
> ```





_Suggestion:_
```XML
account_contract_class
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 136 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZPsT151csWtheXCCGR:-NZPsT151csWtheXCCGS:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/a220d98dde7727ba8606391512ad59e6ad394016/crates/blockifier/src/transaction/transactions_test.rs#L136)):*
> ```XML
>         },
>         // The account contract we use for testing has trivial `validate` functions.
>         execution: CallExecution { retdata: (returned_data), ..Default::default() },
> ```





_Suggestion:_
```XML
returned_data
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 284 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZPswKNATW0WEAZpBLi:-NZPswKNATW0WEAZpBLj:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/a220d98dde7727ba8606391512ad59e6ad394016/crates/blockifier/src/transaction/transactions_test.rs#L284)):*
> ```XML
>     let expected_account_class_hash = ClassHash(stark_felt!(TEST_ACCOUNT_CONTRACT_CLASS_HASH));
>     let expected_account_address = ContractAddress(patricia_key!(TEST_ACCOUNT_CONTRACT_ADDRESS));
>     let expected_returned_data = Retdata::default();
> ```





_Suggestion:_
```XML
expe [...]

2023-07-03 13:53 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/649)* status: 1 of 35 files reviewed, 12 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 15 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvOwJk7yTTWvNUCQpI:-NZQjO1y8wI-fo7UO966:b-frl4np) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/feature_contracts/cairo1/account.cairo#L15)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Interesting. Can you please remove the public key?
</blockquote></details>

It was removed on the 2nd PR.
___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 22 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZPjJzFB-RNR2i1NPhq:-NZQjuLvCsNs2dkasaCp:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a220d98dde7727ba8606391512ad59e6ad394016/crates/blockifier/feature_contracts/cairo1/account.cairo#L22)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Is it needed?
</blockquote></details>

Done.
___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 27 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZPjvrrDkEvAtwIbLSc:-NZQkAKK0bmtfKkHnqh4:bjus88n) ([raw file](https://github.com/starkware-libs/blockifier/blob/a220d98dde7727ba8606391512ad59e6ad394016/crates/blockifier/feature_contracts/cairo1/account.cairo#L27)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What is the meaning of this decorator? 
Why do we use  `#[external]` in `__validate_deploy__`?
Why isn't it needed for `__validate__` and `__execute__`?
</blockquote></details>

I've added `#[external(v0)]` to all the functions. We need it to enable using functions in the transactions_test.rs file.
The new compiler version doesn't support `#[external]`
___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 42 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZPmN976rArmbFt_zIe:-NZQo1X24WqimAE51eQf:b-n3rid4) ([raw file](https://github.com/starkware-libs/blockifier/blob/a220d98dde7727ba8606391512ad59e6ad394016/crates/blockifier/feature_contracts/cairo1/account.cairo#L42)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What does it have to do with `__execute__`?
Invoke version 0 did not have to go via `__execute__`. 
</blockquote></details>

You're right, we enable using invoke v0.
Removed!
___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 57 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZPmEcn47umB2QpZlP4:-NZQyLGuCx2VFYso4c-C:b-ov7aw6) ([raw file](https://github.com/starkware-libs/blockifier/blob/a220d98dde7727ba8606391512ad59e6ad394016/crates/blockifier/feature_contracts/cairo1/account.cairo#L57)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

What does it mean? (out of curiosity :))
</blockquote></details>

No idea :), I removed it.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 113 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvFzp241fArxrA3jD5:-NZQv_oQ42NzgAP5W6iT:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/src/transaction/transactions_test.rs#L113)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Got it. Great. Add a TODO?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 136 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZPsT151csWtheXCCGR:-NZQvlQo02-eVpgcXaIJ:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a220d98dde7727ba8606391512ad59e6ad394016/crates/blockifier/src/transaction/transactions_test.rs#L136)):*
> ```XML
>         },
>         // The account contract we use for testing has trivial `validate` functions.
>         execution: CallExecution { retdata: (returned_data), ..Default::default() },
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 284 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZPswKNATW0WEAZpBLi:-NZQwMk7CJt7SuuqiNhs:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a220d98dde7727ba8606391512ad59e6ad394016/crates/blockifier/src/transaction/transactions_test.rs#L284)):*
> ```XML
>     let expected_account_class_hash = ClassHash(stark_felt!(TEST_ACCOUNT_CONTRACT_CLASS_HASH));
>     let expected_account_address = ContractAddress(patricia_key!(TEST_ACCOUNT_CONTRACT_ADDRESS));
>     let expected_returned_data = Retdata::default();
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-07-04 08:47 UTC, noaov1 approved these changes
> Reviewed 2 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/649)* status: 3 of 35 files reviewed, 7 unresolved discussions (waiting on @alonh5 and @MohammadNassar1)

___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 22 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZPjJzFB-RNR2i1NPhq:-NZUwWGd0h0mLE_JyvM5:bfofhjd) ([raw file](https://github.com/starkware-libs/blockifier/blob/a220d98dde7727ba8606391512ad59e6ad394016/crates/blockifier/feature_contracts/cairo1/account.cairo#L22)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I saw you removed it in the next PR :)
___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 57 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZPmEcn47umB2QpZlP4:-NZUx2UI6i91MLeJYuXt:b-psysl9) ([raw file](https://github.com/starkware-libs/blockifier/blob/a220d98dde7727ba8606391512ad59e6ad394016/crates/blockifier/feature_contracts/cairo1/account.cairo#L57)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

No idea :), I removed it.
</blockquote></details>

Maybe ask someone from the compilers team?
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 68 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZV4Ce7DGU3zHXxHv9U:-NZV4Ce7DGU3zHXxHv9V:b8c0v51) ([raw file](https://github.com/starkware-libs/blockifier/blob/978aa414461a696248402cf8140b37ce5c7b47f7/crates/blockifier/src/transaction/transactions_test.rs#L68)):*
> ```XML
>     let test_account_class_hash = ClassHash(stark_felt!(account_class_hash));
>     let test_erc20_class_hash = ClassHash(stark_felt!(TEST_ERC20_CONTRACT_CLASS_HASH));
>     let account_class_hash = if account_path.contains("cairo1") {
> ```

Maybe it's better to pass directly a `ContractClass` object. WDYT?



_Code quote:_
```XML
if account_path.contains("cairo1")
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 75 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZV0LA09wcXi3tZioVM:-NZV0LA09wcXi3tZioVN:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/978aa414461a696248402cf8140b37ce5c7b47f7/crates/blockifier/src/transaction/transactions_test.rs#L75)):*
> ```XML
>     let class_hash_to_class = HashMap::from([
>         (test_account_class_hash, account_class_hash),
>         // TODO(Mohammad,01/08/2023): Use Cairo 1 test contract.
> ```





_Suggestion:_
```XML
// TODO(Mohammad,01/08/2023): Use Cairo 1 test contract when running Cairo 1 account contract. 
```


<!-- Sent from Reviewable.io -->

2023-07-05 08:10 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/649)* status: 3 of 35 files reviewed, 7 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/feature_contracts/cairo1/account.cairo` line 57 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZPmEcn47umB2QpZlP4:-NZXB2AA0cf7dGAVbowu:b-5knbjb) ([raw file](https://github.com/starkware-libs/blockifier/blob/a220d98dde7727ba8606391512ad59e6ad394016/crates/blockifier/feature_contracts/cairo1/account.cairo#L57)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Maybe ask someone from the compilers team?
</blockquote></details>

I've changed the code in `__execute__`, the new code doesn't use it. Please see 3rd PR :)


<!-- Sent from Reviewable.io -->

2023-07-05 08:35 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/649)* status: 3 of 35 files reviewed, 7 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/test_utils.rs` line 64 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZPsmqB13Ru7L85hJs4:-NZ_B4qa-neHespu7qv2:b-uy08tk) ([raw file](https://github.com/starkware-libs/blockifier/blob/a220d98dde7727ba8606391512ad59e6ad394016/crates/blockifier/src/test_utils.rs#L64)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

In a separate PR
</blockquote></details>

Changed in PR #711 


<!-- Sent from Reviewable.io -->

2023-07-05 15:26 UTC, noaov1 reviewed
> Reviewed 3 of 34 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/649)* status: 5 of 53 files reviewed, 6 unresolved discussions (waiting on @alonh5 and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 65 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZadLEEDb8mVAgbgdSx:-NZadLEEDb8mVAgbgdSy:bueu347) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8ae78ad7fbf5e70a3cb33645e40d5e88494b842/crates/blockifier/src/transaction/transactions_test.rs#L65)):*
> ```XML
>     class_hash: ClassHash,
>     entry_point_selector_name: &str,
>     return_data: Retdata,
> ```

You can also have an empty return data for the Cairo1 contract (avoiding this parameter), no?



_Code quote:_
```XML
return_data: Retdata,
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 89 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZa02eKD2PXZnYibp3d:-NZa02eKD2PXZnYibp3e:b6hegi6) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8ae78ad7fbf5e70a3cb33645e40d5e88494b842/crates/blockifier/src/transaction/transactions_test.rs#L89)):*
> ```XML
>         (constants::VALIDATE_ENTRY_POINT_NAME, CairoVersion::Cairo1) => 21_usize,
>         (selector, _) => panic!("Selector {selector} is not a known validate selector."),
>     };
> ```

Maybe use a `match` inside `match`?



_Code quote:_
```XML
    let n_steps = match (entry_point_selector_name, cairo_version) {
        (constants::VALIDATE_DEPLOY_ENTRY_POINT_NAME, CairoVersion::Cairo0) => 13_usize,
        (constants::VALIDATE_DEPLOY_ENTRY_POINT_NAME, CairoVersion::Cairo1) => 13_usize,
        (constants::VALIDATE_DECLARE_ENTRY_POINT_NAME, CairoVersion::Cairo0) => 12_usize,
        (constants::VALIDATE_DECLARE_ENTRY_POINT_NAME, CairoVersion::Cairo1) => 54_usize,
        (constants::VALIDATE_ENTRY_POINT_NAME, CairoVersion::Cairo0) => 21_usize,
        (constants::VALIDATE_ENTRY_POINT_NAME, CairoVersion::Cairo1) => 21_usize,
        (selector, _) => panic!("Selector {selector} is not a known validate selector."),
    };
```


<!-- Sent from Reviewable.io -->

2023-07-05 15:54 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/649)* status: 5 of 53 files reviewed, 8 unresolved discussions (waiting on @alonh5 and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 73 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZakS2J1ihj0XKuMH-v:-NZakS2J1ihj0XKuMH-w:bybv597) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8ae78ad7fbf5e70a3cb33645e40d5e88494b842/crates/blockifier/src/transaction/test_utils.rs#L73)):*
> ```XML
> }
> 
> pub fn create_state_with_trivial_validation_account() -> CachedState<DictStateReader> {
> ```

Can be done in the next PR



_Suggestion:_
```XML
create_state_with_trivial_validation_cairo0_account
```
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 84 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZakY6EC0JQxlD-Moij:-NZakY6EC0JQxlD-Moik:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8ae78ad7fbf5e70a3cb33645e40d5e88494b842/crates/blockifier/src/transaction/test_utils.rs#L84)):*
> ```XML
> }
> 
> pub fn create_state_with_cairo1_account() -> CachedState<DictStateReader> {
> ```





_Suggestion:_
```XML
create_state_with_trivial_validation_cairo1_account
```


<!-- Sent from Reviewable.io -->

2023-07-05 18:24 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/649)* status: 5 of 53 files reviewed, 8 unresolved discussions (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/test_utils.rs` line 73 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZakS2J1ihj0XKuMH-v:-NZbI7Iz5OKMhBFStaKT:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8ae78ad7fbf5e70a3cb33645e40d5e88494b842/crates/blockifier/src/transaction/test_utils.rs#L73)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Can be done in the next PR
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/test_utils.rs` line 84 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZakY6EC0JQxlD-Moij:-NZbI8HH99aj0wuChB7L:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8ae78ad7fbf5e70a3cb33645e40d5e88494b842/crates/blockifier/src/transaction/test_utils.rs#L84)):*
> ```XML
> }
> 
> pub fn create_state_with_cairo1_account() -> CachedState<DictStateReader> {
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 589 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NYvLCaJD5XCoLhoQoP7:-NZbI2y8ESPh0VJfefap:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/c61a6bcc24740da8650ac105f960497ea784e0d7/crates/blockifier/src/transaction/transactions_test.rs#L589)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 68 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZPs0t8Eee6FUVMaLMs:-NZbI9GW8iPgxbNqQVxU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/a220d98dde7727ba8606391512ad59e6ad394016/crates/blockifier/src/transaction/transactions_test.rs#L68)):*
> ```XML
>     let test_account_class_hash = ClassHash(stark_felt!(account_class_hash));
>     let test_erc20_class_hash = ClassHash(stark_felt!(TEST_ERC20_CONTRACT_CLASS_HASH));
>     let account_class_hash = if account_path.contains("cairo1") {
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 68 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZV4Ce7DGU3zHXxHv9U:-NZbI9fW09Ahh5c5Rw2r:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/978aa414461a696248402cf8140b37ce5c7b47f7/crates/blockifier/src/transaction/transactions_test.rs#L68)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Maybe it's better to pass directly a `ContractClass` object. WDYT?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 75 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZV0LA09wcXi3tZioVM:-NZbHlRRDuQNp-Il4MC4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/978aa414461a696248402cf8140b37ce5c7b47f7/crates/blockifier/src/transaction/transactions_test.rs#L75)):*
> ```XML
>     let class_hash_to_class = HashMap::from([
>         (test_account_class_hash, account_class_hash),
>         // TODO(Mohammad,01/08/2023): Use Cairo 1 test contract.
> ```

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 65 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZadLEEDb8mVAgbgdSx:-NZbHmOu0CzVLD6H_pil:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8ae78ad7fbf5e70a3cb33645e40d5e88494b842/crates/blockifier/src/transaction/transactions_test.rs#L65)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

You can also have an empty return data for the Cairo1 contract (avoiding this parameter), no?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 89 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZa02eKD2PXZnYibp3d:-NZbHnIZEQfVq9FSEflt:b345sg4) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8ae78ad7fbf5e70a3cb33645e40d5e88494b842/crates/blockifier/src/transaction/transactions_test.rs#L89)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Maybe use a `match` inside `match`?
</blockquote></details>

I'll check a similar code in Blockifier!


<!-- Sent from Reviewable.io -->

2023-07-06 06:21 UTC, noaov1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/649)* status: 5 of 53 files reviewed, 1 unresolved discussion (waiting on @alonh5)



<!-- Sent from Reviewable.io -->

2023-07-06 06:23 UTC, noaov1 reviewed
> Reviewed 16 of 30 files at r3, 1 of 5 files at r7, 31 of 34 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/649)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5)



<!-- Sent from Reviewable.io -->

2023-07-06 06:34 UTC, noaov1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/649)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 65 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZadLEEDb8mVAgbgdSx:-NZdu5LF6E8qDTY_hmN0:bp3kjc) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8ae78ad7fbf5e70a3cb33645e40d5e88494b842/crates/blockifier/src/transaction/transactions_test.rs#L65)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Will be in another PR. 


<!-- Sent from Reviewable.io -->

2023-07-06 06:34 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/649)* status: all files reviewed, 1 unresolved discussion (waiting on @alonh5 and @noaov1)

___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 65 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/649#-NZadLEEDb8mVAgbgdSx:-NZduFXMAG_zbkzdzpOf:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d8ae78ad7fbf5e70a3cb33645e40d5e88494b842/crates/blockifier/src/transaction/transactions_test.rs#L65)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Will be in another PR. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-06 06:38 UTC, noaov1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/649)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alonh5)



<!-- Sent from Reviewable.io -->

2023-07-06 06:38 UTC, merged