add n_reverted_steps to the flow
starkware-libs/blockifier pull request #677
Opened 2023-06-28 08:29 UTC by zuphitf

2023-06-28 08:49 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/677)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 419 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZ0AJTZ-LnOzYJ4BRXB:-NZ0AJTZ-LnOzYJ4BRXC:bb2xyy6) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c131cf61233a30cac136006d2a0177334de1038/crates/blockifier/src/transaction/account_transaction.rs#L419)):*
> ```XML
>                 execution_state.abort();
>                 let n_reverted_steps = (max_n_steps as usize)
>                     - context.vm_run_resources.get_n_steps().unwrap_or_default();
> ```

The RunResources contains an `Option<usize>` as the n_steps, right?
I think you should use `unwrap()` here, because a `None` value means *unbounded* number of steps.
1. We should always bound the number of steps in an account tx, so this should never be None
2. If it is None, we cannot compute the resources used. The default value of 0 means we will always take `max_n_steps` fee in these cases (seems wrong)



_Code quote:_
```XML
unwrap_or_default()
```


<!-- Sent from Reviewable.io -->

2023-06-29 14:58 UTC, zuphitf commented
*[`crates/blockifier/src/transaction/account_transaction.rs` line 419 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZ0AJTZ-LnOzYJ4BRXB:-NZ6eQE9AQ0PvlxgN3zl:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/5c131cf61233a30cac136006d2a0177334de1038/crates/blockifier/src/transaction/account_transaction.rs#L419)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

The RunResources contains an `Option<usize>` as the n_steps, right?
I think you should use `unwrap()` here, because a `None` value means *unbounded* number of steps.
1. We should always bound the number of steps in an account tx, so this should never be None
2. If it is None, we cannot compute the resources used. The default value of 0 means we will always take `max_n_steps` fee in these cases (seems wrong)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-01 17:27 UTC, dorimedini-starkware requested changes
> Reviewed 7 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/677)* status: all files reviewed, 7 unresolved discussions (waiting on @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 375 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZHSK1D7UoFryIrCTJf:-NZHSK1D7UoFryIrCTJg:bynewbg) ([raw file](https://github.com/starkware-libs/blockifier/blob/737dec711cbaaf4a8b7f794f143ce1b8182470c5/crates/blockifier/src/transaction/account_transactions_test.rs#L375)):*
> ```XML
> /// the delta of two consecutive recursive successful transactions.
> /// In this test reverted transactions are valid function calls that got insufficient steps limit.
> fn test_reverted_reach_steps_limit() {
> ```

instead of `0, 1, 237, 238` please use `small_recurse, small_recurse + diff_recurse, large_recurse, large_recurse + diff_recurse` (so reader sees how the four scenarios relate)
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 401 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZHRJ1yDJqxK-OrxAUy:-NZHRJ1yDJqxK-OrxAUz:bm50mbv) ([raw file](https://github.com/starkware-libs/blockifier/blob/737dec711cbaaf4a8b7f794f143ce1b8182470c5/crates/blockifier/src/transaction/account_transactions_test.rs#L401)):*
> ```XML
>         ..tx
>     }));
>     let res = account_tx.execute(&mut state, &block_context).unwrap();
> ```

rename to `result`, everywhere



_Code quote:_
```XML
res
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 405 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZHRwcR4qbfkVfEDz6C:-NZHRwcSBx5d6j-AHdln:b-qxu5tf) ([raw file](https://github.com/starkware-libs/blockifier/blob/737dec711cbaaf4a8b7f794f143ce1b8182470c5/crates/blockifier/src/transaction/account_transactions_test.rs#L405)):*
> ```XML
>     let actual_fee_0 = res.actual_fee.0;
>     // Ensure the transaction was not reverted.
>     assert!(!res.is_reverted());
> ```

define and use a `run_scenario(depth: u8) -> (usize, u128)`?
you repeat this logic 4 times (it only depends on depth)
you may also end up removing `create_calldata` after this refactor, you only need to create it once



_Code quote:_
```XML
    let execute_calldata = create_calldata(&contract_address, 0);
    let tx = invoke_tx(execute_calldata, account_address, max_fee, None);
    let account_tx = AccountTransaction::Invoke(InvokeTransaction::V1(InvokeTransactionV1 {
        nonce: nonce_manager.next(account_address),
        ..tx
    }));
    let res = account_tx.execute(&mut state, &block_context).unwrap();
    let n_steps_0 = res.actual_resources.0.get("n_steps").unwrap();
    let actual_fee_0 = res.actual_fee.0;
    // Ensure the transaction was not reverted.
    assert!(!res.is_reverted());
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 394 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZHT6_N-bkLR4mHHJB3:-NZHT6_N-bkLR4mHHJB4:bybtuw8) ([raw file](https://github.com/starkware-libs/blockifier/blob/b46141581009b4da82f9efd06622309a94e78d7a/crates/blockifier/src/transaction/account_transactions_test.rs#L394)):*
> ```XML
>         calldata![
>             *contract_address.0.key(),       // Contract address.
>             selector_from_name("recurse").0, // EP selector.
> ```

Don't you mean `recursive_fail`?
Otherwise, you only fail on max steps; not on `1 = 0` assert.
Currently I think you should test that `n_steps_237` actually *does* equal `n_steps_238`; why is it not?



_Code quote:_
```XML
"recurse"
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 509 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZHTj854h1wf89EYRVT:-NZHTj869cFaUPQHv0ao:b-ligeu1) ([raw file](https://github.com/starkware-libs/blockifier/blob/b46141581009b4da82f9efd06622309a94e78d7a/crates/blockifier/src/transaction/account_transactions_test.rs#L509)):*
> ```XML
>     let actual_fee_0 = res.actual_fee.0;
>     // Ensure the transaction was reverted.
>     assert!(res.is_reverted());
> ```

ditto on the `run_scenario` comment. Consider making it a common function to the two tests (then maybe call it `recurse_for(depth: usize, recurse_function: String, should_succeed: bool) -> (usize, u128)` instead)



_Code quote:_
```XML
    let execute_calldata = create_calldata(&contract_address, 0);
    let tx = invoke_tx(execute_calldata, account_address, max_fee, None);
    let account_tx = AccountTransaction::Invoke(InvokeTransaction::V1(InvokeTransactionV1 {
        nonce: nonce_manager.next(account_address),
        ..tx
    }));
    let res = account_tx.execute(&mut state, &block_context).unwrap();
    let n_steps_0 = res.actual_resources.0.get("n_steps").unwrap();
    let actual_fee_0 = res.actual_fee.0;
    // Ensure the transaction was reverted.
    assert!(res.is_reverted());
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 548 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZHUHCa21DsDyKMK9YZ:-NZHUHCa21DsDyKMK9Y_:bbbvumu) ([raw file](https://github.com/starkware-libs/blockifier/blob/b46141581009b4da82f9efd06622309a94e78d7a/crates/blockifier/src/transaction/account_transactions_test.rs#L548)):*
> ```XML
> 
>     // Invoke the `recursive_fail` function with 100 iterations. This call should fail.
>     let execute_calldata = create_calldata(&contract_address, 100);
> ```

name this constant



_Code quote:_
```XML
100
```
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 20 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZHUcJS-9yXyOGl06v3:-NZHUcJS-9yXyOGl06v4:b-n3hy8w) ([raw file](https://github.com/starkware-libs/blockifier/blob/b46141581009b4da82f9efd06622309a94e78d7a/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L20)):*
> ```XML
> // `COMPILED_CONTRACTS_SUBDIR`.
> // 2. for each `X.cairo` file in `TEST_CONTRACTS` there exists an `X_compiled.json` file in
> // `COMPILED_CONTRACTS_SUBDIR` which equals `starknet-compile-deprecated X.cairo -- -no_debug_info`.
> ```

DANKE
Coordinated with @giladchase  ?



_Code quote:_
```XML
starknet-compile-deprecated
```


<!-- Sent from Reviewable.io -->

2023-07-03 09:19 UTC, zuphitf reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/677)* status: 7 of 8 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @giladchase)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 401 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZHRJ1yDJqxK-OrxAUy:-NZPleMc2PRoOZeaAvS3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/737dec711cbaaf4a8b7f794f143ce1b8182470c5/crates/blockifier/src/transaction/account_transactions_test.rs#L401)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

rename to `result`, everywhere
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 405 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZHRwcR4qbfkVfEDz6C:-NZPlgVIEYXAQkAT0jD5:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/737dec711cbaaf4a8b7f794f143ce1b8182470c5/crates/blockifier/src/transaction/account_transactions_test.rs#L405)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

define and use a `run_scenario(depth: u8) -> (usize, u128)`?
you repeat this logic 4 times (it only depends on depth)
you may also end up removing `create_calldata` after this refactor, you only need to create it once
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 394 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZHT6_N-bkLR4mHHJB3:-NZKWniIDUnx8YF3sQOf:b-dr58fo) ([raw file](https://github.com/starkware-libs/blockifier/blob/b46141581009b4da82f9efd06622309a94e78d7a/crates/blockifier/src/transaction/account_transactions_test.rs#L394)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Don't you mean `recursive_fail`?
Otherwise, you only fail on max steps; not on `1 = 0` assert.
Currently I think you should test that `n_steps_237` actually *does* equal `n_steps_238`; why is it not?
</blockquote></details>

I did not mean to use `recursive_fail`, the next test does. This test reaches the steps' limit (see test name). Depth 237 is where this happens.
When it's pretty close to the limit the diff thing works. When passing it more significantly thery're indeed equal.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 509 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZHTj854h1wf89EYRVT:-NZPk3Hj4EcNH5bJl_l3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b46141581009b4da82f9efd06622309a94e78d7a/crates/blockifier/src/transaction/account_transactions_test.rs#L509)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto on the `run_scenario` comment. Consider making it a common function to the two tests (then maybe call it `recurse_for(depth: usize, recurse_function: String, should_succeed: bool) -> (usize, u128)` instead)
</blockquote></details>

Done.
___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 20 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZHUcJS-9yXyOGl06v3:-NZKWBAk8cy-9dsaWPUc:b-ze5imc) ([raw file](https://github.com/starkware-libs/blockifier/blob/b46141581009b4da82f9efd06622309a94e78d7a/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L20)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

DANKE
Coordinated with @giladchase  ?
</blockquote></details>

Not coordinated. The compilation line below is `let mut command = Command::new("starknet-compile-deprecated");` and the documentation here is out of sync with it, so this aligns it.
There were a few other issues when actually trying to run this though.


<!-- Sent from Reviewable.io -->

2023-07-03 09:27 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/677)* status: all files reviewed, 12 unresolved discussions (waiting on @giladchase and @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 434 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ2eZ980V0oO8e2yiJ:-NZQ2eZA496Y8vv9BaJV:b-rtagwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L434)):*
> ```XML
>     assert!(!result.is_reverted());
>     println!("n_steps_0: {}", n_steps_0);
>     println!("actual_fee_0: {}", actual_fee_0);
> ```

delete



_Code quote:_
```XML
    println!("n_steps_0: {}", n_steps_0);
    println!("actual_fee_0: {}", actual_fee_0);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 452 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ2lFwBgtlnAE18jIn:-NZQ2lFwBgtlnAE18jIo:b-rtagwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L452)):*
> ```XML
>     assert!(!result.is_reverted());
>     println!("n_steps_1: {}", n_steps_1);
>     println!("actual_fee_1: {}", actual_fee_1);
> ```

delete



_Code quote:_
```XML
    println!("n_steps_1: {}", n_steps_1);
    println!("actual_fee_1: {}", actual_fee_1);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 482 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ2s7eAq8DG6DcqzDa:-NZQ2s7eAq8DG6DcqzDb:b-rtagwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L482)):*
> ```XML
>     assert!(actual_fee_237 > actual_fee_1);
>     println!("n_steps_237: {}", n_steps_237);
>     println!("actual_fee_237: {}", actual_fee_237);
> ```

delete



_Code quote:_
```XML
    println!("n_steps_237: {}", n_steps_237);
    println!("actual_fee_237: {}", actual_fee_237);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 500 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ2v5H9k_V2bTpn0ER:-NZQ2v5H9k_V2bTpn0ES:b-rtagwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L500)):*
> ```XML
>     assert!(result.is_reverted());
>     println!("n_steps_238: {}", n_steps_238);
>     println!("actual_fee_238: {}", actual_fee_238);
> ```

delete



_Code quote:_
```XML
    println!("n_steps_238: {}", n_steps_238);
    println!("actual_fee_238: {}", actual_fee_238);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 510 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ3B-V0o7T5jaJQGGB:-NZQ3B-V0o7T5jaJQGGC:b-fyvqbp) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L510)):*
> ```XML
>     // non-reverted transactions.
>     assert!(n_steps_1 - n_steps_0 == n_steps_238 - n_steps_237);
>     assert!(actual_fee_1 - actual_fee_0 == actual_fee_238 - actual_fee_237);
> ```

strange thing to test.
I think the 237 + 238 scenario shouldn't be added as a test here - it exposes a bug, so it would be nice to test that `n_steps_237 == n_steps_238` (which would currently fail).
@noaov1 WDYT?



_Code quote:_
```XML
    assert!(n_steps_1 - n_steps_0 == n_steps_238 - n_steps_237);
    assert!(actual_fee_1 - actual_fee_0 == actual_fee_238 - actual_fee_237);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 528 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ2yq06D9CDGLdBFKm:-NZQ2yq06D9CDGLdBFKn:b-rtagwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L528)):*
> ```XML
>     assert!(result.is_reverted());
>     println!("n_steps_250: {}", n_steps_fail);
>     println!("actual_fee_250: {}", actual_fee_fail);
> ```

delete



_Code quote:_
```XML
    println!("n_steps_250: {}", n_steps_fail);
    println!("actual_fee_250: {}", actual_fee_fail);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 542 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ32a8276S_rp6uS_P:-NZQ32a8276S_rp6uS_Q:bqqpoqs) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L542)):*
> ```XML
>     );
>     let n_steps_fail_next = result.actual_resources.0.get("n_steps").unwrap();
>     let actual_fee_fail_next: u128 = result.actual_fee.0;
> ```

assert these values are equal to the previous values?



_Code quote:_
```XML
    let n_steps_fail_next = result.actual_resources.0.get("n_steps").unwrap();
    let actual_fee_fail_next: u128 = result.actual_fee.0;
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 546 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ30g37bbgqqiULkfy:-NZQ30g37bbgqqiULkfz:b-rtagwg) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L546)):*
> ```XML
>     assert!(result.is_reverted());
>     println!("n_steps_251: {}", n_steps_fail_next);
>     println!("actual_fee_251: {}", actual_fee_fail_next);
> ```

delete



_Code quote:_
```XML
    println!("n_steps_251: {}", n_steps_fail_next);
    println!("actual_fee_251: {}", actual_fee_fail_next);
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 599 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ3bubDKqviZEa80qQ:-NZQ3bubDKqviZEa80qR:b-q67k7d) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L599)):*
> ```XML
> 
>     // Invoke the `recursive_fail` function with 2 iterations. This call should fail.
>     let result: TransactionExecutionInfo = run_recursive_function(
> ```

why do you need to annotate? (please delete everywhere)



_Suggestion:_
```XML
result
```


<!-- Sent from Reviewable.io -->

2023-07-03 09:33 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/677)* status: all files reviewed, 12 unresolved discussions (waiting on @dorimedini-starkware and @zuphitf)

___
*[`crates/blockifier/tests/feature_contracts_compatibility_test.rs` line 20 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZHUcJS-9yXyOGl06v3:-NZQ5HhS8hIShd3YraQc:bg7igkv) ([raw file](https://github.com/starkware-libs/blockifier/blob/b46141581009b4da82f9efd06622309a94e78d7a/crates/blockifier/tests/feature_contracts_compatibility_test.rs#L20)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

Not coordinated. The compilation line below is `let mut command = Command::new("starknet-compile-deprecated");` and the documentation here is out of sync with it, so this aligns it.
There were a few other issues when actually trying to run this though.
</blockquote></details>

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 


<!-- Sent from Reviewable.io -->

2023-07-03 09:48 UTC, zuphitf commented
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 452 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ2lFwBgtlnAE18jIn:-NZQ8kTU7MnsPMWH2ysz:b-3zbjx6) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L452)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

It's there for now for Noa...


<!-- Sent from Reviewable.io -->

2023-07-03 09:49 UTC, zuphitf commented
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 482 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ2s7eAq8DG6DcqzDa:-NZQ8s208YOOuhQRDH0Z:bgcxn4b) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L482)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

See this commit's message. This is a debug commit.


<!-- Sent from Reviewable.io -->

2023-07-03 10:19 UTC, zuphitf commented
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 510 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ3B-V0o7T5jaJQGGB:-NZQFr77Ab0NbcSDMqnc:b-ri63zk) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L510)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

strange thing to test.
I think the 237 + 238 scenario shouldn't be added as a test here - it exposes a bug, so it would be nice to test that `n_steps_237 == n_steps_238` (which would currently fail).
@noaov1 WDYT?
</blockquote></details>

I can test this for 250, 251 like we talked


<!-- Sent from Reviewable.io -->

2023-07-03 11:59 UTC, zuphitf reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/677)* status: 7 of 8 files reviewed, 11 unresolved discussions (waiting on @dorimedini-starkware and @noaov1)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 375 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZHSK1D7UoFryIrCTJf:-NZQazw6B4CsgYWuJlSc:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/737dec711cbaaf4a8b7f794f143ce1b8182470c5/crates/blockifier/src/transaction/account_transactions_test.rs#L375)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

instead of `0, 1, 237, 238` please use `small_recurse, small_recurse + diff_recurse, large_recurse, large_recurse + diff_recurse` (so reader sees how the four scenarios relate)
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 548 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZHUHCa21DsDyKMK9YZ:-NZQbJvlA07Fd3sEjV8c:b-u00841) ([raw file](https://github.com/starkware-libs/blockifier/blob/b46141581009b4da82f9efd06622309a94e78d7a/crates/blockifier/src/transaction/account_transactions_test.rs#L548)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

name this constant
</blockquote></details>

a bit of an overkill? that will make this less readable, there's hardcoded `100` in the calculations below and variable names
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 434 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ2eZ980V0oO8e2yiJ:-NZQb-lc8SJPq58_RJd-:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L434)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 482 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ2s7eAq8DG6DcqzDa:-NZQb1IE7zYDeM3u2qZo:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L482)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

See this commit's message. This is a debug commit.
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 500 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ2v5H9k_V2bTpn0ER:-NZQb2xv5-HWOCInELAi:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L500)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 510 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ3B-V0o7T5jaJQGGB:-NZQb4B44wA0f5KTjlpM:bb6un1j) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L510)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

I can test this for 250, 251 like we talked
</blockquote></details>

Done
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 528 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ2yq06D9CDGLdBFKm:-NZQb6Wi0nR5KMtJgT0S:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L528)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 542 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ32a8276S_rp6uS_P:-NZQb7NWDgOhOOKuwUa4:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L542)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

assert these values are equal to the previous values?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 546 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ30g37bbgqqiULkfy:-NZQb7xK7OlfGIZPVSyz:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L546)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 599 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ3bubDKqviZEa80qQ:-NZQb8xhAkUqcBOyUUbE:bndazut) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L599)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do you need to annotate? (please delete everywhere)
</blockquote></details>

y u don't like type annotations?
we use `TransactionExecutionInfo` fields in the lines below


<!-- Sent from Reviewable.io -->

2023-07-03 12:37 UTC, dorimedini-starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/677#-:-NZQkPTz3aAPSj2ghBkV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 599 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ3bubDKqviZEa80qQ:-NZQkFOZEbNspkdZ1LX1:b3a42o5) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L599)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

y u don't like type annotations?
we use `TransactionExecutionInfo` fields in the lines below
</blockquote></details>

yes, but you don't need annotation to do so; the `run_recursive_function` is annotated. anyway, unblocking


<!-- Sent from Reviewable.io -->

2023-07-03 12:47 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/677)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 455 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQkvzI4ds9Qq_4oBOc:-NZQkvzI4ds9Qq_4oBOd:b97w27p) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ddb229e592c779e5451bc92d4f2a07a3eb048d/crates/blockifier/src/transaction/account_transactions_test.rs#L455)):*
> ```XML
> 
>     let steps_diff = n_steps_1 - n_steps_0;
>     let fail_depth = block_context.invoke_tx_max_n_steps / (steps_diff as u32);
> ```

While `53` is the number of steps of invoke with `depth = 0`. What am I missing?



_Suggestion:_
```XML
    let fail_depth = (block_context.invoke_tx_max_n_steps as f64 - 53.0) / (steps_diff as f64);
    let fail_depth = fail_depth.ceil() as u32;
```


<!-- Sent from Reviewable.io -->

2023-07-03 13:17 UTC, zuphitf commented
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 455 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQkvzI4ds9Qq_4oBOc:-NZQt1h39LA681_CmBfG:b-8zregb) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ddb229e592c779e5451bc92d4f2a07a3eb048d/crates/blockifier/src/transaction/account_transactions_test.rs#L455)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

While `53` is the number of steps of invoke with `depth = 0`. What am I missing?
</blockquote></details>

I'm not sure what you mean.

Also, this is not necessarily `min_fail_depth`. Just an easy calc to follow that fails.


<!-- Sent from Reviewable.io -->

2023-07-03 13:17 UTC, zuphitf commented
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 455 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQkvzI4ds9Qq_4oBOc:-NZQt1h39LA681_CmBfG:b-8zregb) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ddb229e592c779e5451bc92d4f2a07a3eb048d/crates/blockifier/src/transaction/account_transactions_test.rs#L455)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

While `53` is the number of steps of invoke with `depth = 0`. What am I missing?
</blockquote></details>

I'm not sure what you mean.

Also, this is not necessarily `min_fail_depth`. Just an easy calc to follow that fails.


<!-- Sent from Reviewable.io -->

2023-07-03 13:26 UTC, noaov1 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/677)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 510 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQ3B-V0o7T5jaJQGGB:-NZQv7s1-qEHpWpvR7UO:b77jldx) ([raw file](https://github.com/starkware-libs/blockifier/blob/6f86c43717b3fbf25bee39ebf28ddbf2261f1b8b/crates/blockifier/src/transaction/account_transactions_test.rs#L510)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

Done
</blockquote></details>

Note for documentation reason: We should not use the `n_steps` in the `actual_resources` because it behaves differently depending on when we reach the limit.
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 455 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQkvzI4ds9Qq_4oBOc:-NZQumay2IJN3nS4rp6h:b-ci01g6) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ddb229e592c779e5451bc92d4f2a07a3eb048d/crates/blockifier/src/transaction/account_transactions_test.rs#L455)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

I'm not sure what you mean.

Also, this is not necessarily `min_fail_depth`. Just an easy calc to follow that fails.
</blockquote></details>

I see. I find it confusing that we ignore the "base cost" of `invoke`, so maybe add a note?


<!-- Sent from Reviewable.io -->

2023-07-03 13:33 UTC, zuphitf commented
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 455 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/677#-NZQkvzI4ds9Qq_4oBOc:-NZQxCPS3HBOCoFy0WZm:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b4ddb229e592c779e5451bc92d4f2a07a3eb048d/crates/blockifier/src/transaction/account_transactions_test.rs#L455)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I see. I find it confusing that we ignore the "base cost" of `invoke`, so maybe add a note?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-03 13:38 UTC, noaov1 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/677)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2023-07-03 13:44 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/677)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)



<!-- Sent from Reviewable.io -->

2023-07-04 08:16 UTC, zuphitf reviewed
> Reviewed 7 of 8 files at r2, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/677)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2023-07-04 08:18 UTC, zuphitf reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/677)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)



<!-- Sent from Reviewable.io -->

2023-07-04 08:18 UTC, dorimedini-starkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/677)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)



<!-- Sent from Reviewable.io -->

2023-07-04 08:18 UTC, merged