Storage cleanup
starkware-libs/blockifier pull request #731
Opened 2023-07-10 14:08 UTC by giladchase

- initialize storage using a `StorageConfig` motivation is two-fold: first, `Storage` will soon be internalized into a more general struct (BlockExecutor), so when we initialize it we want to wrap all the storage-relevant arguments up nicely to differentiate from the other arguments it is initialized with; second, there will soon be an additional argument here (chain_id) and three arguments is starting to get verbose.
- Added a testing initializer for Python usage (currently we're doing this in Python, which is wrong cause this is an implementation detail)

python: https://reviewable.io/reviews/starkware-industries/starkware/30775

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/731)

2023-07-10 14:17 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/731)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/731#-N_-9Nd91KPXpeyAMWiJ):*
Blocking until rc0 fix.


<!-- Sent from Reviewable.io -->

2023-07-11 15:13 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/731#-:-N_4VsYx5Vhkfrrtbpaf:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/native_blockifier/src/storage.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/731#-N_4VrSN3ncx5DUjgF7q:-N_4VrSN3ncx5DUjgF7r:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/c17af960e2fd3b723a0c84b89610da2a59adbd01/crates/native_blockifier/src/storage.rs#L37)):*
> ```XML
>     #[new]
>     #[args(storage_config)]
>     pub fn new(storage_config: StorageConfig) -> NativeBlockifierResult<Storage> {
> ```





_Suggestion:_
```XML
config
```


<!-- Sent from Reviewable.io -->

2023-07-11 16:17 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/731)* status: 0 of 22 files reviewed, 3 unresolved discussions (waiting on @giladchase and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/731#-N_4jboOEmkDSurjgxeY:-N_4jboP7QUTWVLwm-lk:b-ulzre9) (no related file):*
Bad rebase?

___


<!-- Sent from Reviewable.io -->

2023-07-12 05:28 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/731)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/731#-N_4jboOEmkDSurjgxeY:-N_7ZIUiEytWUOODX_jT:b31jgy6) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Bad rebase?
</blockquote></details>

Merge base was stale.

___


<!-- Sent from Reviewable.io -->

2023-07-12 13:14 UTC, elintul submitted a review, later dismissed
> Reviewed 1 of 6 files at r7, 1 of 4 files at r12, 14 of 19 files at r13, 6 of 6 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/731)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-07-17 12:57 UTC, merged