Refactor `PapyrusReader` and `py_transaction_executor.py` to remove unnecessary RO tx storage
starkware-libs/blockifier pull request #758
Opened 2023-07-18 17:29 UTC by giladchase

This commit simplifies handling read-only transactions (RO tx) in the `PapyrusReader` and `py_transaction_executor.py` modules.
The previous design saved an open RO tx in the instance, which led to unnecessary complexity, including the need for a lifetime/ouroboros pattern. This commit modifies the system to open a new RO tx on demand, which is a more efficient and simpler approach.

Key changes:

- The `PapyrusReader` has been refactored to generate the required transactions on demand. This removes the need to store an open RO tx.

- The `py_transaction_executor.py` module has been significantly simplified. The changes primarily involve the removal of the ouroboros pattern, which required certain fields and complex constructor methods.
With the removal of stored RO tx, we can replace the previous elaborate constructor with a regular one and substitute the 'with_X' accessors with standard accessors.

Please note: The significant changes seen in the 'execute' diff mainly pertain to the removal of the 'with_mut' closure and other 'with_X' accessors. No other modifications have been made to this section.

Python PR: https://reviewable.io/reviews/starkware-industries/starkware/30934

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/758)

2023-07-18 17:36 UTC, alonh5 reviewed
Yay :star_struck: :croissant: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/758#-:-N_e3W1yBfgdzfknxr_G:b2q7l6r)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2023-07-20 14:41 UTC, elintul requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/758)* status: all files reviewed, 3 unresolved discussions (waiting on @giladchase)

___
*[`crates/native_blockifier/src/papyrus_state.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/758#-N_njAcu86iswiYjb35_:-N_njAcv9_S5395cENc3:bjs9gg8) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2384ab5913f1fe13c544339cb77b8bd2152bdf8/crates/native_blockifier/src/papyrus_state.rs#L28)):*
> ```XML
>         Self { storage_reader, latest_block }
>     }
> ```

Maybe we should switch to `Result`s and `?`s?
So that the Batcher won't crash.
___
*[`crates/native_blockifier/src/py_transaction_executor.rs` line 91 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/758#-N_njUyz2-EeB8FZO5SF:-N_njUyz2-EeB8FZO5SG:ba3dfmt) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2384ab5913f1fe13c544339cb77b8bd2152bdf8/crates/native_blockifier/src/py_transaction_executor.rs#L91)):*
> ```XML
> 
> // To access a field you must use `self.borrow_{field_name}()`.
> // Alternately, you can borrow the whole object using `self.with[_mut]()`.
> ```

Remove.



_Code quote:_
```XML
// To access a field you must use `self.borrow_{field_name}()`.
// Alternately, you can borrow the whole object using `self.with[_mut]()`.
```
___
*[`crates/native_blockifier/src/py_transaction_executor.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/758#-N_nj_8W8ObhtPtLZQnw:-N_nj_8W8ObhtPtLZQnx:ba3dfmt) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2384ab5913f1fe13c544339cb77b8bd2152bdf8/crates/native_blockifier/src/py_transaction_executor.rs#L99)):*
> ```XML
> 
>     // State-related fields.
>     // Storage reader and transaction are kept merely for lifetime parameter referencing.
> ```

Remove.



_Code quote:_
```XML
// Storage reader and transaction are kept merely for lifetime parameter referencing.
```


<!-- Sent from Reviewable.io -->

2023-07-21 18:21 UTC, giladchase reviewed
:baguette_bread: 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/758#-:-N_ssVl3DjcbYj278Huh:b-ptk0e7)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/papyrus_state.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/758#-N_njAcu86iswiYjb35_:-N_sxHk83TR48FdXLg_X:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/f2384ab5913f1fe13c544339cb77b8bd2152bdf8/crates/native_blockifier/src/papyrus_state.rs#L28)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Maybe we should switch to `Result`s and `?`s?
So that the Batcher won't crash.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-23 10:02 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

As usual: please merge adjacently to the Python PR.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/758#-:-Na1BhfK0PRIKj1FfbHv:b48t8m6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-07-23 10:02 UTC, merged