Add `PyBlockExecutor`
starkware-libs/blockifier pull request #776
Opened 2023-07-23 17:45 UTC by giladchase

* For simplicity, all it does at the moment is hold general_config and max_recursion_depth, where the former's definition was moved into `PyBlockExecutor`'s module, since it is its primary owner.
* It is also in charge of initializing the PyTransactionExecutor for Python.
* Make `py_block_context` into a method of `PyGeneralConfig` --- note that PyBlockInfo can be used there instead of PyAny, will do in separate PR to keep the diff small.
* in subsequent PRs it will also be in charge of Storage, and later on hide both storage and transaction executor from Python.
* The change in `account_transactions_test`.rs is an unrelated unnecessary `clone` clippy spotted only now for some reason.

2023-07-23 19:10 UTC, elintul requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/776)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/776#-Na38U2138NmayFtyXIb:-Na38U2138NmayFtyXIc:bax67b1) ([raw file](https://github.com/starkware-libs/blockifier/blob/4be642ef40ac0011c94b257ffeceadcde5d162ce/crates/native_blockifier/src/py_block_executor.rs#L32)):*
> ```XML
>     #[staticmethod]
>     fn create_for_testing(general_config: PyGeneralConfig) -> Self {
>         Self { general_config, max_recursion_depth: 50 }
> ```

Isn't this a constant / passed from Python?



_Code quote:_
```XML
50
```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/776#-Na38yWm8z-vXEJRWqbL:-Na38yWm8z-vXEJRWqbM:b-dg1soa) ([raw file](https://github.com/starkware-libs/blockifier/blob/4be642ef40ac0011c94b257ffeceadcde5d162ce/crates/native_blockifier/src/py_block_executor.rs#L58)):*
> ```XML
> 
> impl PyGeneralConfig {
>     pub fn into_block_context(
> ```

Isn't it a bit weird it's a method of `PyGeneralConfig`, when it also needs a `PyBlockInfo`?



_Code quote:_
```XML
into_block_context
```


<!-- Sent from Reviewable.io -->

2023-07-23 19:18 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/776)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/776#-Na38U2138NmayFtyXIb:-Na3A1dO4iVFatlKvhY7:b-hlad1u) ([raw file](https://github.com/starkware-libs/blockifier/blob/4be642ef40ac0011c94b257ffeceadcde5d162ce/crates/native_blockifier/src/py_block_executor.rs#L32)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Isn't this a constant / passed from Python?
</blockquote></details>

Ya but in multiple locations, and if we want them all to use the same const they'll be coupled.
I can move this into a `const` in the module, but since it was a testing method I didn't think it was worth the noise.

I can put it as an inline `const` though, but again, not sure if it's worth it:
```rust
    fn create_for_testing(general_config: PyGeneralConfig) -> Self {
       const max_recursion_depth: usize = 50; 
       Self { general_config, max_recursion_depth }
    }

```
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/776#-Na38yWm8z-vXEJRWqbL:-Na3AgkZ67NbMMz0H27J:b-d6t6wk) ([raw file](https://github.com/starkware-libs/blockifier/blob/4be642ef40ac0011c94b257ffeceadcde5d162ce/crates/native_blockifier/src/py_block_executor.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Isn't it a bit weird it's a method of `PyGeneralConfig`, when it also needs a `PyBlockInfo`?
</blockquote></details>

I didn't remember if in the big PR you wanted it to be a method of PyBlockInfo or PyGeneralConfig, I picked this one because it was referenced more times inside the method.
Do you prefer I move it to `PyBlockInfo`? 


<!-- Sent from Reviewable.io -->

2023-07-23 19:23 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/776)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/776#-Na38U2138NmayFtyXIb:-Na3C8SJBcwVB1scX3XC:bfysfns) ([raw file](https://github.com/starkware-libs/blockifier/blob/4be642ef40ac0011c94b257ffeceadcde5d162ce/crates/native_blockifier/src/py_block_executor.rs#L32)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Ya but in multiple locations, and if we want them all to use the same const they'll be coupled.
I can move this into a `const` in the module, but since it was a testing method I didn't think it was worth the noise.

I can put it as an inline `const` though, but again, not sure if it's worth it:
```rust
    fn create_for_testing(general_config: PyGeneralConfig) -> Self {
       const max_recursion_depth: usize = 50; 
       Self { general_config, max_recursion_depth }
    }

```
</blockquote></details>

Nah, it's okay. I missed the fact this is a testing method.
___
*[`crates/native_blockifier/src/py_block_executor.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/776#-Na38yWm8z-vXEJRWqbL:-Na3CI1lAKzGt5cMh1Jv:bo1vbbz) ([raw file](https://github.com/starkware-libs/blockifier/blob/4be642ef40ac0011c94b257ffeceadcde5d162ce/crates/native_blockifier/src/py_block_executor.rs#L58)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I didn't remember if in the big PR you wanted it to be a method of PyBlockInfo or PyGeneralConfig, I picked this one because it was referenced more times inside the method.
Do you prefer I move it to `PyBlockInfo`? 
</blockquote></details>

You think a method is better than a function here?


<!-- Sent from Reviewable.io -->

2023-07-23 19:34 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/776)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/776#-Na38yWm8z-vXEJRWqbL:-Na3E5lO3pvi8HUvh2eF:b-dc3ft) ([raw file](https://github.com/starkware-libs/blockifier/blob/4be642ef40ac0011c94b257ffeceadcde5d162ce/crates/native_blockifier/src/py_block_executor.rs#L58)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

You think a method is better than a function here?
</blockquote></details>

I don't mind either way, I only did it cause you asked in the big PR :P

It's a cast, which is a method, but since it is a cast from 3 objects into 1, there isn't really a standard as to what it should be.


<!-- Sent from Reviewable.io -->

2023-07-23 19:38 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/776)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)

___
*[`crates/native_blockifier/src/py_block_executor.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/776#-Na38yWm8z-vXEJRWqbL:-Na3FYUA4W8gqyu7Nw0f:b-8v8jug) ([raw file](https://github.com/starkware-libs/blockifier/blob/4be642ef40ac0011c94b257ffeceadcde5d162ce/crates/native_blockifier/src/py_block_executor.rs#L58)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I don't mind either way, I only did it cause you asked in the big PR :P

It's a cast, which is a method, but since it is a cast from 3 objects into 1, there isn't really a standard as to what it should be.
</blockquote></details>

We can leave it a function.


<!-- Sent from Reviewable.io -->

2023-07-24 07:57 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/776#-:-Na5tlLiC0g7qSy9huc3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-07-24 19:10 UTC, merged