Refactor run_or_revert.
starkware-libs/blockifier pull request #796
Opened 2023-07-26 12:53 UTC by zuphitf

Check actual fee before committing the execution result. Revert and charge max fee when running out of gas instead of failing due to FeeTransferError and charging nothing.

2023-07-26 14:33 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/796)* status: all files reviewed, 5 unresolved discussions (waiting on @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 452 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/796#-NaH_dd66DLnfSGrOb9K:-NaH_dd66DLnfSGrOb9L:btfimte) ([raw file](https://github.com/starkware-libs/blockifier/blob/94c1d3946858f4317bd078bcac5a3d3276a715c3/crates/blockifier/src/transaction/account_transaction.rs#L452)):*
> ```XML
>         // Create copies of state and resources for the execution.
>         // Both will be rolled back if the execution is reverted or committed upon success.
>         let mut execution_resources = resources.clone();
> ```

why do you separate the resources? you don't really need to revert the resources used; right? Only the state diff (is there a problem with keeping the full resources in a reverted tx?)
also I see three `clone[_from]`s due to this



_Code quote:_
```XML
execution_resources
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 490 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/796#-NaH_vc8DqZERvV4Bcr1:-NaH_vc99QaZ-cpqYD00:b-ru6xjx) ([raw file](https://github.com/starkware-libs/blockifier/blob/94c1d3946858f4317bd078bcac5a3d3276a715c3/crates/blockifier/src/transaction/account_transaction.rs#L490)):*
> ```XML
>                     // Insufficient fee. Revert the execution.
>                     execution_state.abort();
>                     let remaining_steps = execution_context.vm_run_resources.get_n_steps().unwrap();
> ```

change to `expect` and add an error message



_Code quote:_
```XML
unwrap()
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 515 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/796#-NaHYQS99b13b6COO2-G:-NaHYQSA-HMFhNSwH6ub:bkt47yl) ([raw file](https://github.com/starkware-libs/blockifier/blob/94c1d3946858f4317bd078bcac5a3d3276a715c3/crates/blockifier/src/transaction/account_transaction.rs#L515)):*
> ```XML
>                 let remaining_steps = execution_context.vm_run_resources.get_n_steps().unwrap();
>                 let reverted_steps = allotted_steps - remaining_steps;
>                 let out_of_gas = allotted_steps == reverted_steps;
> ```

not such a good indication IMO; you should be able to capture the error and check it to see if you are out of resources.
 (maybe in the future we will limit runs by more than just steps)
You can do this by checking the inner error type, or, if it's recursive error nesting nightmare, check if the error text contains the out-of-resources message 



_Code quote:_
```XML
let out_of_gas = allotted_steps == reverted_steps;
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 648 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/796#-NaHb1YXCA381_OGrUd1:-NaHb1YY9T98tPeNWRro:b-x2j3u1) ([raw file](https://github.com/starkware-libs/blockifier/blob/94c1d3946858f4317bd078bcac5a3d3276a715c3/crates/blockifier/src/transaction/account_transaction.rs#L648)):*
> ```XML
>         if out_of_gas {
>             actual_fee = account_tx_context.max_fee;
>         }
> ```

It is possible that we are out of gas, but the actual fee is less than the max fee, right? e.g. max fee covers more than 1,000,000 steps, but this is the hard limit for execution, so we would get out of gas?
This can easily cause us to charge a huge sum for no reason



_Code quote:_
```XML
        if out_of_gas {
            actual_fee = account_tx_context.max_fee;
        }
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 754 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/796#-NaHbSEDD4vesAMHjDWY:-NaHbSEDD4vesAMHjDWZ:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/94c1d3946858f4317bd078bcac5a3d3276a715c3/crates/blockifier/src/transaction/account_transactions_test.rs#L754)):*
> ```XML
>     assert!(tx_execution_info2.is_reverted());
>     assert!(tx_execution_info2.actual_fee == actual_fee_depth1);
>     assert!(tx_execution_info2.revert_error.unwrap().contains("Insufficient max fee"));
> ```





_Suggestion:_
```XML
startswith
```


<!-- Sent from Reviewable.io -->

2023-07-26 15:07 UTC, dorimedini-starkware requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/796)* status: all files reviewed, 1 unresolved discussion (waiting on @zuphitf)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 648 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/796#-NaHb1YXCA381_OGrUd1:-NaHjRB23usZoFB60tNr:bspo7j5) ([raw file](https://github.com/starkware-libs/blockifier/blob/94c1d3946858f4317bd078bcac5a3d3276a715c3/crates/blockifier/src/transaction/account_transaction.rs#L648)):*
<details><summary><i>Previously, zuphitf wrote…</i></summary><blockquote>

Done. Now out of gas can only be triggered when really out of gas.
(we might slightly undercharge some reverted txs though, but I gather from everyone that it's not a big deal here)
</blockquote></details>

so "RunResources reached step limit" is not an "out of gas" situation?
maybe rename `out_of_gas` to `underpaid` or something more specific?


<!-- Sent from Reviewable.io -->

2023-07-26 15:28 UTC, zuphitf reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/796)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 648 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/796#-NaHb1YXCA381_OGrUd1:-NaHm2I78aB54AOl7tfA:b-326iga) ([raw file](https://github.com/starkware-libs/blockifier/blob/94c1d3946858f4317bd078bcac5a3d3276a715c3/crates/blockifier/src/transaction/account_transaction.rs#L648)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

so "RunResources reached step limit" is not an "out of gas" situation?
maybe rename `out_of_gas` to `underpaid` or something more specific?
</blockquote></details>

It is out of gas in the sense that you filled more than your tank can hold and gas is spilled on the floor. Renaming.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 650 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/796#-NaHjmet27B3qr4hjEuo:-NaHk70d33XFqv1MknoE:b-o370xu) ([raw file](https://github.com/starkware-libs/blockifier/blob/44399580cd6e4dd82169bafa940572be08dad37e/crates/blockifier/src/transaction/account_transaction.rs#L650)):*
> ```
> && actual_fee > account_tx_context.max_fee
> ```

This will never be true though.  `actual_fee` calculation path will always cap it by `account_tx_context.max_fee`
Moreover, `actual_fee`'s value before this `if` fixes it will likely be smaller than `account_tx_context.max_fee`  when we revert the execution and erase its resources (when aborting due to fee transfer fail).


<!-- Sent from Reviewable.io -->

2023-07-27 08:16 UTC, dorimedini-starkware submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/796)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)



<!-- Sent from Reviewable.io -->

2023-07-27 08:33 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/796#-:-NaLTpBL1iC7mSmQ_kSz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zuphitf)



<!-- Sent from Reviewable.io -->

2023-07-27 08:34 UTC, merged