Remove python bouncer callback from `native_blockifier`
starkware-libs/blockifier pull request #839
Opened 2023-08-17 13:04 UTC by giladchase

- Removed `enough_room_for_tx`, a Python bouncer callback, allowing PyTransactionExecutionInfo to be allocated in Rust, rather than on the Python heap (so it is no longer of type `Py<PyTransactionExecutionInfo>`, just `PyTransactionExecutionInfo`). Also, now no longer need specialized Python exception handling, since we are no longer running Python code.
- Added new API to block-executor to replace the callback: `commit_tx` and `abort_tx`, which Python calls after getting the results from the bouncer.
- Added `StagedTransactionalState`, which represents a TransactionalState after the transaction has finished executing. Thus, it only holds the results of the exeuction that are subject to be commited to the state, or the set of executed class hashes. There is still a bit of duplication between it's commit/abort and the ones in `TransactionalState`, but this will be hard to refactor, since the commit here must use `&mut self`, while in `TransactionalState` they consume self.

2023-08-17 13:24 UTC, elintul requested changes
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/839)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 673 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/839#-Nc2c_7D7zo39Pq1OXRD:-Nc2c_7D7zo39Pq1OXRE:bteo649) ([raw file](https://github.com/starkware-libs/blockifier/blob/082fa81b3107a7ea2014449b880dc878fe486633/crates/blockifier/src/state/cached_state.rs#L673)):*
> ```XML
> }
> 
> pub struct StagedTransactionalState {
> ```

Move after `TransactionalState`?



_Code quote:_
```XML
StagedTransactionalState
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 677 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/839#-Nc2d27j7JI5Gm4pRMOn:-Nc2d27j7JI5Gm4pRMOo:bzas7um) ([raw file](https://github.com/starkware-libs/blockifier/blob/082fa81b3107a7ea2014449b880dc878fe486633/crates/blockifier/src/state/cached_state.rs#L677)):*
> ```XML
>     pub class_hash_to_class: ContractClassMapping,
>     pub global_class_hash_to_class: GlobalContractCache,
>     pub tx_executed_class_hashes: HashSet<ClassHash>,
> ```

Should this appear here? It's currently only used by native.



_Code quote:_
```XML
pub tx_executed_class_hashes: HashSet<ClassHash>,
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 681 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/839#-Nc2cfpn1GN0wmLOM3I2:-Nc2cfpn1GN0wmLOM3I3:bx9hlty) ([raw file](https://github.com/starkware-libs/blockifier/blob/082fa81b3107a7ea2014449b880dc878fe486633/crates/blockifier/src/state/cached_state.rs#L681)):*
> ```XML
> 
> impl StagedTransactionalState {
>     pub fn finalize_transaction_state(
> ```

WDYT about `stage` method for `TransactionalState`, consuming it and returning `StagedTransactionalState`?



_Suggestion:_
```XML
finalize_transactional_state
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 685 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/839#-Nc2czI1-z3gz7GY1WJT:-Nc2czI1-z3gz7GY1WJU:belo6zs) ([raw file](https://github.com/starkware-libs/blockifier/blob/082fa81b3107a7ea2014449b880dc878fe486633/crates/blockifier/src/state/cached_state.rs#L685)):*
> ```XML
>         tx_executed_class_hashes: HashSet<ClassHash>,
>     ) -> Self {
>         let TransactionalState { state: _, cache, class_hash_to_class, global_class_hash_to_class } =
> ```

Explain this syntax?



_Code quote:_
```XML
state: _
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/839#-Nc2dD7X10k1qIIMlqhj:-Nc2dD7X10k1qIIMlqhk:bc0v12h) ([raw file](https://github.com/starkware-libs/blockifier/blob/082fa81b3107a7ea2014449b880dc878fe486633/crates/native_blockifier/src/transaction_executor.rs#L37)):*
> ```XML
>     pub state: CachedState<PapyrusReader>,
>     // Transactional state, awaiting commit/abort call.
>     // Is None while a transaction is being executed and in between transactions.
> ```

Consider rephrasing in the positive direction: when does it exist?



_Code quote:_
```XML
// Is None while a transaction is being executed and in between transactions.
```
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/839#-Nc2e9XB9GE51eaFlEBD:-Nc2e9XB9GE51eaFlEBE:b228yug) ([raw file](https://github.com/starkware-libs/blockifier/blob/082fa81b3107a7ea2014449b880dc878fe486633/crates/native_blockifier/src/transaction_executor.rs#L132)):*
> ```XML
> 
>     pub fn commit(&mut self) {
>         let Some(finalized_transactional_state) = self.staged_for_commit_state.take() else {
> ```

What does this mean?



_Code quote:_
```XML
.take()
```


<!-- Sent from Reviewable.io -->

2023-08-17 13:44 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/839)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 673 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/839#-Nc2c_7D7zo39Pq1OXRD:-Nc2gLVeEjeT5uQEPUAe:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8258ce74deb65a364d717d3fc59557720b8976a8/crates/blockifier/src/state/cached_state.rs#L673)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move after `TransactionalState`?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 677 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/839#-Nc2d27j7JI5Gm4pRMOn:-Nc2gNCABvvSvuly5Im0:bd0fgb4) ([raw file](https://github.com/starkware-libs/blockifier/blob/8258ce74deb65a364d717d3fc59557720b8976a8/crates/blockifier/src/state/cached_state.rs#L677)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Should this appear here? It's currently only used by native.
</blockquote></details>

Good point, i'll need to think about this one :thinking: 

Moving this into native_blockifier will require making `CachedState`'s `cache, class_hash_to_class` and `global_class_hash_to_class` all public, since they are unpacked inside `finalize_transaction_state`.
Alternatively, we can add getters and setters, but that is equally invasive, since no one needs those except `StagedTransactionalState`.
___
*[`crates/blockifier/src/state/cached_state.rs` line 681 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/839#-Nc2cfpn1GN0wmLOM3I2:-Nc2hBjr4J9bFdKp-Omq:bpq38qk) ([raw file](https://github.com/starkware-libs/blockifier/blob/8258ce74deb65a364d717d3fc59557720b8976a8/crates/blockifier/src/state/cached_state.rs#L681)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYT about `stage` method for `TransactionalState`, consuming it and returning `StagedTransactionalState`?
</blockquote></details>

Sounds great! :star_struck: 
Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 685 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/839#-Nc2czI1-z3gz7GY1WJT:-Nc2i-jd1Nmrt5kWYOgf:b-x62vek) ([raw file](https://github.com/starkware-libs/blockifier/blob/8258ce74deb65a364d717d3fc59557720b8976a8/crates/blockifier/src/state/cached_state.rs#L685)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Explain this syntax?
</blockquote></details>

Should have been `state: _state`, which means "unpack state into the unused variable `_state` (or unused variable `_`).

There's a way around it though (I just tried it and it worked :heart_eyes: ), just adding `..` at the end is equivalent to disregarding the rest of the fields.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 132 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/839#-Nc2e9XB9GE51eaFlEBD:-Nc2ixfi2QQR2vTKzpI5:bgjy5ll) ([raw file](https://github.com/starkware-libs/blockifier/blob/8258ce74deb65a364d717d3fc59557720b8976a8/crates/native_blockifier/src/transaction_executor.rs#L132)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

What does this mean?
</blockquote></details>

It's equivalent to "unwrap the `Option` and set `None` instead", kind of like "draining the `Option`".


<!-- Sent from Reviewable.io -->

2023-08-17 14:15 UTC, elintul requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/839)* status: all files reviewed, 2 unresolved discussions (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 677 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/839#-Nc2d27j7JI5Gm4pRMOn:-Nc2pfdD-cs_nMXapr3e:b-t29v0b) ([raw file](https://github.com/starkware-libs/blockifier/blob/8258ce74deb65a364d717d3fc59557720b8976a8/crates/blockifier/src/state/cached_state.rs#L677)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Good point, i'll need to think about this one :thinking: 

Moving this into native_blockifier will require making `CachedState`'s `cache, class_hash_to_class` and `global_class_hash_to_class` all public, since they are unpacked inside `finalize_transaction_state`.
Alternatively, we can add getters and setters, but that is equally invasive, since no one needs those except `StagedTransactionalState`.
</blockquote></details>

It's part of the Bouncer's state, let's add a comment on that. Once we have a Rust Bouncer, it'll move there.
___
*[`crates/native_blockifier/src/transaction_executor.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/839#-Nc2nJe6DOAsuEiuArI4:-Nc2nJe6DOAsuEiuArI5:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/8be871fb047b97e533ea70bc4e8d133702d19997/crates/native_blockifier/src/transaction_executor.rs#L38)):*
> ```XML
>     // Transactional state, awaiting commit/abort call.
>     // Is `Some` only after transaction has finished executing, and before commit/revert have been
>     // called.None while a transaction is being executed and in between transactions.
> ```





_Suggestion:_
```XML
    // Is `Some` only after transaction has finished executing, and before commit/revert have been
    // called. `None` while a transaction is being executed and in between transactions.
```


<!-- Sent from Reviewable.io -->

2023-08-20 06:09 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/839)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 677 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/839#-Nc2d27j7JI5Gm4pRMOn:-NcGYxhz0CmV-xJFJNXB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/8258ce74deb65a364d717d3fc59557720b8976a8/crates/blockifier/src/state/cached_state.rs#L677)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

It's part of the Bouncer's state, let's add a comment on that. Once we have a Rust Bouncer, it'll move there.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-20 06:18 UTC, elintul reviewed
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/839)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-08-20 07:38 UTC, elintul submitted a review, later dismissed
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/839)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 607 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/839#-NcGs2tJ359WD0HY8KjG:-NcGs2tJ359WD0HY8KjH:b1pvd80) ([raw file](https://github.com/starkware-libs/blockifier/blob/1a7cff8cd2305875e999b59ae12baba9045d98b9/crates/blockifier/src/state/cached_state.rs#L607)):*
> ```XML
>     pub fn abort(self) {}
> }
> ```

Not accurate, this is the state of a transaction applied on it, but not yet committed (I won't say "of a transaction" or "to the blockchain"). 


<!-- Sent from Reviewable.io -->

2023-08-20 08:05 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/839)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @elintul and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 607 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/839#-NcGs2tJ359WD0HY8KjG:-NcGwoI69CnBw-PGRGld:b-g05m6i) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e5c2d6d8d3ac252a4ad855659d1aa38241924bc/crates/blockifier/src/state/cached_state.rs#L607)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not accurate, this is the state of a transaction applied on it, but not yet committed (I won't say "of a transaction" or "to the blockchain").
</blockquote></details>

Whoops, i wrote something and had chatGPT edit it but didn't get a good enough look at its rewrite :scream: 
Thanks :sweat: 

Is it OK now?


<!-- Sent from Reviewable.io -->

2023-08-20 08:28 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/839#-:-NcH2pT088oWczpU6Sdq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 607 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/839#-NcGs2tJ359WD0HY8KjG:-NcH2iOS564dQzmwKaBo:b-77hf4z) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e5c2d6d8d3ac252a4ad855659d1aa38241924bc/crates/blockifier/src/state/cached_state.rs#L607)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Whoops, i wrote something and had chatGPT edit it but didn't get a good enough look at its rewrite :scream: 
Thanks :sweat: 

Is it OK now?
</blockquote></details>

Yup.
No worries. 


<!-- Sent from Reviewable.io -->

2023-08-20 08:28 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/839)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-08-24 07:35 UTC, merged