Remove get_uint256_storage_var_addresses from abi_utils and use Sierr…
starkware-libs/blockifier pull request #857
Opened 2023-08-27 16:25 UTC by barak-b-starkware

…aU256 instead.

2023-08-28 12:13 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/abi/sierra_types.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Ncw2uc-4ns3NmJ-ydRV:-Ncw2uc03oOQOcI6Abm_:bni926c) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c1685d9da5e7cb16c2dbe3817b087858fb91533/crates/blockifier/src/abi/sierra_types.rs#L98)):*
> ```XML
>     }
> 
>     pub fn get_explicit_storage_keys(
> ```

document.

why are those keys explicit?



_Code quote:_
```XML
get_explicit_storage_keys
```


<!-- Sent from Reviewable.io -->

2023-08-28 12:14 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/state/cached_state.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Ncw34WbDjdZbqLyBAwZ:-Ncw34WbDjdZbqLyBAw_:b-y38tes) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c1685d9da5e7cb16c2dbe3817b087858fb91533/crates/blockifier/src/state/cached_state.rs#L86)):*
> ```XML
>         // the block.
>         if let Some(sender_address) = sender_address {
>             let (sender_low_key, _sender_high_key) = SierraU256::get_explicit_storage_keys(
> ```

Why is it computed if it is unused?



_Code quote:_
```XML
_sender_high_key
```


<!-- Sent from Reviewable.io -->

2023-08-28 12:45 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/abi/abi_utils.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/857#-NcwAI1-9zTTNdB3yp13:-NcwAI1-9zTTNdB3yp14:bqwf7cz) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c1685d9da5e7cb16c2dbe3817b087858fb91533/crates/blockifier/src/abi/abi_utils.rs#L58)):*
> ```XML
> }
> 
> pub fn get_erc20_balances_var_address(
> ```

why did you change it?



_Suggestion:_
```XML
 get_erc20_balance_var_addres
```


<!-- Sent from Reviewable.io -->

2023-08-29 08:49 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/abi/abi_utils.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/857#-NcwAI1-9zTTNdB3yp13:-Nd-MybP4EXly09gpwMT:b-caux5i) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c1685d9da5e7cb16c2dbe3817b087858fb91533/crates/blockifier/src/abi/abi_utils.rs#L58)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

why did you change it?
</blockquote></details>

Because of the string `"ERC20_balances"`. It feels wrong to name it `balance` and not `balances` while the specific variable is this string.
But I can change it back if you prefer.
___
*[`crates/blockifier/src/abi/sierra_types.rs` line 98 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Ncw2uc-4ns3NmJ-ydRV:-Nd-Tjwe2nXqIeNMXHAS:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c1685d9da5e7cb16c2dbe3817b087858fb91533/crates/blockifier/src/abi/sierra_types.rs#L98)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

document.

why are those keys explicit?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Ncw34WbDjdZbqLyBAwZ:-Nd-NU7OAT_xI2mPTTAH:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c1685d9da5e7cb16c2dbe3817b087858fb91533/crates/blockifier/src/state/cached_state.rs#L86)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

Why is it computed if it is unused?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-29 08:50 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/abi/abi_utils.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/857#-NcwAI1-9zTTNdB3yp13:-Nd-U-9K-iduvavIsqpE:b-gyrpbj) ([raw file](https://github.com/starkware-libs/blockifier/blob/0c1685d9da5e7cb16c2dbe3817b087858fb91533/crates/blockifier/src/abi/abi_utils.rs#L58)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Because of the string `"ERC20_balances"`. It feels wrong to name it `balance` and not `balances` while the specific variable is this string.
But I can change it back if you prefer.
</blockquote></details>

It return the address of `ERC20_balances[contract_address]`


<!-- Sent from Reviewable.io -->

2023-08-29 08:51 UTC, ilyalesokhin-starkware reviewed
> Reviewed 1 of 5 files at r1, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware)



<!-- Sent from Reviewable.io -->

2023-08-29 08:54 UTC, ilyalesokhin-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 87 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd-V6rE5bewfrODFLHx:-Nd-V6rE5bewfrODFLHy:b-j4rs8i) ([raw file](https://github.com/starkware-libs/blockifier/blob/4cb10ce3ef820d90ddc2c5dd35accae5fe5c96a7/crates/blockifier/src/state/cached_state.rs#L87)):*
> ```XML
>             let sender_key = get_erc20_balances_var_address(&sender_address)?;
>             let key = (fee_token_address, sender_key);
>             // The only requirement for the value is to be different from the previous one.
> ```

why did you add this code?



_Code quote:_
```XML
   // The only requirement for the value is to be different from the previous one.
```


<!-- Sent from Reviewable.io -->

2023-08-29 08:56 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/state/cached_state.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd-VBzlEbomTR0XrULD:-Nd-VBzlEbomTR0XrULE:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4cb10ce3ef820d90ddc2c5dd35accae5fe5c96a7/crates/blockifier/src/state/cached_state.rs#L94)):*
> ```XML
>             // Take into account the future change in the fee_token contract, which takes place
>             // becasue of the fee transfer.
>             storage_updates.insert(key, value);
> ```





_Suggestion:_
```XML
storage_updates.entry((fee_token_address, sender_key)).or_insert_with(StarkFelt::default) += 1
```


<!-- Sent from Reviewable.io -->

2023-08-29 11:02 UTC, ilyalesokhin-starkware reviewed
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: all files reviewed, 1 unresolved discussion (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-08-29 11:07 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/state/cached_state.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd-yRsV-nrg-BW8iVm-:-Nd-yRsW0sZ24t-rgn7i:brvk6ha) ([raw file](https://github.com/starkware-libs/blockifier/blob/52f0889b20390e005405b3736a57ae9a1fe90cc3/crates/blockifier/src/state/cached_state.rs#L85)):*
> ```XML
> 
>         if let Some(sender_address) = sender_address {
>             // False only for L1Handler and Deploy transactions.
> ```

what is false for l1 handlers?



_Code quote:_
```XML
 // False only for L1Handler and Deploy transactions.
```


<!-- Sent from Reviewable.io -->

2023-08-29 11:28 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: all files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd-yRsV-nrg-BW8iVm-:-Nd01UaW3JqXnN5RYgcQ:b-k1sbpn) ([raw file](https://github.com/starkware-libs/blockifier/blob/52f0889b20390e005405b3736a57ae9a1fe90cc3/crates/blockifier/src/state/cached_state.rs#L85)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what is false for l1 handlers?
</blockquote></details>

`L1HandlerTransaction` doesn't have `sender_address` field so in this case the parameter `sender_address` is `None` and we don't enter this `if` block.
```
pub struct L1HandlerTransaction {
pub tx: starknet_api::transaction::L1HandlerTransaction,
pub tx_hash: TransactionHash,
pub paid_fee_on_l1: Fee,
}
```
```
pub struct L1HandlerTransaction {
pub version: TransactionVersion,
pub nonce: Nonce,
pub contract_address: ContractAddress,
pub entry_point_selector: EntryPointSelector,
pub calldata: Calldata,
}
```


<!-- Sent from Reviewable.io -->

2023-08-29 11:30 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/state/cached_state.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd02baB2doj9qhTVbzP:-Nd02baB2doj9qhTVbzQ:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/52f0889b20390e005405b3736a57ae9a1fe90cc3/crates/blockifier/src/state/cached_state.rs#L85)):*
> ```XML
> 
>         if let Some(sender_address) = sender_address {
>             // False only for L1Handler and Deploy transactions.
> ```





_Suggestion:_
```XML
        // `sender_address` is None for L1Handler and Deploy transactions.
        if let Some(sender_address) = sender_address {
          
```


<!-- Sent from Reviewable.io -->

2023-08-29 11:31 UTC, ilyalesokhin-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: all files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd-yRsV-nrg-BW8iVm-:-Nd02tQR5-_FDAlPivWE:b-vwrze6) ([raw file](https://github.com/starkware-libs/blockifier/blob/52f0889b20390e005405b3736a57ae9a1fe90cc3/crates/blockifier/src/state/cached_state.rs#L85)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

`L1HandlerTransaction` doesn't have `sender_address` field so in this case the parameter `sender_address` is `None` and we don't enter this `if` block.
```
pub struct L1HandlerTransaction {
pub tx: starknet_api::transaction::L1HandlerTransaction,
pub tx_hash: TransactionHash,
pub paid_fee_on_l1: Fee,
}
```
```
pub struct L1HandlerTransaction {
pub version: TransactionVersion,
pub nonce: Nonce,
pub contract_address: ContractAddress,
pub entry_point_selector: EntryPointSelector,
pub calldata: Calldata,
}
```
</blockquote></details>

I find this comment confusing.
see bellow.


<!-- Sent from Reviewable.io -->

2023-08-29 11:34 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: all files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd-yRsV-nrg-BW8iVm-:-Nd03SZK8IMGG_scvVSR:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/52f0889b20390e005405b3736a57ae9a1fe90cc3/crates/blockifier/src/state/cached_state.rs#L85)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I find this comment confusing.
see bellow.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 85 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd02baB2doj9qhTVbzP:-Nd03cjb1hQsGl_kimaP:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/52f0889b20390e005405b3736a57ae9a1fe90cc3/crates/blockifier/src/state/cached_state.rs#L85)):*
> ```XML
> 
>         if let Some(sender_address) = sender_address {
>             // False only for L1Handler and Deploy transactions.
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-08-29 11:37 UTC, noaov1 reviewed
Why is it called `SierraU256`?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857#-:-Nd0-4Eb7kiHDeNGKLEG:bd9zdrc)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd0-dlz4wlL93-LPHez:-Nd0-dlz4wlL93-LPHf-:beg77ie) ([raw file](https://github.com/starkware-libs/blockifier/blob/0212ac4b4c9ac6e3efc8e9e8bf028ff6b0004e2c/crates/blockifier/src/state/cached_state.rs#L83)):*
> ```XML
>         // Calculated before executing fee transfer and therefore we add manually the fee transfer
>         // changes. Exclude the fee token contract modification, since it’s charged once throughout
>         // the block.
> ```

I would leave this documentation.



_Code quote:_
```XML
        // Calculated before executing fee transfer and therefore we add manually the fee transfer
        // changes. Exclude the fee token contract modification, since it’s charged once throughout
        // the block.
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd0-IMH9ddqJYe_vsa0:-Nd0-IMH9ddqJYe_vsa1:b-kefb31) ([raw file](https://github.com/starkware-libs/blockifier/blob/4cb10ce3ef820d90ddc2c5dd35accae5fe5c96a7/crates/blockifier/src/state/cached_state.rs#L84)):*
> ```XML
> 
>         if let Some(sender_address) = sender_address {
>             // False only for L1Handler and Deploy transactions.
> ```

And you may want to write it before the `if let`



_Suggestion:_
```XML
// Relevant only in account transactions.
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd003u3DCj3IESuZp59:-Nd003u3DCj3IESuZp5A:bmkr35a) ([raw file](https://github.com/starkware-libs/blockifier/blob/4cb10ce3ef820d90ddc2c5dd35accae5fe5c96a7/crates/blockifier/src/state/cached_state.rs#L94)):*
> ```XML
>             // Take into account the future change in the fee_token contract, which takes place
>             // becasue of the fee transfer.
>             storage_updates.insert(key, value);
> ```

I think `StarkFelt::default()` is okay (and better).
I'll explain: we want the change in the account balance to appear in the storage updates. For every account, the balance is changed in the transaction execution (in the fee transfer) and even more than once for some (if they include a transfer in `__execute__`, for instance).
In the first case- balance 0 will be counted as a storage change since a transaction can only be executed if the account has enough balance at the beginning of the execution.
In the second case- the last value of the balance can be 0 at this point, so the `insert` will do nothing. But it does not matter since the balance has changed anyway.



_Code quote:_
```XML
            // The only requirement for the value is to be different from the previous one.
            let value_as_felt = stark_felt_to_felt(
                storage_updates.get(&key).map_or_else(StarkFelt::default, |v| *v),
            ) + Felt252::from(1_u8);
            let value = felt_to_stark_felt(&value_as_felt);
            // Take into account the future change in the fee_token contract, which takes place
            // becasue of the fee transfer.
            storage_updates.insert(key, value);
```


<!-- Sent from Reviewable.io -->

2023-08-29 12:30 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/state/cached_state.rs` line 86 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd0GOexCaIu4TsP5FNF:-Nd0GOexCaIu4TsP5FNG:b-o754h5) ([raw file](https://github.com/starkware-libs/blockifier/blob/32ef97df7d776dbbc51218922c91acd56d184fb4/crates/blockifier/src/state/cached_state.rs#L86)):*
> ```XML
>         // `sender_address` is None for L1Handler and Deploy transactions.
>         if let Some(sender_address) = sender_address {
>             let sender_key = get_erc20_balance_var_address(&sender_address)?;
> ```

sender_balance



_Suggestion:_
```XML
sender_balance_key
```


<!-- Sent from Reviewable.io -->

2023-08-29 12:30 UTC, ilyalesokhin-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd003u3DCj3IESuZp59:-Nd0GSbt0v9aJvpYdw__:bgz1479) ([raw file](https://github.com/starkware-libs/blockifier/blob/4cb10ce3ef820d90ddc2c5dd35accae5fe5c96a7/crates/blockifier/src/state/cached_state.rs#L94)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I think `StarkFelt::default()` is okay (and better).
I'll explain: we want the change in the account balance to appear in the storage updates. For every account, the balance is changed in the transaction execution (in the fee transfer) and even more than once for some (if they include a transfer in `__execute__`, for instance).
In the first case- balance 0 will be counted as a storage change since a transaction can only be executed if the account has enough balance at the beginning of the execution.
In the second case- the last value of the balance can be 0 at this point, so the `insert` will do nothing. But it does not matter since the balance has changed anyway.
</blockquote></details>

I don't understand the suggestion.


<!-- Sent from Reviewable.io -->

2023-08-29 12:45 UTC, barak-b-starkware reviewed
Because Sierra is typed and Cairo is type-less.
@ilyalesokhin-starkware can you elaborate?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857#-:-Nd0JaEj7-WjDKDoOwkv:b-oo9vyq)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd0-dlz4wlL93-LPHez:-Nd0JA5Z57RqW9trps5b:b-sd06nt) ([raw file](https://github.com/starkware-libs/blockifier/blob/0212ac4b4c9ac6e3efc8e9e8bf028ff6b0004e2c/crates/blockifier/src/state/cached_state.rs#L83)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I would leave this documentation.
</blockquote></details>

Do you mean you think it's better explained this way, and the other new comments should be removed? (Because you suggested a fix for one of them)
___
*[`crates/blockifier/src/state/cached_state.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd0-IMH9ddqJYe_vsa0:-Nd0IdEU0HaUyaBl87_L:besb6cx) ([raw file](https://github.com/starkware-libs/blockifier/blob/4cb10ce3ef820d90ddc2c5dd35accae5fe5c96a7/crates/blockifier/src/state/cached_state.rs#L84)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

And you may want to write it before the `if let`
</blockquote></details>

Done.
It's already before, please look at the last revision :pray:
___
*[`crates/blockifier/src/state/cached_state.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd003u3DCj3IESuZp59:-Nd0Io1L1DU3Yp02sd3J:b-mlbvna) ([raw file](https://github.com/starkware-libs/blockifier/blob/4cb10ce3ef820d90ddc2c5dd35accae5fe5c96a7/crates/blockifier/src/state/cached_state.rs#L94)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't understand the suggestion.
</blockquote></details>

@noaov1 can you please look at the last revision and suggest how to change the code :pray:
___
*[`crates/blockifier/src/state/cached_state.rs` line 86 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd0GOexCaIu4TsP5FNF:-Nd0J9EV5f6GRatcSZ5L:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/32ef97df7d776dbbc51218922c91acd56d184fb4/crates/blockifier/src/state/cached_state.rs#L86)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

sender_balance
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-29 12:47 UTC, ilyalesokhin-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @noaov1)



<!-- Sent from Reviewable.io -->

2023-08-30 07:12 UTC, noaov1 reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: all files reviewed, 7 unresolved discussions (waiting on @barak-b-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/abi/abi_utils.rs` line 58 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd4EePQ3b6q151egCXa:-Nd4EePQ3b6q151egCXb:bc8m2qu) ([raw file](https://github.com/starkware-libs/blockifier/blob/738494b4b2035df6573a3c0468e4dd4c6585a42b/crates/blockifier/src/abi/abi_utils.rs#L58)):*
> ```XML
> }
> 
> pub fn get_erc20_balance_var_address(
> ```

Can you please replace every `get_storage_var_address("ERC20_balances",contract_address)` with this function? (can be done in a separate PR).



_Code quote:_
```XML
pub fn get_erc20_balance_var_address(
```
___
*[`crates/blockifier/src/abi/abi_utils.rs` line 60 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd4Fr8XAMv58qoPdSLN:-Nd4Fr8XAMv58qoPdSLO:b-o9w3p5) ([raw file](https://github.com/starkware-libs/blockifier/blob/738494b4b2035df6573a3c0468e4dd4c6585a42b/crates/blockifier/src/abi/abi_utils.rs#L60)):*
> ```XML
> pub fn get_erc20_balance_var_address(
>     contract_address: &ContractAddress,
> ) -> Result<StorageKey, StarknetApiError> {
> ```

I'm confused. Isn't the balance contains two addresses?



_Code quote:_
```XML
) -> Result<StorageKey, StarknetApiError> {
```
___
*[`crates/blockifier/src/abi/sierra_types.rs` line 52 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd4HHdy5iseBgBDLkeE:-Nd4HHdy5iseBgBDLkeF:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/738494b4b2035df6573a3c0468e4dd4c6585a42b/crates/blockifier/src/abi/sierra_types.rs#L52)):*
> ```XML
> 
> // TODO(barak, 01/10/2023): Move to starknet_api under StorageKey implementation.
> pub fn increment_storage_key(key: &StorageKey) -> Result<StorageKey, StarknetApiError> {
> ```





_Suggestion:_
```XML
pub fn next_storage_key(key: &StorageKey) -> Result<StorageKey, StarknetApiError> {
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd0-dlz4wlL93-LPHez:-Nd4DSR10YnSKj4ugrpU:b-a53nod) ([raw file](https://github.com/starkware-libs/blockifier/blob/0212ac4b4c9ac6e3efc8e9e8bf028ff6b0004e2c/crates/blockifier/src/state/cached_state.rs#L83)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Do you mean you think it's better explained this way, and the other new comments should be removed? (Because you suggested a fix for one of them)
</blockquote></details>

Yes. But it's just my opinion :)
___
*[`crates/blockifier/src/state/cached_state.rs` line 84 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd0-IMH9ddqJYe_vsa0:-Nd4BsPb1DNCsOQOE0jG:bkrqfq1) ([raw file](https://github.com/starkware-libs/blockifier/blob/4cb10ce3ef820d90ddc2c5dd35accae5fe5c96a7/crates/blockifier/src/state/cached_state.rs#L84)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Done.
It's already before, please look at the last revision :pray:
</blockquote></details>

Opps. I think it's better to write an account transaction (rather then specifying non-account ones). And we don't support a deploy transaction in the blockifier :)
___
*[`crates/blockifier/src/state/cached_state.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd003u3DCj3IESuZp59:-Nd4ChRC9isRHwEd7CCD:byhkqpq) ([raw file](https://github.com/starkware-libs/blockifier/blob/4cb10ce3ef820d90ddc2c5dd35accae5fe5c96a7/crates/blockifier/src/state/cached_state.rs#L94)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

@noaov1 can you please look at the last revision and suggest how to change the code :pray:
</blockquote></details>

Sorry. I suggested to use `storage_updates.insert((fee_token_address, sender_balance_key), StarkFelt::default());`
I explained why it's good. 
___
*[`crates/blockifier/src/state/cached_state.rs` line 95 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd4DjR_6XrdFAlhazjf:-Nd4DjR_6XrdFAlhazjg:bhpt4v2) ([raw file](https://github.com/starkware-libs/blockifier/blob/738494b4b2035df6573a3c0468e4dd4c6585a42b/crates/blockifier/src/state/cached_state.rs#L95)):*
> ```XML
>                     &(stark_felt_to_felt(*entry.get()) + Felt252::from(1_u8)),
>                 )),
>                 Entry::Vacant(entry) => *entry.insert(felt_to_stark_felt(&Felt252::from(1_u8))),
> ```

Why `Felt252::from(1_u8)`?



_Code quote:_
```XML
Entry::Vacant(entry) => *entry.insert(felt_to_stark_felt(&Felt252::from(1_u8))),
```


<!-- Sent from Reviewable.io -->

2023-08-30 08:38 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: all files reviewed, 10 unresolved discussions (waiting on @barak-b-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/abi/abi_utils.rs` line 60 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd4Fr8XAMv58qoPdSLN:-Nd4MGxq8lzU7hik0FR-:bshfftp) ([raw file](https://github.com/starkware-libs/blockifier/blob/738494b4b2035df6573a3c0468e4dd4c6585a42b/crates/blockifier/src/abi/abi_utils.rs#L60)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I'm confused. Isn't the balance contains two addresses?
</blockquote></details>

Document that it returns the first address (and the invariant: we store the balance in a consecutive addresses)
___
*[`crates/blockifier/src/abi/sierra_types.rs` line 106 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd4YflV1TziSq-h-RZy:-Nd4YflV1TziSq-h-RZz:bqbneat) ([raw file](https://github.com/starkware-libs/blockifier/blob/738494b4b2035df6573a3c0468e4dd4c6585a42b/crates/blockifier/src/abi/sierra_types.rs#L106)):*
> ```XML
>     /// This function retrieves the storage keys responsible for holding the u256 value based on the
>     /// provided key. An instance of SierraU256 is represented by two consecutive u128 values in
>     /// the storage.
> ```

Why is it relevant `two consecutive u128 values in the storage.`? Why do we care about `u128` and not a Patricia key?
@ilyalesokhin-starkware is it correct?



_Suggestion:_
```XML
    /// provided key. An instance of SierraU256 is represented by two consecutive felts values in
    /// the storage.
```
___
*[`crates/blockifier/src/abi/sierra_types.rs` line 107 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd4UhAsB9UXgUJ3OM_7:-Nd4UhAsB9UXgUJ3OM_8:bx9w6vw) ([raw file](https://github.com/starkware-libs/blockifier/blob/738494b4b2035df6573a3c0468e4dd4c6585a42b/crates/blockifier/src/abi/sierra_types.rs#L107)):*
> ```XML
>     /// provided key. An instance of SierraU256 is represented by two consecutive u128 values in
>     /// the storage.
>     pub fn get_storage_keys(key: StorageKey) -> Result<(StorageKey, StorageKey), StarknetApiError> {
> ```

Will it be removed?
Isn't it a bit odd that it's a method of `SierraU256`that has nothing to do with that type?



_Suggestion:_
```XML
    pub fn get_storage_keys(first_key: StorageKey) -> Result<(StorageKey, StorageKey), StarknetApiError> {
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd003u3DCj3IESuZp59:-Nd4Zgkq02i1HHB4O3Ly:bmwdzei) ([raw file](https://github.com/starkware-libs/blockifier/blob/4cb10ce3ef820d90ddc2c5dd35accae5fe5c96a7/crates/blockifier/src/state/cached_state.rs#L94)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Sorry. I suggested to use `storage_updates.insert((fee_token_address, sender_balance_key), StarkFelt::default());`
I explained why it's good.
</blockquote></details>

You can write:
Add the account balance change to storage updates (we choose a value different from the initial balance, so it will indeed be counted as a change). 
___
*[`crates/blockifier/src/state/state_api.rs` line 54 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd4a0rv-C3HGYQpPA6M:-Nd4a0rv-C3HGYQpPA6N:b-64mwjx) ([raw file](https://github.com/starkware-libs/blockifier/blob/738494b4b2035df6573a3c0468e4dd4c6585a42b/crates/blockifier/src/state/state_api.rs#L54)):*
> ```XML
>     // TODO(Dori, 1/9/2023): NEW_TOKEN_SUPPORT Determine fee token address based on tx version,
>     //   once v3 is introduced.
>     fn get_fee_token_balance(
> ```

Will i return the first key as well?



_Code quote:_
```XML
fn get_fee_token_balance(
```


<!-- Sent from Reviewable.io -->

2023-08-30 08:45 UTC, noaov1 reviewed
> Reviewed 1 of 3 files at r3, 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: all files reviewed, 10 unresolved discussions (waiting on @barak-b-starkware and @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2023-08-30 19:28 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd003u3DCj3IESuZp59:-Nd6epbYBH_noeKV4jxr:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4cb10ce3ef820d90ddc2c5dd35accae5fe5c96a7/crates/blockifier/src/state/cached_state.rs#L94)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

You can write:
Add the account balance change to storage updates (we choose a value different from the initial balance, so it will indeed be counted as a change).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-31 06:54 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/state/cached_state.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd0-dlz4wlL93-LPHez:-Nd9MpfED6ZeiXu5JCqz:bv4l2ia) ([raw file](https://github.com/starkware-libs/blockifier/blob/0212ac4b4c9ac6e3efc8e9e8bf028ff6b0004e2c/crates/blockifier/src/state/cached_state.rs#L83)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

Yes. But it's just my opinion :)
</blockquote></details>

what is "Calculated before executing fee transfer"?


<!-- Sent from Reviewable.io -->

2023-08-31 06:56 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/state/cached_state.rs` line 87 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd9N7er9RRuhFTMPbnj:-Nd9N7es7l9hJrXmwTFd:b-62dxjb) ([raw file](https://github.com/starkware-libs/blockifier/blob/d5f4ce2de0180f0d0f64078228b928b368a71c58/crates/blockifier/src/state/cached_state.rs#L87)):*
> ```XML
>             // Default value is zero, which must be different from the initial balance, otherwise
>             // the transaction would have failed.
>             storage_updates.insert((fee_token_address, sender_balance_key), StarkFelt::default());
> ```

It doesn't explain to motivation for the doing the `storage_updates.insert`



_Code quote:_
```XML
            // Default value is zero, which must be different from the initial balance, otherwise
            // the transaction would have failed.
            storage_updates.insert((fee_token_address, sender_balance_key), StarkFelt::default());
```


<!-- Sent from Reviewable.io -->

2023-08-31 07:05 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/abi/abi_utils.rs` line 59 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd9NuBEAJgWI1fR_UIQ:-Nd9NuBEAJgWI1fR_UIR:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/d5f4ce2de0180f0d0f64078228b928b368a71c58/crates/blockifier/src/abi/abi_utils.rs#L59)):*
> ```XML
> 
> /// Returns the address of the low part of the balance. Notice that we store the balance in two
> /// consecutive cells in memory.
> ```





_Suggestion:_
```XML
/// Returns the storage key corresponding to the first storage cell where the balance of `contract_address` is stored.
/// Note that the reference implementation of an ERC20 stores the balance in two consecutive storage cells.
```


<!-- Sent from Reviewable.io -->

2023-08-31 07:09 UTC, ilyalesokhin-starkware reviewed
> Reviewed 4 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2023-08-31 07:09 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/abi/abi_utils.rs` line 59 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd9NuBEAJgWI1fR_UIQ:-Nd9QDivEU3Jy2oLMLcT:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d5f4ce2de0180f0d0f64078228b928b368a71c58/crates/blockifier/src/abi/abi_utils.rs#L59)):*
> ```XML
> 
> /// Returns the address of the low part of the balance. Notice that we store the balance in two
> /// consecutive cells in memory.
> ```

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd0-dlz4wlL93-LPHez:-Nd9P2lM5UZpQ2LWYnCF:b6ovcn4) ([raw file](https://github.com/starkware-libs/blockifier/blob/0212ac4b4c9ac6e3efc8e9e8bf028ff6b0004e2c/crates/blockifier/src/state/cached_state.rs#L83)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

what is "Calculated before executing fee transfer"?
</blockquote></details>

This function calculates the actual state changes. So, we say everything happens before we make the fee transfer.
Do you have any better wording for that?



_Code quote:_
```XML
    pub fn get_actual_state_changes_for_fee_charge(
```
___
*[`crates/blockifier/src/state/cached_state.rs` line 87 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd9N7er9RRuhFTMPbnj:-Nd9PbpVB9y-izMR3-NX:b130z6q) ([raw file](https://github.com/starkware-libs/blockifier/blob/d5f4ce2de0180f0d0f64078228b928b368a71c58/crates/blockifier/src/state/cached_state.rs#L87)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

It doesn't explain to motivation for the doing the `storage_updates.insert`
</blockquote></details>

I tried to move the motivation part above the beginning of the `if` block, WDYT? 



_Code quote:_
```XML
        // Calculated before executing fee transfer and therefore, for account transactions, we add
        // manually the fee transfer changes.
```


<!-- Sent from Reviewable.io -->

2023-08-31 07:30 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/state/cached_state.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd0-dlz4wlL93-LPHez:-Nd9V-teEg-axEm1aQra:b-93xr18) ([raw file](https://github.com/starkware-libs/blockifier/blob/0212ac4b4c9ac6e3efc8e9e8bf028ff6b0004e2c/crates/blockifier/src/state/cached_state.rs#L83)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

This function calculates the actual state changes. So, we say everything happens before we make the fee transfer.
Do you have any better wording for that?
</blockquote></details>

I don't understand :(


<!-- Sent from Reviewable.io -->

2023-08-31 08:07 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/state/cached_state.rs` line 82 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd9awgE7TWhsmg-5yfT:-Nd9awgE7TWhsmg-5yfU:bm7q0hl) ([raw file](https://github.com/starkware-libs/blockifier/blob/d5f4ce2de0180f0d0f64078228b928b368a71c58/crates/blockifier/src/state/cached_state.rs#L82)):*
> ```XML
> 
>         // Calculated before executing fee transfer and therefore, for account transactions, we add
>         // manually the fee transfer changes.
> ```

If this transaction originates from an account contract, make sure the fee transfer related changes are included in the list of state changes.
Note that we can use any value here as it is going to be overridden later.



_Code quote:_
```XML
        // Calculated before executing fee transfer and therefore, for account transactions, we add
        // manually the fee transfer changes.
```


<!-- Sent from Reviewable.io -->

2023-08-31 09:37 UTC, noaov1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @barak-b-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd0-dlz4wlL93-LPHez:-Nd9vSkV8A7pUkrqu9vx:b-9m90ib) ([raw file](https://github.com/starkware-libs/blockifier/blob/0212ac4b4c9ac6e3efc8e9e8bf028ff6b0004e2c/crates/blockifier/src/state/cached_state.rs#L83)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

I don't understand :(
</blockquote></details>

I'll try to explain: We compute the state changes of a transaction to know the L1 data availability cost (so we know how much fee we need to charge). Therefore, it is done before we execute ("on" the state) the fee transfer. Hence, we need to add the fee transfer changes manually. We only add the account balance change (and exclude the sequencer balance and the ERC20 modification).


<!-- Sent from Reviewable.io -->

2023-08-31 10:26 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/state/cached_state.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd0-dlz4wlL93-LPHez:-NdA63EnADwe9H4QNzg0:bivhakq) ([raw file](https://github.com/starkware-libs/blockifier/blob/0212ac4b4c9ac6e3efc8e9e8bf028ff6b0004e2c/crates/blockifier/src/state/cached_state.rs#L83)):*
<details><summary><i>Previously, noaov1 (Noa Oved) wrote…</i></summary><blockquote>

I'll try to explain: We compute the state changes of a transaction to know the L1 data availability cost (so we know how much fee we need to charge). Therefore, it is done before we execute ("on" the state) the fee transfer. Hence, we need to add the fee transfer changes manually. We only add the account balance change (and exclude the sequencer balance and the ERC20 modification).
</blockquote></details>

So maybe some like:

We need to compute the transaction fee before we can execute the fee transfer, and the fee should cover the state changes that happen in the
fee transfer.
The fee transfer is going to update the balance of the sequencer and the balance of the sender contract, but we don't charge the sender for the sequencer balance change as it is amortized across the block.


<!-- Sent from Reviewable.io -->

2023-08-31 13:18 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/state/cached_state.rs` line 82 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nd9awgE7TWhsmg-5yfT:-NdAjXrQ6Uz3E9ouHsqC:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d5f4ce2de0180f0d0f64078228b928b368a71c58/crates/blockifier/src/state/cached_state.rs#L82)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

If this transaction originates from an account contract, make sure the fee transfer related changes are included in the list of state changes.
Note that we can use any value here as it is going to be overridden later.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-31 13:28 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/abi/abi_utils.rs` line 61 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/857#-NdAltjY16zdUKnq-W9B:-NdAltjY16zdUKnq-W9C:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/260fc3d54884f48d0270f6fbfdf45ddc6556ae1e/crates/blockifier/src/abi/abi_utils.rs#L61)):*
> ```XML
> /// `contract_address` is stored. Note that the reference implementation of an ERC20 stores the
> /// balance in two consecutive storage cells.
> pub fn get_erc20_balance_var_address(
> ```





_Suggestion:_
```XML
/// Returns the storage key corresponding to the first storage cell where the balance of
/// `contract_address` is stored. Note that fee token contract stores the
/// balance in two consecutive storage cells.
pub fn get_fee_token_balance_var_address(
```


<!-- Sent from Reviewable.io -->

2023-08-31 13:49 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: 1 of 8 files reviewed, 5 unresolved discussions (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/abi/abi_utils.rs` line 61 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/857#-NdAltjY16zdUKnq-W9B:-NdAohsP0Kkh6KXnnj3c:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/260fc3d54884f48d0270f6fbfdf45ddc6556ae1e/crates/blockifier/src/abi/abi_utils.rs#L61)):*
> ```XML
> /// `contract_address` is stored. Note that the reference implementation of an ERC20 stores the
> /// balance in two consecutive storage cells.
> pub fn get_erc20_balance_var_address(
> ```

Done.
___
*[`crates/blockifier/src/state/cached_state.rs` line 89 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/857#-NdAm92j7T_ooA2TVoWV:-NdAotnJBqCvKkk0A-NB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/260fc3d54884f48d0270f6fbfdf45ddc6556ae1e/crates/blockifier/src/state/cached_state.rs#L89)):*
> ```XML
>             let sender_balance_key = get_erc20_balance_var_address(&sender_address)?;
>             // Default value is zero, which must be different from the initial balance, otherwise
>             // the transaction would have failed.
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-08-31 14:47 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/abi/abi_utils.rs` line 61 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/857#-NdAltjY16zdUKnq-W9B:-NdB2nQi5yzcX0iBe-ft:bmg71w8) ([raw file](https://github.com/starkware-libs/blockifier/blob/260fc3d54884f48d0270f6fbfdf45ddc6556ae1e/crates/blockifier/src/abi/abi_utils.rs#L61)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

FeeToken::get_contract_address_balance_storage_address
</blockquote></details>

FeeToken::get_storage_key_of_balance_for
?


<!-- Sent from Reviewable.io -->

2023-08-31 14:53 UTC, ilyalesokhin-starkware commented
*[`crates/blockifier/src/abi/abi_utils.rs` line 61 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/857#-NdAltjY16zdUKnq-W9B:-NdB47Dn8yep3P-My-dN:b-s8loge) ([raw file](https://github.com/starkware-libs/blockifier/blob/260fc3d54884f48d0270f6fbfdf45ddc6556ae1e/crates/blockifier/src/abi/abi_utils.rs#L61)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

FeeToken::get_storage_key_of_balance_for
?
</blockquote></details>

/// Returns the storage key inside the fee token corresponding to the first storage cell where the balance of
/// `contract_address` is stored. Note that the reference implementation of an ERC20 stores the
/// balance in two consecutive storage cells.


pub fn get_balance_storage_key


<!-- Sent from Reviewable.io -->

2023-09-03 07:01 UTC, ilyalesokhin-starkware requested changes
> Reviewed 1 of 8 files at r7, 1 of 1 files at r9, 2 of 7 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @barak-b-starkware and @noaov1)



<!-- Sent from Reviewable.io -->

2023-10-03 06:47 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware and @noaov1)

___
*[`crates/blockifier/src/abi/abi_utils.rs` line 61 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/857#-NdAltjY16zdUKnq-W9B:-NfoBb-uBGjH6NPIDY-r:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/260fc3d54884f48d0270f6fbfdf45ddc6556ae1e/crates/blockifier/src/abi/abi_utils.rs#L61)):*
<details><summary><i>Previously, ilyalesokhin-starkware wrote…</i></summary><blockquote>

/// Returns the storage key inside the fee token corresponding to the first storage cell where the balance of
/// `contract_address` is stored. Note that the reference implementation of an ERC20 stores the
/// balance in two consecutive storage cells.


pub fn get_balance_storage_key
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-03 08:32 UTC, dorimedini-starkware requested changes
> Reviewed 7 of 7 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: all files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 90 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/857#-NfodGVKCOK4GvYBp-OG:-NfodGVKCOK4GvYBp-OH:b-nvqu23) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd4ea1a13206493c794f50a2f7767642dfdf4a18/crates/blockifier/src/state/cached_state.rs#L90)):*
> ```XML
>             // StarkFelt::default() value is zero, which must be different from the initial balance,
>             // otherwise the transaction would have failed the "max fee lower than
>             // balance" validation.
> ```

What does this comment explain?
And, if `max_fee=0` (i.e. no fee charge), you may indeed have a balance of zero; not sure if it's relevant but the comment seems incorrect



_Code quote:_
```XML
            // StarkFelt::default() value is zero, which must be different from the initial balance,
            // otherwise the transaction would have failed the "max fee lower than
            // balance" validation.
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 104 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/857#-NfoddNF3qMpXW9e6Wby:-NfoddNF3qMpXW9e6Wbz:b-5krw97) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd4ea1a13206493c794f50a2f7767642dfdf4a18/crates/blockifier/src/transaction/account_transactions_test.rs#L104)):*
> ```XML
>     // can pay for the transaction execution.
>     let deployed_account_balance_key =
>         get_fee_token_var_address(&contract_address!(*account_address.0.key()));
> ```

isn't `account_address` already of the correct type?



_Suggestion:_
```XML
account_address
```
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 320 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nfodj2vBGCuxbM4HFEp:-Nfodj2vBGCuxbM4HFEq:b-7ropln) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd4ea1a13206493c794f50a2f7767642dfdf4a18/crates/blockifier/src/transaction/account_transactions_test.rs#L320)):*
> ```XML
>     // can pay for the transaction execution.
>     let deployed_account_balance_key =
>         get_fee_token_var_address(&contract_address!(*deployed_account_address.0.key()));
> ```

ditto



_Suggestion:_
```XML
deployed_account_address
```
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 789 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/857#-NfodwJnEP3BUd2zCmIT:-NfodwJo8lFxjUhS0OqM:b-7ropln) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd4ea1a13206493c794f50a2f7767642dfdf4a18/crates/blockifier/src/transaction/transactions_test.rs#L789)):*
> ```XML
>     // can pay for the transaction execution.
>     let deployed_account_balance_key =
>         get_fee_token_var_address(&contract_address!(*deployed_account_address.0.key()));
> ```

ditto



_Suggestion:_
```XML
deployed_account_address
```
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 149 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nfoe0Q0D5douYrzakPp:-Nfoe0Q0D5douYrzakPq:b-7ropln) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd4ea1a13206493c794f50a2f7767642dfdf4a18/crates/native_blockifier/bench/blockifier_bench.rs#L149)):*
> ```XML
>         nonces.push(1_u64);
>         let deployed_account_balance_key =
>             get_fee_token_var_address(&contract_address!(*deployed_account_address.0.key()));
> ```

ditto



_Suggestion:_
```XML
deployed_account_address
```


<!-- Sent from Reviewable.io -->

2023-10-03 10:42 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/state/cached_state.rs` line 90 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/857#-NfodGVKCOK4GvYBp-OG:-Nfp6ySc5DOvBQ1JaVvB:b-bbz1xb) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd4ea1a13206493c794f50a2f7767642dfdf4a18/crates/blockifier/src/state/cached_state.rs#L90)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

This comment explains why we insert `StarkFelt::default()` as the value for the `(fee_token_address, sender_balance_key)` key. Do you think it's redundant?
Regarding correctness, is `max_fee=0` supported somehow, and the `get_actual_state_changes_for_fee_charge` method of the `CachedState` might be called in some flow that supports it?
The alternative is to "pull" the balance and add something, but it's less elegant (code-wise).

Anyway, notice that the `StarkFelt::default()` is also inserted before this PR, so if there is a correctness problem, it needs to be handled regardless of the PR.
</blockquote></details>

ah, didn't see the `default()`... my bad
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 104 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/857#-NfoddNF3qMpXW9e6Wby:-Nfp7DiiBvtksPyYlrtg:b12q3yp) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd4ea1a13206493c794f50a2f7767642dfdf4a18/crates/blockifier/src/transaction/account_transactions_test.rs#L104)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

get_storage_var_address signature:
```
pub fn get_storage_var_address(storage_var_name: &str, args: &[StarkFelt]) -> StorageKey
```
gets `&str`.

get_fee_token_address signature:
```
pub fn get_fee_token_var_address(contract_address: &ContractAddress) -> StorageKey
```
whereas `get_fee_token_address` gets `&ContractAddress`

Maybe there is a shortcut for the `&contract_address!(*account_address.0.key())` conversion?
</blockquote></details>

still unclear...
the type of `account_address` is `&ContractAddress`.
the `contract_address!` macro outputs an instance of `ContractAddress`, so the type of `&contract_address!(...)` is the same as `account_address`, no?
Why the conversion?
No string is used or created here


<!-- Sent from Reviewable.io -->

2023-10-03 13:22 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @ilyalesokhin-starkware)

___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 104 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/857#-NfoddNF3qMpXW9e6Wby:-Nfp9g2r8DS4EDnMmVtE:b-f2ckwf) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd4ea1a13206493c794f50a2f7767642dfdf4a18/crates/blockifier/src/transaction/account_transactions_test.rs#L104)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

still unclear...
the type of `account_address` is `&ContractAddress`.
the `contract_address!` macro outputs an instance of `ContractAddress`, so the type of `&contract_address!(...)` is the same as `account_address`, no?
Why the conversion?
No string is used or created here
</blockquote></details>

Right! I missed it (: 
___
*[`crates/blockifier/src/transaction/account_transactions_test.rs` line 320 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nfodj2vBGCuxbM4HFEp:-Nfp9oGv6V2AeqIS5zjx:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd4ea1a13206493c794f50a2f7767642dfdf4a18/crates/blockifier/src/transaction/account_transactions_test.rs#L320)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions_test.rs` line 789 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/857#-NfodwJnEP3BUd2zCmIT:-NfpA6Sy8bgyNykktDZ9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd4ea1a13206493c794f50a2f7767642dfdf4a18/crates/blockifier/src/transaction/transactions_test.rs#L789)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`crates/native_blockifier/bench/blockifier_bench.rs` line 149 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/857#-Nfoe0Q0D5douYrzakPp:-NfpADsL9--vsxxzXZli:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/dd4ea1a13206493c794f50a2f7767642dfdf4a18/crates/native_blockifier/bench/blockifier_bench.rs#L149)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-03 13:28 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857#-:-NfpiOrJ1AgSXoqj8RR1:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2023-10-03 13:30 UTC, dorimedini-starkware approved these changes
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: all files reviewed, 1 unresolved discussion (waiting on @ilyalesokhin-starkware)



<!-- Sent from Reviewable.io -->

2023-10-04 04:50 UTC, ilyalesokhin-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 7 files at r12, 1 of 4 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857#-:-Nft0Xeq7YdjpCBmdOLx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)



<!-- Sent from Reviewable.io -->

2023-10-04 07:24 UTC, dorimedini-starkware approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/857)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @barak-b-starkware)



<!-- Sent from Reviewable.io -->

2023-10-04 11:55 UTC, merged