Adjust Declare transaction to V3 changes in starknet-api.
starkware-libs/blockifier pull request #866
Opened 2023-08-31 08:58 UTC by barak-b-starkware

2023-08-31 09:21 UTC, elintul requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: all files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware and @MohammadNassar1)

___
*[`Cargo.toml` line 49 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Nd9slbO2QhtLhDcZA5C:-Nd9slbO2QhtLhDcZA5D:b-eaidc2) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f5e09655c99641ec008980c0e4111ef60a2e48/Cargo.toml#L49)):*
> ```TOML
> thiserror = "1.0.37"
> 
> [patch.crates-io]
> ```

Is this enough to compile? I think Papyrus also needs to be patched.
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 153 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Nd9sp0p89Fhtp8giojU:-Nd9sp0p89Fhtp8giojV:b-bgqpgc) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f5e09655c99641ec008980c0e4111ef60a2e48/crates/blockifier/src/transaction/account_transaction.rs#L153)):*
> ```XML
>                 AccountTransactionContext {
>                     transaction_hash: tx.tx_hash(),
>                     max_fee: match sn_api_tx {
> ```

Perhaps we also need an aggregated one for `AccountTransaction` too (in another PR).



_Code quote:_
```XML
max_fee: match sn_api_tx
```
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Nd9sxJJ7uSBeFkBFAXA:-Nd9sxJK2p-LsRLwee57:bsxxnzt) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f5e09655c99641ec008980c0e4111ef60a2e48/crates/blockifier/src/transaction/account_transaction.rs#L161)):*
> ```XML
>                             // block_context.gas_price.
>                             Fee(tx.resource_bounds.max_price_per_unit
>                                 * tx.resource_bounds.max_amount as u128)
> ```

Why not now? Also, this is duplicated... define a small function receiving resource bounds.



_Code quote:_
```XML
                            // TODO(barak, 01/10/2023): Change to max_price_per_unit *
                            // block_context.gas_price.
                            Fee(tx.resource_bounds.max_price_per_unit
                                * tx.resource_bounds.max_amount as u128)
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Nd9t9V32k0KfAnjkQOl:-Nd9t9V32k0KfAnjkQOm:b-ahpe7m) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f5e09655c99641ec008980c0e4111ef60a2e48/crates/blockifier/src/transaction/transactions.rs#L137)):*
> ```XML
>                     contract_class: contract_class.into(),
>                 })
>             }
> ```

Can we share this code?
___
*[`crates/blockifier/src/transaction/transactions.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Nd9tFk1Aa7z3BQrRSwZ:-Nd9tFk1Aa7z3BQrRSw_:b-oz0mcg) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f5e09655c99641ec008980c0e4111ef60a2e48/crates/blockifier/src/transaction/transactions.rs#L181)):*
> ```XML
>     }
> 
>     pub fn max_fee(&self) -> Fee {
> ```

Use above?



_Code quote:_
```XML
pub fn max_fee(&self) -> Fee
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Nd9tD3a6kYHGotpmBF9:-Nd9tD3a6kYHGotpmBFA:b-ahpe7m) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f5e09655c99641ec008980c0e4111ef60a2e48/crates/blockifier/src/transaction/transactions.rs#L211)):*
> ```XML
>                 Ok(None)
>             }
>             starknet_api::transaction::DeclareTransaction::V2(tx) => {
> ```

Can we share this code?


<!-- Sent from Reviewable.io -->

2023-08-31 13:42 UTC, elintul reviewed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: all files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2023-09-05 11:13 UTC, elintul requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 112 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Nd_20V8CYlBESP2Zwde:-Nd_20V8CYlBESP2Zwdf:b-mpt5bt) ([raw file](https://github.com/starkware-libs/blockifier/blob/551d0d3f5a342e107a6acb77351e95eb3653909b/crates/blockifier/src/transaction/account_transaction.rs#L112)):*
> ```XML
>                 AccountTransactionContext {
>                     transaction_hash: tx.tx_hash(),
>                     max_fee: tx.max_fee(),
> ```

Where is this implemented?



_Code quote:_
```XML
max_fee()
```


<!-- Sent from Reviewable.io -->

2023-09-08 04:49 UTC, elintul requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: all files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware and @MohammadNassar1)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ndn6m494wE0kgoAPMGc:-Ndn6m494wE0kgoAPMGd:b-mftnul) (no related file):*
Need to add `account_deployment_data` to declare and invoke.

___
___
*[`crates/native_blockifier/src/py_transaction.rs` line 48 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ndn6_oODmL_J14e0e6G:-Ndn6_oODmL_J14e0e6H:b-29sewk) ([raw file](https://github.com/starkware-libs/blockifier/blob/85caa387d3d323012503fe1f21bdf0ee0eacbdfa/crates/native_blockifier/src/py_transaction.rs#L48)):*
> ```XML
> #[pyclass]
> #[derive(Clone)]
> pub enum PyDataAvailabilityMode {
> ```

@giladchase, PTAL too?



_Code quote:_
```XML
pub enum PyDataAvailabilityMode
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 147 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ndn6hO70RcehYzWb0ZC:-Ndn6hO70RcehYzWb0ZD:bqucrg6) ([raw file](https://github.com/starkware-libs/blockifier/blob/85caa387d3d323012503fe1f21bdf0ee0eacbdfa/crates/native_blockifier/src/py_transaction.rs#L147)):*
> ```XML
>                 py_attr(tx, "fee_data_availability_mode")?;
>             let fee_data_availability_mode =
>                 DataAvailabilityMode::try_from(py_fee_data_availability_mode)?;
> ```

This can be shared code between all three, right?



_Code quote:_
```XML
            let tip = Tip(py_attr::<u64>(tx, "tip")?);
            let py_resource_bounds: PyResourceBounds = py_attr(tx, "resource_bounds")?;
            let resource_bounds = ResourceBounds::from(py_resource_bounds);
            let py_nonce_data_availability_mode: PyDataAvailabilityMode =
                py_attr(tx, "nonce_data_availability_mode")?;
            let nonce_data_availability_mode =
                DataAvailabilityMode::try_from(py_nonce_data_availability_mode)?;
            let py_fee_data_availability_mode: PyDataAvailabilityMode =
                py_attr(tx, "fee_data_availability_mode")?;
            let fee_data_availability_mode =
                DataAvailabilityMode::try_from(py_fee_data_availability_mode)?;
```


<!-- Sent from Reviewable.io -->

2023-09-08 17:41 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @elintul, @MohammadNassar1, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ndn6m494wE0kgoAPMGc:-Ndprwgh4PExGorTWfo7:b-ifj62n) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Need to add `account_deployment_data` to declare and invoke.
</blockquote></details>

I think you mean `account_init_code`, and also `paymaster_address` should be added to all three, right?
I've just found the SNIP so I'll first change it in starknet_api and then in `blockifier` and `papyrus`,

___
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Nd9sxJJ7uSBeFkBFAXA:-Ndpl-wCB-Qzx8uqD4zI:b-fry5jj) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f5e09655c99641ec008980c0e4111ef60a2e48/crates/blockifier/src/transaction/account_transaction.rs#L161)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not now? Also, this is duplicated... define a small function receiving resource bounds.
</blockquote></details>

As we've discussed, I suggest to add block_context to the max fee after the upgrade (:
___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 112 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Nd_20V8CYlBESP2Zwde:-NdplFVh6rn4E2IdqL0S:b3sefsk) ([raw file](https://github.com/starkware-libs/blockifier/blob/551d0d3f5a342e107a6acb77351e95eb3653909b/crates/blockifier/src/transaction/account_transaction.rs#L112)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Where is this implemented?
</blockquote></details>

In `crates/blockifier/src/transaction/transactions.rs` under `impl DeclareTransaction`
___
*[`crates/blockifier/src/transaction/transactions.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Nd9t9V32k0KfAnjkQOl:-NdpltSW1QsGTIcEdwbm:bvrxj0j) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f5e09655c99641ec008980c0e4111ef60a2e48/crates/blockifier/src/transaction/transactions.rs#L137)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we share this code?
</blockquote></details>

I didn't find an elegant way to share this code. We `match` the tx itself, so we must specify `...::V?` in the return value.
But maybe @yair-starkware has an idea?
___
*[`crates/blockifier/src/transaction/transactions.rs` line 181 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Nd9tFk1Aa7z3BQrRSwZ:-NdpnLDBDJTxgNp7BOXJ:b-7zi8tj) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f5e09655c99641ec008980c0e4111ef60a2e48/crates/blockifier/src/transaction/transactions.rs#L181)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Use above?
</blockquote></details>

WDYM?
___
*[`crates/blockifier/src/transaction/transactions.rs` line 211 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Nd9tD3a6kYHGotpmBF9:-NdpnUA2DHV5gfB_Drk2:b-wr47zq) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f5e09655c99641ec008980c0e4111ef60a2e48/crates/blockifier/src/transaction/transactions.rs#L211)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we share this code?
</blockquote></details>

It's shared for V2 and V3. I miss something here?
___
*[`crates/native_blockifier/src/py_transaction.rs` line 147 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ndn6hO70RcehYzWb0ZC:-NdpqN1Z7NQnjdoHXVLE:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/85caa387d3d323012503fe1f21bdf0ee0eacbdfa/crates/native_blockifier/src/py_transaction.rs#L147)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This can be shared code between all three, right?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-09 08:25 UTC, elintul requested changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @MohammadNassar1, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ndn6m494wE0kgoAPMGc:-Ndt1oXYDX4vaIYx-a1w:b-4nyp79) (no related file):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I think you mean `account_init_code`, and also `paymaster_address` should be added to all three, right?
I've just found the SNIP so I'll first change it in starknet_api and then in `blockifier` and `papyrus`,
</blockquote></details>

Yup, thanks! 

___


<!-- Sent from Reviewable.io -->

2023-09-10 08:08 UTC, yair-starkware commented
*[`crates/blockifier/src/transaction/transactions.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Nd9t9V32k0KfAnjkQOl:-Ndy4QgSCuLBueNr-I5I:b-qdd20s) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f5e09655c99641ec008980c0e4111ef60a2e48/crates/blockifier/src/transaction/transactions.rs#L137)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I didn't find an elegant way to share this code. We `match` the tx itself, so we must specify `...::V?` in the return value.
But maybe @yair-starkware has an idea?
</blockquote></details>

In our code, I create an enum called ExecutableTransactionInput where each variant must be a valid combination of the transaction and its additional data, so the checks are being done by the compilation/deserialization.
Here I think you can improve the code by writing a function for the class conversion.


<!-- Sent from Reviewable.io -->

2023-09-10 11:54 UTC, elintul requested changes
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: all files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware, @giladchase, and @MohammadNassar1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 69 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/866#-NdywF1P84i1R7bUMsNo:-NdywF1P84i1R7bUMsNp:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/70e2efb0712a9b7f32cee810e2a36ee02a1c31cb/crates/native_blockifier/src/py_transaction.rs#L69)):*
> ```XML
> }
> 
> pub struct V3NewParameters {
> ```





_Suggestion:_
```XML
CommonTransactionFields
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 71 at r8](https://reviewable.io/reviews/starkware-libs/blockifier/866#-NdywJeb6sprgbiURutJ:-NdywJeb6sprgbiURutK:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/70e2efb0712a9b7f32cee810e2a36ee02a1c31cb/crates/native_blockifier/src/py_transaction.rs#L71)):*
> ```XML
> pub struct V3NewParameters {
>     pub resource_bounds: ResourceBounds,
>     pub resource: Resource,
> ```





_Suggestion:_
```XML
    pub resource_bounds: ResourceBoundsMapping,
```


<!-- Sent from Reviewable.io -->

2023-09-11 02:29 UTC, elintul requested changes
> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware, @giladchase, and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 177 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne12v5DEQ_XmKf1JuBW:-Ne12v5DEQ_XmKf1JuBX:b-nr4jdv) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa4ff457325631dbf0b4543c89a21ee91b5b24d8/crates/blockifier/src/transaction/account_transaction.rs#L177)):*
> ```XML
>                     TransactionVersion(StarkFelt::from(1_u8)),
>                     TransactionVersion(StarkFelt::from(2_u8)),
>                     TransactionVersion(StarkFelt::from(3_u8)),
> ```

Want to use constants? 
___
*[`crates/blockifier/src/transaction/transactions.rs` line 189 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne12ygw5olgQ4sobBqJ:-Ne12ygw5olgQ4sobBqK:b-wbyamm) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa4ff457325631dbf0b4543c89a21ee91b5b24d8/crates/blockifier/src/transaction/transactions.rs#L189)):*
> ```XML
>             starknet_api::transaction::DeclareTransaction::V3(tx) => {
>                 // TODO(barak, 01/10/2023): Change to max_price_per_unit * block_context.gas_price.
>                 Fee(tx
> ```

Get the resource once, instead of repeating code.
Why is `map_or` needed?
Also, can this code be shared (we can do it after the upgrade). 
___
*[`crates/native_blockifier/src/py_transaction.rs` line 72 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne13L-c6PEVQjcZpfRb:-Ne13L-d63GEGQU5-yLk:b-qnswz9) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa4ff457325631dbf0b4543c89a21ee91b5b24d8/crates/native_blockifier/src/py_transaction.rs#L72)):*
> ```XML
>         let mut resource_bounds_mapping = BTreeMap::new();
>         resource_bounds_mapping.insert(
>             Resource::L1Gas,
> ```

Use a loop, instead of repeating code. You can ask ChatGPT to refactor. :) 


<!-- Sent from Reviewable.io -->

2023-09-12 11:50 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @elintul, @giladchase, @MohammadNassar1, and @yair-starkware)

___
*[`crates/blockifier/src/transaction/account_transaction.rs` line 177 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne12v5DEQ_XmKf1JuBW:-Ne7sBdZEq46W5jOU8Ll:bo30028) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa4ff457325631dbf0b4543c89a21ee91b5b24d8/crates/blockifier/src/transaction/account_transaction.rs#L177)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Want to use constants?
</blockquote></details>

Yes (: I do it once for all txs types in another PR:
https://reviewable.io/reviews/starkware-libs/blockifier/904
___
*[`crates/blockifier/src/transaction/transactions.rs` line 137 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Nd9t9V32k0KfAnjkQOl:-Ne86AOY9JIfU_w0FJa3:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/49f5e09655c99641ec008980c0e4111ef60a2e48/crates/blockifier/src/transaction/transactions.rs#L137)):*
<details><summary><i>Previously, yair-starkware (Yair) wrote…</i></summary><blockquote>

In our code, I create an enum called ExecutableTransactionInput where each variant must be a valid combination of the transaction and its additional data, so the checks are being done by the compilation/deserialization.
Here I think you can improve the code by writing a function for the class conversion.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 189 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne12ygw5olgQ4sobBqJ:-Ne87JQ0CSql8_hX6zcU:b-8p3l73) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa4ff457325631dbf0b4543c89a21ee91b5b24d8/crates/blockifier/src/transaction/transactions.rs#L189)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Get the resource once, instead of repeating code.
Why is `map_or` needed?
Also, can this code be shared (we can do it after the upgrade).
</blockquote></details>

Done.
1. The 'get' method of the dictionary returns an `Option` so we need the `map_or` (maybe there is more elegant way to do that? @yair-starkware?)
2. By "share this code" do you mean with the `max_fee` of `DeployAccount` and `Invoke`?
___
*[`crates/native_blockifier/src/py_transaction.rs` line 72 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne13L-c6PEVQjcZpfRb:-Ne8BY5z7CBTfy7K4QwY:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa4ff457325631dbf0b4543c89a21ee91b5b24d8/crates/native_blockifier/src/py_transaction.rs#L72)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Use a loop, instead of repeating code. You can ask ChatGPT to refactor. :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-12 11:56 UTC, elintul requested changes
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: all files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware, @giladchase, @MohammadNassar1, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8ESSa9Wi_xPgx-Bch:-Ne8ESSa9Wi_xPgx-Bci:b-gt4u1t) (no related file):*
Please add Gilad as a reviewer.

___
___
*[`crates/blockifier/src/transaction/transactions.rs` line 189 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne12ygw5olgQ4sobBqJ:-Ne8EY-G0CF4GGbbRpzg:b86yfmv) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa4ff457325631dbf0b4543c89a21ee91b5b24d8/crates/blockifier/src/transaction/transactions.rs#L189)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

Done.
1. The 'get' method of the dictionary returns an `Option` so we need the `map_or` (maybe there is more elegant way to do that? @yair-starkware?)
2. By "share this code" do you mean with the `max_fee` of `DeployAccount` and `Invoke`?
</blockquote></details>

Yes.
For now, give `l1_max_amount` a name, so this line is easier to read.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 121 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8EQEz15CzwllyaQaT:-Ne8EQEz15CzwllyaQaU:bz7sjil) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e342ae665325a157c468b9442d769477f0bafbd/crates/blockifier/src/transaction/transactions.rs#L121)):*
> ```XML
>     match contract_class {
>         ContractClass::V0(_) => {
>             if let 0 | 1 = ver {
> ```

Can you explain this annotation?



_Code quote:_
```XML
if let 0 | 1 = ver {
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 127 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8EoDI3TYHyt8B7puY:-Ne8EoDI3TYHyt8B7puZ:b45h) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e342ae665325a157c468b9442d769477f0bafbd/crates/native_blockifier/src/py_transaction.rs#L127)):*
> ```XML
> }
> 
> fn get_common_transaction_fields(tx: &PyAny) -> NativeBlockifierResult<CommonTransactionFields> {
> ```





_Suggestion:_
```XML
build_common_tx_fields
```
___
*[`crates/native_blockifier/src/py_transaction.rs` line 190 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8EvkqBOHXeNIz13gf:-Ne8EvkqBOHXeNIz13gg:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e342ae665325a157c468b9442d769477f0bafbd/crates/native_blockifier/src/py_transaction.rs#L190)):*
> ```XML
>             let compiled_class_hash =
>                 CompiledClassHash(py_attr::<PyFelt>(tx, "compiled_class_hash")?.0);
>             let common_transaction_fields = get_common_transaction_fields(tx)?;
> ```





_Suggestion:_
```XML
common_tx_fields
```


<!-- Sent from Reviewable.io -->

2023-09-12 12:06 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul, @giladchase, @MohammadNassar1, and @yair-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8ESSa9Wi_xPgx-Bch:-Ne8H5RF5zKhRFXjp-mQ:b-l7vygn) (no related file):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please add Gilad as a reviewer.
</blockquote></details>

He was added two days ago (:

___
___
*[`crates/blockifier/src/transaction/transactions.rs` line 189 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne12ygw5olgQ4sobBqJ:-Ne8GrRJDV3NTSs10hMB:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa4ff457325631dbf0b4543c89a21ee91b5b24d8/crates/blockifier/src/transaction/transactions.rs#L189)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Yes.
For now, give `l1_max_amount` a name, so this line is easier to read.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 121 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8EQEz15CzwllyaQaT:-Ne8F_JGDqhPcDxoLPRd:b-fnzzuh) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e342ae665325a157c468b9442d769477f0bafbd/crates/blockifier/src/transaction/transactions.rs#L121)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you explain this annotation?
</blockquote></details>

It means "if `ver` in {0, 1} then..."


<!-- Sent from Reviewable.io -->

2023-09-12 13:26 UTC, elintul approved these changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: all files reviewed, 1 unresolved discussion (waiting on @barak-b-starkware, @giladchase, and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 121 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8EQEz15CzwllyaQaT:-Ne8ZIlm4FQrYSfFvYqr:b-vxjqaa) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e342ae665325a157c468b9442d769477f0bafbd/crates/blockifier/src/transaction/transactions.rs#L121)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

It means "if `ver` in {0, 1} then..."
</blockquote></details>

Hard to read... :smiling_face_with_tear:
If there's still duplicateion, can you add TODOs to fix them? 


<!-- Sent from Reviewable.io -->

2023-09-12 13:55 UTC, giladchase requested changes
> Reviewed 2 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: all files reviewed, 5 unresolved discussions (waiting on @barak-b-starkware, @elintul, and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 121 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8EQEz15CzwllyaQaT:-Ne8cIXbC7diSDT5xVJp:bcub088) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e342ae665325a157c468b9442d769477f0bafbd/crates/blockifier/src/transaction/transactions.rs#L121)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Hard to read... :smiling_face_with_tear:
If there's still duplicateion, can you add TODOs to fix them?
</blockquote></details>

chez chatGPT: 
```rust

let (valid_versions, cairo_version) = match contract_class {
    ContractClass::V0(_) => (vec![0, 1], 0),
    ContractClass::V1(_) => (vec![2, 3], 1),
};

if valid_versions.contains(&ver) {
    Ok(contract_class)
} else {
    Err(TransactionExecutionError::ContractClassVersionMismatch {
        declare_version,
        cairo_version,
    })
}
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 118 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8b5ii-NvEQ3DG0F8s:-Ne8b5ij-zF-rWlBS1Tw:bvxq2k6) ([raw file](https://github.com/starkware-libs/blockifier/blob/125152b51d26f682f8f21f97f73f8f135b497782/crates/blockifier/src/transaction/transactions.rs#L118)):*
> ```XML
>         v if v == TransactionVersion(StarkFelt::from(3_u8)) => 3,
>         _ => 4,
>     };
> ```

Do we want to assert that ver <= 3 here?



_Suggestion:_
```XML
 let ver = usize::try_from(declare_version.0)?;
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 153 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8eDhC4NO7H3Z3I9j3:-Ne8eDhC4NO7H3Z3I9j4:bqnxf90) ([raw file](https://github.com/starkware-libs/blockifier/blob/125152b51d26f682f8f21f97f73f8f135b497782/crates/blockifier/src/transaction/transactions.rs#L153)):*
> ```XML
>             starknet_api::transaction::DeclareTransaction::V0(tx) => {
>                 let contract_class =
>                     verify_contract_class_version(contract_class, declare_version)?;
> ```

You can extract from all branches and define outside of the match



_Code quote:_
```XML
                let contract_class =
                    verify_contract_class_version(contract_class, declare_version)?;
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 159 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8ehNg7RKBNZs_FLTk:-Ne8ehNg7RKBNZs_FLTl:b-mkevyp) ([raw file](https://github.com/starkware-libs/blockifier/blob/125152b51d26f682f8f21f97f73f8f135b497782/crates/blockifier/src/transaction/transactions.rs#L159)):*
> ```XML
>                     contract_class,
>                 })
>             }
> ```

Then you can initialize the `Ok(Self{...})` at the last line of the function, without repeating the initialization in every branch



_Suggestion:_
```XML
        let tx = match declare_tx {
            starknet_api::transaction::DeclareTransaction::V0(tx) => {
                starknet_api::transaction::DeclareTransaction::V0(tx)
            }
```
___
*[`crates/blockifier/src/transaction/transactions.rs` line 202 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8f4wVEiTHHR6SMqHV:-Ne8f4wWDQizVuoCteSp:b-69ldw0) ([raw file](https://github.com/starkware-libs/blockifier/blob/125152b51d26f682f8f21f97f73f8f135b497782/crates/blockifier/src/transaction/transactions.rs#L202)):*
> ```XML
>     pub fn contract_class(&self) -> ContractClass {
>         self.contract_class.clone()
>     }
> ```

I think you can remove these getters if you added the macro?



_Code quote:_
```XML
    implement_inner_tx_getter_calls!((class_hash, ClassHash));

    pub fn tx(&self) -> &starknet_api::transaction::DeclareTransaction {
        &self.tx
    }

    pub fn tx_hash(&self) -> TransactionHash {
        self.tx_hash
    }

    pub fn contract_class(&self) -> ContractClass {
        self.contract_class.clone()
    }
```


<!-- Sent from Reviewable.io -->

2023-09-12 15:34 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @elintul, @giladchase, and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 118 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8b5ii-NvEQ3DG0F8s:-Ne8sDL-1uDuxBoeTp2T:b6lb8qe) ([raw file](https://github.com/starkware-libs/blockifier/blob/125152b51d26f682f8f21f97f73f8f135b497782/crates/blockifier/src/transaction/transactions.rs#L118)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Do we want to assert that ver <= 3 here?
</blockquote></details>

Removed in this PR:
https://reviewable.io/reviews/starkware-libs/blockifier/904
___
*[`crates/blockifier/src/transaction/transactions.rs` line 202 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8f4wVEiTHHR6SMqHV:-Ne8vfGU6He0U3BevrV5:b3ct0de) ([raw file](https://github.com/starkware-libs/blockifier/blob/125152b51d26f682f8f21f97f73f8f135b497782/crates/blockifier/src/transaction/transactions.rs#L202)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I think you can remove these getters if you added the macro?
</blockquote></details>

I'm not sure I know which macro you mean that I added?
___
*[`crates/blockifier/src/transaction/transactions.rs` line 214 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8h8us0khE0l73HaB9:-Ne8yKuA2vbLWVYn1AZO:boydpmh) ([raw file](https://github.com/starkware-libs/blockifier/blob/125152b51d26f682f8f21f97f73f8f135b497782/crates/blockifier/src/transaction/transactions.rs#L214)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

can you use `unwrap_or_default()` here?
Also i think its missing an import for `ResourceBounds`
</blockquote></details>

I can, but then we need to add `impl Default for ResourceBounds` in starknet_api. We want it?
(Even though we have `#[derive(Default)]` it complains that "the trait bound std::default::Default is not satisfied".
___
*[`crates/native_blockifier/src/py_transaction.rs` line 32 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8oWdA-FWDu8XCyiLw:-Ne8zBhh2bQyq-RCheqy:b-26v9mv) ([raw file](https://github.com/starkware-libs/blockifier/blob/125152b51d26f682f8f21f97f73f8f135b497782/crates/native_blockifier/src/py_transaction.rs#L32)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Also for the rest of the additions here.
`pyclass` is for exporting from rust into python, if you just want to import from python into rest, you only need to implement `FromPyObject`.
</blockquote></details>

It doesn't work for enums ("cannot derive FromPyObject for empty structs and variants").
So there is another alternative for enums`PyDataAvailabilityMode` and `PyResource`?


<!-- Sent from Reviewable.io -->

2023-09-12 15:35 UTC, elintul requested changes
> Reviewed 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: all files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware, @giladchase, and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 214 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8h8us0khE0l73HaB9:-Ne91-aa8Fv80IiP926L:b-7xtei2) ([raw file](https://github.com/starkware-libs/blockifier/blob/125152b51d26f682f8f21f97f73f8f135b497782/crates/blockifier/src/transaction/transactions.rs#L214)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I can, but then we need to add `impl Default for ResourceBounds` in starknet_api. We want it?
(Even though we have `#[derive(Default)]` it complains that "the trait bound std::default::Default is not satisfied".
</blockquote></details>

Yeah.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 48 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ndn6_oODmL_J14e0e6G:-Ne90hfK2Wq-jgPXafEW:bgc7vqv) ([raw file](https://github.com/starkware-libs/blockifier/blob/85caa387d3d323012503fe1f21bdf0ee0eacbdfa/crates/native_blockifier/src/py_transaction.rs#L48)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Non-blocking, i rewrote parts of this module to adhere with our current PYO3 coding idioms (the py_attr stuff is legacy).
See `gilad/refactor-resource-pyo3`.
We can discuss these changes once we're passed the upgrade.
</blockquote></details>

:heart: 
___
*[`crates/native_blockifier/src/py_transaction.rs` line 32 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8oWdA-FWDu8XCyiLw:-Ne90wOOEfOCzknpniZg:b-1zaqxk) ([raw file](https://github.com/starkware-libs/blockifier/blob/125152b51d26f682f8f21f97f73f8f135b497782/crates/native_blockifier/src/py_transaction.rs#L32)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

It doesn't work for enums ("cannot derive FromPyObject for empty structs and variants").
So there is another alternative for enums`PyDataAvailabilityMode` and `PyResource`?
</blockquote></details>

Can you use the internal `Resource`?
___
*[`crates/native_blockifier/src/py_transaction.rs` line 132 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne90mW6-LheGTacmDm4:-Ne90mW6-LheGTacmDm5:b9urvod) ([raw file](https://github.com/starkware-libs/blockifier/blob/9202132dadd1eb3406e56126e6bf080f8f6352f9/crates/native_blockifier/src/py_transaction.rs#L132)):*
> ```XML
>         py_attr(tx, "fee_data_availability_mode")?;
>     let py_paymaster_data: Vec<PyFelt> = py_attr(tx, "paymaster_data")?;
>     let paymaster_data: Vec<StarkFelt> = py_paymaster_data.into_iter().map(|felt| felt.0).collect();
> ```

Don't we have a util for that?



_Code quote:_
```XML
    let py_paymaster_data: Vec<PyFelt> = py_attr(tx, "paymaster_data")?;
    let paymaster_data: Vec<StarkFelt> = py_paymaster_data.into_iter().map(|felt| felt.0).collect();
```


<!-- Sent from Reviewable.io -->

2023-09-12 15:37 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: all files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware, @giladchase, and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 208 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8fkU_3pNo9ZTkAn73:-Ne91URz36w-uWlyrqYw:b-21b38e) ([raw file](https://github.com/starkware-libs/blockifier/blob/125152b51d26f682f8f21f97f73f8f135b497782/crates/blockifier/src/transaction/transactions.rs#L208)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Consider using `|` here, if @elintul is OK with this
</blockquote></details>

Do you think it's better now? :smiling_face_with_tear: 


<!-- Sent from Reviewable.io -->

2023-09-12 15:39 UTC, barak-b-starkware commented
*[`crates/blockifier/src/transaction/transactions.rs` line 121 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8EQEz15CzwllyaQaT:-Ne91gQoCHIHxkR6rgZ0:b-fje69b) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e342ae665325a157c468b9442d769477f0bafbd/crates/blockifier/src/transaction/transactions.rs#L121)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

chez chatGPT: 
```rust

let (valid_versions, cairo_version) = match contract_class {
    ContractClass::V0(_) => (vec![0, 1], 0),
    ContractClass::V1(_) => (vec![2, 3], 1),
};

if valid_versions.contains(&ver) {
    Ok(contract_class)
} else {
    Err(TransactionExecutionError::ContractClassVersionMismatch {
        declare_version,
        cairo_version,
    })
}
```
</blockquote></details>

I'll add a TODO in the last PR where you can see the "final result" of this function:
https://reviewable.io/reviews/starkware-libs/blockifier/904


<!-- Sent from Reviewable.io -->

2023-09-12 15:40 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: all files reviewed, 6 unresolved discussions (waiting on @barak-b-starkware, @giladchase, and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 121 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8EQEz15CzwllyaQaT:-Ne92Gt3BFrADEAcrj0N:b32w07) ([raw file](https://github.com/starkware-libs/blockifier/blob/0e342ae665325a157c468b9442d769477f0bafbd/crates/blockifier/src/transaction/transactions.rs#L121)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I'll add a TODO in the last PR where you can see the "final result" of this function:
https://reviewable.io/reviews/starkware-libs/blockifier/904
</blockquote></details>

NP


<!-- Sent from Reviewable.io -->

2023-09-12 15:47 UTC, barak-b-starkware commented
*[`crates/native_blockifier/src/py_transaction.rs` line 132 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne90mW6-LheGTacmDm4:-Ne929Yu0k6mx5-fPTZY:bbuetfn) ([raw file](https://github.com/starkware-libs/blockifier/blob/9202132dadd1eb3406e56126e6bf080f8f6352f9/crates/native_blockifier/src/py_transaction.rs#L132)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Don't we have a util for that?
</blockquote></details>

I copy-pasted it from the signature (quoted, lines 113-114), you want to add util for that? where?



_Code quote:_
```XML
    let py_signature: Vec<PyFelt> = py_attr(tx, "signature")?;
    let signature: Vec<StarkFelt> = py_signature.into_iter().map(|felt| felt.0).collect();
```


<!-- Sent from Reviewable.io -->

2023-09-12 15:48 UTC, barak-b-starkware commented
*[`crates/blockifier/src/transaction/transactions.rs` line 208 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8fkU_3pNo9ZTkAn73:-Ne91z7gBjPqVHZjjxNI:b-8cta62) ([raw file](https://github.com/starkware-libs/blockifier/blob/125152b51d26f682f8f21f97f73f8f135b497782/crates/blockifier/src/transaction/transactions.rs#L208)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Do you think it's better now? :smiling_face_with_tear:
</blockquote></details>

I like it (: 


<!-- Sent from Reviewable.io -->

2023-09-13 04:12 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @elintul, and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 202 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8f4wVEiTHHR6SMqHV:-NeBcmLu5qFhMZhBi0-E:b-4u7ytm) ([raw file](https://github.com/starkware-libs/blockifier/blob/125152b51d26f682f8f21f97f73f8f135b497782/crates/blockifier/src/transaction/transactions.rs#L202)):*
<details><summary><i>Previously, barak-b-starkware wrote…</i></summary><blockquote>

I'm not sure I know which macro you mean that I added?
</blockquote></details>

Oh right you didn't add it, it was just moved, I was talking about `implement_inner_tx_getter_calls`, but not critical for now.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 208 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8fkU_3pNo9ZTkAn73:-NeBd56V2ZDZw0BfiKZg:b5mel83) ([raw file](https://github.com/starkware-libs/blockifier/blob/125152b51d26f682f8f21f97f73f8f135b497782/crates/blockifier/src/transaction/transactions.rs#L208)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

The repeating line of capturing the field isn't so elegant, but perhaps it's idiomatic.
</blockquote></details>

Mmm i didn't realize previously that you couldn't keep using `tx`, if you have to unpack all the way up to max_fee then I agree with Elin that it is unreadable, your previous implementation was better.
___
*[`crates/blockifier/src/transaction/transactions.rs` line 214 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8h8us0khE0l73HaB9:-NeBeikxARtdfjr1l5_6:b-isjq06) ([raw file](https://github.com/starkware-libs/blockifier/blob/125152b51d26f682f8f21f97f73f8f135b497782/crates/blockifier/src/transaction/transactions.rs#L214)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Yeah.
</blockquote></details>

Note the full error message, it says that there is no `Default::default` on for `&ResourceBounds`, which is what you usually get from collections, and it is also true that `derive(Default)` implemented the trait only for `ResourceBounds`, and not for the different type `ResourceBounds`.

To get around that, you need to deference before you call `unwrap_or_default()`, which can be done when chaining calls using `cloned().unwrap_or_default()` or `copied().unwrap_or_default()`.
The latter is better, should it be implemented for the type (because it "promises" a very copy of the value).
In our case, since `ResourceBounds` implements `Copy`, you can indeed use the latter.
___
*[`crates/native_blockifier/src/py_transaction.rs` line 32 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8oWdA-FWDu8XCyiLw:-NeBgPIz0TReAIEYvFTu:bgep3qa) ([raw file](https://github.com/starkware-libs/blockifier/blob/125152b51d26f682f8f21f97f73f8f135b497782/crates/native_blockifier/src/py_transaction.rs#L32)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you use the internal `Resource`?
</blockquote></details>

I didn't know about the enum thing :scream: 
Looks like indeed pyclasses are the way to go for enums in Pyo3 :/

BTW, technically, you could have implemented FromPyObject by hand (only the `derive` isn't supported), which is trivial, but in relevant github issues on this they hint that they want ppl to use pyclass for these. 
___
*[`crates/native_blockifier/src/py_transaction.rs` line 132 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne90mW6-LheGTacmDm4:-NeBhto41QLYBnUG-HSE:b-c4lsqb) ([raw file](https://github.com/starkware-libs/blockifier/blob/9202132dadd1eb3406e56126e6bf080f8f6352f9/crates/native_blockifier/src/py_transaction.rs#L132)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

No, I thought we  already had one.
</blockquote></details>

Ya there was a py_sequnce or something like that, for creating `Vec<PyFelt>`, but Nir deleted it since it is unnecessary.
This is because py_attr (and in particular, the `extract` call inside it) knows how to make collections of `FromPyObject`able types.


<!-- Sent from Reviewable.io -->

2023-09-13 06:42 UTC, elintul reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: all files reviewed, 4 unresolved discussions (waiting on @barak-b-starkware, @giladchase, and @MohammadNassar1)

___
*[`crates/blockifier/src/transaction/transactions.rs` line 214 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne8h8us0khE0l73HaB9:-NeCFiC97EU1VvlKFqpl:b-j9tzok) ([raw file](https://github.com/starkware-libs/blockifier/blob/125152b51d26f682f8f21f97f73f8f135b497782/crates/blockifier/src/transaction/transactions.rs#L214)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Note the full error message, it says that there is no `Default::default` on for `&ResourceBounds`, which is what you usually get from collections, and it is also true that `derive(Default)` implemented the trait only for `ResourceBounds`, and not for the different type `ResourceBounds`.

To get around that, you need to deference before you call `unwrap_or_default()`, which can be done when chaining calls using `cloned().unwrap_or_default()` or `copied().unwrap_or_default()`.
The latter is better, should it be implemented for the type (because it "promises" a very copy of the value).
In our case, since `ResourceBounds` implements `Copy`, you can indeed use the latter.
</blockquote></details>

Can you elaborate on the derive part of the first paragraph? 


<!-- Sent from Reviewable.io -->

2023-09-13 07:07 UTC, barak-b-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul and @MohammadNassar1)

___
*[`crates/native_blockifier/src/py_transaction.rs` line 132 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/866#-Ne90mW6-LheGTacmDm4:-NeCM9dv9Dw37SixS5sK:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9202132dadd1eb3406e56126e6bf080f8f6352f9/crates/native_blockifier/src/py_transaction.rs#L132)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Ya there was a py_sequnce or something like that, for creating `Vec<PyFelt>`, but Nir deleted it since it is unnecessary.
This is because py_attr (and in particular, the `extract` call inside it) knows how to make collections of `FromPyObject`able types.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-13 07:43 UTC, elintul approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2023-09-13 13:25 UTC, elintul approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/866#-:-NeDhuoh-SEdYO8O2PhP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2023-09-14 08:10 UTC, barak-b-starkware commented
Merged in the following PRs: [1](https://github.com/starkware-libs/blockifier/pull/918), [2](https://github.com/starkware-libs/blockifier/pull/919), [3](https://github.com/starkware-libs/blockifier/pull/920).

2023-09-14 08:10 UTC, closed without merging