Restrict the use of get_block_hash syscall in during validate.
starkware-libs/blockifier pull request #922
Opened 2023-09-14 15:23 UTC by ArniStarkware

2023-09-18 07:28 UTC, ArniStarkware commented
Next PRs: Do the same for validate_declare and validate_deploy_account.




<!-- Sent from Reviewable.io -->

2023-09-18 09:23 UTC, ArniStarkware commented
We have two tests here:
1. Tests that the syscall `get_block_hash` fails as expected when in validate mode.
2. Tests that during a transaction's execution - the `__validate__`entry point is created with `CallEntryPoint` with the proper execution mode.




<!-- Sent from Reviewable.io -->

2023-09-18 10:10 UTC, elintul requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: 0 of 10 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Nebl734CuwgbPwUQPY2:-Nebl734CuwgbPwUQPY3:bldnr2v) (no related file):*
Let's either look at the syscall counter after validate, as we do [here](https://github.com/starkware-libs/blockifier/blob/72087fe729a950f284189fa74304824e7c1c99ee/crates/blockifier/src/transaction/account_transaction.rs#L255).
Or move all validate-related checks into the syscall handler. Currently, it's not aligned.

___
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 371 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Nebl4aL2wLr3_ogC0UJ:-Nebl4aL2wLr3_ogC0UK:b7swz3n) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef60ba2068bfa2ac28f54972fbe73d99ea450a07/crates/blockifier/src/execution/syscalls/hint_processor.rs#L371)):*
> ```XML
>                     error_data: vec![invalid_syscall_error],
>                 }
>             }
> ```

Where is `get_block_hash` restricted?



_Code quote:_
```XML
            ExecutionMode::Validate => {
                let invalid_syscall_error = StarkFelt::try_from(EXECUTION_MODE_ERROR)
                    .map_err(SyscallExecutionError::from)?;
                SyscallResponseWrapper::Failure {
                    gas_counter: remaining_gas,
                    error_data: vec![invalid_syscall_error],
                }
            }
```


<!-- Sent from Reviewable.io -->

2023-09-18 10:47 UTC, ArniStarkware commented
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's either look at the syscall counter after validate, as we do [here](https://github.com/starkware-libs/blockifier/blob/72087fe729a950f284189fa74304824e7c1c99ee/crates/blockifier/src/transaction/account_transaction.rs#L255).
Or move all validate-related checks into the syscall handler. Currently, it's not aligned.
</blockquote></details>

I like the second option. Do we want to do this urgently - for 0.12.3?




<!-- Sent from Reviewable.io -->

2023-09-18 10:49 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: 0 of 10 files reviewed, 4 unresolved discussions (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 371 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Nebl4aL2wLr3_ogC0UJ:-NebsrmC3c93eJJvtZCX:b-li771a) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef60ba2068bfa2ac28f54972fbe73d99ea450a07/crates/blockifier/src/execution/syscalls/hint_processor.rs#L371)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Where is `get_block_hash` restricted?
</blockquote></details>

On the creation of the syscall handler. Any syscall handler whose execution mode is `Validate`, will restrict this syscall.
No longer relevant here. It was moved to the execution of `get_block_hash` (in `crates/blockifier/src/execution/syscalls/mod.rs`).


<!-- Sent from Reviewable.io -->

2023-09-18 10:58 UTC, ArniStarkware commented
+reviewer:@giladchase 





<!-- Sent from Reviewable.io -->

2023-09-18 13:46 UTC, ArniStarkware commented
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 616 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/922#-NecXPHy6byNB5gSFyOm:-NecXPHy6byNB5gSFyOn:byh34ur) ([raw file](https://github.com/starkware-libs/blockifier/blob/016df46ec21623dfd5a03521446acdf983f2aad8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L616)):*
> ```XML
>         call_type: CallType::Delegate,
>         initial_gas: *remaining_gas,
>         ..Default::default()
> ```

Maybe should be



_Suggestion:_
```XML
        execution_mode: syscall_handler.execution_mode
```


<!-- Sent from Reviewable.io -->

2023-09-18 13:56 UTC, ArniStarkware commented
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 175 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Nec_3HlCSyCnsNd9jsv:-Nec_3HlCSyCnsNd9jsw:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/016df46ec21623dfd5a03521446acdf983f2aad8/crates/blockifier/src/execution/syscalls/mod.rs#L175)):*
> ```XML
>         call_type: CallType::Call,
>         initial_gas: *remaining_gas,
>         ..Default::default()
> ```





_Suggestion:_
```XML
execution_mode: syscall_handler.execution_mode
```


<!-- Sent from Reviewable.io -->

2023-09-18 14:06 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: 0 of 10 files reviewed, 6 unresolved discussions (waiting on @elintul, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 616 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/922#-NecXPHy6byNB5gSFyOm:-Necb5-F7WOtVbX7RHDQ:b-a2ujfl) ([raw file](https://github.com/starkware-libs/blockifier/blob/016df46ec21623dfd5a03521446acdf983f2aad8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L616)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Maybe should be
</blockquote></details>

Changed.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 175 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Nec_3HlCSyCnsNd9jsv:-NecbKyFCtc7qjK-j7KX:b-a2ujfl) ([raw file](https://github.com/starkware-libs/blockifier/blob/016df46ec21623dfd5a03521446acdf983f2aad8/crates/blockifier/src/execution/syscalls/mod.rs#L175)):*
> ```XML
>         call_type: CallType::Call,
>         initial_gas: *remaining_gas,
>         ..Default::default()
> ```

Changed.


<!-- Sent from Reviewable.io -->

2023-09-18 15:04 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: 0 of 10 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @giladchase, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Nebl734CuwgbPwUQPY2:-NecoOd2AydLxsoRWn4R:b-eil7yh) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

I like the second option. Do we want to do this urgently - for 0.12.3?
</blockquote></details>

I want to understand how to locate all the post-validate checks in the same place.

___


<!-- Sent from Reviewable.io -->

2023-09-18 15:07 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: 0 of 10 files reviewed, 7 unresolved discussions (waiting on @ArniStarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/execution/entry_point.rs` line 59 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/922#-NecpCnL7EAR9-Y99rQC:-NecpCnL7EAR9-Y99rQD:b918bvl) ([raw file](https://github.com/starkware-libs/blockifier/blob/d18c056a42814995865809e78e32b7c3d1be03a0/crates/blockifier/src/execution/entry_point.rs#L59)):*
> ```XML
>     // We can assume that the initial gas is less than 2^64.
>     pub initial_gas: u64,
>     pub execution_mode: ExecutionMode,
> ```

I think it's better to put it in the execution context.


<!-- Sent from Reviewable.io -->

2023-09-19 07:53 UTC, ArniStarkware commented
*[`crates/blockifier/src/execution/entry_point.rs` line 59 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/922#-NecpCnL7EAR9-Y99rQC:-NegQHZ02xKMD2tGfPQL:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/d18c056a42814995865809e78e32b7c3d1be03a0/crates/blockifier/src/execution/entry_point.rs#L59)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I think it's better to put it in the execution context.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-19 07:56 UTC, ArniStarkware commented
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I want to understand how to locate all the post-validate checks in the same place.
</blockquote></details>

IIUC, this is not a part of the plan. The plan is that the behavior (syscall X not running on validate) will be a property of the syscall - and not a property of the validate. @liorgold2 - Do I understand the design correctly?




<!-- Sent from Reviewable.io -->

2023-09-19 08:11 UTC, Yoni-Starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: 0 of 14 files reviewed, 5 unresolved discussions (waiting on @elintul, @giladchase, and @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Nebl734CuwgbPwUQPY2:-NegTSGT2J9FCO5EBOdr:bwics1q) (no related file):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

IIUC, this is not a part of the plan. The plan is that the behavior (syscall X not running on validate) will be a property of the syscall - and not a property of the validate. @liorgold2 - Do I understand the design correctly?
</blockquote></details>

I see one additional check - `verify_no_calls_to_other_contracts`.

We want to close all DDOS holes. A new hole requires the syscall handler to know (live, not post-run) 
that it runs in validate context (to create a different `execution_info`). And that's a good reason to pass the post-checks to it, for consistency.

___


<!-- Sent from Reviewable.io -->

2023-09-19 08:15 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: 0 of 14 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, and @liorgold2)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 62 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/922#-NegV1yQ-wTAwXcGR9wr:-NegV1yQ-wTAwXcGR9ws:bfoievf) ([raw file](https://github.com/starkware-libs/blockifier/blob/032de0e9c98e326455efa3079acc99822135444e/crates/blockifier/src/execution/syscalls/hint_processor.rs#L62)):*
> ```XML
>     /// Validate execution mode.
>     Validate,
> }
> ```

We currently need a boolean, `is_validate_context` or something.
@elintul, what do you think? Do you see a future use in this enum?



_Code quote:_
```XML
/// Transaction execution mode.
#[derive(Debug, Clone, Default, Eq, PartialEq, Copy)]
pub enum ExecutionMode {
    /// Normal execution mode.
    #[default]
    Default,
    /// Validate execution mode.
    Validate,
}
```


<!-- Sent from Reviewable.io -->

2023-09-19 08:20 UTC, ArniStarkware commented
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 62 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/922#-NegV1yQ-wTAwXcGR9wr:-NegWMbQ-FAuxo7Wvmp0:bk5lrn7) ([raw file](https://github.com/starkware-libs/blockifier/blob/032de0e9c98e326455efa3079acc99822135444e/crates/blockifier/src/execution/syscalls/hint_processor.rs#L62)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

We currently need a boolean, `is_validate_context` or something.
@elintul, what do you think? Do you see a future use in this enum?
</blockquote></details>

@liorgold2 - said he wanted this to be an enum - for future use.
I have split this PR in two - as it was becoming too big. See #926.


<!-- Sent from Reviewable.io -->

2023-09-19 08:20 UTC, ArniStarkware reviewed
Split this PR in two. See #926.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922#-:-NegWhcpCebYzdLiygxP:b-963m2r)* status: 0 of 14 files reviewed, 6 unresolved discussions (waiting on @elintul, @giladchase, @liorgold2, and @Yoni-Starkware)



<!-- Sent from Reviewable.io -->

2023-09-19 08:53 UTC, Yoni-Starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: 0 of 14 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, and @liorgold2)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 343 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Neg_FrNBubmCI5Ozuu2:-Neg_FrO9GnveQsmpx5p:bfisjep) ([raw file](https://github.com/starkware-libs/blockifier/blob/ab3fee7d9ccddd4a7195371b854bd907c5db0f3d/crates/blockifier/src/execution/syscalls/mod.rs#L343)):*
> ```XML
>     _remaining_gas: &mut u64,
> ) -> SyscallResult<GetBlockHashResponse> {
>     if syscall_handler.execution_mode == ExecutionMode::Validate {
> ```

We have to stop the execution immediately in this case and not revert the syscall.

Otherwise, users could call this syscall and ignore the result - so the `validate` might pass.
It would require enforcing this flow by the OS.

@EvyatarO WDYT? do we want to keep these logics out of the OS as much as possible?



_Code quote:_
```XML
    if syscall_handler.execution_mode == ExecutionMode::Validate {
```


<!-- Sent from Reviewable.io -->

2023-09-19 09:27 UTC, liorgold2 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: 0 of 14 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 62 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/922#-NegV1yQ-wTAwXcGR9wr:-NegkyFlBjxw6MS-U5N3:bkcz7ry) ([raw file](https://github.com/starkware-libs/blockifier/blob/032de0e9c98e326455efa3079acc99822135444e/crates/blockifier/src/execution/syscalls/hint_processor.rs#L62)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

@liorgold2 - said he wanted this to be an enum - for future use.
I have split this PR in two - as it was becoming too big. See #926.
</blockquote></details>

In general, it's not bad to use enums instead of bools in rust


<!-- Sent from Reviewable.io -->

2023-09-19 09:45 UTC, liorgold2 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: 0 of 14 files reviewed, 6 unresolved discussions (waiting on @ArniStarkware, @elintul, @giladchase, and @Yoni-Starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Nebl734CuwgbPwUQPY2:-NegoqKf6oESzfeeUUEs:b-hs9sbb) (no related file):*
I think the second option (moving all to be handled during the handler) is better. It stops the execution immediately when it breaks the requirements.

> IIUC, this is not a part of the plan. The plan is that the behavior (syscall X not running on validate) will be a property of the syscall - and not a property of the validate.

I don't understand what you mean by this question.

___


<!-- Sent from Reviewable.io -->

2023-09-19 09:59 UTC, ArniStarkware commented
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

I think the second option (moving all to be handled during the handler) is better. It stops the execution immediately when it breaks the requirements.

> IIUC, this is not a part of the plan. The plan is that the behavior (syscall X not running on validate) will be a property of the syscall - and not a property of the validate.

I don't understand what you mean by this question.
</blockquote></details>

Answering Elin's question. There will be no easy way to locate all the post-validate checks in the same place. But this is true on another level. All the current post-validate checks will now be handled mid-validate, by the syscall handler.




<!-- Sent from Reviewable.io -->

2023-09-19 14:02 UTC, ArniStarkware commented
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 343 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Nehk0Xq6pcrAwCzzl5k:-Nehk0XrBrfP52PSfzIk:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/b5bba2529172092c5457e9126fb60279e9170ee9/crates/blockifier/src/execution/syscalls/mod.rs#L343)):*
> ```XML
>     _remaining_gas: &mut u64,
> ) -> SyscallResult<GetBlockHashResponse> {
>     if syscall_handler.execution_mode == ExecutionMode::Validate {
> ```





_Suggestion:_
```XML
 if syscall_handler.context.execution_mode == ExecutionMode::Validate {
```


<!-- Sent from Reviewable.io -->

2023-09-20 07:01 UTC, EvyatarO reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: 0 of 14 files reviewed, 7 unresolved discussions (waiting on @elintul, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 343 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Neg_FrNBubmCI5Ozuu2:-NelNPSK36sI-5Me-ABa:bod1kh2) ([raw file](https://github.com/starkware-libs/blockifier/blob/ab3fee7d9ccddd4a7195371b854bd907c5db0f3d/crates/blockifier/src/execution/syscalls/mod.rs#L343)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

We have to stop the execution immediately in this case and not revert the syscall.

Otherwise, users could call this syscall and ignore the result - so the `validate` might pass.
It would require enforcing this flow by the OS.

@EvyatarO WDYT? do we want to keep these logics out of the OS as much as possible?
</blockquote></details>

Yes, we prefer to kill it in the gateway w/o changes in the OS


<!-- Sent from Reviewable.io -->

2023-09-21 13:35 UTC, ArniStarkware commented
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 343 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Neg_FrNBubmCI5Ozuu2:-Nerw2cI-y-FN2HK76aH:b-p84ln4) ([raw file](https://github.com/starkware-libs/blockifier/blob/ab3fee7d9ccddd4a7195371b854bd907c5db0f3d/crates/blockifier/src/execution/syscalls/mod.rs#L343)):*
<details><summary><i>Previously, EvyatarO (Evyatar) wrote…</i></summary><blockquote>

Yes, we prefer to kill it in the gateway w/o changes in the OS
</blockquote></details>

The function now returns a raises an `InvalidSyscallInExecutionMode` error, which means the transaction should be `rejected`. 


<!-- Sent from Reviewable.io -->

2023-09-21 13:54 UTC, ArniStarkware commented
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 164 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Nes-PepBh9cS-_aqfi2:-Nes-PepBh9cS-_aqfi3:bunzo9a) ([raw file](https://github.com/starkware-libs/blockifier/blob/993240ac36338c15114a9d0b31a7efc046ec5a93/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L164)):*
> ```XML
> 
>     assert_matches!(error, EntryPointExecutionError::VirtualMachineExecutionErrorWithTrace{ trace, source: _ }
>         if trace.contains("Invalid syscall in execution mode error: GetBlockHash in Validate."));
> ```

It might be better to move this test near/ into `test_validate_accounts_tx`. Upside for keeping here - readable and compact. Downside - we added a new test util for it: `validate_directly` WDYT @Yoni-Starkware ?
In the meantime - is this the right error message to raise? Is this the right way to unpack it in the test? WDYT @elintul ?



_Code quote:_
```XML
    // Negative flow. Execution mode is Validate.
    let entry_point_call = CallEntryPoint {
        entry_point_selector: selector_from_name("test_get_block_hash"),
        calldata,
        ..trivial_external_entry_point()
    };

    let error = entry_point_call.validate_directly(&mut state).unwrap_err();

    assert_matches!(error, EntryPointExecutionError::VirtualMachineExecutionErrorWithTrace{ trace, source: _ }
        if trace.contains("Invalid syscall in execution mode error: GetBlockHash in Validate."));
```


<!-- Sent from Reviewable.io -->

2023-09-28 06:43 UTC, Yoni-Starkware requested changes
> Reviewed 5 of 14 files at r5, 3 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: 8 of 15 files reviewed, 8 unresolved discussions (waiting on @ArniStarkware, @elintul, and @giladchase)

___
*[`crates/blockifier/src/test_utils.rs` line 347 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/922#-NfPWSiA0dN27uXkDIXm:-NfPWSiA0dN27uXkDIXn:bca6gr4) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa9283a2e38d074cc600b39a817487d1e41cb92c/crates/blockifier/src/test_utils.rs#L347)):*
> ```XML
>     }
>     /// Executes the call directly, without account context in validate mode.
>     pub fn validate_directly(self, state: &mut dyn State) -> EntryPointExecutionResult<CallInfo> {
> ```

A bit less confusing



_Suggestion:_
```XML
    /// Executes the call directly in validate mode, without account context.
    pub fn execute_directly_in_validate(self, state: &mut dyn State) -> EntryPointExecutionResult<CallInfo> {
```
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 346 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/922#-NfPV6wA7bfaOba-Puut:-NfPV6wB48hgQs0tGjZ6:b-q77sx8) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa9283a2e38d074cc600b39a817487d1e41cb92c/crates/blockifier/src/execution/syscalls/mod.rs#L346)):*
> ```XML
>     if syscall_handler.context.execution_mode == ExecutionMode::Validate {
>         return Err(SyscallExecutionError::InvalidSyscallInExecutionMode {
>             syscall_name: "GetBlockHash".to_owned(),
> ```

I think that you used `call_contract` in another PR. Choose one style and be consistent.



_Code quote:_
```XML
"GetBlockHash"
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 159 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/922#-NfPVwTV3JZNxJGtniiI:-NfPVwTW4VgbRuoR6Gep:b-r2qtx6) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa9283a2e38d074cc600b39a817487d1e41cb92c/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L159)):*
> ```XML
>         calldata,
>         ..trivial_external_entry_point()
>     };
> ```

Why do you need to redefine this struct?



_Code quote:_
```XML
    let entry_point_call = CallEntryPoint {
        entry_point_selector: selector_from_name("test_get_block_hash"),
        calldata,
        ..trivial_external_entry_point()
    };
```


<!-- Sent from Reviewable.io -->

2023-09-28 07:11 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: 8 of 15 files reviewed, 8 unresolved discussions (waiting on @elintul, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/test_utils.rs` line 347 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/922#-NfPWSiA0dN27uXkDIXm:-NfPaHOq-49WhbpsyY4V:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa9283a2e38d074cc600b39a817487d1e41cb92c/crates/blockifier/src/test_utils.rs#L347)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

A bit less confusing
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 346 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/922#-NfPV6wA7bfaOba-Puut:-NfPaYbNEDxMfOqSMp98:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa9283a2e38d074cc600b39a817487d1e41cb92c/crates/blockifier/src/execution/syscalls/mod.rs#L346)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

I think that you used `call_contract` in another PR. Choose one style and be consistent.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 159 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/922#-NfPVwTV3JZNxJGtniiI:-NfPbuUm-FT5XEmPyVGr:bdziq71) ([raw file](https://github.com/starkware-libs/blockifier/blob/fa9283a2e38d074cc600b39a817487d1e41cb92c/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L159)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Why do you need to redefine this struct?
</blockquote></details>

Done. (Now cloning correctly).


<!-- Sent from Reviewable.io -->

2023-09-28 07:15 UTC, ArniStarkware commented
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

Next PRs: Do the same for validate_declare and validate_deploy_account.
</blockquote></details>

See: #940. 




<!-- Sent from Reviewable.io -->

2023-09-28 07:32 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 4 files at r9, 2 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: 11 of 15 files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)



<!-- Sent from Reviewable.io -->

2023-09-28 08:50 UTC, elintul requested changes
> Reviewed 2 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: 13 of 15 files reviewed, 4 unresolved discussions (waiting on @ArniStarkware and @giladchase)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 371 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Nebl4aL2wLr3_ogC0UJ:-NfPymlSBkm1VjKyIYm3:b-kyz08m) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef60ba2068bfa2ac28f54972fbe73d99ea450a07/crates/blockifier/src/execution/syscalls/hint_processor.rs#L371)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

On the creation of the syscall handler. Any syscall handler whose execution mode is `Validate`, will restrict this syscall.
No longer relevant here. It was moved to the execution of `get_block_hash` (in `crates/blockifier/src/execution/syscalls/mod.rs`).
</blockquote></details>

I can't see it, please add a link to the code.


<!-- Sent from Reviewable.io -->

2023-09-28 09:02 UTC, ArniStarkware commented
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 371 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Nebl4aL2wLr3_ogC0UJ:-NfQ0Abh3JJPfs0zJx9l:bxpyw2a) ([raw file](https://github.com/starkware-libs/blockifier/blob/ef60ba2068bfa2ac28f54972fbe73d99ea450a07/crates/blockifier/src/execution/syscalls/hint_processor.rs#L371)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I can't see it, please add a link to the code.
</blockquote></details>

See: https://github.com/starkware-libs/blockifier/blob/9b8a40c780ff266b282398af658b80e355643b1a/crates/blockifier/src/execution/syscalls/mod.rs#L344-L349


<!-- Sent from Reviewable.io -->

2023-10-02 12:22 UTC, Yoni-Starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 9 files at r8, 1 of 2 files at r10, 1 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922#-:-NfkKk1I1Bff76hNfzYQ:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul and @giladchase)



<!-- Sent from Reviewable.io -->

2023-10-02 13:41 UTC, elintul approved these changes
> Reviewed 4 of 14 files at r5, 3 of 9 files at r8, 1 of 2 files at r10, 3 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: all files reviewed, 3 unresolved discussions (waiting on @ArniStarkware, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 337 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/922#-NfQBIGw4ADiiNh1bqfZ:-NfQBIGw4ADiiNh1bqf_:br2qjb4) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b8a40c780ff266b282398af658b80e355643b1a/crates/blockifier/src/execution/syscalls/mod.rs#L337)):*
> ```XML
> /// [constants::STORED_BLOCK_HASH_BUFFER] blocks before the current block. Otherwise, returns an
> /// error.
> /// This syscall is not availiable in validate mode.
> ```

Remove, you're repeating code.



_Code quote:_
```XML
/// This syscall is not availiable in validate mode.
```
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 164 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Nes-PepBh9cS-_aqfi2:-NfkbgWEBETvNsOe8uMM:b-uhwwo1) ([raw file](https://github.com/starkware-libs/blockifier/blob/993240ac36338c15114a9d0b31a7efc046ec5a93/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L164)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

It might be better to move this test near/ into `test_validate_accounts_tx`. Upside for keeping here - readable and compact. Downside - we added a new test util for it: `validate_directly` WDYT @Yoni-Starkware ?
In the meantime - is this the right error message to raise? Is this the right way to unpack it in the test? WDYT @elintul ?
</blockquote></details>

Can we extract the error variant? ChatGPT might know.
I think it's okay to leave it in `get_block_hash` test.


<!-- Sent from Reviewable.io -->

2023-10-03 07:25 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: 13 of 15 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/mod.rs` line 337 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/922#-NfQBIGw4ADiiNh1bqfZ:-Nfkxvka2ov1yv72EFxw:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/9b8a40c780ff266b282398af658b80e355643b1a/crates/blockifier/src/execution/syscalls/mod.rs#L337)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Remove, you're repeating code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-03 08:53 UTC, elintul submitted a review, later dismissed
> Reviewed 1 of 14 files at r5, 1 of 4 files at r9, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: all files reviewed, 2 unresolved discussions (waiting on @ArniStarkware and @giladchase)

___
*[`crates/blockifier/src/execution/common_hints.rs` line 28 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/922#-NfojK3T0gT-uvHbay06:-NfojK3T0gT-uvHbay07:b-m00kv2) ([raw file](https://github.com/starkware-libs/blockifier/blob/628c5262ccdd1a9cdbb484cc84e47ba13a8a104a/crates/blockifier/src/execution/common_hints.rs#L28)):*
> ```XML
> 
> /// Transaction execution mode.
> #[derive(Debug, Clone, Default, Eq, PartialEq, Copy, Display)]
> ```

Please alphabetize. 
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 164 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Nes-PepBh9cS-_aqfi2:-NfojCY3-aPgHLB80hmF:b-2uuo5y) ([raw file](https://github.com/starkware-libs/blockifier/blob/993240ac36338c15114a9d0b31a7efc046ec5a93/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L164)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we extract the error variant? ChatGPT might know.
I think it's okay to leave it in `get_block_hash` test.
</blockquote></details>

Please ask Gilad to briefly review the test assertion. 


<!-- Sent from Reviewable.io -->

2023-10-03 10:01 UTC, ArniStarkware commented
*[`crates/blockifier/src/execution/common_hints.rs` line 28 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/922#-NfojK3T0gT-uvHbay06:-Nfoz0EG5hP5aKj8c0ua:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/628c5262ccdd1a9cdbb484cc84e47ba13a8a104a/crates/blockifier/src/execution/common_hints.rs#L28)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please alphabetize.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-03 10:30 UTC, elintul submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922#-:-Nfp4mZDB4S_hrIGuocM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-10-05 06:19 UTC, Yoni-Starkware reviewed
> Reviewed 1 of 2 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-10-05 07:58 UTC, elintul submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-10-05 13:45 UTC, elintul approved these changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: all files reviewed, 1 unresolved discussion (waiting on @giladchase)



<!-- Sent from Reviewable.io -->

2023-10-05 14:13 UTC, ArniStarkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: 10 of 15 files reviewed, 1 unresolved discussion (waiting on @elintul, @giladchase, and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 164 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Nes-PepBh9cS-_aqfi2:-Ng-AYu6-dHLhuFguvb_:brotlq9) ([raw file](https://github.com/starkware-libs/blockifier/blob/993240ac36338c15114a9d0b31a7efc046ec5a93/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L164)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Please ask Gilad to briefly review the test assertion.
</blockquote></details>

@giladchase Suggested this test util (and a few other things).


<!-- Sent from Reviewable.io -->

2023-10-08 08:51 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922)* status: 10 of 15 files reviewed, all discussions resolved (waiting on @elintul and @Yoni-Starkware)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 164 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Nes-PepBh9cS-_aqfi2:-NgDTv0018qk8HbyO7cg:bxeeyak) ([raw file](https://github.com/starkware-libs/blockifier/blob/993240ac36338c15114a9d0b31a7efc046ec5a93/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L164)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

@giladchase Suggested this test util (and a few other things).
</blockquote></details>

Will the test-utils be useful outside of this module? or will it only be reused in the syscall_tests.rs module?


<!-- Sent from Reviewable.io -->

2023-10-08 09:01 UTC, ArniStarkware commented
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 164 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Nes-PepBh9cS-_aqfi2:-NgDW2VUAUhnV1rGMCwT:b-qxcq7g) ([raw file](https://github.com/starkware-libs/blockifier/blob/993240ac36338c15114a9d0b31a7efc046ec5a93/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L164)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Will the test-utils be useful outside of this module? or will it only be reused in the syscall_tests.rs module?
</blockquote></details>

It will also be useful in `transaction/transactions_test.rs` See: #940.


<!-- Sent from Reviewable.io -->

2023-10-08 10:00 UTC, giladchase approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 5 of 14 files at r5, 5 of 9 files at r8, 5 of 5 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/922#-:-NgDinoXEObCP_9v1GQQ:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArniStarkware)

___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 164 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/922#-Nes-PepBh9cS-_aqfi2:-NgDic_M7hyXLE6wXfdh:b593w57) ([raw file](https://github.com/starkware-libs/blockifier/blob/993240ac36338c15114a9d0b31a7efc046ec5a93/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L164)):*
<details><summary><i>Previously, ArniStarkware (Arnon Hod) wrote…</i></summary><blockquote>

It will also be useful in `transaction/transactions_test.rs` See: #940.
</blockquote></details>

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 


<!-- Sent from Reviewable.io -->

2023-10-09 06:40 UTC, merged