Gilad/py state reader add to validation
starkware-libs/blockifier pull request #980
Opened 2023-10-10 13:23 UTC by giladchase

2023-10-11 12:30 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/980)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @elintul, and @giladchase)

___
*[`crates/native_blockifier/src/py_validator.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/980#-NgThT4OBQR940vnaVEP:-NgThT4OBQR940vnaVEQ:bn4pvxj) ([raw file](https://github.com/starkware-libs/blockifier/blob/56af2b9229f2f2d5bb02014b264c3f6bef97c054/crates/native_blockifier/src/py_validator.rs#L30)):*
> ```XML
>         let tx_executor = None;
> 
>         log::debug!("Initialized Validator.");
> ```

what does this do...? nothing is happening between the logs



_Code quote:_
```XML
        log::debug!("Initializing Validator...");
        let tx_executor = None;

        log::debug!("Initialized Validator.");
```
___
*[`crates/native_blockifier/src/py_validator.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/980#-NgThflOBdEcDnR37mlW:-NgThflOBdEcDnR37mlX:b-7zi8ni) ([raw file](https://github.com/starkware-libs/blockifier/blob/56af2b9229f2f2d5bb02014b264c3f6bef97c054/crates/native_blockifier/src/py_validator.rs#L57)):*
> ```XML
>             self.global_contract_cache.clone(),
>         )?;
>         self.tx_executor = Some(tx_executor);
> ```

WDYT?



_Suggestion:_
```XML
        self.tx_executor = Some(TransactionExecutor::new(
            reader,
            &self.general_config,
            next_block_info,
            self.max_recursion_depth,
            self.global_contract_cache.clone(),
        )?);
```


<!-- Sent from Reviewable.io -->

2023-10-11 12:45 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/980)* status: all files reviewed, 2 unresolved discussions (waiting on @dafnamatsry, @dorimedini-starkware, and @elintul)

___
*[`crates/native_blockifier/src/py_validator.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/980#-NgThT4OBQR940vnaVEP:-NgTka3n5Adn216yvCF-:b-kf4l13) ([raw file](https://github.com/starkware-libs/blockifier/blob/56af2b9229f2f2d5bb02014b264c3f6bef97c054/crates/native_blockifier/src/py_validator.rs#L30)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what does this do...? nothing is happening between the logs
</blockquote></details>

Ya good point, this is what happens when you plagiarize other modules without thinking it all through :sweat_smile: 
___
*[`crates/native_blockifier/src/py_validator.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/980#-NgThflOBdEcDnR37mlW:-NgTlDuE4ugB7x9TsUsS:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/56af2b9229f2f2d5bb02014b264c3f6bef97c054/crates/native_blockifier/src/py_validator.rs#L57)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYT?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-11 13:00 UTC, dorimedini-starkware requested changes
> Reviewed 8 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/980)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry, @elintul, and @giladchase)

___
*[`crates/native_blockifier/src/state_readers/py_state_reader.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/980#-NgToTCwBIHyk7KClOSy:-NgToTCwBIHyk7KClOSz:bsgpvl2) ([raw file](https://github.com/starkware-libs/blockifier/blob/a6e42f1bdc4e612f672460deaad7d30fb5e21d6f/crates/native_blockifier/src/state_readers/py_state_reader.rs#L40)):*
> ```XML
>     ) -> StateResult<StarkFelt> {
>         Python::with_gil(|py| -> PyResult<PyFelt> {
>             let args = (ON_CHAIN_STORAGE_DOMAIN, PyFelt::from(contract_address), PyFelt::from(key));
> ```

always...?
isn't this reader supposed to work with multiple DA modes?



_Code quote:_
```XML
ON_CHAIN_STORAGE_DOMAIN
```


<!-- Sent from Reviewable.io -->

2023-10-11 15:36 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/980)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry, @dorimedini-starkware, and @elintul)

___
*[`crates/native_blockifier/src/state_readers/py_state_reader.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/980#-NgToTCwBIHyk7KClOSy:-NgUNNWX9VlLSku1_dZD:b-alh2li) ([raw file](https://github.com/starkware-libs/blockifier/blob/a6e42f1bdc4e612f672460deaad7d30fb5e21d6f/crates/native_blockifier/src/state_readers/py_state_reader.rs#L40)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

always...?
isn't this reader supposed to work with multiple DA modes?
</blockquote></details>

I'll have to check, i recall Dafna telling me that it is always


<!-- Sent from Reviewable.io -->

2023-10-15 10:05 UTC, elintul approved these changes
> Reviewed 2 of 9 files at r2, 1 of 1 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/980)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2023-10-15 10:05 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/980)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2023-10-15 11:34 UTC, giladchase reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/980)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @dorimedini-starkware)

___
*[`crates/native_blockifier/src/state_readers/py_state_reader.rs` line 40 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/980#-NgToTCwBIHyk7KClOSy:-Ngn6KZ63NYz-BtnAzmj:b-4bb0rr) ([raw file](https://github.com/starkware-libs/blockifier/blob/a6e42f1bdc4e612f672460deaad7d30fb5e21d6f/crates/native_blockifier/src/state_readers/py_state_reader.rs#L40)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

I'll have to check, i recall Dafna telling me that it is always
</blockquote></details>

Talked to Elin.
For now always, when volition comes into play it'll change, but that's months from now.


<!-- Sent from Reviewable.io -->

2023-10-15 11:38 UTC, elintul approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/980)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry and @dorimedini-starkware)



<!-- Sent from Reviewable.io -->

2023-10-15 13:33 UTC, dorimedini-starkware reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/980)* status: all files reviewed, 1 unresolved discussion (waiting on @dafnamatsry)



<!-- Sent from Reviewable.io -->

2023-10-15 13:33 UTC, dorimedini-starkware submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/980#-:-NgnXl-tAJG8I8Th1BMr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)



<!-- Sent from Reviewable.io -->

2023-10-16 08:35 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/980#-:-Ngrc0cP446qTHkZ44xk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dafnamatsry)



<!-- Sent from Reviewable.io -->

2023-10-16 08:41 UTC, merged