Update TxInfo syscall
starkware-libs/blockifier pull request #984
Opened 2023-10-15 17:05 UTC by MohammadNassar1

2023-10-16 10:36 UTC, elintul requested changes
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @MohammadNassar1)

___
*[`crates/blockifier/src/test_utils.rs` line 378 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngrx0sS6xupUx5gd9Z9:-Ngrx0sTCIXLycfsRTwG:b-ydserg) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/test_utils.rs#L378)):*
> ```XML
>             &AccountTransactionContext::Deprecated(DeprecatedAccountTransactionContext::default()),
>         );
>         self.execute(state, &mut ExecutionResources::default(), &mut context)
> ```

Perhaps call `execute_directly_with_custom_context`?



_Code quote:_
```XML
self.execute(state, &mut ExecutionResources::default(), &mut context)
```
___
*[`crates/blockifier/src/test_utils.rs` line 381 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngrx5KgAWdWCThFDQFo:-Ngrx5KgAWdWCThFDQFp:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/test_utils.rs#L381)):*
> ```XML
>     }
> 
>     pub fn execute_directly_with_custom_context(
> ```





_Suggestion:_
```XML
execute_directly_given_account_context
```
___
*[`crates/blockifier/src/test_utils.rs` line 384 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NgrxCePDDdziaHN00Uu:-NgrxCePDDdziaHN00Uv:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/test_utils.rs#L384)):*
> ```XML
>         self,
>         state: &mut dyn State,
>         current_context: CurrentAccountTransactionContext,
> ```





_Suggestion:_
```XML
account_tx_context: CurrentAccountTransactionContext,
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 448 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs2X5Z0hsuATkWJin8:-Ngs2X5Z0hsuATkWJin9:baoh8qc) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L448)):*
> ```XML
>         Ok(resource_bounds_segment_start_ptr)
>     }
> ```

Let's have a util of allocating a segment for an array of felts instead.


<!-- Sent from Reviewable.io -->

2023-10-16 10:40 UTC, elintul requested changes
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 494 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs2zSx00AGnlTS98eo:-Ngs2zSx00AGnlTS98ep:bgnu5y4) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L494)):*
> ```XML
>         let tx_signature_length = account_tx_context.signature().0.len();
>         let tx_signature_end_ptr = (*tx_signature_start_ptr + tx_signature_length)?;
> ```

WDYT of defining `max_fee` using `if-let`, then write the common prefix for both versions once, then another `if` for `Current` variant where you add the suffix of V3?
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 215 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs3Fgd-ToItI_NWfw0:-Ngs3Fgd-ToItI_NWfw1:b7viyvu) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L215)):*
> ```XML
>         ..trivial_external_entry_point()
>     };
> ```

Let's move to another PR (you can open it, so we don't forget), since it will take some time for a new compiler release.
___
*[`crates/blockifier/src/execution/syscalls/syscalls_test.rs` line 215 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs3Ppy0FhjTPpKEV1E:-Ngs3Ppy0FhjTPpKEV1F:b5yb4yr) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/syscalls_test.rs#L215)):*
> ```XML
>         ..trivial_external_entry_point()
>     };
> ```

Let's add checks for previous version: all V3 fields are zeroed, while for V3: `max_fee=0`.


<!-- Sent from Reviewable.io -->

2023-10-16 10:44 UTC, dorimedini-starkware requested changes
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 19 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/test_utils.rs` line 378 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NgryNOB17zOSzXBIEJt:-NgryNOB17zOSzXBIEJu:b82b612) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/test_utils.rs#L378)):*
> ```XML
>             &AccountTransactionContext::Deprecated(DeprecatedAccountTransactionContext::default()),
>         );
>         self.execute(state, &mut ExecutionResources::default(), &mut context)
> ```

code reuse



_Suggestion:_
```XML
        self.execute_directly_with_custom_context(state, DeprecatedAccountTransactionContext::default())
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 427 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngrya2y76DkdoNNRBFr:-Ngrya2z0aO-CJ_LHLC2:bqj7i1u) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L427)):*
> ```XML
>                 let resource_int = match resource {
>                     Resource::L1Gas => 1,
>                     Resource::L2Gas => 2,
> ```

on the OS it's zero and one, IIRC



_Suggestion:_
```XML
                    Resource::L1Gas => 0,
                    Resource::L2Gas => 1,
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 439 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngryu3s4TUyRaTmmOX8:-Ngryu3s4TUyRaTmmOX9:banaauy) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L439)):*
> ```XML
>                 let max_amount = MaybeRelocatable::from(Felt252::from(max_amount));
> 
>                 vec![resource, max_price_per_unit, max_amount]
> ```

shorter, less dup.
maybe need `.collect::<Vec<MaybeRelocatable>>()`, but it may work without explicit typing



_Suggestion:_
```XML
                [resource_int, resource_bounds.max_price_per_unit, resource_bounds.max_amount]
                    .into_iter()
                    .map(|value| MaybeRelocatable::from(Felt252::from(value)))
                    .collect()
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 448 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NgrzwOODzo1Gd1Iqm8y:-NgrzwOODzo1Gd1Iqm8z:bcqd3un) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L448)):*
> ```XML
>         Ok(resource_bounds_segment_start_ptr)
>     }
> ```

why not define a private method
```
fn allocate_data_segment(&mut self, vm: &mut VirtualMachine, data: Vec<StarkFelt>) -> SyscallResult<Relocatable>
```
?

you duplicate the same logic ~4 times:
1. paymaster and account deployment data allocation are similar
2. resource bounds allocation also includes converting to MaybeRelocatable - you can do it in a single helper function
3. empty array pointer can also use this utility function 
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 453 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs-OEi6qbVLFnXFRto:-Ngs-OEi6qbVLFnXFRtp:btn6pfw) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L453)):*
> ```XML
>         vm: &mut VirtualMachine,
>     ) -> SyscallResult<Relocatable> {
>         let paymaster_data = &self.context.account_tx_context.signature().0;
> ```

signature?



_Code quote:_
```XML
signature().
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 466 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NgrzsdoCEotE1lYGTWJ:-Ngrzsdp3DO7F41VPIo1:btn6pfw) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L466)):*
> ```XML
>         vm: &mut VirtualMachine,
>     ) -> SyscallResult<Relocatable> {
>         let account_deployment_data = &self.context.account_tx_context.signature().0;
> ```

signature?



_Code quote:_
```XML
.signature().0
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 502 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs-x2nDJL4SbCRS4AP:-Ngs-x2nDJL4SbCRS4AQ:bi48kzn) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L502)):*
> ```XML
>                 let tx_resource_bounds_length = current_ctx.resource_bounds.0.len();
>                 let tx_resource_bounds_end_ptr =
>                     (*tx_resource_bounds_start_ptr + tx_resource_bounds_length)?;
> ```

does this work...? no need to multiply the offset by the size of a single resource bounds struct, like in the OS?



_Code quote:_
```XML
(*tx_resource_bounds_start_ptr + tx_resource_bounds_length)?
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 507 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs05Z48x9GS94u6kx7:-Ngs05Z48x9GS94u6kx8:b-l8l7r9) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L507)):*
> ```XML
>                 let tx_paymaster_data_length = current_ctx.paymaster_data.0.len();
>                 let tx_paymaster_data_end_ptr =
>                     (*tx_paymaster_data_start_ptr + tx_paymaster_data_length)?;
> ```

same question



_Code quote:_
```XML
(*tx_paymaster_data_start_ptr + tx_paymaster_data_length)?
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 513 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs07Ec4BPqpMMKRRx_:-Ngs07Ec4BPqpMMKRRxa:b-l8l7r9) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L513)):*
> ```XML
>                 let tx_account_deployment_data_length = current_ctx.account_deployment_data.0.len();
>                 let tx_account_deployment_data_end_ptr =
>                     (*tx_account_deployment_data_start_ptr + tx_account_deployment_data_length)?;
> ```

same question



_Code quote:_
```XML
(*tx_account_deployment_data_start_ptr + tx_account_deployment_data_length)?;
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 534 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs0YfqDzdo6cIy6wlX:-Ngs0Yfr92bsTNYK4IFU:bn6si8q) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L534)):*
> ```XML
>                     tx_paymaster_data_end_ptr.into(),
>                     tx_account_deployment_data_start_ptr.into(),
>                     tx_account_deployment_data_end_ptr.into(),
> ```

reorder to match OS (move paymaster pointers up):
```
// The tip.
tip: felt,
// If specified, the paymaster should pay for the execution of the tx.
// The data includes the address of the paymaster sponsoring the transaction, followed by extra
// data to send to the paymaster.
paymaster_data_start: felt*,
paymaster_data_end: felt*,
// The data availability mode for the nonce.
nonce_data_availabilty_mode: felt,
// The data availability mode for the account balance from which fee will be taken.
fee_data_availabilty_mode: felt,
// If nonempty, will contain the required data for deploying and initializing an account
// contract: i [...]

2023-10-16 14:54 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: 0 of 3 files reviewed, 17 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/test_utils.rs` line 378 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NgryNOB17zOSzXBIEJt:-NgsOJtm3TOpKCcREtz2:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/test_utils.rs#L378)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

code reuse
</blockquote></details>

Done.
___
*[`crates/blockifier/src/test_utils.rs` line 378 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngrx0sS6xupUx5gd9Z9:-NgsOKbnBM8KSERQMGLH:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/test_utils.rs#L378)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Perhaps call `execute_directly_with_custom_context`?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 427 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngrya2y76DkdoNNRBFr:-NgsP-y2EZTvwv0Ykou0:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L427)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

on the OS it's zero and one, IIRC
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 439 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngryu3s4TUyRaTmmOX8:-NgsYMsrDL7UA5oVLYoT:bcl8qku) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L439)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

shorter, less dup.
maybe need `.collect::<Vec<MaybeRelocatable>>()`, but it may work without explicit typing
</blockquote></details>

It needs explicit typing.
Done
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 448 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NgrzwOODzo1Gd1Iqm8y:-NgsfGRz0Y-4mimzaC9K:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L448)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not define a private method
```
fn allocate_data_segment(&mut self, vm: &mut VirtualMachine, data: Vec<StarkFelt>) -> SyscallResult<Relocatable>
```
?

you duplicate the same logic ~4 times:
1. paymaster and account deployment data allocation are similar
2. resource bounds allocation also includes converting to MaybeRelocatable - you can do it in a single helper function
3. empty array pointer can also use this utility function
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 448 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs2X5Z0hsuATkWJin8:-NgsfHdt5_VO-L7qkB9j:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L448)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's have a util of allocating a segment for an array of felts instead.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 453 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs-OEi6qbVLFnXFRto:-NgsfId97258bIq4axtk:b-cv48yh) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L453)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

signature?
</blockquote></details>

A typo, fixed by using the suggested private method.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 466 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NgrzsdoCEotE1lYGTWJ:-NgsfXUE4huxXSeOMTV9:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L466)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

signature?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 494 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs2zSx00AGnlTS98eo:-NgsjwPyCt3mrhFtoLkl:bvrszti) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L494)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

WDYT of defining `max_fee` using `if-let`, then write the common prefix for both versions once, then another `if` for `Current` variant where you add the suffix of V3?
</blockquote></details>

Sounds good.
Updated!
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 507 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs05Z48x9GS94u6kx7:-Ngsvbl_9O1diGx-qm3a:b4r6i2a) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L507)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

same question
</blockquote></details>

I noticed that for the signature, we didn't multiply by the size.
And both are with the same type: `Vec<StarkFelt>`
WDYT?
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 534 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs0YfqDzdo6cIy6wlX:-Ngsqrq8BYmW2-sij_Ex:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L534)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

reorder to match OS (move paymaster pointers up):
```
// The tip.
tip: felt,
// If specified, the paymaster should pay for the execution of the tx.
// The data includes the address of the paymaster sponsoring the transaction, followed by extra
// data to send to the paymaster.
paymaster_data_start: felt*,
paymaster_data_end: felt*,
// The data availability mode for the nonce.
nonce_data_availabilty_mode: felt,
// The data availability mode for the account balance from which fee will be taken.
fee_data_availabilty_mode: felt,
// If nonempty, will contain the required data for deploying and initializing an account
// contract: its class hash, address salt and constructor calldata.
account_deployment_data_start: felt*,
account_deployment_data_end: felt*,
```
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 539 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs12G4D-xc2mO_X-be:-NgstBmv06ThdOejll-F:b813q0) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L539)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. Cast the empty array ptr to Relocatable *once*, drop all the `into()`s
2. I'm pretty sure `Felt252::ZERO` is defined (and better than `::from(0)`)
3. Define the zero felt once and reuse (preferably without `into()`s)
</blockquote></details>

I used  [...]

2023-10-16 14:59 UTC, elintul requested changes
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: 2 of 3 files reviewed, 17 unresolved discussions (waiting on @dorimedini-starkware and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 448 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs2X5Z0hsuATkWJin8:-NgszqaN8GYO9ndTK2T0:b-wulndy) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L448)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you use it instead of all the locations we allocate arrays of felts? If it gets too big - a separate PR.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 455 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NgszQ1l2L4JpsMNi-bY:-NgszQ1l2L4JpsMNi-bZ:b-8bchxf) ([raw file](https://github.com/starkware-libs/blockifier/blob/b1221e3c07ef840580ce2ec4349522ed76ed9572/crates/blockifier/src/execution/syscalls/hint_processor.rs#L455)):*
> ```XML
>         let data_segment_start_ptr = self.read_only_segments.allocate(vm, &data)?;
> 
>         Ok(data_segment_start_ptr)
> ```

Let's return start and end?



_Code quote:_
```XML
Ok(data_segment_start_ptr)
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 459 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngsz8c4BVvGRtaRAVWt:-Ngsz8c4BVvGRtaRAVWu:b-5pu8kk) ([raw file](https://github.com/starkware-libs/blockifier/blob/b1221e3c07ef840580ce2ec4349522ed76ed9572/crates/blockifier/src/execution/syscalls/hint_processor.rs#L459)):*
> ```XML
> 
>     fn allocate_tx_info_segment(&mut self, vm: &mut VirtualMachine) -> SyscallResult<Relocatable> {
>         let account_tx_context = self.context.account_tx_context.clone();
> ```

Try to arrange differently to prevent `clone`ing?



_Code quote:_
```XML
let account_tx_context = self.context.account_tx_context.clone();
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 460 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NgszFnVCo2Vby7PBxyB:-NgszFnVCo2Vby7PBxyC:b-wes0ar) ([raw file](https://github.com/starkware-libs/blockifier/blob/b1221e3c07ef840580ce2ec4349522ed76ed9572/crates/blockifier/src/execution/syscalls/hint_processor.rs#L460)):*
> ```XML
>     fn allocate_tx_info_segment(&mut self, vm: &mut VirtualMachine) -> SyscallResult<Relocatable> {
>         let account_tx_context = self.context.account_tx_context.clone();
>         let tx_signature_start_ptr = &self.allocate_tx_signature_segment(vm)?;
> ```

I think we can lose this function and use `allocate_data_segment` directly.



_Code quote:_
```XML
allocate_tx_signature_segment
```


<!-- Sent from Reviewable.io -->

2023-10-16 15:29 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 12 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 507 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs05Z48x9GS94u6kx7:-Ngt4mNzAQdJTEU5hBoI:b-rrvp4z) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L507)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I noticed that for the signature, we didn't multiply by the size.
And both are with the same type: `Vec<StarkFelt>`
WDYT?
</blockquote></details>

each element of a signature is 1 felt, so it can work, but if `tx_resource_bounds_length` is `2`, then we need 6 felts, right?
Do you have access to some constant representing the size (in felts) of a flattened ResourceBounds instance?
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 384 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt3iv_7CWiZiUFjtsW:-Ngt3iv_7CWiZiUFjtsX:b-7k24j5) ([raw file](https://github.com/starkware-libs/blockifier/blob/628e5de210f800ac8cdf1fda4a77867354ceb3b8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L384)):*
> ```XML
>             self.read_only_segments.allocate(vm, &additional_info)?;
> 
>         Ok(execution_info_segment_start_ptr)
> ```

reuse



_Suggestion:_
```XML
        self.allocate_data_segment(vm, vec![
            block_info_ptr,
            tx_info_ptr,
            stark_felt_to_felt(*self.caller_address().0.key()),
            stark_felt_to_felt(*self.storage_address().0.key()),
            stark_felt_to_felt(self.entry_point_selector().0),
        ])
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 399 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt3z9U72a9G5iwBhOi:-Ngt3z9U72a9G5iwBhOj:b-7k24j5) ([raw file](https://github.com/starkware-libs/blockifier/blob/628e5de210f800ac8cdf1fda4a77867354ceb3b8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L399)):*
> ```XML
>         let block_info_segment_start_ptr = self.read_only_segments.allocate(vm, &block_info)?;
> 
>         Ok(block_info_segment_start_ptr)
> ```

reuse



_Suggestion:_
```XML
        self.allocate_data_segment(vm, vec![
            block_context.block_number.0,
            block_context.block_timestamp.0,
            *block_context.sequencer_address.0.key(),
        ])
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 411 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt4QVHE4NU2EN4ki8h:-Ngt4QVHE4NU2EN4ki8i:b-7k24j5) ([raw file](https://github.com/starkware-libs/blockifier/blob/628e5de210f800ac8cdf1fda4a77867354ceb3b8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L411)):*
> ```XML
>         let signature_segment_start_ptr = self.read_only_segments.allocate(vm, &signature)?;
> 
>         Ok(signature_segment_start_ptr)
> ```

reuse



_Suggestion:_
```XML
        self.allocate_data_segment(vm, &self.context.account_tx_context.signature().0)
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 444 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt2nSo64_JUqenJ2XN:-Ngt2nSo64_JUqenJ2XO:biwiul2) ([raw file](https://github.com/starkware-libs/blockifier/blob/628e5de210f800ac8cdf1fda4a77867354ceb3b8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L444)):*
> ```XML
>             self.read_only_segments.allocate(vm, resource_bounds)?;
> 
>         Ok(resource_bounds_segment_start_ptr)
> ```

(re)use `allocate_data_segment` please



_Suggestion:_
```XML
        let resource_bounds = &context
            .resource_bounds
            .0
            .iter()
            .flat_map(|(resource, resource_bounds)| {
                // Convert the key (resource) to an int.
                let resource = match resource {
                    Resource::L1Gas => StarkFelt::ZERO,
                    Resource::L2Gas => StarkFelt::ONE,
                };

                vec![
                    resource,
                    StarkFelt::from(resource_bounds.max_price_per_unit),
                    StarkFelt::from(resource_bounds.max_amount),
                ]
            })
            .collect();
        
        self.allocate_data_segment(vm, resource_bounds)
```


<!-- Sent from Reviewable.io -->

2023-10-16 15:30 UTC, elintul requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 14 unresolved discussions (waiting on @dorimedini-starkware and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 507 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs05Z48x9GS94u6kx7:-Ngt4D3TCLq-PElnQMbE:b-obfem7) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L507)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I noticed that for the signature, we didn't multiply by the size.
And both are with the same type: `Vec<StarkFelt>`
WDYT?
</blockquote></details>

When it's a single felt, yes. Pointer arithmetic is done in felt size.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 467 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt3Ar8DK_rt-9D8Hqi:-Ngt3Ar91d54sAB8m-z4:br9ae2q) ([raw file](https://github.com/starkware-libs/blockifier/blob/628e5de210f800ac8cdf1fda4a77867354ceb3b8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L467)):*
> ```XML
>             stark_felt_to_felt(self.context.account_tx_context.version().0).into(),
>             stark_felt_to_felt(*self.context.account_tx_context.sender_address().0.key()).into(),
>             Felt252::from((self.context.account_tx_context).max_fee().0).into(),
> ```

This should be `0` for `CurrentAccountTransactionContext`; define `max_fee` separately.



_Code quote:_
```XML
Felt252::from((self.context.account_tx_context).max_fee().0).into(),
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 475 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt50St-JDJwTpBQewM:-Ngt50St-JDJwTpBQewN:b-8brxaw) ([raw file](https://github.com/starkware-libs/blockifier/blob/628e5de210f800ac8cdf1fda4a77867354ceb3b8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L475)):*
> ```XML
>         ];
> 
>         match account_tx_context {
> ```

Consider defining a `TransactionInfo` struct, in order not to repeat the order.
Perhaps it can have a c-tor from `BlockContext` and `AccountTransactionContext`.


<!-- Sent from Reviewable.io -->

2023-10-16 15:34 UTC, dorimedini-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 14 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 507 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs05Z48x9GS94u6kx7:-Ngt6vMMCQZAYKjGn2Ow:b-i7orlu) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L507)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

When it's a single felt, yes. Pointer arithmetic is done in felt size.
</blockquote></details>

so do we or do we not need to multiply by 3 explicitly..?


<!-- Sent from Reviewable.io -->

2023-10-16 15:37 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: 2 of 3 files reviewed, 14 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 507 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs05Z48x9GS94u6kx7:-Ngt7JlI7UkWo8Ter5WY:brwd6j6) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L507)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

so do we or do we not need to multiply by 3 explicitly..?
</blockquote></details>

I think only for `resource_bound` we need to multiply by three explicitly.
The code was updated accordingly.


<!-- Sent from Reviewable.io -->

2023-10-16 15:38 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 16 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 483 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt7bvA7-qlD-1IFUa6:-Ngt7bvA7-qlD-1IFUa7:b-u41n14) ([raw file](https://github.com/starkware-libs/blockifier/blob/fdf0b5b548e48a38d1167d6968cdbae203189add/crates/blockifier/src/execution/syscalls/hint_processor.rs#L483)):*
> ```XML
>                 let tx_resource_bounds_end_ptr =
>                     // Each resource_bound contains 3 felts.
>                     (*tx_resource_bounds_start_ptr + (3 * tx_resource_bounds_length))?;
> ```

no magic numbers please - define `pub const RESOURCE_BOUNDS_ELEMENT_SIZE = 3` somewhere and use it here



_Code quote:_
```XML
                    // Each resource_bound contains 3 felts.
                    (*tx_resource_bounds_start_ptr + (3 * tx_resource_bounds_length))?;
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 489 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt7PPuExaAj0WWz097:-Ngt7PPuExaAj0WWz098:b-r7aooc) ([raw file](https://github.com/starkware-libs/blockifier/blob/fdf0b5b548e48a38d1167d6968cdbae203189add/crates/blockifier/src/execution/syscalls/hint_processor.rs#L489)):*
> ```XML
>                 let tx_paymaster_data_length = current_ctx.paymaster_data.0.len();
>                 let tx_paymaster_data_end_ptr =
>                     (*tx_paymaster_data_start_ptr + tx_paymaster_data_length)?;
> ```

paymaster data is a flat list of felts, right? unlike resource bounds?
would feel better if you multiply by some `PAYMASTER_DATA_ELEMENT_SIZE` constant (equal to `1`)



_Code quote:_
```XML
tx_paymaster_data_length
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 495 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt7k9V6_8cZoMC3Rva:-Ngt7k9V6_8cZoMC3Rvb:b-um633k) ([raw file](https://github.com/starkware-libs/blockifier/blob/fdf0b5b548e48a38d1167d6968cdbae203189add/crates/blockifier/src/execution/syscalls/hint_processor.rs#L495)):*
> ```XML
>                 let tx_account_deployment_data_length = current_ctx.account_deployment_data.0.len();
>                 let tx_account_deployment_data_end_ptr =
>                     (*tx_account_deployment_data_start_ptr + tx_account_deployment_data_length)?;
> ```

ditto (define `ACCOUNT_DEPLOYMENT_DATA_ELEMENT_SIZE = 1`)



_Code quote:_
```XML
tx_account_deployment_data_length
```


<!-- Sent from Reviewable.io -->

2023-10-16 15:39 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 14 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 502 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs-x2nDJL4SbCRS4AP:-Ngt7mChDWJ8mgbFjuIg:b-bw8e14) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L502)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does this work...? no need to multiply the offset by the size of a single resource bounds struct, like in the OS?
</blockquote></details>

Updated.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 513 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs07Ec4BPqpMMKRRx_:-Ngt7nlJ4rnX2eSYJBFw:b-23vrmw) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L513)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

same question
</blockquote></details>

No need to multiply by element size, since pointer advancement in Cairo is done in felt size.


<!-- Sent from Reviewable.io -->

2023-10-16 15:45 UTC, dorimedini-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 14 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 513 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs07Ec4BPqpMMKRRx_:-Ngt9Ilw2n9xkC3C-Q97:b-dtnma2) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L513)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

No need to multiply by element size, since pointer advancement in Cairo is done in felt size.
</blockquote></details>

... because the individual element size in this case is 1 felt, right?
unblocking here, blocking in another comment...


<!-- Sent from Reviewable.io -->

2023-10-17 07:35 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: 2 of 3 files reviewed, 14 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 448 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs2X5Z0hsuATkWJin8:-NgtCg_2-9C0PRr9KVAG:b-80tlqx) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L448)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can you use it instead of all the locations we allocate arrays of felts? If it gets too big - a separate PR.
</blockquote></details>

Sure!
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 513 at r1](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngs07Ec4BPqpMMKRRx_:-NgtBXQEBFV3z7b2MFaI:btqqu5l) ([raw file](https://github.com/starkware-libs/blockifier/blob/4e227419bb928bd19145a933cf5942e8a6949550/crates/blockifier/src/execution/syscalls/hint_processor.rs#L513)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

... because the individual element size in this case is 1 felt, right?
unblocking here, blocking in another comment...
</blockquote></details>

Correct.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 455 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NgszQ1l2L4JpsMNi-bY:-NgwJ23dASKGrmX2psHI:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b1221e3c07ef840580ce2ec4349522ed76ed9572/crates/blockifier/src/execution/syscalls/hint_processor.rs#L455)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's return start and end?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 459 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngsz8c4BVvGRtaRAVWt:-NgwR8Vw0hlZr4hMNOiL:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b1221e3c07ef840580ce2ec4349522ed76ed9572/crates/blockifier/src/execution/syscalls/hint_processor.rs#L459)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Try to arrange differently to prevent `clone`ing?
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 460 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NgszFnVCo2Vby7PBxyB:-NgwR9C-3o2RJGLn9YkA:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/b1221e3c07ef840580ce2ec4349522ed76ed9572/crates/blockifier/src/execution/syscalls/hint_processor.rs#L460)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I think we can lose this function and use `allocate_data_segment` directly.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 384 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt3iv_7CWiZiUFjtsW:-NgtCa6v75hWKKY69ree:b-l6b5lo) ([raw file](https://github.com/starkware-libs/blockifier/blob/628e5de210f800ac8cdf1fda4a77867354ceb3b8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L384)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

reuse
</blockquote></details>

Will do all the reuse in separate PR.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 399 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt3z9U72a9G5iwBhOi:-NgwYful6yLPH9Lsecc8:b-l6b5lo) ([raw file](https://github.com/starkware-libs/blockifier/blob/628e5de210f800ac8cdf1fda4a77867354ceb3b8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L399)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

reuse
</blockquote></details>

Will do all the reuse in separate PR.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 411 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt4QVHE4NU2EN4ki8h:-NgwYgaj1qQnwkykBsHN:b-l6b5lo) ([raw file](https://github.com/starkware-libs/blockifier/blob/628e5de210f800ac8cdf1fda4a77867354ceb3b8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L411)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

reuse
</blockquote></details>

Will do all the reuse in separate PR.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 444 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt2nSo64_JUqenJ2XN:-NgwYi09Bd9ykqKURcAf:b-l6b5lo) ([raw file](https://github.com/starkware-libs/blockifier/blob/628e5de210f800ac8cdf1fda4a77867354ceb3b8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L444)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

(re)use `allocate_data_segment` please
</blockquote></details>

Will do all the reuse in separate PR.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 467 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt3Ar8DK_rt-9D8Hqi:-NgwSn27DKpXDeHGSqJd:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/628e5de210f800ac8cdf1fda4a77867354ceb3b8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L467)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

This should be `0` for `CurrentAccountTransactionContext`; define `max_fee` separately.
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 483 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt7bvA7-qlD-1IFUa6:-NgwTIFFCOGe7VGcHVUU:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/fdf0b5b548e48a38d1167d6968cdbae203189add/crates/blockifier/src/execution/syscalls/hint_processor.rs#L483)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no magic numbers please - define `pub const RESOURCE_BOUNDS_ELEMENT_SIZE = 3` somewhere and use it here
</blockquote></details>

Done.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 489 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt7PPuExaAj0WWz097:-NgwXfL8APOByBR-V7p-:b1z08ky) ([raw file](https://github.com/starkware-libs/blockifier/blob/fdf0b5b548e48a38d1167d6968cdbae203189add/crates/blockifier/src/execution/syscalls/hint_processor.rs#L489)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

paymaster data is a flat list of felts, right? unlike resource bounds?
would feel better if you multiply by some `PAYMASTER_DATA_ELEMENT_SIZE` constant (equal to `1`)
</blockquote></details>

I moved the calculation of the `end_ptr` to the `allocate_data_segment` method, and the input data is a vector of `StarkFelt`
is it still relevant?
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 495 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt7k9V6_8cZoMC3Rva:-NgwYcCh36e73JDrgx07:b-f712kn) ([raw file](https://github.com/starkware-libs/blockifier/blob/fdf0b5b548e48a38d1167d6968cdbae203189add/crates/blockifier/src/execution/syscalls/hint_processor.rs#L495)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ditto (define `ACCOUNT_DEPLOYMENT_DATA_ELEMENT_SIZE = 1`)
</blockquote></details>

I moved the calculation of the `end_ptr` to the `allocate_data_segment` method, and the input data is a vector of `StarkFelt`


<!-- Sent from Reviewable.io -->

2023-10-17 07:53 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 12 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 384 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt3iv_7CWiZiUFjtsW:-Ngwb4dbBdxtx2OUUsAz:b-memo2t) ([raw file](https://github.com/starkware-libs/blockifier/blob/628e5de210f800ac8cdf1fda4a77867354ceb3b8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L384)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Will do all the reuse in separate PR.
</blockquote></details>

ok, can you mark with TODOs or paste a link to the PR...? So we don't have a temporary state with no reminders
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 489 at r4](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt7PPuExaAj0WWz097:-NgwbmL1DVu_IwkDCqMd:br6rrro) ([raw file](https://github.com/starkware-libs/blockifier/blob/fdf0b5b548e48a38d1167d6968cdbae203189add/crates/blockifier/src/execution/syscalls/hint_processor.rs#L489)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I moved the calculation of the `end_ptr` to the `allocate_data_segment` method, and the input data is a vector of `StarkFelt`
is it still relevant?
</blockquote></details>

Nope :)
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 477 at r5](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NgwbbdHB2UdczoYt-Qa:-NgwbbdHB2UdczoYt-Qb:b-z283qf) ([raw file](https://github.com/starkware-libs/blockifier/blob/9f8c8d7495c4c88dfbc065110971a373b88042d1/crates/blockifier/src/execution/syscalls/hint_processor.rs#L477)):*
> ```XML
>                 let tx_resource_bounds_length = current_ctx.resource_bounds.0.len();
>                 let tx_resource_bounds_end_ptr = (*tx_resource_bounds_start_ptr
>                     + (RESOURCE_BOUNDS_ELEMENT_SIZE * tx_resource_bounds_length))?;
> ```

will change soon I guess, now that you return the end pointers from the segment allocation util :)
The util takes the total size into account, in units of `felt`, so there will be no need for this multiplier



_Code quote:_
```XML
                let tx_resource_bounds_start_ptr =
                    &self.allocate_tx_resource_bounds_segment(vm, &current_ctx)?;
                let tx_resource_bounds_length = current_ctx.resource_bounds.0.len();
                let tx_resource_bounds_end_ptr = (*tx_resource_bounds_start_ptr
                    + (RESOURCE_BOUNDS_ELEMENT_SIZE * tx_resource_bounds_length))?;
```


<!-- Sent from Reviewable.io -->

2023-10-17 08:14 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: 2 of 3 files reviewed, 11 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 384 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt3iv_7CWiZiUFjtsW:-NgwddOHBVBfl9PS5O3Z:b-896fix) ([raw file](https://github.com/starkware-libs/blockifier/blob/628e5de210f800ac8cdf1fda4a77867354ceb3b8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L384)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ok, can you mark with TODOs or paste a link to the PR...? So we don't have a temporary state with no reminders
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-17 08:15 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 10 unresolved discussions (waiting on @elintul and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2023-10-17 08:16 UTC, dorimedini-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984#-:-NgwhD9b2-sWpXj_3bjD:bnfp4nl)* status: all files reviewed, 10 unresolved discussions (waiting on @elintul and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2023-10-17 09:06 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 10 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 399 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt3z9U72a9G5iwBhOi:-NgwsahrCh_x4ERL9OYr:b-3u6u9j) ([raw file](https://github.com/starkware-libs/blockifier/blob/628e5de210f800ac8cdf1fda4a77867354ceb3b8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L399)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Will do all the reuse in separate PR.
</blockquote></details>

I've implemented it [here](https://github.com/starkware-libs/blockifier/compare/mohammad/Update_txInfo_syscall...mohammad/Refactor_allocate_data_segment?expand=1).
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 411 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt4QVHE4NU2EN4ki8h:-Ngwomqr9aTFyeP3xJzN:bgjb1a3) ([raw file](https://github.com/starkware-libs/blockifier/blob/628e5de210f800ac8cdf1fda4a77867354ceb3b8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L411)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Will do all the reuse in separate PR.
</blockquote></details>

This function was deleted, and replaced by `allocate_data_segment`.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 444 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt2nSo64_JUqenJ2XN:-NgwsjYfAUhYN1q1iNQA:b-3u6u9j) ([raw file](https://github.com/starkware-libs/blockifier/blob/628e5de210f800ac8cdf1fda4a77867354ceb3b8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L444)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Will do all the reuse in separate PR.
</blockquote></details>

I've implemented it [here](https://github.com/starkware-libs/blockifier/compare/mohammad/Update_txInfo_syscall...mohammad/Refactor_allocate_data_segment?expand=1).


<!-- Sent from Reviewable.io -->

2023-10-17 09:13 UTC, dorimedini-starkware submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 10 unresolved discussions (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2023-10-17 09:14 UTC, elintul reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 11 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 109 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngwu0fF3ED1UJC7vsAx:-Ngwu0fF3ED1UJC7vsAy:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b63451364d4ffb5152cbb7f3725f22bd4d952bb/crates/blockifier/src/execution/syscalls/hint_processor.rs#L109)):*
> ```XML
>     "0x00000000000000000000000000000000496e76616c696420617267756d656e74";
> // Each resource_bound contains 3 felts.
> pub const RESOURCE_BOUNDS_ELEMENT_SIZE: usize = 3;
> ```





_Suggestion:_
```XML
// Each resource bound contains three felts; see struct `Resource`.
pub const RESOURCE_BOUNDS_ELEMENT_SIZE: usize = 3;
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 407 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NgwuEr55UQr2DbUCiQd:-NgwuEr55UQr2DbUCiQe:bw3rhmv) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b63451364d4ffb5152cbb7f3725f22bd4d952bb/crates/blockifier/src/execution/syscalls/hint_processor.rs#L407)):*
> ```XML
> 
>     // TODO(Mohammad, 20/10/2023): Refactor to use allocate_data_segment method.
>     fn allocate_tx_resource_bounds_segment(
> ```

Move under `pub`lic methods.



_Code quote:_
```XML
allocate_tx_resource_bounds_segment
```


<!-- Sent from Reviewable.io -->

2023-10-17 16:14 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 10 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 407 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NgwuEr55UQr2DbUCiQd:-NgyPUUGCkTQxDutgzl9:b-q8uqdq) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b63451364d4ffb5152cbb7f3725f22bd4d952bb/crates/blockifier/src/execution/syscalls/hint_processor.rs#L407)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Move under `pub`lic methods.
</blockquote></details>

Moved.
But why it should be public?


<!-- Sent from Reviewable.io -->

2023-10-17 17:00 UTC, dorimedini-starkware submitted a review, later dismissed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 10 unresolved discussions (waiting on @elintul and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2023-10-19 08:55 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 6 unresolved discussions (waiting on @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 475 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt50St-JDJwTpBQewM:-Nh67zs37b9tWgN9Imqd:b9pdp16) ([raw file](https://github.com/starkware-libs/blockifier/blob/628e5de210f800ac8cdf1fda4a77867354ceb3b8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L475)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Consider defining a `TransactionInfo` struct, in order not to repeat the order.
Perhaps it can have a c-tor from `BlockContext` and `AccountTransactionContext`.
</blockquote></details>

After our discussion, is it still needed?


<!-- Sent from Reviewable.io -->

2023-10-22 10:58 UTC, elintul requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 5 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 459 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngsz8c4BVvGRtaRAVWt:-NhM0yMhCLEq2A_UXcnK:b-1i3hgl) ([raw file](https://github.com/starkware-libs/blockifier/blob/b1221e3c07ef840580ce2ec4349522ed76ed9572/crates/blockifier/src/execution/syscalls/hint_processor.rs#L459)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not possible anymore?
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 475 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt50St-JDJwTpBQewM:-NhM13KR8CxhWFBja6b5:b-dz0xaa) ([raw file](https://github.com/starkware-libs/blockifier/blob/628e5de210f800ac8cdf1fda4a77867354ceb3b8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L475)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

After our discussion, is it still needed?
</blockquote></details>

Let's consider it after this PR. Can you build another `vec`tor in the `match` and in the end do `extend` (instead of `push, push, push)?
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 407 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NgwuEr55UQr2DbUCiQd:-NhM0ociBM36gjoc22Qo:bxfa01s) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b63451364d4ffb5152cbb7f3725f22bd4d952bb/crates/blockifier/src/execution/syscalls/hint_processor.rs#L407)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

Moved.
But why it should be public?
</blockquote></details>

I doesn't, I meant it should be located in the area of private methods (under the `pub`lic ones).
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 505 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NgwvJsv2T0dfuxb-EOZ:-NgwvJsv2T0dfuxb-EO_:b-bfjaa6) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b63451364d4ffb5152cbb7f3725f22bd4d952bb/crates/blockifier/src/execution/syscalls/hint_processor.rs#L505)):*
> ```XML
>                 // Handle the DeprecatedAccountTransactionContext.
>                 let (empty_array_ptr, _) =
>                     &self.allocate_data_segment(vm, Vec::<StarkFelt>::new())?;
> ```

I don't think we need to allocate anything here, we simply use `0` as the pointer value. Can you please make sure with Ilya?



_Code quote:_
```XML
                let (empty_array_ptr, _) =
                    &self.allocate_data_segment(vm, Vec::<StarkFelt>::new())?;
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 332 at r7](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NhLsXcCEaFZ8zA2oBCH:-NhLsXcD8QGYj7g35QuH:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/e6c964be9492e745c7f44538eaff503c5149f3ff/crates/blockifier/src/execution/syscalls/hint_processor.rs#L332)):*
> ```XML
>                 .collect::<Vec<MaybeRelocatable>>()
>             })
>             .collect();
> ```





_Suggestion:_
```XML
let flat_resource_bounds = context.resource_bounds.0.iter().flat_map(|(resource, resource_bounds)| {
    let resource_as_int = match resource {
        Resource::L1Gas => 0,
        Resource::L2Gas => 1,
    };

    vec![
        resource_as_int,
        resource_bounds.max_price_per_unit,
        resource_bounds.max_amount as u128,
    ]
    .into_iter()
    .map(|value| MaybeRelocatable::from(Felt252::from(value)))
}).collect();
```


<!-- Sent from Reviewable.io -->

2023-10-24 06:43 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 459 at r2](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngsz8c4BVvGRtaRAVWt:-NhVPR4HDbkfMFVZodgg:b-ljndb3) ([raw file](https://github.com/starkware-libs/blockifier/blob/b1221e3c07ef840580ce2ec4349522ed76ed9572/crates/blockifier/src/execution/syscalls/hint_processor.rs#L459)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Not possible anymore?
</blockquote></details>

I don't think.
Otherwise, I'll need to use an immutable reference to `self.context`, while later in the scope it creates a mutable reference to `self` itself.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 475 at r3](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ngt50St-JDJwTpBQewM:-NhVJENw7P2ZQLoaCxGt:b-q00eqz) ([raw file](https://github.com/starkware-libs/blockifier/blob/628e5de210f800ac8cdf1fda4a77867354ceb3b8/crates/blockifier/src/execution/syscalls/hint_processor.rs#L475)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Let's consider it after this PR. Can you build another `vec`tor in the `match` and in the end do `extend` (instead of `push, push, push)?
</blockquote></details>

I used `extend_from_slice` instead.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 505 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NgwvJsv2T0dfuxb-EOZ:-NhVKhbw5fhYMQ28YhLR:btw8c4i) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b63451364d4ffb5152cbb7f3725f22bd4d952bb/crates/blockifier/src/execution/syscalls/hint_processor.rs#L505)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

I don't think we need to allocate anything here, we simply use `0` as the pointer value. Can you please make sure with Ilya?
</blockquote></details>

I'm checking with Ilya.
It should be aligned with the OS code. 


<!-- Sent from Reviewable.io -->

2023-10-24 08:30 UTC, dorimedini-starkware approved these changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 4 unresolved discussions (waiting on @elintul)



<!-- Sent from Reviewable.io -->

2023-10-24 09:13 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 505 at r6](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NgwvJsv2T0dfuxb-EOZ:-NhVx9lzBD2stsWuDFbb:b-7ne1ra) ([raw file](https://github.com/starkware-libs/blockifier/blob/0b63451364d4ffb5152cbb7f3725f22bd4d952bb/crates/blockifier/src/execution/syscalls/hint_processor.rs#L505)):*
<details><summary><i>Previously, MohammadNassar1 (mohammad-starkware) wrote…</i></summary><blockquote>

I'm checking with Ilya.
It should be aligned with the OS code.
</blockquote></details>

Updated to zero value.


<!-- Sent from Reviewable.io -->

2023-10-24 09:22 UTC, dorimedini-starkware requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 515 at r9](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NhVzXFB-vh6jfktR__5:-NhVzXFB-vh6jfktR__6:b2ir41n) ([raw file](https://github.com/starkware-libs/blockifier/blob/12e017acd97e74d2e06cbce7638085c03e2888be/crates/blockifier/src/execution/syscalls/hint_processor.rs#L515)):*
> ```XML
>             AccountTransactionContext::Deprecated(_) => {
>                 tx_info.extend_from_slice(&[
>                     Felt252::from(0).into(), // Empty list of ResourceBound
> ```

there is a `zero` function on Felt252



_Suggestion:_
```XML
zero()
```


<!-- Sent from Reviewable.io -->

2023-10-24 10:13 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 5 unresolved discussions (waiting on @elintul and @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 514 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NhWA48v8U5ve3ZH7s5f:-NhWA48v8U5ve3ZH7s5g:bodab0e) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0b43654939556dd8e35c40694c1dd6496d9f7aa/crates/blockifier/src/execution/syscalls/hint_processor.rs#L514)):*
> ```XML
>             }
>             AccountTransactionContext::Deprecated(_) => {
>                 tx_info.extend_from_slice(&[
> ```

you could, in theory, go with something like `[0..9].iter().map(|_| Felt252::zero()).collect()`, but the `9` is a magic number... maybe better to be explicit.


<!-- Sent from Reviewable.io -->

2023-10-24 11:36 UTC, elintul requested changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 499 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NhWT0-I8uZSxZrYBTIY:-NhWT0-JBcVnmEWGrXt7:bfc2ua3) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0b43654939556dd8e35c40694c1dd6496d9f7aa/crates/blockifier/src/execution/syscalls/hint_processor.rs#L499)):*
> ```XML
>                 let (tx_account_deployment_data_start_ptr, tx_account_deployment_data_end_ptr) =
>                     &self
>                         .allocate_data_segment(vm, current_ctx.account_deployment_data.0.clone())?;
> ```

Why do we have to `clone` here?



_Code quote:_
```XML
current_ctx.account_deployment_data.0.clone()
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 515 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NhWT7Mz6bRLKlBqy_R-:-NhWT7Mz6bRLKlBqy_R0:b8g56g4) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0b43654939556dd8e35c40694c1dd6496d9f7aa/crates/blockifier/src/execution/syscalls/hint_processor.rs#L515)):*
> ```XML
>             AccountTransactionContext::Deprecated(_) => {
>                 tx_info.extend_from_slice(&[
>                     Felt252::zero().into(), // Empty list of ResourceBound
> ```

Why not create once?



_Code quote:_
```XML
Felt252::zero().into()
```


<!-- Sent from Reviewable.io -->

2023-10-24 11:36 UTC, elintul reviewed
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2023-10-24 12:15 UTC, dorimedini-starkware approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2023-10-24 12:17 UTC, elintul reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 4 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 487 at r11](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NhWbTbi6feBCq3uHfmA:-NhWbTbi6feBCq3uHfmB:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/768e4fd9422225b101418ea901af55d8fc09e776/crates/blockifier/src/execution/syscalls/hint_processor.rs#L487)):*
> ```XML
> 
>         match account_tx_context {
>             AccountTransactionContext::Current(current_ctx) => {
> ```





_Suggestion:_
```XML
context
```


<!-- Sent from Reviewable.io -->

2023-10-24 15:54 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 499 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NhWT0-I8uZSxZrYBTIY:-NhW_H0I78tQUu5GDL79:bw46kac) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0b43654939556dd8e35c40694c1dd6496d9f7aa/crates/blockifier/src/execution/syscalls/hint_processor.rs#L499)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why do we have to `clone` here?
</blockquote></details>

You're correct.
I shouldn't. I missed these two clones.
Now, I'm only retaining the clone on account\_context, which I believe we need to keep.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 514 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NhWA48v8U5ve3ZH7s5f:-NhW_sJ69Mk_CTD96YZy:bbjgxsr) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0b43654939556dd8e35c40694c1dd6496d9f7aa/crates/blockifier/src/execution/syscalls/hint_processor.rs#L514)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you could, in theory, go with something like `[0..9].iter().map(|_| Felt252::zero()).collect()`, but the `9` is a magic number... maybe better to be explicit.
</blockquote></details>

Yeah, but I wanted to add a comment for each one.
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 515 at r10](https://reviewable.io/reviews/starkware-libs/blockifier/984#-NhWT7Mz6bRLKlBqy_R-:-NhXO6qJ97WVounVX06M:b-vboqoz) ([raw file](https://github.com/starkware-libs/blockifier/blob/b0b43654939556dd8e35c40694c1dd6496d9f7aa/crates/blockifier/src/execution/syscalls/hint_processor.rs#L515)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Why not create once?
</blockquote></details>

Updated.
Note that I had to add clones.


<!-- Sent from Reviewable.io -->

2023-10-24 17:20 UTC, dorimedini-starkware submitted a review, later dismissed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul and @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2023-10-30 10:44 UTC, elintul requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 467 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ni-AT7W17fGVL1NnzXn:-Ni-AT7W17fGVL1NnzXo:b-z1j6yu) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad5fab84e3cf9555c4f1279deb73003140a56bc0/crates/blockifier/src/execution/syscalls/hint_processor.rs#L467)):*
> ```XML
>         let (tx_signature_start_ptr, tx_signature_end_ptr) =
>             &self.allocate_data_segment(vm, self.context.account_tx_context.signature().0)?;
>         let account_tx_context = self.context.account_tx_context.clone();
> ```

Can we avoid this `clone` as well?



_Code quote:_
```XML
let account_tx_context = self.context.account_tx_context.clone();
```
___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 522 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ni-AeZQ5jB5z4yLhqnh:-Ni-AeZQ5jB5z4yLhqni:undefined) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad5fab84e3cf9555c4f1279deb73003140a56bc0/crates/blockifier/src/execution/syscalls/hint_processor.rs#L522)):*
> ```XML
>                     zero_felt.clone(), // nonce_data_availability_mode
>                     zero_felt.clone(), // fee_data_availability_mode
>                     zero_felt.clone(), // Empty list of account_deployment_data
> ```





_Suggestion:_
```XML
                    zero_felt.clone(), // Empty array of resource bounds.
                    zero_felt.clone(),
                    zero_felt.clone(), // Tip.
                    zero_felt.clone(), // Empty array of paymaster data.
                    zero_felt.clone(),
                    zero_felt.clone(), // Nonce DA mode.
                    zero_felt.clone(), // Fee DA mode.
                    zero_felt.clone(), // Empty array of account deployment data.
```


<!-- Sent from Reviewable.io -->

2023-10-30 10:44 UTC, elintul reviewed
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: all files reviewed, 3 unresolved discussions (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2023-10-30 14:35 UTC, MohammadNassar1 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @elintul)

___
*[`crates/blockifier/src/execution/syscalls/hint_processor.rs` line 467 at r12](https://reviewable.io/reviews/starkware-libs/blockifier/984#-Ni-AT7W17fGVL1NnzXn:-Ni0-1LFEeNjha5XNF3c:b-cbch38) ([raw file](https://github.com/starkware-libs/blockifier/blob/ad5fab84e3cf9555c4f1279deb73003140a56bc0/crates/blockifier/src/execution/syscalls/hint_processor.rs#L467)):*
<details><summary><i>Previously, elintul (Elin) wrote…</i></summary><blockquote>

Can we avoid this `clone` as well?
</blockquote></details>

I don't think so.
I tried to use a mutable reference, and it failed on mutable borrow.


<!-- Sent from Reviewable.io -->

2023-10-30 18:36 UTC, dorimedini-starkware approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/blockifier/984)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MohammadNassar1)



<!-- Sent from Reviewable.io -->

2023-10-31 10:59 UTC, merged